### ISSUE TITLE
Updating the value of IgxDateRangePicker while its still open should reflect in the calendar

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#10003]
## Is your feature request related to a problem? Please describe.
Right now the IgxDateRangePickerComponent will not reflect any changes made to its value in the calendar. This can be inconvenient if we want to implement user scenarios which require the picker to remain open while the value is being updated.

## Describe the solution you'd like
If the calendar is open the picker should update it when the value is changed.

## Describe alternatives you've considered
n/a

## Additional context
n/a

**Comment by hanastasov** [comment]
Same goes for `IgxDatePicker`:

1. Open https://infragistics.com/angular-demos/scheduling/datepicker-sample-1
2. Open the calendar to select a date
3. Update the input value and press Enter

Logged with #9685

**Comment by jackofdiamond5** [comment]
@hanastasov I decided to create a separate issue for the range picker since we already have a scenario (https://github.com/IgniteUI/igniteui-angular-samples/issues/2750) in which we want to leave it open while also updating its value. We are going to give the rest of the pickers the same treatment in future PRs.
