### ISSUE TITLE
Text Highlight Directive: TypeError: can't access property "classList", el is undefined

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#10002]
## Description  

I use text highlight directive inside an igxFor virtualized list and I have a filter on it.
When I use the filter everything works fine, but when I clear the filter it crashes.

 * igniteui-angular version: 12.0.0
 * browser: Firefox

## Steps to reproduce  

I don't currently have isolated it.

## Result  

Exception: TypeError: can't access property "classList", el is undefined

## Attachments  
![image](https://user-images.githubusercontent.com/12942794/129373549-1fd638c3-603e-4f96-8bc7-075d044e5976.png)
![image](https://user-images.githubusercontent.com/12942794/129373640-7a682b82-2451-4fe8-8a79-756dd03f724a.png)
![image](https://user-images.githubusercontent.com/12942794/129373696-fbcf7849-7f73-40dc-b7f9-e9cfbce69058.png)
![image](https://user-images.githubusercontent.com/12942794/129373749-85138e97-ca20-41a6-82e2-050362506024.png)

**Comment by pmoleri** [comment]
I tried to isolate the issue, I couldn't get the exact same result but I got errors anyway.
Use this stackblitz: https://stackblitz.com/edit/github-bwxvr8?
- Open the stackblitz console
- Search for "light20" 
   --> you'll see some errors in the stackblitz console
- Press clear button in the search field
  --> some more errors

The highlight is inside a component that is rendered inside a virtualized igxFor.

![image](https://user-images.githubusercontent.com/12942794/129811380-8d07e35a-7990-41cd-b697-492d004310dd.png)

**Comment by DiyanDimitrov** [comment]
@pmoleri. The text highlight expects that you will track an active highlight, but in your case I guess that you won't have an active highlight. I will make a change to skip the active highlight if the index is -1.

**Comment by pmoleri** [comment]
>  I will make a change to skip the active highlight if the index is -1.

That's how I monkey patched it yersterday :)

```ts
function highlightBugFix() {
    // Fix bug https://github.com/IgniteUI/igniteui-angular/issues/10002
    const highlight = IgxTextHighlightDirective.prototype as any;
    if (highlight && highlight.activate) {
        const activateOriginal: (index: number) => void = highlight.activate;

        highlight.activate = function(index: number) {
            if (index === -1) {
                // When activating nothing remove the highlight element, otherwise activate fails
                this.deactivate();
                this.clearHighlight(false);
            }

            activateOriginal.call(this, index);
        };
    }
}
```

**Comment by pmoleri** [comment]
I don't know exactly how `IgxFor` directive works, but it seems to me that at some point the component instances are still alive, but the DOM elements are not there and that's when the highlight fails.
The highlight didn't fail with a regular `ngFor`.

**Comment by DiyanDimitrov** [comment]
I am also not sure why it works with regular `ngFor`, but this issue is definitely reproducible with a simple highlight if no active highlight is set.
