### ISSUE TITLE
Igx tree with dynamic content

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10016]
Hi guys.

I flag this as a feature request, but its more of a comment really, as I noticed the following in the documentation:
![image](https://user-images.githubusercontent.com/12936286/129850898-4c06d83a-cafe-44bd-b582-4fac502b2772.png)

I was just now exploring the new tree component for the first time, and was surprised and disappointing by this decision. We have been waiting for this component in order to convert some old jquery ignite trees to angular, and we don't really want to use tree grids in these scenarios. In my opinion it would have been far better if the tree also supported solutions like childDataKey and primary/foreign keys. Now we will be forced to either look for another tree component or just create nested nodes until we are certain that all nodes are displayed (which can be hard to judge sometimes).

**Comment by kdinev** [comment]
@Eralmidia As linked in the explanation, this limitation was not enforced by us, but is due to a limitation in the Angular framework. As soon as the Angular issue is fixed, we will be able to support this.

**Comment by Eralmidia** [comment]
@kdinev  Guess I didn't click the read more link 😛  But wow, that bug is from 2017. Doesn't seem like this will happen anytime soon then.
