### ISSUE TITLE
IgxInput does not update required and invalid styles when validators are dynamically removed/added

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#10010]
## Description  
When setting form validators dynamically - clearValidators/setValidators, inputs with the `IgxInput` directive do not reflect the change by removing/adding the asterisk required sign, nor by removing/adding the invalid style.

 * igniteui-angular version: 10.2.x, 11.1.x, 12.1.x
 * browser: any

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/igx-input-toggle-validators-update-state?file=src/app/input-group/reactive-forms/reactive-forms.component.ts)
2. Press "Toggle Validators.required for all form controls"
3. Observe the "Full Name" and "Email address" form controls.

## Result  
The `IgxSelect`, `IgxDropDown`, `IgxDatePicker` and `IgxTimePicker` correctly update the UI.
The "Full Name" and "Email address" inputs still appear invalid, despite no validator being applied.

## Expected result  
The "Full Name" and "Email" inputs to reflect the change, similar to the other editors.

**Comment by grosch** [comment]
@IvayloG I really hope this is a quick and simple fix. I'm now in the untenable situation of having to strip out this framework if this isn't a quick fix because all of my inputs change their required state dynamically.
