### ISSUE TITLE
How to Create the Nested drag and drop using Ignite UI Drag and Drop

### ISSUE THREAD

**Issue by dharmarajmr** [IgniteUI/igniteui-angular#10014]
I'm facing issue when I have decided to create the nested drag and drop. Those features are available in drag n drop ignite UI component.

This is the below sample that you provided in stackblitz 

> https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/interactions/kanban-sample?file=src%2Fapp%2Fdrag-drop%2Fkanban-sample%2Fkanban-sample.component.ts

but I have to drag the ToDo and Progress and Done article as well. What Should I do?, Thanks

**Comment by dharmarajmr** [comment]
Is there any update guys? My few modules depends on that functions. Kindly give me a solution for this. Thank you

**Comment by ChronosSF** [comment]
Hi @dharmarajmr , while the sample doesn't show drag and drop of the kanban areas , it contains all the important code that you could re-use to allow for that.  Have you tried to do it and faced issues that we can help you with?

The Drag & Drop topic - https://www.infragistics.com/products/ignite-ui-angular/angular/components/drag-drop has other great code samples as well that could help you start implementing your use case.
