### ISSUE TITLE
igx-input-group style not updating

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-angular#10029]
## Description  
Describe the issue.

 * igniteui-angular version:  12.1.0
 * browser: chromium

## Steps to reproduce  

create reactive form with disabled field
then set the field to enabled in a async callback

## Result  
What is the actual result after following the steps to reproduce?

the input style still looks disabled

## Expected result  
What is the expected result after following the steps to reproduce?

the input style should should reflect the state of the control

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

https://stackblitz.com/edit/github-nmwouz?file=src/app/input-group-sample-1/input-group-sample-1.component.ts

**Comment by PlamenaMiteva** [comment]
Hi, @ricardosaracino, this will be fixed in issue [#9997](https://github.com/IgniteUI/igniteui-angular/issues/9997l) and should be available next week in the patches for igniteui-angular.

**Comment by Lipata** [comment]
@ricardosaracino the fix will be available in our next patches.
