### ISSUE TITLE
On FireFox, moving a row to the first element temporary disappears.

### ISSUE THREAD

**Issue by dmthornton** [IgniteUI/igniteui-angular#10028]
## Description  
We are using the igx-grid to list out items and have 'Move Up' and 'Move Down' buttons. Users will use these buttons to sort the rows as they see fit. Ran into a small issue on FireFox, when the user selects an item a ways down on the list and click 'Move Up' until it's the first item. The item will disappear when it becomes the first item. If you scrolled the list down and back up, it will be shown. This issue does not show up on Chrome. I tried adding some detectChanges and that doesn't seem to help. 

https://stackblitz.com/edit/igxgrid-rowmove-wqma8w

 * igniteui-angular version: 11.1.10
 * browser: FireFox 91.0

## Steps to reproduce  

1. On FireFox go to: https://igxgrid-rowmove-wqma8w.stackblitz.io/ 
2. Select an item without scrolling
3.  Click the 'Move Up' until it's the first item
4. Notice it will not disappear
5. Scroll down some and select an item
6. Click the 'Move Up' until it's the first item
7. Notice when becomes the first item it will disappear
8. Scroll the grid down and back up
9. Item will appear
10. Repeat on Chrome, the issue will not show up.

## Result  
What is the actual result after following the steps to reproduce?
When item becomes the first element it temporary disappears in Firefox. Have to scroll down and up to make it appear.

## Expected result  
What is the expected result after following the steps to reproduce?
Item to be shown without the scrolling.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

https://user-images.githubusercontent.com/8482394/130078310-46008002-a540-4a67-8786-1ec1575672e4.MP4

**Comment by zdrawku** [comment]
@hanastasov lets check with latest 12.1.x

**Comment by Svetloslav15** [comment]
The bug is fixed on **v12** and **v13**.
There are only 2 changes that should be make to the sample in order to work:
### event.cell.rowIndex -> event.cell.row.index
```js 
onSelection(event: IGridCellEventArgs): void {
    // v11 
    //this._selectionClearAndSelect(event.cell.rowIndex);

    // v12 and v13
    this._selectionClearAndSelect(event.cell.row.index);
}
```

### (onSelection)="onSelection($event)" -> (selected)="onSelection($event)"
```html
<igx-grid
        #headerGrid
        [cellSelection]="'single'"
        [(data)]="headers"
        id="columnId"
        primaryKey="columnId"
        displayDensity="cosy"
        // v11
        // (onSelection)="onSelection($event)"
        // v12 and v13
        (selected)="onSelection($event)"
      >
        <igx-column field="headerText" header="Header"></igx-column>
</igx-grid>
```
