### ISSUE TITLE
It would be good if IRowSelectionEventArgs had bound data item even when the grid has a primary key setting.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#10050]
## Is your feature request related to a problem? Please describe.
When igx grid has a primary key setting, IRowSelectionEventArgs has the primary key value instead of the data item. We can identify the data item with the primary key, but it would be much more convenient if this event arg had the data item.

## Describe the solution you'd like
IRowSelectionEventArgs has the data item, too.

## Additional context
Here is the sample: 
[cas35132-app4.zip](https://github.com/IgniteUI/igniteui-angular/files/7037480/cas35132-app4.zip)

1. npm install and npm start the sample.
2. Open it in a browser.
3. Click the checkbox of the first row.
4. See the Console of the browser's developer tool.
-> Its bound data item is not in the IRowSelectionEventArgs.

![screenshot](https://user-images.githubusercontent.com/33947244/130578599-a98e005d-21fe-4e45-80f6-e24d6536879a.png)

**Comment by hanastasov** [comment]
If one wants to have the bound data item exposed, then another would benefit from exposing the row itself. Better not to burden the code with more calculations, when everyone can take the row/rowData from the current event arguments.
