### ISSUE TITLE
IgxLinearProgressBar: progress doesn't change when max property changes dynamically

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#10067]
## Description  
If you change `IgxLinearProgressBar.value` property then progress changes.
If you change `IgxLinearProgressBar.max` property then progress doesn't change.

 * igniteui-angular version: 12.1.0
 * browser: Chrome

## Steps to reproduce  
Change `IgxLinearProgressBar.max` property dynamically.

## Result  
Progress doesn't update.

## Expected result  
Progress should update.

## Attachments  
https://stackblitz.com/edit/github-gvbevv

**Comment by hanastasov** [comment]
@Timmeeeey, this seemed quite tricky to fix, without first refactoring the animations as per your other request - #10068. We are currently researching what is the best option to enable customizing the animations and will let you know.

**Comment by hanastasov** [comment]
Hi @Timmeeeey, the issue is resolved and you will be able to test the behavior coming Monday, when a patch version is scheduled to be released.
