### ISSUE TITLE
IgxLinearProgressBar: don't animate initial progress

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#10068]
## Is your feature request related to a problem? Please describe.
If I start a progress bar at 100% then it starts to animate from 0 to 100%.
This takes a few seconds and is confusing because it should start with 100% (or any other value > 0).

## Describe the solution you'd like
Is it possible to not animate the first value but any following changes?

**Comment by katherinedragieva** [comment]
Hello @Timmeeeey ,

We found a solution on application level: [Stackblitz](https://stackblitz.com/edit/github-y8sjiw-93n2je?file=src/app/linear-progressbar/linear-progressbar.component.ts).

Are you satisfied with the solution?

**Comment by Timmeeeey** [comment]
Unfortunately this solution doesn't work for me because the progress bars are created dynamically with ngFor after a http call.
But I found a different solution which seems to work:
I initially set `animate = false` and after the first http call I execute `setTimeout(() => animate = true)`.

**Comment by katherinedragieva** [comment]
Hello @Timmeeeey ,

If you have any questions do not hesitate to ask or contact us.

**Comment by Timmeeeey** [comment]
Is it possible to make the animation faster? Currently the update interval of the progress values is 2s but the animation takes often longer than that and this seems to cause problems.
My current solution is to disable animation and use this css to make the animation myself:
``` css
.igx-linear-bar__indicator {
  transition: width 0.5s;
}
```

**Comment by kdinev** [comment]
@simeonoff Could you chip-in on this?

**Comment by hanastasov** [comment]
> @simeonoff Could you chip-in on this?

@Aleksandyr is making a research on what we could expose here.

**Comment by hanastasov** [comment]
Hi @Timmeeeey, the issue is resolved and you will be able to test the behavior coming Monday, when a patch version is scheduled to be released. A new `animationDuration` input property is exposed, so that animation duration is controlled.
