### ISSUE TITLE
IgxCsvExporterService: Support multi-column headers export

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#10078]
## Is your feature request related to a problem? Please describe.
Grid multi-column headers cannot be exported to CSV.

## Describe the solution you'd like
I want to be able to export grid with multi-column headers to CSV.

**Comment by gedinakova** [comment]
@viktorkombov **The CSV file format** is known to be specified under [**RFC4180**](https://datatracker.ietf.org/doc/html/rfc4180). Although, it's very common and widely used, _there is no formal specification_ available. However, according to RFC4180, it may or may not contain a header line. The header line, when present, is supposed to have the same format as the data records, meaning it should contain _the same number of fields as all records do_. 
Having this said, note that in general, we should be able to export the multi-column headers, however, we will end up with header lines, possibly with different format or with empty fields, which I am not sure is desirable. What concerns me even more, is that this format is widely supported by different spreadsheet (and not only) applications, and although MS Excel does not seem to have a problem with the different formatted lines, other apps may not be so liberal. 
So, can you please provide some more information about this feature request? Is this a customer's question? If so, what exactly do they expect? Let's get all on the same page before we proceed with a decision how to handle this issue. 
Thanks in advance.

**Comment by viktorkombov** [comment]
@gedinakova This issue have been mentioned in [this ](https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/123485/exporting-multi-header-grid-as-csv)forum thread posted by a customer who is asking if the fact that multi-column headers couldn't be exported to a CSV file is a bug. Accordingly, after I have seen that with [this ](https://github.com/IgniteUI/igniteui-angular/pull/9673)pull request the issue of exporting a grid with multi-column headers with IgxExcelExporterService was resolved, I have thought that this could be achieved for the IgxCsvExporterService too.

**Comment by gedinakova** [comment]
@viktorkombov Well, this thread doesn't give us any details about the use case. Maybe we should bring the customer's attention to the concerns I mentioned above, so we can understand why he's trying to do this and if it is really necessary. In general, I don't think we should implement this.
