### ISSUE TITLE
Summary is not aligned with its respective column

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1008]
### Description  
Summary is not aligned with its respective column.
(The issue is reproduced both when enabling the summary in the markup and when enabling it in code.)

### Steps to reproduce  

Download and run the sample application.

### Result  
The Summary for the "Downloads" column is **not** aligned under its column.

### Expected result  
The Summary for the "Downloads" column is aligned under its column.

### Attachments  
[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1915322/igxgridSample.zip)

![image](https://user-images.githubusercontent.com/12784974/38810284-fecadaec-418e-11e8-93d3-95e6a52389a9.png)

**Comment by zdrawku** [comment]
This issue is not Summaries specific, if you remove the summaries the missalign issue will still appear.

**Comment by ChronosSF** [comment]
@zdrawku - the main issue is that the summaries for the first two columns are not rendered, so the first summary with content takes the space under the first column. The small misalignment between header and body that is unrelated with summaries is a different issue.
