### ISSUE TITLE
IgxGridBaseDirective throws console warnings even when the deprecated properties are not used

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/igniteui-angular#10083]
## Description  
There are some console warnings of the IgxGridBaseDirective deprecated properties that are thrown even when the deprecated properties are not used.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open the [grid paging sample ](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-paging-sample) and grid [export to excel sample](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/services/export-excel-sample-1)
2. See console warnings.

## Result  
Console warnings about IgxGridBaseDirective deprecated properties are thrown

## Expected result  
Console warnings should not be thrown when deprecated properties are not used

## Attachments  
![paginator-warning](https://user-images.githubusercontent.com/10612538/132306176-abf6eba7-1e43-4ef1-a31b-ecd238cc99b9.jpg)

![export-warning](https://user-images.githubusercontent.com/10612538/132308058-e996c630-30a2-4b27-9f77-e43f9fa0996d.jpg)

**Comment by Lipata** [comment]
There are some new ones with 12.2.0 - evenRowCSS and oddRowCSS:

![image](https://user-images.githubusercontent.com/2621802/135235041-f286807e-a1fb-4077-b4c3-85afc7029a50.png)

**Comment by hanastasov** [comment]
Paging props are used internally by the grid, so expected to see those warnings for now.
