### ISSUE TITLE
IgxGridStateDirective does not reflect state after Row Pinning event

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#10108]
## Description  
My app subscribes to `IgxGridComponent.rowPinning`; when a rowPinning event is fired, my code queries `IgxGridStateDirective.getState()` for the state, but the state does not include the newly pinned row. Why doesn't the state include the newly pinned row? Am I subscribing to the wrong row-pin observable? 

 * igniteui-angular version: 12.1.5
 * browser: Chrome 91.0.4472.114

## Attachments  
```
this.grid.rowPinning.subscribe(event => this.state.getState(true, ['rowPinning'])) // return value doesn't include the pinned row
```

**Comment by hanastasov** [comment]
The `rowPinning` event is emitted when trying to pin a row, so at this time the row is not yet pinned/unpinned. I'm marking this is a request to implement a `'-ed'` event, that will only be emitetd when a row has been succesfully pinned/unpinned.
