### ISSUE TITLE
Toolbar advanced filtering button is not visible when toolbar actions are added

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#10148]
## Description  
Toolbar actions hide advanced filtering button from the toolbar

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/github-czvphk?file=src%2Fapp%2Fgrid%2Fgrid-toolbar-sample%2Fgrid-toolbar-sample-4.component.html) sample.
2. Use the  toggle button below the grid to add/remove toolbar actions.
3. Observe toolbar advanced filtering button.

## Result  
Advanced filtering button is visible only when toolbar actions are removed.

## Expected result  
Advanced filtering button is always visible.

**Comment by hanastasov** [comment]
Possible related to #10075

**Comment by hanastasov** [comment]
Since the toolbar has a custom template, then the AdvancedFiltering should be available there:
```html
      <igx-grid-toolbar-actions *ngIf="show">
        <igx-grid-toolbar-exporter></igx-grid-toolbar-exporter>
        <igx-grid-toolbar-hiding></igx-grid-toolbar-hiding>
        <igx-grid-toolbar-pinning></igx-grid-toolbar-pinning>
        <igx-grid-toolbar-advanced-filtering></igx-grid-toolbar-advanced-filtering>
      </igx-grid-toolbar-actions>
```
