### ISSUE TITLE
Filtering dialog is cut off when there is only one filtering result

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular#1014]
### Description  
When the grid has no width and height explicitly set and the user filters the grid, so that it returns only one filtering result, the filtering dialog is cut off

### Steps to reproduce  

1. Run Grid Performance sample and remove the width and height options (you may decrease the rows and columns as well)
2. Open the filtering dialog and filter by some value that would return a single record

### Result  
The grid height shrinks and the filtering dialog is cut off

### Expected result  
The filtering dialog is fully visible

**Comment by kdinev** [comment]
Related #940

**Comment by tachojelev** [comment]
After discussing this with @simeonoff , we believe that using min-height in combination with the current implementation for the grid and the filtering would probably cause some additional issues.
An alternative future approach suggested by @simeonoff would be to wait for the [igxDropDown feature](https://github.com/IgniteUI/igniteui-angular/issues/984), which might be a more applicable approach for the grid filter UI in this case.
