### ISSUE TITLE
Getting error while fetching data from private npm feed, the message is below

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#10155]
## Description  
error An unexpected error occurred: "https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-11.0.9.tgz: Request failed \"400 Bad Request\"".

 * igniteui-angular version: 11.0.9
 * browser: 

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by amitmoondra** [comment]
@hanastasov can you help here, its urgent, this started happening today suddenly on all our environments, can release stuff to production as well.

**Comment by yuhongcheng2003** [comment]
I also been having this problem this afternoon. Please investigate.

**Comment by hanastasov** [comment]
@yuhongcheng2003 this was resolved already on your end, right?

**Comment by yuhongcheng2003** [comment]
@hanastasov Yes, thanks. Do you know what was causing this and if there were anything implemented to prevent it in future?

**Comment by hanastasov** [comment]
It's just infrastructure issues with heavy loads at certain times.
