### ISSUE TITLE
Cannot Reorder Columns with Templated header/cell

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#10151]
## Description  
I have movable columns with a templated header and cell, but I can't reorder them. If I comment out the templates, I can reorder them again. I found this snippet in the documentation:
```
If a column header is templated and the corresponding column is movable (or groupable), then the templated elements need to have the draggable attribute set to false! This allows to attach handlers for any event emitted by the element, otherwise the event is consumed by the igxDrag directive. 
```
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-moving

I followed this example:
```
<ng-template igxHeader>
    <igx-icon [attr.draggable]="false" (click)="onClick()"></igx-icon>
</ng-template>
```

but now I can't drag the column at all. How do I enable reordering for my columns with templated header & cell? Thanks

igniteui-angular version: 12.1.5
browser: Chrome 91.0.4472.114

**Comment by hanastasov** [comment]
Duplicate of #8129 #9583 #8896

There is a workaround suggested in those tickets, taht is to use the columns template setter to assign templates:
```html
<igx-grid>
    <igx-column field="column2"  [movable]="true" [headerTemplate]="headerTmpl">
    </igx-column>
</igx-grid>

<ng-template let-val #headerTmpl>
    <div>
        <igx-icon [attr.draggable]="false" (click)="onClick()"></igx-icon>
    </div>
</ng-template>
```

Please let me know if this resolves the issue on your end.

**Comment by hanastasov** [comment]
@SkylerLutz it will be interesting to tell us if same issue reproduces on your end in the area of pinned columns, or only in the area of unpinned columns.

**Comment by SkylerLutz** [comment]
Thanks @hanastasov! Yes that workaround seems to do the trick. Yes, the issue is only in the unpinned area -- no issues in the pinned area. Yes, I am using ngFor in the template.
