### ISSUE TITLE
TypeError is thrown when an excel style filter menu is opened if rowData is used in the column formatter.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#10175]
## Description  
TypeError is thrown when an excel style filter menu is opened if rowData is used in the column formatter.

 * igniteui-angular version:12.1.4,  12.2.0-alpha.2
 * browser: Chrome

## Steps to reproduce  

1. Run the sample.
https://stackblitz.com/edit/github-mbtefa-w3v4nx?file=src%2Fapp%2Fgrid%2Fgrid-resizing-sample%2Fgrid-resizing-sample.component.ts
2. Click the filter icon on "Company Name" column header.

## Result  
TypeError is thrown.

## Expected result  
Filter menu should open without errors.

**Comment by gedinakova** [comment]
@mkamiishi Hello Mihoko, in order for the excel-style filtering to work with formatted values, we need to set the grid's `filterStrategy` property to a specific strategy named `FormattedValuesFilteringStrategy`. Esentially, it tells the filtering that it should not use the original data values, but the formatted ones instead. I updated your [sample application](https://stackblitz.com/edit/github-mbtefa-1jkjrj?file=src%2Fapp%2Fgrid%2Fgrid-resizing-sample%2Fgrid-resizing-sample.component.ts) to resolve the error. More information on this approach can be found in the [Filtering topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#formatted-values-filtering-strategy). 
Let me know if you need further assistance.

**Comment by mkamiishi** [comment]
Hi Galina,
I have verified that the excel-style filtering works as expected with filterStrategy=FormattedValuesFilteringStrategy.
Thank you for the sample.

**Comment by mkamiishi** [comment]
Hi Galina,
I've found that the filtering actually is not working.
Can you please try applying a filter on the "Company Name" column in the modified sample?
