### ISSUE TITLE
Programmatically show Dialog?

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#10177]
## Question  
Hi -- can someone please provide an example on how to programmatically show an Ignite confirmation Dialog Window? Say, from an Angular Guard. The examples in the documentation only show how to spin them up from components, not guards. Thanks!

**Comment by hanastasov** [comment]
The Ignite UI for Angular Dialog window can be opened in two ways:
- the [`open`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDialogComponent.html#open) API method.
- declaratively with the [`isOpen`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDialogComponent.html#isOpen) property

**Comment by kdinev** [comment]
@SkylerLutz Guards are meant to return whether a certain route can or cannot be activated by a user. The guard logic is not part of your components` logic, so you cannot initiate a UI change from inside the guard logic. However, you can initiate a UI action from the component initiating the routing change, or from the one that is being routed to, if the guard returns that it can be accessed by the user.
