### ISSUE TITLE
getCellByColumn returns undefined on a cell click in lazy loaded grid

### ISSUE THREAD

**Issue by palnar-dev** [IgniteUI/igniteui-angular#10172]
## Description  
In a cell click of a particular row, we are showing the details of that row data in a pop up.
But when we scroll downwards and click on a particular cell , the getCellByColumn method returns as undefined.

 * igniteui-angular version: 12.1.6
 * browser: Chrome

## Steps to reproduce  

1. npm install
2. Select any cell in the ShipName column - we can see the selected rowdata in the console log of the browser.(lazy_attachment01).
3. Scrolldown some records and select any cell like we did in step 2 - getting error in the console 'cell' value is undefined (lazy_attachment02)

## Result  
Without scroll on a cell click, getCellByColumn returns the value.
But after Scroll downwards click on the 'ShipName' column , getCellByColumn() return as undefined.

## Expected result  
What is the expected result after following the steps to reproduce?
getCellByColumn() should return the value.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

Sample application attached here [lazy-loading-grid-04.zip](https://github.com/IgniteUI/igniteui-angular/files/7204102/lazy-loading-grid-04.zip)

![lazy_attachment01](https://user-images.githubusercontent.com/91135100/134193835-45780dff-9953-458c-aa97-b42960514813.PNG)
![lazy_attachment02](https://user-images.githubusercontent.com/91135100/134193838-7a0b6d39-b125-4669-aa18-7c391b3a7dbd.PNG)

**Comment by hanastasov** [comment]
@palnar-dev Thanks for reaching out to us! I looked at the sample and confirm this is a bug. The remote data scenario needs additional handling. This will be planned and fixed. Meanwhile, you can use the `$event.cell` or the following workaround:

```typescript
IgxGridCell {grid: IgxGridComponent, _rowIndex: 10, _columnField: 'ShipName'}

  onCellClick($event){
    const relativeRowIndex = this.grid.dataRowList.last.index - $event.cell._rowIndex;
    cell = this.grid.getCellByColumn(
      relativeRowIndex,
      $event.cell._columnField
      );
  }
``
The `cell` object created this way will correctly return all other values you need, but will work with a relative index, so use the index carefully.

**Comment by hanastasov** [comment]
Please test:
- flat grid with master-detail view (detail view is counted as a row)
- tree-grid with summaries
