### ISSUE TITLE
Alpha version?

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10174]
## Question  
I wanted to try out the new add row changes you have done. First of all, I'm a bit confused as to which version has this functionality. In the pull request (https://github.com/IgniteUI/igniteui-angular/pull/10071) this seems to indicate that this is for 12.1, but the information about the changes is listed in the 12.2.0 alpha.

Also, how exactly do I use an alpha version? I tried installing both 12.2.0 and 12.2.0-alpha.2, but npm can't seem to find them.
![image](https://user-images.githubusercontent.com/12936286/134291650-02eca115-8293-484b-9290-c965874079eb.png)
![image](https://user-images.githubusercontent.com/12936286/134291681-6190c9b5-5c85-403e-833e-5def0089eb50.png)

 * igniteui-angular version: 12.2.0
 * browser:

**Comment by ChronosSF** [comment]
It should be released in 12.1.6 as well. There was a small issue when merging the changelog together.
