### ISSUE TITLE
Alternative way of applying formatter

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10180]
## Is your feature request related to a problem? Please describe.
In our system, there are other parts of the system which need access to the column data of a given grid. Because of this, we define the column data for the grid in a separate class like this:
![image](https://user-images.githubusercontent.com/12936286/134503805-94e42c1a-f72d-401f-a1ff-04baf34c2267.png)

Then in the grid template, we simply loop over all the IGridColumnDataElement in the array:
![image](https://user-images.githubusercontent.com/12936286/134503896-0a2382b2-be64-430f-a266-a012e40c9992.png)

Finally, we can create igxCell and igxCellEditor templates:
![image](https://user-images.githubusercontent.com/12936286/134503982-61ad3761-6b84-46f1-a402-bd485a8b01e5.png)

All of this works just fine. But, now we are looking into changing the advanced filter for the excel style filter, and we get issues like this:
![image](https://user-images.githubusercontent.com/12936286/134504237-3d52f603-d79b-49ef-ab8d-a910deac1c31.png)

This seems to be because the grid does not specify a formatter, but the formatter is a property on the column, which should point to a method. And this become quite challenging.

First of all, since we are adding the columns by ngFor, the formatter can't really point to one single function. If anything it would have to point to a function witch could return one of multiple functions, but the formatter is declared like this
![image](https://user-images.githubusercontent.com/12936286/134504644-d4c1b3f8-30df-482f-aefc-27208fa0ef43.png)

and dosen't include the field which is actually requesting a formatter, so that doesn't seem to be an option. I know I probably could do some ternary logic to choose the function perhaps, but that would get really messy in a grid with a lot of columns.

Also a function as input requires us to retreive that function from the ts file, not the template. This is cumbersome in examples like this for instance:
![image](https://user-images.githubusercontent.com/12936286/134504904-29ed1ff3-2bd9-47f8-b300-b57d8037c2be.png)

In this instance, we have a igxCell which relies on both a pipe and an observable in order to map the actual value (stored in the data of the grid) into the textual value (read from the Organizations array in this case). Doing this in a formatter would add clutter to the ts file. I would need to import and inject the pipe, subscribe/unsubscribe to the observable etc.

## Describe the solution you'd like
Ideally I would like the excel filter list to simply use the igxCell template, or at least some more "template-friendly" way than supplying a formatter function. At the very minimum the formatter method should include the field so the ts file could return the correct formatter function (although this is not really desirable, as described above).

**Comment by Eralmidia** [comment]
Btw, if this is something you won't consider addressing, it would nice with a heads up, as we will have to revert our grids to the old filtering type.

**Comment by Eralmidia** [comment]
Just noticed that this is also causing issues for us regarding export. Since we can't apply a formater we template the cells to get them to display the info we want, and since there is no formatter, the excel exporter exports the raw data, which is not what we want. Hope you can take a look at this soon.

**Comment by Eralmidia** [comment]
@kdinev Any hope for this one in the next milestone?

**Comment by kdinev** [comment]
@Eralmidia Hello! I apologize for the inactivity on this issue from our side. I looked at the request and I believe this is already partially supported by using a `FormattedValuesFilteringStrategy`. There's a sample here:

**Comment by Eralmidia** [comment]
@kdinev Thank you. This however still applies a formatter on the column? Than main issue is that we use a ngFor loop on the igx-column in order to render columns, so I don't see an easy way to determine what formatter to apply, because the formatter does not have a parameter for the field.

**Comment by kdinev** [comment]
@Eralmidia You can apply formatters using the `onColumnInit` event, which fires for each column. This way you can apply different formatters to the different columns. We can actually extend the callback to include the field name in the formatter as a parameter, if this will make it more usable.

**Comment by Eralmidia** [comment]
@kdinev Ah this looks promising, thank you! One followup question though: Is it possible for a formatter to be dependent on other data than the row data? For instance I have a grid with an Organizations column. The data of this column is the id of the organization. In the column template however we of course map this to the name of the organization for user readability. But I find this a bit challenging when trying to create a formatter for this. I have the following formatter:

![image](https://user-images.githubusercontent.com/12936286/155685540-5dbfae75-3ce9-4998-b1fc-1c232bd5d6b6.png)

This uses a pipe to map the ID property into the Name property. But in order to do this I need to feed it the list of all available organizations. This works fine in the column template, because there we simply feed it an observable for the list of organizations. But trying to retrieve the list in the formatter won't work, because "this" will not refer to the same component/service when run by the grid. 

The only way I can think of is to create another hidden column along with the organization ID column to hold the Name property. It should work, as the formatter can get the rowData as the second argument, but it doesn't sound ideal to me.

**Comment by Eralmidia** [comment]
Or rather I guess I only need a new property in the data source? I assume you get all properties on the data source object even if there is no column assigned to it? Maybe that is the best option then?

**Comment by kdinev** [comment]
@Eralmidia You do get the entire data row, but even inside the method you're able to use context which is to your component and not to the grid. Have you tried that this doesn't work because the `this` context is different and also have you tried to pass the method as a proxy with the specific context being the component?

**Comment by Eralmidia** [comment]
Console logging this gives the IgxColumnComponent as context yes. What do you mean by "pass as a proxy"? Are you taling about something like this? https://www.javascripttutorial.net/es6/javascript-proxy/ I'm not really familiar with this, how would that look?

**Comment by kdinev** [comment]
Yup, that's what I'm talking about!

**Comment by Eralmidia** [comment]
Alright, got this working by using column init. Thanks. Don't think we need to keep this request open as there was a way to achieve this already.
