### ISSUE TITLE
Start the advanced excel filter with one condition

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10184]
## Is your feature request related to a problem? Please describe.
This is sort of nit-picky, but I still feel it should be corrected:

For some reason, all the advanced filters starts of with two conditions, like so:
![image](https://user-images.githubusercontent.com/12936286/134630067-df675e83-6201-49e8-8519-db4f49de1c66.png)

I would have found it a lot cleaner if it would just start with one condition, like this:
![image](https://user-images.githubusercontent.com/12936286/134630128-511e7466-9372-4557-9172-308f6024430e.png)

Is this a bug, or by design, and if its by design, what is the reasoning for this? It just adds clutter to the initial view, and I'm guessing in many situations one would use only one filtering option.

**Comment by Eralmidia** [comment]
Btw, just noticed that this is the setup in Excel as well, is that perhaps where this came from?
![image](https://user-images.githubusercontent.com/12936286/134630644-3b6f6eae-bcf1-46a5-9fc0-bbb22fcd695f.png)

But this is still a bit different, because in Excel you seems to be limited to just two options. There is not add/remove of conditions.

**Comment by StefanIvanov** [comment]
Hi @Eralmidia our design rationale behind grid features is to follow the example of Excel indeed as many of our customers are very used to what they get there in terms of functionality, visual structure, and even shortcuts. This is also the case with the Advanced Filtering dialog, but whenever we can do something more, on top of what Excel does, we extend things following their established patterns. Therefore with the Ignite Grids, you may define advanced filters across multiple columns and define as complex conditions and criteria as you need. However, if you look at our demo [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/advanced-filtering) you will notice that the dialog is empty by default. On the other hand, if some filters are configured e.g. via the API, the dialog will display them when opened. I hope this provides more clarity on the design rationale behind the Advanced Filter.
