### ISSUE TITLE
Template grid excel filter footer

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10183]
## Is your feature request related to a problem? Please describe.
The full list of components to style in the excel filter seems to be this:
![image](https://user-images.githubusercontent.com/12936286/134629096-1907e1d1-092c-44d4-aeab-c16e4c7cf0dc.png)
It includes header, but not footer, so we are unable to place/style the buttons how we usually do.

## Describe the solution you'd like
igx-excel-style-footer component to be added to this list.

**Comment by gedinakova** [comment]
@Eralmidia Hello, I see how this may be a little confusing, but the footer is actually part of the `igx-excel-style-search` component. It has the `igx-excel-filter__menu-footer` class applied and you should be able to style it as needed. In our [Styling demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#demo-2), for instance, we are styling the `Apply` button.
Is there something you are not able to achieve? Please, let us know so we can review it and provide further assistance.

**Comment by Eralmidia** [comment]
Ah, yes, I guess a better title for this request would actually be template footer, not style footer. We generally use icons in front of the text for all buttons. We don't use uppercase letters for buttons, which results in our buttons now looking like this:
![image](https://user-images.githubusercontent.com/12936286/134632388-3a18d660-9478-4682-95b5-19b75ab96b20.png)
while a set of buttons for us usualy would look something like this:
![image](https://user-images.githubusercontent.com/12936286/134632481-1b238d42-a9fb-4038-932b-58d53b7efd51.png)

I guess by applying some global flex and text transform CSS I should be able to fix the latter two. The icons might be a bit more tricky, but guess we can live with that. In any case, having control over these buttons would be nice, like we have in for instance the igx dialog.
