### ISSUE TITLE
igxGrid takes the width of its parent, rather than the total width of its columns.

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1019]
### Description  
Grid takes the width of its parent, rather than the total width of its columns.

Put a grid on the page:
```html
<div style="width:500px;">
  <igx-grid #grid1 [data]="data" [autoGenerate]="false" [height]="'400px'"  [columnWidth]="'200px'">
    <igx-column field="index" header="index" dataType="number"></igx-column>
    <igx-column field="value" header="value" dataType="string"></igx-column>
    <igx-column field="value2" header="value2" dataType="number"></igx-column>
    <igx-column field="value3" header="value3" dataType="number"></igx-column>
  </igx-grid>
</div>
```

### Result  
Grid width equals its parent's width

### Expected result  
Grid width to equal its columns total width.

### Attachments  
[igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/1918623/igx-grid-app.zip)

**Comment by MayaKirova** [comment]
@hanastasov As part of the new Grid width/height defaults if no width is set a default value of “100%” will be applied, hence the grid will be spanning the container it's placed in. 

The related issue with more details on the defaults is here: 
https://github.com/IgniteUI/igniteui-angular/issues/1054
