### ISSUE TITLE
Cell selection is not working with remote virtualization

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#1020]
### Description  
Cell selection is not working with remote virtualization

### Steps to reproduce  

1. Open the grid remote virtualization sample from demos
2. Click a cell
3. Navigate to the last visible cell from the column
4. Try to navigate to next cell, that is still not visible

### Result  
The new data is not not loaded or if it is loaded the cell from the column is not selected

### Expected result  
The new loaded cell should be selected

**Comment by Lipata** [comment]
In order to have proper cell and row selection 'primaryKey' should be defined. Still there is a problem that the newly loaded cell is not selected

**Comment by bazal4o** [comment]
Already fixed
