### ISSUE TITLE
Rounded theme borders are cutoff

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#10206]
* igniteui-angular version: 12.2.0-alpha.3

## Steps to reproduce  

Rounded theme borders are cutoff – Use a fluent light theme with roundness. This happens only to the input part of the Excel-style filtering dialog

## Result  

![1](https://user-images.githubusercontent.com/14248932/135218998-4bd379ed-b1b8-4a50-9659-a1ba899f5a69.png)
![2](https://user-images.githubusercontent.com/14248932/135219209-d40b06a0-e674-4f4f-a312-0066dcb74d2a.png)

**Comment by zdrawku** [comment]
@hanastasov, I am closing this bug as it is not reproducible anymore with the latest versions of the library:

![image](https://user-images.githubusercontent.com/11193764/161941942-f787d45c-2707-4f97-9b77-cc316608c6ec.png)
