### ISSUE TITLE
Error thrown when changing theme

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#10207]
* igniteui-angular version:  12.2.0-alpha.3

## Steps to reproduce  

Create a project with the app builder and change the theme from light to dark. You can use this app as a reference: https://github.com/jberes/Webinar-Demo
Starting from scratch w/ a Dark Theme

## Result  
![3](https://user-images.githubusercontent.com/14248932/135219363-025e7ef0-fc66-4182-8d49-2cfd0704e7d3.png)

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by radomirchev** [comment]
@hanastasov is the issue still reproducible?

**Comment by zdrawku** [comment]
The demo is not available anymore. I am closing this one after testing this with the latest version of 13.1.0 and:

![image](https://user-images.githubusercontent.com/11193764/161525536-52cfcb6c-2547-4d40-bcdc-ac5d41a1e2ac.png)
