### ISSUE TITLE
Grid alignment issues 

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#10208]
* igniteui-angular version: 12.2.0-alpha.3

## Steps to reproduce  

Grid alignment issues - add paging and group by. Do the following actions – gif below.

https://www.screencast.com/t/bH2NBAmkk 

Make sure to watch the entire video.

## Result  
![4](https://user-images.githubusercontent.com/14248932/135219642-721d0453-8478-4e2b-8607-ccd8b9cb4b87.png)

**Comment by zdrawku** [comment]
We can test if this issue is still relevant

**Comment by hanastasov** [comment]
> We can test if this issue is still relevant

ME and @dobromirts  could not reproduce it now, but this bug regularly "comes on the surface" after active working in this sample. I mean swe cant still get the proper and complete steps/conditions to reproduce it. Let's keep it open for now.

**Comment by zdrawku** [comment]
I am going to leave it open and remove it from the current sprint iteration
