### ISSUE TITLE
Igx Grid Sort Icon Change

### ISSUE THREAD

**Issue by sajeesh-pankajakshan** [IgniteUI/igniteui-angular#10217]
## Igx Grid Sort Icon Change 
 We are using 'igniteui-angular' version '12.1.5'. Need to change the 'igx-grid' column sort icons with custom icons. Three state of sorting icons needed to be changed(Ascending, Descending and Normal). 
In the existing grid sorting icons are shown as in the below image.

<img width="350" alt="Current Icons" src="https://user-images.githubusercontent.com/91657070/135460963-a328e8c5-53dc-4599-b00c-0a65c7b82eab.png">

We need to change the icons in the image above to below.

<img width="350" alt="Changing Icons" src="https://user-images.githubusercontent.com/91657070/135461518-218fb3c3-b074-4e97-94a4-c24d2e4a4d03.png">

## Describe the solution you'd like
We need grid property or option for changing sorting icons.

**Comment by sajeesh-pankajakshan** [comment]
With out any performance issue is there any possibility to change the sorting icon through style, theming or any script ?

**Comment by viktorkombov** [comment]
> With out any performance issue is there any possibility to change the sorting icon through style, theming or any script ?

We will prioritize this task and include it in our next sprint for review and development. Until the feature is implemented, what I can suggest is using the following temporary workaround that I prepared for you:

In this workaround, each time when the grid is rendered or the sorting expressions are changed, the native element of the sorting icon is selected and its text content is changed depending on what sort order is set for the current column:
```
HTML
<igx-grid igxPreventDocumentScroll #grid1 [data]="data" (sortingDone)="sortingHandler($event)">
       ...
</igx-grid>
```
```
TYPESCRIPT
public ngAfterViewInit(): void {
    Array.from(
      this.grid.nativeElement.getElementsByClassName('sort-icon')
    ).forEach((elem: Element) => {
      elem.textContent = 'unfold_more';
    });

    if (this.grid.sortingExpressions.length > 0) {
      this.grid.sortingExpressions.map(column => this.sortingHandler(column));
    }  
}

public sortingHandler(sortingExpression: ISortingExpression): void {
    const sortIcon = this.grid
      .getColumnByName(sortingExpression.fieldName)
      .headerCell.nativeElement.getElementsByClassName('sort-icon')[0];

    if (sortingExpression.dir === 0) {
      sortIcon.textContent = 'unfold_more';
    } else if (sortingExpression.dir === 1) {
      sortIcon.textContent = 'expand_less';
    } else {
      sortIcon.textContent = 'expand_more';
    }
}
```
Please keep in mind that with this workaround you are limited to use only the icons that are provided by the[ material icon set by Google](https://fonts.google.com/icons).

I have created a small [sample ](https://stackblitz.com/edit/github-vszsvh?file=src%2Fapp%2Fgrid%2Fgrid-sorting-indicators%2Fgrid-sorting-indicators.component.ts)demonstrating how the above approach is working. Please test it on your side and let me know whether you find it helpful.
