### ISSUE TITLE
Blank space after the last grid row displayed

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1022]
### Description  
After scrolling grid rows do not fullfill all the available space and there is blank space after the last row:

### Steps to reproduce  
1) Put a grid on the page:
```html
<igx-grid #grid1 [data]="data" [height]="'450px'" [width]="'900px'" [autoGenerate]='false'>
...
</igx-grid>
```
2) Scroll down the grid by dragging the scroll bar.

### Result  
What is the actual result after following the steps to reproduce?
![capture](https://user-images.githubusercontent.com/14248932/38856924-898a1232-4230-11e8-8d6d-8b5d1e366366.PNG)

### Expected result  
Rows to fullfill all the available space.

### Attachments  
[igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/1918741/igx-grid-app.zip)

**Comment by mpavlinov** [comment]
@hanastasov this is duplicate to #1016 .
