### ISSUE TITLE
IgxCombo: selection is not displayed when data is set after value

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#10229]
## Description
If you set an inital selection for the combo before the data is set (because of API delay) then the selection is not displayed.

 * igniteui-angular version: 12.1.7

## Attachments  
https://stackblitz.com/edit/github-cx6ksj-bymkqa

**Comment by PlamenaMiteva** [comment]
hi @Timmeeeey,
this is an expected behavior since the combo does not have the data at the time you are setting the selection. Everything seems fine if the selected items are set after all the data have been fetched
`public ngOnInit() {
    setTimeout(() => {
      this.lData = localData;
      this.selection = [localData[0].field];
    });
  }`

**Comment by Timmeeeey** [comment]
I have a form and I want to set some default values for the combo. But because the data is fetched from a server the data is set after my inital selection for the combo.
In this case my selection is present in my form data but it is not displayed in the browser.
Isn't there a way you could reevaluate the selection after data is changed?

**Comment by Timmeeeey** [comment]
I don't need to use `dataPreLoad` because I load all items at once and not in chunks.
As a workaround I just set the selection again after I set data:
`this.selection = [...this.selection]`
This way the selection is displayed correctly.
