### ISSUE TITLE
Row separators are visible within the vertical scrollbar when only the last row is not in view

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1025]
### Description  
Row separators are visible within the vertical scrollbar when only the last row is not in view.

_For example, in a grid with 9 records:_
The issue is **not** reproduced when the grid has 400px height.
The issue is reproduced when the grid has 450px height.
Refer to the attached sample for details.

The issue is reproduced in Chrome.
The issue is **not** reproduced in Firefox, IE and Edge.

### Steps to reproduce  

Download and run the attached sample application.

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?

### Attachments  
![image](https://user-images.githubusercontent.com/12784974/38858397-5c2f8a48-4234-11e8-8e16-3a32612c5c85.png)

[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1918862/igxgridSample.zip)

**Comment by simeonoff** [comment]
This should already be fixed with #1033. @tachojelev can you test?

**Comment by tachojelev** [comment]
I tested the issue and it is indeed fixed.
