### ISSUE TITLE
When igxGrid has its height set and only partial space is available for the last row, there is blank space instead of the row

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1026]
### Description  
When igxGrid has its height set and only partial space is available for the last row, there is blanks space instead of row.

The issue is reproduced on Chrome, Firefox, IE and Edge.
The issue might be related to #1025 

### Steps to reproduce  

1. Download and run the attached sample application.
2. Scroll to the bottom of the grid.

### Result  
Record is **not** rendered (only blank space).

### Expected result  
Record is rendered.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/38858807-4fd5b820-4235-11e8-9819-cb1a7e2bf94d.png)
[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1918887/igxgridSample.zip)

**Comment by hanastasov** [comment]
Issue does not reproduce anymore, it is fixed with other enhancements of the grid and the igxForDirective:
![capture](https://user-images.githubusercontent.com/14248932/39425172-e186aed0-4c82-11e8-923d-aa9996ff9cf0.PNG)
