### ISSUE TITLE
Date picker month

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10293]
## Question  
After upgrading to igx 12, there seems to be quite a few changes to the date picker. We format our dates in a speficic format using a formatter like so:
![image](https://user-images.githubusercontent.com/12936286/137135454-32aacd5e-dbc8-4b41-881f-608379aa4e14.png)
This still seems to be working fine. However, when I set focus to the input field, the date is changed to a numeric value. 
![image](https://user-images.githubusercontent.com/12936286/137135932-9c8f497a-28c5-439c-a86b-5f4b8200907d.png)

I can see there is an inputFormat input, but what should I set this to in order to keep text based months?

![image](https://user-images.githubusercontent.com/12936286/137135800-48a4204b-5ae3-4d4c-acbc-e5c9b04ca485.png)

 * igniteui-angular version: 12

**Comment by jackofdiamond5** [comment]
Hi @Eralmidia, the `IgxDatePickerComponent` supports custom `inputFormat` and `displayFormat`. The former is intended to be used only while editing and it is restricted to showing numeric dates. The latter is to be used when the component is not focused (and no custom formatting is applied) and it supports all formats outlined in Angular's [DatePipe](https://angular.io/api/common/DatePipe#custom-format-options).

**Comment by Eralmidia** [comment]
That's really unfortunate. My product manager will almost certainly dislike this change. 

It's not possible to use just the "drop down part" of the date picker and implement your own input instead either?
