### ISSUE TITLE
Dialog does not prevent "tabbing through" underneath dialog

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#10300]
## Description  
Hi - I invoked `IgxDialogComponent.open()` to bring up a dialog but I'm still able to "tab through" elements on the page underneath the dialog modal. How can I disable tabbing (focus events?) until the dialog is dealt with? Thanks

"tabbing through" meaning, using the tab key to focus on elements on the page one element at a time

igniteui-angular version: 12.1.5
browser: Chrome 91.0.4472.114

**Comment by PlamenaMiteva** [comment]
hi @SkylerLutz,

the issue with the Tab key focus not being trapped inside dialog has already been resolved and will be available with the IgniteUI for Angular 13.0.0 release.

**Comment by SkylerLutz** [comment]
Fantastic, thank you. When will 13 be released? 

Skyler Lutz
***@***.***

**Comment by PlamenaMiteva** [comment]
hi @SkylerLutz,

we are still working on the IgniteUI for Angular 13.0.0 official release, but you can test the functionality with [13.0.0-alpha.7](https://github.com/IgniteUI/igniteui-angular/releases/tag/13.0.0-alpha.7)
