### ISSUE TITLE
Why CTRL+C not working in igx-grid?

### ISSUE THREAD

**Issue by akopian-artur-25** [IgniteUI/igniteui-angular#10302]
## Question  
Hi. Why CTRL+C not working in igx-grid?
How I can setup grid for allow to copy value from cell to clipboard via CTRL+C?
Preferably using standard text selection.

 * igniteui-angular version: 11.0.3
 * browser: Chrome

**Comment by ChronosSF** [comment]
Hey,

Please, check this topic and sample: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/clipboard-interactions
