### ISSUE TITLE
There is no indication when a cell with no value is in edit mode

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1031]
### Description  
There is no indication when a cell with no value (or an empty string value for example) is in edit mode.

**NOTES:**
If the igxGrid loses focus after entering edit mode of a cell, there is an underscore indication that the cell is in edit mode.

### Steps to reproduce  

1. Open the "Grid" demo sample.
2. Delete the content of the "Name" cell of the first record and click on some other cell.
3. Double click the "Name" cell of the first record again to enter edit mode.

**NOTES:**
The issue is reproduced in Chrome and Firefox.
The issue is **not** reproduced in IE and Edge (they have a cursor indication that the cell is in edit mode).

### Result  
There is **no** indication that the cell is in edit mode.

### Expected result  
There is indication that the cell is in edit mode.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/38865780-81f282f4-4247-11e8-86d1-36eb7101107e.png)

**Comment by zdrawku** [comment]
This is because of a missing style, @simeonoff can comment further on this.

**Comment by zdrawku** [comment]
After the PR is merged and the changes are present, editing of the cell value will look like this

![image](https://user-images.githubusercontent.com/11193764/39914673-6112ed4c-550e-11e8-91d4-aa9228e0552c.png)
