### ISSUE TITLE
Slider does not show correct value with ngModel

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#10327]
## Description  
I have a slider like this:
```
<igx-slider
    [(ngModel)]="range"
    [lowerBound]="150"
    [upperBound]="450"
    [minValue]="0"
    [maxValue]="500"
    [type]="'range'"
    [showTicks]="true"
    [primaryTickLabels]="true"
    [primaryTicks]="6"
  >
  </igx-slider>
```
and `range` set like this
```
  public range: IRangeSliderValue = {
    lower: 200,
    upper: 300
  };
```

 * igniteui-angular version: 12.2.2
 * browser: all

## Result  
When start application both upper and lower value become 100
![image](https://user-images.githubusercontent.com/5990334/138075635-85aab622-07bb-4efa-8289-59b8f523baee.png)

## Expected result  
Lower value should be 200 and upper value should be 300

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
Related 
https://github.com/IgniteUI/igniteui-docfx/pull/3197
https://github.com/IgniteUI/igniteui-angular-samples/pull/2995
