### ISSUE TITLE
Grid Template Control gets duplicated/reused.

### ISSUE THREAD

**Issue by Szanik** [IgniteUI/igniteui-angular#10323]
## Question  

I am currently working on a datagrid table which should have some controls inside some cells.
For example there is a column UseOffset? and inside it we render a ng-template with an checkbox.

The Tempalte looks like this and is also set in the columnInit-Method

```
<ng-template #useOffsetColumnTemplate igxCellEditor let-cell="cell" let-value>
     <igx-checkbox [value]="value" 
            (change)="handleCheckboxChange($event, cell.rowData.m_iID)" >
     </igx-checkbox>
</ng-template>
```

In the handleCheckboxChange-Method is use the igx-grid method to update the data.
The workflow works but the contorls get duplicated.

If I check the first checkbox, and the list is large enough, then for example the 9th checkbox gets also checked.
The 9th wasn't visible in the first place and i need to scroll down  to it.

Also the 9th row doesn't have the same data behind it and the data isn't true. so the checkbox should be unchecked.

The primary key for the grid is also been set.

What am i missing? Is there a keyword missing like "key" in react?

 * igniteui-angular version: 12.0.5
 * browser: Edge v94.0.992.50

**Comment by Szanik** [comment]
Hello, 

thanks for your help.

So as I understand it, it seems to be a bug or at least a way that is not supported.
[Here](https://stackblitz.com/edit/github-cc7scy-akcakh?file=src/app/grid/grid-editing-sample/grid-editing-sample.component.html) is an example what we tried to do.
Just click the first checkbox and scrolldown and you will see another checkbox clicked.

For now we can use your approach, which works, and use your other tipps (editValue)

Thank you

**Comment by teodosiah** [comment]
Hello,

I am glad that you find my suggestion helpful.

I have been looking at the provided sample and since you are re-templating the igxCell template i.e. the template when the cell is not in edit mode, I could suggest binding the checkbox checked property to the cell.value and updating it in the change event handler.

I have modified the previously attached sample and it could be found [here](https://stackblitz.com/edit/github-cc7scy-vgax2a?file=src/app/grid/grid-editing-sample/grid-editing-sample.component.html).

If you require any further assistance on the matter, please let me know.

**Comment by Szanik** [comment]
Thanks teodosiah, with your last example I could implement the behaviour which we initially targeted.
It even works in 12.0.5.

I initially stated that there was also an issue with inputs but I could resolve it, so I think there is no issue in ignite-angular.

To complete this question [here ](https://stackblitz.com/edit/github-cc7scy-cqijle?file=src/app/grid/grid-editing-sample/grid-editing-sample.component.html) is the last sample, which I extended so it also works with inputs.
Editable  is also set to false.

I would like to write a conclusion, but it's really hard to break it down in words in the end.
Maybe:  One-way-binding is the way. Which I think is the approach in the last two samples. But maybe it's to oversimplified.

Thanks for the help 👍
