### ISSUE TITLE
Error: 'igx-grid-toolbar-title' is not a known element

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#10330]
## Description  
Error in /turbo_modules/@angular/compiler@9.1.3/bundles/compiler.umd.js (2845:21)
Template parse errors:
'igx-grid-toolbar-title' is not a known element:
1. If 'igx-grid-toolbar-title' is an Angular component, then verify that it is part of this module.
2. If 'igx-grid-toolbar-title' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
>
<igx-grid-toolbar>
[ERROR ->]<igx-grid-toolbar-title>Grid Toolbar</igx-grid-toolbar-title>
</igx-grid-toolbar>

"): ng:///AppModule/GridToolbarSample1Component.html@10:6
 * igniteui-angular version: 9.1.28
 * browser: chrome

## Steps to reproduce  

https://stackblitz.com/edit/github-of6jue

## Result  
What is the actual result after following the steps to reproduce?

Error

## Expected result  
What is the expected result after following the steps to reproduce?

No Error

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
@mddifilippo89 The toolbar as element was introduced in `v11.0.0`. Before that version toolbar is configured by setting the following inputs on the grid component:

```html
<igx-grid
    [showToolbar]="true"
    [toolbarTitle]="'Grid Toolbar'"
  >
```
