### ISSUE TITLE
Exporting Excel file from a Grid with pinned headers messed up the order of the data columns

### ISSUE THREAD

**Issue by wannadream** [IgniteUI/igniteui-angular#10359]
### Description  
Exporting Excel file from a Grid with pinned headers messed up the order of the data columns.

 * igniteui-angular version: 12.0.2
 * browser: Chrome 95

### Steps to reproduce  

1. Create a grid and set several pinned columns.
2. Create a button for exporting the grid to Excel file

### Result  
Web:
![image](https://user-images.githubusercontent.com/6989212/138806535-17033278-006a-4590-be98-70970c9b7e36.png)

Excel:
![image](https://user-images.githubusercontent.com/6989212/138806614-66f75782-7ba1-4757-8b5c-468c8971e5e0.png)

### Expected result  
Data should respect the settings of pinned headers rather than the order of properties of the JSON data objects.

### Attachments  
I will try to create a example in Stackblitz or somewhere.

**Comment by gedinakova** [comment]
@wannadream This issue was fixed in version 12.0.11 (#https://github.com/IgniteUI/igniteui-angular/issues/9872). Please, let us know if you experience the faulty behavior after upgrading? Thanks in advance!

**Comment by kdinev** [comment]
@Lipata @jackofdiamond5 Why does the bot keep setting the `status: in-review` after it's being removed?

**Comment by wannadream** [comment]
Resolved in 12.2.
