### ISSUE TITLE
Style of filtering icon for a header cell is not updated when (clear)filtering through the API

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1035]
### Description  
Style of filtering icon for a header cell is not updated when filtering through the API or when clear the filtering through the API.

**NOTES:**
The filtering icon gets updated when manually clicking the filtering icon.
For more details, refer to the gif file.

### Steps to reproduce  

1. Download and run the attached sample application.
2. Click the "Filter grid" button to filter the grid.
   - issue 1
3. Click the filtering icon to trigger a manual refresh of the icon.
4. Click the "Clear Filter grid" button to clear the filtering of the grid.
   - issue 2

### Result  
- issue 1: The filtering icon is **not** updated and is grey.
- issue 2: The filtering icon is **not** updated and is pink.

### Expected result  
- issue 1: The filtering icon is updated and is pink.
- issue 2: The filtering icon is updated and is grey.

### Attachments  
![filter](https://user-images.githubusercontent.com/12784974/38874467-ce28284a-4260-11e8-9722-5bafe81a23b3.gif)
[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1920085/igxgridSample.zip)

**Comment by zdrawku** [comment]
Duplicate #1153
