### ISSUE TITLE
IgxGrid don't generate row id after data has been updated (IgxGrid infinite scroll).

### ISSUE THREAD

**Issue by PhuQuy** [IgniteUI/igniteui-angular#10371]
## Description  
After the data changed, the event for cellClick is not contain row/rowid

 * igniteui-angular version: 12.2.2
 * browser: chrome

## Steps to reproduce  

1. Step 1
create an igx-grid with custom infinite scroll
2. Step 2
Add an event for cellClick with console.log(event.cell)
3. Step 3
Scroll the table to page 2

## Result  
What is the actual result after following the steps to reproduce?
After init, the console log the cell with row
After scroll to page 2, console log the cell without the row

## Expected result  
What is the expected result after following the steps to reproduce?
After scroll to page 2, console log the cell should has the row as IgxGridRow

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
Please check my url: https://github-jmyttw.stackblitz.io/

**Comment by 3phase** [comment]
@PhuQuy,

Thanks for noting! I tested your scenario and it looks like a bug in that particular version (I noticed that igniteu-angular@12.1.6 is used in the Stackblitz sample you provided). 
However, the issue does not seem to replicate in the later versions of the product, so my suggestion is that you update your igniteui-angular version to either the latest supported 12.x version, which is 12.3 at that time, or make a major version update to 13.0.
