### ISSUE TITLE
Ability to disable Done or Cancel button in hierarchicalgrid row-editing

### ISSUE THREAD

**Issue by amrit-moomie** [IgniteUI/igniteui-angular#10370]
## Question  
During row-editing I want to disable the Done and Cancel button Banner that appears. I want to completely hide the banner with text and buttons. Is there a way I can disable it?

![image](https://user-images.githubusercontent.com/6138925/138989183-9b45b6e4-d287-46ee-90fa-802865078100.png)

 * igniteui-angular version: any
 * browser: any

**Comment by viktorkombov** [comment]
Customizing the buttons and the text of the row editing overlay is possible using the igxRowEditActionsDirective and the igxRowEditTextDirective. [Here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-editing#customizing-row-editing-overlay), you can find examples how they can be used. However, at this point we do not provide an out of the box option for removing the row editing banner itself. What I can suggest is hiding it with the help of SCSS:
```
:host {
    ::ng-deep {
        .igx-banner__border-top, .igx-banner__border-bottom {
            display: none;
        }
    }
}
```
I created a small sample, illustrating my suggestion, which you can find [here](https://stackblitz.com/edit/github-jv21hq?file=src%2Fapp%2Fgrid%2Fgrid-row-editing-sample%2Fgrid-row-editing-sample.component.scss). Please test it on your side and let me know whether you find it helpful.
