### ISSUE TITLE
igx-excel-filter missing valid ARIA parents role

### ISSUE THREAD

**Issue by GibletJr** [IgniteUI/igniteui-angular#10391]
## Description
According to the w3 aria specification, any element with a role set to menuitem should contain a parent set to the following roles: menu, menubar, group

Currently, there is no parent role set for the igx-excel-filter <div> element.

igniteui-angular version: 12.1.x
browser: any

## Steps to reproduce  

1. Install the Accessibility Insights extension for chrome
2. Create an example igx-grid control setting the **filterMode** attribute to _excelStyleFilter_
3. Click on the column filter icon to open the filter options window.
4. Run the FastPass check from the notification Launch Pad

## Result  
![image](https://user-images.githubusercontent.com/56270402/139319318-c41393f3-08dd-479c-8a00-357ef2c3efbe.png)

## Expected result  
igx-excel-filter component should be compliant to w3 aria spec

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by igdmdimitrov** [comment]
To be tested with: [Accessibility Insights extension for chrome](https://accessibilityinsights.io/en/downloads/)
