### ISSUE TITLE
igx-grid-thead: aria-activedescendant attribute not allowed for an element's role

### ISSUE THREAD

**Issue by GibletJr** [IgniteUI/igniteui-angular#10392]
## Description  
According to the w3 aria specification, the aria-activedescendant attribute is only relevant on elements with role of composite widget, combobox, textbox, group, or application whose id is referenced as the attribute.

Currently, the generated HTML uses the unsupported role of "rowgroup"

element.
igniteui-angular version: 12.1.x
browser: any

## Steps to reproduce  

1. Install the Accessibility Insights extension for chrome
2. Create an example igx-grid control with a header
3. Run the FastPass check from the notification Launch Pad

## Result  
![image](https://user-images.githubusercontent.com/56270402/139321459-de1c53be-9e75-4368-91b2-86e28be9be7d.png)

## Expected result  
igx-grid and all child components should be compliant to w3 aria spec

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by GibletJr** [comment]
I see that #10432 is marked for 13.0.x and 12.2.x has been removed.  I would request that the bug also be fixed in 12.x so it doesn't require a migration to Angular 13 (which was just released earlier this month).

**Comment by hanastasov** [comment]
> @hanastasov. #10432 is marked for 13.0.x and 12.2.x has been removed. Please also fix this issue in 12.x so it doesn't have a dependency on migrating to Angular 13 (which was just released earlier this month).

Will add it!

**Comment by hanastasov** [comment]
The fix is there in 12.2.x as well:
https://github.com/IgniteUI/igniteui-angular/commit/9b9e065e4de8ef8edeee24c4958709ef3c75b701#diff-9c0c58bc637085bbffe631932f47f1e939f2a618cc071e4805d12fc967c25efb
