### ISSUE TITLE
Update calendar theme to match material

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#10400]
## Is your feature request related to a problem? Please describe.
Currently the calendar theme and schema result in a calendar with outdated look and feel in Material if we compare it to the [Material Datepicker Specs](https://material.io/components/date-pickers#usage) and our implementation of the styling of the web components. We should update the calendar UI to match the updated look and feel in Ignite UI for Angular.

Items to be updated:

-  [ ] **Navigation Flow** - (Year -> Month -> Date) / (Month -> Date)
-  [ ] **Range Selection Preview**
-  [ ] **Weekday format should update the month view** (i.e. weekday headers)

**Comment by ChronosSF** [comment]
@radomirchev , I think it's high time this is scheduled for a sprint so that we have design parity between WC and Angular

**Comment by IvayloG** [comment]
This issue should be reopened and fixed and is related to inconsistencies between AB Generated NG vs WebComponents vs Blazor  apps

**Comment by radomirchev** [comment]
@IvayloG and @simeonoff is the issue still valid?

**Comment by simeonoff** [comment]
> @IvayloG and @simeonoff is the issue still valid?

Very much so!
