### ISSUE TITLE
Handle a cell value change when a dropdown is edited

### ISSUE THREAD

**Issue by amrit-moomie** [IgniteUI/igniteui-angular#10413]
## Question  
https://github-facgfm-ehyhzk.stackblitz.io

In the above example, during cell Editing, I want to be able to get a `cellEditDone` or any other event when the user changes the dropdown value. Currently, it happens when I edit the dropdown and click outside the cell.

My requirement is to run a custom validation as soon as a user edits the dropdown.

 * igniteui-angular version: any
 * browser: any

**Comment by hanastasov** [comment]
You are using a custom cell editor template, benefiting from the IgxSelect. You can use the `[selectionCHanging](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxSelectComponent.html#selectionChanging)` event of the select itself:

```html
    <ng-template igxCellEditor let-cell="cell" let-value>
      <igx-select
        **(selectionChanging)="handleCellEditDone($event)"**
        class="cell-select"
        [(ngModel)]="cell.editValue"
        [igxFocus]="true"
      >
    </ng-template>
```
