### ISSUE TITLE
Spec files are not excluded upon typedoc generation

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#10417]
## Description  
Looking at the typedocOptions, we should exclude the .spec.ts files on api docs generation. Currently that is not the case and a lot of errors are returned:

Working branch: `rkaraivanov/ivy-partial-compile-dist`

 * igniteui-angular version: 13.0.0
 * browser: any

## Steps to reproduce  

1. Check out into the branch `rkaraivanov/ivy-partial-compile-dist`
2. npm i
3. ` npm run build:typedoc:en:staging`

## Result  
![image](https://user-images.githubusercontent.com/11193764/140065913-2d5b6b59-7735-4aa3-9e28-972443a99d13.png)

**This is the reason not to have staging environment with the API docs with the latest Angular 13 alfa version**

**Comment by Aleksandyr** [comment]
The problem does not come from TypeDoc.
It seems that the branch has some build errors which typedoc identifies when building the project internally and ends the export process for the documentation.

You can check the overlay.ts file where the errors are and fix them.

**Comment by hanastasov** [comment]
Exclude rule mans that those files will not be used to generate DOCS output. Budiling the docs still need to run the project build.
