### ISSUE TITLE
Not being able to read tooltip's content in Narrator

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#10419]
## Description  
Tooltip value is not readable by the narrator.

 * igniteui-angular version: 13.0
 * browser: Chrome 95
 * os: Windows 11 Beta something (Narrator is a system application and it might matter)

## Steps to reproduce  

1. Create a new Angular application, install `igniteui-angular` package and import the Tooltip module.
2. Create a new component, open its template file and paste the following code:
```
    <div style="width: 100px; height: 100px; border: 1px solid #ff0000;" tabindex="1"
        class="cursorHover" [igxTooltipTarget]="tp" [attr.aria-describedby]="'tooltip'">
    </div>

    <div id="tooltip" class="cellTooltip" #tp="tooltip" igxTooltip>
        Title
    </div>
```
3. Run the application. Wait for the browser to open;
4. Open narrator and enable it. Focus back to the browser and click the Tab key in order to focus the div with the red border. If the accessibility feature worked, it should have read "Title" aloud, although the tooltip is not visible.

## Result  
Narrator doesn't read the content of the tooltip.

## Expected result  
Narrator should read it.

## Further notes
If you use the default `title` attribute, it is being read correctly. 
Also, if you provide the tooltip origin with `[attr.aria-label]` attribute, it reads the value of the attribute ([ref](https://www.deque.com/blog/text-links-practices-screen-readers/)).

**Comment by kdinev** [comment]
@3phase It's up to the developer to provide the appropriate `title` or `aria-label` attributes on the tooltip target. The tooltip may or may not contain text-content, which means the dev needs to provide appropriate text. It's probably a good idea to add this to the documentation of the tooltip component.
