### ISSUE TITLE
Selecting text in IgxGrid cells in Firefox is not working as expected

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#10433]
## Description  
Selecting text in some IgxGrid cell is currently not possible in Firefox.
After an investigation I have determined that the text selection was applied properly in igniteui-angular version 12.0.4 and from version 12.0.5 it is working only in Chrome.

 * browser: Firefox

## Steps to reproduce  

1. Open the provided demo in [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid) topic.
2. Try to select some text.

## Result  
The text is not selected.

![text-select](https://user-images.githubusercontent.com/49126110/140752806-47ce1de4-733e-4385-8d84-461d37950dae.gif)

## Expected result  
The text to be selected as in Chrome.

**Comment by Volen99** [comment]
I am reproducing this issue in stackblitz as well as in [this ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing)topic. But when I try to reproduce it locally (master branch) the issue does not reproduce.

Maybe some other PR has fixed it?

**Comment by hanastasov** [comment]
> I am reproducing this issue in stackblitz as well as in [this ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing)topic. But when I try to reproduce it locally (master branch) the issue does not reproduce.
> 
> Maybe some other PR has fixed it?

@katherinedragieva  did a fix that was affecting Firefox browser. If Katrin's fix is also resolving the current issue (and this one too - https://github.com/IgniteUI/igniteui-angular/issues/11042), please update the statuses accordingly.

**Comment by Volen99** [comment]
Already fixed by [this ](https://github.com/IgniteUI/igniteui-angular/pull/11402)PR
