### ISSUE TITLE
Add row results in error

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#10438]
## Description  
Add row programmatically results in error 
eg.
Error: Cannot read properties of undefined (reading 'beginAddRowByIndex') or beginAddRow

 * igniteui-angular version: 12.2.9
 * browser: chrome

## Steps to reproduce  

1. Run sample
https://stackblitz.com/edit/github-trveio
2. Click Add row button

## Result  
Error: Cannot read properties of undefined (reading 'beginAddRowByIndex')

## Expected result  
Row is added at the top, index 0

Note, it should be documented how to set cell values using this method.

**Comment by ChronosSF** [comment]
Hey @mddifilippo89 ,

Your `ViewChild` selector wasn't matching the id in the template and grid1 ended up being undefined. Try it like this: `@ViewChild('gridRowEdit', { read: IgxGridComponent, static: true })`

**Comment by mddifilippo89** [comment]
Thanks!
