### ISSUE TITLE
Exception is thrown when trying to use get_rec_index_by_id method of IgxTreeGridAPIService

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#10468]
## Description  
ERROR TypeError: Cannot read properties of undefined (reading 'ID').

 * igniteui-angular version: 12.2.x
 * browser: any

## Steps to reproduce  

1. Open the following sample - [here](https://stackblitz.com/edit/github-9o6hyg?file=src%2Fapp%2Ftree-grid-paging-sample%2Ftree-grid-paging-sample.component.ts).
2. Click on the "GET INDEX" button and observe the console.

In the console should be logged the result returned by the get_rec_index_by_id event.

## Result  
The following exception is thrown: "ERROR TypeError: Cannot read properties of undefined (reading 'ID')".

## Expected result  
The method should return the index of the record in the data view.

**Comment by hanastasov** [comment]
This is not a bug. It uses a private service, which is not designed to be used this way. The proper way to get a row and its index via the public API is:

```typescript
  public getIndex(id: any): void {
    const row = this.treeGrid.getRowByKey(id);
    console.log(row.index);
  }
```
