### ISSUE TITLE
Igx grid group by and casing

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10488]
## Description  
There seems to be an issue with the grouping not handling upper/lower case

 * igniteui-angular version:  13.0 alpha
 * browser: Chrome

## Steps to reproduce  

1. Load https://stackblitz.com/edit/github-gpktzg?file=src%2Fapp%2Fdata%2FinvoiceData.ts 
2. Apply grouping to the column

## Result  
The data is grouped into 4 groups (germany 2x and Germany 2x). The pair of groups also seems to be connected. If you expand one of the germany groups, the other germany group will also expand.

## Expected result  
The data should be grouped into 2 groups

**Comment by ChronosSF** [comment]
Hey @Eralmidia ,

This is duplicate of #10236 . Seems we missed to match the defaults of sorting and grouping when sorting was changed. We plan to fix this in the next couple of patches.

In the meantime you can customize how grouping works to make it case-sensitive using the guidance here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/groupby#angular-grid-custom-group-by

**Comment by Eralmidia** [comment]
@ChronosSF Thank you. As long as it's planned a fix soon I think we're just live with the issue until the fix to avoid having to add custom grouping to all our grids. I'll close down this one since it's a duplicate then.
