### ISSUE TITLE
igx-tabs background color for active tab changed

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#10485]
## Description  
The background color of the active tab in the `igx-tabs` changed in 13.0 from 12.2.

 * igniteui-angular version: 13.0.0-alpha.7
 * browser: all

## Steps to reproduce  

1. Create an angular view with an `igx-tabs` inside. Theme:
```scss
$primary: white !default;
$secondary: #FF0A3A !default;
$background: #192053;
$banner-background: #2C3D93;
$background-gradient: linear-gradient(to right, $background, #04081D);
$background-gradient-lighter: linear-gradient(135deg, #2f3978 0%, #10193f 100%);
$progress-success: #13FF21;

$app-palette: igx-palette($primary, $secondary);

@include igx-dark-theme(
  $palette: $app-palette
);

/* Tabs */
$tabs-theme: igx-tabs-theme($item-background: $background, $indicator-color: $secondary);
@include igx-css-vars($tabs-theme);
/* END Tabs */
```

## Result  
![image](https://user-images.githubusercontent.com/1472513/141311217-5ca0e725-f1df-4684-a792-ed71ea25308b.png)

## Expected result  
![image](https://user-images.githubusercontent.com/1472513/141311253-b2bb324a-6823-452c-a9ee-450319b50df9.png)

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
Fixed this by adding the following to my tabs theme:

```scss
$item-hover-background: rgba(0, 0, 0, 0.11),
$item-active-background: rgba(0, 0, 0, 0.11),
```

The `$schema: $dark-schema` also didn't do the trick.

**Comment by simeonoff** [comment]
This is strange as I can't reproduce it with the correct schema and palette combo.

**Comment by kdinev** [comment]
The transparency has definitely changed between alpha 7 and the first RC:

![image](https://user-images.githubusercontent.com/1472513/143878516-0bad4f5e-bdf0-4fac-9312-58fe80828cd3.png)

I wanted to have an even more transparent effect, so I've applied my own custom color for hover and active as I have shown in my previous reply so the result is as follows:

![image](https://user-images.githubusercontent.com/1472513/143878808-ca91d6c3-09d4-42ae-bec5-ba5d355a5797.png)

I'm closing the issue, because I believe it's resolved.
