### ISSUE TITLE
Advanced filtering dialog is not working correctly for a row island

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#10532]
## Description  
Advanced filtering dialog is not working correctly for a row island.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the Hierarchical Grid Advanced Filtering sample on staging.
2. Create a filter on the root grid.
3. Expand a record and open the advanced filtering dialog for a row island.

## Result  
The same dialog as the root grid appears.

## Expected result  
Row island specific dialog should appear.

**Comment by DiyanDimitrov** [comment]
@hanastasov This seems to be caused by the toolbar, it doesn't resolve the child grids correctly. The issue is reproducible with column hiding and pinning too.

**Comment by ddincheva** [comment]
This regression is caused by PR #10043
