### ISSUE TITLE
InvalidPipeArgument: '1/1/1970 is not a number' for pipe 'DecimalPipe'

### ISSUE THREAD

**Issue by Volen99** [IgniteUI/igniteui-angular#10557]
## Steps to reproduce  
1. Open IgniteUI Samples
2. Go to Grid Formatting sample
3. Open DevTools and observe

## Result  
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/41373491/142421771-e6e52f18-6cf4-49fb-b4f2-58b1c1cbd336.png)

**Comment by hanastasov** [comment]
Not a bug - since the coumn OrderID is of type 'number', and the summaries of the column return 'date', the value is date string, but is being piped as 'number', this error is returned. THis is why `sumamryFormatter` is exposed, so you can do:
```html
    <igx-column field="OrderID" width="200px" [dataType]="'number'" [filterable]="true" [hasSummary]="true" [summaryFormatter]="dateSummaryFormat" [summaries]="earliest" [sortable]="true">
    </igx-column>
```

and treat the value as date or date string:

```typescript
    public dateSummaryFormat(summary: IgxSummaryResult, summaryOperand: IgxSummaryOperand): string {
        const result = summary.summaryResult;
        if(summaryOperand instanceof IgxDateSummaryOperand && summary.key !== 'count'
            && result !== null && result !== undefined) {
            const pipe = new DatePipe('en-US');
            return pipe.transform(result,'MMM YYYY');
        }
        return result;
    }
```
