### ISSUE TITLE
When igx-datePicker is used as a editor template, it is inside the igx-grid.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1057]
### Description  
What I want to do is edit date cell with igx-datePicker.

When I set  igx-datePicker as a editor template, it is inside the igx-grid.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-issue(I recommend to export this repo and run it locally because icons are not loaded correctly on StackBlitz.)
2. Double click a date cell to enter edit mode.
3. Click a `igx-datePicker`.

### Result  
- `igx-datePicker` is inside the igx-grid's scroll container.
- `igx-datePicker`'s backdrop is also inside the igx-grid's scroll container and behind the pinned column.
![image](https://user-images.githubusercontent.com/15909409/38964286-f77adb88-43b0-11e8-9347-47f119387ff5.png)

### Expected result  
`igx-datePicker` and its back drop should overlay the whole page.

**Comment by sstoyanovIG** [comment]
After I spoke with @simeonoff , it turns out that we should make a refactoring of the Date and Time pickers' templates, which should be discussed first, so we will postpone the fix for now.

**Comment by tkiryu** [comment]
@sstoyanovIG thank you for your info. I understand.

**Comment by zdrawku** [comment]
@ddincheva, we need to sync with @simeonoff and @SlavUI what would be that refactoring and include this in the upcoming sprints.
