### ISSUE TITLE
igx-splitter: Splitter pane collapse malfunctioning after resizing

### ISSUE THREAD

**Issue by NunoMCGoncalves** [IgniteUI/igniteui-angular#10580]
## Description  
Describe the issue.

 * igniteui-angular version: 12.1.8
 * browser: Google Chrome Version 95.0.4638.69

## Steps to reproduce  

1. Resize the panes using the splitter bar.
2. Press the "arrow" in the splitter bar to collapse the right side pane.

## Result  
What is the actual result after following the steps to reproduce?
The right side pane disappears as expected, but the splitter bar doesn't change position and the left side pane isn't resized.

## Expected result  
What is the expected result after following the steps to reproduce?
The splitter bar should be displaced to the screen's right border and the left side pane should be resized to occupy the full screen.

## Attachments  
https://stackblitz.com/edit/github-pl19yy-12cqs2?file=src/app/splitter-horizontal-sample/splitter-horizontal-sample.component.ts

**Comment by mddragnev** [comment]
Hello @NunoMCGoncalves,
Could you please let me know what are you trying to accomplish in that sample? What is your scenario? More specific I am talking  about a method in your code:
```
public paneCollapsedChange(event: any) {
    if (this.collapsed === event) {
      return;
    }

    if (!event) {
      this.notesPaneSize = '620px';
    } else {
      this.notesPaneSize = '0px';
    }
  }
```
Once you remove that method, everything works as expected. Please let me know what do you want to achieve.

Regards.

**Comment by kdinev** [comment]
@mddragnev I am able to reproduce the issue even with the custom event handling removed but in a slightly different way. If the right panel is at its minimum size, then the panel collapses, but the space is not taken by the left panel. If the left panel is resized such that the right one is not at it's minimum size, then it collapses properly.
