### ISSUE TITLE
Vertical bar of pinned column is cut off in the middle when rows are not filled up.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1058]
### Description  
Vertical bar of pinned column is cut off in the middle when rows are not filled up.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-issue

### Result  
![image](https://user-images.githubusercontent.com/15909409/38966452-4cccc70c-43bd-11e8-92ef-968c5b5f4251.png)

### Expected result  
Vertical bar should not be cut off.

**Comment by ChronosSF** [comment]
Actually I don't think this is feasible to fix. It's just how the pinning border works at the moment. We need a different rendering method for it in order to resolve.

@simeonoff , let me know what you think. IMO this should be considered by design.

**Comment by simeonoff** [comment]
@ChronosSF yeah, since we add the pin border to the cell itself, there isn't a feasible fix at the moment.

**Comment by simeonoff** [comment]
@tkiryu I will try to provide a "fix" for this in this release.

**Comment by kdinev** [comment]
@tkiryu @simeonoff This is a scenario with explicit height set and should not be handled by use, but by the developer, by reducing the height. 

The new smart defaults will never get the grid into such scenario by default, when explicit height is not set. #1054

**Comment by tkiryu** [comment]
@kdinev Hmm..., the solution that reducing the grid height doesn't seem to meet the needs of  those who want to fix the grid at specific height no matter how many rows are.

`igGrid`has no problem with vertical bar.
http://jsfiddle.net/mbgoa7tr/

I expect `igx-grid` to be the same behavior.

**Comment by kdinev** [comment]
@tkiryu Have you checked what happens with the new sizing functionality?

**Comment by tkiryu** [comment]
@kdinev Oh, sorry I haven't checked yet. I'll check #1054 with 5.3.0.rc.2.

**Comment by tkiryu** [comment]
@kdinev I checked new sizing functionality. 
It is nice! It makes us more convenient!

But, with my understanding, this functionality is for scenarios that grid's width/height are not provided. Unfortunately, it doesn't cover my scenario.

**Comment by tkiryu** [comment]
By the way, I probably found an issue with calculating height.
https://stackblitz.com/edit/igx-grid-default-sizing

In the sample above, 
- I remove `width`, `height` and `columnWidth` inputs from the igx-grid.
- I set grid container height to `800px` via CSS.
- I add 12 rows. As a result, there are 15 rows.

I expected igx-grid height was `800px`. But in fact, igx-grid height exceeds `800px`.

Should I submit an issue?

**Comment by MayaKirova** [comment]
@tkiryu In the referenced sample I see 15 records in the variousData array to which the grid is bound. So I’m not sure what you mean by :
•	I add 12 rows. As a result, there are 15 rows.
Let me know if I’m missing something.

Based on the defined parameters for the new height defaults as per the original issue - https://github.com/IgniteUI/igniteui-angular/issues/1054 :
height
•	100% - if parent container = 0 then use the height of the viewport/window.
•	if rowHeight * rowCount < height then set height = null.

15 rows x 50px height each = 750px, which is less than 800. => the height is set to null hence the resulting height will not be equal to the container height. The content will span based on its own size.

By that spec headers and footers are not included in the calculations, so it’s possible for them to exceed the container height if they’re larger.

I suppose you can log it as an improvement idea as at this time the behavior is compliant with the spec, hence it shouldn’t be considered a bug.

**Comment by kdinev** [comment]
@tkiryu I just tested your sample. The height was not set and the grid was spanning the container initially.
![image](https://user-images.githubusercontent.com/1472513/39232378-c6ba912c-4875-11e8-8ea6-b0e1a8f10a99.png)

Then I added height, and the grid was within the height.

![image](https://user-images.githubusercontent.com/1472513/39232390-d32b430c-4875-11e8-8b77-0e63f1a39bee.png)
