### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'summaries')

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#10582]
## Description  
Open grid row drag base sample from angular samples

 * igniteui-angular version: 13.0.0-rc.1
 * browser: any

## Steps to reproduce  

1. Try to drag a row to the second grid
2. Error is througn 

## Result  
![image](https://user-images.githubusercontent.com/11193764/142827461-933f6b33-9108-4ac8-aca1-f8b9cdbbaad1.png)

**Comment by Volen99** [comment]
Fixed by #10587
