### ISSUE TITLE
igx-grid - editing cell style should be Improved.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1059]
### Description  
It is hard to understand whether the cell is in edit mode or not.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-issue
2. Double click a cell to enter edit mode.

### Result  
1. It's hard to understand whether the cell is in edit mode or not, especially, it is hard to see  where the caret is.
2. Due to the padding, editor is pushed to the bottom in the cell. 
![image](https://user-images.githubusercontent.com/15909409/38966922-976fc082-43bf-11e8-87e3-0cc41092c06a.png)

### Expected result  
1. Cell in edit mode is not highlighted.
2. Cell in edit mode doesn't have padding.

For example, like below.

#### igx-input-group type is `LINE`(by default)
![image](https://user-images.githubusercontent.com/15909409/38967683-2f1d8a56-43c3-11e8-9277-d8eb4557ed75.png)

#### igx-input-group type is `BOX`
![image](https://user-images.githubusercontent.com/15909409/38967763-806cda1a-43c3-11e8-8792-ea1027305984.png)

#### igx-input-group type is `BORDER`
![image](https://user-images.githubusercontent.com/15909409/38967829-d6ba42ea-43c3-11e8-82a1-aaf62fc2728d.png)

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
Closing this as it has been resolved with #1250
