### ISSUE TITLE
[igxPivot] Several empty cells have a wrong template after adding a filter to the grid configuration

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#10609]
## Description  
When applying sorting, there are several row header cells that are empty.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the Pivot dev sample (`/pivot`)
2. Move the All Products chip from the rows section to the filters section
3. Filter out Components from All Products
4. Then filter out UK from the Country chip
5. Sort the Bulgaria UnitsSold column, the US UnitsSold column and the Uruguay UnitsSold column
6. Collapse the 2011 row
7. Observe the empty row header cells

## Attachments  
![image](https://user-images.githubusercontent.com/8365193/143005537-e9afb8fb-9ae4-49bf-a46a-e67c1787ba64.png)

**Comment by MayaKirova** [comment]
@3phase 
Aren't these empty before filtering and sorting as well?
For example when setting the following config: 
```
 rows: [
            new IgxPivotDateDimension(
                {
                    memberName: 'Date',
                    enabled: true
                },
                {
                    months: false
                }
            ),
            {
                memberName: 'City',
                enabled: true
            }
        ],
```

And scrolling down to 2011:

![image](https://user-images.githubusercontent.com/10397980/143251987-473943bf-a659-4042-8d32-84c78cf6814d.png)

There seem to be missing without the need to filter and then sort.

**Comment by 3phase** [comment]
@MayaKirova 
They are, however an expand/collapse indicator doesn't show unless the pivot grid has a filter applied. 
I managed to track the issue down to adding a filter to the pivot grid configuration - it seems not to have anything in common with the sorting itself. I should update the issue. However, I'm aware of that and am now investigating in that direction.

**Comment by MayaKirova** [comment]
You can check with this PR: https://github.com/IgniteUI/igniteui-angular/pull/10625
It should remove the unnecessary rows with empty cells.

**Comment by 3phase** [comment]
@MayaKirova 
Your PR would resolve this issue as well, so I'd link it here.

**Comment by MayaKirova** [comment]
The PR was merged so I'll close it now.
