### ISSUE TITLE
igx-grid - caret can't be moved in a editing cell.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1060]
### Description  
Caret can't be moved in a editing cell.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-issue
2. Double click a cell to enter into edit mode.
3. Press right or left arrow key.

### Result  
Caret can't be moved(Due to highlighted background color, it's hard to see the caret, though). Edit mode ends and another cell is highlighted instead.

### Expected result  
Caret should be moved in editing cell.

**Comment by rkaraivanov** [comment]
@Aleksandyr 
The `stopImmediatePropagation` decorator is neat but I think it's an overkill in this case. Just return from the handler when the cell is in edit mode.
