### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'groupable')

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#10619]
## Description  
When i switch columns and rows data in the current grid, the error is thrown TypeError: Cannot read properties of undefined (reading 'groupable'), detail error written below.

This doesnot cause any issues, but why is this happening.
It was not the case when we were using version 11.x.x, started happening when we switched to version 12.3.x.

 * igniteui-angular version: 12.3.1
 * browser: 

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
TypeError: Cannot read properties of undefined (reading 'groupable')
    at IgxGroupByMetaPipe.transform (igniteui-angular.js:54724)
    at pureFunction2Internal (core.js:25681)
    at Module.ɵɵpipeBind2 (core.js:25855)
    at IgxGridGroupByAreaComponent_ng_container_1_Template (igniteui-angular.js:4238)
    at executeTemplate (core.js:9618)
    at refreshView (core.js:9484)
    at refreshEmbeddedViews (core.js:10609)
    at refreshView (core.js:9508)
    at refreshComponent (core.js:10655)
    at refreshChildComponents (core.js:9280)

## Expected result  
No error should be thrown

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by dkamburov** [comment]
@amitmoondra 
Looks like the `IgxGroupByMetaPipe` is unable to find the column specified into the grouping expressions. Maybe clearing them, before changing the data will resolve it.
Can you provide a stackblitz demo with the issue, it could help better investigating the issue?

**Comment by amitmoondra** [comment]
But my question is this happens when columns and row array is [] empty, why is it throwing an error when columns are empty?
That ideally should not happen.

**Comment by dkamburov** [comment]
I agree.
