### ISSUE TITLE
Deprecate rowID and rowData in interfaces

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#10617]
Following the removal of `rowID` and `rowData` properties from `IgxRowDirective` and all public classes implementing the `RowType` interface, considering the following:

Deprecate the old `rowID` and `rowData` from any or all of the following:

- [x] context object of [`rowSelectorTemplate`](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html#L18)
- [x] [`IGridEditDoneEventArgs`](https://github.com/IgniteUI/igniteui-angular/blob/13d82c111d668dfdc8c0f4ec9e1498d0d3e32667/projects/igniteui-angular/src/lib/grids/common/events.ts#L20)
- [x] [`IRowToggleEventArgs`](https://github.com/IgniteUI/igniteui-angular/blob/13d82c111d668dfdc8c0f4ec9e1498d0d3e32667/projects/igniteui-angular/src/lib/grids/common/events.ts#L151)
- [x] [ `IPinRowEventArgs`](https://github.com/IgniteUI/igniteui-angular/blob/13d82c111d668dfdc8c0f4ec9e1498d0d3e32667/projects/igniteui-angular/src/lib/grids/common/events.ts#L165)
- [x] #13425
- [x] [`IPathSegment`](https://github.com/IgniteUI/igniteui-angular/blob/13d82c111d668dfdc8c0f4ec9e1498d0d3e32667/projects/igniteui-angular/src/lib/grids/common/grid.interface.ts#L42)

and introduce the new `key` or `primaryKey` (already done with https://github.com/IgniteUI/igniteui-angular/pull/12394) and `data`

**More stuff to be addressed in this PR:**

1) For better readibility and maintenance, destructure `IGridEditDoneEventArgs` to `ICellEditDoneEventArgs`
and `IRowEditDoneEventArgs` as follows:

 
`IGridEditDoneEventArgs` to:

- ICellEditDoneEventArgs
- IRowEditDoneEventArgs

`IGridEditEventArgs` to

- ICellEditEventArgs
- IRowEditEventArgs

Grid,interface.ts shoud look like:

    cellEditEnter: EventEmitter<ICellEditEventArgs>;
    cellEdit: EventEmitter<ICellEditEventArgs>;
    cellEditDone: EventEmitter<ICellEditDoneEventArgs>;
    cellEditExit: EventEmitter<ICellEditDoneEventArgs>;
    rowEditEnter: EventEmitter<IRowEditEventArgs>;
    rowEdit: EventEmitter<IRowEditEventArgs>;
    rowEditDone: EventEmitter<IRowEditDoneEventArgs>;
    rowEditExit: EventEmitter<IRowEditDoneEventArgs>;

 
DONE https://github.com/IgniteUI/igniteui-angular/pull/12832/commits/b92d8ff78c8b518013e9db77a3e238e9ea184d85?show-viewed-files=true&file-filters%5B%5D=

2) For `rowAdd` and `rowDelete` emit new interface, which is cancellable - maybe `IRowDataEventArgs` is the proper candidate.
2.1 - see comment on line 555 in grid,interface about this change - in the end we can reconsider if this will be introduced with 16.1 or other more major version
2.2 - add rowDelete to GridType, build correct object to be emitted

3) Change `rowAdd` and `rowDelete` types for treeGrid and Pivot to be compatible with GridType
4) The `primaryKey` argument also crept into add and edit events, not only `rowDeleted`:

- see changes in crud.service.ts and events.ts here https://github.com/IgniteUI/igniteui-angular/pull/12394/files
- primaryKey should not exist in EDIT events interface
- for rowAdd - is subject of change. Should consider this https://github.com/IgniteUI/igniteui-angular/issues/12091

5) The rest of the events, which emitted `rowID` until now - see if needed to migrate `rowID` to `rowKey` or `key`. For row events, it makes sense to be `key`, while for cell events it makes sense to be `rowKey`. Still, if cell event to emit `rowKey` in difference to row events, which will be emitting `key`, is a big effort, keep cell events to also emit `key` and make sure it is properly documented, so that a user knows what is reading through `eventArgs.key`

6) Make a list of the breaking changes and think of way to avoid them. Damyan can help here too.

**Comment by wnvko** [comment]
I would go with `key` everywhere. I know we just added `primaryKey`, but let change it to `key`.

**Comment by hanastasov** [comment]
> I would go with `key` everywhere. I know we just added `primaryKey`, but let change it to `key`.

Just to remind tt went from `key` to `primaryKey` in https://github.com/IgniteUI/igniteui-angular/pull/12394 by demand.

**Comment by damyanpetev** [comment]
@wnvko The argument was explicitly renamed from `key` to `primaryKey` because it was not the same type - as in it'll never switch to the row object to use as identifier when a primaryKey on the Grid is not defined and will be empty instead. So it's indeed primary key only and best not to mix it with the `key` concept on row. 

IIRC, the argument was actually only on the delete event btw (since that's where it was needed), yet it  might've crept up to some other events? Did we end up with events that have both `key` and `primaryKey`? Cuz that'd be super awkward lol

**Comment by hanastasov** [comment]
> 

Thanks.

1) No, we didn't end up with events that have both `key` and `primaryKey`
2) Yes, the `primaryKey` argument also crept into add and edit events, not only `rowDeleted`. That's totally my mistake as I did not extend the row deleted arguments, as task was logged, but for me it "made sense" to do the same for edit and add events.

Will try to fix this in current PR.
