### ISSUE TITLE
Clicking on the summary text shouldn't toggle the value visibility

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#1062]
### Description  
When clicking on any of the column summaries text, e.g. Count, the value visibility toggles.

### Steps to reproduce  

1. Open the summaries sample
2. Click on count in the Product Name column summary
3. Click again on count in the Product Name column summary

### Result  
The count value visibility is toggled.

### Expected result  
Nothing should happen. The value should stay visible.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/38976941-730d4e0c-43bb-11e8-9a63-2b2be0164fc1.png)

**Comment by simeonoff** [comment]
@kdinev this is by design, requested by @jberes

**Comment by kdinev** [comment]
@simeonoff You're not right. The request is for the whole summary to be toggle-able, not just the summary value.
