### ISSUE TITLE
[igxPivot] When all dimensions are initially collapsed and first dimension has children the second dimension data does not display correctly.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#10639]
## Description  
When all dimensions are initially collapsed ([defaultExpandState] = 'false' or not set) and first dimension has children the second dimension data does not display correctly.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run the pivot-hierarchy sample with config:
```
columns: [
            {
                memberName: 'AllSeller',
                memberFunction: () => 'All Sellers',
                enabled: true,
                childLevel:
                {
                    memberName: 'Seller',
                    memberFunction: (data) => data.Seller.Name,
                    enabled: true,
                },
            },
        ],
        rows: [
            {
                memberName: 'AllProduct',
                memberFunction: () => 'All Products',
                enabled: true,
                childLevel:
                {
    
                    memberName: 'Product',
                    memberFunction: (data) => data.Product.Name,
                    enabled: true
                }
            },
            {
                memberName: 'City',
                memberFunction: (data) => data.Seller.City,
                enabled: true,
            },
        ],
```

## Result  
Observe that the second dimension does not show its values.

![image](https://user-images.githubusercontent.com/10397980/143560119-596ab374-d548-4dcf-aec3-fb9fbbdd92d7.png)

## Expected result  
Should show all unique City values as rows.

Note: Works as expected if [defaultExpandState] = 'true' .

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by skrustev** [comment]
Also if expanded there are cases where there are multiple Cities even when expanded, but the they are not shown
![Cities](https://user-images.githubusercontent.com/3768136/143575681-c624ff3c-4356-478e-ba55-e6cbea31759d.jpg)
