### ISSUE TITLE
Cannot import IgxGridTransaction  from "igniteui-angular"

### ISSUE THREAD

**Issue by katherinedragieva** [IgniteUI/igniteui-angular#10648]
## Steps to reproduce  

1. Open dev demos
2. Try to import  IgxGridTransaction  from "igniteui-angular"

## Result  
Missing component from "igniteui-angular"

![Screenshot 2021-11-26 160309](https://user-images.githubusercontent.com/35975071/143594174-76880a93-94b6-47c4-8180-25f7ef6cce3e.png)

**Comment by Lipata** [comment]
This was deprecated in 12.1.0 and in the [update guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#from-120x-to-121x) you can find the following section:

* The DI pattern for providing `IgxGridTransaction` is deprecated. The following will still work, but you are advised to refactor it, as it **will likely be removed** in a future version:

    ```typescript
    @Component({
        template: `<igx-grid [data]="data">
        ...
        </igx-grid>`,
        providers: [{ provide: IgxGridTransaction, useClass: IgxTransactionService }],
        ...
    })
    export class MyCustomComponent {
        ...
    }
    ```

    In order to achieve the above behavior, you should use the the newly added [`batchEditing`](../grid/batch-editing.md) input:
    ```typescript
    @Component({
        template: `<igx-grid [data]="data" [batchEditing]="true">
        ...
        </igx-grid>`
        ...
    })
    export class MyCustomComponent {
        ...
    }
    ```

I will log an issue to remove `igxGridTransaction` for a future release.

**Comment by katherinedragieva** [comment]
@Lipata I am reopening this issue due to migration issues.

**Comment by Lipata** [comment]
@katherinedragieva, I've now checked and it seems that back then we have decided that we will not add a migration and will leave the explanation in the Update Guide above as a solution. No migration was or will be added. Thanks!
