### ISSUE TITLE
When a grid has height: 100% and is in a flex column container it resizes infinitely.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#10664]
## Description  
If grid is in flex container and has 100% height the size changes on each change detection.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the 'Pivot Grid' sample and put all elements in a flex column:
```
<div class="sample-flex-column">
    <igx-combo #combo class="combo" [itemsMaxHeight]="250" (selectionChanging)="handleChange($event)"
               [data]="dimensions" [displayKey]="'memberName'" [(ngModel)]="selected"
               placeholder="Dimension(s)" searchPlaceholder="Search...">
    </igx-combo>
    <div class="density-chooser">
        <igx-buttongroup>
            <button igxButton [disabled]="grid1.displayDensity === comfortable" (click)="setDensity('comfortable')">Comfortable</button>
            <button igxButton [disabled]="grid1.displayDensity === cosy" (click)="setDensity('cosy')">Cosy</button>
            <button igxButton [disabled]="grid1.displayDensity === compact" (click)="setDensity('compact')">Compact</button>
        </igx-buttongroup>
    </div>
    <igx-pivot-grid #grid1 [data]="origData" [width]="'100%'" [height]="'100%'" [defaultExpandState]='true'
    [pivotConfiguration]="pivotConfigHierarchy" (dimensionsChange)='dimensionChange($event)'>
</igx-pivot-grid>
</div>
```
2. Observe.

![resizing](https://user-images.githubusercontent.com/10397980/144263846-22ac3959-65ad-476f-bb30-9c9cfe550777.gif)

## Result  
Grid resizes infinitely.

## Expected result  
It should stay one size.

**Comment by 3phase** [comment]
@MayaKirova isn't that expected behavior, since all the parent containers have relative height? If you set the parent's height to say 800px, the problem won't reproduce anymore.

**Comment by MayaKirova** [comment]
If no height can be inferred a default height should be set. It should not break the whole page.

**Comment by 3phase** [comment]
I agree with that, I just thought that this is a known issue because I've seen it multiple times with other grids.

**Comment by MayaKirova** [comment]
If it affects multiple grids it should be fixed for all of them in the base code.
