### ISSUE TITLE
Dependabot alerts caused by sassdoc/typedoc plugins

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#10660]
## Description  
Check out the [dependabot alerts](https://github.com/IgniteUI/igniteui-angular/security/dependabot), there are a couple with medium and high sevirity that we have to check.

**Comment by kdinev** [comment]
@zdrawku @rkaraivanov Has this been fixed?

**Comment by zdrawku** [comment]
This has been fixed
