### ISSUE TITLE
[IgxPivot] Having dashes into values in ESF for column dimensions does not reflect the correct value

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#10663]
## Description  
Having dashes into values in ESF for column dimensions does not reflect the correct value

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open pivot dev sample
2. Modify Country value to have dashes(For example change USA to U-S-A)

## Result  
The unique value U-S-A is not displayed in ESF. It renders only 'A'

## Expected result  
The unique value should be rendered correctly

## Attachments  
![image](https://user-images.githubusercontent.com/1182001/144262399-554fcc4b-214e-4978-b58b-bcc98f88beaa.png)

**Comment by MayaKirova** [comment]
Does this not get fixed if you set a different column separator in the pivot config, for example:

```
public pivotConfigHierarchy: IPivotConfiguration = {
        pivotKeys: {
            aggregations: 'aggregations', records: 'records', children: 'children', level: 'level',
            rowDimensionSeparator: '_', columnDimensionSeparator: '_'
        },
```

**Comment by dkamburov** [comment]
> Does this not get fixed if you set a different column separator in the pivot config, for example:
> 
> ```
> public pivotConfigHierarchy: IPivotConfiguration = {
>         pivotKeys: {
>             aggregations: 'aggregations', records: 'records', children: 'children', level: 'level',
>             rowDimensionSeparator: '_', columnDimensionSeparator: '_'
>         },
> ```
Yes, this solves it. But I logged it, because the columns were generated properly
