### ISSUE TITLE
Header of igxGrid is with different size when there is filtering toggle

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#1067]
### Description  
Header of igxGrid is bigger when there is filtering toggle.

### Steps to reproduce  

1. Open https://stackblitz.com/edit/crm-landing-page-4rd4yl
2. Scroll to the end

### Result  
The header is flickering

### Expected result  
The header should not flicker, its height should not change.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/1182001/38988035-72b48f78-43da-11e8-8c33-841c11607d04.png)

**Comment by MayaKirova** [comment]
Seems that the icon styles expands the container a bit. Seems to be a styling issue.

**Comment by simeonoff** [comment]
Closing as this has been resolved with #1125
