### ISSUE TITLE
If you make a row unselectable, the select/deselect all button will not work with deselecting all rows

### ISSUE THREAD

**Issue by egilsd** [IgniteUI/igniteui-angular#10689]
## Description  
We have a grid with multiple row selection, but one of the rows are supposed to be unselectable by the user.
If the user presses the "select all rows" button in the top left of the grid, all rows except the unselectable row will be selected (which is correct).
If the user presses the button again, nothing happens. I assume its because the grid wants all rows to be selected before being able to deselect everything.

 * igniteui-angular version: 12.3.2
 * browser: Google Chrome

## Steps to reproduce  

1. Step 1: Check your own example here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-selection#conditional-selection-demo 
2. Step 2: Press the top-left corner to select all, then press the button again to deselect all.

## Result  
All rows that are able to be selected are selected on the first press, but all (selected) rows are not deselected again on the second press.

## Expected result  
All rows that are able to be selected are selected on first press, all (selected) rows are deselected on the second press.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/93121292/144830998-6208b850-5b9d-4cfb-9cda-a2113ce9f744.png)

**Comment by kdinev** [comment]
@egilsd The issue is with the sample and more specifically the last block of the `onRowSelect` method.

Change this:
```ts
    public onRowSelect(event: IRowSelectionEventArgs) {
        if (!event.added.length && event.removed.length) {
            // ignore deselect
            return;
        }
        const originalAddedLength = event.added.length;

        // update selection to contain only allowed rows
        event.newSelection = event.newSelection.filter(x => this.isSelectionAllowed(x));

        // cleanup selection if all conditionally selectable rows are already selected
        if (event.added.length === 0
            && !event.newSelection.filter(x => event.oldSelection.indexOf(x) === -1).length
            && originalAddedLength > 1) {
                // all selected from header, deselect instead
                event.newSelection = [];
        }
    }
```

To this:
```ts
    public onRowSelect(event: IRowSelectionEventArgs) {
        if (!event.added.length && event.removed.length) {
            // ignore deselect
            return;
        }
        const originalAddedLength = event.added.length;

        // update selection to contain only allowed rows
        event.newSelection = event.newSelection.filter(x => this.isSelectionAllowed(x));

        // cleanup selection if all conditionally selectable rows are already selected
        if (event.newSelection.length
            && !event.newSelection.filter(x => event.oldSelection.indexOf(x) === -1).length
            && originalAddedLength > 1) {
                // all selected from header, deselect instead
                event.newSelection = [];
        }
    }
```

I've also made a PR to fix the sample, which is linked to this issue.
