### ISSUE TITLE
igx-grid default column moving icon is misleading

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#10690]
## Is your feature request related to a problem? Please describe.
When moving a column in the `igx-grid` or any derivative grids, the column header shadow has a 🔒 icon. The icon is misleading as it appears to initiate some kind of a lock action on the column. Instead we should be showing ↔️ or something of that sort.

## Describe the solution you'd like
Change the default icon in the column header shadow when moving. I went through our extended icon pack and noticed we still don't have an icon like that. It would be good to update the pack with such icons.

## Describe alternatives you've considered
The shadow can be retemplated in the application, but that would cause effort for every column in every grid on an application-level, so it's not a good solution.

## Additional context
![image](https://user-images.githubusercontent.com/1472513/144842460-73e93c79-de57-4982-b4fb-17de5dd5d46a.png)

**Comment by StefanIvanov** [comment]
related to #10313
