### ISSUE TITLE
All rows would hide upon committing a transaction with a newly added row on a grid with 1m+ rows

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#10692]
## Description  
All data would disappear right after committing a transaction with a newly added row on a grid with 1m+ rows.

 * igniteui-angular version: 13.0
 * browser: 

## Steps to reproduce  

1. Checkout the following branch: `pbozhinov/sample-10692` (please, delete after resolved)
2. Add a new row to existing grid
2. Commit transaction
3. Observe how dataview becomes empty

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
@3phase Has this been fixed?
