### ISSUE TITLE
The values of boolean type column cells can be modified to any custom value

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1071]
### Description  
The values of boolean type column cells can be modified to any custom value.

**NOTES:**
A derivative issue from this one is that when the column is filtered by "true", the custom values are included in the filtered IN values. (The custom values should not be able to exist at all.)

### Steps to reproduce  

1. Download and run the attached sample application.
2. Try to change the value of any cell from the "Released"column to a custom string (for example "Hello").

### Result  
The change is successful.

### Expected result  
The change is **not** successful.

### Attachments  

[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1928020/igxgridSample.zip)

**Comment by zdrawku** [comment]
related to the enhancement from #1271
