### ISSUE TITLE
Tree Grid cascade selection bad performance

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#10759]
## Description  
Selecting a row with 60k records takes a long time and freezes the browser.

 * igniteui-angular version: 11.1.x, 12.3.x, 13.0.x
 * browser: any

**Comment by armeireles** [comment]
Hello Martin
Thanks. Here you have the video recording of the issue! Have a good christmas!

**Comment by mmart1n** [comment]
> Hello Martin Thanks. Here you have the video recording of the issue! Have a good christmas!

Hello, it seems that the link to the video is missing. Could you please reattach it? Happy Holidays!

**Comment by armeireles** [comment]
https://www.loom.com/share/15e4501dc25a40049614310497cc8eef
