### ISSUE TITLE
The values of number type column cells can be modified to any custom value

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1075]
### Description  
The values of number type column cells can be modified to any custom value.

**NOTES:**
A derivative issue from this one is that when the value of a number type cell is set to a string and then we sort the respective number column - the records above and the records below the edited record are independently sorted.

### Steps to reproduce  

1. Run the "Grid" demo app.
2. Enable "Sorting" and "Editable" for the "ID" column.
3. Change the ID value of the third record from 3 to "TEST".

### Result  
The change is successful.

### Expected result  
The change is **not** successful.

### Attachments  

![edit](https://user-images.githubusercontent.com/12784974/38994354-d2cb8e5c-43ee-11e8-8703-21c35dad5254.gif)

**Comment by zdrawku** [comment]
related to the enhancement from #1271
