### ISSUE TITLE
[IgxColumnActions] The igxColumnHiding state is not updated after grid's stated is restored.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#10769]
## Description  
[IgxColumnActions] The igxColumnHiding state is not updated after grid's stated is restored.

 * igniteui-angular version: 13.0.5
 * browser: Chrome, Edge, Firefox

## Steps to reproduce  

1. npm install and npm start the attached sample c00221444-app1.
2. Click the buttons 1, 2 and 3 in this order.

## Result  
The column list in the IgxColumnActions is not updated after clicking the button 3.

## Expected result  
The column list in the IgxColumnActions should be updated back to that you see before the button 1 is clicked.

## Attachments 
[c00221444-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/7787293/c00221444-app1.zip)

**Comment by Volen99** [comment]
Tested it and find out that a div is stopping us from clicking the button as shown in the screenshot. Removing the div and trying again, the button is actually restoring the state.
![image](https://user-images.githubusercontent.com/41373491/148220900-4faad4b7-1f9a-495f-bc27-28154b213484.png)
