### ISSUE TITLE
Random error while scrolling in filtered view

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#10768]
## Description  
My client is getting this error while scrolling after applying filters in igx-grid
The error says 
**_Cannot read properties of null (reading 'mergedAttrs')_**

## Attachments  
I have an error messgae on Slack channel
![image](https://user-images.githubusercontent.com/79090369/147561289-db856bdd-c60d-44e3-8f24-d0bb5c609710.png)

**Comment by amitmoondra** [comment]
@hanastasov this is production level issue, can you guys look into this?

**Comment by hanastasov** [comment]
Hi @KaushikEDS and @amitmoondra 

Is there any chance to send the stack trace of the error (you can snapshot the browser dev tools), or any other additional information for the steps to follow? I took a random grid, applied filters and scrolled, but no errors.

I am pretty sure the error is thrown by a code external to Ignite UI library, as `mergedATTRS` does not appear anywhere in our code base.
