### ISSUE TITLE
IgxGrid advancedFilteringExpressionsTree cannot be restored from localstorage

### ISSUE THREAD

**Issue by kenshiro1213** [IgniteUI/igniteui-angular#10763]
## Description  
Describe the issue.

 * igniteui-angular version: -
 * browser: -

## Steps to reproduce  

1. Serve sample project 
2. Set advancedFiltering
3. Reload the browser

## Result  
Filters set in 1 will not be restored.

## Expected result  
Filters set in 1 will be restored.

## Attachments  

grid.component.html
```
  <igx-grid
    #grid
    [allowAdvancedFiltering]="true"
    [data]="productsTable1"
    [autoGenerate]="false"
    displayDensity="cosy"
    primaryKey="ProductID"
    class="grid"
    height="500px"
    width="100%"
    (advancedFilteringExpressionsTreeChange)="
      advancedFilteringExpressionsTreeChange($event)
    "
  >
```

grid.component.ts
```
 export class GridComponent implements OnInit {
  public productsTable1: any = null;
  public selectedCustomFilter: any = null;

  @ViewChild('grid', { read: IgxGridComponent, static: true })
  public grid: IgxGridComponent;

  constructor(private productsService: ProductsService) {}

  ngOnInit() {
    this.productsService
      .getData('Table 1')
      .subscribe((data) => (this.productsTable1 = data));

    const state = window.localStorage.getItem(`customFilter`);

    if (state) {
      const filter = JSON.parse(state) as IFilteringExpressionsTree;
      console.log(filter);
      this.grid.advancedFilteringExpressionsTree = filter;
    }
  }

  public advancedFilteringExpressionsTreeChange(
    value: IFilteringExpressionsTree
  ): void {
    console.log(value);
    if (value) {
      window.localStorage.setItem(`customFilter`, JSON.stringify(value));
    }
  }
}
```

**Comment by kenshiro1213** [comment]
[angular-ignite-sample.zip](https://github.com/IgniteUI/igniteui-angular/files/7766928/angular-ignite-sample.zip)

**Comment by hanastasov** [comment]
Hi @kenshiro1213,

What you are doing can be easily done using the [`IgxGridState directive`](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/state-persistence)

By default it saves all features, but you can only work with the features you want:
```html
<igx-grid igxGridState></igx-grid>
```

```typescript
@ViewChild(IgxGridStateDirective, { static: true }) public state;

public saveGridState() {
    const state = this.state.getState(true, "advancedFiltering") as string;
    window.localStorage.setItem('grid-state', state);
}

public restoreGridState() {
    const state = window.localStorage.getItem('grid-state');
    this.state.setState(state);
}
```

Internally the state directive clears the expressions tree from references that may cause circular reference erros when stringifying it, as you do.

**Comment by kenshiro1213** [comment]
[angular-ignite-sample-IgxGridStateDirective.zip](https://github.com/IgniteUI/igniteui-angular/files/7868337/angular-ignite-sample-IgxGridStateDirective.zip)

Thanks, @hanastasov 
I use the state directive in this sample.

After reload, at ngOnInit "restoreGridState" shows error 
```
core.mjs:6469 ERROR TypeError: Cannot read properties of undefined (reading 'find')
    at IgxGridStateDirective.createExpressionsTreeFromObject
```

Is there something wrong with the code?

**Comment by hanastasov** [comment]
Hi @kenshiro1213 ,

Sorry for late answer. `ngOnInit` is too early in the lifecycle, when grid columns are still not resolved, therefore the state directive cannot apply filtering or anything to the columns, thus error is thrown. Use the ngAfterViewInit instead:

```typescript
  ngAfterViewInit() {
    this.restoreGridState();
  }
```

**Comment by kenshiro1213** [comment]
[angular-ignite-sample-IgxGridStateDirective.zip](https://github.com/IgniteUI/igniteui-angular/files/7895103/angular-ignite-sample-IgxGridStateDirective.zip)
I was able to avoid errors by using ngAfterViewInit.
Thank you so much!
