### ISSUE TITLE
IgxGrid: clearing the sorting expressions should not affect the gird's grouping

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#10765]
## Is your feature request related to a problem? Please describe.
If the sorting expressions are cleared with the [clearSort](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#clearSort) method, the grid's grouping will be in messed up state. 

![sortgroup1](https://user-images.githubusercontent.com/75325639/147228236-0e553a60-64d9-4a6d-80c7-9a8447527569.gif)

## Describe the solution you'd like
The grid's grouping shoud be not affected if the clearSort method is executed.

**Comment by viktorkombov** [comment]
Related to #9674

**Comment by Eralmidia** [comment]
@kdinev Will this be prioritized soon? Its a rather major issue, as now we can't really trust the grouping, because there might very well be that one group doesn't contain every row it should.

**Comment by kdinev** [comment]
@ChronosSF Could you comment on this issue. I know that sorting and grouping expressions are connected, since grouping is a superset of sorting, but since the sorting and grouping expression collections are different, wouldn't this be easily achievable?

**Comment by hanastasov** [comment]
@kdinev Regarding https://github.com/IgniteUI/igniteui-angular/issues/9674 we started decoupling sorting from grouping. Materializing the decoupling in code is not much, but not sure how much adittional effort is needed to complete it and add anything neccessary to fix tests. bugs. etc.
