### ISSUE TITLE
How to distinguish the event source for cellEditExit?

### ISSUE THREAD

**Issue by wannadream** [IgniteUI/igniteui-angular#10774]
## Question  
Is it possible to determine the source of cellEditExit? In below scenarios, they both trigger cellEditExit.

- Press "ESC" in row edit mode: this includes a keyboard event object which you can trace the source
- Click on "Done": event object is undefined here.
- Click on "Cancel": event object is undefined here.
- Click on another row: this includes a pointer event object which you can hardly tell if it is a cancellation operation or not.

![image](https://user-images.githubusercontent.com/6989212/147807948-2745d7e5-b3af-4b45-a7bd-add338814ed9.png)

I am doing some customization data manipulation, really want to find out exactly which is which, especially the "Cancel" button.
Any ideas?

 * igniteui-angular version: 12.3
 * browser:  Chrome the latest

**Comment by Aleksandyr** [comment]
@wannadream Can you elaborate more on what you are trying to achieve?
Can you tell me which version of the product you are using?

On my side, I am receiving pointer events for both **Cancel** and **Done**.
The operation might be caught by the event itself.

You are trying to apply different logic based on where you are clicking or something?
In that case, you can implement a [custom template](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-editing#customizing-buttons) for those two buttons and handle your logic there.

Would that work for you?

**Comment by wannadream** [comment]
I am using 12.3.3. I will try your suggestion of custom template.

**Comment by Aleksandyr** [comment]
@wannadream Great, waiting to hear from you.

**Comment by Aleksandyr** [comment]
@wannadream Have you tried this approach? If it's okay with you, we can close this issue.
