### ISSUE TITLE
igx-grid - igxCell isAddRow

### ISSUE THREAD

**Issue by mikerentmeister** [IgniteUI/igniteui-angular#10771]
## Question  
I am currently adding using the beginAddRowByIndex function for the igx-grid, and one thing I noticed is that when I add a row with the following columns, a placeholder value (header text) is shown in the entityId and description columns, but not the dataType column. 

```
<igx-column field="entityId" header="Property Id" [sortable]="true"></igx-column>
<igx-column field="description" header="Description" [sortable]="true"></igx-column>
<igx-column field="dataType" header="Data type" [sortable]="true">
	<ng-template igxCell let-val let-cell="cell">{{val | lookup: dataTypesLookup}}</ng-template>
</igx-column>
```

After digging through the [cell.component.html](https://github.com/IgniteUI/igniteui-angular/blob/13cf8a7d172a7ad228507009cfd9c9f1987cbac3/projects/igniteui-angular/src/lib/grids/cell.component.html) file, I noticed that in the #addRowCell template, it's using a property called isEmptyAddRowCell to conditionally render the cell value, or the header. I know that it's not displaying the header for column because I'm supplying my own template. Given an ng-template with the igxCell directive, is there any way to determine the following:

- If the cell.row is a new row, aka, isAddRow. I see some stuff in the codebase like [let-row](https://github.com/IgniteUI/igniteui-angular/search?q=let-row), but that yields undefined for me when I try to use it.
- Is there a way to get access to the parent IgxGridCellComponent component, so that the its properties like isEmptyAddRowCell and template can be used?

If it's not possible to get access to isAddRow through the igxCell directive, could we turn this into a feature request to add it to the cell.row context for the template? I.e. let-cell="cell". Then using it like cell.row.isAddRow.

 * igniteui-angular version: 
 * browser:

**Comment by ChronosSF** [comment]
Hey @mikerentmeister ,

I'd consider this a bug, not a feature request. The row you get from `cell.row` is not the actual row object which holds a lot more information. It's a stripped down version of it which, however, does not implement the addRowUI getter that would do the job in your case.
