### ISSUE TITLE
Regardless of the column dataType, the value of any cell can be updated to any value through the API

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1077]
### Description  
Regardless of the column dataType, the value of any cell can be updated to any value through the API.

**NOTES:**
The issue is reproduced with the following methods:
- grid.updateCell(...)
- mycell.update(...)
- grid.updateRow(...)

### Steps to reproduce  

1. Download and run the attached sample application.
2. Click a cell from the "ID" column.
3. Click the "Update cell/record" button to set a string value to the cell.

### Result  
The value of the cell is updated.

### Expected result  
The value of the cell **not** updated.

### Attachments  

[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1928396/igxgridSample.zip)

**Comment by zdrawku** [comment]
@ddincheva, discuss all issues related to igxGrid updating with @rkaraivanov.

#1075 #1071 and the current issue.
