### ISSUE TITLE
igx-slider no longer "slides"

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#10805]
## Description  
After implementing the same sample as the one demonstrated into the slider topic  [Labels Orientation and Visibility](https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider/slider#labels-orientation-and-visibility) section in a local project, the slider thumb cannot e dragged. We have to click on a specific tick in order to get the slider to move.

 * igniteui-angular version: 13

## Result  
The slider thumb cannot e dragged

## Expected result  
The thumb should be movable like into the provided demo

**Comment by hanastasov** [comment]
@teodosiah IIRC the issue was reproducible only in the customer sample. Is it possible to upload it here for reference (isolated sample the better).

**Comment by teodosiah** [comment]
@hanastasov , @kdinev  the issue is reproducible when you open [this ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider/slider#labels-orientation-and-visibility) demo in stackblitz, download it and then run it locally


![slider](https://user-images.githubusercontent.com/52423497/167834746-44c373e0-1e02-46c0-b8d0-542eaad5a3b3.gif)

**Comment by kdinev** [comment]
@teodosiah Seems like it's fixed in the latest dev. I copied the slider definition in one of the dev demos and ran against what we have in `master` and the component works fine.

**Comment by teodosiah** [comment]
@kdinev I think it always worked there. The only scenario in which it does not is when the sample is downloaded from stackblitz and run locally.

**Comment by wnvko** [comment]
Here is [StackBlitz ](https://stackblitz.com/edit/angular-qtrzxr?file=src%2Fapp%2Fslider-sample-1%2Fslider-sample-1.component.html) sample reproducing this issue. The first slider is in a form and the second one is the most simple possible range slider. Neither of them slides. 

Tested this on:
MS Edge Version 105.0.1343.53
GC Version 106.0.5249.103
Opera Version 90.0.4480.84
FF Version 105.0.2
Slider does not slide on any of these.

**Comment by Svetloslav15** [comment]
You should import HammerModule in the root module in order for user interactions to work as expected. You can find more information here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider/slider#usage
