### ISSUE TITLE
Feature request: Mouseover fade

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#10821]
It would be nice to have the ability to emphasize the series which are being moused over ngx-charts has a feature like this: https://swimlane.github.io/ngx-charts/#/ngx-charts/line-chart. Hover over a data point, and the series is highlighted, while other series are faded. 

![image](https://user-images.githubusercontent.com/12936286/48259707-10aeb300-e419-11e8-8d83-588a695be797.png)

**Comment by gmurray81** [comment]
This being marked inactive has reminded me that we have this now. You can set `highlightingMode` to `fadeOthers` or `fadeOthersSpecific`
