### ISSUE TITLE
Chart tool tip preserves blank state in the chart body after a dynamic change

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular#10825]
When you have a chart with an item tooltip or category tooltip and you change the series type or tooltip  type(e.g. through buttons click), the chart tooltip remains in the chart area.

![tooltip (1)](https://user-images.githubusercontent.com/25771040/64592652-1ff1ea80-d3b5-11e9-962d-e2aab6375fc3.gif)

**Comment by brianlagunas** [comment]
@sebastian-cox No, there is no update. If/when any progress is made, this issue will be updated.
