### ISSUE TITLE
[igxPivot] Header area scrollbar thumb is not visible.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#10835]
## Description  
When the pivot grid has a scrollbar, the scrollbar placeholder area in the header appears white, because the actual styled thumb element is not visible.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the Pivot Grid and remove any filters if necessary to show the scrollbar.
2. Observe the header right-side area where the thumb should show.

## Result  

The thumb is rendered but is not positioned correctly on the right of the sibling elements, hence that area remains white:

![image](https://user-images.githubusercontent.com/10397980/149537102-160f64dc-7fc4-43a7-8d51-5591109b9c1b.png)

## Expected result  
The thumb should display and position correctly on the right as needed.

**Comment by dkamburov** [comment]
@desig9stein This might be related to styles, can you take a look?
