### ISSUE TITLE
IgxGrid: the grid does not auto size height when a detail template is expanded and page is zoomed

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#10856]
## Description  
The grid do not auto size height when a detail template is expanded and page is zoomed

 * igniteui-angular version: 12.3.x, 13.0.x
 * browser: any

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/github-xqwxy2-q47vgn?file=src%2Fapp%2Fapp.component.ts).
2. Zoom the page to 110%.
2. Expand a detail template.

## Result  
The height of the grid has not been changed.

## Expected result  
The height should be changed in order to be displayed the content of detail template.

## Attachments  
![master-detail](https://user-images.githubusercontent.com/75325639/150037382-814738ca-0890-48ac-a0de-5fa4084b0009.gif)

**Comment by MayaKirova** [comment]
Seems to reproduce only in 12.3.x, in 13.1.x it expand to full auto-size.
