### ISSUE TITLE
Setting "pinned" property of a column at runtime does not work

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1088]
### Description  
Setting "pinned" property of a column at runtime does not work

**NOTES:**
The issue is not reproduced if grid.pinColumn(...) method is used instead of the column's pinned property.

### Steps to reproduce  

1. Download and run the attached sample application.
2. Click the button under the igx-grid.

### Result  
The "ID" column is **not** pinned.

### Expected result  
The "ID" column is pinned.

### Attachments  

[igxgridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/1931910/igxgridSample.zip)

**Comment by SlavUI** [comment]
This is working with 6.1.0
