### ISSUE TITLE
[Pivot] The container height breaks when removing columns by dragging

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#10881]
## Description  
The container height breaks when removing columns, if there is a horizontal scrollbar when removing columns.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open pivot hierarchical dev sample
2. Add Date dimensions to the columns
3. Remove it

## Result  
The size of the container is wrong and seems to break the layout of the pivot grid

## Expected result  
The height of the container should be correct

## Attachments  
![pivot-drag-col](https://user-images.githubusercontent.com/1182001/150520879-c7ffdf01-1733-4706-885e-ac333e62097f.gif)

**Comment by MayaKirova** [comment]
Duplicate of #10877
