### ISSUE TITLE
Sample issue - Hierarchical Grid Row Numbering Demo, wrong row indexing after a row has been expanded

### ISSUE THREAD

**Issue by IvanKitanov17** [IgniteUI/igniteui-angular#10885]
## Description  
When the user expands a row, each row after it has its index incremented by 1. 

 * igniteui-angular version: 
 * browser:  Chrome, Edge and Mozilla

## Steps to reproduce  

1. Open the following sample:
[Row Numbering Demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/row-selection#row-numbering-demo)
2. Expand the first row.
3. Scroll down until the second row is visible, the number in the row selector is 3 instead of 2.

## Result  
When the child container is rendered it is assigned with the row index that follows the row index of the parent row, making all the rows after the expanded one to have their indexes increased by 1.

## Expected result  
The row numbers should have the correct indexes no matter if a row is expanded or not.

**Comment by hanastasov** [comment]
This is by-design. Same applies for the tree grid and hierarchical grid when expanding rows.
