### ISSUE TITLE
Excel Style Filter showing incorrect options

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#10904]
## Description  
I was working on my grid and applying some filters.
Suddenly a set of filters rendered my view blank. I had to reset my filters to load the grid data.
I investigated the excel style filter and some issues.

 * igniteui-angular version: 12.3.0
 * browser: Chrome

## Steps to reproduce  

1. Apply some filters on a column. For eg. Column A
2. Apply some filters on another column. For eg. Column B
3. Reopen the filter for Column A. It still has some options which should not be there. Applying those options renders the grid to show no data.

## Result  
What is the actual result after following the steps to reproduce?

https://user-images.githubusercontent.com/79090369/150990904-1b8b5a6b-8796-4807-abc3-6c50ac6c297d.mp4

## Expected result  
What is the expected result after following the steps to reproduce?
The filters should automatically remove invalid values.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
After applying the invalid filter the filter menu refreshes.
As shown in the image below the option for Blanks is not available now, but as shown in the video it was still there.
![image](https://user-images.githubusercontent.com/79090369/150991188-54cfe8cb-3118-4d72-a303-46f9dbc6b9f3.png)

**Comment by KaushikEDS** [comment]
@ChronosSF @brianlagunas This is an issue in production. It would be great if we get an update on this ASAP.

**Comment by ChronosSF** [comment]
@KaushikEDS , 

@gedinakova 's team will investigate it and if it is reproducible we'll get it into the pipeline for a fix. Thanks for reporting it!
