### ISSUE TITLE
Rework default sorting/filtering strategy's and their methods to be grid agnostic.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#10922]
Currently the sorting/filtering strategy methods sort/filter accept an optional parameter: `grid`. This should be removed and if needed another optional parameter can be exposed in case some data is needed from the grid.

For pivot grid a custom value extraction function (`memberFunction`) is needed to extract the values to sort/filter.
TreeGrid also seems to use the grid reference for something and may need to be modified. 

This came up from: https://github.com/IgniteUI/igniteui-angular/pull/10147#discussion_r787893908

**Comment by MayaKirova** [comment]
@ChronosSF  @rkaraivanov @dkamburov I've noticed that he base filter/sort strategy also use the grid to get some information from the columns (like dataType or formatter):
https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts#L65
https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts#L134

Does it sound reasonable if we remove the grid reference to store the datatype or the column ref as optional parameter in the Filtering/Sorting expression?

**Comment by ChronosSF** [comment]
Btw, researching if you can sort the string values for Date-s with the same results could be worth doing as this parsing on each data op is certainly slow. There are benefits to the full data binding capabilities of igGrid ;)

**Comment by MayaKirova** [comment]
Regarding 1.

The formatter is not one method for the whole grid. It's per column, so we will need to pass either a separate collection of value extractors or an additional prop for that extractor as part of the SortingExpression/FilteringExpression so that they can be associated by fieldName.
Also if it's something that grid can optionally pass, the logic can no longer be encapsulated in a separate filter strategy, so we will need to deprecate/remove the FormattedValuesFilteringStrategy. Since it's public it will be a breaking change. 
Also, how will the grid decide whether it needs to pass formatters as custom extractors for filtering/sorting? Maybe a new prop?

Regarding 2.

Removing them for filtering and assuming by some arbitrary property of the filtering condition like the condition name or logic function, may also cause some breaking changes. If the user has defined some custom condition for a date/time column he would be getting the related date object right now, if we remove this as a whole and format as date only if it's one of the default date conditions this will no longer be the case.
