### ISSUE TITLE
Igx-Tree - Data property is missing from IgxTreeNodeComponent in nodeSelection event.

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#10921]
## Description  
Data property is missing from IgxTreeNodeComponent in nodeSelection event

 * igniteui-angular version: 13
 * browser: chrome

## Steps to reproduce  

1. Run sample
2. Check output window 

## Result  
IgxTreeNodeComponent doesn't expose Data but it's listed in API

https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtreenodecomponent.html
## Expected result  
IgxTreeNodeComponent exposes Data property

https://stackblitz.com/edit/angular-ex825d-jkzgkp

**Comment by teodosiah** [comment]
@mddifilippo89,  when a tree node is defined setting its data is optional and in the attached sample the tree node data property is not bound, so it's expected to return undefined.
Everything should works as expected if you set the data like follows:
```html
 <igx-tree-node *ngFor="let type of data" [data]="type">
            {{ type.Name }}
            <igx-tree-node *ngFor="let value of type.Children" [data]="value">
                {{ value.Name }}
            </igx-tree-node>
        </igx-tree-node>
```
