### ISSUE TITLE
[Pivot] Remote data with async pipe sample throws error and  horizontal scroll does not work

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#10938]
## Description  
Describe the issue.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open Pivot remote filtering sample from branch mdragnev/pivot-remote
2.  Observe the error

## Result  
An error is thrown ( headerContainer is undefined on afterViewInit)

## Expected result  
There should be no error and horizontal scrolling should work

![image](https://user-images.githubusercontent.com/37667452/152186151-1bf6c80d-1a23-43c6-9e81-8dad353a37fa.png)

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by skrustev** [comment]
Steps to reproduce in master branch:
1. Open the Pivot sample demo
2. Set the pivot data to empty array or set the columns dimensions to an empty array.
