### ISSUE TITLE
[Pivot] Remote data sample breaks the grid layout

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#10939]
## Description  
Describe the issue.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the remote data sample in dev samples of branch mdragnev/pivot-remote
2. Observe the grid layout

## Result  
The grid layout at the bottom is broken.

## Expected result  
The layout should be okay

## Attachments  
![image](https://user-images.githubusercontent.com/37667452/152186524-b8208635-32e6-47fb-b895-d8f1a7b5a61e.png)

**Comment by MayaKirova** [comment]
Might be similar to https://github.com/IgniteUI/igniteui-angular/issues/10945
