### ISSUE TITLE
SimpleCombo with NULL values throws an error.

### ISSUE THREAD

**Issue by gazoonie** [IgniteUI/igniteui-angular#10952]
## Description  
If the data source for a SimpleCombo contains a item that has NULL values, an error is thrown.

We have a use case where we need to have an empty row in a dropdown.

Also, if I change the NULLs to empty strings `''` a different error is thrown.

 * igniteui-angular version: 13.0.0
 * browser: Chrome

## Steps to reproduce  

1. Open this [Stackblitz ](https://stackblitz.com/edit/angular-clv3ul?devtoolsheight=33&file=src/app/simple-combo-styling/simple-combo-styling.component.html)(forked from Ignite demo)
2. Open the second combo.
3. Notice the dropdown doesn't open and there is an error in the console.

## Result  
What is the actual result after following the steps to reproduce?

Dropdown doesn't open and there is an error in the console.

## Expected result  
What is the expected result after following the steps to reproduce?

Drop down opens and has an empty row.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
https://stackblitz.com/edit/angular-clv3ul?devtoolsheight=33&file=src/app/simple-combo-styling/simple-combo-styling.component.html

**Comment by mikerentmeister** [comment]
@Lipata 
This is a big headache for my team that we can't have a empty option for this control. Is anyone going to take a look at this soon?

**Comment by Lipata** [comment]
We have planned that for our next sprint - next week.

**Comment by kdinev** [comment]
@mikerentmeister Since I'm working an on issue that came in as a regression from the fix for this issue, I have a question. Do you use `null` for the item value, or `''`? I can make the `''` work just fine, but `null` and `undefined` are a lot of trouble to differentiate from selection reset.

**Comment by kdinev** [comment]
And that's for `igx-simple-combo` not `igx-combo`, right? Would it be a problem if empty string is used instead of null?
