### ISSUE TITLE
igx-grid rowSelectionChanging isSelectAll flag

### ISSUE THREAD

**Issue by mikerentmeister** [IgniteUI/igniteui-angular#10961]
This is probably both a bug and feature request, because the igx-grid "select all" checkbox doesn't play nice with remote data sources

## Is your feature request related to a problem? Please describe.
I am working on building an igx-grid with a remote data source (pretty much exactly like the examples, no paginator, but virtually scrolled), but I'm also adding row selections to the grid. One thing that I've noticed is that when you click the "select all" checkbox, it will only select the rows that the grid knows about at the time (whatever is loaded for the "page"). 

## Describe the solution you'd like
The ability to know if the "select all" checkbox was clicked in the `rowSelectionChanging` event, and add the ability to handle the event _asynchronously_ (promise/observable) to get the row keys of all items.

## Describe alternatives you've considered
I have a work around by looking at the event's `currentTarget`, and seeing if it's the select all checkbox, but it would be nice to not have to do that just in case it changes in the future.

## Additional context
My page size is 50, as you can see the grid thinks that all items are selected, but when I scroll down to load the other items, it's obviously not selected, because the grid knew nothing about that record other than it existing based on the `totalItemCount`

![image](https://user-images.githubusercontent.com/18708788/152853704-9d2df6f0-66f8-404f-b84e-d2c4de3d9d9a.png)

**Comment by ChronosSF** [comment]
Hey @mikerentmeister ,

You don't need to handle the event asynchronously. As long as you know that the header checkbox is clicked (which I agree should be more obvious), you can get your rowIds and directly set them in the selection service of the grid. It will also be more responsive to the end-user to allow the grid to select the visible ones and add the rest under the hood instead of waiting for the response for the initial click.

```typescript
rowIds.foreach(rowID => this.grid.selectionService.rowSelection.add(rowID));
```

Not sure how much the private flag allRowsSelected affects the scenario though.  @hanastasov  and his team may be able to comment futher.

**Comment by kdinev** [comment]
@mikerentmeister Could you comment on whether @ChronosSF's suggestion works for you, or you still need the flag in the event arguments?

**Comment by mikerentmeister** [comment]
Yes, his suggestions should work for us

**Comment by kdinev** [comment]
In this case, I'm closing the issue :)

**Comment by mikerentmeister** [comment]
@kdinev
Apologies, I think I misunderstood your question. We still need some way of knowing whether the select all box was clicked, whether that's through a flag on the event, or a separate `EventEmitter` entirely. I meant that his suggestion would work for us in terms of loading our selected keys after selecting the visible ones, but his suggestion still relies on more work to be done on your side to let us know about the select all. Especially with the `allRowsSelected` flag he mentioned.

**Comment by kdinev** [comment]
@mikerentmeister Understood! Reopening :)

**Comment by kdinev** [comment]
@hanastasov Can you prioritize this bug into the current sprint?

**Comment by hanastasov** [comment]
> @hanastasov Can you prioritize this bug into the current sprint?

Yep, we're on it!
