### ISSUE TITLE
When filter and edit the column that is filtered by the value persists onto the row below

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#1096]
### Description  
When filter and edit the column that is filtered by through (updateCell) method from grid component the value persists onto the next row when changeDetection triggers and filtering is applied again.

### Steps to reproduce  

1. Open the sample for grid-summaries
2. Filter by "ReorderLevel" column
3. Click "update cell" button under the grid.

### Result  
The value that cell is updated persists into the row below.

### Expected result  
The updated value should not remain onto the row below.

**Comment by zdrawku** [comment]
We are currently adding a unit test for the fix
