### ISSUE TITLE
[Pivot] Having no rows specified on init breaks the layout

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#10975]
## Description  

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open pivot sample
2. Remove all rows from configuration
3. Observe

## Result  
The header row layout breaks

## Expected result  
Should not break

## Attachments  
![image](https://user-images.githubusercontent.com/37667452/153171689-ac0535ac-29a2-40b2-adf9-895dceef58da.png)

**Comment by MayaKirova** [comment]
@mddragnev I can't seem to reproduce this in master. Perhaps it's already fixed?

**Comment by mddragnev** [comment]
> @mddragnev I can't seem to reproduce this in master. Perhaps it's already fixed?

Yes, indeed it is not reproducible anymore
