### ISSUE TITLE
Horizontal scroll doesn't work for igx-grid in RTL mode

### ISSUE THREAD

**Issue by feliksmatsko** [IgniteUI/igniteui-angular#10987]
## Description  
Horizontal scrolling doesn't work for the grid component in the right-to-left mode. In fact, the scroll bar is moving but the grid itself remains freezing.

 * igniteui-angular version: 13.0.8
 * browser: 

## Steps to reproduce  

1. Create layout with igx-grid component
2. Add as many columns to see horizontal scroll bar
3. Add dir="rtl" attribute to the body tag
4. Try to move scroll bar right or left

## Result  
Grid content remains freezing

## Expected result
Grid content scrolled together with scroll bar

## Attachments  
[igx-grid rtl scroll issue.mp4.zip](https://github.com/IgniteUI/igniteui-angular/files/8039641/igx-grid.rtl.scroll.issue.mp4.zip)

**Comment by viktorkombov** [comment]
This problem is already addressed in issue https://github.com/IgniteUI/igniteui-angular/issues/10869.
