### ISSUE TITLE
Igx-grid infinite scroll does not select correct value

### ISSUE THREAD

**Issue by PhuQuy** [IgniteUI/igniteui-angular#10988]
## Description  
Describe the issue.

 * igniteui-angular version: > 12.3.10
 * browser: 

## Steps to reproduce  

1. Scroll to second page
2. Scroll up/down few times, click on the row and log out row data

## Result  
What is the actual result after following the steps to reproduce?
The row data did not match with the row display in the grid

## Expected result  
What is the expected result after following the steps to reproduce?
The row data should match with the row display in the grid

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/17820409/153383860-df7bb4d2-2e12-4618-82e8-72bacaf87acf.png)

https://stackblitz.com/edit/angular-q1rtju?file=src%2Fapp%2Fgrid%2Fgrid-sample-5%2Fgrid-sample-5.component.ts

**Comment by ChronosSF** [comment]
@PhuQuy , this seems harder to reproduce than what the Steps to Reproduce suggest. Do you have any other hints on how I can get it to break on my side? I am using the stackblitz link. I tried with both the 13.0.0 version that was set as a dependency and with the newest 13.0.11.

**Comment by PhuQuy** [comment]
hi @ChronosSF I'm using version 12.3.10 now. I'm not sure if 13.0.0 can fix my issues. For now I just customize the allRows functions to make it work:
![image](https://user-images.githubusercontent.com/17820409/156126435-b30f6d6a-2e3f-490c-bbe4-34eb0e55710b.png)
