### ISSUE TITLE
Moving column dimension to row when using noop column strategy would throw an error

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#11008]
## Description  
When moving a column dimension chip to the row dimensions section, a grid that has a noop column strategy configuration would throw an error `Unknown property 'width' of undefined`.

 * igniteui-angular version: next
 * browser: 

## Steps to reproduce  

1. Set the configuration to a grid like the one here: #10984
2. Open the sample and the browser console
3. Try to move the Countries chip to the row dimensions
4. Observe the thrown error

Important is to have the columnStrategy to an instance of `NoopPivotDimensionsStrategy`.

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by dkamburov** [comment]
@3phase should we close that one?
