### ISSUE TITLE
Enable scrolling to Grid Data rows/cells not present in DOM (because of virtualization)

### ISSUE THREAD

**Issue by Poseclop** [IgniteUI/igniteui-angular#11028]
## Is your feature request related to a problem? Please describe.
On a data Grid, I want to be able to scroll automatically to a row/cell that is currently not shown in DOM. I would usually do something like:
```
const row = this.grid.getRowByKey(key)
row.cells.first.focus()
```
This is no longer working though, as we have virtualization and the row will not be found if it's not present in the DOM thus not included in the grid rowList.

## Describe the solution you'd like
Ideally the exact same API but just "fix" it to work with virtualization.

## Describe alternatives you've considered
A less ideal option would be an option to opt out of virtualization.

## Additional context
I'm unsure if this is supposed to be resolved with [#8668](https://github.com/IgniteUI/igniteui-angular/issues/8668) or if there is already an existing solution answered to that problem but I couldn't find anything in the documentation.

**Comment by ChronosSF** [comment]
Hey @Poseclop , 

I think this method is what you are looking for - https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#navigateTo

**Comment by Poseclop** [comment]
Thanks that does the trick. I think what got me suprised in the first place is that grid.getRowByKey(key) would not return anything. I fixed like this:
```
for (let i = 0; i < this.grid.filteredSortedData.length; i++) {
    if (this.grid.filteredSortedData[i].id === mykey) {
        this.grid.navigateTo(i);
        break;
    }
}
```
Might be just a matter of pointing out in doc that getRowByKey() method is affected by virtualization. Other than that all good so I close the issue.
