### ISSUE TITLE
Excel Style Filtering on dateTime columns not applied properly

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#11060]
## Description  
When having multiple grids in the application, excel style filtering is **not applied properly on DateTime column** if the **first grid has a Date column**, and the **second has a DateTime column**.

As demonstrated in the below attachment, when selecting any DateTime value for which there are other entries on the same date, multiple records are displayed, but only one matches the selected DateTime (left side). 

However, when the grid with the DateTime column **is above** the one with the Date column, the correct record is displayed. (right side)

![excel-filtering-demo](https://user-images.githubusercontent.com/49126110/154983101-1b6bfbb0-a49f-406c-8b1f-3c6356b2a0e2.gif)

<hr>

The same is true when the Date column **is before** the DateTime column in a **single grid**:

![excel-filtering-demo2](https://user-images.githubusercontent.com/49126110/154984131-09ba7077-8200-4ad8-b417-8e1ff52d275e.gif)
 

 * igniteui-angular version: 13.0.x, 12.3.x
 * browser: all

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/angular-xf26na-37bjuu?file=src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.html) StackBlitz sample.
2. Filter the Order Date column in the second grid by selecting the first value (Mar 17, 2001, 10:20:37 AM)

## Result  
Multiple records for **Mar 17, 2001** are displayed.

## Expected result  
Only one record should be displayed.

**Comment by m4yorga** [comment]
Hello @RivaIvanova , @DiyanDimitrov , is there any update about this issue?

Thanks.
