### ISSUE TITLE
Cannot open Excel Style Filtering panel on DateTime columns

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#11061]
## Description  

When trying to open the filter panel of a **DateTime column** when Chrome's language is set to **Spanish** a "RangeError: Invalid time value" error is thrown. 
As demonstrated in the attachment below, if the date record is changed from e.g. 2021-10-**13** to 2021-10-**12**, the panel opens successfully, but the date in the grid is **Oct 12, 2021** while the date in the panel is **Dec 12, 2021**.

 * igniteui-angular version: 13.0.x, 12.3.x
 * browser: Chrome

## Steps to reproduce  

1. Use Google Chrome
2. Change the language used to display the Google Chrome UI to Spanish (Latin America) and restart the browser
3. Go to this stackblitz [Grid Filter Issue Browser Regional Settings - StackBlitz](https://stackblitz.com/edit/github-hwzhn1-iupnxp?file=src%2Fassets%2Fdata.json,src%2Fapp%2Fapp.component.html)
4. Click on the icon to open the filtering panel of the Start Time column
5. Filtering panel is not opened, there's an exception logged in the Console saying "Invalid time value"

## Result  
Excel Style Filtering panel is not opened and a **RangeError: Invalid time value** error is thrown.

## Expected result  
The panel should be opened without any errors.

## Attachments  
![excel-panel](https://user-images.githubusercontent.com/49126110/154993172-0577d4fc-59ba-412e-8416-9cb63af25337.gif)

**Comment by m4yorga** [comment]
Hello @RivaIvanova , @DiyanDimitrov , is there any update about this issue?

**Comment by m4yorga** [comment]
Hello @RivaIvanova , @DiyanDimitrov, @igdmdimitrov , @kdinev , is there any update about this issue?

**Comment by ChronosSF** [comment]
@m4yorga , I can't reproduce the issue with the latest 13.1 version . Can you try it as well?

I can still reproduce it with 12.3 so we'll try to fix it but there is no need for you to wait if you app is already using Angular 13
