### ISSUE TITLE
<igx-grid> Inline editable combobox input field must have an accessible name

### ISSUE THREAD

**Issue by GibletJr** [IgniteUI/igniteui-angular#11077]
## Description  
When entering edit mode for a cell that utilizes a combobox/drop-down, FastPass generates a "**aria-input-field-name**: Ensures every ARIA input field has an accessible name" alert.

## Steps to reproduce  

1. Navigate to https://www.infragistics.com/angular-demos/grid/grid-editing
2. Trigger Edit Mode by double-clicking within a cell in the Available At column
3. Click on down arrow to open options list
4. Run FastPass analysis

## Result  
**Path**
#igx-drop-down-2
**Snippet**
<div role="listbox" class="igx-combo__content" tabindex="0" id="igx-drop-down-2" style="overflow: hidden; max-height: 400px;">
**How to fix**
Fix ONE of the following:
aria-label attribute does not exist or is empty
aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
Element has no title attribute

## Expected result  
No Alerts

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![FastPass - Accessible Name Alert Screenshot](https://user-images.githubusercontent.com/56270402/155244289-1433d668-34b0-4875-bdc8-88fc09ff3268.jpg)

**Comment by GibletJr** [comment]
@Lipata - do you have an ETA on when this bug will be resolved?

**Comment by Lipata** [comment]
@GibletJr thank you for the suggestions. We will consider them and will write you about how and when we can proceed.

**Comment by GibletJr** [comment]
@Lipata Checking back in on ETA.

**Comment by PlamenaMiteva** [comment]
Hi, @GibletJr 
We have found a solution and will fix the issue with the combo's dropdown aria label. However, since there are some other issues around combo's aria, which will also be fixed, it will take some time to fully complete and test it.
