### ISSUE TITLE
<igx-grid> Ability to disable default behavior of click selecting a row

### ISSUE THREAD

**Issue by GibletJr** [IgniteUI/igniteui-angular#11078]
## Is your feature request related to a problem? Please describe.
When displaying an editable grid, users can click on a cell to trigger edit mode; however, by clicking they are also triggering the default selection behavior.  This inadvertently, deselects all other selections and makes the current row the only selection.

## Describe the solution you'd like
Would like the ability to disable this default behavior and only support clicking on the row checkbox selector as a way to select a row using a click event.

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by kdinev** [comment]
@GibletJr Currently this is not possible. However, we can reconsider the behavior when we have `rowSelection="multiple" cellSelection="none"` to not trigger the row selection from any cell in the grid, but only from the row selector area/checkbox.
