### ISSUE TITLE
igxMask directive doesn't work with input[type="number"].

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1108]
### Description  
igxMask directive doesn't work with input[type="number"].

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-editors-issue
2. Open console panel.
3. Focus a number input.
4. Type any characters in it

### Result  
1. `promptChar` doesn't work.

4. Errors occur.
> ERROR
Error: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
Error: Converting circular structure to JSON

### Expected result  
igxMask directive should work with input[type="number"].

**Comment by bkulov** [comment]
igxMask directive is meant to work only with input[type="string"]. It's possible that it will work correctly with other input types but we don't guarantee that. 
We will document this limitation.

**Comment by tkiryu** [comment]
@SAndreeva @bkulov thank you for explaining. I understand.

I am able to see the limitation in the following document.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/mask.html
> igxMask directive is used on an input of type text. To get started with the Ignite UI for Angular Mask directive, let's first import the IgxMaskModule and IgxInputGroupModule in our app.module.ts file.

But what about README.md?

**Comment by SAndreeva** [comment]
I have updated the README.md file accordingly. Thanks!

**Comment by tkiryu** [comment]
@SAndreeva thank you!
