### ISSUE TITLE
<igx-simple-combo> Selection lost on blur

### ISSUE THREAD

**Issue by gazoonie** [IgniteUI/igniteui-angular#11111]
## Description  
Selection is lost when leaving the combo box
I can repro the issue in the demo.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/simple-combo#two-way-binding

 * igniteui-angular version: 13.0.12-13.0.13
 * browser: Chrome

## Steps to reproduce  

1. Go to the [Ignite Demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/simple-combo#two-way-binding)
2. If not already at the Two-Way Binding demo, scroll to it.
3. Open the dropdown and select an item.
4. Click outside the dropdown
5. See the selected value get cleared

## Result  
Selection not retained

## Expected result  
Selection is retained.

## Attachments  
[Ignite Demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/simple-combo#two-way-binding)

**Comment by mikerentmeister** [comment]
I am experiencing this issue as well after moving from 13.0.11 to 13.0.13

**Comment by mikerentmeister** [comment]
@jackofdiamond5 and @dkamburov - This is still happening in 13.1.7, and is still happening in this demo: https://www.infragistics.com/products/ignite-ui-angular/angular/components/simple-combo#two-way-binding

**Comment by mikerentmeister** [comment]
Please reopen this issue

**Comment by grosch-intl** [comment]
@mikerentmeister  This has worked fine for me since 13.1.5.  I just upgraded to 13.1.7 and it's still working properly.

**Comment by jackofdiamond5** [comment]
@grosch-intl I just tested it and there is a small issue with two-way binding where after the app has fired up, if you have an initial value in the combo and you focus/blur then it clears. I believe this is what @mikerentmeister is talking about - and thank you for pointing it out, it seems like we've missed it during testing so I'll create PRs for it shortly. :)
