### ISSUE TITLE
Icon button color in Fluent Theme

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#11129]
## Is your feature request related to a problem? Please describe.
Icon button hover color resolves to hsla(var(--igx-grays-800) in Fluent Theme and when observing, there is no visible change for the color on hover.

## Describe the solution you'd like
Icon button hover color resolves to  (--igc-primary-500) in WC. The color is applied on hover.

**Comment by didimmova** [comment]
@desig9stein will [your issue](https://github.com/IgniteUI/igniteui-webcomponents/issues/270) fix this one?

**Comment by didimmova** [comment]
@simeonoff shall we close this issue then?

**Comment by desig9stein** [comment]
> @simeonoff shall we close this issue then?

Don't, I will close it after my PRs for the fluent buttons are closed, I will  put a reference to all issues related to fluent buttons in the PRs

**Comment by simeonoff** [comment]
Fixed in https://github.com/IgniteUI/igniteui-angular/pull/11265
