### ISSUE TITLE
Button color in Fluent Theme

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#11120]
## Is your feature request related to a problem? Please describe.
Button hover color resolves to hsla(var(--igx-grays-800) in Fluent Theme and when observing, there is no visible change for the color on hover.

## Describe the solution you'd like
Button hover color resolves to hsla(var(--igc-gray-900) in WC. The color is applied on hover.

**Comment by IvayloG** [comment]
It is related to the icon buttons and what I am looking at is a card with several of these icon buttons. This is the result in Angular and it differs from the same case for WC.
![image](https://user-images.githubusercontent.com/4296944/158404079-51109a59-566b-4822-8175-f48607d8823b.png)

If more details are needed, I have reproduced this with a Light Fluent Theme, using different primary and secondary colors as  $primary: #d49f01,  $secondary: #987303

**Comment by desig9stein** [comment]
@didimmova My PRs will fix this one as well

**Comment by simeonoff** [comment]
Fixed in https://github.com/IgniteUI/igniteui-angular/pull/11265
