### ISSUE TITLE
Switch in Fluent Theme

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#11130]
## Is your feature request related to a problem? Please describe.
The Switch does not have defined style for hover state when the Switch is on/selected.

## Describe the solution you'd like
The on/selected Switch has a different background color when hovered.

**Comment by StefanIvanov** [comment]
@IvayloG the design in WC is not correct, if you look at the [fluent UI toggle](https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle) you will notice that angular implementation is more accurate when it comes to styles, this issue should be transferred to the WC as a visual bug IMO @didimmova @simeonoff

**Comment by didimmova** [comment]
Maybe there should be 2 separate issues then? One for the selected hover state in igniteui-anuglar, because there aren't any styles for it there. And one for the web components for the things that don't match there?

**Comment by simeonoff** [comment]
@IvayloG

**Comment by IvayloG** [comment]
Sure, please go ahead and fix as per your suggestion in angular plus transferring the update in web components later on.

**Comment by StefanIvanov** [comment]
@didimmova I am changing this issue to be for the selected hover state in igniteui-anuglar styles and leave it to you to create a separate issue for WC switch styles
