### ISSUE TITLE
Modifying the filter of the second filtered column causes an exception

### ISSUE THREAD

**Issue by onlyexeption** [IgniteUI/igniteui-angular#11134]
## Description  
An exception is thrown when modifying the filter of the non-first filtered column.

 * igniteui-angular version: 
 * browser: n/a

## Steps to reproduce  

1. Open [Formatted Values Filtering Strategy Sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/excel-style-filtering#formatted-values-filtering-strategy)
2. Filter by any column different than Unit Price Category
3. Open Unit Price Category and filter by any value
4. Open Unit Price Category and filter again by another value 

## Result  
An exception is thrown in the console.

## Expected result  
Column should be filtered normally.

## Attachments  
![image](https://user-images.githubusercontent.com/19392175/156176670-389f9c0c-44d4-40ce-99a5-2e5ce0847046.png)

**Comment by DiyanDimitrov** [comment]
During fixing this issue I have also found another one:

1. Filter by any column different than Unit Price Category.
2. Open Unit Price Category and filter by any value.
3. Modify the filter of the first column that you have filtered.

Result:
The filter of the Unit Price Category column is lost.

Expected:
The filter of the Unit Price Category column should be preserved.
