### ISSUE TITLE
Fluent inputs styles.

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#11145]
* igniteui-angular version: 
 * browser: all

- [X]  Focus styles
- [x]  Disabled styles
- [x]  Caret color
- [x] The idle and filled state border color

**Comment by StefanIvanov** [comment]
I also noticed we need to fix the disabled styles to match Fluent UI design language, please use the following designs https://share.goabstract.com/27db5a15-0a3d-456f-8a08-fda743566537
