### ISSUE TITLE
IgxDataChart – fillScale setting does not work with series highlighting for a bubble series.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#11157]
## Description  
fillScale setting does not work with series highlighting for a bubble series.

 * igniteui-angular version: 
  igniteui-angular-charts: 13.1.0
 * browser: 
Chrome

## Steps to reproduce  

Run the sample:
https://stackblitz.com/edit/angular-fhlagu-mpstep?file=src/app/scatter-bubble-chart-single-source/data-chart-scatter-bubble-chart-single-source.component.html

## Result  
fillScale setting is ignored.

## Expected result  
fillScale setting should be applied.

**Comment by mddifilippo89** [comment]
Logged TFS 273867
