### ISSUE TITLE
Row editing with custom clone strategy and nested data source is broken

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular#11165]
## Description  
When you have a grid with nested data with the following data structure:
```typescript
{ pk: ..., nesteProp: { prop1: ..., prop2: ..., etc. } }
```
and you enter row edit mode with a custom clone strategy, changes to cells bound to nested properties are
not correctly reflected.

 * igniteui-angular version: 12.x+
 * browser: all

## Steps to reproduce  

1. Enter into row edit mode on a cell bound to nested property.
2. Make a change, and commit it (by Tabbing for example) to another cell.
3. Press Escape to cancel the transaction

## Result  
The transaction is canceled, but the value is committed nonetheless. 

## Expected result  
The value should be reverted to the original state.

**Comment by wnvko** [comment]
`DefaultDataCloneStrategy` does not support such complex scenario. However, you can change the default strategy and provide custom one. For example, to handle nested data you can use this:
```
class CustomCloneStrategy implements IDataCloneStrategy {
    public clone(data: any) {
        return this.deepCopy(data);
    }

    private deepCopy(data: any): any {
        if (Array.isArray(data)) {
            return data.map(item => this.deepCopy(item));
        }
        if (data instanceof Date) {
            return new Date(data.getTime());
        }
        if (data && typeof data === 'object') {
            return Object.getOwnPropertyNames(data).reduce((o, prop) => {
                Object.defineProperty(o, prop, Object.getOwnPropertyDescriptor(data, prop)!);
                o[prop] = this.deepCopy((data as { [kye: string]: any })[prop]);
                return o;
            }, Object.create(Object.getPrototypeOf(data)));
        }
        return data;
    }
}
```
_Note: if this implementation of IDataCloneStrategy does not solve your issue feel free to change it or to use your own implementation_
