### ISSUE TITLE
igx-tabs if direction changes to RTL at runtime, the tab highlight remains on the left

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#11173]
## Description  
I'm adding a `dir="rtl"` attribute to my document body at runtime and the tab direction changes, but the highlight remains on the left.

 * igniteui-angular version: 13.1.0
 * browser: all

## Steps to reproduce  

1. Add a tab to an angular view
2. Change document direction at runtime

## Result  
Tab direction switched, but highlight remains at all position.

## Expected result  
The highlight should also move.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/156772796-cac8aa39-c867-4d9a-90ce-2c64f24deeee.png)

**Comment by simeonoff** [comment]
You need to change the CSS stylesheet with one that supports RTL. It's a separate file that we ship.

**Comment by kdinev** [comment]
@simeonoff This is from the samples and everything aligns properly if I change a tab afterwards. Just the initial switch doesn't move the underline.

**Comment by kdinev** [comment]
@simeonoff @desig9stein If the fix requires significant change in the component, then I would rather have it as `not-to-fix`.

**Comment by desig9stein** [comment]
> @simeonoff @desig9stein If the fix requires significant change in the component, then I would rather have it as `not-to-fix`.

@kdinev If you are asking if it will be a simple fix through the SCSS, the answer is no, it won't. The indicator position is calculated through typescript. It will require refactoring inside the component.

**Comment by kdinev** [comment]
@desig9stein I'm closing this as `not-to-fix` then.
