### ISSUE TITLE
Update add row programmatically

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#11196]
## Question  
I want to give my user the ability to add rows to grid with some pre-populated data in some of the cells. 

After I invoke this line:
```
this.grid.beginAddRowById('ALFKI');  // spawns the add row UI under the row with PK 'ALFKI'
```
How can I then programmatically pre-populate some of the cells? Unfortunately, `beginAddRowById` appears to return void. I would do something like this: 
```
// Directly using the row `update` method
const row = this.grid.getRowByKey(rowID);
row.update(newData);
```
but I don't know what the rowID is ... thanks!

**Comment by SkylerLutz** [comment]
@viktorkombov @teodosiah following up -- thanks!

**Comment by viktorkombov** [comment]
Hello @SkylerLutz,

I have created a small [sample ](https://stackblitz.com/edit/angular-4expch-nifq4b?file=src%2Fapp%2Fgrid%2Fgrid-paging-sample%2Fgrid-paging-sample.component.ts)demontrating how to add a row with pre-populated data using the [updateCell ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#updateCell)method of IgxGrid while handling the [rowEditEnter ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#rowEditEnter)event:

```html
<igx-grid [data]="data" primaryKey="Id" [rowEditable]="true" (rowEditEnter)="onRowAdd($event)">
  <igx-grid-toolbar>
    <button igxButton="raised" (click)="addNewRow()">
      ADD NEW ROW
    </button>
  </igx-grid-toolbar>
  ...
</igx-grid>
```

```typescript
public addNewRow(): void {
  this.grid.beginAddRowById(84);
}

public onRowAdd(args: IGridEditEventArgs): void {
  if (args.isAddRow) {
    const rowID = args.rowID;
    this.grid.updateCell(120, rowID, 'BeatsPerMinute');
  }
}
```


Please test the sample on your side and let me know whether you find it helpful.
