### ISSUE TITLE
Update switch styles for Fluent theme

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#11201]
The enabled switch when on should use primary 500 for the track instead of secondary 500

The enabled switch when off should use gray 700 for the thumb instead of 900
The enabled switch when off should use gray 700 for the track border instead of 500

The disabled switch when on should use gray 100 for the thumb instead of 400
The disabled switch when on should use gray 400 without opacity for the track border and fill instead of 300 variations it currently has

The disabled switch when off should use gray 400 for the track border and have NO fill instead of 300 variations it currently has

**Comment by didimmova** [comment]
@StefanIvanov the solution is in [this PR](https://github.com/IgniteUI/igniteui-angular/pull/11207/files), which is targeting the 13.1.x branch.
