### ISSUE TITLE
Buttons' height in Indigo theme

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/igniteui-angular#11233]
| Type | Comfortable  | Cosy   | Compact  | 
|---|---|---|---|
| Flat | 36px  | 32px  | 28px  |  
| Outlined | 36px  | 32px  | 28px  |  
| Contained | 36px  | 32px  | 28px  |  
| Icon | 36x36px  | 32x32px  | 28x28px  |  
| FAB | 48px  | 42px  | 36px  |

**Comment by simeonoff** [comment]
@YoannaIvanova This doesn't make much sense at all. Setting the height of the button to be 28px in comfortable will actually make it smaller than the cozy variant of the button and only 2px larger than the compact size.

It would be better to have a table that specifies the sizes of the indigo buttons(icon and regular) in all densities;
| Comfortable  | Cosy   | Compact  | 
|---|---|---|
| 36px  | 32px  | 28px  |
