### ISSUE TITLE
Buttons' height in Bootstrap theme

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/igniteui-angular#11231]
Type | Comfortable | Cosy | Compact
-- | -- | -- | --
Flat | 48px | 38px | 31px
Outlined | 48px | 38px | 31px
Contained | 48px | 38px | 31px
Icon | 48x48px | 38x38px | 31x31px
FAB | 48px | 40px | 31px

**Comment by simeonoff** [comment]
The only issue I see here is that the icon button should be 38px in size in the cozy size. What the default density in the sample is doesn't really matter as long as the sizes are correct by definition in the theme files.

**Comment by YoannaIvanova** [comment]
Here are the bootstrap button sizes:

Comfortable | Cosy | Compact
-- | -- | --
48px | 38px | 31px

**Comment by StefanIvanov** [comment]
@YoannaIvanova can you please update the 32px to 31px
