### ISSUE TITLE
Hierarchical Advanced filter should show the columns of the child grid as well along with that while selecting the column iin advanced filter should auto populate values 

### ISSUE THREAD

**Issue by rajendra227** [IgniteUI/igniteui-angular#11245]
Hierarchical Advanced filter should show the columns of the child grid as well along with that while selecting the column in advanced filter should auto populate values

**Comment by kdinev** [comment]
This currently is only supported via setting filtering conditions first to the parent grid and subsequently to the children through their own instances of the advanced filtering dialog. The scenario is different from the tree grid hierarchical excel-style filter, as the tree grid holds reference to the whole data for each column including the hierarchies, while in a hierarchical grid scenarios, grids hold references to the data related to them. There could also be multiple child tables for each parent record and exposing a reference to all through the top-level grid would be highly un-performant. In addition, if this is implemented in such a way, we would effectively kill the load-on-demand feature for child grids.
