### ISSUE TITLE
igx-simple-combo selected value is cleared when combo loses focus

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#11248]
## Description  
When selecting a value from the simple combo, the value is displayed and focused in the input field, but when clicking somewhere outside the combo in order to lose focus, the value is cleared. However, this behavior is not reproducible every time as it could be observed in the provided attachment.

 * igniteui-angular version: 13.1.x, 12.3.x
 * browser: any

## Steps to reproduce  

1. Open this Ignite UI for Angular [demo](https://www.infragistics.com/angular-demos/lists/simple-combo-styling).
2. Open the simple combo and select a value.
3. Click somewhere outside the combo to lose focus.
4. Perform the above steps a few times as this behavior is reproduced randomly.

## Result  
The selected value is cleared randomly when clicking outside the simple combo.

## Expected result  
The selected value should be displayed the whole time.

## Attachments  
![simple-combo-issue-demo](https://user-images.githubusercontent.com/49126110/158826484-c36a0962-2a3b-4f77-a3f8-ec5594a073a7.gif)

**Comment by Lipata** [comment]
This was already fixed in [igniteui-angular@13.1.5](https://github.com/IgniteUI/igniteui-angular/releases/tag/13.1.5) and now the samples browser is also using it, so the issue should not be reproduced anymore.
