### ISSUE TITLE
Change selected text color in Excel Filter Sort

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#11258]
I am trying to change the color of sort selected text inside the excel filter.

![image](https://user-images.githubusercontent.com/36885861/159257593-56b7ee97-cd8b-47cc-8024-ae03d0f6a2e8.png)

 I've read documentations and I have this:

```
$custom-button-group-theme: igx-button-group-theme(
  $item-selected-text-color: $color_green,
  $item-hover-background: $color_row_hover
);

@include igx-button-group($elcano-button-theme);
```

I've tried igx-button-theme too but it doesn't work. I have another custom themes like igx-checkbox, igx-input-group and all of them work.

 * @infragistics/igniteui-angular: 10.2.38
 * browser: chrome

**Comment by didimmova** [comment]
@ssg127  Check out [this sample](https://stackblitz.com/edit/angular-r7d5ey?file=src/app/grid/grid-formatted-filtering-strategy/grid-formatted-filtering-strategy.component.scss) I made for you. I'm using the latest igniteui-angular version but it should be the same for you, except there's still igx prefix to the mixins and functions in your version. Double-check the variable name of the theme you're making and when you're including it in the mixin.

**Comment by ssg127** [comment]
Thank you @didimmova! I only have a different one that I don't use:

`:host { ::ng-deep {}}`

And in the other cases like igx-checkbox or igx-grid it isn't necessary. Why do I need to use :host altought I load this rules in global styles file?

**Comment by didimmova** [comment]
Check out this topic - [Excel Style Filtering](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#styling). You should import the index file "igniteui-angular/theming", where all the theme functions and component mixins live. And then if the component is using an [Emulated](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/sass/component-themes#view-encapsulation) ViewEncapsulation, it is necessary to penetrate this encapsulation using ::ng-deep

**Comment by ssg127** [comment]
Yes, by default the ViewEncapsulation is set to Emulated and I need to use ng-deep as you said. Now, I have another question, why igx-grid-theme() working then? I don't have ::ng-deep or :host and it's working.

**Comment by didimmova** [comment]
Please check the sample again. It's not working for me without penetrating the encapsulation. If you want, you can edit the sample the way it works for you without using ::ng-deep so I can observe it.
