### ISSUE TITLE
Change filter icon in header

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#11266]
I wan't to change the filter icon in column header.

![image](https://user-images.githubusercontent.com/36885861/159450180-e15844f5-026b-4550-8406-db9377b03aa9.png)

 Reading documentation I found this:
```
    <ng-template igxExcelStyleHeaderIcon>
        <igx-icon>filter_alt</igx-icon>
    </ng-template>
```

But in my version of Ignite it is not available. How could I change the icon?

 * @infragistics/igniteui-angular: 10.2.38
 * browser: chome

**Comment by didimmova** [comment]
This feature is not supported in this version of the product. You need to update to 11.0.0 to use it.
