### ISSUE TITLE
Theme not set directly when using ChangeDetection.OnPush

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#11284]
## Description  
If you use ChangeDetection.OnPush then the theme is not set directly. 

 * igniteui-angular version: 13.1.6
 * browser: Chrome

## Steps to reproduce  
https://stackblitz.com/edit/angular-1jq7zu

## Result  
The default theme is set. If you click on the input then the theme is updated.

## Expected result  
The theme should be set directly.

## Attachments  
![2022-03-25_11h11_19](https://user-images.githubusercontent.com/46870283/160101109-569114b2-7f48-4344-92af-868f0d9a4bca.gif)

**Comment by simeonoff** [comment]
@mikerentmeister We want the theme to be implicitly set by the current CSS stylesheet as it is dependent on properties and style rules defined in the stylesheet for each individual theme. Plus, the input group is a little special as its template structure depends on the loaded theme. This is  why the theme property is only set there. Should the need to specify the theme property in other components occur, we will think of a more robust approach, like a service that tracks the theme for instance.

**Comment by mikerentmeister** [comment]
Please consider reopening this issue
