### ISSUE TITLE
Warnings in the theming engine

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#11288]
## Description  
When building an angular project using igniteui-angular@13.1.0 there are warnings in the theming engine.

 * igniteui-angular version: 13.1.0
 * angular version: 13.3.0

## Steps to reproduce  

1. Unzip the attached sample.
2. npm i
3. npm run build

## Result  
```console
Warning: ▲ [WARNING] Expected identifier but found ":"

    styles.36876be4db3415a1.css:71:18931:
      71 │ ...phy .igx-expansion-panel__body{:var(--igx--);margin:0}.igx-typo...
         ╵                                   ^



Warning: ▲ [WARNING] Expected identifier but found ":"

    styles.36876be4db3415a1.css:71:32079:
      71 │ ...ypography .igx-calendar__label{:var(--igx--)}.igx-typography .i...
         ╵                                   ^



Warning: ▲ [WARNING] Expected identifier but found ":"

    styles.36876be4db3415a1.css:71:38590:
      71 │ ...ypography .igx-calendar__label{:var(--igx--)}.igx-typography .i...
         ╵                                   ^
```

## Expected result  
No warnings

## Attachments  
[cli-proj.zip](https://github.com/IgniteUI/igniteui-angular/files/8351746/cli-proj.zip)

**Comment by lalo-mx** [comment]
[11282](https://github.com/IgniteUI/igniteui-angular/issues/11282) looks like be the same issue
