### ISSUE TITLE
Too small unpinned area

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular#1129]
### Description  
The unpinned area is too small when there are several pinned columns

### Steps to reproduce  

1. Run the demos and then start Grid Column Pinning sample
2. Initially ContactName and ContactTitle columns are pinned. Pin CompanyName, City and Region.
3. Unpin City. Pin Address

### Result  
The result is very small unpinned area which cannot be operated with.

### Expected result  
There should be some unpinned area width limitation I guess as for the igGrid - minimalVisibleAreaWidth. 
![unpinnedareawidth](https://user-images.githubusercontent.com/12935806/39131089-485ef20a-4717-11e8-84b7-ccd9a408cabe.png)

**Comment by ChronosSF** [comment]
@mpavlinov , @tbelcheva the fix is only merged to 5.3 and a new pr is needed for master
