### ISSUE TITLE
Make themes consistent

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#11302]
I noticed that the fluent word palette is not using the correct color #2b579a but uses #0078d4. We decided to introduce a fluent default palette with the #0078d4 and use it for both light and dark schemas, preserving the excel palette and preceding a correct  #2b579a, but having the new one as a default for both light and dark schemas, you can also find all color definitions in [this table](https://infragistics.visualstudio.com/Design-System-Model/_wiki/wikis/Design-System-Model.wiki/562/Palettes)

Please check all other palettes against the table in case I have missed anything when reviewing them.

**Comment by didimmova** [comment]
In the table, the secondary color for the dark material theme is #72da67 but in the product, it's using the same secondary color as the light material theme. Shall we change that to match the table, @StefanIvanov?

**Comment by StefanIvanov** [comment]
Yes, @didimmova the default dark palette for material should be blue and green so the color should be updated IMO

**Comment by RobertLeeuwerink** [comment]
Will the word palette be corrected, so as to show to correct color? @didimmova

**Comment by didimmova** [comment]
> Will the word palette be corrected, so as to show to correct color? @didimmova 

Yes, in this issue we're going to fix the fluent word palette and introduce a default fluent palette as well.
