### ISSUE TITLE
IgxDataChart - ValueOverlay's isAxisAnnotationEnabled=true does not work.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#11316]
## Description  
IgxDataChart - ValueOverlay's isAxisAnnotationEnabled=true does not work.

 * igniteui-angular version: 13.1.x
 * browser: Chrome (Not tested with the other browsers.

## Steps to reproduce  

1. Start the attached reproducible sample.
-> Observe whether the value overlay's axis annotations are displayed.

## Result  
Axis annotations are not displayed.

## Expected result  
Axis annotations are displayed.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[c00223259-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/8386700/c00223259-app1.zip)

**Comment by norikois** [comment]
I logged a bug related to this issue in TFS #273973

**Comment by agoldenbaum** [comment]
It appears that the sample project provided is missing a module. If you include the IgxDataChartAnnotationModule in your app.module.ts, the overlay's annotations show up as expected.

I will include this response in TFS 273973 and mark it closed.

**Comment by norikois** [comment]
Thank you. I confirmed that the axis annotation is displayed by importing IgxDataChartAnnotationModule in the app.module.ts. I closed the TFS item.
