### ISSUE TITLE
Issue with Grid State (re-created from Bug 11139)

### ISSUE THREAD

**Issue by m4yorga** [IgniteUI/igniteui-angular#11327]
## Description  
Dear Ignite,
I am re-creating this issue cause I see [this one was closed](https://github.com/IgniteUI/igniteui-angular/issues/11139) but the issue continues to happen.

We have been using the IgxGridStateDirective to persist and set the last state of the Grid.
I think there's an issue when applying filters, please follow these steps to reproduce:

 * igniteui-angular version: 13.1.6
 * browser: tested in Edge but also happens in Chrome

## Steps to reproduce  

1) Go to [this stackblitz](https://stackblitz.com/edit/angular-k7pshd-9bpgqp)
2) Click the FILTER button, the grid will be properly filtered
3) Click the SAVE STATE button, the state will be saved into browser's local storage
4) Click the LOAD STATE button

## Result  
Grid state is not properly restored

## Expected result  
State of the grid should be able to restore properly including the saved filter expressions.

**Comment by hanastasov** [comment]
Hi @m4yorga , issue is fixed, please expect it released with patch version on Monday, 11th April.

**Comment by m4yorga** [comment]
Awesome, thanks much @hanastasov
