### ISSUE TITLE
Setting grid height to null doesn't result in the grid growing to the size of its elements

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#1132]
### Description  
With the new sizing model, we defined that explicit `height="null"` will result in auto height for the grid, meaning that its height is equal to the sum of all rendered elements, including all rows. Currently the grid doesn't show its rows with explicit `height="null"`.

### Steps to reproduce  

1. Configure a grid `<igx-grid #igxGrid1 [data]="localData" [autoGenerate]="true"></igx-grid>`
2. Define some `localData` with several rows.

### Result  
No grid rows are visible.

### Expected result  
Grid should display its rows.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/39133387-bc5fb450-471c-11e8-9b4c-083a44a8f2b6.png)

**Comment by MayaKirova** [comment]
Already merged to master, probably with this merge PR: https://github.com/IgniteUI/igniteui-angular/pull/1200/commits
