### ISSUE TITLE
IgxGrid: rowClasses not working correcly when using remote paging

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#11331]
## Description  
If you use remote paging then rowClasses are not applied correctly when changing the page.

 * igniteui-angular version: 13.1.7
 * browser: Chrome

## Steps to reproduce  
https://stackblitz.com/edit/angular-3unabz

1.First row is highlighted (ProductName: Chai)
2. Go to next page

## Result  
First row is still highlighted.

## Expected result  
First row should not be highlighted anymore.

## Attachments  
![2022-04-01_14h56_29](https://user-images.githubusercontent.com/46870283/161267915-e5bb5254-94fa-42ed-91ff-7e882b809915.gif)

**Comment by ddincheva** [comment]
This issue is no longer reproducible in the latest version of 13.1.x and master branches
