### ISSUE TITLE
Vertical scrollbar disappears when grid width is in %

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular#1135]
### Description  
Describe the issue.

### Steps to reproduce  

1. Run Grid Column Pinning sample in demos
2. Set grid width to %, for example 50%.

### Result  
There is no vertical scrollbar

### Expected result  
There should be vertical scrollbar

**Comment by ChronosSF** [comment]
This happens in the demos project because of the animating nav-bar. The exposed reflow method may be used to fix the grid's dimensions after the expand animation ends.

**Comment by MayaKirova** [comment]
Closing since it's issue in the demos.
