### ISSUE TITLE
Input text field has border on focus when using fluent light theme

### ISSUE THREAD

**Issue by Svetloslav15** [IgniteUI/igniteui-angular#11352]
## Description  
Create an input field with **fluent light theme**. Focus the element and you will see that there is a border on the input field which was missing in the previous versions.

 * igniteui-angular version: 13.1.8
 * browser: Chrome

## Result  
The input field has border when it is focused.

## Expected result  
The input field shouldn't have border when it it focused.

## Attachments  
![image](https://user-images.githubusercontent.com/33124382/161971491-8abb6955-1b38-4b14-a41a-d6573361b4ec.png)

**Comment by simeonoff** [comment]
@Svetloslav15 This is expected. There was a bug in the previous version of the library where the Fluent theme was missing the border required by design. See https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield. The input should look and behave like the one in the link.
