### ISSUE TITLE
The column pinning icon gets displaced in given scenarios and the horizontal scrollbar disappears.

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#1137]
### Description  
In the Grid Column Pinning demo in the staging samples, in some scenarios the pinning icon gets misplaced and changes the height of the column header. This leads to the horizontal scrollbar being hidden below the grid.

### Steps to reproduce  

1. Open the staging samples
2. Open the Grid Column Pinning demo
3. Pin the Company Name column
4. Scroll to the last column (Fax) and pin it as well.
5. Scroll again and pin the Region column also.

### Result  
The pinning icon gets misplaced, which leads to a change in the height of the header. This pushes the horizontal scrollbar downwards and it gets hidden from the user.

### Expected result  
The icon to be aligned with the text and the horizontal scrollbar to be visible

### Attachments  
![column pinning](https://user-images.githubusercontent.com/18643062/39135128-ee5a3eea-4720-11e8-9eae-6e0bb90682bf.gif)

![sketch1](https://user-images.githubusercontent.com/18643062/39135147-f7983750-4720-11e8-87c8-9062d1871eb9.png)

**Comment by simeonoff** [comment]
@PavlovVasil This should be logged under the [igniteui-angular-samples](https://github.com/IgniteUI/igniteui-angular-samples) repository.
