### ISSUE TITLE
Carousel: Arrow keys do not work consistently for swiping left/right the images.

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#1139]
### Description  
Arrow keys do not work consistently for swiping left/right the images. 

### Steps to reproduce  

1. Open a caroucel sample like: https://staging.infragistics.local/products/ignite-ui-angular/angular/components/carousel.html
2. Try navigating via the keyboard arrows left and right after interacting with the caroucel's image/arrows/navigation (if enabled)

### Result  
**In Chrome:** After clicking on the image, only the first navigation by arrow key swipes the image.
**In Edge/IE:** The images do not swipe no matter where the last user interaction was (click on the image, click on an arrow or the bottom nav)

### Expected result  
Arrow keys navigation should work in all above cases.

**Comment by kdinev** [comment]
@IvayloG Is this reproducible in `5.2.x`?
