### ISSUE TITLE
Columns are not sized correctly when some of them are left without width

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#1143]
### Description  
When I have a Grid with 4 columns and only two of them are having defined width (in percent or pixels) the rest of the columns should fill the whole grid width.

This is when I have width of the Grid set to 100%.

### Steps to reproduce  

1. Open the sample
2. Click on the last cell, first row
3. There is unused space 

### Result  
What is the actual result after following the steps to reproduce?

### Attachments  
![image](https://user-images.githubusercontent.com/11193764/39176991-d72768f6-47b6-11e8-8409-b749191940c5.png)

### Sample

https://stackblitz.com/edit/igx-grid-width-issue?file=app%2Fapp.component.html

### Additional note

When I use the docfx more complex sample, the issue is not present, but I cannot see what is the difference

https://stackblitz.com/angular/xedxrrmbxnx?file=app%2Fgrid%2Fgrid-paging-sample%2Fgrid-paging-sample.component.html

**Comment by zdrawku** [comment]
removing 5.2.x tag because the implementation is different there, width/height defaults are missing

**Comment by MayaKirova** [comment]
Already merged to master, probably with this merge PR: https://github.com/IgniteUI/igniteui-angular/pull/1200/commits
