### ISSUE TITLE
When using igx-input-group, there is no UI feedback after ReactiveForm's markAsTouched is called.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1144]
### Description  
When using igx-input-group, there is no UI feedback after ReactiveForm's `markAsTouched` is called.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-editors-v5-2-1 (using igx-form-group class)
2. Click "SUBMIT" button
3. Go to https://stackblitz.com/edit/igx-editors-issue (using igx-input-group component)
4. Click "SUBMIT" button

### Result  
On the step 4, there is no UI feedback.

### Expected result  
There should be UI feedback.

I used igx-form-group class before and it worked well. I want igx-input-group to work as well.

**Comment by simeonoff** [comment]
@tkiryu sorry, I can't open the samples.

**Comment by DDavidkov** [comment]
@tkiryu I have just committed a fix for this. However, it requires a small change in the sample for it to work properly. Since `markAsTouched` simply sets the form control's touched field to true, we have no way of reacting to it, so you need to call `updateValueAndValidity` after you call `markAsTouched`:
```typescript
if (!this.form.valid) {
      for (let key in this.form.controls) {
        this.form.controls[key].markAsTouched();
        this.form.controls[key].updateValueAndValidity();
      }
}
```
Note, that it used to work previously as we had a style that was applied when angular adds ng-touched to the component's classlist, but this is no longer the case.

**Comment by tkiryu** [comment]
@DDavidkov , thank you for the updates.

I understand why we need to call `updateValueAndValidity`. 
https://github.com/IgniteUI/igniteui-angular/commit/d56386b8cc310e9ba6a140aec0637847699dc083#diff-6f41a12bd84d5e6d3bad3cad109e10c3R125


> Note, that it used to work previously as we had a style that was applied when angular adds ng-touched to the component's classlist, but this is no longer the case.

I'm a little concerned. For example, when just focusing in/out an input, `Reactive Forms` adds `ng-touched` class but doesn't emit `statusChanges`. So I guess `IgxInput` cannot know whether the input has been touched or not.

**Comment by DDavidkov** [comment]
@tkiryu, yes what you just explained is essentially the issue here and why we need to call `updateValueAndValidity`

**Comment by tkiryu** [comment]
@DDavidkov What I was concerned about was resolved by your additional commit. Thank you so much!
https://github.com/IgniteUI/igniteui-angular/commit/b0cf011dd5b66bd994c1436b6ac7de054e3d7897#diff-6f41a12bd84d5e6d3bad3cad109e10c3R81

**Comment by kdawg1406** [comment]
Has this required workaround been put in public docs?

@kdinev

**Comment by kdinev** [comment]
@kdawg1406 It's not yet in the docs, but it's on the TODO list.

**Comment by kdawg1406** [comment]
@tkiryu do you have a working project you can share?

**Comment by kdawg1406** [comment]
@tkiryu  the above workaround is no longer required.  This sample shows the new ways to work with ReactiveForms and radio buttons.

https://stackblitz.com/angular/xlodgdreenr?file=app%2Fradio-group-sample%2Fradio-group-sample.component.ts

**Comment by tkiryu** [comment]
@kdawg1406 if the initial value of `fullName` is blank, `igx-input-group` doesn't get any UI feedback after clicking `Submit` button.

https://stackblitz.com/edit/angular-t9inrw

So I think we still need to call `updateValueAndValidity`, though...

Could you tell me your thoughts on this?


By the way, here is my sample using `updateValueAndValidity`.
https://stackblitz.com/edit/igx-editors-issue
