### ISSUE TITLE
Square elements when using light-theme or dark-theme

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular#11445]
## Description  
When changing theme to light-theme (or dark-theme) in the styles.css files the roundness of some elements is lost.
![image](https://user-images.githubusercontent.com/9549439/164178897-0bd2bd25-1949-4a9b-b4fa-0c9c62f6322c.png)
Adding `$roundness: 1`  seems to fix the issue:
`@include light-theme($light-material-palette, $roundness: 1);`

## Steps to reproduce  

1. Start the attached sample and navigate to the FintechGrid.
2. Examine the slider and the checkboxes.

## Result  
The elements don't have roundness.

## Expected result  
The elements should be a bit round.

## Attachments  

[test001.zip](https://github.com/IgniteUI/igniteui-angular/files/8519463/test001.zip)

**Comment by simeonoff** [comment]
version?

**Comment by valadzhov** [comment]
Resolved in #11447 and #11448
