### ISSUE TITLE
The name of interfaces used in grid.dataView

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11467]
## Question  
I am working with igx-grid dataView. 
There I see the following 
![image](https://user-images.githubusercontent.com/79090369/165274366-b34f5b04-486f-4413-bece-b2186555ba33.png)

I was wondering if there is an Interface for the Expression and Summaries object?

Also if there are other type of objects which might be present in dataView, I would like to know about that as well. 

Thanks.

 * igniteui-angular version: 13.1.8
 * browser:

**Comment by ChronosSF** [comment]
For igxGrid these are the three type of records that can appear in the data view besides data ones:

- If you have grouping, the record in the data view for group rows implements the interface `IGroupByRecord`
- Summary row records implement the interface `ISummaryRecord`
- In master-details grids, each detail's view is wrapped in a row that has a corresponding record that doesn't have an exposed interface but can be recognized by having a single property called `detailsData`

**Comment by KaushikEDS** [comment]
Got it thanks @ChronosSF.
