### ISSUE TITLE
IgxTreeGrid – Indentation is reset to the highest level at 27th level.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#11478]
## Description  
IgxTreeGrid – Indentation is reset to the highest level at 27th level.

 * igniteui-angular version: 13.1.12
 * browser: Chrome

## Steps to reproduce  

1.	Run the attached sample.
2.	Scroll down the grid.

## Result  
Indentation is reset to the highest level at 27th level.

## Expected result  
Indentation is not reset.

## Attachments  
[igxApp.zip](https://github.com/IgniteUI/igniteui-angular/files/8600835/igxApp.zip)

**Comment by kdinev** [comment]
@simeonoff @igdmdimitrov This seems to me to be a documentation issue. Please update the specification (know issues and limitations section) to reflect up to what number of levels the component has been tested and what is the known limitation limit.

**Comment by simeonoff** [comment]
@kdinev We decided to remove this limitation.
