### ISSUE TITLE
IgxGrid - issue with the scrollbars when the dimensions of the grid are set in percentages (%)

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#11476]
## Description  
When the grid has rows with different heights and its dimensions (width and height) are set in percentages, the vertical and the horizontal scrollbars will not work as expected.

**NOTE:** The issue is reproducible in Chrome and Edge and not in Firefox.

 * igniteui-angular version:  12.3.x, 13.1.x, 13.2.x
 * browser: Chrome, Edge

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-sidb6b-5cg8p6?file=src%2Fapp%2Fgrid%2Fgrid-paging-sample%2Fgrid-paging-sample.component.html).
2. Try to scroll with the vertical and the horizontal scorllbars.

## Result  
The scrolling will be blocked if an item with а different size comes in view.

## Expected result  
The scrollbars should work as expected.

## Attachments  
The scroll behaviour in Chrome and Edge:

![scrolling-chrome](https://user-images.githubusercontent.com/75325639/165907668-02c2afdd-7ad8-4612-960a-8d8ab672f157.gif)

Firefox:

![scrolling-firefox](https://user-images.githubusercontent.com/75325639/165907780-3f28a132-86f9-4bc4-a371-5b21a1852f1b.gif)

**Comment by hanastasov** [comment]
After verifying #11239 , the above mentioned behavior is not reproducible anymore. 

There is another issue, which is not severe and I consider it an edge case, just mentioning it for history/tracking purposes:
![scrolling_bug](https://user-images.githubusercontent.com/14248932/175943913-78e9afbf-5e65-4679-a33c-29aff31aee89.gif)

Steps to repro:
1) Load the https://stackblitz.com/edit/angular-sidb6b-5cg8p6?file=src%2Fapp%2Fgrid%2Fgrid-paging-sample%2Fgrid-paging-sample.component.html sample into dev demos
2) Do some scroll
3) Drag the scroller to the top

Result:
Until the mouse is released, and while the scrollbar is held at the top most position, grid flickers like in the gif above.
