### ISSUE TITLE
IgxExcelExporterService to format values exactly as displayed in IgxGrid

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11477]
## Is your feature request related to a problem? Please describe.
I want IgxExcelExporterService to format the cells in excel exactly how I display them on the grid. I use ng-template to display cells in the grid. 
![image](https://user-images.githubusercontent.com/79090369/165962183-311a4524-214f-4db3-961f-4660feba5253.png)

However, when I download excel all the formatting done by me is removed as the IgxExcelExporterService uses cell.value of igxCell.

## Describe the solution you'd like
I would like to provide custom formatting in excel for columns for which I have custom formatting enabled in the grid. For ex: We can provide the formula for formatting the values.
For the above template, the excel formula would be `0.00X;(0.00X)`

## Describe alternatives you've considered
If somehow the final values were to be modified according to our formatting just before generating the excel file.

## Additional context
If the solution would only format the column we provide and format the rest of the columns the existing way, would be great.

**Comment by amitmoondra** [comment]
@hanastasov can you let us know if this is possible/ can be considered as a feature request?
or you can suggest us some alternative way.

Our clients want the excel export to have summaries, row grouping, and column grouped header in the excel export.

**Comment by hanastasov** [comment]
> @hanastasov can you let us know if this is possible/ can be considered as a feature request? or you can suggest us some alternative way.
> 
> Our clients want the excel export to have summaries, row grouping, and column grouped header in the excel export.

@igdmdimitrov maybe you can give more information on these questions.

**Comment by onlyexeption** [comment]
Hello @KaushikEDS,

By looking at your issue, the best way to achieve what you described is by providing a [formatter](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxColumnComponent.html#formatter) to the `igx-column` you want to format. I've created a [sample](https://stackblitz.com/edit/angular-jfuzcg-bd9ahp) for you to check how this can be done.

**Comment by amitmoondra** [comment]
Hi, I understand about formatter, but what about having summaries in the excel export as well?
this right now is not supported.

**Comment by radomirchev** [comment]
Hi @amitmoondra we have created a new feature request for supporting of [summaries in the excel exporter](https://github.com/IgniteUI/igniteui-angular/issues/11598).

**Comment by amitmoondra** [comment]
this is great, thank you @radomirchev
