### ISSUE TITLE
Feature request - @input label for igx-datePicker and igx-time-picker

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1147]
### Current behavior  
There is no options to change label for `igx-datePicker` and `igx-time-picker`

### Expected result  
I want `@input label` for `igx-datePicker` and `igx-time-picker`.
```
<igx-datePicker label="xxx"></igx-time-picker>

<igx-time-picker label="yyy"></igx-time-picker>
```

**Comment by bkulov** [comment]
`@Input() label` is already implemented for IgxDatePicker.
