### ISSUE TITLE
[IgxOverlay] width for igx-snackbar is not set correctly when it is initially shown

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#11480]
## Description  
When IgxSnackbar is initially shown, the width is not set correctly. If the snackbar is then closed and opened again, it receives the correct size.

 * igniteui-angular version: 13.1.x
 * browser: all

## Steps to reproduce  

1. Open this [demo](https://stackblitz.com/edit/angular-fbiptb?file=src%2Fapp%2Fgrid%2Fgrid-cellSelection-sample%2Fgrid-cellSelection.component.ts). 
2. The initial appearance of the snackbar is broken.
3. Close the snackbar and open it again by clicking on any of the above buttons.
4. Snackbar is displayed correctly.

## Result  
IgxSnackbar is not shown correctly initially.

## Expected result  
IgxSnackbar should be shown with correct size at all times.

## Attachments  
This behavior could be observed in the attachment below:
![snackbar-overlay-demo](https://user-images.githubusercontent.com/49126110/166461171-8df61135-4755-4c73-a89e-c1dadca6ecb1.gif)

**Comment by viktorkombov** [comment]
The reason why this happens is because the **snackbar** is opened in the `ngOnInit` lifecycle hook, which is called before Angular has fully initialized the component's view. What I would suggest is to open it in the `ngAfterViewInit` lifecycle hook.
