### ISSUE TITLE
DataGrid not rendering properly when data has an object array called `records` in it

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#11485]
## Description  
When attribute `data` of `IgxGridComponent` has an attribute called `records`, an extra row is rendered as if it was grouped by. There's no `groupingExpressions` being used.

 * igniteui-angular version: tested in `13.1.12` and `13.1.11`
 * browser: Chrome Versión 100.0.4896.127 (Build oficial) (64 bits)

## Steps to reproduce  

Please take look to the following stackblitz example:
https://stackblitz.com/edit/angular-ztphzk?file=src/app/data/amino-data.ts

Steps are quiet easy, just add an attribute called `records` to a row, like this:
```typescript
const data = [{
    name: 'Row data 1',
    records: [{}],
    ...
}, {
    name: 'Row data 2',
    ...
}, {
    name: 'Row data 3',
    ...
}, {
    ...
}];
```

## Result  
An extra row is rendered with no data in it, the workaround is easy as I just have to use another attribute name instead of `records` , that was my solution.

## Expected result  
**What is the expected result after following the steps to reproduce?**
It seems as the grid relays on values stored in `data` to render groupBy expressions, so the ideal would be that it would not. Maybe at least add a flag to explicitly "turn on" the groupBy behaviour (?).

It concerns me that `records` is treated like a reserved word for inner grid calculations (I'm not sure if its intended as a feature for users to purposely add "records", I hope is not). It took me a while to figure it out the issue, so the least I would ask for is to print a `warn` or an `error` in the console when `data` received values with reserved attribute names in it. Also, some documentation would be great to be added with a list of all reserved words.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/29953012/166712968-f825a0af-a7a2-4985-a88e-8e51b1de7a44.png)

**Comment by ChronosSF** [comment]
It also needs to be a non-empty array which is much less likely in a flat grid (hierarchical doesn't support grouping). There are certain shortcomings with each way this check can be implemented. In older products that weren't using typescript, we often had the internal props have much harder to hit names, but with typescript it's much more user-friendly to have a pretty interface.

Anyhow, we can make the check just a little bit more complex, which should solve this.

**Comment by luiscla27** [comment]
Thank you so much for the fix, 

By looking at your fix, now I also, now I know that I have to also avoid calling a column in my dataset as `expression`. You could call all your internal variables with a prefix, like `$$` or `_$`, that way you can add to your documentation that we users have to avoid using objects attributes with that prefix. But of course I know that's way too much refactorization for this minor thing.
