### ISSUE TITLE
ComboBox throws an error when it is not binded to proper displayKey

### ISSUE THREAD

**Issue by katherinedragieva** [IgniteUI/igniteui-angular#11481]
## Description  
ComboBox throxs an error when it is not binded to proper displayKey

 * browser: any

## Steps to reproduce  

1. [Open this sample](https://stackblitz.com/edit/angular-n8bgvx?file=src%2Fapp%2Fcombo-main%2Flocal-data.ts)
2. Open console from developer tools

## Result  
Error is thrown in the console.

## Attachments  
![image](https://user-images.githubusercontent.com/35975071/166664783-cb0a6c8e-4f76-456e-a801-905275649ac4.png)

**Comment by hanastasov** [comment]
Duplicate of #10726
