### ISSUE TITLE
Is there a way to force igx grid to treat my data as flat structure?

### ISSUE THREAD

**Issue by yuhongcheng2003** [IgniteUI/igniteui-angular#11494]
## Question  
I'm currently using the igx grid to display my data, but some of the fields in this flat structured data has "." in them. My understanding is igx is trying to treat my data as a nested data type instead of just use they field "as is". This basically makes my filter and sorting unusable unless I create my own sorting. Is there a way to tell the grid this is a flat structure or somehow override the valueResolver for the entire table?

 * igniteui-angular version: 12.1.6
 * browser: all

**Comment by ChronosSF** [comment]
Having dots in the property names does clash with the nested properties implementation that was intended to be seamless and therefore cannot currently be overridden. We'll come up with some way to allow users to disable or override it but have in mind that 12.1 is no longer supported and no patches will be released for it. You'll have to switch to 12.3 once we resolve this to be able to use the solution.
