### ISSUE TITLE
igx-grid - After sorting a column via sort method, sort icon doesn't show. 

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1152]
### Description  
On igx-grid, after sorting a column via sort method, sort icon doesn't show. 

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-method-issues
2. Click "SORT" button.

### Result  
Sort icon doesn't show.

### Expected result  
Sort icon should show.

**Comment by SlavUI** [comment]
@tkiryu  Hi i tried it on your sample and it works:
![capture](https://user-images.githubusercontent.com/33216749/39236233-ed672a00-4880-11e8-9b2a-f80ec03bf993.PNG)

**Comment by tkiryu** [comment]
@SlavUI , "SORT" button is as below.

![image](https://user-images.githubusercontent.com/15909409/39498637-3036d692-4de4-11e8-9625-dce3c9114fd6.png)

After clicking "SORT" button(internally executing sort method), number column gets sorted but sort icon doesn't come up.
![image](https://user-images.githubusercontent.com/15909409/39498736-e4da876a-4de4-11e8-93ad-154041735e49.png)

**Comment by zdrawku** [comment]
@tkiryu we are going to investigate this behavior.

**Comment by tkiryu** [comment]
@zdrawku thanks!

By the way, #1153 is similar issue and it has been closed because I couldn't reply soon. Could you reopen it?

**Comment by sstoyanovIG** [comment]
#1080
