### ISSUE TITLE
IgxHiearchicalGrid State Persistence: is restoring hiding and pinning column features a limitation for child grids?

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#11545]
## Question  
It seems that restoring the `pinned` and `hidden` properties of columns within a child grid in the `IgxHierarchicalGrid` is not working as expected.

[Here ](https://stackblitz.com/edit/hgrid-child-rowislands-hidden-columns-save-state?file=src/app/hierarchical-grid/hierarchical-grid-save-state/hGrid-state.component.html)is a forked demo from the topic with an additional toolbar added on the child grid for displaying the Hiding and Pinning UI.

Steps:
1. Expand first parent
2. Hide/Pin some columns from the first child grid
3. Click "Save" to save the state
4. Optionally Show/Unpin back the columns.
5. Reload the page/ Click "Restore"
6. Observe the hidden/pinned columns are not restored as such.

![githublog-column-hiding](https://user-images.githubusercontent.com/35433937/168254372-2d91be3d-e5dd-424f-8ec5-b3d594ad1a18.gif)

 * igniteui-angular version: 13.1.x
 * browser:  any

**Comment by viktorkombov** [comment]
Related to #11650.
