### ISSUE TITLE
Make context menu more configurable

### ISSUE THREAD

**Issue by manytostao** [IgniteUI/igniteui-angular#11568]
## Is your feature request related to a problem? Please describe.
The context menu in the Angular Spreadsheet component allows to show, hide, enable or disable a very specific set of options. It would be of great value if this menu could be configured in a way that we could show custom options that trigger custom functions.

## Describe the solution you'd like
Consider an app where the Spreadsheet component is used but the options for handling that spreadsheet are limited by user permissions. Cutting and pasting functionalities already appear in the context menu and can be shown and hidden and whatnot. But what about custom options? What if I want to add a context menu item that opens a dialog that allows the user to be very specific about a cell format, like in in LibreOffice calc or even Excel? And bind that options' visibility to the permissions that user has over that spreadsheet?

Maybe something like:
```
this.spreadsheet.addContextMenuItems(
    [
        {
            id: 'custom-id-here',
            text: 'My very custom option...',
            callback: () => this.myVeryCustomFunction()
        }
    ],
    false
);
```

## Additional context
spreadsheet, angular

![image](https://user-images.githubusercontent.com/105673513/168670485-613b9205-f9f7-4435-954e-58419d6f5a1e.png)

**Comment by manytostao** [comment]
Any news on this feature request? The GitHub bot keeps marking this issue as inactive.

**Comment by mahendrauiux** [comment]
I'm trying to create custom context menu. I'm able to disable the default context menu by applying "args.cancel = true". Now my requirement is how to get and x and y value of the mouse.
