### ISSUE TITLE
Hide delete and edit buttons in grid action strip

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#11578]
## Is your feature request related to a problem? Please describe.
I have a grid where I want to use action strip to add new rows. Deleting of rows is not allowed in my grid. How can I remove delete button from grid editing actions.

## Describe the solution you'd like
Add row button can be shown by setting `addRow ` in grid editing actions. Same should be possible for delete and edit buttons.

## Describe alternatives you've considered
I did not find a way to remove the delete button. I can try to implement custom action strip, but it is there.

**Comment by kdinev** [comment]
@wnvko This change will make it in `14.0.0`. Do you need it for `13.2.x`?

**Comment by wnvko** [comment]
having this in 14.0.0 is just enough, no need for 13.2
