### ISSUE TITLE
ExportUtilities is not exported

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#11585]
`Exportutilities` is not exported

 * igniteui-angular version: 13.2.0-beta.0

## Steps to reproduce  

1. Try to import the `ExportUtilities`:
![image](https://user-images.githubusercontent.com/14248932/169213423-35bce3d7-aced-43d7-92f9-6f51915ac596.png)

If you go to Ignite UI For Angular home page and download the artifact, and open the igniteui-angular-examples-DV repo, you will see ExportUtilities was previously been exported from a path that is not found anymore.

[igniteui-angular-examples-DV.zip](https://github.com/IgniteUI/igniteui-angular/files/8725144/igniteui-angular-examples-DV.zip)

**Comment by mddifilippo89** [comment]
@hanastasov  
Was there a breaking change in igniteui-angular after 12.1.3? ExcelUtilities was available and is no longer in version 13

**Comment by hanastasov** [comment]
DV samples is not using this `ExportUtilities` anymore, so I now consider this as not critical.

**Comment by hanastasov** [comment]
DV samples drops the using of Exportutilities in this PR https://github.com/IgniteUI/igniteui-angular-examples/pull/14
