### ISSUE TITLE
Navigation using keyboard up and down arrow keys gets stuck on Edge

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular#1159]
### Steps to reproduce  
1. Open the Grid Performance demo sample
2. Click on the 10th row
3. Click Arrow Down once
4. Hold Arrow Up until you go to the top

### Result  
The navigation cannot go to the top row of the grid. Similar behavior is observed in Chrome when you start navigating down through the cells using down arrow key and at a certain moment the navigation stops working

### Expected result  
Navigation should work properly

*Note: It seems to be a regression from #966 issue.

**Comment by skrustev** [comment]
This seems to be already fixed.
