### ISSUE TITLE
igx-stepper insufficient contrast in non-active steps with indigo dark theme

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#11616]
## Description  
The steps that are not active do not have sufficient font contrast when using the indigo dark theme.

 * igniteui-angular version: 13.1.x
 * browser: all

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/stepper#changing-the-stepper-orientation
2. Change scroll to the section's sample
3. Change the theme to indigo dark

## Result  
Observe the steps that are not active. The font color blends with the background

## Expected result  
There should be sufficient contrast.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/170280872-d779283d-c3d8-4deb-ac2f-d0cb2f8a21e7.png)

**Comment by sdimchevski** [comment]
@simeonoff We have the correct disabled states for the step label in the first sample with the credit cards so I guess it is some kind of a bug?

<img width="1108" alt="Screenshot 2022-05-31 at 18 06 23" src="https://user-images.githubusercontent.com/15327632/171207067-0fb5a8e2-2540-49c3-9a05-1324d3ecf930.png">
