### ISSUE TITLE
Financial charts dont plot specific points in data invalid

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11629]
I'm using **igx-financial-chart** component for my project.
I want to have empty spaces for certain dates in the graph as shown in the image.

![image](https://user-images.githubusercontent.com/79090369/170675010-cef17fa6-e98c-4558-9b33-833f4eb962b8.png)

But when I try to do that the graph automatically joins the data points similar to the image shown below.
![image](https://user-images.githubusercontent.com/79090369/170675282-6c262ef8-c47f-4c24-8506-1fc7a2943318.png)

Is there a way to have empty data points in  **igx-financial-chart**  component?

Ignite UI version: 13.1.8
Ignite angular charts: 13.0.0
Angular: 13

**Comment by kdinev** [comment]
@gmurray81

**Comment by KaushikEDS** [comment]
Got it.
I will try that. Thanks
