### ISSUE TITLE
Memory leak with igx-combo

### ISSUE THREAD

**Issue by m4yorga** [IgniteUI/igniteui-angular#11632]
## Description  
The igx-combo component causes a memory leak when being consumed from child components that are later destroyed. See below to reproduce the issue:

 * igniteui-angular version: 13.1.16
 * browser: Tested in Microsoft Edge, but happens in any

## Steps to reproduce  

1. Use Microsoft Edge as its DevTools contain the Detached Elements panel
1. Open [this stackblitz](https://stackblitz.com/edit/angular-k7pshd-i7bhev)
1. Click the **CREATE NESTED COMPONENT** button
1. Click the combo to open it
1. Click the **DESTROY NESTED COMPONENT** button
1. Open the Detached Elements in DevTools
1. You will realize that the <app-test> component cannot be garbage collected 

## Result  
Any child components that contain combos, such as the **<app-test>** component in this example, are not properly disposed.

This memory leak only happens when user opens the combo.

## Expected result  
Child components should be properly disposed, no Detached Elements should be left behind.

## Attachments  
Take a look at this gif that also demonstrates the issue
![ComboLeak](https://user-images.githubusercontent.com/4580348/170773943-7f38a7a5-bba9-4378-b387-9d5efd195546.gif)

**Comment by ChronosSF** [comment]
Hey @m4yorga , we are going to tackle it in the next sprint starting on June 6.

**Comment by m4yorga** [comment]
Sure @ChronosSF , thanks for letting me know.
Regards.

**Comment by PlamenaMiteva** [comment]
hi @m4yorga,

this seems to be an issue with angular form. Here is your [sample](https://stackblitz.com/edit/angular-k7pshd-rmcczh?file=src/app/test.component.html) with a simple input instead of the igxCombo in the form. If you follow the steps to reproduce the issue you described, you will see that the result is the same and there is a detached element even without the combo in the form.

**Comment by m4yorga** [comment]
Ok thanks much for your response @PlamenaMiteva , I agree that it's not related to the combo
