### ISSUE TITLE
How to set line color in igx-financial-chart?

### ISSUE THREAD

**Issue by FurkanToprak** [IgniteUI/igniteui-angular#11649]
## Question  
I don't know how to set the color of a specific line on the `igx-financial-chart` component. For example, I can set the`title` property so that each line has a label, but there is no way to set the color.

 * igniteui-angular version: `13.1.17`
 * browser: Firefox.

**Comment by mddifilippo89** [comment]
There is a brushes collection. 

 <igx-financial-chart
      Brushes="#ff0000, #cc0000, #aa0000">
 </igx-financial-chart>
