### ISSUE TITLE
Remaining elements after component is destroyed

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular#11646]
## Description  
Some elements are not being destroyed after a component is being disposed of.

 * igniteui-angular version: 12.3.25; 13.1.16
 * browser: Chrome, Edge

## Steps to reproduce  

1. Open the [Stackblitz sample](https://stackblitz.com/edit/angular-k7pshd-i7bhev) on Edge in a new window.
2. Open the Detached Elements view.
3. Click on the CREATE NESTED COMPONENT button.
4. **Click on the nested component which appeared.**
5. Click on the DESTROY NESTED COMPONENT button.
6. In the Detached Elements view click the garbage can icon.
7. Click on the Get Detached Elements icon (circular arrow) left of the garbage can.
8. Examine the node list.

## Result  
There is an element which wasn't destroyed:
![image](https://user-images.githubusercontent.com/9549439/171172541-d97395e7-384e-4fc5-ad0c-ec100e7cb247.png)

## Expected result  
Child components should be properly disposed of.

**Comment by ddaribo** [comment]
Duplicate of #11632.
