### ISSUE TITLE
Hierarchical Grid's row island pinned columns do not persist after restore

### ISSUE THREAD

**Issue by tishko0** [IgniteUI/igniteui-angular#11650]
## Description  
Nested columns do not keep pinned property after restore

 * igniteui-angular version: 13
 * browser: Chrome

## Steps to reproduce  

1. Run sample
2. Use Pin button to pin parent level 'Photo' column and its child 'Launch Date' Column 
3. Click Save Button to save Grid's state
4. Click Pin button again to remove pinned columns
5. Click Restore 

## Result  
Photo column restores correctly, however Launch Date does not

## Expected result  
All columns should retain the saved pinned property

## Attachments  
[Sample](https://stackblitz.com/edit/angular-lzvqt1?file=src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-save-state%2FhGrid-state.component.html,src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-save-state%2FhGrid-state.component.ts,src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-save-state%2Fabout.component.html)

**Comment by viktorkombov** [comment]
We are currently looking into this matter. Until the issue is being fixed, I can suggest a temporary workaround, where the column's pinned state of the child grids is restored manually each time when the state of the hieararchical grid is restored or a child grid is initialized:
```html
<igx-hierarchical-grid igxGridState [data]="data">
    <igx-row-island (gridInitialized)="childGridInitialized($event)">
    </igx-row-island>
</igx-hierarchical-grid>
```
```typescript
// handles gridInitialized event of IgxRowIsland
// and restores the column's 'pinned' state of the child grids 
public childGridInitialized(args: IGridCreatedEventArgs): void {
    // gets the saved state of the hierarchical grid
    const state = window.localStorage.getItem(this.stateKey);
    if (state) {
        const rowIsland = args.owner;
        const childGrid = args.grid;
        const parentRowID = args.parentID;
        const childGridState = this.getChildGridState(state, rowIsland.id, parentRowID);
        if (childGridState) {
            this.restoreColumnPinnedState(childGrid, childGridState);
        }
    }
}

private restoreColumnPinnedState(childGrid: IgxHierarchicalGridComponent, childGridState: any): void {
    if (childGridState.columns) {
        childGridState.columns.forEach(stateColumn => {
            const childGridColumn = childGrid.getColumnByName(stateColumn.field);
            if (childGridColumn.pinned !== stateColumn.pinned) {
                stateColumn.pinned ? childGridColumn.pin() : childGridColumn.unpin();
            }
        });
    }
}
```
[Here ](https://stackblitz.com/edit/angular-lzvqt1-5xpecs?file=src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-save-state%2FhGrid-state.component.ts)can be found a small sample where is demonstrated how the above approach is working.
