### ISSUE TITLE
Provide the base values for each predefined color palette in docs

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#11658]
## Is your feature request related to a problem? Please describe.
I should be able to see all base color values (primary 500, secondary 500, etc.) for each named palette.

## Describe the solution you'd like
Sassdoc should provide the base color values for each named palette. The docfx palettes article should also link each named palette to the base color definitions in sassdoc. 

## Additional context
Related to https://github.com/IgniteUI/igniteui-docfx/issues/3177

**Comment by simeonoff** [comment]
Closing as the values are listed in the theming library documentation.
For example, here's the [values for the light-fluent-palette](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#variable-light-fluent-palette).
