### ISSUE TITLE
igx-radio - does not remove checked style after another igx-radio gets checked when using Reactive Forms

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1166]
### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-editors-issue
To make it easy to see what happens, I override default style and have native radios shown.

2. Click an igx-radio.
3. Click another igx-radio.

### Result  
Checked style for the first igx-radio does not be removed.

### Expected result  
Checked style for the first igx-radio should be removed.

**Comment by tkiryu** [comment]
@simeonoff other editor components/directives(`igx-datePicker`, `igx-time-picker`, `igxInput` and so on) also don't support `Reactive Forms`?

And do you have a plan to support `Reactive Forms`?

**Comment by simeonoff** [comment]
@tkiryu Hm, the igx-radio does support reactive forms, and so do all of the directives/components you mention above. What makes you think they are not supported in reactive forms?

**Comment by bkulov** [comment]
We started to work on a new component (radio group) which will solve this issue.

**Comment by tkiryu** [comment]
@simeonoff I'm so sorry for the late reply. I missed your mention.
That's because there is the Issue #1144.

**Comment by tkiryu** [comment]
@bkulov I got it. I'm looking forward to it!

**Comment by SlavUI** [comment]
related to #1610

**Comment by bkulov** [comment]
@tkiryu Once the PRs are merged you could use the new directive as in the example bellow:
`<form [formGroup]="personForm">
    <igx-radiogroup formControlName="favoriteSeason" name="radioGroupReactive">
        <igx-radio *ngFor="let item of seasons" value="{{item}}">
            {{item}}
        </igx-radio>
    </igx-radiogroup>
</form>`

You could also take a look at the demo I made. It demonstrates `igx-radiogroup` usage without any bindings, with ngModel binding and with formName and formControlName (reactive forms). The demo could be found in `src/app/radio/` folder.

We will be updating the official docs and samples next week.

**Comment by tkiryu** [comment]
@bkulov , thank you for your information! I'll check your repo.

By the way, let me ask you some questions about consistency.

There is a similar component called `IgxInputGroupComponent`.

1) `IgxInputGroupComponent` is implemented as `Component`.
  Could you tell me why `IgxRadioGroupDirective` is  implemented as `Directive`?

2) `IgxInputGroupComponent`'s selector is `igx-input-group`.
  So, I think `igx-radio-group` is better. Could you tell me your thoughts on this?

**Comment by bkulov** [comment]
@tkiryu 
1) `IgxInputGroupComponent` has an html template. `IgxRadioGroupDirective` is a directive because we don't need all the functionality a `Component` provides. Radio group doesn't have a template and only synchronizes the radio buttons selection. Angular Material also have a directive for radio groups.
2) I'll rename the selector to `igx-radio-group` for consistency.

**Comment by tkiryu** [comment]
@bkulov , thank you so much. I got it!
