### ISSUE TITLE
Tooltips don't work on mobile

### ISSUE THREAD

**Issue by FurkanToprak** [IgniteUI/igniteui-angular#11664]
## Description  
Tooltips for `igx-financial-chart` are not  visible upon tapping on lines (or ever)
 * igniteui-angular version: `13.1.17`
 * browser: mobile firefox

## Steps to reproduce  

1. Create datalines with titles so that tooltips occur
2. Try to tap on a chart on mobile
3. See that it doesnt work

## Result  
Tooltips don't show up

## Expected result  
Tooltips should be showing on default or on tapping.

**Comment by FurkanToprak** [comment]
@gmurray81 Hey! Please send me a sample, this is urgently required for 80% of my website traffic. I tried to listen to the chart but haven't figured it out (new to angular). Thank you so much!

**Comment by gmurray81** [comment]
didn't test it with ohlc/candlestick, but this would be the basic idea:
https://codesandbox.io/s/red-rain-6x4m6i?file=/src/app/app.component.ts
