### ISSUE TITLE
Category chart and pie chart theme inconsistencies

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#11663]
## Description  
Noticed some odd inconsistencies in the category chart and the pie chart themes and want to see if that's intentional or something we can clear out

 * igniteui-angular version: 13.x.x
 * browser: N/A

## Steps to reproduce  

1. Run the sample and inspect the charts
2. Change the theme to `dark-theme` mixin and compare again

## Result  
- Light theme: Category chart sets gray 700 to all axis strokes and labels
- Dark theme: Category Chart sets gray 400 (using apparently old format with `to-opaque: #fff`). Is this intentionally different level of gray from the light theme? Bit odd for one and also less contrast-y.
- Pie Chart: Sets gray 900 for both light and dark theme, making its labels nearly black/white depending on theme and visibly different from the category chart.

There appear to be some variations from the intended designs:
- Category chart sets all labels, title and axis strokes to the same color. From what I can see in designs they are all different shades actually. Guessing @tosharky can clarify.
- The Pie didn't have a design, but guessing it'd include some typography which it currently doesn't have (unlike the category). Could be a separate issue/feature though.

## Expected result  
Unless there's a reason for it, maybe we can use the same shade between light and dark for category chart and use the same shade for the pie labels as well

## Attachments  
The sample from #11662 can be reused

**Comment by desig9stein** [comment]
@sdimchevski  can you tell me if I use the correct colors in my PR, if they are not, can you provide the right ones?
