### ISSUE TITLE
Category Chart theme sets the series brushes as negative brushes

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#11662]
## Description  
The current implementation of the Category Chart theme sets the same brushes to all properties of the chart 

 * igniteui-angular version: 13.x.x
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample
2. Change the chart type to waterfall

## Result  
Both negative brushes and negative outlines:
![image](https://user-images.githubusercontent.com/3198469/171646856-22080f54-bf66-4663-b662-252923ef9b19.png)
so the result is this:
![image](https://user-images.githubusercontent.com/3198469/171646222-2744eecd-fb0b-41d3-972b-ec5f679693ec.png)

## Expected result  
Not the most appropriate data for waterfall (sorry) but consecutive lower values should be indicated with red of some sort, right, something like when I drop the theme entirely:
![image](https://user-images.githubusercontent.com/3198469/171645688-cef07466-31cd-4191-8530-1c0ed17d13cf.png)
The default baked into the chart is actually a single brush for negative being `#ee5879`

Unless the design calls for something specific I suppose we can skip setting default values to negative brushes entirely in the theme?

## Attachments  
[ngCategoryChart.zip](https://github.com/IgniteUI/igniteui-angular/files/8824821/ngCategoryChart.zip)

**Comment by sdimchevski** [comment]
@simeonoff yes the negative brush and outline should be #ee5879 indeed

**Comment by desig9stein** [comment]
@sdimchevski I don't like the idea to use hardcoded color, why not use color from the palette instead?

**Comment by ig-georgeA** [comment]
@damyanpetev @sdimchevski we should consider mapping negative brushes to the "error" color of the theme as opposed to picking a red-enough color from chart brushes.
