### ISSUE TITLE
IgxGrid : Change default sorting direction for grouped column

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11729]
Whenever we group a column the default sorting is always ascending.
![image](https://user-images.githubusercontent.com/79090369/174270904-18d0adf0-14a4-4527-8fab-46cef5617a3c.png)

Is there a way to change the default sorting direction to descending?

 * igniteui-angular version: 13.1.8
 * browser: Chrome

**Comment by tishko0** [comment]
Hi, there is no property that would change the default sorting direction, but you can sort the grid as you group columns in the direction you want in the [onGroupingDone ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#onGroupingDone)event:

`this.grid1.sort([
      {
        fieldName: e.groupedColumns[0].field,
        dir: SortingDirection.Desc,
        ignoreCase: true,
      },
    ]);`

Sample [here](https://stackblitz.com/edit/angular-vfthpk?file=src%2Findex.html,src%2Fapp%2Fgrid%2Fgrid-groupby-sample%2Fgrid-groupby-sample.component.html,src%2Fapp%2Fgrid%2Fgrid-groupby-sample%2Fgrid-groupby-sample.component.ts,src%2Fapp%2Fgrid%2Fgrid-groupby-sample%2Fgrid-groupby-sample.component.scss)

**Comment by KaushikEDS** [comment]
@tishko0 
Can we create a sorting strategy where we can always put empty values at the bottom?

**Comment by tishko0** [comment]
Hey there.

Yes, this is possible, however there is no exposed method that would do it, so you will have to implement a custom sorting strategy to do so. I have prepared a sample [here](https://stackblitz.com/edit/angular-vfthpk?file=src%2Findex.html,src%2Fapp%2Fgrid%2Fgrid-groupby-sample%2Fgrid-groupby-sample.component.html,src%2Fapp%2Fgrid%2Fgrid-groupby-sample%2Fgrid-groupby-sample.component.ts,src%2Fapp%2Fdata%2FinvoiceData.ts,src%2Fapp%2Fgrid%2Fgrid-groupby-sample%2Fgrid-groupby-sample.component.scss)
In the sample, I have created two sorting methods(one for ascending and one for descending) that will sort the null values to the end.: _compareValuesAsc_ and _compareValuesDsc_;
Then I have overwritten the comparer in the default class to use those methods so the sorting will be as per the custom sorting methods:
`if (reverse) {
      return this.compareValuesAsc(a, b);
    } else return this.compareValuesDsc(a, b);`

Please check the sample and let me know if you have any questions.
