### ISSUE TITLE
[PivotGrid] Column Width Auto Resize

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11735]
## Question  
Switching between display densities, more evidently on super compact mode, the columns don't seem to adjust their width to fully expand to the current pivot's width.

Would be possible to have a property for this or have it as a default behavior?

 * igniteui-angular version: 13.2.1
 * browser: Chrome

![column-width-auto-resize1](https://user-images.githubusercontent.com/32940839/174558455-1f3253f6-28cf-4ab5-bd4a-a0901a6ab2bd.png)

![column-width-auto-resize2](https://user-images.githubusercontent.com/32940839/174558463-b1c11df9-478f-426a-b12a-b84c7cff8da3.png)

**Comment by MayaKirova** [comment]
I think it would be fine if we make filling the empty space the default behavior, unless there are some design or other considerations @dkamburov I think this can be implemented rather fast.

If not as an alternative I can suggest setting a different width on the [columnInit](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxPivotGridComponent.html#columnInit) event of the grid to fill the space, for example: https://stackblitz.com/edit/angular-zxb95o

**Comment by dkamburov** [comment]
@MayaKirova Let's make this the default behavior. Sounds like that's the way to behave.
