### ISSUE TITLE
[PivotGrid] Date Sorting

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11738]
## Question  

For date type dimensions, we are using IgxPivotDateDimension with everything on false in terms of options apart from "fullDate", which is on true. We've noticed that if we use "memberFunction" and try to sort, it seems it will do a string sorting rather than a date one. Without "memberFunction", the sorting is done okay. Should the method return a different type than string?

 * igniteui-angular version: 13.2.1
 * browser: Chrome

<img width="622" alt="date-sorting" src="https://user-images.githubusercontent.com/32940839/174565746-c6690d84-36a7-43c9-8aa2-128fe5640683.png">

**Comment by dkamburov** [comment]
@anserban Seems like an issue with the `IgxPivotDateDimension` not taking into account the `dataType` property. But if you don't want the predefined hierarchies, sounds like you won't need to go through the build-in `IgxPivotDateDimension`.

You should be able to achieve the same using the following:

```
    private getPivotDateDimension(metadataDimension: DataItem): IPivotDimension {
        return {
            memberName: metadataDimension.name,
            memberFunction: (data) => {
                return PivotGridFormatters.formatData(data[metadataDimension.name]);
            },
            dataType: GridColumnDataType.Date,
            sortDirection: SortingDirection.None,
            enabled: true
        }
    }
```

I'm setting this as a bug and we'll investigate the issue with the `IgxPivotDateDimension` anyway. 
In order to reproduce the issue we can use:
```
        new IgxPivotDateDimension(
            {
                memberName: 'Date',
                memberFunction: (data) => {
                    return data['Date'].toLocaleDateString();
                },
                enabled: true,
                dataType: GridColumnDataType.Date
            },
            {
                total: false,
                years: false,
                quarters: false,
                months: false,
                fullDate: true
            }
        ),
```
While sorting works normally with the same configuration, but not using the `IgxPivotDateDimension`:
```
        {
            memberName: 'Date',
            enabled: true,
            memberFunction: (data) => {
                return data['Date'].toLocaleDateString();
            },
            dataType: GridColumnDataType.Date
        },
```

**Comment by anserban** [comment]
Without `IgxPivotDateDimension`, the sorting works well with dates that have formats like "yyyy-MM-dd" or "yyyy/MM/dd".
In our case, the sorting seems to fail for other types of formats, like "dd-MM-yyyy" or "dd/MM/yyyy".

**Comment by mddragnev** [comment]
> Without `IgxPivotDateDimension`, the sorting works well with dates that have formats like "yyyy-MM-dd" or "yyyy/MM/dd". In our case, the sorting seems to fail for other types of formats, like "dd-MM-yyyy" or "dd/MM/yyyy".

@anserban So the first issue you have talked about - sorting within IgxPivotDateDimension not working is currently fixed on PR. As for the quoted one, internally we are using `Date` constructor to create and therefore sort new dates which comes like strings from the data. You can see that the `new Date` behaviour is ambigious when comes to different string formats and does not provide locale parameter. So far `Date` constructor has good support for these formats : 
```
MM-dd-yyyy
yyyy/MM/dd
MM/dd/yyyy
```
If you return any one of these formats  from the memberFunction, the sorting works as expected. You can currently test this only with pure date without IgxPivotDateDimension (it is still on PR).
