### ISSUE TITLE
[PivotGrid] Realtime Updates

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11743]
## Is your feature request related to a problem? Please describe.
Once we receive a realtime update, we would need a way for us to highlight the cell's value change from its previous value.

## Describe the solution you'd like
Just how Data Grid has the "cellClasses" property, we would probably need a similar property here for applying different CSS classes based on certain conditions.

**Comment by MayaKirova** [comment]
@anserban 
We currently have a [styles](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IPivotValue.html#styles) property on the value configuration that can be used to conditionally style the cell based on the cell value. 

For example:

```
 styles: {
            up: (
              rowData: IPivotGridRecord,
              columnData: IPivotGridColumn
            ): boolean =>
              rowData.aggregationValues.get(columnData.field) > 100000,
            down: (
              rowData: IPivotGridRecord,
              columnData: IPivotGridColumn
            ): boolean =>
              rowData.aggregationValues.get(columnData.field) <= 100000,
          }
```
This applies a css class with a matching name ("up" or "down" for the above example) to the related cell that matches the condition.

Here's a small sample with changing data: https://stackblitz.com/edit/angular-1uigzb
Let me know if using styles would be enough or if perhaps you need some more complex styling.

**Comment by anserban** [comment]
Looks good! Given that we also have access to row and column data, I think it might be enough.
Thank you!
