### ISSUE TITLE
[PivotGrid] Export to Excel

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#11742]
Similar to Data Grid, can the Pivot Grid have support for export to excel functionality?

**Comment by dkamburov** [comment]
@anserban Excel supports pivot girds. Do you expect to have the pivot grid exported in Excel as pivot grid or simply the data as flat grid?

**Comment by anserban** [comment]
I think the user would probably expect the data to be exported directly as a pivot grid here.
That's how our previous pivot behaved.

**Comment by anserban** [comment]
Yes, looks good.
Thank you!
