### ISSUE TITLE
Scrollbar for grid under Windows 11/Firefox 101 is too narrow

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#11757]
* igniteui-angular version: latest
 * browser: Firefox 101.0.1

## Steps to reproduce  

1. Go to https://www.infragistics.com/angular-demos-lob/grid/grid-master-detail

## Result  
Scrolbar is not visible. Hovering the cursor over the edge area on the grid, where scrollbar is expected, you will see a narrow scrollbar appears. This scrollbar actually has two states:

![image](https://user-images.githubusercontent.com/14248932/175019488-05b23bc1-9aa0-48b8-a906-d995fd15e96c.png)
The first one actually disappears by itself after some time(second or two)

![image](https://user-images.githubusercontent.com/14248932/175019516-dc4318c8-9996-4c44-8f51-327a6b64426e.png)
This one does not disappear, maybe we hover somewhere else to get it (around the scrollbar area again)

**Comment by simeonoff** [comment]
This is a Windows 11-specific behavior. Seems like starting with version 100, Firefox adopted the native Windows 11 scrollbar behavior. To always show the scrollbars, you'd have to disabled the corresponding setting in Windows `System Preferences > Accessibility > Visual Effects > Always show scrollbars`.

I couldn't find a way to programmatically change this behavior in Firefox alone. There's an open feed regarding this issue [here](https://connect.mozilla.org/t5/discussions/scrollbars-disappear-in-firefox-100/td-p/5433).

**Comment by simeonoff** [comment]
@hanastasov Why would you remove the inactive label. This is a third-party issue that we cannot resolve.
