### ISSUE TITLE
The expansion panel animation is not smooth especially when collapsing.

### ISSUE THREAD

**Issue by ig-georgeA** [IgniteUI/igniteui-angular#11768]
## Description  
When expansion panel is used, the collapse animation seems to happen in two parts, and looks clunky.

 * igniteui-angular version: 
 * browser: Edge, Firefox, Chrome

## Steps to reproduce  

1. Add expansion panel, and include a list with 4 items inside the expansion panel body
2. Create 3 copies of the panel and stack them vertically
3. Compile and check results

## Result  
What is the actual result after following the steps to reproduce?
The collapse is happening in two states.
![production expansion](https://user-images.githubusercontent.com/41584300/175562651-d935a408-2ee5-4df5-8013-19e2d4cdfa3b.gif)

## Expected result  
What is the expected result after following the steps to reproduce?
See attached GIF

## Attachments  
Attach a sample if available, and screenshots, if appl
![desired expansion](https://user-images.githubusercontent.com/41584300/175562516-a5d14a77-a636-46a0-80a1-85edb7bc295d.gif)

**Comment by ig-georgeA** [comment]
It should be fine even without the extra space. I suspect it's more of a Material thing
![desired expansion no space](https://user-images.githubusercontent.com/41584300/175563998-03e13df4-2ca7-4d71-a5a7-67e5abdce59c.gif)
.

**Comment by andiesm813** [comment]
Here's another Material expansion panel sample which has very smooth expand/collapse animations:
https://daemonite.github.io/material/docs/4.0/material/expansion-panels/
