### ISSUE TITLE
Further clarification on Igx legend

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11774]
It is about a question I asked earlier this year which can be found here: https://github.com/IgniteUI/igniteui-angular/issues/10836

@agoldenbaum 

I checked the demo.zip provided and I couldn't understand a few things.

1. What are LegendTemplates and what does resolveLegendTemplate do?
![image](https://user-images.githubusercontent.com/79090369/175586087-488430e2-c9f4-4d66-80a3-5cdbce792bf4.png)
2. What are obj and child variables? How can I use them?
![image](https://user-images.githubusercontent.com/79090369/175598094-ec4053f4-731f-4f34-b489-0b0c62b1bbd5.png)

I want to do the following things in legend - 

1. Customize the text displayed in the legend
2. Add custom elements (like the checkbox in the demo.zip)
4. Change the position and orientation of the legend in the chart
5. Customize the badge for legend.

_Originally posted by @KaushikEDS in https://github.com/IgniteUI/igniteui-angular/discussions/11250#discussioncomment-3018879_

**Comment by KaushikEDS** [comment]
Thank you very much for this detailed explanation @agoldenbaum.

I have a few questions about the charts

1. Can I modify the legend without providing the external component which we give to **legend** input of financial-charts-component. I'm talking about the legend when we set **isLegendVisible** to true. We get the legend with name appended with some additional information.
![image](https://user-images.githubusercontent.com/79090369/176211025-f7620f22-cc79-4732-8b6f-697d7443edb7.png)
It is quite confusing what it means and I want to remove/modify it if possible.


2. When I try to set **legendItemBadgeTemplate** similar to **legendItemTemplate** I get an error. 
The code for template:
![image](https://user-images.githubusercontent.com/79090369/176211827-36da6f1c-18f8-41bf-9c19-988bf3dbce0f.png)
Setting the template:
![image](https://user-images.githubusercontent.com/79090369/176211895-4ef9709a-dd08-4199-8e24-fe37ccfea850.png)
The error I'm getting: 
![image](https://user-images.githubusercontent.com/79090369/176212271-73906ba0-88b5-4243-8e96-5c142c834263.png)
The source of error:
![image](https://user-images.githubusercontent.com/79090369/176213069-c419dfd8-21c6-4b83-bd95-b5c82ee469e4.png)

Can you give me an example of how to create the badge template, if possible?

**Comment by agoldenbaum** [comment]
Hello KaushikEDS,

I have been investigating into your most recent two requirements, and I have some information for you. I will answer your questions in the order they were asked.

**1.** The legend that becomes visible in the IgxFinancialChart when you set the **isLegendVisible** property to true does not allow modification of its position or orientation – it is fixed to the top of the chart at the time of writing this.
The legend that is used here is actually the new **IgxDataLegend**, which allows you to display additional information, and it will update as you scroll through the chart. You can read about the new Data Legend here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/charts/features/chart-data-legend.

**2.** I am attaching a sample project that demonstrates creation of a custom **legendBadgeItemTemplate** using the **CanvasRenderingContext2D** object that is returned by the **DataTemplateRenderInfo.Context** property.

Please let me know if you have any other questions or concerns on this matter.

[demo.zip](https://github.com/IgniteUI/igniteui-angular/files/9002657/demo.zip)

**Comment by KaushikEDS** [comment]
Thank you @agoldenbaum the provided solution helps a lot.
