### ISSUE TITLE
Date-range-picker theme parameters

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#11803]
## Is your feature request related to a problem? Please describe.
A customer is facing an issue when trying to modify the color for the first selected date when opening the date-range-picker.

## Describe the solution you'd like
Expose theme parameters for changing the hover and focus background, and text colors for date within the selected range (consider current date when it is within the range).

## Additional context
![image](https://user-images.githubusercontent.com/44684385/176686643-2ad642bd-8438-48b5-a544-bdea60b6cad7.png)

**Comment by desig9stein** [comment]
@mmart1n is it just the first selected date, from the conversation we had I get the impression that we need to add styling properties for hover and focus inside the selected range?
