### ISSUE TITLE
IgxDataGrid - In Chrome on mac, when I enter double-byte characters in a cell, it becomes empty.

### ISSUE THREAD

**Issue by IG-Mori** [IgniteUI/igniteui-angular#11836]
## Description 

In the online sample below, when a double-byte character is entered into a string data cell and confirmed, the cell will be blank.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing?gasource=login.microsoftonline.com&gamedium=referral&gacampaign=(not%20set)&gaterm=&gagclid=
![image](https://user-images.githubusercontent.com/93457260/177919826-cf8f28d4-deaf-40cf-ae34-414f0f3f3c96.png)

- OS: macOS 10.15.7
- Browser: chrome (103.0.5060.114)

## Steps to reproduce  

1. Switch to double-byte character input
2. Put the "Product Name" column cell into edit state
3. Input double-byte characters.
4. Press the Return key to confirm the input.

## Result  
The cell becomes empty.

## Expected result  
The input of double-byte characters should be reflected in the cell.

## Attachments  
[IgxDataGrid-CellEditing (1).zip](https://github.com/IgniteUI/igniteui-angular/files/9069025/IgxDataGrid-CellEditing.1.zip)

**Comment by hanastasov** [comment]
Adding this to the work planned for next sprint.
