### ISSUE TITLE
IgxRadioGroup ignores initial disabled state in reactive form

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#11846]
## Description  
IgxRadioGroup ignores initial disabled state in reactive form.

 * igniteui-angular version: 14.0.5
 * browser: Chrome

## Steps to reproduce  

``` html
<form [formGroup]="form">
  <igx-radio-group name="test" formControlName="radio">
    <igx-radio [value]="'value1'">test1</igx-radio>
    <igx-radio [value]="'value2'">test2</igx-radio>
  </igx-radio-group>
</form>
```
``` typescript
form = new FormGroup({
  radio: new FormControl({ value: null, disabled: true }),
});
```

## Result  
Radio Group is not disabled.

## Expected result  
Radio Group should be disabled.

## Attachments  
https://stackblitz.com/edit/angular-obbbi4-az7nrl

**Comment by SisIvanova** [comment]
@Timmeeeey The radio group **disabled** property has been deprecated since version 12.2.0 and will be removed in version 15. However, you can still disable individual radio buttons following the same approach. Here is an example:
https://stackblitz.com/edit/angular-obbbi4-v8tyzx?file=src/app/app.component.ts

**Comment by Timmeeeey** [comment]
@SisIvanova 
Ok, so I just have to move the `formControlName` from `igx-radio-group` to all `igx-radio`?
```html
<form [formGroup]="form">
  <igx-radio-group name="test">
    <igx-radio [value]="'value1'" formControlName="radio">test1</igx-radio>
    <igx-radio [value]="'value2'" formControlName="radio">test2</igx-radio>
  </igx-radio-group>
</form>
```

**Comment by SisIvanova** [comment]
> @SisIvanova Ok, so I just have to move the `formControlName` from `igx-radio-group` to all `igx-radio`?
> 
> ```
> <form [formGroup]="form">
>   <igx-radio-group name="test">
>     <igx-radio [value]="'value1'" formControlName="radio">test1</igx-radio>
>     <igx-radio [value]="'value2'" formControlName="radio">test2</igx-radio>
>   </igx-radio-group>
> </form>
> ```

Yes, that's right.
