### ISSUE TITLE
igxTree overflow auto 

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#11848]
## Description  
Can we consider adding overflow-y and overflow-x to the Tree component? This decision can be made based on the question - is it already present in the WC Tree.
 - If it is, we should add it for the Angular tree as well. This will bring a better consistency as platforms like the AB are relying on this to produce quality code without additional CSS changes depending on the picked framework for code generation. Currently, If overflow is present in WC and missing from Angular, upon code generation this CSS Property should be manually added.
 - If it is not present in both, should we add it or we can "workaround" this on App builder level and export the CSS props based on design surface configuration?

**Example:**
![image](https://user-images.githubusercontent.com/11193764/178683155-889e3565-9f7f-40c9-84b3-a64636965451.png)

**Comment by desig9stein** [comment]
@zdrawku, let me know if that fix is OK, and I will also transfer it to the web components. Also, since this is an enhancement, do I need to make PR for 14.0.x

**Comment by zdrawku** [comment]
Nice, lets get back to you later today and we can wrap this up.

**Comment by zdrawku** [comment]
@desig9stein could you please make a PR for 14.0.x as well
