### ISSUE TITLE
infinite scroll with row selection does not select all rows

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#11886]
A customer is using igx-grid with enabled row selection feature and implemented infinite scroll. After checking the header selector and scroll down in order to load more data only the first 10 rows (the chunk size) are selected, but the header checkbox state is still 'checked'. This could be observed in the following gif:

![inf-scroll-demo](https://user-images.githubusercontent.com/49126110/179966853-5dac89c2-c97e-484e-80cb-9e0ed456cfc6.gif)

His requirement was to select all data when the header checkbox is checked, so a possible approach I have tried is using IgxGrid's **selectAllRows** method when scrolling the vertical scrollbar. In this case, the newly loaded rows are selected, however, the header selector state is **indeterminate** and remains indeterminate even after loading the final chunk of data. This could be observed in the following gif:

![inf-scroll-demo-headerRowSelector](https://user-images.githubusercontent.com/49126110/179968134-5f30ea79-07df-432c-b642-d0bb4bdb5d81.gif)

After an investigation, I have determined that this behavior is due to the values passed as selectedCount and totalCount properties of the headSelectorBaseTemplate's context i.e. when a new chunk of data is loaded the grid's data length is not changing, however the selected rows count keeps all selected records in the previous chunk of data. So, the elements count in these collections is different and the checkbox is marked as indeterminate.

![1](https://user-images.githubusercontent.com/49126110/179984517-e895ec57-5ff1-4e59-9eac-f21cc04221e1.png)
![2](https://user-images.githubusercontent.com/49126110/179984522-ed49d4ab-7171-49b6-9235-71879cab9ded.png)

 * igniteui-angular version: 14.0.x
 * browser: all

## Steps to reproduce  

1. Open this [demo](https://stackblitz.com/edit/angular-ivjavq?file=src%2Fapp%2Fgrid%2Fgrid-sample-5%2Fgrid-sample-5.component.ts).
2. Select all rows via the header selector.
3. Scroll down to load more data.

## Result  
With no workaround - only the first 10 rows are selected.
With a workaround - rows are selected, but the header selector checkbox is wrongly set to indeterminate.

## Expected result  
All rows should be selected and the indicator should be set accordingly.

**Comment by hanastasov** [comment]
Related to #10961
