### ISSUE TITLE
Stackblitz links not working

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#11898]
The link for all documentation gives an error.
It's probably after the angular/ignite version 14 release.

![image](https://user-images.githubusercontent.com/79090369/180436824-54b42e4b-9cc6-4bbc-af47-ce749c2f9dde.png)

**Comment by kdinev** [comment]
@KaushikEDS I tried reproducing this issue just now and I wasn't able to:

![image](https://user-images.githubusercontent.com/1472513/183592876-446f606b-5950-47c2-8bba-ba1d891439b2.png)

Still, there's an issue that we're sending samples to stackblitz with a beta package reference. This will get updated.
