### ISSUE TITLE
Drag&Drop operations, such as column moving in IgxGrid, error w/ "maximum call stack size" when perfromed within the IgcDockManager

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#11913]
## Description 
When attempting to move/group, etc. a column in a Grid (or other drag operation) and the control is placed within an IgcDockManager content pane, a "maximum call stack size" error is thrown. 

Likely related to the fix of #11574 

 * igniteui-angular version: 12.3, 13.2, 14.x
 * browser: any

## Steps to reproduce  

1. Open [this ](https://stackblitz.com/edit/dock-manager-grids-moving?file=src/app/dock-manager-sample/dock-manager.component.ts) sample
2. Attempt to move a column in the grid.
3. Observe console.

## Result  
```
polyfills.js:10546 Uncaught RangeError: Maximum call stack size exceeded
    at IgxColumnMovingDragDirective.getFromShadowRoot (vendor.js:138615:20)?
```

## Expected result  
To be able to perform drag operations for controls within the Dock Manager.

**Comment by skrustev** [comment]
The issue was related to a difference in the Chrome behavior when getting elements from point in a shadow DOM, which includes element up in the DOM structure outside the shadow DOM discussed here:
https://bugs.chromium.org/p/chromium/issues/detail?id=843215
