### ISSUE TITLE
Improve virtualization performance (especially in IE/Edge)

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#1191]
### Description  
With the recent changes to change detection the performance especially horizontally has degraded. A list of things to explore that could improve it are:

| Tested | Description | Assignee |
| ------- | ------------- | ---------- |
|  | Only append and prepend views, not reuse them, remove the unnecessary autowiring | |
|  | Switch to default detection strategy, remove autowiring | #1206 |
|  | Implement a mechanism to have only one horizontal scroll handler instead of each horizontal directive handling it seperately | #1254 |
|  | ***New*** Add debounce/throttle on the onScroll event handlers | |
|   | ***New*** Retain a constant chunk size for horizontal virtualization (calculated based on the max number of columns that can be visible at a time based on their current widths). | #1405|

### Steps to reproduce  

1. Open the performance sample
2. Set width and height comparable to the screen size
3. Check horizontal/vertical keyboard navigation, scrolling etc

### Result  
The performance is slower horizontally than vertically, both are not as good as in 5.2.x 

### Expected result  
Better performance

**Comment by MayaKirova** [comment]
Also we can explore adding debouce for onScroll event handlers.

**Comment by MayaKirova** [comment]
@ChronosSF @rkaraivanov Regarding the scroll events, we should think if we want debouncing or throttling from an UX perspective since both will be perceived differently by the end-user.
