### ISSUE TITLE
Test strategy and test plan for keyboard navigation

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#1194]
### Description  
Add test strategy and test plan for the igx-grid virtualization. Related: #892.

**Comment by MayaKirova** [comment]
@mpavlinov As discussed we'll be adding just a basic test plan with high level scenario descriptions to the specs. Could you please review the one for virtualization at: 
https://github.com/IgniteUI/igniteui-angular/wiki/igxGrid-Specification#virtualization
