### ISSUE TITLE
Financial chart - Volumes pane disappears when changing indicators dropdown

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#11975]
## Description  
Financial chart - Volumes pane disappears when an item is selected from indicators dropdown.

 * igniteui-angular version: 14.1.1
 * browser: Chrome、Edge

## Steps to reproduce  

1. Go to the sample: https://stackblitz.com/edit/angular-8jphuj-albr7f?file=src/app/stock-index-chart/financial-chart-stock-index-chart.component.html
2. Click 'Indicators' dropdown and select any item other than ones under 'Volumes'.

## Result  
Volumes pane disappears.

## Expected result  
Volumes pane stays visible.

**Comment by hanastasov** [comment]
@mkamiishi , is this sill reproducible? I was not able to reproduce it. Please close the ticket if not relevant anymore.

**Comment by mkamiishi** [comment]
@hanastasov This is still reproducible with igniteui-angular-charts:14.1.2.
