### ISSUE TITLE
Multiple language in igx-combo

### ISSUE THREAD

**Issue by vuhust19081995** [IgniteUI/igniteui-angular#11974]
## Is your feature request related to a problem? Please describe.
When i am using igx-combo with empty option list, the 'The list is empty' message is showed.

## Describe the solution you'd like
I want to show multiple language with this message. So, i recommend using resource string like `igx_grid_excel_custom_dialog_header` or `<ng-content>`.

## Additional context

![img1](https://user-images.githubusercontent.com/29648335/184792085-75e7f8b6-2fe1-4690-b8d3-ba73c77bf788.png)
![img2](https://user-images.githubusercontent.com/29648335/184792088-903e8d12-a386-4894-8391-490c7e01ed6c.png)

**Comment by loclv** [comment]
I also need this feature. :smile:

**Comment by ChronosSF** [comment]
@vuhust19081995 , @loclv , this should have been localizable from the get-go so we are considering it a bug . We'll try to have a resource string for this for the next patches coming on on Sep 5.
