### ISSUE TITLE
Comments are not visualized in Excel files

### ISSUE THREAD

**Issue by ekrayzman** [IgniteUI/igniteui-angular#11973]
Comments are not visible when displaying Excel files since the IgxSpreadsheet component does not currently have a way of visualizing comments in the Workbook / Worksheets.
We rely on accurate reproduction of Excel files and not having comments have a serious impact on the integrity of this reproduction so we would very much like to have this enabled.

**Comment by danibenk** [comment]
Hi, why is the feature request closed?
please let us know of any progress, or why you decided to close it.
we use your product with xls/xlsx files and use comments.
thank you/

**Comment by kdinev** [comment]
@agoldenbaum @igandrews Can you guys comment on where there's any plans to implement this?
