### ISSUE TITLE
Add default formatting for numbers in igx-grid

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#1197]
### Description  
Describe the issue.

### Steps to reproduce  

1. Open [this topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_summaries.html)
2. Observe the summaries

### Result  
![image](https://user-images.githubusercontent.com/6794133/39364659-5d7ab9da-4a37-11e8-88f8-f6cda0ce0f35.png)

### Expected result  
By default the numbers should have proper format.

**Comment by zdrawku** [comment]
This is enhancement that we should discuss with @rkaraivanov and @sbozalieva, I am going to create a meeting and will update the issue with more detailed description.

**Comment by zdrawku** [comment]
Summaries templating will be implemented in order to have the ability to use ng numeric pipes. The pipe will be used for number formatting.

For the default formatting we will again use the numeric pipes to format the values depending on the column type. Numeric and Date pipes will be used.
