### ISSUE TITLE
Scrolling in grid with live data is not smooth

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#11996]
* igniteui-angular version: 14
 * browser: Chrome, check others too

## Steps to reproduce  

1. Go to Grid FinJS sample demo https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live-data
2. Add 10k records
3. Scrolling is smooth
4. Start LIVE PRICES

## Result  
Scrolling is laggy. Drag the scrollbar with the mouse - at some point it stops dragging and scrolling is no performed.
Issue can be reoriduced also by clicking on the scrollbar in order to invoke continuos scrolling.

![grid-scrolling](https://user-images.githubusercontent.com/14248932/185859603-8d228020-d8f5-4440-bacf-77135e63e891.gif)

Same is happening in grid with dock manager.

**Comment by gmurray81** [comment]
BTW, when I was looking at this the other day, it seems like the change detector was firing a lot during scroll even without the live prices turned on, so that if you increase the record count to 100k it gets very slow.
