### ISSUE TITLE
[IgxDragDrop] TypeError: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#12004]
## Description  
Drag and drop often throws **TypeError: Cannot read properties of null (reading 'style');**
This behavior is reproducible in all [Grid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag), [TreeGrid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row-drag), and [HierarchicalGrid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/row-drag) row drag samples, as well as most samples in the [Drag and Drop](https://www.infragistics.com/products/ignite-ui-angular/angular/components/drag-drop) topic. It is also reproducible if the dragged object is dropped outside the drop area.

** **NOTE** **: This may be introduced by the following fix #11576 as the behavior is not reproducible in 13.1.x.

 * igniteui-angular version: 13.2.x, 14.0.x
 * browser: any

## Steps to reproduce  

1. Open [Angular Grid Row Drag Example](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag#angular-grid-row-drag-example)
2. Open the dev tools console, drag some rows and observe.

## Result  
TypeError: Cannot read properties of null (reading 'style') error is thrown.

## Expected result  
There should be no errors.

## Attachments  
The described behavior could be observed in the below attachment.
![drag-drop](https://user-images.githubusercontent.com/49126110/185943805-10d74fbc-5d40-4f8a-b9ab-31887234abd3.gif)

**Comment by MayaKirova** [comment]
@RivaIvanova 
This seems to be already fixed. Probably fixed as part of https://github.com/IgniteUI/igniteui-angular/issues/11941
Seems that the error reported there is the same.
