### ISSUE TITLE
Row/cell double click event

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1201]
### Description  
I would like to see some enhancements regarding row/cell selection, namely the ability to detect if a row/cell, is double clicked or right clicked.

### Result  
Only rowSelectionChanged event available

### Expected result  
rowDblclick and rowRightClick events

**Comment by kdinev** [comment]
@Eralmidia We've exposed events for both cell click and cell context menu. The corresponding row can be extracted from the cell in the event arguments. Both are available in `version: 5.3.0`.

https://github.com/IgniteUI/igniteui-angular/tree/master/src/grid#outputs 

We can expose a double click event as well. We already handle it for editing and we can start emitting from it.

**Comment by kdinev** [comment]
@Eralmidia Would you like the double click event in a patch for 5.3, or in 5.4?

**Comment by Eralmidia** [comment]
There is no rush. Until you implement row editing in the grid, we can't really use it, so 5.4 is fine :)

**Comment by zdrawku** [comment]
@Eralmidia, we have added dblClick event emitter from the click event right after we set edit mode of the cell (Currently on PR for 6.0.x). Reference to the double clicked cell is provided, from where you can access the row object.

As for the Row Editing in the grid, we do not plan do add this feature for now, so I hope that this new change will suit your needs. (@SlavUI correct me if I am wrong)

If you have concrete scenario that you want to cover, please do let me know.
