### ISSUE TITLE
Tabs dont have box shadow

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-angular#12018]
## Description  
My tabs dont have boxshadows anymore

 * igniteui-angular version:      "@infragistics/igniteui-angular": "14.0.12",
 * browser:  chrome

## Result  
What is the actual result after following the steps to reproduce?

![image](https://user-images.githubusercontent.com/759253/186738962-921f718a-b8c5-41de-943a-00e99cef29c5.png)

## Expected result  
What is the expected result after following the steps to reproduce?

![image](https://user-images.githubusercontent.com/759253/186738853-137dae5a-13c9-4725-be82-cb73af70af21.png)

## Solution for other who have this problem

```
$custom-tabs: tabs-theme(
  $item-text-color: $custom-text-color,
  $item-background: $custom-background-color,
  $item-active-color: $primary,
  $item-active-icon-color: $primary,
  $item-active-background: null,
  $indicator-color: $primary,
  $disable-shadow: false
);

@include css-vars($custom-tabs);

// hack to get box-shadow on tabs
%tabs-display {
  box-shadow: var-get($custom-tabs, 'tab-area-shadow');
}
```

## Solution for igx team

![image](https://user-images.githubusercontent.com/759253/186739220-f4789d1e-03f7-4efc-872d-8e5e8fee3746.png)

**Comment by SisIvanova** [comment]
Hi @ricardosaracino,

The box-shadow has been removed by design because of another issue with the Tabs component - #11479. We are also going to remove the `$disable-shadow` property from the Tabs theme. However, you can still use a workaround to add a box-shadow to your tabs component. For instance:

```scss
igx-tabs { 
    box-shadow: elevation($elevation: 2);
 }
```

**Comment by ricardosaracino** [comment]
@SisIvanova that is a much cleaner solution, thank you
