### ISSUE TITLE
[PivotGrid] Collapse/Expand Rows/Columns

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#12025]
## Question  

Is there a default option for collapsing/expanding rows and columns?

Example of a configuration for rows:
```
{
      memberName: 'Book',
      dataType: GridColumnDataType.String,
      sortDirection: SortingDirection.None,
      enabled: true
},
{
      memberName: 'Alt ID',
      dataType: GridColumnDataType.String,
      sortDirection: SortingDirection.None,
      enabled: true
},
{
      memberName: 'Position ID',
      dataType: GridColumnDataType.String,
      sortDirection: SortingDirection.None,
      enabled: true
}
```

![Screenshot 2022-08-29 at 12 48 02](https://user-images.githubusercontent.com/32940839/187174248-bdeb33e1-138f-4504-90df-acbc90df513e.png)

We would need to be able to do something like this:

![Screenshot 2022-08-29 at 12 55 55](https://user-images.githubusercontent.com/32940839/187175703-5d2e0b2b-0e6b-42ce-9140-1137ca20885b.png)

Same for columns:

![Screenshot 2022-08-29 at 12 57 36](https://user-images.githubusercontent.com/32940839/187176012-6c555fb8-9692-4818-9682-84d1e95c689d.png)

igniteui-angular version: 14.0.14
browser: Chrome

**Comment by MayaKirova** [comment]
@anserban

You could also nest each dimension you want to expand as a child, rather than as a sibling. For example:

```
{
            memberName: 'Book',
            dataType: GridColumnDataType.String,
            sortDirection: SortingDirection.None,
            enabled: true,
            childLevel: {
                memberName: 'Alt ID',
                dataType: GridColumnDataType.String,
                sortDirection: SortingDirection.None,
                enabled: true,
                childLevel: {
                    memberName: 'Position ID',
                    dataType: GridColumnDataType.String,
                    sortDirection: SortingDirection.None,
                    enabled: true
                },
            }
        }
```
Same for columns.
Only difference is that they will expand/collapse below the parent, rather than next to it.

**Comment by anserban** [comment]
Thank you for the samples.

By chance, would be possible to have it also as a default behavior (like in the screenshots attached), without having to specify hierarchies in the configuration? Or would imply significant changes on the pivot's architecture?

**Comment by dkamburov** [comment]
Unfortunately, yes, supporting this will require significant changes. Expand states are based on the hierarchy of a dimension. Currently a dimension can only expand or collapse it's child and there is no way to declare a child without defining a hierarchy.

**Comment by dkamburov** [comment]
If you have any further questions, please re-open the discussion.
