### ISSUE TITLE
.igx-grid__tbody-content: aria-activedescendant attribute not allowed for an element's role

### ISSUE THREAD

**Issue by polohe** [IgniteUI/igniteui-angular#12038]
## Description  
Based on Accessibility Insights for Web, the following elements are not compliant.

element.
igniteui-angular version: 13.2.9
browser: any

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Install the Accessibility Insights extension for chrome
2. Create an example igx-grid table with columns, paginator and toolbar
3. Run the FastPass check from the notification Launch Pad

## Result  
What is the actual result after following the steps to reproduce?
![image](https://user-images.githubusercontent.com/112661337/188011688-2bae2602-0e4d-44ea-82ac-77ce89055d81.png)

## Expected result  
What is the expected result after following the steps to reproduce?
There should not be failed instances

## Attachments  
Example igx-grid
![image](https://user-images.githubusercontent.com/112661337/188012868-1b9e73da-7597-4699-8c0d-f6fd3cce38bf.png)

**Comment by GibletJr** [comment]
Could someone provide an update on this bug as it was assigned 6 weeks ago.

**Comment by polohe** [comment]
Is there an update regarding this bug?
