### ISSUE TITLE
Option to set drop-down and drop-down-item aria-label

### ISSUE THREAD

**Issue by adi130987** [IgniteUI/igniteui-angular#12047]
## Is your feature request related to a problem? Please describe.
I need to be able to set the drop-down and drop-down-item components aria-label attributes and override default values. 

## Describe the solution you'd like
I would like to have a setter for `ariaLabel` property for these components (and not only, this might be also useful to other components) to allow me to set aria-label value as I want. 

```html
<igx-drop-down #dropdown [ariaLabel]="'drop_down_custom_label' | translate">

<igx-drop-down-item [value]="someValue" [ariaLabel]="'drop_down_item_label' | translate">

```

## Additional context
Drop-down aria-label is now set to id attribute value. 
Drop-down-item aria-label is set by default to the value of the item or the id attribute (is no value is set).
Using the id is not an option, just consider that the text for aria-label needs to be user friendly, it might be translated. Same thing applies to the value, which can be different from the label of the drop-down-item.

**Comment by ddaribo** [comment]
Hello @adi130987,

As of version 14.0.0 of Ignite UI for Angular the `label` attribute of the `IgxDropDown` has been changed to `aria-labelledby` and can be set by the input property `labelledBy`. For more info, please refer to our Changelog [here](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#1400). I would suggest upgrading to version 14 to take advantage of this.

[Here ](https://stackblitz.com/edit/igx-drop-down-set-labelled-by?file=src/app/dropdown-sample-1/dropdown-sample-1.component.html)is also a small sample demonstrating this.

Regarding the second requirement about setting the `aria-label` of the `IgxDropDownItem`, [this PR](https://github.com/IgniteUI/igniteui-angular/pull/12131) will address it.
