### ISSUE TITLE
Having row selection and row styles on the same grid does not work as expected

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#12052]
## Description  
When both properties are set on the same grid, the selection of the row does not work as expected. This reproduces in all grids.

 * igniteui-angular version: 14.1.x, 14.0.x, 13.2.x
 * browser: 

## Steps to reproduce  

1. Open any dev sample (for example row adding)
2. Add these to the grid template
```
[rowSelection]="'multiple'"
[rowStyles]="rowStyles"
```
3. In the component add 
```
public rowStyles = {
        background: (row: RowType) => row.cells[0].value === 'ALFKI' ? '#FF000033' : '#00000000'
    };
```
4. Try to select some other row

## Result  
Observe that once `rowStyles` are set the row selection does not work at all.

## Expected result  
The row selection should work as expected.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by hanastasov** [comment]
IIRC, `rowStyles` pipe is not triggerred on selection change. This is expected behavior. @ddincheva please confirm this statement.

**Comment by mddragnev** [comment]
@hanastasov 
You are right, I have checked it and because selection styles are set as `ngClass` and rowStyles as `ngStyle` the second takes place because it is set directly as a inline style to the element. I have checked that the API works as expected so I will close this issue.
