### ISSUE TITLE
Reopening the tooltip in grid applies different colors 

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#12060]
## Description  
The tooltip in grid gets different color for its text when opened for a second time.

 * igniteui-angular version: n/a
 * browser: n/a

## Steps to reproduce  

1. Open the attached sample
2. Delete a value from a required column to trigger the validation
3. Apply invalid changes
4. Hover tooltip to see the message
5. Hide the tooltip
6. Show it again

## Result  
Reopening the tooltip in grid applies different colors 
![tooltip](https://user-images.githubusercontent.com/1182001/189385852-a2a40844-aa3a-438e-a0ab-a088108b4959.gif)

## Expected result  
The tooltip should be use the same color, when opened again

## Attachments  
[3ov2wi--run.zip](https://github.com/IgniteUI/igniteui-angular/files/9536704/3ov2wi--run.zip)

**Comment by damyanpetev** [comment]
Likely one of the open configs is missing an outlet as goes outside the grid scope with the customized color
