### ISSUE TITLE
Excel Library - Sorting doesn't work in the way as specified by SortingDirection.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#12063]
## Description  
Excel Library - Sorting doesn't work in a way as specified by SortingDirection.

 * igniteui-angular version: 14.0.16
 * igniteui-angular-excel: 14.1.1
 * browser: Any

## Steps to reproduce  

1. npm install and npm run build-serve the attached sample and open it in a browser.
2. Click the "file choose" button and choose Book1.xlsx in the attached zip.
-> Wait until Book2.xlsx is downloaded.
3. Open the downloaded Book2.xlsx and see the Birthday column.

## Result  
The data is sorted in an descending order.

## Expected result  
The data should be sorted in an ascending order.

## Attachments  
[kb9030-angular-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/9546409/kb9030-angular-app1.zip)

## Some notes
Similarly, if you set SortingDirection.None, the data is sorted in an ascending order.
And also, if you set SortingDirection.Desc, an error which says that the value is not valid occurs.

**Comment by onlyexeption** [comment]
@norikois,
You should use the [`SortDirection`](https://www.infragistics.com/products/ignite-ui-angular/api/docs/typescript/latest/enums/sortdirection.html) enum  from 'igniteui-angular-excel' instead of `SortingDirection` as they have opposite values from one another.
