### ISSUE TITLE
Scrollbars get clipped when zoomed

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#1207]
### Description  
Describe the issue.

### Steps to reproduce  

1. Got to here in Chrome: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html
2. Zoom to 67% 

### Result  
Scrollbars get clipped and the vertical scrollbar pulls away from the horizontal scrollbar

### Expected result  
Scrollbars should always show correctly. 

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![scrollbar clipping](https://user-images.githubusercontent.com/19844934/39477725-201b1590-4d2e-11e8-87d8-d1ff8794b960.png)

**Comment by MikeTechSpeak** [comment]
FYI, I will be demoing this sample at MSBuild next week. And we generally had to zoom it to have it properly visible on the monitor at ngConf so it was glaringly obvious to anyone we demo'ed our product to.

**Comment by kdinev** [comment]
The scrollbars adjust properly on edge, but do not respond to zoom level on chrome. Closing this as a 3rd party issue.
