### ISSUE TITLE
Navigation bar background color - has it changed with 14.1.0?

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#12078]
The style received for navbar with

**14.0.5**

https://appbuilder.indigo.design/api/taas?schema=dark-fluent-schema
https://appbuilder.indigo.design/api/taas?schema=light-fluent-schema

```css
igx-navbar{--background: var(--igx-navbar-background, hsla(var(--igx-primary-500), var(--igx-primary-a)));
```

**14.1.0**

```css
igx-navbar{--background: var(--igx-navbar-background, hsla(var(--igx-surface-500), var(--igx-surface-a)));
```

https://appbuilder-dev.indigo.design/api/taas?schema=dark-fluent-schema
https://appbuilder-dev.indigo.design/api/taas?schema=light-fluent-schema

 * igniteui-angular version: 14.1.0

This results for different background color on navbar:
![image](https://user-images.githubusercontent.com/14248932/190165796-805b272b-8d3e-4910-b42b-935ca5653aa3.png)

**Comment by didimmova** [comment]
Yes, we've changed the fluent navbar background to be surface by design in [this PR](https://github.com/IgniteUI/igniteui-angular/pull/11972)
