### ISSUE TITLE
Cannot resize igx-Grid columns on a Touch Device.

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#1209]
### Description  
I cannot resize columns on a touch device with finger - iPad / iPhone / Android device.

### Steps to reproduce  

Select a column, attempt to resize in a TOUCH environment.

### Result  
Nothing happens.

### Expected result  
I should be able to resize columns based on finger in touch environment.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by bkulov** [comment]
I'm closing this issue as currently igxGrid is not designed to support column resizing via TOUCH events.
