### ISSUE TITLE
Make the row adding snackbar optional. 

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#12090]
Currently the row adding snackbar has two issues:

1. It cannot be disabled
2. It shows even when the added row is in view (only its button is hidden)

Change the current UX by adding an option to disable the snackbar and also make the whole snackbar not appear when the row is in view

**Comment by jberes** [comment]
@brianlagunas  can you also comment on how this works in the WPF grid.

**Comment by brianlagunas** [comment]
There are no built-in popups in the WPF grid when CRUD operations are invoked. If a notification is needed, the developer will add it. In my last 15 years of developing enterprise applications, notifications have never been built directly into a grid. Let alone notifications that cannot be controlled/disabled.

**Comment by dkamburov** [comment]
We can go with introducing new option `showRowAddSnackbar: false` by default. And should be considered as a breaking change as well.

**Comment by dkamburov** [comment]
Are we talking for hiding the snackbar **only when the added row is in the current view** or should be hidden even when the row is outside the view?

If the row is outside the view there is also a button that allows you to scroll to it, without it the user will "loose" their newly added row.
