### ISSUE TITLE
Error: unknown arguments: grid, newGrid

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#12129]
## Description  
Error is through while using angular schematics

 * igniteui-angular version:14.1.1 
 * browser: 

## Steps to reproduce  

Step 1 - npm i -g @igniteui/angular-schematics
step 2 - npm i -g @angular/cli
step 3 - ng new SampleApp1
step 4 - ng add igniteui-angular
step 5 - ng g @igniteui/angular-schematics:c grid newGrid

## Result  
![image](https://user-images.githubusercontent.com/11193764/192134785-915042a1-8cbd-445a-bdb8-186be01ad642.png)

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
Using the entire command instead of the alias works:

```
ng g @igniteui/angular-schematics:component grid newGrid
```

I will create a new custom ng schematic to investigate the root of the problem.

**Comment by Lipata** [comment]
I have logged this [issue](https://github.com/angular/angular-cli/issues/24518) in @angular/cli repo, and expect either a fix or a suggestion for properly configuring the schematic because there is a change since angular 14.
