### ISSUE TITLE
Title and subtitle colors in current step in Stepper are wrong in Bootstrap

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/igniteui-angular#12123]
## Description  
The title and subtitle colors in the current step in Stepper have to be primary.500. But when step 2 is current, they are with gray colors.

## Attachments  
<img width="270" alt="Screen Shot 2022-09-21 at 3 45 18 PM" src="https://user-images.githubusercontent.com/61508933/191507214-03b398b7-04b4-477a-83d6-ebd38163c437.png">

**Comment by desig9stein** [comment]
@YoannaIvanova This happens only if the step has **completed** and **current** flags on it, then the title and subtitles use the gray color. Do I need to fix it anyway? If Yes, I suggest making a meeting so we can clarify the colors for all combinations: current/selected, error/selected, optional/ selected, e.t.c.

**Comment by YoannaIvanova** [comment]
> @YoannaIvanova This happens only if the step has **completed** and **current** flags on it, then the title and subtitles use the gray color. Do I need to fix it anyway? If Yes, I suggest making a meeting so we can clarify the colors for all combinations: current/selected, error/selected, optional/ selected, e.t.c.

After a discussion, we decided that title and subtitle in the current completed, and current incompleted steps should be the same colors - grays.900 for title color and grays.700 for subtitle color.
