### ISSUE TITLE
Automatic scroll to igx-radio when patchValue() in formGroup

### ISSUE THREAD

**Issue by hieunm13** [IgniteUI/igniteui-angular#12136]
## Description

When I patchValue() in FormGroup, verticalScroll auto scroll to igx-radio element.

 * igniteui-angular version: 13.1.14, ^14.1.0
 * browser: Chrome

## Steps to reproduce 

I have an [example](https://stackblitz.com/edit/angular-kmg26s?file=src%2Fapp%2Fradio-group-sample%2Fradio-group-sample.component.html,src%2Fapp%2Fradio-group-sample%2Fradio-group-sample.component.scss,src%2Fapp%2Fradio-group-sample%2Fradio-group-sample.component.ts) to reproduce.

## Result

verticalScroll auto scroll to igx-radio element.

## Expected result

verticalScroll do not scroll.

**Comment by loclv** [comment]
I have the same problem.

**Comment by hieunm13** [comment]
Can you please fix in igniteui version 13.1.14?

**Comment by hieunm13** [comment]
@SisIvanova I saw that PR is not merged already in version 13.2

**Comment by hieunm13** [comment]
> @hieunm13 We've just made a new PR targeting version 13.2 since this is the version of IgniteUI that we support.

@SisIvanova I saw that PR is not merged already in version 13.2
