### ISSUE TITLE
When tabbing into a cell (in edit mode) the contents of the cell should be selected so you can easily edit the value

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-angular#12159]
## Steps to reproduce  

1. go to cell editing sample: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing#angular-grid-cell-editing-and-edit-templates-example
2. double click in cell in product column
3. tab to next cell
4. type 9

## Result  
9 is appended to the value currently in the cell

## Expected result  
9 replaces the value currently in the cell

**Comment by hanastasov** [comment]
Related to #11851

**Comment by hanastasov** [comment]
This can be achieved using a template currently:

```html
    <igx-column field="ProductName" header="ProductName" [dataType]="'string'">
      <ng-template igxCellEditor let-cell="cell">
        <igx-input-group>
          <input
            igxInput
            [igxTextSelection]="true"
            [igxFocus]="true"
            [(ngModel)]="cell.editValue"
          />
        </igx-input-group>
      </ng-template>
    </igx-column>
```


Checkout this [stackblitz sample](https://stackblitz.com/edit/angular-g5makt-zardkh?file=src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.html).
