### ISSUE TITLE
The colors of the selected year and month in the Calendar should be changed

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/igniteui-angular#12150]
## Description 
The background and text color of the selected year and month should look like the selected day in the Calendar: text with black color and background with secondary.500 color. For both light theme and dark theme of Material.

## Attachments 
<img width="1456" alt="Screen Shot 2022-09-30 at 1 35 57 PM" src="https://user-images.githubusercontent.com/61508933/193252238-9b48e566-3d7c-40b5-9ab3-9e0ee6a4d9e7.png">

**Comment by simeonoff** [comment]
I believe this is related to https://github.com/IgniteUI/igniteui-angular/issues/10400
