### ISSUE TITLE
editing should start on keypress 

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-angular#12160]
## Describe the solution you'd like
when you are in a cell but it is not currently in edit mode, if you start typing the cell should go into edit mode and the value types should replace the value previously in the cell

**Comment by ddincheva** [comment]
Hello @IGvaleries ,
This is not a feature that the grid currently supports or plans to support as a default behavior but it can be achieved really easily with a small amount of custom logic. 
[Here is a sample](https://stackblitz.com/edit/angular-hh7uwl-gvxzok?file=src/app/grid/grid-batch-editing/grid-batch-editing-sample.component.ts) with this behavior implemented, please take a look and let me know if you have any additional questions.
