### ISSUE TITLE
Financial Chart issue with formatLabel method

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#12178]
I am having an issue with formatLabel method in the financial chart component. 

I have set formatLabel function as :- 
`formatLabel = (value) => {
return value + ' JPY';
}`

I have also set yAxisAbbreviateLargeNumbers to true. It interferes with formatting by appending **'K'** to the formatted value.

![image](https://user-images.githubusercontent.com/79090369/195082038-96d9b54f-9372-4330-82e1-ad906bc854b9.png)

I want the formatting on Y-Axis to show `2.20K JPY`.

Is there any way to do that?

**Comment by agoldenbaum** [comment]
Hello KaushikEDS,

When using the **yAxisAbbreviateLargeNumbers** property and setting it to true and providing my own value to the **formatLabel** event, I am currently seeing a behavior where the Y-Axis abbreviation no longer shows? This seems to be a difference between the behaviors we are seeing, although I wonder if this has to do with a difference in Angular versions we are targeting. I am currently targeting version **14.1.0** of the Ignite UI for Angular packages.

Regardless, it appears that the **yAxisAbbreviateLargeNumbers** property is trying to place a suffix on the label of the Y-Axis. If you would like to have your abbreviation appear as 2.20K JPY, my best recommendation at the moment would be to set **yAxisAbbreviateLargeNumbers** to **false**, and check if the value in the **formatLabel** event is greater than 1000. If it is, you can divide the value by 1000 and add “K JPY” to format it in the way you are looking to format.

Please let me know if you have any other questions or concerns on this matter.
