### ISSUE TITLE
IgxSpreadhseet not displayed in IgxTabs content

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#12184]
## Description  
When an `IgxSpreadsheetComponent` is placed within an `IgxTabContentComponent` it is not displayed correctly.

 * igniteui-angular version: Tested with latest; igniteui-angular `14.2.0` and igniteui-angular-spreadsheet `14.1.2`
 * browser: any

## Steps to reproduce  

1. Open [this sample](https://stackblitz.com/edit/igx-spreadsheet-in-igx-tabs?file=src/app/tabs-sample-3/tabs-sample-3.component.html)

## Result  
Only the cell selection dropdown appears.
For reference, there is a spreadsheet out of the tabs, which is displayed alright.

## Expected result  
To display and interact with the spreadsheet correctly.

## Attachments  
![image](https://user-images.githubusercontent.com/35433937/195305887-806fd74c-6a2c-4cfa-92d8-fe79bdf95b06.png)

**Comment by igandrews** [comment]
This seems like a timing issue in the spreadsheet and when its trying to extract some styling info. You can work around this for now by invoking the `styleUpdated`. 
e.g. 
```typescript
  ngAfterViewInit(): void {
    const excelFile = 'https://static.infragistics.com/xplatform/excel/SalesData.xlsx';
    ExcelUtility.loadFromUrl(excelFile).then((w) => {
      this.spreadsheet.workbook = w;
    });
    ExcelUtility.loadFromUrl(excelFile).then((w) => {
      this.spreadsheet1.workbook = w;
    });

    // temporary workaround to ensure the ss has the current style info
    window.setTimeout(() => {
      this.spreadsheet1.styleUpdated();
    }, 0);
  }
```

**Comment by ddaribo** [comment]
Closing this issue, as it has been fixed by @igandrews and verified by @IGvaleries for the `igniteui-angular-spreadsheet` and will enter the upcoming release.
Thank you!
