### ISSUE TITLE
type definition - `ISelectionEventArgs.oldSelection` can be undefined

### ISSUE THREAD

**Issue by loclv** [IgniteUI/igniteui-angular#12186]
## Description  

`ISelectionEventArgs.oldSelection` can be `undefined` at first time selection.

But type definition of it is:

```ts
export interface ISelectionEventArgs extends CancelableEventArgs, IBaseEventArgs {
    oldSelection: IgxDropDownItemBaseDirective;
    newSelection: IgxDropDownItemBaseDirective;
}
```

This means, the source-code below is valid, but acctually an error has occurred at runtime.

```ts
        if (event.oldSelection.value === 'xxx') {
            // do something
        }
```

> ERROR TypeError: Cannot read properties of undefined (reading 'value')

The corrected code:

```ts
        if (event.oldSelection?.value === 'xxx') {
            // do something
        }
```

 * igniteui-angular version: "^14.2.0", "13.1.14"
 * browser: All

## Steps to reproduce  

0. Access the [Demo](https://stackblitz.com/edit/angular-qte5gn?file=src/app/select-sample-1/select-sample-1.component.ts)
1. Step 1: Select "Apple", output is:

```txt
oldSelection:
newSelection: [object Object]
selectionChangingCount: 1
```

2. Step 2: Select "Banana", output is:

```txt
oldSelection: [object Object]
newSelection: [object Object]
selectionChangingCount: 2
```

## Result

`oldSelection` is undefined at the first time selection.

## Expected result

At type definition, oldSelection can be undefined.

```ts
export interface ISelectionEventArgs extends CancelableEventArgs, IBaseEventArgs {
    oldSelection?: IgxDropDownItemBaseDirective;
    newSelection: IgxDropDownItemBaseDirective;
}
```

## Attachments  

![Screenshot from 2022-10-12 18-45-50](https://user-images.githubusercontent.com/6302717/195568148-2881d150-0dc2-419a-b9a3-2183ce98c0ef.png)

**Comment by hanastasov** [comment]
Thanks for reporting that @loclv. We will have this fixed either using your suggestion or by making `oldSelection` always defined.
