### ISSUE TITLE
Column Summaries Need Default Formatting

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#1221]
### Description  
By default, column summaries should be formatted

### Result  
Numbers do not have formatting (for example, 450000433, instead of 450,000,433

### Expected result  
All numbers should be formatted by default

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![column-summaries](https://user-images.githubusercontent.com/18453092/39522533-87d9b95e-4de0-11e8-92b0-859fb874e74e.PNG)

**Comment by zdrawku** [comment]
Hey @jberes, @mpavlinov already logged such a request, we are going to have a meeting to decide what would be the default formating not only for the summaries rather to all numeric formats within the grid.

Related to - https://github.com/IgniteUI/igniteui-angular/issues/1197
