### ISSUE TITLE
Input properties in elements grid are always in string format

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#12211]
## Description  
Input properties in elements grid are always in string format. For boolean and numeric values this can cause issues.

An example can be in the following draft - the MRL calculations are messed up and needs to make sure the values are numbers - https://github.com/IgniteUI/igniteui-angular/pull/12205

Some boolean checks can translate "false" to true.

In Angular there is no need of additional type checks and parsing, so if this could be handled elements grid on higher level and the props can produce their proper value type it'd be great.

**Comment by damyanpetev** [comment]
Both numeric and boolean props have been updated with https://github.com/IgniteUI/igniteui-angular/commit/4fdebd8bc82dd9e6aae4c19bbb0a6bebe6c5413b and https://github.com/IgniteUI/igniteui-angular/commit/4b78dbc6b962a0fe18accbc750363d2f34d4c4b6 respectively and appear to be working fine now.

Closing this and @dkamburov I guess you can drop your draft PR too
