### ISSUE TITLE
[DataGrid] Custom Summaries with Group By

### ISSUE THREAD

**Issue by anserban** [IgniteUI/igniteui-angular#12247]
We have the following situation - we need to get the summaries for all grid data and for all subgroups (if the user performs group by) from server and then set them using the custom summaries class.

I've managed to do this without group by.
Once the user performs group by, in the "operate" method, I would also need the group path for the respective data that I'm receiving there.

![Screenshot 2022-10-28 at 19 24 48](https://user-images.githubusercontent.com/32940839/198686071-27e30ca8-8d34-4884-ac76-1e2102b6cd58.png)

In the example above, the group paths would be:
- "Argentina", for the first level summary.
- "Argentina"->"Buenos Aires", for the second one.

In this way, I would know which summary to get from the server's response and apply it in the "operate" method.

Is there a way that I can currently get this information or having it available as a property in the upcoming versions?

igniteui-angular version: 14.2.3
browser: Chrome

**Comment by anserban** [comment]
In order to plan some of our current development tasks, we would need a confirmation that this can be achieved in a future version.

**Comment by anserban** [comment]
Thank you!:D
That's great news for us.

**Comment by hanastasov** [comment]
Hello @anserban , this feature is implemented for flat grid now (not available for TreeGrid and HierarchicialGrid). Please monitor the next version release, which I believe will happen tomorrow, 3rd January 2023 to test it.

**Comment by hanastasov** [comment]
@anserban , Version 14.2.12 -> https://github.com/IgniteUI/igniteui-angular/releases/tag/14.2.12 contains the fix.
