### ISSUE TITLE
Hierarchical Grid dynamic row islands can remove auto-generated columns

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#12252]
## Description  
If the top level H Grid is loaded with auto-generated columns and row layouts are added with delay, their possible columns trigger the columns list update handling, and since the root list is empty - the empty list gets assigned to the internal grid collection, essentially deleting the generated columns.

This is related to #12251 and to do with the same handling block. Still, quite a lot of stars to align for this one, thus the low prio.

 * igniteui-angular version: 15.0.x
 * browser: N/A

## Steps to reproduce  

1. Use the sample attached to #12251
3. Set `autoGenerate` to true on the HGrid so the grid renders all columns initially
4. Open the sample
5. Hit the Toggle child layouts button

## Result  
After child layouts are enabled the grid ends up empty

## Expected result  
The grid columns and layouts should render correctly

**Comment by skrustev** [comment]
@damyanpetev 
I was able to reproduce it only in the elements branch, not sure if this was initially logged for it, but that's why for now the fix is there.
There was another issue with the rows not rendering when initially there are only columns set for the  hierarchical grid without layouts. This is also addressed.

**Comment by damyanpetev** [comment]
@skrustev There are repro steps with the sample for the related issue, so I believe it did reproduce in some Angular version before. It's quite possible the fix for the first issue resolved this as well though, and it's just the workaround that was left in the Elements branch as something I didn't notice while merging. If that's the case, I'd still mark this as already resolved by the original PR **AND** add a test covering it so we can actually call it done.

After which, all left to do is cleanup the workaround left in the Elements branch (which you pretty much did as far as I can see)
