### ISSUE TITLE
igx-grid column dataType="image"

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#12255]
## Is your feature request related to a problem? Please describe.
I would like to have default handling for an image column. 

## Describe the solution you'd like
I should be able to define the following type of column:

```html
<igx-column dataType="image" field="imageSourcesField"></igx-column>
```

The grid should disable filtering, sorting, grouping, editing and summaries for this column by default, but should allow for custom strategies to be provided, if the user knows how to sort/filter/group the image column.

## Describe alternatives you've considered
Currently, I can pass a template, which renders the images, but I also have to turn off all the rest of the features for the column manually.

## Additional context
This type of column is just for ease-of-use. It can be achieved with the available features, but this requires more configuration on the developer side.

**Comment by kdinev** [comment]
@zdrawku @damyanpetev @hanastasov The [spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxGrid-Column-Data-Types-and-Templates-Specification) has been updated. Take a look at post comment, if there's any, Meanwhile I'm proceeding with the implementation on the current state, and I'll adjust if there's comments that come in later.

**Comment by hanastasov** [comment]
> The [spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxGrid-Column-Data-Types-and-Templates-Specification) has been updated. Take a look at post comment, if there's any, Meanwhile I'm proceeding with the implementation on the current state, and I'll adjust if there's comments that come in later.

Shall we allow custom filtering/sorting strategies for image column or not? Spec is saying:

![image](https://user-images.githubusercontent.com/14248932/202233686-2bf0dfee-6485-4f67-844f-579d7a26abeb.png)

which did not convince me in one or the other.

**Comment by kdinev** [comment]
@hanastasov Disabled unless custom strategies are provided. If I know how to filter/sort them, then I'll provide strategies, in which case I should be able to enable the features back on.
