### ISSUE TITLE
Bootstrap button outline problem

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#12267]
## Description  
The bootstrap theme has a blue outline around all button types. Since the outline goes around the outside edge of the button, sometimes when the button is close to other elements on the page, the outline gets cut off.

## Steps to reproduce  
1. Open this sample [Grid filtering](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering)
2. Switch to Bootstrap theme through the theming widget.
3. Press the filter chip and add at least 2 filter
4. observe the "And" and "or"  buttons between the filters

## Result  
The button outline is cut off

## Expected result  
The button outline should not be cut off

## Attachments  
<img width="1095" alt="Screenshot 2022-10-26 at 11 23 15" src="https://user-images.githubusercontent.com/21260963/197973908-1ce7f0e0-c511-4bff-8222-469fa66e9858.png">

**Comment by sdimchevski** [comment]
For the different densities of the grid we may need to have different min-height values for the button. Suggestion for min-heights of the button:

comfortable grid ->  2.5rem,
cosy grid -> 1.875rem,
compact grid -> 1.3125rem
