### ISSUE TITLE
Grid: support time strings

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12285]
## Is your feature request related to a problem? Please describe.
If you set a grid column to `time` type, the data must contain a date.

Example:
```html
<igx-column [field]="'value'" [dataType]="'time'">
</igx-column>
```
```typescript
// works
data = [ { time: '2022-11-01T15:00:00' } ]
// doesn't work
data = [ { time: '15:00:00' } ]
```

## Describe the solution you'd like
It would be nice if time strings were supported.

**Comment by kdinev** [comment]
Closing this issue for now. If there's further comments, please reopen it.
