### ISSUE TITLE
IgxGrid: lessThanOrEqualTo and greaterThanOrEqualTo filters for date/dateTime columns

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12295]
## Is your feature request related to a problem? Please describe.
If you want to filter a `date` or `dateTime` column with `lessThanOrEqualTo` or `greaterThanOrEqualTo` you have to combine two filters (`equals` and `before`/`after`).

## Describe the solution you'd like
It would be easier if there was a `lessThanOrEqualTo` and `greaterThanOrEqualTo` filter for `date` and `dateTime` columns.

**Comment by ddaribo** [comment]
Hi @Timmeeeey,

The [Custom Filtering Operands](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering#custom-filtering-operands) feature allows you to customize the filtering operands by altering the existing or creating new ones.

Thus, your requirement could be achieved by either modifying the logic function and optionally the name of the existing ‘after’/’before’ operations to compare with the “>=”/”<=” operators, or add a custom operand and define your own logic/names, etc.

[Here](https://stackblitz.com/edit/igx-grid-filter-dates-after?file=src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts) you can find a StackBlitz sample demonstrating these approaches.
