### ISSUE TITLE
The space between the checkbox and the label is incorrect in the Fluent theme

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/igniteui-angular#12307]
## Description  
The space between the checkbox and the checkbox label should be 8px, not 7px as it is currently.

**Comment by simeonoff** [comment]
Inspecting the margin in the fluent theme, it is 0.5rem or 8px.

![image](https://user-images.githubusercontent.com/4118303/202395986-7f912316-545c-4515-befc-52e802ce56cd.png)

**Comment by YoannaIvanova** [comment]
> Inspecting the margin in the fluent theme, it is 0.5rem or 8px.
> 
> ![image](https://user-images.githubusercontent.com/4118303/202395986-7f912316-545c-4515-befc-52e802ce56cd.png)

I see it's 7px in "Computed". Am I looking in the wrong place?
<img width="926" alt="Screenshot 2022-11-17 at 5 47 46 PM" src="https://user-images.githubusercontent.com/61508933/202493689-a19a3dc0-6798-4806-a4d6-f42cbe94ef97.png">
