### ISSUE TITLE
Last column header is a bit wider than the cells

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#1230]
### Description  
Last column header is a bit wider than the cells.

### Steps to reproduce  

1. Go to [https://stackblitz.com/edit/angular-d6mf92](https://stackblitz.com/edit/angular-d6mf92)
2. Observe last column header and cells.

### Result  
Header is wider than the cells.

### Expected result  
Header and cells are equal in width.

**Comment by hanastasov** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/1115

**Comment by bkulov** [comment]
I'm closing this issue because it's a duplicate of #1115.
