### ISSUE TITLE
Grid columns are not auto-sized on initial load when using async data

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#12312]
## Description  
Grid templated columns are not auto-sized on initial load when using async data

 * igniteui-angular version: latest
 * browser: any

## Steps to reproduce  

1. Open the [sample ](https://stackblitz.com/edit/angular-u7oqer?file=src%2Fapp%2Fgrid%2Fgrid-nested-data-binding-2%2Fgrid-nested-data-bind2.html,src%2Fapp%2Fgrid%2Fgrid-nested-data-binding-2%2Fgrid-nested-data-bind2.ts)
2. Wait for the grids to load
3. First grid is loaded fine
4. Look at the second grid, there is a column template that is overlapping the near column

## Result  
The template column is overlapping the near column

## Expected result  
The template column to be auto-sized initially

## Attachments  
![image](https://user-images.githubusercontent.com/11193764/201957415-470e3bcc-33c8-4835-ba9c-ca30616cb85b.png)

## Note
Please consider performance degradations upon implementation. Look at the finjs sample for a testing point of too many templated columns.

**Comment by pmoleri** [comment]
Workaround:
```
    (dataChanged)="grid.columnList.forEach(c => c.autosize());"  // probably should check which columns are meant to autosize
```

To consider:
 - Always compute autosize columns after first load, i.e. when data changes from null to something
 - Compute autosize each time data changes. This might be expected for users who asked for autosize.
    This might affect performance, e.g. when having live updates every few ms, but still it should be tried, it might not be as bad.
 - Consider exposing a better public API to trigger columns autosize, something like: `grid.columnsAutosize()`

**Comment by mddragnev** [comment]
One thing that bothers me is that if we have a grid with 50+ columns which have width set to auto and live data which is changing each 500ms then column autosizing happens on each data change and this is resulting in depracation in the performance of the grid.
So in the first recording we do not autosize on each change of the data which is the way it works on live:

https://user-images.githubusercontent.com/37667452/203336542-e0b8cf8a-4969-41f6-9d9b-25732e29941b.mov

The second recording is when we autosize on each change of the data:


https://user-images.githubusercontent.com/37667452/203337435-5ce4986f-f607-48c3-b682-f66f8c2bcb4f.mov

You can see that it is lagging.
Note: Than behavior was easily reproducible in the finjs sample

So we discussed it and the aproach we are going for is that we want to autosize the columns that has width=auto each time the grid data goes from empty to filled which will fix that specific issue.
In addition, for the cases where the data source is switched to another (without first setting it to empty array or null) we expose a public api which can be invoked to autosize those columns that have width set to auto only when the customer need to.
