### ISSUE TITLE
Global Filtering doesn't respect column's pipeArgs/formatter

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#12329]
## Description  
Global Filtering doesn't respect column's pipeArgs/formatter and filters by the underlying data source.

 * igniteui-angular version: 13.2.x, 14.2.x
 * browser: any

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-xf26na-jssnnx?file=src%2Fapp%2Fdata%2Fcustom.data.ts,src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.html,src%2Fapp%2Fsample%2Figx-sample%2Figx-sample.component.ts)
2. Within the Search field type Nov 9

## Result  
All records are filtered out

## Expected result  
The record with ProductID 1 should remain

## Attachments  
![global_filtering](https://user-images.githubusercontent.com/44684385/202471101-8f050dab-9e91-4a5d-ba70-8f87c3810639.gif)

**Comment by ChronosSF** [comment]
You need to pull this to master as well.
