### ISSUE TITLE
Dependencies conflicts of @angular/cli with Angular 15

### ISSUE THREAD

**Issue by Svetloslav15** [IgniteUI/igniteui-angular#12336]
## Description  
@angular-eslint/schematics in there latest version 14.3.0 are using @angular/cli@14.2.9, 
while we are now using @angular/cli@15.0.0 and those versions are incompatible and npm install is failing
to download dependencies

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. run npm install

## Result  
What is the actual result after following the steps to reproduce?
npm install is failing to download dependencies

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular-eslint/schematics@14.3.0
npm ERR! Found: @angular/cli@15.0.0
npm ERR! node_modules/@angular/cli
npm ERR!   dev @angular/cli@"^15.0.0" from the root project
npm ERR!   peer @angular/cli@">=12" from @cypress/schematic@2.3.0
npm ERR!   node_modules/@cypress/schematic
npm ERR!     dev @cypress/schematic@"^2.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@">= 14.0.0 < 15.0.0" from @angular-eslint/schematics@14.3.0
npm ERR! node_modules/@angular-eslint/schematics
npm ERR!   dev @angular-eslint/schematics@"^14.3.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/cli@14.2.10
npm ERR! node_modules/@angular/cli
npm ERR!   peer @angular/cli@">= 14.0.0 < 15.0.0" from @angular-eslint/schematics@14.3.0
npm ERR!   node_modules/@angular-eslint/schematics
npm ERR!     dev @angular-eslint/schematics@"^14.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
## Expected result  
What is the expected result after following the steps to reproduce?
It should install required dependencies

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
@Svetloslav15 The pipelines build was waiting on an update from @angular-eslint. The alpha update is already published and the install/ci passes in the PR I've associated.
