### ISSUE TITLE
IgxGridToolbarHiding: The dropdown menu will be hidden if the Grid is scrolled horizontally and a column is being hidden through the UI

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#12331]
## Description  
When the Grid is scrolled horizontally to its end and a column is being hidden through the UI, the dropdown, where is placed the Column Hiding UI, will be hidden.

 * igniteui-angular version: 14.2.x, 13.2.x, 12.3.x
 * browser: any

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-fwgeex?file=src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-column-hiding%2Fhierarchical-grid-hiding.component.ts).
2. Scroll the grid horizontally to its end.
3. Hide a column through the Column Hiding UI.

## Result  
The dropdown, where is placed the Column Hiding UI, will be hidden.

## Expected result  
The dropdown shouldn't be hidden.

## Attachments  
![column-hiding](https://user-images.githubusercontent.com/75325639/202486708-b84a3ab2-0fe0-4dc8-b26e-73797f3aa5a3.gif)

**Comment by AYUSHKUMARGUPTA** [comment]
Hello @viktorkombov  

Shall we get an ETA on the same?

Or do you guys have any specific Bug Resolution Lifecycle time?

As currently, we are using Infragistics Hierarchal Grid for Angular and it seems that we are looking for this bug resolution urgently. 

Also, we purchased the license version for the same, let me know about the ETA and SLA for Infragistics Product.
