### ISSUE TITLE
Autogenerate dimensions and values from the data when no pivot configuration is defined

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#12366]
## Is your feature request related to a problem? Please describe.
Pivot configuration can be difficult to be defined. Autogenerating simple non-hierarchical dimensions and values from  fields of the data when no pivot configuration is defined would be a great benefit for the users. 

## Describe the solution you'd like
Additional field or a place in the data selector where those fields can be populated along side with an empty pivot grid and allow the users to pivot with the data using those autogenerated dimensions/values.

**Comment by radomirchev** [comment]
@dkamburov is that feature request still considered as part of the backlog?

**Comment by dkamburov** [comment]
I believe it is, but I don't think we'll have the time to work on it right now, as it's a rather big item
