### ISSUE TITLE
Grid row selection is inconsistent with and without primaryKey

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#12371]
## Description  
Selection API returns different types of data depending on whether `primaryKey` is set to `igx-grid`, `igx-tree-grid`, `igx-hierarchical-grid`, etc. In the case of `primaryKey` set, I get an array of primitive values. In the case of `primaryKey` not being set, I get an array of data objects behind the grid.

 * igniteui-angular version: 15.0.0
 * browser: all

## Steps to reproduce  

1. Create an app with any grid
2. Turn row selection on
3. Log `args.newSelection` on selection changing
4. Set a `primaryKey`
5. Log `args.newSelection` on selection changing

## Result  
Inconsistent results between `primaryKey` and no `primaryKey`.

## Expected result  
Consistent results. Data members should be provided in both cases.

**Comment by hanastasov** [comment]
Linking the discussion topic just for reference https://github.com/IgniteUI/igniteui-angular/discussions/12099
