### ISSUE TITLE
ng add igniteui-angular fails (Angular CLI 14)

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#12386]
## Description  
ng add igniteui-angular fails with an error "Cannot read properties of undefined (reading 'sourceRoot')"

 * igniteui-angular version: 14
 * browser: n/a
 * Angular CLI: 14.2.10

## Steps to reproduce  

1. ng new and ng add igniteui-angular

## Result  
It tries to install igniteui-angular@14.0.0.
It fails with an error "Cannot read properties of undefined (reading 'sourceRoot')"
![image](https://user-images.githubusercontent.com/33947244/204192890-fe012aa0-7f8d-4b2d-ad60-ef7f7459cf11.png)

## Expected result  
It doesn't fail and the latest igniteui-angular 14.x package are installed.

## Some notes
If you specify an igniteui-angular version in "ng add" like "ng add igniteui-angular@14.2.7", it successfully installs the igniteui-angular package. This could be a workaround for the time being.

**Comment by norikois** [comment]
Here are the "ng version" results of this PC.
===============
Angular CLI: 14.2.10
Node: 16.17.1
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.7.4

**Comment by Lipata** [comment]
@norikois I also get that error when running: `ng add igniteui-angular@14.0.0`, however with the latest 14.x version it seems to work: `ng add igniteui-angular@14.2.13`. It is also working with 15.x, so closing it with already fixed.
