### ISSUE TITLE
Igniteui-Angular pkg - 15.0.2 - sass errors in Samples Browser DV

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#12439]
![image](https://user-images.githubusercontent.com/17785923/206307294-2dec2c48-4be1-4b3d-ae3e-bebd3a4dae57.png)

https://github.com/IgniteUI/igniteui-angular-examples/tree/vnext/samples/charts/sparkline/grid

ERRORS:

./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
7 │ @use 'igniteui-theming/sass/color/functions' as color;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\igniteui-angular\lib\core\styles\themes\_core.scss 7:1  @forward
  igniteui-angular\_index.scss 1:1                                     @use
  src\styles.scss 1:1                                                  root stylesheet

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
7 │ @use 'igniteui-theming/sass/color/functions' as color;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\igniteui-angular\lib\core\styles\themes\_core.scss 7:1  @forward
  igniteui-angular\_index.scss 1:1                                     @use
  src\styles.scss 1:1                                                  root stylesheet

 * igniteui-angular version: 15.0.2
 * browser: chromium

## Steps to reproduce  

1 Run sparkline/grid sample with (PR) updates

https://github.com/IgniteUI/igniteui-angular-examples/tree/vnext/samples/charts/sparkline/grid

https://github.com/IgniteUI/igniteui-angular-examples/pull/37

## Result  
See above

## Expected result  
no errors

**Comment by mddifilippo89** [comment]
![image](https://user-images.githubusercontent.com/17785923/206307263-f216e2c4-180e-4c06-85b6-837c287f348f.png)

**Comment by gmurray81** [comment]
guessing you may just need to npm install igniteui-theming?

**Comment by kdinev** [comment]
@mddifilippo89 Hi Mike! The info is in our product's update guide: https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#from-142x-to-150x

**Comment by kdinev** [comment]
I am reopening the issue, because an `angular.json` migration can be included in the product. Also the igniteui-cli setup should include this in the CLI project `angular.json`, if it doesn't already. @Lipata @wnvko

**Comment by lalo-mx** [comment]
> Have you followed the [Update Guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#from-142x-to-150x)? You have to ensure you have this section in your angular.json file:
> 
> ```json
>     "build": {
>       "options": {
>         "stylePreprocessorOptions": {
>             "includePaths": ["node_modules"]
>         }
>       }
>     }
> ```

I have an strange behavior after that change (["node_modules"]) that any change to SCSS files is not applied on project build(Still using an older version of the file). 
After deleting the .angular folder, the changes are applied. I don't think it's an igniteui-angular issue, but have you encountered these kind of issues?

**Comment by kdinev** [comment]
@lalo-mx Hmm, haven't seen this. @simeonoff have you experienced anything like this?

**Comment by gmurray81** [comment]
@lalo-mx do you mean editing the sass under node_modules? Or in the project src area?

**Comment by lalo-mx** [comment]
> @lalo-mx do you mean editing the sass under node_modules? Or in the project src area?

In the project src area

**Comment by Lipata** [comment]
@kdinev, you are correct that migration for `ng update` is missing. For 15.0.0 we've added [such functionality](https://github.com/IgniteUI/igniteui-angular/pull/12363/files) for `ng add` schematic - you will get the `stylePreprocessorOptions` config in the `angular.json`. The same is valid for the CLI - it is already [there](https://github.com/IgniteUI/igniteui-cli/blob/0495ab2697cae9041392f6f4594f310e10662367/packages/igx-templates/igx-ts/projects/_base/files/angular.json#L39).
