### ISSUE TITLE
Excel filter rendering below neighboring grid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#12473]
## Description  
For some reason, the excel style filter doesn't seem to use the regular igx-overlay, and this causes issues when we render two grids next to each other, as the filter will render below the other grid:
![image](https://user-images.githubusercontent.com/12936286/208688553-1ad828e6-3512-4c73-ae07-7eaae76a492e.png)

 * igniteui-angular version: 14
 * browser: Chrome

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-gp1fk2?file=src%2Fapp%2Fgrid%2Fgrid-excel-style-filtering-sample-1%2Fgrid-excel-style-filtering-sample-1.component.html
2. Open the excel style filter on the left grid
## Result  
The filter is partially rendered below the right grid.

## Expected result  
The filter should not be blocked by the right grid.

**Comment by ddaribo** [comment]
Hi @Eralmidia,

Please, check out the [External Outlet section](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#external-outlet) of our Excel Style Filtering topic, where the reason behind this behavior is explained and additionally a demo showing how this case can be handled is provided.

Should you need further assistance on the matter, do not hesitate to reach out to us.
