### ISSUE TITLE
Introduce contentAppending event in the IgxOverlayService

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#12480]
## Is your feature request related to a problem? Please describe.
In the IgxOverlayService there are -ing and -ed events for open and close actions, but for contentAppend is currently provided only an -ed event. Please expose contentAppend -ing event, which should be emitted before the content is moved to the overlay. 
For example: In this way, it will allow us to make some modifications to the element which will be transferred to the overlay, and apply some additional classes and attributes based on its current position in the DOM, for example, its parent element and so on.

**Comment by wnvko** [comment]
In the newly added `contentAppending ` event we now emit `OverlayEventArgs` type. This same type was emitted and in the `contentAppended`. However, in PR including the fix `OverlayEventArgs` were extended and includes now `elementRef` and `settings`. Both this will be undefined when `contentAppended` is emitted as they are not populated there.

**Comment by hanastasov** [comment]
> In the newly added `contentAppending ` event we now emit `OverlayEventArgs` type. This same type was emitted and in the `contentAppended`. However, in PR including the fix `OverlayEventArgs` were extended and includes now `elementRef` and `settings`. Both this will be undefined when `contentAppended` is emitted as they are not populated there.

Yes, I noticed this. I felt this is ok, as those are optional. Let us know if this needs to be changed. Or, isnt actually possible to emit these in the "ed" event as well?
