### ISSUE TITLE
Grid layout is broken

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#12488]
## Description  
Describe the issue.

 * browser: all

## Steps to reproduce  

1. Open one of the following Dev samples
../gridCellAPI   or ../gridColumnActions
2. Observe the grid 

## Result  
What is the actual result after following the steps to reproduce?
![Screenshot_2](https://user-images.githubusercontent.com/34240583/210759476-3ea777aa-15b7-468f-9f8b-a866b107c6c6.png)
![Screenshot_7](https://user-images.githubusercontent.com/34240583/210759484-5acd306e-2fff-4128-9d15-1df46de9b6ee.png)

## Expected result  
What is the expected result after following the steps to reproduce?
The grid body should be sized correctly and no white space should be visible.

**Comment by simeonoff** [comment]
I addition to the above, the grid autosize sample jumps constantly.

https://user-images.githubusercontent.com/4118303/210766456-16231da2-d533-4e9d-9188-8089088c542d.mov

**Comment by ddincheva** [comment]
> I addition to the above, the grid autosize sample jumps constantly.
> 
>  Screen.Recording.2023-01-05.at.11.19.10.mov

this is logged separately https://github.com/IgniteUI/igniteui-angular/issues/12487

**Comment by skrustev** [comment]
Initial issue is related to #12249 toolbar position switched to being absolute and the group area styles seems to be not updated to reflect that.
