### ISSUE TITLE
Grid not showing on load

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1251]
### Description  
I just upgraded to the latest 5.3, and I'm having an issue with the grid. It seems like it is unable to render the grid when the page loads. If I however navigate to another route, and the back to the route with the grid, it does render. Are there any known issues with the grid regarding this?

On page load:
![image](https://user-images.githubusercontent.com/12936286/39617081-9bb06d7a-4f7e-11e8-8227-e98a2c07b8d7.png)
 On route navigation:
![image](https://user-images.githubusercontent.com/12936286/39617110-b50f489a-4f7e-11e8-991c-11341ba3a060.png)

In both cases, the following test data item is present:
![image](https://user-images.githubusercontent.com/12936286/39617172-f0579b8c-4f7e-11e8-9af2-e9099797c3c9.png)

### Steps to reproduce  
Create the following igx grid:
`<igx-grid #changeLogGrid [data]="changeLog">
    <igx-column field="Username" [sortable]="true" [editable]="false" header="Performed by" [filterable]="true"></igx-column>
    <igx-column field="LogDate" [sortable]="true" [editable]="false" header="Performed on" [filterable]="true"></igx-column>
    <igx-column field="Title" [sortable]="true" [editable]="false" header="Title" [filterable]="true"></igx-column>
    <igx-column field="Description" [sortable]="true" header="Description" [filterable]="true">
        <ng-template igxCell let-cell="cell">
            <mat-icon [matTooltip]="cell.value" (click)="handleDescriptionClick(cell.row.rowData);">textsms</mat-icon>
        </ng-template>
    </igx-column>
</igx-grid>`

**Comment by Eralmidia** [comment]
Seems to be related to flex. If I disable 
![image](https://user-images.githubusercontent.com/12936286/39618135-98de0338-4f82-11e8-9f9f-eec6c606bf18.png)
it seems to grow as it should

**Comment by Eralmidia** [comment]
Please disregard the comment about flex. Doesn't seem to work most times.

Tried to render the data in a simple table without problems, so there should be any issues with the data:
![image](https://user-images.githubusercontent.com/12936286/39619299-a3ef0ef2-4f87-11e8-9291-4b582b7699e5.png)
![image](https://user-images.githubusercontent.com/12936286/39619327-b87f5a20-4f87-11e8-96a2-c4a698ce300e.png)

**Comment by tiliev** [comment]
Hello @Eralmidia,
Thank you for reporting this issue.
I tried to reproduce it in StackBlitz, but is seems to be working - https://stackblitz.com/edit/client-grid.
Can you send us a small isolated sample so we could further investigate your scenario?
Thank you.

**Comment by Eralmidia** [comment]
Weel, the module running the grid is just a plain lazy loaded module, with a container compontent loading the data, and passing the down to a presentation component https://1drv.ms/u/s!Aulu2jLKkn-YnZ1RE-AdMKZhAWFL2A 

I have been digging in the chrome dev console, and I can see that the data is actually displayed in the HTML, so this seems to be some kind of CSS issue. If I set the width property for the columns, the headers actually show in Chrome. it does however not display the data. 
![image](https://user-images.githubusercontent.com/12936286/39626753-9479a9a2-4fa3-11e8-813b-609b3e117149.png)


Firefox still ignores the width, and displays like this: 
![image](https://user-images.githubusercontent.com/12936286/39626328-b5920ad2-4fa1-11e8-9b97-3e0ebbb54546.png) I does however display the data.

**Comment by Eralmidia** [comment]
Also, I find this kinda odd. I set the column size to 200px like so:
![image](https://user-images.githubusercontent.com/12936286/39628461-72132fcc-4fa9-11e8-8fa1-b8ed49a23108.png)

Why then is the width set to 100px?
![image](https://user-images.githubusercontent.com/12936286/39628546-b7b0794a-4fa9-11e8-81cd-432794eb4d3d.png)

**Comment by tiliev** [comment]
@Eralmidia, I'll try to run your sample and will get back to you with my findings.

**Comment by Eralmidia** [comment]
Thank you. 

It seems like the width of igx-grid thead and body is 0px for some reason. If I resize the window, it is updated to the actual size of the window, and the data is displyed, as mentiend above.
![image](https://user-images.githubusercontent.com/12936286/39629052-38f4486e-4fab-11e8-856d-3658e511ff55.png)

**Comment by tiliev** [comment]
@Eralmidia, I'm not able to run your sample since there are a lot of dependencies which are not sent, from /app/shared/ mainly. If you could send us a reproducible working sample, it would be great.

**Comment by tiliev** [comment]
@Eralmidia, I used your files to create a sample and it still works. I am attaching it to this comment. Please send us a working application demonstrating your issue.
[eralmidia-app.zip](https://github.com/IgniteUI/igniteui-angular/files/1974696/eralmidia-app.zip)

**Comment by Eralmidia** [comment]
@tiliev I have investigated this further, and it seems to be caused by a third party navigation drawer component. We will take a look at the igx navigation drawer and see if it has the features we need. Thanks for your assistance.
