### ISSUE TITLE
IgxDatePicker: ability to use an iso date string as model

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12512]
## Is your feature request related to a problem? Please describe.
The IgxDatePicker converts the selected date in a javascript `Date` object.
When you serialize this for a http request the time and timezone is included and converted to UTC.
For example if you are in the timezone UTC+1 and you select the date 2023-01-01 it gets serialized to '2022-12-31T23:00:00.000Z'.
This is a problem when the backend only expects a iso date string (YYYY-MM-DD).

## Describe the solution you'd like
It would be nice if there was a input like `[useIsoString]="true"` so that the date picker uses an iso date string (YYYY-MM-DD) as model instead of a `Date` object.

**Comment by radomirchev** [comment]
@Timmeeeey I will add the feature for a review for the next major release.
