### ISSUE TITLE
Dialog: Change close configuration after opening is not working

### ISSUE THREAD

**Issue by yl-endress** [IgniteUI/igniteui-angular#12537]
## Description  
Whenever a dialog is already opened, the close behavior cannot be changed anymore.
"closeOnEscape" and "closeOnOutsideSelect" are ignoring new incoming values.

 * igniteui-angular version: "@infragistics/igniteui-angular": "14.1.1",
 * browser: Version 109.0.5414.74 (64-Bit)

## Steps to reproduce  

1. Click the button to open the dialog
2. In the dialog, click the button to disable the close behavior
3. Press ESC-Key or click besides the dialog

## Result  
The dialog closes

## Expected result  
The dialog shouldn't close

## Attachments  
Code sample of the template part (html)
```
<button (click)="myDialog.open()">open dialog</button>

<igx-dialog #myDialog [closeOnEscape]="!disableActions"
            [closeOnOutsideSelect]="!disableActions" message="test message">
   <div class="dialog-footer" igxDialogActions>
       <button (click)="disableActions = !disableActions">Escape key and outside shouldn't work anymore</button>
  </div>
</igx-dialog>
```

in the .ts part you just need to declare the var
```
...
export class MyComponent {
   disableActions: boolean = false;
   ...
}
```

**Comment by yl-endress** [comment]
Hello @damyanpetev,
thank you for effort. Our use case is that some actions in our software must be confirmed via dialog: e.g. a delete operation. When entering the buttons/close function is allowed. As soon the operation is triggered (e.g. delete), the action is triggered on the backend side.  At this point any dialog actions are disabled afterwards (also that the operation isn't triggered twice).

Background info:
In our case, the backend performance is quite limited (cannot be changed) and depending on the operation, the execution will take a while. In this case, our UI-expert suggested to stay in the dialog as long the operation is ongoing. By this the user is enforced to stay on dialog until the operation is done (-> the user cannot trigger another operation form the current view). In case of an error, the dialog actions can be triggered again (like another attempt). In case of success, we simply close the dialog.

**Comment by radomirchev** [comment]
@teodosiah I see the bot closed the issue - is that reflecting its status?

**Comment by teodosiah** [comment]
For now, it's on hold
