### ISSUE TITLE
Explore if limiting the horizontal scroll handlers to one for all rows improves performance significantly.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#1254]
### Description  
Implement a mechanism to have only one horizontal scroll handler instead of each horizontal directive handling it seperately in the igxGrid. Test if to see if performance is significantly improved.

Related to #1191

**Comment by MayaKirova** [comment]
Branch with changes available at: https://github.com/IgniteUI/igniteui-angular/tree/mkirova/performance-improvements

Initial observations show that there is a small performance boost but it appears that the main bottle neck is not the event handler's count but the actual change detection (that forces DOM re-rendering). The changes don't appear to bring a large performance boost.

**Comment by MayaKirova** [comment]
Adding performance profiler results when scrolling horizontally on Chrome with and without the improvement on Performance sample grid (with 100% height and width) for reference:
[Profiles.zip](https://github.com/IgniteUI/igniteui-angular/files/1987450/Profiles.zip)

**Comment by mpavlinov** [comment]
This is implemented in https://github.com/IgniteUI/igniteui-angular/pull/2677
