### ISSUE TITLE
Remote Paging with Batch editing issue

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#12551]
### Description  
Describe the issue.

### Steps to reproduce  

1. Go to Remote Paging with Batch editing sample
2. Go to last page
3. Click Add row 4 times - 4th added row increases grid pages size to 9
4. Go to 9th row

### Result  
All records from page 8, and all newly added rows are visible:
![bug7](https://user-images.githubusercontent.com/14248932/143003293-60c04675-072d-468a-a850-3a4aaf0fe366.PNG)

### Expected result  
Only the last added row to be visible on last page

**Comment by hanastasov** [comment]
A duplicate of https://github.com/IgniteUI/igniteui-angular/issues/9990

**Comment by katherinedragieva** [comment]
Issue is fixed with https://github.com/IgniteUI/igniteui-angular-samples/pull/3249
