### ISSUE TITLE
Igxgrid selection is not maintained when cell is edited

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-angular#12582]
## Description  
if multiple rows are selected via the selection checkbox editing a cell in one of the rows should lose selection on all of the other selected rows

## Steps to reproduce  

1. run https://stackblitz.com/edit/angular-pmisng?file=src/app/grid/grid-sample-selection/grid-selection.component.html
2. select multiple rows using the checkbox
3. double click a cell in the grid to edit it

## Result  
the row being edited becomes the only selected rows 

## Expected result  
the selection should be maintained for the other previously selected rows

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Svetloslav15** [comment]
This behavior is by design, you can read more [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection#angular-grid-selection-options). If you would like to select multiple rows, without losing the selection you should use Ctrl + click.
