### ISSUE TITLE
Column Pinning Sample - Icon Styling

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-angular#1259]
### Description  

- [ ] 1. The icon used to indicate pinning is misleading, since the pinning does not **lock** the column.
- [ ] 2. Unpinning and Pinning a column in the Column Pinning sample, moves the icon back and forth.
https://fontawesome.com/icons/thumbtack?style=solid

### Steps to reproduce  

1. Replace not just the Column Pinning but all demos and sample with "thumbstack" icon from Font Awesome
2. Style the icon properly, so that interactions won't misplace it.

### Expected result  

1. The icon will better represent the action.
2. Unpinning and Pinning a column in the Column Pinning sample, won't move the icon.

### Attachments  

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_column_pinning.html

**Comment by mpavlinov** [comment]
@sbozalieva : This issue is for the https://github.com/IgniteUI/igniteui-angular-samples repo.

**Comment by sbozalieva** [comment]
Thanks, @mpavlinov closing the issue and adding it to  https://github.com/IgniteUI/igniteui-angular-samples

**Comment by sbozalieva** [comment]
Reopening one part of the issue, since that one might be product related

**Comment by zdrawku** [comment]
Adding @PavlovVasil to the Assignees

**Comment by mpavlinov** [comment]
I believe the 2 issues are fixed. The icon was changed to pin icon. @SlavUI @zdrawku let me know if you're ok, so I can close this issue.
