### ISSUE TITLE
Igx Financial Chart X-Axis issue

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#12595]
## Description  
Describe the issue.
Igx Financial Charts gives only time on X-axis where it should be date.
For some browsers, it occurs and for some, it doesn't.

 * "@infragistics/igniteui-angular": "13.2.4",
 *  "igniteui-angular-charts": "^13.0.0",
 *  "igniteui-angular-core": "^13.0.0",
 * browser: Chrome

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

The below image is from our clients computer
![image](https://user-images.githubusercontent.com/79090369/215073954-2f25a342-0ec4-4a85-bf82-78dea6dbe9ec.png)

Below video is from MAC
https://user-images.githubusercontent.com/79090369/215072842-33b55dba-fe8e-4b83-994f-05012a93f076.mp4

**Comment by mddifilippo89** [comment]
Hello, 

What does your data look like? I suggest looking at your samples.
https://www.infragistics.com/angularsite/components/charts/types/stock-chart

**Comment by KaushikEDS** [comment]
@mddifilippo89 
This is how my data looks like

I convert time property to actual date objects before giving it to chart component.

[file.zip](https://github.com/IgniteUI/igniteui-angular/files/10534567/file.zip)

**Comment by KaushikEDS** [comment]
@mddifilippo89 do we have any updates?

**Comment by mddifilippo89** [comment]
I'll need a sample if you are converting your time fields to actual dates.
