### ISSUE TITLE
IgxGrid:  Multi-column sorting does not work if custom sortStrategy is used

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#12611]
## Description  
In this sample(https://stackblitz.com/edit/angular-pjwndf-2xqznm?file=src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html) ‘Fruit’ and ‘Company Name’ columns use a custom sortStrategy so that ‘Fruit’ column uses ‘fruitIndex’ column data and ‘Company Name’ column uses ‘companyIndex’ column data respectively when they are sorted.
Now when multi-column sorting is applied, for example, 1st sort by ‘Group’ column, 2nd sort by ‘Fruit’ column, and 3rd sort by ‘Company Name’ column, the 3rd sort does not work as expected.
![image](https://user-images.githubusercontent.com/7463490/216914157-b91e3529-2216-4376-93e0-b255358eeafc.png)

 * igniteui-angular version: 15.0.9
 * browser: Chrome

## Steps to reproduce  

Run the sample:https://stackblitz.com/edit/angular-pjwndf-2xqznm?file=src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html

## Result  
Multi-column sorting does not work as expected.

## Expected result  
Multi-column sorting works with a custom sortStrategy.

**Comment by hanastasov** [comment]
Please add Prs for 14.2.x, 15.0.x as well.
