### ISSUE TITLE
Filtering in number column allows the user to input string values

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1262]
### Steps to reproduce  

1. Open the filter dialog for a number column in igxGrid
2. Enter some non-numbers into the input
3. Value in input is converted to NaN and grid actually does filtering

### Result  
The input should not accept non-numeric values

![capture](https://user-images.githubusercontent.com/14248932/39753614-20012dac-52c8-11e8-8a4e-3a31d6906644.PNG)

**Comment by zdrawku** [comment]
This is a correct behavior of the number column filtering. When anything different than numbers is typed in NaN should be returned, and on filtering the data wont be displayed (with NaN filter value).

Closing this issue.
