### ISSUE TITLE
Simple grid summary

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#12638]
## Is your feature request related to a problem? Please describe.
I have a grid with currency column, and I need to show the sum of this column.

## Describe the solution you'd like
I would like to be able to set column summary in this way `[summary]="sum"`. Also, it will be great if I can specify more than one of the default summary fields, e.g. having date type column set the summary like this `[summary]="earliest | latest"`.

## Describe alternatives you've considered
Now if I set summary on the currency column I got something like this:
![image](https://user-images.githubusercontent.com/5990334/218401249-a8b3d5ef-724e-420a-81b7-cd348f4ca96c.png)

What I need is something like this:
![image](https://user-images.githubusercontent.com/5990334/218397873-1a593157-1e9e-4996-a2c7-08e9dcb821b4.png)

To achieve this I should:
1. Set `summary` to true.
2. Set `summaries` to some custom implemented class.
3. Set `summaryFormatter` to some custom implemented method.

This is too much boilerplate code for something most of the people, putting summary on currency column, will ever need.

**Comment by RivaIvanova** [comment]
@wnvko The feature has been discussed, however, it requires serious refactoring and it will most possibly introduce breaking changes. For this reason, it is considered postponed in order to be discussed further.
