### ISSUE TITLE
Filter reset button not active

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1263]
### Steps to reproduce  

1. Filter the Download column by Null condition
2. Change the filtering condition to equals

### Result  
Grid is filtered by Null, but the Reset button is disabled, so user is not able to reset the filtering state,

### Expected result  
1) Reset button to be active. 
2) Filter condition to be resetted to the default one for the column.

### Attachments  
[igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/1983577/igx-grid-app.zip)

**Comment by hanastasov** [comment]
https://github.com/IgniteUI/igniteui-angular/issues/1286 - Issue is reproducible.

**Comment by zdrawku** [comment]
Removing status: resolved, we set this label when and only when the PR's are verified and approved. If you are a reviewer (testing the PR) please after you set status: verified to the PR, go to the related issue and set status: resolved as well.

@SlavUI, if you have any further comments please do let us know
