### ISSUE TITLE
Private Infragistics npm feed setup giving error: "Web login not supported"

### ISSUE THREAD

**Issue by ankitjindal4** [IgniteUI/igniteui-angular#12677]
## Description  
Cannot access the private npm repo @ https://packages.infragistics.com/npm/js-licensed/

 * igniteui-angular version: 12.1.2
 * browser: all

## Steps to reproduce  

1. Using command "npm adduser --registry=https://packages.infragistics.com/npm/js-licensed/ --scope=@infragistics --always-auth
"

## Result  
npm notice Log in on https://packages.infragistics.com/npm/js-licensed/
npm ERR! code ENYI
npm ERR! Web login not supported

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\X157143\AppData\Local\npm-cache\_logs\2023-02-21T05_13_22_693Z-debug-0.log

I have tried with several combinations of Auth token, username / password.

This is the masked content of ~/.npmrc

@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/
//packages.infragistics.com/npm/js-licensed/:username=USERNAME
//packages.infragistics.com/npm/js-licensed/:_password=PASSWORD
//packages.infragistics.com/npm/js-licensed/:always-auth=true

@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/
//packages.infragistics.com/npm/js-licensed/:_auth=AUTH_TOKEN
//packages.infragistics.com/npm/js-licensed/:always-auth=true

None of this worked. Every time get the same error "Web login not supported".

## Expected result  
Should be able to log into npm registry and download npm packages. 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by jackofdiamond5** [comment]
Hi @ankitjindal4 did you try adding the [--auth-type=legacy](https://docs.npmjs.com/cli/v9/commands/npm-login#auth-type) flag to the command? This may help you log in successfully to the feed.

**Comment by ankitjindal4** [comment]
Hi @jackofdiamond5  thanks for your response. Yes, I did that and now at least I'm seeing options to enter credentials. Post that I'm getting another error now as below:

npm ERR! No credentials to set.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\X157143\AppData\Local\npm-cache\_logs\2023-02-21T06_59_45_691Z-debug-0.log

I have tried multiple times and carefully checking my credentials and its casing etc. but still the same.

**Comment by Lipata** [comment]
Hi, @ankitjindal4 can you submit a case in your [system](https://account.infragistics.com/support-cases/submit) for further investigation?

**Comment by zdrawku** [comment]
@ankitjindal4 can you share the log content?

**Comment by zdrawku** [comment]
@ankitjindal4 for npm version 9.4+ ProGet does not support `npm login` anymore, as for `addUser`  it now actually creates a new user rather than behaving as `login`.

All in all, please set-up your credentials like so:
```
npm config set @infragistics:registry https://packages.infragistics.com/npm/js-licensed/
npm config set //packages.infragistics.com/npm/js-licensed/:username=${username}
npm config set //packages.infragistics.com/npm/js-licensed/:email=${ig_email}
npm config set //packages.infragistics.com/npm/js-licensed/:_auth=${IG_AUTH_TOKEN}
```
Follow these steps to generate access token:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing#access-token-usage

**Comment by zdrawku** [comment]
Docs provided
