### ISSUE TITLE
Pivot grid does not report value of cell in selectedData

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-angular#12719]
## Description  
Pivot grid does not report value of cell in selectedData

### EDIT: Angular repro steps:
1. Open https://stackblitz.com/edit/angular-y3krd8
2. Select a few cells in the grid
3. Click the log getSelectedData button
4. inspect the console

---

1. go to : https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/pivot-grid/overview#web-components-pivot-grid-example
5. Select a few cells in the grid
6. open dev tools and execute the following commands: 
      var grid = document.getElementsByTagName("igc-pivot-grid")[0];
      var selData = grid.getSelectedData();
7. examine the results in selData

 ## Result  
the selected data values contain the key for the column but not the actual cell values
  ex: UK-Vermont: undefined
![image](https://user-images.githubusercontent.com/3198469/223115636-41cbfa2e-9ae3-4103-9664-d0bdea9eaea3.png)

## Expected result  
the selected data values contain the key for the column and the actual cell values
 ex  UK-Vermont: 44989

**Comment by damyanpetev** [comment]
There's also no data in the clipboard when copying from the Pivot:
![image](https://user-images.githubusercontent.com/3198469/223116970-b4e7e969-a214-4847-963b-a2dc3d1f5a85.png)
Pivot data contains just separators for the row value (tabs in plain text).

This is reproducible in both the Stacklitz sample above and on https://www.infragistics.com/products/ignite-ui-angular/angular/components/pivotGrid/pivot-grid#angular-pivot-grid-example and I'm assuming is the same issue. Can log separately if not.
