### ISSUE TITLE
Implement different ng templates for the igxGrid cell component when it comes to inline editing

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#1271]
### Description  
Currently we have only string template with igxInput for iline editing:

Code snippet:
```
<ng-template #inlineEditor let-cell="cell">
    <igx-input-group>
        <input igxInput [value]="value" [igxFocus]="true" [igxTextSelection]="true" (keydown.enter)="cell.update($event.target.value)">
    </igx-input-group>
</ng-template>
```

We need to create additional templates for boolean, number and date inline editing:

- [x] Create boolean ng template
- [x] Create number ng template
- [x] Create date ng template
- [x] Make default template to be the string template
- [ ] Add styling for the new templates

Related to issues:
#1071 
#1075 
#1083

**Comment by zdrawku** [comment]
@SlavUI could you review and consider this enhancement for the current sprint?

**Comment by SlavUI** [comment]
Hi @zdrawku  i see one checkbox not checked ? is the task completed
