### ISSUE TITLE
Wrong edit value after refreshing the grid data

### ISSUE THREAD

**Issue by edmondzymeng** [IgniteUI/igniteui-angular#12724]
## Description  
Edit a cell and then update `igx-grid` data property to refresh the whole grid, the previous edit value remains.
If you open up the previously edited cell, instead of the current value, it shows the last edit value.

 * igniteui-angular version: 15.0.0+
 * browser: Chrome 110.0.5481.178

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-sw373h
2. The "Units in stock" value of the product "Chai" is 39. Edit the cell and update it to 50.
3. Click the "Refresh" button at the top
4. The grid is refreshed. Click the "Units in stock" cell of the product "Chai" again.

## Actual Result  
The default edit value of the cell is 50.

## Expected result  
The default edit value of the cell should be 39 because the cell value before editing was 39.

**Comment by edmondzymeng** [comment]
Seems this issue is introduced on 15.0.0-beta.2 by [this change](https://github.com/IgniteUI/igniteui-angular/pull/12117/files#diff-546e39078a4b678b1598e0e135010a8081b02f4f63bc9997650a08633caa5879).

Previously `editValue` would be passed to the `IgxCell` constructor and honoured while entering edit mode. It is no longer the case now, instead it takes the `editValue` of the existing `FormControl` which was created for the previous editing.

**Comment by Lightw3ight** [comment]
Any movement on this, its causing some pretty funky issues through our code base?

**Comment by dkamburov** [comment]
We are adding this for the next sprint so you can expect a fix in the next couple of weeks
