### ISSUE TITLE
IgxSelectComponent's dd font size is different compared to its input font size

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#12732]
## Description  
The `IgxSelectComponent`'s list items have a font size of `14px` while the input has a font size of `16px`. This causes a bit of a flicker when you open the component as the positioning strategy that we're using attempts to align the text of the currently selected list item perfectly on top of the `IgxSelectComponent`'s input. 

Additionally, some changes needed to be implemented [here](https://github.com/IgniteUI/igniteui-angular/pull/12453) so that the `SelectPositioningStrategy` can take into account the difference between the two fonts.

 * igniteui-angular version: 15.0
 * browser: n/a

## Steps to reproduce  

1. Go to the following page [link](https://www.infragistics.com/products/ignite-ui-angular/angular/components/select)
2. Expand any of the samples and select an item.
3. Close the dd and reopen it a few times.
4. Observe

## Result  
There's flickering caused by the difference of font sizes.

## Expected result  
There should be no flickering.

## Attachments  
![select-flicker](https://user-images.githubusercontent.com/16020256/223669386-2e16d681-8668-453a-8ee1-89d5c518055f.gif)

**Comment by simeonoff** [comment]
I believe it's fine to leave it like that for the moment. We want to get rid of this UI in the next version release and the minor differences don't warrant a temporary fix IMO.

**Comment by Lipata** [comment]
@simeonoff as we talked maybe you should consider having the drop-down size the same as in the web components.

**Comment by simeonoff** [comment]
@Lipata we should verify if there's any size discrepancies between Ignite UI for Angular and Ignite UI for Web Components first. There shouldn't be.
