### ISSUE TITLE
Disable or control animations speed globally

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#12773]
## Is your feature request related to a problem? Please describe.

I want to disable all animations globally. I need to check controls one by one, some of them don't even expose a way to disable them.
It could also be interesting to speed up / slow down by a factor, 0.5 or 1.2.

## Describe the solution you'd like
Either a boolean flag to disable animations. Or a global speed factor that I can set to zero.
I need this to be easily scoped, i.e. affect only one area of my Angular application.

## Describe alternatives you've considered
Using NoopAnimationsModule, but this affects my whole application. I want to disable only controls on a specific area.
I could provide a scoped `IgxAngularAnimationService` but it's not exposed publicly, so I can't reference it to provide mine.

For CSS animations perhaps I could override every animation with `!important` but I haven't try it as it doesn't look like a great solution.

**Comment by ig-georgeA** [comment]
I recently discovered the browser support for prefers-reduced-motion, which is usually available as an accessibility thing. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

If such animation setting is available in the library, I'd expect OS will be able to communicate it to the browser and then the app will work accordingly. I'm not web tech savvy, so I don't know whether this will only work for CSS-transitions.

**Comment by pmoleri** [comment]
Any news about this? Ignite doesn't really fit our design system if we need to disable animations everywhere.
