### ISSUE TITLE
Migrations for 15.1.0 hang

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#12786]
## Description  
Executing migrations for 15.1.0 seems to hang on 

the "Migration completed" message and don't the control to the user in the console.

 * igniteui-angular version: 15.1.0-alpha.0
 * browser: n/a

## Steps to reproduce  

1. You can use this pr that is already loaded to use latest angular alpha - https://github.com/IgniteUI/igniteui-angular-samples/pull/3266/files
2. Run `ng update igniteui-angular --from 15.0 --to 15.1 --migrate-only`

## Result  
Three files do migrate which is great but the command needs to be stopped with Ctrl+C as it doesn't end

## Expected result  
The command to both migrate and return control to the user

**Comment by Lipata** [comment]
Check the following migrations - if they run properly: https://github.com/IgniteUI/igniteui-angular/pull/12651/files#diff-95c4a23fc45b5581a0dfee1d0787585f02b4eaea52a397273bcdb8ced1d75447

and revert back https://github.com/IgniteUI/igniteui-angular/pull/12798/files
