### ISSUE TITLE
Igx-simple-combo selection issue

### ISSUE THREAD

**Issue by m-noumannaveed** [IgniteUI/igniteui-angular#12782]
## Description  
In igx-simple-combo when white space added in displayText at the end of a string or start of a string, after that selection is not working.

 * igniteui-angular version:  15.0.0
 * browser:  chrome

## Steps to reproduce  

1. Step 1 => add white space in end of a displayText field or start of a displayText field
2. Step 2 => do selection with igx-simple-combo with dropdown list.
3. ...

## Result  
Selection will not work with this scenario.

## Expected result  
need to select the value in igx-simple-combo

## Attachments  
![Screenshot 2023-03-17 acaac](https://user-images.githubusercontent.com/128125847/225851064-78486dc1-c1da-41ef-88b0-fc3a4d4fc38c.png)
![Screenshot 2023-03-17 131610](https://user-images.githubusercontent.com/128125847/225851076-13f02a80-b529-46a1-9004-a719ca519e39.png)

#Sample issue link attached:

[sample for igx-simple-combo](https://stackblitz.com/edit/angular-dgbhg2)

**Comment by m-noumannaveed** [comment]
@Lipata please leave comment on this issue.

**Comment by Lipata** [comment]
@m-noumannaveed I've made a PR, but will review it and test it and will decide how to proceed.
