### ISSUE TITLE
Igx grid memory consumption

### ISSUE THREAD

**Issue by remshams** [IgniteUI/igniteui-angular#12799]
## Description  
Hi,

I'd have a question/issue in regards to the memory consumption of the igx-grid.

We are using the igx-grid for a dashboard in our application.
The aforementioned page is kept open for a long period of time (hours/maybe days). We noticed a significant increase in memory consumption after the dashboard was open for some time.

Investigations revealed that the memory increase only occurs when a column is filtered and the filter is collapsed (please see the "FilterCollapsed" screenshot in the attached zip file). In contrast the memory consumption is stable if no filter is set or the filter is expanded ("FilterExpanded" screenshot).
A heap dump shows a lot of allocations for the "IgxChipsAreaComponent" ("HeapBeforeFilterDeletion" screenshot).
The allocations are cleaned up by GC after the filter is deleted ("HeapAfterDeletion" screenshot).
In addition the elements inspector shows a change/update for the "igx-chip-area" with every update of the grid ("App_IgxChipsArea" screenshot).

I've reached out to your customer support to clarify  if we are using the component incorrectly and/or how to reduce the memory consumption. They could not find any issue in our implementation and recommended to open an issue here.

I've created an [example repository](https://github.com/remshams/igx-grid-filter-memory/tree/main) reproducing the issue (this is also the one the screenshots have been taken from).
The app updates the grid every second with the current date.

 * igniteui-angular version: 15.0.16
 * browser: Chrome 111.0.5563.64

## Steps to reproduce  

1. Checkout the main branch and start the application
2. Setup the filter as shown the "FilterExpanded" screenshot
3. When keeping the app open for a while there should be a significant increase in memory consumptions
4. After deleting the filters, the memory should be freed (when the next GC runs)

## Result  
The allocated memory keeps growing when the application is open for a while.

## Expected result  
The allocated memory should stabilise after some time.

## Attachments  
[igx-grid-memory.zip](https://github.com/IgniteUI/igniteui-angular/files/11037195/igx-grid-memory.zip)

**Comment by ChronosSF** [comment]
Thank you for the report @remshams ! 

We take potential memory leak issues very seriously. With our current schedule we can start investigating this in the first week of April. This means the very first chance for a fix to be available is in start of the second week of April. Does this schedule work for you or is the issue critical and time-sensitive for your project?

**Comment by remshams** [comment]
Thanks for the reply @ChronosSF,

since we have a "workaround" available (not collapsing the filters) the timeline should be fine.
Thanks for taking care of it.
