### ISSUE TITLE
Pinning icons are misaligned and horizontal scroll area is shrinked

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular#1280]
### Steps to reproduce  

1. Run the grid pinning sample on staging
2. Pin "Region" column

### Result  
Pinning icon and header text are misaligned. Observe the horizontal scrollbar: it's shrinked

### Expected result  
Correctly aligned pinning icon and header text. Normal horizontal scroll appearance.
![ugly](https://user-images.githubusercontent.com/12935806/39870300-7ca9f474-5469-11e8-86a3-d0e54fb78404.png)

**Comment by mpavlinov** [comment]
@tbelcheva This is for https://github.com/IgniteUI/igniteui-angular-samples repo. Please log it there and close this one.
