### ISSUE TITLE
[TreeGrid]: rowAdd newValue ParentID differs from rowData

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#12845]
## Description  
When adding a child to a row, the ParentID in `newValue` differs from the ParentID in `rowData`. `newValue` shows the correct value.

![igx-tree-grid-addChild](https://user-images.githubusercontent.com/49126110/229559775-2228fd3f-2efc-449e-a5c0-dc695b3a1fb1.png)

 * igniteui-angular version: 15.1.x, 14.2.x
 * browser: any

## Steps to reproduce  

1. Open this [demo](https://stackblitz.com/edit/angular-fbgjfz?file=src%2Fapp%2Ftree-grid-add-row-sample%2Ftree-grid-add-row-sample.component.html,src%2Fapp%2Ftree-grid-add-row-sample%2Ftree-grid-add-row-sample.component.ts).
2. Click the **Add Child** icon on any record and add a new row.
3. Open the Dev Tools Console and observe `newValue` and `rowData`.

## Result  
The ParentID in `newValue` differs from the ParentID in `rowData`.

## Expected result  
The ParentID should be the same.

**Comment by SeanWickstrom** [comment]
How this is shown in the browser debugger console is confusing and burned me for longer than I want to admit until I realized that when you log an object to the console the contents of the object aren't evaluated until you expand the object in the debugger.   So by the time you're viewing newValue.ParentId in the debugger it's value is different than it was while in the event.

You can see this by changing 
  console.log(args);
to
  console.log(args.rowData.parentId)
  console.log(args.newValue.parentId)

When you log the value this way you will see it is incorrect for both.
