### ISSUE TITLE
Remove ComponentFactory and ComponentFactoryResolver as they are being removed in Angular 16

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#12851]
## Is your feature request related to a problem? Please describe.
Review all components using ComponentFactory and ComponentFactoryResolver and update the APIs to not use them. They are being removed in Angular 16.

## Additional context
Related to #12765
The overlay is already updated here - https://github.com/IgniteUI/igniteui-angular/pull/11685

**Comment by MayaKirova** [comment]
Note that grids use ComponentFactory/ComponentFactoryResolver for other purposes such as re-emitting events (outputs) from child grids to row island: https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts#L202

Which may not be so trivial to replace.

**Comment by damyanpetev** [comment]
@MayaKirova `createComponent` is indeed one of the intended replacements (along with the `ViewContainerRef.createComponent()` equivalent). Was sort of wondering the same thing about `inputs/outputs` meta replacements, but the PR that added the first one (https://github.com/angular/angular/pull/46685) sort of answered that for me. 
It looks to me like [`reflectComponentType`](https://angular.io/api/core/reflectComponentType) is a direct replacement for the meta props of the factory.
