### ISSUE TITLE
Gantt Chart Component

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#12865]
### Discussed in https://github.com/IgniteUI/igniteui-angular/discussions/12847

<div type='discussions-op-text'>

<sup>Originally posted by **SkylerLutz** April  3, 2023</sup>
Hi, I'm trying to build a visualization for some data signals that have distinct start and end dates. I'd also like to allow my users to optionally select which columns to roll up the data by i.e. ad-hoc group-by. I was wondering if IgniteUI Angular had any options to visualize this type of data, either today or in the near future. Thanks! </div>

**Comment by radomirchev** [comment]
@SkylerLutz the Gantt chart is not included in the Ignite UI for Angular. Both Gantt Chart and #8097 were considered but not yet scheduled for development.
