### ISSUE TITLE
Grid: height 100% doesn't work correctly with flex-grow

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12896]
## Description  
Grid height 100% doesn't work correctly with flex-grow.

 * igniteui-angular version: 15.1.3
 * browser: Chrome

## Steps to reproduce  
https://stackblitz.com/edit/angular-tc333n

```html
<div style="
    display: flex;
    flex-direction: column;
    height: 100%;
">
  <div style="flex-grow: 1;">
    <igx-grid></igx-grid>
  </div>
</div>
```

## Result  
Grid grows when window grows but it doesn't shrink when the window shrinks.

## Attachments  
![2023-04-19_13h13_22](https://user-images.githubusercontent.com/46870283/233057854-2dbbdb67-4003-4af6-8b79-ad74cc702b38.gif)

**Comment by MayaKirova** [comment]
@Timmeeeey I don’t think flex containers can shrink below the size of their content out of the box. You can set height:100% on it so that it sizes based on the size of its parent.
For example: https://stackblitz.com/edit/angular-tc333n-8guoxk

**Comment by Timmeeeey** [comment]
@MayaKirova 
With `height: 100%` it doesn't quite work because it ignores the footer when shrinking the window.
But I found out when you set `overflow: auto` instead, it works.
