### ISSUE TITLE
IgxStepper - The content of the steps is not stretching vertically

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#12892]
## Description  
The content of the steps can't be set to fill the remaining space of its container.

 * igniteui-angular version: 13.2, 14.2, 15.1
 * browser: any

## Steps to reproduce  

1. Open the following sample where the height of the steps' conents are set to 100% - [here](https://stackblitz.com/edit/angular-ugy9he?file=package.json).
2. See the result.

## Result  
The content isn't stretching vertically.

## Expected result  
The content should fill the remaining space of its container.

## Attachments  
![image](https://user-images.githubusercontent.com/75325639/232899831-d727bb35-0e5f-4888-972c-6963ac48e460.png)

**Comment by viktorkombov** [comment]
The issue is still reproducible when igxStepContent's height is not set to 100%:

![image](https://github.com/IgniteUI/igniteui-angular/assets/75325639/afbcc791-9c63-4391-9d73-368d49778df0)

**Comment by radomirchev** [comment]
@desig9stein can we close this issue?
