### ISSUE TITLE
When filtering condition is selected move the element focus to the filter input

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#1290]
### Description  
I want to be able to choose a condition and type in directly my value.

1. Open the sample - https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
2. For Athlete, show filtering dialog

### Result  
The input is not focused and I need to focus it first and then start typing the filtering value.

### Expected result  
1) The input to be focused.

2) The input to be always focused when it is available, this includes:
- opening the filter UI
- changing selection in the select element

**Comment by zdrawku** [comment]
@sbozalieva if you have any comments from UX point of view, please do let me know.

**Comment by sbozalieva** [comment]
@zdrawku Focus the input automatically! :)
