### ISSUE TITLE
Igx-grid event name when sorting is changed on grouped columns

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#12904]
What event is emitted when we change sorting on grouped columns

I have tried [sortingExpressionsChange](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#sortingExpressionsChange) & [sortingDone](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#sortingDone), but it didn't work.

Package.json :
    "@angular/animations": "~13.3.6",
    "@angular/cdk": "^13.3.2",
    "@angular/common": "~13.3.6",
    "@angular/compiler": "~13.3.6",
    "@angular/core": "~13.3.6",
    "@infragistics/igniteui-angular": "13.2.4",

![image](https://user-images.githubusercontent.com/79090369/233424368-13900c50-4b1b-4686-b294-7f105ed5e93b.png)

**Comment by KaushikEDS** [comment]
@georgianastasov is there no existing event for this?

**Comment by georgianastasov** [comment]
Hello, @KaushikEDS 

Currently, the igx-grid component does not provide an event to be fired when sorting the grouped columns when clicking on the chips in the Group By toolbar, as this request of yours has been determined to be a feature request.

In the latest version of Ignite UI Angular you have the option to subscribe to the **groupingExpressionsChange** property of the grid and you will be able to access which column is sorted in which order and strategy. [Here](https://stackblitz.com/edit/angular-a5e8ph?file=src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html) you can find a small sample illustrating this behavior.

**Comment by KaushikEDS** [comment]
Thanks @georgianastasov

**Comment by ChronosSF** [comment]
> @ChronosSF I believe this should be fixed. Events should be raised through every UI part that initiates the actions.

Me too. Here the issue is that grouping wraps sorting in some sense and calls to it a bit deeper in the sorting execution chain than what would allow the normal sorting events to fire. But yes, we should see how we can fix it so at least sortingDone is fired. `sortingExpressionsChanged` might not be correct to trigger as technically sorting the group only changes the grouping expressions and not the sorting ones. More info when we get the chance to look into it.

**Comment by amitmoondra** [comment]
Hi @ChronosSF ,
Any timeline when this will be fixed?

**Comment by ChronosSF** [comment]
We can schedule it for development in the sprint starting on May 1. However, please have in mind that 13.2 is no longer in active support and since the issue has a pretty straightforward workaround we are not going to release a fix for it in 13.2.

**Comment by amitmoondra** [comment]
Got it, thanks @ChronosSF.

**Comment by KaushikEDS** [comment]
@kdinev @ChronosSF 
The event groupingExpressionsChange is not available on the Documentation page
Can you update that too?
