### ISSUE TITLE
Include IgxButtonGroupComponent in IButtonGroupEventArgs

### ISSUE THREAD

**Issue by grosch-intl** [IgniteUI/igniteui-angular#12913]
## Is your feature request related to a problem? Please describe.
If I'm using the `selected` or `deselected`  events, it's pretty much guaranteed that I need the igx-buttongroup element as well because I need the `selectedButtons` value.  

## Describe the solution you'd like
Include the button group component in the event args.

## Describe alternatives you've considered
Include the `selectedButtons` property in the event args.

**Comment by grosch-intl** [comment]
Yes, no, maybe so?

**Comment by radomirchev** [comment]
@grosch-intl the issue is to be reviewed next sprint.

**Comment by radomirchev** [comment]
@grosch-intl the feature is completed and will be released with the Ignite UI for Angular 16.1

**Comment by grosch-intl** [comment]
@radomirchev Thanks!
