### ISSUE TITLE
Couple of CSS props for filtering styling not working

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#12928]
## Description  
There are couple of CSS props that should style the advanced filtering but does not effect anything:

--igx-grid-filtering-row-text-color
--igx-grid-filtering-header-background
--igx-grid-filtering-header-text-color

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open this [sample](https://stackblitz.com/edit/angular-hhpcgb?file=src/app/grid/grid-advanced-filtering-sample/grid-advanced-filtering-sample.component.scss)
2. Try changing one of the above css props
3. Observe

## Result  
There is no visible change when those props are set/changed.

## Expected result  
Are those even used ? Should we remove them or there is a bug?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by desig9stein** [comment]
@mddragnev Hi, the props are working just fine, I don't see any filtering row in your sample that's why you don't see the effect.

Here is a screenshot
<img width="1401" alt="Screenshot 2023-05-03 at 12 00 30" src="https://user-images.githubusercontent.com/21260963/235874092-5ae40d68-fa3e-4944-b56a-ad389903c78b.png">

**Comment by mddragnev** [comment]
Yup, my bad. Anyway, how did u manage to remove the chip with filtered value and apply `--igx-grid-filtering-row-text-color` ? I cannot manage to get this prop working?

**Comment by desig9stein** [comment]
> @desig9stein Yup, my bad. Anyway, how did u manage to remove the chip with filtered value and apply `--igx-grid-filtering-row-text-color` ? I cannot manage to get this prop working?

I did it in the browser just to prove that the variable worked. Not sure if the user can actually put text there.

**Comment by mddragnev** [comment]
Ok, closing the issue then.
