### ISSUE TITLE
Selecting a half-visible cell at the bottom of a grid and then scrolling horizontally results in displaced vertical scroll

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#1292]
### Description  
Describe the issue.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html
2. Select a cell from the last (half-visible) row
3. Scroll horizontally to the right
4. Observe the vertical scrollbar

### Result  
The scrollbar height is changed so that there is a blank space between horizontal and vertical scrollbar

### Expected result  
The scrollbar should not change its height.

Note: This is a regression in 5.3.1. It is working fine in 5.3.0

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
@mpavlinov This may have already been fixed with this PR: https://github.com/IgniteUI/igniteui-angular/pull/1777

Could you check and close it if it's already fixed?

**Comment by mpavlinov** [comment]
@MayaKirova Yes. this is fixed in version 6.1. Please make a PR for 5.3.1.
