### ISSUE TITLE
Excel style filtering filter area too small if all features are enabled

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#12942]
## Description  
Having excel style filtering with all sorting,pinning,hiding, moving features makes the filter area too small in web components.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/excel-style-filtering#configure-menu-features and look at the configure menu features sample. 
2. Open the Product name ESF. It has all features enabled
3. Observe that the filtering area inside the ESF dialog is too small
![Screenshot 2023-04-27 at 13 58 16](https://user-images.githubusercontent.com/37667452/234842777-050b2243-8ec1-43bb-b035-7acc737cd84e.png)
4. Open Quantity per Unit ESF. It has some of the features only.
5. Observee that the filtering area is big enough.
![Screenshot 2023-04-27 at 13 59 25](https://user-images.githubusercontent.com/37667452/234842976-53e68731-6042-4b09-8852-dea855e32c3d.png)

**Comment by damyanpetev** [comment]
Yeah, not sure exactly what the ESF dialog is supposed to do in this situation - unless there are some design considerations I'm not aware of that should be in play. The rest can be down to configuration really:

Note the equivalent Angular sample is running in a much higher container (950px)? Probably a good reason for that ;) If you reduce the height on it to the same 620px, delete the button group and switch to Bootstrap you get a _very_ similar result:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/27ae8db4-d1e5-430f-b7c7-3004673c0096)

Now there's a slight difference still from the live WC sample as [per above](https://user-images.githubusercontent.com/37667452/234842777-050b2243-8ec1-43bb-b035-7acc737cd84e.png), however that's down to another missing piece in the WC sample too - it doesn't seem to have typography enabled at all. Adding `ig-typography` class to the sample container gets you within the ballpark:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/3523e7d9-3dfc-439d-a3e8-40198d777b10)

The typography thing seems to be a widespread issue with just about all the samples as far as I can see. Any other diffs might be best inspected by someone more design-inclined :)

**Comment by mddragnev** [comment]
Updated the sample container in the xplat docfx. Closing since not a bug.
