### ISSUE TITLE
columnVisibilityChanged is not triggered when columns visibilities are changed from setState

### ISSUE THREAD

**Issue by bmtheo** [IgniteUI/igniteui-angular#12958]
## Description  
columnVisibilityChanged is not triggered when columns visibilities are changed from setState

 * igniteui-angular version: 14.0.2
 * browser: Google Chrome Version 112.0.5615.138 (Official Build) (64-bit)

## Steps to reproduce  

1. columnVisibilityChanged 
Listen to columnVisibilityChanged on your grid
```
  @ViewChild('grid') grid: IgxGridComponent;

  ...

  this.grid.columnVisibilityChanged.subscribe(_ => console.log('visibility changed'));
```

2. setState
Change the state of your grid with this.state.setState()
```
  @ViewChild(IgxGridStateDirective)
  public state: IgxGridStateDirective;

  ...

  this.state.setState(...); // use a state that changes the column visibility to make sense
```

## Result  
'visibility changed' is not displayed

## Expected result  
'visibility changed' should be displayed

## Other solution
If it is not possible to trigger columnVisibilityChanged that way, is it possible to have a stateChanged EventEmitter so that I can manually do it ?

## Use case
I have a directive that listens to columnVisibilityChanged to execute some codes depending on the displayed columns

**Comment by bmtheo** [comment]
Bumping issue so it does get forgotten/closed

**Comment by bmtheo** [comment]
if the base feature is too time consuming to implement, would that be possible to just have an emitter when setState is called ?

**Comment by hanastasov** [comment]
> if the base feature is too time consuming to implement, would that be possible to just have an emitter when setState is called ?

Hi @bmtheo , this is a public API and is not used internally, generally you dont need an emitter for this. You can actually implement an emitter in your app and emit an event every time shi setState api is used, and you know when it is used.
