### ISSUE TITLE
Stepper - Differences with the step indicаtor between WC and Angular

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#12988]
## Description  
There are differences with the step indicаtor between WC and Angular when the indicator is customized:

Angular:

![image](https://user-images.githubusercontent.com/75325639/234532070-25d6c699-49ca-4c26-b9c2-82b24b1a9b7f.png)

WC:

![image](https://user-images.githubusercontent.com/75325639/234532959-701b10f6-e8cf-4241-a97b-9cc9e5de0a24.png)

## Steps to reproduce  

1. Download and run the following samples - [Angular](https://filetransfer.infragistics.com/public.php?service=files&t=0713422232e99a5573752cb1c0afb0ca), [WC](https://filetransfer.infragistics.com/public.php?service=files&t=a6120f334e059bec6f56e41056befb1f).
2. See the differences.

## Result  
There are differences with the step indicator between WC and Angular.

## Expected result  
There should not be any differences.

**Comment by viktorkombov** [comment]
@desig9stein, in the [design handoff](https://www.figma.com/file/iBiSKAZJ56Z3Pd0zertjHb/Stepper-Design-Handoff?type=design&node-id=0-1&t=w0JuBk91jPZrNQh8-0) there is a background when the indicator is customized but we cannot see it in WC:

Handoff:

![image](https://github.com/IgniteUI/igniteui-angular/assets/75325639/d75e7c29-0d15-4af0-bb99-f932bf7f592f)

WC:

![image](https://github.com/IgniteUI/igniteui-angular/assets/75325639/8102e250-91a0-45f0-a68a-74284a47a5c8)

What I also have observed is that in both - Angular and WC, the optional step doesn't have differences with the regular step, which is not the same in the design handoff where the optional step is with different background in the indicator:

Handoff:

![image](https://github.com/IgniteUI/igniteui-angular/assets/75325639/dfa4cc81-a8f8-47ba-9ca6-7cb8f0c60aba)

WC:

![image](https://github.com/IgniteUI/igniteui-angular/assets/75325639/4ca8b0eb-cdda-4410-b56c-590d282077a7)

**Comment by desig9stein** [comment]
> design handoff

@viktorkombov there is a gray background when the step is **complete**, when the step is **optional** or **Incomplete** they look the same, when the step is selected there is a blue background that has the higher precedence and always overrides the other states colors.

WC
<img width="981" alt="Screenshot 2023-05-18 at 11 45 14" src="https://github.com/IgniteUI/igniteui-angular/assets/21260963/cca04bb7-7759-473e-92f2-e7265a91468f">

Angualr
<img width="1562" alt="Screenshot 2023-05-18 at 11 53 53" src="https://github.com/IgniteUI/igniteui-angular/assets/21260963/dd5b254c-f21e-4c38-ba50-4ae275b8c1f5">

Design
<img width="678" alt="Screenshot 2023-05-18 at 11 54 50" src="https://github.com/IgniteUI/igniteui-angular/assets/21260963/0bb18066-445d-40a4-94c9-7bc4c1378deb">

**Comment by viktorkombov** [comment]
> @viktorkombov there is a gray background when the step is **complete**, when the step is **optional** or **Incomplete** they look the same, when the step is selected there is a blue background that has the higher precedence and always overrides the other states colors.
> 
Yeah, my mistake. But the issue with the missing background of the customized indicators still persists.
