### ISSUE TITLE
[Angular elements] Grid's clearCellSelection method is not a function

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#13020]
## Description  
clearCellSelection is not exposed on the angular elements grid.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run a grid sample and try to call the clearCellSelection method on the grid.

## Result  
clearCellSelection is not a function

## Expected result  
It should clear cell selection.

**Comment by damyanpetev** [comment]
@MayaKirova Yes, well would've been great if that wasn't marked as hidden/internal ¯\\_(ツ)_/¯
https://github.com/IgniteUI/igniteui-angular/blob/a9b2dd7161c2f7b71f46cad5673760221911f3c4/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L5458-L5461

Apparently it's being used by samples and judging by https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-selection#clear-cell-selection (link doesn't work for the same reason), so I suppose it is indeed intended to be part of the public API?

Perhaps @hanastasov might want to weigh in, but either one can document correctly if it's indeed supposed to be public so it can be picked up for Elements.

**Comment by MayaKirova** [comment]
@dkamburovb @hanastasov  I guess we can remove the hidden/internal tag and add info as a bug fix.

**Comment by hanastasov** [comment]
Looking at it I agree with that. It is the only way to clear selected cells, so I assume this mus have been public from beginning.
