### ISSUE TITLE
Select Component Dropdown - Incorrect Placement

### ISSUE THREAD

**Issue by andiesm813** [IgniteUI/igniteui-angular#13034]
## Description  
According to [Material UI guidelines](https://firebasestorage.googleapis.com/v0/b/design-spec/o/projects%2Fm3%2Fimages%2Fl01ijuvs-menu_usage_3P_2.mp4?alt=media&token=cbd1828a-7253-4f7c-93ff-1210434bdbdd), the positioning of the dropdown when you open the dropdown in the select component should be the following:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/2686debf-1e4d-46ac-9da1-299c553c83f7)

Notice that the width of the dropdown is exactly the same width as the select, and the positioning is identical. Right below the select, the dropdown opens:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/327c6851-6ddd-4e71-bc94-eba668ded9ab)

## Ignite UI Components

But if we take a look at our [Select samples](https://www.infragistics.com/products/ignite-ui-angular/angular/components/select), the position of the dropdown is way off:

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/cbf8746a-2d76-4d6e-b68f-4f6bcda54fc9)

And it gets worse if it has a prefix:
![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/5c09f786-8a20-4ef0-9f1c-ea4cf62eb5ee)

## Expected result  

When the select dropdown is opened, it has to match the width of the select component, and there shouldnt be an offset.

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/b2d9bc07-97c9-43dd-83b0-b6d4bff19a6c)

![image](https://github.com/IgniteUI/igniteui-angular/assets/86068582/7d24f3af-c649-43e6-8d53-180dbf29a853)

**Comment by andiesm813** [comment]
@sdimchevski i assigned this to you because i thought it's your call to push these fixes to dev. So if you think my expectations are accurate, i hope we can fix these issues so the component can improve. Thanks!

**Comment by Lipata** [comment]
This overlay strategy will be removed and the drop-down will show below the input. This will unify igx-select with web components igc-select where such positioning is missing. There is similar issue logged here: https://github.com/IgniteUI/igniteui-angular/issues/12732#event-9585716893
