### ISSUE TITLE
[Angular Elements Grid] Grid's lastSearchInfo is undefined.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#13051]
## Description  

Note that the prop is public but also hidden/internal: https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L2832

While also described in our public docs:  https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/search#display-results-count

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run any wc grid sample and try to access the lastSearchInfo prop.

## Result  
It's undefined.

## Expected result  
It should be defined.

**Comment by damyanpetev** [comment]
Yeah, that's just great. The property being `@hidden @internal` pretty much explains why the Elements property is not available.

Now, is seems like it's one of those API-s that weren't properly documented & one of the sweeping API cleanups hid it, so the obvious solution would be to just properly document it. However, I'd also like a proper type for it (it's anonymous object atm) and somewhat careful evaluation of what's in it and how much is useful.
For example `matchInfoCache` is `any[]` which really isn't useful to anyone as is. If the only meaningful use of it is the length/count, there's yet another `ISearchInfo` (thankfully not exported, but still messy..) in the text highlight directive that simply uses `matchCount` which we might expose instead and deprecated the cache thing.

Also would have it as a getter **only** to match it's use and have it translate better into other platforms.
