### ISSUE TITLE
Grid no longer establishes a local stacking context, clips external items

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#13054]
## Description  
Per the title, the Grid no longer stablishes its own local stacking context (since #12850) leaves internal stacking order interacting with other elements in view and potentially clipping them.

 * igniteui-angular version: 14.2.x, 15.1.x, 16.0.x
 * browser: N/A

## Steps to reproduce  

1. Take the demo under https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag#templating-the-drag-ghost
2. Start dragging a row 
3. Move the drag ghost 'over' the origin grid's header/scroll

## Result  
The drag ghost clips under both:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/c2ee8372-6491-4b07-92c5-2354b1971a90)
That'd be because `z-index` of the the grid header (`2`) and especially the virtual scroll helper (`10001` ❗) are no longer contained and interact with other elements in the page. Without digging through the rest of the grid structure, IIRC there are other elements with pretty high indexes in use for internal ordering too.

@hanastasov @simeonoff This is just one example I could find, I'm sure there might be more and it's not hard to imagine other scenarios that'd break. Like the next dropdown-like component we don't control placed above the grid being clipped by scrollbar or something.
I see you did consider the implications of dropping the local context https://github.com/IgniteUI/igniteui-angular/pull/12994#discussion_r1189979310, though reading over the comments for #5674 I believe those still sand - and not about the particular issue, but in general.

## Expected result  
IMO, the loosing the local stacking context has the potential for more damage than the issue it resolves and should likely be restored. I still think my old comment about "no universal solution" is kinda valid, but so is the following part about containing the grid internals and [some conflicts being application-level scenarios](https://github.com/IgniteUI/igniteui-angular/issues/5674#issuecomment-525621994) - the issue in #12850 is exactly _that_ type of application scenario where the need to bunch some grids in a column layout is where you bump the `z-index` of the top grid to allow it to overlay on top of the others.

Not ideal, I realize. The only actual fix for this would be to do what was initially suggested back in the day - move the local context to another element, so the outlets for overlays can be outside while still in the host element for theming, if that's even feasible. Or move the entire overlay service to a `top-layer` once something like [`showPopover`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/showPopover) is widely available.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
Bonus scenario with trial H Grid (thus not easily discoverable in samples) - if a child grid has scrollbars, those also overlap the trial watermark :)
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/2ca74d15-e5b2-43b9-8aa3-7ae4ec8e8006)

**Comment by hanastasov** [comment]
Due to regressions #13054 and #13114, it was decided to revert the changes from  https://github.com/IgniteUI/igniteui-angular/issues/12850. FYI @ddincheva
