### ISSUE TITLE
igxGrid - extra white space when hiding summaries in certain situations

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#1305]
### Description  
White space when disabling summaries one (bigger) after another (smaller) after scroll to bottom and having horizontal virtualization.

### Steps to reproduce  

1. Run: https://stackblitz.com/edit/angular-wuoy9r
2. Scroll to bottom.
3. Disable 'UnitsInStock' summary.
4. Disable 'OrderDate' summary.

### Result  
There is some white space below the last visible row:

![sum](https://user-images.githubusercontent.com/7972965/40040681-de43c6fc-5823-11e8-8b3d-64a04f60db8f.png)

### Expected result  
There is no white space.
This is not reproducible if there is no horizontal scrollbar, for example if you make the grid wider in the sample.

**Comment by zdrawku** [comment]
The issue is with status resolved
