### ISSUE TITLE
[WebComponents/Blazor] Typings within the context of the exposed templates are buggy

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#13067]
## Description  
As you may remember we exposed inputs of almost all templates in the grid. Those inputs have typed context with implicit parameter. In Angular the implicit parameter is called `$implicit` with the $ sign in front of. But it is exposed without which is causing web components to throw typescript error if used with $ or the implicit argument empty. This also applies to blazor.
Is there any reason of implicit being exposed without the $ sign? 

![Screenshot 2023-05-30 at 13 30 10](https://github.com/IgniteUI/igniteui-angular/assets/37667452/e0b500ee-25f7-479b-9f4e-9a0d5cd743ef)
This is how I tried to use it and in the following photo is the typing.
![Screenshot 2023-05-30 at 13 30 54](https://github.com/IgniteUI/igniteui-angular/assets/37667452/77c5c1af-182f-4709-8da2-0cac11dd6081)

**Comment by damyanpetev** [comment]
Yeah, `$implicit` isn't all that nice as a property name IMO _and_ you rarely (if ever) interact with it directly in Angular - you'd assign it to something like `let-cell` on the template for example. This was likely done for platforms that this goes to - particularly C# is really not happy with properties with such prefix  :)

Ideally, I would've liked to get to a place where the templates implicit props can hint a suggested name for Elements so we can have more meaningful one there but haven't gotten anywhere near that yet. So for the time being, I'd say the typings sort of decided on the naming for us already and will likely add the un-prefixed version alongside the prefixed value to avoid breaking any current use. That way you won't have to fight the typings and can use what they say is available. And looks at least a bit better to me :)
