### ISSUE TITLE
Header text is not truncated correctly for numeric columns with filter icon

### ISSUE THREAD

**Issue by sstoyanovIG** [IgniteUI/igniteui-angular#1307]
### Description  
Header text is not truncated correctly for numeric columns with filter icon.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html
2. Observe 'Change' and 'Change(%)' columns

### Result  
There is no ellipses and  the text is cut from beginning. 

### Expected result  
There should be ellipses.

**Comment by SlavUI** [comment]
@sstoyanovIG  This is to be moved in the Samples repo ;)

**Comment by sstoyanovIG** [comment]
@SlavUI We can easily change the column widths, so the text is not cut off, but I think that if there isn't enough space for the header text, the text should be truncated correctly like in the first or seventh column :)

**Comment by zdrawku** [comment]
I think this is something that should be handled on Grid component level, igxHeader directive to be more specific. @sstoyanovIG I am assigning it for further investigation to you.

**Comment by sstoyanovIG** [comment]
After some investigation, it turns out that the issue comes from a style, created in the samples for the cells, that is also applied to the headers. @SlavUI, you were right :). I will close this issue and create a new one in the samples repo.
