### ISSUE TITLE
Hide grouped columns property does not apply for initially groups when columns load after init

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#13074]
## Description  
Setting `hideGroupedColumns` does not get applied to the initially grouped columns.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Set `hide-grouped-columns="true"` on the grid with initial `groupingExpressions` set.
Can also be viewed in this sample: https://github.com/IgniteUI/igniteui-wc-examples/pull/460
Note that if grouping is toggled off/on then the property takes effect and the grouped columns hide.
## Result  
The grouped columns are not hidden.

## Expected result  
Should be hidden.

**Comment by damyanpetev** [comment]
Similar to a couple of precious issues - all related with the timing of the columns being loaded. This one actually reproduces pretty easily with my go-to explanation for Element's "as if it was loaded by an async request".
Forked from https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/export-excel#angular-excel-exporter-example and simply don't populate the columns array immediately. For example on a button click:
https://stackblitz.com/edit/1mpppp-tgryje 
And sure enough:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/7eda06c8-e8c8-4a21-83dd-1f80742d99e1)
