### ISSUE TITLE
igx-grid advanced filtering dialog action buttons margins/paddings do not match the design system definition

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#13084]
## Description  
The title says it all.

 * igniteui-angular version: 16.0.0
 * browser: all

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/advanced-filtering
2. Click the advanced filtering button

## Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/6c7101a4-91d6-4e4a-aace-8029d7164cfe)

## Expected result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/b0d5527d-2a7a-41b6-9a3c-1b885eab39a1)

**Comment by damyanpetev** [comment]
On the subject of button spacing (or lack thereof), the Bootstrap theme has some padding, but the positioning of the buttons is quite off and they overflow out of the dialog:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/991fa569-53b2-4b73-98ca-e2f8eb6307e2)
Can log it separately if not related.

**Comment by radomirchev** [comment]
and add group buttons in the Indigo theme:

![image](https://github.com/IgniteUI/igniteui-angular/assets/52001020/634788a9-9dca-4be1-ae51-abb560188e0c)

**Comment by desig9stein** [comment]
The issue is also reproducible in 14.2.x  and 15.1.x.
@sdimchevski can you provide a working link to the design handoff? The link in the [wiki](https://github.com/IgniteUI/igniteui-angular/wiki/Advanced-Filtering-(In-Progress)#user-interface) is broken.
