### ISSUE TITLE
Grid footer is cut off with couple of pixels

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1308]
### Steps to reproduce  
1. Run the sample

### Result  
See the footer:
![capture](https://user-images.githubusercontent.com/14248932/40046362-801dca66-5835-11e8-94cd-3fe2844387e7.PNG)

### Expected result  
The footer shadow to be visible:
![2](https://user-images.githubusercontent.com/14248932/40046431-a245b18a-5835-11e8-9f6e-dd6d7617885d.PNG)

### Attachments  
[igxgrid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2004083/igxgrid-app.zip)

**Comment by Aleksandyr** [comment]
@hanastasov The is not reproducible anymore.

**Comment by Aleksandyr** [comment]
@hanastasov I assume that this is not a bug. I have found that we have applied style on the wrapper of the grid which sets overflow: auto to this element. As this element has the same height as the grid(650px) it overflows the grid and respectively it overflows the shadow too as the shadow of the grid is not included into the height of the comp
![capture](https://user-images.githubusercontent.com/7037740/41360154-b963d2dc-6f34-11e8-9f59-eeea55cad7e6.PNG)
![capture1](https://user-images.githubusercontent.com/7037740/41360155-b984cf82-6f34-11e8-8542-aed4068045e7.PNG)

onent. You can see the attached screenshots for better understanding.
