### ISSUE TITLE
Snackbar is incompatible with Angular 6

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1309]
### Description  
After upgrade to Angular 6, I receive an error when I build the project:

_ERROR in node_modules/igniteui-angular/snackbar/snackbar.component.d.ts(1,10): error TS2305: Module '"myPath/node_modules/ @angular /core/core"' has no exported member 'AnimationTransitionEvent'._

### Steps to reproduce  

1. Upgrade to [Angular 6](https://update.angular.io/)
2. Use this [Backwards compatibility for rxjs](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)
3. ng build the project

### Result  
Build failure

### Expected result  
Succeeding build

**Comment by zdrawku** [comment]
We are going to release 6.0.0 version soon, and once you start using it, the error wont appear.

You can check regularly the official npm page for changes:
https://www.npmjs.com/package/igniteui-angular

I am optimistic that we will release 6.0.0 this week.

**Comment by Hypenate** [comment]
@zdrawku  Thank you for the info.
I can't find it on the [roadmap](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md) tough.

**Comment by zdrawku** [comment]
We will update the roadmap with that change. Thank you @Hypenate

**Comment by HEBOS** [comment]
Same with me.

**Comment by zdrawku** [comment]
@Hypenate and @HEBOS I can confirm that using of igxSnackBar with ng version 6 is compatible and successful. Have a look at this sample and let me know if your scenarios are different:

https://stackblitz.com/edit/angular-snackbar-example

**Comment by Hypenate** [comment]
@zdrawku Thank you.
The issue has been fixed.
