### ISSUE TITLE
Width of text content inside igx-icon

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#13115]
Text content under most icons ends up being "inside" the size of the igx-icon.
`sentiment_very_satisfied` icon:
![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/0f8bdb0a-7585-486f-b4bc-9a732dde1158)

However, depending on the given icon, text content may go off really strange:

`medical-book` icon:
![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/355083bf-c80c-4876-ae8b-f7f710a7509b)

Considering this discrepancies, should igx-icon component care for these somehow?

**Comment by SisIvanova** [comment]
@hanastasov I believe you're trying to use an icon from the material icons extended set as a regular igx-icon. To use the `medical-book` icon, you have to first register it in your component. Here is a sample demonstrating the usage of both icons:
https://stackblitz.com/edit/6chemt?file=src%2Fapp%2Ficon-sample-1%2Ficon-sample-1.component.ts
