### ISSUE TITLE
Grid: scrollbars on top of nav-drawer

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13114]
## Description  
The grid's scrollbars have a higher z-index than the navigation-drawer so they are always on top.

 * igniteui-angular version: 16.0.5

## Attachments  
https://stackblitz.com/edit/angular-tc333n-fruz8v

![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/f83bc360-c769-4548-8ed8-7e09f038da40)

**Comment by simeonoff** [comment]
Related https://github.com/IgniteUI/igniteui-angular/issues/13054
