### ISSUE TITLE
Overlay service should return unique id

### ISSUE THREAD

**Issue by grosch-intl** [IgniteUI/igniteui-angular#13122]
## Is your feature request related to a problem? Please describe.

The `id` returned from loading a component via the overlay service doesn't have a unique ID, which makes it very hard to use with dynamically loaded components.  If I have something like this:

```html
<app-custom-first />
<app-custom-second />
```

Both of those components load other components *lazily at runtime* and show them.  Now imagine that each component needs to know when the loaded runtime component is displayed in order to do something, like via the `contentAppending` subscription.  

BOTH components are going to be given the subscription, and BOTH components are going to be told that it's id 0. The only way to know the difference is to look into the details of the event. However, as soon as I do that, the component is no longer really lazily loaded as the compiler now has to include that component in the bundle.

## Describe the solution you'd like

The `id` is currently defined as a `string`, not a `number`.  I'm requesting that you stop giving numeric identifiers and instead supply something truly unique, like a UUID.  That way, all my code can *just* check the `id` of the even against what was returned in that component's attachment.

## Describe alternatives you've considered

None.

## Additional context

None

**Comment by wnvko** [comment]
The only way, I can think of, where overlay service will return you non unique `id`s is if you are using several instances of the service in your application. Please note, this is not the intended way overlay service was designed to be used. Overlay service should always be provided as a root service in the application.

If you are using the overlay service as a single service provided in the root of your application and still get non unique `id`s please share more information how this happens. Code snippet showing the way you are using the service, or better sample reproducing this behavior will help a lot to investigate it further.

**Comment by grosch-intl** [comment]
@wnvko I don't actually "provide" it anywhere.  It's just doing `readonly #overlayService = inject(IgxOverlayService)` in each component that needs it.

**Comment by grosch-intl** [comment]
Here's a simple example showing the issue:

```ts
import {Component, DestroyRef, Directive, inject, OnInit, Type, ViewContainerRef} from '@angular/core'
import {takeUntilDestroyed} from '@angular/core/rxjs-interop'
import {IgxOverlayService} from '@infragistics/igniteui-angular'

@Component({standalone: true, template: '<p>Hi</p>'})
export class FirstDialogComponent {
}

@Component({standalone: true, template: '<p>Hi</p>'})
export class SecondDialogComponent {
}

@Directive()
abstract class Picker implements OnInit {
    readonly abstract name: string
    #viewContainerRef = inject(ViewContainerRef)
    #overlayService = inject(IgxOverlayService)
    #destroyRef = inject(DestroyRef)

    ngOnInit(): void {
        this.#overlayService.contentAppended
            .pipe(takeUntilDestroyed(this.#destroyRef))
            .subscribe(x => console.info(this.name, x))
    }

    protected attach(component: Type<unknown>): void {
        this.#overlayService.show(this.#overlayService.attach(component, this.#viewContainerRef))
    }
}

@Component({
    selector: 'app-first-picker',
    standalone: true,
    template: '<button (click)="showPicker()">Show {{ name }}</button>'
})
class FirstPickerComponent extends Picker {
    readonly name = 'First'

    protected showPicker(): void {
        super.attach(FirstDialogComponent)
    }
}

@Component({
    selector: 'app-second-picker',
    standalone: true,
    template: '<button (click)="showPicker()">Show {{ name }}</button>'
})
class SecondPickerComponent extends Picker {
    readonly name = 'Second'

    protected showPicker(): void {
        super.attach(SecondDialogComponent)
    }
}

@Component({
    selector: 'app-demo',
    standalone: true,
    imports: [FirstPickerComponent, SecondPickerComponent],
    template: '<app-first-picker/><app-second-picker/>'
})
export class DemoComponent {
}
```

**Comment by wnvko** [comment]
@grosch-intl first of all thank you for the snippet.
Looking at your code both `FirstPickerComponent` and `SecondComponentPicker` are subscribed to `contendAppended` event of the `IgxOverlayService`. Once anything calls `attach` method over the `IgxOverlayService` `contendAppended` will fire with unique id. What happens in you code in this case is in both `FirstPickerComponent` and `SecondPickerComponent` subscriptions will log this id. It does not matter if the id is number, string or UUID all subscribers will receive the same id. [Here](https://stackblitz.com/edit/scd4vf-bwgpwn?file=src%2Fapp%2Fapp.component.ts) is a StackBlitz showing this. On each button click an unique id is logged several times, as there are several subscriptions.

If what you need is to distinguish for which component `attach` method was called, you should save the `id` provided from `attach` method. Then in `contentAppended` subscription you should compare the emitted `id` against the one you have saved when `attach` was called. If the `id`s are the same overlay service just appended the component you need.
