### ISSUE TITLE
Some keyboard operations on the filter UI of the Grid show errors in the browser's console

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-angular#13155]
## Description  

Some keyboard operations on the filter UI of the Grid show errors in the browser's console.

## Steps to reproduce  

1. Open the filter UI of the igc-grid by clicking the "Filter" button. (The focus will be entered into the filter input box.)
  https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing#angular-grid-cell-editing-and-edit-templates-example (Stackblitz snapshot: https://stackblitz.com/edit/dsjjm3)
2. Enter `Shift` + `Tab` key. (The filter input box lost focus but is still active.)
3. Enter the `Left` or `Right` key. (Important: This seems to be the trigger of the problem I'm reporting in this issue. Pressing any other keys doesn't cause the problem.)

## Result  

After doing that, you will find there is an error below in the browser's console:
```
ERROR TypeError: Cannot read properties of undefined (reading 'level')
```

After once happens that error, any user interaction events, such as keydown, mousemove, etc., cause the same error continuously.

## Expected result  

No error messages are in the browser's console.

## Attachments
- https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing#angular-grid-cell-editing-and-edit-templates-example
- https://jp.infragistics.com/products/ignite-ui-blazor/blazor/components/grids/grid/cell-editing

![movie-002](https://user-images.githubusercontent.com/102948935/234200420-cf6608fd-bc6f-4e1a-b210-663832c12e60.gif)

**Comment by damyanpetev** [comment]
Also got a different error locally, though still around header navigation in the service
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/632ab873-fefc-4aca-9c61-7e6f3c025e74)
