### ISSUE TITLE
Grid validation is not triggered with custom edit column templates when adding a row

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#13165]
## Description  
We have an IgxGrid with custom edit column templates and enabled validation for these columns with the `required ` property. When adding a row the grid validation is not triggered and the notification icon and tooltip for required fields do not appear.

 * igniteui-angular version: ^14.2 ^15.1 ^16.0

## Steps to reproduce  

1. Open this [sample](https://stackblitz.com/edit/24nhly?file=src%2Fapp%2Fgrid%2Fgrid-column-hiding-toolbar-sample%2Fgrid-column-hiding-toolbar-sample.component.html).
2. Observe the created custom edit column templates and enabled validation. 
3. Add a row to the grid.
4. Go through the cells of the different columns.

## Result  
Grid validation is not triggered and the notification icon and tooltip for required fields do not appear.
![result](https://github.com/IgniteUI/igniteui-angular/assets/48180072/a34f1528-7ee1-492e-b0e7-5331d7fc698b)

## Expected result  
Grid validation is triggered and the notification icon and tooltip for required fields appear.
![expect](https://github.com/IgniteUI/igniteui-angular/assets/48180072/21d5e23f-66ee-4952-a0dc-a51f15d86ffb)

**Comment by mddragnev** [comment]
This is somehow related to https://github.com/IgniteUI/igniteui-angular/issues/15379. The related PR fixes the bug where on row adding, initially, the templated columns does not apply validation.However, I dont think that the missing icon and tooltip is a bug because once you add a template of the column the user is in charge to show the validation message. @MayaKirova What do u think?

**Comment by MayaKirova** [comment]
> This is somehow related to [#15379](https://github.com/IgniteUI/igniteui-angular/issues/15379). The related PR fixes the bug where on row adding, initially, the templated columns does not apply validation.However, I dont think that the missing icon and tooltip is a bug because once you add a template of the column the user is in charge to show the validation message. [@MayaKirova](https://github.com/MayaKirova) What do u think?

You can show the validation UI if you pass reference to the form control to the custom editor, for example:

```
                <ng-template igxCellEditor let-cell="cell" let-value let-fc="formControl">
                    <input  type="text" [igxFocus]="true" [formControl]="fc"/>
                </ng-template>
```

So that it can react to user interactions (for example, on focus). Otherwise it would only trigger after changing the value.
