### ISSUE TITLE
The columnFormatter pipe was converted to standalone but it was not exported

### ISSUE THREAD

**Issue by pierophp** [IgniteUI/igniteui-angular#13168]
## Description  
The columnFormatter pipe was converted to standalone, but it was not exported.

 * igniteui-angular version: 16.0.6

## Steps to reproduce  

1. Use the columnFormatter (before 16, it works)

## Result  
Even if import it manually:
```js
import { IgxColumnFormatterPipe } from '@infragistics/igniteui-angular/lib/grids/common/pipes';
```
This error  happens:

Module not found: Error: Package path ./lib/grids/common/pipes is not exported from package ***\node_modules\@infragistics\igniteui-angular (see exports field in ***\node_modules\@infragistics\igniteui-angular\package.json)

**Comment by kdinev** [comment]
@pierophp Just a quick question. The `IgxColumnFormatterPipe` was previously exported, but it wasn't actually intended for public use, hence it undocumented. Could you share what your usage of the pipe is and how you pass it back to a grid column if you override it?

**Comment by pierophp** [comment]
@kdinev Sorry for the delay; I didn't see the message before.

As that was never intended to use, we can close this issue. 

My use case was to use a formatter without creating a new pipe, like that:
```html
<igx-column [field]="'test'"
                    [header]="'test'"
                    [width]="'170px'"
                    [sortable]="true"
                    [movable]="true"
                    [resizable]="true"
                    [disableHiding]="false"
                    [dataType]="'string'"
                    [formatter]="testFormatter">
  <ng-template igxCell
                let-cell="cell"
                let-value>
    <span [title]="value">
      {{ value | columnFormatter: testFormatter }}
    </span>
  </ng-template>
</igx-column>
```
I realized that the ngTemplate was not really necessary for my use case, so I just removed it.
