### ISSUE TITLE
IgxGrid: Horizontal scrollbar is displayed when row selection is enabled

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#13161]
## Description  
When there are no row selection checkboxes in the grid, the columns are taking the entire space and there is no horizontal scrollbar if you enable the row selection a scrollbar would be rendered.

## Steps to reproduce  

1. Open [this ](https://stackblitz.com/edit/6nzdyv?file=src%2Fapp%2Ftree-grid-selection-sample%2Ftree-grid-selection-sample.component.html) demo.
2. Change the selection to 'multiple'

## Result  
A horizontal scrollbar is displayed

## Expected result  
The first three columns should resize in order to take the available space and there shouldn't be a scrollbar if there is enough space.

## Attachments  
![grid-selection-sizing](https://github.com/IgniteUI/igniteui-angular/assets/52423497/2a7c63f3-4ad7-412f-bfd5-c949a973cb0b)

**Comment by Glopter** [comment]
Is it possible to estimate until there will be a solution here?

**Comment by hanastasov** [comment]
> Is it possible to estimate until there will be a solution here?

Hi @Glopter,
Initial estimation is we should be able to have the issue fixed and verified next week, which means the first patch after next week should contain the fix (4th September). The issue is now added to the sprint and we will try to have the fix even earlier. I will keep you posted.

**Comment by hanastasov** [comment]
> 

Hi @Glopter, the issue was not worked on until due to priorities. I am re-prioritizing it again for a fix to be available with a patch until 18th September

**Comment by Glopter** [comment]
Thank you @hanastasov !
