### ISSUE TITLE
Fluent Theme: border radius too big

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13177]
## Description  
Since version 16.0.7 the border radius in the fluent theme is very big.
Is this an intended change?

 * igniteui-angular version: 16.0.7

## Attachments  
https://stackblitz.com/edit/auu7xc

Before:
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/5976e106-50f8-4669-9684-c29df4d85e5b)

After:
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/75fe58ad-faa7-472f-a6d1-cb6ee088a2fb)

**Comment by simeonoff** [comment]
@Timmeeeey Sorry about that, we've been doing quite a few updates around theming and roundness especially. I've just tagged 16.0.9. It should fix the issue for you.
