### ISSUE TITLE
Badge - Add support for material extended icons

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/igniteui-angular#13174]
## Description  
Add support for material extended icons in Badge component

**Comment by damyanpetev** [comment]
@simeonoff Before I forget again:
I realize the description didn't give details on that and the implementation already done would work just fine, but for our needs in the App Builder and code generation we would ideally [also] have the icon projected.
Just like the Avatar does already btw and that would actually bring it more in line with the Web Components implementation that used slotted icons exclusively. It'll also allow us to project other icon elements (not just igx-icon) which we do use at least for the moment.
