### ISSUE TITLE
Grid selectedCells does not return all selected cells

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#13170]
## Description  
The selectedCells property of the grid does not return all selected cells as it is mentioned into the topic:
![image](https://github.com/IgniteUI/igniteui-angular/assets/52423497/cc40e4c5-9de4-49ba-9b95-ed0caf7f7f0a)

## Steps to reproduce  

1. Run this sample
2. Select cells with ProductID 1 to 20 with mouse drag
3. Click on the 'Get Selected Cells' button

## Result  
The cells logged in the console are with rowIndex from 6 to 19

## Expected result  
The cells logged in the console are with rowIndex from 0 to 19

## Attachments  

![grid-selection](https://github.com/IgniteUI/igniteui-angular/assets/52423497/4dcc605c-7ce0-4106-aee6-60f2ebedc119)

**Comment by hanastasov** [comment]
`selectedCells` will return cells from:
- all visible rows (rows in the view)
- all columns, regardless if they are in or out of view.

Please update documentation with that.
