### ISSUE TITLE
The selected event of the IgxButtonGroup is fired after the component is loaded if there is initially selected button

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#13172]
## Description  
The `selected` event of the IgxButtonGroup component is fired without any user interaction after the component is loaded, if in the component there is an initial selected button. 

 * igniteui-angular version: ^14.2 ^15.1 ^16.0

## Steps to reproduce  

1. Open this [sample](https://stackblitz.com/edit/1deymq-rkw7j5?file=src%2Fapp%2Fbutton-group-sample-1%2Fbutton-group-sample-1.component.html).
2. Observe that the one of the buttons in the button group is initially selected.
3. Open the developer console and see that the `selected` event was fired without any user interaction.

## Result  
The selected event of the IgxButtonGroup component is fired after the component is loaded. 

## Expected result  
The selected event of the IgxButtonGroup component should not be fired after the component is loaded, instead, it should only fire when the button is selected by the user interaction.

## Attachments  
![issue](https://github.com/IgniteUI/igniteui-angular/assets/48180072/0b9d648e-e5c4-4e97-a449-2ce329676d4a)

**Comment by grosch-intl** [comment]
This bug results in very complicated code trying to figure out if the user pressed the button, and thus actions need to be taken, or if it was just component initialization, and therefore no actions should be done.

**Comment by grosch-intl** [comment]
@ChronosSF What release will this be in? Do you have an ETA for deployment?
