### ISSUE TITLE
Feature request - event binding and style/class binding capability for igx-grid-row

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1317]
### Description  
Similar to #1079 , I'd like to conditionally change `igx-grid-row` style( such as background color) according to its data or something. In addition, I'd like to do event binding to `igx-grid-row`.

### Expect

For example, I'd like `igx-grid-row` to become like `mat-row`.  Here is a sample.
https://stackblitz.com/edit/angular-material-datatable
```
    <mat-row *matRowDef="let row; columns: displayedColumns;"
             (mousedown)="onMousedown($event)"
             (mouseover)="onMouseover($event)"
             (click)="onClick($event)"
             [class.foo]="true"
             [style.backgroundColor]="'red'">
    </mat-row>
```
- `igx-grid-row` can be defined as a child of `igx-grid`.
- Event binding(click, mousedown, mouseover and so on...) can be available to `igx-grid-row`.
- Style and Class binding can be available to `igx-grid-row`.

This is just my idea. If you have any better ideas, that'll be great!

I'd appreciate your consideration.

**Comment by kdinev** [comment]
Since we don't have a row component, we don't have a way to expose this on a row level currently.
