### ISSUE TITLE
[IgxSimpleCombo]: input text is not cleared on blur when bound to remote data

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#13220]
## Description  

When filtering the combo data and clicking outside the combo (or pressing `Tab`) in order to lose the input's focus, the text is not cleared when using remote data.
When using local data and performing the above steps - the text is cleared.

 * igniteui-angular version: 16.0.x, 15.1.x, 14.2.x
 * browser: any

## Steps to reproduce  

1. Open the Simple Combo Remote Binding demo [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/simple-combo#demo).
2. Type some text inside the input in order to filter the data, e.g., `cha`.
3. Click outside the combo or press `Tab`. -> **the text remains**
4. Type some text until the `The list is empty` message appears, e.g., `chaa`.
5. Click outside the combo or press `Tab`. -> **the text is cleared**

## Result  
The text is not cleared on blur if there are filtered results.

## Expected result  
The text should be cleared if there is no selected item.

## Attachments  
- Simple Combo with local data
![simple-combo-clear1](https://github.com/IgniteUI/igniteui-angular/assets/49126110/fce44cec-bf35-44e6-91bc-55b7d75669b5)

- Simple Combo with remote data
![simple-combo-clear2](https://github.com/IgniteUI/igniteui-angular/assets/49126110/eb21a40d-b114-48c1-9b9e-6912261a70ca)

**Comment by Timmeeeey** [comment]
Hi,
is there any update on this bug?

**Comment by RivaIvanova** [comment]
Hi @Timmeeeey,
Currently, there are pending PRs targeting this behavior - https://github.com/IgniteUI/igniteui-angular/pull/13507, https://github.com/IgniteUI/igniteui-angular/pull/13509, https://github.com/IgniteUI/igniteui-angular/pull/13510.
