### ISSUE TITLE
Property 'updateCell' does not exist on type 'GridType'

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#13239]
## Steps to reproduce  

1. Attach on `cellEditExit` event
2. Try to call `updateCell` on eventArgs.owner

P.S: Check other CRUD methods like `updateRow` too, this should also ve avialable on GridType.

```html
<igx-grid [data]="data" (cellEditExit)="cellEditExit($event)">
```

```typescript
  public cellEditExit(eventArgs: IGridEditDoneEventArgs) {
    eventArgs.owner.updateCell(
      eventArgs.newValue,
      eventArgs.rowID,
      eventArgs.column.field
    );
  }
```

## Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/7457811f-db5c-4f2f-880e-28858e6817d1)

**Comment by GrblackStar** [comment]
Note: PivotGridType extends from GridType. Due to the structure of the PivotGridType, the changes to the GridType might create issues to the PivotGridType.

**Comment by hanastasov** [comment]
@GrblackStar , please create PRs for that against 15.1.x, 16.0.x branches as well, not only against master.
