### ISSUE TITLE
The exportRow's formatting function is only being called with rawValue.

### ISSUE THREAD

**Issue by acemir** [IgniteUI/igniteui-angular#13234]
The exportRow's formatting function is only being called with rawValue.
https://github.com/IgniteUI/igniteui-angular/blob/73d7949c23b33cf3947a5b760df1ba8cdffd9589/projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts#L471

Although the formatter function can receive a rowData, if I have a formatting function that uses rowData, it will not execute correctly at this point.
https://github.com/IgniteUI/igniteui-angular/blob/73d7949c23b33cf3947a5b760df1ba8cdffd9589/projects/igniteui-angular/src/lib/grids/common/grid.interface.ts#L137

Can we add the corresponding data in this call as well?

```diff
- let formattedValue = shouldApplyFormatter ? e.formatter(rawValue) : rawValue; 
+ let formattedValue = shouldApplyFormatter ? e.formatter(rawValue, record.data) : rawValue; 
```

_Originally posted by @acemir in https://github.com/IgniteUI/igniteui-angular/discussions/13127_

**Comment by RivaIvanova** [comment]
### Steps to reproduce:

1. Add a formatter function to a column.
```html
<igx-grid #grid [data]="data">
  <igx-column
    [field]="'ProductName'"
    [header]="'Formatted Value'"
    [dataType]="'string'"
    [formatter]="formatter"
  >
  </igx-column>
</igx-grid>
```
2. Set up the formatter to access any value in **rowData**.
```ts
public formatter = (value: any, rowData: any) => {
  return `${value} - ${rowData.UnitPrice}$`;
};
```
3. Export the grid to Excel.

### Result
An error is thrown and the grid is not exported.

![export-formatted-values](https://github.com/IgniteUI/igniteui-angular/assets/49126110/4e82e51c-346d-496c-ab9d-05700402bcbe)

[Here](https://stackblitz.com/edit/ysuav4-4ukxk6?file=src%2Fapp%2Fgrid%2Fgrid-sample-pinning%2Fgrid-toolbar-pinning.component.ts,src%2Fapp%2Fgrid%2Fgrid-sample-pinning%2Fgrid-toolbar-pinning.component.html) could be found a sample reproducing the behavior.
