### ISSUE TITLE
disable radio button in reactive form

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13236]
## Description  
Disabling individual radio buttons in a radio group doesn't work when using formControlName.
There is an angular warning: "It looks like you're using the disabled attribute with a reactive form directive. ..."

Moving the formControlName to `igx-radio-group` solves this issue but then #11846 doesn't work anymore.

 * igniteui-angular version: 16.0.11

## Steps to reproduce  

```html
<igx-radio-group>
  <igx-radio formControlName="radio" value="London">London</igx-radio>
  <igx-radio formControlName="radio" value="New York">New York</igx-radio>
  <igx-radio formControlName="radio" value="Tokyo">Tokyo</igx-radio>
  <igx-radio formControlName="radio" value="Sofia" [disabled]="true">Sofia</igx-radio>
</igx-radio-group>
```

## Result  
Radio button "Sofia" is not disabled.

## Expected result  
Radio button "Sofia" should be disabled.

## Attachments  
https://stackblitz.com/edit/hyytgl

**Comment by simeonoff** [comment]
When using the radio group in reactive forms, set the `formControlName="radio"` on the radio group. Once you do that, handle the disabled state of individual radio buttons by setting the `disabled` input property on the ones that need to be disabled.

The following should work fine:

```html
<article class="sample-column" [formGroup]="form">
  <igx-radio-group formControlName="radio">
    <igx-radio value="London">London</igx-radio>
    <igx-radio value="New York">New York</igx-radio>
    <igx-radio value="Tokyo">Tokyo</igx-radio>
    <igx-radio value="Sofia" [disabled]="true" >Sofia</igx-radio>
  </igx-radio-group>
</article>
```

To disable all radio buttons (as a workaround for now) you can just set the `disabled` input property on all of them. I understand that we can't ignore the fact that Angular provides the `disabled` option on the FormControl object, which currently is not being utilized by the radio group - this will be amended in an upcoming PR that will also close this issue.

If you want to have a value selected on initialization without having to specify the disabled state on the form control, just pass it as argument to the FormControl constructor:

```ts
public form = new FormGroup({
   radio: new FormControl('London'),
});
```
