### ISSUE TITLE
HierarchicalGrid: columnInit event is not emitted for rowIslands

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#13251]
## Description  
columnInit event is not emitted for rowIslands

## Steps to reproduce  

1. Open [this ](https://stackblitz.com/edit/icblvp?file=src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-column-resizing%2Fhierarchical-grid-resizing.component.ts) sample
2. Expand some row

## Result  
The columnInit is not emitted for child grids

## Expected result  
The event should be emitted

**Comment by IMinchev64** [comment]
Wouldn't it be better to use gridInitialized or gridCreated in this example?

**Comment by IMinchev64** [comment]
So, what I have managed to find out is that the property `[autoGenerate]` affects whether `columnInit` is emitted or not in row-island. When the property is set to false `columnInit` is not emitted. On the contrary, when it is set to true, `columnInit` emits as intended.

This behavior is not intended and I am currently trying to investigate what causes the issue.

**Comment by dkamburov** [comment]
@IMinchev64 Can you please create prs for 16.0 and 15.1 as well?
