### ISSUE TITLE
[IgxButtonGroup]: selectButton method does not emit selected event

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#13262]
## Description  
The `deselectButton` method emits the `deselected` event, however, the `selectButton` method does not emit the `selected` event.

 * igniteui-angular version: 16.1.x, 16.0.x, 15.1.x
 * browser: any

## Steps to reproduce  

1. Open this sample [here](https://stackblitz.com/edit/rdk6sa-hr9d9y?file=src%2Fapp%2Fbutton-group-sample-2%2Fbutton-group-sample-2.component.html,src%2Fapp%2Fbutton-group-sample-2%2Fbutton-group-sample-2.component.ts).
2. Open DevTool Console.
3. Click the `select` button.
4. Click the `deselect` button.

## Result  
The `selectButton` method does not emit the `selected` event.

## Expected result  
The `selectButton` method should emit the `selected` event.

**Comment by simeonoff** [comment]
This is the intended behavior. This change was introduced with [this PR](https://github.com/IgniteUI/igniteui-angular/pull/13183). The button shouldn't emit the select event upon programmatic invocation of selection operations. The button group emitting the deselect event upon calling `deselectButton` is a mistake that should be corrected. These events should only be emitted on user interaction.
