### ISSUE TITLE
IgxDrag not performing pointer events on correct element when using ShadowDom

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#13302]
## Description  
IgxDrag is not registering pointerup event when the target element is other than the draggable element itself when using root ShadowDom.

This was fixed in #12966, but the issue was not fixed in older version due to it changing to enhancement. 

 * igniteui-angular version: 15.1.x
 * browser: any

## Steps to reproduce  

1. Open the Drag/Drop demo
2. Set encapsulation of the Sample component to `Shadow`
3. Add the following element and just click it
4. Move the mouse and observe it creating a ghost

```html
       <div style="width: 500px; height: 300px;">
            <div igxDrag>
                <div igxDragHandle>
                    <span>Drag me</span>
                    <igx-icon>drag_indicator</igx-icon>
                </div>
            </div>
        </div>
```

## Result  
The pointerup event is not fired correctly, thus resulting in moving the element when moving with the mouse.

## Expected result  
The element should not start dragging after clicking on it

**Comment by dkamburov** [comment]
@skrustev does that one has pr to master? Please link it and close the issue
