### ISSUE TITLE
Row Selection: selecting all rows is slow when having large amount of data

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#13325]
## Description  
When having an IgxGrid with a large amount of data, e.g., 60 000 records, selecting all rows takes a certain amount of time. This is true with or without a `primaryKey` set, however, when setting the `primaryKey` it takes even more time.

The above is not reproducible when using version 14.2.x.

* Version 16.1.x, 16.0.x, 15.1.x:

![row-selection v16 0](https://github.com/IgniteUI/igniteui-angular/assets/49126110/7a188d29-a223-407f-95af-5f081f3d0d50)

* Version 14.2.x:

![row-selection 14 2](https://github.com/IgniteUI/igniteui-angular/assets/49126110/3d8eefd4-8104-4f5f-9973-2880e8ef193f)

 * igniteui-angular version: 16.1.x, 16.0.x, 15.1.x
 * browser: any

## Steps to reproduce  

1. Open this sample [here](https://stackblitz.com/edit/6mnlvy-ufxpjw?file=src%2Fapp%2Fgrid%2Fgrid-toolbar-sample%2Fgrid-toolbar-sample-1.component.ts,src%2Fapp%2Fgrid%2Fgrid-toolbar-sample%2Fgrid-toolbar-sample-1.component.html) and select all rows.

## Result  
The rows are selected slower compared to version 14.2.x.

## Expected result  
The rows should be selected similarly to version 14.2.x with or without a primary key.

**Comment by hanastasov** [comment]
in 15.1, a breaking & behavioral change was introduced (see [Changelog](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md)): 

> - **Breaking Change** - `rowSelectionChanging` event arguments are changed. Now the `oldSelection`, `newSelection`, `added` and `removed` collections no longer consist of the row keys of the selected elements when the grid has set a primaryKey, but now in any case the row data is emitted.
> When the grid is working with remote data and a primary key has been set- for the selected rows that are not currently part of the grid view, will be emitted a partial row data object.

To achieve this, on selecting all rows, more code is executed, so when regarding 60k rows, it obviously affect eprformance:

https://github.com/IgniteUI/igniteui-angular/pull/12400/files#diff-ce4e4207ce86db87f5289ba3e1bc805c6d5131733ea6a73ca2a1de32bb8bf872R405

We can think of some optimization here, though I am not sure is possible at all.
