### ISSUE TITLE
Grid LastSearchInfo matchInfoCache missing/wrong docs

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#13334]
I've noticed another thing
![image](https://github.com/IgniteUI/igniteui-angular/assets/26311786/46e510c4-b4a9-45d9-8bc1-35ab9b2d604d)
this is from your angular docs
But in reality
![image](https://github.com/IgniteUI/igniteui-angular/assets/26311786/5601c43d-3519-4c54-8b2d-a0f2a01ec095)

_Originally posted by @fexxdev in https://github.com/IgniteUI/igniteui-angular/issues/13265#issuecomment-1655437725_

Edit: Related to issue #13051

**Comment by lalo-mx** [comment]
It was useful to have the column and row available in matchInfoCache, this can be used to customize the highlight by row/column.

**Comment by lalo-mx** [comment]
> > It was useful to have the column and row available in matchInfoCache, this can be used to customize the highlight by row/column.
> 
> @lalo-mx Thanks for the feedback! For how the `matchInfoCache` was exposed (it almost wasn't) and typed (hint: also was `any[]`), you sure did some digging :) Still, the use for it you describe sounds interesting and makes sense in the context of the grid and something we'll want to consider for this issue. Assuming you've implemented this already, I'd actually be interested to hear about the customizations you're making - perhaps even a GH repo if public / small repro app / Stackblitz / etc. Just as something to inform on the useful metadata in there for us to keep in mind.

https://stackblitz.com/edit/xrrp7g-nqysqk?file=src%2Fapp%2Fgrid%2Fgrid-column-data-types-sample%2Fgrid-column-data-types-sample.component.html

![image](https://github.com/IgniteUI/igniteui-angular/assets/7459881/1226c3d6-5f36-4c3a-ba13-8c3e91473ad3)

[xrrp7g-nqysqk.zip](https://github.com/IgniteUI/igniteui-angular/files/12253861/xrrp7g-nqysqk.zip)

**Comment by damyanpetev** [comment]
@lalo-mx Thank you for the sample. As an immediate fix `matchInfoCache` with #13365 and we'll only consider changes in a next major release, while still keeping in mind usage like your scenarios.

**Comment by fexxdev** [comment]
@damyanpetev either case i've fixed what was broken locally. You can close this issue if it's done. Thank you!
