### ISSUE TITLE
12.3.13 not found? 

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#13345]
```
npm ERR! 404 Not Found - GET https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-12.3.13.tgz
npm ERR! 404 
npm ERR! 404  '@infragistics/igniteui-angular@12.3.13' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ui'
```
did you remove 12.3.13? Can you put it back please? our ci is broken

**Comment by zdrawku** [comment]
Hey @SkylerLutz, it looks like the package management service that we use for the licensed packages was interrupted in some way. Now everything should be fine.

Please do consider upgrading to a newer version of the library as 12.3.x is out of support for some time now.

**Comment by SkylerLutz** [comment]
@zdrawku @kdinev this reoccurred today -- can someone please take a look? our ci is broken
```
14:00:27  npm ERR! 404 Not Found - GET https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-12.3.21.tgz
14:00:27  npm ERR! 404 
14:00:27  npm ERR! 404  '@infragistics/igniteui-angular@12.3.21' is not in the npm registry.
14:00:27  npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by kdinev** [comment]
@SkylerLutz Apologies that I did not respond earlier. It seems like we've had a temporary service outage yesterday. You probably already tried to rerun the CI. Does the issue persist?
