### ISSUE TITLE
Igx icons in prefix and suffix are now way smaller 

### ISSUE THREAD

**Issue by fexxdev** [IgniteUI/igniteui-angular#13344]
## Description  
Something has changed and hasn't been documented on the upgrade guide on igx 16 as far as im aware of.
All the suffix or prefix icons are now defaulted to 16px and if you change their size to what it was before (24px) then it's all misaligned.

Also, there's no way to customize it through scss variables as there's no prefix/suffix icon size in the available vars. 

The only way i found to fix this is by defining a global theme for icons

```
$j-icon-theme: icon-theme(
    $size: var(--font-size-h5) // 1.25rem or 20px
);
```

Before
![image](https://github.com/IgniteUI/igniteui-angular/assets/26311786/19570385-b3d5-4ed3-9760-2b308296d179)

After
![image](https://github.com/IgniteUI/igniteui-angular/assets/26311786/577a37ba-f3ae-4ae6-b354-48d78c69e150)

Before
![image](https://github.com/IgniteUI/igniteui-angular/assets/26311786/bfade5da-bbed-4c18-9334-787ea6526df4)

After
![image](https://github.com/IgniteUI/igniteui-angular/assets/26311786/6b224958-2a74-48b9-8c6f-58ac3f19802b)

I've noticed that changing igx input group display density changes also igx icon size. Eg: display density cosy will set prefix / suffix icon to 20px
But before those two behaviors where not connected

 * igniteui-angular version: 16.0.14
 * browser: Chrome latest (115.0.5790.110) x64

![image](https://github.com/IgniteUI/igniteui-angular/assets/26311786/598f67ae-00ee-433f-bb84-288b4ee63a71)

```
<igx-input-group [focus]="true" type="border" displayDensity="compact">
    <igx-prefix>

        <igx-icon family="material-icons">search</igx-icon>

    </igx-prefix>

    <input #searchBar igxInput type="text" role="searchbox" [ngModel]="text" (ngModelChange)="setText($event)"

        (keyup.enter)="onEnterPressed()" placeholder="shared.search" l10n-placeholder l10nTranslate>

    <igx-suffix [class.visibility-hidden]="!(text?.length > 0)" (click)="setText('')">

        <igx-icon>clear</igx-icon>
    
    </igx-suffix>

    <igx-suffix>

        <igx-icon (mouseenter)="showTooltip = true" (mouseleave)="showTooltip = false" family="material-icons-outlined"

                  class="j-color-primary">info

        </igx-icon>

    </igx-suffix>

</igx-input-group>
```

**Comment by SisIvanova** [comment]
Hi @fexxdev 
The change in the size of the prefix/suffix icons and its relation to the `igx-input-group` display density is by design. If you want to customize the `igx-icon` size you can use the code snippet below: 

```scss
igx-input-group {
    igx-icon {
        --size: 36px;
    }
}

// use ::ng-deep for components that has nested `igx-input-group`
::ng-deep {
    igx-date-picker {
        igx-icon {
            --size: 36px;
        }
    }
}
```

**Comment by fexxdev** [comment]
@SisIvanova Thanks for the explanation! 
I was confused because in the documentation it's never written, so i thought it was a problem in our end. 
Anyway, this issue can be closed :)
