### ISSUE TITLE
Issues with window events and elements in child windows

### ISSUE THREAD

**Issue by agencia-estado** [IgniteUI/igniteui-angular#13359]
## Is your feature request related to a problem? Please describe.
When render components in child windows, like Angular CDK portal for example, there are some issues with events like window resize, element resizeobservable. Some parts of the code don't use injected document.defaultView to reference a window, instead call window directly, so events are bound to main window and not child window.

## Describe the solution you'd like
The solution seems simple to me.
In the GridComponent, for example, in the _zoneBegoneListeners method, the window resize event is implemented using the window directly.

**Current**
`fromEvent(window, 'resize').pipe(takeUntil(this.destroy$)).subscribe(() => this.resizeNotify.next());`

**Solution**
`fromEvent(this.document.defaultView, 'resize').pipe(takeUntil(this.destroy$)).subscribe(() => this.resizeNotify.next());`

So to fix all components that subscribe to window events this solution fixes the issue

Another issue is with resizeObservable, because it always call window.ResizeObserver

**Current**
**File: utils.ts**
```
export const getResizeObserver = () => window.ResizeObserver;

export const resizeObservable = (target: HTMLElement): Observable<ResizeObserverEntry[]> => new Observable((observer) => {
    const instance = new (getResizeObserver())((entries: ResizeObserverEntry[]) => {
        observer.next(entries);
    });
    instance.observe(target);
    const unsubscribe = () => instance.disconnect();
    return unsubscribe;
});
```
**Solution**
```
export const getResizeObserver = (win) => (win || window).ResizeObserver;

export const resizeObservable = (target: HTMLElement, win): Observable<ResizeObserverEntry[]> => new Observable((observer) => {
    const instance = new (getResizeObserver(win))((entries: ResizeObserverEntry[]) => {
        observer.next(entries);
    });
    instance.observe(target);
    const unsubscribe = () => instance.disconnect();
    return unsubscribe;
});
```
And in every resizeObservable call, pass the correct window.

**Method _zoneBegoneListeners  in GridComponent**

**Current**
`resizeObservable(this.nativeElement).pipe(takeUntil(this.destroy$)).subscribe(() => this.resizeNotify.next());`

**Solution**
`resizeObservable(this.nativeElement, this.document.defaultView).pipe(takeUntil(this.destroy$)).subscribe(() => this.resizeNotify.next());`

----------------------------------------------------------

Thank you very much and I look forward to your reply.

**Comment by agencia-estado** [comment]
Any news? Tks

**Comment by ChronosSF** [comment]
Hello @agencia-estado , we'll consider this for the Q4 release cycle, however, igniteui-angular is an  open-source project and since you already did research on what needs changing and have validated the changes for these particular use-cases I wanted to point you to our contributing guidelines - https://github.com/IgniteUI/igniteui-angular/blob/master/.github/CONTRIBUTING.md#overview . We welcome all community contributions to the repo.
