### ISSUE TITLE
Badge component to do content projection

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#13375]
Current way of setting icon to a badge component is through the input property, but would be nice for Badge component to take into account what content is put inside the badge and have it projected at the proper place:

```html
<!-- Current way -->
<igx-badge class="badge" icon="accessibility_new">
</igx-badge>

<!-- Not working, but would be nice to have it working -->
<igx-badge >
    <igx-icon>accessibility_new</igx-icon>
</igx-badge>
```

**Comment by SisIvanova** [comment]
This feature request is already implemented  https://github.com/IgniteUI/igniteui-angular/pull/13315
