### ISSUE TITLE
[IgxButtonGroup] Selected event is fired on init, not only when the selection is actually changed

### ISSUE THREAD

**Issue by gmartinezig** [IgniteUI/igniteui-angular#13371]
## Description  
When a buttongroup component contains a set of buttons and one of them is selected by default, the igx-buttongroup component triggers a selected event on init.
That's not good, because the host already knows the state of the collection it's setting as source of the button group component.
- Depending on the scenario it could lead to write unnecessary defensive code for every event handler.
- The event will be fired once per buttongroup component instance, which could lead to performance issues, depending on how many instances we have, and how heavy is the code that's being executed on its handlers.

 * igniteui-angular version: 15.11.9

## Steps to reproduce  

Run the following sample code:

_Template:_
```
<igx-buttongroup (selected)="handleThemeSelected($event)">
    <button igxButton *ngFor="let item of themeItems" [selected]="item.selected">
        {{item.text}}
    </button>
</igx-buttongroup>
```
_Code:_
```
public themeItems = [
    { text: 'Light' },
    { text: 'Dark', selected: true },
];

public handleThemeSelected(ev: IButtonGroupEventArgs){
    console.log(ev);
}
```

## Result  
handleThemeSelected function is called on init.

## Expected result  
handleThemeSelected function should be only called when the selection actually changes.

**Comment by pmoleri** [comment]
Adding point from guideline from Google Chrome developer relations:
> **Do not dispatch events in response to the host setting a property (downward data flow).**
> Why? | Dispatching  an event in response to a host setting a property is superfluous (the  host knows the current state because it just set it). Dispatching events  in response to a host setting a property may cause infinite loops with  data binding systems.

https://web.dev/custom-elements-best-practices/#events

**Comment by simeonoff** [comment]
This has already been resolved with https://github.com/IgniteUI/igniteui-angular/pull/13229
