### ISSUE TITLE
IgxCombo/IgxSimpleCombo: remote binding not working without valueKey

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13373]
## Description  
IgxCombo/IgxSimpleCombo are not working correctly when valueKey is not set and remote binding is used.

 * igniteui-angular version: 16.0.17
 * browser: any

## Steps to reproduce  

1. Use remote binding and no valueKey
2. select an item

## Result  
see gif below.

## Attachments  
IgxSimpleCombo
https://stackblitz.com/edit/xxvkdn
![2023-08-11_09h16_20](https://github.com/IgniteUI/igniteui-angular/assets/46870283/f68bd24c-5df2-4b51-b93b-1077f21ae9dd)

IgxCombo
https://stackblitz.com/edit/23ntfr
![2023-08-11_09h17_31](https://github.com/IgniteUI/igniteui-angular/assets/46870283/c9db8ca6-37ed-4950-a897-4cb459bf9dd7)

**Comment by ChronosSF** [comment]
@Timmeeeey , we are prioritizing this for the sprint starting Oct 16.

**Comment by ChronosSF** [comment]
Going over this again, this is actually expected - in remote scenarios, the control should consider the data mutable and quite likely to change between the frequent requests, so it needs an unique property to store selection with. So even if an entity changes that property can still be used to uniquely define it. For a combo that's the value key, for grid it would be the primary key but they essentially has the same purpose. This is also explained in the documentation: https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo-remote#handling-selection

For this reason I am marking this as not a bug.
