### ISSUE TITLE
igx-button-group does not bind to onClick

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#1338]
### Description  
The igx-button-group doesn't have an onClick even to bind to as described in the documentation.

### Steps to reproduce  

1. Include an igx-button-group component in your app.
2. Bind a class method to the onClick event on the component.

### Result  
The method is never called as the onClick event is never fired on the igx-button-group component. 

### Expected result  
Either the button onClick event must bubble up to the igx-button-group component or the onClick event should not be listed in the documentation for the igx-button-group component.

**Comment by DDavidkov** [comment]
@simeonoff I can't reproduce that. I am attaching the sample I used to test this, you can see in the console that "Click" messages are outputted whenever a button from the button group is clicked.
[buttonGroupClick.zip](https://github.com/IgniteUI/igniteui-angular/files/2017345/buttonGroupClick.zip)
