### ISSUE TITLE
Utilize the booleanAttribute transformation

### ISSUE THREAD

**Issue by grosch-intl** [IgniteUI/igniteui-angular#13381]
## Is your feature request related to a problem? Please describe.

Please update all of your boolean inputs to use the booleanAttribute transformation.

## Describe the solution you'd like

Instead of `@Input() filterable = true` use the new `@Input({transform: booleanAttribute}) filter = true`.

**Comment by ChronosSF** [comment]
@grosch-intl , this is something we'd like to do. We'll try to get this in before EOY.
