### ISSUE TITLE
Disable items in igx-simple-combo

### ISSUE THREAD

**Issue by yl-endress** [IgniteUI/igniteui-angular#13382]
## Is your feature request related to a problem? Please describe.
Hey guys,

In the <igx-simple-combo> i'd like to disable some items. It would be nice if you can also add besides a [data] input an additional import for [disabledData].

Currently, I tried to resolve this by a directive. Unfortunately, it looks like you didn't published the IgxComboItemComponent:

```
index.js:493 [webpack-dev-server] ERROR

projects/my-lib/src/lib/directives/combo-item-disable.directive.ts:2:9 - error TS2724: '"@infragistics/igniteui-angular"' has no exported member named 'IgxComboItemComponent'. Did you mean 'IgxComboComponent'?

2 import {IgxComboItemComponent} from "@infragistics/igniteui-angular";
          ~~~~~~~~~~~~~~~~~~~~~

  node_modules/@infragistics/igniteui-angular/lib/combo/combo.component.d.ts:59:22
    59 export declare class IgxComboComponent extends IgxComboBaseDirective implements AfterViewInit, ControlValueAccessor, OnInit, OnDestroy, DoCheck, EditorProvider {
                            ~~~~~~~~~~~~~~~~~
    'IgxComboComponent' is declared here.
```

My directive looks like this:
```
import {Directive, Input} from "@angular/core";
import {IgxComboItemComponent} from "@infragistics/igniteui-angular";

@Directive({
  standalone: true,
  selector: "[comboItemDisabled], [igxComboItem]",
})
export class ComboItemDisableDirective {
  constructor(private igxComboItemComponent: IgxComboItemComponent) {
  }

  @Input("comboItemDisabled") set disabled(isDisabled: boolean) {
    console.log("igxComboItemComponent", this.igxComboItemComponent);
    this.igxComboItemComponent.disable = isDisabled;
  }
}
```

The html part looks like this:

```
    <igx-simple-combo [data]="comboboxData">
      <ng-template igxComboItem let-display>
        <div [comboItemDisabled]="display === 'disabled'">{{ display }}</div>
      </ng-template>
    </igx-simple-combo>

```

## Describe the solution you'd like
1. Add "disabledData" input to all combobox variants
2. Publish the "IgxComboItemComponent" so people can overwrite the behavior

## Additional context
We are using the commerical version:
    "@infragistics/igniteui-angular": "16.0.13",

**Comment by yl-endress** [comment]
FYI: for igx-select the hack with the disabled-directive is working (sorry was a bit to lazy to adjust the var names):

```
@Directive({
  standalone: true,
  selector: "[comboItemDisabled]",
})
export class ComboItemDisableDirective {
  constructor(private igxSelectItemComponent: IgxSelectItemComponent) {
  }

  @Input("comboItemDisabled") set disabled(isDisabled: boolean) {
    console.log("igxComboItemComponent", this.igxSelectItemComponent);
    this.igxSelectItemComponent.disabled = isDisabled;
  }
}
```

Here comes the HTML

```
    <igx-select>
      <igx-select-item value="Hello">Hello</igx-select-item>
      <igx-select-item value="World">World</igx-select-item>
      <igx-select-item [comboItemDisabled]="true" value="42">42</igx-select-item>
    </igx-select>
```

**Comment by MonikaKirkova** [comment]
Hi @yl-endress , after an investigation, I have determined that your requirement could be achieved on application level by accessing the dropdown of the combo component and disabling the items as follows:
this.simpleCombo.dropdown.items[0].disabled = true;
[Here](https://stackblitz.com/edit/b8k9of?file=src%2Fapp%2Fcombo-main%2Fcombo-main.component.html) could be found a sample, demonstrating this suggestion.

**Comment by yl-endress** [comment]
Hi @MonikaKirkova, sorry for the late response. indeed your suggestions helped. Anyway, it would also be nice to somehow set it directly

**Comment by yl-endress** [comment]
@MonikaKirkova currently i am having another use case and need to set the disabled behavior again. I tried your previous example once more. Unfortunately, that sample only works with the a small amount of data in the dropdown. Whenever you try to disable an element that is not yet visible in the dropdown, you will access a not existing index!
The following line will fail
`this.combo.dropdown.items[11].disabled = true; `

See the fork here:
https://stackblitz.com/edit/b8k9of-dvte5o?file=src%2Fapp%2Fcombo-main%2Fcombo-main.component.ts,src%2Fapp%2Fcombo-main%2Flocal-data.ts

**Comment by yl-endress** [comment]
For now, i found a workaround with a directive for everyone else who is having the same issue. Heres a code sample:


`
import {Directive, Input, OnDestroy, OnInit} from "@angular/core";
import {IgxSimpleComboComponent} from "@infragistics/igniteui-angular";
import {Subscription} from "rxjs";

@Directive({
  standalone: true,
  selector: "igx-simple-combo[disabledItems]",
})
export class IgxSimpleComboDisableDirective<T = any> implements OnInit, OnDestroy {
  private items: T[] = [];
  private subscription: Subscription = new Subscription();

  constructor(private host: IgxSimpleComboComponent) {
    this.host = host;
  }

  @Input("disabledItems") set disableItems(disabledItems: T | T[]) {
    this.items = Array.isArray(disabledItems)
      ? disabledItems
      : (disabledItems === undefined
        ? []
        : [disabledItems]);
  }

  ngOnDestroy() {
    this.subscription?.unsubscribe();
  }

  ngOnInit() {
    this.subscription.add(this.host.opening.subscribe(() => {
      this.disableVisibleItems();
    }));

    this.subscription.add(this.host.dataPreLoad.subscribe(() => {
      this.disableVisibleItems();
    }));
  }

  private disableVisibleItems() {
    if (this.items.length > 0 && this.host?.dropdown?.children?.length) {
      for (let item of this.items) {
        let hostItem: IgxSimpleComboComponent["dropdown"]["items"][0] = this.host.dropdown.items.find(currentHostItem => currentHostItem.value === item);
        if (hostItem) {
          hostItem.disabled = true;
        }
      }
    }
  }
}

`

Just use it in the template part like this:
`
    <igx-simple-combo
      [data]="myData"
      [disabledItems]="myDisabledData"
    >
`
