### ISSUE TITLE
Gird Row Conditional Selection is not working as it did

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-angular#13401]
## Description  
Cannot conditionally disable grid rows

## Steps to reproduce  

Just use your demo

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-selection#conditional-selection-demo

![image](https://github.com/IgniteUI/igniteui-angular/assets/759253/427b9ae0-2800-459a-b164-6d4ad8e1fbdf)

## Result  
I can select rows that should not be selectable

## Expected result  
I should not be able to select these rows

**Comment by ddaribo** [comment]
Hi @ricardosaracino,

Thank you for reporting this behavior!

It appears that there have been two breaking changes related to this feature. They are both documented in our [Changelog](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#ignite-ui-for-angular-change-log):

_"`rowSelectionChanging` event arguments are changed. Now the `oldSelection`, `newSelection`, `added` and `removed` collections no longer consist of the row keys of the selected elements when the grid has set a `primaryKey`, but now in any case the row data is emitted."_
as of version 15.1.0 and is listed [here](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#general-2)

and

"_`rowID` in the context object of the `igxRowSelector` is now deprecated and will be removed in future version. Use `key` property instead_."
as of version 13.0.0  and is listed [here](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#general-8).

So, that means what has to be changed is passing the `rowContext.key` property to the function bound the `disabled` property of the `igx-checkbox` in the row selector template:

`[disabled]="!isSelectionAllowed(rowContext.key)"`

and in the `rowSelectionChanging` event handler, passing the `primaryKey` property of the data items to the `isSelectionAllowed` function, for example:

```
    // update selection to contain only allowed rows
    event.newSelection = event.newSelection.filter((x) =>
      this.isSelectionAllowed(x.ID)
    );
```
[Here](https://stackblitz.com/edit/igx-grid-conditional-row-selection-16-x?file=src%2Fapp%2Fgrid%2Fgrid-conditional-row-selectors%2Fgrid-conditional-row-selectors-sample.component.ts) you can find a modified fork of the demo that works as expected.

Finally, there is also [an issue](https://github.com/IgniteUI/igniteui-angular-samples/issues/3379) logged in our samples repository to update the sample in the documentation.

**Comment by ricardosaracino** [comment]
stackblitz looks good, i will update my code accordingly.

**Comment by ricardosaracino** [comment]
I added another check to prevent clicking an disabled row from clearing the selected rows

```
   if (!args.added.length && args.removed.length) {
      // ignore deselect
      return;
    }

    const originalAddedLength = args.added.length;

    // update selection to contain only allowed rows
    args.newSelection = args.newSelection.filter((x) =>
      this.isSelectionAllowed(x.uuid),
    );

    // prevent selecting disabled row from deselecting all
    if (args.newSelection.length === 0) {
      args.cancel = true;
      this.cancelRow = false;
      return;
    }

    // cleanup selection if all conditionally selectable rows are already selected
    if (
      args.newSelection.length &&
      !args.newSelection.filter((x) => args.oldSelection.indexOf(x) === -1).length &&
      originalAddedLength > 1
    ) {
      // all selected from header, deselect instead
      args.newSelection = [];
    }
```
