### ISSUE TITLE
When I import a set of i18n strings, all strings for all languages are imported and bundled

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#13411]
## Description  
Unused language resources are imported and bundled.

 * igniteui-angular version: 16.0.x
 * browser: all

## Steps to reproduce  

1. Import localization strings `import { IgxResourceStringsBG } from 'igniteui-angular-i18n';`
2. Use them in your `app.module`
3. Inspect `vendor.js`

## Result  
All languages are included,

## Expected result  
Only the imported strings should be included.

## Attachments  
![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/28786dcc-bd96-4bf5-b4e6-f28aeacf558d)

**Comment by damyanpetev** [comment]
Don't see anything obviously wrong with the exports and barrels in the package, it _should_ be tree-shakable.
Wondering, since Angular's builder is still Webpack based and that tool does insist on `"sideEffects": false` in the package.json IIRC, perhaps that's the missing bit?
