### ISSUE TITLE
Input Group label position for Border/Outline style (Material theme)

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#13420]
## Description  

When using Input Groups with style border label position is not consistent.

 * igniteui-angular version: 16.0.20
 * browser: any

## Steps to reproduce  

In a column layout:

1. Add Input Groups
   - type="border"
   - with and without prefix
   - input type = text / date
2. Add Date Picker

## Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/0ef2a4fd-21ae-48f9-9ffe-0270df296ec2)

## Expected result  

According to Material spec v2 and v3 outline labels are aligned to the left of the group.

![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/e43a81b3-53ab-47ca-8dd3-66be53575a60)

![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/7cfb930b-c331-4a8e-bd31-5e9b4397c925)

## Attachments  

[stackblitz example](https://stackblitz.com/edit/qordfz?file=src%2Fapp%2Finput-group-sample-5%2Finput-group-sample-5.component.html)

**Comment by simeonoff** [comment]
I am aware of the difference, but for us this was an implementation limitation. We wanted to preserve the transparency, while allowing for dynamic sizing of the border. We can revisit the implementation and see if we can achieve the design as outlined in the spec.

**Comment by simeonoff** [comment]
@sdimchevski Can we take a decision here? Our opinion is that the current implementation is better from UX perspective. What do you think?

**Comment by sdimchevski** [comment]
@simeonoff the current implementation is better, I agree. We do consider having more than 1 prefix which is not the case in Material. Having 2 prefixes is a valid use case so lets keep the current implementation
