### ISSUE TITLE
OverlayService uses wrong document reference in show method

### ISSUE THREAD

**Issue by agencia-estado** [IgniteUI/igniteui-angular#13422]
## Description  
Method show at IgxOverlayService class, uses wrong document reference as below

```
info.settings.positionStrategy.position(
            info.elementRef.nativeElement.parentElement,
            { width: info.initialSize.width, height: info.initialSize.height },
           **wrong** document, **should be this._document**
            true,
            info.settings.target);
```

This affects child windows with different DOCUMENT tokens injected

 * igniteui-angular version: 16.0.16
 * browser: Chrome

**Comment by ChronosSF** [comment]
@agencia-estado , we are prioritizing this for the next sprint starting Oct 16.

**Comment by agencia-estado** [comment]
Thanks
