### ISSUE TITLE
[ESF]: cannot change the color of the column header and actions titles

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#13434]
## Description  
I would like to change the color of the column header and the actions' titles. Currently, there are no exposed properties for this. 

![esf-theming](https://github.com/IgniteUI/igniteui-angular/assets/49126110/b018ae69-0db8-4a40-bcd3-7562d0f00d7c)

 * igniteui-angular version: 16.1.x, 16.0.x, 15.1.x
 * browser: any

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
@RivaIvanova We will be able to cover this in 16.1.x only.
