### ISSUE TITLE
igxCheckbox: Focus state is not shown when a checkbox is clicked (light-indigo)

### ISSUE THREAD

**Issue by gmartinezig** [IgniteUI/igniteui-angular#13447]
## Description  
Focus state is not shown when a checkbox is clicked

 * igniteui-angular version: 16.0.15
 * browser: all
 * theme: light-indigo

## Steps to reproduce  

1. Create an app and set $light-indigo-schema as its default theme schema.
2. Add a checkbox somewhere and run the app.
3. Click the checkbox created in step 2.
4. Observe.

## Result  
The checkbox is not showing the focus state after clicking it.

## Expected result  
The checkbox should show the focus state

## Clarifications 
The focus state is working properly on keyboard navigation, it's failing only when the checkbox is clicked.
Despite this behavior is intentional in material theme, it would be nice to review if it's needed on the rest of the themes.

**Comment by simeonoff** [comment]
As agreed with @sdimchevski, we're not gonna have visible focus styles on click, only on keyboard navigation. This should be reflected in the Indigo Design UI kit when it's developed.
