### ISSUE TITLE
Grid cells misalignment when there are Multi-column headers' child columns with % width

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#13452]
## Description  
Related to #13392. This was fixed for the column headers, however, a slight misalignment is still present for the cells. This can be observed when activating a cell, or for cells having borders:
![image](https://github.com/IgniteUI/igniteui-angular/assets/35433937/4bf1e555-018e-47c0-9cf3-5ca82dd8a70e)

 * igniteui-angular version: 16.1.x, 16.0.x, 15.1.x
 * browser: any 

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/igx-grid-multi-column-headers-perc-width-fixed?file=src%2Fapp%2Fgrid%2Fmulti-column-headers%2Fmulti-column-headers.html) sample.
2. Click on the "ContactName" column ->  "Maria Anders" cell to activate it, so that it has a border.

## Result  
The cell is not aligned to the parent header. For instance, if the parent's width is `205 px`, the cell's width is not rounded and is `205.19 px`

## Expected result  
Proper alignment

**Comment by ddaribo** [comment]
As discussed with @dkamburov, an easy fix would allow a parent column group’s width to be float (as mentioned in issue #13392 description).

IMO, the dimensions for group headers should allow floats _with the current implementation_, since: 1) one could set a float pixel width on a column and this will not be rounded and 2) in most cases a percentage value yields a float pixel value. Therefore, for such a column, in case it is a part of a group, that group’s total width will be float (float + int  + .. = float, no rounding).

So, there are two options:
1. Allow float width for column groups. However, **this should be tested across all browsers**, as there might be browser-specific rounding behaviors (specifically **Safari**, as I noticed no difference in Chrome, Mozilla & Edge). 
Additionally, this would require several tests expectations to be edited to expect _non-rounded values_ for column groups' headers.

2. Round all widths to integers, including the cells. Currently all grids (tree, hierarchical, pivot) cells are sized with the following bindings:
```
        [style.min-width]="col.width"
        [style.max-width]="col.width"
        [style.flex-basis]="col.width"
        [width]="col.getCellWidth()"
```
,where `col.width` is the string value set on a column, such as `[width]=”’30px’”` or `[width]="'333.33px'"`. This implementation sets the width as-is. So, this option would require a bit of refactoring and has to probably be discussed further.

**Comment by hanastasov** [comment]
> As discussed with @dkamburov, an easy fix would allow a parent column group’s width to be float (as mentioned in issue #13392 description).
> 
> So, there are two options:
> 
> 1. Allow float width for column groups. However, **this should be tested across all browsers**, as there might be browser-specific rounding behaviors (specifically **Safari**, as I noticed no difference in Chrome, Mozilla & Edge).
>    Additionally, this would require several tests expectations to be edited to expect _non-rounded values_ for column groups' headers, which I believe is not the best practice.
> 2. Round all widths to integers, including the cells. Currently all grids (tree, hierarchical, pivot) cells are sized with the following bindings:
> 
> ```
>         [style.min-width]="col.width"
>         [style.max-width]="col.width"
>         [style.flex-basis]="col.width"
>         [width]="col.getCellWidth()"
> ```
> 
> ,where `col.width` is the string value set on a column, such as `[width]=”’30px’”` or `[width]="'333.33px'"`. This implementation sets the width as-is, resulting in float widths of cells.
> 
> On the other hand, in many places, when calculating values such as the grid's `totalWidth` ([here](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L4399)) , the `pinnedWidth` ([here](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L5289)), the columns' widths are parsed to `int`. IMO, this appears inconsistent, given that float column widths are allowed and are produced. Additionally, all tests check against `int` values. Also leaving `int` widths would avoid potential issues in case different browsers indeed render them differently. This makes option 2) more preferable?

Nice and detailed explanation.

Option 2# sounds better to me. Does option #2 means that one can set column width to "295.5px", but column.width would return an integer 290?
