### ISSUE TITLE
13.2.24 not found

### ISSUE THREAD

**Issue by benmesza** [IgniteUI/igniteui-angular#13463]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-13.2.24.tgz
npm ERR! 404 
npm ERR! 404  '@infragistics/igniteui-angular@https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-13.2.24.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

did you remove 13.2.24? Can you put it back please? our ci is broken

**Comment by zdrawku** [comment]
Hi there, could you try again installing the dependency, this might have been a temporary problem with the package feed as it is present:

![image](https://github.com/IgniteUI/igniteui-angular/assets/11193764/bfb8c128-8592-4ae0-89e6-804326d1c858)

**Comment by kdinev** [comment]
@benmesza There was a temporary outage in the identity servers and this has probably caused the issue. Let us know if you're still unable to access the packages.

**Comment by benmesza** [comment]
@kdinev I still can't access the package.

**Comment by ChronosSF** [comment]
@benmesza , it could also be an issue with licensing . Please submit a support case here: https://account.infragistics.com/support-cases so that our staff can investigate if there are issues with your subscription.
