### ISSUE TITLE
[IgxGrid]: error on horizontal scroll when having pinned columns

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#13479]
## Description  
If I change the grid's columns at runtime while having pinned columns, errors are thrown and the grid is not displayed properly.
This is not reproducible in version 15.0.x. Sample [here](https://stackblitz.com/edit/angular-2jrf3w-dreewt?file=src%2Fapp%2Fgrid%2Fgrid-resizing-sample%2Fgrid-resizing-sample.component.ts).

 * igniteui-angular version: 16.1.x, 16.0.x, 15.1.x
 * browser: any

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/ysuav4-fa2njw?file=src%2Fapp%2Fgrid%2Fgrid-sample-pinning%2Fgrid-toolbar-pinning.component.ts) sample.
2. Pin a few columns, scroll to the last column, and click the switch. 

## Result  
Errors are thrown and the grid is not displayed properly.

## Expected result  
No errors

## Attachments  
![grid-scroll-pinned-cols](https://github.com/IgniteUI/igniteui-angular/assets/49126110/7094fd1c-cc74-446f-8dc0-d0d697a54c3a)

**Comment by RivaIvanova** [comment]
May be related to https://github.com/IgniteUI/igniteui-angular/issues/13468 due to the similar errors that are thrown after scrolling.

**Comment by ddaribo** [comment]
Closed by the PRs addressing https://github.com/IgniteUI/igniteui-angular/issues/13546
