### ISSUE TITLE
igx-spreadsheet hidden column is not being sorted 

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-angular#13486]
## Description  
Hidden column is not being sorted 

 * igniteui-angular version: 23.2.18

**## Steps to reproduce**  

1.Run the sample (also attached)

https://www.infragistics.com/products/ignite-ui-angular/angular/components/spreadsheet-overview
2. Hide column B
3. Sort C

## Result  :
All visible columns sorted correctly, but hidden column B did not sort. and data is misaligned.
Before and after screenshots attached for the reference.

## Expected result  
Hidden column should also sort. Not able to reproduce it with WPF and Microsoft Excel.

![Before](https://github.com/IgniteUI/igniteui-angular/assets/22081100/6064c786-a56d-454f-9623-11a5a102d365)
![after](https://github.com/IgniteUI/igniteui-angular/assets/22081100/eba6e296-cd6c-4a9f-9d42-db490ec56054)

**Comment by igandrews** [comment]
The logic that was calculating the range to which the sort would be applied was incorrectly ignoring hidden rows which didn't match Excel's behavior. This has been corrected in the spreadsheet code.

**Comment by igandrews** [comment]
The logic that was calculating the range to which the sort would be applied was incorrectly ignoring hidden rows which didn't match Excel's behavior. This has been corrected in the spreadsheet code.
