### ISSUE TITLE
IgxGrid: autosize columns inside dockmanager not working properly

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13488]
## Description  
When using IgxGrid with autosize columns inside a Dockmanager then the column width is not calculated properly when no data is set.

 * igniteui-angular version: 16.0.24
 * igniteui-dockmanager version: 1.14.1
 * browser: chrome

## Steps to reproduce  
https://stackblitz.com/edit/t1jy5s

## Attachments  
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/bd0942a9-ff41-44b1-b3ab-fb657e3d57da)

**Comment by ChronosSF** [comment]
@Timmeeeey , we are prioritizing the issue for our next sprint starting Oct 16.
