### ISSUE TITLE
igx-dialog: dialog is closed if user clicks inside dialog but release the click outside of it 

### ISSUE THREAD

**Issue by alorle** [IgniteUI/igniteui-angular#13481]
## Description  
When a `igx-dialog` is create with `closeOnOutsideSelect` input to true, the user is able to close the dialog clicking outside of it, on the backdrop.

The issue here is that if the user inits the click inside the dialog and then moves the mouse outside and releases the mouse button, the dialog is closed.

 * igniteui-angular version: `15.1.2`
 * browser: Google Chorme Version 117.0.5938.89 (Official Build) (64-bit)

## Steps to reproduce  

1. Create and open a `igx-dialog` with `closeOnOutsideSelect` input setting to true.
1. Click inside the dialog but do not release the mouse button.
1. Move the mouse pointer outside of the dialog.
1. Release the mouse button.

## Result  
The dialog is closed.

## Expected result  
The dialog is still opened.

Or at least, there should be an option that allows you to configure which event triggers that behavior. For example, `closeOnOutsideSelect` could be an enum input with these values:
- `down` | `start`: when click starts outside the dialog, close it (_expected behavior_)
- `up` | `end`: when click ends outside the dialog, close it (_current behavior_)
- `both`: in both cases, close the dialog

## Attachments  
None

**Comment by ChronosSF** [comment]
@alorle , we are prioritizing this for the next sprint, starting Oct 16.

**Comment by tishko0** [comment]
Hello,

We have reviewed this issue and have concluded that this behavior is normal, and we do not consider it a bug. The issue here is that the mouse up event will always be fired upon another element, which may have no connection to the dialog, which is far from ideal.

Instead, I can offer a very simple solution to your problem that can be resolved at the app level. Below are some code snippets that you can add to your dialog of choice, preventing them from closing when clicked on the outside while the click started inside:

**HTML:**
```html
<igx-dialog ..... (closing)="closeDialog($event)" ...>
  <!-- Your dialog content here -->
</igx-dialog>
```
**Typescript:**
```
export class DialogSampleComponent implements OnInit, OnDestroy {
  public initialPointerPosition = null;
  public mousedownSubscription: Subscription;

  ngOnInit() {
    // Set up a subscription to mousedown so we are certain the dialog has been initialized when we click
    this.mousedownSubscription = fromEvent(document, 'mousedown').subscribe((event: MouseEvent) => {
      this.initialPointerPosition = { x: event.clientX, y: event.clientY };
    });
  }

  closeDialog(evt) {
    // Get the location of the dialog
    const rect = evt.dialog.toggleRef.element.getBoundingClientRect();
    
    // Check if the initial click happened inside. If so, cancel the closing event
    if (
      this.initialPointerPosition.x >= rect.left &&
      this.initialPointerPosition.x <= rect.right &&
      this.initialPointerPosition.y >= rect.top &&
      this.initialPointerPosition.y <= rect.bottom
    ) {
      console.log('cancel');
      evt.cancel = true;
    }
  }

  ngOnDestroy() {
    this.mousedownSubscription.unsubscribe();
  }
}
```
Please let me know if you have any other questions or concerns.

**Comment by dkamburov** [comment]
please re-open if there are additional questions on that
