### ISSUE TITLE
I should be able to click the tree node to expand/collapse, not only by clicking the expand/collapse icon indicator

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#13491]
## Is your feature request related to a problem? Please describe.
I want to toggle the tree node not only on icon click, but also on _node item_ click.

## Describe the solution you'd like
Upon clicking on the node item, the whole node will expand/collapse. A behavior similar to how [expansion panel](https://www.infragistics.com/products/ignite-ui-angular/angular/components/expansion-panel) is working. When I click on the item itself, the whole panel expands/collapses.

## Describe alternatives you've considered
The API is rich enough to handle this, although I would expect this to be a default behavior or achieve it through a property.

**Comment by teodosiah** [comment]
Currently, clicking on a tree node sets it as focused and active. However, something to consider in this case is that there may be a link in the node and then this link is opened on click.

**Comment by kdinev** [comment]
If such behavior is enabled, then it should be configurable by option, since it goes into conflict with links, node selection, etc.

The behavior is achieved currently by attaching a `(click)="$event.owner.expanded = !$event.owner.expanded"` on the node.

**Comment by zdrawku** [comment]
> If such behavior is enabled, then it should be configurable by option, since it goes into conflict with links, node selection, etc.
> 
> The behavior is achieved currently by attaching a `(nodeSelection)="$event.added.expanded = !$event.added.expanded"` on the tree.

I was thinking of exposing a property as well, let's say a boolean prop  `toggleOnNodeClick` or `toggleNodeOnClick`.
