### ISSUE TITLE
Slider thumb stops moving, but still emitting values

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#13490]
## Description  
Drag the slider thumb slowly and see what happens: - at some point the thumb does not move along with the mouse anymore, while values are still emitted.

![slider_behavior](https://github.com/IgniteUI/igniteui-angular/assets/14248932/d6f72378-561f-4ebd-bb08-c61a81957b79)

To reproduce:
1) Run dev demos
2) prepare slider demo:
```
// html
<igx-slider id="slider"
  [type]="sliderType.RANGE"
  [minValue]="150"
  [maxValue]="650"
  [lowerBound]="100"
  [upperBound]="1200">
</igx-slider>

// ts
export class SliderSampleComponent {
    public sliderType = IgxSliderType;
    public priceRange = {
        lower: 200,
        upper: 800
    };

    constructor() { }

}
```

**Comment by PlamenD95** [comment]
The issue with the slider can no longer be reproduced.

The slider's interaction works properly in the current version of the library and there is no longer a visual stutter or blockage of the movement of the thumb.
