### ISSUE TITLE
Stale grid.groupsRecords on groupingDone

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#13514]
## Description  
Hi, this.grid.groupsRecords is not up to date when this.grid.groupingDone emits. I expected the groupsRecords to be grouped by all expressions in groupingDone's IGroupingDoneEventArgs event, but it is stale. For example if grouped by four expressions and I add a fifth grouping, the state of groupsRecords after groupingDone is as if I only have four expressions, not five. Perhaps I am using the wrong callback? Thanks

 * igniteui-angular version: 15.1.13
 * browser: Chrome Version 115.0.5790.110 (Official Build) unknown (64-bit)

**Comment by SkylerLutz** [comment]
Bump, I am still seeking an answer. Thank you

**Comment by kdinev** [comment]
@ChronosSF Could you respond to this one? @MonikaKirkova is going to be back on Monday, I believe, so she won't be able to look at this until then.

**Comment by ChronosSF** [comment]
@SkylerLutz , it's scheduled for development for the current sprint so you can expect a fix as early as Oct 30.

**Comment by ChronosSF** [comment]
If the fix makes it for Oct 30 patches the release will be 15.1.32 . The current latest is 15.1.30 and we release every week.

And yes, 15.1.x is in full support and the fix will be released for it.

**Comment by SkylerLutz** [comment]
Thank you very much. Last question: what is the scope/nature of the "fix"? Will groupsRecords reflect the new state at the time groupingDone fires?

**Comment by ChronosSF** [comment]
Yeah, I think so. Haven't looked into what's happening under the hood for this case but at the time any `done` event fires all related API should give you the updated state.
