### ISSUE TITLE
Grid Remote Filtering: columnValuesStrategy is invoked unnecessarily

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#13526]
## Description  
Hi, I have a grid with remote filtering that is using columnValuesStrategy to pre-fetch all distinct values for an excel-style external filter. What I don't understand is, after the user checks/unchecks an option in the excel style filter, and applies the filter, the columnValuesStrategy is invoked again for the same column. This is triggering an unnecessary call to my backend service to fetch the distinct values for the column, when that information has already been provided to the grid. To avoid this, I'll have to resort to some sort of caching, which I don't want to do. If the columnValuesStrategy invocation is necessary, can someone please shed some light on why that is the case? I suspect it is not needed. Thank you

 * igniteui-angular version: 15.1.13

**Comment by ChronosSF** [comment]
In many cases the server-side data is mutable and having the list refresh alongside data request could be beneficial. As you already suggested, the function returning the list of values could be entirely client-side and you can choose whether to use a cached version of the values of fetch new ones based on your application scenario. Unless there is an issue with this mechanism, I am changing the state to not-a-bug.
