### ISSUE TITLE
[Keyboard Navigation-Name menu-Text filter] 'Text filter' popup is not getting by 'Esc' key under 'Name' dialog.

### ISSUE THREAD

**Issue by v-kumarsatya** [IgniteUI/igniteui-angular#13531]
User Experience:
The "Esc" key is a common and expected method to close modals, and its absence can hinder their ability to move through the interface. This can interrupt the natural flow of navigation and interaction, making the experience more cumbersome.

'Text filter' popup is not getting closed by 'Esc' key under 'Name' dialog.
Observation: When the keyboard focus lands on 'text filter' control and after invoking it popup appears and 
after pressing 'esc' key it is not getting closed the popup and by pressing shift + tab key it is moving to 'apply' button.

source link: [Excel Style Filtering in Angular Data Grid- Ignite UI for Angular (infragistics.com)](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering)

**Comment by v-kumarsatya** [comment]
Request you to provide update on this bug.

**Comment by v-kumarsatya** [comment]
Duplicate bug (https://github.com/IgniteUI/igniteui-angular/issues/13525) has been raised from our end. Now we have closed duplicate bug. Now please consider and revert on this bug only for this issue.

**Comment by v-kumarsatya** [comment]
Any update on this bug.

**Comment by ChronosSF** [comment]
This is getting fixed alongside https://github.com/IgniteUI/igniteui-angular/issues/13522 so please check my  answer for that item.

**Comment by v-kumarsatya** [comment]
Request you to share a patch version which you are going to release on coming Monday for these bugs.
