### ISSUE TITLE
Grid cells jumble after resizing grid - Cannot read properties of null (reading 'getRootNode')

### ISSUE THREAD

**Issue by baleeds** [IgniteUI/igniteui-angular#13546]
## Description  
When resizing the grid after horizontally scrolling, the grid can't recover the scroll position correctly, and crashes in a severe way, jumbling the cell data.

The issue is in the IgForOf directive.

The issue is reproducible across various machines and browsers.

 * igniteui-angular version: 16.0.27
 * browser: Chrome - Version 117.0.5938.149 (Official Build) (arm64)

## Steps to reproduce  

1. Load this repository: https://github.com/baleeds/infragistics-angular-grid-bug
2. Start the app.
3. Scroll the grid to the right so that at least some of the columns are off the screen.
4. Click the "Toggle sidebar" button once.  Click the button again.
5. Scroll the grid back to the left.
6. The cells are jumbled and there's a javascript error in the console.

## Result  
The cells are jumbled after a JavaScript NPE.

## Expected result  
The cells should be normal.

## Attachments  
I've included a video of myself running the app in the repository above since it was too big to upload.

**Comment by ChronosSF** [comment]
@baleeds , I am not reproducing this with 16.0.27. Could you please try the latest patch for the version you are using and let me know if the issue persists?

**Comment by baleeds** [comment]
The reproduction is already using 16.0.27, as seen in the package lock.  Did you try the repository?

**Comment by ChronosSF** [comment]
Yes, however I only tested it on a Windows machine. I'll see if running it on a Mac makes the difference.

**Comment by baleeds** [comment]
> Yes, however I only tested it on a Windows machine. I'll see if running it on a Mac makes the difference.

I had my coworker run the repo on Windows and he saw the issue as well.  We see the issue in production on a wide variety of machines and browsers, but it can be somewhat intermittent.  In the example repo, on my machine, I see the issue 90% of the time.

**Comment by ChronosSF** [comment]
It's quite a lot easier to reproduce on Mac indeed, though I did manage to break it on my Windows Chrome too.

As a note to whomever ends up trying to fix it: try to horizontally scroll both when the mock sidebar is on and off and after toggling a few times you'll end up with the console errors.

**Comment by baleeds** [comment]
Will this fix make it into a minor/patch version?  It's a major production issue for our users, and we are not planning to upgrade to Angular v17 until the new year, probably.

**Comment by ChronosSF** [comment]
@baleeds , the fix will be released for 16.1.x on Monday (likely as v. 16.1.5)
