### ISSUE TITLE
Unable to move cursor via mouse click when using igxFilterCellTemplate

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#13554]
## Description  

When re-templating the filter cell with an `IgxInputGroup`, typing some characters, and clicking in a particular place in order to move the cursor, the cursor remains at the end.

This behavior is caused by the following `mousedown` event handler:
https://github.com/IgniteUI/igniteui-angular/blob/213b915d6be2804b11417b8b21d16ebacd37c292/projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts#L263-L267

 * igniteui-angular version: 16.1.x, 15.1.x
 * browser: any

## Steps to reproduce  

1. Open the Re-templating filter cell sample [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering#re-templating-filter-cell).
2. Type some text inside the input group and try moving the cursor via mouse click.

## Result  
The cursor remains at the end of the text when using mouse click.

## Expected result  
The cursor should be placed at the desired position.

## Attachments  
![cursor-mouse-click](https://github.com/IgniteUI/igniteui-angular/assets/49126110/62adcce8-4666-432c-b6e8-453053902b5a)

**Comment by pipeng119** [comment]
So there is no plan to fix this bug? @RivaIvanova
