### ISSUE TITLE
Always set button type attribute

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13567]
## Description  
Buttons should always have `type="button"` except when it should be a submit button.

When pressing Enter in a form and the submit button is disabled then no submit should be fired.
But when there are other buttons in the form which do not have `type="button"` then this button is used as the submit button and the form gets submitted.

 * igniteui-angular version: 16.1.2
 * browser: Chrome

## Steps to reproduce  
https://www.infragistics.com/products/ignite-ui-angular/angular/components/angular-reactive-form-validation#angular-reactive-form-validation-example

1. Enter Full Name and press Enter

## Result  
The form gets submitted even though the submit button is disabled.
In this case this is because IgxTimePicker has two submit buttons "cancel" and "ok".

## Expected result  
The form should not be submitted.

**Comment by Timmeeeey** [comment]
@maheshchandra10
Hi, I just want to emphasize that the point is to add the `type` attribute in general to all buttons so that there are not multiple submit buttons in one form.

**Comment by kdinev** [comment]
@Timmeeeey The commit and PR associated with the issue is an external contribution and doesn't really apply to the issue you've submitted. I've applied the necessary labels and a fix will be PRed.
