### ISSUE TITLE
Pressing Enter in IgxSimpleCombo throws error

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13568]
## Description  
When you select a value in IgxSimpleCombo and press Enter, then an error is thrown.
Sometimes another item is selected and the error is thrown after pressing Enter multiple times.

`TypeError: Cannot read properties of null (reading 'itemID')`

In following code line:
https://github.com/IgniteUI/igniteui-angular/blob/913905bca392b01f5c0b6c74df920549abec89dd/projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts#L306

 * igniteui-angular version: 16.1.2
 * browser: Chrome

## Steps to reproduce  

1. Open https://stackblitz.com/edit/ezpv2p
2. Select Item 3
3. Press Enter multiple times

## Result  
First Item 31 gets selected then Item 311 and then the error is thrown.

## Expected result  
Pressing Enter should not throw an error or select a different item.

## Attachments  
https://stackblitz.com/edit/ezpv2p

![2023-10-19_09h09_11](https://github.com/IgniteUI/igniteui-angular/assets/46870283/94de15c9-8032-4267-859e-710e8368d3cd)

**Comment by ChronosSF** [comment]
@Lipata , we'll have to look into these simple combo issues next sprint.
