### ISSUE TITLE
After migration from v12 to v13.2.24 SassError: Undefined mixin

### ISSUE THREAD

**Issue by DevMarkDevelopment** [IgniteUI/igniteui-angular#13578]
## Description  
How to resolve issue with undefined mixin. I read update guide but cant find answers to my problems.

 * igniteui-angular version:  13.2.24
 * angular: 15.2.10

## Steps to reproduce  

1. Update igniteui-angular to version 13.2.24
2. run application
3. see errors

## Result  
Receive complilation error in terminal:
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/16f737c3-417a-4008-afc6-5d52b0ae0d8e)

## Expected result  
Run application normally

**Comment by kdinev** [comment]
@DevMarkDevelopment Please share your import code in the `.scss` file. Btw, `igniteui-angular@13.x` has dependency on `angular@13.x`. I see your Angular version is `15.x` though. Also, when updating `igniteui-angular` did you do it using `ng update`?

**Comment by DevMarkDevelopment** [comment]
@simeonoff thanks for ng-update way it helped a lot, but now I am stopped on 
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/ab187797-b134-4f8a-ae7d-53b096f4f930)
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/b1e51c58-2732-4ce0-ad47-e264124d7d62)
any idea how to solve this problem. I updated igniteui-angular to 15.1.30

**Comment by simeonoff** [comment]
The `surface` color has become required when constructing a custom palette in 15.1.x. Here's an example of how you should define palettes from 15.1.0 onwards. 

Adjust the surface color based on whether you will be generating a light or dark theme. Pick a lighter surface color when generating palettes that will be used with a light schema (default is $light-material-schema).

Based on the screenshot you provided, yours should looks something like that:

```scss
@use "node_modules/igniteui-angular/lib/core/styles/themes" as *;

$primary: rgb(53, 150, 205) !default;
$secondary: rgb(53, 150, 205) !default;
$tertiary: rgba(255, 19, 75, 255) !default;
$surface: #fff; // <--- 

@include core();
@include typography();
@include theme(
    $palette: palette($primary, $secondary, $surface),
);
```

**Comment by DevMarkDevelopment** [comment]
@simeonoff once again you fixed my problem, but receive different 
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/57307720-1389-4747-b769-e6300ad77fa9)
I have no idea what is wrong here

**Comment by simeonoff** [comment]
It could have something to do with you app config. This is very cryptic now and I can't decipher what's going on based on the screenshot.

**Comment by DevMarkDevelopment** [comment]
Okay so where should I look for issues?

**Comment by kdinev** [comment]
@DevMarkDevelopment The error is no longer a sass one, it's in the typescript. Your editor should be highlighting a type you've imported could you inspect the specific component that you get the error in and see whether there's a highlighted import which is mistyped or anything of that sort. Also, if possible, share with us a screenshot of the imports in that file.

**Comment by DevMarkDevelopment** [comment]
Okay, this is personal library, made for personal use but it is important. In node_modules in this package imports look like that 
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/dd1f6136-43f5-40a7-8d0b-b4e8af570a9d)
what is more in package.json here are dependencies for this package 
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/57aa83be-7a3c-4eeb-90f2-be654fa31606)
in whole application I use angular 15.2.10 ang igniteui-angular 15.1.30, 
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/1c9d59db-6962-4b5d-97c7-3b1346f17630)
and here are my dependencies. Also I use node in version 18.10.0

**Comment by kdinev** [comment]
@DevMarkDevelopment Remove the line

```ts
import * as i1 from 'igniteui-angular';
```

In fact remove all lines saying `import * as X from ...`

**Comment by DevMarkDevelopment** [comment]
These imports are in node_modules file so I cant delete them because I receive different errors in console:  
![image](https://github.com/IgniteUI/igniteui-angular/assets/147808539/f740fcd2-77d5-41d7-be04-a33763607733)
additionally, many js files in node modules have these lines, even in igniteui-angular

**Comment by kdinev** [comment]
OK, so the file you were showing is a lib that comes from node_modules, correct? You need to make changes to the lib then. See if it uses a type/class which has changed. The lib itself needs to be updated as well.

**Comment by DevMarkDevelopment** [comment]
Okay so if I understand correctly the only thing that I have to do is to change in package.json versions of peerDependencies for angular and igniteui?

**Comment by kdinev** [comment]
Well, assuming nothing else needs to be adjusted to the new versions of @angular/core and igniteui-angular, then yes.
