### ISSUE TITLE
Button group selected and deselected events are fired before the buttons are selected and deselected

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#13580]
## Description  
The `selected` and `deselected` events of the `IgxButtonGroup` component are fired before the buttons are selected and deselected.

 * igniteui-angular version: 15.1 16.1

## Steps to reproduce  

1. Go to this [sample](https://stackblitz.com/edit/pdpfrn-8aayy3?file=src%2Fapp%2Fbutton-group-sample-1%2Fbutton-group-sample-1.component.html). 
2. Open the dev console.  
3. Select one button from the button group component. 
4. Observe that the `selected` event is fired but the selected buttons `length` is **0**. 
5. Deselect the button from the button group component.
6. Observe that the `deselected` event is fired but the selected buttons `length` is **1**. 

## Result  
When a button is selected from the button group component, the `selected` event is fired before the button is selected and the `length` of the selected buttons is **0**. When a button is deselected from the button group component, the `deselected` event is fired before the button is deselected and the `length` of the selected buttons is **1**.

## Expected result  
When a button is selected from the button group component, the `selected` event should fire after the button is selected and the `length` of the selected buttons should be **1**. When a button is deselected from the button group component, the `deselected` event should fire after the button is deselected and the `length` of the selected buttons should be **0**.

## Attachments  
![issue](https://github.com/IgniteUI/igniteui-angular/assets/48180072/16c5e139-0017-4e16-acde-1f6e09bcd844)

**Comment by damyanpetev** [comment]
👀 Wait a minute.. Those events are `selected`/`deselected` (note the `-ed`), yet are cancellable and as such technically fire at the right time (i.e. before the operation completes), which explains the results seen in the sample as well. However, the naming really isn't following the convention here.

Those should've really been `[de]selecting` if they fire before and are cancellable and potentially a second set of `-ed` non-cancellable events to emit after the operation completes.

**Comment by grosch-intl** [comment]
@damyanpetev Is it fixed yet?  :)

**Comment by ChronosSF** [comment]
@kdinev , @damyanpetev , we plan to revert the selected/deselected cancellable functionality for 16.1 and 15.1 and implement -ing events that are cancellable  for 17.0
