### ISSUE TITLE
Igx-time-picker custom actions are not working anymore

### ISSUE THREAD

**Issue by yl-endress** [IgniteUI/igniteui-angular#13585]
## Description  
The   `<ng-template igxTimePickerActions>` seems not to work anymore.

## Steps to reproduce  

1. go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/time-picker#custom-action-buttons and see your example
2. go the html part -> there are only 2 buttons and not 3

## Result  
2 buttons are displayed

## Expected result  
3 buttons should be displayed

**Comment by yl-endress** [comment]
I just noticed that instead of `<ng-template igxTimePickerActions>` you can simply use `<ng-container *igxPickerActions>` but this seems to be a odd syntax with the * in it

**Comment by ChronosSF** [comment]
Thank you for the report. I've scheduled this item for our next sprint starting Oct 30

**Comment by kdinev** [comment]
@yl-endress The two syntaxes you're showing are in fact equivalent:

`<div *igxPickerActions>` === `<ng-template igxPickerActions>`.

The breaking change for the picker actions rename was introduced in `12.0.0`: https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#1200

I'm surprised there was no automatic migration. @Lipata can comment on why that is.

**Comment by Lipata** [comment]
@kdinev @yl-endress no obvious reason for omitting that migration, even though we have several migrations related to pickers: https://github.com/IgniteUI/igniteui-angular/blob/de8de4acccb4a25db741b41ae43facb2208a8b4c/projects/igniteui-angular/migrations/update-12_0_0/index.ts#L256

So let's leave that bug open and add a custom and class migrations to do it.
