### ISSUE TITLE
Expose a List selection feature

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#13598]
## Is your feature request related to a problem? Please describe.
Expose a List Selection feature. I want the igx-list to provide an interface for selection values. 

## Describe the solution you'd like
The material list is handling this behavior with checkboxes where each list item is an option. We can explore this approach.
https://material.angular.io/components/list/overview#selection-lists

## Describe alternatives you've considered
There is an alternative, to manually configure the Selection state.

## Additional context
6 years ago when we added the list component we didnt explore the Selection functionality, now its worth considering it:
https://github.com/IgniteUI/igniteui-angular/wiki/List-Specification

**Comment by kdinev** [comment]
The `igx-list` is a declarative component. Item selection is shown here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/list#list-item-selection

**Comment by zdrawku** [comment]
Cover by https://github.com/IgniteUI/igniteui-angular/issues/15121
