### ISSUE TITLE
Avatar component visual enhancement

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-angular#136]
Improve avatar visuals when zoomed in:
- [x] make the Initials avatar an SVG element
- [x] increase the native image size by 2 to give the avatar a crisper look on mobile devices

**Comment by kdinev** [comment]
@zdrawku Is this issue still relevant?

**Comment by zdrawku** [comment]
Yes, we are currently using canvas element for Initials mode, although using of SVG would be better approach.
