### ISSUE TITLE
Nested menu for selection

### ISSUE THREAD

**Issue by amrit-moomie** [IgniteUI/igniteui-angular#13616]
Hi

Does Ignite UI have any elements to implement nested menu like selections example here: https://material.angular.io/components/menu/examples#menu-nested

At this moment, I don't think `select` or `dropdown` has nested item support.

**Comment by ChronosSF** [comment]
Hello @amrit-moomie , 

Unfortunately, a menu component has been on our backlog for a while but hasn't been scheduled for development yet.

**Comment by teodosiah** [comment]
Hello @amrit-moomie , 
Nested menu similar to the attached could be implemented on application level using the IgxDropDownComponent and such a sample will be available in our documentation later this month.
Meanwhile, a demo that demonstrates the approach could be found [here](https://stackblitz.com/edit/8rqyuj?file=package.json).
