### ISSUE TITLE
IgxChip component implementation

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#1364]
Related to #856

**Comment by sbozalieva** [comment]
<img width="795" alt="screen shot 2018-05-21 at 14 02 36" src="https://user-images.githubusercontent.com/23053821/40305071-afc02a72-5d01-11e8-8606-bb05a1b434fb.png">
<img width="392" alt="screen shot 2018-05-21 at 14 01 44" src="https://user-images.githubusercontent.com/23053821/40305073-afdf1c52-5d01-11e8-9950-8af78e40e43a.png">
<img width="802" alt="screen shot 2018-05-21 at 10 05 44" src="https://user-images.githubusercontent.com/23053821/40305074-affd9614-5d01-11e8-96d4-fab26faddd88.png">
