### ISSUE TITLE
Grid rows are not visible

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1367]
### Description  
Grid header and footer take up the whole height and grid body is not visible

### Steps to reproduce  
1. Run the sample

### Result  
![2](https://user-images.githubusercontent.com/14248932/40303937-73adef1e-5cfd-11e8-8858-e2ff30bd4257.PNG)

### Attachments  
[igxgrid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2022253/igxgrid-app.zip)

**Comment by bkulov** [comment]
This is not a bug. Sample is using Angular v5.2 with igniteui-angular v6.0 which are not compatible.
