### ISSUE TITLE
igx-avatar is cut when used inside igx-chip and wrapped with igxPrefix directive

### ISSUE THREAD

**Issue by claudiopi** [IgniteUI/igniteui-angular#13679]
## Description  
Describe the issue.

 * igniteui-angular version: 17.0.0 
 * browser: any compatible browser

When igxPrefix directive is used as a wrapper igx-avatar gets cut when used inside an igx-chip 
Note: This doesn't happen with igx-icon.

## Steps to reproduce  

1. Unzip attached [chip-avatar-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/13342936/chip-avatar-issue.zip) angular project.
2. cd chip-avatar-issue
3. npm install
4. npm start

## Result  

Notice how igx-avatar gets cut when it is wrapped with igxPrefix directive:

![image](https://github.com/IgniteUI/igniteui-angular/assets/17047466/b5dabec6-1217-4ec7-9bc3-81961ee218f0)

These cases **don't render correctly**:

![image](https://github.com/IgniteUI/igniteui-angular/assets/17047466/5da7b381-579c-474b-8496-34b2fdef80b2)

![image](https://github.com/IgniteUI/igniteui-angular/assets/17047466/ebbe6e14-cfd8-4ef7-acfe-8c1583adf036)

These cases **do render correctly**:
![image](https://github.com/IgniteUI/igniteui-angular/assets/17047466/33c779a3-10bf-46c4-9ddd-256289f7c3ee)

## Expected result  

igx-avatar should render correctly in all cases as happens with igx-icon 

## Attachments  
Attached 
[chip-avatar-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/13342936/chip-avatar-issue.zip)

**Comment by simeonoff** [comment]
@skrustev is it reproducible only in 16 or in 17 or in both?

**Comment by claudiopi** [comment]
@simeonoff @skrustev it happens in both 16 and 17 igniteui-angular versions (didn't test with previous versions).  
You can test by including the same code of the attached project in a 16 one. 

Thanks!
