### ISSUE TITLE
IgxGridStateDirective: setState() throws error when column and columnGroup have same header

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13697]
## Description  
When you call IgxGridStateDirective.setState() and a column has the same header as a group column then an error is thrown.

 * igniteui-angular version: 16.1.7, 17.0.1
 * browser: any

## Steps to reproduce  

1. A column and a column group have the same header and the column is to the left of the group column.
2. Call IgxGridStateDirective.setState()

## Result  
Following error is thrown on line 
https://github.com/IgniteUI/igniteui-angular/blob/3055cd88df8bc2759587987dcae9881c4ba60174/projects/igniteui-angular/src/lib/grids/state.directive.ts#L231

`Cannot read properties of undefined (reading 'reset')`

This is because following line finds a IgxColumnComponent instead of a IgxColumnGroupComponent:
https://github.com/IgniteUI/igniteui-angular/blob/3055cd88df8bc2759587987dcae9881c4ba60174/projects/igniteui-angular/src/lib/grids/state.directive.ts#L228

## Expected result  
No error should be thrown.

## Attachments  
https://stackblitz.com/edit/3uvton

**Comment by hanastasov** [comment]
The issue is resolved. Next minor version for 16 and 17 (last minors are 16.1.9 and 17.0.4) major versions will both contain the fix. You can monitor when the next version is released at https://github.com/IgniteUI/igniteui-angular/releases
