### ISSUE TITLE
igx-buttongroup throws an exception in a server environment

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#13692]
## Description  
When used in a server-side rendered application, the `igx-buttongroup` throws an exception.

 * igniteui-angular version: 17.0.0
 * browser: server

## Steps to reproduce  

1. Create a new application with `ng new`
2. Choose to enable SSR through the prompt
3. Add a button group to the landing page
4. Run with server-side rendering

## Result  
Exception thrown in console.

## Expected result  
There should be no exceptions.

## Attachments  
![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/0400b4a7-2b0d-4275-8cec-33766252626b)

**Comment by georgianastasov** [comment]
The issue has been resolved by [this PR](https://github.com/IgniteUI/igniteui-angular/pull/13694) and can be considered fixed. This results in no need for the added changes in [this PR](https://github.com/IgniteUI/igniteui-angular/pull/13703) to fix the issue, so the PR is closed and the branch deleted.
