### ISSUE TITLE
Review tests and rewrite them if needed

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#1371]
### Description  
Review all tests that we own and refactor them.
For example, test that are having async or a lot of checks in them (like the Filtering and Filtering UI tests)

**Comment by hanastasov** [comment]
I did not found any flickering tests that need to be refactored. I also did not find it possible to rewrite tests using a lot of asyncs in an other way - they were written with asyncs for a purpose.
