### ISSUE TITLE
IgxCalendar: header does not display with Bootstrap theme

### ISSUE THREAD

**Issue by IMinchev64** [IgniteUI/igniteui-angular#13726]
## Description  
If the theme of the component is set to bootstrap (either light or dark) the header of the calendar has a display set to none as can be observed [here](https://stackblitz.com/edit/scbmiq?file=src%2F_variables.scss)

 * igniteui-angular version: 17.0.4
 * browser: Chrome

## Steps to reproduce  

Either navigate to [this sample](https://stackblitz.com/edit/scbmiq?file=src%2F_variables.scss) or go to [this topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/calendar) and set the theme to Boostrap via the theming widget.

## Result  
Observe how the header is not visible.

## Expected result  
Similar to the Material, Fluent and Indigo themes, the calendar should have a visible header.

**Comment by simeonoff** [comment]
@IMinchev64 The calendar is going over a major refactor of almost all of its UX elements, including the header behavior, it will not be prudent to be fixing this issues in parallel with the ongoing refactoring, thus this issue will be closed with the upcoming update to the calendar.
