### ISSUE TITLE
Changes in component styles

### ISSUE THREAD

**Issue by GrblackStar** [IgniteUI/igniteui-angular#13751]
## Description  
1. Height of grid's advanced filtering dialog:
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/9a99af50-1950-4f73-9d31-42bd439a6364)

2. min-width of the bundle of the input group (screenshot from pinned columns dialog in grid)
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/73e412c8-528b-4057-a953-a1e7e8fc39f5)

**Comment by simeonoff** [comment]
@GrblackStar Is this only reproducible in the app builder? If not, can you provide a supporting sample(s) to compare against as we can't reproduce it on our own.

**Comment by GrblackStar** [comment]
@simeonoff The issue is present on master as well as the AB:
![image](https://github.com/IgniteUI/igniteui-angular/assets/86851411/aa93c548-27d9-4b13-ab22-0ce00e2611a9)
