### ISSUE TITLE
Add a `rowClick` event similar to the `cellClick` one. It should also fire when clicking on space not occupied by columns.

### ISSUE THREAD

**Issue by ericop** [IgniteUI/igniteui-angular#13755]
### Description  
Selecting a row `<igx-grid rowSelection="single" ...` does successfully select the row when clicking to the right of the defined columns (screenshot below). This same sort of functionality ought to be included for clicking a row to taking other actions and aligns with what users expect.

 * igniteui-angular version: 17.0.0
 * browser: Chromium

### Steps to reproduce  

1. Create a grid component where the `igx-column`s have a defined `width` that is less than the width of the grid
2. Clicking in the area right of the defined columns (and cells) 

### Result  
Nothing happens. 
_Clicking on cells with data does work to trigger the expected action but this inconsistence is confusing (in our case, the action opens modal using `cellClick`, but it would serve us well to have a `rowClick`)_

### Expected result  
Users expect clicking anywhere on the row will result in the same action, as visually the row extends to the right. This expectation is set by the way row selection already functions.

#### Working for selecting a row when clicking to right of cells but still in the grid:
![image](https://github.com/IgniteUI/igniteui-angular/assets/5218249/c22fd550-42c9-4e96-ae5c-d24cfde6cc70)

#### Not working for clicking a row when clicking to right of cells but still in the grid:
![image](https://github.com/IgniteUI/igniteui-angular/assets/5218249/ec9c4d7a-69a6-45e0-8cf7-8dd1e34e0528)

**Comment by ChronosSF** [comment]
Hello @ericop ,

I can't think of many other operations that happen on click. I remember a similar case suggesting opening the context menu should also be doable on right click to the right of the right-most column but all useful menu features are column-related and require a cell to get a column context from.

Do you have specific suggestions of features that should work when clicking in that area besides row selection?

The second screenshot shows a grid that has what seems like a custom template / hover action button the implementation of which may interfere with the default functionality. I can try looking into what happens there and why selection doesn't work but I'll need a sample to see how the Process button is implemented.

**Comment by ericop** [comment]
### 2nd draft of the reply:
@ChronosSF, our team makes use of an enhanced GridComponent that is a superset of [IgxGridComponent](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html). The most common implementation of what happens on a row click in the enhanced grid is to open a drawer/modal for viewing or editing that entity's details. So for grids with only a few columns, they could be clicking in that "filler column" but nothing would happen sadly with the current setup. We have wired this up in the following way:
```
// within GridComponent.ts
@Output() rowClick = new EventEmitter<any>();
// ...
  public onCellClick($event: IGridCellEventArgs) {
    this.rowClick.emit($event.cell.row.key ?? get($event.cell.row.data, this.primaryKey));
    $event.event.stopPropagation();
  }
// html template
<app-grid  (rowClick)="handleRowClick($event)">
<!-- only including relevant content in this snippet -->
  <igx-grid ... (cellClick)="onCellClick($event)">
</app-grid>
```

Our ask would be that IgxGridComponent gets a native `(rowClick)`, that detects a click event anywhere on the row within the grid and has access to that rows Id. Then we would no longer have to rely on `(cellClick)`, users would be happy, and all would be right in the world :) .

**Comment by ChronosSF** [comment]
Okay I am adding a feature request and changing the title a bit to be less ambiguous as to what needs to be implemented. I agree that we can add a `rowClick` as a counterpart to `cellClick` for certain scenarios.
