### ISSUE TITLE
IgxButtonGroup: When first selecting any other item in the button group, the last item appears to be the one selected

### ISSUE THREAD

**Issue by PlamenD95** [IgniteUI/igniteui-angular#13761]
## Description  
When the initial value for the "selected" bound prop is undefined, selecting an item for the first time in the button group causes the last item in the button group to be selected.

![button-group-issue-03](https://github.com/IgniteUI/igniteui-angular/assets/26519730/872d6d01-b4ec-4833-80a0-ab258d57e938)

For the case of the capture the initial value of the collection looks like this:

![image](https://github.com/IgniteUI/igniteui-angular/assets/26519730/74870df1-f57c-4895-8887-7418d1dd5a48)

When an item in the button group is clicked, all the item.selected props are set to false, except for the clicked one, which is set to true.

After investigating in the ignite code, the following set + event emitter seems to be at fault:

![image](https://github.com/IgniteUI/igniteui-angular/assets/26519730/65053f7b-5319-4eb7-8b61-4c3e8e4cc2fe)

The button components are triggering a buttonSelected event when its selected value changes from undefined to false, which is not correct.
It could be an issue related to the angular booleanAtribute which is being used there at line 106.

Even though the button.selected prop is boolean and it's being set to undefined, if it's not throwing an error or logging a warning, it would be better to be transformed to false.

 * igniteui-angular version: 16.1.11
 * browser: Chrome Version 120.0.6099.109

## Steps to reproduce  

1. Create a button group with the selected props being set initially to undefined, instead of false.
2. Click on an item in the button group.

## Result  
The last item in the button group appears to be selected

## Expected result  
It is expected for the item that was clicked to appear as the selected one

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
As this issue is related to 16.1 only in the context of the App builder, I am closing it. Seems that it's no longer reproducible in 17.0 of Ignite UI for Angular.
