### ISSUE TITLE
IgxTreeGrid multipleCascade selection + filtering scenario - sibling records get implicitly deselected

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#13762]
## Description  
The current behavior of the `multipleCascade` selection is such that the parent's `selected` state is determined based on the filtered-in children, in case of applied filtering conditions.
However, the result of performing the below listed steps might not quite be expected, as this behavior would cause non filtered-in sibling records' selections state to get implicitly changed. 

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open [this demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row-selection) from the Tree Grid Row Selection topic.
2. Choose 'Cascade' selection mode.
3. Select the first two child records of "Name: Johnathan Winchester"' - "Michael Burke" and "Thomas Anderson".
4. Filter the "Name" column by entering "bu" in the filter input - only the "Michael Burke" child remains.
5. Observe the Parent record checkbox state - it changes from `indeterminate` to `checked` since now all its visible children are selected. 
6. The tree.selectedRows property could also be observed in the console - the currently selected records IDs are `[1, 2, 3]`.
8. Now deselect the "Michael Burke" record -> both child and parent become deselected, because none of the filtered-in children of the parent are now selected. 
9. Clear the filter.

## Result  
No selected records remain at this point, despite not having explicitly deselected the "Thomas Anderson" record.

## Expected result  
The non-filtered child record not to get deselected. It should become deselected only by explicitly deselecting it, or by deselecting its parent record, provided the child is within the currently filtered-in records. 

## Attachments  

![tree-grid-2](https://github.com/IgniteUI/igniteui-angular/assets/35433937/a9c9a2e1-179a-41f2-ba1a-9a2c4b15062a)

**Comment by Glopter** [comment]
Hello. Can anyone give a rough estimate of when work will start here?
