### ISSUE TITLE
Picture Avatar does not render correctly when a large image is provided.

### ISSUE THREAD

**Issue by kdawg1406** [IgniteUI/igniteui-angular#1378]
### Description  
Picture Avatar does not render correctly when a large image is provided.

### Steps to reproduce  

Run attached project.

### Result  
See attached image for the second row, the middle avatar does not render correctly.

### Expected result  
Avatar renders correctly.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
[testBench.zip](https://github.com/IgniteUI/igniteui-angular/files/2027227/testBench.zip)
![2018-05-22_10-59-13](https://user-images.githubusercontent.com/5623887/40370855-34760d42-5daf-11e8-981d-695992f8bca1.jpg)

**Comment by simeonoff** [comment]
@kdawg1406 you never really include the igx-core and igx-theme mixins in your app.
In your `src/styles.scss` file, add:

```scss
@import '~igniteui-angular/core/styles/themes/index';

@include igx-core();
@include igx-theme($default-palette);
```

Once you do that, the avatars will display correctly. To avoid further issues with custom themes, please take a look at:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes.html#generating-a-theme

**Comment by kdawg1406** [comment]
@simeonoff thank you.  I was using your below example to set the files up.  Really appreciate the information, things are moving fast, difficult to keep up sometimes.  Thanks again.

@import '~igniteui-angular/core/styles/themes/index';

// Themes for the first two avatars
// using colors from the default-palette (global)
//  $icon-background: igx-color($default-palette, success),
$avatar-1-theme: igx-avatar-theme(
  $icon-color: white
);

$avatar-2-theme: igx-avatar-theme(
  $icon-background: igx-color($default-palette, warn),
  $icon-color: igx-color($default-palette, error)
);

// Define a custom palette
$my-palette: igx-palette($primary: pink, $secondary: purple);

// Theme for the third avatar
// using colors from the custom palette - $my-palette
$avatar-3-theme: igx-avatar-theme(
  $initials-background: igx-color($my-palette, primary, 800),
  $initials-color: igx-color($my-palette, secondary, 500)
);

:host {
  display: block;
  padding: 16px;

  ::ng-deep {
    .avatar-1 {
      @include igx-avatar($avatar-1-theme);
    }

    .avatar-2 {
      @include igx-avatar($avatar-2-theme);
    }

    .avatar-3 {
      @include igx-avatar($avatar-3-theme);
    }
  }
}

.my-text {
    font-family: 'Titillium Web', sans-serif;
    font-size: 50px;
    font-weight: 400;
    color: igx-color($default-palette, primary);
}

**Comment by kdawg1406** [comment]
@simeonoff after applying this code to my scss file, my layout gets broken.  Please see the before and after pictures.
![before](https://user-images.githubusercontent.com/5623887/40376125-8fd84e14-5dbb-11e8-9e67-960acdc45f00.jpg)
![after](https://user-images.githubusercontent.com/5623887/40376137-93017cfa-5dbb-11e8-8184-b9dc7e32869f.jpg)



@include igx-core();
@include igx-theme($default-palette);

**Comment by simeonoff** [comment]
@kdawg1406 Attaching an updated version of your sample with the changes I suggested in my previous reply.

[testBench-proper.zip](https://github.com/IgniteUI/igniteui-angular/files/2027839/testBench-proper.zip)

**Comment by kdawg1406** [comment]
@simeonoff I put it in the wrong file.  Glad we got this sorted out.
