### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when setting grid size 

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#13797]
## Description  
When the size of the grid with action strip is set through --ig-size ExpressionChangedAfterItHasBeenCheckedError is thrown on hover. 

 * igniteui-angular version: 17.0
 * browser: 

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/dqaqb7?file=src%2Fapp%2Fgrid%2Fgrid-add-row-sample%2Fgrid-add-row-sample.component.html) demo
2. Hover the grid

## Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/52423497/bf2662a7-ca06-491a-9660-e17057b3c709)

## Expected result  
No error

**Comment by Andrix64** [comment]
The same thing appear to be appening with the 
`<igx-grid-toolbar>` 
and his child
`<igx-grid-toolbar-hiding>`

**Comment by adi130987** [comment]
I also have this issue. As a workaround until it's fixed I added ```[displayDensity]="'compact'"``` on the igx-action-strip component and on the grid I have ```--ig-size: var(--ig-size-small)```.
