### ISSUE TITLE
IgxGrid: draggable row behind dialog

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13810]
## Description  
When `rowDraggable` is enabled on a grid inside a dialog then the dragged element is behind the dialog.

 * igniteui-angular version: 17.0.10

## Steps to reproduce  

1. Open IgxGrid inside a IgxDialog
2. Drag a row

## Result  
The dragged row is behind the IgxDialog.

## Expected result  
The dragged row should be in the foreground.

## Attachments  
https://stackblitz.com/edit/ns5xrp

![2024-01-16_10h51_43](https://github.com/IgniteUI/igniteui-angular/assets/46870283/ae80b0a7-78ad-4f18-ab27-b961bb790f4b)

**Comment by Timmeeeey** [comment]
@Lipata Hi, is there any update on this issue?

**Comment by Lipata** [comment]
@Timmeeeey as general solution we have the following improvement in our radar: #14665, which will resolve such issues.
