### ISSUE TITLE
Calendar: Default date formatting in the header

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#13811]
## Description  
The default date formatting in the header differs from the ones in Ignite UI for Angular.

We should agree on default formats for day and month. 

Ignite UI for Angular:

- Day - narrow
- Month - long

Ignite UI for Web Components:

- Day - short
- Month - short

Also, the title always stays at `Select Date`, while it shows the year in Ignite UI for Angular.

## Attachments  
![image](https://github.com/IgniteUI/igniteui-webcomponents/assets/4118303/a7909e63-2738-4c40-a2d1-17be34ce90c9)

**Comment by phuong5** [comment]
how to fix the title: "Select Date" ? please!
I fixed it like below but it doesn't work
<ng-template igxCalendarHeaderTitle let-formatCalendar>{{ formatCalendar.year }}</ng-template>
