### ISSUE TITLE
Igx-spreadsheet: rotation property of the cellFormat doesn't work

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#13829]
## Description  
When we want to set the rotation of a cell, merged cells, column or row in igx-spreadsheet with the `cellFormat` `rotation` property, the text in the cell, merged cells, column or row is not rotated and the `rotation` property doesn't work.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Go to this [sample](https://stackblitz.com/edit/igx-spreadsheet-issue-fixed-16-yttuvk?file=src%2Fapp%2Fapp.component.ts).
2. Observe that there is a set rotation of merged cells region.

      `mergedRegion.cellFormat.rotation = 45;`

## Result  
The text in the merged cells region is not rotated.

## Expected result  
The text in the merged cells region should be rotated.

## Attachments  
![2](https://github.com/IgniteUI/igniteui-angular/assets/48180072/34af1fec-028f-438f-b36e-22c4eddad0dd)
![1](https://github.com/IgniteUI/igniteui-angular/assets/48180072/786e8de6-25da-4d92-93c1-7c9a1d71a03f)

**Comment by mddifilippo89** [comment]
The Spreadsheet doesn't support cell rotation, as the property is exposed from the Excel Engine for it's intent and purposes only. Adding spreadsheet cell rotation is considered a feature request.
