### ISSUE TITLE
Search API replaces avatar the with image source when grid column is templated with an image

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1383]
### Description  
Search API replaces avatar the with image source when grid column is templated with an image.

### Steps to reproduce  

1. Download and run the sample application.
2. Type "http" inside the search input below the grid.

### Result  
The image gets replaced with its source (in this case the hyperlink).

### Expected result  
The image is not affected by the search and remains an image.

### Attachments  

[igxGridSampleSearch.zip](https://github.com/IgniteUI/igniteui-angular/files/2031057/igxGridSampleSearch.zip)
![avatarsearch](https://user-images.githubusercontent.com/12784974/40425472-264ef0ec-5ea1-11e8-90a5-4bbd8a4644d8.gif)

**Comment by DDavidkov** [comment]
Note that for the fix to work you need to set the searchable property of the avatar column to false.
