### ISSUE TITLE
stopPropagation on click in the igx-dialog component

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#13849]
## Description  
Currently the dialog is defined like this:
`<div tabindex="0" #dialog class="igx-dialog" igxToggle [igxFocusTrap]="focusTrap" (click)="onDialogSelected($event)"></div>`

When clicked in the dialog `stopPropagation` is called:
`public onDialogSelected(event) {
        event.stopPropagation();
        //...
}`

With this implementation, event propagation is always stopped at the moment. This implementation is made in relation to scenarios with nested igx-dialog components. This is because when we have nested igx-dialog components and a click is made outside the inner igx-dialog, only it should close, and the parent dialog should remain open as this is related to this [issue](https://github.com/IgniteUI/igniteui-angular/issues/590).

However, this implementation leads to the impossibility of closing some components inside the dialog, such as context menus, because after opening a context menu in the igx-dialog component, when clicking outside the context menu but inside the igx-dialog component, it cannot close because `stopPropagation` is called.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Create igx-dialog with context menu in in. 
2. Handle `@HostListener('document:click', ['$event'])` to close the context menu. 
3. Click in the igx-dialog component.

## Result  
The context menu does not close.

## Expected result  
The context menu should close.

## Attachments  
The issue is discussed in this [discussions](https://github.com/IgniteUI/igniteui-angular/issues/590).

**Comment by Timmeeeey** [comment]
@Lipata Hi, is there any plan to address this issue?

**Comment by georgianastasov** [comment]
Hi @Timmeeeey

After thorough discussions with the development team, we have come to an agreement regarding this issue. It has been decided that we will not be fixing this issue within the current implementation.

As a proposed solution, we recommend using another overlay to show the context menu within the `igx-dialog` component. By using the `IgxOverlayService`, you can create and attach an overlay to display your context menu. This approach will avoid the described behavior and allow you to close the overlay by clicking anywhere in the document, including on top of the `igx-dialog` component.

For more information on how to use the `IgxOverlayService`, please refer to the documentation here: [IgxOverlayService Documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/overlay).

**Comment by Timmeeeey** [comment]
Hi @georgianastasov 
Since I use a third-party context menu (PerfectMemory/ngx-contextmenu), I don't know how I could use the IgxOverlayService.

**Comment by Timmeeeey** [comment]
Ok, I think I have to use the `attach(element: ElementRef, settings?: OverlaySettings)` because the component has inputs.
This seems to work but when opening the context menu, the background darkens. Can this be prevented?

**Comment by Timmeeeey** [comment]
@georgianastasov 
It didn't work without modal true, but I figured out another solution with a custom backdrop.

**Comment by georgianastasov** [comment]
Hello @Timmeeeey 

Thank you for the update. I'm glad to hear that you found a solution using a custom backdrop. If you need any further assistance or have any other questions, please feel free to reach out.
