### ISSUE TITLE
Binding 2 calendars to the same value makes the app freeze

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#13850]
## Description  
Describe the issue.

 * igniteui-angular version: ^17.0.0
 * browser: Chrome/FF

## Steps to reproduce  

1.
```
@Component({
  selector: 'card-sample',
  templateUrl: './card-sample.component.html'
})
export class CardSampleComponent {
  public date = new Date('2024-01-30T00:00');
}
```
```
  <igx-calendar [(ngModel)]="date"></igx-calendar>
  <igx-calendar [(ngModel)]="date"></igx-calendar>
```

## Result  
Everything freezes, high CPU usage

## Expected result  
Display both calendars bound to the same value

## Attachments  
Stackblitz: https://stackblitz.com/edit/s81ez8?file=src%2Fapp%2Fcalendar-sample-5%2Fcalendar-sample-5.component.html)

**Comment by kdinev** [comment]
@deyvidnenchev I believe this is also reproducible in `17.0.x` and `16.1.x`. Could you please cherry-pick your changes and make PRs against all applicable branches?

**Comment by pmoleri** [comment]
Re-opening as this is also reproduce-able using "range" mode.
"multi" mode already has a safe-guard by comparing the new and old dates.
But it has a different issue, it's not possible to unselect dates using Ctrl when using 2 2-way bounds calendars.

**Comment by hanastasov** [comment]
> Re-opening as this is also reproduce-able using "range" mode. "multi" mode already has a safe-guard by comparing the new and old dates. But it has a different issue, it's not possible to unselect dates using Ctrl when using 2 2-way bounds calendars.

@deyvidnenchev  was about to log the range issue as a separate one(he is aware of it), but we didnt want to  make this PR late. Anyway, first fix is already merged so the same issue can be used about the range one.

**Comment by hanastasov** [comment]
> > Re-opening as this is also reproduce-able using "range" mode. "multi" mode already has a safe-guard by comparing the new and old dates. But it has a different issue, it's not possible to unselect dates using Ctrl when using 2 2-way bounds calendars.
> 
> @deyvidnenchev was about to log the range issue as a separate one(he is aware of it), but we didnt want to make this PR late. Anyway, first fix is already merged so the same issue can be used about the range one.

This will be resolved as a separate issue https://github.com/IgniteUI/igniteui-angular/issues/14068
