### ISSUE TITLE
Global filtering the igx-grid throws error

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1385]
### Steps to reproduce  

1. Run the sample and click the Filter button
2. Try to open the filter UI for the Age, RegisterDate or isActive columns

### Result  
See the errors in the browser dev tools console:
IgxDatePickerComponent.html:1 ERROR TypeError: value.toLocaleDateString is not a function

### Expected result  
No errors to be thrown

TBD:
- It seems like the grid will set the correct filtering condition per column, if such is not passed to the filterGlobal method. However, passing the a filter condition to the globalFilter method will result in setting the same filter to all columns.
- How is the filterGlobal method going to work for a grid where columns are of different type. The filterGlobal method accepts filtering condition as a parameter, but there is no universal conditon that can be applied to any type of column.

### Attachments  
[igxgrid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2031700/igxgrid-app.zip)

**Comment by Aleksandyr** [comment]
This is the normal behavior of this method considering the implementation now. It works perfectly when the whole columns of the grid are with the same type. The problem comes when the type of the columns are different because the value which is passed to the method is not handled based on the type of the column. So this have to be discussed:
1. Whether this method should exists as a whole
2. Whether this method should be exposed to the users
3. Whether we should handle somehow the value that is passed based on the type of the columns that are declared.

@SlavUI If you have any comments or suggestions please point them out.

**Comment by zdrawku** [comment]
A new feature request has been logged regarding this error.
Our main focus is on different features now, and we are going to start working on this after June.

Feature request - https://github.com/IgniteUI/igniteui-angular/issues/1577

**Comment by Hypenate** [comment]
Has this fix/feature been 'released' yet?
I'm having the issue when I want to filter on a DataType of Date.

On serving I get a red line an error:

> IgxDatePickerComponent.html:7
> ERROR TypeError: value.toLocaleDateString is not a function
>     at IgxDatePickerComponent.push.../node_modules/igniteui-angular/fesm5/igniteui-angular.js.IgxDatePickerComponent._setLocaleToDate (igniteui-angular.js:12002)
>     at IgxDatePickerComponent.push.../node_modules/igniteui-angular/fesm5/igniteui-angular.js.IgxDatePickerComponent._customFormatChecker (igniteui-angular.js:12017)
>     at IgxDatePickerComponent.get [as displayData] (igniteui-angular.js:11797)
>     at Object.eval [as updateDirectives] (IgxDatePickerComponent.html:7)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.js:10853)
>     at checkAndUpdateView (core.js:10250)
>     at callViewAction (core.js:10491)
>     at execComponentViewsAction (core.js:10433)
>     at checkAndUpdateView (core.js:10256)
>     at callViewAction (core.js:10491)

Line 7 is:
`<input class="igx-date-picker__input-date" igxInput [value]="displayData" [disabled]="isDisabled" readonly />`
