### ISSUE TITLE
Bootstrap igx-button has a default margin with !important

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#13865]
## Description  
The bootstrap variant of the `igx-button` has a default margin, which is not there in the other themes. The margin misaligns buttons relative to input elements in forms

 * igniteui-angular version: 17.0.x
 * browser: all

## Steps to reproduce  

1. Open app builder
2. Create a new app and set the theme to bootstrap light
3. Drop and input and a button in a column layout

## Result  
The input and button are not aligned.
The issue is also somewhat visible [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/input-group#typed-forms), when you switch to bootstrap light theme.

## Expected result  
The two should be aligned.

## Attachments  
![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/09fba798-a847-440b-b86b-76d9d61e0821)

**Comment by zdrawku** [comment]
@desig9stein This is the one I shared with you, a probable cause of the problem:

![image](https://github.com/IgniteUI/igniteui-angular/assets/11193764/636dba9c-3221-42d4-b1f3-7589378d87ff)

**Comment by desig9stein** [comment]
@SisIvanova @kdinev take a look in this issue before merging
https://github.com/IgniteUI/igniteui-angular/issues/12267
