### ISSUE TITLE
Feature Request - Improved UI of Row Selection

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#1386]
### Description  
Row selection should not require a check box, just an appearance change
Row selection should allow for ranged selection with Shift + Click
Selecting multiple should be done with a ctrl + click
De-selecting a single item when multiple are selected should also be able to be done with a ctrl+click

Doing a Shift + Click, should not do a text selection on all the text between those two points.

### Attachments  
https://stackblitz.com/edit/angular-qba2bh

**Comment by kdinev** [comment]
The requested interactions can be implemented using the exposed row selection events. The row selection feature is implemented according to the material guideline and is device and input agnostic. We would switch to an input or design specific implementation.

https://material.io/design/components/data-tables.html
