### ISSUE TITLE
IgxStepper: css issue with font-size 14px

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13864]
## Description  
When using the IgxStepper with a base font-size of 14px then the indicators are cut off at the bottom.

 * igniteui-angular version: 17.0.12
 * browser: Firefox

## Attachments  
https://stackblitz.com/edit/zmyd2c

![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/b2f60c3f-c922-499e-b364-1a8660dcf47b)

**Comment by didimmova** [comment]
@Timmeeeey, you should update the `$base-font-size` variable to 14px so the rem function can scale sizes according to this base size.

`@use 'igniteui-theming/sass/config' as * with ($base-font-size: 14px);`

**Comment by Timmeeeey** [comment]
@didimmova 
The issue seems to be the box-shadow:

```css
.igx-stepper__step-indicator {
  box-shadow: 0 0 0 0.0625rem var(--indicator-outline);
}
```

With a base font-size of 14px, 0.0625rem is less than 1px and Firefox seems to have problems with this.
Wouldn't it be reasonable to have a minimum of 1px here?

**Comment by didimmova** [comment]
Check this out https://stackblitz.com/edit/zmyd2c-ezecmx?file=src%2Fstyles.scss it's working as it should.

**Comment by Timmeeeey** [comment]
Actually I'm using the css theme and not the sass theme.
There it doesn't  matter if you set the `--ig-base-font-size` variable.

https://stackblitz.com/edit/zmyd2c-wpw887
