### ISSUE TITLE
Calendar set value code improvement

### ISSUE THREAD

**Issue by dobromirts** [IgniteUI/igniteui-angular#13894]
In this pull requet #13877 highlighted by @pmoleri, enhancements to the calendar set value method are suggested to improve checks, eliminate redundant assignments, and ensure non-date values are handled appropriately.

![image](https://github.com/IgniteUI/igniteui-angular/assets/46093564/77a73b3f-9fa6-4d3c-9f01-f36dfa500601)

**Comment by pmoleri** [comment]
Also, this cast has no sense:
![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/f9ae4230-8034-478e-9aa8-196085122096)

Also noticing this possible inconsistency:
![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/50a97a47-e0f6-4283-9356-eb7f9efdfef4)

I don't see any reason why `set value` and `writeValue` should do different things.
They should probably have the exact same code, or one delegate the work to the other.

**Comment by pmoleri** [comment]
Perhaps we should report his as a different bug.
But using `selection='multi'` the calendar doesn't react to removing dates from the input array:
https://stackblitz.com/edit/s81ez8-yryk3e?file=src%2Fapp%2Fcalendar-sample-5%2Fcalendar-sample-5.component.html,src%2Fapp%2Fcalendar-sample-5%2Fcalendar-sample-5.component.ts

**Comment by dobromirts** [comment]
Resolved with calendar refactoring and improvements PR: #13650
