### ISSUE TITLE
Feature Request - igxGrid Persistence Framework

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#1390]
### Description  
This has been a common request with most of my client meetings; That is the ability to save and load the state of the grid. While I know that all the properties to have the developer achieve this do exist, and are public. If we could have built in methods to save and load the current state of the grid. Essentially serialize all the properties related to the current state of all columns and rows, if row states are configurable. With options to include\exclude any of the groups of states.
States to be stored would be:
 filtering, sorting, column position, column size, pinned location, essentially any state that the end user can change excluding cell values.

**Comment by kdinev** [comment]
We've documented how state can be persisted and restored for the `igx-grid` in this document:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence
