### ISSUE TITLE
Error on copying cells linked to other sheets

### ISSUE THREAD

**Issue by KV-Development** [IgniteUI/igniteui-angular#13924]
Browser: Chrome/Firefox both have the same behaviour
Version: I think the igx spreadsheet demo page uses the latest one

## Description  

I am reaching out regarding an issue I encountered while exploring the IGX Spreadsheet Demo on your website. Specifically, I was testing the functionality of linking cells between sheets and noticed an unexpected behavior.

Initially, I successfully linked a cell to another sheet using the formula '=Sheet1!C8'. However, upon attempting to copy and paste this cell to generate a new one, I observed that the sheet name was lost and the pasted cell exhibited unexpected behavior, as depicted in the attached screenshot.

Could you please advise if this issue is a known bug or if there is a workaround to ensure consistent behavior when copying cells with sheet references?

## Steps to reproduce  

1. Create a new sheet on the demo of igx spreadshet website
2. On the new sheet link a cell to another one in the first sheet
3. Then try to copy the formula present in the second sheet in a new cell still on the second sheet

## Result  
The result after doing this is a corrupted formula that doesn't link to the first sheet cell. I't seems the problem is with the word 'Sheet' cause the cell get's adapted correctly. In example if i copy the '=Sheet1!C8' in the C9 cell i will get something like this '=[null]#ref!'!C9'

## Expected result  
The expected result after the steps to reproduce is that in the cell where the formula is copied is correctly mantained the link with the first sheet.

## Attachments  
![Screenshot 2024-02-15 104149 (1)](https://github.com/IgniteUI/igniteui-angular/assets/118280286/248d2bab-8395-4e73-99b3-6dc7c0998917)

**Comment by KV-Development** [comment]
Any news on this? @ChronosSF

**Comment by ChronosSF** [comment]
@agoldenbaum , could you please take a look?

**Comment by igandrews** [comment]
You're correct that it should have been able to reference the cell on the other worksheet. This is a bug in the internal copy handling. We have a potential fix internally that needs to be verified and then it will be available in an upcoming build. I don't see a way to workaround the issue with the current version.

**Comment by KV-Development** [comment]
Thank you for the answer. Have u already an ETA for the upcoming build? Or can u link me the PR if is public so i can keep updates on that and check the status?
