### ISSUE TITLE
Unable to update to 17

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#13936]
## Question  
Running the I `ng update @infragistics/igniteui-angular` get the follwing error. Running npm install seems to work fine. Any suggestions?
![image](https://github.com/IgniteUI/igniteui-angular/assets/12936286/41e0c36e-d8fa-47c1-994c-e01b6d0c8f4d)

Running `ng update` results in
![image](https://github.com/IgniteUI/igniteui-angular/assets/12936286/298a6d0c-319f-4399-9dd8-2cada07486f4)

**Comment by ChronosSF** [comment]
@Eralmidia , quite peculiar - my best guess is that `ng update` doesn't take into account your npmrc config that points to packages.infragistics.com for the @infragistics scope. Is that set in a local npmrc file or in your global config? Does ng cli say that it's installing a newer local version when you run `ng update`?
