### ISSUE TITLE
Theme issue when having an OnPush component inside igx-tabs or igx-stepper

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#13958]
## Description  

Theme is always Material having an OnPush component inside igx-tabs or igx-stepper.

 * igniteui-angular version: 17.1.0
 * browser: all

## Steps to reproduce  

1. Set Theme to Fluent
2. Create an OnPush form with igx-inputs inside
3. In the main view add a tabs component with a Form instance in each tab
4. Run

## Result  

The Form inputs get rendered as Material theme. After clicking one of them they change to fluent.

Note: If I add ` [selected]="true"` to the first tab, then it fixes for it but it still happens on the 2nd tab.

## Expected result
The inputs should render as Fluent from the beginning.

## Attachments
![tab-theme-form](https://github.com/IgniteUI/igniteui-angular/assets/12942794/d695b1e5-fe19-4fb7-8b85-71c1282ac0ec)

https://stackblitz.com/edit/vn4fjr?file=src%2Fapp%2Ftabs-sample-3%2Ftabs-sample-3.component.html

**Comment by simeonoff** [comment]
Honestly, the only viable solution I can think of right now (after numerous ugly attempts to magically update the theme from within the input group) is to just manually call `detectChanges()` in `ngAfterViewChecked`. Since the theme property is read from the `--theme` css variable, it's difficult to read the prop from within the input group component when it's inside another component with OnPush strategy set.

```ts
export class MyFormComponent implements AfterViewChecked {
    constructor(private cdr: ChangeDetectorRef) {}

    public ngAfterViewChecked() {
        this.cdr.detectChanges();
    }
}
```

The other approach (if you are concerned about performance) is to set the `theme` property directly on each `igx-input-group`.

```html
<igx-input-group type="line" theme="fluent">
    <input igxInput name="fullName1" type="text" />
    <label igxLabel for="fullName1">Full Name</label>
    <igx-suffix>
        <igx-icon>person</igx-icon>
    </igx-suffix>
</igx-input-group>
```

**Comment by pmoleri** [comment]
@simeonoff 
```ts
    public ngAfterViewChecked() {
        this.cdr.detectChanges();
    }
```
I believe this will perpetually check for changes and not just for this component but for everything up in the tree.

This is how I believe it should be done, on inputgroup component which is the one that's making the assumption that has access to the css props.

```ts
export class InputGroupComponent implements DoCheck, {
    #lastIsConnected: boolean | undefined;

    constructor(
        private elementRef: ElementRef<unknown>,
        private cdr: ChangeDetectorRef,
    ) { }
    
    ngDoCheck() {
        const isConnected = this.elementRef.nativeElement?.isConnected;
        if (this.#lastIsConnected === false && isConnected) {
            // Trigger change detection when changing from disconnected to connected state
            // To force the component to re-render once they get attached in OnPush context.
            // https://github.com/IgniteUI/igniteui-angular/issues/13958
            this.cdr.markForCheck();
        }
    
        this.#lastIsConnected = isConnected;
    }
}
```

**Comment by simeonoff** [comment]
Thanks, will try this to see if it resolves to problem.

**Comment by simeonoff** [comment]
This should be resolved by https://github.com/IgniteUI/igniteui-angular/pull/14035/files#diff-3a8eee910c2ea04cd03aa2cb41b21e94c0844017e6743d7721cabea136010cdb
