### ISSUE TITLE
IgxButtonGroup: The button selection doesn't work properly when two button groups are bound to the same data collection

### ISSUE THREAD

**Issue by PlamenD95** [IgniteUI/igniteui-angular#13967]
## Description  
When there are two button groups bound to the same data collection, the button selection doesn't work as expected.
One button group correctly updates the selected button according to the user selection, but the second group doesn't.

The most probable reason for that is that the `updateButtonSelectionState` method in the `buttonGroup` component calls the `deselectButton` for the button that should be selected in the second button group.

 * igniteui-angular version: 17.1.0
 * browser: Chrome 121.0.6167.161

## Steps to reproduce  

1. Create an app with two button groups bound to the same data collection
2. Change the selection of the first group.
3. The second button group should also update its selection accordingly, but it doesn'tm when the user clicks on a button to the left of the previously selected one.

## Result  
![button selection](https://github.com/IgniteUI/igniteui-angular/assets/26519730/0dd940de-04b2-408e-be65-202b2629c9fe)

## Expected result  
Both button groups should correctly update the selected button after user interaction

**Comment by hanastasov** [comment]
Gaby spent the time to replicate this bug in a [stackbliz sample](https://stackblitz.com/edit/mbvkqn?file=src%2Fapp%2Fbutton-group-sample-1%2Fbutton-group-sample-1.component.html,src%2Fapp%2Fbutton-group-sample-1%2Fbutton-group-sample-1.component.scss,src%2F_app-layout.scss). Thank you @gmartinezig !
