### ISSUE TITLE
Grid rowAdded event missing data

### ISSUE THREAD

**Issue by deyvidnenchev** [IgniteUI/igniteui-angular#13986]
## Description  
All data apart from primary key is undefined when rowAdded event is triggered

 * igniteui-angular version: 17.1.0
 * browser: 122.0.6261.95

## Steps to reproduce  

1. Create Grid with Row Add functionality 
2. Log rowAdded event output of the grid
3. Start the app and add a row to the grid (fill in some of the cells)

## Result  
On the logged event everything apart from the primary key is undefined.

## Expected result  
Filled in data in  the cells should be present in the rowAdded event

## Attachments  
https://stackblitz.com/edit/v6fp1s-wysysb?file=src%2Fapp%2Fgrid%2Fgrid-action-strip%2Fgrid-action-strip-sample.html

https://github.com/IgniteUI/igniteui-angular/assets/60451908/98771ce1-45aa-4937-8984-8006109da23c

**Comment by hanastasov** [comment]
I see all related info, 
![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/aa448a1b-0a4b-4352-8290-4482f4d1967c)

@deyvidnenchev  are you sure you have added info for all columns?

**Comment by hanastasov** [comment]
Ok, it seems that when clicking the DONE button while a cell is still in edit mode, the cell value will not be committed.

**Comment by deyvidnenchev** [comment]
Still reproducible in 17.1.9
