### ISSUE TITLE
igx-grid memory leak when users click pagination buttons

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-angular#13994]
## Description

The `igx-grid` has a memory leaking problem. It happens when users click the paginator buttons.

 * igniteui-angular version: 17.1.4
 * browser: Microsoft Edge Version 122.0.2365.92 (Official Build) (64-bit)

## Steps to reproduce  

1. Open the browser's Dev Tools / Memory tab.
2. Take the 1st memory snapshot (don't forget to click the "Collect garbage" button before taking.)
3. Navigate to the page with an `igx-grid` component with a pagenator.
4. Click on the "next page" button of the pagenator.
5. Go back to the home page.
6. Take the 2nd memory snapshot (remember to click the "Collect garbage" button before taking it).
7. In the Dev Tools Memory tab, Choose "Comparison" in the "Perspective" dropdown and input "igx" into the "Class filter" text field.

https://github.com/IgniteUI/igniteui-angular/assets/102948935/1ea9cfc5-d00a-4d87-bc03-0d73f58d888b

## Result  
You will see there are some objects with the name "igx" that were added but not deleted in the "Comparison" view of the Memory tab.

## Expected result  
The "Delta" column for all objects with the name "igx" should be zero in the "Comparison" view of the Memory tab.

## Attachments  

[📦c-00235192-ng-app1-v17.1.4 (2).zip](https://github.com/IgniteUI/igniteui-angular/files/14632583/c-00235192-ng-app1-v17.1.4.2.zip)

**Comment by jsakamotoIGJP** [comment]
Hi @ChronosSF, thank you for reopening this ticket!

**Comment by ChronosSF** [comment]
Thank you for investigating this so thoroughly, @MayaKirova . I am closing this as a third-party-issue.
