### ISSUE TITLE
Date/datetime/time editors should accept the same formats that the angular pipes accept

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#14011]
## Is your feature request related to a problem? Please describe.
Currently if you want to set 12-hour date-time format using the Angular date formatting pipe you do something like this:

`dd/MM/yyyy hh:mm:ss a`

But our date-time editor that is supposed to seamlessly edit such cells need a format like this:

`dd/MM/yyyy hh:mm:ss tt`

Our editors should be able to understand formats that the default Angular pipes use as users shouldn't be required to set two different formats to achieve the same result between a cell in and out of edit mode.

**Comment by ddaribo** [comment]
Angular's DatePipe supports 19 field types, including the supported for editing by the Ingite UI for Angular date/time editors: Date, Month, Year, Hours, Minutes, Seconds, and Period (named AmPm in the library). Non-supported types include Era, Month standalone, etc, [ref](https://angular.io/api/common/DatePipe#custom-format-options).

To extend support for additional custom formats, editors would need to handle the same features implemented for currently supported date parts, such as spin editing, masking and validation. This may introduce complexities in editing non-numeric date parts.

Currently, only the numeric equivalents of the DatePipe's formats are covered for input by the editors, excluding Fractional Seconds. Period (AmPm) is supported through the format `tt`, as in the given example above, but other variations like `aaaa` & `aaaaa`, etc. are not.

Regarding `currency`, `percent`, and `number` types columns in the `igx-grid`, their formats can be configured using the `pipeArgs` property and they support the same set of configs as the corresponding Angular pipes ([ref](https://angular.io/api/common#pipes)) - for display. There is no formatting/mask applied for their edit mode as a result of configuring the `pipeArgs`  whatsoever.

The options to enhance this could include:

- Supporting Period format as `a`, `aa`, & `aaa`. Consideration for `aaaa` & `aaaaa` formats and Period* field types?
- Adding support for editing Fractional Seconds, the only numeric field type currently unsupported, if it makes sense in the context of the date/time editors.

**Comment by rkaraivanov** [comment]
I'm thumbs up for supporting the `a`, `aa`, etc. for the display format of the period in the date time editor.

As an aside, the web component version already does `t`, `tt`, `ttt`, `tttt` and `ttttt` as [display format values](https://github.com/IgniteUI/igniteui-webcomponents/wiki/Date-Time-Input#functionality), so if the Angular version does not support them, then we should consider adding that as well.

As for the fractional second, sure let's add that too. Open a new issue or link this one to the web component repository as these changes should be implemented there as well.
