### ISSUE TITLE
InlineEditorTemplate of the grid is not working correct if not two way bound to the editValue of the cell

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#14020]
## Description  
If you try to use inlineEditorTemplate like this and not bound to ngModel: 
```
       <ng-template igxCellEditor let-cell="cell">
            <input name="units"  [value]="cell.editValue" (change)="test($event,cell)"/>
        </ng-template>
```
then the edited value is not updated.
 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Use the above inlineEditorTemplate
2. Try to edit the cell and update the value
3 .Press enter

## Result  
The value of the cell is not updated

## Expected result  
The value of the cell should be updated

This is happening because the change event is called after the editing is done (after the cell template is destroyed) because pressing enter goes to the `keydown` event of the grid body which is before change in the sequence

**Comment by hanastasov** [comment]
Due to the same reason (the grid keyboard navigation handling keydown, which might come before a value is updated), the cell.editValue is not updated in another scenario too:

```
       <ng-template igxCellEditor let-cell="cell">
            <input name="units"  [(ngModel)]="cell.editValue" [ngModelOptions]="{ updateOn: 'blur' }" />
        </ng-template>
```

Let's verify it works for all possible values of upddateOn option (see updateOn: Defines the event upon which the form control value and validity update. Defaults to 'change'. Possible values: 'change' | 'blur' | 'submit'.)

**Comment by mddragnev** [comment]
@hanastasov I dont think that `submit` as `ngModelOptions` makes much sense to me for an editing template. Do you have anything in mind? The PR fixes the `blur` part

**Comment by hanastasov** [comment]
> @hanastasov I dont think that `submit` as `ngModelOptions` makes much sense to me for an editing template. Do you have anything in mind? The PR fixes the `blur` part

I agree, I think a form control in the editing template is an edge case rather than the common case.
