### ISSUE TITLE
IgxToggle not working properly on Safari

### ISSUE THREAD

**Issue by altju** [IgniteUI/igniteui-angular#14030]
## Description  
The IgxToggleDirective (and very likely all related components that are using it) is not working properly on Safari (iPhone/iPad).
Content is still visible after toggling.

 * igniteui-angular version: 16.0.13
 * browser: Safari (iOS/iPadOS 17.4.1)

## Steps to reproduce  

1. Go to the Angular Igx Toggle Demo page (https://www.infragistics.com/products/ignite-ui-angular/angular/components/toggle)
2. Press toggle button (picture is visible)
3. Press toggle button again (picture is still visible)

## Result  
Picture (or whatever gets toggled) is still visible after toggling again.

## Expected result  
Picture (or whatever gets toggled) should not be visible after toggling.

**Comment by jesshannon** [comment]
We're seeing this on dropdowns for igx-select, it seems to be a Safari bug, specifically on iOS/iPadOS with 17.4

The _igx-drop-down__list_ doesn't disappear even though it has _igx-toggle--hidden_ set. Looking at the computed styles for that element it show's display:block. But then clicking to view the source it takes you to the rule for igx-toggle--hidden, which is of course display:none.

Manipulating _any_ part of the CSS in the inspector causes it to apply the display:none correctly.

**Comment by dafo** [comment]
This issue does not seem to be a Safari specific. I am able to reproduce it on Chrome and DuckDuckGo on iOS 17.4.1.

**Comment by jesshannon** [comment]
> This issue does not seem to be a Safari specific. I am able to reproduce it on Chrome and DuckDuckGo on iOS 17.4.1.

Those browsers are still using the safari rendering engine on iOS.

**Comment by jesshannon** [comment]
Has anyone been able to test this on Safari 17.5 beta to see if it's still an issue?
