### ISSUE TITLE
Fluent theme: size of button groups not working

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#14063]
## Description  
The css fluent themes `igniteui-fluent-light-word.css` and `igniteui-fluent-dark-word.css` have been changed since `17.1.0` so that the size of button groups doesn't work anymore.

Apart from that, is it intentional that the font-weight of the buttons changed from 400 to 600?

 * igniteui-angular version: 17.1.0

## Attachments  

version 17.0.15
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/0dcafab8-217c-4806-9d3e-436a7b5a412c)

version 17.1.0
![image](https://github.com/IgniteUI/igniteui-angular/assets/46870283/7b7528dd-2727-4f5e-b7ab-39e1a77a11e3)

**Comment by SisIvanova** [comment]
Hey @Timmeeeey, the problem with the button group size was just fixed. As for the font-weight of the buttons, this change is intentional.
