### ISSUE TITLE
IgxSimpleCombo: Combo gets cleared when entering a valid value and press tab

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#14085]
## Description  
If you enter a valid value and press `tab` then the combo doesn't select the value.

It would be better for user experience if the user could just enter a valid value and go on instead of having to select a value every time.
It's confusing when you enter a valid value and the combo gets cleared when tabbing or clicking outside.

 * igniteui-angular version: 17.1.7

## Attachments  
![2024-04-09_14h24_26](https://github.com/IgniteUI/igniteui-angular/assets/46870283/410afd9b-adcd-4e76-9079-8f28f57069ca)

**Comment by Timmeeeey** [comment]
@jackofdiamond5 hi, is this something that is being considered to be implemented?

**Comment by Lipata** [comment]
@Timmeeeey we will look at this issue next week.

**Comment by sdimchevski** [comment]
Users typically expect the value they entered to remain in the field when they press "Tab," especially if it’s valid. Allowing them to move on without any further interaction is a more user-friendly approach. It respects the user’s intent and streamlines the process as they often expect to move through forms quickly. I think for a better user experience, if a user enters a valid value and presses "Tab" to move to the next field the Combo should automatically accept and select that value without requiring an additional "Enter" or click action.
