### ISSUE TITLE
Simplyfy igx-icon

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1409]
### Description  
Just a tiny suggestion for the igx-icon. Please implement support for content projection in addition to  attribute. So instead of 

`<igx-icon name="volume_off"></igx-icon>`

we can simply do

`<igx-icon>volum_off</igx-icon>`

Its a small thing, but it looks cleaner

**Comment by Eralmidia** [comment]
Perfect :) Then perhaps this issue could be modified to show this in the docs https://www.infragistics.com/products/ignite-ui-angular/angular/components/icon.html Doesn't seem to be menitoned or shown in the examples.

**Comment by zdrawku** [comment]
I have created a separate issue for this suggstion in the corrext repository. Thank you @Eralmidia
