### ISSUE TITLE
Indigo Theme | Input Group: incorrect paddings and icon size in prefix and suffix

### ISSUE THREAD

**Issue by imincheva** [IgniteUI/igniteui-angular#14128]
## Description  
The most recent updates on the Indigo theme in regards to the Input Group have been applied on the demos on the Input Group page. However, on the rest of the pages, where the Input Group base is used, the paddings and the size of the icons in prefix and suffix aren't applied. Some examples can be seen on the following pages: Date Picker, Forms, Time Picker. 

## Steps to reproduce (Date Picker)

1. Open Date Picker page
2. Inspect the igx-prefix and look at the left and right paddings 
3. Inspect the igx-icon and look at the size of the icon

*The same steps can be used to reproduce the issue on the above mentioned pages. Bare in mind, this problem occurs in a number of pages across the samples so probably not all of them have been mentioned in this bug report.

## Result  
1. Upon inspecting the igx-prefix you'll see the left and right paddings are 6px. In the Input Group, however, the paddings are 4px, which is by design and the expected result.
<img width="206" alt="image" src="https://github.com/IgniteUI/igniteui-angular/assets/116892553/c6928496-8329-4d7c-90df-cfbe3259794a">

2. Upon inspecting the igx-icon you'll see the size is 18x18x.  In the Input Group, however, the size is 16x16px, which is by design and the expected result.
<img width="318" alt="image" src="https://github.com/IgniteUI/igniteui-angular/assets/116892553/c9f567bd-689b-4c5a-9fd1-683a6daa36a1">

## Expected result  
It is expected that the above mentioned paddings and size of the icon in the prefix and suffix should be aligned to the ones in the Input Group across all samples.

**Comment by SisIvanova** [comment]
@imincheva The input-group sizes that you're referring to (16px icon size and 4px padding) are for `displayDensity="cosy"` or the medium size of the component. The size of the date picker and time picker in the samples is large therefore the padding is 6px and the icon size is 18px which are the defaults for large input.

Input Group Default Sizes in Indigo Theme:
- small/compact mode => Icon size - 14px; Prefix/suffix padding - 2px;
- medium/cosy mode => Icon size - 16px; Prefix/suffix padding - 4px;
- large/comfortable mode => Icon size - 18px; Prefix/suffix padding - 6px;

If any of these should be updated please let me know.
