### ISSUE TITLE
Scrolling the grid on row drag not working

### ISSUE THREAD

**Issue by Ugla-Bugla** [IgniteUI/igniteui-angular#14130]
## Description  
Row drag with scrolling is not working. It seems to be unstable when scrolling down(sometimes it just stops). When scrolling up this seems to be less of an issues.

If zoom level is anything but 100% the scrolling simply seems to stop by itself both directions.
It is possible to reproduce the errors in "Scrolling the grid on row drag" stackblitz located here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag

## Steps to reproduce  

1. Open the stackblitz from the example above.
2. Try to scroll the grid while dragging.
3. Zoom in or out and repeat step 1 and 2.

## Result  
The grid will stop scrolling.

## Expected result  
The grid wont stop scrolling

## Attachments  
"Scrolling the grid on row drag" stackblitz located here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag

**Comment by Eralmidia** [comment]
Second this issue. We have raised this previously in #9660 , arguing this should actually be built into the grid. Seems to me like such a fundamental thing to have built-in for such a feature rich grid as the igx-grid. The value of row drag without scrolling the grid up or down is quite small, unless you use it to move from one grid to another or similar. For creating something like a file explorer, this would be really handy to have native support for this.
