### ISSUE TITLE
Switch and checkbox value is not assigned

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#14136]
## Description  
I have a switch and checkbox both bound to a variable via `value` property. Component does not render the value of the bound variable. Also, the value of the components does not update when bound variable's value is changed.

 * igniteui-angular version: ~17.1.0
 * browser: all

## Steps to reproduce  
Use code like this:
```html
<igx-switch [value]="checked" (change)="switchChange($event)">My switch</igx-switch>
<igx-checkbox [value]="checked" (change)="checkboxChange($event)">Not update on property update</igx-checkbox>
```
In `switchChange` and in `checkboxChange` events I am setting the value of the variable like this:
```ts
public checked: boolean | undefined = true;
...
switchChange = (e: IChangeCheckboxEventArgs) => this.checked = e.checked;
checkboxChange = (e: IChangeCheckboxEventArgs) => this.checked = e.checked;
```

## Result  
Both components does not render initial bound variable value. Also. when the value of the bound variable is changed the value of the component does not reflect the change.

## Expected result  
Component should show the value of the bound variable.

**Comment by simeonoff** [comment]
The issue reads as if you want to use the `checked` property of the components. Closing for now.
