### ISSUE TITLE
Radio group does not update bound variable on blur

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#14134]
## Description  
I have a radio group bound trough `ngModel` to a variable. `ngModelOptions` in my sample hase `updateOn: blur`.

 * igniteui-angular version: ~17.1.0
 * browser: all

## Steps to reproduce  
Use code like this:
```html
<igx-radio-group [(ngModel)]="radioGroupValue" [ngModelOptions]="{updateOn: 'blur'}">
    <igx-radio value="1">First</igx-radio>
    <igx-radio value="2">Second</igx-radio>
    <igx-radio value="3">Third</igx-radio>
</igx-radio-group>
<p>Radio group value is: {{radioGroupValue}}</p>
```

## Result  
Clicking on the radios and then blur the component does not update the bound variable.

## Expected result  
Bound variable should be updated on radio group blur.

**Comment by simeonoff** [comment]
I don't there's an issue in how to Radio group handles ngModel value updates when the `updateOn: 'blur'` option is set. In fact, it behaves exactly the same as a bunch of native radio buttons bound to the same ngModel (see the attached clips). For that reason I'm closing this issue. In case you fill the behavior should be different, please comment below and/or reopen the issue.

Native:


https://github.com/IgniteUI/igniteui-angular/assets/4118303/cb612258-32e8-4edc-8704-d30a92c185d4


Ignite UI for Angular:


https://github.com/IgniteUI/igniteui-angular/assets/4118303/42ef1385-a985-4479-b174-001292362ca9
