### ISSUE TITLE
Calendar does not update bound variable whit update on blur

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#14132]
## Description  
I have a calendar bound to a date via `ngModel`. I also set `ngModelOptions` with `updateOn: blur`.

 * igniteui-angular version: ~17.0.1
 * browser: all

## Steps to reproduce  
Setup calendar like this"
```html
<igx-calendar [(ngModel)]="date" [ngModelOptions]="{updateOn: 'blur'}"></igx-calendar>
```
Select a date in the calendar and blur the component.

## Result  
Bound variable, `date` in this case is not updated.

## Expected result  
Bound variable should be updated.

**Comment by ChronosSF** [comment]
@wnvko , does this reproduce in master with the new calendar?

**Comment by wnvko** [comment]
@StefanIvanov yes, it is reproducing there.
