### ISSUE TITLE
Operations UI Implementation

### ISSUE THREAD

**Issue by DDavidkov** [IgniteUI/igniteui-angular#1413]
Research and implement Grid Operations UI.

Initial spec: https://github.com/IgniteUI/igniteui-angular/wiki/Operations-UI

**Comment by sbozalieva** [comment]
![opui](https://user-images.githubusercontent.com/23053821/41041967-27caec7e-69a9-11e8-922f-083693c74075.png)

**Comment by sbozalieva** [comment]
Pin/
![base copy 31](https://user-images.githubusercontent.com/23053821/41044620-55c0131a-69af-11e8-822a-f06eea2d13fe.png)
![base copy 33](https://user-images.githubusercontent.com/23053821/41044621-55ec88c8-69af-11e8-94be-5362e55769f0.png)

Unpin
