### ISSUE TITLE
npm install is failing

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#14148]
* igniteui-angular version: n/a
 * browser: n/a

## Steps to reproduce  

1. Make sure to be at the tip of `master`
1. Run `npm i`
2. Observe

## Result  
The following error is thrown:
![image](https://github.com/IgniteUI/igniteui-angular/assets/16020256/2efaef0b-ca91-49d7-8730-ce4468d4b98c)

## Expected result  
No errors should be thrown and the command shuld run normally.

## Remarks
Judging by the error, this seems to be caused by `puppeteer` which attempts to set up Chrome but fails due to certificate verification issues. This may be something internal but I'm still logging it so it's visible.

PS - setting `--ignore-scripts` allows the install to continue normally, but this is more of a workaround than an actual fix.

**Comment by kdinev** [comment]
@jackofdiamond5 I just tried it and the install went through. Could have been a temporary issue?

**Comment by jackofdiamond5** [comment]
> @jackofdiamond5 I just tried it and the install went through. Could have been a temporary issue? What node version are you using?

Yeah, it works fine now, apparently it was related to this problem here - [ESET](https://forum.eset.com/topic/40702-eset-ssl-protection-produces-an-invalid-certificate-chain-for-nodejs-apps/) which must've been resolved internally.
