### ISSUE TITLE
igxToggle: setOffset function increments the offset instead of setting a specific value

### ISSUE THREAD

**Issue by gmartinezig** [IgniteUI/igniteui-angular#14174]
## Description  
setOffset function increments the current offset value instead of setting a specific value

 * igniteui-angular version: ^17.0.0
 * browser: All

## Steps to reproduce  

1. Go to the following sample:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/toggle#offsetting-the-toggle-container
2. Click the TOGGLE button several times

## Result  
![offsetting-the-toggle-container-bug](https://github.com/IgniteUI/igniteui-angular/assets/12627640/3846010f-cc97-4b8e-85b8-279f3cbbc740)

## Expected result  
The toggle popup should be always offset 30px from the target element

**Comment by georgianastasov** [comment]
### Suggested Improvement For Feature
After discussing with @wnvko, we identified that this behavior could be modified to better suit different use cases. Specifically, there are two main approaches to the `setOffset` function:

- **Relative Positioning**: The current implementation where the offset is applied relative to the current position.
- **Absolute Positioning**: A new implementation where the offset is set to an absolute value relative to the target element.

Both approaches are valid and have their own applications. To accommodate both use cases and avoid a breaking change, we propose introducing a third parameter to the `setOffset` method. This parameter would allow clients to choose the desired positioning behavior.
