### ISSUE TITLE
Data grid filtering:Programatic filtering on data-grid does not reflect selection in filter dialog

### ISSUE THREAD

**Issue by vpoharkar** [IgniteUI/igniteui-angular#14188]
## Description 
When data filtered programatically with [Data-grid-excel-style-filtering](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering) although the actual filtering operation performs as expected, however the filter representation/selection in filter dialog is absent 

 * igniteui-angular version: "^17.0.11"
 * browser: Edge

## Steps to reproduce  
Here is stackblitz where the issue can be reproducible: [stackblitz](https://stackblitz.com/edit/zkcdsk?file=src%2Findex.html)

1. Step 1: Click any link displayed in first column of the grid => '**ProductName**'. This should filter the grid by whichever value the user clicked on.
2. Step 2: The filtering indicator(dots) for the productName column will be highlighted to indicate that this column has same filter present.
3. Step 3: Click on the indicated filter to check if the dialog reflects the applied filtered condition.

## Result  
Once the filter dialog is opened although the actual filtering operation performs as expected however there is no indication/selection in the filter dialog to indicate that a programatic filter was applied to the grid

## Expected result  
There should be some indication/selection in the filter dialog that displays that a filter was applied to this grid programatically.

## Attachments  
Expected"
![image](https://github.com/IgniteUI/igniteui-angular/assets/25928165/c5025889-2aeb-4a4a-90fc-9f52c6158366)

Result:
![image](https://github.com/IgniteUI/igniteui-angular/assets/25928165/998cb56a-6e22-4acc-a30c-40eca33dcbbf)

**Comment by hanastasov** [comment]
Excel Style Filtering is meant to work with a strict comparison filter ("equals"), instead of "contains" one. When you select an item in the ESF list, the actual operation performed is filtering by "equals", not "contains".

So, if you would like your custom filter to be "respected" by the ESF, use "equals" instead:

```typescript
    public filterByval(val: string): void {
        this.grid2.filter(
        'CompanyName',
        val,
        IgxStringFilteringOperand.instance().condition('equals'),
        true
        );
    }
```

**Comment by kdinev** [comment]
@hanastasov I think that it would still be good if the `text filter` indicates there's a text filter applied:
![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/c6c14fee-ffca-43c5-a2c7-379881f65263)

**Comment by hanastasov** [comment]
Story - user chooses a filtering condition, e.g. Contains, and applies some filter. User gets back to this UI:

![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/15a87d9d-2114-4711-b7a6-aba252c00753)

@sdimchevski shall both the Text Filter item and the corresponding filter item in the dropdown menu be highlighted and if so, please provide the correct styles.

**Comment by damyanpetev** [comment]
The UI reflects some for the provided scenario, except it falls under the text filter category and the indication that's the case isn't really there. From the Result image these are the indications _some_ filtering is active:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/1ca9fab4-c049-4a19-bfb7-7070dd5f1178)
Certainly not clear what is active. For comparison the same scenario in Excel:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/f3621956-4e87-4c42-9747-9508583aecd1)
Also a secondary open of the Contains option the dialog doesn't reflect the active filter:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/db4908f4-2f61-48f5-b94d-d0a52d9e54d8)
Again against the same state in Excel:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/bf53eced-4351-4fc2-b0f1-11abc2b98a40)

**Comment by kdinev** [comment]
@hanastasov I also want to add the story with advanced filtering not applying any visual states to the grid - neither in the advanced filtering prompt (button), nor in any of the columns that have been filtered.

**Comment by sdimchevski** [comment]
@hanastasov Why don't we do something like this and use the active state of the Text Filter list item and the selected state for the dropdown menu items (filter items)
<img width="774" alt="Screenshot 2024-06-04 at 13 35 23" src="https://github.com/IgniteUI/igniteui-angular/assets/15327632/c300ff68-db92-4013-a57a-fc078fd4933a">


Also this dialog should reflect the active filter 

<img width="839" alt="Screenshot 2024-06-04 at 13 33 18" src="https://github.com/IgniteUI/igniteui-angular/assets/15327632/ff007c49-dc9b-4e66-9a4b-66ed2fdef4b2">

**Comment by sdimchevski** [comment]
@kdinev for the advanced filtering we can also color the icon in the grid column and add a number to the prompt (button) showing how many columns are being filtered

<img width="979" alt="Screenshot 2024-06-05 at 16 16 15" src="https://github.com/IgniteUI/igniteui-angular/assets/15327632/5f4560cb-020e-4271-95dc-a7c03b00a2d5">

**Comment by kdinev** [comment]
> @hanastasov Why don't we do something like this and use the active state of the Text Filter list item and the selected state for the dropdown menu items (filter items) <img alt="Screenshot 2024-06-04 at 13 35 23" width="774" src="https://private-user-images.githubusercontent.com/15327632/336414869-c300ff68-db92-4013-a57a-fc078fd4933a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjAzNDcsIm5iZiI6MTcxNzY2MDA0NywicGF0aCI6Ii8xNTMyNzYzMi8zMzY0MTQ4NjktYzMwMGZmNjgtZGI5Mi00MDEzLWE1N2EtZmMwNzhmZDQ5MzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA3NDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTk1YjQ4MzRmYTg1ZjgzMDhiNzI1ZjAyZjQ2NjZmODk5MjNkMjczMTVkNGE2Nzg3YzFlZTU1YTY1NWIyODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PUPZYGLB4krC1xgHKUKGw9uiEA2SbdW_AtUSbw-3q2g">
> 
> Also this dialog should reflect the active filter
> 
> <img alt="Screenshot 2024-06-04 at 13 33 18" width="839" src="https://private-user-images.githubusercontent.com/15327632/336414338-ff007c49-dc9b-4e66-9a4b-66ed2fdef4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjAzNDcsIm5iZiI6MTcxNzY2MDA0NywicGF0aCI6Ii8xNTMyNzYzMi8zMzY0MTQzMzgtZmYwMDdjNDktZGM5Yi00ZTY2LTlhNGItNjZlZDJmZGVmNGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA3NDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MDRjN2NmOGJjOGU1N2RiMjBmNzUwNzNmMjY2OGY5MGE0ZTIxMDY3YzM5OWVhYzg2MDdkYWYzMjQyNTc2YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nv0syu4cG_kEDNcRePqME7Oe2vqGlcmoCsgiW2tOOKI">

Also, the prompt (list item) for the text filter should somehow indicate there's one applied before you click on it to see a condition highlighted.

**Comment by sdimchevski** [comment]
@kdinev for the Text Filter list item we can apply the same logic and add a number to show how many filter items are selected

<img width="825" alt="Screenshot 2024-06-06 at 14 16 14" src="https://github.com/IgniteUI/igniteui-angular/assets/15327632/eb4cce7a-7a85-4bf7-b848-0f79895816f8">

**Comment by deyvidnenchev** [comment]
> @kdinev for the Text Filter list item we can apply the same logic and add a number to show how many filter items are selected
> 
> <img alt="Screenshot 2024-06-06 at 14 16 14" width="825" src="https://private-user-images.githubusercontent.com/15327632/337241897-eb4cce7a-7a85-4bf7-b848-0f79895816f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTc2OTMsIm5iZiI6MTcxODE5NzM5MywicGF0aCI6Ii8xNTMyNzYzMi8zMzcyNDE4OTctZWI0Y2NlN2EtN2E4NS00YmY3LWI4NDgtMGY3OTg5NTgxNmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzMDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MTE0NzVjYzhjOGMwNTQwZDBlMTg1ZGYwNTZkNTE1MzdkMThhZmU4MzZkYTBjZjE2MWZmZmMzYzM0ZDRlNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJ3oClJ_qSZNsZeGwJ9u10yWJVTh3eNXMsvHaGzA704">

@kdinev Currently on the development branch of this issue https://github.com/IgniteUI/igniteui-angular/pull/14328 if we add excel style filter through the dropdown and then add another one via the dropdown the first one is overridden. If we add two or more filters via Custom auto-filter the custom filter will be highlighted in the dropdown and the two or more added filters will be only visible in Custom auto-filter dialog if we click on Custom Filter in the dropdown. If we click on any other filter type the initial Custom auto-filter will be shown. This behavior is not in accordance with the comment I quoted and is not mentioned anywhere in the specifications.

**Comment by hanastasov** [comment]
> > @kdinev for the Text Filter list item we can apply the same logic and add a number to show how many filter items are selected
> > <img alt="Screenshot 2024-06-06 at 14 16 14" width="825" src="https://private-user-images.githubusercontent.com/15327632/337241897-eb4cce7a-7a85-4bf7-b848-0f79895816f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTc2OTMsIm5iZiI6MTcxODE5NzM5MywicGF0aCI6Ii8xNTMyNzYzMi8zMzcyNDE4OTctZWI0Y2NlN2EtN2E4NS00YmY3LWI4NDgtMGY3OTg5NTgxNmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzMDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MTE0NzVjYzhjOGMwNTQwZDBlMTg1ZGYwNTZkNTE1MzdkMThhZmU4MzZkYTBjZjE2MWZmZmMzYzM0ZDRlNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJ3oClJ_qSZNsZeGwJ9u10yWJVTh3eNXMsvHaGzA704">
> 
> @kdinev @hanastasov Currently on the development branch of this issue #14328 if we add excel style filter through the dropdown and then add another one via the dropdown the first one is overridden. If we add two or more filters via Custom auto-filter dialog the custom filter option will be highlighted in the dropdown and the two or more added filters will be only visible in Custom auto-filter dialog when we click on Custom Filter in the dropdown. If we click on any other filter type in the dropdown the initial Custom auto-filter dialog will be shown. This behavior is not in accordance with the comment I quoted and is not mentioned anywhere in the specifications.

I agree with Deyvid. The behavior he describes (it is like that from beginning) is that choosing A filter Condition from the fly out menu **overrides the existing condition**. This is the default in Excel, too.

If a user wants to add more than one filter conditon ,he is expected to do this in the dialog, where **Add filter action** is available:

![image](https://github.com/IgniteUI/igniteui-angular/assets/14248932/0547183e-04ad-4325-8a85-77134a8337b4)

Let's have the dialog height bigger of course, to see the whole button.
