### ISSUE TITLE
Simple Combo misses the first input when filtering after being focused

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-angular#14195]
## Description  

Simple Combo misses the first input when filtering after being focused.

## Steps to reproduce  

I can reproduce this on your example by selecting "3M" then "Shift+Tab" back to the Simple combo and typing "W"

https://www.infragistics.com/products/ignite-ui-angular/angular/components/simple-combo#angular-simple-combobox-example

![image](https://github.com/IgniteUI/igniteui-angular/assets/759253/a7f95e79-e3ba-4f83-9021-f7295ca77abe)

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  

I would expect it to filter correctly 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by georgianastasov** [comment]
Hello @ricardosaracino,

Thank you for reporting this issue. It seems that the problem you've encountered with the Simple ComboBox is overlapping with a previously reported issue. The issue you've described aligns closely with the one reported earlier, and here is the link to the previous report for your reference: [Issue #14187](https://github.com/IgniteUI/igniteui-angular/issues/14187).

Given the similarities between the two issues, it appears that they are likely manifestations of the same underlying behavior. I've made note of this in our records to ensure proper tracking and resolution.

If you have any additional information or insights to add, please feel free to share them in the other issue.
