### ISSUE TITLE
Clearing Simple Combo with input does not trigger selectionChanging

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-angular#14200]
## Description  

After having a valid selection i can re-enter the input and then press a character "d" and then click outside of the input. That will clear the input and mark it as invalid.  This does NOT fire a `(selectionChanging)` as i would expect it to.

I would also find it acceptable to return the original selected text to the input, but just having it invalid without an event is confusing 

** EDIT I think a better user experience would be to return the original text instead of clearing it and making it invalid. The user could then manually clear the input with the `X` 

![image](https://github.com/IgniteUI/igniteui-angular/assets/759253/550bd88b-6898-4882-a9ed-30bae05a1d11)

Click outside of input

![image](https://github.com/IgniteUI/igniteui-angular/assets/759253/382f53c0-bf2f-4484-8ddc-f87bb4213dc5)

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  

Invalid form without a selection changing event

## Expected result  

I would expect the same selectionChanging event as when you `close()`

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by georgianastasov** [comment]
Hello @ricardosaracino,

Thanks for pointing this out!

We've decided that in the upcoming fix, we will ensure that when you input a character and click outside the input, the `selectionChanging()` event will trigger as expected. However, we won't be restoring the original text to the input field.
