### ISSUE TITLE
[Elements]: autoGenerate does not override columns declared in markup

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-angular#14260]
## Description  
When set to `true`, the `autoGenerate` property in `igniteui-angular` overrides all columns declared through code or in markup as stated in the [API docs](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#autoGenerate).
When used in WebComponents/React/Blazor the declared columns persist.

 * "igniteui-webcomponents-grids": "4.8.0",
 * "igniteui-react-grids": "18.6.0",
 * "IgniteUI.Blazor": "23.2.223"

## Steps to reproduce  

1. Define a grid that has autoGenerate set to true.
2. Define a column in the markup.

```html
<igc-grid auto-generate="true" id="grid">
    <igc-column field="ID"></igc-column>
</igc-grid>
```
```ts
private data: any[] = [
    { ID: 1, Product: "Chai", Category: "Beverages" },
    { ID: 2, Product: "Chang", Category: "Food" },
    { ID: 3, Product: "Tofu", Category: "Food" }
];

constructor() {
    const grid = document.getElementById("grid") as IgcGridComponent;
    grid.data = this.data;
}
```

## Result  
Only the defined `ID` column is rendered.

## Expected result  
The columns should be generated based on the provided data, i.e., three columns (`ID`, `Product`, `Category`) should be rendered.

**Comment by ddaribo** [comment]
Closing - ref to [this](https://github.com/IgniteUI/igniteui-angular/pull/14590#issuecomment-2255246859) and [this](https://github.com/IgniteUI/igniteui-angular/pull/14590#issuecomment-2288491438) comments.
