### ISSUE TITLE
Grid rows do not update when parent container has 'display: contents' and resizing the window up.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#14278]
## Description  
When the parent container of the grid has `display: contents` and the user has scrolled to the furthest right position and resizes the window to be larger, the rows do not update for the new size and scroll position correctly. 

When display is set to `block`, this does not happen.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open the grid auto size demo.
2. Resize the window down.
3. Set display to contents using the button.
4. Set any data.
5. Scroll to the furthest right position.
6. Resize the window up

## Result  
The rows and headers are misaligned.

## Expected result  
The rows should be aligned to the headers and scrollbar position.

## Attachments  
![grid_resize_scroll2](https://github.com/IgniteUI/igniteui-angular/assets/3768136/a438f52f-ab5e-42cf-9f2a-1539f0491f34)

**Comment by MayaKirova** [comment]
@dkamburov We should retest this after the display density and resizer changes in master.
