### ISSUE TITLE
Incorrect hover behavior in splitter (vertical orientation)

### ISSUE THREAD

**Issue by andiesm813** [IgniteUI/igniteui-angular#14276]
## Description  
In the Indigo UI Theme, the vertical splitter remains "grown" (possibly its focus state) even though i'm clicking elsewhere. This doesnt happen in the horizontal splitter, only in vertical.

I'm attaching a video for easier explanation.

## Expected result  
The vertical splitter should go back to its original size (before being clicked and dragged) just like the horizontal does.

## Attachments  

https://github.com/IgniteUI/igniteui-angular/assets/86068582/4667751e-ee9e-4785-a1da-8b95b8dabf04

**Comment by georgianastasov** [comment]
Hello @andiesm813,

Could you please check if you can still reproduce the issue with the vertical splitter in the Indigo UI Theme? I've tried to reproduce it on my end but haven't been successful so far. It's possible that this issue has been addressed in one of the recent PRs.

If you can still reproduce it, could you provide more details or steps to replicate? Alternatively, if it's no longer occurring, we can assume it has been fixed.
