### ISSUE TITLE
Remote Virtualization support for Sorting and Filtering

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#1428]
### Description  
Not sure if this is a documentation issue, sample issue, grid issue, or a feature request. 
Although by looking at the limited properties in the IForOfState interface I am leaning towards feature request, because it is only passing in the information for index and chunksize. Which is insufficient to support sorting and filtering. 

### Steps to reproduce  
Open the sample here in StackBlitz: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html#grid-remote-virtualization-demo
Set a column to filterable or sortable
Run the sample and Apply a Sort

### Result  
Only Filters\Sorts what is already on the page

### Expected result  
Should return filtered\sorted data from the remote call. 
An extension of the expected results would be that it builds the oData queryString automatically from the state of the grid, and not expect the developer to do it, but allow the developer to do it if they desire to, similar to IgniteUI for javaScript. 
https://www.igniteui.com/help/handling-remote-features-manually

**Comment by MayaKirova** [comment]
@MikeTechSpeak All remote operations should be implemented in a service that queries the remote data.
The igxGrid does not directly query the backend, so it’s up to the developer to build a service that handles the requests/responses to/from the backend based on the current state of that grid ( virtualization state, the  grid’s sortingExpressions/filteringExpressions etc.) on the related events (onDataPreLoad, onFilteringDone, onSortingDone etc.).

There are plans to update the remote sample to show an example implementation for such a service:  https://github.com/IgniteUI/igniteui-angular-samples/issues/272
There is already a pending PR you can refer to as a point of reference.

Let me know if you have any additional questions.

**Comment by MikeTechSpeak** [comment]
I am just thinking considering all the different permutations of properties that can affect the data grab. Having us auto generate an oData query string like we do for the igGrid would be a very useful functionality to provide our users.

**Comment by ChronosSF** [comment]
As we didn't agree internally on the need to develop out-of-the-box solution I am closing this.
