### ISSUE TITLE
Change takeUntil import path causing duplicated import in bunded igniteui-angular.mjs

### ISSUE THREAD

**Issue by dobromirts** [IgniteUI/igniteui-angular#14281]
## Description  
Duplicated import for 'takeUntil' rxjs operator is generated in igniteui-angular.mjs file , causing compile errors for applications with rxjs version lower than 7.

![image](https://github.com/IgniteUI/igniteui-angular/assets/46093564/b50d3f51-eaa3-4ed4-8da6-3744ab3e8411)

Describe the issue.

 * igniteui-angular version: 18.0.0-alpha
 * browser: all

## Steps to reproduce  

1. Update igniteui-angular to 18.0.0-alpha.3 in project that has rxjs version lower than 7 .eg. "rxjs": "^6.6.7",
2. Start the application

## Result  
Error is thrown for export 'takeUntil' (imported as 'takeUntil$1') was not found in 'rxjs'

## Expected result  
Ensure the application compiles successfully by preventing errors and avoiding duplicate imports.

**Comment by mddifilippo89** [comment]
I found this when updating the angular dv browser today
https://github.com/IgniteUI/igniteui-angular-examples/issues/195
