### ISSUE TITLE
[Elements] Grid state persistence does not properly restore column features 

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#14284]
## Description  
After investigating [this issue](https://github.com/IgniteUI/igniteui-xplat-examples/issues/611), it was determined that the column features state is not properly restored on the Elements grids (Flat, Tree, Hierarchical, Pivot). Moreover, this is only *consistently* observed when restoring the state within the embedded samples in the documentation page, for example:

![wc-grid-state-issue-demo](https://github.com/IgniteUI/igniteui-angular/assets/35433937/436c56fb-0c31-4307-aea8-de0c96b7d7de)

This is the case on initial loading - the sample is configured to restore the state on the windows's `load` event, which fires as expected. 
When clicking the "Restore" button, the grid being all rendered, the columns' state is restored as expected.

On the other hand, opening the same sample in a separate window and performing the same steps results in successfully restoring the columns state. Although this is rather inconsistent - on several occasions the behavior is reproduced there as well. 
Possibly some timing issue, where the grid columns are reinitialized under certain conditions after the state had been restored, thus overriding it.

I have not been able to isolate this behavior for the `IgxGrid`, so it is to be investigated whether this is related to the Elements grids only and how they are initialized, or is coming from the `IgxGrid` and is reproducible under certain specific conditions?

 * igniteui-angular version: *
 * browser: any

## Steps to reproduce  

1. Make changes to the columns - hide, pin, etc.
2. Click "Save"
3. Click "Leave"/ Reload the page
4. Click "Go Back"
5. Columns are restored to initial settings. Features like filtering or selection are properly restored.

## Result  
Described above.

## Expected result  
Properly restore everything on initialization.

**Comment by MayaKirova** [comment]
@ddaribo Doesn't seem to be a product issue. It's just that the window's `load` event that the sample uses fires before the grid is fully initialized with all of its pre-defined columns from the DOM. So the state applies, but then the columns from the actual declaration in the DOM overwrite it once the grid fully loads.
It could be fixed in the sample by waiting for all columns to initialize before applying the state.
