### ISSUE TITLE
Tiny mistake in the documentation of the Switch & Checkbox

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1429]
### Description  
There is an error in the documentation
`checked="true"` should be `[checked]="true"`.

### Steps to reproduce  (for the Switch, the Checkbox is about the same)

1. Goto [Infragistics Switch](https://www.infragistics.com/products/ignite-ui-angular/angular/components/switch.html) or [Infragistics Checkbox](https://www.infragistics.com/products/ignite-ui-angular/angular/components/checkbox.html)
2. Follow the code of the simple switch/checkbox

### Result  
The switch/checkbox is always true (default).

### Expected result  
A switch/checkbox that is able to be false.

### Solution
Currently:
```
<igx-switch checked="true">
    Simple switch
</igx-switch>
```
```
<igx-checkbox checked="true">
    simple checkbox
</igx-checkbox>
```

Should be (usage of [ ] around the property `checked`)

```
<igx-switch [checked]="true">
    Simple switch
</igx-switch>
```
```
<igx-checkbox [checked]="true">
    simple checkbox
</igx-checkbox>
```

**Comment by zdrawku** [comment]
Moving the issue to the relevant repository, you can track the progress of it [here] (https://github.com/IgniteUI/igniteui-docfx/issues/426).

Thank you!
