### ISSUE TITLE
Default Chip Size in Pivot/GroupBy increased because the icons inside increased

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#14312]
## Description  
It seems that chips used in the grid (probably not just there) are bigger by default because their icons expand them.

 * igniteui-angular version: 18.0.0-rc.0
 * browser: 

Open any of the Pivot/Groupby samples that have chips.

![Screenshot 2024-06-03 143350](https://github.com/IgniteUI/igniteui-angular/assets/2188411/f71da55e-76db-406a-93bd-56fff841faf8)

**Comment by simeonoff** [comment]
Ok, closing as I can't reproduce. I compared the chip height in 17.1.x in the context of the pivot grid and here are the findings:

Large - 32px
Medium - 24px
Small - 20px

In 18.0, again, in the context of the pivot grid, the height of the chip is:

Large - 32px
Medium - 24px
Small - 20px
