### ISSUE TITLE
igx-grid: CSS Variable (--ig-size) Not Applied When Nested in igx-tabs

### ISSUE THREAD

**Issue by Zneeky** [IgniteUI/igniteui-angular#14338]
## Description  
When nesting igx-grid within igx-tabs, the CSS variable --ig-size is not being applied correctly. Despite defining and attempting to apply the variable through various methods (::ng-deep, direct application in the component), the styling does not affect the igx-grid element within tabs as expected.

 * igniteui-angular version:  17.0.0
 * browser: all

## Steps to reproduce  
1. Nest an igx-grid within an igx-tabs component.
2. Apply the style --ig-size: var(--ig-size-small) directly to the igx-grid via the style attribute.
`<igx-grid #grid [data]="data" style="--ig-size: var(--ig-size-small)">
</igx-grid>`
3. Observe that the CSS variable styling is applied only to the header of the igx-grid and not to other parts of the grid.

## Result  
After following the steps to reproduce, the CSS variable --ig-size is observed to be applied only to the header of the igx-grid. 

## Expected result  
The expected behavior is for the CSS variable --ig-size to be applied uniformly across the parts of the igx-grid, including headers and rows.

## Attachments  
Screenshots:
![image](https://github.com/IgniteUI/igniteui-angular/assets/105818882/ccab60e4-a510-4177-b4d6-e3b07be8bc34)

Sample:
[View Sample ](https://stackblitz.com/edit/3g7m4e?file=src%2Fapp%2Fgrid%2Fgrid-rowClasses-sample%2Fgrid-rowClasses.component.html)

**Comment by mddragnev** [comment]
Hello @Zneeky,
The above mentioned issue is already fixed in the newly released 18.0.0 version of the igniteui-angular.
I am closing the issue as fixed but feel free to reopen it if you have any additional questions
