### ISSUE TITLE
onFilteringDone is not triggered when "Reset" button is clicked or the textbox is cleared (either with keyboard or with X button)

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#1434]
### Description  
Describe the issue.

### Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-4xovq7
2. Filter by column -> "Filtering Done" message appears
3. Click on the Reset button (or click on the X button of the text box)

### Result  
No message appears

### Expected result  
Message should appear to indicate that the onFilteringDone event is triggered

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Aleksandyr** [comment]
@mpavlinov As I saw in the [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html#outputs) it is said that the event is emitting only when the filtering is performed. Also in the [wiki](https://github.com/IgniteUI/igniteui-angular/wiki/igxGrid-Specification#outputs) section the description is similar. So in my opinion the event is fired correctly, only when you have added some value into the input or you have changed the condition value.

**Comment by zdrawku** [comment]
To be honest clear/reset of the filter is a "filtering" action, so we can consider to add emitting of **onFilteringDone** on clear/reset filter as well.
