### ISSUE TITLE
[IE] Errors thrown when opening any IgxGrid

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#1436]
### Description  
A JS errors are thrown when using any IgxGrid under IE.
The error is:
ERROR TypeError: Object doesn't support property or method 'forEach'

### Steps to reproduce  

1. Navigate to any IgxGrid sample on the staging, for [example](https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid.html)

2. Look at the browser console.

### Result  
JS errors are thrown.

### Expected result  
JS errors should not be thrown.

### Attachments  
![image](https://user-images.githubusercontent.com/11978058/40720852-bb88bd80-6420-11e8-849b-579ae41dd0bb.png)

# Findings:

The issue started to appear after upgrading of the angular-cli version.

There is a recommendation how to load polyfills correctly:
https://github.com/angular/angular-cli/issues/6577
Possible Fix: https://github.com/angular/angular/pull/16805/files

**Comment by Aleksandyr** [comment]
@zdrawku I couldn't reproduce the issue.

**Comment by Aleksandyr** [comment]
@zdrawku This is happened when you filter by some column and then clear the filtering the errors appear.

**Comment by bkulov** [comment]
The issue is the same as #1531.
The problem is that NodeList used in text-highlight.directive.ts doesn't support forEach in IE and doesn't have polyfill.
