### ISSUE TITLE
Need property on igx-badge to make it square

### ISSUE THREAD

**Issue by kdawg1406** [IgniteUI/igniteui-angular#1446]
Need property to control the shape or border-radius on the inner div so we can make badge square.

I see this generated CSS setting border-radius so it's always round.  Need to be able to make it square: border-radius: 0;

.igx-badge__circle {
    border-radius: 11px;
    border: 0 solid #fff;
    box-shadow: none;
    overflow: hidden;
}

**Comment by SlavUI** [comment]
@zdrawku  How much time will you guys need to make this possible
 :)

**Comment by zdrawku** [comment]
@SlavUI considering the current work load, at least 2 days.

**Comment by SDinev** [comment]
Consider a resolution through issue #1393

**Comment by zdrawku** [comment]
@SDinev referenced the issue that will cover this requirement
