### ISSUE TITLE
Select Bootstrap theme start border doesn't match

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#14472]
## Description  
Select Bootstrap theme start border doesn't match anymore - it's flat and doubled in thickness.

 * igniteui-angular version: 18.0.x
 * browser: N/A

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid
2. Change the theme to Bootstrap
5. Observe the paginator select

## Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/0f0ceb1d-e8e2-4af9-a4d0-93409aa22dfe)

## Expected result  
Start border should match the end one. 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
Actually similar thing happens for Fluent as well:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/56856963-2dd8-4b8f-8bf6-9a825bece848)

**Comment by simeonoff** [comment]
@dkamburov I believe there's something wrong when generating the themes for the documentation of Ignite UI for Angular. Choosing bootstrap there doesn't seem to update the schema files, or it may be that the generated themes are for an older version of angular?

**Comment by dkamburov** [comment]
@simeonoff seems like the theming service was deployed with 18.0.0 version of Ignite UI for Angular. Should we use newer?

**Comment by simeonoff** [comment]
> @simeonoff seems like the theming service was deployed with 18.0.0 version of Ignite UI for Angular. Should we use newer?

Hm, then we should investigate why the issue occurs in the [documentation LOB Boston Marathon sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid#angular-data-grid-example) but not in the actual LOB Boston Marathon sample when tested manually against a build of Ignite UI for Angular from the 18.0.x branch.

**Comment by dkamburov** [comment]
> > @simeonoff seems like the theming service was deployed with 18.0.0 version of Ignite UI for Angular. Should we use newer?
> 
> Hm, then we should investigate why the issue occurs in the [documentation LOB Boston Marathon sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid#angular-data-grid-example) but not in the actual LOB Boston Marathon sample when tested manually against a build of Ignite UI for Angular from the 18.0.x branch.

It still might be an issue with the TaaS

**Comment by dkamburov** [comment]
> > > > @simeonoff seems like the theming service was deployed with 18.0.0 version of Ignite UI for Angular. Should we use newer?
> > > 
> > > 
> > > Hm, then we should investigate why the issue occurs in the [documentation LOB Boston Marathon sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid#angular-data-grid-example) but not in the actual LOB Boston Marathon sample when tested manually against a build of Ignite UI for Angular from the 18.0.x branch.
> > 
> > 
> > It still might be an issue with the TaaS
> 
> Can you investigate, please?

Yeah, sure.
