### ISSUE TITLE
Need a theme SASS function for the button to allow setting or removing elevations from the button.

### ISSUE THREAD

**Issue by kdawg1406** [IgniteUI/igniteui-angular#1447]
The Nebula UI Kit allows designers to change the default Elevation for a button.

Need a theme SASS function for the button to allow setting or removing elevations from the button.

**Comment by SlavUI** [comment]
@kdawg1406 I'm closing this one, reopen if needed

**Comment by kdawg1406** [comment]
@kdinev why is this being closed?

@SDinev @StefanIvanov  don't we need this?

**Comment by SlavUI** [comment]
@kdawg1406  i closed because after the comments from Konstantin you have not replayed or provided any comments. If there is still something to be done please update the issue.

**Comment by kdawg1406** [comment]
See the original issue, it still needs a solution.  

The comment only refers to how it works today, great we know how it works today, comment unnecessary because it does not address the issue.

**Comment by kdinev** [comment]
@kdawg1406 I think you're referring to some issue in the UI kit. The `igx-button` has type presets, and they define fixed elevations. This is by design.
