### ISSUE TITLE
Grid row selection flow improvement

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#14519]
## Question  
A grid with primary key and multiple selection. Select all rows, the following flow executes:

```typescript
// 1. Iterate all data and execute this.getRecordKey(row) >
selectAllRows > this.allData.filter((row) => !this.isRowSelected(this.getRecordKey(row))) >

// 2. Iterate the same data again and execute the same this.getRecordKey(r), this can be skipped, it produces the same result already available in newSelection
emitRowSelectionEvent > this.areAllRowSelected(newSelection.map(r => this.getRecordKey(r))) >
EDITED: During review, it proved that this point 2. is not correct, so a new point 2 is listed below:

// 2. Inside emitRowSelectionEvent, newSelection is mapped two times. Save the result of the mapping and reuse it.
emitRowSelectionEvent > newSelection.map(r => this.getRecordKey(r)

// 3. Again doing the same operation over the same dataset
areAllRowSelected >  const allData = this.getRowIDs(this.allData); > data.map(rec => rec[this.grid.primaryKey])  
```

Check if it is worth the effort to improve this flow. Check if the same is valid when selecting only a bunch of all items, not all items.

**Comment by georgianastasov** [comment]
# Performance Optimization for Select All Rows :chart_with_upwards_trend:

## Current Flow
The current implementation for selecting all rows in the grid involves multiple iterations over the same dataset:

1. Iterate all data to get record keys
2. Filter data to find unselected rows
3. Iterate again to get record keys for new selection
4. Additional iterations in `areAllRowSelected` method
5. More additional iterations in `areAllRowSelected` method

## Is it worth optimizing?

### Pros of optimization:
- Reduced time
- Improved performance, especially noticeable with large grids
- More efficient use of resources

### Cons of optimization:
- More complex
- Requires careful testing to ensure no regression

### Conclusion:
The optimization is worth the effort, especially:
1. The grid frequently deals with large datasets (1000+ rows)
2. The "Select All" operation is commonly used
3. The grid should have better performance

For smaller datasets, the current implementation may be sufficient. However, optimizing now could prevent future performance issues with grid with large datasets.
