### ISSUE TITLE
[Igx-snackbar]: Enhance the snackbar with an optional icon property

### ISSUE THREAD

**Issue by PlamenD95** [IgniteUI/igniteui-angular#14533]
## Is your feature request related to a problem? Please describe.
It would be beneficial to add easy support for `igx-icons` in a snackbar, by including an `iconName` property to the `igx-snackbar`.
In this way, developers would not need to manually add an `igx-icon` to the template of their Angular application.

## Describe the solution you'd like
An optional `iconName` property can be added to the `igx-snackbar`.
In the template of the snackbar, an `igx-icon` can be added which will be shown if there is an `iconName`, and based on the icon name it would show the corresponding `igx-icon`, e.g.:

![image](https://github.com/user-attachments/assets/69802da2-59bf-41a6-a1e8-a2761349c0cb)

## Describe alternatives you've considered
Alternatively, the developers themselves can manually add `igx-icons` to the templates where they use `igx-snackbar` in their Angular applications wherever it is necessary.

**Comment by hanastasov** [comment]
The library kind of tries to imply more declarative way of describing the component, i.e, instantiate the icon in the template, rather than through a property.

Closing with not to fix status.
