### ISSUE TITLE
Are there any built-in click events available for the igx-line-series?

### ISSUE THREAD

**Issue by Vighneshaa** [IgniteUI/igniteui-angular#14580]
I am using the data-chart inside which I have used the line Series.

<img width="421" alt="image" src="https://github.com/user-attachments/assets/c83b1af5-8c84-4eba-8394-946be97a9899">

**Comment by Vighneshaa** [comment]
Any updates here?

**Comment by ChronosSF** [comment]
@agoldenbaum , could you please take a look?
