### ISSUE TITLE
[Igx-navbar] The icon buttons' color doesn't match the title text color when changing to the material dark theme

### ISSUE THREAD

**Issue by PlamenD95** [IgniteUI/igniteui-angular#14599]
## Description  
When using the material dark theme, the color of the icon buttons doesn't match the black color of the title text for the navigation bar:

![image](https://github.com/user-attachments/assets/001d998b-71b5-4212-adac-90167f3eae38)

The correct color is properly assigned to the `igx-navbar` css class:

![image](https://github.com/user-attachments/assets/d12119b5-b4e9-4761-ad1a-b272b0f7262a)

However, it gets overwritten by the `igx-icon-button` class for the icon buttons:

![image](https://github.com/user-attachments/assets/5d8010cd-0af4-4d3d-96a1-dfaebd3b5aa0)

 * igniteui-angular version: 17.2.0
 * browser: Chrome 126.0.6478.185

## Steps to reproduce  

1. Add the `igx-navbar` component in an application
2. Use the material dark theme.

## Result  
There is a mismatch between the colors of the icon buttons and the title text of the navigation bar.
The icon buttons are white, while the title text is black,

## Expected result  
Both the icon buttons and the title text should be black.

**Comment by simeonoff** [comment]
@PlamenD95 17.2.0 is no longer supported, however, the issue is still (partially) reproducible in 18.1.0.

**Comment by sdimchevski** [comment]
I've discussed this issue with the Design team and we've worked on a solution. The problems that we have with the icon buttons in the Navbar are in Material and Indigo. What we propose is not to change the icon buttons in the context of the Navbar but change the Navbar styling instead. The changes are discussed with @simeonoff and @andiesm813 as well.

@kdinev To keep the icon buttons styling (flat, outlined and contained) intact, these are the changes that we want to make:

**Material**:

- The Navbar background color will be updated to primary 400 in Light mode and primary 800 in Dark mode
- The title color in Dark mode will be changed to white

<img width="800" alt="material-navbar" src="https://github.com/user-attachments/assets/be8780a0-12a4-4c1b-9c6e-96e3ae462725"><p></p>

**Indigo**:

- The Navbar background color will be updated to surface light in Light mode and surface dark in Dark mode
- The title color in Light mode will be changed to grays 800
- A bottom border will be added to the Navbar

<img width="787" alt="indigo-navbar" src="https://github.com/user-attachments/assets/4cb48bde-9424-4566-849b-6cd779f9a3f1"><p></p>

Here are a few design patterns, showcasing the applied changes in

**Material**

<img width="951" alt="Screenshot 2024-08-20 at 15 09 42" src="https://github.com/user-attachments/assets/41b50f6f-e5b5-484f-b539-02ffd508f244"><p></p>

**Indigo**

<img width="1052" alt="Screenshot 2024-08-20 at 15 11 50" src="https://github.com/user-attachments/assets/1c788beb-cef1-4ac7-9d60-9443605150cb">

**Comment by kdinev** [comment]
@sdimchevski Looks good to me!
