### ISSUE TITLE
[Igx-banner] Enhance the 'templateability' of the banner

### ISSUE THREAD

**Issue by PlamenD95** [IgniteUI/igniteui-angular#14606]
## Is your feature request related to a problem? Please describe.
According to the changelog and the wiki, the `IgxBannerComponent` was introduced with the idea to allow developers to display a highly templateable message:

![image](https://github.com/user-attachments/assets/bf9e74a5-397d-46f4-835a-5c6fe7372ecb)

![image](https://github.com/user-attachments/assets/c924537f-5434-402c-b1a2-9e3afd7f2dbb)

However, this is not easily achieved for `igx-icons` for certain use cases.

The `igx-banner` consists of an `igx-expansion-panel` and the text or icon content is projected in a `div` inside the `igx-expansion-panel-body`:

![image](https://github.com/user-attachments/assets/27cd1cc5-a725-45e5-960e-f47e193f239a)

In a use case where I wish to have a background color specific to the `igx-icon` which I use in the banner, this background color would be contained to the `div` in the `igx-expansion-panel-body`:

![image](https://github.com/user-attachments/assets/ad77f4f2-d351-4917-b410-f014940ff2d4)

In the example above, the first banner is a custom component consisting of two divs - one for the `igx-icon` and one for the text.
The styling of the background color is the desired one according to the use case.

The second banner is an `igx-banner` for which the div which contains the projected `igx-icon` is styled with a background color.
The background color fills only the div inside the `igx-expansion-panel-body` as it would be expected.

## Describe the solution you'd like
One way to achieve the desired styling could be to update the template of the `igx-banner` to allow projecting the `igx-icon` outside of the `igx-expansion-panel-body`.
This can allow the background color to fill the whole space at the head of the banner from top to bottom, instead of being contained to the `div` currently used for content projection inside the `igx-expansion-panel-body`

## Describe alternatives you've considered
The use of an `igx-expansion-panel` for the `igx-banner` is interesting.
Refactoring the whole `igx-banner` to not be based on an expansion panel can simplify the use of content projection, but it would be time consuming and it would possibly break other use cases which require the `igx-banner` to consist of an expansion panel.

**Comment by ddaribo** [comment]
@PlamenD95,
I have been looking into this request and before any changes in the component are discussed, it appears that the required look can be achived with a few CSS rules targeting the inner classes of the `igx-banner`.
[Here](https://stackblitz.com/edit/igx-banner-indigo-theme-app-builder-look?file=src%2Fapp%2Fbanner-sample-1%2Fbanner-samples.scss) is the sample I prepared. It uses the Indigo Light theme, which I believe matches the look from the screenshot.

[Here](https://codesandbox.io/p/sandbox/banner-styling-pcx3js?fontsize=14&hidenavigation=1&theme=dark&view=preview&workspaceId=a9af8cf6-ba46-4200-afb0-b7148c7da1b1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm02dlw340006356lu2js3qg4%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm02dlw340002356lcx29lxjg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm02dlw340003356lvhlwnaol%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm02dlw340005356lcnk401tl%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm02dlw340002356lcx29lxjg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm02dlw340001356lq78zojbj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm02efgtb0002356rpj5ctv0k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FBannerStyling.css%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm02dlw340002356lcx29lxjg%2522%252C%2522activeTabId%2522%253A%2522cm02efgtb0002356rpj5ctv0k%2522%257D%252C%2522cm02dlw340005356lcnk401tl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm02dlw340004356l11e1ixl1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm02dlw340005356lcnk401tl%2522%252C%2522activeTabId%2522%253A%2522cm02dlw340004356l11e1ixl1%2522%257D%252C%2522cm02dlw340003356lvhlwnaol%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm02dlw340003356lvhlwnaol%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is also an equivalent for the recently added Web Components `igc-banner`.

For both, the style rules are pretty much identical, apart from the selectors of course. It seems the Angular and WC’s banner layout is also quite similar, except the expansion panel part, still it does not seem to affect the final result.

![image](https://github.com/user-attachments/assets/4c44127e-9740-4823-8cf8-b3dcdf4d58e8)

**Comment by PlamenD95** [comment]
@ddaribo, thank you for the provided examples!

I've tested them out and they work for me.
