### ISSUE TITLE
Row height not respected in grid components

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#14605]
## Description  
The `rowHeight` parameter in the `igx-grid`, `igx-tree-grid`, and `igx-hierarchical-grid` components of Ignite UI for Angular is not functioning as expected in versions 18.0.0 and above. Despite setting the `rowHeight` property, the row height does not adjust accordingly, and there is no min-height property set on the respective grid cell elements.

_P.S: This issue does not occur in version 17.2.0 where everything works as expected._

 * igniteui-angular version: 18.0.0+
 * browser: All

## Steps to reproduce  

1. Set up an Angular application using Ignite UI for Angular version 18.0.0 or above.
2. Implement the `igx-grid`, `igx-tree-grid`, or `igx-hierarchical-grid` component and set the `rowHeight` property to a specific value.
3. Observe that the row height is not adjusted according to the specified value.

## Result  
The row height remains unchanged regardless of the `rowHeight` property value. There is no min-height property applied to the respective grid cell elements.

## Expected result  
The row height should adjust according to the specified `rowHeight` property value, as it did in previous versions (e.g., 17.2.0).

## Attachments  
Please refer to the provided sample links demonstrating the issue:

- [Version 17.2.0 Sample](https://stackblitz.com/edit/yvlztf-jfbzdx?file=src%2Fapp%2Fgrid%2Fgrid-column-hiding-toolbar-sample%2Fgrid-column-hiding-toolbar-sample.component.html)
- [Version 18.0.0 Sample](https://stackblitz.com/edit/yvlztf?file=src%2Fapp%2Fgrid%2Fgrid-column-hiding-toolbar-sample%2Fgrid-column-hiding-toolbar-sample.component.html)
- [Version 18.1.0 Sample](https://stackblitz.com/edit/yvlztf-dqfetp?file=src%2Fapp%2Fgrid%2Fgrid-column-hiding-toolbar-sample%2Fgrid-column-hiding-toolbar-sample.component.html)

**Comment by JJJanson73** [comment]
Hello guys,
are there any updates on this case?
We are using this feature in a production environment and it's important to get an easy workaround or a solution.
