### ISSUE TITLE
Headers are misaligned after resizing window

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#1461]
### Description  
Headers are misaligned after resizing window

### Steps to reproduce  
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_search.html
2. Resize window to smaller
3. Scroll horizontal and vertical in the grid
4. Select a cell
5. Maximize window

### Result  
Headers are misaligned

### Expected result  
Headers should be aligned

### Attachments  
![image](https://user-images.githubusercontent.com/11463104/40969912-cf8ef902-68c1-11e8-8565-989175729a7f.png)

**Comment by tachojelev** [comment]
Possibly related to another issue - #1399
