### ISSUE TITLE
IgxNavigationDrawerComponent throws errors

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1467]
### Description  
Describe the issue.

### Steps to reproduce  

1. Get attached sample
2. npm install, npm link igniteui-angular, ng serve --preserve-symlinks
3. Open http:://localhost:4200 and obesrve the browser console

### Result  
![nav](https://user-images.githubusercontent.com/14248932/40976706-9d90a304-68d7-11e8-88b9-5ce829b9d6b3.PNG)

### Attachments  
[igxgrid.zip](https://github.com/IgniteUI/igniteui-angular/files/2072382/igxgrid.zip)

**Comment by zdrawku** [comment]
@hanastasov, we shoud add tests for the rowHeight on the 3 different states.

**Comment by hanastasov** [comment]
Issue is due ot outdated rxjs package.
