### ISSUE TITLE
Igx-switch styles out of order in 'RTL' mode

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#14677]
## Description  
The `IgxSwitch` styles appear out of order in 'RTL' mode.

 * igniteui-angular version: 18.x
 * browser: tested with Chrome, Mozilla, Edge

## Steps to reproduce  

1. Change the dir to 'rtl'

## Result  
![switch](https://github.com/user-attachments/assets/1d865435-5e86-4b42-b509-7209e3fce76b)

## Expected result  
![image](https://github.com/user-attachments/assets/e0d6d1bb-f036-4d1f-a0d6-271989e91492)

**Comment by simeonoff** [comment]
Setting dir directly on the switch is not supported. Setting dir to an element up the tree should work just fine.
