### ISSUE TITLE
The toolbar hiding/pinning dropdown does not scroll using mouse wheel

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#14716]
## Description  
The toolbar pinning/hiding dropdown does not scroll on the WebComponents Grid
 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open https://www.infragistics.com/webcomponents-demos/grids/grid/column-pinning-right-side
2. Open the pin toolbar dropdown
3. Try to scroll the columns list using the mouse wheel

Same is on staging as well with latest version.

## Result  
The columns list does not scroll using the mouse wheel

## Expected result  
The columns list should scroll using the mouse wheel

**Comment by tishko0** [comment]
Issue is in samples browser, fixes here:
https://github.com/IgniteUI/igniteui-wc-examples/pull/861
https://github.com/IgniteUI/igniteui-react-examples/pull/659
https://github.com/IgniteUI/igniteui-blazor-examples/pull/836
