### ISSUE TITLE
igx-badge with value does not respond to setting --size

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#14777]
## Description  
When setting --size on a badge with value, the badge does not reflect it under a certain threshold. 

 * igniteui-angular version: 18.x
 * browser: all

## Steps to reproduce  

1. Define an `igx-badge` with `value`.
2. Create a class for it and set `--size: 12px`.
3. Observe the badge size and compare to a badge with `igx-icon`.

## Result  
The badge does not reflect the size setting.

## Expected result  
The badge should reflect the size setting.

## Attachments  
![image](https://github.com/user-attachments/assets/8e01dc8c-6a92-4e59-b99d-b726bf50d11d)

**Comment by simeonoff** [comment]
@kdinev I see that you've merged the PR that closes this issue. Keep in mind that the PR only introduces a few changes to the badge that will make it a bit more proportional with small values for `--size`, but they will not make it collapse to 12px when you set its `--size` variable to that value. The badge styles enforce a `font-size` and `line-height` for its text values to the ones defined in the `caption` typography style. For this reason, it will not collapse beyond a certain threshold.

If you want the badge to collapse fully to 12px when using text values, you will also need to override its typography. Here's one way to do it:

```css
igx-badge {
  --size: 12px;

  font-size: calc(var(--size) / 2);
  line-height: normal;
}
```

**Comment by simeonoff** [comment]
> ```css
> igx-badge {
>   --size: 12px;
> 
>   font-size: calc(var(--size) / 2);
>   line-height: normal;
> }
> ```

Here's the related [documentation PR](https://github.com/IgniteUI/igniteui-docfx/pull/5951).
