### ISSUE TITLE
Grid Excel Export does not work with readonly data

### ISSUE THREAD

**Issue by jjs98** [IgniteUI/igniteui-angular#14786]
## Description  
Providing the grid with an immutable object like a signal breaks the excel export function.

Its because in

```ts
private addLevelData() {
  if (this.options.exportSummaries && this.summaries.size > 0) {
    for(const r of this.flatRecords){
      if (r.type === ExportRecordType.DataRecord || r.type === ExportRecordType.TreeGridRecord || r.type === ExportRecordType.HierarchicalGridRecord) {
         r.data[GRID_LEVEL_COL] = r.level;
      }
    }
  }
}
```

the data field needs to be changed. If this would be a copy of data you could provide readonly objects as you like.

 * igniteui-angular version: 18.1.10
 * browser: Edge (chromium)

## Steps to reproduce  

1. Use ngrx/signals
2. Use the value of a signal as data

## Result  
Error Message: ERROR TypeError: Cannot add property GRID_LEVEL_COL, object is not extensible

## Expected result  
The excel export works

**Comment by ivanvpetrov** [comment]
Hi @jjs98!

I'm not quite able to replicate the issue. I've altered the grid-export sample in such a way that it uses ngrx/signal store data, but the export functionality works fine:
[](https://stackblitz.com/edit/ar71wt?file=src%2Fapp%2Fservices%2Fexcel-export-sample-1%2Fexcel-export-sample-1.component.html  )

If I deliberately make the **r.data** object read-only like this:
    ```
private addLevelData() {
        if (this.options.exportSummaries && this.summaries.size > 0) {
            for(const r of this.flatRecords){
                if (r.type === ExportRecordType.DataRecord || r.type === ExportRecordType.TreeGridRecord || r.type === ExportRecordType.HierarchicalGridRecord) {
                    **Object.freeze(r.data);**
                    r.data[GRID_LEVEL_COL] = r.level;
                }
            }
        }
    }
``` 
Now, it indeed throws the 'Cannot add property GRID_LEVEL_COL' error, but I'm not sure how to get there in a real world scenario. Do you have sample of the problematic code, or if you could edit my example?

Thanks,
Ivan Petrov

**Comment by jjs98** [comment]
Hi @ivanvpetrov,

I tried to reproduce it in your stackblitz example, but I also could not repruce it anymore....

I guess you can close this issue. If I stumble across this issue again and find a consistent way to reproduce it, I will reach out to you.
