### ISSUE TITLE
igx-radio should support Reactive Forms

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular#1479]
### Description  
IgxRadio does not support Reactive Forms.

### Steps to reproduce  

1. Open https://stackblitz.com/edit/igx-radio-reactive-forms
2. Click on 'Green color'

### Result  
The 'Red color' does not uncheck.

### Expected result  
The 'Red color' should uncheck.

**Comment by tkiryu** [comment]
I think this is related to #1166.

**Comment by tiliev** [comment]
@tkiryu, it's the same.

**Comment by tiliev** [comment]
This appears to have been working in the past - version `5.2.0-beta.1`. It doesn't work in `5.3.1` anymore. Stackblitz sample - https://stackblitz.com/edit/igx-radio-reactive-working.

**Comment by zdrawku** [comment]
Development of this will start next month (start of July), as we discussed with @SlavUI.

**Comment by SlavUI** [comment]
We will start working on this issue in the current Sprint

**Comment by bkulov** [comment]
We will create a new component (radio group) which will solve this problem.
