### ISSUE TITLE
Pivot Grid: gap in header borders

### ISSUE THREAD

**Issue by imincheva** [IgniteUI/igniteui-angular#14810]
## Description  
On one of the Pivot Grid demos there's a gap in the header border

NOTE:  This is only reproduced when you dont have a column dimension

## Steps to reproduce  

1. Open Pivot Grid page (applicable for all themes and all sizes of the Pivot Grid)
2. Look at the second header row (first cell in the row says "Drop Row Fields here"

## Result  
The vertical borders aren't connected with the horizontal border underneath them
<img width="812" alt="image" src="https://github.com/user-attachments/assets/d968268e-5ae3-46fa-b598-496fb19ad6a8">

## Expected result  
The borders are supposed to be connected and no gap should appear. I believe the problem comes from the applied max-height on igx-grid-thead--virtualizationWrapper
<img width="815" alt="image" src="https://github.com/user-attachments/assets/830639aa-da87-477b-9506-e006a5c3e0c0">

**Comment by simeonoff** [comment]
@mddragnev After some investigation, it turns out this issue happens because of incorrectly applied heights (bound via templates) to some of the elements (igx-grid-thead--virtualizationWrapper and igx-grid__tr).

**Comment by mddragnev** [comment]
Note for testers: This is only reproduced when you dont have a column dimension
