### ISSUE TITLE
Stepper jumps when content has different height

### ISSUE THREAD

**Issue by didimmova** [IgniteUI/igniteui-angular#14828]
## Description  
The Angular Stepper is jumping when the size of the content isn't the same in all steps. I think it would be better if we fix it, the way it's acting in the Web Components.

## Steps to reproduce  

1. Open IgniteUI Angular Demos App
2. Open Stepper Sample
3. See how the height changes with the content, which results in that jumpy feeling.

## Expected result  
The stepper should inherit the height of the highest step content, so it doesn't jump.

## Attachments  
https://github.com/user-attachments/assets/f0788a90-5592-4785-ba36-5b894f6ec73c

**Comment by SisIvanova** [comment]
To fix this issue we should change the whole layout of the stepper component which for the time being is not necessary.
