### ISSUE TITLE
QueryBuilder: Changes in edited condition are committed when start editing another

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#14881]
## Description  
When we change the currently edited condition without committing or discarding it, it is committed.

![QB_issue9](https://github.com/user-attachments/assets/83f40363-f8dd-4796-b609-c7df32c5e027)

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Start editing a condition
2. Without committing/discarding it click on another condition in order to enter edit mode

## Result  
The previously edited condition is committed

## Expected result  
Instead of committing it, wouldn't it be better to discard the change (since it is not explicitly committed) or prevent entering edit mode if the change in the edited condition is not committed or discarded?

**Comment by teodosiah** [comment]
After discussing the behavior with @sdimchevski, we have decided that if we change the edited condition, it should be discarded.

**Comment by teodosiah** [comment]
@sdimchevski After further investigation, I have determined that the same behavior is observed in the Grid Row Editing, i.e. the changed cell value is committed when clicking in another row.
![rowediting](https://github.com/user-attachments/assets/c9c6c00d-9e82-4cd4-ba81-11780a1191da)
Considering this, should we change the Query Builder behavior or keep it this way?

**Comment by sdimchevski** [comment]
@teodosiah OK, it's not optimal but let's keep it this way in the Query Builder because I don't want to change the behavior in the grid.
