### ISSUE TITLE
Add Multi-row layout support to igxGridState 

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#14907]
Multi-row layout settings get lost when columns are restored using igxGridState.
Multi-row layout is currently not included in the supported features for igxGridState.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/state-persistence#supported-features
Consider adding the functionality that restores multi-row layout settings to the grid state persistence feature.

**Comment by ChronosSF** [comment]
@mkamiishi , I think we might actually be able to get this in for 18.2 that's coming next week. I'll update you again if our plans change.
