### ISSUE TITLE
Fetching private npm feed getting 403 Forbidden error

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#14929]
### Description  
Private feed not getting pulled.
Even after we created new token as we thought the token must have expired.

This started happening to us from Saturday and before that everything was fine,

 * igniteui-angular version: 16.1.30
 * browser: chrome

### Result  

error Error: https://packages.infragistics.com/npm/js-licensed/@infragistics/igniteui-angular/-/igniteui-angular-16.1.30.tgz: Request failed "403 Forbidden"
--
2916 | at ResponseError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:696:66)
2917 | at new ResponseError (/usr/local/lib/node_modules/yarn/lib/cli.js:802:124)
2918 | at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:66750:16)
2919 | at Request.emit (node:events:517:28)
2920 | at module.exports.Request.onRequestResponse (/usr/local/lib/node_modules/yarn/lib/cli.js:142287:10)
2921 | at ClientRequest.emit (node:events:517:28)
2922 | at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
2923 | at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
2924 | at TLSSocket.socketOnData (node:_http_client:541:22)
2925 | at TLSSocket.emit (node:events:517:28)
2926 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### Expected result  
Npm private feed should work without any issues.

**Comment by amitmoondra** [comment]
@hanastasov can you assist us with this?
I have also emailed @kdinev about it.
This is urgent and that is why I am opening a case here too.

**Comment by ChronosSF** [comment]
@amitmoondra , could you please give it another try? There was an unexpected outage to our private npm/nuget feed but it was just resolved. I am sorry for any inconvenience it might have caused.

**Comment by ChronosSF** [comment]
You should be able to check for such issues on https://www.infragistics.com/status but in this particular case the issue would not be caught by the automatic detection the service performs as it is designed to look for different symptoms (and this particular type of outage has never happened before). We'll look into adding it to the list of things it checks for though.

**Comment by amitmoondra** [comment]
ok this is great thank you very much.
@ChronosSF
