### ISSUE TITLE
igxTextHighlight - searching has side effect on unmatched cell.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1493]
### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-highlight-text-issue
2. Type "aaa" in the search box.
3. Press enter key.

### Result  
There are two problems.

1. `igxCell` template style is cleared.
2. `undefined` is displayed on dummy cell.  

### Expected result  
1, 2. Nothing should happen to the cell that the search word doesn't match.

**Comment by DDavidkov** [comment]
@tkiryu Both of these things aren't bugs with the search.

The search simply replaces the cell content with text and span elements. So it isn't a good idea to define styles inline, as the node itself will be replaced with new content. Instead you can simply use the cellClasses input of the column to define a custom class for the cells and use this class for your styling. I modified the [stackblitz](https://stackblitz.com/edit/igx-highlight-text-issue-vvzykd) to demonstrate this.

As for the dummy column, any column for which the search feature makes no sense can be excluded using its searchable input. Simply set it to false and the undefined text will no longer appear. Note that this input is not present in 6.0.0 and will be included in the next release.

**Comment by tkiryu** [comment]
@DDavidkov , thank you for your comment. I get your point.

As for the latter,  for sure, `searchable` input will solve the issue. Thank you for your info. I'm looking forward to it.

But, as for the former, I have different thoughts. Let me explain later on.

**Comment by tkiryu** [comment]
@DDavidkov 

There is a common scenario to change cell style according to its value or row data or something(Please refer to #1079).

In order to achieve that, `cellClasses` is not suitable. Instead, we currently need to use `igxCell` template and set style to its child nodes. That's why I think defining styles inline is a possibility.

At least, only the cells that matches search text should be replaced with new content. Unmatched cells should have no side effect.

**Comment by DDavidkov** [comment]
@tkiryu 
I understand your concerns, but still we can't do a lot in this case.

Support for the search to not change the structure and attributes of arbitrary markup will be a very difficult task that will have limited use. Also, while not affecting unmatched cells will help a bit, it won't really solve anything, as the problem will still appear in the matched cells, so I am not willing to introduce changes in the code for no reason.
