### ISSUE TITLE
Chips direction arrow is interactable element

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#1495]
### Description  
The arrow between the chips is interactable element and when you click that arrow you can sort the column ore drag the whole chip.

### Steps to reproduce  

1. Open group by sample
2. Sort by more than one column so you can see the arrow between the chips
3. Click on that arrow or drag it to see the problem explained in the description.

### Result  
The arrow trigger sorting and dragging actions?

### Expected result  
The arrow should not trigger sorting and dragging actions?

### Attachments  
![screenshot-2018-6-7 igniteuidevdemos](https://user-images.githubusercontent.com/21260963/41096409-2e1f167c-6a5d-11e8-9d90-68e5979ef230.png)

**Comment by skrustev** [comment]
This should be resolved since the chips now use the drag and drop directives.
