### ISSUE TITLE
Avatar component fails to display images with spaces or special characters in file names

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#14965]
## Description  
When using the Avatar component, images with file names containing spaces or special characters do not display correctly. The issue arises because the component does not handle URL encoding for file names, which leads to broken image links. However, the native HTML <img> element can display these images without issues. While a workaround will be applied in CodeGen, the Avatar component should also be fixed to ensure correct rendering of image file names containing spaces or special characters.

 * igniteui-angular version: latest
 * browser: any

## Steps to reproduce  

1. Add an Avatar component to the page and set the src attribute to an image file with spaces or special characters in its name (e.g., "profile pic.jpg" or "profile@icon.png").
2. Load the page.

## Result  
The Avatar component fails to display the image. Instead, an empty image icon appears.

![image](https://github.com/user-attachments/assets/21fad8d3-4c76-42ed-a0f0-46066f19dfca)

## Expected result  
The Avatar component should display the image correctly, similar to how the native HTML <img> element handles URLs with spaces or special characters by automatically encoding them.

![image](https://github.com/user-attachments/assets/227c537a-b668-4fed-9229-5a1197754558)

**Comment by mddragnev** [comment]
@simeonoff I found a scenario where your fix seems that doesn't work. 
If you open the attached sample and run it you can see that the avatar is not rendering an image. For some reason after the `encodeURI` the image url becomes invalid. Here the specific issue seems to be the `(` and `)` symbols in the name of the png. If I rename the `Advanced Micro Devices Inc. (AMD).png` to `Advanced Micro Devices Inc.png` then everything works fine. Do you think that this is related?
[avatar-test.zip](https://github.com/user-attachments/files/17978601/avatar-test.zip)
