### ISSUE TITLE
Public method close() in igx-dialog emits onClose.

### ISSUE THREAD

**Issue by alexalex972** [IgniteUI/igniteui-angular#1497]
### Description  
Public method close() in igx-dialog emits onClose.
(this also applies for API method open() and event onOpen)

### Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-del6th.
2. Click Open button.
3. Click Close button.

### Result  
Public method close() triggers an event onClose.

### Expected result  
Public methods shouldn't trigger events.

**Comment by sstoyanovIG** [comment]
I talked with @damyanpetev and he said that this is by design. I also checked the igDialog and it behaves in a similar way.
