### ISSUE TITLE
igx-datePicker in igx-grid is not shown properly

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1499]
### Description  
When I add a datePicker into the igx-Grid, the datePicker is not shown properly.
Also, the alignment of the datePicker is off in the grid.

### Steps to reproduce 
1. Create a new  Angular UI project with everything in place
2. Add a igx-grid
3. Add a igxColumn with an ng-template that contains a igx-datePicker
4. Provide it with data
5. `ng serve`

### Result  
The datePicker is not shown or is shown inside the grid without much functionality

### Expected result  
The datePicker is shown _over_ the grid with all it's functionality

### Attachments  
I created a reproduction in my git:
[Link to reproduction](https://github.com/Hypenate/IgniteUI_issues/tree/datepickerInGridAlignment)

**Comment by Hypenate** [comment]
Except for the alignment, it's related to #1057?

**Comment by Aleksandyr** [comment]
@Hypenate Could you please give me more details of what exactly you mean with not shown properly? I have made a [sample ](https://stackblitz.com/edit/angular-pmxpyk-ak72gr?file=app/grid/grid.component.html) for you into the stackblitz with the same configuration as yours where you can manipulate it directly. So could you please give some screenshots and precise descriptions based on that sample.

**Comment by Hypenate** [comment]
@Aleksandyr I would expect that the igx-datePicker is aligned in the middle, and not at the bottom.
![image](https://user-images.githubusercontent.com/7478681/41341783-d84b642e-6efa-11e8-9ec7-8935f76e7c1d.png)

If you would reduce the height of the row, the igx-datePicker will almost fall of.
![image](https://user-images.githubusercontent.com/7478681/41342202-f72924fc-6efb-11e8-82ed-1911e6b747aa.png)

If #1520 would be approved, you could hide "date" label and center the actual igx-datePicker

Check out my [sample](https://stackblitz.com/edit/angular-pmxpyk-pfdnhg).

**Comment by Aleksandyr** [comment]
@Hypenate This problem is fixed in the next version which would be 6.1.x. r. There is no plan for now this fix to be added into the versions that are lower than the one I have mentioned. So for now you can workaround this by removing the label of the datePicker and add some styling from your side.

**Comment by Hypenate** [comment]
Thank you!
