### ISSUE TITLE
[Igx-navbar] The color of the icon buttons doesn't match the color of the title of the navbar when using Fluent or Bootstrap themes

### ISSUE THREAD

**Issue by PlamenD95** [IgniteUI/igniteui-angular#15059]
## Description  
This is a related issue to https://github.com/IgniteUI/igniteui-angular/issues/14599.

The related issue above was resolved by introducing an enhancement to the way the `igx-navbar` works with the material and indigo themes.
Thanks to this enhancement, in v18.2.x of `igniteui-angular` the colors of the `navbar` match between the text and the icons when using the Material Dark or Indigo Dark themes:

Material Dark theme:

![image](https://github.com/user-attachments/assets/a8ed1d2f-4e19-491d-916c-3f631503bcb6)

Indigo Dark theme:

![image](https://github.com/user-attachments/assets/1174549c-583d-4c64-bb4b-72688e9e49fb)

Is it possible to introduce a similar enhancement for the Fluent and Bootstrap dark and light themes as well?

Currently there is a mismatch between the colors of the title and icons for them, in the same way as the original mismatch in the related issue for Material and Indigo themes:

Fluent Light:

![image](https://github.com/user-attachments/assets/eb938064-d9d8-4c26-b6ad-d22574d6131b)

Fluent Dark:

![image](https://github.com/user-attachments/assets/f5aad4f4-7aab-466e-8a24-651c8f570c05)

Bootstrap Light:

![image](https://github.com/user-attachments/assets/5efa84ca-36f9-4335-af82-7d4fffcafaba)

Bootstrap Dark:

![image](https://github.com/user-attachments/assets/44fd593a-7ee5-4d73-b1fa-a388aeaaddde)

 * igniteui-angular version: 18.2.x
 * browser: Google Chrome

## Steps to reproduce  

1. Add the `igx-navbar` component to an application.
2. Use the Fluent light, Fluent dark, Bootstrap light or Bootstrap dark themes.
3. ...

## Result  
There is a mismatch between the colors of the icon buttons and the title text of the navigation bar.

## Expected result  
The colors of the title text and buttons in the navigation bar should match when using the Fluent light, Fluent dark, Bootstrap light or Bootstrap dark themes.

**Comment by simeonoff** [comment]
@PlamenD95 I'm replacing the label `bug` with `question` as this is by design. Assigning Svilen as well as this matter is in his court.

**Comment by sdimchevski** [comment]
@PlamenD95 In the Fluent and Bootstrap design systems, blue titles are not used anywhere, so including one in the navbar would feel inconsistent and out of place. This is by design and should stay like this

**Comment by PlamenD95** [comment]
@sdimchevski, thank you for the answer!

Regarding, Fluent Dark, would it be possible to have the title in green, or would that also clash with the title colors used elsewhere?

**Comment by sdimchevski** [comment]
I don't know why the green color in Fluent Dark. By design it's blue

**Comment by sdimchevski** [comment]
It comes down to the unique principles, goals, and context each design system is built to address. It’s not about one being right or wrong - it’s just different philosophies. Titles and icons might have different colors because their roles differ: titles often grab attention as primary text, while icons complement the design or serve interactive purposes. Fluent and Material take different approaches to hierarchy and visual priorities. Fluent typically uses one color for the navbar title and another for icons to establish a clear hierarchy, while Material tends to use the same color for both, focusing on a simpler, more unified look.
