### ISSUE TITLE
Summaries are not correct when they are disabled and filter items

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#1506]
### Description  
Summaries are not correct when they are disabled and filter items

### Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-sjcjda-rbt5gc?file=app%2Fgrid%2Fgrid-filtering-sample%2Fgrid-filtering-sample.component.html
2. Click button Disable Summary
3. Filter column (for example with condition contains and value chai)
4. Click button Enable Summary

### Result  
Summary count is 20

### Expected result  
Summary count should be 1

### Attachments  

![image](https://user-images.githubusercontent.com/11463104/41234420-c9759af8-6d94-11e8-8f8c-de52fcdf3cb5.png)

**Comment by zdrawku** [comment]
Already fixed, I have updated the [sample ](https://stackblitz.com/edit/angular-single-summary-example)with the latest version
