### ISSUE TITLE
Avatar and badge should have separate samples

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#152]
Currently the avatar sample shows both the avatar and the badge, and it doesn't mention that it shows both.

The avatar samples should show only the avatar.
There should be separate badge component samples, which show badge on avatar, on tab-bar and on list.

**Comment by zdrawku** [comment]
Two different samples/topics were implemented for both Avatar and Badge component when Ignite UI for Angular topics were released. 

As for the recommendation badge to be shown not only on avatar, but also on tab-bar and list, we are currently working on general modification of all angular component topics based on the new [contributing guidance](https://github.com/IgniteUI/igniteui-docfx/blob/master/.github/CONTRIBUTING.md) which are part of the Ignite UI DocFX Site Builder [repo](https://github.com/IgniteUI/igniteui-docfx)

Current topics:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/badge.html
https://www.infragistics.com/products/ignite-ui-angular/angular/components/avatar.html
