### ISSUE TITLE
No rows are present when the igx-grid has no width and height set and is placed in a div container

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1528]
### Description  
No rows are present when the igx-grid has no width and height set and is placed in a div container.

For example:
```html
<div>
    <igx-grid [data]="data" >
    </igx-grid>
</div>
```
### Steps to reproduce  

Download and run the attached sample application.

### Result  
There are no rows visible. (refer to image below)

### Expected result  
There are visible rows.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/41289683-4760d7c0-6e53-11e8-906f-f5da6a1f8b6e.png)
[igxGridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/2093933/igxGridSample.zip)

**Comment by kdinev** [comment]
@tachojelev This should be covered by setting `[height]='null'`. Try it, and if it doesn't work, then there's a bug.
