### ISSUE TITLE
igx-Tabs doesn't work with ngFor

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1538]
### Description  
When you use ngFor to generate tabs it fails to do so properly.
Might be related to #1388 as it contains the same errormessage?

### Steps to reproduce  
1. Create a new  Angular UI project with everything in place
2. Add a igx-tabs
3. Add a igx-tabs-group with an *ngFor
5. `ng serve`

### Result  
Tabs are not (correct) created.

### Expected result  
Tabs are shown the same way if I would specify them manually in html

### Attachments 
![image](https://user-images.githubusercontent.com/7478681/41335797-57bfb036-6eea-11e8-9e68-1dbc7de20cd1.png)

I created a reproduction in my git:
[Link to reproduction](https://github.com/Hypenate/IgniteUI_issues/tree/TabsNgFor)

**Comment by sboykova** [comment]
This issue is fixed in version [6.0.1](https://github.com/IgniteUI/igniteui-angular/releases/tag/6.0.1)
