### ISSUE TITLE
Enabling Paging and Summaries of the igxGrid through API does not work

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1540]
### Description  
Enabling Paging and Summaries of the igxGrid does not work through API.

**NOTES:**
If the browser windows is resized, both the paging and the summary area get displayed.

### Steps to reproduce  

1. Download and run the attached sample application.
2. Click the button on the bottom.

### Result  
Paging and Summary area are **not** visible.

### Expected result  
Paging and Summary area are visible.

### Attachments  

![refreshissue](https://user-images.githubusercontent.com/12784974/41336380-c57b6174-6ef4-11e8-8678-bd227284ff4f.gif)
[gridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/2097002/gridSample.zip)

**Comment by kdinev** [comment]
@tachojelev Call `markForCheck` after setting these inputs. The reason why we do not react to this out of the box is that if there's hundreds of columns, and summaries are set on each column on init, then change detection would be ran hundreds of times.

This should work for paging though!

**Comment by DDavidkov** [comment]
Fixed the paging input to properly update the grid and I kept the current behavior of hasSummary intact for the aforementioned reasons. Note that you need to call `reflow` instead of `markForCheck` for summaries to work properly.
