### ISSUE TITLE
Column moving does not keep the selection.

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#1546]
### Description  
When a selection on a cell is made and the column is moved the selection does not move with the column.

### Steps to reproduce  

1. Open Grid Column Moving Demo.
2. Click on a cell to select it.
3. Move the column.

### Result  
The selected cell stays - a cell from the column placed on the moved column's old position is selected.
There is no selection in the moved column.

### Expected result  
The selected cell should be moved with the 
column to the column's new position.

### Attachements 
![selectionmoving](https://user-images.githubusercontent.com/11095014/41349483-a4d7a1de-6f18-11e8-83e6-e967fee62cd7.gif)

**Comment by SlavUI** [comment]
@SAndreeva See if you can resolve this by the end of next week.

**Comment by npaunov** [comment]
Related #1542
