### ISSUE TITLE
Bootstrap & IgniteUI issues

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1548]
### Description  
I'm using bootstrap for my layout, but I'm having issues with controls from ignite ui, switching over to your Layout Manager is not an option due a policy at work.
I added a small video of the weird things I encounter in the attachment section.

Is there anyway to overcome this? 

### Steps to reproduce  

1. Add igniteUI
2. Add bootstrap
3. Design a website? 😄 

### Result  
For example the igx-dataGrid would go out of screen.

### Expected result  
The controls are 'slave'/working of/with bootstrap

### Attachments  
A small video: 
[BootstrapWithIgnite.zip](https://github.com/IgniteUI/igniteui-angular/files/2098168/BootstrapWithIgnite.zip)

**Comment by kdinev** [comment]
@Hypenate The layout of the components is all done with flex. There's probably an incompatibility between flex and bootstrap, but @simeonoff is the expect and I will let him comment on this.

**Comment by Hypenate** [comment]
I have just updated to bootstrap 4.1.1, but the issue remains.

My feeling is that the [bootstrap container](https://getbootstrap.com/docs/4.1/layout/overview/#containers) is causing this.

**Comment by kdinev** [comment]
@Hypenate Most probably. Simo will investigate and will update you.

**Comment by simeonoff** [comment]
@Hypenate and @kdinev Looks like a bug width the sizing of the grid to me.

**Comment by zdrawku** [comment]
I agree with @simeonoff.
@Hypenate could you try something out, because I am unable to reproduce the issue, but I have memoris that I saw this somewhere before? Set grid witdh and all grid parent elements to 100%.

Also as I see from the video, you are using navigation drawer, is it possible to remove it just for the test. The issue could be related to the drawer container as well.

In general, providing a working sample with the issue would be highly appreciated.

**Comment by Hypenate** [comment]
Allright, so I made something, @zdrawku is correct, the navigation drawer has an effect on things but also the `container-fluid` from bootstrap.
It's a bit different from the issues I showed in the video but hopefully this sets things in the right direction as I commented the igx-nav-drawer in "the real app" and the grid/bootstrap behaved in a normal way.

With igx-nav-drawer commented, **with** a `<div class="container-fluid">` around the `igx-grid`'s:
![image](https://user-images.githubusercontent.com/7478681/41496431-77e7a2b2-7140-11e8-9cde-7809243c1ef7.png)

With igx-nav-drawer uncommented, **with** a `<div class="container-fluid">` around the `igx-grid`'s:
![image](https://user-images.githubusercontent.com/7478681/41496437-99326042-7140-11e8-94ff-6827fb39446d.png)

With igx-nav-drawer uncommented, **without** a `<div class="container-fluid">` around the `igx-grid`'s:
![image](https://user-images.githubusercontent.com/7478681/41496456-2561555a-7141-11e8-9248-318d0fc857f7.png)

I created a reproduction in my git:
[Link to reproduction](https://github.com/Hypenate/IgniteUI_issues/tree/bootstrapIssue)
Note: check out the app.component.html to get the different results as described above.

**Comment by zdrawku** [comment]
@Hypenate thank you for the provided information, @DDavidkov could you take a look at this

**Comment by Hypenate** [comment]
We  added a second navigation drawer, the issues is worse now.
The navigation drawer definitely has an impact.

**Comment by DDavidkov** [comment]
@Hypenate Yes, it is connected to the nav drawer and it seems to be caused by the transitionDuration property not playing along nicely with the grid's sizing logic. For now you can add the following CSS as a workaround in your styles.css file, while we implement a proper fix:
```CSS
.igx-nav-drawer__aside {
  transition-duration: 0ms;
}
```

**Comment by Hypenate** [comment]
@DDavidkov Doesn't seem to fix the issue for me but I understand you have found the issue and are solving it!
I will await this holy grail 😄

**Comment by Hypenate** [comment]
I removed the igx-tabs and replaced them with tabs from bootstrap (see request #1982), now there is no horizontal scrollbar visible and things are working as expected.
Also the grid now stays in it's tab.
