### ISSUE TITLE
Implement animation when loading remote data in igxGrid

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-angular#1578]
We've updated the remote virtualization sample to show empty boxes when loading remote virtualization data. #1398

The next step is to implement animation similar to this one:
![animation](https://user-images.githubusercontent.com/2705882/41526456-facef7e0-72ec-11e8-8ebb-4f828df94c99.gif)

**Comment by StefanIvanov** [comment]
We will add an indeterminate state to the [Circular Progress](https://github.com/IgniteUI/igniteui-angular/wiki/Circular-Progress-Bar-Specification) and use that for the remote loading scenario

**Comment by simeonoff** [comment]
@StefanIvanov This will require some advanced refactoring of the circular progress component. I think the approach shown in the prototype above is better.

**Comment by StefanIvanov** [comment]
@SlavUI now that the indeterminate progress bars are merged, we should reconsider this issue for all the grids

**Comment by desig9stein** [comment]
@SlavUI can we close that issue?

**Comment by SlavUI** [comment]
@desig9stein We still can improve the visual representation of the Loading :) don't think we should close it
