### ISSUE TITLE
6.0.1 upgrade issues

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1579]
### Description  
Hi Guys

A couple of issues when upgrading from 6.0 til 6.0.1. 

First of all, the theming did not work, when trying to import from the path stated at https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes.html (@import "~igniteui-angular/core/styles/themes/index"). Changing this to
![image](https://user-images.githubusercontent.com/12936286/41527830-a0c3aa74-72e8-11e8-84e4-3a87f5104806.png)
seems to remove the error, but not sure if it works, because of the second issue below.

The second issue is with the IgxTabItemComponent and IgxTabsGroupComponent. It seems they are not exported from the ignite-angular module:
![image](https://user-images.githubusercontent.com/12936286/41528115-701baab0-72e9-11e8-8edd-f29c6fcef4cd.png)

 and my intellisence keeps wanting to get them here
![image](https://user-images.githubusercontent.com/12936286/41528036-3c7de290-72e9-11e8-9b33-6bac83c3a890.png)
which doesn't work very well.

**Comment by Eralmidia** [comment]
Removing the aliases in the igniteui-angular.d.ts seems to make everything work fine
![image](https://user-images.githubusercontent.com/12936286/41530144-9303482a-72ef-11e8-8ef9-81fa3ff88398.png)

**Comment by kdinev** [comment]
Related #1582

**Comment by Eralmidia** [comment]
No problem, I got the dev envoironment up and running, just wanted to let you know. Feel free to close the issue whenever you consider it resolved.
