### ISSUE TITLE
Column moving hides filtering UI

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#1585]
### Description  
When column moving is activated, the filtering UI in the last column changes direction outside of the grid.

### Steps to reproduce  

1. Open Grid Column Moving Demo.
2. Scroll to the last column "Fax".
3. Open the filter UI.

### Result  
The UI dialog is outside of the grid and a big part is not visible.

### Expected result  
The UI dialog should be inside the grid and should be visible.

**Note:** If you change the column to not movable, the filter dialog is shown correctly.

### Attachments  
![moving](https://user-images.githubusercontent.com/11095014/41535110-cd2f37e2-7309-11e8-8297-45d1e51a0bb8.png)

**Comment by SlavUI** [comment]
Just to Add then when the filter is open and you move the column the filter stays at the same position as the column was and now it is open for another column.

**Comment by npaunov** [comment]
Related #1542
