### ISSUE TITLE
Six warnings when building in production mode

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1599]
### Description  
The project builds fine, this is just a heads up ☺️ 
When building the Angular project with --prod you get six warnings about _empty properties_.

### Steps to reproduce  

1. Create a new  Angular UI project with everything in place
2. Add a igx-button and a igx-grid (maybe there are more?)
5. `ng build --prod`

### Result  
![image](https://user-images.githubusercontent.com/7478681/41586751-ced6f284-73ad-11e8-91ea-17ae58491feb.png)

### Expected result  
No warnings.

**Comment by kdinev** [comment]
I'm not sure if the classes are placeholders that are intended to be overridden for customizations, or just leftovers. @simeonoff ?

**Comment by simeonoff** [comment]
These are CSS variables. I will take a look at them today.
