### ISSUE TITLE
Column moving - dragged header is displayed below the grid

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#1607]
### Steps to reproduce  

1. Start dragging a column header

### Result  
In the sample, dragged column header appears below the grid

### Expected result  
Dragged column header appears in the headers area

[testColumMoving.zip](https://github.com/IgniteUI/igniteui-angular/files/2115469/testColumMoving.zip)

**Comment by npaunov** [comment]
Related #1542
