### ISSUE TITLE
Grid data bind fails initially until window resize

### ISSUE THREAD

**Issue by QuinntyneBrown** [IgniteUI/igniteui-angular#1614]
https://stackblitz.com/github/QuinntyneBrown/IgniteUIGridIssue

### Description  
The grid displays the column names. The grid does not display the data

### Steps to reproduce  

1. Open https://stackblitz.com/github/QuinntyneBrown/IgniteUIGridIssue
2. Install missing dependecies on StackBlitz
3. Observe header of "Code" but no data
4. Slightly adjust the window
5. Observe data rendered

### Result  
Observe header of "Code" but no data until you adjust the window and then the data appears.

### Expected result  
The data should appear imeediately

### Attachments  

https://stackblitz.com/github/QuinntyneBrown/IgniteUIGridIssue

Install the dependencies.

![image](https://user-images.githubusercontent.com/1749159/41608327-436a4ef4-73b6-11e8-8a42-85460814135f.png)

Observe no data

![image](https://user-images.githubusercontent.com/1749159/41608389-6a945d12-73b6-11e8-8f1b-e43ed0b824e6.png)

Observe data

![image](https://user-images.githubusercontent.com/1749159/41608424-7edb53d4-73b6-11e8-8032-4805ecc98e7f.png)

**Comment by DDavidkov** [comment]
@QuinntyneBrown We had a few releases recently so I didn't get a chance to work on this. Since they are now over, I have committed a fix and it is on PR. It needs to get review and verified and it will be merged into the main product.
