### ISSUE TITLE
Drag and drop is working with delay on touch screen in Firefox

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular#1621]
### Description  
Dragging element on touch screen in Firefox has delay.

### Steps to reproduce  

1. Open either the 'Chips', 'Drag and Drop', or the 'Column Moving' dev sample in Firefox on touch screen device.
2. Touch and hold a chip or column header so you could drag it and drop it

### Result  
The dragged element is moving with couple seconds delay after the finger moving

### Expected result  
Dragged chip/header to be moving with no delay.

**Comment by mpavlinov** [comment]
@MartinKamenov Closing it, because it no longer reproduces.
