### ISSUE TITLE
Filtering a movable column in grid makes the header moving in Firefox

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular#1635]
### Description  
When you try to filter a movable column, the column becomes movable in Firefox.

### Steps to reproduce  

1. Open either Grid Column Moving or GroupBy sample.
2.  Make a column movable and filterable.
3. Choose to filter and select one of the dropdown options.

### Result  
The header of the column becomes movable.

### Expected result  
The header should stay static and only the filtering should be applied.

### Attachments  
![firefoxfilter1](https://user-images.githubusercontent.com/24592428/41701726-2faa3830-7536-11e8-9d8c-bb0b016c8678.PNG)
![firefoxfilter2](https://user-images.githubusercontent.com/24592428/41701753-44d24d92-7536-11e8-9dab-369904eaba21.PNG)
![firefoxfilter3](https://user-images.githubusercontent.com/24592428/41701777-569a278e-7536-11e8-9edc-1d69dc6ce4b4.PNG)

**Comment by npaunov** [comment]
Related #1542
