### ISSUE TITLE
importing IgxGridSortingPipe problem with igniteui-angular@6.0.2

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1636]
### Description  
I'm updating `igniteui-angular` from 6.0.0 to 6.0.2 and running into a problem with importing `IgxGridSortingPipe`.

I imported `IgxGridSortingPipe` like this before.
```
import { IgxGridSortingPipe } from 'igniteui-angular/grid/grid.pipes';
```
I know that it doesn't work anymore due to breaking change.

### Result  
So, I tried several ways to import `IgxGridSortingPipe` with `igniteui-angular@6.0.2`.

1)
```
// It gets error highlight on VS Code.
import { IgxGridSortingPipe } from 'igniteui-angular';
```

2)
```
// There is no error highlight on VS Code, but it gets error at compile time.
import { IgxGridSortingPipe } from 'igniteui-angular/lib/grid/grid.pipes';

// The error message is "Module not found: Error: Can't resolve 'igniteui-angular/lib/grid/grid.pipes' in ..."
```

3)
I checked `node_modues/igniteui-angular/igniteui-angular.d.ts` and  found that `IgxGridSortingPipe` is exported as `eo`.

So, we can do that like this. But it doesn't make sense.
```
import { ɵo as IgxGridSortingPipe }  from 'igniteui-angular';
```

igniteui-angular.d.ts
``` 
/**
 * Generated bundle index. Do not edit.
 */
export * from './public_api';
export { EaseIn as ɵa, EaseOut as ɵb } from './lib/animations/easings';
export { DeprecateClass as ɵc, DeprecateProperty as ɵd } from './lib/core/deprecateDecorators';
export { IgxSelectionAPIService as ɵk } from './lib/core/selection';
export { HammerGesturesManager as ɵt } from './lib/core/touch';
export { IgxDialogActionsDirective as ɵj, IgxDialogTitleDirective as ɵi } from './lib/dialog/dialog.directives';
export { DisplayContainerComponent as ɵe } from './lib/directives/for-of/display.container';
export { HVirtualHelperComponent as ɵg } from './lib/directives/for-of/horizontal.virtual.helper.component';
export { VirtualHelperComponent as ɵf } from './lib/directives/for-of/virtual.helper.component';
export { IgxGridFilterComponent as ɵn } from './lib/grid/grid-filtering.component';
export { IgxGridHeaderComponent as ɵl } from './lib/grid/grid-header.component';
export { IgxGridSummaryComponent as ɵm } from './lib/grid/grid-summary.component';
export { IgxGridFilterConditionPipe as ɵr, IgxGridFilteringPipe as ɵq, IgxGridPagingPipe as ɵp, IgxGridSortingPipe as ɵo } from './lib/grid/grid.pipes';
export { IgxIconComponent as ɵh } from './lib/icon/icon.component';
export { IgxListItemComponent as ɵs } from './lib/list/list-item.component';
export { IgxEmptyListTemplateDirective as ɵu } from './lib/list/list.common';
export { IgxAmPmItemDirective as ɵy, IgxHourItemDirective as ɵw, IgxItemListDirective as ɵv, IgxMinuteItemDirective as ɵx } from './lib/time-picker/time-picker.directives';
```
Note that other pipes, components and directives also would lead to same problem.

### Expected result  
Simply, just like this.
```
import { IgxGridSortingPipe } from 'igniteui-angular';
```

**Comment by kdinev** [comment]
@tkiryu In #1432 you requested the grid API for the modified data to be exposed. We've now hidden grid specific pipes, since they are not generic.

**Comment by tkiryu** [comment]
@kdinev , thank you. I got it.

As for igniteui-angular@6.0.2, `IgxGridSortingPipe` has already been hidden, but `filteredSortedData` hasn't been exposed as public API yet. 

This is a problem for me. I'll wait for upcoming release.

Best regards,

**Comment by kdinev** [comment]
@tkiryu You're right. That was exposed only in master and will be released with `6.1.0`. If you badly need it in `6.0.x`, I can expose it back until `6.1.0`.

**Comment by kdinev** [comment]
@tkiryu I exposed it for you in `6.0.x` as well. It will appear in `6.0.3`.

**Comment by tkiryu** [comment]
@kdinev , thank you sooo much!!!
