### ISSUE TITLE
On editing of a Boolean cell the Checkbox is not working properly

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#1638]
### Description  

- [x] If I click somewhere aroun the text of the cell, it will enter edit mode and the checkbox will be populated with the cell value, although if I click directly to the text of the cell, the checkbox will be unchecked everytime.
- [x] On cell edit entered with tab click, when the checkbox is focused, if I press the space key, the checked value should toggle.
- [x] There is some issue with the focus, if I check

**Comment by Aleksandyr** [comment]
The following [pull request](https://github.com/IgniteUI/igniteui-angular/pull/1525) fixes the issue.

**Comment by zdrawku** [comment]
@Aleksandyr the PR is merged, I am going to test it and close the issue if it's fixed

**Comment by zdrawku** [comment]
I confirm, the issue is fixed
