### ISSUE TITLE
Implement scrolling inertia when scrolling on touch

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#1640]
### Description  
Scrolling using touch does not have inertia.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html
2. Try to scroll using swipe

### Result  
The grid scrolls but there is no inertia

### Expected result  
There should be inertia on swipe scrolling

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
Linking #2409
