### ISSUE TITLE
Exception is thrown when trying to delete chip using "x" icon  in Edge and IE11

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#1643]
### Description  
ERROR TypeError: Object doesn't support property or method 'animate' exception is thrown when trying to delete chip using its "x" button in Edge and IE 11
### Steps to reproduce  

1. Run chips sample from ignite-ui repo in Edge/IE11
2. Click "x" (remove) icon in the chip
3. Observe the console

### Result  
Chip is deleted, however, there is an exception thrown in the console.
ERROR TypeError: Object doesn't support property or method 'animate'

### Expected result  
Chip to be deleted successfully without any exception

**Comment by skrustev** [comment]
This is caused by the igxRipple as it uses animations that are not supported in Edge/IE11.
The `web-animations-js` polyfill needs to be imported in order for these animations to work.
