### ISSUE TITLE
onClick event is not fired when user clicks on a chip

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#1644]
### Description  
onClick event is not fired when the user clicks on a chip

### Steps to reproduce  

1. Open the chips sample from igniteui-angular repo
2. Add onClick event 
   onClick(){
        console.log("click");
    }
3. Run chips sample
4. Click on any of the chips
5. Observe the console

### Result  
onClick event is not fired and the message is not logged in the console

### Expected result  
onClick event to fire and the message from the event handler to be logged in the console

**N.B** This issue is reproducible when the onClick event is attached to the chips area. If attached to the chip the events is fired so this might be the behavior by design.

**Comment by skrustev** [comment]
I am closing this issue since the onClick event is event of the chip itself and not the chip area.
