### ISSUE TITLE
Chip can not be deleted in Edge and IE11 using the "Delete" key

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#1645]
### Description  
A chip cannot be deleted in IE11 and Edge using the "Delete" key form the keyboard

### Steps to reproduce  

1. Run the chips sample from igniteui-angular repo under Edge/IE11
2. Click on any of the chips
3. Press "Delete" button on the keyboard

### Result  
Chip is not deleted

### Expected result  
The chip should be deleted. Expected behavior can be observed in Chrome or Firefox

**Comment by SlavUI** [comment]
@kacheshmarova at what situation using the keyboard can the chips be removed.
