### ISSUE TITLE
Do we have to install hammerjs and @types/hammerjs by ourselves?

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1683]
### Description  
Since `igniteui-angular@5.2.1` had been released, we didn't have had to install `hammerjs` manually.
https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#521
> hammerjs and @types/hammerjs are removed from peerDependencies and were added as dependencies. So if you are using Igniteui-Angular version 5.2.1 or above it is enough to run npm install igniteui-angular in your project for getting started. For more detailed information see Ignite UI for Angular Getting Started

### Result  
Today, I updated to `igniteui-angular@6.0.3` and got the following warnings.
> npm WARN igniteui-angular@6.0.3 requires a peer of @types/hammerjs@^2.0.35 but none is installed. You must install peer dependencies yourself.
npm WARN igniteui-angular@6.0.3 requires a peer of hammerjs@^2.0.8 but none is installed. You must install peer dependencies yourself.

I checked `package.json` and found that `hammerjs` and `@types/hammerjs` is added to `peerDependencies` again.
https://github.com/IgniteUI/igniteui-angular/blob/6.0.3/projects/igniteui-angular/package.json#L27-L28

### Expected result  
I think `hammerjs` and `@types/hammerjs` should be added to `dependencies`. Maybe so does `jszip`.

Any concerns or technical Difficulties on this?

**Comment by zdrawku** [comment]
Hello @tkiryu this change was made when we changed the structure of our project at the end of may. I am going to leave this issue open, I will reference it with the corresponding change. hammerjs and types/hammerjs would be returned as dependencies.

**Comment by zdrawku** [comment]
Adding reference to [issue](https://github.com/dherges/ng-packagr/issues/716)

**Comment by zdrawku** [comment]
@tkiryu the PR is merged, closing this issue, thank you for submitting your observations.

**Comment by tkiryu** [comment]
@zdrawku , thank you so much!

One last question. what about `jszip`?
