### ISSUE TITLE
Horizontal scrollbar on MAC disappears too fast, which makes it hard to interact with.

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#1689]
### Description  
Horizontal scrollbar on MAC disappears too fast, which makes it hard to interact with.

### Steps to reproduce  

1. Open sample with igx-grid on mac (Safari or Chrome)
2. Scroll horizontally with the trackpad
3. Try to click on the scrollbar

### Result  
It harder to interact with the horizontal scrollbar than with the vertical scrollbar

### Expected result  
The experience with both scrollbars should be the same

**Comment by dkamburov** [comment]
Having custom scrollbars would resolve this, but this is outside of the scope of this issue.
Here's a [fiddle](http://jsfiddle.net/dkamburov/ars69tjc/3/), where simulated scrollbars can be compared to the native scrollbars.

![3kryabxrml](https://user-images.githubusercontent.com/1182001/41974396-893be4ea-7a20-11e8-97c6-3613d972c5ab.gif)

There is a slight, but not significant difference between interacting with the simulated or with the native scrollbars.

**Note:** The easiest way to "grab" the thumb is to start the dragging when the mouse pointer is on the scrollbar.

![grab_the_thumb](https://user-images.githubusercontent.com/1182001/41974574-0591bd44-7a21-11e8-8d3c-58203d13c4a0.gif)

**Comment by mpavlinov** [comment]
We will leave it as is for now.
