### ISSUE TITLE
igx-grid [width] doesn't accept % or px

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1699]
### Description  
According to the [documents](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html#inputs), you can pass 100% or 100px into the input `width `in the igx-grid
Can be related to #1474?

### Steps to reproduce  

1. `<igx-grid [width]="100"></igx-grid>` <-- this sets the width to 100%
2. `<igx-grid [width]="100%"></igx-grid>` <--- throws an error
3. `<igx-grid [width]="100%"></igx-grid>` <--- throws an error

### Result  
See above

### Expected result  
Should work as described in the docs

**Comment by bkulov** [comment]
Hi @Hypenate ,
Could you please post the errors thrown when the width is set in percents?

**Comment by rkaraivanov** [comment]
@Hypenate 
For your 2nd and 3rd step this is expected as binding with the `[property]=value` syntax evaluates the value as a Javascript object. You can achieve that with `[width]='100%'`

**Comment by bkulov** [comment]
Or `width="100%"`.

**Comment by Hypenate** [comment]
`[width]="100%"` --> Parser Error: Unexpected end of expression: 100% at the end of the expression [100%] 
`[width]="100px"` --> Parser Error: Unexpected token 'px' at column 4 in [100px]
`[width]="'100%'"` --> No error but also no result
`width="'100%'"` --> No error but also no result

In the 2 last items it gives me back this while it parent is a `col-12`:
![image](https://user-images.githubusercontent.com/7478681/41891562-48904dc0-7915-11e8-8e91-6a415a24c904.png)

**Comment by bkulov** [comment]
These two should work fine: `[width]="'100%'"`, `width="100%"`. Please note the brackets and the quotation marks.
If you still have issues you could attach a small sample application demonstrating the issue so we could investigate it further.

**Comment by Hypenate** [comment]
This `<div class="ng-star-inserted"` is giving the issue. Could be that the last 2 items work but the div encapsulating it is that large.

![image](https://user-images.githubusercontent.com/7478681/41896358-af20d776-7924-11e8-937c-ab5cc482d65c.png)

**Comment by Hypenate** [comment]
I had an `<div *ngIf="selectedNode">` which generated the  `<div class="ng-star-inserted">`
I replaced the first item with `<ng-container *ngIf="selectedNode" class="row w-100">`
