### ISSUE TITLE
IgxCombo does not retain scroll state after closing

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#1705]
### Description  
If scrolled, the items in the igxCombo do not retain their scroll top after closing and then reopening the component

### Steps to reproduce  

1. Open the IgxCombo sample in JSBlocks
2. Open the IgxCombo dropdown
3. Scroll the list (e.g. to the middle)
4. Click outside of the combo drop down to close it
5. Reopen the combo drop down

### Result  
The scroll is positioned at the top of the drop down container. The list is showing results from the middle of the list of items

### Expected result  
The scroll is positioned at the middle of the drop down container. The list is showing results from the middle of the list of items

### Attachments  
![combo-item-bug-screen](https://user-images.githubusercontent.com/24314672/41856149-09d180e0-789d-11e8-8aa0-7b2852793678.PNG)

**Comment by Lipata** [comment]
This is good if you close the drop down unintentionally, but then there are several UX questions that are not easily resolved like - if we select several items and them scroll to an unselected item then what position we should save - to one of the selected items or to the last scroll position; if start to type, after scroll (like you did with 'conn') and then should we scroll again to the top; after we clear the filtering text, should we scroll again to the previous position. On other hand even the position is lost, then using the filtering we can easily reach a new item we want to select. So for the moment we choose the option not to preserve the scroll position with the option to review that in the future.
