### ISSUE TITLE
Deleting the last chip from a chip area doesn't remove the previous connector for chips

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular#1707]
### Description  
When deleting the last chip from a chip area the last chip connector isn't removed.

### Steps to reproduce  

1. Open chips sample.
2. Delete the last chip.

### Result  
The connector between the last and the before last chip stays after the last one is deleted.

### Expected result  
The last connector should be removed.

### Attachments  
![issuechips1](https://user-images.githubusercontent.com/24592428/41892458-d47b7228-7920-11e8-8603-08a12112bda8.PNG)
![issuechips2](https://user-images.githubusercontent.com/24592428/41892463-d65614cc-7920-11e8-8bf9-8bba306819b4.PNG)

**Comment by harshyadav9** [comment]
can i pick up this issue ?

**Comment by SlavUI** [comment]
@harshyadav9 Of course go for it :)

**Comment by skrustev** [comment]
This is not an issue in the chips themselves but in the demo. `detectChanges()` need to be called in order the template for the demo to be updated and the chips to render correctly.
