### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular#1721]
### Description  
Cannot run tests

### Steps to reproduce  

1. `npm i`
2. `npm test:lib`

### Result  
![capture](https://user-images.githubusercontent.com/6439482/41910490-7d190bda-7952-11e8-90ca-83547be0b98e.PNG)
Text: ERROR in node_modules/@angular-devkit/core/node_modules/rxjs/internal/symbol/observable.d.ts(4,9): error TS2687: All declarations of 'observable' must have identical modifiers.

### Expected result  
Tests should run

**Comment by tiliev** [comment]
Updating `@angular-devkit/build-angular`, `@angular-devkit/build-ng-packagr` and `@angular-devkit/schematics` to `~0.6.8` resolves the issue.

**Comment by zdrawku** [comment]
This is caused by the following [commit](https://github.com/IgniteUI/igniteui-angular/commit/aa38587fdb63fb3d8b52f7a0dd6b9487a0a0878b#diff-32607347f8126e6534ebc7ebaec4853d). I am going to update the package-lock.json file with the latest versions
