### ISSUE TITLE
Entering edit mode then clicking on a cell throws an error on Edge & Firefox

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#1761]
### Description  
If you have a cell in edit mode then click on another cell in the grid nothing happens and a browser error is thrown (Edge&Firefox)

### Steps to reproduce  

1. Open the Cell Editing dev sample on Edge or Firefox
2. Enter edit mode for a cell
3. Click on another cell.
4. Observe the browser's console

### Result  
An error is thrown and the cell is not focused, check the screenshots

### Expected result  
No error is thrown and the clicked cell is focused

### Attachments  
![capture1](https://user-images.githubusercontent.com/2188411/42148839-6896cf42-7ddc-11e8-8bbc-66f2d4c6b043.JPG)
![capture2](https://user-images.githubusercontent.com/2188411/42148840-68b168ac-7ddc-11e8-8c79-e46241b6a798.JPG)

**Comment by ChronosSF** [comment]
@ddincheva , @zdrawku , @kdinev  - making the bug blocking and critical as this happens on Firefox too (thought it's Edge only) . Also you don't have to scroll out of view. It is very easy to reproduce and the error thrown means we have to fix this for the release.

**Comment by zdrawku** [comment]
@ChronosSF [this ](https://github.com/IgniteUI/igniteui-angular/issues/1667)is the same issue. I am currently working on it.

**Comment by ChronosSF** [comment]
@zdrawku , yes, you are right. I am closing this. Made the other one blocking instead.
