### ISSUE TITLE
Dropdown/Combo obscured in grid

### ISSUE THREAD

**Issue by jfineman** [IgniteUI/igniteui-angular#1765]
### Description  
Dropdown/Combo obscured in grid, not able to see it when in an open state

![image](https://user-images.githubusercontent.com/25512430/41982978-c60b60b0-79fa-11e8-8e95-01ae04b9fe27.png)

**Comment by SlavUI** [comment]
@jfineman Hi we are currently working on resolving this as it should be connected with the Dialog and the integration of the Overlay in it. I will confirm tomorrow if this is the case with the Dev team and will update the issue

**Comment by simeonoff** [comment]
@jfineman This should already be fixed with the official 6.1.0 release.
