### ISSUE TITLE
Horizontal scroll is broken if columns are pinned while a cell is being edited for columns that are not in the immediate view

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#1766]
### Steps to reproduce  

1. Open the Column Moving dev sample
2. Enter edit mode for a cell in the last column
3. Pin all the columns through the buttons
4. Try to scroll back to the cell in edit mode

### Result  
Scrolling causes the pinned columns to offset

### Expected result  
Scrolling should not be broken

### Attachments  
![updating-pinning](https://user-images.githubusercontent.com/2188411/41983529-097b6f02-7a37-11e8-96d4-89f55b2c4619.gif)

**Comment by MayaKirova** [comment]
Possibly the same as #1759
