### ISSUE TITLE
igx-grid - body becomes empty on igniteui-angular@6.1.0-beta.0

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1767]
### Steps to reproduce  

1. Unzip the attached sample: [igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2141828/igx-grid-app.zip)
.2. npm install
3. Replace node_modules/igniteui-angular with [igniteui-angular.zip](https://github.com/IgniteUI/igniteui-angular/files/2141832/igniteui-angular.zip), which is a `igniteui-angular@6.1.0-beta.0` built code,
4. ng serve -o

### Result  
Grid width and height are 100% against its parent div(dimension is 800px x 500px). But grid body is empty.
![image](https://user-images.githubusercontent.com/15909409/41983561-74bc5678-7a69-11e8-8d0e-81d65d072e6f.png)

### Expected result  
Grid body should not be empty.

**Comment by hanastasov** [comment]
It seems the displayDensity value also affects if the grid body will be empty or not.

**Comment by kdinev** [comment]
No need to copy/paste the package, just change the `package.json` version of igniteui-angular to `6.1.0-beta.0`. 

This seems to not be related to `displayDensity`. It reproduces even with 11 records, which should render a vertial scrollbar. With 10 records the data is visible - when there's no vertical scrolling.
