### ISSUE TITLE
Samples logo misspelled

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#1768]
### Description  
Angular spelled wrong\cut off in our samples logo.

### Steps to reproduce  
View Image
https://github.com/IgniteUI/igniteui-angular/blob/master/src/assets/images/rsrcs/igniteui-angular_logo.svg

### Result  
Image spells Angular, ANGULA

### Expected result  
Unless we are branding our product "IgniteUI for Angula", we should spell it correctly.

**Comment by simeonoff** [comment]
Hm, this is strange. Opening the image in my Chrome browser on MacOS, I see the following:

![screen shot 2018-06-28 at 12 02 33 pm](https://user-images.githubusercontent.com/4118303/42024658-5ed23816-7acb-11e8-94bd-4b761bef03c3.png)
Also this is how the samples look in the same browser and OS combination.
![screen shot 2018-06-28 at 12 04 21 pm](https://user-images.githubusercontent.com/4118303/42024727-8569352e-7acb-11e8-803d-36362d91f96f.png)

**Comment by kdinev** [comment]
@MikeTechSpeak It's actually "Ignite UI" not "IgniteUI" :)
