### ISSUE TITLE
Cell content overlaps the cell

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1769]
### Steps to reproduce  

1. Go to https://stackblitz.com/angular/dknvxamllrr
2. Enter some text in the search area, for example "Airlines"

### Result  
See how the content in the last cell stars overlapping the cell.

**Comment by gedinakova** [comment]
Fixed by https://github.com/IgniteUI/igniteui-angular/pull/1901

**Comment by DDavidkov** [comment]
Yeah, once you update the dependencies in stackblitz, the issue is no longer reproducible.
