### ISSUE TITLE
Filtering does not happen on input

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1770]
### Description  
Describe the issue.

### Steps to reproduce  

1. Go to https://stackblitz.com/angular/pakyexgxdrl
2. Scroll the grid horizontally to bring new column into view
3. Try to filter or sort any of the new columns
### Result  
No filtering happens until focus is lost

### Expected result  
Filtering to happens on input

**Comment by MayaKirova** [comment]
@hanastasov The sample has columns with the same keys. If you set unique column keys then this no longer reproduces.
Here's a sample with no duplicate keys:
https://stackblitz.com/edit/angular-tegms2?file=app/grid/multi-column-headers/multi-column-headers.html

**Comment by hanastasov** [comment]
Duplicate keys should not be a problem, displaying same field from the data source into more than one column is a valid scenario. Issue does not reproduce with duplicated columns when MHC are not there.

**Comment by MayaKirova** [comment]
Fine. But I would not consider this blocking since this is not a scenario that was ever planned or tested.
