### ISSUE TITLE
Cannot move columns when the grid page is scrolled vertically

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1778]
### Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-y51wxx-bnwdfc / https://stackblitz.com/angular/qmkbgexlmqy
2. Scroll the page a bit down, until the grid headers are at the top
3. Try to move some column - for example the "Contact Title", "Contact Name" or "CompanyName" column

### Result  
The element being dragged is not rendered at the place where dragging started. Also user is not able to drop it anywhere:
![moving](https://user-images.githubusercontent.com/14248932/42023601-ee845cd0-7ac8-11e8-8dfa-2c702e04a2dd.png)

**Comment by SAndreeva** [comment]
We will need another fix as window.scrollX and window.scrollY are not compatible with IE.

**Comment by SAndreeva** [comment]
Drag ghost on MCH is cut off in IE.

**Comment by zdrawku** [comment]
Fixed
