### ISSUE TITLE
Header template height is not considered when rendering the headers

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1779]
### Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-y51wxx-djbsoi

### Result  
The first child column of the Address Information group is templated to have a height of 600px:
```
                        <ng-template igxHeader let-column>
                            <div style="height: 600px">{{ column.field | lowercase }}</div>
                        </ng-template>
```

But the header is not 600px high.

**Comment by sstoyanovIG** [comment]
This is a limitation in the implementation of the multi-column headers. Currently we use the defaultRowHeight of the grid for the nested columns' heights.
