### ISSUE TITLE
Cell is not selected on click [IE]

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1780]
### Steps to reproduce  

1. Go to https://stackblitz.com/angular/ygyoladyeam
2. Hover over the first cell and the Agriculture text
3. Click to select the cell

### Result  
Cell is not highlighted as selected

### Expected result  
Cell to be highlighted as selected

**Comment by zdrawku** [comment]
Fixed in 6.1.0-beta.1

**Comment by zdrawku** [comment]
It is reproducable when trying to click on the cell text, not at the empty cell space. Bug is reproduced with the latest available version Fixed in 6.1.0-beta.1

**Comment by Lipata** [comment]
[This](https://stackoverflow.com/questions/51404782/focus-event-not-fired-on-focusable-custom-html-element-in-ie11-when-one-of-its) is an issue with IE11. As far as I understood it, bugs different from the Edge, are logged in StackOverflow, so I posted a question there. I'll close this when there is some answer to confirm it.

**Comment by Lipata** [comment]
As visible from the StackOverflow post, there are two options for the moment. 

1. Change cell `display` from `flex` to `block`.
2. Don't use `<div>` but other tag

I've also tried to set some other flex options, like `flex-basis` or `flex-grow` but it seems there is a problem with `flex` and IE11. @simeonoff if you think you can help with something, you are welcome. Will it be a problem to use `display: block` instead of `display:flex`.

**Comment by Lipata** [comment]
In this [issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14325016/), there are answers from MS team, saying that they don't support IE11 unless some security issues.

**Comment by Lipata** [comment]
@rkaraivanov is working on a grid improvements, where selection will be executed on a click not focus and this is supposed to be fix the current issue. I will close it, when I test the pull request for that change and see if the problem is resolved.

**Comment by rkaraivanov** [comment]
closed via #2289

**Comment by tkiryu** [comment]
Hi, @Lipata , @rkaraivanov , I found that this issue is still reproducible.
>@rkaraivanov is working on a grid improvements, where selection will be executed on a click not focus and this is supposed to be fix the current issue.

It seem that selection is still executed by focus event.

You can try it on online sample. 
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/virtualization.html

**Comment by zdrawku** [comment]
Fixed with the referenced PR
