### ISSUE TITLE
The last column in Column Resizing sample disappears.

### ISSUE THREAD

**Issue by alexalex972** [IgniteUI/igniteui-angular#1788]
### Description  
The last column disappears when you resize the previous ones to take large enough space.

### Steps to reproduce  

1. Open the Column Resizing sample on staging.
2. Resize the ID column as shown in the gif below.
3. Observe that the last column is missing.

### Result  
The last column disappears.

### Expected result  
The last column should not disappear.

### Attachments  
![columnresizing](https://user-images.githubusercontent.com/33548921/42032523-8112594e-7ae2-11e8-91bb-15560963de78.gif)

**Comment by SAndreeva** [comment]
It is probably a bug in virtualization.

@ChronosSF, @skrustev  what do you think?
