### ISSUE TITLE
Swipe scrolling on touch does not work on group rows.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#1790]
### Description  
Scrolling horizontally via swipe interaction on touch does not work on group rows.

### Steps to reproduce  

1. Run the demos dev samples and open them on touch device.
2. Open the GroupBy sample.
3. Group by some columns
4. Try to swipe right on a group row to scroll horizontally 

### Result  
The grid does not scroll.

### Expected result  
The grid should scroll the same way as when you swipe on a data row.

**Comment by ChronosSF** [comment]
The group row does not have a horizontal directive which scrolls it so it is questionable if we should do it at all.

@kdinev , what do you think?

On a separate note, if we do the performance improvement task to use a single directive for all horizontally scrolling rows, its handlers will be grid-wide and natively solve this issue.

**Comment by kdinev** [comment]
@ChronosSF I think this should be handled by setting a single directive for horizontally scrolling the grid.

**Comment by mpavlinov** [comment]
@kdinev @rkaraivanov did research the single directive option, but from what I remember the performance was not satisfactory. @rkaraivanov can you share your thoughts on the research.
