### ISSUE TITLE
Input line exceed cell width after date is selected on cell editing

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#1793]
### Description  
On date cell editing, after date is selected, the input 

### Steps to reproduce  

1. Open igniteui angular demos
2. Open grid cell editing sample
3. Edit a cell from OrderDate column
4. Select a date
5. Take a look of the image

### Result  
![image](https://user-images.githubusercontent.com/11193764/42038588-f91b7112-7af3-11e8-84ca-4c7fa5c04f4d.png)

**Comment by zdrawku** [comment]
This has to do something with the focus.

**Comment by hanastasov** [comment]
It rather seems like a styling issue.
