### ISSUE TITLE
Combo sample, searching triggers poor UX functionality.

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#1798]
### Description  
Describe the issue.

### Steps to reproduce  
Run Sample:
https://github.com/IgniteUI/igniteui-angular/tree/master/src/app/combo
Drop down
Scroll down
Then type Con, to find Connecticut

### Result  
The scroll position stays at it's lower point, but the scrollbar disappears and Connecticut is hidden outside the top bounds.
Additionally you cannot recover from the functionality without reloading the page.
  Deleting the value
   or typing something else, just wipes the search entirely
Also the close drop down stops working at that point. It closes and pop's back open with the same problem.
### Expected result  
Filtering should probably reset the scroll position to the top as you change the filter conditions.
Also none of the other bad stuff... :P

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/19844934/42056549-911c3f66-7ae8-11e8-95a4-13e8f9c66a42.png)

**Comment by MikeTechSpeak** [comment]
FYI, I noticed when I turned off Groups it worked fine.

**Comment by Lipata** [comment]
@MikeTechSpeak, there was an issue in the sample, which we resolved and I think your scenario is also fixed. Please check it. Thank you!

**Comment by MikeTechSpeak** [comment]
I grabbed the latest and it still does not work. Can you tag this with the bug fix, so that I can confirm I have it in the version that I am testing.

**Comment by Lipata** [comment]
@MikeTechSpeak I have fixed that with the pull request above.

Initially we had a logic in the combo that was [preserving the scroll position](https://github.com/IgniteUI/igniteui-angular/issues/1705) after the drop down was closed - then it was opened again on the same scroll position. This is good if you close the drop down unintentionally, but then there are several UX questions that are not easily resolved like - if we select several items and them scroll to an unselected item then what position we should save; if start to type (like you did with 'conn') and then should we scroll again to the top; after we clear the filtering text, should we scroll again to the previous position. On other hand even the position is lost, then using the filtering we can easily reach a new item we want to select. So for the moment we choose that option, and of course will review that for the future. What do you think?
