### ISSUE TITLE
When updating an input through the bound ngModel object the validation ins't applying.

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#1814]
### Description  
When updating an input through the bound ngModel object the validation ins't applying.

### Steps to reproduce  

1. Bind an input to ngModel and apply some validations on it.
2. Try to update the input value through the bound object/prop

### Result  
There is no indication whether the input is valid or not.

### Expected result  
The input should be marked as valid or invalid.

### Sample
[input-validation.zip](https://github.com/IgniteUI/igniteui-angular/files/2205393/input-validation.zip)

**Comment by bkulov** [comment]
When value of the input is changed through the form (ngModel, Reactive form) the validation UI should be shown only in case the value is invalid.
