### ISSUE TITLE
Escape key does not close the dialog.

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#1820]
### Description  
Escape key does not close the dialog. 

### Steps to reproduce  

1. Open the Overlay dev sample.
2. Press the "Toggle" button.
3. Press any key on the keyboard.
4. Press the ESC key

### Result  
The dialog does not close.

### Expected result  
The dialog closes.

**Comment by rkaraivanov** [comment]
Closed via #1883
