### ISSUE TITLE
 igx-grid - groupby and toolbar features can't be used together

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1834]
### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid

### Result  
Although groupable is set to true, grouping area is invisible. It is behind the toolbar. It means that groupby feature can't be used.

### Expected result  
groupby and toolbar features can be used together.

**Comment by ChronosSF** [comment]
This should already be fixed. I'll test it again with the upcoming beta 2 .

**Comment by ChronosSF** [comment]
Seems to work in beta1 https://stackblitz.com/edit/igx-grid-egfgtv

**Comment by tkiryu** [comment]
@ChronosSF , thank you for checking! I confirmed it too.

By the way, there might be an another issue. Toolbar overlay can't be hidden. The following warning is output.
> igxOverlay.hide was called with wrong id: undefined

Is this known issue?

**Comment by ChronosSF** [comment]
I am not sure. @gedinakova may know more.

**Comment by gedinakova** [comment]
@tkiryu 
The issue is not related to grouping and/or toolbar because the filter popup would also not close. It seems to be an angular [issue](https://github.com/angular/material2/issues/11875) related to animations. The problem would go away if the "@angular/platform-browser" package is updated to latest (6.0.7).

**Comment by tkiryu** [comment]
@gedinakova , thank you for the information. That's good to know.

I tried updating to angular@6.0.7, then the problem has gone!

Thank you so much!

**Comment by ChronosSF** [comment]
Seems the issue is good to be closed.
