### ISSUE TITLE
Row height

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1842]
Is there currently a good way of setting the row height? Couldn't find anything in either the theme docs or the grid docs. While the current height is quite "material", we often need to display large amount of data, and feel the need to have more compact grids.

I can achieve this by doing something like setting a height of .igx-grid__tr and then a negative margin to .igx-grid__td to adjust the content. But this feels kinda hackish. Also, it causes side effects, like the selected cell not displaying correctly.

![image](https://user-images.githubusercontent.com/12936286/42155409-a23181aa-7de8-11e8-9dc2-b11fbc8e8d65.png)

**Comment by SlavUI** [comment]
@Eralmidia we are releasing with the current release a dense grid theme :)  which makes the grid more compact if you have huge amount of data

**Comment by Eralmidia** [comment]
@SlavUI  Thank you. You're on top of things as usual ;) is this a flag only, or do we have control over how dense dense actually is?

**Comment by SlavUI** [comment]
@Eralmidia at the moment you will not have control over how dense it will be

**Comment by Eralmidia** [comment]
Ok, thanks. I'll take a look at it when 6.1 is out, and add a feature request if it doesn't fit our needs :)
