### ISSUE TITLE
Tab navigation breaks the grid's layout

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-angular#1848]
When pressing Tab in the grid and the focus is getting out of view the grid's layout is broken. Headers doesn't correspond to columns content and the pinned columns are out of view.

### Steps to reproduce  

I'm using the business propeller sample.
1. Select a cell on the first row.
2. Press Tab key until the last visible cell on the same row is focused.
3. Press Tab key again.

### Result  
The grid's layout is broken:
![animation_bad](https://user-images.githubusercontent.com/2705882/42163449-519257ba-7e0b-11e8-93f6-25cd7312e2a8.gif)

Scroll backwards with Shift + Tab:
![animation](https://user-images.githubusercontent.com/2705882/42164311-58fa83ee-7e0e-11e8-8a7e-23a612665cdb.gif)

### Expected result  
The selection should go to the first cell of the next row.
![animation_ok](https://user-images.githubusercontent.com/2705882/42163461-5dcc57c4-7e0b-11e8-8736-acad4bba8e65.gif)

**Comment by bkulov** [comment]
Might be related to this #1420.

**Comment by mpavlinov** [comment]
Closing this one as it will be developed as part of #1420. The break in the grid layout is fixed in #1781 , but wrapping is not implemented there.
