### ISSUE TITLE
igx-linear-bar is not visible when inside igx-grid

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1859]
### Description  
Describe the issue.

### Steps to reproduce  

1. Go to https://stackblitz.com/angular/vmraqemkveg
2. The igx-linear-bar in the Track Progress column is not visible

### Expected result  
To be visible

**Comment by simeonoff** [comment]
@hanastasov This is not a bug. Give the templated cell some context like width. Since the template you pass sits inside a parent flex element, it needs to have some width set to it for it to work.
