### ISSUE TITLE
Grid with 100% height will incorrectly exceed its parent container if the total row height is smaller than it

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#1861]
### Description  
The grid bases its percent height rendering only on the total row height which means that it will exceed the container it is put in by potentially the full height of its headers, pager, summaries, group area, toolbar, etc as long as it doesn't have enough ***data*** rows to fill in that parent container.

### Steps to reproduce  

1. Open the Summaries dev sample, wrap the grid in a container with height 500px. Set the height to 100%

```html
<div style="height: 500px">
     <igx-grid #grid1 [data]="data" [autoGenerate]="false" displayDensity="compact" height="100%" width="600px" (onColumnInit)="initColunm($event)" [paging]="true">
     ...
</div>
```

2. Observe the sample

### Result  
The grid renders in a total of 611 pixels instead of the expected 500 to fit its parent container

### Expected result  
The grid to render with 500px height

### Attachments  
![untitled](https://user-images.githubusercontent.com/2188411/42205209-7582a516-7eac-11e8-87ae-d018982372a0.png)

**Comment by MartinKamenov** [comment]
@ChronosSF 
Couldn't reproduce the issue in master.
![heightfixed](https://user-images.githubusercontent.com/24592428/50824073-3e8f7580-133e-11e9-82e1-4419ce355f52.JPG)

**Comment by mpavlinov** [comment]
I can successfully reproduce it. Div height should be 800px
