### ISSUE TITLE
Search match highlight not always scrolled into view

### ISSUE THREAD

**Issue by rmkrmk** [IgniteUI/igniteui-angular#1886]
### Description  
The search match highlight is not always scrolled into view when a horizontal scrolling is required.

### Steps to reproduce  

1. Run the attached sample app
2. Type "ne" in the "Search API" box on the right
3. Click the "Find next" button until the ORANGE highlight is on the "Wayne" word
4. Click one more time the "Find next" button

### Result  
The grid tries to scroll right to show the next match but it is not scrolling enough.

### Expected result  
The grid should scroll enough horizontally so that the "Company" column is visible as well as the orange highlight in it.

### Attachments  

[gridsample2.zip](https://github.com/IgniteUI/igniteui-angular/files/2159386/gridsample2.zip)

**Comment by gedinakova** [comment]
The issue is stably reproduced when grid columns have different widths set. 

[grid-crm-sample.zip](https://github.com/IgniteUI/igniteui-angular/files/2163705/grid-crm-sample.zip)
