### ISSUE TITLE
igxCombo list is not rendered correctly under Edge (42.17134.1.0)

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-angular#1894]
### Description  
igxCombo list is not rendered correctly under Edge
### Steps to reproduce  

1. Navigate to the combo sample under Edge
2. locate Toggle features combo
3. Click fast 5-6 times on the dropdown button

### Result  
The dropdown remains on opened state, but the dropdown is not visible

### Expected result  

The dropdown be visible and the combo works as expected. 

### Attachments  
![image](https://user-images.githubusercontent.com/4228115/42226401-8a936dd8-7ee7-11e8-904f-b173461ac267.png)

![image](https://user-images.githubusercontent.com/4228115/42226481-bb01e544-7ee7-11e8-8281-4d4cd8c11e82.png)

**Comment by wnvko** [comment]
This is actually an issue in MS Edge which is logged here
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18151136/

**Comment by kdinev** [comment]
Closing the issue. Please follow the link @wnvko provided and upvote the Edge issue.
