### ISSUE TITLE
An existing item can be added as "custom value" when Filtering is disabled

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-angular#1899]
### Description  
When you have Filtering disabled and type an existing value inside the input, the "ADD ITEM" button appears and you are allowed to add the existing value as a custom one. This is reproduced only the first time an existing item is entered. If you add this existing item as a custom one and try to do the same for any other of the existing items - the "ADD ITEM" button will not show.

**Note**: In addition, actual custom values cannot be submitted after the first time, which looks like the very same issue

### Steps to reproduce  

1. Navigate to https://staging.infragistics.local/products/ignite-ui-angular/angular/components/combo.html#usage
2. Disable the Filtering for the combos in the sample that is inside this section of the topic
3. Open the "Toggle Features" combo
4. Type "Maine"
5. Press "ADD ITEM"

### Result  
Maine is added at the end of the list

### Expected result  
"ADD ITEM" button should not be shown

### Attachments  
![screenshot](https://user-images.githubusercontent.com/2778393/42228864-b3531dc6-7eed-11e8-960e-d08b79638884.png)

**Comment by bazal4o** [comment]
Closing the issue, because the PR won't close it until merged to master
