### ISSUE TITLE
Setting ripple duration input property does nothing

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#1905]
### Description  
When using the the igxRippleDuration property on an igxRipple directive, the value set has no effect on the duration of the ripple animation.

### Steps to reproduce  

1. Set igxRipple directive on any element.
2. Set igxRipple duration property on the same element to a a certain value.

### Result  
The ripple animation duration doesn't change regardless of what value is passed to the igxRippleDuration property.

### Expected result  
The ripple animation duration should respect the value passed to the igxRippleDuration property.

**Comment by kdinev** [comment]
@simeonoff Is this a regression?

**Comment by simeonoff** [comment]
@kdinev, no. It was a bug we haven't caught before.
