### ISSUE TITLE
Combo is not visible when droped down in Edge 42.17134.1.0

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#1917]
### Description  
Combo is not visible under Edge 42.17134.1.0 when is in iframe and there is hidden input in the iframe.

### Steps to reproduce  

1. Go to staging samples and open combo sample here;
2. Drop down any combo.

### Result  
Combo is not visible. The visual part of the combo is positioned somewhere down in the page, but the interaction are in place, e.g. if you tab to a combo, click down arrow four times, click space-bar and then enter combo will select an item.

### Expected result  
Combo should be visible.

### Attachments  
![untitled](https://user-images.githubusercontent.com/5990334/42276094-2b6a5916-7f9b-11e8-8d06-fcd2c4323c99.png)

**Comment by bazal4o** [comment]
Duplicate to #1894
