### ISSUE TITLE
Grid rows disappear when you scroll the grid back in view

### ISSUE THREAD

**Issue by DDavidkov** [IgniteUI/igniteui-angular#1924]
### Description  
When you scroll a grid in and out of view, its rows disappear

### Steps to reproduce  

1. Go to the DataGrid sample ("Boston Marathon 2018") in staging
2. Wait for its data to load and then scroll the grid out of view
3. Scroll the grid back in view

Note that you may need to do that a few times as it doesn't happen every time. I wasn't able to pinpoint exactly what causes the issue.

### Result  
The grid rows have disappeared

### Expected result  
The grid rows are still there

### Attachments  
![gridrowsdisappear](https://user-images.githubusercontent.com/25929663/42280813-74f7a26e-7faa-11e8-831b-81e8a5292156.gif)

**Comment by hanastasov** [comment]
A consistent reproduction of the issue is when you page the grid after scrolling the grid back in view.

**Comment by Aleksandyr** [comment]
Issue is not caused by the grid but from the sample so the issue was copied there.
Reference : [#449](https://github.com/IgniteUI/igniteui-angular-samples/issues/499)
