### ISSUE TITLE
igx-grid - In IE11, an error is thrown when grouping a column

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1940]
### Description  
In IE11, an error is thrown when grouping a column.

 * igniteui-angular version: 6.1.0-beta.1
 * browser: Windows 10 IE11

### Steps to reproduce  

1. Unzip the attached file
2. npm install
3. ng serve
4. Open in IE11
5. Open the dev tool.
6. Drag a column

### Result  
6. The following error is thrown when grouping a column. 
> SCRIPT5007: Unable to get property 'length' of undefined or null reference
As a result, I cannot group a column in IE11.

When I used `igniteui-angular@6.1.0-beta.0`, there was no error.

### Expected result  
There is no error, and I can group a column in IE11.

### Attachments  
[igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2166499/igx-grid-app.zip)

**Comment by mpavlinov** [comment]
@tkiryu I cannot replicate it on the staging samples. Can you check with [igniteui-angular@6.1.0](https://www.npmjs.com/package/igniteui-angular/v/6.1.0)

**Comment by tkiryu** [comment]
@mpavlinov , I've updated to `igniteui-angular@6.1.0` and the issue has gone.

Thanks!
