### ISSUE TITLE
Choosing a month in calendar increases the component height

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#1942]
### Description  
When click on a month to choose another one the height of the component becomes bigger.

### Steps to reproduce  
1. Open this sample in stack blitz https://stackblitz.com/angular/qmqmqxqreng
2. In single selection calendar click on the month.

### Result  
The height of the component becomes bigger.

### Expected result  
Component should not increase its size and all the months should be visible.

### Attachments  
![image](https://user-images.githubusercontent.com/5990334/42323458-eafb42b8-8068-11e8-833c-f47294028ceb.png)
![image](https://user-images.githubusercontent.com/5990334/42323471-f58938b6-8068-11e8-9fca-85fe6daadf21.png)

**Comment by simeonoff** [comment]
@wnvko This is by design.
