### ISSUE TITLE
Grid - Row Selection - Row Selection Checkbox Navigation

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#1955]
### Description  
There is currently no way to reach the grid row selection checkbox via keyboard navigation.
 * igniteui-angular version: 6.1.0
 * browser: all

Previously, Shift + TAB / TAB could be used to enter the selection column by using the default browser key handling. This will need to be removed so that [enhanced cell navigation](https://github.com/IgniteUI/igniteui-angular/issues/1420) can be implemented.

Need to add navigation logic that handles:
 - Movement from very first cell to checkbox
 - Movement from checkbox to very first cell
 - Movement from checkbox to next/previous checkbox
 - Key handler for selection of row regardless of current focused cell (?)

Related: #1420, #1937
### Steps to reproduce  

1. Open the grid selection DevSample
2. Select the first cell on any row
3. Hit Shift + TAB

### Result  
The selection checkbox is not focused

### Expected result  
The selection checkbox is should be focused

**Comment by SlavUI** [comment]
@ViktorSlavov  i think this should be closed as this is fixed ?

**Comment by ViktorSlavov** [comment]
@SlavUI 
Thanks for pointing this out! With the latest changes to the cell navigation, this is indeed resolved.
Closing.
