### ISSUE TITLE
Feature request: routing support for igxTabs

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1957]
### Description  
It would be great if the tabs component could support routing, meaning that each tab represents it's own route, similar to the nav mat-tab-nav-bar of material (described on https://material.angular.io/components/tabs/overview#tabs-and-navigation). This would allow back-button support for child routes within a tab for instance.

**Comment by bkulov** [comment]
After we discussed this issue we decided not to implement this feature into the `igxTabs`. This should be implemented on application level. We will create a sample application demonstrating how to implement routing for `igxTabs` on application level.

**Comment by Eralmidia** [comment]
Ok, thanks. I actually proposed this based on the material2 library already having this. But after testing it, we have seen some unwanted effects by this and have abandoned this route of implementing things. I'm sure a sample of how to do it would suffice. I'll leave it to you to close this when suited.
