### ISSUE TITLE
Remove reflow grid invocation from some setters into the grid component

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#1961]
### Description  
Do we really need the invocation of **calculateGridSizes** from every setter pointed below?
 ```typescript
 if (this._ngAfterViewInitPaassed) {
    this.calculateGridSizes();
}
```
setters:

1. toolbarTitle
2. exportExcel
3. exportCsv
4. exportText
5. exportExcelText
6. exportCsvText

**Comment by rmkrmk** [comment]
I think these invocations are no longer necessary. Initially when we created the toolbar it was able to be shown/hidden using any of these setters. Later we changed the implementation and now only "showToolbar" is able to change its visibility. You can remove the above invocations from the above mentioned setters.

**Comment by SlavUI** [comment]
@Aleksandyr should we close this question now as it seems answered ?
