### ISSUE TITLE
Filtering UI menu themes don't work

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#1963]
### Description 
The 
 * igniteui-angular version: 6.1.0
 * browser: All

### Steps to reproduce  

1. Create a grid filtering UI theme using Sass and set its background to a color different than white.
2. Pass the theme to the igx-grid-filtering mixin and scope it to a specific grid sample.

### Result  
The theme is not applied due to a structural change. The theme relies on a class being present on the host element, but the toggle directive is applied on an inner element in the template of the filtering UI component.

### Expected result  
The theme for the filtering UI should apply regardless of the fact it is in an overlay container.

**Comment by sstoyanovIG** [comment]
This is fixed by this PR #2427
