### ISSUE TITLE
igx-grid 'onSelection' on key-up instead of key-down

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1969]
### Description  
I have a igx-grid, when I select a row I do a call to the api to get the details of that row.
When I use the arrow keys I can go up or down a row.
When I hold down the key, for each row that is passed a call is done to my api, it would be beter that you select the row on key-up instead of key-down.

 * igniteui-angular version: 6.1.0
 * browser: Chrome

### Steps to reproduce
1. Create an igx-grid & add some data
2. In the handle event, do a call to the api (or console.log)
3. Select the first row
4. Keep the button down

### Result  
For each row that is 'selected' a cal is done.

### Expected result  
When the user releases the key, then fire 'onSelection'.

**Comment by kdinev** [comment]
@Hypenate onSelection is thrown when an `IgxCellComponent` is focused, and focus is given on keydown. We can't really change this.

**Comment by Hypenate** [comment]
HTML
```
   igx-grid (keyDown.arrowUp)="isKeyUp(false)" (keyDown.arrowDown)="isKeyUp(false)"
              (keyUp.arrowUp)="isKeyUp(true)" (keyUp.arrowDown)="isKeyUp(true)"
              (onSelection)="handleRowSelection($event)">
```

Angular
```
  private keyUp: boolean = true;

  public handleRowSelection(event: any): void {
    const targetCell: any = event.cell;

    //Reset selection
    this.grid1.deselectAllRows();
    this.grid1.selectRows([targetCell.row.rowID]);

    if (this.keyUp) {
      let selected: any = event.cell.row.rowData;
      this._someService.get(selected.id).then(result => this.someDetails = result);
    }
  }
```
```
  public isKeyUp(keyUp: boolean) {
    this.keyUp = keyUp;

    //This might cause a duplicate call in some scenarios, but the release of keydown happens after handleRowSelection() is handled.
    if (keyUp) {
      let selected: Header = this.grid1.selectedRows()[0];
      this._someService.get(selected.id).then(result => this.someDetails = result);
    }
  }
```
