### ISSUE TITLE
Can't bind to 'isDisabled' since it isn't a known property of 'igx-datePicker'

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1970]
### Description  
After upgrading from 6.0.4 to 6.1.0 I get the error:
> Can't bind to 'isDisabled' since it isn't a known property of 'igx-datePicker'

The [documentation ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date_picker.html )states it's still available

 * igniteui-angular version: 6.1
 * browser: Chrome

### Steps to reproduce  
3. `<igx-datePicker [isDisabled]="true"></igx-datePicker>`

### Result  
I get an error:
> Can't bind to 'isDisabled' since it isn't a known property of 'igx-datePicker'

### Expected result  
Works like before

**Comment by Aleksandyr** [comment]
@Hypenate We have made a big change where we are renaming all properties that are connected with  disabled mode due consistency between components. We have documented this into the [CHANGELOG](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md) section as Breaking change.
I have logged an [issue ](https://github.com/IgniteUI/igniteui-docfx/issues/558) about the following observation (updating the documentation)
Sorry about the inconvenience..
