### ISSUE TITLE
DisplayDensity does not work

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1973]
### Description  
When I set the `displayDensity `on the grid nothing happens.
Although #1543 states this is for the rows, the [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html#known-limitations) states otherwise?

Nonetheless, when settings the DisplayDensity to Compact, no changes happen.

 * igniteui-angular version: 6.1.0
 * browser: Chrome

### Steps to reproduce
1. `<igx-grid #grid1 [data]="YourData" [displayDensity]="compact">`

### Result  
`displayDensity `does not work

### Expected result  
Working `displayDensity`

**Comment by rkaraivanov** [comment]
The values for passed for `displayDensity` are of type string. Either pass it as `[displayDensity]="'compact'"` or as `displayDensity="compact".

Here is a [sample](https://stackblitz.com/edit/angular-hfb9x2)

**Comment by Hypenate** [comment]
`[displayDensity]="'compact'"` in HTML does the trick!
