### ISSUE TITLE
Bottom of letters fall of in the label of igx-tabs-group

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1978]
### Description  
Letters are aligned too low in the igx-tabs.
In the screenshot you can see that the letters 'abc' are fine but 'gjy' are not

 * igniteui-angular version: 6.1
 * browser: Firefox

### Steps to reproduce  

1. Add igx-tabs
2. Add a igx-tabs-group in igx-tabs
2. Add a label to the igx-tabs-group

### Result  
The lower end of the letters fall off.

### Expected result  
Letters are fully shown

### Attachments  
![image](https://user-images.githubusercontent.com/7478681/42506454-3cd65d48-8442-11e8-9eb3-d42495ca5409.png)

**Comment by sboykova** [comment]
Reproducible to different extend in all browsers - most visible in IE.
