### ISSUE TITLE
Content goes over a control when using a splitter

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1979]
### Description  
When sliding the SplitterJS, content goes 'over' the grid.

 * igniteui-angular version: 
 * failing browsers: Firefox and Edge
 * working browsers: Chrome and IE

### Steps to reproduce  
1. Add a igx-grid
2. Add [SplitterJS](https://nathancahill.github.io/Split.js/)
3. Add igx-tabs
4. ngServce
5. Slide

### Result  
Content goes over the grid

### Expected result  
Same as in Chrome, content moves up

### Attachments  
1. The start
![image](https://user-images.githubusercontent.com/7478681/42506857-72965612-8443-11e8-8cfc-f485a5672b35.png)

2. After sliding
![image](https://user-images.githubusercontent.com/7478681/42506923-a823f942-8443-11e8-9219-ea33f5fd7a6c.png)

**Comment by Aleksandyr** [comment]
@Hypenate Could you please prepare some isolated sample which reproducing the issue. Because I had a bit of struggle with configuring the  [SplitterJS](https://nathancahill.github.io/Split.js/) library.
You may try to modify [this ](https://run.stackblitz.com/api/angular/v1) sample for the purpose.

**Comment by Aleksandyr** [comment]
@Hypenate I wasn't able to reproduce your issue. You can refer to the [Stackblitz ](https://stackblitz.com/angular/robvxmrkrkq?file=app%2Fgrid%2Fgrid-sample-3%2Fgrid-sample-3.component.html) sample and see that everything works fine.

**Comment by Aleksandyr** [comment]
@Hypenate I wasn't able to reproduce your issue.
