### ISSUE TITLE
💎 Grid - Sorting - styling on header cells

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/igniteui-angular#2004]
### Description  
To better fit Material Design guidelines and to improve user experience, several changes are proposed:
- [ ] Change font color of a header cell on hover to grays 900
- [x] Make the sorting arrow appear on hover on applicable header cells at 54% black.
- [x] Make the active sorting arrow at primary 500
- [ ] Rotate (animate) the active sorting arrow when changing its state
- [ ] Change font color of a header cell when sorted to grays 900

![grid-sorting-hover](https://user-images.githubusercontent.com/13866657/42693560-3351dff4-86b8-11e8-9fb9-da68d8adb188.gif)

**Comment by SDinev** [comment]
Preview of hovering when the column header is longer and needs ellipsis. This behavior allows us to show more of the header text in a rest state, making the grid easier to read. 

![sorting-ellipsis](https://user-images.githubusercontent.com/13866657/42697542-0e2992ba-86c4-11e8-8f96-992521d428f7.gif)

**Comment by simeonoff** [comment]
@desig9stein let's discuss.

**Comment by DaniMarinov** [comment]
I recommend the following behavior for a sortable cell:
- on hover (mouseover) everywhere on the **whole** cell appears arrow icon which indicates that the column is sortable
- sorting would be triggered **only** after clicking on the very icon in the right end of the cell
