### ISSUE TITLE
When delete all records in the last page pager should be changed

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2014]
### Description  
When delete all records in the last page pager should be changed

### Steps to reproduce  

1. Open https://www.infragistics.com//angularsite/components/grid_editing.html
2. Go to the last page
3. Delete all records in the page

### Result  
Page is not changed and it displays 2 of 1

### Expected result  
Page should be changed to previous 

![image](https://user-images.githubusercontent.com/11463104/42758440-34fb8912-890c-11e8-9eb6-bf08711a0f48.png)

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by bkulov** [comment]
Duplicated issue #2015
