### ISSUE TITLE
When the last single item from the last grid page gets deleted the page index shown is incorrect

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#2015]
### Description  
When a single item has left on the last grid page and it gets deleted, the current page index is bigger than the number of pages

 * igniteui-angular version: 6.1.0
 * browser: All

### Steps to reproduce  

1. Open the Grid Editing sample: [https://www.infragistics.com/angularsite/components/grid_editing.html](url)
2. Add a new item 
3. Go to the third page - it should have only 1 item
4. Delete it

### Result  
The grid shows it is on page 3 of 2 

### Expected result  
The grid should go to the previous page and show "page 2 of 2" 

### Attachments  

![sketch](https://user-images.githubusercontent.com/18643062/42759973-6f1fbe9c-8911-11e8-8678-2ef73f13a34c.png)

**Comment by bkulov** [comment]
Closing this issue as duplicate to #2014 .
