### ISSUE TITLE
The combo list always opens at the top in IE11

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-angular#2022]
### Description  
The combo list opens at the top item position even if scrolling was executed before closing it.

 * igniteui-angular version: 6.1.1
 * browser: IE11

### Steps to reproduce  

1. Navigate to https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo.html
2. Open any of the combo controls and scroll down a bit
3. Close the combo
4. Open the combo again

### Result  
The combo list opens at the top position

### Expected result  
The combo list should open at the position it was closed at.

**Comment by ViktorSlavov** [comment]
Closing this as it seems to be a third party issue.

This seems to be a third party issue cause by [inputs with placeholders in IE firing change events on focus](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/).
The handleChangeEvent is called with an empty value every time the combo list is dropped down (and the filter is reset)

The issue can also be observed in IE with the following steps (on the first combo control in demos):
Drop down -> Blur search (click on scrollbar) -> Scroll to the middle of the list (w/o typing anything) -> Focus Input => Scroll is reset
Drop down -> Type "e" in search -> Blur search -> Scroll to middle of list -> Focus Input => Scroll is not reset.

Related issues:
[Microsoft Open Issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/)
[Angular Open Issue](https://github.com/angular/angular/issues/17951)
