### ISSUE TITLE
6.1.1 error on npm install

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#2023]
### Description  
I downloaded the new 6.1.1 to rebuild my sass theme docs for the new components, but I'm getting an error during the npm module install.

 * igniteui-angular version:  6.1.1

### Steps to reproduce  

1. Download 6.1.1 from https://github.com/IgniteUI/igniteui-angular/releases
2. Run npm install

### Result  
![image](https://user-images.githubusercontent.com/12936286/42808629-003b13a2-89b4-11e8-8ddf-85beb1eac8b7.png)

**Comment by kdinev** [comment]
@Eralmidia The docs are not available because we haven't applied a custom theme to them yet. This is currently in development. We will look into why you're getting this error.

**Comment by Eralmidia** [comment]
Ok, so the generation of docs is just temporary then? Good to hear. Do waste too much time on this :) If there are are any theme available for the new dropdown and combo components, a screenshoot of the available theme function will do as well. If not, we'll just leave it unthemed for now. It's still a couple of months until our next release. No rush ;)

**Comment by kdinev** [comment]
Run the install twice, and the second time you shouldn't get the error. Then you would be able to build the docs.

Otherwise @simeonoff can provide you with screenshots.

**Comment by Eralmidia** [comment]
No luck running it twice I'm afraid.

**Comment by kdinev** [comment]
@Eralmidia As @kdawg1406 prompted me, if you do `git init` on the folder then `npm install` will run without the error.

**Comment by Eralmidia** [comment]
Perfect, that works :) Thanks. I'll close down this issue then, as this is handled in #2030.

**Comment by Aleksandyr** [comment]
@Eralmidia I have reopened the issue because #2030 is the PR which fixes it. We are going to close this issue when the PR gets merged.

**Comment by Aleksandyr** [comment]
Closing the issue after merging the [PR](https://github.com/IgniteUI/igniteui-angular/pull/2030)
