### ISSUE TITLE
Filter icon in the header changes its position

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#2036]
### Description  
Describe the issue.

 * igniteui-angular version: 6.1.1
 * browser: all

### Steps to reproduce  

1. Open grid virtualizaion and perofrmance sample in the samples browser (https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html)
2. Filtering icons the the numeric columns like Change  column are positioned on the left
3. Start scrolling the grid horizontally

### Result  
When the first column goes out of view the position of the filter icon in the Change and other columns changes and goes to the left

### Expected result  
No change in the header layout

**Comment by nrobakova** [comment]
This issue is reproducible when headerClasses is set for a column.
There is similar issue when cellClasses is set.
Both scenarios should be tested.
