### ISSUE TITLE
IgxDropDown Item cannot be set as selected.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#2061]
### Description  
There's no option that allows to pre-select an item from the igx-drop-down.
There's an `isSelected` option, however it currently only has a getter.

### Result  
Cannot pre-select a drop-down item.

### Expected result  
Users should be able to pre-select an item from the drop-down, for example something like:

    <igx-drop-down>
        <igx-drop-down-item  isSelected='true'>
            1
        </igx-drop-down-item>
        <igx-drop-down-item>
            2
        </igx-drop-down-item>
    </igx-drop-down>

**Comment by wnvko** [comment]
This is by design. The only way now to set the selected item is through calling setSelectedItem(index) method of IgxDropDownComponent. You cannot set selected item in markup.
