### ISSUE TITLE
In carousel when call method remove for selected slide it is still previewed

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2182]
### Description  
In carousel when call method remove for selected slide it is still previewed

### Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-ncldde?file=app/carousel-sample-1/carousel-sample-1.component.ts
2. Click on button Remove Slide

### Result  
Slide 1 is removed, but the carousel still displays it.

### Expected result  
When the current slide is removed, next slide should be selected

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by rmkrmk** [comment]
Adding a sample application.
[CarouselTest1.zip](https://github.com/IgniteUI/igniteui-angular/files/2253722/CarouselTest1.zip)
