### ISSUE TITLE
Blank space on the right of igxGrid when there is a hidden column and grid width is 100%

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#2249]
### Description  
There is a blank space on the right when there is a hidden column, grid width is 100% and columns do not have width set.

 * igniteui-angular version: 6.1.2
 * browser: All browsers

### Steps to reproduce  

1. Given the following grid configuration (taken from [here](https://staging.infragistics.local/products/ignite-ui-angular/angular/components/integration_excel.html#paste-from-excel))

```
    <igx-grid #grid1 [data]="data" [width]="'100%'" [height]="'505px'" [autoGenerate]="false" paste-handler (onDataProcessed)="dataPasted($event)" [primaryKey]="'ID'">
        <igx-column [field]="'ID'" [hidden]="true"></igx-column>
        <igx-column [field]="'Name'"></igx-column>
        <igx-column [field]="'Title'"></igx-column>
        <igx-column [field]="'Phone'"></igx-column>
        <igx-column [field]="'Country'"></igx-column>
    </igx-grid>
```

2. Use the configuration in [this](https://github.com/IgniteUI/igniteui-angular-samples/blob/master/src/app/grid/grid-paste/grid-paste-sample.component.html) sample
3. Run the sample and observe the result

Note: This is only reproduced in igniteui-angular version 6.1.2

### Result  
There is a blank space on the right

### Expected result  
There should be no blank space

### Attachments  
![image](https://user-images.githubusercontent.com/6794133/43570712-aaad2654-9643-11e8-9bce-cb2c562d2b98.png)

**Comment by ddincheva** [comment]
the issue is still reproducible in versions 6.2.0 and 6.1.4, also the fix causes the following [regression](https://github.com/IgniteUI/igniteui-angular/issues/2516)
