### ISSUE TITLE
Is "date" a reserved css class name?

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/igniteui-angular#2287]
### Description  
If I create a CSS class and call it "date" it appears to combine with another date class defined somewhere else that I'm not aware of.

 * igniteui-angular version: 6.1.2
 * browser: Google Chrome 67.0.3396.99

### Steps to reproduce  

1. Run sample here: https://stackblitz.com/edit/angular-7rzufe

### Result  
The Date text is positioned weirdly.  Look at the .date class in the chrome debugger and there are other CSS properties attached to the class that I did not specify.

### Expected result  
I should be able to use a css class named "date" unless it is reserved.  In that case, is this documented somewhere?

**Comment by simeonoff** [comment]
@ig-robstoffers Yeah, this is definitely not desired. We will update the class names. Good thing those are outliers, we usually don't have class names like these.
