### ISSUE TITLE
Overlay modal is lower z-index than list items default

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#2307]
### Description  
If I have a modal dialog opened and list items below, then the list items are above the overlay.

 * igniteui-angular version: 6.1.2
 * browser: Chrome

### Steps to reproduce  

1. Create an new angular app with the CLI
2. Add a list
3. Add a modal dialog and open it in the list view

### Result  
You can see the list items above the modal overlay.

### Expected result  
List items shouldn't be on top.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/43643555-4d4fef7c-9734-11e8-9f4f-32f287866bd3.png)

**Comment by damyanpetev** [comment]
@kdinev You can also 'contain' elements with `z-index` by updating the `.main` container rule with `z-index: 0;` to create a separate stacking context for the page content.Could even add that to the Ignite UI CLI project defaults even if such solution is reasonable.
