### ISSUE TITLE
Japanese character is redundantly inserted into textbox on filter dialog on Safari

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#2316]
### Description  
As Japanese character is being typed, typed characters are inserted repeatedly.

 * igniteui-angular version: 6.1.2
 * browser: Safari on iOS / OS X

### Steps to reproduce  
1. Build the attached sample with the following command:
 * ng build --base-href "/my-app1/" --prod
2. Host the attached sample on IIS (or serve it from your machine by `ng serve --host 10.14.1.129` replacing the ip address with yours)
3. Open the sample on iOS Safari
4. Open the filter dialog on "name" field
5. Type 'あ' (a on English keyboard)
6. Type 'い' (i on English keyboard)

### Result  
'ああい' is inserted into the filter textbox

### Expected result  
'あい' is inserted into the filter textbox.

### Attachments  
[my-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/2261279/my-app1.zip)

### Note
iOS version is 11.4.1 (15G77). This is not reproduced on Chrome on Windows 10.

**Comment by bkulov** [comment]
Browsers are using `CompositionEvent` to handle indirect text input such as Japanese. However `CompositionEvent` is not fully supported for Safari. That's the reason for this behavior. Probably the composition events are not fired in the proper order. Check the following link for more information:
https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent

**Comment by ymita** [comment]
@bkulov 

The behavior is reproducible on Chrome browser on iPad. It means this is not limited to Safari browser.

I also notice that the igx-input for grid's global filter has no problem typing Japanese characters on both Safari and Chrome. Can you consider fixing this behavior of igx-input on filter dialog? You can observe the difference using this online sample.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html


![image](https://user-images.githubusercontent.com/14340675/44069315-18a52a02-9fb9-11e8-9dfb-06326aa6e49a.png)

**Comment by bkulov** [comment]
@ymita thanks for the clarification. Will take a look.
