### ISSUE TITLE
Circular Progress doesn't accept floating point values

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#2328]
### Description  
When I set a floating point value to the `IgxCircularProgressBarComponent`, the component mishandles it.

 * igniteui-angular version: 6.1.2
 * browser: Chrome

### Steps to reproduce  

1. Create a circular progress bar
`<igx-circular-bar class="icon-avatar" [value]="37.79" [max]="100" [animate]="true" [textVisibility]="true"></igx-circular-bar>`
2. Set it's value to `37.79` or any other floating point, and set max to `100`

### Result  
The progress bar fills to maximum.

### Expected result  
The progress bar should show the progress.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/43724828-a31e9dc4-99a3-11e8-928b-228ee7cd57dd.png)

**Comment by ddincheva** [comment]
Resolved with PR #2327
