### ISSUE TITLE
Circular progress bar animation duration grows with the max value

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#2329]
### Description  
The animation duration of the circular progress becomes bigger, as the max value grows.

 * igniteui-angular version: 6.1.2
 * browser: Chrome

### Steps to reproduce  

1. Create a progress bar
`<igx-circular-bar class="icon-avatar" [value]="378" [max]="1000" [animate]="true" [textVisibility]="true"></igx-circular-bar>`
2. Set the max value to `1000` and the value to `900`

### Result  
The animation takes ~20 seconds

### Expected result  
The animation duration shouldn't get affected

**Comment by ddincheva** [comment]
Resolved with PR #2327
