### ISSUE TITLE
Feature request: Using text field input for date and time picker

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#2337]
### Description  
When using the date and time picker, it seems it is currently only possible to use the popup to select a date. Both controls should support keyboard inputs as well, similar to https://eonasdan.github.io/bootstrap-datetimepicker/ for instance.

**Comment by bkulov** [comment]
We already had planned to implement this. This is the spec for the time picker:
https://github.com/IgniteUI/igniteui-angular/wiki/Time-Picker

**Comment by bkulov** [comment]
I've created a new issue to implement input for date picker. - #3034

We will implement input for time picker only in this issue as it's already described in the time picker specification.

**Comment by bkulov** [comment]
With this issue we will implement new mode - input + drowdown. In addition the component will be migrated from dialog to overlay. See the spec for more details.
