### ISSUE TITLE
The Value of the igxTextHighlight directive shows up twice when calling highlight()

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2362]
### Description  
The Value of the igxTextHighlight directive shows up twice when calling highlight()

 * igniteui-angular version: 6.0.x, 6.1.x
 * browser: all

**NOTES:**
- The most-top element in our application's template gets hidden when the issue gets reproduced.

### Steps to reproduce  

1. Download and run the sample applicaiton.
2. Type "lorem" in the input.

### Result  
The Value of the igxTextHighlight directive shows up twice

### Expected result  
The Value of the igxTextHighlight directive shows up once (with the highlights)

### Attachments  

![highlightissue](https://user-images.githubusercontent.com/12784974/43890339-195d0296-9bcf-11e8-9039-05112614031d.gif)
[highlightSample.zip](https://github.com/IgniteUI/igniteui-angular/files/2273570/highlightSample.zip)

**Comment by DDavidkov** [comment]
This isn't a bug, the sample is not set up properly. The div to which we apply the IgxTextHighlight directive needs to be the only child on it's level. so you need to wrap it in another div. See the modified sample for reference.

[highlightSample.zip](https://github.com/IgniteUI/igniteui-angular/files/2274141/highlightSample.zip)
