### ISSUE TITLE
igxDropDownItemNavigation directive arrowDown handler should open drop down

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#2377]
### Description 

When igxDropDownItemNavigation directive is applied to a target element now the onArrowDownKeyDown handler will navigate drop down items, but if only the drop down is opened. The target element should take care to open the drop down. If there aren't any other considerations moving the opening of the target (if it is closed) to the onArrowDownKeyDown handler is preferred.

**Comment by ViktorSlavov** [comment]
There are separate applications scenarios to enforce both behaviors (opening on arrow down by default and having the user need to overwrite it **vs**. not and having the user implement the open logic) - closing this as it is not necessarily needed and there are samples in place to illustrate how to implement open logic.
