### ISSUE TITLE
Cannot set chip as selected through API if selectable is false

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#2383]
### Description  
I'm allowing chips to be selectable only under a certain condition, but I want selected chips to be shown regardless.

 * igniteui-angular version: 6.1.2
 * browser: Chrome

```html
<igx-chip *ngFor="let weekday of weekDays"
    [selectable]="player.steamUser.steamID64 === authUser.steamID64">
  <span class='igx-chip__text'>{{ weekday.day }}</span>
</igx-chip>
```

```typescript
this.activatedRoute.params.subscribe(params => {
  const userid = params['userid'];
  this.apiService.getUser(userid).subscribe(
    data => {
      this.player = data;
      this.chips.chipsList.forEach((item, index) => {
        item.selected = data.availability[index].available;
      });
    }
  );
});
```

Btw, I found out that I can hack it around, by temporarily changing the selectable value and them move it back to what it should be:

```typescript
this.activatedRoute.params.subscribe(params => {
  const userid = params['userid'];
  this.apiService.getUser(userid).subscribe(
    data => {
      this.player = data;
      this.chips.chipsList.forEach((item, index) => {
        const temp = item.selectable;
        item.selectable = true;
        item.selected = data.availability[index].available;
        item.selectable = temp;
      });
    }
  );
});
```

### Steps to reproduce  

1. Define a chip and set its selectable to false
2. Set the chip's selected property to true on init

### Result  
The chip does not look selected.

### Expected result  
The chip should be selected.

**Comment by kdinev** [comment]
@skrustev This is happening again. I have

```
<igx-chips-area>
        <igx-chip *ngFor="let role of team.Members | openPositions"
                  [selectable]="false" [selected]="true">
          <span class='igx-chip__text'>{{ role.roleName }}</span>
        </igx-chip>
</igx-chips-area>
```

And the chips are not rendered as selected. Marking the issue with `regression`.

**Comment by skrustev** [comment]
@kdinev I investigated it and I cannot seem to reproduce the exact same issue. I looked through the code and there isn't anything that prevents it from selecting the chips.

The only possible issue I could see is that the select icon is not displaying when chip is selected and set to `[selectable]='false'`
