### ISSUE TITLE
Docs Bug: IgxDropDown.selectedItem returns IgxDropDownItemComponent

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#2387]
### Description  
The docs say that it returns a number, but it returns an IgxDropDownItemComponent
https://www.infragistics.com/products/ignite-ui-angular/angular/components/drop_down.html#getters

### Expected result  
Either the docs should be changed to match the functionality or functionality needs to be changed to match the docs.

**Comment by zdrawku** [comment]
We are going to remove entirely the API table from every topic once we deploy the official API site. Closing this issue
