### ISSUE TITLE
Undefined ig-data-chart dataSource

### ISSUE THREAD

**Issue by JoeStead** [IgniteUI/igniteui-angular#24]
If the data source for the `ig-data-chart` is undefined, `ds.push` fails as `push` not accessible on undefined. This would be expected, however I'm using deferred execution, which means my data source is not being set/defined straight away.

My current workaround is to set the data source to a blank array and update later, so my controller contains the following:

```javascript
    $scope.dataChart = new Array();
    result.then(function (response) {
        if (response) {
            $scope.dataChart = response;
        }
    });
```

It may seem like a non-issue, but as directives such as `ng-repeat` just works, I was expecting the data chart to do the same.

**Comment by dkamburov** [comment]
Yes, you are right about that and I don't think this is chart specific. The data-boundable directive depend on that they should have data, even if empty(as you mentioned).
I'll have to do a deeper investigations and see whether, we could use use the widgets and angular directives without specifying their data.
