### ISSUE TITLE
Getting error on compile 

### ISSUE THREAD

**Issue by tariqaqeel** [IgniteUI/igniteui-angular#2402]
### Description  
After install npm module getting following error. i am trying to implement  range slider in my project. 

 * igniteui-angular version:  6.1.3
 * browser: 

### Steps to reproduce  
following to  [stack blitz](https://stackblitz.com/angular/lkgbprrqxlm?file=app%2Fslider-sample-1%2Fslider-sample-1.component.html)

### Result  
ERROR in node_modules/igniteui-angular/lib/combo/combo.component.d.ts(110,18): error TS2315: Type 'ElementRef' is not generic.
node_modules/igniteui-angular/lib/combo/combo.component.d.ts(117,17): error TS2315: Type 'ElementRef' is not generic.
node_modules/igniteui-angular/lib/directives/dragdrop/dragdrop.directive.d.ts(396,24): error TS2315: Type 'CustomEvent' is not generic.
node_modules/igniteui-angular/lib/drop-down/drop-down-item.component.d.ts(110,23): error TS2315: Type 'ElementRef' is not generic.
src/app/app.module.ts(189,3): error TS2304: Cannot find name 'IgxSliderModule'.

### Expected result  
What is the expected result after following the steps to reproduce?

### Attachments  
![image](https://user-images.githubusercontent.com/7837132/43991853-c28ca384-9d92-11e8-8da8-295535b68cec.png)

**Comment by zdrawku** [comment]
@tariqaqeel is there a specific 'steps to reproduce' flow that should be followed? I am unable to invoke this error in the provided sample on locally on my machiene.

**Comment by rkaraivanov** [comment]
@tariqaqeel can you check the version of your Angular packages? It seems to me you're trying to use Igniteui Angular 6.x while your Angular dependencies are < 6.

**Comment by zdrawku** [comment]
If you are still experiencing this issue, please do let us know.
