### ISSUE TITLE
Momentum scrolling on igx-grid

### ISSUE THREAD

**Issue by furugen** [IgniteUI/igniteui-angular#2409]
### Description  
I tryed scroll of igx-grid on iPad, But igx-grid is not supported momentum scrolling.
https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html

Momentum scrolling is very popular function. For example, Kendo UI is supported momentum scrolling.
https://www.telerik.com/kendo-angular-ui/components/grid/browser-performance/

I hope introduce momentum scrolling features into Ignite UI for Angular.

 * igniteui-angular version: 6.1.2
 * browser: Safari

Thanks,
Yuu.

**Comment by pnishimura** [comment]
@SlavUI 
CC: @zdrawku , @furugen , @ymita , @tkiryu

Even if we can not add this feature to our igniteui-angular,
It would be great if you can provide a workaround for our customer to implement in their code.

Thanks,
Paul

**Comment by mpavlinov** [comment]
This is something that we couldn't implement for the initial version of the virtualization, so we left it for later. It is logged as #1640.

**Comment by mpavlinov** [comment]
This is implemented, so I'm closing it.
