### ISSUE TITLE
Setting the 'height' of the combo does not work

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2410]
### Description  
Setting the 'height' of the combo does not work.

 * igniteui-angular version: 6.1.x, 6.2.x
 * browser: all

### Steps to reproduce  

1. Run the "**Combo Features**" sample from the **igniteui-angular-samples** repo.
2. Edit the template of the sample by setting the height of the igx-combo to 30px.
```html
<igx-combo #combo1 class="input-container" width="270px" height="30px"
```

### Result  
The height of the combo remains unchanged.

### Expected result  
The height of the combo is changed and it's 30px.

**Comment by Lipata** [comment]
The most proper solution would be the input-group to allow setting a custom height (#2426). Then combo will set its height to the input group one.
