### ISSUE TITLE
igx-grid - Filter dialog is not displayed if igx-grid surrounded by div with set Z-index.

### ISSUE THREAD

**Issue by furugen** [IgniteUI/igniteui-angular#2411]
### Description  
Filter dialog is not displayed if igx-grid surrounded by div with set Z-index.

 * igniteui-angular version: 6.1.x
 * browser: Chrome, Edge

```
<div style="z-index: 1;background-color: red;position: relative; width: 1000px; height: 700px;" >
    <igx-grid #grid1 [data]="localData"   width="960px" height="550px">
      <igx-column field="EmployeeID" filterable="true" dataType="string"></igx-column>
    </igx-grid>
</div>
```

### Result  
Filter dialog is hide behind.

### Expected result  
Filter dialog is show front.

### Attachments  
![image](https://user-images.githubusercontent.com/8131662/44081752-74186d96-9fea-11e8-9a0d-cf5c93eb48da.png)

**Comment by zdrawku** [comment]
It is possible this issue to be related to [PR](https://github.com/IgniteUI/igniteui-angular/pull/2363).

This PR is introducing a new overlay structure to the host element instead of the body, to preserve DOM hierarchy for styling.

We should give it a try.
