### ISSUE TITLE
Search not working properly in grid with custom cell using ngFor

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#2441]
### Description  
Search not working properly in grid with custom cell using ngFor

 * igniteui-angular version: 6.1.3
 * browser: Chrome 68.0.3440.106

### Steps to reproduce  

1. Open example: [Sample](https://stackblitz.com/edit/igx-grid-with-searching-2-redtvp)
2. Search "consumer" in main input of search

### Result  
In column IndustrySector in the first row the value of the cell is "--Consumer--Consumer"

### Expected result  
In column IndustrySector in the first row the value of the cell should be "Consumer"

Reference: #1931 

### Attachments  
![image](https://user-images.githubusercontent.com/7459881/44238098-d666aa00-a178-11e8-944e-698c55f71d3e.png)
[igx-grid-with-searching-2-redtvp.zip](https://github.com/IgniteUI/igniteui-angular/files/2295413/igx-grid-with-searching-2-redtvp.zip)

**Comment by DDavidkov** [comment]
@lalo-mx [My comment](https://github.com/IgniteUI/igniteui-angular/issues/1931#issuecomment-403035634) from the issue you have referenced explains exactly what is going on here, as well. The search currently has a limitation and it doesn't work properly with templates. Do you really need the this template? Virtually identical functionality can be achieved with simply using a column formatter and then the search will work well. If you need help to do this, please see [this](https://stackblitz.com/edit/igx-grid-with-searching-2-mbxav9) stackblitz sample.

**Comment by lalo-mx** [comment]
@DDavidkov The problem I am trying to solve is when a column has a numerical value that is represented by a label, for example (The active state has value "1" and the label "Active", the value "0" and the label "Inactive").
This problem can be solved with a select but the grid does not support this type of columns.
My idea to solve this problem was to have a template and filter the collection states and only show the one that corresponds to the value of the cell.

I will test the column formatter option that you are suggesting.

**Comment by DDavidkov** [comment]
@lalo-mx If I am understanding your use case correctly and you just want to have labels representing numbers in your data, you can definitely implement this by just using a column formatter. To do that add a switch case in your formatter that would switch on the numeric value and return the appropriate string for that number.
