### ISSUE TITLE
DropDown onSelection errors on load

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#2489]
### Description  
If there's initially selected item in the drop down, and you're accessing the drop down component in the event, then on initial load you get an exception.

 * igniteui-angular version: 6.1.4
 * browser: N/A

### Steps to reproduce  

1. Configure a drop down with `[isSelected]="true"` item and `(onSelection)` output handler
2. Configure your component to access the dropdown as a `@ViewChild` and access it on selection

### Result  
Exception on initial load.

### Expected result  
No exception. The drop down should be exposed in the event arguments.

**Comment by wnvko** [comment]
I have tested this and was not able to reproduce it. Closing the issue
