### ISSUE TITLE
Conversation component

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#2513]
### Description  
Create an Angular component that renders conversation bubbles, annotated with the author of the message and supporting visual grouping of sequential messages from the same author. Such interfaces are common for chats, instant messaging, chatbots etc.

### Result  
![chat](https://user-images.githubusercontent.com/1702064/44713908-c629c580-aabc-11e8-92bd-9af8349987f9.png)

**Comment by kdinev** [comment]
Isn't this a series of avatars and bubbles?

**Comment by StefanIvanov** [comment]
@kdinev what component do you refer to that Ignite UI for Angular has at hand to display the bubble? Also when it comes to conversations, there is a notion of grouping things just like a list can be grouped through the use of headers and spacing, however our header here is an avatar since the group is according to the author of the message group and bubbles are as list items belonging to the same run of messages.

**Comment by kdinev** [comment]
@StefanIvanov We don't have a bubble component, but we can add one to the backlog.

**Comment by StefanIvanov** [comment]
What layout component would be able to render bubbles and avatars to shape up a conversation as in the screenshot provided? I mentioned list as a reference but will the igxList be able to do that?

**Comment by kdinev** [comment]
I'll assign this for investigation. Let's see what components we would need to achieve this, if there's anything missing, of course.

**Comment by bkulov** [comment]
I've prepared a demo application using IgxList. In my opinion we don't need a dedicated chat component but we could add this demo application to our live samples.
https://angular-dzqean.stackblitz.io

@kdinev @StefanIvanov What do you think?

**Comment by StefanIvanov** [comment]
Designs for the final layout and style are below (ignore the Navbar at the top it is only for illustrative purposes to provide context for scrolling)

![group chat](https://user-images.githubusercontent.com/1702064/45877933-15a39e80-bda8-11e8-88ce-a76c9c92f6d2.png)
![chat](https://user-images.githubusercontent.com/1702064/45877934-15a39e80-bda8-11e8-9514-5d6bd12fff83.png)

**Comment by bkulov** [comment]
This is implemented as application sample under List article and it would be available at the following location after we deploy the new stuff:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/list.html
