### ISSUE TITLE
Localization (i18n) not available for inputs/buttons on the grid filtering dialog

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#2517]
### Description  
Localization (i18n) not available for inputs/buttons on the grid filtering dialog, for example "value" (null text for inputs), "AND", "OR", "RESET" and "CLOSE".

 * igniteui-angular version: 6.1.4
 * browser: anything

### Steps to reproduce  

Please see the attached image.

### Result  
No way to localize some text on the filter dialog.

### Expected result  
Text on the filter dialog can be localized.

### Attachments  
![igx-grid-filtering-dialog](https://user-images.githubusercontent.com/7350918/44773744-4d099b80-abac-11e8-917f-ae7475f382f6.PNG)

**Comment by zdrawku** [comment]
@gdayori we are waiting for runtime localization feature of Angular to be implemented in order to use it.

[This is the issue](https://github.com/angular/angular/issues/16477) in the angular repository, and as I see they are currently working on it (5 day comment), [the runtime part is done without the the compliler part yet](https://github.com/angular/angular/issues/16477#issuecomment-415689685).

**Comment by SlavUI** [comment]
@bkulov please start working on this Issue from Monday.

**Comment by juancarlosbaezpozos** [comment]
I know the pipe makes the translation but how can I change the locale from "en-US" to another. the locale must be declared in the HTML as attribute?. thank you in advance

**Comment by bkulov** [comment]
@juancarlosbaezpozos Note that this feature is still in development. Angular have some tools to provide localization but only for client applications and not for components. So we are going to implement a temporary solution for the time being.
As for the `LOCALE_ID` - it's Angular DI token providing the current application locale. If you provide Angular CLI localizations to your application you could provide it in the command line `ng serve --configuration=fr`. Or you could provide it into the `providers` array of ngModule, Component, etc. like this `providers: [ { provide: LOCALE_ID, useValue: 'fr' } ],`.

For more info take a look at the following article. Note that we will be using only the DI token and not the whole Angular localization process. Once done we will provide an extensive documentation with samples how the localization could be done.
https://angular.io/guide/i18n

**Comment by zdrawku** [comment]
@bkulov do we consider this issue as completed?

**Comment by bkulov** [comment]
@zdrawku Not yet. We're working on a separate repo containing the localized string resources for JA and JP. When it's done I'll close this issue.

**Comment by bkulov** [comment]
This is the documentation we have for the localization:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/localization.html
