### ISSUE TITLE
When a column is moved in a grid using a theme, the drag-ghost is not styled in the theme's color

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#2518]
### Description  
When a column is moved in a grid using a theme, the drag-ghost is not styled in the theme's color

 * igniteui-angular version: 6.2.x
 * browser: All

### Steps to reproduce  

1. Open and run the attached sample.
2. Select a color-picker sample.
3. Start moving a column.

### Result  
The drag-ghost is not styled in the theme's color.

### Expected result  
The drag-ghost should be styled in the theme's color.

Note: The same result is reproduced if you change the theme to Dark.

### Attachments  
![dragghost](https://user-images.githubusercontent.com/11095014/44782363-aca57e00-ab8f-11e8-9f70-77105341ecff.png)

[grid-column-moving.zip](https://github.com/IgniteUI/igniteui-angular/files/2331763/grid-column-moving.zip)

**Comment by simeonoff** [comment]
@npaunov This could be resolved by moving the outlet the ghost column is rendered in inside the grid component template.
