### ISSUE TITLE
Selected row checkboxes are flickering on vertical scrolling

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2523]
### Description  
On vertical scrolling the checkboxes are flickering.

### Steps to reproduce  

1. In product dev samples open Grid Column Pinning
2. Select rows from 4th row to 6th
3. Start to scroll vertically very slow
4. Observe how the selected row checkbox indicators are flickering

### Result  
Row checkbox indicators are flickering

### Expected result  
Row checkbox indicators should not be flickering

### Attachments  
![image](https://user-images.githubusercontent.com/11193764/44796363-84c91100-abb5-11e8-81e1-4f9ca3ac609a.png)

**Comment by Lipata** [comment]
@simeonoff As we discussed this behavior above, if animation of the checkbox can be disabled, then flickering on scroll, in the grid will disappear. Are there some plans to introduce such an option for the checkbox?

**Comment by simeonoff** [comment]
@Lipata yeah, I will introduce an option for no animation via some css class.
