### ISSUE TITLE
Documentation sounds incomplete

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-angular#2524]
**Description**

There are placeholder comments in the Angular API docs.
../typescript/classes/hammergesturesmanager.html
../typescript/classes/igxnavigationservice.html
•	igniteui-angular version: 6.1.x
•	browser: Chrome

**Steps to reproduce**
1.	Go here: ../typescript/classes/hammergesturesmanager.html
2.	Go here: ../typescript/classes/igxnavigationservice.html
3.	Read the description at the top.

**Result**
"Very TBD. Much TODO." <- I appreciate this meme.
"TODO: Track currently active? Events?"
Expected result
The documentation should explain the class. It looks like the class isn't implemented fully if it's TBD or TODO?

**Comment by SlavUI** [comment]
@ig-ealbert hi Liz the Documentation is still work in progress and it not accessible to the public deleting the links and closing the issue.
