### ISSUE TITLE
igx-grid editing: Japanese inputs are not committed on enter or press key in edit mode 

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/igniteui-angular#2525]
### Description  
When igx-grid is editable, users can edit cell value. when user uses IME and press enter or return key to commit, input values are gone on certain browsers.

 * igniteui-angular version: 6.1.4
 * browser: Windows IE11, MacOs Chrome 68.0.3440.106（Official Build） （64 bits）

Chrome on Windows works ok

### Steps to reproduce  

1. Prepare IME or input  
2. Open igx-grid sample page: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html
3. Select one of cells in Product Name column
4. Turn IME on
5. Press a 3 times. it should show "あああ"
6. Press enter or return to commit value

### Result  
Japanese inputs are not committed.

### Expected result  
Japanese inputs should be committed

### Attachments  
![entercellvalueinjapanese mov](https://user-images.githubusercontent.com/14284406/44827650-f3a67880-ac4e-11e8-9a9f-0b99b49f9357.gif)

**Comment by zdrawku** [comment]
Hey Daizen, I just tested this and it seems that it is working as expected with the latest 6.2.0 version. When I type something in Japanese and press enter, the value is commited.
![image](https://user-images.githubusercontent.com/11193764/48263426-bddff600-e42e-11e8-9bb8-be174bb332c5.png)

I am using windows IME input

![image](https://user-images.githubusercontent.com/11193764/48263462-de0fb500-e42e-11e8-92d1-1b09d831fc5b.png)


Could you check this

**Comment by SlavUI** [comment]
@DaizenIG closing this one please reopen if needed as the issue seems to be resolved

**Comment by DaizenIG** [comment]
@SlavUI 

With the latest sample on https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html, assuming it's 7.x.x,  IE11 still has the same issue, on the other hand Safari on Mac worked as expected.

re-opening the issue.

**Comment by SlavUI** [comment]
@zdrawku can you guys check again please
