### ISSUE TITLE
Edit cell value is blank on paging

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2535]
### Description  
When editing a cell in the grid, and the cell is still in edit mode on paging, the value gets blank/empty and when the template is checked again, only then the cell value starts to be visible

 * igniteui-angular version: 6.1.4, 6.2.0-beta.1
 * browser: any

### Steps to reproduce  

1. Open [sample](https://stackblitz.com/edit/paging-issue-when-editing-cell?file=app/grid/grid-editing-sample/grid-editing-sample.component.html)
2. Scroll to Order Date column
3. Put any cell in edit mode
4. Navigate to second page (second page)
5. Navigate back to the initial page (first page)
6. Cell in edit mode gets blank

### Result  
Cell is blank

### Expected result  
Cell should not be blank

### Attachments  
![image](https://user-images.githubusercontent.com/11193764/44856982-6fb4b680-ac77-11e8-914c-3a5064abbd60.png)

**Comment by nrobakova** [comment]
Now when change page the cell edit mode is closed and after return to first page the cell is only selected

**Comment by zdrawku** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/2956

**Comment by nrobakova** [comment]
Close because now when change page the cell edit mode is closed #2956
