### ISSUE TITLE
Cell is not editable on iOS

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#2538]
### Description  
Cell is not editable on iOS

 * igniteui-angular version: 6.1.4
 * browser: Chrome 68.0.3440.83, Safari (iOS 11.4.1(15G77))

### Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html
2. Try to edit a cell

### Result  
The cell does not go into edit mode.

### Expected result  
The cell goes into edit mode.

**Comment by ymita** [comment]
@zdrawku
Do you assume this issue will take a long time to fix? Or does this look like a straightforward one to fix? I appreciate any information about this issue.

**Comment by zdrawku** [comment]
@ymita today I will take a closer look and will let you know about all my findings regarding the issue.

**Comment by tiliev** [comment]
This is related to #https://github.com/angular/angular/issues/23954, I pushed a PR. We'll implement a workaround for the time being.

**Comment by rkaraivanov** [comment]
Unfortunately, this PR breaks other of our components which rely on hammerjs events. I'm reopening the issue and we should either extend our kind of forgotten hammer manager class to work with Angular, or hopefully the Angular team will add the doubletap support by default.

**Comment by pnishimura** [comment]
Hi @zdrawku, @rkaraivanov 
Out of my curiosity,
Regarding this issue,
Is there no way rather then waiting for the doubletap support by the Angular team?
Or do we have any workaround for it?

**Comment by damyanpetev** [comment]
It does seem like this is taking a while to get resolved by wither Angular or in iOS (one can dream) so we might as well try to fix it on our own for now.
There's an option to manually attach the double tab to HammerJS though one of our old manager class as @rkaraivanov said.
That'd require a bit refactoring at least. We'll look into it.

**Comment by pnishimura** [comment]
@damyanpetev Thank you for your reply!
Well understood now :)
As you mentioned, originally, this issue should be resolved by Angular or iOS, I think as well.
I'm glad to hear your comment this time.
This issue is not high priority thing,
But It would be great if you guys can let me know if any update around this issue in future.
Thank you again,
Paul
