### ISSUE TITLE
How to raise events attached to cell after grid's searching feature is used?

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#2549]
### Description  
Events that are attached to cells do not raise after grid's text search is performed. This is because new text labels are populated and original text labels become hidden, so that the attached events to the original text are not called. How can we call the such events even after grid's text search is performed?

 * igniteui-angular version: 6.1.4
 * browser: Chrome

### Steps to reproduce  

1. Run the attached sample
2. Open console window of browser's Developer Tool
3. Enter 5 on the input box
4. Click a cell on a cell

### Result  
mousedown, mouseup and mouseenter event are not raised.

### Expected result  
mousedown, mouseup and mouseenter event are raised.

### Attachments  
[igniteui-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/2347592/igniteui-app1.zip)

**Comment by ymita** [comment]
@gedinakova 
May I ask the current status of this issue? Is this considered a bug of igx-grid?

**Comment by gedinakova** [comment]
@ymita Yes, this is considered a bug. We are currently looking into it.

**Comment by gedinakova** [comment]
@ymita After further investigation and internal discussions, it was determined that this behavior is a limitation. The search feature is a simple text search. With custom cell templates there is no way for us to know whether the cells contain any text which can be searched and highlighted. So for this case, if the extended cell functionality is required when there's active search, the only option to avoid the broken behavior is by marking the respective column unsearchable by setting [searchable]=false.

**Comment by ymita** [comment]
@gedinakova Thank you for the information. Do you plan to write this limitation on the documentation for existing/future customers?

**Comment by DDavidkov** [comment]
@ymita I have just update the Grid Search spec file to include this [limitation](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Search#5-limitations).

**Comment by ymita** [comment]
@DDavidkov Thank you!

**Comment by DDavidkov** [comment]
@ymita You are welcome!

Also I have just created a [PR](https://github.com/IgniteUI/igniteui-docfx/pull/692) for this in our docs, so when it is merged, the [grid search topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_search.html) will include the know limitations of the feature.

**Comment by ymita** [comment]
@DDavidkov 
Is the limitation that is described on the Wiki going to be reflected on grid search topic soon?

**Comment by gedinakova** [comment]
@ymita Yes, Yuki, it will be available when our next major release is ready.
