### ISSUE TITLE
Cannot hide an element due to unfinished animation in the IgxOverlay

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2551]
### Description  
Cannot hide an element due to unfinished animation in the IgxOverlay.

 * igniteui-angular version: 6.1.x, 6.2.x
 * browser: all

### Steps to reproduce  

1. Run the **"Toggle Overview"** sample from the **igniteui-angular-samples** repo.
2. Modify the **template** and the **ts** respectively as follows:
```html
...
  <article class="sample-column">
    <div>
        <button (click)="open()">open</button>
        <button (click)="close()">close</button>
    </div>
    <button class="toggle-button" #button igxButton="raised" (click)="toggle()">Toggle</button>
...
```

```typescript
...
    open() {
        this._overlaySettings.positionStrategy.settings.target = this.igxButton.nativeElement;
        this.igxToggle.open(this._overlaySettings);
        console.log("OPEN invoked");
    }
    close() {
        this.igxToggle.close();
        console.log("CLOSE invoked");
    }
...
```
3. Click the **open** button and then immediately the **close** button. (do not wait for the open animation to finish)

### Result  
Even though close was invoked (as seen in the console), the box element is still visible.

### Expected result  
A way should be provided, so the user can both terminate the animation before it is finished and hide the element immediately.

### Attachments  

![toggleissue](https://user-images.githubusercontent.com/12784974/45019012-ed8c0f80-b033-11e8-80b7-dd40ac7e2cf5.gif)

**Comment by wnvko** [comment]
This should be fixed with PR #2587 
Note in the same PR we have exposed OnAnimation event. You can handle this event on open/close and get reference to animation player. This allows you to control the animation as you need, e.g. finish it or cancel it.
