### ISSUE TITLE
IgxChip remove icon has wrong color

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/igniteui-angular#2573]
### Description  
The chip remove icon color is white when it should use the default color (0,0,0,0.74). This happens when I apply my own igx-chip-theme but I am not changing the remove icon color in the function so it should use the default.

I think it might have something to do with importing the icon-theme and icon-component style files but I should be able to import them.  Especially if I have to use icons in other places and want to style them.

 * igniteui-angular version: 6.1.4
 * browser: Google Chrome 68.0.3440.106

### Steps to reproduce  

1. Go here: https://stackblitz.com/edit/angular-q1bj24

### Result  
The first chip has a white remove icon while the second chip has the correct color.  The second chip does NOT have a theme applied to it.

### Expected result  
The first chip has the correct icon color since the applied chip theme does not change the icon color.

**Comment by ig-robstoffers** [comment]
I just realized that I also had set the chip text [class] incorrectly.  I updated the sample to set it properly (I.e. [class]="'igx-chip__text'").  As a result the chip text has also turned white.  I now believe the chip text and the remove icon are white because of the dynamic color contrast stuff being done in the chip theme.

**Comment by ig-robstoffers** [comment]
Not sure if this is related but if I try and set ONLY the $remove-icon-color function argument it seems to be ignored.
https://stackblitz.com/edit/angular-mknlxl

**Comment by ig-robstoffers** [comment]
@desig9stein, these weren't merged to master yet were they? I don't see them in the latest beta 4 build.

Also are these changes still going to work even after the igx-chip-theme changes that were recently done? A bunch of the argument names were changed but if I look at #2663 it still has the old names.

**Comment by desig9stein** [comment]
@ig-robstoffers With the refactoring of the chip component, my changes are no longer required and will not work.
The refactoring of the chip component fix all the issues mentioned above so I am going to close the issue also.

**Comment by ig-robstoffers** [comment]
@desig9stein I think this issue is still partially present in the master branch.  If you look at the igx-chip-theme [here](https://github.com/IgniteUI/igniteui-angular/blob/9ddce0f5dcd151ac449a852d56c05362c1759b23/projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss#L99) you will see that it is not using that **hexrgba()** function that it uses for all of the other colors like this [one](https://github.com/IgniteUI/igniteui-angular/blob/9ddce0f5dcd151ac449a852d56c05362c1759b23/projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss#L113).  As far as I can see this is the only one missing it.
