### ISSUE TITLE
Pickers and Combo Input Group

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#2576]
### Description  

 * Extract the input group to provide more styling flexibility by changing the input group elements and layout
 * Allow for the focus style to be preserved on the input group e.g. when the combo is opened or the date/time picker dialog is shown

### Attachments

![artboard](https://user-images.githubusercontent.com/1702064/45286910-abf5db80-b4ef-11e8-9106-c7a4f60b8993.png)
![artboard copy](https://user-images.githubusercontent.com/1702064/45286915-b021f900-b4ef-11e8-856b-8422ddde9fbd.png)

**Comment by StefanIvanov** [comment]
@SAndreeva , @sboykova  please tag this issue as you make your PRs

**Comment by bkulov** [comment]
Date and Time pickers' PRs are already merged so I'm closing this issue.
