### ISSUE TITLE
Slider in Real Time Chart sample not working correctly

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#2586]
### Steps to reproduce  
Run sample:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/categorychart_real_time_data.html
move number of rows slider. 
Move it back.

### Result  
It seems to only bounce between maxPoints and maxPoints - 1. 
If you open the sample in stackblitz and set [isContinuous]=false you can see the values more clearly

### Expected result  
The slider should slide between values like the refresh rate one does

**Comment by kdinev** [comment]
Moving the issue to the correct repository.

https://github.com/IgniteUI/igniteui-angular-charts/issues/2
