### ISSUE TITLE
Input group text in Filtering UI dialog is not with a contrast color 

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2590]
### Description  
The issue could be related to the placeholder itself. 

### Steps to reproduce  

1. Open Theme-chooser samlple from our dev demos (/samples/theme-chooser)
2. Open any filtering dialog

### Result  
Text is nearly invisible

### Expected result  
Text color should be noticeable.

### Attachments  
![image](https://user-images.githubusercontent.com/11193764/45486486-f2ec0700-b763-11e8-9fb0-892c023759d9.png)

**Comment by bkulov** [comment]
This filtering UI will be deprecated in near future so no need to fix this bug.

**Comment by zdrawku** [comment]
Closing the issue as per the upcomming deprecation
