### ISSUE TITLE
Async callback was not invoked within timeout specified by jasmine

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular#2607]
Our tests are randomly failing with this error.
Here is a list of the things which might cause this:

## Not cancelled subscriptions ##
Memory leaks.

- [x] `igx-chips-area` has 5 subscriptions in `ngDoCheck` which we should unsubscribe from (`onMoveStart`, `onMoveEnd`, `onDragEnter`, `onKeyDown` and `onSelection`).
- [x] `igx-combo-drop-down` - missing `takeUntil` in `virtualContainer.onChunkLoad` subscription.
- [x] `igx-date-picker` - missing `takeUntil` in `calendar.onSelection` subscription.
- [x] `igx-radio-group` - `button.change` subscription not cancelled.
- [x] `igxTextHighlight` - `IgxTextHighlightDirective.onActiveElementChanged`
- [x] `igxToggle` - `overlayService.onOpened`. We could introduce `takeUntil` for all of the subscriptions.
- [x] `igx-grid-cell` - `row.virtDirRow.onChunkLoad`
- [x] `igx-column-hiding` - `item.valueChanged`
- [x] `igx-grid` - `virtualContainer.onChunkLoad`
- [x] `IgxOverlayService` - `fromEvent(wrapperElement, 'keydown')` and `fromEvent(info.elementRef.nativeElement.parentElement.parentElement, 'click')`

## Incorrect usage of  `takeUntil` ##

Possible memory leaks. More information [here](https://blog.angularindepth.com/rxjs-avoiding-takeuntil-leaks-fb5182d047ef).
- [x] `igxDrag` subscriptions in `ngOnInit`. Example:
```
pipe(takeUntil(this._destroy),
    throttle(() => interval(0, animationFrameScheduler)));
```
It should be:
```
pipe(throttle(() => interval(0, animationFrameScheduler)),
    takeUntil(this._destroy));
```

- [x] `igxResizer` constructor - should have `takeUntil` in `this.resizeStart.pipe` as last operator. I guess here it does not leak, because we have `takeUntil` in the observable in the `switchMap`.
- [x] `igxResizer` `ngOnInit` - `takeUntil` should be last operator in `mousemove`.

## Missing `removeEventListener` ##
- [x] `igxFor` - `this.vh.instance.elementRef.nativeElement` and `this.hvh.instance.elementRef.nativeElement` have `scroll` event listeners not removed.
- [x] `igxScrollInertia` - a lot of not removed event listeners in `ngOnInit`
- [x] `igx-grid-header` - `this.resizeArea.nativeElement` event listeners
- [x] `igx-grid` - `vertScrDC` has `scroll` event listener.

## Tests using subscriptions ##
We have a lot of tests which do not cancel their subscriptions - `igx-combo, igxForOf, igx-grid-cell, igx-column-hiding, igx-column-pinning, grid-toolbar, grid-search, list, csv-exporter-grid/excel-exporter-grid, csv-exporter/excel-exporter`. Some of them partially do. We should discuss whether we should address this.

**Currently we won't start working on these until I get the full list of tasks and we decide which of them should be addressed.**

**Comment by zdrawku** [comment]
@gedinakova, as we discussed you are going to distribute the pending work related to this task, if you need any help, let me know

**Comment by mpavlinov** [comment]
@kdinev @zdrawku All the checkboxes are fixed and there are improvements in the tests. Should we close this one?

**Comment by zdrawku** [comment]
I can verify that all points are covered, closing this issue.
