### ISSUE TITLE
IgxChip and IgxChipArea ignore user CSS

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/igniteui-angular#2614]
### Description  
I have a CSS class defined with some margins and try to apply this css to the IgxChip and IgxChipArea however they seem to be ignored.

 * igniteui-angular version: 6.1.5
 * browser: Chrome 68.0.3440.106

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-vn52qt

### Result  
No margins are applied to the IgxChipArea or IgxChip

### Expected result  
Margins are applied to the IgxChipArea and IgxChip

**Comment by simeonoff** [comment]
@SlavUI This is not a styling issue. It's related to how CSS class names are bound to the component host.

**Comment by skrustev** [comment]
This should be resolved in #2712.
