### ISSUE TITLE
Range Slider Thumps collapsing

### ISSUE THREAD

**Issue by shaunlab** [IgniteUI/igniteui-angular#2622]
### Description  
The Range Slider has a left and a right thumb that appear during interaction to both ease the end user navigation and also display the current slider value. These need to stay expanded whenever the user interacts with the control but the range thumbs currently hide after several seconds in Internet Explorer 11.
This is a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/463 although the issue still seems to exist in IE 11.

 * igniteui-angular version: 6.1.5
 * browser: Internet Explorer 11

### Steps to reproduce  

1. Adjust slider min/max values in IE 11.

### Result  
the label disappears while still dragging the dot

### Expected result  
Thumbs to stay visible during the whole interaction

**Comment by kdinev** [comment]
@shaunlab This could be a side effect of the web animations polyfill, since the standard animations are not supported in IE11. We will investigate!

**Comment by shaunlab** [comment]
Thanks @kdinev - hopefully there will be a fix for this implemented soon
