### ISSUE TITLE
[API Docs] Interface is displayed twice when both child and base classes implement it

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2628]
### Description  
Interface is displayed twice when both child and base classes implement it.

 * igniteui-angular version: 6.1.x, 6.2.x
 * browser: all

### Steps to reproduce  

1. Switch to the tooltip feature branch (because it is currently not merged):
https://github.com/IgniteUI/igniteui-angular/pull/2564
2. Execute **npm run build:docs**
3. Open index.html in the **igniteui-angular\dist\igniteui-angular\docs\typescript** folder.

### Result  
An interface is displayed twice when both child and base classes implement it.

(In this case, both the **IgxToggleActionDirective** and the **IgxTooltipTargetDirective** implement **onInit**)

### Expected result  
An interface is displayed once when both child and base classes implement it.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/45753730-5d002280-bc22-11e8-9640-16fe632b17d2.png)

**Comment by hanastasov** [comment]
I am not sure there would be a way to avoid this, as a derived class would not need to implements its base class interface. In the case of Angular lifecycle hooks, the tslint "use-life-cycle-interface": true rule requires us to implement the interface for the derived class.

I did not find anything in Typedoc API, so i opened a [question](https://github.com/TypeStrong/typedoc/issues/893).

If there is no way to avoid this, I guess we can live with it.

**Comment by SlavUI** [comment]
@zdrawku Hey if this is still labeled as a question and it is answered we should close it ?

**Comment by hanastasov** [comment]
There is a [logged issue in Typedoc](https://github.com/TypeStrong/typedoc/issues/893), I have also reproduced the behavior in isolated sample and updated their issue.

Hope they answer soon, but anyway we may close ours.
