### ISSUE TITLE
IgxDrop should also expose drop data like IgxDrag does

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#2629]
### Description  
When I initialize the `IgxDrag` directive, I can bind it to my data, and then access it during drag events. I cannot do the same for `IgxDrop`.

 * igniteui-angular version: 6.1.5
 * browser: N/A

Expected:  
`<img igxDrop="imageData" (onDrop)="$event.owner.data.src = $event.drag.data.src" />`

**Comment by Eralmidia** [comment]
@kdinev Quick question: are the igxDrag and igxDrop components internal, or are they new, and not yet documented on https://www.infragistics.com/products/ignite-ui-angular? Just asking, as we are going to rewrite a dashboard module soon, which requires quite a bit of dragging and dropping, and I would rather avoid going outside infragistics if I can ;)

**Comment by kdinev** [comment]
@Eralmidia The `IgxDragDropModule` is new and would be officially released with `6.2.0`. It has been released already because we're using it for the column moving and for the groupby of the `igxGrid`. If you want to start using it, then you can refer to the readme that we have, as the documentation would be published with 6.2.0. 

https://github.com/IgniteUI/igniteui-angular/pull/2609
