### ISSUE TITLE
Chart questions

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#2632]
### Description  
Before adding feature requests, I'd like to get an overview of a few things regarding the new charts:

We are considering when to rewrite an older module to use igx-chart (currently using igniteui charts), and I was wondering if the following is supported:

1. Multiple axis
2. ScatterLine type
3. Configurable lines in line chart (ie dotted/dashed instead of solid line).
4. Since we are doing a rewrite, we would like to freshen up the looks as well. Is it possible to configure a line/area chart with a combination of gradients and transparency, similar to this: https://cdn-images-1.medium.com/max/2000/1*Dc_ghRRz_QPo-yoOUaCe9Q.png ?

**Comment by kdinev** [comment]
@Eralmidia I've moved your question to the charts repository. 

https://github.com/IgniteUI/igniteui-angular-charts/issues/3
