### ISSUE TITLE
igxGrid position of header's feature icon (e.g. filtering icon) and header text become inverted on number columns

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#2633]
### Description  
On number type columns, cell values get right-aligned which is great, and the position of the header's feature icon (e.g. filtering icon) and the header text become inverted. The icon is placed on the left of the header text on number column. I've got questions regarding this behavior from SEVERAL customers that they feel this behavior unnatural, some of them said operational icons (e.g. filtering icon) should be placed on the same position even on a number type (right-aligned) column in terms of UX.
![headericonposition](https://user-images.githubusercontent.com/7350918/45799088-44a60b80-bce7-11e8-99fe-a605afb18c43.png)

Is this designed in the material guideline? If it's by designed with a certain reason then could you consider to have an option to allow developers to choose the alignment?

 * igniteui-angular version: 6.1.5
 * browser: whatever

### Steps to reproduce  

1. Open https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html
2. Check the header of Unit Price column

### Result  
The filtering icon is placed on the left of the header text "Unit Price"

### Expected result  
The icon should be placed on the same place on every column regardless of the column's dataType.

**Comment by StefanIvanov** [comment]
The layout is by design as described in the Material guidelines https://material.io/design/components/data-tables.html#specs

**Comment by tiliev** [comment]
@gdayori, also, the users can alter the look & feel of our components using Sass. Let us know if you need a sample demonstrating how to achieve the desired scenario using custom styles.

**Comment by gdayori** [comment]
@StefanIvanov I couldn't find description that icons should be placed on the left of the header text. Where's described about it?

**Comment by gdayori** [comment]
@tiliev Thanks! I know how to achieve it with Sass but I just want to discuss how the default style should look.

**Comment by gdayori** [comment]
@StefanIvanov Thanks for your reply. I found some images indicating that you are right... I understand that this UI is exactly following the Material Guideline.

**Comment by gdayori** [comment]
I'm closing this since the current UI is by design.
