### ISSUE TITLE
The onGroupingDone event doesn't get raised when columns get ungrouped.

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#2645]
### Description  
The onGroupingDone event currently gets raised only when columns get grouped, but by specification it should be raised when columns get grouped **or ungrouped**. ~~This makes the name ambiguous - it should be changed to onGroupingChanged. As this is a breaking change, a new onGroupingChanged event would be added **in addition** to the old one - onGroupingDone should be deprecated in later product versions.~~

Additionally, the clearGrouping grid method should have an overload to accept an array of column names and ungroup them all at once. Currently it should get called separately for each column about to be ungrouped - this would raise the onGroupingDone multiple times, which in many cases would **not** be what the user wants.

 * igniteui-angular version: 6.2.x
 * browser: any

### Steps to reproduce  

1. Run the provided sample 
2. Open [http://localhost:4200/grid](url)
3. Group columns and upgroup them afterwards
4. Observe the browser console - it would log the onGroupingDone event. 

### Result  
The onGroupingDone event doesn't get raised when columns get ungrouped, only when they get grouped.

### Expected result  
By specification the event should get raised when columns get grouped or ungrouped.

### Attachments  

[GroupByAPI.zip](https://github.com/IgniteUI/igniteui-angular/files/2404407/GroupByAPI.zip)

**Comment by norikois** [comment]
The onGroupingDone event is not raised, too, when grouping order is changed.  Could you cover this case by onGroupingDone event?

**Comment by PavlovVasil** [comment]
@norikois The pull request fixes this problem also.

**Comment by norikois** [comment]
@PavlovVasil Thanks!
