### ISSUE TITLE
Responsive calendar 

### ISSUE THREAD

**Issue by al-matari** [IgniteUI/igniteui-angular#2653]
Hallo Everyone

Calendar in landscape format is not scaled correctly. It looks like the dimensions are fixed and not responsive. Please look at the image. Is there a way to scale the calendar automatically if there is no space or to make it responsive.  
![querformat](https://user-images.githubusercontent.com/43603628/46071548-8e2ba600-c180-11e8-99cd-34b3d89acdcf.jpg)

best Regards
Al-Matari

 * igniteui-angular version: 5.2.0
 * browser: all mobile browsers

**Comment by StefanIvanov** [comment]
In landscape you should use the horizontal Calendar layout.

**Comment by tiliev** [comment]
@al-matari, as @StefanIvanov pointed out, you can use the vertical layout of the Calendar. Here is a [live sample](https://stackblitz.com/edit/vertical-igx-date-picker?file=app%2Fdatepicker-sample-1%2Fdatepicker-sample-1.component.html). If you need to make additional changes to your layout, you can override the calendar styles via Sass.

**Comment by kdinev** [comment]
@al-matari We had a meeting to discuss a general approach to screen types, as well as other global application settings, which certain components would react with different defaults to.

What we concluded is that we should expose an app-level token, which is settable based on a developer provided strategy, which will then be used by components, like the `IgxCalendar` to change their default. This will look something like:

app.module:
`TOKEN.Display = DisplayType.TabletLanscape;`

Same approach would be taken for the display density, like:

`TOKEN.DisplayDensity = DisplayDensity.Compact`

How this would impact the components would be that the calendar would automatically become `[vertical]="true"` if `TabletLandscape` is set, and `[vertical]="false"` if `TabletPortait` is set. 

All of the properties and values I'm using are dummy, so the things may not be called the same way. What do you think?

**Comment by bkulov** [comment]
This is the PR for implementation of the DisplayDensity token:
https://github.com/IgniteUI/igniteui-angular/pull/2748

**Comment by SalkiDixit** [comment]
@tiliev I am trying to remove header form igx-calender, 
 <igx-calendar [hasHeader]="false" [selection]="selectionType"></igx-calendar>
Ignite version I am using is "^7.0.2" and Angular version is 7.2.0 but this is not working,
Kindly assit.
