### ISSUE TITLE
Column header's text is missing when column has no width set

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#2667]
### Description
Headers of some of the columns in grid are not visible.

### Steps to reproduce  
1. Run dev samples
2. Navigate to Grid Row Edit sample.
3. Scroll the grid in horizontal direction.

### Result  
Some of the column headers are not visible

### Expected result  
Column header should be visible

Setting width of the columns fixes this issue

**Comment by tachojelev** [comment]
@wnvko I tested the issue and it seems to no longer be reproduced. Can you take a look at it and possibly confirm this, so we can close this issue or provide additional details for reproducing it (I might be doing something incorrectly).
I tested the issue on the following current branches: 6.2.x, 7.1x, master (7.2.x)

**Comment by wnvko** [comment]
Yes, I am not able to reproduce this anymore. Closing this issue now.
