### ISSUE TITLE
Is it supported to have different height on each template?

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#2670]
### Description  
Is it supported to have different height on each template? Or is it against the expected usage of IgxForOfDirective?

 * igniteui-angular version: 6.1.6
 * browser: n/a

### Steps to reproduce  

1. Run the attached sample
2. Scroll down and up
## Note
igxForItemSize is set to "50px". However, the template item(div) height is overridden by its height style(random value).
`    <ng-template igxFor let-item [igxForOf]="localData"
        [igxForScrollOrientation]="'vertical'"
        [igxForContainerSize]='"500px"'
        [igxForItemSize]='"50px"'
        let-rowIndex="index">
        <div [style.height]="item.height" [style.border]="'1px solid red'">{{rowIndex}} - {{item.name}}</div>
    </ng-template>`

### Result  
Vertical virtualization works well.

### Expected result  
I am not sure if vertical virtualization is expected to work well.

### Attachments
[igniteui-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/2432997/igniteui-app1.zip)

**Comment by MayaKirova** [comment]
@ymita 
At this time this is not supported. This is also the reason variable row heights is not supported in the grid:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html#virtualization-limitations

This feature is a prerequisite for the hierarchical grid implementation so it will be implemented in a future version (probably together with the Hierarchical Grid implementation).

**Comment by ymita** [comment]
@MayaKirova, thank you for the information!
