### ISSUE TITLE
Cannot change Month/Year in IgxCalendar, rendered from DatePicker with IgxOutletOverlay property.

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular#2682]
### Description  
Cannot select new month neither new year when the IgxCalendar  is rendered from a Date Picker that has initialized igxOvelayOutlet input property.
![datepickerinitialuzation](https://user-images.githubusercontent.com/25771040/46348454-b96a3580-c657-11e8-8cef-daed922570c6.PNG)

### Steps to reproduce  

1. Open this sample: [angular-date-picker-bug-master](https://stackblitz.com/edit/angular-date-picker-bug-master)

2. Click to change either the year  or the month 
![year](https://user-images.githubusercontent.com/25771040/46348572-1665eb80-c658-11e8-92cc-161d4a051cfd.PNG)  ![month](https://user-images.githubusercontent.com/25771040/46348647-4f05c500-c658-11e8-8875-0905ffae2489.PNG)

 

### Result  
Cannot focus or change the years/months.

### Expected result  
Should be able to focus or change  the years/months.

**Comment by wnvko** [comment]
I was able to reproduce this only in the Stackblitz sample. Showing igxCalendar in igxOverlayOutlet in dev samples does not reproduce the issue. One more thing - commenting this line in Stackblitz sample ngOnInit method:

this.datePicker.outlet = this.outlet;

does not solve the issue too. Try to isolate this so we can look on to it further.
