### ISSUE TITLE
IgxChip doesn't apply css class applied through class attribute

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#2683]
### Description  
I apply a class attribute on my igxchips, but the class is not applied to the chip elements.

 * igniteui-angular version: 6.2.0-beta.3
 * browser: N/A

`<igx-chip *ngFor="let weekday of player.availability" class="day-available">`

### Steps to reproduce  

1. Define a chip
2. Add a class attribute
3. Inspect the chip's DOM

### Result  
The class is not applied.

### Expected result  
The class should be available in the class list.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/46358916-c0ea0880-c670-11e8-9912-3d73c9f825c6.png)

**Comment by skrustev** [comment]
This is duplicate to #2614.
Also this should be resolved by #2712.
