### ISSUE TITLE
IgxGrid Grouped column's title is not displayed in IE 11

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#2707]
### Description  
IgxGrid Grouped column's title is not displayed in IE 11

### Steps to reproduce  

1. Open the dev samples in IE 11
2. Go to Grid Group By sample
3. Drag a column and group it.

### Result  
The column's title is not shown.

### Expected result  
The column's title should be shown.

![image](https://user-images.githubusercontent.com/11095014/46540419-f20d4780-c8c1-11e8-9744-424295ea3d15.png)

**Comment by SlavUI** [comment]
This seems to be working 
![image](https://user-images.githubusercontent.com/33216749/47368578-937e0100-d6ea-11e8-847a-c393db12125f.png)
