### ISSUE TITLE
Create Active cell style

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2709]
### Description  
Add style for Active cell that will indicate that a cell is active, this should apply for:
- Grid cell
- Summary cell

Active cell example:
![image](https://user-images.githubusercontent.com/11193764/46597246-0a5eab80-cae8-11e8-8e2e-d9307c408094.png)

In the image above, the active cell style is with black border.

**Comment by zdrawku** [comment]
Hey team, I wanted to check what is the status of this requirement, more especially the style for "Focused Grouped row"?

**Comment by zdrawku** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/pull/2752#event-1917146658

**Comment by zdrawku** [comment]
[Grouped row focus style separate issue](https://github.com/IgniteUI/igniteui-angular/issues/2747)

**Comment by simeonoff** [comment]
@zdrawku I feel we should follow the processes to the T. Not skipping steps. We don't have designs for that feature request yet. We should plan for that first, then jump to implementation.

**Comment by zdrawku** [comment]
@StefanIvanov could you update the issue based on the design meeting from today, as well as the specification.

**Comment by StefanIvanov** [comment]
I don't seem to able to find a specification and we have only the three styles as takeaways from the meeting today:

- Row selection will use a secondary 200 background color style for the cells
- Active cell style will use a 2px cell border with secondary 500 color (outline similar to the one for editing)
- Cell selection will use a grays 200 style (if rows are selected the two colors will stack)

**Comment by StefanIvanov** [comment]
![row selected](https://user-images.githubusercontent.com/1702064/49073084-4be31b80-f23a-11e8-9d4f-0087e00f5db9.png)
![cell active](https://user-images.githubusercontent.com/1702064/49073087-4be31b80-f23a-11e8-8ff9-01f44d7f609a.png)
![cell selected](https://user-images.githubusercontent.com/1702064/49073083-4b4a8500-f23a-11e8-9bdc-64f0809811c9.png)

**Comment by desig9stein** [comment]
@StefanIvanov Which one indicates what?

**Comment by StefanIvanov** [comment]
My bad I was misled by the meta description and thought it would annotate the respective image :)

**Comment by desig9stein** [comment]
@StefanIvanov Can you also include the colours which they should use

**Comment by StefanIvanov** [comment]
They are included in the text paragraph just above the screenshots, but AFAIK @simeonoff is already playing with them

**Comment by simeonoff** [comment]
@desig9stein I would advise to wait for this pull request to get merged first https://github.com/IgniteUI/igniteui-angular/pull/3195
