### ISSUE TITLE
Ungrouping a column through the chip remove icon does not emit onGroupingDone output

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#2711]
### Description
Ungrouping a column through the chip remove icon does not emit onGroupingDone output
Go to https://stackblitz.com/edit/angular-uetflb
 * igniteui-angular version: 
 * browser: 

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-uetflb
2. Group a column and see the console --> onGroupingDone output is emitted
3. Ungroup a column by removing its chip via the X icon on the chip

### Result  
onGroupingDone output is NOT emitted

### Expected result  
onGroupingDone output to be emitted

**Comment by MartinKamenov** [comment]
@mpavlinov This bug is resolved in the pull request of @PavlovVasil:
https://github.com/IgniteUI/igniteui-angular/pull/2648
Using these changes, after clicking on the remove button the onGroupingDone event is emitted.
So this bug will be fixed after pull request is merged.
