### ISSUE TITLE
In Chrome when scroll the grid vertical the last row is previewed 2 times

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2730]
### Description  
In Chrome the when scroll horizontal the last row is previewed 2 times

 * igniteui-angular version: 6.2.x
 * browser: Chrome

### Steps to reproduce  

1. Open https://www.infragistics.com//angularsite/components/grid_summaries.html in Chrome
2. Scroll down to the end

### Result  
The last row is doubled 

### Expected result  
Rows should be previewed just once

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/46801758-3ede9b80-cd64-11e8-83c0-e8ed7013a340.png)

**Comment by zdrawku** [comment]
Fixed
