### ISSUE TITLE
Feature request - Add a custom sort functionality to igxGrid

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#2734]
### Description  
Add a functionality to specify a comparer which implements a custom sort logic and use it on sort.

**Comment by SlavUI** [comment]
@sballarati We are currently working on this one will update you as soon as we are ready :)

**Comment by hanastasov** [comment]
Needs to be refactored.

**Comment by kdinev** [comment]
@mkamiishi @sballarati This requires some further rework. It would be done and you'll be able to access it in a version next week.

**Comment by kdinev** [comment]
Closing this issue as the work on it is done. This will be officially released in: `6.1.9`, `6.2.1`, `7.0.0`.
