### ISSUE TITLE
IgxGrid date picker cell edit template outlet

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#2745]
### Description  

A recent change (#2462) to the cell edit templates moved the datepicker outlet inside the grid:
https://github.com/IgniteUI/igniteui-angular/blob/1d5a2b8d6ba89b3160d43dc07b1b42c90e2007b8/projects/igniteui-angular/src/lib/grid/cell.component.html#L25
This was done for for theming support (#2444), however it opens (back) up others:

The modal backdrop of the picker:
- has `position: fixed` and is much more likely to be affected by CSS transforms that create a new containing block in the outlet than under the document body;

  We've already dealt with that for non-modals (#2491) but there's not much we can do for modal overlays.
- is clipped by `overflow:hidden` on the grid container, part of the reasons we wanted an overlay service to begin with, right?

Case in point - our samples, if you position a grid further down enough, opening a datepicker will not only be positioned at scrollTop of the content, but also clipped by the grid container and basically invisible.

@kdinev @rkaraivanov @simeonoff 
I'd much rather the modal IgxDatePicker not getting properly themed than going back to clipped modal dialogs in the grid. If the date picker uses a drop down it'll be okay to use the grid outlet, but until then modal-s should generally stick to body to work properly.

### Steps to reproduce  

1. Step 1
2. Step 2
3. ...

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?

**Comment by simeonoff** [comment]
I agree. We should, however, consider an approach to tackle this. A valid option is to let the user specify the theme bounding selector explicitly so we can copy it over to the overlay.
