### ISSUE TITLE
Live sample hosted on StackBlitz is not running

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#2750]
### Description  
Live sample hosted on StackBlitz is not running because of error.

 * igniteui-angular version: 
 * browser: Chrome

### Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html
2. Click "VIEW ON STACKBLITZ" button
3. Observe the sample on StackBlitz

### Result  
Error occurs and the sample does not run.

### Expected result  
The sample runs without error.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/14340675/47073766-f75c8180-d233-11e8-9ee0-60cf454f2a1f.png)

**Comment by tiliev** [comment]
@ymita, thank you for your report.
The samples repository is located [here](https://github.com/IgniteUI/igniteui-angular-samples). This issue is logged and already fixed - https://github.com/IgniteUI/igniteui-angular-samples/issues/675.
