### ISSUE TITLE
IgxForOf directive failing tests

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2756]
### Description  
Run each one of the tests alone and observe the results.

### Result
Tests are failing with the following errors:

1) should not render vertical scrollbar when number of rows change to 5
     IgxForOf directive - vertical and horizontal virtual component
     Expected false to be true.
  
2) should not render vertical scrollbars when number of rows change to 0 after scrolling down
     IgxForOf directive - vertical and horizontal virtual component
     Expected false to be true.
 

3) should not render vertical scrollbar when number of rows change to 0 after scrolling right
     IgxForOf directive - vertical and horizontal virtual component
     Expected false to be true.
   

4) should not render horizontal scrollbars when number of cols change to 3
     IgxForOf directive - vertical and horizontal virtual component
     Expected false to be true.

**Comment by dkamburov** [comment]
The reason for these failing test is that there is no scrollbars on Mac OS by default when there is no mouse connected. There is an option to make the scrollbars always visible.
![image](https://user-images.githubusercontent.com/1182001/47222388-3ec34900-d3bf-11e8-9ef1-c67572fbc9e5.png)
I ran IgxForOf tests with this option and they are all passing.

Should we consider refactoring those test or should we ignore this environment(MacBook with hidden scrollbars)?

For MacBook with hidden scrollbars there is no point of verification for scrollbar presence.

**Comment by mpavlinov** [comment]
It's good that we know what the cause is. I don't think we need to take further action.
