### ISSUE TITLE
Failing tests caused by inconsistent behavior when sorting a column with equal values

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#2767]
### Description  
Found a couple of test which are failing on Travis CI, they were passing locally, but they need to be refactored, as they can give different results on different environments.

1. IgxGrid - multi-column headers sorting - sort a grouped column by API
2. IgxGrid - multi-column headers sorting - sort a grouped column by clicking on header cell UI

I believe this is cause by the different sorting algorithms. See the pic for more info:
![image](https://user-images.githubusercontent.com/1182001/47151501-9e97f200-d2e2-11e8-8578-d58bd29af301.png)

### Steps to reproduce  

1. Check https://travis-ci.org/IgniteUI/igniteui-angular/builds/443119082#L1584
2. Verification result should be strictly specified.

### Result  
It seems that on Travic CI another sorting takes place and a record with ID - BLONP is sorted before the one with ID - FRANR

### Expected result  
The test should be done in a way that there is consistent result for verification

**Comment by tiliev** [comment]
@HristoP96, please take a look at [stable sorting](https://stackoverflow.com/questions/1517793/what-is-stability-in-sorting-algorithms-and-why-is-it-important).

**Comment by mpavlinov** [comment]
@tiliev @HristoP96 Why not just sorting by "ContactName" column?
