### ISSUE TITLE
Template editor does not end edit by calling cell.update() on Enter pressed

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#2773]
### Description  
Template editor does not end edit by calling cell.update() on Enter key press.

 * igniteui-angular version: 6.2.0-beta.3
Note: This is not reproduced on 6.0.3

 * browser: Chrome, IE11

### Steps to reproduce  

1. Run the attached sample
2. Enter edit mode on "startDate" cell
3. Type some characters on the editor
4. Hit enter to end edit mode

### Result  
Edit mode does not end.

### Expected result  
Edit mode ends and edited value is set to the cell.

### Attachments
[igniteui-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/2494483/igniteui-app1.zip)

**Comment by hanastasov** [comment]
I am working on fixing this behavior. Meanwhile, the customers can avoid it by stopping the event propagation in the keydown event listener (because both the input in the template and the cell itself listen for the keydown event):

                <igx-input-group>
                    <input type="text" [ngModel]="value" igxInput
                        **(keydown.enter)="handleUpdate($event, cell, startDate.value)"**
                        #startDate="ngModel">
                    </igx-input-group>

...
    handleUpdate(event, cell, value) {
        **event.stopPropagation();**
        cell.update(value);
    }

**Comment by hanastasov** [comment]
Issue is fixed in version 7.
