### ISSUE TITLE
The filtering icon cannot be clicked when the header is not wide enough

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-angular#2778]
### Description  
When a column header is not wide enough and filtering is enabled for it - the filtering icon is shown inside the next column header and when you click it - the filtering dialog is not opened.

 * igniteui-angular version: 6.1.x
 * browser: N/A

### Steps to reproduce  

1. Run an igxGrid with a filterable column which width is 50-60px
(I am able to reproduce this issue with width="60px" in Chrome, width="50px" in IE)
2. Click the filtering icon to show the filtering dialog

### Result  
The filtering icon is shown inside the next column header.
The filtering dialog is not shown after clicking the filtering icon.

### Expected result  
The filtering icon is shown inside the correct column header.
The filtering dialog is shown after clicking the filtering icon.

### Attachments  
![screenshot](https://user-images.githubusercontent.com/2778393/47206637-d0b45d00-d391-11e8-8618-5b2074af5720.png)

[sample_filtering.zip](https://github.com/IgniteUI/igniteui-angular/files/2494972/sample_filtering.zip)

**Comment by bkulov** [comment]
I'm closing this bug because we no longer support 6.1.x version and this UI doesn't exist in 6.2.x and newer versions.
