### ISSUE TITLE
Some columns that are next to column-groups cannot be resized after moving was performed

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2783]
### Description  
Some columns that are next to column-groups cannot be resized after moving was performed.

 * igniteui-angular version: 6.1.x, 6.2.x
 * browser: any

### Steps to reproduce  

1. Run the "Grid Column Groups" dev demo.
2. Try resizing the "ID" column.
 **2.1** Resizing works as expected.
3. Move the "General Information" column group on right of the "ID" column.
4. Try resizing the "ID" column.
 **3.1 (issue)** Resizing **cannot** be performed. (resizing indicator is gone)
5. Move the "General Information" column group back on the left of the "ID" column.
6. Try resizing the "ID" column.
 **6.1 (issue)** Resizing **cannot** be performed. (although resizing indicator is present)
### Result  
The "ID" column can**not** be resized at steps **3.1** and **6.1**.

### Expected result  
The "ID" column can be resized at steps **3.1** and **6.1**.

### Attachments  

![resizing](https://user-images.githubusercontent.com/12784974/47220641-09b4f780-d3bb-11e8-950d-f600a5c639b8.gif)

**Comment by zdrawku** [comment]
@nrobakova could you take a look at this injury
