### ISSUE TITLE
Shadows Styleguide does not show how to use the classes mentioned

### ISSUE THREAD

**Issue by jdk339** [IgniteUI/igniteui-angular#2788]
### Description  
The [Shadows Styleguide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/shadows.html) does not explain how to use the classes for providing shadows to elements.

### Expected result  
The docs should explain, or show an example, how to use the classes that are mentioned.

**Comment by kdinev** [comment]
@jdk339 Our SassDoc site will be live at the beginning of next week, so you'll have online access to the full Sass API documentation on elevations and shadows :)

![image](https://user-images.githubusercontent.com/1472513/47345758-38311c00-d6b4-11e8-8816-456caf5c256b.png)

**Comment by zdrawku** [comment]
@jdk339 [This](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/#function-igx-elevations) is the API documentation of elevations and shadows and [here you can find a demo app](https://www.infragistics.com/products/ignite-ui-angular/angular/components/shadows.html#elevations-setting) that we've created to demonstrate the elevations settings.
