### ISSUE TITLE
Column template continues to be evaluated.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#2791]
### Description  
Column template continues to be evaluated.

 * igniteui-angular version: 6.1.7
 * browser: Chrome, IE11, Edge
 * component: igx-grid

### Steps to reproduce  

1. Unzip the attached sample and execute the following commands.
>npm install
>npm start
2. Open http://localhost:4200 with a browser.
-> Observe the console of browser's developer tool.

### Result  
The function which is specified in the template continues to be called endlessly.

### Expected result  
The function which is specified in the template should be called only once.

### Attachments  
[my-app2.zip](https://github.com/IgniteUI/igniteui-angular/files/2500218/my-app2.zip)

**Comment by zdrawku** [comment]
@norikois this issue is fixed in version @6.2.0-beta.4, the fix is part of the keyboard navigation implementation that we've added. It would be very hard to add the whole keyboard navigation logic in 6.1.x so we need time to figure this out, meanwhile you can use version @6.2.0-beta.4

**Comment by zdrawku** [comment]
Closing this issue, my suggestion is to update to 6.2.x version
