### ISSUE TITLE
When move/sort a column keyboard navigation does not start at correct position

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2797]
### Description  
When move a column keyboard navigation does not start at correct position

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Click on a cell in column ContactTitle
3. Move column ContactTitle at first position
4. Press arrow right key

Note: Same is valid when sort a column where the selected cell is

### Result  
Cell in column Address is selected

### Expected result  
Cell in column Id should be selected

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ddincheva** [comment]
This issue is no longer reproducible neither in version 6.2.x nor in 7.1.x.
