### ISSUE TITLE
IE11: When open filtering dialog for a column the filter for other columns is cleared

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2799]
### Description  
When open filtering dialog for a column the filter for other columns is cleared

 * igniteui-angular version: 6.2.x
 * browser: IE11

### Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Open filter dialog for column Id and filter with condition contains and value 'an'
3. Click on Close in the filtering dialog
4. Open filtering dialog for column Address and wait for a second

### Result  
Filter is cleared and all records are previewed

### Expected result  
Filtering for other columns should not be cleared

**Comment by bkulov** [comment]
There is new filtering UI in 6.2.x in which this bug is not reproducible.
I'm closing this bug as we no longer support 6.1.x.
