### ISSUE TITLE
Using grid formatter function

### ISSUE THREAD

**Issue by asulaiman** [IgniteUI/igniteui-angular#28]
How would one go about using a formatter function to map nested values in the grid? For example in order to map a value within nested objects in the ignite grid, you need to do the following - 

headerText: "Quantity", key: "Results", dataType: "object", formatter: function(val){
	            																			return val.Quantity;
},

**Comment by mpavlinov** [comment]
Try with the following syntax:
In HTML:
```
<column key="Results" header-text="Quantity"  width="250px"  data-type="object" formatter="{{productNameFormatter}}"></column>
```
In Controller:
```
$scope.productNameFormatter = function(val, row) {
    return val.Quantity;
}
```
