### ISSUE TITLE
When grid has vertical scroll and change page not correct items are previewed 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2800]
### Description  
When grid has vertical scroll and change page not correct items are previewed 

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridCellEditing
2. In the first grid scroll with the mouse wheel once
3. Go to the last page
3. Go to the first page

### Result  
Items from the last page are previewed in the grid. After scroll the correct items are previewed

### Expected result  
Correct items should be previewed

**Comment by rkaraivanov** [comment]
The problem seems to be the `IgxForOf` startIndex which has a value of -1 in case of the issue.
When fixing it make sure to test filtering, paging and resizing; behaviors that change both startIndex/chunkSize.
