### ISSUE TITLE
Samples do not work in StackBlitz

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular#2814]
### Description  
Samples do not work in StackBlitz because of Sass error. Further investigation is needed. We should find what is the cause of this and decide whether there is an issue at our end or it is a third-party issue related to StackBlitz. As @hanastasov pointed out, this might be connected with the older angular 5 config file we are currently using (this is a pending issue - https://github.com/IgniteUI/igniteui-angular-samples/issues/387). Judging by the error there is some issue with the ripple, perhaps a typo somewhere in the Sass.

 * igniteui-angular version: 6.2.0-beta.4
 * browser: Chrome, Firefox and Edge. It works in IE because we use CSS instead of Sass there.

### Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_paging.html
2. Hit open in StackBlitz

### Result  
```
Error in igniteui-angular/lib/core/styles/base/utilities/_mixins.scss (228:12)
argument `$map` of `map-get($map, $key)` must be a map

Backtrace:
sass/igniteui-angular/lib/core/styles/base/utilities/_mixins.scss:228, in function `map-get`
sass/igniteui-angular/lib/core/styles/base/utilities/_mixins.scss:228, in mixin `igx-root-css-vars`
sass/igniteui-angular/lib/core/styles/components/ripple/_ripple-theme.scss:38, in mixin `igx-ripple`
sass/igniteui-angular/lib/core/styles/themes/_index.scss:111, in mixin `igx-theme`
sass/~/styles.scss:4
```

![error](https://user-images.githubusercontent.com/6439482/47419579-2d928780-d785-11e8-9f07-e3420f2691fa.PNG)

### Expected result  
The sample should work.

### Details
The issue is introduced in version `6.2.0-beta.4`. The samples work correctly with `6.2.0-beta.3` - https://stackblitz.com/edit/iggrid-working-beta-3. The issue might be connected with some of these changes:

![diff-1](https://user-images.githubusercontent.com/6439482/47419739-7ea27b80-d785-11e8-982b-780ddfc5af1d.PNG)
---
![diff-2](https://user-images.githubusercontent.com/6439482/47419742-8104d580-d785-11e8-95ff-5d7fed8af23e.PNG)

**Comment by zdrawku** [comment]
@tiliev once we merge this change and tag a new version, we will be able to test the change with StackBlitz.

Using of map, empty-map, list, null etc - [Example](https://www.sassmeister.com/gist/4e4be722bb130f10cc0c6a712d2d996f)

**Comment by luiscla27** [comment]
Hello, this issue also occurs at DatePicker demos ([example](https://stackblitz.com/angular/egkjqjgrnpe)):

https://www.infragistics.com/products/ignite-ui-angular/angular/components/date_picker.html

![image](https://user-images.githubusercontent.com/29953012/47441093-10ee5380-d775-11e8-90e9-ee1bbeb70f0f.png)

**Comment by tiliev** [comment]
@luiscla27, the fix will affect all of the samples with similar error, including the date picker's samples.

**Comment by luiscla27** [comment]
Thank you @tiliev !

**Comment by tiliev** [comment]
@zdrawku @simeonoff 
After the release of the [Beta 6](https://github.com/IgniteUI/igniteui-angular/releases/tag/6.2.0-beta.6) the issue still persists. After further research I see one of the packages [used by StackBlitz](https://c.staticblitz.com/d/plugin-sass.4b4ff5a0b4b637b9393.js) is [Sass.js](https://github.com/medialize/sass.js). The next step would be to compile our Sass with Sass.js, hopefully we can reproduce the error. Please keep in mind we use `node-sass` for [compiling to CSS](https://github.com/IgniteUI/igniteui-angular-samples/blob/master/live-editing/services/SassCompiler.ts) in [igniteui-angular-samples](https://github.com/IgniteUI/igniteui-angular-samples). In the Sass.js docs we can see:
> Sass.js and node-sass should generate the same results.

### Current Workaround to open samples in prod in StackBlitz
Open the documentation in IE 11, after that hit "View in StackBlitz". Use the URL to play in any browser.

**Comment by tiliev** [comment]
After further investigation it turned out Stackblitz uses `Sass.js` version `0.10.6`. This parses uses Sass version `3.4.5`. In our code we use first-class functions which are supported from Sass version `3.5`. We should introduce a fallback.

**Comment by tiliev** [comment]
I logged an issue in Stackblitz related to the older Sass.js version - https://github.com/stackblitz/core/issues/757
