### ISSUE TITLE
In pinned column the cell editor is not fully visible

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2857]
### Description  
In pinned column the cell editor is not fully visible

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Click on button "Pin/Unpin 'ContactName'"
3. Open a cell in column ContactName is edit modes

### Result  
Cell editor right border is not visible

### Expected result  
Cell editor should be visble

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/47642324-0961ec80-db71-11e8-8eba-fdbb4dc15166.png)

**Comment by nrobakova** [comment]
I am closing the issue because of the comment.

**Comment by simeonoff** [comment]
@nrobakova @tiliev We can still color the pinned border when we are in cell editing to make it look right.
