### ISSUE TITLE
Column filter is cleared when a filter popup of another column is displayed (IE only)

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#2864]
### Description  
Column filter is cleared when a filter popup of another column is displayed (IE only)

 * igniteui-angular version: 6.2.0-beta.7
 * browser: IE11

### Steps to reproduce  

1. Access the following page with IE.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html
2. Click a filter icon on 'Product Name' column.
3. Enter some text in the input field and click CLOSE button on the popup.
4. Click a filter icon on 'Quantity Per Unit' column.

### Result  
Column filter for 'Product Name' is cleared.

### Expected result  
Column filter for 'Product Name' is not cleared.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by SlavUI** [comment]
@mkamiishi We are now releasing a new Filtering in which this is working correctly. I will be closing this one for now :)
