### ISSUE TITLE
Visual improvements in quick filtering row

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-angular#2875]
- [x] In IE11 the chips in filtering cell are collapsed
![default](https://user-images.githubusercontent.com/2705882/47728505-2842aa80-dc67-11e8-9172-fe9425b4a2be.png)

- [x] In IE11 the arrow in logic operator button is not properly placed
![default](https://user-images.githubusercontent.com/2705882/47728685-7eafe900-dc67-11e8-9647-ea8e79ca7911.png)

- [x] Row selection check-box in the top left corner is partially covered by the filtering row
![default](https://user-images.githubusercontent.com/2705882/47728941-faaa3100-dc67-11e8-9dcc-f83efe20e340.png)

- [x] When the filtering row is visible there is a horizontal line at the bottom of it
![default](https://user-images.githubusercontent.com/2705882/47729174-5bd20480-dc68-11e8-8296-4c25b5136ff9.png)

- [x] When the column is too wide there is space between chips and logic operators
![default](https://user-images.githubusercontent.com/2705882/47844792-feef5f00-ddcb-11e8-9c64-637e3b7e7b2a.png)

- [x] Make the filtering condition's dropdown smaller - requires a modifier for desktop and mobile styles based on platform

- [x] Make the logical operator button smaller - requires button display density implementation

~~When resizing a column and the filtering row is visible the resizer goes under the filtering row - afaik this can't be achieved with the current grid implementation~~

- [x] Expand/Collapse all groups button in the top left corner is partially covered by the filtering row
![new bitmap image](https://user-images.githubusercontent.com/34062094/47843199-88e8f900-ddc7-11e8-82d6-2fa3d666b494.png)

~~When filter row is opened and we start to resize horizontally, the filtered column moves above the select all checkbox instead of bellow it.
![new bitmap image](https://user-images.githubusercontent.com/34062094/47858739-5e159980-ddf5-11e8-97ed-e85b69c78ff6.png)~~

**Comment by bkulov** [comment]
There are some blockers currently and the rest of the things which are not yet done will be done later.

**Comment by simeonoff** [comment]
@radomirchev I consider all possible changes to have been completed. If you find the current state of the filtering row unacceptable please open a new issue.

**Comment by radomirchev** [comment]
@simeonoff I agree. If needed new issues could be created, this one is considered done.
