### ISSUE TITLE
[Chrome] Vertical scrollbar is not aligned properly, which makes cell values visible on its right side

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2884]
### Description  
Vertical scrollbar is not aligned properly, which makes cell values visible on its right side.

 * igniteui-angular version: 6.1.x, 6.2.x
 * browser: **Chrome**

### Steps to reproduce  

1. Run the "Grid Column Resizing" dev demo.

### Result  
Vertical scrollbar is **not** aligned properly, which makes cell values visible on its right side.

### Expected result  
Vertical scrollbar is aligned properly and cell values are **not** visible on its right side.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/47776453-1f031d80-dcfb-11e8-8832-3866c1fbeb3f.png)

**Comment by nrobakova** [comment]
I tested this issue in 6.1.x and 6.2.x latest versions and cannot reproduce it.
