### ISSUE TITLE
[Chrome] Some row separators are not fully rendered among the row selector area with 'cosy' and 'comfortable' display density

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2891]
### Description  
Some row separators are not fully rendered among the row selector area with 'cosy' and 'comfortable' display density

* OS: Windows
 * igniteui-angular version: **6.2.x**
 * browser: **Chrome**

**NOTES:**
- The issue is **not** reproduced in 6.1.x with Chrome.
- The issue is **not** reproduced with Firefox, IE and Edge.

### Steps to reproduce  

1. Open the **grid-cellEditing.html** file and comment the first column that is templated. (In order better observe the issue)
2. Run the **Grid Cell Editing** dev demo
3. Change the display density to either **cosy** or **comfortable**

### Result  
Some row separators are not fully rendered in the row selector area with '**cosy**' and '**comfortable**' display density

### Expected result  
All row separators are fully rendered among in row selector area.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/47787732-72379900-dd18-11e8-8f97-ef6913d41f45.png)

**Comment by desig9stein** [comment]
@tachojelev I test with latest Chrome Version 70.0.3538.110, both Windows and Mac. Can you please test and if you can't reproduce it close the issue

**Comment by tachojelev** [comment]
@desig9stein, the issue seems to be no longer reproduced.
