### ISSUE TITLE
Cannot type negative value in filtering input box.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#2899]
### Description  
Cannot type negative value in filtering input box.

 * igniteui-angular version: 6.2.0-beta.7
 * browser: Chrome, IE11
 * igx-grid

### Steps to reproduce  

1. 'npm install' and 'npm run' the attached reproducible sample.
2. Click the filter icon of "Value" column.
3. Type '-' in filter dialog's text box.

### Result  
NaN is displayed.

### Expected result  
'-' should be displayed

### Attachments  
[my-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/2537460/my-app1.zip)

**Comment by bkulov** [comment]
The current filtering UI will be deprecated in the final 6.2 version. In the new filtering UI this bug is not reproducible.

**Comment by bkulov** [comment]
I'm closing this issue since it's reproducible only in 6.1.x version which we no longer support.
