### ISSUE TITLE
Unable to get all selected values for multiselect combobox

### ISSUE THREAD

**Issue by asulaiman** [IgniteUI/igniteui-angular#29]
If you enable the multiselect option for combobox, the model does not get updated with all values selected it only gets updated with the first one. Will look to do a pull request to fix this.

**Comment by mpavlinov** [comment]
Did you check the following [commit](https://github.com/IgniteUI/igniteui-angular/commit/a6e5d7a694fcf3fed4ff1ac1faddd8131cc8e1d4)? It should now work with [igCombo.multiSelection](http://help.infragistics.com/jQuery/2014.2/ui.igcombo#options:multiSelection).
