### ISSUE TITLE
An error is returned when update a filtered cell and press Tab key

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2901]
### Description  
An error is returned when update a filtered cell and press Tab key

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. In dev demos open sample gridCellEditing
2. In first grid (gridWithPK) filter column ReorderLevel with value 10 and condition 'Equals'
3. 3 rows are previewed
4. In the 3th row double click on cell in column ReorderLevel  to enter edit mode and change its value to 11
5. Press Tab or Shif+ tab

Note: this issue is similar to the issue #2465

### Result  
In the console an error is previewed:
IgxGridRowComponent.html:13 ERROR Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

### Expected result  
No errors should be previewed.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ddincheva** [comment]
The described issue is not currently reproducible in 6.2.x, 7.0.x and 7.1.x.
