### ISSUE TITLE
After sort the cell in previous selected column cannot be selected

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2903]
### Description  
After sort the cell in previous selected column cannot be selected

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Click on a first row cell 
3. Sort column Id in descending order
4.  Click on first row cell

### Result  
Cell is not selected

### Expected result  
Cell should be selected

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by zdrawku** [comment]
It is expected to be fixed with multi-cell selection merge.

**Comment by nrobakova** [comment]
Now when multi cell selection is implemented the cell stays selected after sort.
