### ISSUE TITLE
Feature Request: IgxToggle with no overlay

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#2914]
### Description  
IgxToggle currently wraps its contents inside an IgxOverlay so its contents are always postion "fixed" and display "flex" so it works like a custom dialog.

 * igniteui-angular version: 6.2.0-beta.7
 * browser: Chrome 70.0.3538.77

### Result  
[Current behaviour](https://stackblitz.com/edit/angular-fsnmtp)
![image](https://user-images.githubusercontent.com/29953012/47945938-63451800-decb-11e8-8856-166b235b6314.png)

### Expected result  
The expected result would be that the box stays where it originally was, it'll look something like this:
![image](https://user-images.githubusercontent.com/29953012/47945997-e2d2e700-decb-11e8-997c-e5695621d543.png)

It seams that the content is already there hidden by the `--hidden` class (`toggle-content igx-toggle--hidden`) the expected result would include the current animations ([something like this](https://angular-muvaqu.stackblitz.io/)).
![image](https://user-images.githubusercontent.com/29953012/47946059-5117a980-decc-11e8-84a3-78fbe9a4660d.png)

**Comment by ViktorSlavov** [comment]
@luiscla27 
You can check out the `IgxExpansionPanelComponent` - it's a lightweight component that allows you to dynamically display content without making use of the overlay service.
It is slated to be released in the new 6.2 version of the igniteui-angular suite.
I've put together a [small sample](https://stackblitz.com/edit/angular-jwxus5?file=app%2Fapp.component.html) that you can play around with - hope it's useful to you!

**Comment by luiscla27** [comment]
Hello Viktor, unfortunately the `IgxExpansionPanelComponent` doesn't fulfill our requirement, the main reason is **_desing_** im putting together a component needed for our application and `IgxExpansionPanelComponent` seems to be meant only for static content. 

Right now it looks like this, its not finished yet but i guess i'll have to set the animation manually.

![igniteui - toggle 2914](https://user-images.githubusercontent.com/29953012/48151531-1d030680-e287-11e8-842f-4b64f3beef68.gif)

**Comment by luiscla27** [comment]
Update, im using igniteui-angular latest version `6.2.0-rc.1`

**Comment by ViktorSlavov** [comment]
@luiscla27 
Thank you for the detailed exampled, Luis!
As far as I understand, you want to display an input form field inside of the panel body, which is a scenario which the expansion-panel is able to cover. When you can, please check [this sample](https://stackblitz.com/edit/angular-pkrnc9?file=app%2Fexpansion-sample-6%2Fexpansion-sample-6.component.html) and let me know if something similar works for you.
You can find further useful information on the `IgxExpansionPanel`, as well as some demos covering different user scenarios, on the [official documentation page](https://www.infragistics.com/products/ignite-ui-angular/angular/components/expansion_panel.html).

**Comment by luiscla27** [comment]
Thank you for the documentation link @ViktorSlavov, that example fulfills our requirement so i guess you can cancel this feature request :)
