### ISSUE TITLE
Errors are thrown when CryptoApp is built with --prod

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#2916]
### Description  
Error is thrown when trying to open application built with --prod --aot.

1. Open crypto app locally
2. Execute `ng build --prod --aot` 
3. Go to `dist` folder
4. Use IIS or lite-server to serve the app
5. Go to block-grid view
6. Error is thrown

Result:
![image](https://user-images.githubusercontent.com/11193764/47991922-2f990680-e0f4-11e8-9591-f480e45ae3f2.png)

[App with --prod](https://filetransfer.infragistics.com/public.php?service=files&t=c2924c12e4aec6d6da71a044d21d6879)
[App without --prod](https://filetransfer.infragistics.com/public.php?service=files&t=9d371c82a5dea57cba5e6f502a17262d)

**Comment by zdrawku** [comment]
The app also throws the errors below:
![image](https://user-images.githubusercontent.com/11193764/48005928-53bd0d80-e11d-11e8-82fd-8fe08c379bfd.png)

And:

![image](https://user-images.githubusercontent.com/11193764/48005962-66374700-e11d-11e8-8c73-3084a8e586f1.png)

**Comment by bkulov** [comment]
I'm closing this issue as it's no longer applicable.
