### ISSUE TITLE
Filtering chip disappears when filter a column from column-group through API

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#2926]
### Description  
Filtering chip disappears when filter a column from column-group through API

 * igniteui-angular version: 6.2.x
 * browser: any

**NOTES:**
- The issue is reproduced for both the **IgxGrid** and the **IgxTreeGrid**.
- The issue is reproduced **ONLY** when filtering is performed on a column that is in a **column-group**!
- After **step 4**, if another filter chip is opened and closed, the view gets refreshed and the issue is fixed.

### Steps to reproduce  

1. Open the **grid-column-groups.sample.html** dev demo template and add  a filter button in markup:
```html
...
<button (click)="test()">filter</button>
```
2. Add the following handler in **grid-column-groups.sample.ts**:
```typescript
  test() {
        this.grid.filter('ContactName', 'anna', IgxStringFilteringOperand.instance().condition('contains'));
    }
```
3. Run the **"Grid Column Groups"** dev demo.
4. Observe the **"Contact Name"** column's filter chip and click the **filter** button.

### Result  
The chip disappeared.

### Expected result  
The chip is still present and properly updated with the filtering condition from the API.

### Attachments  

![filter](https://user-images.githubusercontent.com/12784974/48002698-f4f39600-e114-11e8-9066-5fb44d216f9f.gif)

**Comment by norikois** [comment]
Hello,
This issue also occurs when a column in a column-group is filtered from UI.
I attached a sample.
Could you cover this scenario by this issue, too?

Steps to reproduce:
1. npm install, npm start and open http://localhost:4200.
2. Click the filter icon of "Name" field and filter by any text, for example "a".
3. Click "Close" button.

Actual:
The filter chip of "Name" field is not displayed.

Expected:
The filter chip of "Name" field is displayed.

Sample:
[my-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/2564645/my-app1.zip)
