### ISSUE TITLE
When using Filter row to filter numbers the arrow for changing the number is cut off

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#2927]
### Description  
Describe the issue.

 * igniteui-angular version: 6.2.0
 * browser: Chrome on Windows

### Steps to reproduce  

1. Open Filter row in a number column
2. See the arrows for up and down
3. The UP arrow is slightly cut off 

### Result  
The UP arrow is slightly cut off 

### Expected result  
The Up Arrow should be fully visible

### Attachments  
![image](https://user-images.githubusercontent.com/33216749/48006796-ea3dfe80-e11e-11e8-9a90-c5fb5e87675e.png)

**Comment by desig9stein** [comment]
@SlavUI In which browser is this happening?

**Comment by SlavUI** [comment]
@desig9stein Chrome :)
