### ISSUE TITLE
Filter's UI dropdown is hidden under the bottom level of the grid

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#2928]
### Description  
Filter dropdown is hidden under the bottom level of the grid

 * igniteui-angular version: all
 * browser: 6.2.x

### Steps to reproduce  

1. Go to dev samples - "Grid Column Moving" , "Grid Summary"
2. Open the Filtering dropDown

### Result  
The end of operands list is not visible.

### Expected result  
The end of operands list is should be visible.

### Attachments  
![image](https://user-images.githubusercontent.com/11095014/48007867-27a38b80-e121-11e8-81b6-43a2d9ab9c4f.png)

**Comment by bkulov** [comment]
Filtering conditions dropdown now have a limited height so please take a look at the case where it goes under the summaries.

**Comment by desig9stein** [comment]
We can increase the z-index of .igx-grid__outlet from 2 to 1003 in order to make it bigger than the z-index footer, I test that and it fixes the issue @simeonoff are you ok with that?

**Comment by desig9stein** [comment]
Here is a table with all z-index added form SCSS
![screenshot 2018-11-14 at 14 33 50](https://user-images.githubusercontent.com/21260963/48482920-ab90fe00-e81a-11e8-8cb0-d61962beb5d2.png)

**Comment by simeonoff** [comment]
@desig9stein thanks for the z-index mapping, however without markup context it's still difficult to grasp the z-index structure. Also, I don't think this table takes into account all dynamically assigned z-index values.
