### ISSUE TITLE
In batch editing when change Boolean value form true to false the row is not marked as updated

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2934]
### Description  
In batch editing when change Boolean value form true to false the row is not marked as updated

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridRowEdit
2. In the second grid ("Grid with rowEditing and with transactions") change value in column ' PINNED DISCONTINUED' and row 1 from true to false and click button Done

### Result  
Row is not marked as updated

### Expected result  
Row should be marked as updated

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by desig9stein** [comment]
I will apply a simple fix, for now, but I think we should create a table with all components that have z-index and start adding some normal values like for example from 1 to 10. Value like 9999 doesn't seem right to me. Here is an example of what I am imagining.

![screenshot 2018-11-06 at 13 40 34](https://user-images.githubusercontent.com/21260963/48062070-a2c07c80-e1c9-11e8-9e2f-700338618ab9.png)
