### ISSUE TITLE
When columns have specified width arrow Right key does not work 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2939]
### Description  
When columns have specified width arrow Right key does not work 

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-kmazuu?file=app/grid/grid-sample-pinning/grid-pinning.component.html
2. select cell in column 'company name' and row 1
3. Press Ctr+Arrow right
4. Cell in column Fax is selected
5. Press arrow left
6. Cell in column Phone is selected
7. Press arrow right

### Result  
Cell selection is not changed
### Expected result  
Cell in column Fax should be selected

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ddincheva** [comment]
This issue is no longer reproducible neither in version 6.2.x nor in version 7.1.x.
