### ISSUE TITLE
When change page or pin column the cell edit mode is closed

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2956]
### Description  
When change page or pin column the cell edit mode is closed

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridCellEditing
2. Open a cell in edit mode
3. Change page or pin a column

### Result  
Cell edit mode is closed

### Expected result  
Cell edit mode should not be closed or the topic for editing should be changed, because now it is:

The cell remains in edit mode when you scroll vertically or horizontally, click outside the grid, resize column, pin column or go to another page.
https://www.infragistics.com//angularsite/components/grid_editing.html

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/48118804-0e602380-e276-11e8-9e63-1b3c3328daa6.png)

**Comment by Lipata** [comment]
@rkaraivanov as you know the editing logic for row editing and cell editing was refactored. So I guess we want similar behavior for cell editing and row editing - when on paging and pinning the cell stays in edit mode then row will also stay in edit mode? In that case we we will consider that as a bug and will fix it, but I remember that we discussed that we should exit edit mode in that cases and in the [specification ](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Editing) for row editing we have described that the row will exit edit mode when paging and pinning. Let's clear that and fix the behavior and specification.

@StefanIvanov, @kdinev do you think that the behavior, related to the cell editing and described in the documentation, should stay and we just make the necessary corrections in the row editing and its specification.

**Comment by StefanIvanov** [comment]
IMO the cell should stay in edit mode and we must implement the behavior treating the current closing of edit mode as a bug

**Comment by Lipata** [comment]
@StefanIvanov I commented this with @rkaraivanov and we prefer that you stay in edit mode only on scroll and only when you accidentally click outside the grid. In other other operations where you intentionally pin or move a column or change page - to exit edit mode.

**Comment by Lipata** [comment]
https://github.com/IgniteUI/igniteui-docfx/pull/867 This pull requests updates the documentation and I close this bug, cause no changes will be applied to the code. The grid will stay in edit mode only on scroll and when you accidentally click outside the grid.
