### ISSUE TITLE
Extend DropDown and Combo to support DisplayDensity

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-angular#2960]
Extend DropDown and Combo to support DisplayDensity similar to the input group and the grid.

**Comment by ViktorSlavov** [comment]
As discussed, we need to further look into if and how exactly combo/drop down items display density will be implemented.
For the time being, we are adding only extending the `DisplayDensityBase` class in the `IgxComboComponent`, allowing input of display density and passing it down to the `input-group` (#2410)

**Comment by DaniMarinov** [comment]
@desig9stein You can find the updated spec here https://github.com/IgniteUI/igniteui-angular/wiki/IgxCombo-(Component)#2-design-and-display-density

**Comment by DaniMarinov** [comment]
@desig9stein Find the updated spec for the Dropdown component https://github.com/IgniteUI/igniteui-angular/wiki/DropDown-Specification#2-display-density-design
