### ISSUE TITLE
igx-grid - groupsRecords is not updated yet at the time of onGroupingDone event.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#2967]
### Description  
`groupsRecords` is not updated yet at the time of onGroupingDone event.

 * igniteui-angular version: 6.2.0
 * browser: N/A

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-ongroupingdone-620
2. Open the console.
3. Drag and drop a column to the group area.

### Result  
Although `onGroupingDone` event is emitted, `groupsRecords` is not updated yet. We get the previous value.

### Expected result  
Until 6.1.8, this value had been updated as expected.
https://stackblitz.com/edit/igx-grid-ongroupingdone-618

**Comment by SkylerLutz** [comment]
I'm seeing this issue in 13.1.12 and 13.2.24. Can this please be reopened?

**Comment by SkylerLutz** [comment]
@kdinev 
I'm seeing this issue in 13.1.12 and 13.2.24. Can this please be reopened? Thank you

**Comment by kdinev** [comment]
@SkylerLutz @ChronosSF I'm reopening the issue. Someone will take a look at whether and why it has been regressed,

**Comment by ChronosSF** [comment]
@SkylerLutz , I tried this here: https://stackblitz.com/edit/angular-hv2b6k-wnnhgk using the latest supported version 15.1 and it works fine. I am console logging what `grid.groupsRecords` returns in the handler of `groupingDone` and it looks correctly updated.

Have in mind that `groupsRecords` returns a tree-like structure where the initial array contains only top-level group records. You need to drilldown to get child groups, e.g. `grid.groupsRecords[0].groups` returns the second level children for the first group record, `grid.groupsRecords[0].groups[0].groups` would be the third level children of the first parent and the first of its children, etc.
