### ISSUE TITLE
When a cell is opened in edit mode and move scroll the cell editor is flickering

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2971]
### Description  
When a cell is opened in edit mode and move scroll the cell editor is flickering

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridCellEditing
2. Open a cell in column OrderDate and row 5 in edit mode
3. Start scrolling

### Result  
Cell editor is flickering

### Expected result  
Cell editor should not flicker

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by rmkrmk** [comment]
Adding "regression" label because this issue is not reproducible in 6.1.x
