### ISSUE TITLE
igxToolbar should have the option to add custom template

### ISSUE THREAD

**Issue by jdk339** [IgniteUI/igniteui-angular#2983]
### Feature Request

It would awesome if the Grid (`igx-grid`) could have additional toolbar features, such as clearing the current filters, clearing sorting, and toggling the summary. Currently, it's no trouble to include such functionality elsewhere, but it would make sense to be in the Grid toolbar along with the other features.

Here is how I currently do it outside the grid:

    <div>
      <button igxButton="flat" igxRipple igxRippleCentered="true" (click)="grid.clearFilter()">
        <igx-icon fontSet="material" name="clear"></igx-icon>
        CLEAR FILTERS
      </button>
      <button class="marg-l-10" igxButton="flat" igxRipple igxRippleCentered="true" (click)="grid.clearSort()">
        <igx-icon fontSet="material" name="clear"></igx-icon>
        CLEAR SORTING
      </button>
      <igx-switch class="marg-l-10" [checked]="summariesEnabled" (change)="toggleSummaries($event)">
        TOGGLE SUMMARY
      </igx-switch>
    </div>

![igx grid toolbar idea](https://user-images.githubusercontent.com/16578448/48282444-b36e2e00-e427-11e8-9a8d-3b3d5f2baab7.png)

**Comment by SlavUI** [comment]
@kdinev and @StefanIvanov Guys what do you think ?

**Comment by kdinev** [comment]
The issue is similar to #2887  The toolbar should expose the empty outlet for templating by the user. There will be different use-cases for actions developers want to put in the toolbar, so instead of trying to exhaust them all with configuration, we should just expose a template. 

@SlavUI Can we prioritize this for the next sprint?

**Comment by StefanIvanov** [comment]
I agree 100% with @kdinev and that would allow @jdk339 to use the snippet and create such a template but spare his time regarding styling as the toolbar will define that for him.

**Comment by kdinev** [comment]
@jdk339 This update will appear with the next tag - `7.1.0`, as well as in patches `6.2.4` and `7.0.3`
