### ISSUE TITLE
Redefining the columns in igx-grid causes the grid to crash

### ISSUE THREAD

**Issue by ammritt** [IgniteUI/igniteui-angular#3010]
### Description  
I have a service/store  based on which I define my columns and the dropdown data in them. I tried to duplicate that logic in the stackblitz example below. When service has new data, I try to re-instantiate the columns but that causes the grid to crash unexpectedly.

 * igniteui-angular version: 6.1.3
 * browser: Google Chrome Version 70.0.3538.102

### Steps to reproduce  

Click Test on the Stackblitz

### Result  
Grid is crashing

### Expected result  
Grid should re-instantiate with the new column value

### Attachments  
https://stackblitz.com/edit/igx-grid-ngfor-columns-wxqlmf

**Comment by rkaraivanov** [comment]
@ammritt 
This is already fixed in 6.1.8. I would suggest to update to the latest 6.1.x package.
https://stackblitz.com/edit/igx-grid-ngfor-columns-xg2ddk

**Comment by SlavUI** [comment]
@ammritt closing this on reopen if you are still experiencing issues after updating to the 6.1.8 or higher :)
