### ISSUE TITLE
Error while targeting es2017

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/igniteui-angular#3011]
### Description  
Created a brand new Angular project and changed the `target` in the `tsconfig.json` file to `es2017`.  After attempting to add an `igx-input-group` the following error is displayed in the chrome developer console:
![image](https://user-images.githubusercontent.com/18489991/48441831-8046da00-e75a-11e8-931d-fe364a1e08af.png)

Changing the `target` back to the default `es5` value causes everything to work as expected.

 * igniteui-angular version: 6.2.0
 * browser: Chrome 70.0.3538.77

### Steps to reproduce  

1. Extract attached sample
2. Run `npm install`
3. Run `npm start`
4. Open site in browser and look at dev tools console.

### Result  
What is the actual result after following the steps to reproduce?

IgxCalendarDateDirective is not defined error is shown

### Expected result  
What is the expected result after following the steps to reproduce?

No error is shown and the Input component is rendered.

### Attachments  
[input-sample-seven.zip](https://github.com/IgniteUI/igniteui-angular/files/2578022/input-sample-seven.zip)

**Comment by ig-robstoffers** [comment]
Just a note, I only tested this against the Input Group component but not all the other components so it's possible the other components may have similar issues as this one.

**Comment by grosch** [comment]
Definitely looking forward to this one being fixed!

**Comment by QuinntyneBrown** [comment]
This is also happening when targeting es2015

**Comment by kdinev** [comment]
@ig-robstoffers @grosch @QuinntyneBrown We made the fix available in `6.2.1` and in `7.0.0`.
