### ISSUE TITLE
Minor grid filtering tweaks

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3014]
### Description  
A couple of minor issues with the new filtering:

1. When entering filtering mode, you can jump to the different column filters by clicking the column header. Since this is possible, shouldn't they use the hand cursor, indicating they are clickable?
2. In the Custom Filtering Operands sample, the functionality of the boolean custom operand is a bit confusing. The Discontinued column does not accept text input (disabled text field), and you have to click the button, and choose All, true or false. This is great, but there is is a text field there, which says: "Add filter value", and it also has the hand cursor. It looks like this is a button (Because the text Add filter value indicates an action). But when clicking it, it instead highlights the input field (which is disabled). I think clicking anywhere in the input, when not accepting text, should open the dropdown
![image](https://user-images.githubusercontent.com/12936286/48473210-52b06e00-e7f8-11e8-99ff-93ac1784b59b.png)

 * igniteui-angular version: 6.2.0

### Steps to reproduce  

1. Go to the Custom Filtering Operands sample on https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by DaniMarinov** [comment]
Find below my replies:
1. The cursor shouldn't change, but still we can think about another indication that this header column is clickable.
2. We'll review it asap. 

Thank you.

**Comment by sstoyanovIG** [comment]
First question is covered by #2004 and second one by #3086, #3092, #3093
