### ISSUE TITLE
Unnecessary horizontal scrollbar in the dropdown

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-angular#3015]
1) Open filtering sample:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html

2) Open filtering edit mode for `Discontinued` column.

3) Click on the filtering condition icon to open the dropdown.

There is an unnecessary horizontal scrollbar:

![default](https://user-images.githubusercontent.com/2705882/48475661-f05e6a00-e805-11e8-9883-dc9ff0bedc5d.png)

**Comment by SlavUI** [comment]
No longer reproducible 
![image](https://user-images.githubusercontent.com/33216749/53944593-64c85c00-40c8-11e9-8d03-0c6ed866d7b1.png)
