### ISSUE TITLE
igx-grid - on IE11, misalignment between column headers and cells happens  when the total width of the columns is shorter than the grid width.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#3027]
### Description  
On IE11, misalignment between column headers and cells happens  when the total width of the columns is shorter than the grid width.

 * igniteui-angular version: 6.2.0
 * browser: IE11

### Steps to reproduce  

1. Run the attached sample on IE11.

### Result  
Misalignment between column headers and cells happens.
Here is screenshots.
- IE11 has a problem.
![ie11](https://user-images.githubusercontent.com/15909409/48531356-510da580-e8df-11e8-8613-f450f97cb7ce.jpg)

- Chrome is OK
![chrome](https://user-images.githubusercontent.com/15909409/48531371-5cf96780-e8df-11e8-8190-c5269887e774.PNG)

### Expected result  
Misalignment between column headers and cells should not happen.

### Attachments  
[igx-grid.zip](https://github.com/IgniteUI/igniteui-angular/files/2583702/igx-grid.zip)

**Comment by tkiryu** [comment]
The behavior of  `igx-grid-header` is OK thanks to `max-width`.
https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-header.component.ts#L73-L75

On the other hand, the behavior of  `igx-grid-cell` is not good. It doesn't have `max-width`, which causes the problem.
https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/cell.component.ts#L381-L382

**Comment by tkiryu** [comment]
I found the root cause. `flex-basis` and `box-sizing` don't work well together on IE11. Please see the following link.
https://stackoverflow.com/questions/37353792/flex-basis-and-box-sizing

**Comment by SAndreeva** [comment]
@tkiryu, we are currently making some refactoring that tends to fix similar issues. Thanks for the deep observations and the help!
