### ISSUE TITLE
igx-combo dynamic data not working

### ISSUE THREAD

**Issue by nikunjgajera** [IgniteUI/igniteui-angular#3031]
I am new in this Ingite UI.

I need to use combo dropdown in my angular html page. so i am using `<igx-combo></igx-combo>` As per google research. Also i found 

> https://stackblitz.com/angular/yonamgeqmka?file=app%2Fcombo%2Fcombo-main%2Fcombo-main.component.html

this working demo, in this demo its using static value not dynamic value.

please see my below code,
register.html
```
<div id="combo_types" class="filter-ele">
            <igx-combo #templateCombo
                       [data]="families" [displayKey]="'type'" [valueKey]="'type'">
            </igx-combo>
          </div>
```

register.ts
```
@Component({
  selector: 'app-register',
  templateUrl: './register.html',
  styleUrls: ['./register.scss']
})

export class RegisterComponent implements OnInit {
   /********** below code is working **************/
    public families = new Array({'type': 'demo'}); 
    constructor() {}
    /**************************************************/

    /*************** below code is not working ************/
    public families:any;
    constructor() {
        this.http.get(apiURL)
           .subscribe((data) => {
           this.families = data;
      });
    }
   /*********************************************************/
}
```

In short, static value assign its working properly, but when i call api and get results and set in scope. its not working properly

so how can i use this dynamically?

**Comment by rkaraivanov** [comment]
Hey @nikunjgajera 

The combo should not really care whether the data is static/dynamic as long as there is a collection to bind to. I've prepared a [sample](https://stackblitz.com/edit/angular-9mrh8z) which demonstrates how to bind to a dynamically populated local array (similar to your sample) and to an observable using `async` pipe.
Also, it will be extremely helpful if you can provide a full sample replicating your issue.
