### ISSUE TITLE
Grid flickers when enter edit mode

### ISSUE THREAD

**Issue by astaev** [IgniteUI/igniteui-angular#3037]
### Description  
Grid flickers when enter edit mode

 * igniteui-angular version: 6.2.x
 * browser: chrome 70.0.3538.102

### Steps to reproduce  

1. Open Dev Demos
2. Open Grid cell editing sample
3. (Optional) Select all rows
4. Go to another opened tab 
5. Open back the demos tab 
6. Double click any cell to enter edit mode
7. Execute the same steps with boolean column

### Result  
Grid flickers. 

### Expected result  
No flicker. 

### Attachments  
Boolean column behavior
![igxgrid](https://user-images.githubusercontent.com/44602698/48707682-e030fb00-ec08-11e8-8c0c-fa5e21057f49.png)

**Comment by rmkrmk** [comment]
Some observations:

1. The gray rectangle height depends on the browser window's height, check the images:
Browser with large height:
![image](https://user-images.githubusercontent.com/11978058/50766077-9f587880-1280-11e9-8b53-5db84e6e3632.png)
Browser with small height:
![image](https://user-images.githubusercontent.com/11978058/50766095-b008ee80-1280-11e9-82c1-c9b5e91baae8.png)

2. After entering edit mode of a cell (and this way making the gray rectangle show up) if you move the mouse pointer to the left over the values of the "OrderDate" and "UnitsInStock" column you will see the mouse pointer changes to text selection pointer although the values are not visible.

3. The gray rectangle is shown when entering edit mode. I tried to put a break point in the "set_cell_inEditMode" method in the "api.service.ts" file and entered edit mode. The break point was hit and during the execution of the above method the grayed rectangle was now shown. The rectangle is shown later when executing code in the angular/zone framework.

**Comment by astaev** [comment]
This is not reproducible with 7.2.x, so closing it.
