### ISSUE TITLE
Igx-grid when json object has an object or an array inside 

### ISSUE THREAD

**Issue by corganfuzz** [IgniteUI/igniteui-angular#3046]
### Description  
Could you put in the documentation what to do when you have an array inside of the data array for igx grid, how do you display that ?

this [link ](https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/119075/if-column-datatype-is-oobject-how-can-i-get-all-the-properties-of-object-inside-grid-template/529174#529174)explains my question, but the answer is poor. in fact it doesnt solve it.

This can easily be implemented with ngfor and tables, but it's hard on igx-grid 

Here is my data, how do you display aval (an array property)  inside igx-grid ?

Actually I would like to display "start" and "ava". that's it. if I do a ngfor or a map I get **[object Object]** on my grid

```javascript
   {
      "EmployeeID": "56250fa57ab1535722e564a6",
      "FirstName": "Downs",
      "LastName": "Holcomb",
      "Country": "Italy",
      "Age": 35,
      "RegistererDate": "07/25/2015",
      "IsActive": false, 
      "aval": [{start: "1", end: "2", ava:"3", health:"4"}]
    },
    {
      "EmployeeID": "56250fa5c0fd04f12555d44d",
      "FirstName": "Mckenzie",
      "LastName": "Calderon",
      "Country": "USA",
      "Age": 26,
      "RegistererDate": "09/22/2014",
      "IsActive": false, 
      "aval": [{start: "5", end: "8", ava:"7", health:"9"}]
    },
```

Thanks

**Comment by mpavlinov** [comment]
You can do it with [formatter](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/igxcolumncomponent.html#formatter) like this:
``` html
    <igx-grid #grid1 [data]="localData">
        <igx-column width="100px" field="aval" [formatter]="formatAval">
        </igx-column>
    </igx-grid>
```
```ts
    formatAval(value) {
        return value[0].start + " " + value[0].ava;
    }
```

Here's a StackBlitz [sample](https://stackblitz.com/edit/angular-6xxpgn)

Or you can do it with cell template:
```html
<igx-column header="aval" headerClasses="myClass" width="100px" field="aval" sortable="true" [filterable]="false">
    <ng-template igxCell let-cell="cell">
        <div class="cell__inner">
            <div *ngFor="let a of cell.value" >{{ a.start }}</div>
        </div>
    </ng-template>
</igx-column>
```
Here's another StackBlitz [sample](https://stackblitz.com/edit/angular-6xxpgn-gvfmfh)

**Comment by corganfuzz** [comment]
Thanks @mpavlinov , Your answer helped me a lot , however because of the [0] I only get the first value, so, Im trying different things now but  I was thinking more like as extra columns like this. putting it more like this:

"EmployeeID" | FirstName | LastName | ... | **start** | **ava**|
56250fa57ab1| Downs........|...Holcomb .......|.....**1**....|......**3**|
56250fa5c0fd.| Mckenzie...|...Calderon .......|.....**5**....|......**7**|

```
<igx-grid #grid1 [data]="localData">
        <igx-column 
                   width="100px" 
                   field="aval" [formatter]="formatAval" 
                   *ngFor="let item of aval.ava">
        </igx-column>
    </igx-grid>
```

I used an *ngfor in jgx-column, but didnt work

**Comment by mpavlinov** [comment]
@corganfuzz Yes. It's complicated to do this scenario in igxGrid. The easiest solution is to transform your data to flat array and then bind it to the igxGrid.

**Comment by corganfuzz** [comment]
@mpavlinov  figured it out myself. 

Per @zdrawku I'm opening an issue at @igniteui-docfx where it should be stated what kind of data structure igx-grid takes, at least when it comes to remote data. does it take an array, an object or an array of objects ?

The solution for me here [StackBlitz ](https://stackblitz.com/edit/angular-6xxpgn-w95mpz) wouldnt been simpler if I knew igx-grid would only take an array of objects when you are trying to generate columns dynamically. 

For example, in this data structure, how you even start ? well 2 things to take in consideration.

```
 "timeline": {
        "timeline_values": [{
          "tag": 0,
          "start": "11-19"
        },
        {
          "tag": 1,
          "start": "11-20"
        },
        {
          "tag": 2,
          "start": "11-21"
        },
        {
          "tag": 3,
          "start": "11-22"
        }
        ]
      },
      "employees": [{
        "EmployeeID": "56250f",
        "FirstName": "Downs",
        "aval": [
          {"start": "11-19","end": "2","ava": "30","health": "4"},
          {"start": "11-20","end": "2","ava": "40","health": "4"},
          {"start": "11-21","end": "2","ava": "50","health": "4"},
          {"start": "11-22","end": "2","ava": "60","health": "4"}
        ]
      },
      {
        "EmployeeID": "46250f",
        "FirstName": "Mckenzie",
        "aval": [
          {"start": "11-19","end": "2","ava": "1","health": "4"},
          {"start": "11-20","end": "2","ava": "2","health": "4"},
          {"start": "11-21","end": "2","ava": "3","health": "4"},
          {"start": "11-22","end": "2","ava": "4","health": "4"}
        ]
      }, {
        "EmployeeID": "56250f",
        "FirstName": "Charles",
        "aval": [
          {"start": "11-19","end": "2","ava": "100","health": "4"},
          {"start": "11-20","end": "2","ava": "200","health": "4"},
          {"start": "11-21","end": "2","ava": "300","health": "4"},
          {"start": "11-22","end": "2","ava": "400","health": "4"}
        ]
      }
      ]
    }
```

As far as I know, both [headers] , [field] in <igx-colum> and [data] in <igx-grid>  need to be in sync. While it is possible to put 2 data sources for both I would not recommend it, as in you will run in a lot of unnecessary headaches if you do(there might be a way but I dont think this is very efficient for the app).

therefore here is the html:

```
<div class="grid__wrapper">
    <igx-grid #grid1 [data]="newLocalData" >
        <igx-column
            *ngFor="let c of columns"
            [sortable]="true"
            [filterable]="true"
            [field]="c.tag"
            [header]="c.tag" 
        >
        </igx-column>
    </igx-grid>
</div> 
```

Now let say you would wanna put icons such as a green check mark or something, you just add an extra <igx-column> to this and you are ready to go. Make sure you use the same [data] thing tho.

Now the fun part, 

```
    this.localData = this.localObject.employees;
    const firstLevel = this.localData;
    const result = firstLevel.reduce((r, { EmployeeID, aval}) => [
      ...r,
      ...aval.map(({ start}) => ({tag: start}))
    ], []);

    // console.log(result);

    const unique = result.map(item => item.tag)
    .filter((value, index, self) => self.indexOf(value) === index);
  //  console.log(unique);

    const json = unique.reduce(value => { 
       return unique.map(value => ({tag: value}))
     }, {});
     this.extraheaders = json

     console.log('json', json)

     const res = firstLevel.map(({ EmployeeID, aval }) => (
      Object.assign(
        { EmployeeID },
        ...aval.map(({ start, ava }) => ({ [start]: ava }))
      )
    ));
   
  //  console.log(res);  
   this.newLocalData = res;


this.columns = [
  { tag: "EmployeeID", width: "100px", type: "number" },
  ...this.extraheaders
]
```

All this code does is to convert that wacky data above into a data structure igx-grid can understand. (btw, I still need to tune this a lil bit, but I just wanted to work)

Like this:
```
[
{ header: value, header2: value1, header3, value2, header4: value3 },
{ header: value, header2: value1, header3, value2, header4: value3 },
{ header: value, header2: value1, header3, value2, header4: value3 },
{ header: value, header2: value1, header3, value2, header4: value3 },
{ header: value, header2: value1, header3, value2, header4: value3 },
...and so on 
]
```

The question is , is this the only data structure igx-grid **takes** , can it take any other ? is there a future plan to make it easier for other users ?. Actually I do not mind to do this transformations, since they are supposed to be at API level anyway but at least I would be nice if this is in the documentation.

**Comment by mpavlinov** [comment]
@corganfuzz We will describe what data structure igx-grid supports in the docs. I cannot find an issue logged by you in @igniteui-docfx repo. Let me know what the issue number is.

**Comment by corganfuzz** [comment]
@mpavlinov sorry , been busy all week. will do this now.

**Comment by corganfuzz** [comment]
@mpavlinov here you go [link](https://github.com/IgniteUI/igniteui-docfx/issues/882)

**Comment by mpavlinov** [comment]
@corganfuzz Thanks!

**Comment by SlavUI** [comment]
@corganfuzz closing this one as there is a relevant issue logged in docfx repo
