### ISSUE TITLE
Grid's right side is cut out when there is no grid width or column width defined

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#3054]
### Description  
Grid's right side is cut out when there is no grid width or column width defined

 * igniteui-angular version: 6.2.x
 * browser: Chrome, Edge, Firefox

### Steps to reproduce  

1. Go to dev demos Grid Column Groups
2.  Add to the grid:
```[showToolbar]="true" [columnHiding]="true" [columnPinning]="true"```
3. Change displayDensity to comfortable
```displayDensity="comfortable"```
4. Run the demos.
5. Open the column **pinning toolbar,** open the last **filter chip**.
---
6. If you resize the browser and then maximize it again, the issue is fixed and the right side is visible again. 

### Result  
5. Both pop-ups are cut out from the right side. The grid is cut out from the right side. The Column Pinning dropdown scrollbar is not visible.

### Expected result  
5. Both pop-ups should not be cut out from the right side. The grid should not be cut out from the right side. The Column Pinning dropdown scrollbar should be visible.

![test](https://user-images.githubusercontent.com/11095014/48771281-a70c8f80-ecc9-11e8-835c-166100164ed5.gif)

Note: If displayDensity is set to "compact", the pinning toolbar is cut out even more, not displaying the inputs whole text:

![pinned](https://user-images.githubusercontent.com/11095014/48771454-21d5aa80-ecca-11e8-9d18-e14c4381dad8.png)

**Comment by hanastasov** [comment]
This is a known limitation in grid sizing, when there is an animation on the page ( like the navbar pushing the grid to the side). Soon there will be topic explaining the issues and expected behaviors with the grid sizing. Closing as not to fix.
