### ISSUE TITLE
IgxGridHeaderGroupComponent should have preset min width

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#3071]
### Description  
IgxGridHeaderGroupComponent should have preset min width

 * igniteui-angular version: 6.2.x
 * browser:  N/A

### Steps to reproduce  

1.  Switch to  **SAndreeva/header-group-component-6.2.x**
2.  Run **Grid Column Moving** demo
3.  Inspect the the 'ID' column header group

### Result  
**IgxGridHeaderGroupComponent** is sized to 40px as this is the width set on the column. **IgxGridHeaderComponent** and **IgxGridFilteringCellComponent** are 48px as they have paddings.
Therefore cells and headers looked misaligned, the resize handler on the header is not shown at the expected place.

### Expected result  
The  **IgxGridHeaderGroupComponent** should not be able to go below a certain min width.

**Comment by simeonoff** [comment]
@SAndreeva This is not something that can be fixed by setting css properties on the item class as the min-width value is set via HostBinding.
