### ISSUE TITLE
Group column header is not styled correctly when moving that column

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#3072]
### Description  
Group column header is not styled correctly when moving that column

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Switch to **SAndreeva/header-group-component-6.2.x**
2. Run **Grid Column Groups** demo
3. Start dragging the 'General Information' column group.
4. Observe the style applied on the header group.

### Result  
Not all of the titles receive the same background color, etc.

### Expected result  
All of the titles receive the same background color, etc.

**Comment by simeonoff** [comment]
@SAndreeva Can you elaborate a bit more?
