### ISSUE TITLE
Scrolling igxGrid on iPad Poor Performance

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#3083]
### Description  

Scrolling performance on iPad very poor.  Open 
https://www.infragistics.com/angular-demos/finjs-sample on iPad, attempt to scroll.

 * igniteui-angular version: 6.2.0.
 * browser:  Chrome, Safari, Edge on iPad.

### Steps to reproduce  
1. run 
https://www.infragistics.com/angular-demos/finjs-sample on iPad.

### Result  
What is the actual result after following the steps to reproduce?

Expect smooth scrolling.  On Chrome on iPad, it is very poor.  On Safari on iPad, it appears to do well, but becomes choppy and chunky and doesn’t scroll well after several good scrolls.

### Expected result  
What is the expected result after following the steps to reproduce?

Buttery smooth, just like Desktop.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by mpavlinov** [comment]
@jberes What generation is this iPad?

**Comment by ChronosSF** [comment]
@SlavUI

**Comment by SlavUI** [comment]
@ChronosSF  the change in behavior is big we should implement this it may add code to the Virtualization but the improvement is worth it :)

**Comment by kdinev** [comment]
It's a noticable improvement. If it's not risky, then I think it should be implemented.
