### ISSUE TITLE
Cells position is changed when scroll vertical

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#3094]
### Description  
Cells position is changed when scroll vertical

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Group by column City
3. Collapse all groups 
4.  Scroll to group Lielle and expand it
5. Scroll vertical
6. Scroll horizontal to half of column ContactName to be previewed
7. Start scroll vertical

### Result  
Cells content is changed

### Expected result  
Cells content should be correct after scroll

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/48850052-60de2b80-edb0-11e8-84c6-b2c362ffde31.png)

**Comment by hanastasov** [comment]
Please make sure the fix also resolves #3350.
