### ISSUE TITLE
Support for igTreeGrid

### ISSUE THREAD

**Issue by nvdnkpr** [IgniteUI/igniteui-angular#31]
Will there be any directive for a igTreeGrid ?

**Comment by mpavlinov** [comment]
The Ignite UI directives are dynamically generated, which means that there is an igTreeGrid directive available. You can check the following [sample] (https://github.com/IgniteUI/igniteui-angular/blob/master/samples/igTreeGrid.html).
The two-way data binding is manually written and is not available yet.
