### ISSUE TITLE
Need a month picker (feature request)

### ISSUE THREAD

**Issue by grosch** [IgniteUI/igniteui-angular#3126]
### Description  
Would be very useful if the calendar component let us pick a month instead just a specific day in the month.  For example, this order counts against December.  I don't care about a specific date in December, I just care about the month.  

It would be fine if you just picked the 1st as far as the Date() object, but for the UI the person still just sees a month.

 * igniteui-angular version: 6.2.0
 * browser: Any

**Comment by kdinev** [comment]
@grosch There's already a UI for that in the `IgxCalendar`. What we can do is extract it as a separate component and expose it.

**Comment by StefanIvanov** [comment]
IMO it is not necessary to extract it in a component, but @grosch is asking how to change the month in the date picker, which is possible upon clicking the month name in the area just above the weekdays.

**Comment by kdinev** [comment]
@StefanIvanov The UI is there, but currently you cannot have that at the only calendar UI, which you go directly to, and can react to user choice.

**Comment by kdinev** [comment]
@StefanIvanov This would be similar concept to the time picker component. With a time picker, you only expose a specific portion of a date object to be editable by an end user, namely the time portion. A month picker would only be for the month portion of a date.

**Comment by grosch** [comment]
@StefanIvanov The idea is that, for example, you've got an order/billing system, and you have to identy what month the order goes against, and so you're picking a year and a month, but you don't care about the day.  Just have a list of month dropdowns isn't good because then you have to have a second input to type in a year.

**Comment by grosch** [comment]
@kdinev Put a year picker at the top of that image you posted and that's exactly what I'm looking for!

**Comment by kdinev** [comment]
@grosch Like this?
![image](https://user-images.githubusercontent.com/1472513/49170116-1c203a80-f344-11e8-8ef9-736b361d7354.png)

**Comment by grosch** [comment]
@kdinev No, something more like this, from ng2-date-picker:

![image](https://user-images.githubusercontent.com/315966/49207910-26a1fa80-f36b-11e8-92fe-77dc290e962b.png)

**Comment by kdinev** [comment]
My screenshots are from this demo: https://stackblitz.com/angular/eymadmbgxko

Click on the month name or year name and you get the views. My understanding is you just don't need the days view from the whole thing.

**Comment by grosch** [comment]
I suppose it could work like that.  If it defaulted to just the month view, and I could click the year to get the scroller, and then going back would be the month view, that could work.

**Comment by kdinev** [comment]
@grosch We will prioritize this for one of our upcoming sprint and we will keep you posted on the progress. I think it would be rather easy to separate those views from the calendar into a separate component.

**Comment by grosch** [comment]
Any ETA on a delivery date?

**Comment by kdinev** [comment]
@grosch We will assign this to a sprint and will try to get it for `7.1.3` which will be in a week or so. We wouldn't be able to get it in `7.1.2` because that's planned for tomorrow.

**Comment by StefanIvanov** [comment]
I am working on some initial designs and a draft of a [specification](https://github.com/IgniteUI/igniteui-angular/wiki/Month-Picker-Specification), where they will be placed.

**Comment by grosch** [comment]
Any update?

**Comment by kdinev** [comment]
@grosch This is in development already. It will be released with 7.2.0.

**Comment by SAndreeva** [comment]
Adding some initial draft of the [calendar views specification](https://github.com/IgniteUI/igniteui-angular/wiki/Calendar-Views-Specification) to serve as a base for the month picker implementation.

**Comment by grosch** [comment]
I still think you're missing the most common case:

As a developer I want to be able to instantiate a year and month picker, as a single control, without having to have a year selector and then another control as a month selector.

**Comment by StefanIvanov** [comment]
@grosch refer to the [specification](https://github.com/IgniteUI/igniteui-angular/wiki/Month-Picker-Specification) shared by me a few comments back for your request, these further specs provide the scope of a parallel effort to make each calendar view sort of a standalone to give us the flexibility support further scenarios, similar to the one you mentioned.

**Comment by bkulov** [comment]
The development part is done and the PR is merged. We will be working on samples and docs in the following weeks.
