### ISSUE TITLE
Filter UI does not display input's placeholder text in IE11

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#3128]
### Description  
Filter UI does not display input's placeholder text in IE11

 * igniteui-angular version: 6.2.x
 * browser: IE11

### Steps to reproduce  

1. Open dev Demos Column Moving in IE11
2. Click on "Region" column filter chip.

### Result  
There is no text displayed.

### Expected result  
There should be a input text "Add filter value".

Note: If you click on a operator to make a filter selection the text appears.

### Attachments  
![image](https://user-images.githubusercontent.com/11095014/48934495-ec6ccf00-ef0c-11e8-9108-5c3b9f14b2be.png)

**Comment by simeonoff** [comment]
@npaunov This is the default behavior in IE. Since behind the scenes we still use the native input element, this is expected.
