### ISSUE TITLE
Pager - new component

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-angular#314]
### Description  
Implement a paging component consisting of:

- first page
- previous page
- current page dropdown with page selection
- next page
- last page

UX to be researched

**Comment by kdinev** [comment]
@rkaraivanov Don't we currently have a pager as part of the grid paging implementation?

**Comment by rkaraivanov** [comment]
We do, but I think the issue is for a general pager component/directive.

**Comment by zdrawku** [comment]
Currently we have pagination template which is used for the paging feature of the gird, and based on the [Roadmap ](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md) we do not plan to change this to a component, at least not before April 16th, 2018, if we do we are going to consider this issue.
