### ISSUE TITLE
Feature Request: igxSelect Component

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#3148]
### Description  
Create a simplified version of the IgxCombo a.k.a “Single Select” component that comes without the multi-selection checkboxes.

* This is to be considered as clients feature request.
For reference: https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/119230/how-do-i-mimic-a-select-element

**Comment by kdinev** [comment]
@IvayloG @grosch The component, that is supposed to handle the HTML select-like behavior, is the `igx-dropdown`. The team is adding a sample, which covers the `igx-dropdown` being bound to an input, with placeholder, title and label. I will update with a link to the sample to verify if the sample is satisfactory for the requirements described in the forum thread linked above.

**Comment by grosch** [comment]
@kdinev That would be wonderful.  How are you coming with that sample?

**Comment by grosch** [comment]
@kdinev Thanks for that.  I'm seeing an issue though that it only works as long as your list of items is less than the height of the screen.  How can I tell it to only show X number of items and then scroll if there are more?

**Comment by bazal4o** [comment]
The initial spec is available here: [igxSelect Specification](https://github.com/IgniteUI/igniteui-angular/wiki/IgxSelect-Specification).

**Comment by grosch** [comment]
Is there an ETA for release of this to production?

**Comment by bazal4o** [comment]
It will be included into the next major release (7.2.0). The release should be out the door at the end of February. Expect beta packages available by the end of the next week.
