### ISSUE TITLE
igx-grid with multi layer header

### ISSUE THREAD

**Issue by nikunjgajera** [IgniteUI/igniteui-angular#3169]
My requirements is create table using grid layout and Display two layers header same as below link

> https://github.com/IgniteUI/igniteui-angular/issues/488

But I reaseach on this but i am not able to find source code in `Angular`

I also found same functionality but that code is in jQuery

> https://www.igniteui.com/help/iggrid-multicolumnheaders-multicolumnheaders

but not able to find code in `Angular`

Also I made table dynamically using below link

> https://stackblitz.com/edit/igx-grid-ngfor-columns

Now I want to add two layer header in this grid by dynamically

can you please provide any source for this requirement?

**Comment by kdinev** [comment]
@nikunjgajera You're looking at the Ignite UI for JavaScript examples. The Ignite UI for Angular samples are located here:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_multi_column_headers.html

**Comment by kdinev** [comment]
Closing the issue.
