### ISSUE TITLE
IgxCalendar  throws an error on date selection after Deselection on a single Date through the API.

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular#3172]
### Description  
When you deselect a single Date through the igxCalendar API and after that select  a new Date an Error is thrown.

### Steps to reproduce  

Step 1:
Create a method that uses IgxCalendar [deselectDate](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxcalendarcomponent.html#deselectdate) method and bind it to a button in app template.

Step 2:
Select a Date from the Calendar and after that deselect it through the button that uses the [deselectDate](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxcalendarcomponent.html#deselectdate) method

Step 3:
Select a new Date in the Calendar.

### Result  
An error is thrown.

![calendarerror](https://user-images.githubusercontent.com/25771040/49067559-1ab01e80-f22d-11e8-9553-e2d36061a687.PNG)

### Expected result  
Should select the new Date rather throwing an error.

**Comment by rkaraivanov** [comment]
Closed via #3226
