### ISSUE TITLE
Upgrade to 7.0.0 broke my slider , broke fonts on mac, Initializers are not allowed in ambient contexts on nav drawer

### ISSUE THREAD

**Issue by corganfuzz** [IgniteUI/igniteui-angular#3185]
### Description  
I'm using the normal Angular CLI v7, added ignite-ui as a package, went to ignite-ui 7.0.0 from 6.2.0 and slider no longer sliding (windows). On a mac, the same happens and the fonts were gone, browser displaying  default fonts.

 * igniteui-angular version: 7.0.0
 * browser: Chrome

### Steps to reproduce  

1. Install angular cli v7
2. add iginite-ui as a package
3. install ignite-ui version 6.1.7 or 6.1.2
4. upgrade to 7.0.0 npm uninstall and npm install igniteui-angular

### Result  
What is the actual result after following the steps to reproduce?
slider breaks, doesnt slide and error message on mac for navigation drawer:

**Initializers are not allowed in ambient contexts.**

Initializers error goes away when I upgraded to the latest CLI v7.1

### Expected result  
What is the expected result after following the steps to reproduce?
Not to break. I upgraded 6.1.7 to 6.2.0 rc to 6.2.0 and everything worked fine

### Recomendations
You guys really need a beta categorization for new releases or something. I had to go back to my cloud repo and get another copy of my app. Thank god for Git.

**Comment by kdinev** [comment]
@corganfuzz Did you upgrade using `ng update igniteui-angular`?

**Comment by kdinev** [comment]
@corganfuzz I confirm, we've released a regression in the slider with `7.0.0` that has somehow slipped through testing. We will be delivering a patch that fixes it shortly.

**Comment by corganfuzz** [comment]
I did npm install ingiteui-angular and changed the contents of my package.json to 7.0.0, how are you supposed to upgrade to the newest version of it? ( do we have to do ng update always?). could you please include it somewhere in the documentation ?

**Comment by kdinev** [comment]
The `ng update` ensures that if any breaking changes are introduced from your current package version to the latest one, then a migration would be executed on your project and the necessary code changes would be applied by the migration script, so you wouldn't have to make the changes yourself. With most version updates, there isn't anything that needs to be migrated.

Example: With 6.0.0, the `igx-tab-bar` component selector was deprecated, and we introduced `igx-bottom-nav` selector for the same component. The 6.0.0 migration finds all the places where you're using the `igx-tab-bar` selector and replaces them with `igx-bottom-nav`.

In general, when updating packages in an Angular project, the guidance is to do it through the Angular CLI, as the update command provides these migration schematic hooks.

As for the slider fix, the PRs are being verified at the moment, and as soon as they get merged, I will tag `7.0.1`, which will include the fix. I will also post an update here in the issue.

**Comment by rkaraivanov** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/2538

**Comment by kdinev** [comment]
I guess for #2538 we really need this https://github.com/angular/angular/pull/26362 merged...

**Comment by kdinev** [comment]
I've triggered a build to publish 7.0.1 and it should finish shortly. Once it's done, you can grab `7.0.1`.
