### ISSUE TITLE
ISortingStrategy docs

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3186]
### Description  
After upgrading to 6.2.1, we are now getting a few errors in lines like this:
![image](https://user-images.githubusercontent.com/12936286/49136002-aa66d300-f2e8-11e8-8037-171ae54f534b.png)
 I assume this is related to the move to ISortingStrategy, as mentions in the change log. But the docs still have samples like
![image](https://user-images.githubusercontent.com/12936286/49136060-cff3dc80-f2e8-11e8-8d14-7ad6793ac1e1.png)
Could we please have a sample of proper use of the new way of sorting?

**Comment by kdinev** [comment]
Hi @Eralmidia,

I've applied the changes to the docs and they're expected to be published either later today, or tomorrow.

Meanwhile: https://github.com/IgniteUI/igniteui-docfx/commit/344fee4afb6c7dc63684e6c85211df7b51be39e5
