### ISSUE TITLE
Filtering input gets populated on keyboard action

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#3202]
### Description  
- [ ] - 1. Filtering input gets populated on keyboard action
- [ ] - 2. X clear icon dissappers after activating/deactivating the chip:
![image](https://user-images.githubusercontent.com/14248932/49154323-c1c1b280-f320-11e8-85a2-a81c198d2979.png)

 * igniteui-angular version: 6.2.0, 7.0.0

### Steps to reproduce #1

1. Go to https://stackblitz.com/angular/brljdreeyelm
2. Click the filter button for OpenPrice column
3. Use the arrow down key to open the dropdown with filterin conditions

### Result  
The input is populated with "-1":
![image](https://user-images.githubusercontent.com/14248932/49151754-840d5b80-f319-11e8-8c91-8f91ad520368.png)

### Steps to reproduce #2
1. Open filter for a column and type value in the input
2. Deactivate the chip
3. Activate the cip and the X icon dissappears

**Comment by sstoyanovIG** [comment]
From now on the drop down will be opened with Alt+ Arrow Down, because for numeric columns the down arrow decrements the value.

**Comment by hanastasov** [comment]
It would be good to update the [grid-filtering topic](https://github.com/IgniteUI/igniteui-docfx/blob/master/en/components/grid_filtering.md) with a section covering the keyboard navigation over the filtering ui.
