### ISSUE TITLE
Pager component  - UI research

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-angular#321]
## Description  
Research pager component UI consisting of:

- first page
- previous page
- current page (dropdown with page selection or buttons)
- next page
- last page

**Comment by kdinev** [comment]
@zdrawku @rkaraivanov Don't we already have a pager? Should I close this?

**Comment by kdinev** [comment]
I guess the "UI research" can be closed as well, since we already have a UI that is implemented in the `igx-grid` pagination.
