### ISSUE TITLE
IgxExpansionPanel is missing a README file

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#3217]
### Description  
The `igx-expansion-panel` component is missing a README.md file

 * igniteui-angular version: 6.2.x, 7.x
 * browser: N/A

### Result  
There is not README.md file

### Expected result  
There is a README.md file

**Comment by zdrawku** [comment]
Closing this issue, Readme.md file is going to be updated with all latest changes at once. [Related issue](https://github.com/IgniteUI/igniteui-angular/issues/3173)

**Comment by zdrawku** [comment]
Reopen, readme.md should be added to the folder of IgxExpansionPanel
