### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by Ingreydavid** [IgniteUI/igniteui-angular#3232]
Grid issue using [columnPinning]="true" [columnHiding]="true"

If you are building the columns from an array after the inital load of the screen the columns never show up in the drop downs.

igniteui-angular 6.2.0

**Comment by MayaKirova** [comment]
Please provide some additional information like:

### Steps to reproduce  

1. Step 1
2. Step 2
3. ...

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?


### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by tachojelev** [comment]
@Ingreydavid , It seems that the issue you are referring to is the same as [this one](https://github.com/IgniteUI/igniteui-angular/issues/3085).
Closing this one as a duplicate.
