### ISSUE TITLE
igx-grid - VIEW MORE icon is not displayed correctly in IE11.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#3236]
### Description  
`VIEW MORE` icon is not displayed correctly in IE11.

 * igniteui-angular version: 7.0.1
 * browser: IE11

### Steps to reproduce  

1. Run the attached sample.

### Result  
There are two problems.
1. badge is on the left of filter icon.
2. `column1` doesn't have enough space, but filter chip is still displaced. 
![image](https://user-images.githubusercontent.com/15909409/49265591-163a6e80-f496-11e8-89cd-4c732afd9902.png)

### Expected result  
Only `VIEW MORE` icon should be displayed.

Here is the result of Chrome.
![image](https://user-images.githubusercontent.com/15909409/49265059-120d5180-f494-11e8-90e9-6217b63c7de2.png)

### Attachments  
[igx-grid.zip](https://github.com/IgniteUI/igniteui-angular/files/2631768/igx-grid.zip)

**Comment by SlavUI** [comment]
@tkiryu i have tested and it works the same in both browsers. If the First filter you have applied is with longer text then the Filter icon will be shown as in the second picture you provided. If the text in the first filter is shorter then the chip will be displayed as you are showing in the first picture :)

**Comment by tkiryu** [comment]
@SlavUI , here is a behavioral difference in between IE11 and Chrome. It doesn't seem that IE11's behavior is correct.

## IE11
![ie11](https://user-images.githubusercontent.com/15909409/49275497-d340c100-f4be-11e8-809a-993fdc1297d1.gif)


## Chrome
![chrome](https://user-images.githubusercontent.com/15909409/49275357-704f2a00-f4be-11e8-916a-fabf7cfaee59.gif)

**Comment by SlavUI** [comment]
@tkiryu It is browser related and in the end it does what it is supposed to do :) so I don't think this is a real issue :)
