### ISSUE TITLE
IgxTab color doesn't follow the material design colors.

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#3253]
### Description  
IgxTab color doesn't follow the material design colors.

 * igniteui-angular version: 6.2.0 and 7.0.0
 * browser: Chrome

### Steps to reproduce  

1. Go to [your demo page](https://www.infragistics.com/products/ignite-ui-angular/angular/components/tabs.html) and look the tab background color.

### Result  
The background tab color is always white.
![image](https://user-images.githubusercontent.com/29953012/49332881-cbdeed80-f57a-11e8-8e1f-cb26f1d76df6.png)
Also elevation is wrong.

### Expected result  
The background color should be the `primary` color,

The main reason to use the same color is consistency when using [for example a `banner`](https://github.com/IgniteUI/igniteui-angular/issues/2672), according to material documentation a `banner `component needs to go at the [same elevation](https://material.io/design/components/banners.html#placement) that the application bar, white `tabs `break that behaviour.
![image](https://user-images.githubusercontent.com/29953012/49332892-09dc1180-f57b-11e8-97c3-4fd3a2bc6c60.png)

**Comment by StefanIvanov** [comment]
Hello @luiscla27 and thanks for pointing this out. What you have shown in the image is a behavior we are familiar with and it is a specific usage of the tabs within the navbar, or to be more precise extending the navbar vertically to contain a set of tabs below the usual content.

**Comment by simeonoff** [comment]
@luiscla27 We tend to follow the material design guidelines very closely. In this case, the tabs follow the [material design guidelines for default tabs](https://material.io/design/components/tabs.html#spec). If you examine the spec closely, the default text and active indicator color is the primary color.

I understand the material guidelines can get confusing, especially if you isolate specific themed samples on the component guidelines page. In the 'Dog breeds' sample, they are showing tabs in composition with the app bar(navbar in our framework). We believe that this is an application specific scenario, which can be achieved easily via theming.

I've prepared an [app sample](https://stackblitz.com/edit/angular-cnazxm?file=styles.scss), showcasing how you can achieve the desired result via theming.

**Comment by luiscla27** [comment]
Thank you @StefanIvanov, @simeonoff, the theming approach is enough to fulfill the desired result so it's ok :)


Certainly you should consider adding a feature to directly modify the component theming.

Actually i prefer the white background with primary-color font... (i think it looks better) but some people may think it looks especially wrong when used together with a banner component, see by yourself:

![image](https://user-images.githubusercontent.com/29953012/49384625-06629a80-f6e1-11e8-8cf7-70456eddd76c.png)

And this is how it looks using a primary-color background:

![image](https://user-images.githubusercontent.com/29953012/49384812-75d88a00-f6e1-11e8-9c32-1830d8bef483.png)

**Comment by kdinev** [comment]
Related issue #3269 

@luiscla27 From your first screenshot, if the nav-bar shadow is removed and only the tabs shadow remains, then wouldn't it look better?

**Comment by luiscla27** [comment]
@kdinev yup better :) 
but stills looks weird:
![image](https://user-images.githubusercontent.com/29953012/49388070-dcad7180-f6e8-11e8-923a-173472ab01a9.png)

**Comment by kdinev** [comment]
For your app, using the primary color as tabs background seems like the best choice, since the tabs are placed directly below the nav-bar. So just stick with the theming change and keep the background at the primary color.

I'm working on an app which has tabs inside large cards and they would look weird, if the background is different than the surface color. It would be impossible from a theming perspective to detect if tabs are below a nav-bar, which means to me that having the tabs background be, by default, the surface color is a correct guideline.

**Comment by luiscla27** [comment]
Thank you @kdinev, i'll stick to theme change and keep the background at the primary color,

btw! you don't need to detect if the tabs are below a nav-bar... :D 

**Implementation for this should be similar to this:**
```
<div class="items-wrapper__item items-wrapper__item-small items-wrapper__item--blue">
    <h5 class="sample-title">FIXED TABS</h5>
    <igx-navbar title="Contacts" actionButtonIcon="menu">
        <igx-icon>search</igx-icon>
        <igx-icon>more_vert</igx-icon>
        <igx-tabs tabsType="fixed">
            <igx-tabs-group label="HOME">Home content.</igx-tabs-group>
            <igx-tabs-group label="RECENT CONTACTS">Recent contacts list.</igx-tabs-group>
            <igx-tabs-group label="MORE INFORMATION ABOUT SELECTED CONTACT">More detailed contact information.</igx-tabs-group>
        </igx-tabs>
    </igx-navbar>
</div>
```

As a justification for this maybe it could be that this behavior is already implemented by many other material-libraries depending on the use case  ([vuetify](https://vuetifyjs.com/es-MX/components/tabs), [material-ui](https://material-ui.com/demos/tabs/#tabs), [reac-toolbox](http://react-toolbox.io/#/components/tabs)).

**Comment by kdinev** [comment]
@luiscla27 We can actually add this as an enhancement to the existing project template, or a new project template in the `igniteui-cli`, so you can get it out of the box when running `ig new`.
