### ISSUE TITLE
Navbar title color became black

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#3259]
### Description  
Navbar title color became black. It was white when on the version 6.2.0

 * igniteui-angular version: 7.0.2
 * browser: Chrome

### Steps to reproduce  

1. Just use the igx-navbar in your component without modifying any theme.
```
<igx-navbar
    [title]="'title'"
    actionButtonIcon="menu"
    (onAction)="onClickMenu()">
</igx-navbar>
```

### Result  
Fore color gets black, which is not contrasty.

### Expected result  
White fore color.

### Attachments  
Please see the attached 
![navbar-title-color](https://user-images.githubusercontent.com/7350918/49363811-01740a00-f726-11e8-9be9-8577c32e7754.PNG)
image.

**Comment by SlavUI** [comment]
@gdayori  Hi this is the correct contrast color according to the accessibility standards. So this is by design

**Comment by kdinev** [comment]
@SlavUI Please post the contrast coefficients for `white` and `black` for reference.

**Comment by simeonoff** [comment]
@gdayori there was a bug in the navbar theme resulting in the navbar text color always being white. We have fixed the bug, hence why the resulting text color is now black. 

In this case black, according to the accessibility standards, has a contrast ratio of 7:1 against the blue background color (#09f). White, on the other hand, has a contrast ratio of 3:1, which doesn't even satisfy the AA [accessibility standard](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html).
