### ISSUE TITLE
Pivot Grid

### ISSUE THREAD

**Issue by mflerin** [IgniteUI/igniteui-angular#33]
Hi,

Are there any plans to create an IgPivot?

It seems to be the only one missing.

**Comment by mpavlinov** [comment]
The igPivotGrid already has a directive, but there were no samples for it. I added 2 samples to demonstrate its usage. You can check [igPivotGrid with Flat Data Source](http://igniteui.github.io/igniteui-angular/samples/igPivotGrid-FlatDataSource.html) and [igPivotGrid with Xmla Data Source](http://igniteui.github.io/igniteui-angular/samples/igPivotGrid-XmlaDataSource.html).
Please note that in the scope you still need to create an instance of the [$.ig.OlapFlatDataSource](http://help.infragistics.com/jQuery/2014.2/ig.OlapFlatDataSource) or [$.ig.OlapXmlaDataSource](http://help.infragistics.com/jQuery/2014.2/ig.OlapXmlaDataSource).
