### ISSUE TITLE
Expose *Change events for state inputs so that users can two-way bind their models

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#3323]
### Description  
Most of the state inputs (e.g. pinned, hidden, etc. for columns, width/height for most components and others) do not have a *Change output and cannot be two-way bound for when that state change needs to be propagated back to the user's app.

 * igniteui-angular version: all
 * browser: n/a

### Steps to reproduce  

1. Open a sample from the demos app and take some sample that sets certain state props e.g.:
```html
<igx-grid #grid1 [data]="data" [width]="'1200px'" [height]="'800px'" [rowSelectable]="true">
        <igx-column *ngFor="let c of columns" [sortable]="true" [field]="c.field" [header]="c.field" [width]="c.width" [pinned]='c.pinned'
                [hidden]='c.hidden'>
        </igx-column>
</igx-grid>
```

2. Check the model after a prop such as hidden or pinned is changed.

### Result  
As expected the prop is not updated. While it is possible to update it yourself by binding to certain events, the disconnect between the model objects and the component instances will make it harder than it has to be.

### Expected result  
Subscribing to changes in the props should be as simple as using the banana in a box syntax.

```html
<igx-column *ngFor="let c of columns"[field]="c.field" [(width)]="c.width" [(pinned)]='c.pinned'
                [(hidden)]='c.hidden'>
```

### Attachments  
n/a

Assigning to @SlavUI  for distribution. Discussed with @kdinev and based on a user question from the forums.

_**Note:**_ We should first identify which properties should allow such two-way binding. The change is by no way limited to `pinned`, `hidden`, `width` and `height` .

**Comment by MayaKirova** [comment]
@ChronosSF @mpavlinov @kdinev IMO this should affect only Inputs that are state related, whose value the component can change as a result of a user interaction or API calls.

For example, for the igxGrid, Inputs whose value is not mutated by the Component like width, height, autoGenerate, rowSelectable, allowFiltering etc. SHOULD NOT have *Change output. Since those values are never internally changed by the component so there would be no need for two-way binding for them.
Other Inputs that get changed via the UI or API of the igxGrid component, like filteringExpressionsTree, page, perPage, sortingExpressions etc. SHOULD  have *Change output so that the related bound models can be updated in case a user interaction or API call changes the value inside the component.

Let me know what you think.

**Comment by MayaKirova** [comment]
Below is the full list of components and directives. The ones that have such options have the options listed with the action/api that triggers the change from within the component.

### Components Change events

- igxAvatar - None

- igxBadge - None

- igxBanner - None

- igxButtonGroup - None

- igxCalendar - None

- igxCard - None

- igxCarousel

- igxSlide

    Property | Changed |
    ---|---|
    active | When the active slide changes.

- igxCheckbox - None

- igxChip

    Property | Changed |
    ---|---|
    selected | When chip is selected.

- igxLinear/CircularBar - None

- igxCombo - none

- igxDatePicker - None

- igxDialog - None

- igxDropDown - None

- igxDropDown Item

    Property | Changed |
    ---|---|
    selected | When Selection in igxDropDown/igxCombo UI or via API.

- IgxExpansionPanel

    Property | Changed |
    ---|---|
    collapsed | When expanding/collapsing via the UI/API.

- igxIcon - None

- igxInputGroup - None

- igxList - None

- igxNavBar - None

- igxNavigationDrawer

    Property | Changed |
    ---|---|
    isOpen| When Opening/closing via the API.

- igxRadio - None

- igxSelect - None
- IgxSelectItemComponent

    Property | Changed |
    ---|---|
    selected | Selection changes via UI/APi (inherited from igxDropDownBase)

- igxSlider - None

- igxSnackbar - None

- igxSwitch - None

- igxTabbar - None

- igxTabPanel

    Property | Changed |
    ---|---|
    selectedIndex| When Selection changes via UI/APi.

- igxTimePicker - None

- igxToast

    Property | Changed |
    ---|---|
    isVisible | Via show/hide API.

- igxColumn

    Property | Changed |
    ---|---|
    pinned|Pinning Toolbar and API|
    hidden|Hiding Toolbar and API|
    width| Resisizng UI and API|

- igxGridBase

    Property | Changed |
    ---|---|
    filteringExpressionsTree| Filtering UI and API|
    page| Paging UI
    perPage | Paging UI
    sortingExpressions| Sorting UI and API

- igxGrid

    Property | Changed|
    ---|---|
    groupingExpressions| Grouping UI and API
    groupingExpansionState| Groups expand/collapse UI and API.

- igxTreeGrid

    Property | Changed|
    ---|---|
    expansionStates| Parent rows expand/collapse UI and API.

- igxHierarchicalGrid

    Property | Changed|
    ---|---|
    hierarchicalState| Parent rows expand/collapse UI and API. 

### Directives

- igxAutocomplete - None
- igxButton - None
- igxDrag - None
- igxFilter - None
- igxForOf - None
- igxHint - None
- igxInput - None (uses ngModel for value)
- igxLabel - None
- igxLayout - None
- igxMask - None (uses ngModel for value)
- igxRadioGroup - None (uses ngModel for value)
- igxRipple - None
- IgxTextHighlight - None
- igxToggle - None
- igxTooltip - None
