### ISSUE TITLE
Collapsible column groups feature

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#3343]
### Description  
Implement collapsible column group feature.

[Example](https://www.infragistics.com/community/blogs/b/igniteui_team/posts/iggrid-collapsible-column-groups-feature), igGrid feature.

**Comment by kdinev** [comment]
@zdrawku By the forum thread, my understanding is that the request is for the `igxHeader` to be exposed for column groups, as well as for regular columns, in order for custom elements and interactions to be templated inside.
