### ISSUE TITLE
When scroll combo active item is changed

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#3361]
### Description  
Describe the issue.

 * igniteui-angular version: 7.0.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample combo
2. Expand combo for location
3. Start scrolling down

### Result  
Combo active item is changed to the first visible item

### Expected result  
Activ item shoul not be changed

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
@ViktorSlavov is resolving this with #4315. Note that this will be released following 7.2.x, because drop down with igxForOf is a new feature.
