### ISSUE TITLE
Active summary cell's border disappears on scrolling.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#3373]
### Description  
Active summary cell's blue border disappears on scrolling.

 * igniteui-angular version: 7.1.x
 * browser: Chrome & Edge

### Steps to reproduce  

1. Start Dev demos (in Chrome or Edge)
2. Navigate to Grid GroupBy demo
3. Group by "Country"
4. Show summaries for root and child levels
5. Click on a summary cell, press the right arrow key - an active border is shown
6. Scroll down (via mouse wheel or scroll button)

### Result  
The active border (blue in Chrome, white dashed in Edge) disappears.

### Expected result  
We should either not have this border initially (as it is in IE and Firefox) or persist it after scrolling.

### Attachments  
![image](https://user-images.githubusercontent.com/16817847/49731062-cd976800-fc82-11e8-8090-d7b0bd18b6e4.png)

**Comment by ddincheva** [comment]
This behavior is intended ... on scroll/ wheel we blur the active element if is inside the grid's body. That's behavior is necessary because of the specifics related with grid's virtualization.
