### ISSUE TITLE
Grid cannot be navigated down with keyboard after hiding the Summaries in a variable row height grid

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#3376]
### Description  
If the row heights set by the grid is different than the rendered height of the rows hiding the summaries (through hiding the only column that has them enabled) causes keyboard navigation to no longer be able to scroll the grid

 * igniteui-angular version: 6.2.x
 * browser: n/a

### Steps to reproduce  

1. Open the Grid Summary sample in the repo
2. Hide the UnitsInStock column with the last button on the button row
3. Click on a cell and try to navigate down

### Result  
Navigation stops before it can scroll the grid down

### Expected result  
Users should be able to use keyboard navigation to navigate down through the rows

### Attachments  
n/a

**Comment by ChronosSF** [comment]
FYI - @rkaraivanov

**Comment by MayaKirova** [comment]
Note: This cannot be reproduced in 7.2.x and later.
