### ISSUE TITLE
Bottom navigation missing from the github home

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#3400]
### Description  
The bottom navigation is missing from the github homepage components and directives listing

### Steps to reproduce  

1. Go [here](https://github.com/IgniteUI/igniteui-angular)
2. Scroll to the "Current list of controls include:" section

### Result  
There is no entry for the igxBottomNav

**Comment by StefanIvanov** [comment]
My bad, there was tabbar, which was the old name for the bottomnav, nevertheless we should update the name.

**Comment by SlavUI** [comment]
@StefanIvanov  updated ;)
