### ISSUE TITLE
Row selectors header is not updated when commit transactions

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#3424]
### Description  
Describe the issue.

 * igniteui-angular version: 7.1.x
 * browser: N/A

### Steps to reproduce  

1. Edit dev sample gridRowEdit and set rowSelectable="true"
2. Delete first row
3. Select deleted row
4. Row selectors header is changed
5. Commit transactions

### Result  
Row selectors header is not updated

### Expected result  
Row selectors header should be updated

### Attachments  
 ![image](https://user-images.githubusercontent.com/11463104/49875962-fbb7ac00-fe2a-11e8-9872-215b4e866af3.png)

**Comment by bazal4o** [comment]
The fix is mered, so I'm closing the issue
