### ISSUE TITLE
Ignite Angular Grid Footer Row

### ISSUE THREAD

**Issue by nikunjgajera** [IgniteUI/igniteui-angular#3450]
I am new in this Ignite UI (Angular)

I created one dynamic grid and its created successfully but now i have below requirement
**In grid i need to display total amount in last row(footer row) and this row should be stick on footer. Also this footer row should not be sort while column short**

so is there any example for like this my requirements?

**Comment by SlavUI** [comment]
@nikunjgajera Hi do you mean something like summaries, if so you can check how to add summaries in the grid here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_summaries.html

**Comment by SlavUI** [comment]
@nikunjgajera hi I'm closing this one let us know if you have additional questions
