### ISSUE TITLE
Angular Material autocomplete does not close its dropdown upon blur on igxDialog

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#3478]
### Description  
Angular Material autocomplete does not close its dropdown list upon blur timing on IgxDialog. I am not sure if the mixture of Ignite UI for Angular component (IgxDialog) and Angular Material component (autocomplete) is expected to work as same as stand alone usage of Angular Material component(autocomplete). Should this be supported by Ignite UI for Angular? Details are below.

 * igniteui-angular version: 7.0.4
 * browser: Chrome 71.0.3578.98

### Steps to reproduce  
1. Run the attached sample
2. Click the button to open dialog
3. Click 'Category 2' input to open its dropdown list
4. Click 'Category 1' input to open its dropdown list

### Result  
Dropdown list opened on step 3 remains open.

### Expected result  
Dropdown list opened on step 3 closes.

### Attachments
[drop-down-sample.zip](https://github.com/IgniteUI/igniteui-angular/files/2693774/drop-down-sample.zip)

**Comment by SlavUI** [comment]
@ymita we are going to develop an autocomplete after new year in the next Milestone.

**Comment by ymita** [comment]
@SlavUI 
Thanks for the information. I see it on the road map. So the combination of igxDialog and Angular Material autocomplete is not (and will not be) supported. Is this understanding correct?

**Comment by SlavUI** [comment]
@ymita for now we do not plan such implementation :)
