### ISSUE TITLE
Feature request: dialog max width

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3481]
### Description  

It would be nice to be able to limit the width of the dialog, as some dialogs simply doesn't need to span the whole page width

![image](https://user-images.githubusercontent.com/12936286/50213308-8ba2ac00-037d-11e9-8d71-843b1653fe30.png)

### Result  
Dialog always spans the page width

### Expected result  
Max width input to limit width

**Comment by kdinev** [comment]
The dialog dimensions are controlled by the wrapper container of the `ng-content` you put inside. So just wrap the content in a div and apply min and max dimensions to that container.
