### ISSUE TITLE
Unable to put href in igx-column header

### ISSUE THREAD

**Issue by grosch** [IgniteUI/igniteui-angular#3489]
### Description  
I've created some HTML for the header of an igx-column,  but any &lt;a> tags are not appearing.

 * igniteui-angular version: 7.1.0
 * browser: Chrome

### Steps to reproduce  

```html
<igx-tree-grid>
  <igx-column-group header="...">
    <igx-column>
      <ng-template igxHeader class="pphwHeader">
        <a href="..." target="_blank" rel="noopener noreferrer">...</a><br/>
        <span class="subhead">&lt;= 7 days</span>
      </ng-template>
```

### Result  
The span text shows up.  Neither the link nor the link text appears.

### Expected result  
Should show two lines.

**Comment by tiliev** [comment]
@grosch, you are right, the `<a>` in your sample is rendered but does not appear because it is on the second line. Currently the grid column headers can render only one line of text. The height of the headers is not adjustable because of the virtualization. 
I am marking this as a feature request.

**Comment by hanastasov** [comment]
@grosch, there is a way to force the header show everything. In the current example I diminished the height:
:host ::ng-deep {
  igx-grid-header[id$='Country'] > .igx-grid__th-title {
      height: 50px;
      line-height: normal;
  }
}

See the sample here: https://stackblitz.com/edit/angular-y51wxx-xw4wan
