### ISSUE TITLE
incorrectly applied height style on grouparea wrapper

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#3500]
### Description  
incorrectly applied height style on grouparea wrapper

 * igniteui-angular version: 7.1.1
 * browser: IE

### Steps to reproduce  

1. Run igniteui-angular-samples
2. Run grid-finjs-demo
3. Observe grouped area

![image](https://user-images.githubusercontent.com/7037740/50344348-4b852a00-0533-11e9-8673-d6aa80fd4031.png)

### Result  
The area is too big

### Expected result  
The area should as big as the chips inside.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by nrobakova** [comment]
This issue is already fixed
