### ISSUE TITLE
Grid Filter design change

### ISSUE THREAD

**Issue by nikunjgajera** [IgniteUI/igniteui-angular#3538]
I am using Ignite UI `"igniteui-angular": "6.1.1"` at that time grid filter design is like below
![selection_016](https://user-images.githubusercontent.com/12508078/50815433-1eae8080-1343-11e9-925f-ddee7df201f5.png)

But when i updated Ignite UI version `"igniteui-angular": "6.2.x"` then design is changed
![selection_015](https://user-images.githubusercontent.com/12508078/50815459-3554d780-1343-11e9-8218-babf6cb5ce67.png)

but i want to use this version `"igniteui-angular": "6.2.x",` with old filter design, so how can this possible?

**Comment by SlavUI** [comment]
@nikunjgajera Hi all version after 6.2.x are using the new design of the filtering you can't go to the old one after this.

**Comment by kdinev** [comment]
@nikunjgajera We're currently working on an excel-style filter UI, in addition to the current filtering row. As soon as the spec is made available in our wiki, I will update the issue with a link, so you can see it. We're planning to make it swappable with the filter row.

**Comment by SlavUI** [comment]
@nikunjgajera here is the spec closing this one you can follow on the Excel Style filtering issues:
https://github.com/IgniteUI/igniteui-angular/wiki/Excel-Style-Filtering
