### ISSUE TITLE
Incorrect focused cell after collapsing rows in the treeGrid in Chrome

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#3556]
### Description  
The focused cell is not correct after collapsing the rows in a treeGrid scrolled to bottom.

 * igniteui-angular version: 7.1.x
 * browser: Chrome

### Steps to reproduce  

1. Open 'Tree Grid Flat Data' dev demo in Chrome.
2. Scroll to the bottom of the grid.
3. Collapse row with ID=20.
4. Collapse row with ID=18.

### Result  
The cell with ID=3 is focused.

### Expected result  
The cell with ID=18 should be focused.

### Attachments  
![image](https://user-images.githubusercontent.com/43128948/50903672-1760a300-1427-11e9-9f8c-afca4182f9c8.png)

**Comment by astaev** [comment]
Cannot reproduce it with 7.2.x. And not-to-fix for 7.1.x
