### ISSUE TITLE
igx-action-icon is not vertically aligned in IgxNavbar

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#3584]
### Description  
igx-action-icon is not vertically aligned in IgxNavbar

 * igniteui-angular version: 7.1.x, 7.2.x
 * browser: any

### Steps to reproduce  

1. Run the navbar dev demo.
2. Put the following action icon in any navbar:
```html
<igx-navbar>
  <igx-action-icon>
    <igx-icon fontSet="material">arrow_back</igx-icon>
  </igx-action-icon>
</igx-navbar>
```

### Result  
igx-action-icon is **not** vertically aligned.

### Expected result  
igx-action-icon is vertically aligned

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/51034759-730a6800-15b0-11e9-80c2-a559095e23a7.png)

**Comment by tachojelev** [comment]
@simeonoff Would you provide your opinion on whether or not we should vertically center the content of the igx-action-icon, or we should leave that to the user?

Currently, the igx-action-icon itself is centered, because its parent (the **div** with **class="igx-navbar__left"...**) has **display:flex** and **align-items:center**. However the content of the igx-action-icon is **not** centered and in order to do so, the developer will probably have to include a couple of more css properties. Do you think we should style the igx-action-icon, so its content is always vertically centered by default, or should we leave that for the developer to do?

**Comment by simeonoff** [comment]
@tachojelev It should be vertically centered by default.
