### ISSUE TITLE
igx-category-chart should have @Input() for legend

### ISSUE THREAD

**Issue by grosch** [IgniteUI/igniteui-angular#3591]
Please let me set the `legend` on the igx-category-chart in HTML.  Right now I have to do this in the typescript, which is kinda silly:

```typescript
    @ViewChild('chart') chart: IgxCategoryChartComponent;
    @ViewChild('legend') legend: IgxLegendComponent;

    ngOnInit(): void {
        this.chart.legend = this.legend;
    }
```

**Comment by gmurray81** [comment]
I believe this is actually already fixed, as I see @Input on legend in the current codebase. So this fix will be available in the next public release.
