### ISSUE TITLE
In some cases, click event is not triggered in igx-overlay

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#3595]
### Description  
When the overlay is not modal, click event is not triggered

 * igniteui-angular version: 7.2.x
 * browser: All

### Steps to reproduce  

1. Pull sboykova/editable-date-picker branch ([pull-request](https://github.com/IgniteUI/igniteui-angular/pull/3583)), run demos and open the date picker page
2. Open the drop-down of the **Editable Date Picker** clicking the calendar image on the left
3. Click 2018 (year link) of the calendar, then click another year to select

### Result  
Click event is not fired and new year is not selected

### Expected result  
Click event to be triggered

**Comment by wnvko** [comment]
This is not related to igxOverlay. If you add click event in dacade view teamplate of igxCalendar like this
```
<div *ngIf="isDecadeView" class="igx-calendar__body" [@animateView]="activeView">
    <div (click)="decadeClick($event)" class="igx-calendar__body-column" (wheel)="onScroll($event)" (pan)="onPan($event)">
        <span (onYearSelection)="changeYear($event)" [igxCalendarYear]="year" *ngFor="let year of decade">
            {{ formattedYear(year) }}
        </span>
    </div>
</div>

```
click event fires
