### ISSUE TITLE
PowerShell script should be added in order to apply some rules for deployment of the API DOCS (sassdoc, typedoc)

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#3618]
### Description  
PowerShell script should be added in order to apply some rules for deployment of the API DOCS (sassdoc, typedoc)

**Comment by Aleksandyr** [comment]
@VMihalkov Can we move that file location here](https://github.com/IgniteUI/igniteui-angular/tree/master/extras)?

**Comment by VMihalkov** [comment]
@Aleksandyr the file has been moved under extras folder
