### ISSUE TITLE
Templated datepicker has inconsistent behavior compared to input group

### ISSUE THREAD

**Issue by ninaarens** [IgniteUI/igniteui-angular#3624]
### Description  
Input field with type text within a datepicker template does not behave consistently with how an input field with type text does inside an input group.

 * igniteui-angular version: 7.1.1
 * browser: Chrome

### Steps to reproduce  

1. Fill in name
2. Pick a date greater than today
3. Pick a date smaller than today
4. Edit the code so the appMinDate directive is on the igx-date-picker instead of the input field

### Result  
1. Filling in just the name marks the form as valid, enabling the submit button
2. Date field is not marked as valid
3. Date field is marked as valid
4. appMinDirective works and marks form as invalid when picked date is smaller than today

### Expected result  
1. Submit button should only enable after both name and date have valid values in them
2. Date field should show valid
3. Date field should not be valid because the directive appMinDate says the minimum date should be Date.Now()
4. Technically correct but would expect it to need to be and work on the input field

### Attachments  
https://stackblitz.com/edit/inputinconsistencies

I also have a forum discussion open at https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/119412/how-to-make-a-date-and-time-picker-required-template-driven-forms but haven't had any more answers there for workarounds, and the ones given are insufficient to solve my case.

**Comment by ninaarens** [comment]
Thank you for your response, that works much more as expected. But not quite there yet. I've included a second sample which also includes feedback from the forum. The remaining inconsistency is that when you pick a date in the past, the field will colour green rather than red. Is there a workaround for this?

https://stackblitz.com/edit/inputinconsistencies2

**Comment by kdinev** [comment]
@ninaarens With the current binding, the custom validator doesn't execute on your input. Change it to:

```html
<igx-date-picker name="datePicker" required [(ngModel)]="date" [appMinDate]="minDate">
  <ng-template igxDatePickerTemplate let-openDialog="openDialog"
               let-value="value" let-displayData="displayData">
    <igx-input-group (click)="openDialog()">
      <igx-prefix>
        <igx-icon>today</igx-icon>
      </igx-prefix>
      <label igxLabel>Date</label>
      <input #dateInput igxInput name="date" [(ngModel)]="displayData" [appMinDate]="minDate" />
    </igx-input-group>
  </ng-template>
</igx-date-picker>
```

**Comment by ninaarens** [comment]
Thank you, that explains it well. However I need the required attribute on the input field, because I want to show the user that the field is required (that is why I use a template here). But when I do that, the field lights up in red straight on page load. And that is not what I want, because this doesn't happen with the name input either.

**Comment by kdinev** [comment]
@ninaarens Closing the issue for now. If there's anything else, please reopen it!
