### ISSUE TITLE
ng-template for dialog buttons

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3632]
### Description  
This is mostly a follow up to #1238, a request to template the buttons for the igx-dialog. This seems to have seen some work in #1264. Is it currently possible to ng-template the buttons to use? I can't see any mention of this in the docs. If it's not, how do we implement fairly common actions like hiding or disabling buttons?

**Comment by Eralmidia** [comment]
Also, enabling templating would allow for more than 2 buttons in custom dialogs, which is sometimes needed

**Comment by kdinev** [comment]
@Eralmidia Just put whatever buttons you need inside the dialog content, and don't use the standard buttons of the dialog.
