### ISSUE TITLE
Need a 'deselect' on the date picker

### ISSUE THREAD

**Issue by grosch** [IgniteUI/igniteui-angular#3638]
On the date picker component, we need a way to deselect the date.  Basically the form has a date picker and it links to the model.  If the end user clicks on the input field the date picker pops up and they choose a date.

Now they realize they don't want a date at all, and they have no way to remove that date.  They click on the date and the picker pops up, but all they can do is pick a different date.

We really need a way to add a Clear button or something like that to the date picker, just like the Today and Cancel buttons that can go there today.

It makes for a messy UI if I have my nice form with a couple date pickers, and then elsewhere I have to add an explicit "Remove due date" button.

**Comment by kdinev** [comment]
@grosch You currently can template a clear button in an `IgxDatePicker`. Here's an example:

```html
<igx-date-picker #picker name="datePicker" [(ngModel)]="date">
  <ng-template igxDatePickerTemplate let-openDialog="openDialog" let-displayData="displayData">
    <igx-input-group>
      <igx-prefix>
        <igx-icon>today</igx-icon>
      </igx-prefix>
      <label igxLabel>Date</label>
      <input (click)="openDialog()" #dateInput igxInput name="date" [(ngModel)]="displayData" />
      <igx-suffix *ngIf="displayData" (click)="picker.value = null">
        <igx-icon>clear</igx-icon>
      </igx-suffix>
    </igx-input-group>
  </ng-template>
</igx-date-picker>
```

**Comment by grosch** [comment]
@kdinev This isn't working very well for me.  How do I make this work with a reactive form?  I tried putting the formControlName on both the igx-date-picker and the input itself.  Neither one worked.

If I click on the clear icon then the date input field is selected and you're able to type anything into that value, which breaks the control then.

**Comment by kdinev** [comment]
@grosch Here's the sample with an `ngModel`: 

https://stackblitz.com/edit/inputinconsistencies2-runpc1?file=src%2Fapp%2Fdatepicker%2Fdatepicker-sample-6%2Fdatepicker-sample-6.component.html 

I'll try to rework it with a reactive form now and I'll post an update!
