### ISSUE TITLE
Filtering on Date type column doesn't work.

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#3640]
### Description  
Filtering on Date type column doesn't work.

 * igniteui-angular version: 7.1.1
 * browser: Chrome

### Steps to reproduce  

1. Open this sample
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html
2. Filter on the OrderDate column by any date.
3. Filtered rows don't appear and you couldn't set any additional date any more.
    Also, you can see errors on Console.

### Result  
Filtering doesn't work on Date type column.

### Expected result  
Filtering should work on Date type column.

### Attachments  
Non

**Comment by kdinev** [comment]
I think you may have encountered some random error on the website, like the chat module not loading correctly, which has broken your interactions. I tried both Edge and Chrome and here's the results:

![image](https://user-images.githubusercontent.com/1472513/51303303-a3815480-1a3d-11e9-85de-a57051e80879.png)

**Comment by bkulov** [comment]
It works properly even in IE11.

**Comment by kdinev** [comment]
Closing this, as it doesn't seem to be a product issue.

**Comment by gdayori** [comment]
@kdinev I confirmed it doesn't occur if the primary language on Chrome is English. To reproduce the issue please change the primary language to Japanese. The error sounds regarding localization.

![image](https://user-images.githubusercontent.com/7350918/51355210-c2ddb780-1af9-11e9-8bde-230f2f7fd06b.png)

**Comment by bkulov** [comment]
I confirm this issue is reproducible on production. It's already fixed and the fix will be released with the following release.
