### ISSUE TITLE
Support multi-row selection using shift + checkboxes click

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-angular#3654]
### Description  
As a use I want to be able to select multiple rows with row selection feature using checkboxes and shift. 

### Steps to reproduce  

1. Click on 1st row checkbox
2. Hold shift and click on another checkbox (for example row number 5)
3. ...

### Result  
Currently row number 1 and row number 5 gets selected

### Expected result  
Row range from 1 to five to be selected

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
There is a duplicate issue #5004.
