### ISSUE TITLE
Using igValidation with igDatePicker

### ISSUE THREAD

**Issue by juliekirwin** [IgniteUI/igniteui-angular#37]
Is there documentation anywhere showing how to use igValidation with an editor? I have been trying to use it with the igDatePicker, but I don't think my syntax is right and I couldn't find anything on validation with igniteui-angular. 

Here's my attempt:
```HTML
<ig-date-picker class="form-control" 
                         id="endDate"
                         ng-model="input.end">
     <validator-options event-check-value='myValidator'>
     </validator-options>                   
</ig-date-picker>
```

```JavaScript
$scope.myValidator= function (evt, ui){
     console.log('called myValidator');
}
```

**Comment by mpavlinov** [comment]
Your syntax is correct, but you probably didn't reference the igValidator script. Make sure to reference `js/modules/infragistics.ui.validator.js` in your page.

**Comment by juliekirwin** [comment]
I have added the the reference to the validator file and it is still not hitting my validator.

**Comment by mpavlinov** [comment]
Here is a sample [fiddle](http://jsfiddle.net/kkof3veb/1/) that you can check.

**Comment by damyanpetev** [comment]
Updates:
For 15.1 and previous: http://jsfiddle.net/damyanpetev/kkof3veb/3/
For the 2015 Vol. 2 release as the igValidator has been updated: 
http://jsfiddle.net/damyanpetev/4mfoxh92/
Events are just events, custom validation is an option that can be used to achieve similar behavior as the one above.
