### ISSUE TITLE
When grid and columns have width in IE the columns are visible outside the grid

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#3716]
### Description  
When grid and columns have width in IE the columns are visible outside the grid

 * igniteui-angular version: 7.2.x
 * browser: IE11

### Steps to reproduce  

1. Open dev sample gridCellEditing
2. Look at the summaries and columns headers

Note: This issue is reproducible in 6.2.x and 7.1.x also 

### Result  
headers and summaries are visible outside the grid

### Expected result  
As in other browsers the grid should look correct

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/51675466-6dfbde80-1fdc-11e9-9d26-7612c7699698.png)

**Comment by zdrawku** [comment]
The issue is caused by missing `-ms-` prefixes. [Autoprefixer](https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie) plugin will enable `-ms-` prefixes for Grid Layout by adding `/* autoprefixer grid: autoplace */` to demos styles.
