### ISSUE TITLE
Grid header and row cells are misaligned compared to the summaries in hierarchical grid.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#3724]
### Description  
The header and row cells are not in line with the summaries.

 * igniteui-angular version: 
 * browser: any

### Steps to reproduce  

1. Open the hierarchical grid sample
2. Observe the first grid

### Result  
The header and row cells are not in line with the summaries due to the expand cells being bigger than the default summaries indentation.

### Expected result  
The header and row cells should be aligned with the summaries.

**Comment by mpavlinov** [comment]
@skrustev Can you verify it, please.
