### ISSUE TITLE
[IE11] igx-grid - Enable/Disable of filtering textbox is not changed as expected.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#3725]
### Description  
Enable/Disable of filtering textbox is not changed as expected.

 * igniteui-angular version: 7.1.1
 * browser: IE11

### Steps to reproduce  

1. Go to [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html) on IE11.
2. Click the filtering chip of "Product Name".
3. Type something in the filtering textbox.
4. Click the filtering icon then change condition to "Empty".
5. Type something in the filtering textbox.
6. Click the filtering icon then change condition to "Contains".
7. Type something in the filtering textbox.

### Result  
At step 5, filtering textbox is NOT cleared and you CAN type characters in the filtering textbox.
At step 7, you CANNOT type characters in the filtering textbox.

### Expected result  
At step 5, filtering textbox is cleared you CANNOT type characters in the filtering textbox.
At step 7, you CAN type characters in the filtering textbox.

### Attachments  
N/A

**Comment by kdinev** [comment]
Is this reproducible under other browsers, as well, or just under IE11?

**Comment by tkiryu** [comment]
@kdinev , so sorry for the late reply. Just under IE11.
