### ISSUE TITLE
Ignite UI For Angular styles lib overrides list-type for all lists on the page

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#3730]
* igniteui-angular version: 7.1.2

### Steps to reproduce  

1. Add any `<ol>` or `<ul>` to a page along with a component from the Ignite UI for Angular library

### Result  
The list has no enumeration or bullets. The list-type iis list-type:none

### Expected result  
Lists to have their default styling.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/14248932/51754535-36b52c80-20c5-11e9-8c9b-74b60c664534.png)

**Comment by grosch** [comment]
Any eta on when this fix will go to production?

**Comment by simeonoff** [comment]
@grosch It's already on a PR. Should be available in 7.2.0.
