### ISSUE TITLE
igx-column-group needs to allow styling

### ISSUE THREAD

**Issue by grosch** [IgniteUI/igniteui-angular#3735]
There's no way to set the styling of an igx-column-group.  That makes the grid look pretty bad when the rest of the headers and cells are styled, and then the group is plain/default.'

**Comment by kdinev** [comment]
@grosch Can you provide the code that you use for styling the column headers and the result with the multi-column headers for reference?

**Comment by grosch** [comment]
%gridHeader {
    width: 100%;
    text-align: center !important;
  }

  .thickRightBorder {
    border-right-width: 8px;
  }

  .pphwHeader {
    @extend %gridHeader;
    background-color: beige;
    border-right: 1px;
    border-right-color: white;
  }

  .pphwHeaderLast {
    @extend .pphwHeader;
    @extend .thickRightBorder;
  }

**Comment by Aleksandyr** [comment]
@grosch Once the [3344](https://github.com/IgniteUI/igniteui-angular/issues/3344) is done you would be able to pass your custom template where you would be able to apply your custom styling freely.

**Comment by zdrawku** [comment]
Hey @grosch, as Alex mentioned we believe that using of Header Templates will allow you to accomplish the column styling that you want. I am closing this issue and if further questions appear we may re-open it.
