### ISSUE TITLE
The last search result of the previous page is not scrolled to when navigating back to it from another page

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#3747]
### Description  
The last search result of the previous page is not scrolled to when navigating back to it from another page.

 * igniteui-angular version: 7.1.x, 7.2.x
 * browser: any

**NOTES:**
- The issue is reproduced for both the **IgxGrid** and the **IgxTreeGrid**.

### Steps to reproduce  

0. Open the **tree-grid-flat-data.sample.html** file and delete the setting for the summaries from the tree grid: **[hasSummary]="c.hasSummary"**. (we do not need it)
1. Run the **Tree Grid Flat Data** dev demo.
2. Enable the paging.
3. Type **ware** in the search box.
4. Navigate to the next search result by using the right-arrow in the search box. (the treeGrid will navigate to its second page)
5. Navigate back to the previous result by using the left-arrow in the search box (the treeGrid will navigate to its first page)

### Result  

The current search result is **not** scrolled to.

### Expected result  
The current search result is scrolled to.

**Comment by DiyanDimitrov** [comment]
We are fixing this issue only for 7.2.x since the fix relies on the onDataChanged event which is not available in the older versions.
