### ISSUE TITLE
Summaries do not use the column's formatter

### ISSUE THREAD

**Issue by astaev** [IgniteUI/igniteui-angular#3762]
### Description  
Summaries do not use the column's formatter

 * igniteui-angular version: 7.1.x
 * browser: any

### Steps to reproduce  

1. Run the sample
2. Click the AddSummary button
3. Scroll the grid to view the change(probably another bug)

### Result  
'Salary' cells values are formatted, but the summaries are not

### Expected result  
Summaries values should be formatted as well

### Attachments  
[mainProj.zip](https://github.com/IgniteUI/igniteui-angular/files/2811314/mainProj.zip)

**Comment by rkaraivanov** [comment]
AFAIK the column formatter function [should not](https://github.com/IgniteUI/igniteui-angular/wiki/Summaries-Specification) affect the summary of the column. If the user wants to modify the formatting/type of summaries he should extend one of our [base classes](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/igxsummaryoperand.html) and pass it to the column.

I agree about the delayed change detection though. Maybe log it as a separate issue.
