### ISSUE TITLE
Issue with export excel/csv from grid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3763]
### Description  
Are there any known issues with the export function in the toolbar of the grid? When I set
![image](https://user-images.githubusercontent.com/12936286/51965100-ca418100-2468-11e9-9cfb-d6e89070eb70.png)
 it looks like this:
![image](https://user-images.githubusercontent.com/12936286/51965121-d6c5d980-2468-11e9-8c7f-7662adaf223e.png)
The buttons are there, but no icon or text:
![image](https://user-images.githubusercontent.com/12936286/51965187-fd841000-2468-11e9-98be-e452a7fdbfbb.png)

When clicking, it gives the following error:
![image](https://user-images.githubusercontent.com/12936286/51965216-0e348600-2469-11e9-9411-00a1a5ad92f2.png)

 * igniteui-angular version: 7.1.3
 * browser: Chrome latest

### Steps to reproduce  

Create a igx grid
Set the exportExcel and exportCsv to true

**Comment by gedinakova** [comment]
@Eralmidia In addition to enabling the export (via the two boolean properties), one needs to specify the actual text that will be shown in the drop-down for each option. Our assumption is that the developer would specify the text that best fits their application, so we don't have default values, hence the tiny empty drop-down. 
  exportExcelText="Export to Excel"
  exportCsvText="Export to CSV"
However, I am not able to reproduce the exception at our end. Could you, please, share some more details or attach a small sample application that demonstrates it?

**Comment by Eralmidia** [comment]
Hi Galina

I was able to reproduce the issue in a fork of your grid sample app. For some reason, on my dev server it fails on both excel and csv. In the sample app, it works on excel, but fails on csv when using the toolbar. But at least that should give you a starting point to find the error:

https://stackblitz.com/edit/angular-uueun1

**Comment by gedinakova** [comment]
@Eralmidia Thank you for providing the sample, it helped a lot. The issue was that the IgxCsvExporterService was not provided in the NgModule and not injected in the component's constructor. I updated the sample with these 2 changes and the export seems to be successful. Please, let me know if you still experience any issues.
https://stackblitz.com/edit/angular-export-configuration

**Comment by Eralmidia** [comment]
Ah, the exports are their own module. That makes sense. Thanks for the support

**Comment by Eralmidia** [comment]
So, after providing the services, the export works. But whenever I choose excel, I get the following message:

![image](https://user-images.githubusercontent.com/12936286/52404591-abc33180-2ac9-11e9-8ecd-0262e0b9173f.png)

**Comment by gedinakova** [comment]
Ok, that's not good. Unfortunately, we cannot reproduce this on our end. I would really appreciate if you can send me the 2 excel files - the exported one before recovery and then the recovered so we can investigate this further.

**Comment by Eralmidia** [comment]
Ok, I've attached one file where I have pressed yes to recover, and one where I have not.

[Data export recovered.xlsx](https://github.com/IgniteUI/igniteui-angular/files/2859858/Data.export.recovered.xlsx)
[Data export.xlsx](https://github.com/IgniteUI/igniteui-angular/files/2859859/Data.export.xlsx)

**Comment by gedinakova** [comment]
Thank you. I get the corrupted file error for both of these 2 files. So I compared them and they seem to be absolutely the same. Can you, please, make sure the repaired one was properly saved and resend it? Thanks in advance.

**Comment by Eralmidia** [comment]
Actually, it seems like repairing and saving the file doesn't really fix the issue. If I repair, and save it as a new workbook, the next time I open it, it needs to repair again. Here is one untouched corrupted, and one which has be repaired and saved as a new workbook:

[Export_corrupted.xlsx](https://github.com/IgniteUI/igniteui-angular/files/2889605/Export_corrupted.xlsx)
[Export1.xlsx](https://github.com/IgniteUI/igniteui-angular/files/2889606/Export1.xlsx)


![image](https://user-images.githubusercontent.com/12936286/53174770-dd201f00-35ea-11e9-88fe-892db4bf2221.png)

Repair log:
![image](https://user-images.githubusercontent.com/12936286/53175000-633c6580-35eb-11e9-8f9d-ad2040e099a2.png)

**Comment by astaev** [comment]
@Eralmidia I've noticed when excel recovers the corrupted files that you've sent, they contain an empty column - with no header and cell values. 
So, I've updated the app with similar grid - to contain an empty column. Here is the app:
https://stackblitz.com/edit/angular-export-configuration-pnbzmt

On that project, if you click on the exportExcel you will get the same Excel message. 
So can you please share, do you have such a column in your igxGrid?

**Comment by Eralmidia** [comment]
@astaev Ah, good catch. I didn't notice that. Yes actually, we do have a column which are templated with a few buttons, for actions which can be applied for each row:
![image](https://user-images.githubusercontent.com/12936286/53863568-d7630a00-3fea-11e9-976b-43256f97b915.png)

It is templated like this
![image](https://user-images.githubusercontent.com/12936286/53863884-81db2d00-3feb-11e9-9b57-733d243c31bb.png)

So the actions field doesn't really have any data, it is just used to identify the template to use. How can I mark the actions column to be excluded from the export then?

**Comment by Eralmidia** [comment]
@astaev Thanks, I'll that a go then
