### ISSUE TITLE
Feature request: ability to omit column from columnHiding list

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3764]
### Description  
We have a grid with a quite a few columns. Because of this, we would like the users to be able to choose which columns to view. This feature is already present in the igx-grid, through the column hiding feature.

However, the grid also contains a "actions" column, to the left, templated with different action buttons for each row (see screen shot below). I would like for this column not to be included in the list of columns in the column hiding.

![image](https://user-images.githubusercontent.com/12936286/51965712-b9920a80-246a-11e9-9eb9-7d0607fcd037.png)

 * igniteui-angular version: 7.1.3.
 * browser: Chrome latest

**Comment by Eralmidia** [comment]
Yes, I think that would be a useful change, thanks.

**Comment by kdinev** [comment]
@Eralmidia This enhancement will appear in `7.1.4` tonight!
