### ISSUE TITLE
Ability to move dialog/toggle

### ISSUE THREAD

**Issue by sstoyanovIG** [IgniteUI/igniteui-angular#3768]
### Description  
I want to be able to move the dialog/toggle around.

**Comment by mpavlinov** [comment]
@radomirchev @kdinev We should define what are the requirements for this feature request.

**Comment by ChronosSF** [comment]
@radomirchev @kdinev ,

With the recently merged Drag&Drop changes adding a drag handle to the dialog is as simple as doing something like this:

```html
<div igxToggle #toggleForm="toggle" class="igx-dialog" [style.width.px]="280" 
    igxDrag [renderGhost]="false" [dragTolerance]="0" [dragChannel]="'dialog'">
    <div class="igx-dialog__window">
        <div class="login-form">
            <div class="dialogHeader">
                <span [style.margin.px]="10">Sign In</span>
                <igx-icon igxDragHandle fontSet="material" class="dialogHandle">
                    control_camera
                </igx-icon>
            </div>
            ...
        </div>
    </div>
</div>
```
The result is:
![issue1](https://user-images.githubusercontent.com/2188411/63168944-33bc6200-c03e-11e9-96bb-d769da2e3ada.gif)

Is there anything else needed for this issue?
