### ISSUE TITLE
Tree Grid collapse icon need to be adjusted

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#3780]
### Description  
Tree Grid collapse icon need to be adjusted to point down in collapsed state and up in expanded state as Material Guide indicates 

 * igniteui-angular version: 7.2.x; 7.1.x ; 6.2.x

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/33216749/52043004-45796480-2547-11e9-819d-f43a37a57b27.png)

**Comment by gedinakova** [comment]
@SlavUI We made some further investigation on this and I am not sure we should go for such a change. [Material's expansion panel](https://material.io/archive/guidelines/components/expansion-panels.html) is using those 2 icons in exactly the opposite way - expand_more is shown on the collapsed item, while expand_less is shown on the expanded item. As opposed to expansion panel, the [only tree implementation](https://material.angular.io/components/tree/overview) we found does exactly what we currently have - chevron_right on the collapsed item and expand_more on the expanded one. What do you think?

**Comment by StefanIvanov** [comment]
We have agreed to follow the expansion panel for all grids, therefore expand_more will be shown on the collapsed row, while expand_less will be shown on the expanded row. The issue description is incorrect.
