### ISSUE TITLE
No event emitted when column is unpinned

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#3799]
### Description  
As a developer I would like to keep track of when a columns gets unpinned. Currently no event is emitted when a column is unpinned. It makes sense that the same onColumnPinning is emitted when column is unpinned as well, with a proper argument indicating if pinning or unpinning action has been done.

Valid for both pinning/unpinning through the API or by the ColumnMoving interactions: https://stackblitz.com/edit/angular-1awm9u

 * igniteui-angular version: 7.1.3
 * browser: all

**Comment by MartinKamenov** [comment]
@kdinev @hanastasov 
Currently the onColumnPinning event emits IPinColumnEventArgs {
    column: IgxColumnComponent
    insertAtIndex: number
}
We can make a second event called onColumnUnpinning. 
In my opinion better option would be changing the IPinColumnEventArgs to have boolean indicaing column's pinned state.
InsertAtIndex name may also be changed as it won't have valid name when column is unpinned.
What is your advice regarding which way to choose for implementation?

**Comment by hanastasov** [comment]
My preference go to emitting the same event for both actions, though we should think how would that impact apps that are currently using this event after upgrading. If we go for that, it seems reasonable adding a boolean indicating the state as you mentioned. I am not sure if we should consider this as a breaking change.

Also, is there the possibility that pinning/unpinning fails  in the end, which would make the boolean in the PinningEvent having the wrong value ?
