### ISSUE TITLE
Feature request: programmable column ordering

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#3814]
### Description  
Often we display grids with quite a few columns. Different customers may value the columns differently, and therefore we want to give them as much customization as possible, through features like column hiding and moving.

We also store these options, so that when the grid loads the next time, it is displayed the same way. This works fine for column hiding, where the hidden property is controlled by the hidden input. But a similar option seems to be missing for column moving (or rather the column order). What I would like is a get/set for the order of columns, so I can load the users preferred order from the server, and apply it to the grid.

**Comment by Eralmidia** [comment]
Hmm, maybe I was to quick with the assessment of column hiding. Is it actually possible to set the hidden column in code?

**Comment by kdinev** [comment]
@Eralmidia If you preserve the columns collection in, let's say localStorage, on destroy, by their `visibleIndex`, then recovering the collection with the order of the visible indices will render the columns in the other your end-user has had them before unloading.

**Comment by Eralmidia** [comment]
Thanks for the stellar support, as usual 👍

**Comment by Eralmidia** [comment]
@kdinev Sorry for opening this issue. But in the sample, it is used a ngFor to render back to columns. What if you need to template some of the columns?

**Comment by kdinev** [comment]
@Eralmidia Take a look at this sample: https://stackblitz.com/edit/angular-1v1k8m

**Comment by Eralmidia** [comment]
@kdinev  I'm sorry for wasting your time 😮 For some reason, I was sure that you couldn't do conditionals on the templates, and that it would simply pick the first one. Might be knowledge from an earlier version of angular perhaps.

**Comment by kdinev** [comment]
@Eralmidia You're not wasting my time at all. I had done this example for another person who had the same question :)

**Comment by Eralmidia** [comment]
@kdinev  I'm afraid I still have issues with the grid setup.

In our case, we save user settings to the server, not local storage or similar, so they are available across pcs. The columns are components themselves, and contains a lot of data, so it seems like a bad idea to have to store those on the server. Instead, I try to store simple arrays (like an array of field names for the order of the columns, and array of field names which should be hidden ect). When rendering the data back, this works well, with an ngFor of the custom column data.

So typically, I have a default array of columns data, then apply some loaded user settings, which for instance removes some elements from the array (hidden columns), and then feed that tho the columns ngFor.

The problem I'm getting, is with the column hiding feature. I'm trying to build a custom toolbar, which includes an instance of the igx-column-hiding component. But this seems to require an array of columns. It becomes a bit cumbersome to set up. I can't read the actual columns of the grid, because this will allready miss all columns previously hidden by the user. It seems to me that it would be easier if there was some kind of visibility setter (input) for the column components.

Do you have any ideas for this use case?

**Comment by kdinev** [comment]
@Eralmidia Apologies for the delay getting back to you. There is a way to set the column as hidden:

https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcolumncomponent.html#hidden

**Comment by Eralmidia** [comment]
That works great. Thanks again, Konstantin
