### ISSUE TITLE
Unwanted one-side borders shown on inputs in toolbar's drop-downs.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#3820]
### Description  
Filter inputs show a thin either right or left border which does not seem to be intended.

 * igniteui-angular version: all
 * browser: N/A

### Steps to reproduce  

1. Run DEV demos
2. Navigate to 'Grid Toolbar' demo
3. Enable pinning drop-down
4. Open pinning UI > note the filter input borders
5. Open hiding UI > note the filter input borders

### Result  
A thin right border only is shown in the pinning UI. A thin left border only is shown in the hiding UI. 

### Expected result  
There should be no borders at all.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/16817847/52270272-1dc03d00-2949-11e9-9620-e66faf209054.png)

**Comment by simeonoff** [comment]
@gedinakova This is a rendering issue related to how the overlay positioning works. It tries to position elements on the sub-pixel level, which breaks the layout.

@wnvko Can you make sure you floor/round the coordinates?
