### ISSUE TITLE
Badges component not working

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#3830]
### Description  
Describe the issue.

 * igniteui-angular version: `7.1.2` and `7.2.0-beta.1`
 * browser: Chrome

### Steps to reproduce  

1. Go to your demo page 
2. https://www.infragistics.com/products/ignite-ui-angular/angular/components/badge.html

### Result  
You'll see that the badges are missing

### Expected result  
Badges should work showing correctly the three badge-type "warning", "error" and "success"

### Attachments  
![igx-badge-missing](https://user-images.githubusercontent.com/29953012/52312263-9508c780-296f-11e9-9c4c-b8212244fa43.gif)

**Comment by zdrawku** [comment]
Hi @luiscla27, I am moving this issue to our angular-samples repository where all other samples live.
