### ISSUE TITLE
KeyDown event is no longer fired when clicked inside an overlay

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#3832]
### Description  
KeyDown event is no longer fired when clicked inside an overlay.

 * igniteui-angular version: 7.2
 * browser: NA

### Steps to reproduce  

1. Open this [sample](https://stackblitz.com/edit/angular-omgoqm)
2. Click on the button to open the overlay 
3. Click in the test div and then any button and observe the console

### Result  
Key down event is not fired when clicked inside the overlay

### Expected result  
Key down event is fired when clicked inside the overlay

**Comment by wnvko** [comment]
Clicking on the div forces the button to lose focus. All events at this point goes through overlay. As overlay is direct child element of the body key down event goes through overlay and then directly to body element. You can still handle key down event on the document body element or in the overlay element, if the last one has some focusable element.
