### ISSUE TITLE
Filtering input is not opened on tap on IPad

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#3839]
### Description  
Filtering input is not open when you tap "Filter" icon on IPad

 * igniteui-angular version: 7.2
 * browser: Safari

### Steps to reproduce  

1. Open [this ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html)sample on IPad
2. Tap on "Filter" icon for "Product Name" (or any other column)

### Result  
The filtering input is not opened.

### Expected result  
Filtering input to be opened.

**Comment by DiyanDimitrov** [comment]
The issue is no longer reproducible.
