### ISSUE TITLE
Button: Outlined button should be supported as a built-in style option.

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#3846]
### Description  
Can we have an option to switch the style to support outlined button?

Here's the guide line describing about the Outlined button.
https://material.io/design/components/buttons.html#outlined-button

 * igniteui-angular version: 7.1.4
 * browser: N/A

```html
<button igxButton="outlined">Outlines Button</button>
```

**Comment by StefanIvanov** [comment]
<img width="419" alt="idle disabled and hover state of outline button" src="https://user-images.githubusercontent.com/1702064/52403226-eda2a680-2ace-11e9-9149-a9393be5e8ad.png">
