### ISSUE TITLE
API docs for igxTreeGrid/igxHierarchicalGrid contain code snippets that are for igxGrid

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#3863]
## Description  
Describe the issue.

 * igniteui-angular version: 7.1.5
 * browser: *

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/igxtreegridcomponent.html#autogenerate
2. Observe the code snippet

## Result  
The code snippet is for igxGrid

## Expected result  
The code snippet should be for the igxTreeGrid

**Comment by Aleksandyr** [comment]
There are some comments (snippets) that need to be updated.
@zdrawku should we consider adding this issue in the upcoming sprint/milestone?

**Comment by zdrawku** [comment]
@Aleksandyr, I've added it to the next milestone

**Comment by hanastasov** [comment]
I am not aware of a way to do this (how a base class example to show code snippet depending on the derived class). I logged a [question on typedoc repo](https://github.com/TypeStrong/typedoc/issues/1418) about it.
