### ISSUE TITLE
Build Error in Angular Library after installing and using controls of igniteui-angular

### ISSUE THREAD

**Issue by YousafKhan0800** [IgniteUI/igniteui-angular#3894]
### Description  
I have created an angular project which also has an angular library in which I need to install and use Ignite UI for angular. When I install it using the command **"npm i igniteui-angular"** and use NgxInputGroupModule in it, it starts giving build error given below; 

> BUILD ERROR : Template parse errors: The pipe 'titlecase' could not be found 
>              ("dy-row"> <span *ngFor="let dayName of generateWeekHeader()" 
>             class="igx-calendar__label">[ERROR ->] {{ dayName | titlecase }}
>         </span>
>     </div> "): D:/GitProjects/BASFProj/projects/ssi- 
>         framework/node_modules/igniteui-angular/igniteui- 
>         angular.d.ts.IgxCalendarComponent.html@38:3 The pipe 'titlecase' 
>         could not be found ("Month($event)" [igxCalendarMonth]="month" 
>         [index]="i" *ngFor="let month of months; index as i;"> [ERROR ->]         
>         {{ formattedMonth(month) | titlecase }}
>         </div>
>     </div> "): D:/GitProjects/BASFProj/projects/ssi- 
>                framework/node_modules/igniteui-angular/igniteui- 
>                angular.d.ts.IgxCalendarComponent.html@53:3

### Steps to reproduce  

1. clone Angular Project from git
2. ng generate library TestLib
3. npm install igniteui-angular
4. Add below-mentioned code in Library Module
`import { NgModule } from '@angular/core';
import {IgxInputGroupModule} from 'igniteui-angular';

@NgModule({
  declarations: [],
  imports: [
    IgxInputGroupModule
  ],
  exports: [],
  providers: [
    // { provide: AuthenticateClientService }
  ]
})
export class SsiFrameworkModule { }`
5. ng build TestLib

### Result  

> BUILD ERROR : Template parse errors: The pipe 'titlecase' could not be found 
>              ("dy-row"> <span *ngFor="let dayName of generateWeekHeader()" 
>             class="igx-calendar__label">[ERROR ->] {{ dayName | titlecase }}
>         </span>
>     </div> "): D:/GitProjects/BASFProj/projects/ssi- 
>         framework/node_modules/igniteui-angular/igniteui- 
>         angular.d.ts.IgxCalendarComponent.html@38:3 The pipe 'titlecase' 
>         could not be found ("Month($event)" [igxCalendarMonth]="month" 
>         [index]="i" *ngFor="let month of months; index as i;"> [ERROR ->]         
>         {{ formattedMonth(month) | titlecase }}
>         </div>
>     </div> "): D:/GitProjects/BASFProj/projects/ssi- 
>                framework/node_modules/igniteui-angular/igniteui- 
>                angular.d.ts.IgxCalendarComponent.html@53:3

Here is my package.json file's content,

> {
>   "name": "web-shell",
>   "version": "0.0.0",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e",
>     "build-all": "ng build ssi-framework && ng build ssi-identity && ng serve"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "~7.1.0",
>     "@angular/common": "~7.1.0",
>     "@angular/compiler": "~7.1.0",
>     "@angular/core": "~7.1.0",
>     "@angular/forms": "~7.1.0",
>     "@angular/http": "^7.1.4",
>     "@angular/platform-browser": "~7.1.0",
>     "@angular/platform-browser-dynamic": "~7.1.0",
>     "@angular/platform-server": "^7.1.4",
>     "@angular/router": "^7.1.4",
>     "@fortawesome/free-brands-svg-icons": "^5.6.3",
>     "@fortawesome/free-regular-svg-icons": "^5.6.3",
>     "angular-font-awesome": "^3.1.2",
>     "angular-fontawesome": "^1.0.0",
>     "angular-oauth2-oidc": "^5.0.2",
>     "bootstrap": "^4.2.1",
>     "core-js": "^2.6.1",
>     "font-awesome": "^4.7.0",
>     "hammerjs": "^2.0.8",
>     "igniteui-angular": "^7.1.1",
>     "jquery": "^3.3.1",
>     "rxjs": "^6.3.3",
>     "rxjs-compat": "^6.3.3",
>     "ssi-framework": "file:dist/ssi-framework",
>     "zone.js": "^0.8.26"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^0.11.4",
>     "@angular-devkit/build-ng-packagr": "~0.8.0",
>     "@angular/cli": "^7.1.4",
>     "@angular/compiler-cli": "^7.1.4",
>     "@angular/language-service": "^7.1.4",
>     "@types/jasmine": "^3.3.5",
>     "@types/jasminewd2": "~2.0.3",
>     "@types/node": "^10.12.18",
>     "codelyzer": "^4.5.0",
>     "jasmine-core": "^3.3.0",
>     "jasmine-spec-reporter": "^4.2.1",
>     "karma": "^3.1.4",
>     "karma-chrome-launcher": "^2.2.0",
>     "karma-cli": "^2.0.0",
>     "karma-coverage-istanbul-reporter": "~2.0.1",
>     "karma-jasmine": "^2.0.1",
>     "karma-jasmine-html-reporter": "^1.4.0",
>     "ng-packagr": "^4.4.5",
>     "protractor": "^5.4.2",
>     "rxjs-tslint": "^0.1.6",
>     "ts-node": "~7.0.0",
>     "tsickle": "^0.34.0",
>     "tslib": "^1.9.0",
>     "tslint": "^5.12.0",
>     "typescript": "^3.1.2",
>     "webpack": "^4.28.3"
>   }
> }
>

**Comment by rkaraivanov** [comment]
@YousafKhan0800 
I've followed your description but I cannot seem to reproduce the problem. I've attached a freshly generated cli app with a library using our latest stable package [testlib.zip](https://github.com/IgniteUI/igniteui-angular/files/2859424/testlib.zip) and running `ng build TestLib` does not crash.

Also the error is quite strange as the calendar component is not even in the input group module. Are you using the calendar component somewhere in your module and you did not include it in the imports section?

**Comment by kdinev** [comment]
@YousafKhan0800 I'm closing the issue due to inactivity. Please reopen if you're still experiencing it.

**Comment by AnatoliyMovchan** [comment]
The same problem in building rendering server of Angular Universal.

`
ERROR in : Template parse errors:
The pipe 'titlecase' could not be found ("dy-row">
        <span *ngFor="let dayName of generateWeekHeader()" class="igx-calendar__label">
   [ERROR ->]         {{ dayName | titlecase }}
        </span>
    </div>
"): /Users/node_modules/igniteui-angular/igniteui-angular.d.ts.IgxCalendarComponent.html@38:3
The pipe 'titlecase' could not be found ("Month($event)" [igxCalendarMonth]="month" [index]="i" *ngFor="let month of months; index as i;">
   [ERROR ->]         {{ formattedMonth(month) | titlecase }}
        </div>
    </div>
"): /Users/node_modules/igniteui-angular/igniteui-angular.d.ts.IgxCalendarComponent.html@53:3`

**Comment by kdinev** [comment]
@AnatoliyMovchan Can you share your `app.server.module` imports?
