### ISSUE TITLE
igPivotGrid issue

### ISSUE THREAD

**Issue by arsinawaz** [IgniteUI/igniteui-angular#39]
Hhi,

I am trying the igpivotgrid and there is a wired issue, i get an error 1 on loading the pivot even though the pivot table is shown correctly and when i try to change the object of the pivot table i get error 2. 

This happens randomly, sometimes it works totally fine and some times it gives these errors.

1.  TypeError: Cannot read property 'top' of undefined
2. Error: cannot call methods on igPivotGrid prior to initialization; attempted to call method 'destroy'

error 1 occurs on this line 
columnsOverlayTop = firstColumnHeaderPosition.top + headersTable.parent().parent().position().top;

in infrajistics.lob.js

URGENT Help needed. Thanks in advance

**Comment by mpavlinov** [comment]
Can you provide a working sample (in (jsFiddle)[http://jsfiddle.net/] for example) or sample code, please.

**Comment by mpavlinov** [comment]
I guess this issue is outdated.
