### ISSUE TITLE
Grid date type editable field does not support string values. Throws error value.toLocaleDateString is not a function when editing.

### ISSUE THREAD

**Issue by ajayambre** [IgniteUI/igniteui-angular#3901]
## Description  
Date type column in the grid expects a real date object as a value.
Passing a String value (for e.g. "2019-02-13T00:00:00") gives the following error:

`ERROR TypeError: value.toLocaleDateString is not a function`
 `   at IgxDatePickerComponent.push.../../../../node_modules/igniteui-angular/fesm5/igniteui-angular.js.IgxDatePickerComponent._setLocaleToDate`

In a real application, the JSON data returned from a server will not have a real Date object.
It will have a string format or long number representation of the date value.

To make this work, I will have to iterate through the data and convert the string values to date objects and then pass that data to the grid.
This is an overhead and will require huge additional processing and memory when dealing with hundreds of rows.

I am using the current JS version of IgniteUI Grid and it supports string values in a given format for date columns.
I am thinking of moving to the igniteui-angular components and found [this DATEPICKER ISSUE](https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/118747/how-to-bind-string-date-to-igxdatetime-picker) during my evaluation.
This is a potential deal breaker for me.

I checked the `grid-crm` samples and found that all the grid samples are driven by  `data.ts` file which has the date as `new Date("2/13/2019")`.

 * igniteui-angular version: 7.1.5
 * browser: Chrome Version 67.0.3396.79

## Steps to reproduce  

1. Add `igx-grid` to the component template with `rowEditable` set to `true`
2. Use `data` property from the component to pass data to the `igx-grid`
3. Set the value of `data` property in the component to 
`[{
    id: 1,
    name: "ABC",
    date: "2019-13-02"
}, {
    id: 2,
    name: "XYZ",
    date: "2019-14-02"
}]`
4. Double click on the date field to try to edit the date.

## Result  
What is the actual result after following the steps to reproduce?
The datepicker does not show up and so the date cannot be edited.

## Expected result  
What is the expected result after following the steps to reproduce?
The datepicker should show up allowing the user to select a date.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/5074211/52701002-2fd05a00-2f9f-11e9-9249-47a13860b2fb.png)

**Comment by tiliev** [comment]
@ajayambre, this behavior is by design. You have to pass `Date` objects to columns with type `Date`.
