### ISSUE TITLE
Scrolling down and going to a page with not enough records to fill up the current scroll top leaves the grid blank

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#3907]
## Description  
In Firefox Scrolling down and going to a page with not enough records to fill up the current scroll top leaves the grid blank

 * igniteui-angular version: 7.2 (master)
 * browser: Firefox

## Steps to reproduce  

1. Open the Grid Cell Editing sample on Firefox
2. Scroll either of the grids all the way down
3. Go to the next (last) page

## Result  
No data is visible (in the first grid half a row is visible)

## Expected result  
The second page records (5-6 or so) should be visible and no scrollbar should be shown

## Attachments  
n/a

**Comment by skrustev** [comment]
This seem to be already fixed in 7.3.x and 8.0.x
