### ISSUE TITLE
Allow transaction value override during commit

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#3910]
## Is your feature request related to a problem? Please describe.
In a real-world application entity ids are assigned server-side, so that an additional update is needed on the data based on the server's response. However, when grid states depend on the data (basically anything that alters the result of the pipes), it is cumbersome to have the grid update its state based on the commit with the wrong data then do it again with the right one.

## Describe the solution you'd like
This is somewhat linked to #3909 . Ideally `commit` should accept an override parameter that is an object that is merged last to the aggregated value to be committed. Logically it works best when committing transactions separately but can be exposed for an overall commit with a collection of some kind. 

## Describe alternatives you've considered
This can be achieved currently by committing then altering the data outside the transaction service, then calling for change detection but it's not as intuitive or elegant as part of a user app. Committing wrong data at first may also be error prone in more complex scenarios.

## Additional context
Part of usability testing with an IgxHierarchicalGrid + ASP.NET Core WebAPI application.

**Comment by wnvko** [comment]
There is no way to distinguish the records returned from server after batch update. Added records for example has new primary keys assigned from the data base. This is application scenario which developers should solve. One way to do this is shown in this blog post "[Editing entities without breaking the network tab](https://medium.com/ignite-ui/editing-entities-without-breaking-the-network-tab-part-1-5-934b5a1dab38)"
