### ISSUE TITLE
Drop down should have modal set to false by default

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#3929]
## Description
If you call `open()` or `toggle()` to ixgDropDown, without providing `overalySettings` drop down appears as dialog - modal and centered on the screen. It should appear as dialog - not modal and connected to its target.

 * igniteui-angular version: 7.2.0 
 * browser: all

## Steps to reproduce  

1. Call `open()` or `toggle()` method of igxDropDown without passing `overlaySettings` parameter.

## Result  
Drop down is shown as dialog - modal and centered on the screen.

## Expected result  
Drop down should not be shown by default as dialog.

**Comment by bazal4o** [comment]
If possible let's make the change into the dropdown position settings, because the developer (in most cases ) expects drop downs to be shown with modal false setting

**Comment by wnvko** [comment]
By default `igxDropDown`, when `open/toggle` is called without `overlaySettings`, will be shown as dialog. If it should be shown as combo box the developer may add `IgxToggleAction` directive to the caller of the `igxDropDown`, or provide `OverlaySettings` with `modal` set to false and `closeOnOutsideClick` set to true to the `open/toggle` method as well as `IPositionStrategy` that best match the developer's scenario, e.g. `ConnectedPositionStrategy` with `target` set as needed.

**Comment by bazal4o** [comment]
Okay I'm closing the issue in that case.
