### ISSUE TITLE
On Keyboard Navigation upon navigating up the Screen Jumps or the navigation stops working

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#3936]
## Description  
On Keyboard Navigation upon navigating up the Screen Jumps or the navigation stops working

 * igniteui-angular version: 7.1.x
 * browser: IE

## Steps to reproduce  

1. Open a sample Virtualization and Performance on the website
2. Scroll down
3. .Then use the keyboard to navigate up 

## Result  
The navigation either stops and the screen flickers and the navigation is not possible any more

## Expected result  
Should continue to navigate up

**Comment by zdrawku** [comment]
I've tested this with the latest [8.2.10](https://github.com/IgniteUI/igniteui-angular/releases) version of the product and scrolling along with keyboard navigation worked well, with slight delays (acceptable for IE11) and without any stops or browser hangs.
