### ISSUE TITLE
igx-grid: Vertical scrollbar overlaps the content of the last column when displayDensity is set to 'compact'.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#3948]
### Description  
Vertical scrollbar overlaps the content of the last column when displayDensity is set to 'compact'.

 * igniteui-angular version: 7.1.7
 * browser: Chrome

### Steps to reproduce  
Run the attached sample.

### Result  
Vertical scrollbar overlaps the content of the last column.

### Expected result  
The last column is fully visible.

### Attachments  

[testApp.zip](https://github.com/IgniteUI/igniteui-angular/files/2878450/testApp.zip)

**Comment by mpavlinov** [comment]
@mkamiishi I believe this is fixed by https://github.com/IgniteUI/igniteui-angular/issues/3396, but the fix is in 7.2.x branch only.
