### ISSUE TITLE
[ng add]: add comment to enable Autoprefixer grid. 

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#3968]
## Is your feature request related to a problem? Please describe.
As [Grid styling Configulation](https://github.com/IgniteUI/igniteui-docfx/blob/master/en/components/grid/grid.md#styling-configuration) says, we need to add comment `/* autoprefixer grid:on */` to enable Autoprefixer grid property in order `igx-grid` to render prolerly in IE11.

Currently, `ng add` adds almost all the configurations but lacks adding the comment.

## Describe the solution you'd like
`ng add` should adds `/* autoprefixer grid:on */` as well.

**Comment by jackofdiamond5** [comment]
Since `ng-add` invokes the `igniteui-cli` schematics - it is responsible for the addition of the custom theme, hence we add the autoprefixer comment as part of the custom theme import.
