### ISSUE TITLE
Drag and Drop the selected row in igx-grid

### ISSUE THREAD

**Issue by pnishimura** [IgniteUI/igniteui-angular#3993]
## Is your feature request related to a problem? Please describe.
Want to drag the selected row (not the selected cell) in igx-grid and drop it on other grids, lists or some other area.
I know this can achieve by cell, but want to achieve by row.
This means that I want to copy the whole cell data in a row to another area.

Note that I do not need to drag and drop multiple rows simultaneously. 

## Describe the solution you'd like
- Change the interface to set the custom function to igxDrag's property in order to set the ghost.
- The parameters of the custom function to set the ghost should be the dragging source node and the return value should be the ghost node.
- When create the ghost, if set the custom function, it will be called. if set nothing, the default setting will be used.

The proposal code change is just like below.

https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts#L582
**At the line #582**

**Current**
this._dragGhost = node ? node.cloneNode(true) : this.element.nativeElement.cloneNode(true);
 
**Proposal code change**
this._dragGhost = this._XXXXX_ ? this._XXXXX_（node) : node ? node.cloneNode(true) : this.element.nativeElement.cloneNode(true);
Note that _XXXXX_ is the custom function name to be able to set the ghost.

## Describe alternatives you've considered
The proposal code change might be just a temporary measure,
If you guys have alternative ideas and code changes, it would also be great.
e.g.) Add a new event igx-grid to capture the row which can be drag-gable.

**Comment by kdinev** [comment]
@pnishimura For dragging and dropping rows we can have the following alternatives:

1. Expose a drag+drop UI, in the form of an icon that apprears in front of the row, like the row selection checkbox, which upon drag will trigger an event, which the dev can consume, and upon drop would trigger another event that the dev can consume. 

> The default behavior would be that if none of the events are handled, then the dragged and dropped row ghost would always revert back to the position of the row. If handled, then the behavior would be defined by the dev. 
> 
> The dragging would be performed on one row at a time, and would not be related to row selection. It would also be toggleable, and by default would not be turned on.

2. Expose a callback to create custom drag ghost for the `igxDrag`. 

> This alternative would not be related to the `igxGrid`. If the dev wants to apply draggable on an element and provide a custom drag ghost, then they would also be responsible for showing to the end-user that the specific element is draggable. 
> 
> The dev can handle multiple elements to be dragged simultaneously, as the whole UI and UX would be a custom definition of the dev. 

Let me know which alternative seems better?

**Comment by pnishimura** [comment]
Hi @kdinev @SlavUI 
I just updated in the section "Is your feature request related to a problem? Please describe." above,
would be more understandable to know the scenario I want to achieve.
Thanks,
Paul

**Comment by pnishimura** [comment]
Hi @kdinev @SlavUI 
I just updated in the section "Is your feature request related to a problem? Please describe." above.

I do not need to drag and drop multiple rows simultaneously.

**Comment by kdinev** [comment]
@pnishimura Post `7.2.0` we will get @StefanIvanov and @DaniMarinov engaged in producing a design for alternative 1.

**Comment by StefanIvanov** [comment]
Hi @pnishimura to understand a little better, you basically want to drag a record from a grid to another surface passing the record information to that receiving surface, whatever it is. Two questions arise:

1. Is the user required to select the row beforehand
2. We are passing the row object and our clients' developers are responsible what to do with the record data e.g. how to handle / render it

I think it will also help a lot if you are able to provide a specific business case in order for us to understand the context in which such a functionality is needed.

**Comment by ymita** [comment]
@StefanIvanov 
I am writing the response on behalf of @pnishimura.
> 1. Is the user required to select the row beforehand

--> No. It is not required to select in order to drag a row.

> 2. We are passing the row object and our clients' developers are responsible what to do with the record data e.g. how to handle / render it

--> I expect the behavior as you describe.

If you have any question with this, please let me know.

**Comment by StefanIvanov** [comment]
Thank you @ymita and @pnishimura in that case I am sharing with you a design proposal that has been discussed internally and for the moment seems like a viable solution, please provide your feedback as well.
![row drag](https://user-images.githubusercontent.com/1702064/53790668-2dbf4280-3f30-11e9-8f27-652c5b83d9c1.png)

**Comment by pnishimura** [comment]
Hi @StefanIvanov 
Sorry, I missed your comment above.
Your design proposal looks good to me!

@ymita @tkiryu 
Could you give us your comment on the design proposal above?

**Comment by StefanIvanov** [comment]
Also check out the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/Row-Dragging)

**Comment by ymita** [comment]
Overall, it looks good. There is one thing to add. As a scenario, I would want to drag row itself. In that case, I would add a pseudo element after the row drag icon.
