### ISSUE TITLE
Autocomplete shows browser default alongside custom drop-down

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#4004]
## Description  
Describe the issue.

 * igniteui-angular version: 7.2.x
 * browser: Chrome

## Steps to reproduce  

1. Start typing in the autocomplete component

## Result  
If you have stored addresses in Chrome, the browser autocomplete menu appears on top of the custom dropdown.

## Expected result  
The default browser autocomplete menu should not appear.

## Attachments  

![Uploading Screen Recording.gif…]()

**Comment by damyanpetev** [comment]
We apply `autocomplete="off"`, but that is ignored in for a few cases.
Actually, all browsers (IE/Edge/FF/Chrome) will ignore this for login forms, which is fine: https://caniuse.com/#search=autocomplete

However, more recent Chrome versions decided on ignoring the off option altogether ([468153](https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164) is WontFix). Reasoning being the option is abused or not a common case, or that Chrome's auto-fill and auto-complete are separate functionalities. The suggestion is to apply some other value that is not recognizable by the browser to disable the auto-fill and in my testing `none` seems to work.

The [spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute) states `off` is the value to apply:
`When an element's autofill field name is "off", the user agent should not remember the control's data, and should not offer past values to the user.`
And as I understand the acceptable values for the attribute, setting `none` is not valid.

There's a feedback issue opened: https://bugs.chromium.org/p/chromium/issues/detail?id=587466
and new ones popping up: bugs.chromium.org/p/chromium/issues/detail?id=914451
though I'm not sure if we should leave the valid value hoping Chrome changes behavior.

**Comment by simeonoff** [comment]
So we are leaving it as it is then?

**Comment by damyanpetev** [comment]
@simeonoff Issue isn't closed, still considering options:
Case is actually narrower as per their closed issue: Auto-complete on most inputs outside a login form will respect the option. So a list of names is perfectly fine.
Auto-fill (the 'separate' functionality, chrome://settings/autofill) however will ignore it and is only related to credit card/address stuff and there's _some_ validity to that choice I suppose.

Not a huge fan of setting an invalid value to the attribute to get around this. Alternatively, we could make the `autocomplete` attribute both `@HostBinding` and `@Input` so it can be changed and warn about using it with payment fields.

**Comment by damyanpetev** [comment]
//CC @rkaraivanov

**Comment by Lipata** [comment]
Still, Chromium bugs are not closed:

https://bugs.chromium.org/p/chromium/issues/detail?id=587466
https://bugs.chromium.org/p/chromium/issues/detail?id=914451

**Comment by Lipata** [comment]
Still no updates on the Chromium bugs above, however, I will close our bug as we prefer that we don't want to do additional logic in our code.
