### ISSUE TITLE
"Select All" should not be treated as a match when searching.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#4020]
## Description  
When performing search in Excel-style filtering UI, "Select All" option should not be treated as a match similar to the behavior in MS Excel.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run Grid Column Moving dev demo
2. Open Excel-style filtering dropdown on the first column
3. Type 'se' in the search box
4. Note the results

## Result  
"Select All" option remains as the only match. Checking/unchecking it an applying the filter does nothing.

## Expected result  
"Select All" should not be treated as a match.

**Comment by gedinakova** [comment]
@SlavUI @kdinev @DaniMarinov I think we should reconsider the design in this case - it doesn't make sense to treat "Select All" as a cell value.

**Comment by SlavUI** [comment]
@gedinakova Hi I agree with you we should spend some time and adjust this accordingly as per your suggestion.

**Comment by DaniMarinov** [comment]
@gedinakova Thank you for letting us know, I will describe this case in the spec. I do agree - it should be correctly adjusted.

**Comment by DaniMarinov** [comment]
@gedinakova I've added UX solution for the case when no values have been found [https://github.com/IgniteUI/igniteui-angular/wiki/Excel-Style-Filtering#43-no-results-found-when-searching-in-the-esf-list](url)
