### ISSUE TITLE
Custom filter dialog opens pre-populated with currently applied filter conditions.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#4023]
## Description  
Custom filter dialog opens pre-populated with currently applied filter conditions.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run Grid Column Moving Dev demo
2. Open filtering drop-down on ID column
3. Uncheck a single checkbox and apply the filter
4. Reopen the dropdown
5. Open text filters sub-menu
6. Select one of the items, e.g. "Contains"
7. Note the content of custom filter dialog

## Result  
The custom filter dialog opens up with a long list of applied filters. There's no item added with the contains condition and an empty value to select.

## Expected result  
The custom filter dialog should not be pre-populated with the applied filters. Only its first condition should be the one selected from the sub-menu with an empty value.

**Comment by gedinakova** [comment]
Maybe we should reconsider the design, because currently you end up with a ton of already applied filters but you don't get the single one you selected in the menu.

**Comment by bkulov** [comment]
The last item in the conditions list is called "Custom filter ...". If this item is selected the custom filters dialog will be populated with the currently applied filters. In all other cases the selected condition will be pre-selected in the dialog.
