### ISSUE TITLE
Excel style filtering is not styled correctly when used for child grid in IgxHieararchicalGrid

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#4038]
## Description  
Excel style filtering is not styled correctly when used for child grid

 * igniteui-angular version: * 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Edit the Hierarchical grid sample to have excel style filtering
2. Open the sample
3. Expand a row
4. Open excel style filtering dialog for a child

## Result  
The horizontal scroll is overlapping the filtering dialog and when scrolling the parent grid stays on its place

## Expected result  
Filtering dialog should be styled correctly when used in child grid

## Attachments  

![hierarchical_filtering4](https://user-images.githubusercontent.com/1182001/53414203-d91f4300-39d6-11e9-90ee-ffd58cd66f46.gif)

**Comment by simeonoff** [comment]
This seems to be an overlay issue.
