### ISSUE TITLE
Number and date filters do not work.

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#4057]
## Description  
Equals operator doesn't filter correctly number values 

 * igniteui-angular version: 7.2
 * browser: NA

## Steps to reproduce  

1. Open dev demos - Grid Column Moving 
2. Open excel style filter for Employees column - Number filter - Equals
3. Enter existing number 68

## Result  
No records found

## Expected result  
Existing filtered record should be displayed

**Comment by gedinakova** [comment]
In addition, if you open Filtering drop-down after step 3, all checkboxes are unchecked.
None of the filters applied via the custom dialog on number and date columns work.

**Comment by sstoyanovIG** [comment]
@gedinakova The default behavior in Excel is like this. If one or more expressions have operators different than 'equals' or values that doesn't exist in the list or the logical operator is 'And', all items in the list are unchecked.
