### ISSUE TITLE
In Edge the datepicker input mask is not correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4079]
## Description  
In Edge the datepicker input mask is not correct

 * igniteui-angular version: 7.2
 * browser: Edge

## Steps to reproduce  

1. Open dev sample datePicker
2. In the last datePicker (Editable Date Picker bind with ngModel) click to edit the value

## Result  
The mask is CCCCCCCCCC and the value cannot be edited

## Expected result  
It should be possible to edit the value

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/53490543-9b84ed80-3a9c-11e9-968c-7d3d8f6e6997.png)

**Comment by sboykova** [comment]
Not reproducible with the latest EDGE version : 
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
