### ISSUE TITLE
Overlay elements are not fully visible in child grid if they need to show outside the bounds of their owner grid.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#4095]
## Description  
Elements that show in overlay like the Done/Cancel buttons or editors that open additional lists/dialogs like the DatePicker may be hidden behind parent grid elements.

Describe the issue.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Open a hierarchical grid with row editing sample.
2. Start editing for a row and open an DatePicker editor.

## Result  
In case the UI element needs to show outside the bounds of its owner grid it may be overlapped by other elements, for example:

![image](https://user-images.githubusercontent.com/10397980/53507939-82dafe80-3ac1-11e9-9adf-60b3e144f330.png)
In the above screenshot the Done/Cancel buttons need to be displayed above the child grid row, but are not visible.

Similarly the date picker also gets cut off:
![image](https://user-images.githubusercontent.com/10397980/53508061-bb7ad800-3ac1-11e9-95dc-bac2b308e19c.png)

## Expected result  
Elements should be attached to their root grid element so that they display on top.
Since the main grid has overflow: visible to prevent those elements from showing outside their root grid container, all overlays should probably close.

**Comment by mpavlinov** [comment]
The same as #4090
