### ISSUE TITLE
Style of grouping drop area

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#4097]
## Question  
How do you style the drop area of the grouping? It seems to remain black
![image](https://user-images.githubusercontent.com/12936286/53551402-88742b00-3b39-11e9-8e79-811b66d17043.png)

I have tried setting all of the variables related to grouping in the docs, but they doen't seem to have any effect
![image](https://user-images.githubusercontent.com/12936286/53551223-10a60080-3b39-11e9-8c95-a51a965f60df.png)

 * igniteui-angular version: 
 * browser: 7.1.4

**Comment by simeonoff** [comment]
@Eralmidia Use the following properties to style the drop-area:

- `drop-area-text-color` - The drop area text color.
- `drop-area-icon-color` - The drop area icon color.
- `drop-area-background` - The drop area background color.
- `drop-area-on-drop-background` - The drop area background on drop color.

The grouparea-background property is used once a group is creating by dropping a column header in the drop-area, if that makes sense.
