### ISSUE TITLE
Combobox set value and clear value

### ISSUE THREAD

**Issue by nikunjgajera** [IgniteUI/igniteui-angular#4098]
I have requirement to use two combo box (multi select dropdown). When first combo box select multiple items then as per this items i need to set records in second combo box.

I am following below url for combo box
https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo.html

I am not found any function or event to clear combo box and set value in combo box
can you please help me?

**Comment by ViktorSlavov** [comment]
@nikunjgajera ,
You can use the combo method [deselectAllItems()](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcombocomponent.html#deselectallitems) to clear the selection.
To set the selection, you can use [selectAllItems()](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcombocomponent.html#selectitems), by passing an array of the objects you want to select from your data. You can specify whether the previously selected items should be cleared by passing the second parameter, `clearSelection`.
The IgxCombo is also supports value binding via `[(ngModel)]` - you can use that for the cascarding scenario and also for clearing the selected values (by setting the bound property to `[]`)

Here is the [StackBlitz example](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcombocomponent.html#selectitems) which illustrates the above concepts.

**Comment by nikunjgajera** [comment]
@ViktorSlavov thanks i will try it

**Comment by nikunjgajera** [comment]
@ViktorSlavov its working perfectly
thanks once again
