### ISSUE TITLE
Calendar should be closed when scrolling is initiated 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4099]
## Description  
Calendar should be under the edited cell when scroll 

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open dev sample gridCellEditing
2. Open cell in column OrderDate in edit mode
3. Open calendar
4. Start scroll vertical or horizontal

Note: when scroll horizontal and the cell is no longer visible the calendar should be closed(Now it is done only for vertical scroll)

## Result  
The calendar is no longer under the edited cell

## Expected result  
Calendar should be closed when scrolling is initiated

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

![image](https://user-images.githubusercontent.com/11463104/53556761-2e7d6080-3b4d-11e9-8cb4-413e0c61ddcb.png)

**Comment by bkulov** [comment]
The calendar should be closed when scrolling.

**Comment by bkulov** [comment]
There should be a discussion what to do with all overlays that could be opened in the grid.
