### ISSUE TITLE
igHtmlEditor online sample is not working properly (one-way binding)

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#41]
igHtmlContent is not correct on initialization, and also when typing into the TEXTAREA content, the one-way binding is not working as expected.
![capture](https://cloud.githubusercontent.com/assets/11193764/8845913/b4451b20-312b-11e5-953b-4f20c0a23de3.JPG)

**Comment by mpavlinov** [comment]
Fixed issue #41 with 0a7e4c253157adb8c67a2cb36ffddd9fcc49c7a9
