### ISSUE TITLE
disable filtering in column hiding

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#4102]
A tiny request guys: The column hiding feature already has disableHideAll and disableShowAll. Could we have a disableFilter as well? When a grid has like half a dozen columns, the filtering feature really is nothing more than UI noise.

**Comment by kdinev** [comment]
Does setting `[filterable]="false"` on the column definition not do the trick?

**Comment by Eralmidia** [comment]
@kdinev for filtering on the columns yes, this was related to the filtering in the column hiding popup:
![image](https://user-images.githubusercontent.com/12936286/53864623-47728f80-3fed-11e9-8afd-2d119f9b245e.png)

It's a tiny request, and for grids with maybe a hundred columns, it's obviously a good feature. But we generally doesn't work with more than 5-15 columns, and the filtering just looks kinda unnecessary in those scenarios.

**Comment by kdinev** [comment]
I see what you mean now! @gedinakova Is there a way to hide the search input in the hiding UI at the moment?

**Comment by gedinakova** [comment]
Currently, the only option for hiding the filtering input would be via a global style setting display:none for input groups in a column hiding header. So basically, adding the following to the global styles.(s)css should do the trick:
.igx-column-hiding__header > .igx-input-group {
    display: none;
}

We will consider, however, adding a property to control the visibility of the filtering input.
