### ISSUE TITLE
In IE11 and Edge when scroll page the excel filter dialog is not moved 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4112]
## Description  
In IE11 and Edge when scroll page the excel filter dialog is not moved

 * igniteui-angular version: 7.2
 * browser: IE11, Edge

## Steps to reproduce  

1. Open dev sample gridColumnMoving in IE/ Edge.
2. open excel filter for a column
3. Scroll page

## Result  
The dialog position is not over the grid

## Expected result  
As in other browsers the dialog position should be correct

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/53571171-e8d28f00-3b70-11e9-9ace-6ffa157780e0.png)

**Comment by bkulov** [comment]
The issue is related to the scrolling strategy of the overlay.

**Comment by wnvko** [comment]
The issue is not reproducible in isolated sample. Tests were run on IE11, Edge, Google Chrome and Opera. This test was run on all the browsers:

- open overlay in grid's outlet;
- scroll the grid's container.

The tests were run in two modes - normal grid container and container with `transfrom: 500px`. In all tests the overlay content was scrolling correctly.

This should be dev sample related issue and not an issue in the `IgxOverlayService`.

**Comment by wnvko** [comment]
@bkulov 
After investigating this we found that:
- on filter icon click [toggleFilterDropDown](https://github.com/IgniteUI/igniteui-angular/blob/30ac6d9117cfa633a59df63929f61dca042ccc4b/projects/igniteui-angular/src/lib/grids/grid-header.component.ts#L208) is called. In this method we show the filter via `overlay.show()` method;
- then in `overlay.opened` event a reference to filter component is get. Then in [onOverlayOpened](https://github.com/IgniteUI/igniteui-angular/blob/30ac6d9117cfa633a59df63929f61dca042ccc4b/projects/igniteui-angular/src/lib/grids/grid-header.component.ts#L284) event handler again is called open this time over the filter toggle.

This is not Ok. Open/Show should be called once.

**Comment by wnvko** [comment]
This is an [issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20763697/) in Edge and in IE. Filtering dialog is shown in fixed container which has a parent with `perspective`. When scrolling fixed container should scroll, but it is not.
