### ISSUE TITLE
In IE11 datePicker delete button is not in correct position when open a cell in edit mode

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4116]
## Description  
In IE11 datePicker delete button is not in correct position when open a cell in edit mode

 * igniteui-angular version: 7.2
 * browser: IE11

## Steps to reproduce  

1. Open dev sample gridColumnMoving in IE11
2. Open cell in column DateCreated in edit mode

## Result  
Clear button for datePicker is over the other cell

## Expected result  
Clear button should be in the cell

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/53573837-0a367980-3b77-11e9-9050-42ce3df8895e.png)

**Comment by tachojelev** [comment]
**Quick notes for IE 11:**
- When a number or string cell is in edit mode, there is an igx-input-group inside that has a width of 100% (from theme) and is a direct child of the cell. Here IE wraps the content successfully.
- When a date cell is in edit mode, there is an igx-date-picker that has **no** width of 100% and it is a direct child of the cell. Making the width of the date picker 100% fixes the issue, however another issue becomes visible in this situation - the value in the middle overlaps with the calendar icon (This is not a follow-up issue, but an existing one).
