### ISSUE TITLE
ExcelStyleFiltering dialog cannot be fully scrolled into view if it opens outside of view

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#4145]
## Description  
The excel style filtering dialog moves with the page scroll so that it can never be scrolled into view if it is initially opened outside of it.

 * igniteui-angular version: 7.2.x
 * browser: MS Edge

## Steps to reproduce  

1. Enable excel style filtering for the second grid in the grid percentage widths sample.
2. Without scrolling the page to have the second grid fully into view open the excel-style-filtering dialog
3. Try to scroll so that you can see the entirety of the dialog

## Result  
Scrolling the page causes the dialog to scroll with it. Scrolling the grid hides it.

## Expected result  
You should be able to scroll the page after opening the dialog to see it fully

## Attachments  
![issue](https://user-images.githubusercontent.com/2188411/53645331-53eb9680-3c41-11e9-8209-f5a3a76c1669.gif)

**Comment by sstoyanovIG** [comment]
Related to #4112

**Comment by ChronosSF** [comment]
Duplicate to #4112
