### ISSUE TITLE
When does isLoading stops and displays emptygridmessage ?

### ISSUE THREAD

**Issue by corganfuzz** [IgniteUI/igniteui-angular#4154]
## Question  

When I've applied the `isloading` prop to the grid, it behaves like it should. However, even tough I'm suppose to have data on my grid at all times, there are strange times (_weekends mostly_) where my data returns an empty array (which my API does by design). 

Therefore, if `isLoading = true` , then data loads asynchronously and loading circular progress waits for it (this is fine)

But shoudln't **circular progress stop** or get replaced by the `emptygridmessage` prop if it finds an empty array?. 
At the end, in the previous version the grid does displays the `emptygridmessage  `prop when `data = []`, right?. 

Right now, if `data=[]` **isloading** just keeps loading forever. In the previous version 7.1.7, it does get replaced by the **emptygridmessage**. This mimic a very alike behavior we used to have previously without infragistics and users were very annoyed by that. (**their feedback was is it actually waiting for something or not?**)

If this is not the case , can you provide some info into mixing `emptygridmessage `and `isloading=true `?

 * igniteui-angular version: 7.2.0-rc.1
 * browser: Chrome

**Comment by kdinev** [comment]
@corganfuzz Do you set `isLoading = false` after you receive the empty array? If yes, and the empty message is not shown instead of the progress indicator, then there's a bug. 

Otherwise, the grid doesn't know when your service has finished loading, so as long as `isLoading === true` the progress indicator will show.

**Comment by corganfuzz** [comment]
Oh man, of course please close this issue. Thanks for the info
