### ISSUE TITLE
Changing the 'filterMode' of a grid at run time does not work

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#4159]
## Description  
Changing the '**filterMode**' of a grid at run time does not work.

 * igniteui-angular version: 7.2.x
 * browser: any

**NOTES:**
Invoking **this.grid.cdr.detectChanges()** after setting the **filterMode** fixes the issue.

## Steps to reproduce  

1. Open the grid-column-groups.sample.html and grid-column-groups.sample.ts files and add the following content to them:

**grid-column-groups.sample.html:**
```html
<button (click)="toggleFilterMode()">Toggle Filter Mode</button>
```
**grid-column-groups.sample.ts:**
```typescript
    toggleFilterMode() {
        if (this.grid.filterMode === FilterMode.quickFilter) {
          this.grid.filterMode = FilterMode.excelStyleFilter;
        } else {
          this.grid.filterMode = FilterMode.quickFilter;
        }
      }
```
2. Run the **Grid Column Groups** dev demo.
3. Click the **Toggle Filter Mode** button.

## Result  
The filter mode is **not** changed.

## Expected result  
The filter mode is changed.

**Comment by bkulov** [comment]
This is by design. The filtering mode couldn't be changed at run time. It should be documented.

**Comment by bkulov** [comment]
Filtering mode cannot be changed at runtime. This is documented here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html
