### ISSUE TITLE
Summaries on the last level are not aligned with the columns

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#4160]
## Description  
Summaries on the last level are not aligned with the columns.

 * igniteui-angular version: 7.2.x
 * browser: NA

## Steps to reproduce  

1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/hierarchicalgrid/summaries.html
2. Expand 'Naomí Yepes' row.
3. Expand 'Dream Driven' row.
4. Scroll down to the summary row.

## Result  
The summary cells are not aligned with the grid cells and headers.

## Expected result  
The summary cells should be aligned with the grid cells and headers.

## Attachments  
![image](https://user-images.githubusercontent.com/43128948/53790720-4d566b00-3f30-11e9-8ae0-eb454f0c7f70.png)

**Comment by dkamburov** [comment]
@DiyanDimitrov Should be resolved already with this issue - https://github.com/IgniteUI/igniteui-angular/issues/4108
