### ISSUE TITLE
Grid cells are not aligned with the column headers when grouping is applied

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#4161]
## Description  
Grid cells are not aligned with the column headers when grouping is applied.

 * igniteui-angular version: 7.2.x
 * browser: NA

## Steps to reproduce  

1. Open the 'Data Grid' -> 'Group By' topic  on staging environment.
2. Look at the demo.

## Result  
The cells are not aligned with the column headers.

## Expected result  
The cells should be aligned with the column headers.

## Attachments  
![image](https://user-images.githubusercontent.com/43128948/53790992-f9985180-3f30-11e9-9ba5-28faabef1609.png)

**Comment by mpavlinov** [comment]
@desig9stein `.igx-grid__row-indentation` is now `padding-right: 1.5rem;`. It was `padding-right: 0.75rem`

**Comment by desig9stein** [comment]
@mpavlinov I can't remember any particular reason, probably I've test something and forgot to bring it back.
