### ISSUE TITLE
Grouping expand/collapse all button is not aligned with the row selector checkbox.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#4178]
## Description  
Grouping expand/collapse all button is not aligned with the row selector checkbox.

 * igniteui-angular version: 7.2.x
 * browser: All

## Steps to reproduce  

1. Open the Grid Group By demo
2. Group by a column

## Result  
The expand all/collapse all button is not updated to be aligned with the row selector checkbox

## Expected result  
The expand all/collapse all button should to be aligned with the row selector checkbox.

## Attachments  
![collapse-expand](https://user-images.githubusercontent.com/3768136/53821109-ca580380-3f75-11e9-943b-917e9b59339e.jpg)

**Comment by desig9stein** [comment]
@skrustev in order for me to move that button, I need a class on that button when the filter row is open. We do the same thing for the hierarchical grid. the class should be ".igx-grid__group-expand-btn--push"

**Comment by desig9stein** [comment]
I've added the styles for the class .igx-grid__group-expand-btn--push. When the class is added the issue can be closed

**Comment by skrustev** [comment]
@desig9stein Should that class be applied to the button itself, because I noticed that for the checkbox it is applied to the parend `div` element?

**Comment by desig9stein** [comment]
@skrustev Add it to the button, please.
