### ISSUE TITLE
Completing filter in the filtering row

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#4198]
## Problem:
When users are adding filters for numeric or string column **using mouse**, they need to confirm completion of the current filter. Now, when they click outside of the input or current filter chip, the input goes out of focus but the filter chip stays selected, so the user may stay with the impression that the filter is not completed.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/41998471/53888566-8c1e1b00-402d-11e9-8f67-57400a13de2a.gif)

## Solution:
Proposed solution:
- having additional UI for confirmation filter chip completion
- clicking (using mouse) out of the input will unfocus the input and the current chip

![Solution 3](https://user-images.githubusercontent.com/41998471/55478885-75b3b100-5625-11e9-8d7a-eb4d1751aba5.png)

Similar to the Erase action icon, the Confirm action icon is:
- not shown if there is nothing typed
- inactive if there is at least 1 symbol typed

In that way we are not going to add more interactions, this Confirmation Action would serve as a reminder to select Enter when the filtering condition is done.

## Describe alternatives you've considered
Currently considering other alternative solution.

**Comment by DiyanDimitrov** [comment]
@DaniMarinov, I am planning to start working on this issue. I think your second suggestion is better since there is no much space for other elements in this UI. If you are ok with it, could you please add it to the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/Filtering-Row)?

**Comment by StefanIvanov** [comment]
Actually, the two points are not alternatives but part of the solution together i.e. if you implement the second idea that would mean that in time we would need to come back to the issue and cover the first idea as well.

**Comment by DaniMarinov** [comment]
@DiyanDimitrov I've updated the solution, check it and let me know if you have any comments.
