### ISSUE TITLE
[Grid] Default pagination template with a custom value for the per page property

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular#4207]
## Description  
Custom `perPage` values are not correctly reflected in the default pagination template.

 * igniteui-angular version: 7.1+
 * browser: All

## Steps to reproduce  

1. Open [this sample](https://stackblitz.com/edit/angular-hxnrvv)

## Result  
The grid per page property is set to 12 and the grid has 12 rendered rows. However the default select shows 5.

## Expected result  
The select in the default pagination template should reflect the value.

**Comment by rkaraivanov** [comment]
Additionally, it would be nice to have the current select element replaced by our `igx-select`.
Something along the lines of this:
![default](https://user-images.githubusercontent.com/20106115/59747128-ecedfe00-9280-11e9-8d42-785c2f892eef.jpg)

@DaniMarinov @simeonoff 
Your thoughts on this?

**Comment by DaniMarinov** [comment]
Yes, it will be better, I will provide design.

**Comment by DaniMarinov** [comment]
@rkaraivanov What do you think about this idea, available for all 3 display density variations?
Comfortable - ![Comfortable](https://user-images.githubusercontent.com/41998471/59858294-68d06f00-9383-11e9-98e0-5bda78b3d21c.png) - uses Cosy Input

Cosy - ![Cosy](https://user-images.githubusercontent.com/41998471/59858296-69690580-9383-11e9-826a-6276fa40a852.png) - uses Compact Input

Compact - ![Compact](https://user-images.githubusercontent.com/41998471/59858295-69690580-9383-11e9-8b28-a6c3b32cb55b.png) - uses Compact Input

**Comment by rkaraivanov** [comment]
@DaniMarinov 
LGTM
