### ISSUE TITLE
IgxGrid - Grid throws an error in `totalWidth` when autogenerate === true && custom column formatter

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#4213]
## Description  

In a basic grid scenario (autogenerate === true & applying a custom formatter onColumnInit), the grid throws an error in the console.

The grid does ultimately render properly and function as expected.

 * igniteui-angular version: post 7.1.9 (inclusive)
 * browser: N/A

## Steps to reproduce  

1. Open the following [StackBlitz sample](https://stackblitz.com/edit/grid-columninit-formatter?file=src/app/grid/grid-resizing-sample/grid-resizing-sample.component.ts)
2. Observe the console

## Result  
Error is thrown:
```
ERROR TypeError: Cannot read property 'getPossibleColumnWidth' of undefined
    at IgxColumnComponent.get [as calcWidth] (column.component.ts:278)
    at IgxGridComponent.get [as totalWidth] (grid-base.component.ts:2778)
```

## Expected result  
No error is thrown

## Additional Notes 
This seems to be introduced in v7.1.9, it can not be reproduced with earlier versions

**Comment by HristoP96** [comment]
@ViktorSlavov This is sample based. The formatter triggers changedetection on the grid too early, which causes this Error. A workaround in this scenario might be setting time out, so that the grid could have time to render its body. Here is a sample: [Formatter with setTimeOut](https://stackblitz.com/edit/grid-columninit-formatter-rl2aju)

**Comment by rlesavre** [comment]
@ViktorSlavov Should we consider that this bug will never be fixed ?

**Comment by rkaraivanov** [comment]
@rlesavre 

This is was [fixed](https://stackblitz.com/edit/angular-3gjf4o) in 7.2.x and upwards.

**Comment by rlesavre** [comment]
@rkaraivanov @ViktorSlavov Awesome, thanks
