### ISSUE TITLE
igxDialog is not positioned correctly under IE11

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#4220]
## Description  
igxDialog is not positioned in the middle of the container under IE11

 * igniteui-angular version: 7.2
 * browser: Internet Explorer 11

## Steps to reproduce  

1. Open [this](https://stackblitz.com/angular/gggbmpbqeyn) sample
2. Click any of the "Show Dialog" buttons. For example, the one for  "Standard Dialog"
3. Observe dialog`s position

## Result  
Dialog is positioned in the bottom right corner.
![dialogposition1](https://user-images.githubusercontent.com/13034836/53969390-62362880-4101-11e9-84a6-9f6604659849.png)

## Expected result  
Dialog window to be positioned in the middle (as it is in Chrome)
![dialogposition2](https://user-images.githubusercontent.com/13034836/53969530-a1fd1000-4101-11e9-8703-373936a4a082.png)

**Comment by damyanpetev** [comment]
@Aleksandyr @wnvko This is totally the `position: absolute` + flex in IE11 messing up.
Did we not make it `relative` just for that reason when using flex(Global) positioning?

**Comment by wnvko** [comment]
No we did not, but we had to.
