### ISSUE TITLE
When click on Apply without any changes in the row, the row is added in the transactions list

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4227]
## Description  
When click on Apply without any changes in the row, the row is added in the transactions list

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open dev sample gridRowEdit
2. In the second grid open a cell in edit mode
3. Click on Apply without make any changes
4. Click on button Commit

## Result  
The row is added in the transactions

## Expected result  
The row should not be added in the transactions, because there are no changes on it

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by wnvko** [comment]
These steps do not log transaction in current state of the grid. However if you follow these steps in the same grid as above:

1. Edit cell value.
2. Commit the change.
3. Put same cell in edit mode.
4. Commit change.

This logs transaction in transaction service. If after above steps you click undo nothing will happen - undo will remove the "empty" transaction.

This should be fixed.
