### ISSUE TITLE
Add column summaries feature to the grid

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-angular#424]
### Description  
Add column summaries feature to the grid (incl. the data util). The summaries must be configurable per column and have predefined 'count', 'min', 'max', 'sum', 'avg' calculations and a custom function support.

**Comment by SlavUI** [comment]
Wiki Specs can be found here: https://github.com/IgniteUI/igniteui-angular/wiki/Summaries-Specification
