### ISSUE TITLE
Grid sizing in flexible layout

### ISSUE THREAD

**Issue by ninaarens** [IgniteUI/igniteui-angular#4244]
## Description  
The grid control doesn't properly adjust its size when inside a flexible layout

 * igniteui-angular version: 7.1.5
 * browser: chrome

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/grid-in-flex-layout
2. Scale the right hand preview window by dragging it left and then right. The grid will grow bigger but not smaller.
3. Use the "open in new window" top right link on StackBlitz to see the sample in desktop modus with pinned side menu
4. Press the hamburger button to hide and show the menu. The grid will grow bigger or smaller but there will be empty white space at the rigth side of the grid
5. Scale the browser window down a little while still staying in desktop resolution. The grid will not scale with the page.

## Result  
See step 2, step 4 and step 5

## Expected result  
After step 2: Grid should grow smaller when the page width is reduced
After step 4: Grid should adjust its layout over the full width rather than getting some empty white space
After step 5: Grid should grow smaller when the page width is reduced

## Attachments  
Sample: https://stackblitz.com/edit/grid-in-flex-layout

**Comment by joedementri** [comment]
Maybe similar to #3639 ?

I found that you can subscribe to size changes in the screen (in my case based on the nav drawer) and call grid.reflow when that happens

[Comment detailing solution](https://github.com/IgniteUI/igniteui-angular/issues/3639#issuecomment-456520590)

**Comment by ChronosSF** [comment]
@rkaraivanov , @MayaKirova , @mpavlinov - likely related to the resize observer implementation.
