### ISSUE TITLE
How to resize  excelfilter, or at least get some features out of this box (pin, hide, text)

### ISSUE THREAD

**Issue by corganfuzz** [IgniteUI/igniteui-angular#4246]
## Question  
One of my favorite new features is the excefilterstyle mode. However, I got 2 observations:

1. My grid is in the middle of my page and the height of my table is 805px , when you click on the filters they do show up. However, because the box is too big , if you scroll down the filters disapear and you have to click the filter menu again for them to show.

2.  What if I dont want the **Pin column**, **Hide column** and **Text Filter** options ? that could solve my problem.  (I have them in my toolbar, already),. Also, the font I set for the grid doesnt affect the font in the excelfilterstyle, **they are actually bigger** than the grid's font. That doesnt make sense, even in excel the filter box and fonts are smaller than the font of the actual data.

See [Blitz](https://stackblitz.com/edit/angular-6xxpgn-thzdr7?file=app/grid/grid.component.html)

![filtertoobig](https://user-images.githubusercontent.com/11259414/54078087-dd294b80-4287-11e9-9c09-b0a35ab09344.jpg)

**Unrelated , yet helpful.**

Looks like all the links for these new components documentation are broken. 

![brok](https://user-images.githubusercontent.com/11259414/54060378-1c8d6480-41c2-11e9-86a1-60942cfd08b5.PNG)

 * igniteui-angular version: 7.2.0
 * browser: Chrome

**Comment by SlavUI** [comment]
@corganfuzz HI you can disable Pin and Hide by disable them from the Grid it self, if you have them active for the grid they will appear in the Excel Style Filtering as well. As for other kind of resize currently it is no possible. About the docs they will be update and published this week :) together with the samples on the website :)

**Comment by corganfuzz** [comment]
You mean active on the toolbar? But I dont want to diaable them there. Or how do you mean “active on the grid”?

**Comment by SlavUI** [comment]
@corganfuzz if the are set to true for the Grid they will be active in the excel filtering as well.

**Comment by corganfuzz** [comment]
Ahh you mean in <igx-column [pinned]=false. Ok that sorta saves me. How about font and styles? Mixins maybe?

**Comment by simeonoff** [comment]
@corganfuzz We can definitely create a typography mixin specific to the excel style filtering. This will allow you to change the font-size of the header and some of the other elements. However, most components used in the excel style filtering menu have typography mixins of their own. As to your other request - being able to hide some of the options in the menu, I guess @SlavUI and @kdinev can chime in.

**Comment by sstoyanovIG** [comment]
@corganfuzz There are two ways to hide the Sorting, Moving, Hiding and Pinning items from the ExcelStyle menu. First one is to disable the feature for the column. Setting 'sortable' and 'movable' inputs of the column to false will remove the Sorting and Moving items from the menu. Setting 'disableHiding' and 'disablePinning' inputs of the column to true will remove the Hiding and Pinning items from the menu. The second way is to add empty templates to the column for the options you don't want to appear in the menu. E.g. adding:

<igx-column field="ID" sortable=true>
    <ng-template igxExcelStyleSortingTemplate>
    </ng-template>
</igx-column>

to a column that is sortable will remove the sorting item from the excel style filtering menu, but the column will remain sortable. There are also igxExcelStyleMovingTemplate, igxExcelStyleHidingTemplate and igxExcelStylePinningTemplate.

**Comment by corganfuzz** [comment]
disableHIding and disablePinning works perfectly. sortable and movable dont. I will take a look at the template. I sorta hesitate to to change every single column I have on my grid. I wish there was something global. If worst comes to worst I could probably do it, but programatically instead of putting it inside the HTML

**Comment by sstoyanovIG** [comment]
@corganfuzz you can see this sample:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel_style_filtering.html#configure-menu-features

e.g. the 'Quantity Per Unit' column has hiding, moving, sorting an pinning turned off.

**Comment by bkulov** [comment]
@corganfuzz we are working on a sample which demonstrates how you could hide some of the features (sorting, hiding, pinning) from this dialog without disabling those features per column. Once we're done we will update this issues with a link to the sample.

**Comment by bkulov** [comment]
Excel style filtering dialog should use grid's displayDensity property. Related issue #4300.

**Comment by bkulov** [comment]
There are plans to have different layouts of the excel style filtering dialog according to grid's `displayDensity` property. Related issue is #4367

**Comment by SlavUI** [comment]
@corganfuzz  closing this one as there is an issue open to add displayDensity :)

**Comment by corganfuzz** [comment]
btw @sstoyanovIG your approach in conjunction with `*ngFor` worked wonderfully.

**Comment by bkulov** [comment]
@corganfuzz We've added a sample demonstrating how to use custom templates to customize excel style filtering UI. If you provide an empty template the corresponding feature will not be visible in the excel style filtering UI. 
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel_style_filtering.html#configure-menu-features
