### ISSUE TITLE
Hierarchical Grid 

### ISSUE THREAD

**Issue by rakeshongithub** [IgniteUI/igniteui-angular#4247]
## Hierarchical Grid #827
As per roadmap document Hierarchical grid was about to ship on March 8, 2019. Can we get it deployed on production.

**Comment by zdrawku** [comment]
Hello @rakeshongithub, the Grid [was released on March 8th](https://twitter.com/KonstantinDinev/status/1104019547382837248) and it is available on [npm](https://www.npmjs.com/package/igniteui-angular/v/7.2.0), as for the Grid samples, api and documentation, we plan to publish them at the beginning of this week. I will keep you updated with the progress.

Grid stackblitz sample available [here](https://stackblitz.com/edit/angular-hierarchical).

**Comment by zdrawku** [comment]
Hi @rakeshongithub, igxHierarchicalGrid docs and samples are available now.
- [Samples and docs](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/hierarchical_grid.html)
- [API docs](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/)

**Comment by rakeshongithub** [comment]
Thanks @zdrawku.
