### ISSUE TITLE
igx-carousel animated slides

### ISSUE THREAD

**Issue by roscheld** [IgniteUI/igniteui-angular#4268]
It would be really nice to have animations when the slides are changing.

**Comment by ninthtide** [comment]
Thanks Rudy for raising this request.  I tried MDB Bootstrap carousel but I couldn't embed other Angular components into the carousel slides, whereas I can with Ignite UI, so am considering using that in my projects.  I'd also like to have some options for transitions between carousel components, ideally a slide option, and a cross-fade option, if that can be done.
