### ISSUE TITLE
An error gets thrown when a cell in a date column is being edited in MS Edge

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4274]
## Description  
When a column of type "date" gets edited in MS Edge, an error gets thrown in the browser console. The issue does not reproduce when testing with a sample in production, like [this one](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html).

 * igniteui-angular version: 7.2.x, 7.2.0
 * browser: MS Edge

## Steps to reproduce  

1. Run the dev samples
2. Open http://localhost:4200/gridRowEdit in MS Edge
3. Double-click a cell in the OrderDate column (the second to last one)

## Result  
Opening the console shows the following error message: 
ERROR TypeError: Object doesn't support property or method 'formatToParts'

ERROR CONTEXT [object Object]

Trying to clear the date in the input throws another error: 

ERROR TypeError: Unable to get property 'replace' of undefined or null reference

ERROR CONTEXT [object Object]

## Expected result  
No errors should be thrown when the user edits a date cell
## Attachments  

![Sketch](https://user-images.githubusercontent.com/18643062/54141474-7003ea80-442e-11e9-96bc-87cee021c0fb.png)

**Comment by nrobakova** [comment]
The is fixed in the latest Edge version (Microsoft Edge 44.17763.1.0)
