### ISSUE TITLE
When you pin child column the whole group is not pinned

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#4278]
## Description  

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Open hierarchicalGrid dev sample
2. Set pinned of the column **Id** to false in the parent grid
3. Set pinned of the column **ChildLevels** to true

## Result  
The grid layout is broken and only the column is pinned
![image](https://user-images.githubusercontent.com/34240583/54182028-0543c500-44a9-11e9-944d-573515dc07e0.png)

## Expected result  
the whole column group should be pinned

**Comment by ChronosSF** [comment]
FYI, this happens for every grid with set width in px but with columns that don't have width defined. Basically you can't initially pin columns part of groups in such scenarios.
