### ISSUE TITLE
Multiview Calendar with Range Selection of Date

### ISSUE THREAD

**Issue by rakeshongithub** [IgniteUI/igniteui-angular#4282]
## Multiview Calendar with Range Selection of Date  
I am looking for Multiview calendar with Range Selection. Right now you have only one month view with range but I want to display two month with range selection.

Is this available or not.

**Comment by kdinev** [comment]
@rakeshongithub Currently it's not. You can achieve it with multiple month views though. 

I can turn this into a feature request where the number of months to show can be configurable and a start month can be set?

**Comment by rakeshongithub** [comment]
Thanks for the quick response.

Please move this in feature request so in future we can have this configurable. Please suggest by when we can get this if possible.

**Comment by kdinev** [comment]
@rakeshongithub As soon as we plan it for a milestone, myself or @SlavUI will update the issue to let you know when to expect it.

**Comment by hanastasov** [comment]
Progress:
[ ] - multi view inputs and rendering
[ ] - keyboard navigation
[ ] - selection
[ ] - date picker bug
