### ISSUE TITLE
Angular httpinterceptor(jwt token header) not working after importing IgxTreeGridModule in lazy loaded module

### ISSUE THREAD

**Issue by badre429** [IgniteUI/igniteui-angular#4285]
### Description  
Angular httpinterceptor(jwt token header) not working after importing IgxTreeGridModule in lazy loaded module

- Ignite UI CLI version: no
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. create lazy loaded module 
2. import  IgxTreeGridModule in the module 

### Result  
in the app module httpinterceptor is working 
![image](https://user-images.githubusercontent.com/5818051/54189001-2b6d6300-44b1-11e9-849b-fa08c581166e.png)
in the lazy loaded module the unterceptor stop 

![image](https://user-images.githubusercontent.com/5818051/54189175-8a32dc80-44b1-11e9-8aa2-4a70612f190f.png)

### Expected result  
if we remove IgxTreeGridModule from import list in the lazy loaded it works 
![image](https://user-images.githubusercontent.com/5818051/54189504-3e346780-44b2-11e9-9bd7-68224cb4fc6f.png)

### code for this issue
https://github.com/badre429/igx-jwt-error

[or live on stackblitz](https://stackblitz.com/github/badre429/igx-jwt-error)

**Comment by rkaraivanov** [comment]
@badre429 
I'm not sure if this is related to the tree grid at all.

Checking the JwtInterceptor I found [this](https://github.com/auth0/angular2-jwt/issues/440).
And it seems to fall with your case:
1. If we stick the TreeGrid module (which provides services locally to itself) in the main app module all works.
2. If we stick it in the lazy loaded module (and remove it from the app module) the JwtInterceptor fails.

I modified your [sample](https://stackblitz.com/edit/github-8vq3yd) following one of the workarounds in the thread, and it works. I suspect that any lazy loaded module importing another module with services in it will fail.

I'll mark this as a 3rd party issue as the tree grid uses neither the HttpClient nor any global singleton services.

**Comment by badre429** [comment]
this work around  has to be don for each service provider replaced on the AppModule (MomentAdapter+ i18nAddapter+...)  
```ts
 providers: [{
    provide: HTTP_INTERCEPTORS,
    useClass: JwtInterceptor,
    multi: true
  }]
...........
```
> need to know : why IgxTreeGridModule remove services provided from AppModule ???
