### ISSUE TITLE
Unify display of all form components

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#4287]
## Description  
Components like input-group and combo have `display: block`, which allows setting CSS rules like `margin`. Select, date and time pickers have the default `display: inline` and when placed together with input-group and combo, additional HTML containers are needed in order to unify their look.

## Steps to reproduce  

1. Open the following [demo](https://stackblitz.com/edit/igx-input-form)
2. Open application [scss](https://stackblitz.com/edit/igx-input-form?file=src%2Fapp%2Finput-group%2Freactive-forms%2Freactive-forms.component.scss) file and note that the CSS rules set `margin `and `width `of all the input components.

## Result  
input-group and combo components accept the CSS rules (`display: block`)
select, date-picker and time-picker don't accept CSS rules (`display: inline` - default one)

## Expected result  
Components have a similar display that allows applying the same CSS rules

**Comment by simeonoff** [comment]
@Lipata Ok, however, the combo sets its width to a 100% using inline styles in javascript, so the width you set in the class selector style rules will be overridden by the one specified in the template.

**Comment by Lipata** [comment]
@simeonoff this default width of `100%` can be removed. Thanks!

`@HostBinding('style.width')`
`@Input()`
public width<s> = '100%</s>';
