### ISSUE TITLE
[calendar] Weekday formatting doesn't respect formatViews set to false 

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#4298]
## Description  
weekday formatting doesn't respect formatViews set to false

 * igniteui-angular version: 7.2
 * browser: NA

## Steps to reproduce  

1. Open the [sample](https://stackblitz.com/edit/angular-smha5w?file=src%2Fapp%2Fcalendar-sample-5%2Fcalendar-sample-5.component.ts)
2. Observe weekdays - they should be short (by default) 

## Result  
weekdays formatting doesn't respect  formatViews settings

## Expected result  
weekdays formatting should respect  formatViews settings

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by SAndreeva** [comment]
I would rather leave this way. Otherwise I we need to add one additional format option which will introduce a breaking change.
