### ISSUE TITLE
igxTreeGrid Export to Excel missing file extension in downloaded file

### ISSUE THREAD

**Issue by prabakaran1311** [IgniteUI/igniteui-angular#4302]
## Description  
I am using igxTreeGrid in angular7. while exporting to excel file is downloading without file extension .xlsx
Also i am using remote filtering i have to download remote data in the excel.
 * igniteui-angular version: 7.1.7
 * browser: Internet Explorer

## Steps to reproduce  
Basic implementation steps i have used to setup igxTreeGrid

## Result  
while Exporting to excel file is downloading without file extension .xlsx
![sample](https://user-images.githubusercontent.com/18000286/54277233-4fb26800-45b5-11e9-9b9a-e0c87ae7864c.PNG)

## Expected result  
Need to download Excel file with file extension

## Attachments  
Sample screenshot is Attached

**Comment by kdinev** [comment]
@prabakaran1311 I just tested the exporter in the live samples and the file extension is correct:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/export_excel.html

![image](https://user-images.githubusercontent.com/1472513/54277537-d0af3680-4598-11e9-86af-60f724f83e05.png)

Could you please provide the code you initiate the export with?

**Comment by prabakaran1311** [comment]
@kdinev Thanks for your reply. below is my code

**Comment by tachojelev** [comment]
Hello @prabakaran1311,

Can you please provide us with an isolated working sample that uses the settings you mentioned from above, where the issue with the missing extension is reproduced? Is MS Excel installed on the machine you reproduced the issue?
It would also be great if you could attach one of the files with the missing extension you produced. This will allow us to look further into the issue.

**Comment by prabakaran1311** [comment]
@tachojelev i find the issue why its not exporting with the file extension. Because i am using older jquery infragistics js files which is referencing to our application **infragistics.core.js** this file causing the conflicts between both version. Once i removed this js its started working fine. Thanks for your help
