### ISSUE TITLE
On touch device when the grid is scrolled row selectors cannot be checked

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4308]
## Description  
On touch device when the grid is scrolled row selectors cannot be checked

 * igniteui-angular version: 7.2
 * browser: -

## Steps to reproduce  

1. Open https://www.infragistics.com//angularsite/components/grid/selection.html on touch device
2. Scroll grid vertical
3. Tap on a row selector checkbox

## Result  
Row is not selected

## Expected result  
It should be possible to select a row

**Comment by zdrawku** [comment]
@nrobakova can we test this, a lot of changes were included lately.

**Comment by ddincheva** [comment]
This bug can be no longer reproduced in our latest major versions.
