### ISSUE TITLE
Igx-carousel steals the focus when slides are changed automatically

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#4312]
## Description  
Igx-carousel steals the focus when slides are changed automatically

 * igniteui-angular version: 7.2
 * browser: all

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-zjub6a
2. Scroll down to the bottom and click somewhere in the white space
3. Wait 3-5 second when the slide will be automatically changed

## Result  
The Igx-carousel steals the focus and scrolls the page to the top

## Expected result  
The Igx-carousel steals the focus and scrolls the page to the top when changing slides.

**Comment by nrobakova** [comment]
This issue is similar to the bug #4292 and it should be fixed with PR #4577
