### ISSUE TITLE
In IE11 list items are not correct formatted 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4320]
## Description  
In IE11 list items are not correct formatted 

 * igniteui-angular version: 7.2
 * browser: IE11

## Steps to reproduce  

1. Open dev sample listPanning in IE11
2. Look at the list items

## Result  
In the list items phone is not previewed and text is not to the image

## Expected result  
As in other browsers the phone and text align should be correct

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/54366004-8b623600-4678-11e9-8ab5-99290573dd2c.png)

**Comment by simeonoff** [comment]
@nrobakova this is sample specific.

**Comment by nrobakova** [comment]
close because of the comment.
