### ISSUE TITLE
In IE11 when swipe an item it is flickering 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4321]
## Description  
In IE11 when pan an item it is flickering 

 * igniteui-angular version: 7.2
 * browser: IE11

## Steps to reproduce  

1. Open dev sample listPanning in IE11
2. Start moving item to the left/right

This issue can be related to the bug #4320 
## Result  
The panel is flickering

## Expected result  
As in other browsers the sample should work correct

**Comment by rmkrmk** [comment]
After investigating the issue it looks like the more containers and elements you have in a list item the more flickering there is (in IE 11). If you populate the list items with a text value only there is minimal flickering or no flickering at all. I had a talk with @rkaraivanov and after profiling is looks like most of the CPU time is consumed by IE's Garbage Collection and handling events in the Angular FW and Hammer FW. There is nothing that can be optimized in our code.
