### ISSUE TITLE
Virtualization of grid not working in tab

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#4329]
## Description  
The virtualisation of the igx-grid seems to break when the grid is placed in a tab component, and not on the first tab. I'm guessing something fails since the grid is effectively hidden when the data is triggered.

On the screenshot below, notice that the log (igx-grid) is on the second tab, and the number of DOM nodes is running crazy:
![image](https://user-images.githubusercontent.com/12936286/54430921-4a742b00-4725-11e9-9a17-ceeea94213d4.png)

If I instead move the log to the first tab, making it visible on init, the virtualisation seems to work fine:
![image](https://user-images.githubusercontent.com/12936286/54431030-97f09800-4725-11e9-991e-52f50c685504.png)

 * igniteui-angular version: 7.2.0
 * browser: Chrome

## Steps to reproduce  

1. Create a igx tab component
2. Create a igx grid with a lot of rows on a tab which is not the first

## Result  
Half a million DOM nodes is rendered for 10k rows, freezing up the browser for several minutes

## Expected result  
Virtualization should not break when grid is hidden

**Comment by mpavlinov** [comment]
@Eralmidia What's the grid height that you set? There is a logic that will set implicitly height to null in some scenarios which will basically disable virtualization and will render all rows.

**Comment by Eralmidia** [comment]
@mpavlinov 

![image](https://user-images.githubusercontent.com/12936286/54431889-e43cd780-4727-11e9-8c27-7ab227652ce7.png)

![image](https://user-images.githubusercontent.com/12936286/54431902-edc63f80-4727-11e9-99c5-73c18525af15.png)

We have had quite a few issues with the virtualization already, so I've made a habit of always testing with fixed px values ;)

**Comment by mpavlinov** [comment]
@Eralmidia Ok. Thanks. This is not expected. Will investigate it with this setup.
