### ISSUE TITLE
igxHGrid column can not be sorted on iPad if it is movable

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#4352]
## Description  
igxHGrid movable columns can not be sorted on iPad.

 * igniteui-angular version: 7.2.0
 * browser: Safari

## Steps to reproduce  

1. Run [this ](https://stackblitz.com/angular/oaelmojkenm?file=src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-sorting%2Fhierarchical-grid-sorting.component.html)sample on iPad
2. Set "Artist" column to be movable, [movable]="true"
2. Tap on "Artist" column header.

## Result  
Column is not sorted.

## Expected result  
Column to be correctly sorted when tapping on its header.

**Comment by MayaKirova** [comment]
This appears to be fixed with the fix for #4376
