### ISSUE TITLE
Provide a way to turn off the built-in filtering and sorting for remote scenarios

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#4356]
## Is your feature request related to a problem? Please describe.
If you want to implement remote filtering and sorting, the grid's built-in filtering and sorting cannot be prevented.
You can see this if you open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/virtualization.html#remote-sortingfiltering-virtualization. Click the "ProductID" column header to sort descending. First you see the row with ProductID=9 on top because of the grid local sorting, then the remote data is loaded and ProductID=77 is on top.

## Describe the solution you'd like
Provide a way to turn off the built-in sorting and filtering pipes when you perform these operations remotely.

**Comment by prabakaran1311** [comment]
@DiyanDimitrov when it will be available because i am facing one issue. while filtering done first it filters the local data if filtered data is not available in local data it showing **"no data"** message then it is rendering the Remote datas in grid. how to solve this in tree grid.

**Comment by DiyanDimitrov** [comment]
@prabakaran1311, Currently there is no way to solve this. We are discussing the possible ways to implement it inside the component and we will plan working on it in a future sprint.

**Comment by brookhutchinson** [comment]
Is there any update on this issue?  Why would the grid show "No records found" message if there grid is still waiting on a response from an API?  How can we remove this "No records found" message?

**Comment by DiyanDimitrov** [comment]
@brookhutchinson, The reason the grid is showing the "No records found" message is that the grid is not aware of the waiting for a response. The gird just performs the filtering on the locally loaded data. 

Currently the `onFilteringDone` event is fired after the local filtering is completed. We were discussing with @rkaraivanov that we can add `onFiltering` event which is fired before the local filtering is performed and we could give the option to cancel the local filtering in that event.

If you want to hide this message as a workaround you could set the [emptyFilteredGridMessage](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#emptyfilteredgridmessage) input property to an empty space character like this `[emptyFilteredGridMessage]="' '"`. Keep in mind that this way the message won't appear even if the filtered data from the server is empty.

**Comment by brookhutchinson** [comment]
Thank you for your suggestion.  Issue resolved by setting the emptyFilteredGridMessage input property to an empty space character.
