### ISSUE TITLE
Excel style filtering - display density design and UX changes

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#4367]
## Description  
Due to the various actions within the ESF dialog, it has to be optimized for comfortable, cozy, compact display density which leads to some UX and design changes.
Check specification here:
https://github.com/IgniteUI/igniteui-angular/wiki/Excel-Style-Filtering

* [x] Tests
* [x] Development
* [x] CHANGELOG
* [x] Samples
* [x] Localization Strings (https://github.com/IgniteUI/igniteui-angular-i18n)

**Comment by bkulov** [comment]
@DaniMarinov could you please add these designs to the spec too?

**Comment by DaniMarinov** [comment]
@bkulov The spec is updated, so you can find them there, too. 
https://github.com/IgniteUI/igniteui-angular/wiki/Excel-Style-Filtering#42-display-density

**Comment by tachojelev** [comment]
Related to #4300
