### ISSUE TITLE
Excel Style Filtering - changes in the ESF dialog when opening after previous filtering

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#4368]
##Description
When I, as an end user, open a ESF dialog for first time, it displays all available unique values: 
<img width="304" alt="Screen Shot 2019-03-20 at 12 56 25 PM" src="https://user-images.githubusercontent.com/41998471/54679313-a4069c00-4b0f-11e9-8ab9-e822e4a54473.png">
Currently, when the ESF dialog is opened after previous filter selection, it displays only the previously selected unique values:
<img width="294" alt="Screen Shot 2019-03-20 at 12 54 05 PM" src="https://user-images.githubusercontent.com/41998471/54679155-45d9b900-4b0f-11e9-9606-777cf837afd3.png">

## Result  
When I select unique value(s) to filter, then close the ESF dialog and open it again, it has to display only the previously selected unique values. In addition, the _Select all_ checkbox is not available, because not all initially available unique values are visible, there is a Secondary button _Reset all filters_ instead.
![adasde](https://user-images.githubusercontent.com/41998471/54679410-dd3f0c00-4b0f-11e9-9161-5ab4ebcf2b7e.png)

**Comment by bkulov** [comment]
@DaniMarinov we already have an option to clear/reset the applied filter.
![изображение](https://user-images.githubusercontent.com/2705882/54742074-040d4900-4bc9-11e9-84fd-2afc45b9d0d2.png)
