### ISSUE TITLE
[igxInputGroup] How to add validation messages?

### ISSUE THREAD

**Issue by ramunas-k** [IgniteUI/igniteui-angular#4369]
## Question  
Looking into documentation [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/label_input.html). There are several samples with validation rules applied but none of them show any error messages. Does this library provide something out of the box?

 * igniteui-angular version: latest
 * browser: any

**Comment by StefanIvanov** [comment]
@ramunas-k you can use the igxInputGroup with a hint like shown [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/input_group.html) under the hint section. Within the hint you can display the error message and the whole input group can be styled as error/warning.

**Comment by ramunas-k** [comment]
@StefanIvanov got it.
Thank you
