### ISSUE TITLE
Load the grid with cells in edit mode

### ISSUE THREAD

**Issue by ammritt** [IgniteUI/igniteui-angular#4373]
## Is your feature request related to a problem? Please describe.
I find it bit inconvenient for the users when they are required to double click OR press Enter to enable Edit mode in the cell.

## Describe the solution you'd like
Is there a way to automatically load the grid with all the cells in edit mode, meaning when the page loads single click on any cell with open the cell editor.

**Comment by zdrawku** [comment]
Hey @ammritt, you can use igxCell template in order to achieve this.
[StackBlitz samples](https://stackblitz.com/edit/igx-grid-cascading-sgnilw).


```
  <igx-column field="UnitPrice" header="Unit Price" [dataType]="'number'">
    <ng-template igxCell let-cell="cell" let-val let-row>
      <input name="units" [(ngModel)]="cell.value" style="color: black; width: 100px"/>
    </ng-template>
  </igx-column>
```

**Comment by ammritt** [comment]
Hi @zdrawku thanks for the reply.
I think you misunderstood my question. I want to load my grid in edit mode so user doesn't have to double-click any cell to start the edit mode but  just single click a cell and start editing.

**Comment by zdrawku** [comment]
Hi @ammritt, did you have the chance to check the [provided sample](https://stackblitz.com/edit/igx-grid-cascading-sgnilw)? `Unit Price` cells are in edit mode when the grid is loaded, you can use the same 
 approach for all orher cells that you want to put in edit mode by default, by using the igxCell template.

![image](https://user-images.githubusercontent.com/11193764/55055601-28a36e00-506c-11e9-9ab2-2e081bb77014.png)

**Comment by ammritt** [comment]
@zdrawku  Thanks I tried your way, this works as we are basically using an edit input as bodyTemplate for the cell.
Unfortunately this is not what I need, this solution will need me to write the cell editor markup for all the column definitions each time I define a grid. HTML5 input markup also look bit off when used.

All I want for my users is to be able to start editing without double-clicking on any cell. I think a simple method to set the edit mode of the grid can be useful. What you think?

**Comment by zdrawku** [comment]
hey @ammritt, you can use [cellClick ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#oncellclick)emmiter, and from there you can put the cell in edit mode with [inEditMode](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcellcomponent.html#ineditmode) setter.
After that on any cell click (single) or keyboard navigation change, the newly focused cell will be put in edit mode.

[Example](https://stackblitz.com/edit/angular-grid-edit-mode-on-click)

**Comment by ammritt** [comment]
Thanks for the update @zdrawku 
I will close this issue.
