### ISSUE TITLE
Gird - sorting is not working with the new Chrome version

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#4376]
## Description  
DragDrop directive **stePointerCapture()** method breaks the click HostListener in the header component in Chrome browser.

 * igniteui-angular version: all
 * browser: Chorme

## Steps to reproduce  

1. Update chrome to Version **73.0.3683.86 (Official Build) (64-bit)**
2. Run any dev demo that has sortable columns
3. Try sorting a column.

## Result  
Sorting is not working.

## Expected result  
Sorting works.

**Comment by mpavlinov** [comment]
@SAndreeva I think that moving needs to enabled too in order to reproduce it, because I can sort in this [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/sorting.html)
