### ISSUE TITLE
[igx-grid] height is not calculated properly when summaries are enabled

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/igniteui-angular#4383]
![summaries](https://user-images.githubusercontent.com/10612538/54768178-52d9d380-4c07-11e9-9b87-519ee08ac8c1.png)

## Description  
Describe the issue.

 * igniteui-angular version: all
 * browser: Chrome

## Steps to reproduce  

1. Open the grid summaries sample
2. Change the background color

## Result  
Grid height is not calculated correctly and there is a red border between the grid content and the summaries

## Expected result  
Grid height should be calculated correctly 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by gedinakova** [comment]
This is no longer reproduced - marking "already fixed".
