### ISSUE TITLE
igx-dialog add button

### ISSUE THREAD

**Issue by nikunjgajera** [IgniteUI/igniteui-angular#4389]
In my application, i need to add 3 button in dialog.
1) Cancel
2) Update
3) Delete
I am able to add 2 buttons and dont know how to add 3rd button
I am using below code for add 2 buttons
```
<igx-dialog #form_editindata
    title="Update Data"
    leftButtonLabel="Cancel"
    (onLeftButtonSelect)="form_data.close()"
    (onRightButtonSelect)="btn_submit()"
    rightButtonLabel="Update"
    [closeOnOutsideSelect]="true">
</igx-dialog>
```

But how to add 3rd button let me know

**Comment by zdrawku** [comment]
Hey @nikunjgajera, dialog actions are customizable throught `igxDialogActions` directive. [This sample](https://stackblitz.com/edit/dialog-actions-directive) shows how to configure it:

```
<igx-dialog #alert
    title="Notification"
    message="Your email has been sent successfully!"
    (onLeftButtonSelect)="alert.close()">
    <igx-dialog-actions>
        <div igxButton="raised">BUTTON 1</div>
        <div igxButton="raised">BUTTON 2</div>
        <div igxButton="raised">BUTTON 3</div>
    </igx-dialog-actions>
</igx-dialog>
```

Note: Keep in mind that both `leftButtonLabel` and `rightButtonLabel` should not be set.

**Comment by nikunjgajera** [comment]
thanks @zdrawku its working fine

**Comment by Eralmidia** [comment]
@zdrawku  I don't know if the dialog actions directive is very new? Just wanted to point out that this isn't mentioned in the dialog docs page.

**Comment by zdrawku** [comment]
You are correct :) The [PR updating our docs was merged yesterday](https://github.com/IgniteUI/igniteui-docfx/pull/1143/files#diff-b1908b5789510e24573633b0cba25cf8R131) and we plan the dialog topic to be promoted to production on friday, once this is done I will let you know. Thank you for your constant help toward improving our product and docs.

**Comment by Eralmidia** [comment]
Good to hear. Thank you for making a great product ;)
