### ISSUE TITLE
Implement Display Density for the IgxList

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#4393]
## Is your feature request related to a problem? Please describe.
We need to have a displayDensity input for the IgxList in order to be able to implement a displayDensity for the Excel Style Filtering dialog, which uses the IgxList (#4300).

## Describe the solution you'd like
IgxListComponent or IgxListBase should extend DisplayDensityBase.

## Describe alternatives you've considered
N/A

## Additional context

The **igx-list** will have a different css class based on the its **displayDensity** input value. The list items will be styled accordingly as well.

- [x] Tests
- [x] Development
- [x] README
- [x] Specification
- [x] Documentation
- [x] Samples

**Comment by rkaraivanov** [comment]
closed via #4401
