### ISSUE TITLE
Dynamic Multicolumn header

### ISSUE THREAD

**Issue by Dineshreddy73** [IgniteUI/igniteui-angular#4403]
Hi,

We are working with the remote data where we are getting the data dynamically and for that we need multi column header. So could you please help me out with the issue.

Thanks in Advance,
Dinesh.

**Comment by SlavUI** [comment]
@Dineshreddy73 Hi we already have multi column header for the data grid and it should work with remote data as well. You can check it here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/multi_column_headers.html

**Comment by kdinev** [comment]
@Dineshreddy73 Can you provide a sample of your code and tell us what's not working with your current setup and remote data?

**Comment by SlavUI** [comment]
@Dineshreddy73  Hi do you have any comments ?

**Comment by SaranyaDwarampudi** [comment]
Hello,In the above example you shared, the column headers e.g General Information and Company Name were created statically in the html page (i.e column names and number of columns are fixed). So i just wanted to know either we do the same thing dynamically ? (Column names and number of columns are not fixed every time we load the page and must be populated dynamically say from .ts file)

**Comment by kdinev** [comment]
@SaranyaDwarampudi Yes, as long as you have objects that describe your columns, you can `*ngFor` the `<igx-column>` definition and assign the configuration from your column objects.

**Comment by SaranyaDwarampudi** [comment]
@kdinev Can you please provide me an example ?

**Comment by nrobakova** [comment]
@SaranyaDwarampudi you can look at this sample. There the columns has field 'group' and base on it the columns are added to the columns groups dynamically:
https://stackblitz.com/edit/angular-wymx5x-4efpyd?file=src/app/grid/multi-column-headers/multi-column-headers.html

**Comment by SaranyaDwarampudi** [comment]
@nrobakova Thank you for the example. Our requirement is like,we will use 2 tables. So i am explaining you based on the example you have provided. First table will have only the columns names to populate the Group1,Group2,Group3 column names(names change every-time) and Second table is used used to populate the the column names like region and so on and its respective data. So from the second table(from region column) everything looks fine, but the groups must also be populated dynamically and the groups may also increase in some cases(Group1,Group2,Group3 in some cases and Group1,Group2,Group3,Group4).

**Comment by nrobakova** [comment]
@SaranyaDwarampudi can you send a small sample(set of data) for how tables looks like. In the sample the first grid(grid1) uses one list for column groups and one for the columns, so the column groups may increase.

**Comment by SaranyaDwarampudi** [comment]
[SampleData.xlsx](https://github.com/IgniteUI/igniteui-angular/files/3042020/SampleData.xlsx)
@nrobakova Please find the sample data. In relation to the example you have provided, the first table in the excel sheet is used to populate the columns (Group1,Group2,Group3) and the second table is used to populate the columns like region and its data.The third table in the excel sheet tells you how the table should look like.

**Comment by nrobakova** [comment]
@SaranyaDwarampudi  when you have the columns and groups you can always use the *ngFor to show them in the way that you want. I here is the updated sample and hope this will help you:
https://stackblitz.com/edit/angular-wymx5x-ec52ja?file=src/app/grid/multi-column-headers/multi-column-headers.html

**Comment by nrobakova** [comment]
@SaranyaDwarampudi does the sample help you to resolve your scenario? Can I close the issue

**Comment by SlavUI** [comment]
@SaranyaDwarampudi  closing this one reopen if needed
