### ISSUE TITLE
Bug - ExcelFilterStyle checkmark missing when you search for a filter

### ISSUE THREAD

**Issue by corganfuzz** [IgniteUI/igniteui-angular#4407]
## Description  
Describe the issue.

 * igniteui-angular version: 7.2.2
 * browser: Chrome

## Steps to reproduce 

Alright, It is my understanding the Excel Filtering Style is supposed to "mimic" the filtering used in excel. Ok let's take a look how excel fitltering work in the actual excel software. 

1. In regular excel, If I type SME I get the following: 

![bug1](https://user-images.githubusercontent.com/11259414/55046138-74bfc580-500e-11e9-9cf7-f6326993e89e.jpg)

Now as soon as I press **Enter** or the **OK** button I get:

![bug2](https://user-images.githubusercontent.com/11259414/55046195-acc70880-500e-11e9-872e-c53e62c9d50a.jpg)

which translates to:

_a **checkmark** to the 'SME' value and several **empty boxes** to the rest of the other values_

Basically, we have 2 cases:

**Case 1:**

if I type "SM" I get => a **checkmark** for all the values that start with SM Ex: SME, SMP, SMX, and empty boxes (without checkmarks) for the rest of the values BTM, BTR or whatever

**Case 2:**

if I type "SME" or a value that is inside my "filters" then the only **checkmark** I get is in the "SME" value and the rest get an empty box (**no checkmarks**).

**To get back to initial State:**

If you click on **Clear filter from Unit**, I should get back to the initial state, which _adds a checkmark to every single box next to the filters._ 

When you try to do the same in iginite-ui angular. 

If I type "SME" => if you either **press enter** or click on the **apply button**, nothing happens. which makes sense because the checkmark is still on every single filter. which makes sense, this is logical. However, this is different in how actual excel does it. 

**Solution**.

Infragistics needs to change how this particular search functionality works, here. It should be able to add a checkmark If I type the first letter of my filters and the response should add a checkmark to all the possible values that match my query criteria, the rest of the values should **not** get a checkmark. That way, whenever I click apply or press enter I should filter the grid correctly just like regular excel. To get back to initial state , then "Clear filter" will clear any selection I've typed in the beginning

**Comment by kdinev** [comment]
@corganfuzz The reasons why we didn't implement it like this are two:

1. This will perform filtering operations on each search resulting in event being fired every time you type and any additional UI bound to the filtered collection or to the filtering events would start responding to key strokes in the search. This can get very slow in a larger Angular application.
2. The behavior in excel is exactly how you describe it, but if we add one more step and want to filter by `SM` AND `SP`, then we cannot do it using the search. When we search `SM` the values starting with `SM` will get checked and all the rest unchecked. Then when we search for `SP` the `SP` values get checked, and the rest unchecked, including the values containing `SM`. 

The excel-'style' filter is very close in terms of UI and functionality to the filtering in excel, but is not 100% the same.

**Comment by corganfuzz** [comment]
Ok. Performance is a big deal , got it. Just wish there was an alternative

**Comment by kdinev** [comment]
@corganfuzz I know it's one more click to check the checkboxes, but at least they will persist their check state through a second search :)

**Comment by SlavUI** [comment]
@corganfuzz  closing this one :) re open if necessary :)
