### ISSUE TITLE
NavDrawer breaks server-side rendering

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#4426]
## Description  
I tried to build and app-shell that uses the nav-drawer in the app.component, and the build fails.

 * igniteui-angular version: 7.2.2
 * browser: N/A

## Steps to reproduce  

1. Create a default cli project with side-nav.
2. Add an app-shell and build.

## Result  
Build fails.

## Expected result  
Build should pass.

## Attachments  

> Hammer is not defined
> ReferenceError: Hammer is not defined
>     at new HammerGesturesManager (D:\GitHub\angular-training\node_modules\igniteui-angular\bundles\igniteui-angular.umd.js:67038:29)
>

**Comment by damyanpetev** [comment]
Will see if the drawer can fail with a warning instead without hammer.
Would love to point to https://github.com/angular/universal/issues/830, but that has workarounds assuming a[ full universal setup](https://angular.io/guide/universal) with access to server to patch stuff.

There is however a potential `isPlatformBrowser` check that looks promising in the meantime - disabling gestures on the drawer based on that might do the trick.

**Comment by zdrawku** [comment]
@damyanpetev @radomirchev, I am adding this in the current sprint as it was part of a customer question in relation to Angular Server Side Rendering of our components
