### ISSUE TITLE
Snackbar text cannot be styled

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#4429]
## Description  
I'm trying to modify the snackbar text and to center it relative to the icon displayed in the snackbar, but this doesn't seem possible.

 * igniteui-angular version: 7.2.2
 * browser: N/A

## Steps to reproduce  

1. Define a snackbar:
```html
<igx-snackbar #success [displayTime]="2000" message="Success...">
  <igx-icon class="color-success">done</igx-icon>
</igx-snackbar>
```

## Result  
The snackbar text is not centered relative to the icon.

## Expected result  
I should at least be able to modify the class of the text element, which currently there's no element wrapping the text. Another option would be to allow me to define the snackbar content so I can change the structure and apply whatever styles I want to it.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/55324853-f343b980-548b-11e9-87b4-97addfb9c832.png)

**Comment by gedinakova** [comment]
@kdinev Actually, we recently made a change that allows setting the message as content instead of using the "message" input (this is now the recommended approach), as shown below:

``` html
<igx-snackbar #success [displayTime]="2000">
     <div class="snackbar-content">
           Success...
           <igx-icon class="color-success">done</igx-icon>
    </div>
</igx-snackbar>
```
This approach should allow aligning the message and the icon properly.

**Comment by kdinev** [comment]
@gedinakova Thanks for the suggestion. I used your suggestion and it works perfectly.

```
<igx-snackbar #success [displayTime]="2000">
  <div class="snackbar-msg">
    <span>{{successMsg}}</span>
    <igx-icon class="color-success">done</igx-icon>
  </div>
</igx-snackbar>
```
