### ISSUE TITLE
New added row cannot be expanded by clicking on expand icon but it can using Alt+Arrow Right or Alt+ Arrow Down 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4431]
## Description  
New added row cannot be expanded by clicking on expand icon

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open dev sample hierarchicalGridUpdating
2. Click on button 'ADD PARENT ROW'
3. Scroll to the new added row
4. Click on its expand button

Note: When select a cell in this row and pres Alt+Arrow Right or Alt+ Arrow Down the row is expaned

## Result  
Row is not expanded

## Expected result  
Row should be expanded

**Comment by skrustev** [comment]
The button is correctly disabled, since the transaction is still not committed, but it neither should be able to be expanded using keyboard navigation.
