### ISSUE TITLE
Opening the Filtering dropdown twice in an igxHierarchicalGrid results in warning messages in the browser console

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4436]
## Description  
In igxHierarchicalGrid when the Filtering is enabled, clicking twice on the dropdown button results in warning messages being shown in the browser console on every scroll event. 

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run the dev demos and open http://localhost:4200/hierarchicalGrid
2. Click the filtering chip of the ID column
3. Click on the dropdown button in order to show the Filtering conditions
4. Click the button again - this would hide the dropdown and open it again
4. Scroll the grid vertically

## Result  
Every scroll event raises this warning message in the browser console: 
igxOverlay.hide was called with wrong id: 0

## Expected result  
No warnings should be shown in the console when scrolling.

## Attachments  
![Sketch3](https://user-images.githubusercontent.com/18643062/55398841-336d6f80-5552-11e9-8770-f49d233ee56c.png)

**Comment by lalo-mx** [comment]
The warning is similar to https://github.com/IgniteUI/igniteui-angular/issues/4222
