### ISSUE TITLE
Retained child grids post paging displace their vertical scrollbars

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#4445]
## Description  
Cached child grids will displace their vertical scrollbar after coming back in view through pagе size changes

 * igniteui-angular version: 7.2.x
 * browser: n/a

## Steps to reproduce  

1. Open the hierarchical grid sample in demos
2. Expand the third row
3. Change the page size to 5
4. Page the parent grid to 2nd and back to 1st page

## Result  
The vertical scrollbar of the child grid appears to the right of the previous right edge of the grid container

## Expected result  
The vertical scrollbar's position should not change

## Attachments  
![issue](https://user-images.githubusercontent.com/2188411/55486163-7dc71d00-5634-11e9-9d4b-6a511991e945.gif)

**Comment by MayaKirova** [comment]
This no longer reproduces in 7.2.x, 7.3.x, 8.0.x and master.
