### ISSUE TITLE
3rd level child does not scroll with keyboard nav

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#4447]
## Description  
3rd level child does not scroll when using keyboard navigation 

 * igniteui-angular version: 7.2.x
 * browser: n/a

## Steps to reproduce  

1. Open the hierarchical grid demos sample
2. Expand in depth to the 3rd child
3. Focus a cell on its first row
4. Press the down arrow to navigate it 

## Result  
Focus is lost and the child grid does not scroll

## Expected result  
The child grid to scroll down

***Note***: This is a regression from the MCS implementation and is not yet released

## Attachments  
![issue1](https://user-images.githubusercontent.com/2188411/55488258-612ce400-5638-11e9-891e-95cf9f7e6250.gif)

**Comment by MayaKirova** [comment]
Note: This can be reproduced in any grid that has only 1 record visible

**Comment by MayaKirova** [comment]
The reason this started reproducing in the hierarchical grid is the following issue - https://github.com/IgniteUI/igniteui-angular/issues/4458
Which causes the child grids that have filtering to have incorrect height.
