### ISSUE TITLE
IgxForOf - Default values for template

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#4453]
## Is your feature request related to a problem? Please describe.
Currently, the `igxForOfDirective` does not provide a drop-in replacement for Angular's `ngFor`. Though the functionality of the `igxForOfDirective` is vastly more complex, it would be nice if it were not up to the user to **initially** configure all of the props.

This is more of an ease-of-use feature, not a functionality improvement

### Current State
Currently, when using `igxForOf`, you have to specify a lot of configuration options in the template:
```
<div #myContainer>
   <div *igxFor="let item of data; index as index; scrollOrientation: 'vertical'; containerSize: 
   itemsMaxHeight; itemSize: itemHeight;">
        {{ item }}
   </div>
</div>
```
### Feature State
It would be convenient if the user could just specify the data and the directive would take care of the rest via default values for the missing props:
```
<div #myContainer>
    <div *igxFor="let item of data">
        {{ item }}
    </div>
</div>
```

## Describe the solution you'd like
Where possible, default values should be provided for the configuration options:
For example: 
 - `scrollOrientation`: default value 'vertical'.
 - `containerSize`: taken from the parent element (assuming the parent has a `height` or `width` for `vertical` or `horizontal`, resp.)
 - `itemSize`: calculated based on `(containerSize / default chunk size`)

Even with default the values, the values could still be manually passed and overwritten.

## Describe alternatives you've considered
Currently - none. The configuration options have to be passed in the definition, otherwise the virtual items do not render properly.

## Additional context
Curenlty, `totalItemCount` cannot be passed when using `*igxFor`. If possible, it should also be exposed for use in the above configuration for ease of use

**Comment by ChronosSF** [comment]
@radomirchev , do you agree with @ViktorSlavov 's proposals on the default values? Do we need to setup a meeting to discuss these?

**Comment by radomirchev** [comment]
@ChronosSF the proposal is to be discussed in a meeting.

**Comment by dkamburov** [comment]
We did a discussion on this issue and decided, that will do the scroll orientation to be vertical by default and will expose `igxForOfTotalItemCount`.
At this point we are not going to provide defaults for `containerSize` and `itemSize`, they should be defined by the developer.
