### ISSUE TITLE
When first tree grid column is with type date the calendar mode is not correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4457]
## Description  
When first tree grid column is with type date the calendar mode is not correct

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-1sbn8g?file=src/app/tree-grid-editing-sample/tree-grid-editing-sample.component.html
2. Open cell in column 'HireDate' in edit mode

## Result  
Calendar is opened as dialog 

## Expected result  
Calendar should be opened as dropdown, as when the column is not the first treeGrid column

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/55561540-00b2ab00-56fb-11e9-946a-ce0edd6f1ce0.png)

**Comment by zdrawku** [comment]
Closing this one, the fix is available in 7.2.x and master
