### ISSUE TITLE
When child grids have Filtering enabled, they get rendered with only a single row, which is almost entirely hidden

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4462]
## Description  
When Filtering has been enabled for the child grids, they get rendered with only a single row, which is hidden below the horizontal scrollbar. The issue does _not_ reproduce if Summaries have been enabled for the child grids as well. 

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run the igniteui-angular-samples repo
2. Open http://localhost:4200/samples/hierarchical-grid/hierarchical-grid-filtering
3. Expand the first row - Naomí Yepes

## Result  
The child grid has several rows, which are not rendered. In gets rendered with a single row instead, which is almost entirely hidden below the horizontal scrollbar. 

## Expected result  
All of the child rows should be visible.

## Attachments  

![childFiltering](https://user-images.githubusercontent.com/18643062/55572388-25fde400-5710-11e9-87ba-439eff605997.png)

![childFiltering2](https://user-images.githubusercontent.com/18643062/55572394-2a2a0180-5710-11e9-9a36-d393a7d8f996.png)

**Comment by kacheshmarova** [comment]
This issue is similar to issue #4458.
I tested the sample with Maya`s PR and it seems resolved.
