### ISSUE TITLE
If igxGrid has Filtering enabled and the rows get deleted, trying to navigate with Tab key after the last chip throws an error

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4463]
## Description  
When an igxGrid does not have any rows and Filtering has been enabled, trying to navigate through them with Tab key throws an error after the last chip.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run the igniteui-angular-samples
2. Open http://localhost:4200/samples/grid/grid-editing
3. Delete each row by clicking the icon on the right 
4. Click the last Filtering chip
5. Press Esc and close the filtering - the chip should still be focused
6. Press Tab key

## Result  
The following error gets thrown in the console: IgxGridHeaderGroupComponent.html:25 ERROR TypeError: Cannot read property 'virtDirRow' of undefined

## Expected result  
No errors should be thrown

## Attachments  

![Sketch](https://user-images.githubusercontent.com/18643062/55573113-dcae9400-5711-11e9-833c-55eaac31bb6f.png)

**Comment by nrobakova** [comment]
This bug was fixed when the bug #4537 was fixed.
The fix is included in the pr #4590
