### ISSUE TITLE
The vertical scroll bar is not rendered when the the grid height is set in %

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#4467]
## Description  
 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-zjebxa)
2. Observe the grid 

## Result  
The vertical scroll bar is not shown

## Expected result  
The vertical scroll bar should be shown

Note:
If you click to the next page the scroll bar will be shown

**Comment by VMihalkov** [comment]
@ddincheva, I was unable to reproduce the issue with version 7.2.16. Can you please try to reproduce it?

**Comment by ddincheva** [comment]
@VMihalkov yes .. this problem is no longer reproduced in the latest 7.2.x version :)
