### ISSUE TITLE
If hierarchical grid has height in %(or no height) and summary on the parent level then height is not calculated correctly

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#4468]
## Description  
Describe the issue.

 * 7.2.x 
 * N/A 

## Steps to reproduce  

1. Go to hierarchical-grid sample.
2. Remove the height setting of the first grid.

## Result  
Only one data record and the summary row are rendered.

![igx-Hrid](https://user-images.githubusercontent.com/13034836/55620709-32cc1780-57a4-11e9-97e9-545ad0dca041.png)

## Expected result  
Since height cannot be calculated it should use the defaultTargetBodyHeight which is the rowHeight*number records per page or 10 (if no paging is applied).

If the hasSummary='true' for "ProductName" column in the parent grid is removed the height is calculated correctly.

![igx-Hrid2](https://user-images.githubusercontent.com/13034836/55620827-96eedb80-57a4-11e9-94f9-a9ebe617ed1f.png)

**Comment by MayaKirova** [comment]
This no longer reproduces in 7.2.x, 7.3.x, but reproduces in 8.0.x and above.
