### ISSUE TITLE
When the page size changes, the hierarchical grid renders an empty placeholder in the place of the horizontal scrollbar

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4469]
## Description  
When the page size gets changed, the igxHierarchicalGrid renders an empty placeholder in the place where the horizontal scrollbar should be. The issue might be related to issue #4445 

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run the dev demos and open http://localhost:4201/hierarchicalGrid
2. Change the page size to 5
3. Change the page size to 15

## Result  
The hierarchical grid shows an empty placeholder in the place of the horizontal scrollbar

## Expected result  
There should be no placeholder or scrollbar

## Attachments  
![Sketch](https://user-images.githubusercontent.com/18643062/55622902-29de4480-57aa-11e9-8f30-55f1d9293369.png)

**Comment by VMihalkov** [comment]
@PavlovVasil, I was not able to reproduce the issue with version 7.2.x. Can you please try to reproduce it again?

**Comment by PavlovVasil** [comment]
@VMihalkov I cannot reproduce it either, it seems it has been fixed.
