### ISSUE TITLE
In IE parent grid scrolls when using ctr + right navigation.

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular#4488]
## Description  
Currently when using ctr + right for navigating to the last cell parent grid scrolls and child grid flips on IE.
 * igniteui-angular version: 7.2.x
 * browser: IE

## Steps to reproduce  

1. Open hierarchical grid dev sample on IE.
2. Select the first cell of the first child grid.
3. Use ctr + right for navigation.

## Result  
Child grid flips and parent grid scrolls down even though the cell is visible without scrolling.

## Expected result  
Grid should stay in same position without scrolling.

## Attachments  
![KeyboardNavIE](https://user-images.githubusercontent.com/13034836/55553660-744bbc80-56e9-11e9-9453-58b7ef9611ba.gif)

**Comment by VMihalkov** [comment]
The original issue seems to be fixed, but when using Ctrl + down there is some up/down moving. Here are the steps to reproduce:

1. Open hierarchical grid dev sample on IE.
2. Select the first cell of the first child grid.
3. Use ctr + down for navigation.

![CtrlDownKeysJumping](https://user-images.githubusercontent.com/12252163/60886064-b1c86480-a259-11e9-9363-e8cab5ac7b0a.gif)
