### ISSUE TITLE
InputGroup - Input value is misaligned in input-group with label

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#4490]
## Description  
When an input-group uses a `type` different than `"line"`, and has a label and a prefix/suffix, the value of the input field and the prefix are misaligned.
Removing the label seems to fix the issue

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Open the following [StackBlitz](https://stackblitz.com/edit/input-border-misalign?file=src%2Fapp%2Finput-group%2Finput-group-sample-6%2Finput-group-sample-6.component.html)

## Result  
The input and prefix are misaligned in all but the first input

## Expected result  
The input and prefix are properly aligned

**Comment by desig9stein** [comment]
@ViktorSlavov, since we don't know what kind of content you may have in your prefix/suffix we can't provide you the styling out of the box.
I suggest you add a class on your prefix/suffix and use that class to position the element.

You can do it like this: 

Markup
```
<igx-input-group type="box">
    <label for="phone" igxLabel>Phone</label>
    <igx-prefix class="ps-position">+359</igx-prefix>
    <input igxInput name="phone" [(ngModel)]="phoneNumber">
    <igx-suffix><igx-icon>phone</igx-icon></igx-suffix>
</igx-input-group>
```
style
```
.ps-position {
  align-self: flex-end;
  padding: 5px 5px 4px 0;
}
```

In my opinion, you can close the issue since this is not a bug!

**Comment by simeonoff** [comment]
@desig9stein I think the users can handle that case on their own as well.

**Comment by ViktorSlavov** [comment]
@desig9stein @simeonoff 
Thanks for the explanation! I assume that most of the times an icon will be used as prefix/suffix, but you are right that enforcing styles would interfere with the other use cases.
The example @desig9stein provided serves fine for a workaround, should anyone need it.
Marking this as "not-a-bug' and closing
