### ISSUE TITLE
Add 'always visible' functionality to thumb labels

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#4492]
## Is your feature request related to a problem? Please describe.
When the slider is initialized I cannot determine what is the defined range selection, I need to click on the slider in order to show the thumb labels.

## Describe the solution you'd like
I want to set thumb labels visibility with a property.

## Additional context
![image](https://user-images.githubusercontent.com/11193764/55777418-842c1d80-5aa8-11e9-8785-2181105746e6.png)

**Comment by StefanIvanov** [comment]
According to the [Material Design Guidelines](https://material.io/design/components/sliders.html#discrete-slider) the labels are visible only for a discrete slider upon hover, focus or pressed states. This feature request IMO diverges from what is prescribed by the Google Material team and we should drop it.

**Comment by StefanIvanov** [comment]
This is depicted a dev story in the [updated slider spec](https://github.com/IgniteUI/igniteui-angular/wiki/slider)

**Comment by DaniMarinov** [comment]
Link to the updated [Slider Spec](https://github.com/IgniteUI/igniteui-angular/wiki/Slider-Specification)

**Comment by Aleksandyr** [comment]
@StefanIvanov @DaniMarinov as far as I understood, the issue relates to the last applied changes regarding ticks and discreet slider. Can we consider it as done and close it?

**Comment by StefanIvanov** [comment]
It is related but at the same time, I am not sure that we have exactly what is requested in this issue in terms of a property for slider thumbs visibility. @zdrawku can say if his original goal when requesting the enhancement has been met with the updates made thereafter.

**Comment by zdrawku** [comment]
By the time this issue was logged we didn't have the `Ticks` functionality, which is vital when it comes to slider track values `visualization`. The requirement to have always visible thumbs no longer applies, as we now have both always visible ticks (with plenty of options for them) and [thumb label visibility duration](https://staging.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxslidercomponent.html#thumblabelvisibilityduration) when hovered.

Also, I agree with your initial [comment ](https://github.com/IgniteUI/igniteui-angular/issues/4492#issuecomment-481664392)based on the Material Design Guidelines
