### ISSUE TITLE
The text in the filter column textbox truncates in the igx-grid component

### ISSUE THREAD

**Issue by gbhojak** [IgniteUI/igniteui-angular#4496]
## Description  
In the igx-grid component, when the filtering for a column is enabled and some text is typed into the textbox, the text doesn't show up in the text box, but it does appear correctly in the tag, gith next to the textbox.

 * igniteui-angular version: 7.2.4
 * browser: Safari 12.x

## Steps to reproduce  

1. Added a igx-grid component with allowFiltering set to true.
2. Added a column with filterable set to true.
3. In Safari, click on the filter icon for the column and type some text.
4. The text in the textbox appears to be truncated, the text in the close-able tag is rendered properly.

## Result  
 The text in the textbox appears to be truncated, the text in the close-able tag is rendered properly.

## Expected result  
 The text in the textbox should be rendered properly.

## Attachments  
![Truncated](https://user-images.githubusercontent.com/29307397/55808944-0b7e8e80-5ab3-11e9-82f7-dd1da4a4be57.png)

**Comment by simeonoff** [comment]
@gbhojak There seems to be an issue with the default font face we use in Safari. For now changing the font-family to something else should resolve the issue. Can you confirm?

We will look into it and try to make it work with Titillium Web, too.
