### ISSUE TITLE
Grid layout is broken when we edit row and scroll vertically

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#4497]
## Description 

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Open row editing dev sample
2. Enter edit mode for the last visible row
3. Start scroll with the mouse 
 

## Result  
![image](https://user-images.githubusercontent.com/34240583/55805392-063b3700-5ae7-11e9-920b-def8b9b63ea5.png)

## Expected result  
Row Editing overlay should not be shown.

**Comment by zdrawku** [comment]
Non reproducible
