### ISSUE TITLE
igDatePicker dateOptions

### ISSUE THREAD

**Issue by michaelgroiser** [IgniteUI/igniteui-angular#45]
Hi,
Is there any documentation how to add datePickerOptions to igDatePicker, using Angular.for example i want to add Month and Year choose in the igDatePicker
Also i am trying to bind a click event to the igDatePicker button (the one that opens the calendar).

**Comment by damyanpetev** [comment]
Hello,
We keep a combined documentation that explains how options are handled, because it'd be quite redundant to go and write up for each control's options, considering they are handled the same way. The basic rules you can find on the readme:
https://github.com/IgniteUI/igniteui-angular#configuring-control-options
And there's a bit more detailed topics at:
http://www.igniteui.com/help/angularjs-directives
Since the [`datePickerOptions`](http://help.infragistics.com/jQuery/2015.2/ui.igdatepicker#options:datepickerOptions) are a nested object, you can provide a nested tag for the date picker (same dash naming applies) and assign attributes you want set. For example setting [`numberOfMonths`](http://api.jqueryui.com/datepicker/#option-numberOfMonths) looks like this:
```html
<ig-date-picker id="datePicker1" ng-model="editors.date">
    <datepicker-options number-of-months="2"></datepicker-options>
</ig-date-picker>
```
As for the events (see [Readme](https://github.com/IgniteUI/igniteui-angular#handling-events) and [topic](http://www.igniteui.com/help/using-ignite-ui-with-angularjs#events)), you can handle with scope functions by using event- prefixed attribute:
```html
<ig-date-picker class="form-control" id="datePicker1" ng-model="editors.date" 
    event-drop-down-list-opened="calendarEvent"
    event-drop-down-list-closed="calendarEvent"
    event-blur="calendarEvent">
</ig-date-picker>
```
Sample: http://jsfiddle.net/damyanpetev/nwxc6a9g/

**Comment by damyanpetev** [comment]
P.S. For completeness I should mention functions in nested options. Since it's not possible to pass reference with tag attributes, those can also be prefixed with `event-` where it makes sense or place those in curly braces to get them [evaluated in the scope](http://www.igniteui.com/help/using-ignite-ui-with-angularjs#options-evaluation):

```js
$scope.onChangeMonthYear = function (){}
```
```html
...
<datepicker-options 
event-on-change-month-year="onChangeMonthYear"
OR
on-change-month-year="{{onChangeMonthYear}}"></datepicker-options>
```
> Note: You can create options in the controller instead of declarative options.

**Comment by michaelgroiser** [comment]
thanks. i was able to add datepickerOptions and add ChangeYear and ChangeMonth. But trying to select Year/Month doesn't open the Select List. when i use IE it works. Doesn't work with Chrome

**Comment by damyanpetev** [comment]
Thank you for reporting this. I believe you might have stumbled upon a known issue with the widget itself, that we already have resolved internally. There should be a scheduled bi-weekly build next week, but in case this is something urgent preventing your work from moving forward I can think of a quick workaround:
http://jsfiddle.net/damyanpetev/nwxc6a9g/5/
The handling on this event is not intended to do anything at the moment, but I'd still suggest deleting the rendered event after an update is available.

**Comment by michaelgroiser** [comment]
it is still the same . I define datepicker this way-
<ig-date-picker class="form-control datepick"  event-drop-down-list-opened="calendarEvent" event-drop-down-list-closed="calendarEvent" event-blur="calendarEvent" event-rendered="pickerRendered" id="startDate" ng-model="Filter.startDate">
                                <datepicker-options max-date="d" select-other-months="true" show-other-months="true" change-year="true" show-week="true" change-month="true" week-header="WW"></datepicker-options>
                            </ig-date-picker>

those are my includes and jquery versions:
<link src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" />

<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://code.angularjs.org/1.2.20/angular.js" data-semver="1.2.20"></script>
<script src="http://angular-ui.github.io/ui-router/release/angular-ui-router.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap-tpls.min.js"></script>


<link href="Lib/infragistics.theme.css" rel="stylesheet" />
<link href="Lib/infragistics.css" rel="stylesheet" />

<link href="http://www.igniteui.com/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
<link href="CSS/StyleSheet.css" rel="stylesheet" />
<link href="CSS/app.css" rel="stylesheet" />



<script type="text/javascript" src="JS/app.js"></script>
<script type="text/javascript" src="JS/angularInit.js"></script>
<script type="text/javascript" src="Controllers/aboutController.js"></script>
<script type="text/javascript" src="Services/frameLinksService.js"></script>
<script type="text/javascript" src="Services/LabsSitesService.js"></script>
<script type="text/javascript" src="Services/WebServices.js"></script>
<script type="text/javascript" src="Services/igServices.js"></script>
<script type="text/javascript" src="Controllers/genericFrameController.js"></script>
<script type="text/javascript" src="Controllers/DashboardController.js"></script>
<script type="text/javascript" src="Controllers/moveMoleJobController.js"></script>
<script type="text/javascript" src="Controllers/ShiftReportController.js"></script>
<script type="text/javascript" src="Controllers/RawDataReportController.js"></script>

<script type="text/javascript" src="http://www.igniteui.com/js/external/FileSaver.js"></script>
<script type="text/javascript" src="http://www.igniteui.com/js/external/Blob.js"></script>
<script type="text/javascript" src="Lib/infragistics.loader.js"></script>
<script type="text/javascript" src="Lib/infragistics.core.js"></script>
<script type="text/javascript" src="Lib/infragistics.lob.js"></script>
<script type="text/javascript" src="Lib/igniteui-angular.js"></script>
<script type="text/javascript" src="Lib/infragistics.documents.core.js"></script>
<script type="text/javascript" src="Lib/infragistics.excel.js"></script>
<script type="text/javascript" src="Lib/infragistics.gridexcelexporter.js"></script>

<script type="text/javascript" src="JS/angularRoute.js"></script>

**Comment by michaelgroiser** [comment]
still the same. can't open Year / Month Chooser. 
Those are my datepicker-options

                                <datepicker-options max-date="d" select-other-months="true" show-other-months="true" change-year="true" show-week="true" change-month="true" week-header="WW"></datepicker-options>

and this is my datepicker-
< class="form-control datepick"  event-drop-down-list-opened="calendarEvent" event-drop-down-list-closed="calendarEvent" event-blur="calendarEvent" event-rendered="pickerRendered" id="startDate" ng-model="Filter.startDate">

**Comment by michaelgroiser** [comment]
thanks. but now when i try to open the year chooser, it opens for a moment and immediately the datepicker is closed (calendar as well)

**Comment by damyanpetev** [comment]
Any chance you can provide a small sample (feel free to modify the fiddle from above) that I can take a look at?

**Comment by mpavlinov** [comment]
This issue is outdated.
