### ISSUE TITLE
Button text (igx-button) is tiny, much smaller than previous Ignite UI version

### ISSUE THREAD

**Issue by jdk339** [IgniteUI/igniteui-angular#4527]
## Description  
I upgraded `igniteui-angular` from `7.1.7` to `7.2.4` and now the buttons appear much smaller than they used to.

Code:

```
<button class="full-width rounded" igxButton="raised" igxButtonColor="white" igxButtonBackground="#003086" igxRipple="gray" (click)="priceStructureFilter.open()">
  LOAD PRICE STRUCTURES
</button>
```

Old:
![image](https://user-images.githubusercontent.com/16578448/55966146-deaeb080-5c45-11e9-9c0f-20076f85d725.png)

New:
![image](https://user-images.githubusercontent.com/16578448/55966099-cb9be080-5c45-11e9-85b6-89ff19fe024b.png)

---- EDIT ----

It also appears the nav drawer's styles are not as good as they used to be:

Old: 
![image](https://user-images.githubusercontent.com/16578448/55968180-837ebd00-5c49-11e9-8ea0-b77ebcffbd8c.png)

New:
![image](https://user-images.githubusercontent.com/16578448/55968162-782b9180-5c49-11e9-8c88-4ab65afa6527.png)

In my opinion, the old version looks 10x better and I am curious if there is a bug that is causing this or an easy fix. Also, I should mention that the buttons are appearing as much smaller than what shows up on the official website, so I imagine it might have something to do with my specific setup.

 * igniteui-angular version: 7.2.4
 * browser: Google Chrome 73.0.3683.86

## Steps to reproduce  

1. Upgrade `igniteui-angular` to `7.2.4`
1. Use a igx-button

## Result  
Button with very small text

## Expected result  
Button with normally-sized text

**Comment by simeonoff** [comment]
@jdk339 I am not sure why the button text in 7.1.7 is so big in your example. The default button font-size (0.875rem or 14px for a base global font-size of 16px) doesn't not match with what I'm seeing in your screenshot.

That being said, you can always change the typography of the button using the [igx-button-typography](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#mixin-igx-button-typography) mixin to adjust the button typography the way you want it to look.

As to the navigation drawer, we have updated it to match the look in the [new material spec](https://material.io/design/components/navigation-drawer.html#).

**Comment by jdk339** [comment]
I am not familiar with mixins. How would I change the button font size globally to 16px?

**Comment by jdk339** [comment]
I was able to fix it myself by looking at the first StackBlitz sample in the button docs.

I just added `<body class="igx-typography">` to my body and now it looks much better.

**Comment by zdrawku** [comment]
@jdk339 I believe you will find [this topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/typography.html#usage) interesting. We do not apply any `typography` styles by default. To use our `typography` in your application you have to set the `igx-typography` CSS class on a top level element, as you already did
