### ISSUE TITLE
Wrong label position for input with type "Border"

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#4535]
## Description  
According material.io the labels for input types "border" must not be inside the input, they should be at the middle of the border. 

You may see material-component implementation [here](https://material-components.github.io/material-components-web-catalog/#/component/select) (see the outlined demo).

 * igniteui-angular version: ^7.2.4
 * browser: Chrome

## Steps to reproduce  

1. Open your demo [here](https://stackblitz.com/angular/keropxgornk)
2. Go to the input named with "Border Type" and write some value...

## Result  
The label is moved at position -50% and scaled to 75%, like this:
![image](https://user-images.githubusercontent.com/29953012/56055992-92846e80-5d20-11e9-9cd4-985f0acb1ad6.png)

## Expected result  
Label should be positioned at the middle of the border like this:
![image](https://user-images.githubusercontent.com/29953012/56056493-f491a380-5d21-11e9-826e-855f40d50b5b.png)

**Comment by StefanIvanov** [comment]
Hi @luiscla27 we are aware of this inconsistency with material.io and have looked for some viable ways to improve our implementation and match the guidelines, but there isn't a clean way to do so at the moment. We are keeping this in the backlog and will also keep you updated once we come up with a solution that will work well with our architecture and theming.

**Comment by luiscla27** [comment]
Thank you @StefanIvanov, i'll wait for your feedback, by now i've fixed this at my project by adding the following styling to style.scss,

```
.igx-input-group--border {
  &.igx-input-group {
    &--filled .igx-input-group__label,
    &--focused .igx-input-group__label {
      transform: translateY(-130%) scale(0.75)!important;
      background: #fff!important;
      width: auto!important;
      padding: 0px 5px!important;
    }
    &--filled .igx-input-group__input,
    &--focused .igx-input-group__input {
      transform: translateY(-25%)!important;
    }
  }
}
```

Here's the working sample: https://stackblitz.com/edit/angular-6zescz

**Comment by simeonoff** [comment]
@luiscla27 yeah, this is a nice workaround, however, we can't implement it this way, since we don't know what the surrounding background will be. In your case you know it and it's easy, but we gotta ensure our solution works for each background.

We can implement the specification, no doubt, but it will require a fundamental refactoring of our input-group template. We can plan the refactoring for a later version, but it's not our main focus for now.

**Comment by luiscla27** [comment]
There's no hurry! good thing that you'r considering to refactor your input-group template.
