### ISSUE TITLE
igx-slider update to match latest material guidelines

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#4542]
## Is your feature request related to a problem? Please describe.
The current implementation and style of the igx-slider is not up to date with the latest [material guidelines](https://material.io/design/components/sliders.html#discrete-slider) for a slider component

## Describe the solution you'd like
Update spec and igx-slider to support ripple, new label balloon shape, behaviors that match the different states in the material guidelines.

**Comment by DaniMarinov** [comment]
The spec and designs are updated https://github.com/IgniteUI/igniteui-angular/wiki/Slider-Specification . The feature is in progress now.
