### ISSUE TITLE
In Edge when collapse the last group row cannot continue navigation with keyboard

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4543]
## Description  
In Edge when collapse the last group row cannot continue navigation with keyboard

 * igniteui-angular version: 7.2
 * browser: Edge

## Steps to reproduce  

1. Open dev sample gridColumnMoving in Edge
2. Group by a column
3. Scroll to the bottom and click on the last group row to select it
4. Press Alt+Arrow Left key to collapse the row
5. Press Alt + Arrow Right to expand the row

Note: This bug is similar to bug #2796 , but appears only in Edge

## Result  
Row is not expanded and cannot continue with key board navigation

## Expected result  
Row should be expanded

**Comment by ddincheva** [comment]
This issue is produced as a result of the fix for  #3601 , also when perform collapse and the grid is scrolled to bottom scroll event is rised twice because of the fix for issue #3409.
