### ISSUE TITLE
Calendar locale not working under firefox mobile

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-angular#456]
### Description  
The date localization strings are not being formatted properly under FireFox mobile (tested under Android 5.0)

### Steps to reproduce  
Open the JS Blocks igx-calendar with FireFox mobile

### Result  
The dates are not formatted.

### Expected result  
Calendar to display dates formatted as in Chrome.

### Attachments  
![image](https://user-images.githubusercontent.com/22883855/29614031-45a989be-8811-11e7-91d4-c46e777f8492.png)

**Comment by rkaraivanov** [comment]
Cannot reproduce on the latest versions of Firefox for Android.
