### ISSUE TITLE
[igx-grid] some cells are not rendered when resizing window.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4568]
## Description  
Some cells are not rendered when resizing window.

 * igniteui-angular version: 7.2.5
 * browser: N/A

## Steps to reproduce  

1. Make browser window size down.
2. Run the attached sample.
3. Vertical scroll down to the middle.
4. Horizontal scroll right to the middle.
5. Click maximize button of the browser.

## Result  
Some cells are not rendered.

### Before maximizing
![before](https://user-images.githubusercontent.com/15909409/56258134-7a8a6180-6109-11e9-9046-7a63d288b3f3.PNG)

### After maximizing
![after](https://user-images.githubusercontent.com/15909409/56258199-aad20000-6109-11e9-966a-7adf8d423743.jpg)

## Expected result  
Cells should be rendered.

## Attachments  
[igx-grid-rendering-cell-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/3087742/igx-grid-rendering-cell-issue.zip)

**Comment by zdrawku** [comment]
@mpavlinov and @ChronosSF we've spend some time to identify and fix the issue, although a possible fix was not found. It looks there is a problem with the virtual for, @nrobakova could share more information here.
