### ISSUE TITLE
Add tics to <igx-slider> control

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#4594]
## Question  
How do I add tics (tic marks) to an <igx-slider> ?

I am using an <igx-slider> control to allow a user to select a time range.
Yesterday, Last 3 days, Last 7 days

I would like to add 3 tics to the <igx-slider> control, one tic for each possible time range selection.

 * igniteui-angular version:  7.2.4

 * browser: Google Chrome 73.0.3683.103

**Comment by zdrawku** [comment]
Hi @brookhutchinson, I am going to mark your question as `Feature request`. Using of `tick marks` is something that we definetely plan to add to the slider, although for now I can only suggest you to achieve this functionality on application level. Check out [this sample](https://stackblitz.com/edit/angular-slider-with-ticks) 

Result:
![image](https://user-images.githubusercontent.com/11193764/56408427-1a1c3100-627d-11e9-9a32-06c139110af6.png)

As for the custom select range (Yesterday, Last 3 days, Last 7 days), this is a feature that we are currently working on, you can see the [progress of the development here](https://github.com/IgniteUI/igniteui-angular/pull/4540).

Related to [Feature request](https://github.com/IgniteUI/igniteui-angular/issues/3449) with the [following specification](https://github.com/IgniteUI/igniteui-angular/wiki/igxSlider-Specification#developer).

Let me know if there is sometihing else that you want to add here or discuss with us.

**Comment by SlavUI** [comment]
@StefanIvanov can you comment here based on our discussion on this yesterday :)

**Comment by StefanIvanov** [comment]
@DaniMarinov is handling the slider so I would delegate to him rather than being a proxy for information. He will share the spec once we merge all requirements in one place.

**Comment by DaniMarinov** [comment]
Hi @brookhutchinson you can find the UX solution here https://github.com/IgniteUI/igniteui-angular/wiki/Slider . Let me know whether the Discrete variation of the slider is what you need.
