### ISSUE TITLE
Navigating up from parent to child grid doesn't happen if child is not visible on IE.

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular#4600]
## Description  
Navigating up in Hierarchical grid from parent to child grid doesn't happen if child is not visible on IE.

 * igniteui-angular version: 7.2.x
 * browser: IE

## Steps to reproduce  

1. Open hierarchical grid dev sample on IE.
2. Expand first row.
3. Select cell from the second row of parent.
4. Try navigating using arrowUp.

## Result  
Focused cell doesn't change.

## Expected result  
Navigation should happen.

## Attachments  
![navigation5](https://user-images.githubusercontent.com/24592428/56420036-156b7300-62a5-11e9-8498-9fe63c3bbeca.gif)

**Comment by MayaKirova** [comment]
This no longer reproduces in 7.2.x, 7.3.x, 8.0.x and master.
