### ISSUE TITLE
Is the typedoc theme free for bussiness application?

### ISSUE THREAD

**Issue by experdot** [IgniteUI/igniteui-angular#4609]
## Question  
The typedoc theme is great and useful. Is it possible to be under `MIT` license?

**Comment by kdinev** [comment]
@experdot We have had plans, for a while now, to separate the typedoc and sassdoc themes in a separate repository and to create packages with them. Your request will most probably speed this process up. 

Meanwhile we can add a temporary license file at their current locations inside this repo. @simeonoff

**Comment by kdinev** [comment]
@simeonoff Could you cherry-pick this for master as well? I will close the issue afterwards as done.
