### ISSUE TITLE
[igx-grid] Question about resizing behavioral change after v7.2.1.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4610]
## Question  
I have a question about resizing behavioral change after v7.2.1.

 * igniteui-angular version: 7.2.0 <-> 7.2.1
 * browser: N/A

### Until v7.2.0:
- `drag-to-resize`: We can start resizing by dragging the edge of column headers.

https://stackblitz.com/edit/igx-grid-resizing-behavior-720

### After v7.2.1
- `drag-to-resize`
- `click-to-resize`: Now we can also start resizing by click the edge of column headers.

https://stackblitz.com/edit/igx-grid-resizing-behavior-721

I think `click-to-resize` is very convenient but is this an intended change? Let me confirm this just in case(I can't find any information from release note or changelog).

**Comment by SAndreeva** [comment]
@tkiryu, this is not an intended change, I will mark the issue as a bug and take care of fixing it.

**Comment by tkiryu** [comment]
@SAndreeva , thank you for reviewing! Let me share one more thing with you.

When I right-clicked a resize handler, the following error was thrown.
>Error: Cannot read property 'resizer' of undefined
![image](https://user-images.githubusercontent.com/15909409/56554855-0995ee80-65ce-11e9-95ee-df973c655eff.png)

There was no problem with 7.2.0. Could your take care of it together?

**Comment by SAndreeva** [comment]
Thanks @tkiryu! I will take care and fix this as well.
