### ISSUE TITLE
Igx-date-picker's "Today" and "Cancel" buttons is not visible if mode is set to "dropdown".

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#4634]
## Description  
When using the Igx-date-picker in regular mode (dialog) the "cancel" and "today" buttons are visible if cancelButtonLabel and todaybuttonLabel inputs are specified. Unfortunately, the buttons are not displayed if Igx-date-picker's input "mode" is set to "dropdown". 

 * igniteui-angular version: 7.2.6
 * browser: Chrome

## Steps to reproduce  

Follow the stackblitz link below to run the code snippet:
https://stackblitz.com/edit/angular-n8xk1l?file=src/app/scheduling/datepicker/datepicker-sample-7/datepicker-sample-7.component.html

## Result  
Cancel and Today buttons are not displayed

## Expected result  
Cancel and Today button should be displayed at the bottom of the dropdown menu.

**Comment by zdrawku** [comment]
Hello @VirtualisProject, this is the expected behavior of `drop down` mode. Configuring the 'Today' and 'Cancel' buttons is applicable only when the date picker is in [dialog mode.](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date_picker.html#adding-buttons).
