### ISSUE TITLE
[igx-grid][IE11] filtering problems with IME mode.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4636]
## Description  
When typing with IME mode in the filter textbox, some problems with filtering happens on IE11.

 * igniteui-angular version: 7.2.6
 * browser: IE11

## Steps to reproduce  

1. Run the attached sample on IE11.
2. Click a filter chip on the column "1".
3. Focus in the filter textbox.
4. Enable IME.
3. Type "ha" quickly, which is coverted to "は", in the filter textbox.
4. Type "hi" quickly, which is coverted to "ひ",  in the filter textbox.
5. Type "fu" quickly, which is coverted to "ふ",  in the filter textbox.
  

## Result  
There are two problems.

1. The result of filtering is not correct. Because "hahifu" is converted to "はひふ" and matches one row.
2. Filtering chip text is not updated correctly. (You can reproduce it on [online sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html) as well)
    - textbox: "は"  <-> chip text: "ｈ"
    - textbox: "はひ"  <-> chip text: "はｈ"
    - textbox: "はひふ"  <-> chip text: "はひｆ"

![issue](https://user-images.githubusercontent.com/15909409/56626764-06f2d200-667e-11e9-8407-daab109ff416.gif)

## Expected result  
1. The result of filtering should be one row.
2. Filtering chip text should updated correctly.
    - textbox: "は"  <-> chip text: "は"
    - textbox: "はひ"  <-> chip text: "はひ"
    - textbox: "はひふ"  <-> chip text: "はひふ"

In fact, when typing slowly, the problems don't happen.

![expected result](https://user-images.githubusercontent.com/15909409/56626881-7ec0fc80-667e-11e9-95ba-902b6e3da902.gif)

## Attachments  
[igx-grid-filtering-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/3110215/igx-grid-filtering-issue.zip)

**Comment by gedinakova** [comment]
@tkiryu Tatsushi, can you, please, test one of the pull requests and confirm the issue is gone, because I wasn't able to very stably reproduce it at my end even before the fix, so I will appreciate it if you can double  check the fix for me?

**Comment by tkiryu** [comment]
@gedinakova , OK, I will do that!

**Comment by tkiryu** [comment]
@gedinakova , I tested it. The fix in itself seemed to work well for this issue.

By the way, when I close the filtering row, an error happened.
Here is a stacktrace.
>"Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
   at debugUpdateDirectives (http://localhost:4200/vendor.js:65903:9)
   at checkAndUpdateView (http://localhost:4200/vendor.js:65302:5)
   at callWithDebugContext (http://localhost:4200/vendor.js:66172:9)
   at debugCheckAndUpdateView (http://localhost:4200/vendor.js:65874:5)
   at ViewRef_.prototype.detectChanges (http://localhost:4200/vendor.js:63683:13)
   at Anonymous function (http://localhost:4200/vendor.js:139161:13)
   at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:3113:13)
   at onInvokeTask (http://localhost:4200/vendor.js:59285:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:3113:13)
   at Zone.prototype.runTask (http://localhost:4200/polyfills.js:2886:21)"

![error-when-closing-filtering-row](https://user-images.githubusercontent.com/15909409/57605460-a500fa80-75a1-11e9-9b17-8ab15343cc64.gif)

I'll log it as an another issue. If you know anything about it, please let me know.

 Anyway, I think the fix is OK!. Thanks!

**Comment by tkiryu** [comment]
@gedinakova , FYI, #4764
