### ISSUE TITLE
List items are shifted down on search if the list was scrolled down beforehand.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#4645]
## Description  
If a search is performed after the list of checkboxes has been scrolled down, the whole list of matches is shifted down.

 * igniteui-angular version: 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Run Dev demos
2. Navigate to Grid Column Moving demo
3. Open filter drop-down on 'ContactTitle' column
4. Scroll the list of checkboxes to the middle
5. Enter 'sale' in 'Search' input

## Result  
The list items are shifted down. Not reproduced in 7.2.

## Expected result  
The matching list items should start at the top.

## Attachments  
![image](https://user-images.githubusercontent.com/16817847/56662684-3a992080-66ad-11e9-8d63-422775401397.png)

**Comment by tachojelev** [comment]
The issue seems to be related to the igxFor directive when the filtered-in items should fully fit the display container (#4719). (currently reproduced both on **7.2.x** and **7.3.x**)
We will introduce a workaround for this current issue and will adjust it again once #4719 is resolved.
