### ISSUE TITLE
When using an igxGrid with MRL, sorting a column several times changes the vertical scrollbar size

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4652]
## Description  
Sorting a column in an igxGrid with MRL changes the vertical scrollbar size.
 * igniteui-angular version: 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample with the latest master
2. Open http://localhost:4200/
3. Click "Fax" column several times in order to sort it in an ascending and descending order.

## Result  
The vertical scrollbar changes its size each time the "Fax" column gets sorted

## Expected result  
The vertical scrollbar should not change its size when a column gets sorted

## Attachments  

[igxGridMRLSorting.zip](https://github.com/IgniteUI/igniteui-angular/files/3115565/igxGridMRLSorting.zip)

![vScrollSize](https://user-images.githubusercontent.com/18643062/56715926-af1d9f00-6741-11e9-8351-37623d85f093.gif)

**Comment by skrustev** [comment]
This seems to be already fixed in the latest 7.3.x branch.

**Comment by PavlovVasil** [comment]
@skrustev It has been fixed, indeed.
