### ISSUE TITLE
igx-tree-grid when no data in grid pagination shows wrong

### ISSUE THREAD

**Issue by prabakaran1311** [IgniteUI/igniteui-angular#4666]
## Description  
i am using angular igx-tree-grid for my application. when there is no data in grid pagination shows wrong. showing 1 of  0 in grid. 
i need to completely remove pagination when there is no data in grid

 * igniteui-angular version: 7.2.4
 * browser: all browser

## Result  
when there is no data grid shows  1 of 0 pagination(wrong)
## Expected result  
when there is no data in grid i want to remove pagination completely
![gridd](https://user-images.githubusercontent.com/18000286/56911187-f7361c00-6ac9-11e9-8c36-1579371a917c.PNG)

**Comment by SlavUI** [comment]
@zdrawku as i remember this is a general issue for the Grid

**Comment by prabakaran1311** [comment]
@SlavUI thank you. let me know when it will be fixed

**Comment by prabakaran1311** [comment]
@SlavUI i am need for this bug let me know when it will be fixed and when it will be relesed. thanks

**Comment by SlavUI** [comment]
@prabakaran1311  When we plan it I will let you know :)

**Comment by gedinakova** [comment]
@SlavUI @StefanIvanov How do we want to fix this issue? Should we hide the paginator or rather show page 1 of 1?

**Comment by StefanIvanov** [comment]
Since there is absolutely no data in the grid, I believe that hiding the paginator is a much better approach and solution.

**Comment by zdrawku** [comment]
Consider also the case when filtering is applied, and no data is returned, related issue https://github.com/IgniteUI/igniteui-angular/issues/485
