### ISSUE TITLE
Expanded row island grid does not update when data is changed

### ISSUE THREAD

**Issue by ammritt** [IgniteUI/igniteui-angular#4668]
## Question  
In the stackblitz example below, I am updating the data for the grid with code and resupply but the row island grid doesn't update.

https://stackblitz.com/edit/angular-vyzefw

Steps to reproduce:
1. Expand the first row for Artist 'Naomí Yepes'
2. First Album Name should be 'Initiation' and Debut year is '2011'
3. Click Update Data button on top.
4. Debut year will change to 2012 but data inside the rowIsland grid doesn't update.

How can I update this grid to show the right data.
 
 * igniteui-angular version: 7.2.6
 * browser: Google chrome  74.0.372

**Comment by dkamburov** [comment]
Invoking `markForCheck()` for the the root grid is not going down through the children and invoke `markForCheck()` for them. So you have to do it manually. You can use [onGridCreated ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxrowislandcomponent.html#ongridcreated) event emitter to store all of the grids that were created. And invoke markForCheck once you've made a change into their data.
Here's the modified stackblitz - https://stackblitz.com/edit/angular-vyzefw-93dqgf

**Comment by dkamburov** [comment]
If there are any additional questions on this, please re-open it.
