### ISSUE TITLE
Grid remains in pending state after commiting row edit w/o changes

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#4680]
## Description  
Grid w/ `[rowEditable]="true"` remains in pending transaction state (even when no transaction are enabled) after a commit row editing w/o making changes.

 * igniteui-angular version: 7.2.x, 7.3.x
 * browser: N/A

## Steps to reproduce  

Open the devSample for **Grid Row Editing**.
Under the first grid (*Row Editing w/o Transactions): 
1. Enter row editing on the first row and make a change (without exiting)
2. Click on the **Delete** button on another row - that row is properly deleted
3. Enter row editing on the first row and **make no change** (do not exit)
4. Click on the **Delete** button on another row

## Result  
The row **is not** deleted and stays in a pending deleted state

## Expected result  
The row is deleted

## Attachments  
**Invalid state**:
![image](https://user-images.githubusercontent.com/24314672/57135910-b3862f80-6db3-11e9-81ad-45630970e58c.png)

**Comment by jdk339** [comment]
Curious if this will also fix the issue where values changed in custom `ng-template`s **will not** trigger a changed row value.

[In the StackBlitz sample for the documentation's "Grid Row Editing" page](https://stackblitz.com/angular/gagpbalpqoe), here is the result after changing a row's `UnitsInStock` value:

`{rowID: 1, oldValue: {…}, newValue: null, cancel: false…}`

The expected result would be:

`{rowID: 1, oldValue: {…}, newValue: {...}, cancel: false…}`

If this is too unrelated to this issue (#4680), then I can create another issue. It's an extremely important feature for our company, so please fix quickly.

**Comment by wnvko** [comment]
@jdk339 this fix is not related to the issue you are facing. Actually the issue you are facing is related to the wrong binding in the sample. I logged this sample issue [here](https://github.com/IgniteUI/igniteui-angular-samples/issues/1137). To fix this at your side bind to `cell.editValue` instead of to `cell.value`.

**Comment by jdk339** [comment]
Thanks again, @wnvko. Everything is working fine now.
