### ISSUE TITLE
Row dragging styling issues

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4681]
## Description  
Describe the issue.

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. In all the browsers when filter row is opened the the and start scroll horizontal the column headers are over the drag header:
![image](https://user-images.githubusercontent.com/11463104/57135707-0ca19380-6db3-11e9-82aa-ecb0d46558df.png)

2. In all the browsers: When move a column the move indicator is over the drag header:
![image](https://user-images.githubusercontent.com/11463104/57136385-58553c80-6db5-11e9-9145-c9ec87b74e16.png)

3. In all browsers there is not border between dgard header and column headers:
![image](https://user-images.githubusercontent.com/11463104/57136633-0fea4e80-6db6-11e9-9c49-196d3b2988c3.png)

4. In Edge when a cell is opened in edit mode and start scroll horizontal the border is visible
![image](https://user-images.githubusercontent.com/11463104/57135818-6904b300-6db3-11e9-9c22-cd7675fb13f1.png)

5. In IE11 when start dragging the drag style is not applied
![image](https://user-images.githubusercontent.com/11463104/57135888-9a7d7e80-6db3-11e9-9e77-973322f8122f.png)

6. In IE11 when group by a column the drag indicator is not fully visible
![image](https://user-images.githubusercontent.com/11463104/57136027-28596980-6db4-11e9-8862-5b826323848d.png)

7. In all browsers: When there is a pinned column and the grid is scrolled horizontal in the drag row content of pinned cells is over the content of other cells:
![image](https://user-images.githubusercontent.com/11463104/57138101-6bb6d680-6dba-11e9-8d75-544354f8a226.png)

## Result  
Styling is not correct

## Expected result  
Styling should be correct

**Comment by dafo** [comment]
PR #4693 targets issues: 1,2 and 7.

**Comment by dafo** [comment]
@desig9stein will look into issue 4: "In Edge when a cell is opened in edit mode and start scroll horizontal the border is visible"

**Comment by desig9stein** [comment]
For **number 4** at first, I was thinking that the transparent border of the row is causing the issue but it appears that this is not the problem. After some observation, I notice that the rendering is not consistent, sometimes the border leaks on top of the row sometimes on the bottom and sometimes it doesn't'. I think that this is a third-party issue.

**Comment by Lipata** [comment]
I've logged a separate [issue](https://github.com/IgniteUI/igniteui-angular/issues/4729) for 3, in order to choose the most appropriate UX. 5 is not reproducible anymore.

**Comment by desig9stein** [comment]
I fix issue 6 in [this commit](https://github.com/IgniteUI/igniteui-angular/commit/c61d623320f87ca4029e0021f26f870c0cf8b1ff)

**Comment by Lipata** [comment]
Thanks to @desig9stein #6 is resolved - closing the issue.
