### ISSUE TITLE
Date picker drop-down opening behavior is inconsistent in igx-grid in Edge

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#4685]
## Description  
There is a small issue in Edge only - when the edited date cell is in the bottom - first click on the calendar icon opens the drop down above and the second click - below the edit field.

Related to #4526

 * igniteui-angular version: NA
 * browser: Edge

## Steps to reproduce  
1. Run Dev demos and open Grid Column Moving sample
2. Edit some date field at the bottom of the grid
3. Click twice on the calendar icon

## Result  
On the second click- drop-down opens below the editor field not above

## Expected result  
On opening - drop-down to appear correctly 

## Attachments  
![datePicker_test](https://user-images.githubusercontent.com/11226391/57137881-d1569300-6db9-11e9-97ff-49880ec45b34.gif)

**Comment by wnvko** [comment]
This was fixed in #4599
