### ISSUE TITLE
IgxDropDown requires overlay in constructor

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#4691]
## Description  
The IgxDropDownComponent constructor accepts overlay as an optional parameter. If something else is provided in place of the overlay, the build will fail.
In the current case, this is cause the igniteui-angular-samples build to fail.

This is a leftover from IgxDropDown - virtual PR and should be removed.

 * igniteui-angular version: 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Clone the igniteui-angular-sample repo
2. npm i && npm i igniteui-angular@7.3.0-beta.0
3. npm run build

## Result  
The build fails with:
```
_ERROR in : Can't resolve all parameters for IgxDropDownComponent in G:/Work/igniteui-angular-samples/node_modules/igniteui-angular/igniteui-angular.d.ts: ([object Object], [object Object], [object Object], ?)._
```

## Expected result  
The build passes successfully

## Attachments  
Attach a sample if available, and screenshots, if applicable.
![image](https://user-images.githubusercontent.com/24314672/57281093-edf11480-70b2-11e9-8a36-e4dcbb08c78f.png)

**Comment by zdrawku** [comment]
Related to https://github.com/IgniteUI/igniteui-angular-samples/pull/1135
