### ISSUE TITLE
In IE11 when chips length is bigger then filter row scrolls position is not correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4699]
## Description  
In IE11 when chips length is bigger then filter row scrolls position is not correct

 * igniteui-angular version: 7.3
 * browser: IE11

## Steps to reproduce  

1. Open dev sample gridGroupBy in IE11
2. Add filtering conditions to can scroll be previewed

## Result  
Scrolls position is not correct

## Expected result  
As in other browsers the scroll position should be correct

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/57298221-5bfd0200-70da-11e9-8e78-4c032ad5a645.png)

**Comment by simeonoff** [comment]
@mtsvyatkova I think this is related to styling. Can you confirm you will need help from us?

**Comment by mtsvyatkova** [comment]
@simeonoff Yes, it is related to styling. Setting the Display to a block value fixes the position of the pseudo elements (::before and ::after) in IE but I am not quite sure it is the best option. It will be great if you could have a look into it.
