### ISSUE TITLE
ig-hierearchical grid

### ISSUE THREAD

**Issue by prasanthkvm** [IgniteUI/igniteui-angular#47]
I am porting an app with infragustics grid from knockout to angular, i am stuck at the below scenario

have a template data-bind="template: { name: 'childDataTemplate'}" which i am setting using  childDiv.setAttribute("data-bind", "template: { name: 'childDataTemplate'}");

and the template i have in my page as `<script id="childtemplate"></script>`

On expand of child div i need to render this template inside the childdiv area where i have a child grid and some other fields coming from template

is this possible with angular ig directive? if yes What all infragustics plugins are needed for this, it would be great if u can giv a fiddle

Thanks.

**Comment by dkamburov** [comment]
This doesn't sound like a grid or ig directives issue. So you are using knockout templating and you are applying it to the child area

If I understand correctly you are trying to append angularjs template into the child are([$compile](https://docs.angularjs.org/api/ng/service/$compile) could do the trick for).

It might be helpful if you can provide your knockout app, so we can fully understand the scenario.

Regards, Deyan

**Comment by kdinev** [comment]
Closing this as inactive.
