### ISSUE TITLE
When using an igxGrid with MRL and pinned column group, after hiding and showing again the unpinned column group, data is missing

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/igniteui-angular#4704]
## Description  
When hiding and showing again a column group in igxGrid with MRL, when there is pinned column group, data is missing from the grid.

 * igniteui-angular version: 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Open Grid MRL sample in IgniteUI Dev Samples
2. Go with the mouse inside the column group that is not pinned and scroll down a little
3. Click the column hiding button in the toolbar and check group2 so it gets hidden
4. Uncheck group2 so it shows again

## Result  
Data is missing from group2 column group

## Expected result  
All the data should be present
![DataMissing](https://user-images.githubusercontent.com/12252163/57300770-2a873500-70e0-11e9-940d-8923f23d0984.gif)

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by skrustev** [comment]
I think this is already fixed in the latest 7.3.x branch. Probably due to the improvements to minimum unpinned width to work with Multi Row Layout.
@VMihalkov Could you verify that this is not reproduced anymore as well?

**Comment by VMihalkov** [comment]
I verified that this is fixed in latest 7.3.x
