### ISSUE TITLE
Pressing "space" on a highlighted item causes the dropdown to close and reopen

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#4705]
## Description  
On an opened dropdown with a highlighted item, if you press the "space" key, the dropdown will close and reopen.

 * igniteui-angular version: 7.3.x
 * browser: Firefox

## Steps to reproduce  

1. Run the dev samples and navigate to /dropDown
2. Click the "WITH ACTION DIRECTIVE" button
3. Click the "Down Arrow" key
4. Click the "Space" key
5. Observe

## Result  
The dropdown closes and reopens.

## Expected result  
The dropdown should close.

**Comment by wnvko** [comment]
When you click the button it gets focus. When you press the _Spacebar_ key two things happens:
- first we are handling keyDown event. In this event we are setting the selection and closing the drop down. We are also calling preventDefault.
- in Firefox click event is called on the button and drop down opens as we already have closed it.

Second action should not happen as we have called preventDefault. This is an issue in Firefox which is logged [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1552419).
