### ISSUE TITLE
Drop-down has horizontal scrollbar in Firefox

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-angular#4711]
## Description  
Drop-down is showing a horizontal scrollbar in Firefox. This is not happening in Chrome or IE11.

 * igniteui-angular version: 7.2.x
 * browser: Firefox

## Steps to reproduce  

1. Open Grid Search dev demo
2. Click on any column's filtering cell to open the filtering row
3. Click on the icon in the input group. This will open the filtering conditions drop-down

## Result  
Drop-down shows horizontal and vertical scrollbars.

## Expected result  
Drop-down should not show horizontal scrollbar.

## Attachments  
![изображение](https://user-images.githubusercontent.com/2705882/57359487-78537a00-7180-11e9-953b-eb6b374644e8.png)

**Comment by Lipata** [comment]
Not reproduced anymore.
