### ISSUE TITLE
When columns does not have width and filter with no found items and reset it, the grid has empty space 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4715]
## Description  
When columns does not have width and filter with no found items and reset it, the grid has empty space 

 * igniteui-angular version: 7.3
 * browser: N/A

## Steps to reproduce  

1. Edit dev sample gridCellEditing and change the first grid to:
<igx-grid #grid1 [data]="data" [primaryKey]="'ProductID'" [autoGenerate]="false" [displayDensity]="density" width="800px" height="550px" [allowFiltering]="true">
    <igx-column field="ProductID" header="Product ID"  [headerClasses]="'prodId'" [hasSummary]="false" [editable]="true">
    </igx-column>
    <igx-column field="ReorderLevel"   [filterable]="true"  [dataType]="'number'" [hasSummary]="false" >
    </igx-column>
    <igx-column field="ProductName"  header="ProductName"  [dataType]="'string'"  >
    </igx-column>
     <igx-column field="OrderDate"  [dataType]="'date'"  [hasSummary]="false"   [hidden]="orderDateHidden">
    </igx-column>
    <igx-column field="Discontinued" header="Discontinued" [dataType]="'boolean'"  [hasSummary]="false"  >
    </igx-column>
</igx-grid>

2. Open the sample
3. Filter column ProductID with condition "IsNull"
4. Clear filter

## Result  
The grid has empty space

## Expected result  
The grid should not have empty space

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/57373284-b365a580-71a0-11e9-994a-64b873bfa9b5.png)

**Comment by mtsvyatkova** [comment]
The fix for https://github.com/IgniteUI/igniteui-angular/issues/4745 fixes this issue as well.
