### ISSUE TITLE
When MRL and GroupBy have been enabled, the "Expand all" button does not have a bottom border

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4717]
## Description  
When MRL and GroupBy have been enabled, the expand all button does not have a bottom border, which visually merges it with the first group's collapse button.

 * igniteui-angular version: 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample with the latest master 
2. Open http://localhost:4200/

## Result  
The GroupBy  "Expand all" button looks like a part of the first group's "collapse" button.

## Expected result  
The "Expand all" button should be separate from the first group's "collapse" button

## Attachments  

![Sketch](https://user-images.githubusercontent.com/18643062/57388592-2aab3180-71c1-11e9-87d9-c23cb077c540.png)

[igxGridMRLGroupBy.zip](https://github.com/IgniteUI/igniteui-angular/files/3158153/igxGridMRLGroupBy.zip)

**Comment by mpavlinov** [comment]
Also there should be left border of the first column.

**Comment by simeonoff** [comment]
@mpavlinov I think the cells in the first column should have border bottom, which is the same as the one in the grid rows.
