### ISSUE TITLE
Distinguish row drag space in grid header from the grid column headers

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#4729]
## Description  
We decided to leave the row drag indicator in the row and in the header, without a right border in difference with the row selector column with the checkboxes. When having both row drag row and row selection it is looking good. However when having only row dragging and filtering enabled, then the missing border is looking like this:

![image](https://user-images.githubusercontent.com/2621802/57468282-d40b2980-728c-11e9-855b-c3ff7edad929.png)

![image](https://user-images.githubusercontent.com/2621802/57468553-57c51600-728d-11e9-9daa-a3b1d92fb24d.png)

Putting the right border (only in the header) is the way it is done in the hierarchical grid expander header cell, however, there is an expand icon there, while in the row selectable header there is nothing.

![image](https://user-images.githubusercontent.com/2621802/57468827-e9cd1e80-728d-11e9-93b5-1ffb8d9d0cd1.png)

![image](https://user-images.githubusercontent.com/2621802/57469018-4e887900-728e-11e9-9bc6-dd778adbf45a.png)

@StefanIvanov @simeonoff  Do you think there is a better UX for that case?

**Comment by desig9stein** [comment]
In my opinion, the drag handler should have space from both sides which should always be in compact mode. Another solution is to have the same density as the cells. I don't like the idea to have space only from one side because as we can see we constantly hit visual issues with that.

**Comment by StefanIvanov** [comment]
And to the question @Lipata is pointing out, to me the proper solution wold be to continue the horizontal border in the circled out area on the first shot.

**Comment by Lipata** [comment]
@StefanIvanov Just to note that in the case when there is both row dragging and row selection it will behave differently and will have no horizontal or vertical line. 

![image](https://user-images.githubusercontent.com/2621802/57513948-13328c80-7318-11e9-9558-c835fd6695bd.png)

Here is it how it will look with the continued horizontal line when the grid is configured only with row dragging - grid, tree grid and hierarchical grid:

![image](https://user-images.githubusercontent.com/2621802/57514222-a075e100-7318-11e9-9ca8-ec39a06b7b42.png)

![image](https://user-images.githubusercontent.com/2621802/57515373-2561fa00-731b-11e9-8f20-41a61a97bcb9.png)

![image](https://user-images.githubusercontent.com/2621802/57514374-0498a500-7319-11e9-8943-ea9e76f8654b.png)

**Comment by StefanIvanov** [comment]
OK so the final solution is the following. Since an approach with horizontal borders will cause many issues when the feature interplays with multicolumn headers and multi row layouts. Therefore, our final solution is to treat the expander hierarchical grid column, the row selector checkbox column and the row drag indicator as one visual entity i.e. horizontal border only to separate from the grid body and vertical border only to separate from the data column headers (no horizontal borders in the header area between these internally)

**Comment by Lipata** [comment]
The final solution will be:
- when only row dragging is used - to have vertical separator only in the header, and when in the hierarchical grid to remove the separator for the expand indicator, presented in the header:

![image](https://user-images.githubusercontent.com/2621802/57694930-a8ee5480-7655-11e9-8c2c-266eea8ec9ac.png)

![image](https://user-images.githubusercontent.com/2621802/57694603-d555a100-7654-11e9-8c8e-3dd7fbadd174.png)


 - when having both row dragging and row selection - as it is now vertical separator in the header and in the rows and in the case of the hierarchical grid remove expand separator, presented in the header.

![image](https://user-images.githubusercontent.com/2621802/57694916-9e33bf80-7655-11e9-819e-68642120e294.png)


![image](https://user-images.githubusercontent.com/2621802/57694901-95db8480-7655-11e9-9e57-d0bc998aec8c.png)

We will work on that. Thanks!
