### ISSUE TITLE
[igx-tree-grid] loading indicator not shown in IE11

### ISSUE THREAD

**Issue by rmkrmk** [IgniteUI/igniteui-angular#4754]
## Description  
Describe the issue.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Start the samples
2. Open "Tree Grid" > "Load On Demand"
3. Try expanding a node in the tree column using the expansion indicator.

## Result 
The data is loaded, the node is expanding, but while it loads the data the loading indicator is not shown.

## Expected result  
The loading indicator should be visible when data is being loaded.

**Comment by DiyanDimitrov** [comment]
@simeonoff, Could you please take a look at this issue? It seems to be a styling issue with IE11, the circular bar is in the DOM, but its size and placement seems to be incorrect.

**Comment by kdinev** [comment]
@simeonoff Could you cherry-pick this to master?
