### ISSUE TITLE
When height is not set or it is in percents the grid does not have vertical scroll

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4758]
## Description  
When height is not set or it is in percents the grid does not have vertical scroll

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. Edit dev sample hierarchicalGridUpdating and change it to:

```
....
<div style="width: 600px; height: 600px;">
        <igx-hierarchical-grid #grid1 [data]="remoteData" [rowEditable]="true" [primaryKey]="'CustomerID'" [autoGenerate]="false"
                #hGrid>
...
```

2. Open the edited sample

Note: this is not valid for the flat grid
## Result  
The grid has horizontal scroll according to container width, but the grid does not have vertical scroll

## Expected result  
The grid height should be 600px andit should have scrollbar

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/57622881-39b22b00-7597-11e9-8b5f-e6c081f7b82d.png)

**Comment by MayaKirova** [comment]
This issue seems to be a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/4809, which is already fixed.

**Comment by ChronosSF** [comment]
@nrobakova , please close if this is already fixed

**Comment by nrobakova** [comment]
this issue is already fixed
