### ISSUE TITLE
Cell in edit mode is not correct when expand a row

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4761]
## Description  
Row editing buttons are not in correct position when expand a row in a child grid

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGridUpdating
2. Expand first row
3. In the child grid double click on a cell in row with id 3
4. Row edit template is opened
5. In the child grid expand row with id 1
6. Scroll to row 3

Note1: Same is valid for the root grid
Note2: same is valid for cell editing

## Result  
Cell in row 2 is in edit mode and Done/Cancel buttons are under row 3

## Expected result  
Cell in edit mode should be in row 3

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/57625319-50a74c00-759c-11e9-8b66-599fd7c510e3.png)

**Comment by wnvko** [comment]
The issue is a result of how HierarchicalRow determines if the cell is in edit mode:
`[editMode]="col.editable && crudService.isInEditMode(index, col.index)"`
The cell is using `index` which is row index. When a row expands the row indexes of cells are changed.

**Comment by MayaKirova** [comment]
@wnvko The same applies to normal grid row and treegrid row. They all use the isInEditMode function, which currently reads the row index.  I assumed you were going to change the isInEditMode function to also use the rowID, not the row index as it represents the index in the rows collection, which changes when the rows or their order is changed. Let me know if that would be a viable fix or if we should discuss other possible approaches.
