### ISSUE TITLE
When grid width is less than 400px and type into filter input the chips arrows are displayed

### ISSUE THREAD

**Issue by astaev** [IgniteUI/igniteui-angular#4794]
## Description  
When grid width is less than 400px and type into filter input the chips arrows are displayed. But cannot see the chips because chips-area is too small. 

 * igniteui-angular version: 7.2.x
 * browser: n/a

## Steps to reproduce  

1. Edit dev sample gridSummary and change grid width to 400px
2. Open the sample and open filter row for a column
3. Enter a value at the input

## Result  
Arrows appear, but the chips-area is not visible. 
And if filter is applied, it cannot be selected at all

## Expected result  
There should be a visible part of the chips-area(add a min-width). 

## Attachments  
![filterArea](https://user-images.githubusercontent.com/44602698/69787407-2417f200-11c5-11ea-9219-161c7ba742e6.PNG)

**Comment by astaev** [comment]
@StefanIvanov @DaniMarinov, Can you help us with this bug, and advise what to do in this corner case?
![filterArea](https://user-images.githubusercontent.com/44602698/69787583-87a21f80-11c5-11ea-907c-3c9b43a20813.PNG)

**Comment by DaniMarinov** [comment]
@astaev I will think about solution and will let you know

**Comment by DaniMarinov** [comment]
@astaev Find my proposal below. Note that we have to set chip min-width and filtering row min-width. 
![min-width](https://user-images.githubusercontent.com/41998471/69872530-493c5b80-12be-11ea-9fc4-c61c98844bae.png)

**Comment by StefanIvanov** [comment]
@DaniMarinov I think it will be useful to define the specific values and also mention whether they change as one switches from one display density to another

**Comment by DaniMarinov** [comment]
@StefanIvanov We've already discussed that with @astaev and @DiyanDimitrov, I will provide the specific values in the specification of the Filtering Row. 
As to display density - thanks, I will do it

**Comment by radomirchev** [comment]
@DaniMarinov any update on the issue?

**Comment by DaniMarinov** [comment]
@radomirchev  the spec was updated back then, check here https://github.com/IgniteUI/igniteui-angular/wiki/Filtering-Row#15responsive-design

**Comment by onlyexeption** [comment]
@StefanIvanov I've already resolved this issue locally but I wanted to ask you whether you want to handle it with JavaScript or CSS ?

**Comment by simeonoff** [comment]
@onlyexeption A CSS fix would be ideal. Draft a PR and I will take a look at your fix.
