### ISSUE TITLE
Custom footer in igxgrid

### ISSUE THREAD

**Issue by shaileshyadav24** [IgniteUI/igniteui-angular#4805]
## Is your feature request related to a problem? Please describe.
Not able to show custom values in the footer of a column

## Describe the solution you'd like
Should be able to use variable in footer of a column

## Describe alternatives you've considered
Tried to override summary of grid, but not able to achieve solution

**Comment by kdinev** [comment]
I'm closing this one, as custom values can be rendered in the grid footer, as well as in custom column summaries per column.

```html
<igx-grid>
  .....
  <igx-grid-footer>
  </igx-grid-footer>
</igx-grid>
```

Or  

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries.html
