### ISSUE TITLE
Hierarchical child rows that have a filtering row and no height set show no data  in Edge

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#4807]
## Description  
The height of child grids that have a filtering row and no height set is calculated incorrectly on Edge leading to them rendering just their header and rows without height (or something similar)

 * igniteui-angular version: 7.2.x
 * browser: Edge

## Steps to reproduce  

1. Open the Hierarchical Grid sample from the demos on Endge
2. Expand a row in the second grid (the one that has Filtering enabled)

## Result  
The two child layouts render squashed grids with no data or scrollbar

## Expected result  
The child layouts have data to be displayed, Chrome shows them correctly

## Attachments  
n/a

**Comment by MayaKirova** [comment]
@ChronosSF This no longer seems to reproduce in 7.2.x, 7.3.x, 8.0.x and master.
