### ISSUE TITLE
[IE11][igx-grid][MRL] header cell is not row-spanned.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4825]
## Description  
About `multi row layout, when only one `igx-column` is in `igx-column-layout`, its header cell is not row-spanned.
```
    <igx-column-layout field='group1'>
      <igx-column [rowStart]="1" [rowEnd]="4" [colStart]="1" field="ID" [width]="'200px'"></igx-column>
    </igx-column-layout>
```

 * igniteui-angular version: 7.3.1-beta.1
 * browser: IE11

## Steps to reproduce  

1. Run the attached sample in IE11.

## Result  
![IE11-mrl-header-rowspan-issue - コピー](https://user-images.githubusercontent.com/15909409/57916357-a5650280-78cd-11e9-95ce-81b203459391.png)

## Expected result  
This is the result on Chrome.
![chrome 46_LI](https://user-images.githubusercontent.com/15909409/57917271-50c28700-78cf-11e9-9ab1-c36550b808d7.jpg)

## Attachments  
[igx-grid-multi-row-layout.zip](https://github.com/IgniteUI/igniteui-angular/files/3190718/igx-grid-multi-row-layout.zip)

**Comment by mpavlinov** [comment]
Note: Please verify that the fix for this issue also fixes #4815
