### ISSUE TITLE
[igx-grid][MRL]the column on the right end can't be resized.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4826]
## Description  
About `igx-grid` with multi row layout, the column on the right end can't be resized.

 * igniteui-angular version: 7.3.1-beta.1
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample.
2. Try to resize the column on the right end.

## Result  
The column can't be resized.
![cant-resize-column-on-the-right-end](https://user-images.githubusercontent.com/15909409/57919566-00015d00-78d4-11e9-9603-5545fa3d06c3.gif)

## Expected result  
The column should be resized.

## Attachments  
[igx-grid-multi-row-layout.zip](https://github.com/IgniteUI/igniteui-angular/files/3190905/igx-grid-multi-row-layout.zip)

**Comment by skrustev** [comment]
Hello @tkiryu,  I've looked into the sample you have attached and it seems like you have defined 'colEnd' for the 'Address' column to 1, which is the same as the colStart for that column. That is why the resizing for that column is not working.

If you don't set the 'colEnd', which by default would size the column to 1 column span, or set it to 2, everything seems to be working correctly.

**Comment by tkiryu** [comment]
@skrustev , oh, I'm so sorry about that. I'm totally wrong.

Thank you for looking into it!

I'm closing this issue.
