### ISSUE TITLE
Font-sizes in ESF do not match the font-size of the respective grid

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#4833]
## Description  
Font-sizes in ESF do not match the font-size of the respective grid.

This currently includes:
- **sort** and **move** headers (this should be considered for all display densities, currently the sort and move headers for '**comfortable**' and '**cosy**' are the same, while it is different for '**compact**')
- **clear filter** and **text filter** headers
- **text of the checkboxes** in the list items
- **dropdown items** from the cascade menu

We should also consider font-size changes for the custom filter dialog as well.

 * igniteui-angular version: 7.3.x
 * browser: any

## Steps to reproduce  

1. Run the 'Column moving' dev demo.
2. Switch to any display density.
3. Open the Excel Style Filtering component.
-> issue 1
3. Open the cascade menu for operators by clicking '**Text Filter**'.
-> issue 2
3. Open the Excel Style Custom Filtering dialog.
-> issue 3

## Result  

Issues 1,2,3: Font-size does **not** match the font-size of the respective grid.

## Expected result  

Issues 1,2,3: Font-size does match the font-size of the respective grid.

## Attachments  

![esf](https://user-images.githubusercontent.com/12784974/57927049-adb14380-78b5-11e9-9029-2d6803778c2f.PNG)

**Comment by tachojelev** [comment]
Related to #4766

**Comment by DaniMarinov** [comment]
You can find the updated spec here https://github.com/IgniteUI/igniteui-angular/wiki/Excel-Style-Filtering
