### ISSUE TITLE
IgxButtonGroup does not respect compact styles

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#4840]
## Steps to reproduce  

1. Run the Excel Style Filtering dev demo
2. Change the DisplayDensity to cosy
3. Open the Filtering dialog

## Result  
Some inconsistencies in the buttons style (see height) :
![Untitled](https://user-images.githubusercontent.com/14248932/58007835-c60ea180-7af3-11e9-8a7d-3b686740163c.png)

## Expected result  
Sorting and Moving columns buttons to look same

**Comment by hanastasov** [comment]
The sorting buttons are part of a ButtonGroup, while the Move buttons are single buttons.

**Comment by hanastasov** [comment]
@bkulov , @gedinakova , what do you think about changing the IgxButtonGroup with the sorting buttons with single buttons ?

**Comment by simeonoff** [comment]
@hanastasov This was part of the design, I think @DaniMarinov would be a more appropriate person to consult with about that.

**Comment by DaniMarinov** [comment]
It's better to have sorting buttons with Text and Icon (like it is in the current design), not only icon. First, it is more consistent with the Move buttons; second, the action is more clear when having both icon and text;

**Comment by bkulov** [comment]
#4698
