### ISSUE TITLE
Grid filtering shows "1 of 0" when there are no results

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-angular#485]
### Description  
Grid filtering shows "1 of 0" when there are no results.

### Steps to reproduce  

1. Go here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
2. Filter by something that doesn't exist in the grid.
3. Observe the result.

### Result  
"1 of 0"

### Expected result  
I'm not sure.  Maybe "0 of 0" or nothing displayed for page numbers?

### Attachments  

![image](https://user-images.githubusercontent.com/8162597/32843756-8eda746c-c9ee-11e7-90bb-2795cd0600bb.png)

**Comment by SlavUI** [comment]
@zdrawku Hi is there any update on the issue ?

**Comment by zdrawku** [comment]
Grid is going to be rewritten in some paging aspects soon and we are going to consider this suggestion

**Comment by SlavUI** [comment]
Closing this one as the Grid will soon have a new sample :)

**Comment by PavlovVasil** [comment]
Reopening this one, as it has _not_ been fixed in the igxGrid, only in the Paging sample

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html
2. Filter "Units In Stock" column by "Greater than" 250

The Paging shows "Page 1 of 0"
