### ISSUE TITLE
[igx-grid] "quick clicking twice resizer " can sometimes lead to unable to sort.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4858]
## Description  
"quick clicking twice resizer" can sometimes lead to unable to sort. It's not a double-click. It's a little slower than double-click.

 * igniteui-angular version: 7.2.9
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample.
2. Mouse down and hold until resizer handler shows up.
3. Then click quickly.

## Result  
After step3, columns can't be sorted. 

You might feel that it is difficult to reproduce. But steps 2-3 are almost double-click. Therefore, there is a good chance for this issue to happen accidentally.

![igx-grid-sorting-issue](https://user-images.githubusercontent.com/15909409/58095419-f185af00-7c0d-11e9-9328-bbe892ac8945.gif)

## Expected result  
Columns should be able to be sorted.

## Attachments  
[igx-grid-sorting-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/3202520/igx-grid-sorting-issue.zip)

**Comment by tkiryu** [comment]
Hi, @SAndreeva , 
By operating steps 2-3, for some reason, it seems that `colResizingService.isColumnResizing` is not set to false, thus sorting becomes not working.

https://github.com/IgniteUI/igniteui-angular/blob/7.2.9/projects/igniteui-angular/src/lib/grids/grid-header.component.ts#L155-L168

```
    @HostListener('click', ['$event'])
    public onClick(event) {
        if (!this.colResizingService.isColumnResizing) {
            event.stopPropagation();
            if (this.grid.filteringService.isFilterRowVisible) {
                if (this.column.filterable && !this.column.columnGroup &&
                    !this.grid.filteringService.isFilterComplex(this.column.field)) {
                    this.grid.filteringService.filteredColumn = this.column;
                }
            } else if (this.column.sortable) {
                this.triggerSort();
            }
        }
    }
```

**Comment by tkiryu** [comment]
I ran into a behavior that the column resizer is not hidden when I accidentally moved mouse cursor during operating step 3.  It is similar to #4610. I operated this again and again, then I managed to reproduce this. I'm attaching reproducible gif.

![igx-grid-resizer-issue](https://user-images.githubusercontent.com/15909409/58237847-0e8ebf00-7d81-11e9-9dc4-28c55d92d392.gif)

It was so difficult to reproduce. I'm not sure but I guess the root cause is the same as this issue.

Could you please consider this resizer behavior when you work on this issue?

Thanks!

**Comment by SAndreeva** [comment]
@tkiryu, thanks for reporting and investigating these behaviors. I will take a look and try fixing both of them.
