### ISSUE TITLE
Data Operations UI

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#486]
### Description  
Provide a UI that covers the common data operations that can be applied on a data container using our `DataUtils`. The UI should enable end users to apply the following operations on a column of the data the UI is instantiated for:

1. Filter the data by conditions (advanced)
2. Search the data (simple filter)
3. Sort the data ascending or descending
4. Filter the data by unique values (excel-style)
5. Group the data by the column

Create a specification in the wiki with the research.

**Comment by sbozalieva** [comment]
Based on the research we defined two types of operations applied on data:

1. Filtering - shows part of the data.
2. Transforming - shows the same data. Reorders it or changes the state (hide, pin etc).

![image](https://user-images.githubusercontent.com/23053821/33482048-e9e9cc8c-d69f-11e7-91f1-7dfa77acbc32.png)


Explored are the basic samples of an UI element. Defining it as a container holding the **operation** and corresponding **actions**. 

## Next Steps
- [x]  Exploring complex samples.
- [x]  Refining the visual design.
/more/

**Comment by SlavUI** [comment]
This item is now Obsolete since the concept has changed and now some of the tools are move in the igxToolbar section
