### ISSUE TITLE
Conditional row island in hierarchical grid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#4869]
## Question  
Is it possible to conditionally show/hide row islands in the hierarchical grid? Meaning that some rows will be expandable, while others are not.

**Comment by kdinev** [comment]
There is a bug logged about this #4779

**Comment by Eralmidia** [comment]
es, I actually saw that question, but since Martins reply mentioned rendering both grid and hierarchical grid, it din't seem like it was the same thing. But I'll close this and track that issue then. Thanks Konstantin.
