### ISSUE TITLE
IE 11 does not display the MRL correctly

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4876]
## Description  
The "display: ms-grid" style does not get applied to the grid when there is a MRL, which breaks the layout in IE 11. The two screenshots below show the difference in the layout when the same grid gets rendered in Chrome (screenshot1) vs IE 11 (screenshot2)

 * igniteui-angular version: 7.3.x
 * browser: Internet Explorer 11

## Steps to reproduce  

1. Run the attached sample with latest 7.3.x
2. Open http://localhost:4200/

## Result  
The MRL does not get applied, which displaces all grid cells

## Expected result  
The MRL should be rendered correctly.

## Attachments  

Sample: 

[igxGridMRLGroupBy.zip](https://github.com/IgniteUI/igniteui-angular/files/3208322/igxGridMRLGroupBy.zip)

Chrome: 
![Sketch4](https://user-images.githubusercontent.com/18643062/58190749-d7a7a300-7cc5-11e9-959a-e075d0830dd4.png)

IE 11: 
![Sketch3](https://user-images.githubusercontent.com/18643062/58190767-e1310b00-7cc5-11e9-8615-ae1ec70ca59b.png)

**Comment by PavlovVasil** [comment]
@simeonoff Тhe problem appears only when the package with the styles get loaded in the browser in an isolated sample or in the samples repo. However, it does not reproduce on production or when the dev demos are run. 
Do we build the styles for the dev demos (and production as well) in some different way? That might explain why the "display: ms-grid" somehow gets added there?

**Comment by rkaraivanov** [comment]
@PavlovVasil 
I think this is [documented](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#styling-configuration) for IE 11

**Comment by simeonoff** [comment]
@PavlovVasil as @rkaraivanov pointed out, you need    
```css
/* autoprefixer grid:on */
```
For prefixing to work.

**Comment by PavlovVasil** [comment]
@rkaraivanov @simeonoff : Thank you for the clarification, I am closing the issue.
