### ISSUE TITLE
Mozilla Firefox does not render a vertical scrollbar in some scenarios

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4877]
## Description  
Running the attached sample shows a vertical scrollbar in all browsers except Mozilla Firefox.

 * igniteui-angular version: 7.3.x
 * browser: Mozilla Firefox

## Steps to reproduce  

1. Run the attached sample with the latest 7.3.x
2. Open http://localhost:4200/ in Mozilla Firefox

## Result  
There is no vertical scrollbar.

## Expected result  
There should be a vertical scrollbar.

## Attachments  

Sample: 
[igxGridMRLGroupBy.zip](https://github.com/IgniteUI/igniteui-angular/files/3208416/igxGridMRLGroupBy.zip)

![Sketch22](https://user-images.githubusercontent.com/18643062/58192667-fa3bbb00-7cc9-11e9-8fdc-b0f97d5cca27.png)

**Comment by mddragnev** [comment]
Does not reproduce in 8.2.x
