### ISSUE TITLE
igx-grid multi-column headers

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#488]
### Description  
As a developer, I would like to configure the igx-grid to display multiple layers of headers on top, in order to display groups into which certain columns belong.

As a user, I would like to see what columns of the grid apply to the location information encapsulated in the `Country`, `Street`, and `Zip Code` columns.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/33552059-2e88ed6a-d8fc-11e7-8479-984efdabea65.png)

**Comment by SlavUI** [comment]
Spec created and available in Wiki

**Comment by SlavUI** [comment]
@SDinev and @StefanIvanov  guys please put the designs in the issue :)

**Comment by SDinev** [comment]
Designs incoming:

### Default Styling

- Text in the header cells is set in _Title Case_
- Text is aligned left. 
- If styling allows, we should create horizontal lines to separate each level of the multicolumn headers. 

![igx-grid_multicolumn_headers](https://user-images.githubusercontent.com/13866657/41286350-c6fe8696-6e47-11e8-9f44-c05ef49cb4fb.png)

### Possible user styling
Headers and summaries have blue shades applied, the toolbar uses the primary color, and the secondary color is changed to yellow. Headers are set in uppercase. 
This screenshot is for purely presentation purposes.
![igx-grid_multicolumn_headers-styled2](https://user-images.githubusercontent.com/13866657/41286349-c6de1ca8-6e47-11e8-9cb5-4e356d1ccd39.png)
