### ISSUE TITLE
igx-grid alternating row styles

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#489]
### Description  
As a developer, I would like to enable alternating row styling for the grid rows, in order to improve readability of the table.

As a user, I would prefer if the grid rows have a different background, which alternates between rows, in order to easily follow which row the data I'm reading belongs to.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/33555593-a52e655a-d909-11e7-917a-15bbdcce6b67.png)

**Comment by SlavUI** [comment]
This has been completed
