### ISSUE TITLE
Keyboard navigation with Enter key

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#4903]
## Is your feature request related to a problem? Please describe.
Add keyboard navigation with Enter key as is in Excel.

## Describe the solution you'd like
Enter key moves selection on the next row. Shift + Enter key moves selection on the previous row.

## Describe alternatives you've considered
Right now we expose this functionality with custom keyboard navigation. Consider making it a part of the default grid functionality.

**Comment by kdinev** [comment]
Related #4054

**Comment by zdrawku** [comment]
@kdinev and @radomirchev In my opinion we should not consider this suggestion. We strive to be as much ARIA compliant as possible, and the Design that we established (for the Keyboard Navigation Enhancements) is upon the [WAI ARIA Practices for Editing a Grid while navigating](https://www.w3.org/TR/wai-aria-practices/#gridNav_inside), which is by using `Enter key`, and using the arrow keys for moving focus from cell to cell.

In Addition, as Martin mentioned, we already show a way to achieve the desired functionality with Custom Navigation implementation, I believe that's enough.

> While navigation keys, such as arrow keys, are moving focus from cell to cell, they are not available to perform actions like operate a combobox or move an editing caret inside of a cell. The user may need keys that are used for grid navigation to operate elements inside a cell if a cell contains:
> 
> Editable content.
> Multiple widgets.
> A widget that utilizes arrow keys in its interaction model, such as a radio group or slider.
> Following are common keyboard conventions for disabling and restoring grid navigation functions.
> 
> **Enter: Disables grid navigation and:**
> **If the cell contains editable content, places focus in an input field, such as a textbox.** If the input is a single-line text field, a subsequent press of Enter may either restore grid navigation functions or move focus to an input field in a neighboring cell.
