### ISSUE TITLE
igx-grid multi-selection data should be put in the clipboard on copy

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#4907]
## Is your feature request related to a problem? Please describe.
Multi-cell selection is put into the clipboard only if the copy event is manually handled by the developer. 

## Describe the solution you'd like
I would like, by default, the data to make it into the clipboard when copy is performed.

## Describe alternatives you've considered
Handling the event manually for every grid in the application.

## Additional context
Currently, the multi-cell selection does nothing out-of-the-box, than to apply selection styles on the cells. Since the text selection is not applied, the default copy puts nothing in the clipboard.

Related to #3915

**Comment by zdrawku** [comment]
Adding [specification ](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-clipboard-interactions)to the issue
