### ISSUE TITLE
igx-grid column misalignment occurs with many columns

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#492]
### Description  
Column misalignment occurs when there are many columns

### Steps to reproduce  

1. Run the sample application
2. Observe the column alignment after "column3"

### Result  
String value on "column3" does not start from the left edge of "column3". The following columns have the same symptom.

![image](https://user-images.githubusercontent.com/14340675/33816724-4fb08688-de7e-11e7-9342-3888b0e62c58.png)

### Expected result  
String value on "column3" starts from the left edge of "column3". The following columns behave the same.

### Attachments  
[demo-app.zip](https://github.com/IgniteUI/igniteui-js-blocks/files/1546614/demo-app.zip)

**Comment by zdrawku** [comment]
Hey Yuki, this issue will no longer appear if you start to use the latest igniteui-angular pachage. What should you consider:
1. igniteui-js-blocks@5.0.1 is deprecated
2. Use igniteui-angular for the latest features
3. Uninstall igniteui-js-blocks and run npm install igniteui-angular.

```
npm uninstall igniteui-js-blocks
npm install igniteui-angular
```
4. Update `.angular-cli.json`

```
"styles": [
        "styles.scss",
        "../node_modules/igniteui-angular/igniteui-angular.css"
      ],
```
5. Update `app.module.ts`


```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import 'hammerjs';
import {
  IgxGridModule,
  IgxSwitchModule,
  IgxDatePickerModule
} from 'igniteui-angular/main';


```
6.  Update `app.module.ts` **IgxGridModule.forRoot(ROUTES)**

```
@NgModule({
  declarations: [
    AppComponent,
    GridComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(ROUTES),
    IgxGridModule.forRoot(),
    IgxSwitchModule,
    IgxDatePickerModule,
  ],

```

Result:

![image](https://user-images.githubusercontent.com/11193764/35511141-7ef9091e-0503-11e8-8c5a-411a4ff2cb4d.png)

**Comment by ymita** [comment]
Hi Zdravko,

Thank you for the update. I confirmed that the alignment issue is not reproduced with Ignite UI for Angular version 5.1.3.

I'm attaching an updated sample. It also contains changes on column definitions since some columns had wrong dataType in the previous one.
[demo-app_1.zip](https://github.com/IgniteUI/igniteui-angular/files/1676452/demo-app_1.zip)

Thanks,
Yuki
