### ISSUE TITLE
Selected cell remains highlighted after selected moves down by Enter key hit

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#4922]
## Description  
Selected cell remains highlighted after selected moves down by Enter key hit. This is originally asked at the following link.
https://github.com/IgniteUI/igniteui-angular/issues/4054#issuecomment-491678028

 * igniteui-angular version: 7.3.2
 * browser: n/a

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-leyboard-navigation-zudbpe
2. Select a cell
3. Hit Enter key to move down the cell

## Result  
The cell selected on step 2 remains selected after step 3.

## Expected result  
The cell selected on step 2 is cleared after step 3.

**Comment by rkaraivanov** [comment]
Closed by #5068
