### ISSUE TITLE
ESF jumps up and down while scrolling the page

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#4927]
## Description  
When I open the ESF and try to scroll the **PAGE** using **my mouse wheel** the filtering dialog jumps up and down. If I do the same thing by dragging the scroll I don't see that problem.

in **Safari** you can observe the problem in both cases.
In **Firefox** and **IE**, there is no problem.

 * igniteui-angular version: all
 * browser: **Chrome, Safari, Edge**

## Steps to reproduce  

1. Run dev demos.
2. Open this sample.
3. Open the ESF by pressing the filter icon.
4. While the ESF is open scroll the **PAGE** up and down using your mouse wheel.

## Result  
EFS filter container jumps up and down while scrolling.

## Expected result  
The ESF container should maintain its position.

## Attachments  
! The gif loads a bit slower :)
https://drive.google.com/file/d/1h9XNDb3K_tssRzNJBvvnmmB7JopPbv5K/view?usp=sharing

**Comment by wnvko** [comment]
We are already handling `scroll` event outside Angular Zone. However in `scroll` handler we are calling `reposition` method of the `overlay`. This sets top and/or left and/or right and/or bottom of the content element. This forces the browser to repaint and leads to flickering in some browsers, e.g. Edge and IE. We cannot fix this as even if you try reposition an empty div in scroll event you will see it will start flicker.
