### ISSUE TITLE
igx-grid headers letters are being cut off

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#493]
### Description  
Grid headers letters are being cut off

### Result  
![infragisticsangulargrid 1](https://user-images.githubusercontent.com/1182001/33819552-c269557c-de53-11e7-8188-39f158045f2b.jpg)

**Comment by dkamburov** [comment]
![image](https://user-images.githubusercontent.com/1182001/35511997-d3ed70e2-0506-11e8-81f9-0c469388c9d6.png)

**Comment by ddincheva** [comment]
The whole Grid Demo has been rewritten, so this issue will be fixed in our next release.
