### ISSUE TITLE
[igx-grid] disabled igxButton="flat | icon" don't look like disabled in the igxToolbarCustomContent.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4958]
## Description  
Disabled igxButton="flat | icon" don't look like disabled in the igxToolbarCustomContent.

 * igniteui-angular version: 7.3.2
 * browser: N/A

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igcbutton-disabled-style-issue-in-igx-grid-toolbar

## Result  
igxButton="flat" and igxButton="icon" dont' look like disabled.

## Expected result  
igxButton="flat" and igxButton="icon" should look like disabled.

## Attachments  
None.

**Comment by sengokyu** [comment]
I found a work arround:

```
<button class="igx-button igx-button--flat"
 [class.igx-button--disabled]="true"
 [disabled]="true"
>
```

And this is a tiny patch (not tested).

```diff:
    @Input() set disabled(val) {
        val = !!val;
        if (val) {
            this._renderer.addClass(this.nativeElement, `${this._cssClassPrefix}--disabled`);
        } else {
            this._renderer.removeClass(this.nativeElement, `${this._cssClassPrefix}--disabled`);
        }
+       this._renderer.setAttribute(this.nativeElement, 'disabled', val);
    }
```

**Comment by DiyanDimitrov** [comment]
@simeonoff, This looks like to be a styling issue. Could you take a look at it?
