### ISSUE TITLE
igx-grid column width not applied

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#496]
### Description  
Can not set column width.

### Code-snippet
```
<igx-grid  [data]="localData" [autoGenerate]="false">
    <igx-column [sortable]="false" [field]="'EmployeeID'" [header]="'Id'" [width]="'1020px'"></igx-column>
</igx-grid>
```

### Result  
The Employee Id column does not have width 1020px.

### Expected result  
The Employee Id column should have width 1020px.

**Comment by zdrawku** [comment]
With the next pull request we are going to update the HostBinding of the cellcomponent width:
```
@HostBinding("style.max-width")
get width() {
return this.column.width;
}

// TO

@HostBinding("style.width")
get width() {
return this.column.width;
}
```
