### ISSUE TITLE
The green border for a focused element is not cleared in Firefox and Edge when Group By is enabled

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4970]
## Description  
When the user focuses a cell and groups by a column, scrolling down in Mozilla and Edge shows multiple cells with green border.

 * igniteui-angular version: 7.3.x
 * browser: Mozilla Firefox, MS Edge

## Steps to reproduce  
1. Run the dev demos and open http://localhost:4200/gridGroupBy in Firefox or Edge
2. Select the first cell of the first row in the "Salary" column
3. Group by the CompanyName column
4. Scroll down to the bottom of the grid

## Result  
Scrolling down shows multiple "focused" cells

## Expected result  
The green border styling should get cleared when a column gets grouped

## Attachments  
![MRLMultipleFocusedCells](https://user-images.githubusercontent.com/18643062/58814549-9b156900-862e-11e9-87ac-fe276798dc88.gif)

**Comment by ChronosSF** [comment]
@radomirchev , this is still reproducible in latest
