### ISSUE TITLE
Date Picker and Calendar - Localizing and formatting labels

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#498]
### Description  
On a calendar, the place of date, month, year and week day are hard-coded in a template. It causes that I can't localize the header label(selected date) and the year-month label into valid Japanese date formats. I set locale "ja-JP" to the locale option then each of elements (for example month and weekday) is correctly localized but the order of the elements is not valid. It should be able to format the whole label since the order of them is different depending on a local culture.

![image](https://user-images.githubusercontent.com/7350918/34699602-9d129b5a-f521-11e7-820b-ffc219523644.png)

**Comment by zdrawku** [comment]
Hey @gdayori we are not currently plannig to add this enhancement to the upcomming sprint (Sprint 6). Keep track of the Projects section. Once we start working on it, the projects would be updating with the Sprint number that will take place for further implementation.
