### ISSUE TITLE
Selecting a cell range in MRL does not apply border-bottom if the group is pinned

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4981]
## Description  
When several cells in a pinned group get selected, the border-bottom gets set to 0px and the cells on different rows look as one large cell.

 * igniteui-angular version: 7.3.x
 * browser: n/a

## Steps to reproduce  

1. Run the dev demos and open http://localhost:4200/gridMRL 
2. Select the first cell in the pinned group of the first row - Maria Anders
3. Drag with the left mouse button pressed in order to select multiple cells from that group

## Result  
The cells do not have border-bottom and look like one big row instead.

## Expected result  
There should be a border at the bottom to indicate that there are three rows in that group.

## Attachments  
![Sketch](https://user-images.githubusercontent.com/18643062/58898573-835be480-8703-11e9-8ffe-27120faac714.png)

**Comment by ChronosSF** [comment]
@radomirchev , this is still reproducible but is a styling issue. It looks like it's indended, @simeonoff should be able to confirm

It is caused by css similar to this one:
```css
.default-theme .igx-grid__td--pinned.igx-grid__td--selected {
    border-bottom: 0px;
}
```
