### ISSUE TITLE
Grid selection issues

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#4989]
## Question  
In regards to #2572: Has there been any changes done to selection since this? I find the way selection works in the grid very cumbersome. Why isn't there simply a [selection] input, which controls the selection behavior, with values like "none", "cell", "multiCell", "row" and "multiRow"?

For most of our grids, we need a simple single row selection. You click a row, and it gets selected (and should be highlighted as per the $row-selected-background theme property). #2572 does provide a workaround for this, but it seems like such a basic functionality, that having to write a handler, for every grid, in order to do it is very odd.

Also, while there is a [rowSelection] input, I can't see a [cellSelection] input, so how to I create a plain grid with no selection? Do I have to create another handler to deselect the cell on selection or something like that?

 * igniteui-angular version: 7.3.2

**Comment by Eralmidia** [comment]
Today I also noticed another oddity in the grid. Seems like range selection of cells are on by default. Even if I create a handler for cell selection to select the row, I can still make an additional range selection of cells, making it possible to do things like this:
![image](https://user-images.githubusercontent.com/12936286/59254573-bdac1100-8c30-11e9-967e-e8748f5c91a5.png)

Why on earth are all these features on by default?

**Comment by rkaraivanov** [comment]
@Eralmidia 

I agree on exposing a `cellSelection` input or something along those lines with the most common combinations - no selection, cell + row selection on click, etc.
We'll try to take a look at it as soon as possible and update the spec, so any updates will be linked in this issue.

As for why multi selection is enabled by default - it was a conscious decision from our part and this will probably remain the default behavior.

**Comment by Eralmidia** [comment]
@rkaraivanov Yes, we had a good meeting with @kdinev and co last week. Looking forward to see what comes out of it. Default multi select isn't really an issue, as long as we can turn i off with an input or two, instead of how it is now, where we kinda feel we are trying to fight the grid into behaving as we want. Getting a more "native" support for single row select + avoiding the multi cell (spider select I believe Konstantin called it), would be the top requirements.

**Comment by kdinev** [comment]
@Eralmidia Yesterday we agreed on introducing `rowSelection` and `cellSelection` inputs, which can both be set to `none`, `single`, or `multi`. This will cover all selection permutations out of the box. Specification in progress is located [here](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Selection-%5BGeneral%5D). Not all changed have been applied to the spec yet, as you will see it still has a `selectionMode` input, but that is going to get updated.

**Comment by Eralmidia** [comment]
Perfect 👍 This will selection easier and more clear when defining the grid.

**Comment by zdrawku** [comment]
Hello @Eralmidia we've released a [beta version ](https://github.com/IgniteUI/igniteui-angular/releases/tag/8.2.0-beta.0)of 8.2.0 which includes the implementation of the new Grid Selection, I would be thankful if you find time to try it and provide any comments or thoughts that you have.
