### ISSUE TITLE
When row editing is opened and navigate with PageUp/PageDown buttons the layout is not in correct position

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4993]
## Description  
When row editing is opened and navigate with PageUp/PageDown buttons the layout is not in correct position

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridRowEdit
2. In the first grid click on the 4th row to enter edit mode
3. Press Page Down key

## Result  
The grid is scrolled, but the row edit is not in correct position

## Expected result  
The row editing layout should be under the edited row

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/58964918-5d444c00-87b8-11e9-87a1-4aee94739ea7.png)

**Comment by MayaKirova** [comment]
Issue no longer reproduces in 9.1.x
