### ISSUE TITLE
Update README component list to include Charts and Excel

### ISSUE THREAD

**Issue by brianlagunas** [IgniteUI/igniteui-angular#4999]
## Question  
There seems to be a number of components missing from the component list on the Readme.  Specifically the charts and excel components.  I understand those are not in the actual source code in the repo, but they are still part of the Ignite UI product.  They should probably be added to the component list to give a full list of available components.

Thoughts?

**Comment by kdinev** [comment]
They are technically part of other packages, but we can expand the table to reflect on what's available as a whole and which package each component belongs to.

**Comment by brianlagunas** [comment]
If you have an idea of how you would like to represent that, I could submit a PR.  Just provide an image of how you want it to look in the read me and I'll make it happen.

**Comment by kdinev** [comment]
@brianlagunas I just see it as two other tables below the LOB table, titled something like:

### Components Available in [igniteui-angular-charts](https://github.com/IgniteUI/igniteui-angular-charts)
Table

### Components Available in [igniteui-angular-excel](https://www.npmjs.com/package/igniteui-angular-excel)
Table
