### ISSUE TITLE
[igx-grid] Toolbar height for displayDensity = 'compact' is the same as the one for displayDensity = 'cosy'.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#5002]
## Description  
Toolbar height for displayDensity = 'compact' is the same as the one for displayDensity = 'cosy'.

 * igniteui-angular version: 7.3.3
 * browser: N/A

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-button-height-issue-in-toolbar

## Result  
Toolbar height for displayDensity = 'compact' is the same as the one for displayDensity = 'cosy'.

### Compact : NG
![image](https://user-images.githubusercontent.com/15909409/59014524-cdfe6d80-8877-11e9-9fe2-9e05e427c91a.png)

### Cosy : OK
![image](https://user-images.githubusercontent.com/15909409/59014565-df477a00-8877-11e9-9c2d-5172477218d7.png)

### Comforable : OK
![image](https://user-images.githubusercontent.com/15909409/59014582-e9697880-8877-11e9-94e9-8dbb389424f1.png)

## Expected result  
Toolbar height for displayDensity = 'compact' should be smaller than the one for displayDensity = 'cosy'.

## Attachments  
None.

**Comment by tkiryu** [comment]
It seems that  the `compact` toolbar height  is same as the `cosy` one. It may be one of the causes.

**Comment by tachojelev** [comment]
@tkiryu , the igxButtons that are used in the toolbar have a **displayDensity** property as well and it is bound to the displayDensity of the grid. This means that the button itself (even when it is used as just a button outside the grid) becomes smaller (with smaller height) when changing the displayDensity to 'compact'.

**Comment by tkiryu** [comment]
@tachojelev , thank you for explaining.
>the igxButtons that are used in the toolbar have a displayDensity property as well and it is bound to the displayDensity of the grid.

Yes, I understand that this is the reason that button height in the toolbar gets smaller. 



As I said yesterday, 
>It seems that the compact toolbar height is same as the cosy one. It may be one of the causes.

This issue might be not about button height but toolbar height.  Maybe, I should change the issue title like this.

**Toolbar height doesn't get smaller when displayDensity is 'compact'**

What do you think about it?

**Comment by tachojelev** [comment]
@tkiryu Yes, I believe this would be more relevant.
The height of the toolbar is indeed the same for both **compact** and **cosy** - 48px. It is 56px for **comfortable**. (This is how they are set in styles) I guess @desig9stein and @simeonoff should have a better idea if this is by-design or should be changed.

**Comment by tkiryu** [comment]
@tachojelev thank you for your opinion. I changed the title.

>Toolbar height for displayDensity = 'compact' is the same as the one for displayDensity = 'cosy'.

**Comment by desig9stein** [comment]
@StefanIvanov @DaniMarinov Do you think that we need to change the height of the toolbar also?
If yes, what should be the height for all density types?

**Comment by StefanIvanov** [comment]
Since the actions (buttons) respect the display density and they are the most common content for the toolbar, I feel that we should reduce the toolbar height to 40px for the compact display density. I also think that 48px for cosy and 56px for comfortable are good and should stay as they currently are. Thank you @tkiryu for pointing this out.

**Comment by DaniMarinov** [comment]
In addition to what @StefanIvanov  mentioned - display density should affect not only height but also left/right paddings.

**Comment by DaniMarinov** [comment]
@tkiryu @StefanIvanov @tachojelev @desig9stein You can check the updated Specification of the Toolbar 
https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Toolbar-Specification#user-interface

**Comment by desig9stein** [comment]
@DaniMarinov Please update the first screenshot with the buttons to show the right padding of the toolbar.

**Comment by DaniMarinov** [comment]
@desig9stein Check it now, I've updated it
