### ISSUE TITLE
[igx-grid] range row selection capability by Shift+Click

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#5004]
## Is your feature request related to a problem? Please describe.
Currently, we can't select multiple rows in a certain range at once. We have to select rows one by one. 

## Describe the solution you'd like
I'd like `igx-grid` to have a capability for range row selection by `Shift+Click` as a built-in feature.

## Describe alternatives you've considered
I've implemented the feature as a directive.

Here is a code.
[range-row-selection.directive.ts](https://gist.github.com/tkiryu/60631af8642e45a007c49a6b5ad01c1f)

## Additional context
Gmail web version has this feature.

**Comment by Lipata** [comment]
@tkiryu We have already logged such a [feature request](https://github.com/IgniteUI/igniteui-angular/issues/3654), so will review it and will implement it as a build in feature. Thank you for the solution with the directive!

**Comment by tkiryu** [comment]
@Lipata , thanks!

**Comment by Lipata** [comment]
@tkiryu We are now going to work on issues #4989 and #4998 and will have some improvements and changes related to cell and row selections. When both are implemented then we can consider again this issue and find a solution in the new context. Until then this issue is held.

**Comment by zdrawku** [comment]
@tkiryu this functionality is not available in the 8.2.0-beta.0 version and will be released with the official 8.2.0 release. You can give it a try and if you have any questions or concerns just share them here.

**Comment by tkiryu** [comment]
@zdrawku , thank you, thank you so much :smile:
