### ISSUE TITLE
odd behavior selecting cells/rows while sorting

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular#504]
### Description  
When sorting is enabled on columns, when a cell is selected rows are resorted for some reason and according to some unknown schema.

### Steps to reproduce  

1. clone https://github.com/jVanZwieten/simple-grid
2. build, run
3. click link "MYGRID"
4. sort by first column
5. select various cells and rows

### Result  
Rows are reordered

### Expected result  
Rows maintain order by sort.

### Attachments  
https://github.com/jVanZwieten/simple-grid

**Comment by kdinev** [comment]
@jVanZwieten Can you check whether you can still reproduce this with the latest version?

**Comment by jVanZwieten** [comment]
I still reproduce this, but I'm not certain I'm using latest version. In node_modules/igniteui-js-blocks/package.json I see ID "_id": "igniteui-js-blocks@5.0.1" which is less than the 5.1.0 I see as latest. To try to get latest, I tried:

1. npm install
2. delete node_modules, then npm install

each led me to my current state. Is there something else I should do to get the 5.1.0 update?

I apologize that I'm not well enough versed with npm to know this yet, but I'm looking forward to learning.

**Comment by kdinev** [comment]
Remove `igniteui-js-blocks` and install `igniteui-angular`

```bash
$ npm install igniteui-js-blocks
npm WARN deprecated igniteui-js-blocks@5.0.1: 
WARNING: This package has moved to igniteui-angular. 
For the latest features, please uninstall this package and run npm install igniteui-angular.
```

**Comment by zdrawku** [comment]
@jVanZwieten are you still reproducing the sorting issue after following the recommendation of kdinev?

**Comment by zdrawku** [comment]
Let us know if the issue is still present and we will reopen the issue.

**Comment by jVanZwieten** [comment]
Indeed, I no longer reproduce this in the latest.
