### ISSUE TITLE
The horizontal scrollbar does not appear/disappear when using the API to change the column width at runtime

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#5048]
## Description  
If all columns fit the grid width(no horizontal scrollbar is needed initially), and a column gets resized by using the API, the horizontal scrollbar does not appear and the user is unable to scroll right in order to see the rest of the data. And reversely - if you change the page, the horizontal scrollbar would appear, but if a column is resized and the scrollbar is not needed anymore, it does not get removed.

 * igniteui-angular version: 7.2.x, 7.3.x
 * browser: n/a

## Steps to reproduce  

In the Grid Percentage dev demo, 
1. Set the ProductName column pinning to false 
2. Create a button that sets the ProductName column width to 50% 
```        
<igx-grid #grid2 [allowFiltering]="true" [data]="data" [autoGenerate]="false" displayDensity="comfortable" width="100%" height="600px" [paging]="true" [perPage]="10">
            <igx-column field="ProductName" [pinned]="false" [movable]="true" header="Product Name" [width]="'19%'" [dataType]="'string'" [sortable]="true" [hasSummary]="false" [editable]="true" [filterable]="true" [resizable]="true">
            </igx-column>
            <igx-column field="UnitsInStock" [pinned]="false" [movable]="true"  header="Units In Stock" width="19%" [dataType]="'number'" [sortable]="true" [hasSummary]="false" [editable]="true" [filterable]="true" [resizable]="true">
            </igx-column>
            <igx-column field="OrderDate" [movable]="true" header="Order Date" width="19%" [dataType]="'date'" [sortable]="true" [hasSummary]="false" [editable]="true" [filterable]="true" [resizable]="true">
                <ng-template igxCell let-cell="cell" let-val>
                    {{val | date:'dd/MM/yyyy'}}
                </ng-template>
            </igx-column>
            <igx-column field="Discontinued" [movable]="true" [resizable]="true"  header="Discontinued" width="15%" [dataType]="'boolean'" [sortable]="false" [hasSummary]="false" [editable]="true" [filterable]="false" [resizable]="true">
            </igx-column>
            <igx-column field="ReorderLevel" header="Reorder Level" [movable]="true" [resizable]="true" [dataType]="'number'" width="19%" [sortable]="false" [hasSummary]="false" [editable]="true" >
                <ng-template igxCellEditor let-cell="cell">
                    <input type="number" [(ngModel)]="cell.value" style="color: black"/>
                </ng-template>
            </igx-column>
        </igx-grid>
       <button igxButton="raised" (click)="toggleWidth('ProductName')">Toggle Width</button>
```
```
    public toggleWidth(name: string) {
      const col = this.grid2.getColumnByName(name);
      col.width = col.width === '50%' ? '19%' : '50%'
      this.grid2.cdr.detectChanges()
    }
```
3. Open http://localhost:4200/gridPercentage

## Result  
Toggling the width does not hide/show the horizontal scrollbar

## Expected result  
The scrollbar to hide/show

## Attachments  

![58034414-34bd2080-7b2f-11e9-8199-6032915d6007](https://user-images.githubusercontent.com/18643062/59289130-076f1880-8c7e-11e9-9a07-b88bcdd62df0.gif)

![58034787-012ec600-7b30-11e9-88b5-dfd242153786](https://user-images.githubusercontent.com/18643062/59289138-0a6a0900-8c7e-11e9-9c4a-ec88ca7f2395.png)

**Comment by MayaKirova** [comment]
Resolved in master with Resize Observer implementation. Related issue - https://github.com/IgniteUI/igniteui-angular/issues/5529
