### ISSUE TITLE
Memory leak when destroying grid based components with different row templates (data rows, group rows, summary rows, hierarchical rows etc.).

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#5053]
## Description  
Memory leak when destroying grid based components with different row templates (data rows, group rows, hierarchical rows etc.).
Components do not get destroyed and remain in memory.

 * igniteui-angular version: 7.2.x, 7.3.x
 * browser: any

## Steps to reproduce  

1. Run the attached sample.
2. Group by "First Name"
3. Click the "Toggle grid existence" button, which will destroy/create the grid (ngIf is used).
4. Open the console and click the "Check all rows are destroyed" button.
5. Observe that only half of the rows have been destroyed.

Also do a Memory Profile in Chrome using the following steps:
1) Do steps from 1 to 3 and do a heap snapshot.
2) Repeat the same steps and take another.
3) Do a comparison between the two and filter all the igx components.
4) Observe what remains after the grid has been destroyed:
![image](https://user-images.githubusercontent.com/10397980/59359074-5ed0bf80-8d36-11e9-9a3e-5dd7296794a4.png)

## Result  
Some components from the grid remain. While they may not leak much in  cases like the karma tests where a large amount of grids are created/destroyed this dramatically increases memory usage and causes the test to timeout in travis.

## Expected result  
When the grid is destroyed all related components inside it should also be destroyed.

## Attachments  
Sample: 
[GridMemLeak.zip](https://github.com/IgniteUI/igniteui-angular/files/3281767/GridMemLeak.zip)

**Comment by kdinev** [comment]
Merged in all branches
