### ISSUE TITLE
[igx-grid] filter row menu transparency issue

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/igniteui-angular#5056]
## Description  
When setting the $header-background theme to a color with some transparency opening the filter row menu results in being able to see through it.

 * igniteui-angular version: 7.3.1
 * browser: Chrome 75.0.3770.80

## Steps to reproduce  

1. Go to [https://stackblitz.com/edit/angular-bpkxrh](url)
2. Click on filter chip under first column header

## Result  
You can see through the filter row menu.
<img width="689" alt="Screen Shot 2019-06-12 at 11 05 01 AM" src="https://user-images.githubusercontent.com/18489991/59362732-f667eb00-8d01-11e9-9437-00c46644392a.png">

## Expected result  
The filter row menu should probably ignore transparency so you don't see what is behind it.

**Comment by mpavlinov** [comment]
@desig9stein The reported version is 7.3.x, but I don't see a PR for 7.3.x branch. Is that on purpose?

**Comment by desig9stein** [comment]
@mpavlinov no, I will create a PR for 7.3.x
