### ISSUE TITLE
routes keep appending to URL when continuously recompiling

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular#506]
### Description  
As I'm working in VSCode with NG listening to saves and recompiling, my routes keep getting appended to the URL on reload.

This happens to any project I start with the ignite cli, doesn't occur with a project started by the nG cli.

### Steps to reproduce  

1. clone https://github.com/jVanZwieten/simple-grid, npm install, npm start
2. open browser to http://localhost:[xxxx]/
3. click link to "MYGRID", URL will now be http://localhost:[xxxx]/mygrid
4. make a change in VSCode, save, recompile will be triggered

### Result  
Page will reload as http://localhost:4200/mygrid/home.
Subsequent click on MYGRID will go to http://localhost:4200/mygrid/mygrid.
Subsequent edit, save, recompile will fail to reload

### Expected result  
Page reloads as http://localhost:4200/ as many times as is recompiled.

**Comment by damyanpetev** [comment]
That's an issue with https://github.com/IgniteUI/igniteui-cli
Too lazy to move, will just close it with a fix :)
