### ISSUE TITLE
keyboard navigation is not working on custom filtering template(Retemplating filter cell)

### ISSUE THREAD

**Issue by prabakaran1311** [IgniteUI/igniteui-angular#5099]
## Description  
I am using angular 7 igx-tree-grid. In that if i am using custom filtering template(Retemplating filter cell). Keyboard navigation is not working input field in filter up, down, forward, backward is not working in filtering template.

 * igniteui-angular version: 7.3.1
 * browser: all browser

## Result  
Custom filtering template keyboard navigation is not working

## Expected result  
Custom filtering template needs keyboard navigation.

**Comment by ddincheva** [comment]
Hello @prabakaran1311 , currently the behavior that you describe is not provided, keyboard navigation in the filter cell move focus always to the filter chip. When you have a custom template, which may be consisted from a different elements, we can not expose predefined behavior. So we will discuss this issue and will try to provide a API you allows you to specify which element of your custom template to be focused.

**Comment by zdrawku** [comment]
@prabakaran1311 with the 9.1.0 release we've added enhanced keyboard navigation support. Now we have header navigation and you are able to navigate through all Grid elements.

Resources:
[Detailed topic on the subject](https://www.infragistics.com/community/blogs/b/engineering/posts/grid-keyboard-navigation-accessibility-)
[Header navigation topic])https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/keyboard_navigation.html#header-navigation_
