### ISSUE TITLE
Is it possible to use virtual scroll instead of pagination in Tree Grid?

### ISSUE THREAD

**Issue by kkseven07** [IgniteUI/igniteui-angular#5117]
I've got a big number of elements inside tree grid component, but pagination is not the best way for my case. Is it possible to use virtual scroll or apply [Angular virtual scroll](https://github.com/rintoj/ngx-virtual-scroller)?

**Comment by rkaraivanov** [comment]
All of the grids have virtual scroll behavior by default. 
[Take a look at this sample for a tree grid with moderate amount of data.](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/aggregations.html).
