### ISSUE TITLE
Show grid column based on User Preferences

### ISSUE THREAD

**Issue by prabakaran1311** [IgniteUI/igniteui-angular#5118]
## Question  
I am using igx-tree grid in angular 7. while loading grid i want to show the grid columns based on user preferences.

is there a way to show column based on user preference.

 * igniteui-angular version: 7.3.2
 * browser: all browser

**Comment by prabakaran1311** [comment]
@astaev is there a way to show columns based on user preference?

**Comment by astaev** [comment]
@prabakaran1311, yes.
The IgxTreeGrid supports column hiding functionality. Here is our sample - https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/column_hiding.html.
Also you can control each column's visibility via Hidden property, which can also be bind as well.

**Comment by prabakaran1311** [comment]
@astaev i am binding remote datas to the grid in component.html file. also grid has remote features like sorting filtering and paging. I want to separately call another api like userpreference and bind that column in Grid. Is there any example or sample available.

**Comment by astaev** [comment]
No, there isn't such an API, you need to implement it on your own.

**Comment by kdinev** [comment]
@prabakaran1311 I would suggest to call your API in your client side service and to augment the collection that you've already bound the grid to with the results of the call. If the user preferences data is a separate collection from the collection you're binding the grid to, then you wouldn't be able to pass it to the grid alongside your original data. You will need to combine both into a single collection.

**Comment by prabakaran1311** [comment]
@kdinev do u want to add separate objects collections for user preference in the same grid data service. Can you give me some sample... thanks

**Comment by kdinev** [comment]
@prabakaran1311 I didn't read your question correctly the first time. I understand that you want to load a different column collection depending on the user choice. Here's an example of how you can do save/restore of columns.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence

The example is based on `localStorage`, but exactly the same logic will apply if your user preferences are saved by your service somewhere.

**Comment by prabakaran1311** [comment]
@kdinev above example shows like grid attributes are created in component.ts file and its looped inside component.html for each column. But i have created grid columns in component.html. Because i have used custom template for header and some of columns. is there a way to implement with component.html file

**Comment by kdinev** [comment]
@prabakaran1311 How are you saving the user preferences and where do you get them from? They cannot be available in the template, unless you pass them in a property in your component. You can still have templates for the headers based on a condition coming from your user preferences column definitions.

**Comment by prabakaran1311** [comment]
@kdinev really i want to use the template because i am showing images in header and also showing images in grid cells. Also i am using custom filtering template. so i have to integrate the user preference in same grid. or else is there a way to show images using property in component?

**Comment by kdinev** [comment]
@prabakaran1311 What I'm saying is you still can have conditional templates, even when your columns are objects coming from the component, like this:

```ts
public ngOnInit() {
    const columnsFromState = this.state.getColumnsForGrid(this.gridId);
    this.columns = this.state.columns && columnsFromState ?
        columnsFromState : this.initialColumns;
}
```

```html
<igx-column *ngFor="let c of columns" [sortable]="true" [movable]="true" [filterable]="true"
            [field]="c.field" [header]="c.header" [dataType]="c.dataType" [pinned]="c.pinned" [hidden]="c.hidden">
  <ng-template *ngIf="c.certainUserPreferenceFlag" igxCellEditor let-cell>
    <!-- custom editor template that would be rendered only if certainUserPreferenceFlag is present -->
  </ng-template>
  <ng-template *ngIf="c.otherUserPreferenceFlag" igxHeader let-column>
    <!-- custom header template that would be rendered only if otherUserPreferenceFlag is present -->
  </ng-template>
</igx-column>
```

**Comment by prabakaran1311** [comment]
@kdinev thanks for your solution one more question i am using custom filtering template how to include custom template in grid. I have attached my sample grid with all the funtions like custom filtering template, custom column, custom cell templates i have used.
![testttt](https://user-images.githubusercontent.com/18000286/60093378-3f169f80-9717-11e9-9e15-563159d1eee1.png)

**Comment by kdinev** [comment]
Same way as in the example above, with an additional `igxFilterCellTemplate`, which is conditionally rendered.

**Comment by prabakaran1311** [comment]
@kdinev i am getting below error while implementing state-persistence below is the screen shot.
In igxstate directive grid id is not calling it shows null value
![errorr](https://user-images.githubusercontent.com/18000286/60328233-db30e880-995b-11e9-8a8b-2059347c41fb.PNG)

**Comment by kdinev** [comment]
@prabakaran1311 I would not be able to tell you where the problem is, based on the screenshot alone. Inspect the first exception that you get, as the following are probably a result of the first one.

**Comment by prabakaran1311** [comment]
@kdinev thanks for your reply. Actually grid objects are not capturing in directive while i console.log(this.grid) it shows as null so grid id also shows null. it causes the issue i have updated the screenshot.
![Capture](https://user-images.githubusercontent.com/18000286/60334123-c3ac2c80-9968-11e9-9c37-e5de524246e3.PNG)

**component.html:** 
                 <igx-tree-grid [id]="gridId" #grid1 igxState [data]="data" childDataKey="Properties" [paging]="true" [perPage]="pageSize" [allowFiltering]="true" width="100%" [height]="null" [isLoading]="true"   [showToolbar]="true" [columnHiding]="true" [autoGenerate]="false" [toolbarTitle]="GridName" [expansionDepth]="expansionDepth" [displayDensity]="'compact'"  (onDataPreLoad)="processData($event,false)" (onSortingDone)="processData($event,true)" (onFilteringDone)="processData($event,false)" [emptyGridMessage]="gridMessageEmpty">

                <igx-column *ngFor="let c of columns" [header]="c.headerText" [field]="c.key" [sortable]="c.sortable" [filterable]="c.filterable" [width]="c.width" [disableHiding]="c.disableHiding" [dataType]="c.dataType" [hidden]="c.hidden" [filters]="c.filters" [formatter]="c.formatter" [cellClasses]="(c.columnCssClass == 'linkClasses')? linkClasses: '' || (c.columnCssClass == 'columnRightAlign')? columnRightAlign: '' || (c.columnCssClass == 'changeCaseCapitalize')? changeCaseCapitalize: ''">
                    <ng-template igxCell let-cell="cell" *ngIf="c.key == 'ImageInd'">
                        <div class="cell__inner">
                            <ng-container>                               
                                    <img src='Content/images/test.png' alt="Bookmarked" width='15' height='15' />
                            </ng-container>
                        </div>
                    </ng-template>
                    <ng-template igxHeader *ngIf="c.key == 'ImageInd'">
                        <div>
                            <img src='Content/images/test.png' alt="Bookmark_head" width='15' height='15' />
                        </div>
                    </ng-template>                    
                </igx-column>
                </igx-tree-grid>

**component.ts**
         ngOnInit(): void { 
            const columnsFromState = this.state.getColumnsForGrid(this.gridId);
            this.columns = this.state.columns && columnsFromState ?
            columnsFromState : this.initialColumns;
        }

not: i am using remote pagination with sorting and filtering like this https://github.com/IgniteUI/igniteui-angular/issues/4736 as example

**state.directive.ts**

// tslint:disable:object-literal-sort-keys
import { AfterViewInit, Directive, Host, OnDestroy, Optional, Self } from "@angular/core";
import { NavigationStart, Router } from "@angular/router";
import {
    DefaultSortingStrategy, FilteringExpressionsTree,
    IFilteringExpression, IgxGridComponent, ISortingExpression
} from "igniteui-angular";
import { take } from "rxjs/operators";

interface IGridState {
    paging: { index: number, recordsPerPage: number };
    selection: any[];
    filtering: FilteringExpressionsTree;
    sorting: ISortingExpression[];
    columns: any[];
}

@Directive({
    selector: "[igxState]"
})
export class IgxGridStateDirective implements AfterViewInit {

    public perPage = 15;
    public selection = true;
    public filtering = true;
    public paging = true;
    public sorting = true;
    public columns = true;
    public shouldSaveState = true;

    public initialState: IGridState = {
        filtering: new FilteringExpressionsTree(0),
        paging: { index: 0, recordsPerPage: this.perPage },
        selection: [],
        sorting: [],
        columns: []
    };

    public gridState: IGridState;

    constructor(@Host() @Self() @Optional() public grid: IgxGridComponent, private router: Router) {
    }

    public ngOnInit() {
        this.loadGridState();
                
        this.router.events.pipe(
            take(1)
        ).subscribe((event: NavigationStart) => {
            this.saveGridState();
        });
    }

    public ngAfterViewInit() {
        this.restoreGridState();
        this.grid.cdr.detectChanges();
    }

    public saveGridState() {
        const pagingState = { paging: this.grid.pagingState };
        this.storeState("paging", pagingState);

        const sortingState = { sorting: this.grid.sortingExpressions };
        this.storeState("sorting", sortingState);

        const filteringState = { filtering: this.grid.filteringExpressionsTree };
        this.storeState("filtering", filteringState);

        const selectionState = { selection: this.grid.selectedRows() };
        this.storeState("selection", selectionState);

        const columnsState = { columns: this.getColumns() };
        this.storeState("columns", columnsState);
    }

    public loadGridState() {
        this.gridState = Object.assign({}, this.initialState);
        for (const propt in this.gridState) {
            if ((this.gridState as any).hasOwnProperty(propt)) {
                this.gridState[propt] = this.getStoredState(propt);
            }
        }
    }

    public restoreGridState() {
        // this.loadGridState();

        // restore filtering
        if (this.filtering && this.gridState.filtering) {
            const gridFilteringExpressionsTree = new FilteringExpressionsTree(this.gridState.filtering.operator);

            for (const f of this.gridState.filtering.filteringOperands) {
                const filtOperand = f as FilteringExpressionsTree;
                let columnsFiltOperands: any;

                // We need to make sure that we have a IFilteringExpression[] to pass to the createExpressionsTree method
                // Depending on filtering logic (AND or OR), filtOperand.filteringOperands returns different content,
                // so we have three cases, where to build IFilteringExpression[], see #1, #2 and #3
                if (filtOperand.filteringOperands.length > 1) {
                    // #1 filtOperand.filteringOperands is an array of IFilteringExpression objects
                    columnsFiltOperands = filtOperand.filteringOperands as IFilteringExpression[];
                } else {
                    columnsFiltOperands = filtOperand.filteringOperands[0] as IFilteringExpression;
                    if (Array.isArray(columnsFiltOperands.filteringOperands)) {
                        // #2 filtOperand.filteringOperands is an array of just one IFilteringExpression\
                        // containing filteringOperands property, which value is an array of IFilteringExpression objects
                        columnsFiltOperands = columnsFiltOperands.filteringOperands;
                    } else {
                        // #3 just an IFilteringExpression object, that we wrap in an array
                        columnsFiltOperands = [columnsFiltOperands];
                    }
                }
                // we pass an array of IFilteringExpression to the createExpressionsTree
                const columnFilteringExpressionsTree = this.createExpressionsTree(columnsFiltOperands, filtOperand);
                gridFilteringExpressionsTree.filteringOperands.push(columnFilteringExpressionsTree);
            }

            this.grid.filteringExpressionsTree = gridFilteringExpressionsTree;
        }

        // restore paging
        if (this.paging && this.gridState.paging) {
            if (this.grid.perPage !== this.gridState.paging.recordsPerPage) {
                this.grid.perPage = this.gridState.paging.recordsPerPage;
                this.grid.cdr.detectChanges();
            }
            if (this.grid.page !== this.gridState.paging.index) {
                this.grid.paginate(this.gridState.paging.index);
            }
        }

        // restore sorting
        if (this.sorting && this.gridState.sorting) {
            const strategy = DefaultSortingStrategy.instance();
            this.gridState.sorting.forEach((expr) => expr.strategy = strategy);
            this.grid.sortingExpressions = this.gridState.sorting;
        }

        // restore selection
        if (this.selection && this.gridState.selection) {
            this.grid.selectRows(this.gridState.selection);
        }
    }

    public storeState(action: string, args: any) {
        if (this[action]) {
            const actionKey = action + "-" + this.grid.id;
            window.localStorage.setItem(actionKey, JSON.stringify(args));
        }
    }

    public getStoredState(action: string, gridId?: string): any {
        console.log("grid objects", this.grid); // grid objects are not loading 
        console.log("grid id", this.grid.id); // Grid id is not calling it shows as null because grid object is not working
        gridId = gridId ? gridId : this.grid.id;
        const actionKey = action + "-" + gridId;
        const item = JSON.parse(window.localStorage.getItem(actionKey));
        return item ? item[action] : null;
    }

    public toggleAction(checked: boolean, action: string) {
        window.localStorage.removeItem(action);
        // if we want to restore paging, it makes sense to work over the same data set
        // therefore we need to reapply filtering as wel
        if (action === "paging" && checked) {
            this.filtering = true;
        }
    }

    public clearStorageForGrid(gridId: string) {
        for (const propt in this.gridState) {
            if ((this.gridState as any).hasOwnProperty(propt)) {
                const actionKey = propt + "-" + gridId;
                window.localStorage.removeItem(actionKey);
            }
        }

    }

    public getColumnsForGrid(gridId: string): any {
        const action = "columns";
        const columns = this.getStoredState(action, gridId);
        return columns;
    }

    /**
     * this method takes every IFilteringExpresion from the columnsFiltOperands
     * and adds it to a FilteringExpressionsTree
     */
    private createExpressionsTree(columnsFiltOperands: IFilteringExpression[],
        filtOperand: FilteringExpressionsTree): FilteringExpressionsTree {
        const columnFilteringExpressionsTree =
            new FilteringExpressionsTree(filtOperand.operator, filtOperand.fieldName);
        const column = this.grid.columns.filter((col) => col.field === filtOperand.fieldName)[0];
        for (const fo of columnsFiltOperands) {
            const columnFiltOperand = fo as IFilteringExpression;
            columnFiltOperand.condition = column.filters.condition(columnFiltOperand.condition.name);
            if (column.dataType === "date") {
                columnFiltOperand.searchVal = new Date(Date.parse(columnFiltOperand.searchVal));
            }
            columnFilteringExpressionsTree.filteringOperands.push(columnFiltOperand);
        }
        return columnFilteringExpressionsTree;
    }

    private getColumns() {
        const gridColumns = this.grid.columns.map((c) => {
            return {
                headerText: c.header,
                key: c.field,
                width: c.width,
                dataType: c.dataType,
                columnCssClass: c.cellClasses,
                sortable: c.sortable,
                filterable: c.filterable,
                formatter: c.formatter,
                hidden: c.hidden,
                filters: c.filters,
                disableHiding: c.disableHiding,
            };
        });
        return gridColumns;
    }
}
// tslint:enable:object-literal-sort-keys

**Comment by kdinev** [comment]
The problem is you're trying to load the stat `onInit`. Move the login in `ngAfterViewInit`.

**Comment by prabakaran1311** [comment]
@kdinev sorry its my mistake i am using igxtreegrid instead of i am calling igxgridcomponent method thats why grid obects are not loaded. thanks for your help

**Comment by prabakaran1311** [comment]
@kdinev i need to reset the grid to its original state(if user already set any preference) while user wants to reset the grid to original initial stage on button click. i tried to load the initial values to grid but its not resetting the grid. Is there a way to reload the grid without reload the whole page.

**Comment by kdinev** [comment]
@prabakaran1311 Setting the initial state should be exactly the same as setting a user preferences state. Can you show an example of how you reset the grid state?

**Comment by prabakaran1311** [comment]
@kdinev below is my code,

    public resetGridPreferences() {
        this.state.clearStorageForGrid(this.gridId); // cleared the localstorage
        this.columns = this.initialColumns;   //initial columns are stored in columns
        this.cdr.detectChanges();
    }

**Comment by kdinev** [comment]
@prabakaran1311 The issue is that you're changing the reference of the `columns` property, instead of just changing the array members inside the columns array. The `detectChanges()` call should catch this thought. @hanastasov @rkaraivanov can you guys take a look at why this is not working?

**Comment by hanastasov** [comment]
> @prabakaran1311 The issue is that you're changing the reference of the `columns` property, instead of just changing the array members inside the columns array. The `detectChanges()` call should catch this thought. @hanastasov @rkaraivanov can you guys take a look at why this is not working?

Sure, @prabakaran1311  I will update you shortly on that.

**Comment by hanastasov** [comment]
@prabakaran1311  this works even without manually calling the changeDetection. Please see [this sample](https://stackblitz.com/edit/angular-nbf3cs).
