### ISSUE TITLE
Pressing Ctrl + Arrow Up inside a second layout child inside a Hierarchical Grid scroll to the first child.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#5127]
## Description  
When pressing Ctrl + Arrow Up when a cell is selected inside a second child grid, the parent grid scrolls to the top position of the first child instead of the second.

 * igniteui-angular version: 7.3.x
 * browser: any

## Steps to reproduce  

1. Open the second grid in the "Hierarchical Grid" demo
2. Expand the first row
3. Select a cell in the second grid
4. Press Ctrl + Arrow Up

## Result  
The parent grid scrolls to the top of the first child grid

## Expected result  
The parent grid should scroll to the top of the second child grid instead.

## Attachments
![Issue#5127](https://user-images.githubusercontent.com/3768136/59775950-ad440800-92ba-11e9-8f43-6af91ea597a8.gif)

**Comment by ChronosSF** [comment]
@skrustev , this doesn't reproduce anymore - you can close it if you can confirm

**Comment by radomirchev** [comment]
@skrustev , @ChronosSF any update on the issue?

**Comment by VMihalkov** [comment]
I was unable to reproduce the issue
