### ISSUE TITLE
The grid header doesn't seem to be working with variable data.

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular#5131]
## Description  
When creating a new grid with columns and their headers, the header is only updated on the first change of the variable. If I update its text, it's not reflected in the grid.

Example:

```html
<igx-grid #grid id="grid" [data]="topShareholders">
    <igx-column field="id" [sortable]="true" [header]="'General.Id' | translate"></igx-column>
    <igx-column field="displayName" [sortable]="true" [header]="nameHeader"></igx-column>
</igx-grid>
```
I've tried it both ways, using the tag and a variable. This is how I update `nameHeader`:

```typescript
ngOnInit(): void {
    this.updateHeaders();
    this.translationService.onLanguageChanged.subscribe(() => this.updateHeaders());
}

updateHeaders(): void {
    this.translationService.getText('General.Name').subscribe(t => this.nameHeader = t);
}
```

Only on the first `updateHeaders()` call the grid is updated. For subsequent calls it remains with its previous value, even though `nameHeader` has been updated.

How to update the header text of a grid?

 * igniteui-angular version: 8.0.0
 * browser: Firefox/Chrome/Safari

## Steps to reproduce  

1. Create a grid
2. Add a variable as the text of the header
3. Try to change the variable's text 
4. The header won't reflect that change

## Result  
The header's text is not updated.

## Expected result  
It should update.

**Comment by bkulov** [comment]
Hi @eestein,

I order to keep the grid fast we're using OnPush change detection strategy. When the underlying property (`this.nameHeader`) is changed the binding changes the value of the column header but the parent grid doesn't know about this change. In order to force the grid to reflect the change you could do the following:
- get access to the grid in the component by adding a ViewChild property:
  `@ViewChild('grid', { read: IgxGridComponent }) grid: IgxGridComponent;`

- in the subscribe method where you're changing the value of `this.nameHeader` property force the grid to reflect changes by executing `markForCheck` method:
`updateHeaders(): void {
    this.translationService.getText('General.Name').subscribe(t => {
         this.nameHeader = t;
         this.grid.markForCheck();
    });
}`

After marking the grid for check it will reflect any changes on the next change detection cycle.

We will consider improving the column's `header` property to reflect changes to the grid. I'll mark this issue as a feature request and we will add to our backlog.

**Comment by eestein** [comment]
@bkulov Thanks, it worked. I'm going to leave it to your discretion when to close the issue, since it's something you're working on.

**Comment by eestein** [comment]
@bkulov actually I spoke too soon... it does update the headers, but only after I perform some action on the grid like scrolling. Any ideas on why? Thanks.

**Comment by bkulov** [comment]
Hi @eestein,
You can try putting `this.grid.markForCheck` in `requestAnimationFrame`. Something like this: `requestAnimationFrame(() => this.grid.markForCheck());`.

Check this sample:
https://stackblitz.com/edit/github-9srzyb

There's a button bellow the grid which changes the title of the first column when pressed.

**Comment by eestein** [comment]
@bkulov it is still not working... I've tried `requestAnimationFrame`, `setTimeout` and `ngZone`, nothing worked. Do you think it might be related to the version I'm using? I noticed your stackblitz sample is using ignite and angular version 7 while I'm running on version 8 of both angular and igniteui.

Here's part of my dependencies:

```json
"@angular/animations": "~8.0.1",
"@angular/common": "~8.0.1",
"@angular/compiler": "~8.0.1",
"@angular/core": "~8.0.1",
"@angular/forms": "~8.0.1",
"@angular/platform-browser": "~8.0.1",
"@angular/platform-browser-dynamic": "~8.0.1",
"@angular/router": "~8.0.1",
"igniteui-angular": "^8.0.0",
```

Please take a look at this gif (screen recording) showing the output. It works with everything else, but the grid:

https://media.giphy.com/media/j3hTfDxUm69cYkXcum/giphy.gif

**Comment by bkulov** [comment]
@eestein If you can send me a simple working application (stackblitz is also fine) I can take a look. The sample I sent you in my last message is working fine. I doubt the different versions can cause the issue but will double check.

**Comment by bkulov** [comment]
I've update my sample to Angular 8 / Igniteui for Angular 8 and it's working fine:
https://stackblitz.com/edit/github-9srzyb-z2wcqd

Probably there is a sync issue in your code.

**Comment by rkaraivanov** [comment]
@eestein 
Here is the same [sample ](https://stackblitz.com/edit/github-9srzyb-28loek)emulating your rxjs pipeline

**Comment by eestein** [comment]
@bkulov yes... I've just updated your sample to mimic my exact behavior and it works. I have no idea what might be going on here then... crazy! 

Anyway, I'll see what else I can try here... Thanks

**Comment by eestein** [comment]
I give up... it's working now... even though I'm always developing using the private tab, there might've been some sort of caching issue, because the only thing I did was to restart the browser...

Thanks again

**Comment by zdrawku** [comment]
@eestein I am closing this issue, I can see that everything is working fine now
