### ISSUE TITLE
How to address and remove Warning Messages igniteui-angular 8.0.0

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#5132]
## Description  
Warning messages display inside the Google Chrome Developer Tools Console.
I understand that there may be features that have been deprecated.
What do I need to do to address and remove these Warning Messages?

 * igniteui-angular version: 8.0.0
 * browser: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

## Steps to reproduce  

1. Run Angular App in browser using Angular CLI ng serve command
2. Open Google Developer Tools Console
3. Warning Messages display inside Google Developer Tools Console
    onOpen: 'onOpen' @Output property is deprecated. Use 'onOpened' instead.
    te @ igniteui-angular.js.pre-build-optimizer.js:5517

    t.onClose: 'onClose' @Output property is deprecated. Use 'onClosed' instead.
    te @ igniteui-angular.js.pre-build-optimizer.js:5517

    t.onFocusChange: onFocusChange event is deprecated. Use onGridKeydown event instead.
    te @ igniteui-angular.js.pre-build-optimizer.js:5517

## Result  
What is the actual result after following the steps to reproduce?
Warning Messages displays in Google Developer Tools Console

## Expected result  
What is the expected result after following the steps to reproduce?
No Warning Message displays in Google Developer Tools Console

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

![warning-messages](https://user-images.githubusercontent.com/6993852/59819929-8c49da00-92ef-11e9-8f92-2f8e131f223b.PNG)

**Comment by ViktorSlavov** [comment]
@brookhutchinson this appears to be a bug on our end - we are using the deprecated properties internally and that's what causes the warning.

@bkulov , @SAndreeva - in the date-picker control, we're calling the [`onClose`](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts#L1197) and [`onOpen`](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts#L1184) emitters which have the DeprecateProperty decorator

@zdrawku - in the grid component, we're calling [`onFocusChanged`](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.component.ts#L1495) emitter which has the DeprecateProperty decorator
