### ISSUE TITLE
[ng-add] Adding polyfills in Angular 8 project leads to compile error

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#5136]
## Description  
Polyfills added from `ng-add` schematic lead to compile error because of missing `core`

 * igniteui-angular version: 8.0.0
 * browser: N/A

## Steps to reproduce  

1. ng new my-example project && cd my-example-project
2. ng add igniteui-angular@latest
3. When asked if you'd like to add polyfills, answer `Y`es
4. ig start

## Result  
The project fails to compile.
Console throws an error:
```bash
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/object'
```

## Expected result  
Project compiles w/o error and starts properly

## Attachments  
![image](https://user-images.githubusercontent.com/24314672/59846511-c3100680-9368-11e9-9e87-636e123db023.png)

**Comment by damyanpetev** [comment]
Related to the build optimizations in Angular 8, where the polyfils are now handled mostly by the build and produced as conditional load module scripts. With that change new Angular projects no longer have core-js listed in the main dependencies (moved to dep of `@angular-devkit/build-angular`) and thus the compilation error.

We have two options - either additionally install the package though the ng add schematic (with the accompanying version juggling) or refactor the usage of `Object.entries`.
After talking with @ChronosSF we agree the extra package install seems a bit excessive for the simple usage we have that can easily be replaced. I'll swap those out for `Object.keys` most likely.
