### ISSUE TITLE
Calendar imports BrowserModule needlessly

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular#516]
### Description  
None of the `Browser*` modules should be directly imported in our component modules as this breaks
lazy loading.

https://github.com/IgniteUI/igniteui-angular/blob/63ee575006194316493f691fe7f1d80dbb6587dc/src/calendar/calendar.component.ts#L14

https://github.com/IgniteUI/igniteui-angular/blob/63ee575006194316493f691fe7f1d80dbb6587dc/src/calendar/calendar.component.ts#L539

**Comment by Eralmidia** [comment]
It also breaks igx-datePicker. I'm assuming this uses the calender component?

**Comment by ddincheva** [comment]
Yes, DatePicker Component uses Calendar Component.

**Comment by kdinev** [comment]
@Eralmidia @ddincheva The fix is now available in version 5.1.3. 

https://github.com/IgniteUI/igniteui-angular/releases/tag/5.1.3
