### ISSUE TITLE
On IE11, exception is thrown when Range object is initialized on grid selection

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#5168]
## Description  
On IE11, exception is thrown when `new Range()` is called in grid-selection.ts.

 * igniteui-angular version: 
 * browser: IE11

## Steps to reproduce  

1. Run the dev sample of 7.3.6
https://github.com/IgniteUI/igniteui-angular/releases/tag/7.3.6
2. Open a grid sample

## Result  
Exception is thrown at https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/core/grid-selection.ts#L215

## Expected result  
No exception is thrown.

**Comment by kdinev** [comment]
@ymita New patch versions will be released today to fix this issue.

**Comment by ymita** [comment]
@kdinev @rkaraivanov Thank you for the patch release! This helps us deliver the feature to our customer in a timely manner.
