### ISSUE TITLE
[igx-grid] Column % widths should calculate from remaining space excluding pixel width columns

### ISSUE THREAD

**Issue by ig-robstoffers** [IgniteUI/igniteui-angular#5201]
## Question  
Currently the grid seems to be calculating percent widths for columns based on the full grid width.  This will work if all your columns use percent widths.  However this will not work as I would expect if you mixed some pixel width columns with percent width ones.  For example, take a look at this sample:

https://stackblitz.com/edit/angular-ecvsrv

The first column has 60% width, the second has 40% and the third has 80px. Since the % width is calculated from the full grid width the third column is pushed out of view.  I would expect that the 3rd column would remain in view and the 60/40 % widths would be calculated from the remaining visible space.  The goal is to be able to resize the grid to any size and keep the same proportions between the first and second columns while the 3rd column remains at 80px and in view.

Is there a way to achieve what I'm looking for without dynamically calculating the column widths every time I resize the grid?  Or is this a bug?

 * igniteui-angular version: 7.3.5
 * browser: Chrome

**Comment by mpavlinov** [comment]
I don't see this scenario covered in the [specification](https://github.com/IgniteUI/igniteui-angular/wiki/igxGrid-Specification). Will investigate.

**Comment by mpavlinov** [comment]
It turns out that this is a known limitation that's documented here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#known-limitations. I updated the specification with the known limitations from the topic.
You'll have to manually handle this case in your application.
