### ISSUE TITLE
Slider label is not correctly positioned in IE

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#5210]
## Is your feature request related to a problem? Please describe.
Slider labels and texts could not be positioned correctly.

## Describe the solution you'd like
We would like the have an identical representation as to the other browsers.

## Describe alternatives you've considered
The label which is held by the thumb should become a separate component.

## Additional context
Chrome:
![Capture](https://user-images.githubusercontent.com/7037740/60189867-526e5b80-983a-11e9-8061-1cdc97c8b729.PNG)
IE:
![Capture1](https://user-images.githubusercontent.com/7037740/60189871-539f8880-983a-11e9-9ba1-e6670cb94eb8.PNG)

**Comment by nrobakova** [comment]
This issue is related to the bug #4561
