### ISSUE TITLE
Grid layout is broken when commit transaction and there is cell/row in edit mode

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#5215]
## Description  
 * igniteui-angular version: 8.0.x; 7.3.x
 * browser: all

## Steps to reproduce  

1. Open HierarchicalGridUpdating or TreeGrid dev samples
2. Delete the first row
3. Enter either rowEdit or set cell in edit mode
4. Commit the transaction

## Result  
![image](https://user-images.githubusercontent.com/34240583/60243959-17b00600-98c2-11e9-8d1d-7433733ae89f.png)

![image](https://user-images.githubusercontent.com/34240583/60244135-6d84ae00-98c2-11e9-92fa-c676cd59e90a.png)

## Expected result  
The changes that are made should be commit and the row/ cell should exit edit mode.

**Comment by wnvko** [comment]
This is application scenario. Before call:
`this.grid1.transactions.commit(this.data, this.grid1.primaryKey, this.grid1.childDataKey);`
you should exit edit mode like this:
`this.grid1.endEdit(true);`
