### ISSUE TITLE
"In" condition filter cannot be created with the IgxFilteringOperand.condition(name) method

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#5216]
## Description  
If you select more than 2 values in the Excel style filtering UI, "in" condition filter is applied, but the IgxFilteringOperand.condition(name) method won't create an instance of this condition.

 * igniteui-angular version: 7.2.x
 * browser: NA

## Steps to reproduce  

1. Run the attached sample.
3. Apply filter with more than two selected values in the Excel style filtering UI of any column.
4. Navigate to the ABOUT page.
5. Go back.

## Result  
Exceptions are thrown in the console.

## Expected result  
No exceptions should be thrown and the applied filter should be loaded.

## Attachments
[qdjamvynxvm.angular.zip](https://github.com/IgniteUI/igniteui-angular/files/3381868/qdjamvynxvm.angular.zip)

**Comment by rondo104** [comment]
If you select more than 2 values in the Excel style filtering UI, and If in the column there are some cells without date values _(for example we got null for some values and these cells are empty)_ we got an error:
```
ERROR TypeError: Cannot read property 'getFullYear' of null
    at IgxDateFilteringOperand.push../node_modules/igniteui-angular/fesm5/igniteui-angular.js.IgxDateFilteringOperand.findValueInSet (igniteui-angular.js:25550)......
```

**Comment by DiyanDimitrov** [comment]
@rondo104, Could you please create a new issue for this scenario? The best way for us to help you is if you provide a small isolated sample where the issue is reproducible.

**Comment by rondo104** [comment]
> @rondo104, Could you please create a new issue for this scenario? The best way for us to help you is if you provide a small isolated sample where the issue is reproducible.

I think it's a library bug. For colum filter which has data type "_Date_".
For data type "_String_" this case works fine. 

![image](https://user-images.githubusercontent.com/13147055/62610835-1afccf80-b90d-11e9-8255-630259b6efcd.png)

![image](https://user-images.githubusercontent.com/13147055/62610855-251ece00-b90d-11e9-89a5-438caab56762.png)

![image](https://user-images.githubusercontent.com/13147055/62610886-3536ad80-b90d-11e9-9b0b-0e818a61e923.png)

**Comment by DiyanDimitrov** [comment]
@rondo104, Yes, that's an issue in the component. It was already submitted #5551.
