### ISSUE TITLE
Calendar and DatePicker: Need description about dependency on Animation Module

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#522]
### Description  
Calendar and DatePicker are dependent on BrowserAnimationsModule. It should be described in README.
https://github.com/IgniteUI/igniteui-angular/issues/516

**Comment by rkaraivanov** [comment]
Already fixed with #518

**Comment by kdinev** [comment]
This issue is for the readme update. Reopening.
