### ISSUE TITLE
Cannot navigate through filter row when there are column groups and the grid is empty

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5224]
## Description  
Cannot navigate through filter row when there are column groups and the grid is empty

 * igniteui-angular version: 8.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridColumnGroups
2. Open filter for column ContactTitle and filter with not existing value
3. Click on Close button
4. Filter is selected
5. Press Tab key 2 times

## Result  
Filter for column ID is not focused

## Expected result  
Filter for column ID should be focused

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by DiyanDimitrov** [comment]
The issue seems to be caused by the keyboard navigation which is using the forOf instance of the header when there is no rows, but the header forOf contains column groups instead of columns.

**Comment by nrobakova** [comment]
This issue is no longer reproducible with the new keyboard navigation in 9.1
