### ISSUE TITLE
Unit Tests for IgxGridComponent

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#5230]
## Question  
How do I write unit tests for the IgxGridComponent inside of an Angular Component?

I have an Angular Component that has an IgxGridComponent.  I would like to add unit tests to the component.spec.ts file to test the functionality of the IgxGridComponent.

Assume that I have a functional grid that has data populating inside the grid, custom column headers, grid buttons are above the grid, grid column sorting is enabled, grid column filtering is enabled, grid column pinning is enabled, grid column hiding is enabled.

Does anyone have advice for how to write unit tests to test the functionality of the IgxGridComponent?

 * igniteui-angular version: 8.0.0
 * browser:

**Comment by kdinev** [comment]
We don't have documentation on our website for this, but you can take a look at the spec files inside the repository. You can start with the [grid.component.spec](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts)

**Comment by kdinev** [comment]
You can also use this [guideline](https://github.com/IgniteUI/igniteui-angular/wiki/General-Naming-and-Coding--Guidelines-for-Ignite-UI-for-Angular#test-implementation-guidelines).

**Comment by brookhutchinson** [comment]
Thank you for your advice

**Comment by kdinev** [comment]
@brookhutchinson Closing the issue for now. Please reopen if you need further guidance.
