### ISSUE TITLE
Igx-select dropdown doesn't render at correct position when outlet is igx-grid

### ISSUE THREAD

**Issue by VladB93** [IgniteUI/igniteui-angular#5249]
## Description  
Describe the issue.

 * igniteui-angular version: all
 * browser: all

## Steps to reproduce  

1. Pull branch from here https://github.com/IgniteUI/igniteui-angular/pull/5116
2. Set the `overlaySettings `in the `grid.component.html` `igx-select` ( the paginator template) to outlet in the grid. E.g 

` <igx-select [(ngModel)]="api.perPage" [displayDensity]="paginatorSelectDisplayDensity()" type="border" [overlaySettings]="{outlet: api.outlet}">`
3. Open demos. Click on the select

## Result  
Select dropdown is not positioned correctly.

## Expected result  
Select dropdown should be positioned correctly.

**Comment by IvayloG** [comment]
Currently,  an igx-paginator is used as a template and this issue is no longer reproducible.
