### ISSUE TITLE
Submitted date value is changed when 'formatter' is used

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5257]
## Description  
This issue is caused by the formatter or the actual code configuration that is applied. When the formatter is removed or return the Date object directly, everything is working as expected.

 * igniteui-angular version: 7.3.5
 * browser: n/a

## Steps to reproduce  

1. [Open the sample](https://stackblitz.com/edit/angular-date-picker-with-custom-formatter)
2. Type in value "55/55/5555"
3. Click on the Date icon in order to open the date-picker (drop down mode is used)
4. Select a date (e.g. 10 of July)

## Result  
Initially "07/10/2019" is filled in the input, although within a second "55/55/5555" appears

## Expected result  
Selected date value to remain "07/10/2019"

**Comment by Aleksandyr** [comment]
@zdrawku The issue is not reproducible anymore with the latest 8.2.0
