### ISSUE TITLE
igx-column filtering broken

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#526]
### Description  
When definng the following column with version 5.1.3: 

`<igx-column field="LogDate" [header]="translatePipe.transform('Log date/time')" [filtering]="true" [sortable]="true"></igx-column>`

I get an error saying filtering is not a known property of igx-column.

### Steps to reproduce  

1. Create a igx-grid
2. Enable filtering for a column

### Result  
Error: Can't bind to 'filtering' since it isn't a known property of 'igx-column'.

### Expected result  
Working filtering feature

**Comment by kdinev** [comment]
@Eralmidia The property is renamed to `filterable` for consistency with `sortable`. I will mark the issue as documentation, as the readme and the docs page have yet to be updated.

**Comment by Eralmidia** [comment]
Ah, thanks for the info. I actually spotted that inconsistency (filtering vs sortable) myself when trying the grid. Good to see consistently named properties.
