### ISSUE TITLE
non-primary click clears selection in hierarchical grid

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5262]
## Description  
non-primary click clears selection in hierarchical grid

 * igniteui-angular version: 8.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGridUpdating
2. Select a range
3. Right/middle click on any cell in the grid

## Result  
Selection is cleared

## Expected result  
Selection should not be cleared

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ddincheva** [comment]
This problem has been already fixed in our latest versions (9.1.x, 10.1.x, and 10.2x);
