### ISSUE TITLE
Localization List Component

### ISSUE THREAD

**Issue by rondo104** [IgniteUI/igniteui-angular#5280]
## Description  
Absent ability to localize List Component in the grid.
File path where describe mesages:
_projects/igniteui-angular/src/lib/list/list.component.html_ 

**_Absent localization for messages:_**
1. - There are no items in the list.
2. - Loading data from the server...

 * igniteui-angular version: ~7.3.1
 * browser: N/A

## Result  
Can't localized List Component in the grid. 

## Expected result  
Can localized List Component in the grid.

**Comment by rkaraivanov** [comment]
@rondo104 
The list component exposes the `igxEmptyList` directive where you can template and localize the content.
You can check [how to use it](https://www.infragistics.com/products/ignite-ui-angular/angular/components/list.html#usage) and [check this example](https://stackblitz.com/edit/angular-atgqht).

**Comment by kdinev** [comment]
@rondo104 Use the template empty list template that @rkaraivanov suggested until we add the default list strings to our i18n resources. We don't have the default list strings in the localization resources and we would have to add them.

**Comment by radomirchev** [comment]
@rondo104 , the feature request is in the list for the current milestone. You could follow the milestone progress on the [Roadmap board](https://github.com/orgs/IgniteUI/projects/122) or in the [Roadmap file](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md)
