### ISSUE TITLE
Introduce an input to set FilteringStrategy per column in IgxGrid

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#5323]
## Is your feature request related to a problem? Please describe.
Currently an approach to provide custom logic for filtering per column means to make a custom filter operands that requires ALL filtering conditions to be implemented by the developer. Another approach would be to filter the underlying datasource and pass a filtered data collection as data source to the grid. Both approaches are not effective and it would be best if the developer can provide a custom filteringStrategy per column.

## Describe the solution you'd like
Being able to pass a filtering strategy for a column:
```html
<igx-column filteringStrategy="customFilteringStrategyInstance">
</igx-column>
```

## Describe alternatives you've considered
Currently an approach to provide custom logic for filtering per column means to make a custom filter operands that requires ALL filtering conditions to be implemented by the developer., which makes the approach ineffective.

Another approach would be to filter the underlying datasource and pass a filtered data collection as data source to the grid.

**Comment by kdinev** [comment]
Related #5448

**Comment by kdinev** [comment]
@hanastasov Is there a scenario that cannot be satisfied with a `CustomFilteringOperand`? The idea behind the operands is to provide custom per-column strategies.

**Comment by hanastasov** [comment]
> @hanastasov Is there a scenario that cannot be satisfied with a `CustomFilteringOperand`? The idea behind the operands is to provide custom per-column strategies.

I don't find a scenario that could not be satisfied with a `CustomFilteringOperand`.  What I find not the best experience is that the dev needs to write the filtering logic for all conditions, even if the dev only wants to do filtering via a nested value, for example.

**Comment by kdinev** [comment]
To filter by complex object would require to override all operand, but with a filtering strategy, the operations would still execute through the operand, which means that all of them would still require to be overridden.

**Comment by hanastasov** [comment]
> To filter by complex object would require to override all operand, but with a filtering strategy, the operations would still execute through the operand, which means that all of them would still require to be overridden.

Wouldn't one be able to unwrap the value from the complex object on filtering strategy level ? In such case, one would not need to override the operands as well:
`export class CustomFilteringStrategy extends FilteringStrategy  {
    protected getFieldValue(rec: object, fieldName: string): any {
        return rec[fieldName]["fieldToGetValueFrom"]
    }
}`

**Comment by kdinev** [comment]
@hanastasov I guess that is right, but this can still be handled in the top-level filtering strategy provided to the grid, can't it?

**Comment by hanastasov** [comment]
> @hanastasov I guess that is right, but this can still be handled in the top-level filtering strategy provided to the grid, can't it?

There is no exposed way for a dev to provide a filtering strategy for the grid, but even if there is, it will work on grid level, not per column.

**Comment by kdinev** [comment]
@hanastasov OK, if the grid-level strategy is not exposed, then we should expose it.
