### ISSUE TITLE
datePicker cropping issue

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#533]
### Description  
Sometimes it's a problem that the datePicker popup is actaully rendered at the place you insert the igx-datePicker tag. If the containing element (or ancestors) provide constraints in height/width, parts og the datePicker is hidden. See attached image.

### Steps to reproduce  

1. Add a igx-datePicker component to a container with for instance height, width and overflow: hidden.

### Result  
datePicker is hidden from view

### Expected result  
The ability to choose that the datePicker is rendered more like a dialog. I've seen other frameworks solve this by adding a "overlay container", typically an element high up in the DOM hierarchy, and attach popups and such on this element instead.

### Attachments  
![igx-datepicker cropped](https://user-images.githubusercontent.com/12936286/35620671-1e195786-0682-11e8-9c37-350e5e22086b.PNG)

**Comment by kdinev** [comment]
@damyanpetev Is the `NavDrawer` implemented with a detached container? What were the issue there?

**Comment by damyanpetev** [comment]
@kdinev All the drawer DOM should be inside the component itself, it is however fixed and has some z-index to it too.

**Comment by Eralmidia** [comment]
I looked some more at the CSS for both the igx-datePicker and our current tab component (not igx). It seems like the tab parent container assigns display: relative and z-index: 1, which breaks the fixed positioning of the date picker. I agree that this is not an issue with igx-datePicker, and that this issue can be closed.
