### ISSUE TITLE
When change column groupable to true the horizontal scroll dispersal 

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5340]
## Description  
When change column groupable to true the horizontal scroll dispersal 

 * igniteui-angular version: 8.0
 * browser: n/a

## Steps to reproduce  

1. Open the sample [link](https://stackblitz.com/edit/angular-wotpov-tqlxgd?file=src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html)
2. Click on button changeGroupable
3. Scroll vertocal

## Result  
As the groping is previewed the horizontal scroll is not longer visible

## Expected result  
The horizontal scroll should be visible

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/60787978-2d47ea00-a164-11e9-9f51-573ad8a1cfe8.png)

**Comment by ChronosSF** [comment]
@nrobakova , is there a customer waiting on this issue?

This is fixed nicely with the resize observer but that is getting merged for 8.2 only so I am wondering if it will be ok to resolve this there only.

**Comment by nrobakova** [comment]
@ChronosSF this is an internal issue and no client is waiting for it. I think it will be ok this bug to be fixed in 8.2 only.
