### ISSUE TITLE
When change the grid width to bigger, not all columns are visible

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5342]
## Description  
When change the grid width to bidder, not all columns are viable

 * igniteui-angular version: 8.1
 * browser: n/a

## Steps to reproduce  

1. Open the [sample ](https://stackblitz.com/edit/angular-wotpov-dxv8uz?file=src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html)
2. Scroll horizontal
3. Click on button changeWidth

Note: this bug can be related to the bug #5339 
## Result  
First columns are not visible

## Expected result  
All the columns should be visible

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/60790471-3f2c8b80-a16a-11e9-9a65-7cf59ccf8110.png)

**Comment by ChronosSF** [comment]
@nrobakova , are you sure this is the right sample for this issue? I tried it out and can't reproduce based on the steps. This is what I did:

![issue1](https://user-images.githubusercontent.com/2188411/60792972-5e79e780-a16f-11e9-8c6c-ed54a08c7672.gif)

After clicking the button the columns do match the column definitions exactly.

**Comment by nrobakova** [comment]
@ChronosSF sorry for the wrong sample. In the sample version is 8.0.0. If you copy the sample in the Dev samples in master(8.1) the issue is reproducible. 
I am adding regression label to this bug.

**Comment by nrobakova** [comment]
@MayaKirova this bug and bug #5339 are regressed by the PR #5277

**Comment by MayaKirova** [comment]
@nrobakova  The fix in #5277 affects only scenarios where the grid is initialized in detached state and is later attached, hence the related code will not be hit in either of those bugs.
