### ISSUE TITLE
When a root row is expanded and filter on root level in the child vertical scroll is not correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5344]
## Description  
When a root row is expanded and filter on root level in the child vertical scroll is not correct

 * igniteui-angular version: 8.1
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGrid
2. In the first grid exapand first row
3. In column ProductName apply firer with condition Contains and value A0
4. Scroll in the child grid

Note: If in p.4 expand a row in the child and then reset filter, the scrollbar in the child grid dissapears

## Result  
The width of the child is changed and there is empty space in the grid

## Expected result  
The width of the child should not be changed

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/60792928-486c2700-a16f-11e9-93b0-ecc6ae8497c8.png)

**Comment by ChronosSF** [comment]
@nrobakova , this doesn't seem to reproduce anymore. Could you please check and close it if this is the case?

**Comment by nrobakova** [comment]
@ChronosSF now the scrollbar position is correct but the the grid is still resizing after scrolling.
Steps to reproduce:
1. Open dev sample hierarchicalGrid
2. In the second grid expand first row
3. In the child grid expand firs row
4. Filter column Col1 in the the child grid with value 0
5. Scroll down the child grid
Its size is changed:
![hgridScrollChild](https://user-images.githubusercontent.com/11463104/72238504-982c1f00-35e6-11ea-864f-b08f1ab36814.gif)

**Comment by dkamburov** [comment]
@nrobakova I can't seem to reproduce this now and I believe it was resolved with https://github.com/IgniteUI/igniteui-angular/pull/6525

**Comment by VMihalkov** [comment]
@nrobakova I can't seem to reproduce this in 8.2.x and master.

**Comment by nrobakova** [comment]
This issue is no longer reproducible
