### ISSUE TITLE
Data is not displayed when set forOf igxForItemSize in pixels and scroll orientation is horizontal

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#5349]
## Description  
 * browser: all

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-4w8rla)
2. There is only two items displayed
3. If you set igxForItemSize  as number all elements are displayed

## Result  
The passed data is not virtualized when set the container size in pixels
![image](https://user-images.githubusercontent.com/34240583/60807974-dd7f1800-a18f-11e9-8693-f6151764414f.png)

## Expected result  
The passed data should be virtualized and should be able to scroll horizontally.
![image](https://user-images.githubusercontent.com/34240583/60808032-03a4b800-a190-11e9-983e-a0c167057cdf.png)

**Comment by MayaKirova** [comment]
Adding sample with flex styles so that additional item, added by virtualization for smooth scrolling, does not render in separate row: 
https://stackblitz.com/edit/angular-4w8rla-fbtnts
