### ISSUE TITLE
How to change the font style, font size, font color of title inside <igx-dialog>

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#5357]
## Question  
How do I change the font style, font size, and font color of the title inside <igx-dialog> ?

 * igniteui-angular version: 8.0.3
 * browser: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by zdrawku** [comment]
@brookhutchinson, if I can help with anything else, please do let me know
