### ISSUE TITLE
In IE11 cannot change slider value with mouse drag

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5359]
## Description  
In IE11 cannot change slider value with mouse drag

 * igniteui-angular version: 8.1
 * browser: IE11

## Steps to reproduce  

1. Open dev sample slider in IE11
2. Tru to move slider thumbs with the mouse

## Result  
Value cannot be changed

## Expected result  
It should be able to change slider value

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Aleksandyr** [comment]
@simeonoff Could you please consider looking into that issue. Because I've replaced the styles from the previous version of the slider and everything worked well.
