### ISSUE TITLE
In Edge the row drag indicators are not visible in the default theme

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5362]
## Description  
In Edge the row drag indicators are not visible in the default theme

 * igniteui-angular version: 8.1
 * browser: Edge

## Steps to reproduce  

1. Open dev sample gridRowDrag
2. Change theme to default

## Result  
Row drag indicators are not visible

## Expected result  
They should be visible

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/60866686-acefba80-a231-11e9-9a13-dea792243a86.png)

**Comment by simeonoff** [comment]
@nrobakova what version of edge?
