### ISSUE TITLE
Grid row wise Index property 

### ISSUE THREAD

**Issue by shubhamghormade19** [IgniteUI/igniteui-angular#5398]
## Is your feature request related to a problem? Please describe.
rowIndex property for cell is there, but while grouping it will add the summary row index also

**Comment by zdrawku** [comment]
Hello @shubhamghormade19, could you please clarify and provide more information on what exactly you are trying to achieve. Thanks in advance

**Comment by shubhamghormade19** [comment]
I am trying to perform index column in table, Which works fine for the normal table.
rowIndex will provide the proper index.
But while grouping table, The rowIndex add the index of that grouping label row too.

**Comment by ChronosSF** [comment]
@shubhamghormade19 , you can search for the data row in the collection of data rows as they are before they pass the grouping pipe. Please, try the following for your index column:

```html
<igx-column [header]="'Index'">
     <ng-template igxCell let-cell="cell">
           {{cell.grid.filteredSortedData.indexOf(cell.row.rowData) + 1}}
     </ng-template>
</igx-column>
```

**Comment by shubhamghormade19** [comment]
Hi @ChronosSF 
Thanks, it works for me
