### ISSUE TITLE
Get remote unique data for Excel filter.

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#5417]
## Question  

Hello. How can i get remote data from server for Excel filter? Now there are displayer only those values that are contained in the total data. All possible values are located in server.
Thanks 

 * igniteui-angular version: 
 * browser:

**Comment by DiyanDimitrov** [comment]
@ivanovla, Currently there is no way to achieve this. You could submit a new feature request.

**Comment by bkulov** [comment]
Closing this issue as there is a feature request for the same thing.
