### ISSUE TITLE
Grid with virtual scrolling scrolls when row dragged to top/bottom of grid

### ISSUE THREAD

**Issue by Lightw3ight** [IgniteUI/igniteui-angular#5419]
## Is your feature request related to a problem? Please describe.
Following the examples at [https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_drag.html#example-demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_drag.html#example-demo) I am able to get drag and drop working, specifically drag and drop re ordering.

One limitation however seems to be that if you have a grid with enough rows that requires a scroll bar and you are using virtual scrolling, if you drag a row to the top or the bottom of the grid, the grid will not scroll to reveal more rows, this means that you can only reorder rows within the current scrolled viewport

## Describe the solution you'd like
It would be nice if this was somehow automatic and the viewport scrolled when you dragged near the top / bottom of the grid.

## Describe alternatives you've considered
Some sort of drag move output that is emitted constantly as the user drags a row around the grid, coupled with some api on the grid to scroll the viewport would allow us to detect when the viewport needs scrolling and then to action that on the grid ourselves

**Comment by dafo** [comment]
@Lightw3ight, thank you for the feature request. Until such functionality is implemented, similar usecase may be achieved by scrolling, using the mouse wheel, while dragging a row. Please, let me know if this approach is suitable for your scenario.
However, have in mind that we have an issue that would affect both scrolling approaches - https://github.com/IgniteUI/igniteui-angular/issues/5459
You may follow the progress of the issue here.

**Comment by dafo** [comment]
@Lightw3ight can you please take a look at this sample, demonstrating how this functionality may be achieved - https://stackblitz.com/edit/all-your-memory-belongs-to-chrome

**Comment by sddania** [comment]
this needs also for list view component

**Comment by dafo** [comment]
Closing this issue as such implementation will be covered in the row drag documentation. You can follow the progress on it in t[his work item](https://github.com/IgniteUI/igniteui-docfx/issues/2788).
