### ISSUE TITLE
Drop indicators between grid rows

### ISSUE THREAD

**Issue by Lightw3ight** [IgniteUI/igniteui-angular#5420]
## Is your feature request related to a problem? Please describe.
When dragging rows to reorder as demo'd [here](https://stackblitz.com/angular/voaxkynkndy?file=src%2Fapp%2Fgrid%2Fgrid-row-reorder-sample%2Fgrid-row-reorder.html) I would like to show a drop indicator to show where the row will be dropped

## Describe the solution you'd like
It would be nice if it was automatic like when we drag columns to re order them

## Describe alternatives you've considered
If its not possible to do automatically then could a dragmove event be exposed on the igxDrop target (the grid) so that we can determine the current row and insert an indicator manually between the rows
It would also be great to add that to your stackblitz example above

**Comment by dafo** [comment]
Such functionality is currently not available but we may create a feature request for implementing such functionality.
About the event that you suggest - we are currently working on exposing an `onOver` event that will be  triggered when an IgxDrag instanced element moves inside the boundaries of the drop area - similar to `MouseOver`. It is going to be available in some of the upcoming versions of the library and we will update the sample once it is done.

**Comment by Lightw3ight** [comment]
> About the event that you suggest - we are currently working on exposing an `onOver` event that will be triggered when an IgxDrag instanced element moves inside the boundaries of the drop area - similar to `MouseOver`. It is going to be available in some of the upcoming versions of the library and we will update the sample once it is done.

You already have an event `onEnter` which triggers when you mouse over an `igxDrop` area (Like a mouse over) but because the `igxDrop` directive is attached to the grid, you dont get any event when the drag goes over a row

would your `onOver` event be more akin to a `mousemove` event while dragging inside a `igxDrop` area?

**Comment by dafo** [comment]
Yes, that's the idea.
You may find more in the [API of the IgxDrag/IgxDrop Directives Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#4-api)

**Comment by kdinev** [comment]
Related #5319

**Comment by ViktorSlavov** [comment]
@Lightw3ight 
With the official release of 8.2 and the new functionality that the `IgxDropDirective` exposes, I've put together [a small sample](https://stackblitz.com/edit/igx-grid-row-drag-highlight?file=src%2Fapp%2Fgrid%2Fgrid-row-reorder-sample%2Fgrid-row-reorder.ts), showcasing how you can emulate custom drop indicators under the target row.

In the example, I make use of the [`over`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdropdirective.html#over) emitter, exposed by the `IgxDropDirective`.

**Comment by Lightw3ight** [comment]
Awesome, thanks @ViktorSlavov
