### ISSUE TITLE
[rowDraggable]="true" causes an un-needed horizontal scroll bar on the grid

### ISSUE THREAD

**Issue by Lightw3ight** [IgniteUI/igniteui-angular#5421]
## Description  
When setting `[rowDraggable]="true"` on a grid that is 100% wide and has a column with no width, the grid gets an un-needed horizontal scroll bar

 * igniteui-angular version: 8.0.2
 * browser: Chrome 75

## Steps to reproduce  

1. Go to (your row reorder stackblitz demo)[https://stackblitz.com/angular/voaxkynkndy]
2. Replace the grid html with the following
```html
<div class="grid-container">
    <igx-grid #grid [data]="data" [height]="'800px'" width="100%" [autoGenerate]="false" [rowDraggable]="true"
        [primaryKey]="'ID'" igxDrop (onDrop)="onDropAllowed($event)">
        <igx-column [field]="'CompanyName'" [header]="'Company Name'" [editable]="true"></igx-column>
    </igx-grid>
</div>
```

## Result  
You will see a horizontal scroll bar

## Expected result  
In the above example, the only column has no specified width, so there should be no horizontal scroll bar

## Attachments  
![hoz-scroll](https://user-images.githubusercontent.com/740446/61251182-d1a5de00-a7ad-11e9-8f7c-7afda3bb9b80.PNG)

**Comment by dafo** [comment]
I was able to reproduce the issue. We will investigate the cause for this behavior further and will update you ASAP.
