### ISSUE TITLE
igx-grid column filters should close when clicked off

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular#543]
### Description  
User expectation is that while a column filter popup is open, when the user clicks outside of the filter UI the popup closes. Currently it stays open, and multiple filter popups could be open at the same time.

### Steps to reproduce  

1. go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
2. click filter button on Athlete column
3. click outside of filter popup

### Result  
Filter popup stays open.

### Expected result  
Filter popup closes.

**Comment by jVanZwieten** [comment]
If the ability to have multiple filter UIs open at once is a desired user case, it should be a setting on the grid, and should be off by default, as I believe the filter popup closing is the most common expectation.

**Comment by jberes** [comment]
We definitely do not want to show multiple Filter UI at once, only one at time should be able to open.  And clicking or tapping outside of the filter dialog should close it.  A filter should only apply if a filter Apply button is clicked or if we implement an immediate mode filter where filter occurs as items are clicked (which could affect performance, but that's also probably not the default).

**Comment by kdinev** [comment]
@jVanZwieten How do you observe multiple filter UIs opened at once, since only one column in the sample has a filter?

**Comment by jVanZwieten** [comment]
I observe it on samples in which filtering is enabled on multiple columns, such as this one:https://stackblitz.com/edit/angular-yrswap
