### ISSUE TITLE
Demos do not run after following listed instructions

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#545]
### Description  
Following the instructions from the readme.md, the demos do not work.

### Steps to reproduce  
First this following line does not work, I believe it is intended to be two lines
cd demos && npm install

Second 
npm run start:demos results in the following

### Result  
WARNING in ./node_modules/@angular/core/esm5/core.js
6541:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./app/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8000 ./app/main.ts

WARNING in ./node_modules/@angular/core/esm5/core.js
6561:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./app/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8000 ./app/main.ts

ERROR in [at-loader] ./app/app.module.ts:7:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/app.module.ts:7:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/app.module.ts:7:52
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxNavigationModule'.

ERROR in [at-loader] ./app/avatar/sample.module.ts:2:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/avatar/sample.module.ts:2:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/badge/sample.module.ts:2:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/badge/sample.module.ts:2:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/button/sample.module.ts:2:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/buttonGroup/sample.component.ts:6:5
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/buttonGroup/sample.module.ts:7:5
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/carousel/sample.module.ts:3:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/dialog/sample.module.ts:2:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/dialog/sample.module.ts:2:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/grid/sample.component.ts:9:3
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxGridBindingBehavior'.

ERROR in [at-loader] ./app/grid/sample.component.ts:10:3
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxGridColumnInitEvent'.

ERROR in [at-loader] ./app/grid/sample.component.ts:11:3
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxGridComponent'.

ERROR in [at-loader] ./app/grid/sample.component.ts:189:16
    TS2339: Property 'filtering' does not exist on type 'IgxColumnComponent'.

ERROR in [at-loader] ./app/grid/sample.module.ts:4:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/grid/sample.module.ts:4:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/input/sample.component.ts:2:9
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/input/sample.component.ts:2:30
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/input/sample.module.ts:4:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/input/sample.module.ts:4:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/layout/sample.module.ts:2:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/list/sample.module.ts:4:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/list/sample.module.ts:4:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/navdrawer/sample.module.ts:4:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/pageHeading/pageHeading.module.ts:2:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/pageHeading/pageHeading.module.ts:2:46
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxNavigationModule'.

ERROR in [at-loader] ./app/ripple/sample.module.ts:2:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/tabbar/sample.component.ts:10:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/tabbar/sample.component.ts:10:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.

ERROR in [at-loader] ./app/tabbar/sample.module.ts:5:10
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxComponentsModule'.

ERROR in [at-loader] ./app/tabbar/sample.module.ts:5:31
    TS2305: Module '"E:/SCCommon/igniteui-angular/demos/lib/main"' has no exported member 'IgxDirectivesModule'.
Child html-webpack-plugin for "index.html":
     1 asset
       [2] (webpack)/buildin/global.js 509 bytes {1} [built]
       [3] (webpack)/buildin/module.js 517 bytes {1} [built]
        + 2 hidden modules
webpack: Failed to compile.

----------------------------
Note while it does run, and open a window, it will just indefinitely show:
Please wait... 
... we're testing your patience.

### Expected result  
The demo samples should run when following the instructions from the readme.md

**Comment by jVanZwieten** [comment]
I get the same. You _just_ beat me to the punch @MikeTechSpeak !

**Comment by SlavUI** [comment]
Zdravko is working on the issue

**Comment by zdrawku** [comment]
The changes that we've made to the directives (structural and naming) affects Ignite UI for Angular Samples repository, once we sync the merges for both repost there wont be any errors. Related pull requests:

https://github.com/IgniteUI/igniteui-angular-samples/pull/45
https://github.com/IgniteUI/igniteui-angular/pull/541

**Comment by SlavUI** [comment]
@MikeTechSpeak  and @jVanZwieten hi guys the Demos are now working fine.

**Comment by kdinev** [comment]
@MikeTechSpeak @jVanZwieten I just verified that both the grid and list performance samples run perfectly. Sync your `igx-virtual-directive` branches and `npm run start:demos`

**Comment by SlavUI** [comment]
@MikeTechSpeak @jVanZwieten closing this one let us know if you still have issues
