### ISSUE TITLE
Provide the state persistence directive of the igx-grid by default

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular#5460]
## Is your feature request related to a problem? Please describe.

Currently the way to save/load the state of the grid is by "copying" the implementation of a state directive in [this](https://stackblitz.com/angular/roonkogkynj) sample.

This is not a good user experience, as the code is not "official" - it is not tested, documented and integrated appropriately.

## Describe the solution you'd like

Provide the `igxGridState` directive as a part of the grid modules. [Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-State-Persistence).

Items:
- [x] - [Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-State-Persistence) DONE
- [x] - Implementation DONE
- [x] - Bugs found during testing DONE
- [ ] - API automated tests - in Progress

**Comment by kdinev** [comment]
Related to #1390

**Comment by hanastasov** [comment]
Specification can be found [here](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-State-Persistence).
