### ISSUE TITLE
Selected cell is not correct when expand collapse group row

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/igniteui-angular#5465]
## Description  
Selected cell is not correct when expand collapse group row

 * igniteui-angular version: 7.3.x
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridGroupBy
2. Group by column Country
3. Click on cell in 4th row
4. Collapse the first row

This issue is not reproducible in 7.1.x, but it is reproducible in 7.2.x and 7.3.x

## Result  
The cell is no longer selected

## Expected result  
The selected cell should remain selected

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by VMihalkov** [comment]
Maya found out that in 7.1.x when determining if cell is selected, we've compared the rowdata, but in 7.2.x forward we compare the rowIndex which changes when expand/collapse group rows.

**Comment by nrobakova** [comment]
@VMihalkov this is expected behavior. Now the selection is  index based (DOM elements selection).
You can look for more details here:
https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Multi-cell-selection-Specification#33-other-igxgrid-features-integration
