### ISSUE TITLE
Row drag indicator is not positioned correct in the child grid(without row island)

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5473]
## Description  
Row drag indicator is not positioned correct in the child grid(without rowIlands)

 * igniteui-angular version: 8.1
 * browser: n/a

## Steps to reproduce  

1. Edit dev sample hierarchicalGrid and in the first hgrid set [rowDraggable]="true" to the last row islend
2. Open the sample
3. Expand first row
4. In the child grid expand row until go to the last row island

## Result  
The cells are misslaigned

## Expected result  
The cells should not be missaligned

## Attachments  

![image](https://user-images.githubusercontent.com/11463104/61633225-4e95f380-ac97-11e9-868f-e8529de3b1fa.png)

**Comment by dafo** [comment]
This seems to be caused by the fact that the last row island does not have an expander and the calculations are messed up.
