### ISSUE TITLE
Add semantic-release to the repo

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#548]
### Description  
[Semantic release](https://github.com/semantic-release/semantic-release) will help us to:
- generates a changelog
- enforce valid and consistent commit messages (have a look at the [VS code extension - commitizen](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-commitizen))

- [x] Copy hooks into local .git file to the user.

**Comment by kdinev** [comment]
I guess this is mostly here because we don't enforce commit messages for semantic release?

**Comment by zdrawku** [comment]
Yes, I am also updating the description based on the sprint commitment related to this task
