### ISSUE TITLE
Simplify import statement

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#550]
### Description  
I want to write import statement for igniteui-angular as simple as possible.

### Result  
Currently, we have to write as below.
```
import { IgxXxxModule } from 'igniteui-angular/main'
```

### Expected result  
`/main` is unnecessary. I want to write as below.
```
import { IgxXxxModule } from 'igniteui-angular'
```

**Comment by rkaraivanov** [comment]
We may eventually provide a barrel module at the root of the package at some point.

**Comment by zdrawku** [comment]
With the new project structure this issue is no longer relevant. @tkiryu as you may see, now the imports are happening without the /main part.

**Comment by tkiryu** [comment]
@zdrawku , I confirmed that now we can import modules and services from 'igniteui-angular'.
Great! Thanks!
