### ISSUE TITLE
igxGrid render content body at default size and max 10 rows within non-first-slide of igxCarousel

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#5508]
## Description  
igxGrid is placed on igxCarousel so that it occupies the entire slide. 
It works as expected on the first slide, but the grid does not take up the whole space on other slides.

 * igniteui-angular version: 8.1.0
 * browser: Chrome

## Steps to reproduce  

1. Run the sample: https://stackblitz.com/edit/angular-ljzgde
2. Go to the third slide.

## Result  
igxGrid does not occupy the entire slide.

## Expected result  
igxGrid is rendered so that it occupies the entire slide as it is shown on the first slide.

**Comment by MayaKirova** [comment]
Seems to be resolved with the ResizeObserver implementation related to the following issue: https://github.com/IgniteUI/igniteui-angular/issues/5529

Note: This will only be fixed in master since it is a new functionality.

**Comment by mpavlinov** [comment]
@mkamiishi I'm closing this issue as the changes for resize observer are merged to master.
