### ISSUE TITLE
Enhance combo selectionChange event args

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5523]
## Description  
I have the following use case, I want to deselect an item from the combo and use this item to perform additional actions, the problem is that in order to access the deselected item, I have to iterate through the old and new selection elements and find the difference (which in my case is the deselected item). 

Check the image below, it illustrates both new and oldSelection collections, and the item that I need is not easily accessible:

![image](https://user-images.githubusercontent.com/11193764/61958255-ae5b0a00-afc9-11e9-9990-40b1bc2e671f.png)
 
How can I get the deselected item in a user-friendly manner?

Steps to reproduce:
1. Select 4 items in a combo
2. Deselect one item
3. onSelectionChange is triggered, although you cannot get the actual item

**Comment by StefanIvanov** [comment]
You mean that for the combo the selection event should have an argument for the item that was selected/deselected. I think it is a fair question and we should consider enhancing the combo with it.
