### ISSUE TITLE
Calling triggerTodaySelection throws error

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#5525]
## Description  
Calling `triggerTodaySelection` when date picker is collapsed throws TypeError:
Cannot set property 'viewDate' of undefined

 * igniteui-angular version: 8.1.0
 * browser: all

## Steps to reproduce  

1. Start this [StackBlitz](https://stackblitz.com/edit/date-picker-today-selection-issue?file=src/app/app.component.ts) sample.
2. Click `Today` button.
3. Observe the console

## Result  
ERROR Error: Cannot set property 'viewDate' of undefined
is logged in the console.

## Expected result  
No errors should be logged in the console.

**Comment by jackofdiamond5** [comment]
The issue will be resolved in https://github.com/IgniteUI/igniteui-angular/issues/6483
