### ISSUE TITLE
igxGrid does not automatically respond to width and height adjustments that are not caused by a window resize

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#5529]
## Description  
Users are forced to call `reflow()` in scenarios where the grid has to respond to a transition, show/hide of a parent element, etc. This should be automatically handled by the grid with a resize observer.

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

TBA

## Result  

TBA

## Expected result  

TBA

*This is an overarching task that can be used to track progress. Issues that stem from the lack of this functionality will be linked below*
- #3639
- #4329
- #5508

Auto-size related issues:
- #4809
- #3950
- #3949
- #4758

**Comment by radomirchev** [comment]
Option A - optimize Tests
Option B - separate Tests

**Comment by radomirchev** [comment]
We are going for Option B - Split Tests
