### ISSUE TITLE
Allow to expand all rows in hierach grid

### ISSUE THREAD

**Issue by Failender** [IgniteUI/igniteui-angular#5540]
## Is your feature request related to a problem? Please describe.
It is always annoying if we want to see the full content of all rows that we need to click each one to expand it.

## Describe the solution you'd like
We have a button which allows to collapse all rows. It would be good if we could reuse this button to expand all rows if we hve no expanded rows. Since this can be quite a performance hit (if we lazy load a lot of rows) this should be configurable. Allowing this feature could be enabling by adding a new property <igx-hierarchical-grid [allowExpandAll]="true">
If this flag is true the behaviour of the button will be the same as the igx-grid in grouped mode

**Comment by kdinev** [comment]
@Failender The reason why this is not implemented out of the box, is the performance consideration that you've described. If you wish, we can make it configurable as you've suggested, but this would hand off all performance considerations to the user, if they decide to turn it on.

**Comment by Failender** [comment]
Yeah thats true, the user should know that this may cause problem if he has a list with thousands of entries and wants the expand them all.
We are working with smaller sets (5-40 entries) in our case so we dont have that much performance converns there

**Comment by kdinev** [comment]
@Failender I will prioritize this item for next sprint and we can release it in a patch.

**Comment by MayaKirova** [comment]
@Failender @kdinev @mmart1n Since we will be supporting templates for the expand/collapse indicators in rows/headers and expose hgrid api’s for expand/collapse all as part of this issue - https://github.com/IgniteUI/igniteui-angular/issues/5621 you will be able to achieve this by setting custom expand/collapse header template for the hierarchical grid and call the related api on click.
