### ISSUE TITLE
Grid sorting. Only icon click

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#5541]
## Bug 

How i can enable sorting only after icon click?
Now it work every click on all header and when i click icon(in example for pine) triggered sorting.
The onSortingDone event fires.

 * igniteui-angular version: 
 * browser:

**Comment by kdinev** [comment]
My suggestion would be to set the column's `[sortable]="false"`, then to template a sorting icon in the header and to invoke the grid's sorting API on click. The related issue is by design, and the entire header is becomes a clickable area for sorting, when `[sortable]="true"`.
