### ISSUE TITLE
Sorting grid. Event onSortingDone triggered every click on header

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#5545]
## Description  
Describe the issue.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  
Now it work every click on all header and when i click icon(in example for pine) triggered sorting.

## Result  
The onSortingDone event fires.

## Expected result  

I do not want to cause sorting every time, since I work with remote data

https://stackblitz.com/edit/igx-grid-column-header-event-handling-issue-when-movable-dfwfyj?file=src/app/grid/grid-sample-pinning/grid-pinning.component.html

**Comment by ivanovla** [comment]
This connect with question #5541

**Comment by kdinev** [comment]
I've explained the status in the related question.
