### ISSUE TITLE
igx-grid - Custom cell does not support ngIf anymore

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#5550]
## Description  

Custom cell does not support ngIf anymore

 * igniteui-angular version: 8.1.2
 * browser: Chrome 75.0.3770.142

## Steps to reproduce  

1. Open sample https://stackblitz.com/edit/angular-1jn6sr
2. Click on the switch "Show images"
3. Click on button "Load grid".

## Result  
The grid is loaded without the images in the columns "Athlete" and "Country".

## Expected result  
The grid is loaded with the images in the columns "Athlete" and "Country".

## Attachments  
The bug is caused by the new flag [static: true](https://angular.io/guide/static-query-migration#is-there-a-case-where-i-should-use-static-true)  at https://github.com/IgniteUI/igniteui-angular/blob/983aba7a2a0cf9af42878fac238552c71c26964a/projects/igniteui-angular/src/lib/grids/column.component.ts#L1105 

Sample working with Angular 7 and igniteui-angular 7.3.12 at https://stackblitz.com/edit/angular-1jn6sr-wsq

**Comment by lalo-mx** [comment]
I found a workaround for the issue. I copied the [default cell template](https://github.com/IgniteUI/igniteui-angular/blob/724a08280427a38d45fcfd4e98b3c1318715a6eb/projects/igniteui-angular/src/lib/grids/cell.component.html#L1) and added the *ngIf iniside the template but the workaround would be easy to break as the API changes.

Sample with the workaround: https://stackblitz.com/edit/angular-1jn6sr-6n3pkw

**Comment by rkaraivanov** [comment]
@lalo-mx 

I guess that's a leftover from the transition to Angular 8. Their migration tool wrongly deducted that the templates should be static: true by default.

We'll definitely fix it for the next release of the 8.x packages
