### ISSUE TITLE
ExcelStyleFilter in DataGrid results in errors when null dates are present in data set

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#5551]
## Description  
ExcelStyleFilter in DataGrid erroring when null dates are present in data set (initially logged at https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/120328/excelstylefilter-in-datagrid-erroring-when-null-dates-are-present-in-data-set)

 * igniteui-angular version: 7.3.11
 * browser: any

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/angular-12e62g
2. Filter the ORderDate column selecting more than two values from the ExcelStyleFilter

## Result  
What is the actual result after following the steps to reproduce?
![image](https://user-images.githubusercontent.com/14248932/62190513-2fbfed00-b37a-11e9-9d68-4cd717b90061.png)

## Expected result  
Filter to be correctly applied and no errors to come up.

**Comment by zdrawku** [comment]
@hanastasov we can submit the fix and start with the test implementation. @radomirchev I believe we can complete this issue for this sprint, if not you can plan it for the next one. The issue is already started.

**Comment by radomirchev** [comment]
@zdrawku I agree with you. Moving the issue to "Development" for current Sprint.
