### ISSUE TITLE
Setting filteringExpressionsTree on grid not working.

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular#5553]
## Description  
I can't get the filter to be loaded on the grid's initial state. I'm saving the grid's state locally, like hidden columns, filters used and column width. But I can't restore the filters. It just won't work. This is my code:

```typescript
console.log('grid config', config);
console.log('this.grid.filteringExpressionsTree', this.grid.filteringExpressionsTree);
this.grid.filteringExpressionsTree = config.filters;
console.log('this.grid.filteringExpressionsTree', this.grid.filteringExpressionsTree);
```

`config` is always set and correctly so. But even after adding filters, which is an `IFilteringExpressionsTree` the property won't reflect that change. What is happening here? Is this a bug or am I missing something?

I checked the source code and noticed a `instanceof FilteringExpressionsTree` check and tried to implement it locally to see its result and I got a false result, even by forcing it like this:

```typescript
const tst: FilteringExpressionsTree = config.filters as FilteringExpressionsTree;
console.log('this.grid.filteringExpressionsTree', tst);
this.grid.filteringExpressionsTree = tst;
console.log('is FilteringExpressionsTree', tst instanceof FilteringExpressionsTree);
```

This is weird, because the logging of `tst` shows it has the proper values set, so it wasn't a cast issue. It's all looking a little bit weird to me.

Also, since I've opened this ticket. Is there a way to retrieve and set the columns' width?

 * igniteui-angular version: 8.0.1
 * browser: Firefox

## Steps to reproduce  

Explained above

## Result  
Nothing.

## Expected result  
The grid would display and react upon the set filters.

## Attachments  
N/A

**Comment by eestein** [comment]
Any comments on this? It's been two days already and this is blocking me. I'd appreciate any help.

**Comment by zdrawku** [comment]
Hello @eestein, this is something that we'll definitely look at.

**Comment by DiyanDimitrov** [comment]
@eestein, This [topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence) demonstrates how to implement persistence of the IgxGrid component. If you still have issues loading the filtering expressions, could you provide a sample where the issue is reproducible?

**Comment by eestein** [comment]
Ok, using that example I was able to figure out the problem. I can't persist and just restore `filteringExpressionsTree`, I need to recreate the object. That was the problem. This behavior is a little bit weird to me, though.

**Comment by zdrawku** [comment]
Thank you for your comments @eestein, we plan to create a state persistence directive that will ease the persistence of filteringExpressionsTree #5460
