### ISSUE TITLE
IgxGridColumnInitEvent and others are obsolete in Documentation

### ISSUE THREAD

**Issue by lucianoybanez** [IgniteUI/igniteui-angular#556]
### Description  
Some Events and dependencies are obsoletes for the latest version

### Steps to reproduce  

1. Follow the readme.md from grid

### Result  
The IgxGridColumnInitEvent and others class don't exist any more when install the latest igniteui-angular. For example I couldn't import this:
import { IgxGridBindingBehavior, IgxGridColumnInitEvent, IgxGridComponent } from "../../../src/grid/grid.component";. The same reference appears in official site of Infragistics. Could you check it and remove if it necessary?, because is very confusing.

### Expected result  
Clean documentation

**Comment by kdinev** [comment]
@lucianoybanez We will have the readme and the grid topics on our website up to date with the official 5.2.0. The new version is still in beta because we're working on getting the docs up-to-date before publishing.

**Comment by ktrkumarbablu** [comment]
i am trying to add this component in angular js 5 project. Could  please how to add in project.
I have system.config.js file shall we add js entry point in system.config.js file.
Could you please give me step of include this component.

**Comment by zdrawku** [comment]
@ktrkumarbablu as I can see you have a case in our system about this, which is answered now and working sample is provided for using our grid with system.js.

**Comment by zdrawku** [comment]
If you have any further question you can reopen this or contact us through the case in our internal system.
