### ISSUE TITLE
How to hide the group area row in IgxGrid

### ISSUE THREAD

**Issue by jdk339** [IgniteUI/igniteui-angular#5561]
## Question  
Is there a way to hide the group area row in the IgxGrid? It would also be great if there was a way to hide that left-most column.

This is useful because sometimes the grouping may never change, so the user does not need to worry about, or try to control, how the table is grouped.

![image](https://user-images.githubusercontent.com/16578448/62219528-85959480-b37c-11e9-9a1c-f91a0b883ab5.png)

**Comment by mpavlinov** [comment]
@jdk339 Currently there is no way to hide the group area row in IgxGrid and have a grouped columns. Also there is no way to hide the left-most column.
@kdinev @radomirchev : We should discuss this questions as a new feature requests.

**Comment by jdk339** [comment]
Okay, thanks for the quick response

**Comment by jdk339** [comment]
I don't think I should have closed this if it's a potential feature request.

**Comment by mpavlinov** [comment]
@jdk339 Ok. We will discuss it.

**Comment by jdk339** [comment]
One of the reasons for this request is that, "space real estate" may be limited on certain devices. For example, some of my users use their mobile devices, and the grid headings start to take up a lot of space with the column headers, grouping header, and title header:

![image](https://user-images.githubusercontent.com/16578448/63035358-05495600-be89-11e9-8ff8-f861c05a7788.png)
