### ISSUE TITLE
How recalculate table rows after change window size

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#5573]
Hello. 
How i can recalculate table rows after changed window size or changed parent container size.
Now there is an empty place.
Thanks in advanced.

![2](https://user-images.githubusercontent.com/31878467/62364332-d8f91580-b529-11e9-8a72-5f4f5d769ae1.png)

![2](https://user-images.githubusercontent.com/31878467/62364293-c088fb00-b529-11e9-85ea-084df2aca47d.png)

**Comment by kdinev** [comment]
@ivanovla The team is currently working on introducing a resize observer in the grid, which will handle scenarios like this one. The work on it is almost completed:

https://github.com/IgniteUI/igniteui-angular/tree/rkaraivanov/observers-and-batch-cdr

We expect to have this introduced in the product within the next few weeks!

**Comment by ivanovla** [comment]
> @ivanovla Команда в настоящее время работает над внедрением наблюдателя изменения размера в сетке, который будет обрабатывать сценарии, подобные этому. Работа над ним практически завершена:
> 
> https://github.com/IgniteUI/igniteui-angular/tree/rkaraivanov/observers-and-batch-cdr
> 
> Мы ожидаем, что это будет введено в продукт в течение следующих нескольких недель!

Good, will wait

**Comment by ivanovla** [comment]
@kdinev Is there any information?

**Comment by kdinev** [comment]
@ivanovla We're going to release it, most likely this week.
