### ISSUE TITLE
IE11 - IgxDialog jumps!

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#5576]
## Description  
IgxDialog appears at the bottom screen and then "jumps" to the center

 * igniteui-angular version: 8.1.0 and 7.3.3
 * browser: IE11

## Steps to reproduce  

1. Open your demo page from IE11
2. https://www.infragistics.com/products/ignite-ui-angular/angular/components/dialog.html
2. Click the "Show dialog" of the "Dialog demo sample"

## Result  
The dialog will show at the bottom of the IFRAME and then it'll move to the center of it.

## Expected result  
Either one of the following would be ok.
1. Show the dialog at the center of the screen from the very begining.
2. Fix the "fadding" animation so the movement doesn't look like a "jump"

If you have a workaround to just "disable" the animation that'll be ok for me :)

## Attachments  
![Video_2019-08-02_175052](https://user-images.githubusercontent.com/29953012/62402612-369f5900-b54e-11e9-9f6b-10d343edce09.gif)

**Comment by luiscla27** [comment]
This is the current workaround am using, wich i think is really really ugly, i'll greatly appreciate a better approach:

```
/* IE10 & 11 Only*/
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
  .igx-dialog__window {
    position: fixed!important;
    top: 50%px!important;
    margin: -150px!important;
  }
}
```

**Comment by zdrawku** [comment]
Hey @luiscla27, we should expose [animationSettings](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxbannercomponent.html#animationsettings) @Input for the Dialog as we did for the Banner component, I confirm this is a bug and I am adding status "In Review"

As for the animations, these are the default animations that we've created for the Dialog component: `openAnimation` is `slideInBottom` and `closeAnimation` is `slideOutTop`.
