### ISSUE TITLE
[igxGrid] Grid selection does not account for non-existent items

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#5583]
## Description  
The grid selection can be forced in an invalid state if the user passes incorrect data to `grid.selectRows()` method

 * igniteui-angular version: 8.1.x
 * browser: N/A

## Steps to reproduce  

1. Open the [following sample](https://stackblitz.com/edit/grid-row-selection-handler?file=src/app/grid/grid-sample-selection/grid-selection.component.html)
2. Click on the `Try Me` button
3. Observe the grid header
4. Select/Deselect some more rows and click the button a couple of time
5. Observe the console

## Result  
The `newSelection` and `oldSelection` properties of the `onRowSelectionChange` event are 'polluted' with invalid properties.
After the first invalid value entered the selection set, the selection header is in indeterminate state (even when no rows are checked).

## Expected result  
The `newSelection` and `oldSelection` properties of the `onRowSelectionChange` event only contain valid rowIDs for rows in the grid.
The selection header's state properly reflects the selection state of the grid.

## Attachments  
![image](https://user-images.githubusercontent.com/24314672/62466643-778bad80-b79a-11e9-9bef-d147528c2939.png)

**Comment by nrobakova** [comment]
This check should be done from the user.
If we check if the row exists in the data, in the case with remote data it will not be possible to select a row which is not loaded.
