### ISSUE TITLE
Null reference error is thrown when dragged row goes out of viewport

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#5587]
## Description  
Null reference error is thrown when dragged row goes out of viewport.

 * igniteui-angular version: 8.1.2
 * browser: IE11

## Steps to reproduce  

1. Run the dev sample
2. Go to "gridRowDrag" page
3. Drag a row upward to go out of viewport

## Result  
Null reference error is thrown.

## Expected result  
No error is thrown.

## Attachment
![drag-and-drop error](https://user-images.githubusercontent.com/14340675/62519457-8b044a80-b866-11e9-9c29-ecf5edf51a39.gif)

**Comment by ymita** [comment]
If the returned value of document['msElementsFromPoint'] is null, returning an empty array prevents the error.

```ts
protected getElementsAtPoint(pageX: number, pageY: number) {
    // correct the coordinates with the current scroll position, because
    // document.elementsFromPoint consider position within the current viewport
    // window.pageXOffset == window.scrollX; // always true
    // using window.pageXOffset for IE9 compatibility
    const viewPortX = pageX - window.pageXOffset;
    const viewPortY = pageY - window.pageYOffset;
    if (document['msElementsFromPoint']) {
        // Edge and IE special snowflakes
        const elements = document['msElementsFromPoint'](viewPortX, viewPortY);
        return elements === null ? [] : elements;
    } ...
}
```

**Comment by dafo** [comment]
@ymita I have tested and applied your proposed fix.

**Comment by ymita** [comment]
@dafo Thank you!!

**Comment by ymita** [comment]
@Lipata @dafo 
This issue is going to be fixed in both 8.x and 7.x, isn't it? If so, can you add corresponding version labels? Thanks.
