### ISSUE TITLE
Typedoc and Sassdoc themes separation

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5614]
## Description  
3.	Move Typedoc and Sass docs themes in package

**Comment by Aleksandyr** [comment]
Related repositories:
[igniteui-typedoc-theme](https://github.com/Aleksandyr/igniteui-typedoc-theme.git)
[igniteui-sassdoc-theme](https://github.com/Aleksandyr/igniteui-sassdoc-theme.git)
