### ISSUE TITLE
Angular 7 Resetting igx-grid does not clearing values in custom filtering textbox

### ISSUE THREAD

**Issue by prabakaran1311** [IgniteUI/igniteui-angular#5620]
## Description  
I am using Angular 7 with igx-tree-grid. In that i am using custom filtering template. If i am resetting the grid filters are cleared but its not clearing text on input field in filter.

 * igniteui-angular version: 7.3.5
 * browser: all browser

## Result  
resetting or clearing all filters in grid does not clearing input values from filter.

## Expected result  
if i am resetting or clearing all filters it should  clear input box as well in custom filtering template.

**Comment by tachojelev** [comment]
@prabakaran1311, when a custom **filterCellTemplate** is used, the igx-tree-grid (or any of the other grids) cannot know what kind of elements this template is consisted of and this is why the custom input should be manually cleared.

For example, in the context of the custom filtering template in this [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/filtering.html#retemplating-filter-cell), when the **clearFilter** method of the igx-tree-grid is manually invoked, we'll have to manually invoke the custom clearInput method as well (the method is a part of the sample).
```html
<button (click)="clear()">clear the filter</button>
```
```typescript
clear() {
  const column = this.grid1.getColumnByName('ProductName');
  this.grid1.clearFilter(column.field);
  this.clearInput(column)
}
```
