### ISSUE TITLE
Make igxNavigationDrawerComponent, IgxDialogComponent and IgxToastComponent toggleabel through IgxToggleActionDirective

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#564]
### Description  
Provide toggleable functionality thorugh IgxToggleActionDirective for igxNavigationDrawerComponent, IgxDialogComponent and IgxToastComponent by implementing IToggleView interface and register the components into IgxNavigationService when user passes identical ID.

**Comment by rkaraivanov** [comment]
Closed via #560
