### ISSUE TITLE
Correct invalid date input

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5657]
## Is your feature request related to a problem? Please describe.
I want the DatePicker to prevent invalid input typing. 

## Describe the solution you'd like
If I try to type in value `14` in the month section, it should either fall-back to `12`- max value available for a month or accept `1`- min value available for a month,  and continue with the next section (based on the mask)

## Describe alternatives you've considered
Use max or min value for day/month or accept the first valid value.

Open [the sample](https://stackblitz.com/edit/angular-mask-and-datepicker-example) and type in 55-55-5555, I expect the date picker to accept 05-05-5555, rather now the value is cleared because it is invalid.

**Comment by Lipata** [comment]
Added to the igxDateTimeEditorDirective [specification](https://github.com/IgniteUI/igniteui-angular/wiki/DateTime-Editor-Specification).
