### ISSUE TITLE
igxGrid Row edit

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#566]
### Description  
I guess you may already be working on this, as it's possible in the old ig grid, but I would really like to see "row mode" in the igx-grid.

### Result  
Can only select / edit one cell at a time.

### Expected result  
Ability to select a row and show editors for all cells in the row at once when editing.

**Comment by SlavUI** [comment]
@Eralmidia yes we have it planned and I will let you know once the feature is scheduled to be ready :)

**Comment by Eralmidia** [comment]
I guess this can be closed, as it is handled in #812 ?

**Comment by Lipata** [comment]
@Eralmidia this is not the same behavior as #812. The latter is related to selection, which is not quite the same as editing all the cells for one row at once, which will require additional logic and UI. If you select a row in #812 it as added to a selected collection, its style is changed, but the row does not enter edit mode. This will bе a future and a different implementation. Thank you!

**Comment by Eralmidia** [comment]
Ah, yes, that makes sense. Thanks for the response. Any change this will make in into 5.4? It seems to me, that with the grid improvements coming in 5.3, this may be the last thing we need in order to start using this component in production.

**Comment by kdinev** [comment]
@Eralmidia We're still considering whether editing should be performed cell-by-cell, or the whole row should be editable. The alternative we're considering is external form to edit the whole row, because we need to be handling data-dense scenarios with lots of columns (200+), in which case the whole grid is horizontally virtualized and row editing is out of the question.

**Comment by Eralmidia** [comment]
Thanks for the input. I guess there are use cases for all of these options. An "excel-like" editing, a regular row editing and the form style for massive grids. If it is cell by cell, I do hope that you can include the option to have commit/cancel buttons for the row, to delay commit of data, even though the data is technically entered cell by cell. In the old grid, we are exclusively using row editing in all grids. I'd imagine this would be the most common generally, for all kinds of entities. Users, roles ect.

**Comment by Eralmidia** [comment]
Any chance this will be a part of milestone 3?

**Comment by kdinev** [comment]
@Eralmidia We've still not gotten to discussing and designing the row editing pattern. There's a very slim chance that this will make it in for June. We may get some progress on the design though.

**Comment by Eralmidia** [comment]
@kdinev Ok, keep me posted. There are only a small number of tables we can implement the igx grid at currently, without any editing features.

Changing the title seems logical, yes :)

**Comment by kdinev** [comment]
@Eralmidia We're working on enhancing the cell editing behavior and introducing row editing with that.

https://github.com/IgniteUI/igniteui-angular/wiki/Cell-Editing

Take a look at the `Tab` key behavior - the cells will be in edit mode one at a time, but `Tab` moves horizontally in the row, putting the next editable cell in edit mode. Let us know what you think!

**Comment by Eralmidia** [comment]
Yes, I think that continuing down the path of cell editing is logical from a technical perspective. What I'm wondering, is whether there will be a layer of "row logic" on top of the cell editing?

In the old ig grids, we have row mode, which edits the whole row, and then commit with a done/cancel button. For instance, if you have a grid of users, we would like to commit the changes for a User model to the server as a whole, not one API call for edit of email, one for username ect.

So maybe there could be something in the grid containing the edit state of the row, and delay the commit for the whole row until confirmed by the user (done/cancel), even though the cells technically are edited on a per cell basis?

**Comment by kdinev** [comment]
@Eralmidia I apologize for delay to respond to your question. You probably see that there's a lot of features that we're pushing at the moment, so I was busy with the other ones.

It's very hard for us to do a design where we spawn all the editors simultaneously, with done and cancel buttons, like in the classic Ignite UI igGrid. The most difficult part would be virtually scrolling the grid horizontally and spawning new editors. This is actually also not supported in the igGrid (horizontal virtualization and row editing). We may explore how to do this later this year.

Btw, once again I want to thank you for all the support and feedback you provide us with for this product!

**Comment by Eralmidia** [comment]
Yes, I do understand the difficulties regarding the editors. What I was proposing was more in the lines of the following:

You edit a single cell at the time, so only one editor is shown at a time. But when a cell in the row is edited, mark the row as "dirty". Visually maybe as simple as a change of color of the row or something. Then show done and cancel buttons for the edited row. If done is pressed, emit an event for row edit, if cancel is pressed, roll back the changes done to all cells in the row. That's was kinda what I meant by "adding some row logic" on top of what is essentially still cell editing. So essentially, the grid should be able to more or less work as in "cell mode", with the exception that you store edited values until done or canceled.

I don't know the inner workings of the grid of course, but it seems to me that it should be possible to use a single editor, but still give the user the feeling that they are editing a row.

No problem. Let me know if I become to nagging ;) In the end, I'm just trying to provide the best user experience for our customers, just like you do. Looking forward to the next release, especially to see the features of the combo/select component. Keep up the good work.

**Comment by kdinev** [comment]
@Eralmidia You're not at all nagging. 
@StefanIvanov @SDinev Can you take a look at the suggestion and see how we can implement a design for this?

**Comment by kdinev** [comment]
@Eralmidia Do you mind if you give me your email address? You can send me a message at kdinev@infragistics.com or on twitter @KonstantinDinev

**Comment by Eralmidia** [comment]
Sure, sent you a mail now :)

**Comment by StefanIvanov** [comment]
![row edit](https://user-images.githubusercontent.com/1702064/45425575-780ee780-b6a2-11e8-9bd4-25993b7b27c3.png)

**Comment by Lipata** [comment]
The button names are not finalized yet, and most probably they will be "Done" and "Cancel". We will also have templates that will allow defining custom buttons.

**Comment by StefanIvanov** [comment]
We are making some final tweaks and later today a slightly updated design will be shared. As @Lipata said the buttons will be customizable through a template and the titles you see on the screen shot are the default label values.

**Comment by kdinev** [comment]
@Eralmidia @Lipata @StefanIvanov The general approach that we've adopted is that if an element would have a default text, then the text for it is exposed as an input, so it can be changed/i18n-ed. We also prefer to expose such elements as templates, as that also allows for text modifications/i18n.

**Comment by Eralmidia** [comment]
Points are always given for template options ;) i18n is also a good point, and very much relevant for us.  Have a nice weekend guys.

**Comment by kdinev** [comment]
@Eralmidia The cases where we don't allow for templates, is when the element is fitting directly in a layout and defines the user experience. If there's possibility for the UX to be regressed by defining a different element in the template, then we prefer to not expose it. I don't think this is the case here.

**Comment by StefanIvanov** [comment]
![Preview](https://user-images.githubusercontent.com/1702064/45551616-2ea3d100-b837-11e8-954c-6c843a767ae1.png)

[Indigo.Design prototype](https://cloud.indigo.design/share/djbxcnq7dc49 )
