### ISSUE TITLE
Input vertical is not applied when calendar selection is range or multi

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5665]
## Description  
Input vertical is not applied when set selection to a calendar

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1. Edit dev sample calendar and in the first calendar add [vertical]="true"
2. Open the sample

Note: same is valid when calendar has selection="multi", but for  selection="single" the issue is not reprodusible

## Result  
First calendar is not vertical

## Expected result  
First calendar should be vertical

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by hanastasov** [comment]
The calendar header, which can be vertical or horizontal, is not available for Multi and Range selection.
