### ISSUE TITLE
Implement containment for the overlay shown by igxOverlayService

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#5667]
## Is your feature request related to a problem? Please describe.
I want to show an overlay with a loading indicator in the middle of the grid's tbody. The outlet should be the tbody, the content centered, the overlay shadow should only cover the tbody.

## Describe alternatives you've considered
A div element child of the tbody with 100%width, 100% height, absolute positioning, z-index and centered content that is declaratively shown/hidden works but the OverlayService should support this as well.

## Additional context
Related to #5517 and possibly the advanced filter dialog

The result should look like this:

![issue13](https://user-images.githubusercontent.com/2188411/63414617-e442b100-c404-11e9-9f53-02d7303f87fe.gif)

**Comment by damyanpetev** [comment]
@tachojelev Asked for something similar actually. I'm thinking this can easily be a new strategy with minor changes to the global positioning one.
