### ISSUE TITLE
Overlay elements that originate from the grid's outlet div are incorrectly rendered

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#5674]
## Description  
Overlay elements that originate from the grid's outlet div are incorrectly rendered. This can be reproduced with the **date picker** for any date cell.

**NOTES:**
- This issue is also reproduced for the **Advanced Filtering Dialog** (when dragged outside the grid) in its ongoing development: ([issue](https://github.com/IgniteUI/igniteui-angular/issues/5496), [PR](https://github.com/IgniteUI/igniteui-angular/pull/5625))

 * igniteui-angular version: 8.2.x
 * browser: any

## Steps to reproduce  

1. Open the Grid search dev demo.
2. Scroll to the DateCreated column so it is the first one in the view port.
3. Open the date picker for the second row's DateCreated cell.

## Result  
Overlay element is rendered beneath certain elements that are outside the grid.

## Expected result  
Overlay element is rendered above all elements that are outside the grid.

## Attachments  

![image](https://user-images.githubusercontent.com/12784974/63439612-0c4b0800-c437-11e9-9a67-e8a9189dc807.png)

**Comment by damyanpetev** [comment]
@simeonoff : We've talked briefly about this with @tachojelev and the issue as expected revolves around `z-index`. The grid needs to create its own stacking context exactly to keep content from jumping over other parts of the app and the default outlet is inside the grid for per-component theming. That makes it hard to overlay much of the external app content without additional work from the app dev (such as giving higher index to the grid or moving the offending outlets). 
_Either way, I think there's no universal solution that we can apply._

Right now, the only suggestion I had would be to move the `z-index:0` away from the host and to each main header/body/footer so the grid outlet itself can be allowed to have higher index than the grid itself. That is currently at 10 with our default styles, which would at least overcome most of those common overlaps. Thoughts?

**Comment by radomirchev** [comment]
Add issue for updating documentation.

**Comment by wnvko** [comment]
We cannot remove z-index as this will break the stacking context. What we can do is set the grid's z-index to 1 instead of 0. This will allow whatever is shown in overlay through grid's outlets to be shown above elements around the grid.
In case anyone set higher z-index to elements around the grid he should set and appropriate z-index to the grid - this is clearly application scenario we should not cover.
