### ISSUE TITLE
Calender-header

### ISSUE THREAD

**Issue by SalkiDixit** [IgniteUI/igniteui-angular#5682]
## Question  
I have an issue with "calender-header" and I'm not sure if I'm doing it right.
I want to remove header for [selection] = single,
       <igx-calendar [hasHeader]="false" [selection]="selectionType"></igx-calendar>
 * igniteui-angular version: 7.0.2
 * browser: all

**Comment by hanastasov** [comment]
@SalkiDixit ,
[[hasHeader](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcalendarcomponent.html#hasheader)]="false" does the job, please see [this sample](https://stackblitz.com/edit/angular-emydqg) for your reference and let us know f you have any questions.

**Comment by SalkiDixit** [comment]
@hanastasov Thanks for the reply, Actually there was issue related to angular version, ng-8 supports [hasHeader]="false" since I was using ignite v8.
But now its resolved.
