### ISSUE TITLE
SASS Properties for the Draggable's Ghost Border Radius not Exposed

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#5694]
## Description  
When an element is draggable, its ghost's border radius cannot be set with one of the properties, exposed in the SASS documentation

 * igniteui-angular version: 8.1.4

## Steps to reproduce  

1. Create an igx-chip within igx-chips-area
2. Assign the igx-chip's draggable directive a 'true'
3. Set the chip's border radius to 5px from the $border-radius property in the igx-chip-theme (which has to affect the ghost item as well)

## Result  
The ghost item's border radius is as is by default

## Expected result  
Its border radius has to be 5px because of the customization

## Attachments   
![image](https://user-images.githubusercontent.com/8365193/63691700-94a32180-c818-11e9-85a8-60d2d526882c.png)
_Screenshot from the chip styling sample, which is still on PR IgniteUI/igniteui-angular-samples#1416_

**Comment by simeonoff** [comment]
@3phase I think this is related to how the drag directive works. If the chip theme you create is scoped to a specific component then the issue you describe will appear. However, if you create a global chip theme and set the border radius there, it will remain the same regardless of weather the chip is being dragged or not.

We have not exposed another border radius property for the drag state as we don't think it's necessary.

**Comment by 3phase** [comment]
@simeonoff Thanks for the explanation.
