### ISSUE TITLE
Angular Pivot Grid

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#5700]
## Is your feature request related to a problem? Please describe.
We are missing Angular Pivot Grid. Data grid is best but there should be Pivot grid as well.  It will be great if you provide this soon. 

## Describe the solution you'd like
Provide Angular Pivot Grid component.

## Describe alternatives you've considered
https://www.webdatarocks.com/demos/javascript-pivot-table-demo/#customize-pivot-table
https://dzone.com/articles/4-best-free-web-pivot-tables-you-should-try-today
https://github.com/nicolaskruchten/pivottable/blob/master/README.md

**Comment by deepakvia** [comment]
Please update on this request. Any plan so we can communicate to our clients.

**Comment by radomirchev** [comment]
@deepakvia the issue is still under consideration and is not included in the queue for the next milestone.

**Comment by deepakvia** [comment]
https://www.flexmonster.com/demos/pivot-table-js/

The above is what our client is expecting. It will be great if you consider adding pivot in your component list. It will be great value addition.

**Comment by luiscla27** [comment]
@radomirchev is there any update on this feature?

**Comment by kdinev** [comment]
@radomirchev @ChronosSF Like we discussed, with the new `igx-tree` and `drag-and-drop`, we can create a pivot data selector, which will drive a grid configuration in terms of columns and row hierarchies on top of flat data. Let's discuss this in terms of effort for the next milestone.

**Comment by ChronosSF** [comment]
@deepakvia , the pivot grid is going to get released with v 13.1.0 expected next week.
