### ISSUE TITLE
Grid blocks page tab navigation/can't get out of the grid with keyboard nav

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#5709]
## Description  
The grid host element currently prevents all tab navigation, making it impossible to navigate in and out of the grid.

 * igniteui-angular version: 8.1.4
 * browser: Chrome

## Steps to reproduce  

1. Go to:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html
2. Focus the "Filter by Country" input

OR

1. Go to:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/editing.html
2. Focus the Add button (click next to it + tab)

OR

1. Go to:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/editing.html
2. Focus the Add button (click next to it + tab)

3. Hit tab to focus the next item (the grid)
4. Keep trying tab / shift-tab

## Result  
After you focus the grid host element all tab events are prevented, so you can't go through the headers (if there's an interaction there), cells, etc. or move out of the grid to the next focusable item on the page.

## Expected result  
I'd expect to be able to shift-tab back out of the grid or jump from the very last cell to the pager or outside the grid with tab navigation.

**Comment by zdrawku** [comment]
Adding this to the KB navigation Epic item, and removing it from the sprint as it will be fixed once we are ready with the enhancements

**Comment by zdrawku** [comment]
Fixed by https://github.com/IgniteUI/igniteui-angular/pull/6910
