### ISSUE TITLE
When navigate with Arrow Down key from child grid to parent, the focus is moved to the child

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5720]
## Description  
When navigate with Arrow Down key from child grid to parent, the focus is moved to the child

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGridRemote
2. Expand first row
3. Expand second row
4. In the child grid for second row click on a cell in firts row
5. Press Arrow down 4 times (to navigate to the root grid)
6. Press arrow down again

## Result  
A cell in the child grid for first row is selected and activated

## Expected result  
The next cell in the root grid should be selected and activated

**Comment by 3phase** [comment]
The issue is duplicated with #5251 and is getting fixed by #5900 💯
