### ISSUE TITLE
Access all data when calculating summary per column

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#5754]
## Is your feature request related to a problem? Please describe.
Depending on a business logic, a value from column X may be needed to calculate summaries for column Y. For example, lets define a custom summary:

```ts
class MySummary extends IgxNumberSummaryOperand {
    operate(data?: any[]): IgxSummaryResult[] {
        // data only contains the data for the corresponding column Y
        // some would like to access value from column X for the given record
        return result;
    }
}
```

## Describe the solution you'd like
When the [operate](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxsummaryoperand.html#operate) method is called, have the option to access other fields data as well.

## Describe alternatives you've considered
A complete manual calculating of sumamries that is rendered inside the grid footer. Makes no use of igxGrid Summaries

**Comment by amitmoondra** [comment]
Very important feature and would be really helpful if implemented early.

**Comment by zdrawku** [comment]
Hello @amitmoondra, thank you for your comment, we are reviewing our feature requests constantly and if one is approved @radomirchev is prioritizing it for further development. For the time being, I can provide you an alternative solution to this requirement by using igx-grid-footer.

[The sample](https://stackblitz.com/edit/angular-m5wsue) is demonstrating how to access the data and manipulate it as you want or use the summary operands to calculate it.
