### ISSUE TITLE
IgxGrid: content size as minimum size

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#5755]
## Describe the solution you'd like
It would be nice to have the ability to flag one or more columns as always visible. You have the auto size method, but this shrinks the column to the size it requires. On the other hand, you have the ability to set a minimum width, but this is done in px or %. Having a special "contentSize" property for min column width, or similar could be a solution?

## Describe alternatives you've considered
An alternative would be to handle this ourselves. In that case, method which returns the required width of the content would be useful

**Comment by kdinev** [comment]
@Eralmidia I was looking through the issues and I have a question about this one. How do you see this behaving when new content, which initially is outside of the virtualization frame, is rendered in the grid via scrolling. If let's say we have a `contentSize`, or `fitContent` property setting for a column width. Initially the largest content item in the virtualization frame is 
 
> `Some relatively long content` 

 and we set the column width to that. However, scrolling down brings into view a  

> `Some even longer content item that doesn't fit in the previous box`

should the column width automatically jump up? Also the same case is when the long items go out of view and the largest content item becomes

> `Short content`

 then should the column shrink down in size? I think that this would create an undesirable experience for the end-user.

**Comment by Eralmidia** [comment]
@kdinev Yes, that is certainly an issue, and as you say the columns width jumping probably isn't desirable. There are ways to calculate the required size of the longest text, but then you would have to do that for all rows, which kinda would kill the performance benefit of the virtualization in that regard. I guess this might not be feasible.

**Comment by kdinev** [comment]
@Eralmidia Precisely. It not only would kill the performance, but it's also not quite possible to do correctly, because the size in pixels of the content doesn't depend just on the length of the text, but also on the specific font, font-sizes, etc. In a templated column it's even more complex, as the content consists of multiple elements. I suggest to close this issue as not doable at the moment.
