### ISSUE TITLE
IgxInput/IgxInputGroup validation on button click

### ISSUE THREAD

**Issue by sohaib-ameen** [IgniteUI/igniteui-angular#5778]
## Question  
I have an issue with IgxInputGroup component.

 * igniteui-angular version: 7.3.11
 * browser: chrome

Apparently IgxInput inside IgxInputGroup gets highlighted whenever a user set focus on the field and then set off the focus by clicking somewhere on the screen. 

I want to validate the control and highlight it on button click. Please provide some solution if there is any.

**Comment by kdinev** [comment]
@sohaib-ameen I believe this is related to #4756.

**Comment by damyanpetev** [comment]
@sohaib-ameen By highlight I assume you mean the error color state, right? If so, the form control [`markAsTouched()`](https://angular.io/api/forms/AbstractControl#markAsTouched) or `markAsDirty()`, depending on use case, should do exactly what you need.
Can you check out the submit handler described in https://github.com/IgniteUI/igniteui-angular/issues/4756#issuecomment-571684611?
