### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5791]
## Is your feature request related to a problem? Please describe.
Right-to-left language support is not working properly in most of the components

## Components list
https://github.com/IgniteUI/igniteui-angular#current-list-of-components-include

| Component | Problem | Assignee | Fixed?
| --- | :---: | :---: | ---:| 
| Banner | styling | @desig9stein  | ✅
| Chip | styling | @simeonoff | ✅
| Calendar | styling | @simeonoff | ✅
| Card | styling | @simeonoff  | ✅
| Card Sample | styling | @simeonoff  | ✅
| Carousel | styling | @simeonoff  | ✅
| Combo | styling | @desig9stein  | ✅
| Input Group | styling | @simeonoff  | ✅
| Dialog | styling | @desig9stein  | ✅
| Expansion Panel | styling | @desig9stein  | ✅
| Switch | styling | @simeonoff  | ✅
| Snackbar |  styling | @simeonoff | ✅
| Radio | styling | @simeonoff  | ✅
| Checkbox | styling | @simeonoff  | ✅
| List | styling | @desig9stein | ✅
| Navbar | styling | @simeonoff  | ✅
| Progress Indicators | styling | @simeonoff | ⚠️ *
| Navdrawer |  styling | @desig9stein  | ✅
| Slider |  Typescript / Styling | @desig9stein |  ⚠️ *
| Tabs |  Typescript | ? | ⚠️ *
| Date Picker | styling | @simeonoff |  ✅
| Time Picker | styling | @desig9stein |  ✅
| Grid |  Typescript / Styling | ? | ⚠️ *

`* Styling done. Requires additional Typescript modification to get some elements fully working.`

## Describe the solution you'd like
The components should provide right-to-left visual alignment and actions of its content and related elements.

Note: Currently, the [Grid provides](https://stackblitz.com/edit/angular-igxgrid-rtl-support) a visual representation of the RTL alignment, although there is additional work that should be done in order to improve it.

**Comment by radomirchev** [comment]
Related #5212
