### ISSUE TITLE
igxCombo: Drop down list is not displayed properly if a data source is updated after the list is scrolled.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#5793]
## Description  
Dropdown list is not displayed properly if a data source is updated after the list is scrolled.

 * igniteui-angular version: 8.1.7
 * browser: Chrome

## Steps to reproduce  

1.Run the sample.
2.Click the drop down icon.
3.Scroll down the list.
4.Click outside the list to close it.
5.Click "Change Data" button.
6.Click the drop down icon.

## Result  
The first two items are blank in the drop down list.

## Expected result  
The dropdown list should be populated properly.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[comboApp.zip](https://github.com/IgniteUI/igniteui-angular/files/3608942/comboApp.zip)

**Comment by ViktorSlavov** [comment]
This issue does not reproduce in the latest version (10.1.x) - [CodeSandbox](https://codesandbox.io/s/vibrant-hooks-9ms7l?file=/src/app/combo-main/combo-main.component.ts)
Closing.
