### ISSUE TITLE
In disabled button group there should be indication for selected button

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5796]
## Description  
In disabled button group there should be indication for selected button

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1. Open dev sample buttonGroup
2. Look at the 'Multiple Selection Horizontal Disabled' buttons group

## Result  
Button Italic is selected but there is no difference with other buttons

## Expected result  
There should be indication for selected button

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/64856844-a6176680-d62b-11e9-8b95-9e93fc10418d.png)

**Comment by tachojelev** [comment]
@DaniMarinov, @StefanIvanov, what are your thoughts on this? Do you think we should have specific styling for the selected button, even if it is disabled (unlike the current behavior)?

**Comment by StefanIvanov** [comment]
IMO the selected button within the disabled button group should look the same way as if the button group was not disabled with the only difference that it is not clickable like the rest of the buttons, thus making it impossible for the user to change the state of the button group. @simeonoff @DaniMarinov what do you think?

**Comment by DaniMarinov** [comment]
@tachojelev Frankly, I cannot come up with real use case, because unlike the button, button group works like a toggle within the same page/screen/session. But still if you have faced a realistic scenario, check that solution:
![Artboard](https://user-images.githubusercontent.com/41998471/64955360-b8dea500-d890-11e9-953e-2beeedd826f0.png)

**Comment by tachojelev** [comment]
@StefanIvanov, @DaniMarinov, we believe the design that @DaniMarinov has proposed looks good, so we will plan and fix this issue in a future sprint.
