### ISSUE TITLE
Tests: ResizeObserver loop limit exceeded thrown

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5809]
## Description  
ResizeObserver error is thrown sporadically in test executions.

 * igniteui-angular version: 8.2.0 beta - master
 * browser: chrome

## Steps to reproduce  

1. Review some PRs from the repo

## Result  
ResizeObserver loop limit exceeded thrown

## Expected result  
Tests to pass

## Attachments  
![image](https://user-images.githubusercontent.com/11193764/64969895-737ca080-d8ad-11e9-8153-c41956454d73.png)

**Comment by nrobakova** [comment]
This issue should be fixed with PR #5790
