### ISSUE TITLE
Provide the overlaySettings in the igxToggle directive's onOpening event

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#5834]
## Is your feature request related to a problem? Please describe.
Sometimes you need to set the target of the overlaySettings in the onOpening event, but you don't have access to the overlaySettings in that event.

## Describe the solution you'd like
Provide the overlaySettings in the onOpening event. Note that it should be exposed to all other components such as the igxSelect component that are using the igxToggle directive internally and re-throw that event.

**Comment by wnvko** [comment]
We should not expose overlay settings in the events, as overlay internally creates a copy of the overlay settings. Exposing of the overlay settings will not affect the settings internally in use.
