### ISSUE TITLE
IgxCarousel animations

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#5838]
## Is your feature request related to a problem? Please describe.
A carousel is supposed to rotate around, animating the content of the different slides in and out of view.

## Describe the solution you'd like
Provided animations, or the ability to add animations to the content.

## Describe alternatives you've considered
CSS transitions of the slides, but it's not a solution, since the old slide is immediately destroyed when the new one is added.

## Additional context
This is a core feature for the carousel component.

**Comment by simeonoff** [comment]
Duplicate of #4268
