### ISSUE TITLE
Error is thrown when restoring grid state with excelStyleFilter and multiple filters selected

### ISSUE THREAD

**Issue by amit-kohli** [IgniteUI/igniteui-angular#5842]
## Description  
When a grid has excel filtering and in one column multiple filters are selected restoring the state throws an error after navigating to a different route and returning. 
The crux of the issue is that the values of excel like filters for a column are stored in an object of type Set which is not compatible with JSON.stringify().
 

 * igniteui-angular version: 8.1.7
 * browser: 76.0.3809.132 (Official Build) (64-bit)

## Steps to reproduce  

1. Create a grid with excelStyleFilter and the igxState directive (https://stackblitz.com/angular/rkapylyvyll?file=src%2Fapp%2Fgrid%2Fgrid-save-state%2Fstate.directive.ts) applied to it for State Persistenct
2. After the grid is rendered choose more than one entry for the filters on a column
3. Navigate to a different route (this is similar to the About route) in https://stackblitz.com/angular/rkapylyvyll
4. Navigate back to the home page

## Result  
![image](https://user-images.githubusercontent.com/8641842/65450028-de742d00-de01-11e9-9d8f-b8b73b3a39e9.png)

## Expected result  
The error should not be thrown and the grid state should be restored.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
Related #5460
