### ISSUE TITLE
[igx-select] Select component doesn't respect injected display density

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#5843]
## Description  
Seems that the select doesn't respect injected display density.

 * igniteui-angular version: 8.x
 * browser: NA

## Steps to reproduce  

1. Open the sample app 
[stackbliz](https://stackblitz.com/edit/angular-4uir8s?file=src/app/display-density/display-density.component.ts)
2. Click on compact button
3. Observe the components

## Result  
Simple select doesn't seems to be in compact mode as the 'Compact select' where display density is set explicitly

## Expected result  
Select should respect the injected display density

**Comment by IvayloG** [comment]
Duplicated of https://github.com/IgniteUI/igniteui-angular/issues/3911

**Comment by IvayloG** [comment]
I have reopened this issue to fix the DisplayDensityToken specific functionality here and edit #3911 so it will contain only the styling fix portion required.
