### ISSUE TITLE
Multi-View Calendar Styling Issues

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#5857]
## Description  

 * igniteui-angular version: 8.2.x

#### Days labels are misplaced with the days number when calendar width become smaller.
![image](https://user-images.githubusercontent.com/34240583/65603250-ff798100-dfad-11e9-971d-a0d3d703c0c1.png)

#### When calendar selection type is "multi" and select more than one date, the styling applied to the disabled dates is not correct.
![image](https://user-images.githubusercontent.com/34240583/65603443-57b08300-dfae-11e9-80ca-74ff797a3ac3.png)

#### There is no clear visual difference between the weekend days and the disabled dates.  
![image](https://user-images.githubusercontent.com/34240583/65603589-9e05e200-dfae-11e9-8665-d48db6f374e0.png)

**Comment by StefanIvanov** [comment]
@ddincheva "There is no clear visual difference between the weekend days and the disabled dates." is by design but the others are visual bugs and glitches indeed

**Comment by hanastasov** [comment]
When calendar selection type is "multi" and select more than one date, the styling applied to the disabled dates is not correct. -- RESOLVED
Days labels are misplaced with the days number when calendar width become smaller. - not a bug.
