### ISSUE TITLE
IgxColumnGroupComponent field is undefined

### ISSUE THREAD

**Issue by Elburevestnik** [IgniteUI/igniteui-angular#5874]
Hello, i use data igx-grid. 
I added subheader, and im wanting get field from IgxColumngroupComponent for my business logic. But when i do this, i get field = underfined. How i can get there?
Thank in advance.

**Comment by Aleksandyr** [comment]
Hello @Elburevestnik Could you please take a look at our topics [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/multi_column_headers.html). This particular topic is showing how you should bind and render a grid with multi-column headers.

If that is not helping, could you please give us more information on your workflow and what exactly you are trying to achieve?

Also, It will be easier if you can show us directly on this [live editable example](https://stackblitz.com/angular/regqdqkooaj) what exactly is your problem.
