### ISSUE TITLE
Column freezing/Pinning on the right (igx-grid)

### ISSUE THREAD

**Issue by sanchhcl** [IgniteUI/igniteui-angular#5879]
Igx-grid currently provides the capability to pin/freeze columns only on the left.
However, looking at the perspective to allow users with an Edit/Delete/Copy option, a column for such functionality would be ideally placed as the rightmost column, that is always visible to the user (without scrolling horizontally)

Further, the horizontal scroll would be applicable to other columns which could be any in number.

Please help me understand if this can be achieved.

Thanks,
Sanchit

**Comment by RolandTa** [comment]
Thats exactly what we need as well. We have a right aligned dropdown action column and want this to be in the visible area all the time.

**Comment by kdinev** [comment]
@sanchhcl @RolandTa We recently did a lot of work on RTL support, and in this context of that work, it should be relatively simple to implement right pinning in the context of LTR as well. 

@radomirchev Can we assign this to next sprint to look at?

**Comment by RolandTa** [comment]
Any news on this topic? We are approaching our release target and would otherwise rearrange our grid definition to overcome this limitation (ie pin it to the left), but it would be the only component which has left aligned action controls.

**Comment by radomirchev** [comment]
@RolandTa this feature and RTL support have been postponed for the next milestone in our roadmap. The feature could be reviewed next sprint, starting 17th of Dec.

**Comment by Raju-N** [comment]
@radomirchev When can we expect this feature in live. Any approx month is also fine which could help us to plan.

**Comment by radomirchev** [comment]
@Raju-N development of the feature has started, you could expected it to be included in 9.1.0 release package.

**Comment by StefanIvanov** [comment]
Hi, I am sharing a toolbar dropdown design that would support both left and right pinning. If a column is pinned left and we click on the pin right icon, it would work as a radio button and unmark left pinning and remove it from the left pin area before continuing with pinning right. To disable pinning on a pinned column one has to click on the active color, which would result in both icons appearing in idle state.
![right](https://user-images.githubusercontent.com/1702064/74341210-f861dc80-4daf-11ea-99f4-a019205cf86a.png)
