### ISSUE TITLE
HierarchicalGrid throws error when clearing advanced filtering on a nested grid

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#5891]
## Description  
HierarchicalGrid throws error when clearing advanced filtering on a nested grid.

 * igniteui-angular version: 8.2.x
 * browser: NA

## Steps to reproduce  

1. Open https://stackblitz.com/angular/nlrxbbrepjx
2. Open the Advanced Filtering Dialog for a nested grid.
3. Apply any filter.
4. Open the Advanced Filtering Dialog again.
5. Click Clear Filter button.

## Result  
An error is thrown in the console: _Cannot set property 'owner' of null_

## Expected result  
No errors should be thrown.

**Comment by MayaKirova** [comment]
Duplicate of https://github.com/IgniteUI/igniteui-angular/issues/6268
Already resolved in 8.2.14.
