### ISSUE TITLE
Keep grid from emitting scroll event

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#5892]
## Question  
If you have a virtualized grid, by default, when you reach the top or bottom of the grid, scrolling will continue in outer container (if any). Is there a way to keep this from happening currently? Meaning scrolling inside the grid will only scroll the grid?

 * igniteui-angular version: 7.3.4
 * browser: Chrome

**Comment by mpavlinov** [comment]
@Eralmidia AFAIR we did this on purpose to make it work the same as every other scrollable container in the browser.

**Comment by Eralmidia** [comment]
@mpavlinov Thanks, I do get this being the default behavior. It's just that if you have a grid with say 10 visible rows, and the total rows is just a few more than 10 (in this case the total number of rows are variable, so no way to tell if will be 12 or 120 before data is loaded, hence the virtualization), its hard to perform scrolling to the hidden rows, because every mouse wheel tick starts scrolling the page as well.

**Comment by Eralmidia** [comment]
Here's a stackblitz showing sort of what I mean. It's very hard to scroll that grid and actually not move the page https://angular-trjjem.stackblitz.io/

**Comment by mpavlinov** [comment]
@Eralmidia Try to bind to the "wheel" event of the grid TBODY and prevent the default action like this:
```js
public ngAfterViewInit() {
  this.grid1.tbody.nativeElement.addEventListener("wheel", (e)=>{e.preventDefault();});
}
```
Here is a StackBlitz: https://stackblitz.com/edit/angular-trjjem-wrjcjz

**Comment by Eralmidia** [comment]
@mpavlinov Thanks, I'll try this out. I'll close this, to not clutter your git 😉
