### ISSUE TITLE
Error is thrown for the paginator when it is not visible and trying to load persistence data

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#5894]
## Description  
Error is thrown for the paginator when it is not visible and trying to load persistence data.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open the **State persistence** demo on the following topic in stackblitz:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence
(**NOTE**: Make sure the local storage is empty.)
2. Filter by any column so there are no filtered-in results and thus the paginator is not visible.
3. Click the "About" hyperlink to navigate to a separate component.
4. Click the "Go Back" button.

## Result  
The following error is thrown in the console:
**Attempt to use a destroyed view:**
![image](https://user-images.githubusercontent.com/12784974/65959038-9e442880-e459-11e9-845a-a09b2de4d486.png)

It seems the error is caused by a **detectChanges** call for the **paginator** component as seen here:
![image](https://user-images.githubusercontent.com/12784974/65959287-422dd400-e45a-11e9-8224-9d2d6c0b17f2.png)

## Expected result  
No error is thrown and the grid loads its state correctly.

**Comment by hanastasov** [comment]
With upcoming version 9, there is the IgxGridState persistence directive, where the issue is fixed.
