### ISSUE TITLE
Tabs component does not support RTL

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#5904]
## Is your feature request related to a problem? Please describe.
The tabs component doesn't have right-to-left support.

## Describe the solution you'd like
I would like to have right-to-left support.

**Comment by radomirchev** [comment]
@DiyanDimitrov , is the issue considered in the (Tabs Refactoring)[#8793]?

**Comment by DiyanDimitrov** [comment]
> @DiyanDimitrov , is the issue considered in the [Tabs Refactoring](https://github.com/IgniteUI/igniteui-angular/issues/8793)?

No, it is not considered.
