### ISSUE TITLE
[igx-select] Footer element 

### ISSUE THREAD

**Issue by sboykova** [IgniteUI/igniteui-angular#5911]
## Is your feature request related to a problem? Please describe.
I need an element which is always into view when scrolling the select items

## Describe the solution you'd like
I want to have a way to define igx-select footer element.

## Additional context
![image](https://user-images.githubusercontent.com/11226391/66141687-c2943680-e60c-11e9-958a-359222da90ba.png)

**Comment by StefanIvanov** [comment]
Have you considered using the igx-combo as it support header and footer templates?

**Comment by sboykova** [comment]
igx-combo comes with multiple selection - and we just need the single selection igx-select.

**Comment by StefanIvanov** [comment]
OK we have discussed with @radomirchev to add the same type of templatable header and footer areas to the igx-select as we have in the combo.
I have added a story at the bottom of dev stories in the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/IgxSelect-Specification#developer-stories)
