### ISSUE TITLE
Grid with single row selection mode allows select all rows

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#5912]
## Description  
On `igx-grid` with the input `[rowSelection]="'single'"`, the header cell "select all" is clickable and it does select all rows (multiple), and it also emits the event `(onRowSelectionChange)="handleRowSelection($event)` with data containing all rows.

 * igniteui-angular version: 8.2.1
 * browser: Chrome (Version 77.0.3865.90)

## Steps to reproduce  

1. Go to the demo at https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html
2. Select "Single" mode
3. Click on the header cell "select all" (even though the checkbox is hidden)

## Result  
All rows are selected and the event `onRowSelectionChange` is being called.

## Expected result  
Should not change the current selection (if any), and should not call the event.

## Attachments  
n/a

**Comment by hanastasov** [comment]
Nice catch ! I confirm this is a bug.
