### ISSUE TITLE
In Multi-View Calendar there is inconsistent behavior when press arrow up and down

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5913]
## Description  
In Multi-View Calendar the is inconsistent behavior when press arrow up and down

 * igniteui-angular version: 8.2
 * browser: n/z

## Steps to reproduce  

1. Open dev sample http://localhost:4200/calendar
2. Select 1st October and press arrow up or arrow left
3. The months are changed with 1 month
4. Select 30th November and press arrow right or down

## Result  
The months are changed with 3

## Expected result  
When pressing arrow key the month should be changed with same count

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by hanastasov** [comment]
This is by design and not a bug.
