### ISSUE TITLE
Excel export performance

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular#5921]
## Description  
excel export takes more than 15 seconds

 * igniteui-angular version: 8.2.x
 * browser: chrome

## Steps to reproduce  

1. Create grid with dimensions: 100 rows x 320 columns
2. Apply Conditional Cell Styling on all columns
2. Export to excel

## Result  
>15 seconds to have the download available

## Expected result  
Significant reduce of timing

**Comment by tachojelev** [comment]
After testing the performance of the excel exporter for the grid, we were unable to reproduce the issue in regards to the time it takes for the operation to finish.

**Comment by radomirchev** [comment]
## Result  
Bug is not reproducible. Time to download is within expectations
