### ISSUE TITLE
When expand a row and click on a cell to select row, the focus starts to move from previous row to current

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5924]
## Description  
When expand a row and click on a cell to select row, the focus starts to move from previous row to current

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1.Open dev sample hierarchicalGrid
2. In the first grid,scroll to bottom and expand row with id 13
3. Click on a cell in this row

## Result  
The focus starts to move from this row to row with id 12

## Expected result  
Only the row with id 13 should be selected

## Attachments  

![RS](https://user-images.githubusercontent.com/11463104/66294627-15fad300-e8f2-11e9-8963-ca176da67065.gif)

**Comment by ddincheva** [comment]
This issue is no longer reproducible in version 8.2.x or 9.0.x
