### ISSUE TITLE
Events not fired when filter expression/sorting is changed

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular#5929]
## Description  
Events are not fired when filter expression / sorting is changed (externally)

 * igniteui-angular version: 8.2.x
 * browser: chrome

**Comment by MayaKirova** [comment]
@kdinev 
We have already exposed *Change events for two-way binding for all state inputs (including sortingExpressions/filteringExpressionsTree etc.) as part of this issue: https://github.com/IgniteUI/igniteui-angular/issues/3323
Which means we already trigger an event on the related property setters - sortingExpressionsChange/ filteringExpressionsTreeChange.

Depending on what the user wants to achieve he can use those events instead. Triggering the other events as well on the property setters seems redundant.

**Comment by amitmoondra** [comment]
cool
