### ISSUE TITLE
Add option to set an igxIcon size.

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular#593]
### Description  
Add option to set an igxIcon size

### Result 

Currently there is no property/attribute to set the size. It is always 24px.

### Expected result  
Add option to set the size to small, medium and large:

<igx-icon name="search" size="large"></igx-icon>

**Comment by bkulov** [comment]
We discussed the need of having predefined icon sizes. As it's now possible to set the icon size with CSS we decided to close this item.
