### ISSUE TITLE
8.2.* IgxGridComponent.updateRow poor performance

### ISSUE THREAD

**Issue by demingjs** [IgniteUI/igniteui-angular#5934]
## Description  
After updating from 8.1.5 to 8.2.2, the performance of updateRow has degraded significantly , even if newer features are disabled such as advanced filtering.

 * igniteui-angular version: 8.2.2
 * browser: Chrome Version 73.0.3683.103 (Official Build) (32-bit)

## Steps to reproduce  
Click on the below links to view performance difference.

1. Create igx-grid with realtime updating rows via the updateRow function call

## Result  
The grid updates very slowly, with greatly increased time needed for each updateRow call.

## Expected result  
The grid should perform as it did in version 8.1.5

## Attachments  
igniteui-angular@8.1.5:  (grid updates normally)
    https://stackblitz.com/edit/angular-wkbmwm

igniteui-angular@8.2.2: (grid updates slowly)
    https://stackblitz.com/edit/angular-wkbmwm-vqzsup

**Comment by wnvko** [comment]
@demingjs in 8.2 we have changed the way grid repaint itself. It is now happens less often and only when it is needed. What happens in your 8.1.5 sample is grid tries to repaint each time you call `updateRow`. In 8.2.2 grid repaints about 10 times less. If you start the two samples side by side you will see that `curr` value updates with same speed in both versions. Long story short - the performance in both samples is same, but in 8.2.2 grid does not repaint on each `updateRow` call.
However we will try to force the grid to update after each call to `updateRow`, if this does not break anything in the grid. We will schedule this test for some of the next sprints.

**Comment by demingjs** [comment]
@wnvko - I actually am not seeing the curr value updating at the same speed.  I updated each example to show the curr value above the grid, and when I run start both applications side by side I see the 8.2.2 version fall way behind 
8.1.5 = 200000
8.2.2 =   15000

**Comment by wnvko** [comment]
@demingjs this is strange. I did the same test in Google Chrome and in both versions there were no difference in the speed (you may check attached in the archive video).
As I wrote we will try to fix `updateRow`. However, as you have bigger issue in your application, please try to isolate it and send us a sample for further investigation.

[GoogleChrome.zip](https://github.com/IgniteUI/igniteui-angular/files/3725191/GoogleChrome.zip)

**Comment by demingjs** [comment]
@wnvko Interesting.  What version of chrome are you using?

**Comment by wnvko** [comment]
@demingjs I am with version 77.0.3865.120 (Official Build) (64-bit)

**Comment by demingjs** [comment]
@wnvko Thank you - I will do some testing with chrome versions this evening.  What is interesting is that in your video, both sides seem to be updating at a slower speed.

**Comment by demingjs** [comment]
@wnvko I was able to test at home using the same version of chrome as you (Version 77.0.3865.120 (Official Build) (64-bit)) and I am still seeing the same performance issues - please see the attached video.  As you can see - the 8.1.5 version is significantly faster.  You can also see mouse interaction comparisons as I hover over each side.  The grids in your video  seem to be updating more slowly than my 8.1.5 grid - is it possible that the performance difference just isn't as noticeable on your box?

[ChromePerformance.zip](https://github.com/IgniteUI/igniteui-angular/files/3727094/ChromePerformance.zip)

**Comment by demingjs** [comment]
@wnvko  @Lipata  Have you had a chance to try this out on any other machines?  Curious if that could be the issue.  I have tried the demo above on 4 different computers and they all have the same performance issue.  Thank you!
