### ISSUE TITLE
Row selection not working correctly with custom cell template for grid

### ISSUE THREAD

**Issue by Lightw3ight** [IgniteUI/igniteui-angular#5935]
## Description  
When I have `rowSelection="multiple"` and I have an editable column with a custom cell template, if I start editing a cell and then click on the text content of another cell in the same column, the row will not be selected

 * igniteui-angular version: 8.2.0
 * browser: Chrome 77.0.3865.90

## Steps to reproduce  

1. Go to https://stackblitz.com/angular/yvmxnqjqxrx
2. Replace the html of the grid to the snippet below
3. Double click on a cell to enter edit mode of the cell (row will be selected)
4. Single click on the text content of another cell, this cell will enter edit mode but the row will not be marked as selected (this is the bug)
5. Single click on anywhere but the text content of another cell, this cell will enter edit mode and the row will be selected (This is for comparison)

```html
<div class="grid__wrapper">
    <igx-grid #myGrid [data]="data" primaryKey="ID" rowSelection="multiple" cellSelection="none">
        <igx-column field='ContactName' [editable]="true">'
          <ng-template igxCell let-cell="cell">
              <div>{{cell.value}}</div>
          </ng-template>
        </igx-column>
    </igx-grid>
</div>
```

## Result  
What is the actual result after following the steps to reproduce?
The row is not selected

## Expected result  
What is the expected result after following the steps to reproduce?
I should be able to click anywhere in a cell and it will select the row

## Attachments  
The below screenshot shows a cell in edit mode but not selected
![image](https://user-images.githubusercontent.com/740446/66344639-d6dc8880-e9aa-11e9-89c1-b98e960bca3a.png)

**Comment by ddincheva** [comment]
Hello,
As you most probably read in the our [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html#grid-row-selection), we provide only tree modes for row selection. 
But the requested behavior is quite easy to achieve, you only need to stop propagation of the cell click event. `(onCellClick)="$event.event.stopPropagation()"` . [Here](https://stackblitz.com/edit/angular-jy6uun) I built a sample which should fulfill your use case. 
Please review it and share with us if you have any concerns.

**Comment by Lightw3ight** [comment]
> Hello @Lightw3ight ,
> As you most probably read in the our [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html#grid-row-selection), we provide only tree modes for row selection.
> But the requested behavior is quite easy to achieve, you only need to stop propagation of the cell click event. `(onCellClick)="$event.event.stopPropagation()"` . [Here](https://stackblitz.com/edit/angular-jy6uun) I built a sample which should fulfill your use case.
> Please review it and share with us if you have any concerns.

Are you perhaps replying to my feature request? - https://github.com/IgniteUI/igniteui-angular/issues/5936

**Comment by ddincheva** [comment]
Yes, this is about #5936. I am sorry, I will move my comment there :)

**Comment by ddincheva** [comment]
Hello @Lightw3ight,
In order for the row selection to have the same behavior as default, when you've defined a custom cell template you just need to add style="pointer-events: none;" to the element that wrap the cell content, because if your template catch the pointer events, the cell can not manage its state properly. Please review [this sample](https://stackblitz.com/edit/angular-votui3) and check if this solution fulfill your requirements.

**Comment by zdrawku** [comment]
@Lightw3ight, let us know if you have any other questions
