### ISSUE TITLE
Native add row

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#5946]
## Is your feature request related to a problem? Please describe.
It would be nice to have native support for adding a new row. This can of course be accomplished today with the edit row functionality, but it is a bit cumbersome.

For instance in some cases a grid have read only columns, meaning that row edit for those columns are disabled. But when adding a new row, these columns may still need an input. In other cases, a grid might be fully read only, but still have the ability to add new rows, in which case we need to enable/disable row editing when row adding starts/ends.

## Describe the solution you'd like
A distinction between add new row and edit exiting row

**Comment by Eralmidia** [comment]
Just to add the discussion from #5947 to this thread: it would be great if the add row used the same transaction based system as editing. Like many others, we use state managements libraries (ngrx, ngxs, akita ect). These systems stream immutable objects, which in turn typically means that the data source for the grid also is immutable, and edits should result in store updates, rather than manipulation of a local array of data.

**Comment by Eralmidia** [comment]
@kdinev Any chance of including this in the not to distant future? 🙏

**Comment by kdinev** [comment]
@Eralmidia It's actually a good time to ask this question. We're currently building the roadmap for the next iterration.

@radomirchev Can we consider this for the next milestone, or is the milestone full already?

**Comment by Eralmidia** [comment]
@kdinev @radomirchev  Did this make it into the milestone?

**Comment by radomirchev** [comment]
@Eralmidia what we have in the current milestone is Row Pinning #6640 which is prerequisite for a solution for your request.  The development has started this sprint. Once is ready we will start working on the sample. You could follow the sprints schedule and progress [here](https://github.com/orgs/IgniteUI/projects).

**Comment by Eralmidia** [comment]
@radomirchev  I see this was moved to validation in the current sprint. Will it be in 10.2?

**Comment by StefanIvanov** [comment]
Hello @Eralmidia we have a design that we are validating internally, so to be more exact the feature is still in the design/specification phase that we plan to finish very soon

**Comment by ChronosSF** [comment]
@Eralmidia , I am happy to inform you that we added the requested functionality with the latest 10.2.0 release. Please, check the documentation for more information - https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_adding.html

**Comment by Eralmidia** [comment]
@ChronosSF One question: how do you trigger the add row grammatically? We generally have buttons etc outside the scope of the grid which also needs to be able to start a new add row (for instance from a menu bar in the feature module). I see the addRow method, but this was present before 10.2 as well, so I assume this still just inserts an empty row into the grid?

**Comment by ChronosSF** [comment]
There is something wrong with the API docs missing the new stuff for 10.2 that we are looking into.

The idea is for the API to correspond with the design, so spawning the UI  happens when you call the `beginAddRow` method for a given existing `IgxGridRowComponent` (you can get all of those instances with `grid.rowList` . For tree grid rows you also have `beginAddChild` .

**Comment by Eralmidia** [comment]
@ChronosSF  Excellent, I'll await the docs fix, and try out the new feature soon 👍
