### ISSUE TITLE
When there is no group column and change summaryModes the grid size in not changed

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5960]
## Description  
When there is no group column and change summaryModes the grid size in not changed

 * igniteui-angular version: 8.2.x
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridGroupBy
2. Click on button "ChildLevelOnly"

Note: this is not reproducible in [samples](https://www.infragistics.com//angularsite/components/grid/summaries.html#summaries-with-group-by)

## Result  
Grid is not resized and the empty summary row is displayed

## Expected result  
Grid should be resized

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/66552201-9408e500-eb51-11e9-941a-b577fed41a4a.png)

**Comment by ddincheva** [comment]
This issue  is no longer reproducible in 8.2.x and 9.0.x.
