### ISSUE TITLE
Should add tooltip for truncated column titles. 

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#5962]
## Is your feature request related to a problem? Please describe.
when grid has many column user resize them. Now column width is reduced to less than column name ( header caption). Until user resize back to original size it is difficult to know what column it is?  

## Describe the solution you'd like
In this case column header should show tool tip to show full column name. So user will know what column it is without resizing it.

**Comment by tachojelev** [comment]
Hello @deepakvia ,

You can currently achieve the desired behavior of showing a tooltip for the column headers when they are overflown by providing a simple **igxHeader** template.

```html
<igx-grid>
    <igx-column>
        <ng-template igxHeader let-column="column">
            <span #el
                   [igxTooltipTarget]="tooltip1"
                   [tooltipDisabled]="el.parentElement.scrollWidth <= el.parentElement.clientWidth"
                   (onTooltipShow)="tooltip1.context = column;">
               {{column.header}}
            </span>
        </ng-template>
    </igx-column>
</igx-grid>

<div #tooltip1="tooltip" igxTooltip>{{tooltip1.context?.field}}</div>
```

**Comment by kdinev** [comment]
@deepakvia We can add a `title` in the default template of the columns, which would always display the default browser tooltip on columns.

**Comment by deepakvia** [comment]
> Hello @deepakvia ,
> 
> You can currently achieve the desired behavior of showing a tooltip for the column headers when they are overflown by providing a simple **igxHeader** template.
> 
> ```
> <igx-grid>
>     <igx-column>
>         <ng-template igxHeader let-column="column">
>             <span #el
>                    [igxTooltipTarget]="tooltip1"
>                    [tooltipDisabled]="el.parentElement.scrollWidth <= el.parentElement.clientWidth"
>                    (onTooltipShow)="tooltip1.context = column;">
>                {{column.header}}
>             </span>
>         </ng-template>
>     </igx-column>
> </igx-grid>
> 
> <div #tooltip1="tooltip" igxTooltip>{{tooltip1.context?.field}}</div>
> ```

@tachojelev - yes this works. But we have large number of grid screens with average 20 columns. That's lot of work. Ideally grid should handle it.
