### ISSUE TITLE
[Combo] Add option to disable search input autofocus on combo

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#5968]
## Is your feature request related to a problem? Please describe.
Currently, when the combo's list of items is opened, the control automatically puts the focus on the search input. For mobile users this will cause a keyboard to show, making scrolling through the list of items more tedious (in some cases, users have to first close the keyboard in order to see the items)

## Describe the solution you'd like
Implement an optional input for the combo (for example, `suppressAutofocus`, `false` by default) that, when set to true, prevents the search input from taking focus when the combo is opened:
```html
<igx-combo [suppressAutofocus]="true"></igx-combo>
```

## Describe alternatives you've considered
A possible workaround is to handle focus on the combo's `onOpened` event. However, this leads to the keyboard flickering, because the default focus switch happens right before the event emit.

## Additional context
When search input focus is suppressed, the focus could move to the drop-down list (as that element needs to be focused to capture keyboard input for navigation).

**Comment by Lipata** [comment]
https://github.com/IgniteUI/igniteui-docfx/issues/1924
