### ISSUE TITLE
When expand a child row, its children grids ExpandAll icons are not correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#5971]
## Description  
When click on expand all in child grid, its children indicators are not correct

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGrid
2. In the first grid expand row with id 2
3. In its child click on expand all icon
4. Look at the children grids

Note: Same is valid when expand a row.

## Result  
All the rows in the child are expanded, but their child grid has ExpandAll icon '-', but they are not expanded

## Expected result  
The child grids expandAll icon should be '+'

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/66735551-57016300-ee6f-11e9-8df3-8abe9b3b1f65.png)

**Comment by VMihalkov** [comment]
This is the collapse indicator, which is always shown, when [showExpandAll]='false'. It can be disabled in the template. If you remove the template, default collapse indicator will be shown, but it is disabled by default. 
In the same sample, on the second grid, under Sample Two, you can trying setting showExpandAll to 'false' and see that the collapse all indicator is shown again, but is disabled by default.

**Comment by nrobakova** [comment]
Close because of the comment
