### ISSUE TITLE
Slider with max value is not 100% filled out in Grid cell template

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#5974]
## Description  
Slider is not filled out when the `value` is equal to `maxValue` on initial Grid rendering

 * igniteui-angular version: 8.2.0
 * browser: any

## Steps to reproduce  

1. Open the [sample](https://stackblitz.com/edit/angular-slider-100-issue)

## Result  
![image](https://user-images.githubusercontent.com/11193764/66749292-27b01d80-ee92-11e9-9a55-8978f7f3fdc9.png)

## Expected result  

`Note:` Scroll the grid vertically and let the ng-template to perform change detection because of the virtual for, and the

**Comment by Aleksandyr** [comment]
This is no longer reproducible with the latest stable: 9.0.14v.
