### ISSUE TITLE
There is no indication whether advanced filtering is applied in the toolbar button

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#5983]
## Description  
Previously we were highlighting the icon of the advanced filtering button when a filtering is applied. Now there is no visual indication that advanced filtering is applied.

 * igniteui-angular version: 8.2.x
 * browser: NA

## Steps to reproduce  

1. Open the Grid Filtering dev demo.
2. Look at the Advanced Filtering button in the toolbar.

## Result  
There is no indication that an advanced filtering is applied.

## Expected result  
There should no indication that an advanced filtering is applied.

## Attachments
![image](https://user-images.githubusercontent.com/43128948/66808973-0f450f00-ef35-11e9-94c3-c8acc9c76e2b.png)

**Comment by DiyanDimitrov** [comment]
@DaniMarinov, previously the text color of the buttons in the toolbar was gray and only the filtering icon was orange when a filter is applied. After fixing #5782 the buttons now have orange text color and there is no indication whether a filter is applied or not. Do you think we could add some other indication for applied filter?

**Comment by DanailSMarinov** [comment]
@DiyanDimitrov I will prepare two designs:
- when the AF dialog is currently on (the AF dialog is opened and active)
- when there are applied filters and the AF dialog is closed

So, we will cover 3 states in general - idle (the AF dialog is closed/not active and there are no applied filters), active (AF dialog is active), applied filters (when the AF dialog is closed, but there are applied filters)
What do you think about that?

**Comment by DaniMarinov** [comment]
@DiyanDimitrov  I will prepare two designs:

when the AF dialog is currently on (the AF dialog is opened and active)
when there are applied filters and the AF dialog is closed
So, we will cover 3 states in general - idle (the AF dialog is closed/not active and there are no applied filters), active (AF dialog is active), applied filters (when the AF dialog is closed, but there are applied filters)
What do you think about that?

**Comment by DiyanDimitrov** [comment]
@DaniMarinov, sounds good to me.

**Comment by DaniMarinov** [comment]
@DiyanDimitrov In order to keep it consistent with all other components (such as Excel Style Filtering), I've decided to use the same styling for Idle and Active (opened AF dialog). Find below my proposal:
![button_states](https://user-images.githubusercontent.com/41998471/66828993-0bc47e80-ef5b-11e9-91ea-6309bbfe96e7.jpg)
I will update the spec.
