### ISSUE TITLE
Exposing a way to provide a custom template for grid rows

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#5988]
## Is your feature request related to a problem? Please describe.
Currently, there is no way for templating the row of the igx-grid.

## Describe the solution you'd like
Ability to provide a custom template for grid rows.

**Comment by Aleksandyr** [comment]
@radomirchev @kdinev @rkaraivanov Do you think this is doable as a request?

**Comment by ChronosSF** [comment]
Imo, the biggest hurdle is when the customer templates the cells without using igxFor as that will mess a lot of internal logic.

And AFAIK we only allow templates where we can ensure most of them won't break something . But @rkaraivanov may correct me.

**Comment by kdinev** [comment]
@ChronosSF @Aleksandyr @rkaraivanov I don't think it's possible to implement a full row template and ensure correct rendering with a mix and match of all features exposed through the grid. Some of the features do render additional columns, or have elements in the templates of the first column cells. The most I see done is to expose a way to apply styles and css classes on the row element, in a similar fashion we do for cells.
