### ISSUE TITLE
WARNING in Invalid property name 'margin-if-left(left, right)' at 6388:2. Ignoring.

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6030]
### Description  
After updating an Angular Project from using npm package igniteui-angular version 8.2.3 to 8.2.5

When I run an ng build command the project compiles, but the following Warning Message displays inside the console "WARNING in Invalid property name 'margin-if-left(left, right)' at 6388:2. Ignoring."  If I open file igniteui-angular.css it looks like there are properties defined with the name "margin-if-left" which is not a valid CSS property name.

 * igniteui-angular version: 8.2.5
 * browser: Version 77.0.3865.120 (Official Build) (64-bit)

### Steps to reproduce  

1. ng update igniteui-angular
2. ng build --configuration=prod
3. Warning Message displays inside console

### Result  
What is the actual result after following the steps to reproduce?
Warning message displays "WARNING in Invalid property name 'margin-if-left(left, right)' at 6388:2. Ignoring."

### Expected result  
What is the expected result after following the steps to reproduce?
Do not expect to see warning message

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by brookhutchinson** [comment]
Thank you for fixing this issue.  When will the code for this issue be part of a release?

**Comment by simeonoff** [comment]
> Thank you for fixing this issue. When will the code for this issue be part of a release?

It should be available in the next minor release.
