### ISSUE TITLE
Rich Text Editor for Igniteui-angular

### ISSUE THREAD

**Issue by SteJoeJohn** [IgniteUI/igniteui-angular#6039]
## Is your feature request related to a problem? Please describe.
We are writing apps in Angular 8 and looking for a Rich Text Editor to use within the app.   Have not found one.  We are considering Infragistics for other controls in our apps, and have noted that one if available within your JavaScript solution and hoped you could make it available directly in the angular tools.

## Describe the solution you'd like
Have a component within the Ignite for Angular suite

**Comment by zdrawku** [comment]
Hey @SteJoeJohn, thank you for this feature request. We do have [a jQuery igHtmlEditor](https://www.igniteui.com/html-editor/overview) in Ignite UI for JavaScript product, although there isn't a way to translate it to Angular. If such a request is approved and planned by our product owner, it would take part in [our roadmap](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md) and this issue will be updated accordingly.

**Comment by SteJoeJohn** [comment]
We found and tried the angular wrapper for the Javascript version,but it doesn't work when you add it within any angular tags (mat-tab for ex).  We were hesitant using the wrapper to begin with due to bloat and the need to bring jquery into angular, but it doesn't seem to work if it is nested inside any angular tag (mat-tab for ex).

**Comment by zdrawku** [comment]
We understand where you're coming from, this is why the item has been moved to our "Discovery" board. You can check our [roadmap ](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md)for any updates

**Comment by prabakaran1311** [comment]
Hi Team we are also need this feature to place the html content directly in the web pages using HTML editor please let us know the some tentative time so that we can plan for the development.

**Comment by digeomel** [comment]
I don't think this should be closed. I'm currently evaluating 3 major Angular UI component libraries for enterprise applications, and yours is one of them. The absence of this component is a deal-breaker for us. I understand it's a very complicated component to port from jQuery, but you don't have to. Start small and build up from that. Any option is better than nothing.

Otherwise maybe you can recommend an integration with a 3rd-party solution like ngx-editor?
