### ISSUE TITLE
Scrollbar is not working in Grid & tree grid

### ISSUE THREAD

**Issue by jaya0selva** [IgniteUI/igniteui-angular#6052]
## Description  
Describe the issue.

 * igniteui-angular version: 8.2.5
 * browser: chrome

## Steps to reproduce  
https://stackblitz.com/edit/angular-qpj69p-zdlm2u

## Result  
Earlier versions grid scroll are working with out including igx-core(). But in 8.2.5, scroll bar works only when the igx-core() is added. but it affects our existing application styles

## Expected result  
Grid scroll should work without including the igx-core()

## Attachments  
  
![image](https://user-images.githubusercontent.com/40403770/67510054-e6014d00-f6b1-11e9-9731-1b94c3afc2c3.png)

**Comment by simeonoff** [comment]
@jaya0selva Actually, the scrollbars working without including igx-core was a bug and not a feature. As the [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes.html#generating-a-theme) instructs, you __must__ include the igx-core mixin before declaring a theme.
