### ISSUE TITLE
Can't scroll to top when there is expanded row in Hierarchical Grid

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#6061]
## Description  

 * igniteui-angular version: 8.3.x

## Steps to reproduce  

1. Open Hierarchical Grid Dev sample
2. Expand the row with ID =  2
3. Scroll the grid to the bottom
4. Try to scroll back to the top

## Result  
It is not possible to scroll back to the top.
If you click over some cell and navigate with Arrow Up the following error is thrown:
![image](https://user-images.githubusercontent.com/34240583/67568829-f22eee00-f735-11e9-8887-92c5de87007a.png)

## Expected result  
Should be able to navigate to the first row in the grid.

**Comment by ChronosSF** [comment]
Possibly related to #6004
