### ISSUE TITLE
What release is Issue #5842 part of?

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6062]
## Question  
Issue #5842 is marked as resolved.  What release is Issue #5842 part of?  If it has not been released then when will this issue be released?

 * igniteui-angular version: 8.2.3
 * browser: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by tachojelev** [comment]
Hello @brookhutchinson ,

The #5842 issue was an issue in the sample itself, not the actual **igniteui-angular** product.
The behavior is fixed and it is visible on the [live sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence).

**Comment by zdrawku** [comment]
@brookhutchinson next sprint we plan to start working on the state persistence directive, as Tacho said you can track its progress in the [issue](https://github.com/IgniteUI/igniteui-angular/issues/5460)
