### ISSUE TITLE
Grid body height is not calculated correctly when there is a custom footer.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#6065]
## Description  
When defining a custom footer for the IgxGrid, the body container where the grid rows should be rendered is not resized so it takes into account the footer. That is why the vertical scrollbar disappears behind the footer when the user have scrolled to the bottom.

 * igniteui-angular version: 8.2.x
 * browser: any

## Steps to reproduce  

1. Open the Column Moving demo and add a custom footer.
2. Scroll to the bottom of the grid.

## Result  
The vertical scrollbar gets partially hidden by the footer.

## Expected result  
The footer shouldn't appear on top of the vertical scrollbar..

## Attachments  
![Custom_footer_grid](https://user-images.githubusercontent.com/3768136/67586626-bce8c700-f75a-11e9-82a1-9eda7e0cf34f.jpg)

**Comment by JIBIN-P** [comment]
Also why is <igx-grid-footer> not mentioned in the documentation?
