### ISSUE TITLE
[igx-grid] Setting initial filter throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6066]
## Description  
Setting the initial filter on igx-grid throws angular exception ExpressionChangedAfterItHasBeenCheckedError

I used the example at https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html#initial-filtered-state

 * igniteui-angular version: 8.2.5
 * browser: Chrome (Version 77.0.3865.120)

## Steps to reproduce  

1. Open sample at https://stackblitz.com/edit/angular-ppkzgw
1.1. This sample was created from https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html#retemplating-filter-cell, and then added the initial filter instructions at https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html#initial-filtered-state
2. After loading sample, open console

## Result  
What is the actual result after following the steps to reproduce?
Console shows error (even though data is being filtered):
```
ERROR
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined: '. Current value: 'undefined: [object Object],[object Object],[object Object],[object Object],[object Object]'.
```

## Expected result  
What is the expected result after following the steps to reproduce?
No error.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
n/a

**Comment by tachojelev** [comment]
Hello @mimurawil ,

The **ExpressionChangedAfterItHasBeenCheckedError** you have referred to is actually an error that occurs when an expression or view element has been updated after Angular has checked it. This is not an issue in the grid itself, because such scenario is applicable for any Angular component.

In order to fix this, you can manually trigger another change detection cycle by invoking the **ChangeDetectorRef**'s **detectChanges** method after the modification logic in the AfterViewInit hook.

```html

constructor(private cdr: ChangeDetectorRef) { }

ngAfterViewInit() {
    ...
    this.grid1.filteringExpressionsTree = gridFilteringExpressionsTree;
    this.cdr.detectChanges();
}
```

**Comment by mimurawil** [comment]
Hello @tachojelev,

Sorry for the late reply, and thank you for your suggestion. It solved the error log!

I believe this instruction should be mentioned at https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html#initial-filtered-state, correct? Or is there any other documentation/instruction in the website?

**Comment by mimurawil** [comment]
I'm closing this issue as it's only concerned about the error log. You guys can open another issue to update the docs, or reopen this one and update the description if you'd like to.

**Comment by tachojelev** [comment]
Hello @mimurawil ,

We will update the **initial filtered state** section of the documentation, so it includes the detectChanges call. You can track its progress [here](https://github.com/IgniteUI/igniteui-docfx/issues/1637).
