### ISSUE TITLE
[igx-DatePicker] DatePicker fires twice on change()

### ISSUE THREAD

**Issue by NoSoup4you2** [IgniteUI/igniteui-angular#6067]
## Description  
When using the DatePicker in a component and using the valueChange Event, it gets fired twice when the user picks a new Date.

 * igniteui-angular version: 8.2.2
 * browser: chrome or IE

## Steps to reproduce  

Enclosed find sample code in StackBlitz
[https://stackblitz.com/edit/github-s61p6b-ykroty](url)

## Result  
Log file will show that the event got fired twice

## Expected result  
Should only fire once the date is changed

**Comment by wnvko** [comment]
In the value setter of `igxDatePickerComponent` we are calling [`_onChangeCallback`](https://github.com/IgniteUI/igniteui-angular/blob/522426dece5e393a385c846f4a34ff0821d29944/projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts#L477) which is correct.
In [`handleSelection`](https://github.com/IgniteUI/igniteui-angular/blob/522426dece5e393a385c846f4a34ff0821d29944/projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts#L1063) of `igxDatePickerComponent` we are setting the component's value, this calls change callback, but we are also wrongly call and value change call back.
We will investigate this on some next sprint and will try to fix it.
