### ISSUE TITLE
igx-list hangs in panning when scrolling is fired on Safari iOS

### ISSUE THREAD

**Issue by PhilippRoessner** [IgniteUI/igniteui-angular#6071]
## Description  
When I try to swipe a list item and move the finger slightly up or down while doing the swipe, the element hangs at the position when I started the scrolling

 * igniteui-angular version: 7.3.1 (can be reproduced in the current stackblitz example with Safari iOS)
 * browser:  Safari iOS

## Steps to reproduce  

1. Open Safari on iOS
2. Go to the panning example on Stackblitz: https://stackblitz.com/angular/vkgjmogxlaae
3. Swipe any Item to any direction and move the finger up or down while siping

## Result  
The swiped item gets stuck at the position where you started to move the finger up or down

## Expected result  
I expect the item not to hang and either snap back or finish the swipe, depending on the threshold

**Comment by astaev** [comment]
Hello @PhilippRoessner 

I tried to reproduce the described behavior but everything works fine on my side with Safari 13 and igniteui-angular@**7.3.5**. Can you check whether you are running the latest Safari, and test it again?

**Comment by PhilippRoessner** [comment]
Hello @astaev 
we noticed this did not occur anymore in newer versions of igx, we don't encounter that issue anymore
