### ISSUE TITLE
IgxGrid Date-Filter crash on restore filtering using filteringExpressionsTree

### ISSUE THREAD

**Issue by muellmarc** [IgniteUI/igniteui-angular#6079]
## Description  
IgxGrid Date-Filter doesn't see to be applied correctly on your demo app. Using ignite-angular, I get the same error.

 * igniteui-angular version: 8.2.3
 * browser: Chrome 77.0.3865.120

## Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence
2. Open the filter on the date column ("Registerer Date")
3. Unselect 1 Date (e.g. Feb 2, 2017) and apply
4. Navigate away by clicking the "About"
5. Go back and try to open the filter again -> you get an exception

## Result  
Date-Filters can't be opened after they were restored
(Error: "t.expression.searchVal.values is not a function")

## Expected result  
Filters were correctly applied and can be opened

**Comment by zdrawku** [comment]
Thank you for pointing that out, next sprint we plan to start working on a [state persistence directive](https://github.com/IgniteUI/igniteui-angular/issues/5460) and we will keep in mind that problem

**Comment by zdrawku** [comment]
@hanastasov will comment here

**Comment by hanastasov** [comment]
Hi @muellmarc, please see a resolved version at https://stackblitz.com/edit/angular-ch71ha
There are two changes related to fixing everything to Excel style filtering and Date objects:
1) parseCallback to convert Arrays to Set is not always needed, so I removed this call from line 87 in state.directive.ts
2) Converting Array to Set is needed only when the searchVal is an array, so this now happens in createExpressionsFromTree, line 193

**Comment by muellmarc** [comment]
Thanks a lot!
