### ISSUE TITLE
On data change?

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#6102]
## Question  
Is there any events for when the data of a grid changes? I tried subscribing to the dataRowList query list, but this doesnt seem to work, and I can't find any onDataChanged event or similar

 * igniteui-angular version: 7.3

**Comment by MayaKirova** [comment]
@Eralmidia 
Depends on what you define as data change. 
If you mean any change that affects which records are currently rendered in the grid – scrolling vertically, changing grid size, applying a data operation (sorting, filtering, paging etc.) and so on, then you can get the vertical virtualization directive from the grid– grid.verticalScrollContainer and subscribe to its [onDataChanged](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxforofdirective.html#ondatachanged) event. For example:
grid.verticalScrollContainer.onDataChanged.subscribe(() => {…});

Let me know if that’s what you are looking for.

**Comment by Eralmidia** [comment]
@MayaKirova Thanks, that's useful info. It seems like the verticalScrollContainer is not mentioned in the docs?

However, I'm not sure that's exactly what I need in this instance. We have a mix of pixel sized columns and percentage columns, and because of this, we do our own calculation for the column widths (making sure the total width of the columns are 100% of the grid size, as we don't like the horizontal scroll for our grids). This works fine, except for one small detail: If the data changes, causing the grid to render a scrollbar, I need to call our width-updating function, since the width of the grid scrollbar now must be taken into account (subtracted from the grid width).

**Comment by MayaKirova** [comment]
@Eralmidia Technically the scrollbar may show/hide on data operations that change the records count like filtering, adding/deleting rows, changing page size, grouping etc. If you happen to have such features in your grids it may be better to use the onDataChange of the virtualization directive as it will trigger for those scenarios as well. 

We don’t expose a specific event for when the grid data is set as typically data changes are handled via a data service, where you can attach observers to track those changes if necessary. Alternatively you can track changes to the grid data collection via [ItterableDiffer](https://angular.io/api/core/IterableDiffer) in case the collection is changed or something is added/deleted from it.

**Comment by Eralmidia** [comment]
Okei, I'll check out the onDataChange event then. Thanks 👍
