### ISSUE TITLE
Improve components' descriptions

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#6104]
## Is your feature request related to a problem? Please describe.
All public components' [descriptions](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html) should be revised and improved if needed.

**Comment by radomirchev** [comment]
Issue is replaced by: [2460](https://github.com/IgniteUI/igniteui-docfx/issues/2460)
