### ISSUE TITLE
Binding to onRowEdit in a hierarchical grid's row island child grid won't return newValue

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#6112]
## Description  
When using onRowEdit.subscribe() on an igx-row-island grid, the returned result is an object, consisting of rowId, oldValue and a null property for the newValue

 * igniteui-angular version: reproduced from 7.2.x to 8.2x
 * browser: Chrome

## Steps to reproduce  

1. Open that sample: https://angular-mqrqkk-jauqkr.stackblitz.com
2. Expand the child grid of the second row
3. Attempt to edit Billboard Review column (replace the existing 86 with, say 100)
4. Press Enter (or just escape the row editing somehow)
5. Observe the Dev Tools for errors

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
Non-null value for newValue

## Attachments  
![image](https://user-images.githubusercontent.com/8365193/68042762-5de7fc80-fcdc-11e9-9491-9943e86b520c.png)

**Comment by mddragnev** [comment]
That is not a product bug but a sample issue. When using igxCellEditor and input in it, two way binding to ngModel is needed to update the values.
