### ISSUE TITLE
[igxAutocomplete] Disabling the autocomplete on item selection doesn't update the UI style correctly in Firefox

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6113]
## Description  
I need to disable the autocomplete control (both input and dropdown) when the user selects an item in the dropdown. The functionality works fine, but the "disabled" style doesn't update in Firefox like in Chrome (this one is correct). 

In Firefox, the style looks like it's still enabled and in focus.

 * igniteui-angular version: 8.2.6
 * browser: 70.0.1 (64-bit)

## Steps to reproduce  

1. Open the demo at https://stackblitz.com/edit/angular-1wdyuf (using Firefox browser)
1.1. This demo was taken from Infragistics sample at https://www.infragistics.com/products/ignite-ui-angular/angular/components/autocomplete.html#demo
2. Type something, so the dropdown shows any result (eg: 'a', or 'b')
3. Choose and click on an item in the list

## Result  
What is the actual result after following the steps to reproduce?
In Firefox, the style of the control doesn't update according to its state (disabled), and it looks like it's still enabled and in focus. 

## Expected result  
What is the expected result after following the steps to reproduce?
If you run the steps in Chrome, you can see the correct result.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
Print screen from Firefox
https://prnt.sc/prcn5u

Print screen from Chrome
https://prnt.sc/prcoen

**Comment by wnvko** [comment]
@mimurawil for some reason the `igx-input-group` retains its `igx-input-group--focused` class. This forces border and label to remain blue. We will plan this for some future sprint.

**Comment by PlamenaMiteva** [comment]
The issue is related with the way Firefox handles the input focus. So, I have created a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1604161). 

Samples:
 [typescript sample](https://bugzilla.mozilla.org/show_bug.cgi?id=1604161)
[angular sample](https://stackblitz.com/edit/angular-firefox-input-focus-ruvvtq)
