### ISSUE TITLE
Additional space rendered when grid row drag is enabled

### ISSUE THREAD

**Issue by Craftwarez** [IgniteUI/igniteui-angular#6124]
## Description  
An additional space seems to be rendering when the grid row drag is enabled and there is no horizontal scroll for the grid.

 * igniteui-angular version: 8.2.6
 * browser: chrome (78.0.3904.87)

## Steps to reproduce  

1. Head to [this demo](https://stackblitz.com/angular/anpgxxkrrgy?file=src%2Fapp%2Fgrid%2Fgrid-row-reorder-sample%2Fgrid-row-reorder.html) and remove the grid width and all column widths. 
2. Remove a few columns so that all columns are visible and rendered on the page. (Open demo in new window if scroll bar is still visible)

## Result  
There is an additional space next to the last column on the grid.
## Expected result  
There should be no additional space next to the last column on the grid.

## Attachments  
Picture of additional space.
![image](https://user-images.githubusercontent.com/17565043/68246598-fafcb980-007d-11ea-9d8e-346074f60fa8.png)

**Comment by 3phase** [comment]
@Craftwarez, the issue was fixed for versions 9.0 and 9.1 while version 8.2 is no longer supported. Sorry for not notifying you earlier.
