### ISSUE TITLE
Carousel enhancements

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#6144]
In order to implement default slide animation, certain changes should be made to the current implementation of the Carousel. Consider adding a navigation buttons and indicator templates, as well as pan interaction with the sliders.

All topics related to these changes should be updated accordingly, which applies for the automation tests based on the updated [Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Carousel-Specification).

**Comment by kdinev** [comment]
Related #6199
