### ISSUE TITLE
igxGrid columns don't autogenerate with enough width

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular#615]
### Description  
When autogenerating columns, the columns don't allocate width according to contents, and therefore by default won't necessarily fully show full header text or column contents.

### Steps to reproduce  

1. create an igxGrid with `[autoGenerate]="true"`
2. bind to data with properties named at least 9 characters long
--- You can use my sample at https://github.com/jVanZwieten/mercury for this
3. install, build, start

### Result  
Columns with headers/contents significantly long have their contents abbreviated with ellipsis.

### Expected result  
At least header text should be shown by default. Ideally, columns could intelligently increase width to accommodate data cell contents to a certain extent.

### Attachments  
reproduction sample: https://github.com/jVanZwieten/mercury

**Comment by kdinev** [comment]
You should use the `onColumnInit` output to set the desired width of the column.

https://github.com/IgniteUI/igniteui-angular/blob/master/src/grid/README.md#outputs
