### ISSUE TITLE
Fix tests in Angular 9 Update

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#6166]
This [PR](https://github.com/IgniteUI/igniteui-angular/pull/6146) updates the product to Angular 9 and there are those failing tests:

Calendar and Date Picker:
- [ ] Multi-View Calendar - [ ] DatePicker/Calendar Integration Tests - [ ] Verify opening Multi View Calendar from datepicker
- [ ] Multi-View Calendar - [ ] DatePicker/Calendar Integration Tests - [ ] Verify setting hideOutsideDays and monthsViewNumber from datepicker
- [ ] IgxCalendar Rendered Component Calendar selection - [ ] outside of current month - [ ] 1
- [ ] Should be able to change month

IgxPaginator:
- [ ] should calculate correctly pages when custom select options are given
- [ ] should add perPage in the select options if not already there

Slider, Circular and Radial Bar:
- [ ] Should update value when we try to decrease it (without animation)
- [ ] Value should not exceed the max limit when operating with floating numbers
- [ ] The template should be applied correct
- [ ] Should update value when we try to decrease it (without animation)
- [ ] Value should not exceed the max limit when operating with floating numbers
- [ ] Value should remain to the max one if it exceeds.
- [ ] When setting min and max value for range slider,
- [ ] should change toast position to bottom, the rest should be undefined

**Comment by zdrawku** [comment]
Fixed and related to:
- https://github.com/IgniteUI/igniteui-angular/issues/6693
- https://github.com/IgniteUI/igniteui-angular/issues/6692
- https://github.com/IgniteUI/igniteui-angular/issues/6691
- https://github.com/IgniteUI/igniteui-angular/issues/6690
