### ISSUE TITLE
View week numbers in datepicker and calendar

### ISSUE THREAD

**Issue by PhilippRoessner** [IgniteUI/igniteui-angular#6172]
## Is your feature request related to a problem? Please describe.
Our customers need to see the week number when they pick any date in our software. The current igx controls datepicker and calendar have no option for that.

## Describe the solution you'd like
I'd like to have an option for activating week numbers in the datepicker and calendar controls. Something like [showWeekNumber]="true"

## Describe alternatives you've considered
-

## Additional context
-

**Comment by StefanIvanov** [comment]
here is the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxCalendar-Specification#view-week-numbers-in-calendar)
