### ISSUE TITLE
Grid initial sorting as input

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#6178]
## Is your feature request related to a problem? Please describe.
Most of the time, we bind our data through observables, so the data input of the grid could typically be `[data]="records | async"`. When applying an initial sorting on the grid, it seems that this must be done with the sort method. In order to do this, we would now have to subscribe to the observable, and sort there when new data is streamed. To add to this problem, it seem like the grid need some time to actually render. So doing something like this doesn't work:

`records$.subscribe(() => { setTimeout(() => { grid.sort(...) }) })`

This however does:

`records$.subscribe(() => { setTimeout(() => { grid.sort(...) }, 1000) })`

But it results in poor code.

## Describe the solution you'd like
An initialSorting input or similar, where we can define the sorting for the grid when it loads, eliminating the need for subscribe to an observable, or detectChanges if input.

## Describe alternatives you've considered
Currently do `records$.subscribe(() => { setTimeout(() => { grid.sort(...) }, 1000) })`. It works, but isn't very pretty.

**Comment by rkaraivanov** [comment]
@Eralmidia 

You can set initial sorting state by using the `sortingExpressions` input of the grid; [more info here](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#sortingexpressions). It is also a two way binding. In fact most of the data operations of the grid are exposed as a two way bind able inputs.
Here is a [sample](https://stackblitz.com/edit/angular-ms4qfj-eqq1lu) with initial sorting state and an observable data source

**Comment by Eralmidia** [comment]
Wow, I now see that was even mentioned in the docs. Totally missed that. Great work, thanks 👍
