### ISSUE TITLE
The getFeatureColumnsWidth function takes about 30% of the vertical scroll execution time

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#6182]
## Description  
Performance enhancement - we should try to cache the widths of templated feature columns so that we don't have to use getBoundingClientRect on every scroll. Additional sizing logic can be delegated to the resizeObserver.

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Run the igxGrid GroupBy Sample
2. Performance profile scrolling up and down with the scroll thumb
3. Check the time distribution of a single scroll execution

## Result  
About 1/3 of the execution is the ```getFeatureColumnsWidth``` func

## Expected result  
We should try to minimize the execution time of this function

**Comment by rkaraivanov** [comment]
@ChronosSF 
The cleanest way would be to move the whole left pinned side of the grid features (row selectors, expand/collapse toggles, etc.) into a separate virtual container and sync its scroll with the vertical scroll of the grid itself. Then just let the browser do its thing with sizing and growing/shrinking of the elements
 😐
