### ISSUE TITLE
Expanding a row and then scrolling to the bottom right and then returning to the row and collapsing it results in scrolled next row.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#6206]
## Description  
Expanding a row and then scrolling to the bottom right and then returning to the row and collapsing it results in scrolled next row.

 * igniteui-angular version: 9.0.x
 * browser: any

## Steps to reproduce  

1. Open Grid Master-Detail in the sample browser and add more columns.
2. Expand the first row.
3. Scroll to the bottom right edge of the grid.
4. Scroll back to the start of the grid.
5. Collapse the first row.

## Result  
The second row appear as if it scrolled to the far right.

## Expected result  
The second row should not appear as if it scrolled to the far right.

## Attachments  
![MasterDetailScrollCollapse](https://user-images.githubusercontent.com/3768136/69647005-6fb98700-1071-11ea-84f7-b3a45502fa2a.gif)

**Comment by MayaKirova** [comment]
Seems to be an issue with caching after updating to Angular 9 & Ivy. Reproduces in other features that utilize caching (like group by, summaries, hierarchical grid etc.). Not specific to master-detail.
