### ISSUE TITLE
Tooltip for grid cell text content

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#6215]
## Is your feature request related to a problem? Please describe.
If the width of a cell become to small for its content, ellipsis is provided. 
![image](https://user-images.githubusercontent.com/12936286/69723775-b8794a80-111a-11ea-991c-ed15784e5b14.png)
In those scenarios, it would be good to have the ability to automatically get a tooltip for the whole text value. 

## Describe the solution you'd like
A boolean input for turning auto tooltips on/off and optionally a delay input to control how fast it is shown.

## Describe alternatives you've considered
Templating all columns in order to do this manually, which is cumbersome if this is the only reason for the template.

**Comment by kdinev** [comment]
@Eralmidia We already added this for the column headers #5962. We will implement the same change for the cells.

**Comment by zdrawku** [comment]
@radomirchev, I saw that you marked the issue with "Discovery". As I remember the next batch of features is already planned for the upcoming milestone, and I guess this won't be part of it, for now.

**Comment by radomirchev** [comment]
@zdrawku the batch is still under discussion. I will update the roadmap and the relevant issues once we are ready with it.

**Comment by radomirchev** [comment]
@Eralmidia , @zdrawku the issue is included in the current milestone list.
