### ISSUE TITLE
How to clear the selection of a [IgxDropDownComponent]?

### ISSUE THREAD

**Issue by cornel-stoica-str** [IgniteUI/igniteui-angular#6218]
Hi,

What is the recommended way to clear the selection from an IgxDropDown component?

Example:
```
<igx-input-group class="input-group">
    <input type="text"
        [igxToggleAction]="myDropdown"
        [igxDropDownItemNavigation]="myDropdown"
        igxInput
        readonly= "true"
        placeholder="{{ myItemLookupValuePlaceholder }}"
        [value]="myDropdown.selectedItem?.value?.LookupValue"/>
             
    <igx-suffix *ngIf="getMyItemId" 
        igxButton="icon"
        igxRipple
        (click)="clearMyDropdown(); clearMySecondDropdown()">
        <igx-icon>delete_outline</igx-icon>
    </igx-suffix>
</igx-input-group>


<igx-drop-down #myDropdown (onSelection)="setMyItemId = $event.newSelection.value?.LookupId;">
    <igx-drop-down-item *ngFor="let myItem of filters?.ArrayOfFilters" [value]='myItem' [selected]="getMyItemId === myItem.LookupId">
        {{ myItem.LookupValue }}
    </igx-drop-down-item>
</igx-drop-down>
```

In the above code, what is the recommended way to clear the selection of "myDropdown" and "mySecondDropdown" (which is not present in the example for the sake of simplicity) when the user clicks on the igxButton?

Extra info:
 - "myItem" is an object that contains "LookupId" and "LookupValue".

 - "getMyItemId" and "setMyItemId" are function in the component that gets and sets the ID of the selected option.

 - The <input> element displays the selected value and opens the Dropdown on click (it will be used to filter in the future).

Thank you for your time.

**Comment by Lipata** [comment]
Hi, @cornel-stoica-str.

Thе `igx-drop-down` current design doesn't allow deselecting an item. I will mark this as a feature request and we will reconsider the need for such a functionality.
