### ISSUE TITLE
In Excel Style filter when filter values the filter is not applied

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6220]
## Description  
In Excel Style filter when filter values the filter is not applied

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridFiltering
2. Open ESF for column Employees
3. In the search type 5

## Result  
Values are not filtered

## Expected result  
Values should be filtered

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/69785325-73a7ef00-11c0-11ea-9bff-6d42cbfb1836.png)

**Comment by 3phase** [comment]
Closing this issue, as the provided solution is not merged and it's outdated since the fix of #6567 got merged.
