### ISSUE TITLE
[SLIDER] Control the pop up of the thumb label when approach the API

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#6222]
## Is your feature request related to a problem? Please describe.
I'm not able to control the thumb label visibility when updating the value through the API.
Also, expose an input through which you could set the always visible state of the thumb label. With this approach, we will be able to visualize the thumb when the slider is continuous as well.

## Describe the solution you'd like
1. Exposing an input that makes the label thumbs always visible.
2. Provide an API method that toggles the thumbs independently.

## Describe alternatives you've considered
There are no alternatives or workarounds for this.

**Comment by Aleksandyr** [comment]
@zdrawku @radomirchev Can we add that feature for the upcoming milestone?

**Comment by zdrawku** [comment]
@radomirchev do we have a board for `next milestone`? I spoke with @Aleksandyr and this FR is something that we can postpone for now.

**Comment by Aleksandyr** [comment]
After discussing this feature request. We have got to the conclusion that there is no need for such behaviour if you are using the API of the slider.

There are plenty of possibilities you can expose the value/labels of the slider like templates, etc.
