### ISSUE TITLE
When grid has horizontal scroll and press tab on a master detail the next row first cell is not selected

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6238]
## Description  
When grid has horizontal scroll and press tab on a master detail the next row first cell is not selected

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Edit dev sample gridMasterDetail and add 3 new columns
2. Open the sample
3. Expand first row
4. Go to the last cell in the first row
5. Press tab
6. Mater detail is selected. Press tab again.

## Result  
The first cell in the second row is not selected

## Expected result  
The first cell in second row should be selected

## Attachments  
![TabOnMD](https://user-images.githubusercontent.com/11463104/69874565-08474580-12c4-11ea-8443-6d165f2f0b22.gif)

**Comment by ChronosSF** [comment]
@rkaraivanov , @nrobakova , This is a side-effect of not handling the focus inside the details view. If we are to fix this we need to know which the last focusable element of the details view is, handle its blur and programmatically move the virtualization frame.

**Comment by ChronosSF** [comment]
If we can't come up with another solution, we'll close it as not to fix as the code that is required was rejected in the original PR.

**Comment by ChronosSF** [comment]
@rkaraivanov , please check the PR for this bug. Maya found another way to resolve it but we'd like your opinion on the fix as well.
