### ISSUE TITLE
FilteringExpressionsTreeChange event is fired after filtering is performed

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#6242]
## Description  
FilteringExpressionsTreeChange event is fired after filtering is performed, however this event is meant to be fired before setting the expressions. ALso, the event documentation is confusing:

![image](https://user-images.githubusercontent.com/14248932/69945301-f519bd00-14f1-11ea-8a07-209207324292.png)

 * igniteui-angular version: 8.2.10

## Expected result  
The event to be emitted before the expressions are changed, and provide the option to cancel setting new value to the expressions object.
Documentation to be corrected.

**Comment by DiyanDimitrov** [comment]
I agree the documentation is misleading and we should fix it. However the purpose of the event is to support two-way binding for the filteringExpressionsTree property and we shouldn't modify it to be cancelable. The proper way of canceling the local filtering is to use the NoopFilteringStrategy.
