### ISSUE TITLE
When a row is selected the highlighted text is not visible

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6249]
## Description  
When a row is selected the highlighted text is not visible

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridSearch
2. Select second row
3. In the search type text 'an'

Note: this is reproducible in the default theme, in dark theme the highlighted text is visible

## Result  
the highlighted text and selected row colors are same and cannot see highlighted text in the second row

## Expected result  
The highlighted text should be vissible

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/69959877-c2cb8800-1510-11ea-93bc-63525c4d8666.png)

**Comment by simeonoff** [comment]
We can fix this for the themes we ship, however, it will not be a universal fix since the user can still modify the selected row background color to match the highlight color.
