### ISSUE TITLE
Separate date and time editing functionalities from igxDatePicker and igxTimePicker into a new directive

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#6271]
- [x] Update [Date Editor Spec](https://github.com/IgniteUI/igniteui-angular/wiki/DateTime-Editor-Specification)
  - [x] Mask Refactoring #6454
  - [x] Update [Mask Editor Spec](https://github.com/IgniteUI/igniteui-angular/wiki/Mask-Directive-Specification)
  - [x]  Implementation & Unit tests
      - [x] I want to able display date/time values based on defined formats (display value and edit value; all defined masks, like shortDate/longDate & custom format)
           - [x] Implementation - move to date-editor.common - util functions and pipes.
           - [x] Unit tests - copy existing tests from date-picker/time-picker and create new.
      - [x] I want to able to spin date/time parts
           - [x] Implementation
           - [x] Unit tests - copy existing tests from time-picker and create new for date-picker.
      - [x] I want to edit date/time values in the editor
           - [x] Implementation 
           - [x] Unit tests
      - [x] I want to be able to set minValue & maxValue
           - [x] Implementation - releated issue #6286
           - [x] Unit tests
       - [x] I want to be able to use date-editor in Template Form and Reactive Form
           - [x] Implementation 
           - [x] Unit tests
       - [x] I want have customizable prompt chars
           - [x] Implementation 
           - [x] Unit tests
       - [x] I want have placeholder text
           - [x] Implementation 
           - [ ] Unit tests
       - [x] I want to complete partialy entered dates
            - [x] Implementation 
            - [x] Unit tests
       - [x] I want to clear any invalid input
            - [x] Implementation 
            - [x] Unit tests
       - [x] Other inputs, outputs & methods
            - [x] Implementation 
            - [x] Unit tests
 - [ ] Demos Dev
     - [x] Separate Demo for date editor
     - [ ] Update existing Reactive Form the demo and add date editor
     - [ ] Add demo for Template Driven Form with editor components
- [ ] Topic and Samples
     - [ ] Create new [topic](https://github.com/IgniteUI/igniteui-docfx/issues/1823) for date-editor
     - [ ] [Simple demo](https://github.com/IgniteUI/igniteui-angular-samples/issues/1840)
     - [ ] [Advanced demo](https://github.com/IgniteUI/igniteui-angular-samples/issues/1841)

## Is your feature request related to a problem? Please describe.
Right now there's a standalone Mask input, but no alternative for Date input. 
Functionality for this exists inside the Date Picker, however it's not exposed. Further, this leads to re-templated pickers being stuck with reduced functionality (see [Retemplated Dropdown Date Picker](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date_picker.html#templating-dropdown-mode-date-picker)) and isn't reusable by other components (e.g. Date Range)

Looking at https://github.com/angular/angular/issues/8203 we might want to look into supporting type "date" and "datetime-local"

## Describe the solution you'd like
Ideally a directive that can handle Date (perhaps and time) input (extending from `igxMask`) and Model binding (`ValueAccessor`), potentially supporting native date input types as well.

## Describe alternatives you've considered
See SO links below. Those don't look clean in API or always work well TBH.

## Additional context
Date input is especially painful, since dates usually require formatting which means a separation of value and display text and there's definitely room for improvement here as seen in multiple SO questions:
https://stackoverflow.com/questions/37055311/angular2-how-to-use-javascript-date-object-with-ngmodel-two-way-binding
https://stackoverflow.com/questions/38175251/angular-2-date-input-not-binding-to-date-value
All of those deal with trying to format the Date as string and somehow parse it back with varying success.

**Comment by Lipata** [comment]
Issue #6286 about min and max values are added to the specification. When confirmed as a component's functionality in the specification we can close #6286.
