### ISSUE TITLE
Calendar keyboard navigation accessibility

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#6275]
## Is your ~feature~ request related to a problem? Please describe.
Related to #6272, after looking at the descriptions for calendar in the [datepicker example](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html):
"calendar that uses the [grid pattern](https://www.w3.org/TR/wai-aria-practices/#grid)"
"as specified in the grid design pattern, only **one** button in the calendar grid is in the Tab sequence."

In other words, tab navigation through the calendar is supposed to allow you to jump through the prev/next buttons, the year/month pickers and the calendar grid itself. Right now the calendar handles the tab as it would cursor keys, which is super tedious.

## Describe the solution you'd like
The tab navigation of the calendar should allow you to jump through the separate groups and have a single tab stop for the actual calendar grid.

## Additional context
I realize this is a behavior change from the current implementation, but the way the spec describes the behavior seems very reasonable, so I'm logging this as an enhancement.

**Comment by damyanpetev** [comment]
Actually, I don't see that in the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxCalendar-Specification#keyboard-navigation).. Is this Tab behavior simply a side-effect of the date elements being focusable?

**Comment by hanastasov** [comment]
> Actually, I don't see that in the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxCalendar-Specification#keyboard-navigation).. Is this Tab behavior simply a side-effect of the date elements being focusable?

AFAIK, we just let the browser handle the tabs as it would. Never heard of any intent on how the calendar should do it. There are some tweaks though that skip a disabled/non-visible date when tabbing.

**Comment by zdrawku** [comment]
@radomirchev does "Next Milestone Draft" means that this issue is planned for the next milestone?

**Comment by radomirchev** [comment]
@zdrawku it is a draft, not a final version. It is under consideration to be included in the next milestone.
