### ISSUE TITLE
Resizing [IgxDrag]

### ISSUE THREAD

**Issue by cornel-stoica-str** [IgniteUI/igniteui-angular#6283]
## Question  
Is there a plan to add a resizing functionality to [IgxDrag]?

Thank you.

**Comment by kdinev** [comment]
Would this be like a resizable handle on a container?

**Comment by cornel-stoica-str** [comment]
Something like that.

Ex:

<div igxDrag>
    <igx-icon igxResizeHandle>drag_indicator</igx-icon>
</div>

The above <div> element would have a hande/icon on the top-left corner, the same way that igxDragHandle works.

Ther IgxDrag already contains information like the position on the screen in pixels.

**Comment by kdinev** [comment]
@cornel-stoica-str It would be a different directive like `igxResize` on top with an `[igxResizeHandle]="location"` as a content child.

**Comment by radomirchev** [comment]
@dkamburov the feature request is to be added for a review in sprint 20
