### ISSUE TITLE
Binding IgxGridComponent.filteringExpressionsTree throws all the errors 

### ISSUE THREAD

**Issue by jdpearce** [IgniteUI/igniteui-angular#6289]
## Description  

Binding a filter tree to the `filteringExpressionsTree` property of `IgxGridComponent` breaks it completely.

e.g.
```html
<igx-grid [filteringExpressionsTree]="filterTree" ...
```

```ts
ngOnInit() {
        const logic = new FilteringExpressionsTree(FilteringLogic.And, 'Id');
        logic.filteringOperands = [
          {
            condition: IgxNumberFilteringOperand.instance().condition(
              'greaterThan'
            ),
            fieldName: 'Id',
            searchVal: 3
          }
        ];
        this.filterTree = logic;
}
```

## Steps to reproduce  

See repro blitz (based on the boston marathon grid example) - https://angular-47t9ya.stackblitz.io

Alternatively (because stackblitz is terrible) there's a repro repo here : https://github.com/jdpearce/igx-grid-test

(NB - Attempting to set the filter programmatically causes the dreaded `ExpressionChangedAfterItHasBeenChecked` error, which suggests that something inside the Grid component lifecycle is being mishandled)

**Comment by DiyanDimitrov** [comment]
Currently in the [documentation ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html#initial-filtered-state) we recommend setting the filteringExpressionsTree in the ngAfterViewInit method and calling detectChanges after that.

I agree that it is a bit frustrating that you can't just bind it. We will investigate if this can be fixed.

**Comment by jdpearce** [comment]
Thanks for the reply. This is a fairly whiffy code smell though - there's no clear reason why the consumer should call `detectChanges` outside of the component. It is also a little frustrating that the intellisense help for `IgxGridComponent.filteringExpressionsTree` indicates that it _can_ be bound to : 

https://github.com/IgniteUI/igniteui-angular/blob/c7e03baddcc07d93add3d8ff5ba197d4dd298280/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L297-L300
