### ISSUE TITLE
Nav-drawer doesn't apply width if initial state is closed.

### ISSUE THREAD

**Issue by VladB93** [IgniteUI/igniteui-angular#6321]
## Description  
Describe the issue.

 * igniteui-angular version: 8.1
 * browser: any

## Steps to reproduce  

1. Create a nav-drawer
2. Set its width to 500px and its `isOpen` to false.
3. Set `isOpen` to `true` to open the drawer

## Result  
The width of the nav-drawer is not 500px.

## Expected result  
The width should be as set.

## Attachments  
https://stackblitz.com/edit/angular-etncmg?embed=1&file=src/app/navdrawer/navdrawer.component.html

**Comment by damyanpetev** [comment]
Just as FYI, the issue is only when opening though the `isOpen` input, rather than `open()/close()`.

**Comment by kdinev** [comment]
@VMihalkov You should open a PR against `10.0.x` as well.
