### ISSUE TITLE
Vertical scroll bar cannot move up after navigateTo method is called

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#6331]
## Description  
Vertical scroll bar cannot move up after navigateTo method is called.

 * igniteui-angular version: 8.2.12
 * browser: Chrome

## Steps to reproduce  

1. Run the attached sample
2. Click "go to bottom right" button
3. Scroll up

## Result  
IgxGrid does not scroll upward.

## Expected result  
IgxGrid scrolls upward.

## Note
The issue occurs when navigateTo method takes both `rowIndex` and `visibleColumnIndex`. If `navigateTo` method only takes `rowIndex`, this does not occur. Scroll works on IE11 or Firefox.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[igx-grid-navigateto.zip](https://github.com/IgniteUI/igniteui-angular/files/3948895/igx-grid-navigateto.zip)
![IgxGrid_navigateToIssue](https://user-images.githubusercontent.com/14340675/70599633-f30dd780-1c30-11ea-98dd-7e9b313d2430.gif)

**Comment by 3phase** [comment]
@ymita might you please tell me what's the Chrome version that you're using, because I'm not able to reproduce it with versions 78 and 79 of the browser.

**Comment by ymita** [comment]
@3phase Thank you for looking into this. I am using Chrome 79.0.3945.79 version. I asked other members here and they could not reproduce it. So there may be something wrong with my environment. I am closing this issue for now.
