### ISSUE TITLE
Column Moving using API

### ISSUE THREAD

**Issue by amitohale** [IgniteUI/igniteui-angular#6334]
## Ability to reorder columns using API
Current grid allow columns reordering via standard drag/drop mouse or touch gestures. It does not allow us to reorder based on saved preferences (somewhere.. say localstorage). 

Support must be added to set column position in a grid. 
1. `setColumnIndex(column: IgxColumnComponent, index: number)`: Set column position to index

**Comment by zdrawku** [comment]
Hey @amitohale, thank you for the feature suggestion, while we review the Feature Request and plan it for the upcoming sprints you may use [this temporary solution](https://stackblitz.com/edit/angular-reorder-grid-columns) that I've created for your convenience.

[The sample](https://stackblitz.com/edit/angular-reorder-grid-columns) demonstrates how to change the columns order based on column `field name` by using a [ComponentFactoryResolver](https://angular.io/api/core/ComponentFactoryResolver), which will help us to create new column instances and add them to the cleared `columnListlist`.

Code snippet:
```
changeColumnsOrder(): void {
      const newColumns = [];
      let newColumnsOrder = [];
      this.grid.columnList.forEach(col => newColumnsOrder.push(col.field));
      const factory = this.resolver.resolveComponentFactory(IgxColumnComponent);
      newColumnsOrder = this.asc ? newColumnsOrder.sort().reverse() : newColumnsOrder.sort();

      newColumnsOrder.forEach(colField => {
          const ref = factory.create(this.viewRef.injector);
          const col = this.grid.columnList.find(c => c.field === colField);
          Object.assign(ref.instance, col);
          ref.changeDetectorRef.detectChanges();
          newColumns.push(ref.instance);
      });

      this.grid.columnList.reset(newColumns);
      this.grid.columnList.notifyOnChanges();
    }
```
![Order](https://user-images.githubusercontent.com/11193764/71670752-9c03aa00-2d79-11ea-83af-ce79feba44fa.gif)

**Comment by amitohale** [comment]
Thanks @zdrawku, this works for me.

**Comment by zdrawku** [comment]
The feature-request is added to our Queue part of the Master Backlog, you will be updated accordingly for any change of the feature-request state.

**Comment by zdrawku** [comment]
As @hanastasov pointed out while we were discussing the FR, we can expose API method (column-based) that will change the column index and reset the columnist collection (similar to the moveColumn API implementation).

```ts
list.splice(toIndex, 0, ...list.splice(fromIndex, 1));
this.columnList.reset(list);
```

I am marking this FR for the next milestone
