### ISSUE TITLE
When cell has editor combo and scroll the grid the layout is broken

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6365]
## Description  
When cell has editor combo and scroll the grid the layout is broken

 * igniteui-angular version: 9.0
 * browser: Chrome

## Steps to reproduce  

1. Open https://www.infragistics.com//angularsite/components/grid/editing.html#grid-cell-editing-and-edit-templates
2. double click on a cell in column Available At
3. Expand combo
4. Scroll down the grid

## Result  
The grid has empty space and when scroll to the top not all rows are visible

## Expected result  
The grid should not have empty space

## Attachments  
![combo](https://user-images.githubusercontent.com/11463104/71098362-44324400-21ba-11ea-9996-bfcbfde1d223.gif)

**Comment by mddragnev** [comment]
The issue does not concern the product but the sample. Having custom templated igxCellEditor with no overlay settings cause the disparity between the grid outlet and the igxCellEditor outlet and afterwards there is a misalignment in the grid. There is a PR made to sample browsers project fixing the issue: https://github.com/IgniteUI/igniteui-angular-samples/pull/1673
