### ISSUE TITLE
How to disable selection for few rows based on any condition in multi selection of igx-grid ignite UI for angular?

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#6367]
Hello.
I have the same question as here:
https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/119601/how-to-disable-selection-for-few-rows-based-on-any-condition-in-multi-selection-of-igx-grid-ignite-ui-for-angular/530761

Your colleague’s decision was this:
https://stackblitz.com/edit/igx-grid-preselected-rows.

But that does not work. If you select everything, then the logic of work is lost.
![image](https://user-images.githubusercontent.com/31878467/71154257-27465100-224c-11ea-90f8-0160dc469b31.png)

**Comment by ViktorSlavov** [comment]
Hi @ivanovla ,
Thanks for the thorough explanation!

I think your desired behavior can be achieved by [templating the header checkbox](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html#header-template) and attaching a listener to the [`onRowSelectionChange`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#onrowselectionchange) event emitter:
On the emitter, filter the `newSelection`, removing all of the disabled IDs from it.
For the header, override the default header with a checkbox that does the following:
 - Handle the click event, stopping it's propagation (so it does not trigger the default header behavior)
 - Call the grid's selection API depending on the state - deselect all rows if `totalSelectable - totalSelected === 0` or select all selectable rows (`data - disabled`)
 - Handles it's view state depending on the selection state (checked state and indeterminate state)

For the rows that are not selectable, hide the selectors by providing a [conditional template](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html#row-template).

Here is a small [StackBlitz sample](https://stackblitz.com/edit/grid-row-selection-disabled?file=src/app/grid/grid-sample-selection-template-numbers/grid-sample-selection-template-numbers.component.html) with the proposed setup - when you have the time, give it a look and let us know if this works for your scenario.

**Comment by ivanovla** [comment]
@ViktorSlavov Yes, it work, but i had to update from version 8.1.0 to 8.2+. Since version 8.2.0, perfomance has decreased. I think this is ude to resize observer. How can i disabled this?
