### ISSUE TITLE
igx-select does not update FormControl.touched appropriately

### ISSUE THREAD

**Issue by jdpearce** [IgniteUI/igniteui-angular#6370]
## Description  

FormControl.touched should be updated with the blur event. i.e. when the control loses focus.

The igx-select control does not update the `touched` property.

This is a huge problem when designing forms which show errors _after_ a control has been touched.

It also seems that setting `updateOn: 'blur'` for an igx-select control means that it _never_ gets updated.

 * igniteui-angular version: 8.2.13

## Steps to reproduce  

See the repro repo here : https://github.com/jdpearce/igx-select-untouched

Possibly related to #4756 

![Kapture 2019-12-19 at 12 26 31](https://user-images.githubusercontent.com/439121/71173618-1c46ed00-225b-11ea-8e5a-b86a1bb11297.gif)

**Comment by Lipata** [comment]
@jdpearce thank you for reporting this! We are planning to work on #4756 and we will take into account the scenarios that you have described.
