### ISSUE TITLE
Error in build-aot: ERROR in Directive ɵch in igniteui-angular.d.ts has no selector, please add it!

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6386]
## Description  
When building the solution with `ng build --aot` I'm getting the error below:
```
ERROR in Directive ɵch in <project_path>/node_modules/igniteui-angular/igniteui-angular.d.ts has no selector, please add it!
```

 * igniteui-angular version: 9.0.0-beta.6
 * browser: n/a

## Steps to reproduce  

1. build the solution with the option --aot

## Result  
What is the actual result after following the steps to reproduce?
The error mentioned above

## Expected result  
What is the expected result after following the steps to reproduce?
No error

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
n/a

**Comment by zdrawku** [comment]
@mimurawil can you please confirm that the problem is related to **9.0.0-beta.6** version. The issue that you are describing is part of the previous **9.0.0-beta.5** version and should not be present in the latest **beta.6**. 

I've tried to reproduce our [Angular Samples project (vNext) branch](https://github.com/IgniteUI/igniteui-angular-samples/tree/vNext) and with a new project generated with the [Ignite UI CLI](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/cli-overview.html). Both times the projects were built without errors.

**Comment by mimurawil** [comment]
Hello @zdrawku,

Yes, the igniteui-angular is definitely **9.0.0-beta.6**

I just tried to create a brand new testing angular app:
```
ng new angular-test
cd angular-test
npm install --save igniteui-angular@9.0.0-beta.6
```

When I execute the command `ng build --aot` with this empty project, it will build with no errors.

But if I add the Igx module imports, and I add a simple grid in the template
```
<igx-grid #myGrid [data]="[]" width="100%" [autoGenerate]="false" [allowFiltering]="true">
  <igx-column field="fieldOne" [header]="'Field One'" [dataType]="'string'" [resizable]="true"
              [sortable]="true" [movable]="true" width="300px">
    <ng-template igxCell let-value>
      <span>{{ value }}</span>
    </ng-template>
  </igx-column>
</igx-grid>
```

Then the `ng build --aot` breaks with the messages:
```
ERROR in Directive ɵch in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts has no selector, please add it!
Directive ɵci in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts has no selector, please add it!
Can't resolve all parameters for ɵci in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts: (?).
Directive ɵcj in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts has no selector, please add it!
Can't resolve all parameters for ɵcj in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts: (?).
Cannot determine the module for class ɵch in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts! Add ɵch to the NgModule to fix it.
Cannot determine the module for class ɵci in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts! Add ɵci to the NgModule to fix it.
Cannot determine the module for class ɵcj in /Users/wmimura/Desktop/temp/angular-test/node_modules/igniteui-angular/igniteui-angular.d.ts! Add ɵcj to the NgModule to fix it.
```

The commands `ng build` and `ng serve` works with no errors though.
I created a temporary git repo at https://github.com/mimurawil/angular-temp-igx-bug of the temp angular project that reproduced the errors above.

**Comment by zdrawku** [comment]
I've managed to reproduce it, thank you @mimurawil for reporting this issue

**Comment by zdrawku** [comment]
@mimurawil this issue is caused by the Angular and Ignite UI for Angular versions mismatch. You should either use version 8.2.x of our product with this configuration or upgrade your project to use Angular 9
