### ISSUE TITLE
[Igx-grid] Add option for infinite scroll (remote call) on the grid

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6387]
## Is your feature request related to a problem? Please describe.
Even thought the paginator works pretty fine, I'd like some grids to have the experience of the "infinite scroll". In our application, the back end is responsible for populating the f/e grid, and some cases there are a lot of data, so we do make use of b/e pagination.

## Describe the solution you'd like
Instead of making use of the igx-paginator, I'd like an option to use the new feature "infinite scroll" to increase the UX in our application.

## Describe alternatives you've considered
We're currently using the igx-paginator in all applicable cases.

## Additional context
n/a

**Comment by zdrawku** [comment]
Hey @mimurawil, we do have a similar feature that handles remote data operations - [Remote Virtualization](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html#remote-virtualization). 

Based on my understanding `Infinite scrolling` should allow the grid to load rows from the server depending on what the scroll position is in the grid. The more the user scrolls down, the more rows get loaded? If this is the case, then the difference with `Remote Virtualization` would be that we do not add the new rows to the already loaded ones, instead, we replace the row content and in the DOM you always have these ~10 HTML rows (based on the Grid height).

I believe you will find the live sample interesting. `Note:` The `debounceTime` is set with demonstration purposes, you can increase or decrease it based on your needs.

**Comment by mimurawil** [comment]
Thanks @zdrawku! I haven't noticed that feature. I'll do some research about that.
