### ISSUE TITLE
How can i make my igx-header have multi lines 

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#6391]
## Question  
How can i make my header having multi lines and word breaks.

This is needed so that i can reduce the column width when the columns names are big with mutiple words.
With plenty of columns the grid looks pretty empty.
And currently i am using this grid to show financial data and people like to see lots of data in one screen without much scroll.
Please let me know how can i achieve this.

 * igniteui-angular version: 
 * browser:

**Comment by zdrawku** [comment]
Hey @amitmoondra, have you tried the header templating. For the word-wrapping you may consider using `white-space: pre-wrap` as for the new lines, you can use `block` elements like `<div>` or `<p>`:

Live demo - https://stackblitz.com/edit/angular-grid-header-template-multiline-example

Code snippet:
```
<ng-template #hMultiTemplate let-column>
    <div><b>Header text:</b> {{column.header}}</div>
    <div><b>Container 1</b></div>
    <div><b>Container 2</b></div>
</ng-template>
<ng-template #hLongTextTemplate let-column>
    <div style="white-space: pre-wrap;">
      <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
           sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
    </div>
</ng-template>
```

**Comment by amitmoondra** [comment]
thank you, this helped i did try using custom template for header.
