### ISSUE TITLE
Slider onValueChange behavior

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#6401]
## Description  
Our documentation [states ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxslidercomponent.html#onvaluechange)

> This event is emitted when user has stopped interacting the thumb and value is changed.

Now the event is triggered on each step change, not on Thumb release action.
https://stackblitz.com/edit/angular-slider-value-changed

**Comment by Aleksandyr** [comment]
@zdrawku We can expose another event ex: **onValueChanged** for that purpose. Because if we modify the current state of the event, we will introduce a breaking change.
