### ISSUE TITLE
Update schematics dependency to version 9

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#6410]
## Description  
The version of `"@angular-devkit/schematics"` used to build our schematics (ng add/update) is `"^7.2.1"`:
https://github.com/IgniteUI/igniteui-angular/blob/master/package.json#L71-L72

The dependency should be updated to validate schematics API against latest packages that ship with the ng cli.

 * igniteui-angular version: 9.0.x
 * browser: N/A

**Comment by Lipata** [comment]
The following [PR](https://github.com/IgniteUI/igniteui-angular/pull/6435) updates the package to ^9.0.0-rc.7. I will leave the issue open so that when the official angular version 9 is released, update the reference as well.
