### ISSUE TITLE
igx-grid doesn't show on IE11(both Win10 and Win7)

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#642]
### Description  
igx-grid doesn't show on IE11.

### Steps to reproduce  

1. Unzip and Run [igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/1746223/igx-grid-app.zip)
2. Open http://localhost:4200/ on IE11

### Result  
igx-grid doesn't show on IE11. And, the following errors are thrown in the browser console.

>ERROR TypeError: Unable to get property 'getElementsByTagName' of undefined or null reference
>ERROR TypeError: Unable to get property 'children' of undefined or null reference

Here is a screenshot.
![image](https://user-images.githubusercontent.com/15909409/36515007-c3710028-17ba-11e8-8702-616d86da40c6.png)

### Expected result  
igx-grid should show on IE11 without errors.

### Attachments  
[igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/1746223/igx-grid-app.zip)

**Comment by tkiryu** [comment]
It seems that the errors is thrown in igxForOf direcitive.
https://github.com/IgniteUI/igniteui-angular/blob/master/src/directives/for-of/for_of.directive.ts#L446

When I tried modifying the code as below, I was able to show igx-grid.
```
    protected getElement(viewref, nodeName) {
        if (!viewref.element.nativeElement.parentElement) {
            return null;
        }
        const elem = viewref.element.nativeElement.parentElement.getElementsByTagName(nodeName);
        return elem.length > 0 ? elem[0] : null;
    }
```

But another issues came up.
1) Grid header doesn't show, although the dom has been rendered.
2) Horizontal scroll doesn't work and the following error is thrown.

>ERROR TypeError: Unable to get property 'destroy' of undefined or null reference

Here is a screenshot.
![image](https://user-images.githubusercontent.com/15909409/36515607-92a46df6-17bd-11e8-89a6-a1af6112f618.png)

**Comment by kdinev** [comment]
Maybe a polyfill is missing?

**Comment by dkamburov** [comment]
Tried loading all the polyfills from igniteui-angular-samples and no luck. Still the same error.

**Comment by mpavlinov** [comment]
There are multiple issues here not related to missing polyfills. 
- A JavaScript error due to a missing "parentElement" API.
- Scrolls doesn't work
- Styling - header is not showing
