### ISSUE TITLE
IgxGrid pagination inconsistency

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6425]
## Description
Several inconsistencies regarding pagination of IgxGridComponent.

 * igniteui-angular version: 9.0.0.beta.6
 * browser: all

### Documentation
At https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/README.md the claim is that a ViewChild is available in `ngOnInit`.
This is not true, it is `undefined` at that time.
It is available in `ngAfterViewInit` instead.
### IgxGridComponent.state does not exist (anymore)
At the same page, it is suggested that the component has a `state` attribute.
In reality it has been renamed to `pagingState`.
### Changing pagingState.recordsPerPage has no effect
I'd like to set it to 26, however it has not effect.
The default behaviour prevails, i.e. the grid is rendered with a preset 15 records per page.

## Expected result
The documentation must be updated.
The attribute recordsPerPage must be settable.

## Attachments  
None

**Comment by kdinev** [comment]
@catull There's several items in this issue. I think the readme inconsistency is negligible, since we have official documentation guides and API docs on the website. As long as the doc on the website reflects the API accurately, I think we're OK. We will still update the readme, but with a lower priority. 

As far as the `recordsPerPage` input setter goes, I believe we should handle it as a product bug.

**Comment by catull** [comment]
Perhaps it would work if I was able to set the records per page figure in `ngOnInit`, as documented.

**Comment by kdinev** [comment]
@catull `perPage` can be two-way data bound, which means that you can bind it to a prop and set the prop in `OnInit`. Have you tried that?

https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#perpage

**Comment by catull** [comment]
Thanks @kdinev, that works.

Now if only I could get rid of the footer (where you can select how many records per page are rendered).

Also, I do not seem to able to get rid of the vertical scrollbar.

**Comment by kdinev** [comment]
Take a look at this for the custom paging template: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html#remote-paging-with-custom-template
