### ISSUE TITLE
Sort grid by formatter

### ISSUE THREAD

**Issue by RolandTa** [IgniteUI/igniteui-angular#6430]
## Is your feature request related to a problem? Please describe.
I'm having a custom formatter for a column in which additional data is appended. The sort operation however simply sorts by row[fieldName] instead of the adjusted value from the formatter.

## Describe the solution you'd like
Allow grid sorting based on the formatter value.

**Comment by zdrawku** [comment]
@RolandTa you can use define your own Custom Sort Strategy based on your custom criteria. I've created a [sample for you](https://stackblitz.com/edit/angular-custom-sorting-strategy-with-formatter) that is showing how to sort by the custom formatter.

**Comment by zdrawku** [comment]
If you have more questions, let me know
