### ISSUE TITLE
How to render RouterLink in IgxColumnComponent ?

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6431]
## Question
I'd like to be able to navigate from a grid column to another page.
This is the HTML template:
```html
    <igx-grid
      #grid1
      [data]="data | async"
      [autoGenerate]="false"
      [allowFiltering]="false"
      [height]="calcHeight"
      [paging]="false"
      [perPage]="26"
      [rowHeight]="25"
    >
      <igx-column [header]="'Canton'" [field]="'canton'" [filterable]="true">
        <ng-template>
          <a [routerLink]="['/search']" [queryParams]="{ canton: canton }"> {{ canton }} </a>
        </ng-template>
      </igx-column>
      <igx-column
        [header]="'Total'"
        [field]="'totalPublications'"
        [filterable]="true"
        [dataType]="'number'"
      ></igx-column>
      <igx-column [header]="'New'" [field]="'toDoNewRegistrations'" [filterable]="true" [dataType]="'number'">
        <ng-template>
          <a [routerLink]="['/search']" [queryParams]="{ canton: canton, publicationType: 'NewRegistration' }">
            {{ toDoNewRegistrations }}
          </a>
        </ng-template>
      </igx-column>
      <igx-column [header]="'Mutation'" [field]="'toDoMutations'" [filterable]="true" [dataType]="'number'">
        <ng-template>
          <a [routerLink]="['/search']" [queryParams]="{ canton: canton, publicationType: 'Mutation' }">
            {{ toDoMutations }}
          </a>
        </ng-template>
      </igx-column>
      <igx-column [header]="'Todo'" [field]="'totalToDo'" [filterable]="true" [dataType]="'number'"></igx-column>
    </igx-grid>
```
![image](https://user-images.githubusercontent.com/150055/72067622-7a5b7300-32e3-11ea-99bf-8c8bb0842160.png)

When I click the cell under `Canton` cell, I'd like to navigate to '/search?canton=AG'.
When I click the cell under `Mutations`, I'd like to navigate to '/search?canton=AG&publicationType=NewRegistration'.

 * igniteui-angular version: 9.0.0.beta.6
 * browser: all

The anchor tag is not rendered though.
I also tried w/o `ng-template`, it also did not get rendered.

I know there is a way to react on a click or double-click event and navigating via router in the component code.

I'd like to do it in HTML, if possible.
How would I do that ?

**Comment by catull** [comment]
I tried with this:

```html
     <igx-column [header]="'Canton'" [field]="'canton'" [filterable]="true">
        <ng-template #cellTemplate igxCell let-canton>
          <a [routerLink]="['/search']" [queryParams]="{ canton: canton }"> {{ canton }} </a>
        </ng-template>
      </igx-column>
      <igx-column [header]="'Total'" [field]="'totalPublications'" [filterable]="true" [dataType]="'number'">
      </igx-column>
      <igx-column [header]="'New'" [field]="'toDoNewRegistrations'" [filterable]="true" [dataType]="'number'">
        <ng-template #cellTemplate igxCell let-value let-canton>
          <a [routerLink]="['/search']" [queryParams]="{ canton: canton, publicationType: 'NewRegistration' }">
            {{ value }}
          </a>
        </ng-template>
      </igx-column>
      <igx-column [header]="'Mutation'" [field]="'toDoMutations'" [filterable]="true" [dataType]="'number'">
        <ng-template #cellTemplate igxCell let-value>
          <a [routerLink]="['/search']" [queryParams]="{ canton: canton, publicationType: 'Mutation' }">
            {{ value }}
          </a>
        </ng-template>
      </igx-column>
```
It works for single values (`Canton`), but not the others.

**Comment by catull** [comment]
This is a bug, IMHO.

Look at the `<a>` tags for `New` and `Mutation` column.

The values (`todoNewRegistrations` / `row.todoMutations`) are rendered in the <a> tags, but not in the `[queryParams]`.

**Comment by rkaraivanov** [comment]
@catull 

AFAIK we do not have `igxRow` as a public directive anywhere in the grid module. If you want to access the row data from the cell use the igxCell directive and bind explicitly to the `cell` template variable.
Check [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#columns-configuration) for binding in the context of the cell components.

I guess [this sample](https://stackblitz.com/edit/angular-19wrtp) should be close to what you are trying to achieve. If not can you reproduce your use case in Stackblitz

**Comment by catull** [comment]
@rkaraivanov Thanks, your trick works perfectly.
