### ISSUE TITLE
"Entry-point "igniteui-angular" has missing dependencies:  - jszip/dist/jszip" error when building w/ Angular 9 RC7

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-angular#6432]
### Description  
When you create a new project and try to build and run it, the following error is thrown in the console and no view is rendered in the browser: 

```bash
ERROR in The target entry-point "igniteui-angular" has missing dependencies:
  jszip/dist/jszip
```
Note: This is not reproduced in Angular 9 RC.7 but reproduces in RC.8

 * igniteui-angular version: 9.0.x
 * browser: N/A

### Steps to reproduce  

1. Install modules in the attached project
2. Run the project

### Result  
WARNING in Entry point 'igniteui-angular' contains deep imports into 'C:/New folder/IG Project/node_modules/jszip/dist/jszip'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

ERROR in The target entry-point "igniteui-angular" has missing dependencies:
 - jszip/dist/jszip

### Expected result  
The project builds and runs correctly.

### Sample
[IG Project.zip](https://github.com/IgniteUI/igniteui-angular/files/4040729/IG.Project.zip)

**Comment by ViktorSlavov** [comment]
This has been identified by the Angular team via the automated [ngcc integration tests](https://github.com/angular/ngcc-validation/tree/master/projects/igniteui-angular-ngcc).
There is an [open PR](https://github.com/angular/angular/pull/34695) that resolves the issue.
You can test the fix by downloading the [PR artifact](https://579375-24195339-gh.circle-artifacts.com/0/angular/compiler-cli-pr34695-d0201a1872.tgz).
In the unzipped [test project](https://github.com/IgniteUI/igniteui-angular/files/4040729/IG.Project.zip), copy the artifact and run:
```
npm i [pr-artifact.tgz]
npm i
npm run start
```
The project should start as expected.

We'll have to keep an eye on the PR and, once it's merged and a new version is tagged, update our version dependencies to _that_ package.

**Comment by ViktorSlavov** [comment]
This is resolved in Angular [`rc-10`](https://github.com/angular/angular/commit/a651fb98c54ea6673774f3abb352e72237025a5e).
Verified in this [CLI PR](https://github.com/IgniteUI/igniteui-cli/pull/646)
