### ISSUE TITLE
IE issue with toggling an autocomplete drop down when placeholder is present

### ISSUE THREAD

**Issue by katesky** [IgniteUI/igniteui-angular#6437]
## Description  
In a component that has both igxToggleAction and igxAutocomplete, when placeholder is present on the input - toggling is broken as in the toggle happens more than once and user is unable to open the drop down. 

 * igniteui-angular version:  ^8.2.2
 * browser: IE

## Steps to reproduce  

1. Step 1
Toggling via clicking the input box or the icon reproduces the issue

## Result  
Drop down is not opening via a click on the input box

## Expected result  
Drop down should open every time

## Attachments  
See my repo for the code examples:
https://github.com/katesky/ie-dropdown-toggle-autocomplete-issue

**Comment by wnvko** [comment]
Here is what happens in the sample:

1. `igxAutocomplete` directive listens the `input` event and opens the drop down in the event listener.
2. `igxToggleAction` directive listens to the `click` event and toggles the drop down in the event listener.

When you click the `input` in IE with `placeholder` the placeholder's text disappears. Probably this forces the IE to wrongly fire the `input` event. At this point `igxAutocomplete` tries to open the drop down. Then `igxToggleAction` receives the `click` event and toggles the drop down - as the drop down is already opening `igxToggleAction` closes it.

This is a known [bug](https://connect.microsoft.com/IE/feedback/details/885747/ie-11-fires-the-input-event-when-a-input-field-with-placeholder-is-focused) in IE discussed also [here](https://stackoverflow.com/questions/30066510/internet-explorer-10-and-11-remove-placeholder-text-when-the-input-is-focused).

I do not see how we can distinguish when real `input` event is fired, after user's input, and when fake one is fired when placeholder disappears in IE. I am marking this as not to fix as this is a bug in IE.
