### ISSUE TITLE
IgxGrid. Two igx-virtual-helper after update from version 8.1.0 to 8.2+

### ISSUE THREAD

**Issue by ivanovla** [IgniteUI/igniteui-angular#6443]
Hello, i noticed that the component igx-virtual-helper doubled after the update. Because of what, my interactive scroll stopped working. Only scroll with the wheel is working. I solved this problem by manipulating styles. Was this done for some reason?

![image](https://user-images.githubusercontent.com/31878467/72155354-01801800-33c4-11ea-8af7-1d8e649a3aa0.png)

**Comment by MayaKirova** [comment]
@ivanovla Yes. We have moved the vertical scrollbar in its own external container it is no longer rendered next to the main display container where the data is rendered. Currently it targets an external igxForOf that is positioned next to the body. That one is not used for anything other than a target for the main virtualization vertical scrollbar location and its elements are disabled and not used in any interactions.
This was done to prevent various sizing issues where the scrollbar might overlap the last header/footer/data cell (for details you can refer to https://github.com/IgniteUI/igniteui-angular/pull/3668).

As such the second scroll element should not affect the functionality in the grid (as it is disabled). This is applicable for both 8.1.x and 8.2.x latest versions. 

In case you have some custom logic that applies scrolling you can use the grid’s navigateTo API method as it will apply scrolling to the correct scrollbar.
