### ISSUE TITLE
Checkbox is not clickable on custom header

### ISSUE THREAD

**Issue by shaileshyadav24** [IgniteUI/igniteui-angular#6447]
### Description  
When header is custom created with checkbox, then it is not clickable. Hover effect can be see on checkbox, but when clicked, it is not updating or none event is emitted from it.

 * igniteui-angular version: 7.2.6

### Expected result  
State of checkbox should changed or atleast event should be emitted from it.

### Attachments  

![Screenshot (13)](https://user-images.githubusercontent.com/39512705/72235704-a59ed480-35f9-11ea-928e-96d76ef50e31.png)

![Screenshot (14)](https://user-images.githubusercontent.com/39512705/72235877-7fc5ff80-35fa-11ea-93c6-dae631126d07.png)

**Comment by hanastasov** [comment]
Issue is not reproducible in version 8.1.x. You can plan upgrading to 8.1.x or later version. According to [Ignite UI for Angular versioning, Maintenance and Support](https://github.com/IgniteUI/igniteui-angular/wiki/Ignite-UI-for-Angular-versioning), fix will not be introduced into 7.2.x version.
