### ISSUE TITLE
When change page and then collapse a row grid data disappears

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6448]
## Description  
When change page and then collapse a row grid data disappears

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGrid
2. In the first grid change page size to 5
3. Go to the second page
4. Expand row with id 5
5. Go to the 3rd page
6. Expand row with id 11 and scroll vertical
7. Return to page 2 and collapse row with id 5

## Result  
Grid is empty

## Expected result  
Grid row should be previewed

## Attachments  
 
![hgridPaging](https://user-images.githubusercontent.com/11463104/72238033-3f0fbb80-35e5-11ea-9664-ef320ce2101e.gif)

**Comment by MayaKirova** [comment]
@nrobakova I can't seem to be able to reproduce this in latest master. This may have already been fixed in another PR.

![steps](https://user-images.githubusercontent.com/10397980/73276955-2b25a580-41f2-11ea-9429-be21ce82ff2c.gif)

**Comment by nrobakova** [comment]
this issue is no longer reproducible.
