### ISSUE TITLE
IgxGridComponent.calcHeight not visible anymore

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6457]
## Description
In version 9.0.0.rc.6, this was accepted:
```html
    <igx-grid
      #grid
      [data]="dailyStats | async"
      [autoGenerate]="false"
      [height]="calcHeight"
      [paging]="false"
      [rowHeight]="25"
    >
     <!--
     COLUMNS
     -->
    </igx-grid>
```
Now I get a build error:

```log
ERROR in src/app/pages/home/statistics/statistics-daily.component.html:10:17 - error TS-992339: Property 'calcHeight' does not exist on type 'StatisticsDailyComponent'.

10       [height]="calcHeight"
                   ~~~~~~~~~~

  src/app/pages/home/statistics/statistics-daily.component.ts:9:16
    9   templateUrl: './statistics-daily.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component StatisticsDailyComponent.
```

 * igniteui-angular version: 9.0.0.rc.7 
 * browser: 

## Steps to reproduce  

1. Use version 9.0.0.rc.6
2. Create a component with `<igx-grid>`, set `[height]="calcHeight"`
3. `ng build --prod` should be successful
4. Upgrade with `ng update igniteui-angular --next`
5. Try to build

## Result  
Build error documented above.

## Expected result  
The build must be fixed.

## Attachments  
None

**Comment by hanastasov** [comment]
Error clearly states that such a property or getter calcHeight does not exist. Please make sure it exists or add a sample that demonstrates the issue.

**Comment by catull** [comment]
The same way [pagingState](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L2678) is accessible, so is [`calcHeight`](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L2686) in the same source file.

```typescript
    /**
     * @hidden
     */
    public pagingState;
    /**
     * @hidden
     */
    public calcWidth: number;
    /**
     * @hidden
     */
    public calcHeight = 0;
    /**
     * @hidden
     */
```
In my eyes, this is still a bug.
Mind you, this is in `master`.

**Comment by hanastasov** [comment]
`calcHeight` property should be available in the `statistics-daily.component.ts` file. Please provide the content of your `statistics-daily.component.ts` file if you are unsure about it.
