### ISSUE TITLE
Scroll is not previewed in the drop down and cannot see all the items

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6459]
## Description  
Scroll is not previewed in the drop down and cannot see all the items

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample dropDown
2. Click on button Toggle

Note: This is also reproducible in the grid filtering conditions

## Result  
List is previewed, but it dos not have scroll and the other items are not vissible

## Expected result  
List should have scroll

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/72262739-296bb780-3620-11ea-819e-eca0e46c4633.png)

**Comment by IvayloG** [comment]
@nrobakova  I have created a new issue based on your comment. 
https://github.com/IgniteUI/igniteui-angular/issues/6472
