### ISSUE TITLE
Change color of the treegrid indicator inside IgxTreeGridComponent

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6460]
## Question  
How do I apply CSS to change color of the treegrid indicator inside IgxTreeGridComponent?

Example I would like to change the color of the treegrid indicator to black #000

 * igniteui-angular version: 8.2.14
 * browser: Google Chrome 79.0.3945.117 (Official Build) (64-bit)

**Comment by hanastasov** [comment]
You need to create a new igx-grid-theme and use the $expand-icon-color and $expand-icon-hover-color to change he indicator color:

```
@import '~igniteui-angular/lib/core/styles/themes/index';

$custom-theme: igx-grid-theme(
  $expand-icon-color: #FFCD0F,
  $expand-icon-hover-color: #E0B710,
);

:host {
    ::ng-deep {
        @include igx-grid($custom-theme);  
    }
}
```
You can find more details and examples on styling in the [igxTreeGridComponent Styling](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree_grid.html#styling) topic.

**Comment by brookhutchinson** [comment]
That you for tour help. Worked as expected.
