### ISSUE TITLE
Grid freeze when clicking Button rapidly

### ISSUE THREAD

**Issue by CoderBN1** [IgniteUI/igniteui-angular#6461]
### Description  
I'm using a hierarchical grid with a header. In this header is a selfmade component with two buttons (forward, previouse) and a DatePicker Component, so i can switch to tomorrow and yesterday. 
After updating to the new v. 8.2.14 the grid freeze if rapidly clicking one of the buttons. When i downgrade to v. 8.1.21 all is working fine

 * igniteui-angular version: 8.2.14
 * browser: tested with firefox and chrome latest versions

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
//datepicker.component.ts

import {Component, forwardRef} from '@angular/core';
import {ControlValueAccessor, NG_VALUE_ACCESSOR} from '@angular/forms';

@Component({
    selector: 'sample-datepicker',
    templateUrl: './datepicker.component.html',
    styleUrls: ['./datepicker.component.scss'],
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => DatepickerComponent),
            multi: true
        }
    ]
})
export class DatepickerComponent implements ControlValueAccessor {
    private _selectedItem: Date = new Date(Date.now());

    constructor() {
    }

    public onChange: (_: any) => void = (_: any) => {
    };

    public onTouched: () => void = () => {
    };

    // inner API
    public get value(): Date {
        return this._selectedItem;
    }

    public set value(newValue: Date) {
        if (newValue !== this._selectedItem) {
            this._selectedItem = newValue;
            this.onChange(this._selectedItem);
        }
    }
    // outer API

    public updateChanges() {
        this.onChange(this._selectedItem);
    }

    public writeValue(value: any): void {
        if (value) {
            this._selectedItem = value;
            this.updateChanges();
        }
    }
    public registerOnChange(fn: any): void {
        this.onChange = fn;
    }

    public registerOnTouched(fn: any): void {
        this.onTouched = fn;
    }
    public changeDate(changeBy: number): void {
        const modified = new Date(this._selectedItem);
        modified.setDate(this._selectedItem.getDate() + changeBy);

        this.writeValue(modified);
    }
}

//datepicker.component.html
<button igxButton="icon" (click)="changeDate(-1)">
    <igx-icon>chevron_left</igx-icon>
</button>
<igx-date-picker [(ngModel)]="value"
                 [cancelButtonLabel]="'standard.cancel' | translate"
                 [todayButtonLabel]="'datePicker.today' | translate"
                 mode="dialog"></igx-date-picker>
<button igxButton="icon" (click)="changeDate(1)">
    <igx-icon>chevron_right</igx-icon>
</button>

//grid.component.html

<div class="hgridWrapper">
    <igx-hierarchical-grid
        #hGridTour
        [data]="tourCompositeData"
        [primaryKey]="'tourNr'"
        [autoGenerate]="false"
        [allowFiltering]="true"
        [paging]="true"
        [showToolbar]="true"
        [isLoading]="_isLoading"
    >
        <div class="datePickerHeader">
            <ng-template igxToolbarCustomContent>
                <equicon-datepicker [(ngModel)]="date" (ngModelChange)="dateHasChanged()">
                </equicon-datepicker>
            </ng-template>
        </div>
        <igx-column
          ....
        >
...
        </igx-column>
...
</igx-hierarchical-grid>

//grid.component.ts

...
 public dateHasChanged() {
        this._log.info(this.date);
        if (!this._isInit) {
            this._loadTours().subscribe(
                response => (this.tourCompositeData = response)
            );
            this._router.navigate(['app/tours']);
        }
    }
...

**Comment by MayaKirova** [comment]
@CoderBN1 How does the clicking of the buttons affect the grid? Does it change the grid’s data or does it do something else? If possible could you also share your grid definition?

**Comment by ChronosSF** [comment]
@CoderBN1 , please let us know if you still need help with the issue.

**Comment by CoderBN1** [comment]
I'm sorry for my late answer, i still have this error in my develop environment but not in production.

I think it had something to do with the cdr.detectchanges() becouse im not using it how the docs describing. Is it realy necessary to do a detectchanges() if the data changes? 
So i'm not using a  ViewChild at all... May that couses the grid to freeze? 

There is another bug: 
When i open a child and changes the complete data property which is bound to the [data] attribute in the grid, then the parents will refresh the data but the child is showing the same data. If i then collapse all and open the child the data is refreshed...

**Comment by MayaKirova** [comment]
@CoderBN1 It is not necessary to manually call detectChanges if you change the full data input. Assuming that on click you change the full data then the grid will automatically reflect the changes. You can refer to the following simplified sample, where on click the data is changed:
https://stackblitz.com/edit/angular-tmqgef
I was not able to “freeze” the grid using the sample. Let me know if there are particular steps needed to replicate your issue or if the sample is not an accurate representation of what you are doing on click please feel free to share a sample of your own.

I have logged your issue with the child data not changing separately as it does not appear to be related to your original question. You can refer to it here: https://github.com/IgniteUI/igniteui-angular/issues/6535
