### ISSUE TITLE
Change fonts used in IgxTreeGridComponent Header text

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6469]
## Question  
How do I change Font-Size, Font-Color.and Font-Style of header text above IgxTreeGridComponent?

 * igniteui-angular version: 8.2.15
 * browser: Google Chrome

**Comment by zdrawku** [comment]
[This suggestion](https://github.com/IgniteUI/igniteui-angular/issues/6470#issuecomment-576291855) applies for the TreeGrid as well
