### ISSUE TITLE
igx-date-picker and igx-time-picker doesn't handle required properly

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#6471]
## Description  
The HTML validation doesn't pass through the igx-date and time pickers properly. Required doesn't put asterisk in the label, no red borders when touched and invalid, etc.

 * igniteui-angular version: 8.2.14
 * browser: all

## Steps to reproduce  

1. Create a date picker and mark it required.
```html
<igx-date-picker label="Start Date"
                 name="startDate"
                 required
                 [(ngModel)]="tournament.StartDate">
</igx-date-picker>
```

## Result  
No visual indication in the component that it's required in the form.

## Expected result  
To behave like other form components.

**Comment by Lipata** [comment]
Added to the igxDateTimeEditor [specification](https://github.com/IgniteUI/igniteui-angular/wiki/DateTime-Editor-Specification).
