### ISSUE TITLE
IgxDatePicker refactoring

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#6483]
Dependant on #6271

Related to #7199

[Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Date-Picker-Specification)

With the new `IgxDateTimeEditorDirective` implemented, we should refactor the `IgxDatePicker` to use the new editor to handle mask parsing, spinning, date validation and any other action related to the date picker's input.

Tasks during refactoring:
- Inheritance of new base parent - introducing new members, renaming old ones (1 day) 
*  Integration of `IgxDateTimeEditorDirective`  (10 days)
     - Code clean up for already existing functionality in the `IgxDatePickerComponent`
     - Refactoring of model binding
     - Move `CalendarContainer` to global date directory
- Have `IgxDateRangePickerComponent` extend `PickersBaseDirective` (2 days)

-  Refactoring of `DatePickerUtils` - will be renamed to `DateTimeUtils` (4 days)
     - Unit tests for `DateTimeUtils`'s public methods
*  Simplify templating #8665
- New features that will be implemented
    - min and max values (will come from igxDateTimeEditor) #6286 
    - add type property #7196 
    - add ARIA (2 days) #6346
    - implementation of Validator interface (1 day)

* Test refactoring (2 days)
* Bugs that must be resolved (1 day) - #8551, #8567, #8475, #8065, #6749, #6925, #5525, #8613, #8913, #8919, #9154, #9189, #9215
* Migrations for `IgxDatePickerComponent` (2 days)
* Updating of `IgxDatePickerComponent`'s documentation and samples

Current estimations are purely for development time.

**Comment by radomirchev** [comment]
Closes #6286
