### ISSUE TITLE
Injecting a Service into a Custom Summary class question.

### ISSUE THREAD

**Issue by cornel-stoica-str** [IgniteUI/igniteui-angular#6484]
## Question  
Hi,

I am trying to inject a Service into a Custom Summary class that extends an `IgxNumberSummaryOperand` class. We need some user specific data from the server to be able to customise the Summaries to customer's needs.

For some reason, the Service data is not visible at all in that class? Am I missing something?

Example:

```
import { TestCustomSummary } from '../pathToSummary/test-custom-summary';

export class MyComponent {
    ...

    testSummary = TestCustomSummary;

    ...
}
```

```
<igx-grid #myGrid [data]="myData">
        <igx-column *ngFor="let column of columns"
                    field="{{ column.property }}"
                    header="{{ column.header }}"
                    [hasSummary]="true"
                    [summaries]="testSummary"
                    dataType="string" // or number
        >
        </igx-column>
</igx-grid>
```

```
export class TestCustomSummary extends IgxNumberSummaryOperand {
    ...
    
    constructor( public testService: TestService ) {
        super();
        // The below console.log is empty. Same behaviour is observed inside an ngOnInit or ngAfterViewInit functions
        console.log(this.testService);
    }

    ...
}
```

Any help or redirection will be of great value.

Thank you very much for your time.

**Comment by ddincheva** [comment]
Hello @cornel-stoica-str ,
I managed to build a small sample that use some simple SummaryService inside a custom Summry class. The custom summary is applied to the column Units In Stock, you can enable summaries for this column with ![image](https://user-images.githubusercontent.com/34240583/72595667-03d9f900-3913-11ea-8334-56df9d35dbc8.png) button.
 Can you please check the [example](https://stackblitz.com/edit/angular-q3cgev) and see if this will be helpful for you and your use case scenario. If you have any additional question, we will be happy to answer.

**Comment by cornel-stoica-str** [comment]
Hi @ddincheva  ,

Thank you for your help. I understand now that this is not an IgniteUi issue / question and that I still have things to learn about Angular.

Thank you once more for your time.
