### ISSUE TITLE
Is there a way to add tooltip  to column summary.

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#6505]
## Question  
I need to add tooltip description to a column summary (bottom summary)and tooltip to  value for each summary, as sometimes if the columns are too narrow the summary values get cut.
Please let me know if there any way to do this right now 
in Igx-grid

 * igniteui-angular version: 8.2.12
 * browser: Chrome

**Comment by zdrawku** [comment]
Currently, there is no way to do so. I am marking this with a feature-request label, we can think of a way to expose a property that will enable tooltips of the item values when needed, instead of ellipsis text-overflow.

**Comment by zdrawku** [comment]
@radomirchev, it appears we've changed the status of this item in January. I guess we can plan this again, as the actual work won't be that much. @StefanIvanov what do you think for the proposed solution from a Design perspective?

**Comment by StefanIvanov** [comment]
This looks to me more like an application scenario that @amitmoondra could achieve by detecting hover over summary cells and use a cell as igxTooltipTarget to show an igxTooltip

**Comment by radomirchev** [comment]
@amitmoondra , the feature request is in the list for the current milestone. You could follow the milestone progress on the [Roadmap board](https://github.com/orgs/IgniteUI/projects/122) or in the [Roadmap file]9https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md)
