### ISSUE TITLE
How to move position of column filter icon to right of column header when column dataType is number

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6515]
## Question  
A column filter triangle icon displays inside the header of a column that is defined to be [filterable]="true".  I would like to change the position of the column filter triangle icon inside the column header.

By default the "filter" triangle icon is positioned to the left of the header if the column is defined with a [dataType]="'number'"

By default the "filter" triangle icon is positioned to the right of the header if the column is defined with a [dataType]="'string'"

**If the dataType of a column is defined to be "'number'", How do I move the position of the column filter triangle icon inside of the column header?**

 * igniteui-angular version: 8.2.15
 * browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by zdrawku** [comment]
You can use `igxHeader` template in order to [achieve this functionality (sample)](https://stackblitz.com/edit/angular-custom-filter-icons-and-positioning). Keep in mind that an appropriate icon class name and icon click handler should be set:

```

<ng-template igxHeader let-col>
    <div class="text">{{col.field}}</div>
    <igx-icon [ngClass]="filterIconClassName(col)" (click)="toggleFilteringDialog(col)">filter_list</igx-icon>
</ng-template>

...
public toggleFilteringDialog(column: IgxColumnComponent) {
  let headerCell = column.headerCell;
  headerCell.onFilteringIconClick({ stopPropagation: () => { }, preventDefault: () => { } });
}

public filterIconClassName(column: IgxColumnComponent) {
   return column.filteringExpressionsTree ? 'igx-excel-filter__icon--filtered' : 'igx-excel-filter__icon';
}
```

**Comment by brookhutchinson** [comment]
Can you please provide an example of how to not show a tooltip on a column?

I tried to click on the example links provided above and I did not see a "title" attribute being set to an empty string for a column in the grid.  Help me understand what I am missing.
