### ISSUE TITLE
Carousel's slides are not visible

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#6518]
## Description  
The slides of `IgxCarousel` are not visible with default configuration. This does not reproduce in version 8.2.16.

 * igniteui-angular version: 9.0.0-beta.3
 * browser: all

## Steps to reproduce  

1. Add `IgxCarousel` to a new Angular application.
2. Add several slides
3. Run the application

## Result  
Only `forward` and `backward` arrows of carousel are visible.

## Expected result  
By default, with no additional setup, the slides should be visible as in previous versions.

## Attachments  
[Carousel 9.0.0-beta.3](https://stackblitz.com/edit/carousel-9x?file=src%2Fapp%2Fcarousel-sample-1%2Fcarousel-sample-1.component.html)
[Carousel 8.2.16](https://stackblitz.com/edit/carousel-8x?file=src%2Fapp%2Fcarousel-sample-1%2Fcarousel-sample-1.component.html)

** Note
If I add to `style.scc` this style:
```
html,
body {
    height: 100%;
    overflow: hidden;
}
```
the slides appear. However resizing of the page works different compared to version 8

**Comment by kdinev** [comment]
@wnvko Define "resizing the page works differently". How did it work previously and how does it work now?

**Comment by wnvko** [comment]
In version 8 the image in the slide retained its aspect ratio when screen was resized. Additionally `igxCarousel` was filling the entire width of its parent element. Run the [version 8 sample](https://stackblitz.com/edit/carousel-8x?file=src%2Fapp%2Fcarousel-sample-1%2Fcarousel-sample-1.component.html) and resize the view to see how it was working.

**Comment by kdinev** [comment]
@wnvko I'm trying with the fix and the aspect ratio is no longer preserved, so the fix doesn't actually fix the issue.

**Comment by wnvko** [comment]
@kdinev as per `IgxCarousel's` [specification](https://github.com/IgniteUI/igniteui-angular/wiki/Carousel-Specification#developer) the carousel should be visible without specifying `height`. The issue is that it is not visible in version 9 without setting its `height`. Now this is fixed.
From other point of view the behavior is still not the same as in version 8. Looking again in the specification nothing is said about what should happen to images' aspect ratio. I believe this is something UI/UX team should resolve.
