### ISSUE TITLE
Input Group consistent focus 

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#6531]
## Is your feature request related to a problem? Please describe.
As the Input Group combines a bunch of separate elements, the actual `<input>` only takes up a portion of the space and thus clicking outside - on the suffix/prefix/label - causes the browser to blur the input by default.
Currently, the Input Group handles a click event to ensure focus is restored to the input so interaction with the built-in elements doesn't disrupt, but that looks a bit weird:
![suffix-click](https://user-images.githubusercontent.com/3198469/73003961-26867900-3e0f-11ea-89c4-f550f6d70792.gif)

![label-click](https://user-images.githubusercontent.com/3198469/73003952-238b8880-3e0f-11ea-8070-124dbf773b38.gif)
Naturally that also means `focus` and `blur` events are re-triggered constantly on the input itself, which can be a bit annoying for users that try to handle those and also affects the integration with `FormControl` as it may cause a value to be updated sooner than expected (came up from #6370)

## Describe the solution you'd like
Looking at the material design spec https://material.io/components/text-fields/ - there's no mention of this, but the reference Web components behave as a single unit (focus doesn't shift around). It seems very reasonable to do that.

More demos of those: https://material-components.github.io/material-components-web-catalog/#/component/text-field

## Additional context
The current click handle can `preventDefault` on pointer down to make sure the focus remains in the input. The material reference components also use a clever trick with the input padding to make it span over other elements to prevent the focus, though I'm not sure this is feasible with our group (diff structure, we use ripples on some icons).
This will affect the Grid's filtering that uses the focus shift to it's befit https://github.com/IgniteUI/igniteui-angular/issues/542 and the existing `supressInputAutofocus` API that was introduced for it. Manual focus will likely be required.

**Comment by simeonoff** [comment]
@damyanpetev Agree. We won't be able to take advantage of the material trick with the padding, due to the way our template is structured.
