### ISSUE TITLE
Define a column as USD currency (sortable)

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6542]
## Question  
How do I define a column as a number formatted as USD currency and allow a user to sort the column in ascending order or descending order?

 * igniteui-angular version: 8.2.15
 * browser: Google Chrome

**Comment by kdinev** [comment]
@brookhutchinson The easiest way I see is to define a column template where you apply the angular currency pipe to the column values. Sorting would just work on the pre-piped values collection, so it would ignore the formatting that is applied.

https://angular.io/api/common/CurrencyPipe
