### ISSUE TITLE
Allow templating of IgxCarousel's indicators container

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#6545]
## Is your feature request related to a problem? Please describe.
I have an `IgxCarousel` with let say 20 slides and I need to show templated indicators. However I need to show 10 indicators instead of all 20.

## Describe the solution you'd like
Indicators container should be templatable.

**Comment by zdrawku** [comment]
Version 9.0.0 includes custom indicators
API docs for [indocatorTemplate](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcarouselcomponent.html#indicatortemplate)
[Official documentation with example](https://www.infragistics.com/products/ignite-ui-angular/angular/components/carousel.html#custom-indicators)
