### ISSUE TITLE
Error thrown when add id to IgxSelect

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#6546]
## Description  
`IgxSelect` throws Cannot set property 'id' of undefined TypeError when select has `id` in the markup. This is not reproducible in 8.2.

 * igniteui-angular version: 9.0.0-beta.3
 * browser: all

## Steps to reproduce  

1. Add `IgxSelect` to the page.
2. Set `id` to some value.
3. Run your application

## Result  
Cannot set property 'id' of undefined TypeError is thrown

## Expected result  
Application should run with no errors

**Comment by rkaraivanov** [comment]
Not reproducible with the latest beta package. See [here](https://stackblitz.com/edit/angular-4hwek8)

**Comment by wnvko** [comment]
You can reproduce this with Angular 9.0.0-rc.10 and 9.0.0-rc.11

**Comment by ViktorSlavov** [comment]
Should be related to https://github.com/angular/angular/issues/34992
