### ISSUE TITLE
Provide "Unfreeze All" option under Freeze button on Data Grid & Tree Grid

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#6549]
## Is your feature request related to a problem? Please describe.
User is requesting to provide "Unfreeze All" option under Freeze button on Data Grid & Tree Grid. 

## Describe the solution you'd like
User is requesting to provide "Unfreeze All" option under Freeze button on Data Grid & Tree Grid.  it is similar to "Show All" & "Hide All" button provided on Hide Button on both grids.

**Comment by radomirchev** [comment]
@deepakvia, the feature request is in the list for the current milestone. You could follow the milestone progress on the [Roadmap board](https://github.com/orgs/IgniteUI/projects/122) or in the [Roadmap file](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md).
