### ISSUE TITLE
Provide option on Tree Grid to "Expand All" and "Collapse All" 

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#6550]
## Is your feature request related to a problem? Please describe.
for large data set in tree grid data is shown in hierarchical order as parent child relationship. It takes lot of time to collapse parent nodes.  

## Describe the solution you'd like
for large data set in tree grid data is shown in hierarchical order as parent child relationship. It takes lot of time to collapse parent nodes. There should be option for "Expand All" and "Collapse All". So in one click user can collapse or expand all records.

**Comment by zdrawku** [comment]
This is achievable by using the public api of the grid - [expandAll()](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtreegridcomponent.html#expandall) and [collapseAll()](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtreegridcomponent.html#collapseall). Check out [this sample ](https://stackblitz.com/edit/angular-expand-collapse-all)for a reference.

Code snippet:
```
<igx-tree-grid #treeGrid [data]="data" [allowFiltering]="true"
        [showToolbar]="true"
        primaryKey="ID" foreignKey="ParentID" width="100%" height="400px"
        [rowSelectable]="true">
        <ng-template igxToolbarCustomContent let-treeGrid="treeGrid">
            <button igxButton="flat" igxRipple igxRippleCentered="true" (click)="toggleAllRows()">
        <igx-icon *ngIf="expanded" fontSet="material">expand_more</igx-icon>
        <igx-icon *ngIf="!expanded" fontSet="material">expand_less</igx-icon>
              Expand/collapse all
            </button>
        </ng-template>
```
