### ISSUE TITLE
Show total number of records on data grid & tree grid

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#6551]
## Is your feature request related to a problem? Please describe.
User wants to see total number of records on data grid & tree grid

## Describe the solution you'd like
User wants to see total number of records on data grid & tree grid. How this is possible? please add this feature on control.

**Comment by zdrawku** [comment]
@deepakvia we have a feature that already handles this kind of requirements - igxSummary. It also provides you with the ability to create custom summary items that can show variety of information based on Grid's data count and type (different from the default Summaries). 

In fact, we have a sample that demonstrates how to show exactly [the total count of Grid records](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries.html#custom-summaries-which-access-all-grid-data)
