### ISSUE TITLE
How to align igx-input-group onto same row ?

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6564]
## Question
I have a form with 10 input fields.
The natural layout is that each input field is rendered on an individual row.
This is quite wasteful, as for instance the Street name and number can be rendered next to each other.
Or the ZIP code and town.

I have tried `igxLayout igxLayoutDir="row" igxLayoutWrap="wrap"` w/ and w/o igxFlex on the.
I also wrapped each `<igx-input-group>` into `<div>` and different `igxFlexGrow`.
The best I got is to have an `<igx-input-group to>` only take up 50% of a row.

Have not found an example yet that shows how to render several on a row.
By the way, if it matters, these input fields are all in a Igx Card content.

I have cases of 2, 3, 4 and 6 fields to be shown horizontally rather than vertically.

 * igniteui-angular version: 9.0.0-rc.0
 * browser: Chrome 79.0.3945.79, Firefox 72.0.1
 * os: Linux Mint 19.3

Sample markup:

```xml
    <igx-card>
      <igx-card-header>
        <h4 igxCardHeaderSubtitle>Company</h4>
      </igx-card-header>

      <igx-card-content igxLayout igxLayoutDir="row" igxLayoutWrap="wrap">
        <div class="wrap-row" igxFlex igxFlexGrow="0">
          <igx-input-group>
            <input igxInput name="pubEditCompanyNameMain" type="text" />
            <label igxLabel for="pubEditCompanyNameMain">Name</label>
          </igx-input-group>
        </div>

        <div class="wrap-row" igxFlex igxFlexGrow="0">
          <igx-input-group>
            <input igxInput name="pubEditLegalForm" type="text" />
            <label igxLabel for="pubEditLegalForm">Legal form</label>
          </igx-input-group>
        </div>
```
The class `wrap-row` is
```css
.wrap-row {
  width: 50%;
}
```

Progress screen shot:

![image](https://user-images.githubusercontent.com/150055/73335838-b8a7da80-4270-11ea-9d8d-52f334659157.png)

**Comment by rkaraivanov** [comment]
@catull 

The `igxFlex` and `igxLayout` directives follow the how the flex layout works in the browser. There's nothing more to it and nothing special about both the card and input group components. 
It's a matter of laying the appropriate markup.

Maybe something like [this](https://stackblitz.com/edit/angular-ncrq9o) can help point you in the right direction.
