### ISSUE TITLE
Key + scroll for horizontal scroll in igx-grid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#6566]
## Is your feature request related to a problem? Please describe.
It would be nice to enable the user to use the scroll wheel to scroll horizontally as well (for mouse with only 1 scroll wheel). 

## Describe the solution you'd like
When holding down for instance the shift key, the grid scrolls horizontally instead of vertically.

**Comment by zdrawku** [comment]
@Eralmidia, this functionality is now part of the latest [alpha.6](https://github.com/IgniteUI/igniteui-angular/releases/tag/11.1.0-alpha.6) and will be officially released with the 11.1.0 release later this month 🎉
