### ISSUE TITLE
Excel style search filter pipe is not working properly with Ivy

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#6567]
## Description  
Searching in excell style filtering dialog does not work properly. 
Probably because change detection.

 * igniteui-angular version: 9.0.x
 * browser: n/a

## Steps to reproduce  

1. Open grid external filtering dev sample
2. Choose column Employees
3. In the search input below type 18

## Result  
Observe that results containing just 1 are displayed too.
If you make any additional interaction with the page, the expected result is shown.

## Expected result  
The result should be just 18.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by DiyanDimitrov** [comment]
The issue is caused by the fix of #4018. We have discussed it with @DaniMarinov and we agreed to revert the fix of #4108.
