### ISSUE TITLE
Cell selection style is not cleared when another cell is clicked on Safari.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#6569]
## Description  
Cell selection style is not cleared when another cell is selected on Safari. 
Does not happen in Chrome on iOS.

 * igniteui-angular version: 8.2.x
 * browser: Safari

## Steps to reproduce  

1. Run the following sample on Safari: https://stackblitz.com/angular/bxgjbloolmr
2. Click on a few cells.

## Result  
All cells remain selected.

## Expected result  
Only the last clicked cell should be selected. 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by zdrawku** [comment]
@MayaKirova, which is the Safari version? Also is that for the Windows Safari Application (v5.1.7) or Apple's (v13.1.0)?

**Comment by MayaKirova** [comment]
@zdrawku It was tested on Mac iOS and it reproduced on Safari but not on Chrome. Safari version may have changed since it was logged a while ago. I would suggest testing it on latest Safari version on Mac.

**Comment by zdrawku** [comment]
I was about to mark it as not-reproducible while using the provided stackblitz, but I've also noticed that the used igniteui-angular version is 9.0.0 there, and not 8.2. You confirm that the issue is reproducible with  8.2, right?

**Comment by MayaKirova** [comment]
@zdrawku Unfortunately I do not have a device with iOS on which to test it at this time. If you can confirm that this cannot reproduce on latest Safari in latest versions of 8.2 and 9.0 feel free to close this.

**Comment by zdrawku** [comment]
Hey Maya, I've [updated the provided sample to the latest 8.2.27](https://stackblitz.com/edit/angular-n2jbem?file=src%2Fapp%2Fgrid%2Fgrid-paging-sample%2Fgrid-paging-sample.component.ts) version and tested it under MacOS Safari v13.1.

The issue is not reproducible.

[Gif]
![2020-05-11 16 23 02](https://user-images.githubusercontent.com/11193764/81569845-7a11d800-93a8-11ea-8e41-18359f6aa44a.gif)
