### ISSUE TITLE
Range drag selection does not work on Safari.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#6570]
## Description  
Drag selection does not work on Safari.

 * igniteui-angular version: 8.2.x
 * browser: Safari

## Steps to reproduce  

1. Run the following sample on Safari: https://stackblitz.com/angular/bxgjbloolmr
2. Try to drag select a range of cells.

## Result  
Cells are not selected.

## Expected result  
Cells should be selected.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by zdrawku** [comment]
I will test that Next sprint

**Comment by nrobakova** [comment]
The issue is still reproducible in the latest version of 9.1
