### ISSUE TITLE
Customize Filter Cell using igxFilterCellTemplate

### ISSUE THREAD

**Issue by NickCook-StruMIS** [IgniteUI/igniteui-angular#6572]
Hi,

I have a question regarding the Filtering inside a Data Grid Column.

I am trying implement an Imperial mask but we still need to filter / sum etc on the imperial length column.

I have read that we can customize the Filter Cell by adding a template marked with igxFilterCellTemplate. Unfortunately, that will remove all the other functionality from the Filter Cell.

Can you suggest a way to apply an Input Mask on the Filter Cell Input ?  without losing all the other functionality available in the filter list. (see attachment for reference).

![FilterMask](https://user-images.githubusercontent.com/18016018/73468217-5b994b00-437c-11ea-875e-f5b65f26fe63.png)

I have used a similar feature in the IgxMaskDirective called displayValuePipe & focusedValuePipe that would suit the behaviour we need. Do you have this feature available in the Filter cell template.

Thanks.

**Comment by Aleksandyr** [comment]
@NickCook-StruMIS From what I understood you would like

**Comment by DiyanDimitrov** [comment]
Hello @NickCook-StruMIS.

Currently we do not expose any way to customize the input inside the filtering row.

**Comment by NickCook-StruMIS** [comment]
Thanks @DiyanDimitrov, 

How can I achieve the functionality that I need, am I doing something wrong, is there another method I can use?

All I am trying to do is expose a length column in the grid and that column has a pipe to display the bound mm value (which is a number), to an imperial string. But I still need to give the user the ability to sum on the length column. I understand that the grid would not sum on a column that has a datatype as string but the bound mm datatype is a number and only pipes the display to a string. 

I think what I was asking for originally was a work around to my problem, is there a better solution for this?

Thanks.

**Comment by DiyanDimitrov** [comment]
Hello @NickCook-StruMIS,

I would suggest you to add the converted length as a separate property in your data and bind the column to that property.

**Comment by NickCook-StruMIS** [comment]
Ok, 

That was the technique we applied in our current software. I thought with the invention of a Pipe on the column would give me more flexibility. I'm sure I will figure something out.

Thanks for your help.
