### ISSUE TITLE
Igxggrid: White space is generated when data is rebind into grid

### ISSUE THREAD

**Issue by shaileshyadav24** [IgniteUI/igniteui-angular#6576]
## Description  
When data is rebind, white space is created in bottom of grid. This make grid scrollable where number of rows are less than height of grid.

 * igniteui-angular version: 7.2.6
 * browser: All

## Expected result  
It should not create white space in bottom and should display data.

## Attachments  
![Screenshot (20)](https://user-images.githubusercontent.com/39512705/73532269-5dc5dd00-4442-11ea-9f4e-cc0b4b78891f.png)

**Comment by ChronosSF** [comment]
Hey @shaileshyadav24 , we no longer support the 7.2 release. Please, try upgrading to 8.2 where this issue should be fixed.
