### ISSUE TITLE
Why am i not able to save edited value in grid on clicking anywhere in the grid

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#6580]
## Question  
So when i edit the grid, using inline editable cells functionality.

Values are not saved when i click anywhere else in the grid, either i have to click on other cell , hide enter or f2 as provided in the document.

But i feel once edited the cell and clicked anywhere in the grid, the value should be saved in the grid instead of keeping the cell still editable and not relflecting the value in the grid.data.

Its a bottleneck and i think this is very much needed as the interaction otherwise with the grid in edit mode is a little annoying.

Its more annoying when the gird has less row and more empty space, so user doesnot have many cells to click in to save their value.

Or if there is any alternative way to handle this , please do let me know.

 * igniteui-angular version: 
 * browser:

**Comment by ddincheva** [comment]
Hello @amitmoondra ,
As you have read in our [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html#cell-editing), when you perform a certain interactions the grid submit the cell in edit mode and in other scenarios the cell exit edit mode without submitting the value or remain in edit mode. 
If you need to change this behavior the grid provides quite rich API, which will allow you to do that easily. The grid expose the following events related to the cell editing:
`onCellEditEnter; onCellEdit; onCellEditCancel`;
 Also you can use the [method endEdit(),](https://www.infragistics.com//angular-docs/typescript/latest/classes/igxgridcomponent.html#endedit) which by default will submit the cell in edit mode;
If you need any additional information or need further support, we will be happy to help.

**Comment by amitmoondra** [comment]
No none of this works, i have already tried every possible ways using the ric API, but it doesnot work.
Cannot save a cell value if in edit mode and clicked outside of any row or even somewhere in the grid.
Provide me a sample if you can for the above implementation, so i would know what i am doing wrong or if there is a new approach to handle it

**Comment by ddincheva** [comment]
Hello @amitmoondra ,
I managed to build a [small example](https://stackblitz.com/edit/angular-e8uvb2) for you where you can see how to submit the cell in edit mode if the user click somewhere in the application. Please take a look at the provided example and see if this fulfill you use case. Similarly you can apply this logic and for other scenarios. 
If you need further assistance, please contact us.

**Comment by amitmoondra** [comment]
Perfect thanks, will check this solution. It satisfies my requirement completely.
