### ISSUE TITLE
Dialog positions incorrectly on second open

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#6581]
## Description  
Dialog window positions incorrectly on second open. 

 * igniteui-angular version: 9.0.0-rc.0
 * browser: 

## Steps to reproduce  

1. Start dev demos
2. Open dialog demo
3. Click `Trigger alert` button to open Fluent dialog.
4. Press `esc` key to close the dialog.
5. Click `Trigger alert` button to open Fluent dialog.

## Result  
On second opening the dialog window is positioned a little above the middle of the page.

## Expected result  
On each opening dialog window should be positioned in the middle of the page.

## Attachments  
[Demo](https://stackblitz.com/edit/angular-itmdz1-aevnvu?file=src/app/app.component.ts) on Stackblitz. Note, you should click `Open in new window live`, as this does reproduce in `iframe`

**Comment by wnvko** [comment]
This is an [issue](https://github.com/angular/angular/issues/35124) in Angular.

**Comment by Lipata** [comment]
This will be fixed with #8780
