### ISSUE TITLE
Grid with row selection to allow CMD+Click for multiple selection on Mac

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#6584]
## Is your feature request related to a problem? Please describe.
Open the [row selection sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html)
It says "On cell click holding ctrl key, the row get selected and previous selection state is preserved." but this type of selection with the mouse is impossible to complete on a Mac.

## Describe the solution you'd like
On cell click holding command key, the row get selected and previous selection state is preserved.

**Comment by StefanIvanov** [comment]
I saw that the [row selection spec](https://github.com/IgniteUI/igniteui-angular/wiki/Row-Selection-(Grid-feature)) lacks a detailed keyboard navigation spec and I will add the scenarios there.

**Comment by Aleksandyr** [comment]
An additional handler is needed for MAC in order to cover that scenario.
