### ISSUE TITLE
igx-timepicker model is not cleared when value in the input is cleared

### ISSUE THREAD

**Issue by sjPrajwal** [IgniteUI/igniteui-angular#6585]
## timepicker works with angular form?
need to integrate the dropdown time picker with angular forms and do validation with reactive form validation.

## Describe the solution you'd like
time picker can integrate to a angular with template reference variable, instead of component directive.

**Comment by Lipata** [comment]
Hi, @sjPrajwal.

Did you had the chance to check the already existing [igxTimePicker](https://www.infragistics.com/products/ignite-ui-angular/angular/components/time_picker.html)?

**Comment by sjPrajwal** [comment]
Hi Nikolay,

i am using your time picker in my application, integrated the time picker
with angular reactive form validation.
Problem is if clear the value in time picker, ngmodel value is still
showing the todays date and time.

**Comment by sjPrajwal** [comment]
Hi @Lipata ,

You got the problem am facing..??
Please suggest any solution..

**Comment by zdrawku** [comment]
For proper ngModel binding in a `form` a `name attribute` needs to be specified for the input you're using or provide [[ngModelOptions]={standalone: true}](https://angular.io/api/forms/NgModel#using-a-standalone-ngmodel-within-a-group)

**Comment by sjPrajwal** [comment]
Hi @Lipata,

 <igx-time-picker format="HH:mm" formControlName="endTime" [minValue]="min" [maxValue]="max" mode="dropdown"
          [(ngModel)]="enquiry.endTime">
        </igx-time-picker>
this is how i am using in application, once the value set, again if i need to clear the by editing feild or by using X mark, ngModel still show the Mon Feb 03 2020 00:00:00 GMT+0530 (India Standard Time) time.

**Comment by sjPrajwal** [comment]
<div class="precondition-form">
  <form class="" [formGroup]="enquiryForm" novalidate>
    <div class="row">
      <div class="form-group date-input-feild">
        <label for="vin">VIN
        </label>
        <br>
        <input type="text" maxlength="17" formControlName="vinNumber" [(ngModel)]="enquiry.vin" id="vin"
          autocomplete="off" placeholder="VIN/FIN">
      </div>
      <div class="form-group date-input-feild">
        <label for="date">Date
        </label>
        <br>
        <input type="text" class="date-input" formControlName="date" [(ngModel)]="enquiry.date" name="date" id="date"
          value="" placeholder="Date" (ngModelChange)="onDateChange(enquiry.date)">
      </div>
      <div class="form-group date-input-feild">
        <label for="start-time">Start Time</label>
        <br>
        <igx-time-picker format="HH:mm" formControlName="startTime" [minValue]="min" [maxValue]="max"
          [(ngModel)]="enquiry.startTime" mode="dropdown" (ngModelChange)="onStartTimeChange(enquiry.startTime)">
        </igx-time-picker>
      </div>
      <div class="form-group date-input-feild zero-margin">
        <label for="end-time">End time
        </label>
        <br>
        <igx-time-picker format="HH:mm" formControlName="endTime" [minValue]="min" [maxValue]="max" mode="dropdown"
          [(ngModel)]="enquiry.endTime">
        </igx-time-picker>
      </div>
      <div class="form-group submit-button date-input-feild">
        <button class="search-btn" type="submit" (click)="preconditionCheck(enquiry)">
          Submit
        </button>
      </div>
      {{enquiryForm.valid}}
    </div>
  </form>
</div>

complete form

**Comment by sjPrajwal** [comment]
Hi @Lipata 

<div class="precondition-form">
  <form class="" [formGroup]="enquiryForm" novalidate>
    <div class="row">
      <div class="form-group date-input-feild">
        <label for="vin">VIN
        </label>
        <br>
        <input type="text" maxlength="17" formControlName="vinNumber" [(ngModel)]="enquiry.vin" id="vin"
          autocomplete="off" placeholder="VIN/FIN">
      </div>
      <div class="form-group date-input-feild">
        <label for="date">Date
        </label>
        <br>
        <input type="text" class="date-input" formControlName="date" [(ngModel)]="enquiry.date" name="date" id="date"
          value="" placeholder="Date" (ngModelChange)="onDateChange(enquiry.date)">
      </div>
      <div class="form-group date-input-feild">
        <label for="start-time">Start Time</label>
        <br>
        <igx-time-picker format="HH:mm" formControlName="startTime" [minValue]="min" [maxValue]="max"
          [(ngModel)]="enquiry.startTime" mode="dropdown" (ngModelChange)="onStartTimeChange(enquiry.startTime)">
        </igx-time-picker>
      </div>
      <div class="form-group date-input-feild zero-margin">
        <label for="end-time">End time
        </label>
        <br>
        <igx-time-picker format="HH:mm" formControlName="endTime" [minValue]="min" [maxValue]="max" mode="dropdown"
          [(ngModel)]="enquiry.endTime">
        </igx-time-picker>
      </div>
      <div class="form-group submit-button date-input-feild">
        <button class="search-btn" type="submit" (click)="preconditionCheck(enquiry)">
          Submit
        </button>
      </div>
      {{enquiryForm.valid}}
    </div>
  </form>
</div>

**Comment by zdrawku** [comment]
Change your code to:

<igx-time-picker format="HH:mm" formControlName="endTime" [minValue]="min" [maxValue]="max" mode="dropdown" **name="test"**
[(ngModel)]="enquiry.endTime">

You can use [this sample](https://stackblitz.com/edit/angular-ngmodel-form-datepicker?file=src%2Fapp%2Fscheduling%2Fdatepicker%2Fdatepicker-dropdown%2Fdatepicker-dropdown.component.html) as a reference

**Comment by sjPrajwal** [comment]
Hi IgniteUI/igniteui-angular team,

for date picker its working perfectly, but not with time picker. please see
the below link.

https://stackblitz.com/edit/angular-v7yofg?file=src/app/timepicker-sample-8/timepicker-sample-8.component.html

**Comment by sjPrajwal** [comment]
difference in date-picker and time-picker with ng-model.
working with date-picker and not working with time-picker.

https://stackblitz.com/edit/angular-ngmodel-form-datepicker-ipevrj?file=src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.html

**Comment by sjPrajwal** [comment]
Hi @Lipata,

Any updates regarding this feature??

**Comment by wnvko** [comment]
@sjPrajwal to bind input to `ngModel` the input should have either `name` attribute set or `[ngModelOptions]="{standalone: true}`. Both ways this is working in your last [sample](https://stackblitz.com/edit/angular-ngmodel-form-datepicker-rsqpsl?file=src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.html).

**Comment by sjPrajwal** [comment]
Hi @wnvko,

i think you didn't get the question i asked, from time-picker value is binding to the ng-model, but its not clearing.
Means:
1). if you try to clear values in input field of picker editing that, only from picker its clearing not from ng-model, still ng-model holding same values or 00:00 value.
2). if try to clear values using X mark in picker, still observing same behavior as above.

Instead for assigning this to feature-request we can tell its a bug in time-picker.
for date picker its working perfectly fine, please test both date-picker and time-picker of below sample.
https://stackblitz.com/edit/angular-ngmodel-form-datepicker-rsqpsl?file=src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.html

i was not able attached the screen shots, otherwise i would have attached the screen shots for better understanding.

Thanks.
Waiting for your reply.

**Comment by Lipata** [comment]
@sjPrajwal, you are correct this is a bug in the time-picker

**Comment by sjPrajwal** [comment]
Hi @Lipata,

When can i expect fix for this bug ?

**Comment by Lipata** [comment]
We can start working on this bug, as early as next week.

**Comment by sjPrajwal** [comment]
@Lipata,
Good morning.
Any updates on the issue.?

**Comment by Lipata** [comment]
Hi, @sjPrajwal. Still not started working on it. I will keep you updated when we have the time to work on this issue.

**Comment by sjPrajwal** [comment]
Okay @Lipata,

Thanks.

**Comment by PlamenaMiteva** [comment]
Hi @sjPrajwal,

Since the time picker component is designed to work with the date picker, the clear() method does not set its value to null, it sets the hours and minutes to zero instead. However we are planning to refactor both time and date picker components very soon and I have already linked this issue to the[ time picker refactoring issue](https://github.com/IgniteUI/igniteui-angular/issues/6482).
Meanwhile, a possible workaround would be to handle the valueChange event and set the value to null if it has been cleared as in the following [sample](https://stackblitz.com/edit/angular-v7yofg-ruzba1?embed=1&file=src/app/timepicker-sample-8/timepicker-sample-8.component.html)

**Comment by ammar4568** [comment]
Hi @PlamenaMiteva @Lipata @sjPrajwal any update on this? Still looking for a way to clear input to null on clear icon or back key press.

**Comment by PlamenaMiteva** [comment]
Hi @ammar4568,

The time picker can be bound to either a Date object or time-only string value in ISO 8601 format. The clear icon clears the time picker value if it is a `string` or resets the time to '00:00:00' if the value is a Date object.
So, what you want to achieve can be done by binding the time picker to a string value in ISO 8601 format. You can read more about [time picker binding](https://www.infragistics.com/products/ignite-ui-angular/angular/components/time-picker#binding) in our documentation.
