### ISSUE TITLE
Collapsing a column header may cause the grid to hide its horizontal scrollbar in a broken state

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#6591]
## Description  
Collapsing a column header while the horizontal scrollbar is not at 0 may hide it and leave the grid in a broken state

 * igniteui-angular version: 9.0.0.rc.0
 * browser: firefox

## Steps to reproduce  

1. Open https://stackblitz.com/angular/olqolmgmlpq
2. Scroll all the way to the right
3. Collapse the Location header

## Result  
The scroll position of the grid doesn't change and it's left in a broken state

## Expected result  
The scroll position should reset when the scrollbar is hidden

## Attachments  
![issue](https://user-images.githubusercontent.com/2188411/73663920-2dcb4380-46a7-11ea-9dcb-b074cd6f327e.gif)

**Comment by nrobakova** [comment]
This issue is no longer reproducible in latest versions of 9.0 and 9.1.
 I tested the issue in Chrome, Firefox and Edge and it is not reproducible.
