### ISSUE TITLE
igGrid BUG: Hidden column in igGrid is still being displayed

### ISSUE THREAD

**Issue by k-DEV1** [IgniteUI/igniteui-angular#66]
![iggrid display bug](https://cloud.githubusercontent.com/assets/19562705/15526017/f3b0d462-222e-11e6-8be8-419b55dcf4ec.png)

Hello,

I have an igGrid and an HTML form binded to one $scope data source. A certain column is set to be hidden in the grid, but it is set to be displayed in the HTML form. When I update the value of the column in the form, the value is incorrectly being displayed in the grid as well. To illustrate the issue better, let's use your example for the AngularJS Grid : http://www.igniteui.com/grid/angular

Using JSFiddle, add the property hidden="true" to the column-key="ProductName". Column Product Name should now be hidden in the grid, then update the value of the Supplier Name (ProductName) in the HTML form, the updated value will be displayed in the Unit Price column in the grid. I have attached an image showing this bug as well.

Could you please fix this?

Thanks

**Comment by dkamburov** [comment]
This one should be fixed with commit #62 
You can also refer to the following sample [http://jsfiddle.net/s5bpobxo/](http://jsfiddle.net/s5bpobxo/)
