### ISSUE TITLE
[Select] Item text and input text size differs

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#6609]
## Description  
 Item text and input text size differs, thus when selecting new item the input and item text are not exactly text-over-text.

input font-size: 1rem;
item font-size: .875rem;

 * igniteui-angular version: 
 9.0.0-rc.2

## Steps to reproduce  

1. https://staging.infragistics.com/products/ignite-ui-angular/angular/components/select.html#features

## Result  
Not matching text-over-text.

## Expected result  
Matching text-over-text.

## Attachments  
![select-item-input-text](https://user-images.githubusercontent.com/4296944/73833149-270d0f80-4812-11ea-9f4e-92f81d8785f9.gif)

**Comment by simeonoff** [comment]
@IvayloG we decided not-to-fix this. In the future, please assign all issues related to styling to me first.
