### ISSUE TITLE
9.0.0-rc.2: cannot set id for igx-drop-down

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#6624]
## Description  
After trying to upgrade to angular 9, I seem to have issues with the igx-drop-down component. I have the following dropdown
![image](https://user-images.githubusercontent.com/12936286/73919415-cd651d80-48c3-11ea-8976-4c9939dc8807.png)

But I get this error:
![image](https://user-images.githubusercontent.com/12936286/73919457-e66dce80-48c3-11ea-8ffc-d3036ba5e196.png)

Seems like the toggle directive is undefined

![image](https://user-images.githubusercontent.com/12936286/73919619-2df45a80-48c4-11ea-8e0b-d2e7e794d731.png)

Are there any known issues with this for the latest rc?

 * igniteui-angular version: 9.0.0-rc.2
 * browser: Chrome, latest

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by IvayloG** [comment]
This should be already resolved in igniteui-angular 9.0.0-rc.2 with the following [PR](https://github.com/IgniteUI/igniteui-angular/pull/6568/files). Please make sure you have this version successfylly installed. In case the issue persist, let me know what is the exact update process you go trough, as it may break something.

**Comment by Eralmidia** [comment]
Yes, you are quire right, I hadn't bumped the igx package to the latest rc after all. Thanks
