### ISSUE TITLE
Add button in the left side of grid toolbar

### ISSUE THREAD

**Issue by jaya0selva** [IgniteUI/igniteui-angular#6626]
## Is your feature request related to a problem? Please describe.
We want to add 'Expand/Collapse All' button for treegrid in the left side of the toolbar. Is there is way to add it in the left side?

**Comment by zdrawku** [comment]
This is achievable by using the public api of the grid - [expandAll()](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtreegridcomponent.html#expandall) and [collapseAll()](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtreegridcomponent.html#collapseall). Check out [this sample ](https://stackblitz.com/edit/angular-expand-collapse-all)for a reference. You can use position the custom button on the left site by using css or other type of ng-template content changes.

Code snippet:
```
<igx-tree-grid #treeGrid [data]="data" [allowFiltering]="true"
        [showToolbar]="true"
        primaryKey="ID" foreignKey="ParentID" width="100%" height="400px"
        [rowSelectable]="true">
        <ng-template igxToolbarCustomContent let-treeGrid="treeGrid">
            <button igxButton="flat" igxRipple igxRippleCentered="true" (click)="toggleAllRows()">
        <igx-icon *ngIf="expanded" fontSet="material">expand_more</igx-icon>
        <igx-icon *ngIf="!expanded" fontSet="material">expand_less</igx-icon>
              Expand/collapse all
            </button>
        </ng-template>
```

Related to https://github.com/IgniteUI/igniteui-angular/issues/6550

**Comment by williamverdolini** [comment]
Could you think of a more integrated solution?
The common user experience for collapse all/expand all is to have this action in the grid header alligned with the other actions for collapse/expande the single rows. 
The same experience you can see here: https://github.com/IgniteUI/igniteui-angular/issues/3298

Could you reopen this issue pls?
Thank you
