### ISSUE TITLE
Error after updating project to angular 9

### ISSUE THREAD

**Issue by pnaika** [IgniteUI/igniteui-angular#6637]
## Description  
Describe the issue.
ERROR in node_modules/igniteui-angular/lib/navigation-drawer/navigation-drawer.component.d.ts:1:84 - error TS2724: Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

This is the error that fails the compilation. I checked  navigation-drawer.component.ts file and I see the import is Renderer2, I believe it's the problem with current stable version. 

 * igniteui-angular version: ^8.2.18
 * browser: chrome

## Steps to reproduce  

1. Step 1 upgrade angular project to 9
2. Step 2 install igniteui-angular version: ^8.2.18

## Result  
What is the actual result after following the steps to reproduce?
Need to compile successfully

## Expected result  
What is the expected result after following the steps to reproduce?
build/compilation fails with the error,  ERROR in node_modules/igniteui-angular/lib/navigation-drawer/navigation-drawer.component.d.ts:1:84 - error TS2724: Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ChronosSF** [comment]
Versions 8.x.x are not compatible with Angular 9. We are at the latest stages of testing and will release Ignite UI for Angular v9.0.0 for Angular 9 in the next couple of days. Until then you can install our latest release candidate so that your app can build with Angular 9 using ```ng update igniteui-angular --next```
