### ISSUE TITLE
Provide support for numeric type in IgxInput

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#6647]
## Is your feature request related to a problem? Please describe.
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/1724

## Describe the solution you'd like
Provide  specification and support for numeric type inputs.

**Comment by Lipata** [comment]
https://stackoverflow.com/questions/23372903/hide-spinner-in-input-number-firefox-29
