### ISSUE TITLE
Page state is not maintained when undo'ing or clearing transaction state in the grid

### ISSUE THREAD

**Issue by ericmahlberg** [IgniteUI/igniteui-angular#6654]
## Description  
With Paging enabled on a grid that is maintaining transactions, if you navigate away from page 1, make some edits and either click undo or clear the transactions, the page skips back one.  You can repro this on the sample here as of 2/10/2020 by adding [paging]="true" to the grid markup:
https://stackblitz.com/angular/gkklevbvkgy?file=src%2Fapp%2Fgrid%2Fgrid-batch-editing%2Fgrid-batch-editing-sample.component.html

 * igniteui-angular version: "9.0.0-beta.3", "8.1" and "8.2" were tested
 * browser: Chrome

## Steps to reproduce  

1. Navigate away from page 1, make edits to records
2. click 'undo' or clear the transactions service
3. Grid goes backwards one page

## Result  
Grid errantly goes back a page

## Expected result  
Grid should maintain the page the user is on if they undo their edits

**Comment by MayaKirova** [comment]
Does not seem to reproduce with just 2 pages. 
Possible steps to reproduce are:
1) Set [paging]='true' [perPage]="5" in the batch editing sample:  https://stackblitz.com/angular/xaapvooypara
2) Go to page 3.
3) Edit a cell value.
4) Click the "Undo" button.

Actual Result:
Grid goes to page 2.

Expected Result:
Grid stays on page 3.
