### ISSUE TITLE
Slider deprecated property isContinuous is missing

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#6660]
### Description  
The fintech-tree-grid scenario has being updated in 5.x.x. If you have this template in a project created with a previous version (4.x.x), _ng serve_ could not be completed because of error. 

- Ignite UI CLI version: 5.0.0-rc.3
- Framework: Angular
- Project type: igx-ts

#related https://github.com/IgniteUI/igniteui-cli/issues/628

### Steps to reproduce  

1. Create a project with 4.4.x and add _fintech-tree-grid_ scenario
2. Execute ng update @angular/core and @angular/cli
3. Execute ng update --next for igniteui-cli and igniteui-angular
4. Execute _ng serve -o_

### Result  
ERROR in src/app/fintech-tree-grid/fintech-tree-grid.component.html:12:153 - error NG8002: Can't bind to 'isContinuous' since it isn't a known property of 'igx-slider'.
    1. If 'igx-slider' is an Angular component and it has 'isContinuous' input, then verify that it is part of this module.

### Expected result  
Update the template where required.

### Attachments  
![image](https://user-images.githubusercontent.com/4296944/74229352-df333000-4cca-11ea-943c-15702e11f638.png)

**Comment by damyanpetev** [comment]
Moved from the CLI, as this is listed as deprecated, but it's actually removed (which is a breaking change BTW). The old prop should either remain as deprecated or the change should be documented as a breaking change.
Either way the rename should be included in the migrations.

**Comment by Aleksandyr** [comment]
@damyanpetev as we already determined the migrations have been updated with the respective change. Also, the note can be found under 9.0.0-rc.1 RTM, though it's not perfectly described. We can update the changelog by moving the property under the appropriate section **breaking changes**.
@IvayloG @damyanpetev  shall we close the issue?

**Comment by damyanpetev** [comment]
Yeah, nvm the migration didn't run without a fix from https://github.com/IgniteUI/igniteui-angular/pull/6643/files#diff-42ff1520040998b9e32b97c4c99e6299R45 that's not in the latest RC. With the update it updated alright
