### ISSUE TITLE
igxToolbar pinning dropdown to support both sides pinning

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#6677]
Parent: #6676

**Comment by StefanIvanov** [comment]
Hi, I am sharing a toolbar dropdown design that would support both left and right pinning. If a column is pinned left and we click on the pin right icon, it would work as a radio button and unmark left pinning and remove it from the left pin area before continuing with pinning right. To disable pinning on a pinned column one has to click on the active color, which would result in both icons appearing in idle state.
![right](https://user-images.githubusercontent.com/1702064/74341210-f861dc80-4daf-11ea-99f4-a019205cf86a.png)

**Comment by ChronosSF** [comment]
Are there icons for this? :astonished:

**Comment by StefanIvanov** [comment]
All pinning icons are custom

**Comment by StefanIvanov** [comment]
I guess you would need them as SVG if design is agreed upon

**Comment by ChronosSF** [comment]
@StefanIvanov , we decided that we won't support both sides pinning.
