### ISSUE TITLE
Scroll position remains negative hiding filtering result partially in the last virtualization chunk in remote scenario

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#6678]
Rows may become partially hidden when the scrollTop applied for smooth scrolling is not cleared during filtering actions in the remote virtualization scenario

 * igniteui-angular version: 9.0.0
 * browser: Chrome, Firefox

## Steps to reproduce  

1. Open the attached sample
2. Scroll all the way down
3. In the Excel filter, choose only 2 rows to be visible

## Result
1. The smooth scrolling applied scrolltop is not cleared and the rows remain half-hidden. This _may_ be a sample issue in which case the fix should be added to angular-samples

## Expected result  
The two rows to be visible

[angular-ed7aib.zip](https://github.com/IgniteUI/igniteui-angular/files/4219582/angular-ed7aib.zip)

**Comment by MayaKirova** [comment]
Resolved in sample: 
https://github.com/IgniteUI/igniteui-angular-samples/pull/1819
https://github.com/IgniteUI/igniteui-angular-samples/pull/1820
