### ISSUE TITLE
Grid searching through virtualised content: highlighting does not work for anchor text or formatted values

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6682]
## Description
Following https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/search.html I have a search component with 7 grid columns.
When I enter some text in the search1 input field, cell text is highlighted on a match, but never the 
anchor text or text I have formatted.

Examples are:
```html
   <!-- HIGHLIGHTING WORKS !! -->
    <igx-column
      [header]="'Subrubric'"
      [field]="'subRubric'"
      [width]="'105px'"
      [resizable]="true"
      [filterable]="true"
      [sortable]="true"
      [hidden]="false"
      [movable]="true"
    ></igx-column>

   <!-- HIGHLIGHTING DOES NOT WORK !! -->
    <igx-column
      [header]="'Company UID'"
      [field]="'companyUID'"
      [resizable]="true"
      [filterable]="false"
      [sortable]="true"
      [hidden]="true"
      [movable]="true"
    >
      <ng-template igxCell let-value>
        {{ displayCompanyUID(value) }}
      </ng-template>
    </igx-column>

   <!-- HIGHLIGHTING DOES NOT WORK !! -->
    <igx-column
      [header]="'Title'"
      [field]="'title'"
      [resizable]="true"
      [sortable]="true"
      [disableHiding]="true"
      [movable]="true"
    >
      <ng-template igxCell let-cell="cell">
        <a [routerLink]="['/edit/', cell.rowData.id]"> {{ cell.value }} </a>
      </ng-template>
    </igx-column>
```
 * igniteui-angular version: 9.0.0
 * browser: Chrome 79.0.3945.130, Firefox 72.0.2
 * os: Linux Mint 19.3

## Steps to reproduce

1. Use the stack blitz instance on the link above
2. change a <igx-column> to have an <ng-template>, make it call a method in the component.
3. try to have the search highlight its content.
4. it will jump to that cell, but there is no highlight

## Result
No highlighting happens, despite the text matching.

## Expected result  
It would be great if the highlight would cover the examples above: anchor text and custom formatted values.

### 1)  Working: "HR01" in `Subrubric`

![image](https://user-images.githubusercontent.com/150055/74345615-a53b5a00-4dae-11ea-9580-8e9b6553b2c4.png)

### 2)  Not working: "CHE-", the `Company UID`'s prefix, formatted

![image](https://user-images.githubusercontent.com/150055/74345758-dc117000-4dae-11ea-98a8-418c080f9e95.png)

### 3)  Not working: "Neueintragung", the anchor text

![image](https://user-images.githubusercontent.com/150055/74345915-1549e000-4daf-11ea-953c-4bf8558a511e.png)

**Comment by ddincheva** [comment]
Hello @catull ,
This behavior in our product is expected and is described in the [Known Limitation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/search.html#known-limitations) section of [Searching topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/search.html). So the requested behavior should be implemented on application level. A possible solution may involve the custom cell styles or column formatters functionalities, so you can take a look at the following [issue](https://github.com/IgniteUI/igniteui-angular/issues/5951) where we explain how to use them in more details.
