### ISSUE TITLE
Radial Pie Chart: Add label position configuration

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#6687]
## Is your feature request related to a problem? Please describe.
The current label position consumes too much space from the window, the only current solution is make the pie smaller so it can fit.

Also if the pie is placed as a part of multiple charts it looks "lonely", that's because the labels leave too much space being unutilized

## Describe the solution you'd like
I would like to be able to do one of the following:
1. Put the labels inside the chart, like the second pie does.
2. Asign a different color to each category so i can add legends and remove the current labels.

## Describe alternatives you've considered
I'll use another chart,

My original requirement was something like a "[skill chart](https://www.google.com/search?q=skill+chart&rlz=1C1CHBF_esMX852MX852&sxsrf=ACYBGNRmd9O3WsyeU66eos_ASdU2TMdxRQ:1581535773360&tbm=isch&source=iu&ictx=1&fir=1LLcVj3jNaEBpM%253A%252CtSbQ7FDv7XrZXM%252C_&vet=1&usg=AI4_-kTpbn6PHiU_7EYMPTqNm1n1F8fYMg&sa=X&ved=2ahUKEwjV1OHv38znAhVCnq0KHcajCNAQ9QEwB3oECAoQEg#imgrc=1BUS1rK_SKU92M)", but i think radial pie full fills most of the requirement, i mention this because i dont want to use another chart...

## Additional context
![image](https://user-images.githubusercontent.com/29953012/74366690-13bfee00-4d96-11ea-9fe9-b50cc3b304db.png)

This FR is about *Radial Pie Chart* only, the second pie is there for illustration porpuses.

**Comment by zdrawku** [comment]
Issue moved to [IgniteUI/igniteui-angular-charts #30](https://github.com/IgniteUI/igniteui-angular-charts/issues/30) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zdrawku** [comment]
hey @luiscla27 the right place for chart issues [is this repository](https://github.com/IgniteUI/igniteui-angular-charts/issues/30), and it has been moved accordingly.
