### ISSUE TITLE
IgxGridComponent columns do not display in same order (left to right)

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6688]
## Description  
When running igniteui-angular 8.2.18 with Angular 8 the IgxGridComponent columns displayed in the correct order, left to right.  First displaying the static columns (Example 6 static columns) and then Next displaying the dynamic columns (Example 4 dynamic columns).

columns left to right
(Example 6 static columns)  (Example 4 dynamic columns)

After updating Angular from 8 to 9.0.0 and updating igniteui-angular from 8.2.18 to 9.0.0
The IgxGridComponent columns no longer display in the same order, left to right.
Now the IgxGridComponent dynamic columns display as the first columns in the grid
and then the IgxGridComponent static columns display to the right of the dynamic columns.

columns left to right
(Example 4 dynamic columns)  (Example 6 static columns)

 * igniteui-angular version: 9.0.0
 * browser: Google Chrome 79.0.3945.130 (Official Build) (64-bit)

## Steps to reproduce  

1. Update project from Angular 8 to Angular 9
2. Update project from igniteui-angular from 8.2.18 to 9.0.0

## Result  
What is the actual result after following the steps to reproduce?
IgxGridComponent displays columns in different order, left to right
Dynamic columns are displayed as the first columns in the grid, left to right
Static columns are displayed as the next columns in the grid after the dynamic columns, left to right

## Expected result  
What is the expected result after following the steps to reproduce?
IgxGridComponent should display columns in same order as before npm package update
Static columns are displayed as the first columns in the grid, left to right
Dynamic columns are displayed as the next columns in the grid after the dynamic columns, left to right

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by brookhutchinson** [comment]
Any news on this bug?

**Comment by hanastasov** [comment]
brookhutchinson, I am currently investigating it and will update you shortly on my findings. ONe clarifying questions is - do you refer to the columns declared in markup with "static columns" and refer to dynamic columns for columns created in code ?

**Comment by hanastasov** [comment]
@brookhutchinson, I assume you mean the autogenerated columns by 'dynamic columns'. My observation shows when autoGenerate columns is true, the grid will NOT render the columns that are declared using markup or code. This is same in 8.2 and 9 versions, please confirm if this is the behavior that you report.

**Comment by brookhutchinson** [comment]
Thank you for your help.  Good news is that all of the columns in the grid render, but the bad news is that after updating the Igniteui-angular / angular 9.0.0 the columns do not render in the same order as igniteui-angular 8.2.18 / angular 8.2.14.

The issue is that the "dynamic columns" are rendered as the first columns in the grid (left to right) instead of the last columns in the grid (left to right).  I need the "dynamic columns" to display as the last columns in the grid just as they did when using igniteui-angular 8.2.18 / angular 8.2.14

For clarification...
When I refer to "static columns" I am referring to a column that is bound to a property
Example the "Name" column

When I refer to "dynamic" columns I am referring to columns that are calculated at runtime and then dynamically displayed in the grid based on calculations.
Example the "Calculation Columns"

Example code below of the grid html template
`<!-- grid -->
<igx-grid #grid [id]="gridId" [isLoading]="false" [data]="newLocalData" (onCellClick)="onCellClick($event)" (onFilteringDone)="filteringDone()" (onSortingDone)="sortingDone($event)" [filterMode]="'excelStyleFilter'" [emptyFilteredGridMessage]="'Data is not available for the selected filters'" [primaryKey]="'analyzer_tag'" (onPagingDone)="pagingDone($event)" (onColumnInit)="initColumns($event)">
  <!-- grid toolbar -->
  <ng-template igxToolbarCustomContent let-grid="grid">
    <!-- save view button -->
    <button id="saveViewButton" igxButton="flat" igxButtonBackground="rgb(0,0,0,.1)" igxRipple igxRippleCentered="true" (click)="saveGrid(grid)" [displayDensity]="'compact'">
      <igx-icon color="#000" fontSet="material">save</igx-icon>
      <span class="button-font-color">Save View</span>
    </button>

    <!-- space between buttons -->
    <span class="button-spacing">&nbsp;</span>

    <!-- clear button -->
    <button id="clearButton" igxButton="flat" igxButtonBackground="rgb(0,0,0,.1)" igxRipple igxRippleCentered="true" (click)="clearGridConfig(grid)" [displayDensity]="'compact'">
      <igx-icon color="#000" fontSet="material">settings_backup_restore</igx-icon>
      <span class="button-font-color">Clear</span>
    </button>

    <!-- space between buttons -->
    <span class="button-spacing">&nbsp;</span>

    <!-- expand button -->
    <button id="expandButton" igxButton="flat" igxButtonBackground="rgb(0,0,0,.1)" igxRipple igxRippleCentered="true" (click)="sendExpandView()" [displayDensity]="'compact'">
      <igx-icon color="#000" fontSet="material">fullscreen</igx-icon>
      <span class="button-font-color">Expand</span>
    </button>
  </ng-template>

  <!-- remove features from the column filter menu by defining column templates -->
  <!-- column sorting template -->
  <ng-template igxExcelStyleSorting></ng-template>
  <!-- column hiding template -->
  <ng-template igxExcelStyleHiding></ng-template>
  <!-- column moving template -->
  <ng-template igxExcelStyleMoving></ng-template>
  <!-- column pinning template -->
  <ng-template igxExcelStylePinning></ng-template>

  <!-- name column -->
  <igx-column field="analyzer_tag" header="Name" width="120" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Analyzer Name</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template igxCell let-value>
      <span class="cell__inner">
        <span>
          <img *ngIf="isDcsFlag(value)" src="assets/images/DCS_analyzer.svg" title="DCS" alt="DCS">
          <img *ngIf="!isDcsFlag(value)" src="assets/images/DVT_analyzer.svg" title="DVT" alt="DVT">
        </span>&nbsp;
        <span>
          {{ value }}
        </span>
      </span>
    </ng-template>
  </igx-column>

  <!-- note column -->
  <igx-column header="Note" field="days_old" width="82" [dataType]="'number'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Days Since Last Note</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template igxCell let-value>
      <span class="cell__inner">{{ value }}</span>
    </ng-template>
  </igx-column>

  <!-- team/complex column -->
  <igx-column field="plant_code" header="Team/Complex" width="115" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Team/Complex</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- unit column -->
  <igx-column field="unit" header="Unit" width="95" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Unit</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- unit name column -->
  <igx-column field="area" header="Unit Name" width="152" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Unit Name</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- technology column -->
  <igx-column field="analyzer_type" header="Technology" width="105" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Technology</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- criticality column -->
  <igx-column field="criticality" header="Criticality" width="173" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Criticality</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- function column -->
  <igx-column field="function_code" header="Function" width="173" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Function</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- obsolescence column -->
  <igx-column field="obsolescence_phase" header="Obsolescence" width="120" [dataType]="'number'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Obsolescence</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- service column -->
  <igx-column field="service" header="Service" width="120" [dataType]="'string'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Service</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- annual value column -->
  <igx-column field="annual_credit_value" header="Annual Value" width="100" [dataType]="'number'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Annual Value (USD)</span>
        <span>Service value 0 indicates license to operate</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- lost opportunity column -->
  <igx-column field="lost_opportunity" header="{{ this.loDays }} days LO" width="100" [dataType]="'number'" [disableHiding]="false" [disablePinning]="false" [filterable]="true" [movable]="false" [resizable]="true" [sortable]="true">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <span class="text" #target="tooltipTarget" [attr.draggable]="false" [hideDelay]="0" [igxTooltipTarget]="tooltipRef" [showDelay]="0">{{ col.header }}</span>
      <div class="tooltip" #tooltipRef="tooltip" igxTooltip>
        <span>Lost Opportunity (USD)</span>
      </div>
    </ng-template>

    <!-- column value template -->
    <ng-template let-value>
      {{ value }}
    </ng-template>
  </igx-column>

  <!-- calculation columns -->
  <igx-column *ngFor="let item of columns" [dataType]="'number'" [field]="item.tag" [header]="item.header" [resizable]="true" [sortable]="true" [width]="item.width">
    <!-- column header template -->
    <ng-template igxHeader let-col>
      <!-- do not show tooltip on calculation columns, set title attribute of column header <span> to "" -->
      <span class="text" title="">{{ col.header }}</span>
    </ng-template>

    <!-- column value template -->
    <ng-template igxCell let-value>
      <div class="currency-badge-container">
        <igx-badge *ngIf="value >= 0 && value < 90" class="badge-left" icon="close" position="bottom-right"></igx-badge>
        <igx-badge *ngIf="value >= 90 && value < 95" class="badge-left" icon="priority_high" position="bottom-right" type="warning"></igx-badge>
        <igx-badge *ngIf="value >= 95" class="badge-left" icon="check" position="bottom-right" type="success"></igx-badge>
        <span class="cellAlignSyle" [class.up]="value >= 95" [class.warning]="value >= 90 && value < 95" [class.down]="value >= 0 && value <= 90">{{ formatNumber(value) }}</span>
      </div><!-- /.currency-badge-container -->
    </ng-template>
  </igx-column>
</igx-grid>`

**Comment by hanastasov** [comment]
hi @brookhutchinson, thank you for your clarifications. My testing shows that the behavior is the same in both 8.2. and 9.0 versions:

Here is an example with 9.0: https://stackblitz.com/edit/angular-xfhtdh

Please refer to the markup where I have added both static and dynamic columns. The order the columns are rendered depends on their order in the declaration.

Currently the markup is: `dynamic columns` + `static columns and in the rendered page `dynamic columns come first. If you move their declaration after the static columns declaration, i.e.: `static columns` + `dynamic columns` then the grid renders them in the corresponding order: `static columns -> dynamic column`.

If you confirm this behavior on your side too, this is expected. If you think that my scenario msises a point, or is not a good representation, please modify it on order to demonstrate the reported issue.

**Comment by brookhutchinson** [comment]
Thank you for taking the time to respond and create an example. I will compare your example to my code and go from there.

One thing that I see that is different between your example an my code is that I am not setting the <igx-grid autoGenerate="false">  I am not setting the "autoGenerate" property at all.  I understand that the default value is set to "false", but I wonder if by not explicitly setting the "autoGenerate" property that this indirectly leads to the columns being rendered inside the grid in a different order?

**Comment by hanastasov** [comment]
> Thank you for taking the time to respond and create an example. I will compare your example to my code and go from there.
> 
> One thing that I see that is different between your example an my code is that I am not setting the I am not setting the "autoGenerate" property at all. I understand that the default value is set to "false", but I wonder if by not explicitly setting the "autoGenerate" property that this indirectly leads to the columns being rendered inside the grid in a different order?

The `autoGenerate` property is false by default, so not setting it explicitly does not make a difference, you can remove it from the sample I provided to see it in action.

**Comment by brookhutchinson** [comment]
After updating my project from ignite angular 8.2.4 to ignite-angular 9.0.4 the columns inside IgxGrid do not display in the same order (left to right). Note that when updating from 8.x.x to 8.x.y the columns in the IgxGrid always displayed in ths correct order.  The issue only starts happening after updating to ignite-angular 9.0.0+

I have tried setting the grid.autoGenerate property to false and tru. No luck. Any other ideas?

**Comment by hanastasov** [comment]
@brookhutchinson , could you please use this 9.0.0 app https://stackblitz.com/edit/angular-xfhtdh  and modify it in a way to reproduce the described behavior ? So far I have not been able to reproduce the issue. You can also start a new stackbltiz sample (or new local sample) and use the same package.json and tsconfig and angular.json file as in your real app to replicate the environment. Once you have the issue isolated, please share it with us so that we can investigate it and make any corrections in our code if needed.

**Comment by zdrawku** [comment]
@brookhutchinson have you tried Hristo's last suggestions?

**Comment by brookhutchinson** [comment]
Thank you for your message.  I have definitely experimented with both setting the "autoGenerate" property of the IgxGridComponent at development time inside the Component HTML Template and at runtime inside the TypeScript.  I have not been successful in having the columns in the IgxGridComponent render in the correct order (left to right).  Note that this works fine with an Angular 8 IgniteUI Project.  I do not even have to set the "autoGenerate" property to true or false with an Angular 8 IgniteUI Project.  It just works as is probably using a default value of "false" for "autoGenerate" since the "autoGenerate" property is not set at development time or runtime.

**Comment by brookhutchinson** [comment]
I am open to more suggestions.

**Comment by brookhutchinson** [comment]
Here is what I have discovered.
1) The “autoGenerate” property on the <igx-grid> default value is “false”
2) The “autoGenerate” property is not defined at development time inside the Component HTML Template right now
3) If I set an autoGenerate=”false” or autoGenerate=”true” on the <igx-grid> directive inside the Component HTML Template then when the grid initially displays in the browser the columns are rendered in the correct order
4) At runtime, if I change a dropdown that will trigger going to get new data, bind to the grid, and then render the new grid, the columns are not rendered in the correct order. The columns do not render in the same order as the columns are defined inside the Component HTML Template

**Comment by brookhutchinson** [comment]
If I set the IgxGridComponent "autoGenerate" property using 2-way data binding to "false" at development time then the columns inside the grid do not display in the correct order (left to right).

**Comment by brookhutchinson** [comment]
Note that your example does not initialize the columns in the grid using the (onColumnInit) method

**Comment by brookhutchinson** [comment]
Looking closer at the Stackblitz Example that was provided 
[ https://stackblitz.com/edit/angular-xfhtdh]
it does not look like the Grid is displaying data correctly in the columns of the grid.

If the "autoGenerate" property is set to "false" then the "ID" Column and "Company Name" column do not have any data displaying inside each column.

If the "autoGenerate" property is set to "true" then the "ID" Column and "Company Name" column does have data displaying in each column, but unfortunately the columns are not being displayed in the correct order inside the grid (left to right) based on how the columns are defined inside the Component HTML Template

**Comment by hanastasov** [comment]
Hi @brookhutchinson , I am currently reviewing all your last comments and will reach out to you.

**Comment by brookhutchinson** [comment]
Any update on this open issue?

**Comment by hanastasov** [comment]
Hi @brookhutchinson,

I carefully reviewed your comments and feel like you are misinterpreting the expected behavior. Pleas let me know if I am missing something from your description in my response.

> Note that the stackblitz example does not initialize the columns in the grid using the (onColumnInit) method of the IgxGridComponent. My code uses the (onColumnInit) method of the IgxGridComponent to initialize the columns of the IgxGridComponent. Is there anything that I need to do inside the onColumnInit method to ensure that the columns display in the correct order?

The `onColumnInit` event is not an event that s used "to initialize" the columns, rather it is an event that is emitted when a column is initialized. It does not make any difference if the column is `autogenerated`, or is defined in markup or in code - the event will be emitted for each column. This event is helpful to set some properties on columns depending on some of their properties - for example, a dev may want to enable sorting for all numeric columns.

> The "args" property that is passed as a parameter to the onColumnInit(args) method shows that each column inside the args property is set to index 0, 1, 2, 3, 4, .... so I would expect the columns to display in the same order 0, 1, 2, 3, 4, ....

**PLEASE NOTE** that the `visibleIndex` is only a **getter**, meaning it will return the `visibleIndex` of the column (based on the order of columns declaration in markupor in code), but this cannot be set. Trying to set it like `column.visibleIndex = n` will not make any difference. Instead, just order the columns in the desired order in the markup.

**Comment by hanastasov** [comment]
> Looking closer at the Stackblitz Example that was provided
> [https://stackblitz.com/edit/angular-xfhtdh](url)
> It does not look like the Grid is displaying data correctly in the columns of the grid.
> 
> If the "autoGenerate" property is set to "false" then the "ID" Column and "Company Name" column do not have any data displaying inside the "ID" Column or the "Company Name" column.
Hi, in this concrete example I used dummy columns to demonstrate my point. So i set `ID` and `CompanyName` columns, but there is no data for them to bind to. Just ignore that, it is irrelevant to the issues discussed here.

> 
> If the "autoGenerate" property is set to "true" then the "ID" Column and "Company Name" column does have data displaying in each column, but unfortunately the columns are not being displayed in the correct order inside the grid (left to right) based on how the columns are defined inside the Component HTML Template
What I see is that columns are defined in the following order - ID, CompanyName, and they are rendered in the same order:
![image](https://user-images.githubusercontent.com/14248932/77887398-2c676300-7273-11ea-8bfb-1d0f4e15ec51.png)
![image](https://user-images.githubusercontent.com/14248932/77887414-325d4400-7273-11ea-9f2e-44a18a88cb17.png)

**Comment by brookhutchinson** [comment]
Thank you for taking the time to look into this issue.  

Unfortunately I still have the issue of the columns not displaying in the same order after upgrading to Angular 9/Ignite 9.  Using your StackBlitz Example you can see this same behavior.

Here are my findings

**When using Angular 8/igniteui-angular 8**
If I use property binding to set the "autoGenerate" property to "false" then columns do render in correct order (left to right)
`<igx-grid #grid [id]="gridId" [data]="newLocalData" [filterMode]="'excelStyleFilter'" [isLoading]="false" [primaryKey]="'analyzer_tag'" (onCellClick)="onCellClick($event)" (onColumnInit)="initColumns($event)" (onFilteringDone)="filteringDone()" (onPagingDone)="pagingDone($event)" (onSortingDone)="sortingDone($event)" [autoGenerate]="false">`

**When using Angular 9/igniteui-angular 9**
If I use property binding to set the "autoGenerate" property to "false" then columns do not render in correct order (left to right)
`<igx-grid #grid [id]="gridId" [data]="newLocalData" [filterMode]="'excelStyleFilter'" [isLoading]="false" [primaryKey]="'analyzer_tag'" (onCellClick)="onCellClick($event)" (onColumnInit)="initColumns($event)" (onFilteringDone)="filteringDone()" (onPagingDone)="pagingDone($event)" (onSortingDone)="sortingDone($event)" [autoGenerate]="false">`

**Comment by hanastasov** [comment]
> Thank you for taking the time to look into this issue.
> 
> Unfortunately I still have the issue of the columns not displaying in the same order after upgrading to Angular 9/Ignite 9. Using your StackBlitz Example you can see this same behavior.
> 
> Here are my findings
> 
> **When using Angular 9/igniteui-angular 9**
> If I use property binding to set the "autoGenerate" property to "false" then columns do not render in correct order (left to right)
> `<igx-grid #grid [id]="gridId" [data]="newLocalData" [filterMode]="'excelStyleFilter'" [isLoading]="false" [primaryKey]="'analyzer_tag'" (onCellClick)="onCellClick($event)" (onColumnInit)="initColumns($event)" (onFilteringDone)="filteringDone()" (onPagingDone)="pagingDone($event)" (onSortingDone)="sortingDone($event)" [autoGenerate]="false">`

Looking at https://stackblitz.com/edit/angular-xfhtdh, expected columns order is:
ID, Company, Static, Static2, Static3 (first two are created dynamically in code, last three are declared through markup), `autoGenerate` is false.

In reality, order is the same as expected:
![image](https://user-images.githubusercontent.com/14248932/77913048-4a958900-729c-11ea-8bca-ba52c40d0c33.png)

**Comment by brookhutchinson** [comment]
Ok. So when using your StackBlitx Example, the columns do display in the correct order if you set the "autoGenerate" property to "false".

Unfortunately when the "autoGenerate" property is set to false then there is no data displays inside the first 2 columns.

If I change the "autoGenerate" property to true then data does display inside the first 2 columns.

My goal is to set the "autoGenerate" property to false and populate all columns in the grid including the first 2 columns.  This was the behavior when using Angular 8/igniteui-angular 8. 

How do I do this using Angular 9/igniteui-angular 9?

**Comment by hanastasov** [comment]
> Ok. So when using your StackBlitx Example, the columns do display in the correct order if you set the "autoGenerate" property to "false".
> 
> Unfortunately when the "autoGenerate" property is set to false then there is no data displays inside the first 2 columns.
> 
> If I change the "autoGenerate" property to true then data does display inside the first 2 columns.
> 
> My goal is to set the "autoGenerate" property to false
> 
> 1. Display columns in correct order (left to right)
>    and
> 2. Populate all columns inside the grid (including the first 2 columns).
> 
> This was the behavior when using Angular 8/igniteui-angular 8.
> 
> How do I do this using Angular 9/igniteui-angular 9?

Hi @brookhutchinson , as I explained earlier, the **first two columns in this concrete demo are just mock columns** - their field names do not correspond to any field in the data source, hence columns are not populated with any data. Just change the column field values to correspond to fields in the data source and columns will be populated accordingly:
![image](https://user-images.githubusercontent.com/14248932/77914939-5898d900-729f-11ea-8b67-20a154b261d9.png)

**Comment by brookhutchinson** [comment]
Help me understand why the "ID" Column and the "CompanyName" do get populated with data when the "autoGenerate" property is set to true?

**Comment by brookhutchinson** [comment]
**My goal is to display static columns and dynamic columns in the grid**
1) Column displayed in the correct order (left to right) based on order defined in HTML Template
2) HTML Template should have static columns then dynamic columns
3) Static columns display in grid
4) Static columns are populated with data
5) Dynamic columns display in grid
6) Dynamic columns are populated with data

Using your StackBlitz Example
https://stackblitz.com/edit/angular-xfhtdh

**If I use property binding to set "autoGenerate" to false then**
1) All columns display in correct order (left to right) based on how defined in HTML Template
2) Dynamic columns display
3) Dynamic columns are not populated with data
4) Static columns display
5) Static columns are populated with data

**If I use property binding to set "autoGenerate" to true then**
1) Only static columns display
2) Static columns display
3) Static columns are populated with data
4) Dynamic columns do not display as columns in the grid
5) Dynamic columns are not populated

**Comment by hanastasov** [comment]
> **My goal is to display static columns and dynamic columns in the grid**
> 
> 1. Column displayed in the correct order (left to right) based on order defined in HTML Template
> 2. HTML Template should have static columns then dynamic columns
> 3. Static columns display in grid
> 4. Static columns are populated with data
> 5. Dynamic columns display in grid
> 6. Dynamic columns are populated with data
> 
> Using your StackBlitz Example
> https://stackblitz.com/edit/angular-xfhtdh
> 
> **If I use property binding to set "autoGenerate" to false then**
> 
> 1. All columns display in correct order (left to right) based on how defined in HTML Template
> 2. Static columns display
> 3. Static columns are populated with data
> 4. Dynamic columns display
> 5. Dynamic columns are not populated with data
> 
> **If I use property binding to set "autoGenerate" to true then**
> 
> 1. Only static columns display
> 2. Static columns display
> 3. Static columns are populated with data
> 4. Dynamic columns do not display as columns in the grid
> 5. Dynamic columns are not populated

When `autoGenerate` is true, the grid will auto create columns based on the data source. All other columns, that are declared as follows:
```
        <!-- Dynamic columns, created in code  -->
        <igx-column *ngFor="let c of columns" [field]="c.field" [dataType]="c.type"></igx-column>

        <!-- Static columns  -->
        <igx-column [field]="'Category'" dataType="number"></igx-column>
```
will NOT BE taken into account, and will not be rendered in the grid.

**Comment by brookhutchinson** [comment]
My grid has both autoGenerated columns and non-autoGenerated columns.

How do I get all of the columns to both display in the grid and show data for each column?

**If I use property binding to set "autoGenerate" to false then**

All columns display in correct order (left to right) based on how defined in HTML Template
Static columns display
Static columns are populated with data
Dynamic columns display
Dynamic columns are not populated with data

**Comment by hanastasov** [comment]
>My grid has both autoGenerated columns and non-autoGenerated columns.
> 
> How do I get all of the columns to both display in the grid and show data for each column?
Hi @brookhutchinson , I answered this question couple of times already. Please let me know if my response does not make any sense. When **`autoGenerate` is true**, the grid will render **ONLY** the autogenerated columns.

Previous Responses:
![responses](https://user-images.githubusercontent.com/14248932/77997306-d6102800-7337-11ea-9895-2c307524c831.png)

**Comment by brookhutchinson** [comment]
Thank you for your answers, but I do not think that you are understanding my question or maybe I am not asking the question correctly.  Your last post mentions when "autoGenerate" is set to true. My last post is asking about when "autoGenerate" is false.

My goal is to display both autoGenerated columns and Non-autoGenerated columns in the same grid. Note that the worked as expected when using Angular 8/igniteui-angular 8 by setting the "autoGenerate" property to false. After upgrading to Angular 9/igniteui-angular this no longer works as expected.

Here is my last post...
My grid has both autoGenerated columns and non-autoGenerated columns.

How do I get all of the columns to both display in the grid and show data for each column?

If I use property binding to set "autoGenerate" to false then

All columns display in correct order (left to right) based on how defined in HTML Template
Static columns display
Static columns are populated with data
Dynamic columns display
Dynamic columns are not populated with data

**Comment by hanastasov** [comment]
> **Here is my last post...**
> My grid has both autoGenerated columns and non-autoGenerated columns.
> 
> How do I get all of the columns to both display in the grid and show data for each column?
> 
> **If I use property binding to set "autoGenerate" to false then**
> 
When **`autoGenerate`** is **false**, you **CAN NOT** have autogenerated columns. This behavior is by design and is same in all versions. If you believe this is not true, please provide a sample with version 8, where **`autoGenerate`** is set to **false** and there are autogenerated columns in the grid.

**Comment by hanastasov** [comment]
@brookhutchinson , In order to clarify the discussion, I was rereading it over and over again. I guess we got lost in the definiton of "dynamic columns", which may result in us talking about different things.

My sample refers to "dynamic columns" to the column created in code, but in discussion here "dynamic columns" sometimes refer to the autogenerated columns.

**Let me clear it out:**
There are two types of columns in the grid - 1) autogenerated and 2) defined by developer. Depending on the `autoGenerate` property, the grid will display just one of those two types of columns. If `autoGenerate` is true, grid will display autogenerated columns only. If `autoGenerate` is false, the grid will display the columns defined by the developer only.

Does the above make sense now ?

**Comment by brookhutchinson** [comment]
I understand your definition of autoGenerated columns. I understand your definition of Non autoGenerated columns.

*I need to have both autoGenerated columns and Non autoGenerated columns in the same grid.

This worked when using angular 8/igniteui-angular 8

After updating to angular 9/igniteui-angular 9, this no longer works as expected. Setting "autoGenerate" to false.

How can I do this after updating to angular 9/ignite 9 ?

This is a blocker.  Why would the behavior of the grid be changed and not clearly documented as a "major" breaking change?

Very much need your help here.

**Comment by hanastasov** [comment]
@brookhutchinson  with respect to your statement, but it is not possible that you had both autogenerated and non autogenerated columns in the grid. Here is an example with version 8: https://stackblitz.com/edit/angular-cscspe-zi8gqc

This behavior is by design and has been the same across all versions. I consider the issue closed now. If you make up a sample in version 8 that has both autogenerated and nonautogenerated columns, please open a new ticket and attach the sample as reference.
