### ISSUE TITLE
Radial Pie Chart: Add "seriesPointer" events

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#6689]
## Is your feature request related to a problem? Please describe.
Currently it seems there's no way to know if the user clic's inside the chart, the event can be usefull for dashboards design, they'll can be used as filters to reload specific data related to the selected one.

## Describe the solution you'd like
I'll like to see those events exposed like is already is done for IgxCategoryChartComponent [here](https://www.infragistics.com/products/ignite-ui-angular/api/docs/typescript/latest/classes/igxcategorychartcomponent.html#seriespointerdown).

## Describe alternatives you've considered
Currently i think i may switch to IgxCategoryChartComponent, however that'll imply some design limitations, because XY axis it'll nedd to fit.

## Additional context
![image](https://user-images.githubusercontent.com/29953012/74387736-f7847700-4dbe-11ea-9444-a23b1871216b.png)

**Comment by zdrawku** [comment]
Issue moved to [IgniteUI/igniteui-angular-charts #31](https://github.com/IgniteUI/igniteui-angular-charts/issues/31) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zdrawku** [comment]
hey @luiscla27 the right place for chart issues [is this repository](https://github.com/IgniteUI/igniteui-angular-charts/issues/31), and it has been moved accordingly.
