### ISSUE TITLE
Migrating from 8 to 9 breaks projects using some enums

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#6698]
## Description  
Migrating from 8 to 9 causes breaking change in enumerations. There's no information in the upgrade guide about this and the change is not migrated.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update_guide.html#from-8xx-to-90x

 * igniteui-angular version: 9.0.0
 * browser: N/A

## Steps to reproduce  

1. Open a project using igniteui-angular 8.x
2. Migrate to 9

## Result  
Enums like 'IgxProgressType.DANGER' are broken.

## Expected result  
Either this should be migrated, or it should be documented.

**Comment by simeonoff** [comment]
Closing as this is resolved via documentation update https://github.com/IgniteUI/igniteui-docfx/pull/1784
