### ISSUE TITLE
Overlay service does not clear scroll strategy ids on hide 

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular#6705]
## Description  
The AbsoluteScrollStrategy always attaches the overlay element on the first attached element.

 * igniteui-angular version:  9.0.0
 * browser: chrome

## Steps to reproduce  
Open this [Stackblitz sample](https://stackblitz.com/edit/angular-ypcslh)
Click on the spans to attach the card.
Then scroll
## Result  
on scroll  the card always attaches on the first attached element.

## Expected result  
on scroll event the card must not be reattached.

**Comment by wnvko** [comment]
In the sample overlay reuses same position strategy. In order to override the target of the position strategy you should create a new position strategy.
