### ISSUE TITLE
Filter UI does not render correctly on right-most columns

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#672]
### Description  
Filter Dialog UI is hidden from view when near right scroll area.  

### Steps to reproduce  

Add filter option, attempt to trigger filter on right-most column(s):

![filterui-renderissue](https://user-images.githubusercontent.com/18453092/36704733-fcf1088c-1ba4-11e8-9102-bd7acf7d8ba6.png)

### Result  
Filter UI does no render

### Expected result  
Filter UI should render either over the grid area, or render left to right.

### Attachments  
Screenshot attached.

**Comment by rkaraivanov** [comment]
Can you provide a sample? I can't seem to reproduce this behavior.

**Comment by SlavUI** [comment]
@jberes  Hi Jason can you test again most likely you checked it before we pushed the new samples to Prod this morning :)

**Comment by kdinev** [comment]
This has been fixed in 5.2.0.

**Comment by SlavUI** [comment]
This issue is resolved
