### ISSUE TITLE
How to make IgxColumnComponent.autosize() work?

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6729]
## Question
I have an `igx-grid` with 7-9 `igx-column`s.

I want the columns to dynamically adapt to the length of their content.
One way I tried is to use widths with percentages, but that does not work, since I cannot predict the individual column lengths.

So I tried this.

After the data is loaded, this code is run:

```typescript
    this.grid.columnList.forEach((col: IgxColumnComponent) => col.autosize());
```
Could it be that I call it at the wrong moment ?

 * igniteui-angular version: 9.0.1
 * browser: Chrome latest, Firefox latest

This is a screen shot

![image](https://user-images.githubusercontent.com/150055/74510035-2b68b500-4f03-11ea-81e1-4c53b7c1ff2f.png)

In particular, notice the second line, where the **Status** `VALIDATION_ERROR` flows into the **Canton** column.
The **Date** values are ellipsed ("12.02.2...") instead of fully shown: "12.02.2020".

The **Title** column texts are the worst, crammed into a post-stamp size cell.
Also, the **Seat** experiences the same abuse, with the ZIP code and town rendered on disparate lines.

And why is only 40% of the width used, despite of `igx-grid` having
```html
[width]="'100%'"
```
???

Any hints are highly appreciated.

Thanks.

**Comment by ddincheva** [comment]
Hello @catull ,
I investigate your use case and I think that you call autosize method very early,  try call the method on AfterViewInit. Take a look at [this example](https://stackblitz.com/edit/angular-s3tutq-crbuev) and see if this fulfill your use case. Also notice If you have cell templates you need to apply some custom styling.
If you need further assistance, we will be happy to help.

**Comment by catull** [comment]
Your example is a toy, i.e. the data is fetched locally, no service is called.
The data is immediately available.
You only show that if you have local data, it could work.

In my code, an asynch call is made in `ngOnInit()`.
It only fetches 15-25 records, they are instantly rendered/

In `ngAfterViewInit()` I do exactly what your example does, to the letter.

However, the effect is that the columns are not auto-sized, but evenly spaced (which is the default).
This is because I do not specify any widths, on purpose.

Is there not a way to specify `flex`y widths, instead of pixels or percentages ?

**Comment by ddincheva** [comment]
Hello @catull ,
In order to be able to provide you more relevant support please describe your use case as much clear and in details as possible. Please check this [sample](https://stackblitz.com/edit/angular-ampzhu) which show how to use autosize functionality in grid with remote data.

**Comment by catull** [comment]
By the way, as some many of the examples, inspecting the one mentioned in this issue, it does not even run.

The blue semi-circle spins and spins.

This is after 2 mins:

![image](https://user-images.githubusercontent.com/150055/75031968-bae40a00-54a7-11ea-8b80-546d8dfd7e73.png)

Exporting the whole project, and trying to build it locally, it does not even `build` or `serve`.
The dependencies are way off.

There are hundreds of errors.

**Comment by catull** [comment]
The second example (remote service call), spins and spins.

I have tried it with different browsers under Linux.
Same result.

**Comment by catull** [comment]
Btw, why do you call `autosize()` in two different code paths, in the second example ?

**Comment by pipeng119** [comment]
> 你好@catull, 为了能够为您提供更多相关支持，请尽可能清晰详细地描述您的用例。请查看此[示例](https://stackblitz.com/edit/angular-ampzhu)，该示例显示如何在具有远程数据的网格中使用自动调整大小功能。



> Hello @catull , In order to be able to provide you more relevant support please describe your use case as much clear and in details as possible. Please check this [sample](https://stackblitz.com/edit/angular-ampzhu) which show how to use autosize functionality in grid with remote data.

This reference link reported a lot of errors, is there any new reference link to provide?
