### ISSUE TITLE
Cannot launch column filter UI when 2 adjacent columns have sorting UI enabled

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#673]
### Description  
It is impossible to launch the Filter UI when 2 adjacent columns are sorted.

### Steps to reproduce  

Load grid with data, sort 2 columns that are next to each other by clicking header, and attempt to launch Filter UI.

### Result  
Cannot select Filter UI glyph in column header

![filterui-sortcolumn-issue](https://user-images.githubusercontent.com/18453092/36704947-0f3d10b6-1ba6-11e8-87dd-f5e9b90b6d3e.gif)

### Expected result  
Filter UI glyph should be selected

### Attachments  
Recording attached

**Comment by hanastasov** [comment]
Cannot reproduce the issue with latest dev, attaching sample.
