### ISSUE TITLE
Toggling any templates in grid by using *ngIf  on two or more levels results in empty columnList if columns are autogenerated.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#6731]
## Description  
Having two or more nested row islands with ngIf applied for toggling runtime and toggling the top one results in empty columnList collection only on Ivy.

 * igniteui-angular version: 9.0.x
 * browser: any

## Steps to reproduce  

1. Open the "Hierarchical Grid" demo
2. Set on both row islands ngIf bound to a variable
3. Toggle the top row island runtime

## Result  
The grid is empty due to the columnList getting empty during change detection.

## Expected result  
The rows should remain, only the expand/collapse column should disappear.

## Attachments  
![ToggleRowIsland](https://user-images.githubusercontent.com/3768136/74516109-7b05ab80-4f18-11ea-856a-558134a9f50d.jpg)

**Comment by MayaKirova** [comment]
Does not seem to be related to the HierarchicalGrid. Happens in any grid that has any type of nested conditional template and autogenerated columns, for example:

    <igx-grid [data]="localData" [autoGenerate]="true" [height]="'600px'" [width]="'800px'">
        <div *ngIf='!riToggle'>
            <div *ngIf='!riToggleChild'></div>
        </div>
    </igx-grid>
