### ISSUE TITLE
igx-select items container has horizontal scrollbar

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#6734]
## Description  
Select drop down now has horizontal scrollbar.

 * igniteui-angular version: 9.0.0
 * browser: All

## Steps to reproduce  

1. Define a select
e.g.
```html
<igx-select class="slot-select" [(ngModel)]="slot.match.Team1Id" [disabled]="!slot.inEdit">
  <label igxLabel>Отбор 1</label>
  <igx-select-item *ngFor="let registration of registrations"
                    [value]="registration.TeamId"
                    [text]="registration.Team.TeamName">
    <igx-avatar [src]="registration.Team.TeamAvatar" [initials]="registration.Team.TeamName"></igx-avatar>
    {{ registration.Team.TeamName }}
  </igx-select-item>
</igx-select>
```
2. Open it 

## Result  
The select drop down has a horizontal scrollbar.

## Expected result  
The select drop down should be content-box in terms of width.

**Comment by IvayloG** [comment]
Resolved in https://github.com/IgniteUI/igniteui-angular/issues/6733
