### ISSUE TITLE
Filter UI Font should match grid font & styles

### ISSUE THREAD

**Issue by jberes** [IgniteUI/igniteui-angular#674]
### Description  
The Filter UI drop down has a different font, style than the Grid

### Steps to reproduce  

Observe font / style of Filter UI drop down vs. the Grid font & styles

### Result  
Filter UI looks odd / out of place w/ style of Grid
![filterui-fontissue](https://user-images.githubusercontent.com/18453092/36705084-be39345a-1ba6-11e8-8edc-6a4f33c04a1a.png)

### Expected result  
What is the expected result after following the steps to reproduce?

### Attachments  
Image attached.

**Comment by kdinev** [comment]
@jberes Which sample are you looking at. I just opened the awesome grid sample and this is what I see:

![image](https://user-images.githubusercontent.com/1472513/36733642-e5b80a96-1bd9-11e8-8ec3-99ec066a08d0.png)

**Comment by SlavUI** [comment]
@kdinev he is looking at the Samples Grid with the Virtualization :)

**Comment by kdinev** [comment]
@SlavUI Even so, the fonts are the same regardless of the sample.
![image](https://user-images.githubusercontent.com/1472513/36808783-c2401cca-1cce-11e8-8ffc-e68dcf986e53.png)

**Comment by simeonoff** [comment]
@jberes Does that mean you want the standard button and input sizes to vary? To me this seems illogical and wrong. Not to mention a developer can template the cells however they want, setting any font size to any column cell. Which should be the "master" cell to inherit the font size from?

**Comment by kdinev** [comment]
@simeonoff He's pointing out that the fonts don't match, not the sizes.

**Comment by simeonoff** [comment]
@kdinev Well in that case, providing a screenshot of the computed styles in the developer tools would be much more helpful. One thing I can see in the screenshot is the sample is not even using Titillium Web, which leads me to believe fonts are missing in the app.

**Comment by kdinev** [comment]
Closing this, as it's an issue with missing theme imports in the sample.
