### ISSUE TITLE
Position IgxDialogComponent absolute

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6744]
## Question  
I wold like to position an IgxDialogComponent in an absolute position 10px from the top of the page and 5px from the right side of the page.  I would like to use OverlaySettings, PositionSettings, and CSS "top" property: 10px and CSS "right" property 5px to position the IgxDialogComponent.

How can I position an IgxDialogComponent in an absolute position 10px from the top of the page and 5px from the right of the page?

 * igniteui-angular version: 8.2.18
 * browser: Google Chrome (latest)

**Comment by zdrawku** [comment]
You can set custom `overlaySettings` to the `open` method of the Dialog. Check out our [documentation ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/dialog.html#configure-different-position-and-animation-settings)for more information and [this sample](https://stackblitz.com/edit/angular-dialog-with-custom-position?file=src%2Fapp%2Fcustom-dialog%2Fcustom-dialog.component.ts).

As you can see the `target` property of the position settings is `Point` which represents how the Dialog will be positioned (20 px vertically and 20 px horizontally from that point).

```
  public positionSettings: PositionSettings = {
      openAnimation: useAnimation(slideInTop, { params: { duration: '2000ms' } }),
      closeAnimation: useAnimation(slideOutBottom, { params: { duration: '2000ms'} }),
      horizontalDirection: HorizontalAlignment.Right,
      verticalDirection: VerticalAlignment.Bottom,
      target: new Point(20, 20),
      minSize: { height: 100, width: 100 }
  };

  public overlaySettings: OverlaySettings = {
    positionStrategy: new ConnectedPositioningStrategy(this.positionSettings),
    scrollStrategy: new NoOpScrollStrategy(),
    modal: true,
    closeOnOutsideClick: true
  };

```
