### ISSUE TITLE
Get the clicked cell from row selection

### ISSUE THREAD

**Issue by sddania** [IgniteUI/igniteui-angular#6748]
## Is your feature request related to a problem? Please describe.

I have a grid which implemented multi-row selection and could have 2 behaviors.
When you click on the row, the row selection event should show a modal with a detail of the row.
Instead when you click on the checkbox on the left, the modal detail will not open the modal detail.
This is because you should do some other bulk actions on the selected rows with other buttons on the top toolbar

## Describe the solution you'd like

now on the payload of the selection event of the IRowSelectionEventArgs row I can't know which cell has been selected from the grid. The selected cell should be inserted on the event payload.

**Comment by ddincheva** [comment]
Hello @sddania ,
Cell selection and row selection work independently in IgxGrid. The onRowSelectionChange event as you have seen emits IRowSelectionEventArgs which give you access to the original MouseEvent from which you can extract the event target. So in this way you can perform any custom logic that is going to fulfill your use case. Also the IgxGrid Public API gives you the selected cells. Please take a look at [the example](https://stackblitz.com/edit/angular-grid-cell-and-row-selection-mgmebj) that I have managed to build. 
If you have any additional question we will be happy to help.

**Comment by sddania** [comment]
Thanks you so much!
