### ISSUE TITLE
Date picker applies non-date mask when dropdown mode is set after init

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#6749]
## Description
When the `mode` option is changed to `dropdown` after control init, the picker applies a mask that's not a date (the `igxMask` default)

 * igniteui-angular version: 9.0.x
 * browser: N/A

## Steps to reproduce  

1. Open https://stackblitz.com/edit/datepicker-mode-switch
2. Change the mode from the select
3. Focus the input

## Result  
The editor displays the date correctly as "5/15/19", but when you focus there's no value and the placeholder shows the underlying mask as "CCCCCCC..":
![image](https://user-images.githubusercontent.com/3198469/74653723-70098000-5191-11ea-8b50-29df2bac8e72.png)

Also if you clear the editor and focus again, the picker throws a parsing error:

![image](https://user-images.githubusercontent.com/3198469/74652769-739c0780-518f-11ea-95b7-b8e6489c6918.png)

## Expected result  
The editor should work the same as if `mode="dropdown"` has been assigned intially, formatting the date as "_5/15/2019" when focused and display an empty mask (`__/__/____`) for cleared.

**Comment by jackofdiamond5** [comment]
The issue will be tackled in https://github.com/IgniteUI/igniteui-angular/issues/6483
