### ISSUE TITLE
Active cell border moves to difference cell

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#6756]
## Description  
Active cell border moves to difference cell when igxFocus is applied to the cell edit template.

 * igniteui-angular version: 9.0.1
 * browser: IE11

## Steps to reproduce  

1. Run the attached sample
2. Start editing on either 'id' column or 'name' column
3. While the cell is in edit mode, scroll quickly several times

## Result  
Active cell border moves to other cell.

## Expected result  
Active cell border stays at the cell which is in edit mode.

## Note
Active cell keeps moving while scroll is performed on vertical scroll bar. If scroll is performed on the grid cell, active cell is reset.

## Attachments  
![IgxGrid_Cell_Active_Color](https://user-images.githubusercontent.com/14340675/74713133-3ad16080-526b-11ea-927a-c70d0a6fceae.gif)
[igx-grid-active-cell-color.zip](https://github.com/IgniteUI/igniteui-angular/files/4217881/igx-grid-active-cell-color.zip)

**Comment by ymita** [comment]
If a workaround is available, would you share it please?

**Comment by ddincheva** [comment]
Hello @ymita ,
When you have custom cell template you should handle some logic and operations manually. One possible workaround  for the described scenario is to bind the IgxFocus directive to cell.focused property or to implement custom logic and set focus to the input in the cell editing template only when the cell is fully visible. 
`    
    <ng-template igxCellEditor let-cell="cell" let-value>
      <igx-input-group>
        <input igxInput type="text" [(ngModel)]='cell.editValue' [igxFocus]="cell.focused" />
      </igx-input-group>
    </ng-template>
`

**Comment by ymita** [comment]
@ddincheva 
Thank you for the solution. I see how to use it in this case. This is very helpful.
