### ISSUE TITLE
igx-tabs tabsType is not migrated correctly

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#6764]
## Description  
I have an `igx-tabs` with `tabsType="'fixed'"` in the template. The template is not migrated to `type="'fixed'"`.

 * igniteui-angular version: 9.0.1
 * browser: N/A

## Steps to reproduce  

1. Define tabs with `tabsType` in a v8 project.
2. Migrate it to v9

## Result  
The input is not migrated.

## Expected result  
The input should be migrated.

**Comment by IvayloG** [comment]
@kdinev I am closing this as not reproducible.
