### ISSUE TITLE
Research: Lint check for wrong code comment format

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#6785]
## Description  
This is important when it comes to API docs export for localization. We should spend some time to research how to limit format errors that can cause the export procedure to fail

**Comment by Aleksandyr** [comment]
Unfortunately, there is not enough strict rule (a combination of rules) that would keep us from bad comment formating. Basically our main problems are with whitespaces and indentions. I couldn't manage to find any rule that sets a strict number of spaces or whitespaces per every line.
