### ISSUE TITLE
Cell edit value incorrect when tabbed into after data input has changed

### ISSUE THREAD

**Issue by Craftwarez** [IgniteUI/igniteui-angular#6793]
## Description  
When you tab into the next cell and change the input data. The cell edit value remains as the previous value instead of the newly changed value. It reloads to the correct value once you tab off it again. It seems this issue ([5763](https://github.com/IgniteUI/igniteui-angular/issues/5763)) is quite similar and is resolved, but I cannot seem to get it working when we directly change the row data

 * igniteui-angular version: 8.2.x, 9.0.x
 * browser:  Chrome 80.0.3987.116 

## Steps to reproduce  

1. Type a number into the Number Test 1 on rowId 1
2. Tab into the next cell.
3. Tab off the cell (or shift tab) and it goes to the new value.

## Result  
What is the actual result after following the steps to reproduce?
Cell edit value is the old value.
## Expected result  
What is the expected result after following the steps to reproduce?
Cell edit value should be the new value (numberTest1 value + 10 in the example)

## Stackblitz link
https://stackblitz.com/edit/angular-v779oe

**Comment by ddincheva** [comment]
Hello @Craftwarez ,
I investigated the problem that you describe and what I could notice from you sample is that you directly update the data which is bind to the grid which is not the correct way to operate with the grid. When onCellEdit event is emitted the new value is still not saved in the grid data source which gives you the ability to validate the edit value or to cancel the cell editing. Also please notice that when the event is emitted this.data[0].numberTest1 is the old cell value /the value that is currently in your data source/. What I can suggest you is to use the emitted edit arguments and to use the provided public [grid API](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#updatecell). Please take a look at the [sample](https://stackblitz.com/edit/angular-36a41c).
