### ISSUE TITLE
Excel style filtering sample - not visualized correctly 

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#6815]
## Description  
Here https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel_style_filtering.html#configure-menu-features
 on the second sample, the ESF is not visualized correctly 

## Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel_style_filtering.html#configure-menu-features
2. Scroll to the ESF sample above
3. Check all ESF for all columns

## Result  
<img width="1440" alt="Screen Shot 2020-02-25 at 11 56 59 AM" src="https://user-images.githubusercontent.com/41998471/75236989-48389e80-57c7-11ea-929c-198c645149c3.png">

**Comment by DiyanDimitrov** [comment]
@DaniMarinov @StefanIvanov, could you guys propose a new design for this sample? The idea is to demonstrate the option to re-template the ESF parts. One of the most common usage of this re-templating is to hide the non-filtering options from the ESF so maybe such sample would be appropriate.

**Comment by DaniMarinov** [comment]
@DiyanDimitrov Ok, I will prepare a design for the sample.
