### ISSUE TITLE
igx-hierarchical grid - hasChildrenKey doesn't block expansion of parent rows without children

### ISSUE THREAD

**Issue by SaranyDwarampudi** [IgniteUI/igniteui-angular#6816]
I want to disable expand button when there is no data in the row-island table in igx-hierarchical grid

**Comment by ChronosSF** [comment]
Hey @SaranyDwarampudi ,

This behavior is controlled through the `hasChildrenKey` input. You may specify a key in your data records that the grid will check and if its value is false, it will not display the chevron that allows expansion. If your backend doesn't serve the records with such a property, you may also add it through your application's data service feeding data to the grid.

```html
<igx-hierarchical-grid [data]="localData" [hasChildrenKey]="'hasChild'">
</igx-hierarchical-grid>
```
```typescript
const localData = [
...
{ id: 'someId', hasChild: false }
...
]
```

**Comment by SaranyDwarampudi** [comment]
![grid](https://user-images.githubusercontent.com/61456539/76677863-334a7080-65f9-11ea-8b27-2a00a773141f.JPG)
Thanks for the solution.
The solution was working well in local machine. But in the hosted machine although we do no see the arrow, we are able to click the empty cell and it shows the table with no stores.
Please look into the attachment.

**Comment by ChronosSF** [comment]
Sorry, there seems to be a regression in the last few versions that prevent this from functioning as intended. We'll plan it with high priority and try to release a fix with next monday's patch.

**Comment by SaranyDwarampudi** [comment]
It is not working on higher versions of typescript and angular cli. i have downgraded them  and its working fine now.Please fix it so that i can upgrade typescript
