### ISSUE TITLE
How to add custom text to Hide Button and Pin Button above IgxGrid

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6824]
### Description  
Buttons that display above an IgxGrid dynamically get created at runtime. Buttons that I am referring to are the Show/Hide columns button and the pinned columns button.

How can I add custom text for the Show/Hide Button?

How can I add custom text for the pinned columns button?

 * igniteui-angular version: 8.2.4
 * browser: Google Chrome

### Steps to reproduce  

1. Define IgxGridComponent inside HTML Template
2. Define id of grid to "grid"
3. Set this.grid.columnHiding = true
4. Set this.grid.columnPinning = true
5. Hide button displays above grid (top right)
6. Pinning column displays above grid (top right)

### Result  
What is the actual result after following the steps to reproduce?
Two buttons display above grid with an icon displaying inside each button

### Expected result  
What is the expected result after following the steps to reproduce?
Two buttons display above grid with custom text and an icon.
Example of buttons showing custom text and icon
"Show/Hide" (and icon) Button
"Pin/Unpin" (and icon) Button

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by DiyanDimitrov** [comment]
Hello @brookhutchinson,

You are not able to re-template the built-in buttons in the toolbar, but you could use the [igxToolbarCustomContent](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/toolbar.html#custom-content-template) directive and add your own buttons. Here is a stackblitz sample https://stackblitz.com/edit/angular-soz8a4.
