### ISSUE TITLE
Document is missing for Dock Manager

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#6825]
## Description  
It seems documentation & sample is missing for Dock Manager component.  I checked below URL & not found anything - 
https://github.com/IgniteUI/igniteui-angular
https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/getting_started.html

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
Provide detail documentation & samples for Dock Manager. 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
@deepakvia We don't have a dock manager component in Ignite UI for Angular.
