### ISSUE TITLE
Docs: igxFlexOrder is missing in igxLayoutDirective typedoc

### ISSUE THREAD

**Issue by didimmova** [IgniteUI/igniteui-angular#6830]
## Description  
`igxFlexOrder` property is missing from igxLayoutDirective documentation in typedoc.

## Attachments  
https://www.infragistics.com//angular-docs/typescript/latest/classes/igxlayoutdirective.html

**Comment by simeonoff** [comment]
This property is not set on the `igxLayoutDirective`. It's set on the `igxFlex` directive and it's [documented](https://www.infragistics.com//angular-docs/typescript/latest/classes/igxflexdirective.html#order) there.
