### ISSUE TITLE
Input field mask

### ISSUE THREAD

**Issue by EvgeniyZhukovets** [IgniteUI/igniteui-angular#6832]
## Description  
When user use autofill to the input field with the with the igxMask, e.g. `<input type="text" igxInput name="phone" required [igxMask]="'(000) 000-0000'"/>` data will be inserted incorrectly.

 * igniteui-angular version: 9.0.1
 * browser: Google Chrome, Safari

## Steps to reproduce  

1. Create an input field with igxMask
E.g. (000) 000-0000
2. Open page with this input field
3. Fill this field with the value
E.g. 7703296393
3. Save this field in the browser memory to use this field with autofill
4. Reopen page
5. Use autofill to insert saved value to this field

## Result  
<img width="303" alt="image" src="https://user-images.githubusercontent.com/22504733/75349565-17836280-58b6-11ea-9088-4506861986da.png">

## Expected result  
<img width="174" alt="image" src="https://user-images.githubusercontent.com/22504733/75349711-5e715800-58b6-11ea-8adb-818970147bc4.png">

**Comment by jackofdiamond5** [comment]
Hi @EvgeniyZhukovets,

We are currently refactoring our `IgxMaskDirective` https://github.com/IgniteUI/igniteui-angular/issues/6454 and the issue that you are describing has been looked into. The new mask will be available in our `9.1` release.

We remain open for any additional comments or questions that you might have.
