### ISSUE TITLE
Errors are thrown when scrolling the grid with touch interaction

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#6835]
## Description  
Errors are thrown when scrolling the grid with touch interaction.

 * igniteui-angular version: 9.0
 * browser: NA

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live_data.html or https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/live_data.html sample.
2. Collapse some rows.
3. Scroll using touch interaction.

## Result  
Errors are thrown:
- Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
- ERROR TypeError: Cannot read property 'context' of undefined

## Expected result  
No exceptions should be thrown.

**Comment by ChronosSF** [comment]
This is best fixed with the changes in KBD that will cause cells to not receive focus.

**Comment by dkamburov** [comment]
This is fixed with https://github.com/IgniteUI/igniteui-angular/pull/6910
