### ISSUE TITLE
Sometimes combobox incorrect calculates position for dropdown with items

### ISSUE THREAD

**Issue by EvgeniyZhukovets** [IgniteUI/igniteui-angular#6842]
## Description  
Sometimes Combobox incorrect calculates position for dropdown with items.
Mostly it happens when selected values (multiple select is on) located at the beginning of the list and end of the list.  After press 2-3 times on up/down arrow buttons, it refreshes it correctly and everything works fine. Is it anyway how to call this recalculation as a workaround for this?

 * igniteui-angular version: 9.0.1
 * browser: 

## Steps to reproduce  

1. Create igxCombo with components (We have nearly 100 components)
E.g. we have such combo: 
```
<igx-combo #comboComponent #comboComponentModel="ngModel" 
                 [data]="states$ | async" valueKey="id" displayKey="name"
                 [(ngModel)]="providerProfile.state" name="history" required>
</igx-combo>
```
2. Pick first two and last two checkboxes
3. Save data to a database on your back-end
4. Reload page
5. Checkboxes have to be set with saved data

## Result  
![Снимок экрана 2020-02-27 в 16 34 30](https://user-images.githubusercontent.com/22504733/75451563-d22c6700-5981-11ea-84ac-1e9e85ad01ad.jpeg)

## Expected result  
![Снимок экрана 2020-02-27 в 16 43 31](https://user-images.githubusercontent.com/22504733/75451542-c771d200-5981-11ea-9d9a-2ec3fe8800f6.jpeg)

**Comment by EvgeniyZhukovets** [comment]
Will this bug be fixed?

**Comment by Lipata** [comment]
Hi, @EvgeniyZhukovets yes it will be fixed. This label is a reminder for us to prioritize it.

**Comment by ViktorSlavov** [comment]
@EvgeniyZhukovets 
I've tried to replicate the issue you're experiencing with a stub service but couldn't. Could you please take a look at this [CodeSandbox Sample](https://codesandbox.io/s/condescending-hofstadter-cbhlf?file=/src/app/app-routing.module.ts) and alter it so it reproduces the behavior you're experiencing? That would be of great help!

The list is positioned relative to the combo and it's scroll is restored to the previous position (so if it's a freshly reloaded page, that shouldn't be an issue). One thing that _might_ be messing the whole scenario up is if your selected items are received before all of the combo's data items are received. Are you loading the items by chunks? Or you could throttle the combo's `onOpening` event until the `data` input is properly received?

Again, a reproducible sample would be of great help, as we haven't faced such an issue with this control previously.

Thanks!
