### ISSUE TITLE
[igx-date-picker] Add UI style to required date picker in form (asterisk)

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6846]
## Is your feature request related to a problem? Please describe.
All the igx input components have an asterisk added when the input control is required in the form, except for the igx-date-picker.

## Describe the solution you'd like
Add the asterisk (*) to the label of the igx-date-picker

## Describe alternatives you've considered
Currently we're manually editing the label of the date picker

## Additional context
Please also consider the UI changes when this control is invalid.

**Comment by wnvko** [comment]
@mimurawil this is same issue as #6471 
We are currently working on this issue and this should be finished in the current sprint - you can look here #6722

**Comment by mimurawil** [comment]
Hello @wnvko, 

Sorry about that, I didn't notice the #6471 
Thanks for linking it.
