### ISSUE TITLE
Button group text overflow issue

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular#6851]
## Description 
Text overflow issue with the button labels. When there's too much text in the buttons or font size is bigger like when you apply a Bootstrap theme, it should display an ellipsis.

You can look at issue [1760](https://github.com/IgniteUI/igniteui-angular-samples/issues/1760)

## Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/live_data.html
2. Apply a Bootstrap theme
3. Look at the button group above the grid

## Result  
Live All Prices button label is clipped

## Expected result  
It should display an ellipsis

## Attachments  
![74166111-b9584d80-4c2e-11ea-8f68-5959a49cb9f8](https://user-images.githubusercontent.com/15327632/75554601-55fa5800-5a43-11ea-8233-e7e34892d21b.png)

**Comment by DiyanDimitrov** [comment]
@simeonoff, Is this a styling issue? Does it require any dev effort?

**Comment by simeonoff** [comment]
@DiyanDimitrov I don't think it will require any other effort than adding ellipsis.

**Comment by hanastasov** [comment]
Issue is reproducible without adding Bootstrap theme.
