### ISSUE TITLE
Override DragAndDrop Group By Icon

### ISSUE THREAD

**Issue by gianmarcoFerranteProm** [IgniteUI/igniteui-angular#6852]
## Question  
Hello, 
i'm looking for some example or doc link.
I'm trying to override system icons, cause i'm using fontAwesome but i'm not sure about how can i override icons when using Group By grid function.

I mean, i was able to replace RowGroup template using
`<ng-template igxGroupByRow let-groupRow>`

![image](https://user-images.githubusercontent.com/55274139/75558196-bb4d4980-5a41-11ea-83f7-1157d3f636f0.png)

but i dont understand how to change top side of the grid, like the screenshot

![image](https://user-images.githubusercontent.com/55274139/75558162-ae305a80-5a41-11ea-9955-290238d8f282.png)

Any example or link doc about this? I was not able to find anything of official site docs.
Thanks

 * igniteui-angular version: latest

**Comment by gianmarcoFerranteProm** [comment]
Any news? :)

**Comment by skrustev** [comment]
Hello @gianmarcoFerranteProm,

You can repalce the template for that specific group by area from your screenshot by setting [dropAreaTemplate](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#dropareatemplate), which is property of the igxGrid itself.

**Comment by gianmarcoFerranteProm** [comment]
Hello @skrustev,
thank you very much, that worked perfectly!
