### ISSUE TITLE
Sass igx-date-picker-theme function is missing

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#6855]
## Description  
I'm attempting to style a date picker the same way I style a time picker with css-vars. For the time picker, I'm using the [`igx-time-picker-theme` function](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss#L7) listed in the [documentation](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-time-picker-theme). For some reason, the date picker has [no equivalent](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss).

 * igniteui-angular version: 9.0.3
 * browser: N/A

## Steps to reproduce  

1. Try to style a date picker with `$legacy: false`

## Result  
Cannot style the date picker the same way as a time picker.

## Expected result  
Theming should be consistent.

**Comment by simeonoff** [comment]
This is not a bug. The igx-date-picker uses the igx-calendar-theme function to style the wrapped igx-calendar. This is specified in the documentation of the igx-date-picker mixin.
