### ISSUE TITLE
Option to select columns instead of hide columns

### ISSUE THREAD

**Issue by GibletJr** [IgniteUI/igniteui-angular#6858]
To allow a user to control what columns appear in the igx-grid, the _columnHiding_ property must be set to true which presents the default IgxColumnHidingComponent.  Our Engineering team is receiving multiple reports that requiring to check which columns to hide is the complete opposite of the Excel Style Filtering dialog which requires the user to check which data they want to see (attached screenshots).

I have reported the above confusing (and contradicting) UX in Support Ticket [CAS-206171-T2N7N1](https://www.infragistics.com/my-account/support-case/CAS-206171-T2N7N1).

We would like to see the option of reversing the current UX to select which columns to display; not hide.  In the response to the above support ticket, a workaround was provided that does work but solely relies on overriding the default behavior by pulling elements by class names.  This type of implementation has proven to be highly brittle and prone to breaking in subsequent releases as the IGX developers don't have an expectation that custom logic has been implemented using CSS class names.

![image](https://user-images.githubusercontent.com/56270402/75801002-49ba1780-5d2f-11ea-8374-55ed0fd6f200.png)

**Comment by ericmahlberg** [comment]
+1.  Agree it would be nice to have this reversed (or at least configurable)

**Comment by radomirchev** [comment]
@GibletJr , the feature is to be available with the release of Ignite UI 11.0.0
