### ISSUE TITLE
Column hiding breaks grid layout and horizontal scrollbar

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#6865]
## Description  
Hiding and unhiding data makes grid layout and horizontal scrollbar broken

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open dev sample grid auto size
2. Set large data
3. Scroll horizontal scrollbar to the middle
4. From the toolbar click "HIDE ALL"
5. From the toolbar click "SHOW ALL"

## Result  
Observe that the horizontal scrollbar is in the begging but the data is not scrolled to the first column

## Expected result  
The data should start from the first column

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
@mddragnev Might be duplicate of https://github.com/IgniteUI/igniteui-angular/issues/6627
You can check if the fix: https://github.com/IgniteUI/igniteui-angular/issues/6840 resolves this one as well.

**Comment by mddragnev** [comment]
Already fixed by #6840
