### ISSUE TITLE
navigateTo method does not scroll horizontally

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#6871]
## Description  
navigateTo method does not scroll horizontally. This is reproduced with Chrome but not with IE11 or Firefox.

 * igniteui-angular version: 9.0.4
 * browser: Chrome 80.0.3987.132

## Steps to reproduce  

1. Click the button
2. Observe the column 
3. Vertical scroll does not function smoothly
![navigateTo](https://user-images.githubusercontent.com/14340675/76056301-99137880-5fb9-11ea-964c-eaa649f796ad.gif)

## Result  
On step 2, col15 does not come into view.
On step 3, vertical scroll does not function smoothly.

## Expected result  
On step 2, col15 comes into view.
On step 3, vertical scroll functions smoothly.

## Attachments  
[igx-grid-scroll-position2.zip](https://github.com/IgniteUI/igniteui-angular/files/4296665/igx-grid-scroll-position2.zip)

**Comment by ymita** [comment]
The attached sample is taken from https://github.com/IgniteUI/igniteui-angular/issues/5889, and updated to the latest Ignite UI for Angular version.

**Comment by zdrawku** [comment]
Will be fixed with the kb navigation enhancements

**Comment by zdrawku** [comment]
FYI, this is fixed with the latest alpha.6, although it is still reproducible if the screen scale and layout settings are set to 125%:
![image](https://user-images.githubusercontent.com/11193764/79122604-c7e2f280-7da0-11ea-88af-2388a52f41f9.png)
