### ISSUE TITLE
igx-time-picker itemsDelta is documented in accessors but it's settable

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#6891]
## Description  
The `itemsDelta` input of the `igx-time-picker` is documented as accessor, but it's an `@Input()`.

 * igniteui-angular version: 9.0.3
 * browser: N/A

## Steps to reproduce  

1. Open the docs
2. https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtimepickercomponent.html#itemsdelta

## Result  
`itemsDelta` documentation is misleading.

## Expected result  
`itemsDelta` should be documented as an `@Input()`.

**Comment by valadzhov** [comment]
@kdinev itemsDelta is marked as accessor because it has a get and a set method. It needs the set method so that the default values (_itemsDelta = { hours: 1, minutes: 1, seconds: 1, ...value }) will be used when they are not provided.
