### ISSUE TITLE
[IgxGridComponent] Method for entering edit mode?

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6892]
## Question  
Looking at the docs https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html I can see there's a method `endEdit`, but I can't find a method for start editing or toggling edit on a specific cell.

I want to create a new row on the grid and toggle edit mode for better UX.

 * igniteui-angular version: 9.0.1

**Comment by wnvko** [comment]
Having the cell you need to edit you can call [setEditMode](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcellcomponent.html#seteditmode) method over the cell. Additionally to allow editing of the cell you should focus the cell. Finally you may use code like this:

```
const cell: IgxGridCellComponent;
cell.setEditMode(newValue);
cell.focused = true;
```

**Comment by mimurawil** [comment]
Thanks for the help @wnvko.
