### ISSUE TITLE
Excel Style Filtering list is empty when it was previously scrolled down

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#6893]
## Description  
If you open the ESF and scroll down the list items and then open the ESF again, the ESF list is empty.

 * igniteui-angular version: 9.0.x
 * browser: NA

## Steps to reproduce  

1. Open https://ovovykqmved.angular.stackblitz.io (https://stackblitz.com/angular/ovovykqmved)
2. Open the ESF for any column.
3. Scroll down the list items.
4. Open the ESF again.

## Result  
The ESF list is empty.

## Expected result  
The ESF list should be populated.

## Attachments  
![image](https://user-images.githubusercontent.com/43128948/76424565-128fda00-63b1-11ea-8db0-3f8f6c8b7cfd.png)

**Comment by DiyanDimitrov** [comment]
@ChronosSF @MayaKirova 
This seems to be an issue with the IgxForOfDirective which is caching the scrollComponent and its scrollAmount. The ESF dialog is re-created each time on opening so it should not cache the scrolling. 
Could you please take a look at this issue?

**Comment by MayaKirova** [comment]
@DiyanDimitrov If the whole dialog is re-created isn't the igxForOf for that list also re-created? If so its scrollbar will also be re-created and nothing would be cached.
