### ISSUE TITLE
Left most column is not rendered after the grid is re-rendered by switching igxTabs

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#6898]
## Description  
The left most column of the grid is not rendered after the grid is re-rendered by switching igxTabs.

 * igniteui-angular version: 9.0.5
 * browser: IE11, Chrome and Firefox

## Steps to reproduce  

1. Run the sample
2. Scroll to the right end of the grid
3. Select TAB2
4. Select TAB1

## Result  
The left most column is not visible on the grid.

## Expected result  
The left most column is visible on the grid.

## Attachments  
[columnissue.zip](https://github.com/IgniteUI/igniteui-angular/files/4323360/columnissue.zip)
![columnissue](https://user-images.githubusercontent.com/14340675/76507415-1cd4d580-6490-11ea-87ae-20b6cf23dfd2.gif)

**Comment by nrobakova** [comment]
I investigated this issue and this happens when the grid is placed in the ng-content and it is hidden and then shown. The horizontal scroll should be reset as like the vertical scroll.
@skrustev  and @MayaKirova  can you look at this issue?

**Comment by MayaKirova** [comment]
@nrobakova @ymita This sounds very similar to this issue: https://github.com/IgniteUI/igniteui-angular/issues/4884
The same is documented as a limitation:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/for_of.html#known-limitations

**Comment by ymita** [comment]
@MayaKirova Thank you for the information. I am closing this issue.
