### ISSUE TITLE
[igx-select] Disabled select can still be focused and change its value using keyboard

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6908]
## Description  
On a disabled select component, the user can still focus the element and change its value by using keyboard navigation.

 * igniteui-angular version: 9.0.1
 * browser: Chrome Version 80.0.3987.132

## Steps to reproduce  

1. Open the example at https://stackblitz.com/edit/angular-uz9xuz
1.1. Its copied from https://www.infragistics.com/products/ignite-ui-angular/angular/components/select.html#select , I just added the `disabled` property
2. Hit "tab" to see you can focus on the disabled select component
3. Hit "arrow down/up" to see you can change the value of the disabled component

## Result  
What is the actual result after following the steps to reproduce?
The disabled component can be focused and can change its value.

## Expected result  
What is the expected result after following the steps to reproduce?
A disabled component should not change its value.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
n/a

**Comment by radomirchev** [comment]
@mimurawil as the issue is triaged, it is in the draft list for the next sprint.
