### ISSUE TITLE
[IgxGridStateDirective] setState ignores cell templates when rendering UI

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#6922]
## Description  
We're using `[igxGridState]` directive to save the state of the hidden columns, sorting, and filtering. When calling the method `this.state.setState(...)`, the UI discard the `<ng-template igxCell>...</ng-template>` in the HTML template and displays only raw data.

 * igniteui-angular version: 9.0.1
 * browser: Chrome Version 80.0.3987.132

## Steps to reproduce  

1. Open the example at https://stackblitz.com/edit/angular-izczdj and click on the "ARRIVALS" tab item
1.1. If this is the first time opening this link, you'll see the literal "with template:" before each value of the cell
1.2. If it's not the first time opening this link, delete the key `grid1_state` inside the local storage and try again
2. Click on the "DEPARTURES" tab item
3. Click back on the "ARRIVALS" to see the `<ng-template>` was ignored

## Result  
What is the actual result after following the steps to reproduce?
The `<ng-template>` was ignored and the grid is just showing the raw data.

## Expected result  
What is the expected result after following the steps to reproduce?
The grid should keep considering `<ng-template>

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
n/a

**Comment by zdrawku** [comment]
This is a feature request, we can consider adding a TemplateRef persistence for all other templates part of the column reference:
- Cell
- CellHeader
- CellEditor
- CollapsibleIndicator
- FilterCell

We currently persist only the following options, listed in the `IColumnState` interface:

```
export interface IColumnState {
    pinned: boolean;
    sortable: boolean;
    filterable: boolean;
    editable: boolean;
    sortingIgnoreCase: boolean;
    filteringIgnoreCase: boolean;
    headerClasses: string;
    headerGroupClasses: string;
    maxWidth: string;
    groupable: boolean;
    movable: boolean;
    hidden: boolean;
    dataType: DataType;
    hasSummary: boolean;
    field: string;
    width: any;
    header: string;
    resizable: boolean;
    searchable: boolean;
}
```

**Comment by sddania** [comment]
Hi, I would advise you to not store the template on the State directive, but the grid should rerender the column template after the setState.

**Comment by williamverdolini** [comment]
> This is a feature request, we can consider adding a TemplateRef persistence for all other templates part of the column reference:
> 
> * Cell
> * CellHeader
> * CellEditor
> * CollapsibleIndicator
> * FilterCell
> 
> We currently persist only the following options, listed in the `IColumnState` interface:
> 
> ```
> export interface IColumnState {
>     pinned: boolean;
>     sortable: boolean;
>     filterable: boolean;
>     editable: boolean;
>     sortingIgnoreCase: boolean;
>     filteringIgnoreCase: boolean;
>     headerClasses: string;
>     headerGroupClasses: string;
>     maxWidth: string;
>     groupable: boolean;
>     movable: boolean;
>     hidden: boolean;
>     dataType: DataType;
>     hasSummary: boolean;
>     field: string;
>     width: any;
>     header: string;
>     resizable: boolean;
>     searchable: boolean;
> }
> ```

Are you sure this a feature request?? the directive should allow to store and retrieve information of IColumnState, leaving untouched all the rest of grid information, mainly template settings that should not be stored cause it should change over time.

IMHO it's a bug.

**Comment by hanastasov** [comment]
This behavior (when recreate columns through the`IgxGridStateDirective`, a new column list is created, which restores all properties from `IColumnState` interface, meaning templates and others are lost) is By Design and is not a bug.

It was decided that if a developer needs to restore templates too, those templates can be set in the `onColumnInit` event.

**Comment by hanastasov** [comment]
It was decided that if a developer needs to restore templates too (or formatter functions let's say), those templates can be set in the onColumnInit event. The dev needs to query those templates using ViewChild or ViewChildren:
```
  @ViewChild('isActive', { read: TemplateRef, static: true }) public isActiveColumnTemplate: TemplateRef<any>;

public onColumnInit(column: IgxColumnComponent) {
   if (column.field === 'IsActive') {
        column.bodyTemplate = this.isActiveColumnTemplate
   }
}
```
If one needs to do this for many grids out there - you can create a custom directive that extends IgxGridState directive and subscribes to the onColumnInit event for the corresponding grid. This way, you save the burden of having to subscribe to each of the many grids. 

Still, it doesn't prevent the need for the developer to query all columns templates using @ViewChild/@VeiwChildren as demonstrated above.

**Comment by hanastasov** [comment]
> setState ignores the cell templates which has added many conditions.
> 
> Example below:
> 
> <igx-column [hidden]="isSmallScreen()" [dataType]="'string'" field="lifecycle" header="lifecycle" >
> <ng-template igxCell let-cell="cell" #isActive>
> 
> {{ cell.value | titlecase }}
> 
> <div *ngFor="let option of cell.rowData.options" class="details-value" fxLayout="row"
> fxLayoutAlign="space-between start">
> 
> 
> {{ option.name }} - {{ option.versionName }}
> {{ option.processStatusName | processStatus | translate}}
> 
> 
> {{ option.price | currency:'EUR' }}
> 
> 
> In the above example ignoring the template which has *for condition applies.

That is expected behavior - the state directive does not support templates. In my previous post I have explained how to handle templates.
