### ISSUE TITLE
Filtering a number column by "equals" returns wrong data

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#693]
1) Run the sample (npm install, ng serve)
2) Filter the Downloads column by value 100 and filter condition Equals (the default one)

Results:
Two records are returned, having values 100 and 1000. It seems filtering is done on "contains" filtering condition rather than on "equals"

[igxgrid.zip](https://github.com/IgniteUI/igniteui-angular/files/1770605/igxgrid.zip)

**Comment by SlavUI** [comment]
@rkaraivanov  also to add to this it seems the filtering is Cut Off after you filter 👍 

![image](https://user-images.githubusercontent.com/33216749/36843792-b002355e-1d58-11e8-9479-8ad9c21bcdaf.png)

**Comment by hanastasov** [comment]
Filteruin UI not visible is logged as another issue: https://github.com/IgniteUI/igniteui-angular/issues/691

**Comment by SlavUI** [comment]
This is fixed and merged
