### ISSUE TITLE
Use header for gropuing in igx-grid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#6933]
## Question  
The grouping feature seems to use the name of the data property. Is it possible to get it to use the header text instead?
![image](https://user-images.githubusercontent.com/12936286/77067123-bcd8b480-69e4-11ea-84aa-4fa598dd0d5f.png)

 * igniteui-angular version: 7.3

**Comment by ChronosSF** [comment]
Sure, you can can template the rows to use the header like this: https://stackblitz.com/edit/angular-77vzyp?file=src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html

```html
 <span class="igx-group-label__column-name">
        {{ grid1.getColumnByName(groupRow.expression.fieldName).header }}:
</span>
```

**Comment by Eralmidia** [comment]
Thanks @ChronosSF, that works. As a suggestion, it would be nice if the grouping picked the header over property name by default, so we wouldn't have to template it at all. Typically the header represents the way we want to present a property to the user after all.

**Comment by ChronosSF** [comment]
You are welcome! I logged your suggestion as a feature request separately.
