### ISSUE TITLE
Equals filter does not work for number column in the groupBy dev demo

### ISSUE THREAD

**Issue by astaev** [IgniteUI/igniteui-angular#6965]
## Description  
Equals filter does not work for number columns

 * igniteui-angular version: 8.2.x
 * browser: any

## Steps to reproduce  

1. Open the gridGroupBy DevDemo 
2. Open Salary field's filters 
3. Add a value(to default Equals condition) which equals to some of the cell values above

## Result  
Filter does not work at all
'Does not equal' also does not work

## Expected result  
Filtering should work as expected

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by rkaraivanov** [comment]
@astaev 
That's because the Salary column is explicitly marked as a number type, while in the underlying data, the salary prop types are strings. Basically the sample is configured in all manners of wrong
