### ISSUE TITLE
Broken styles - IE11 related

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#698]
### Description  
Open igniteui-angular demos under IE 11 and navigate to Grid and Grid Performance samples.

- Cards layout is broken
- Grid columns alignment
- Button text position is with position top.
- Icons are misaligned - little bit to the top.

Note: This issue is not related to the normalize styles changes

Images:

![image](https://user-images.githubusercontent.com/11193764/36893040-56302646-1e0f-11e8-87b7-efd233896693.png)

...................

![image](https://user-images.githubusercontent.com/11193764/36893060-623e7172-1e0f-11e8-94ec-db064a4cef9e.png)

.....................

![image](https://user-images.githubusercontent.com/11193764/36893075-6f95c14a-1e0f-11e8-9c89-345abd43c25a.png)

............................

![image](https://user-images.githubusercontent.com/11193764/36893101-81c9fffc-1e0f-11e8-97ae-2c2d72192203.png)

..............................

![image](https://user-images.githubusercontent.com/11193764/36893122-938fb164-1e0f-11e8-8984-e32a2ea9d120.png)

**Comment by kdinev** [comment]
@zdrawku The styles are broken in 5.2.0, not in 5.2.1.
