### ISSUE TITLE
Unable to set editValue of a cell when entering edit mode using a keypress

### ISSUE THREAD

**Issue by stevospinks** [IgniteUI/igniteui-angular#6986]
## Question  
I am trying to set the editValue of a cell when the user starts editing it (a simple case: the value "1,000" will become "1000" when we edit).

When I use `(onDoubleClick)="onDoubleClick($event)"` in the igx-tree-grid I get the desired behaviour, but this doesn't work for the keypress ways of entering edit mode (using F2 and Enter).

I've tried using `(onCellEditEnter)="onCellEditEnter($event)"` instead, but editValue isn't set when I call it, meaning the user is shown the display value (with commas). I have also tried using `(onGridKeydown)="onGridKeydown($event)"` which has the same result.

Is there something I'm missing?

Here is the related code from the component:
``` typescript
public onDoubleClick(event: IGridCellEventArgs): void {
  this.onCellEdit(event.cell);
}

public onCellEditEnter(event: IGridEditEventArgs): void {
  const column = this.igxTreeGridComponent.columns[event.cellID.columnID];
  const cell = this.igxTreeGridComponent.getCellByKey(event.rowID, column.field);
  this.onCellEdit(cell);
}

private onCellEdit(cell: IgxGridCellComponent): void {
  // Note: this is set via a different method, and always has a value when I use it
  cell.editValue = this.cellValueWithoutCommas;
}
```

 * igniteui-angular version: 8.2.22
 * browser: Chrome

**Comment by stevospinks** [comment]
I've just upgraded to angular 9.1.0 and igniteui-angular 9.0.8 and I'm still facing the same problem.

**Comment by zdrawku** [comment]
@stevospinks, there is not need to provide custom handling for the values in edit mode, the Grid can be configured to interpret them automatically with the help of `formatter` function or simple `decimal pipe`" - [StackBlitz example](https://stackblitz.com/edit/angular-column-formatter?file=src%2Fapp%2Fgrid%2Fgrid-row-editing-sample%2Fgrid-row-editing-sample.component.html)

1. Column formatter:

```html
<!-- Custom formatter -->
<igx-column field="UnitsInStock"[editable]="true" header="UnitsInStock" 
     dataType="number" [formatter]="customFormatter">
</igx-column>
```

2. Decimal pipe:
```html
<igx-column field="ReorderLevel" [editable]="true" header="ReorderLever" dataType="number">
	 <ng-template igxCell let-cell="cell">
		 {{ cell.value | number:'2.2-5'}}
	 </ng-template>
</igx-column>
```

![image](https://user-images.githubusercontent.com/11193764/78896236-d4054200-7a78-11ea-9526-dd708597185f.png)
