### ISSUE TITLE
Exception is thrown with bootstrap theme

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular#6990]
## Description  
Describe the issue.
An exception is thrown when trying to run a sample with bootstrap theme.

 * igniteui-angular version: 9.0.0

**N.B** This issue is related to the time-picker theme .Observe last symbol in second line of teh following snippet.

$_bootstrap-time-picker: extend(
    **$_light-time-picker,§**
    $_bootstrap-shape-time-picker,

## Steps to reproduce  

1.Run the attached sample

## Result  
The following exception is thrown:
(246:12) Unknown word

  244 |     @each $key, $value in $theme {
  245 |         @if $key != 'name' and $key != 'palette' and type-of($value) != 'map' {
> 246 |             --#{$prefix}-#{$key}: #{$value};
      |            ^
  247 |         }
  248 |     }

## Expected result  
No exception to be thrown.

## Attachments  
[src.zip](https://github.com/IgniteUI/igniteui-angular/files/4394541/src.zip)

**Comment by simeonoff** [comment]
I have identified the issue. We will release a new patch that fixes it on Monday.

Meanwhile, if anyone is experiencing issues building the bootstrap theme using dart sass (default in both igniteui-cli and angular-cli) compiler, you can install node-sass, which compiles just fine:

```bash
npm install node-sass
```
