### ISSUE TITLE
Error with IgxSelect pinned in IgxGrid

### ISSUE THREAD

**Issue by bmtheo** [IgniteUI/igniteui-angular#7006]
## Description  

When IgxSelect is pinned at runtime in an IgxGrid, the "unpin" is throwing this error :
Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed

 * igniteui-angular version: 
"igniteui-angular": "^9.0.6",
 * browser: 
Tested on Chrome (Version 80.0.3987.149), Firefox (73.0.1) & Edge (Version 80.0.361.69)

## Steps to reproduce  

https://stackblitz.com/edit/igx-select-pinned-bug-in-igx-grid

1. Start with a wide screen (columns should not be pinned)
2. Reduce the screen so the columns get pinned
3. Widen the screen so the columns get unpinned
4. The error appears in the log and it messes up the display of the grid (see screenshot in attachement)

For some reason this only happens when there is at least 3 columns pinned

## Result  
The error "Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed" is printed in the console
And it messes up the display of the grid

## Expected result  
No error should occur thus fixing the display of the grid

## Attachments  
https://stackblitz.com/edit/igx-select-pinned-bug-in-igx-grid

Exemple of "messing up" the grid in our app (yes it's a hierarchical grid but it has the same behavior as pointed out in the stackblitz)
![image](https://user-images.githubusercontent.com/31310846/77922717-af9fad80-72a1-11ea-8832-5f8dabec5b9c.png)

## "Workaround"
Widening the screen a bit more refreshes the display and fixes the grid
The problem is that you have to tell your user about this

PS : 
https://github.com/IgniteUI/igniteui-angular/issues/6837 and https://github.com/IgniteUI/igniteui-angular/issues/6823 are not related to this issue

**Comment by zdrawku** [comment]
@bmtheo I did q little [update of the app](https://stackblitz.com/edit/resize-action-from-breakpointobserver), to use our typography. As for the error, it is reproducible thank your sample.

**Comment by bmtheo** [comment]
Update to avoid automatic closing
