### ISSUE TITLE
Show both autoGenerated columns and Non-autoGenerated columns inside IgxGridComponent

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#7023]
## Description  
My IgxGridComponent has both autoGenerated columns and Non-autoGenerated columns.

How do I get both autoGenerated columns and Non-autoGenerated columns to both display in the grid and show data for each column using Angular 9/igniteui-angular 9?

I have used property binding to set the "data" property of the grid.

**If I use property binding to set "autoGenerate" to false then**
All columns display in correct order (left to right) based on order defined in HTML Template
Non-autoGenerated columns display
Non-autoGenerated columns are populated with data
autoGenerated columns display
autoGenerated columns are **not** populated with data

**If I use property binding to set "autoGenerate" to true then**
Only Non-autoGenerated columns display
Non-autoGenerated columns display
Non-autoGenerated columns are populated with data
autoGenerated columns do **not** display as columns in the grid
autoGenerated columns are **not** populated

 * igniteui-angular version: igniteui-angular version: 9.0.0
 * browser: browser: Google Chrome 79.0.3945.130 (Official Build) (64-bit)

## Steps to reproduce  

1. Update project from Angular 8 to Angular 9
2. Update project from igniteui-angular from 8.2.18 to 9.0.0
3. Note that when using igniteui-angular, both autoGenerated columns and Non-autoGenerated columns displayed correctly in column order and data displayed in each column.
4. Note that this issue happen with igniteui-angular 9.0.0+

## Result  
Non-autoGenerated columns and autoGenerated columns do **not** display as columns inside the IgxGridComponent and do **not** display with data inside IgxGridComponent.  Depending on whether you use property binding to set the "autoGenerate" property to false or true you will see different results.  See Description above.

## Expected result  
Both autoGenerated columns and Non-autoGenerated columns should display in the IgxGridComponent in the defined column order as defined in the Component HTML Template and each column should display with data.

Note that this worked when using Angular 8/igniteui-angular 8 by not setting the "autoGenerate" property at all.  Note that this also worked when using Angular 8/igniteui-angular 8 using property binding to set "autoGenerate" property to false.  I understand that the default value for the "autoGenerate" property is false.

## Attachments  
StackBlitz Example
https://stackblitz.com/edit/angular-xfhtdh

**Comment by zdrawku** [comment]
@brookhutchinson, this is not a bug or something that we can consider changing. As @hanastasov explained in [this issue](https://github.com/IgniteUI/igniteui-angular/issues/6688#issuecomment-607066604) this behavior is by design and it has always been such.

You can check out our [API documentation](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#autogenerate) and [changelog ](https://github.com/IgniteUI/igniteui-angular/blob/master/CHANGELOG.md#ignite-ui-for-angular-change-log)during the releases

> `autoGenerate`
> An @Input property that autogenerates the IgxGridComponent columns. The default value is false.
> When set to true, it will override all columns declared through code or in markup.

**Comment by brookhutchinson** [comment]
When using angular 8/ignite 8 and using property binding to set autoGenerate to false the columns display in the correct order, all columns display inside the grid as expected.

When using angular 9/ingnite 9 and using property bonding to set autoGenerate to false all of the columns display inside the grid, however, the autoGenerated columns displayed before the Non-autoGenerated columns inside the grid,

How can I have the autoGenerated columns and Non-autoGenerated columns display with data and display in the same column order inside the IgxGridComponent after updating from amAngular 9/ignite-ui 9 ?
