### ISSUE TITLE
IgxGridState is not working with IgxHierarchicalGrid

### ISSUE THREAD

**Issue by bmtheo** [IgniteUI/igniteui-angular#7025]
## Description  

When using the IgxGridState directive with IgxHierarchicalGrid it is throwing an error when trying to getState
"ERROR TypeError: Cannot read property 'columns' of null"

 * igniteui-angular version: 
"igniteui-angular": "^9.0.6",
 * browser: 
Tested on Chrome (Version 80.0.3987.149), Firefox (73.0.1) & Edge (Version 80.0.361.69)

## Steps to reproduce  
https://stackblitz.com/edit/igx-hierarchical-grid-persistence

1. Move a column around
2. Click on Save
3. The error is printed in the console and the state is not saved

## Result  
Error is printed and state is not usable

## Expected result  
No error then we can save/restore the state

## Attachments  
https://stackblitz.com/edit/igx-hierarchical-grid-persistence

Error in Chrome :
![image](https://user-images.githubusercontent.com/31310846/77993640-d228d980-7328-11ea-9f82-a4ece0058282.png)

Error in Firefox :
![image](https://user-images.githubusercontent.com/31310846/77993672-e10f8c00-7328-11ea-861d-07259acb0987.png)

The error in Stackblitz is not printed correctly, please consider reproducing in local to have the full error

## Explanation of error

The error occurs in igniteui-angular-js line 59584 in function "getColumns()" (I don't have sourcemap) because this.grid is null.
I think this.grid is null because I'm using IgxHierarchicalGrid and not IgxGrid but I didn't find anything else to use in the doc/code (for example I looked for a IgxHierarchicalGridStateDirective)

I labeled this as a bug because the spec (https://github.com/IgniteUI/igniteui-angular/wiki/Grid-State-Persistence) specifies that it should work with all grids

If I'm mistaken and I just used the wrong directive, please show me the one to use and consider updating the doc

**Comment by ChronosSF** [comment]
@bmtheo , the `IgxGridState` directive was only implemented for state persistence of the igxGridComponent, not for the Hierarchical or Tree grids. This should be considered a feature request.

**Comment by zdrawku** [comment]
[Specification ](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-State-Persistence)is updated

**Comment by radomirchev** [comment]
@bmtheo the development of the feature request is starting form the current sprint.

**Comment by radomirchev** [comment]
@bmtheo , the feature request is in the list for the current milestone. You could follow the milestone progress on the [Roadmap board](https://github.com/orgs/IgniteUI/projects/122) or in the [Roadmap file](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md)
