### ISSUE TITLE
Regarding igx-grid header text wrappoing

### ISSUE THREAD

**Issue by Srikariimpe** [IgniteUI/igniteui-angular#7047]
Hi we are using igx-grid angular , can you please us  a way to wrap column header text?

**Comment by zdrawku** [comment]
hi @Srikariimpe, you can use [headerTemplate] and add HTML elements or just update the header field text as you wish.

Have a look at these two samples for more information - [Sample 1](https://stackblitz.com/edit/angular-custom-filter-icons-and-positioning?file=src%2Fapp%2Fgrid%2Fgrid-sample-3%2Fgrid-sample-3.component.html) and [Sample 2](https://stackblitz.com/edit/angular-grid-header-template-change-field?file=src%2Fapp%2Fgrid%2Fgrid-paging-sample%2Fgrid-paging-sample.component.html)


```
<igx-column #col field="ProductName" header="Product Name" width="17%" [headerClasses]="'prodId'" [hasSummary]="true">
            <ng-template igxCell let-cell="cell" let-val>
                {{val}}
            </ng-template>
            <ng-template igxHeader let-col>
                <div class="text">{{col.field}}</div>
                <igx-icon #target="tooltipTarget" [igxTooltipTarget]="tooltipRef" [ngClass]="filterIconClassName(col)" (click)="toggleFilteringDialog(col)">filter_list</igx-icon>
                <div #tooltipRef="tooltip" igxTooltip>
                    Her name is Toola Tipa
                </div>
            </ng-template>
        </igx-column>
```
