### ISSUE TITLE
igxLayout - igxLayoutItemAlign input should be "stretch" by default.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#706]
### Description  
Initial value of align-items property is stretch.
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

So that `igxLayoutItemAlign` input should be `stretch` by default as well.

### Result  
When I mark up as below, divs don't stretch.
```
<div igxLayout igxLayoutDir="column">
  <div igxFlex style="background-color: red">aaa</div>
  <div igxFlex style="background-color: yellow">bbbbbb</div>
  <div igxFlex style="background-color: green">c</div>
</div>
```
![image](https://user-images.githubusercontent.com/15909409/37001092-bf0c7718-2108-11e8-839f-a5a9e2433783.png)

### Expected result  
```
<div igxLayout igxLayoutDir="column">
  <div igxFlex style="background-color: red">aaa</div>
  <div igxFlex style="background-color: yellow">bbbbbb</div>
  <div igxFlex style="background-color: green">c</div>
</div>
```
![image](https://user-images.githubusercontent.com/15909409/37001126-de317de6-2108-11e8-947b-0d16a4943db6.png)

**Comment by simeonoff** [comment]
Closed with https://github.com/simeonoff/igniteui-angular/commit/74af1d0002add7be43d9605b0e3fd6e884c1f365
