### ISSUE TITLE
Define new metadata descriptor for inputs that have different property name

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#7060]
## Description  
Some inputs' name in the product has different name for their corresponding property in the component's class:

![image](https://user-images.githubusercontent.com/2621802/78541709-bcbb2000-77fe-11ea-90b7-bb64cd654816.png)

In order to describe that properly, for applications like AppBuilder and CodeGen, new metadata tag is needed. In addition, the parser should recognize the tag.

More similar options:

![image](https://user-images.githubusercontent.com/2621802/78541953-1facb700-77ff-11ea-87ad-cc044c7a48b7.png)

We should also define, somewhere, if a new component is added with such inputs that it should contain that metadata tag.

**Comment by zdrawku** [comment]
Addressed with Code gen
