### ISSUE TITLE
igxList: Swipe scrolling does not work on iOS.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#707]
### Description  
Swipe scrolling does not work on iOS.
This is reproducible with hammerjs 2.0.8 but not with 2.0.6.

### Steps to reproduce  

1. Create a list and run it on iOS.
```
<igx-list>
  <igx-list-item [isHeader]="true">
    Category1
  </igx-list-item>
  <igx-list-item>Item1</igx-list-item>
  <igx-list-item>Item2</igx-list-item>
  <igx-list-item>Item3</igx-list-item>
  <igx-list-item>Item4</igx-list-item>
  <igx-list-item>Item5</igx-list-item>
...
</igx-list>
```

### Result  
Swipe scrolling does not work.

### Expected result  
Swipe scrolling should work.

**Comment by tkiryu** [comment]
I'm not sure but it might be related to the hammerjs issue below.
https://github.com/hammerjs/hammer.js/issues/977

**Comment by zdrawku** [comment]
Yes @tkiryu, the issue related to swipe gesture under iOS is cause by the mentioned hammer.js [issue](https://github.com/hammerjs/hammer.js/issues/977) by you.

This does not change the fact that we need to figure out a way to overcome it. We are not going to close this issue in the repo, and I hope that in the upcoming sprints we will start working on it.
