### ISSUE TITLE
[igxInput and/or igx-input-group] Input element doesn't enable/disable correctly using Reactive Forms

### ISSUE THREAD

**Issue by mimurawil** [IgniteUI/igniteui-angular#7086]
## Description  
I can't tell if this problem is in the igxInput or igx-input-group, but when using Reactive Forms the input element doesn't work correctly when I set the control (or the entire form) to enabled/disabled.

In the sample attached I set my form to start in the "disabled" state, then when I force the control to "enabled", the UI doesn't update and I can't change the control value (still looks like a disabled control).
Using the same sample but setting the form to start in the "enabled" state, I can force the control to "disabled", and even though I can't change the control value the UI still looks like an enabled control.

I added an igx-select component to compare side-by-side. The igx-select works as expected.

 * igniteui-angular version: 9.0.1
 * browser: Chrome Version 80.0.3987.163

## Steps to reproduce  

1. Open the sample at https://stackblitz.com/edit/angular-8gnzsy
1.1. The form starts at the "disabled" state.
2. Click on "Enable Text" to see nothing happens in the UI, and you can't change the text field value
3. Click on "Enable Select" or "Enable Form" to see the igx-select works as expected (just as a comparison)

There's another scenario regarding this same issue.
1. Open the same sample at https://stackblitz.com/edit/angular-8gnzsy and change the constructor of `select-sample-1.component.ts`
```
    constructor(private fb: FormBuilder) {
      // just comment the initial state
      // this.myForm.disable();
    }
```
2. Click on "Disable Text" to see the UI doesn't change, but now you can't change the text field value

## Result  

The input element is not enabling correctly when using reactive forms.
The input element is not updating the UI correctly when disabling using reactive forms.

## Expected result  

Should disable/enable correctly when using the following:
Example:
```html
...
    <form [formGroup]="myForm">
        <igx-input-group>
             <input igxInput name="myTextField" formControlName="myTextField">
...
```
```typescript

this.myForm.get('myTextField').disable();
this.myForm.enable();
```

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
n/a

**Comment by IvayloG** [comment]
This seems to be a feature request, since neither igxInput or igxInputGroup implement controlValueAccessor thus setDisabledState is non implemented as well. We should think of a way to reuse controlValueAccessor though the inherited components, instead of implementing it for each individual component separately.
