### ISSUE TITLE
Overlay in edit row template

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7088]
## Description  
Clicking really fast over the row editable rows by constantly exiting and entering in edit mode, leads to confusion in overlay id's. 

After some investigation, it was determined that the **attach** method gets triggered before the animation has ended. So the callback in **onDone** of the **animationPlayer** lags.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open grid edit row samples
2. Hit a breakpoint in base-grid.directive.ts in the subscription of **onOpened** of the overlay
3. Compare the emitted **ids** and the ones registered in the overlay.

## Result  
There is no consistency in the registration and emit process of the overlay id's.

## Expected result  
Needs consistency in the cycle of registering and emitting correct overlay id's

**Comment by Lipata** [comment]
Related to #6063
