### ISSUE TITLE
Grid filter row does not respect display density

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#7090]
## Description  
Open any sample from the [grid row filter topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html) in Stackblitz and change the display density to cosy/compact the grid respects the new density, but the row filter remains in comfortable density irrelevant of the grid.

## Attachments  
<img width="796" alt="Screenshot 2020-04-09 at 14 32 18" src="https://user-images.githubusercontent.com/1702064/78890801-f1cda980-7a6e-11ea-9650-5fa71077ae0b.png">

**Comment by DiyanDimitrov** [comment]
@StefanIvanov, Do we have a specification how should the filter row look like with different density?

**Comment by StefanIvanov** [comment]
@DiyanDimitrov good point it was not in the spec and I added a [design](https://github.com/IgniteUI/igniteui-angular/wiki/Filtering-Row#16display-density) for it, let's get in touch if you have any questions after looking at it

**Comment by onlyexeption** [comment]
I resolved the issue, however for cosy and compact densities, the input overlaps with other areas since the input group's density height is greater than filtering row's density height. @simeonoff can you have a look at it and share a possible solution to this?
