### ISSUE TITLE
data-visibleindex property not set to correct index of column defined inside HTML Template

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#7101]
## Description  
The IgxGridComponent is not displaying columns in the same order as the columns defined inside the Component HTML Template

 * igniteui-angular version: 9.0.9
 * browser: Version 80.0.3987.149 (Official Build) (64-bit)

## Steps to reproduce  

1. Define IgxGridComponent with columns inside a Component HTML Template
2. Use property binding and the [data] property to bind data to IgxGridComponent
2. Columns do not render in same order as defined inside Component HTML Template
3. Open Google Developer Tools
4. Inpect the IgxCell for each column and you will see that the **"data-visibleindex"** property is not being set to the corresponding column that is defined inside the Component HTML Template

## Result  
What is the actual result after following the steps to reproduce?
Columns do not display inside the same order as the columns as defined inside the Component HTML Template

## Expected result  
What is the expected result after following the steps to reproduce?
Columns should render in the same order as defined inside the Component HTML Template

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by radomirchev** [comment]
@brookhutchinson the issue is scheduled for the next sprint starting on 21st Apr.

**Comment by brookhutchinson** [comment]
Any update on this issue? When should we expect this issue to be addressed?

**Comment by hanastasov** [comment]
Not able to replicate the described behavior. Looking at this [sample](https://stackblitz.com/edit/columns-order) (having columns described in markup, `autoGenerate`=false), columns appear in the expected order:

![coluns order](https://user-images.githubusercontent.com/14248932/82902891-d2c89f80-9f68-11ea-9f0a-22b62610c008.png)
