### ISSUE TITLE
Rows displayed are sometimes limited to very narrow screen displaying two rows

### ISSUE THREAD

**Issue by valiztar** [IgniteUI/igniteui-angular#7135]
## Description  
I have my grid configured to show 10 rows per page, and sometimes it works fine, but most of the time it gets damaged and shows me only 2 rows, with a scroll, I always have more than 10 rows to show

 * igniteui-angular version: 
"igniteui-angular": "^9.0.9",
 * browser: 
chrome

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![error](https://user-images.githubusercontent.com/17414593/79295929-9d2b9380-7e9f-11ea-8142-1d9a795376e3.png)

**Comment by zdrawku** [comment]
@valiztar could you share with us some code or a sample that is reproducing the issue?

**Comment by valiztar** [comment]
hello guys excuse the delay, I was trying to hang my table in https://stackblitz.com/ but there it works perfect, in fact the problem of height to show the content currently only happens to me on some computers, sometimes, not always

**Comment by valiztar** [comment]
hello guys , i fixed the problem using this.igxGrid.reflow() after any change
