### ISSUE TITLE
Grid active element styling

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#7142]
## Description  
Except for the header, cell, summary cell (and “selected” equivalents) active element style should be applicable also to:

1.	Column headers with collapsible column groups
2.	Grouped row
3.	Master detail view 
4.	Active styling on “tab stop” element? @Stefan, this is something that should be considered as well. Currently we do not have active element indication for the tab stops (except the thin blue line, which is browser default from Chrome).

Proposed design by @StefanIvanov :
“I am adding designs based on the approach we use for body cell activation"

With border:
![image](https://user-images.githubusercontent.com/11193764/79334696-731eb380-7f29-11ea-8f3f-c850f053424e.png)

Without border:
![image](https://user-images.githubusercontent.com/11193764/79334702-77e36780-7f29-11ea-9c2a-12cb1ac346d3.png)

**Comment by zdrawku** [comment]
@StefanIvanov did you had the chance to look at point 4.

> Active styling on “tab stop” element? @Stefan, this is something that should be considered as well. Currently we do not have active element indication for the tab stops (except the thin blue line, which is browser default from Chrome).

**Comment by StefanIvanov** [comment]
I am not very sure about any specific to be done on point 4, @simeonoff what is you opinion?

**Comment by zdrawku** [comment]
I want to add the [wai-aria practices explanation](https://www.w3.org/TR/wai-aria-practices/#kbd_focus_discernable_predictable) for this particular functionality

> Visibility of the focus indicator: Users need to be able to easily distinguish the keyboard focus indicator from other features of the visual design. Just as a mouse user may move the mouse to help find the mouse pointer, a keyboard user may press a navigation key to watch for movement. If visual changes in response to focus movement are subtle, many users will lose track of focus and be unable to operate. Authors are advised to rely on the default focus indicators provided by browsers

I like the advice to rely on the default focus indicators provided by browsers, although such default focus indicator exists only in Chrome browser. So here we may consider the following statement:

>  If overriding the default, consider:
> - something about ... Colors and gradients can disappear in high contrast modes.
> - Users need to be able to easily distinguish between focus and selection as described in [§ 6.3 Focus VS Selection and the Perception of Dual Focus](https://www.w3.org/TR/wai-aria-practices/#kbd_focus_vs_selection), especially when a component that contains selected elements does not contain the focus.

I personally like the idea of having a consistent and common `visual indicators` for the `focused elements` for all browsers.

@simeonoff @radomirchev what are your thoughts on the subject?

**Comment by simeonoff** [comment]
@StefanIvanov I can't give you an answer. It really depends on what the expected visual direction is when tabbing between elements in the grid. If you deem it not important, well then it's decided, isn't it?

**Comment by radomirchev** [comment]
@StefanIvanov According to the new [wai-aria](https://w3c.github.io/wcag/guidelines/22/) 

>Success Criterion 2.4.7 Focus Visible
(Level A) [Changed]
Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.

 Having product compatible with ARIA best practices out of the box is important.

**Comment by kdinev** [comment]
Since the suggestion is to reply on the browser default indicators, and since we're not overriding them, we shouldn't worry about such indicators not being preset in certain browsers at the point of development. If this is a requirement by the accessibility specification, then browser vendors that do not provide such will surely implement them. The issue really is with browsers that do not provide such and not with our implementation.

**Comment by zdrawku** [comment]
@StefanIvanov and @simeonoff, I believe the visual representation of the focusable grid elements is very important because even the current "default" style looks broken. Out containers are overlapping part of the default browser styling, examples:
- Body container (Chrome) _Only one right border, the rest are overlapped_ 
![image](https://user-images.githubusercontent.com/11193764/80193461-83b5e480-8621-11ea-8f5b-249992cb7f76.png)

- Body container (Firefox) _Only one right border_ (black dots)
![image](https://user-images.githubusercontent.com/11193764/80193810-21111880-8622-11ea-8abc-e835d55822da.png)

- Header container (Chrome) _Two borders - bottom and right, the rest are overlapped_
![image](https://user-images.githubusercontent.com/11193764/80193585-c11a7200-8621-11ea-9954-da6394b8ae3c.png)

- Header container (firefox) _One right border_
![image](https://user-images.githubusercontent.com/11193764/80193656-ed35f300-8621-11ea-8c05-848a87fe8830.png)

**Comment by simeonoff** [comment]
> @StefanIvanov and @simeonoff, I believe the visual representation of the focusable grid elements is important because even the current _default style_ looks broken. Out containers are overlapping part of the default browser styling, examples:
> - Body container (Chrome) _Only one right border, the rest are overlapped_ (thin blue line)
> ![image](https://user-images.githubusercontent.com/11193764/80193461-83b5e480-8621-11ea-8f5b-249992cb7f76.png)
> 
> - Body container (Firefox) _Only one right border_ (black dots)
> ![image](https://user-images.githubusercontent.com/11193764/80193810-21111880-8622-11ea-8abc-e835d55822da.png)
> 
> - Header container (Chrome) _Two borders - bottom and right, the rest are overlapped_ (thin blue line)
> ![image](https://user-images.githubusercontent.com/11193764/80193585-c11a7200-8621-11ea-9954-da6394b8ae3c.png)
> 
> - Header container (Firefox) _One right border_ (black dots)
> ![image](https://user-images.githubusercontent.com/11193764/80193656-ed35f300-8621-11ea-8c05-848a87fe8830.png)
> 

I share your sentiment.
