### ISSUE TITLE
Potential Bug in igx-tree-grid using loadChildrenOnDemand 

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#7149]
## Question  
I am using the igx-tree-grid to render a tree structure where i expand a unit using loadOnDemand. I am using the loadOnDemand syntax callback: 

public loadHierarchicalUnits = (parentID: any, done: (children: any[]) => void) => {}

when i return done in the callback function i receive the following error: 
"Cannot add property children, object is not extensible at IgxTreeGridComponent.addChildRows (igniteui-angular.js:61723). 

I've ensured that the grid object is extensible. Could you please elaborate around this error? 

![image](https://user-images.githubusercontent.com/43247999/79441379-71132e00-7fd7-11ea-8f69-51d7d7d36f3c.png)

HTML:
![image](https://user-images.githubusercontent.com/43247999/79442410-cb60be80-7fd8-11ea-818a-bddbc5e89f18.png)

**Comment by DiyanDimitrov** [comment]
Hello @VirtualisProjec,

Your `igx-tree-grid` seems incorrectly configured. You are missing a `primaryKey` configuration and you should not set `foreignKey` and `childDataKey` properties at the same time. Depending on your data structure you should set only one of these properties:

- [child collection](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree_grid.html#child-collection)
- [primary/foreign key](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree_grid.html#primary-and-foreign-keys)

If you choose to use `childDataKey`, make sure that each object in the array is extensible and not only the array itself.

**Comment by VirtualisProject** [comment]
Thanks for the reply Diyan, 

Alright, i've removed foreignKey and is currently using childDataKey and primaryKey.

I am having a hard time understanding what makes the object in the array read only though. I am even json parsing the response object to ensure that it's extensible. 
![image](https://user-images.githubusercontent.com/43247999/79565987-0e429500-80b2-11ea-9fcf-7d12a3262dcc.png)

This is the following approach: 
1. Receive response, which automatically renders the following view:
![image](https://user-images.githubusercontent.com/43247999/79566072-33cf9e80-80b2-11ea-98e9-692097c2314f.png)

2. Expand SubPartSN2, which executes a query. the response of this query is inserted into the "done" callback. The child object is then not extensible. 

The initial response contains multiple levels, could the grid make the data object not extensible when rendering the initial children??

**Comment by igdmdimitrov** [comment]
Hi @VirtualisProject ,

There shouldn't be any problems with extending the data object. I've modified one of our [stackblitz](https://stackblitz.com/edit/angular-fmaast) samples to follow your desired approach. Hope this helps.

Regards,
Dimitar
