### ISSUE TITLE
Tab navigation goes to the cell of the next row when a new record is added to the bound data on onCellEdit.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#7158]
## Description  
Tab navigation goes to the cell of the next row when a new record is added to the bound data on onCellEdit.

 * igniteui-angular version: 9.0.10
 * browser: Chrome, Firefox, IE11, Edge

## Steps to reproduce  

1. npm-start the attached sample "sample-app1.zip".
2. Scroll down to the row whose ID is 51.
3. Double click on the "Name" cell of the ID51 row.
4. Hit tab key twice.

## Result  
The focus moves to the cell of the ID52 row.

## Expected result  
The focus moves to the cell of the ID51 row.

## Attachments  
![reproduce](https://user-images.githubusercontent.com/33947244/79825526-342ea900-83d4-11ea-80f6-a1e8cec1adce.gif)

Reproducible sample: [sample-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/4507628/sample-app1.zip)

**Comment by Aleksandyr** [comment]
@norikois This has already been fixed with the (keyboard enhancements)[https://github.com/IgniteUI/igniteui-angular/pull/6910] changes which you can test with **9.1.0-alpha.7** v. 
Please let me know if we can close the issue as **resolved**.

**Comment by norikois** [comment]
Thank you @Aleksandyr.
I checked with 9.1.0-alpha.7. The tab navigation works expectedly with Firefox, IE11 and Edge, but it doesn't with Chrome. The editing cell remains at the "Name" and only the focus moves to the next cells and then, the focus moves to the other part of the browser. Could you check it with Chrome again?

Here is the result with Chrome.
![Issue7158_9 1 0-alpha 7_Chrome](https://user-images.githubusercontent.com/33947244/79935683-7a494280-8490-11ea-93f8-60187945dbc1.gif)

**Comment by Aleksandyr** [comment]
@norikois Ok, I have tested that scenario with some improvements we have made recently, which we are planning to push till the end of the next week.
Till then, if you have any other questions, please let us know.
