### ISSUE TITLE
Deleting a string from a filter input leaves the first char as an active search term.

### ISSUE THREAD

**Issue by onlyexeption** [IgniteUI/igniteui-angular#7159]
## Description  
When filtering a column by string, when the chip is still not committed, deleting the string completely leaves the first letter as an active search term and the chip stays active.

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1. Open Grid Filtering
2. Filter column "Contact name" by "Patricio"
3. Delete the string "Patricio" from the filter input

## Result  
The char 'P' stays in the chip and the grid data is filtered by it.

## Expected result  
All data in the grid should be visible as we do not apply any filter on it hence there should be no filter chip at all.

## Attachments  
![bug](https://user-images.githubusercontent.com/19392175/79839673-86180480-83bd-11ea-8170-879a65c58057.PNG)

**Comment by DiyanDimitrov** [comment]
This issue seems to be introduced by the fix of #6973.
