### ISSUE TITLE
Grid perPage option: 5 is selected for the count per page when I set the unlisted number to perPage option

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#717]
### Description  
5 is selected for the count per page when I set the unlisted number to perPage option.

### Steps to reproduce  
1. Set 8 to perPage option and then run the app

### Result  
5 is selected for the count per page.

### Expected result  
8 should be added into the list, or nothing should be selected on the list at least. The current spec would confuse users.

**Comment by kdinev** [comment]
What is "the unlisted number"?

**Comment by gdayori** [comment]
![listednumber](https://user-images.githubusercontent.com/7350918/37260932-8272bf74-25db-11e8-86f1-058cdbee6513.PNG)

**Comment by kdinev** [comment]
The default template is with a select which lists preset perPage values. You can modify the template and provide any type of input, which can be filled with values other than the predefined ones in the default template.

**Comment by hanastasov** [comment]
There is an example of templating the paging UI at the [Data Grid Paging topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html#paging)

**Comment by gdayori** [comment]
@kdinev @hanastasov Thank you for the update. I think templating the paging UI is enough for the solution.
