### ISSUE TITLE
Grid height: setting "100%" to the height option doesn't work.

### ISSUE THREAD

**Issue by gdayori** [IgniteUI/igniteui-angular#718]
### Description  
setting "100%" to the height option doesn't work.

### Steps to reproduce  

1. Set "100%" to the height option and run the app

### Result  
No recoreds are displayed.

### Expected result  
Grid height should be 100% regardless of the number of records.

**Comment by kdinev** [comment]
@gdayori 100% height takes the 100% of the height of the parent container. By default, the document body height is 0px, thus setting 100% in the context of the document body, means that the grid will have 0px height. Put the grid inside a container with height different from 0px.
