### ISSUE TITLE
IgxCombo - Item selection after scrolling the combo does not work correctly

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#7184]
## Description  
When clicking on a combo item after the virtualized container has been scrolled, selection behaves inconsistently  
 * igniteui-angular version: 9.1x
 * browser: N/A

## Steps to reproduce  

1. Run the dev demos and open the combo sample (http://localhost:4200/combo)
2. Open the "State" combo
3. Scroll the items container to the bottom
4. Scroll back to the top
5. Click on the first item ("Michigan")

## Result  
"Michigan" is **not** selected.
If you click again, it is selected. If you click on **another** state (ie "Indiana"), "Michigan" is **deselected**

## Expected result  
"Michigan" is selected

## Notes
Clicks work fine before scrolling the container. Works fine with keyboard navigation.

**Comment by ViktorSlavov** [comment]
Reproducible w/ `@angular/core~9.0.0` as well

**Comment by ViktorSlavov** [comment]
Looks like this was introduced between `9.1.0-alpha.5` (not reproducible) and `9.1.0-alpha.6` (reproducible)

**Comment by zdrawku** [comment]
@ViktorSlavov it is possible the keyboard navigation enhancements to affect the combo virtualization, more especially this change - https://github.com/IgniteUI/igniteui-angular/pull/6910/files?file-filters%5B%5D=.ts&hide-deleted-files=true#diff-d637aea7875639647b3e0e557ff6d1fbR889

**Comment by ViktorSlavov** [comment]
Yup, that seems to be it, thanks for pointing it out! Locally, reverting the branch to a state prior to this being introduced, the issue does not reproduce.
