### ISSUE TITLE
Can i do ordering items in ig-tree like filter  | orderBy:['Name','Post']?

### ISSUE THREAD

**Issue by bruzhmelev** [IgniteUI/igniteui-angular#72]
Can i do ordering items in ig-tree like filter  | orderBy:['Name','Post']?

**Comment by kdinev** [comment]
You can do this by sorting the underlying `igTree` data source. 

http://www.igniteui.com/help/api/2016.1/ig.datasource#methods:sort

**Comment by kdinev** [comment]
Closing the issue as answered.
