### ISSUE TITLE
IgxForOf - Virtualized items do not properly trigger change detection

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#7202]
## Description  
After scrolling a virtualized container created w/ `IgxForOf`, user input on the items does not trigger change detection as expected

 * igniteui-angular version: 9.1.0-alpha.7
 * browser: N/A

## Steps to reproduce  

1. Open this [StackBlitz sample](https://stackblitz.com/edit/igx-for-of-910-alpha?file=src%2Fapp%2FigxFor%2FigxFor.component.ts)
2. Click on an item in the list - it's contents is populated in the input and the item has a gray background
3. Scroll the list
4. Click on an item

## Result  
The item is not marked as selected

## Expected result  
The item is marked as selected

## Notes
Manually calling `ChangeDetectorRef.detectChanges()` in the click handler causes proper behavior

**Comment by ViktorSlavov** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/7184

**Comment by ChronosSF** [comment]
@zdrawku, If this is caused by the change in igxForOf done with the keyboard navigation changes, I think it should be handled by Phoenix.

IMO, it's very likely that creating embedded views instead of detaching and reattaching them causes this.
