### ISSUE TITLE
Navigating to a row that cannot fit in the tbody produces a never-ending flicker cycle

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#7204]
## Description  
In grids with rows that are bigger than the available space in the tbody, trying to navigate to such rows produces a bizzare effect.

 * igniteui-angular version: 9.1.x
 * browser: n/a

## Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-fqwutj?file=src/app/grid/grid-editing-sample/grid-editing-sample.component.html
2. Try to keyboard navigate

## Result  
![issue11](https://user-images.githubusercontent.com/2188411/80221568-25ebc180-864e-11ea-901c-2ffcbed2f2db.gif)

**Comment by ddincheva** [comment]
I performed some additional testing and noticed that this problem has been resolved and is no longer reproducible in our latest major versions: 10.2.x; 11.0.x and 11.1.x;
![gridrow](https://user-images.githubusercontent.com/34240583/103654058-14dda900-4f6e-11eb-88d1-9ba8986f96b7.gif)
