### ISSUE TITLE
Hide grid column sort indicator

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#7207]
### Description  
Describe the issue.

 * igniteui-angular version: 9.1.0
 * browser: Google chrome

### Steps to reproduce  

1. Open Browser
2. Component displays IgxGridComponent
3. No columns are initially sorted
4. Sort Indicator displays inside column header of each column

### Result  
What is the actual result after following the steps to reproduce?
Sort indicator displays in column header of each column

### Expected result  
What is the expected result after following the steps to reproduce?
I understand that displaying the sorr indicator in the column header of each column is a new feature. However, I do not want to display the sort indicator inside the column header of columns that are not sorted. Similar to ignite-ui Version 8

What can I do to hide the sort indicator when a column is not sorted in ascending order or descending order?  In other wirds, what can I do to hide the sort indicator when a column sort is OFF 

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by nrobakova** [comment]
Hi @brookhutchinson,
Thank you for pointing this.
For now it is not possible to hide the sorting indicator by header template. You can add a feature request for this.
As a work around for now you can the classes for sorting to have the old behavior
```
 ::ng-deep .igx-grid__th--sortable .sort-icon{
    display: none;
}

::ng-deep .igx-grid__th--sortable:hover .sort-icon{
    display: inherit;
    opacity: 0.7;
}

::ng-deep .igx-grid__th--sorted .sort-icon{
    display: inherit;
    opacity: 1;
}
```
