### ISSUE TITLE
Unify the outline style when tabbing between logical grid areas

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#7211]
## Description  
Currently, we do not have a unified style when tabbing between logical areas in the igx-grid component. The current _default style_ is shown below. The containers are overlapping and the outline styles vary from browser to browser:
- Body container (Chrome) _Only one right border, the rest are overlapped_ (thin blue line)
![image](https://user-images.githubusercontent.com/11193764/80193461-83b5e480-8621-11ea-8f5b-249992cb7f76.png)

- Body container (Firefox) _Only one right border_ (black dots)
![image](https://user-images.githubusercontent.com/11193764/80193810-21111880-8622-11ea-8abc-e835d55822da.png)

- Header container (Chrome) _Two borders - bottom and right, the rest are overlapped_ (thin blue line)
![image](https://user-images.githubusercontent.com/11193764/80193585-c11a7200-8621-11ea-9954-da6394b8ae3c.png)

- Header container (Firefox) _One right border_ (black dots)
![image](https://user-images.githubusercontent.com/11193764/80193656-ed35f300-8621-11ea-8c05-848a87fe8830.png)

Initially discussed here https://github.com/igniteui/igniteui-angular/issues/7142

**Comment by StefanIvanov** [comment]
I think we should use a 1px border that takes secondary 500, what do you think

**Comment by StefanIvanov** [comment]
Our final solution involves removing the styles on these tab containers. @desig9stein will make a PR for that
