### ISSUE TITLE
Batch Editing and Paging template unexpected behavior

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#7214]
## Description  
I'm trying to implement grid-batch-editing on a grid with remote data operations and custom paging template. Most of the functionalities are working fine except:
 1) adding a new row
 2) deleting a new added row.

 * igniteui-angular version: 9.0.x
 * browser: any

## Steps to reproduce  

 1) Open the [attached sample](https://stackblitz.com/edit/remote-data-paging-batch-editing?file=src%2Fapp%2Fgrid%2Fgrid-remote-paging-sample%2Fremote-paging-sample.component.html)
 2) Go on the last page(8) and add 4 new rows
 3) Go on the new added page(9) and delete all rows.

## Result  
 1) When adding 4 rows so that a new page is created, on that new page we see all of the new added rows instead only the last one.
 2) When deleting all of the new rows on page(9) we stay on the same empty page and the paging template is gone away.

## Expected result  
Paging to be able to determine adding and deleting rows.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ddincheva** [comment]
The first described problem is a limitation of how the grid works with remote data and a transaction service, because we are facing the situation where the the remote service returns empty array and the only data that is passed to the grid is from the transaction service, so the grid display apply paging according to the data source it has. The second problem is something that can be easily fix on application level, here you can see this [sample](https://stackblitz.com/edit/remote-data-paging-batch-editing-hsndeq).

**Comment by hanastasov** [comment]
If this is a limitation, we should document it in the paging and transactionService topics. We need a viable explanation why the grid does not know what page a corresponding batch record belongs to.

**Comment by zdrawku** [comment]
@ddincheva will provide a sample for the pointed scenario - Batch Editing with Remote paging.

@hanastasov we are going to proceed with [topic update](d) and [sample ](https://github.com/IgniteUI/igniteui-angular-samples/issues/2006)creating when [this request](https://github.com/IgniteUI/igniteui-angular/issues/7215#issuecomment-630146450) is completed

**Comment by ddincheva** [comment]
Hello all,
I managed to build a [sample](https://stackblitz.com/edit/remote-data-paging-batch-editing-1vwjoq) that handle the pagination correctly when you have a grid with remote data and enabled transaction service. The full explanation will be provided in our official documentation.
