### ISSUE TITLE
Paginator displays only one page of data, while there are more data items on the server

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#7215]
## Description  
I'm trying to implement grid-batch-editing on a grid with remote data operations and paging without template.

 * igniteui-angular version: 9.0.x
 * browser: any

## Steps to reproduce  

 1) Open the [attached sample](https://stackblitz.com/edit/remote-data-paging-without-template-and-batch-editing?file=src%2Fapp%2Fgrid%2Fgrid-remote-paging-sample%2Fremote-paging-sample.component.html)
 2) Select for example 25 Items per page

## Result  
 1) There is just a single page where we see only 15(default perPage count) records. 
 2) Can't listen to items per page change.

## Expected result  
 1) Paging to calculate the right number of pages so that we'll be able to see the whole data and to add or delete rows
 2) To be able to listen to items per page changes event.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by rkaraivanov** [comment]
Just want to point out that both `page` and `perPage` are two-way binded input properties of the grid.
That is you have `pageChange` and `perPageChange` event emitters available.

However this is not documented sufficiently neither in the pagination topic nor in the API documentation. So maybe, you should also open an issue for the documentation.

**Comment by zdrawku** [comment]
@radomirchev @rkaraivanov we are going to use this item to expose a `totalRecords` setter along with a new `pagingMode` property (enum - local|remote). When paging mode is set to `remote` the developer should handle the pagination on the server and pass the data to the grid.

We are going to review and update if needed our current samples that are showing:
- How to implement remote paging with `custom paging template` 
- How to implement remote paging with the `default template`
- Add a sample for Batch Editing with Remote Paging Sample and description in the topic.
