### ISSUE TITLE
IgxHierarchicalGrid component does not have an `id` property setter

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#7220]
## Description  
IgxHierarchicalGrid component does not have a id setter

 * igniteui-angular version: 9.1.0, 9.0.0

## Steps to reproduce  
Try to set id for the IgxHierarchicalGridComponent:
<igx-hierarchical-grid [id]="hierGridId" ..></igx-hierarchical-grid>

## Result  
See console:
ERROR
Error: Cannot set property id of [object Object] which has only a getter

**Comment by hanastasov** [comment]
Please fix the issue for version 9.0.0 too.

**Comment by zdrawku** [comment]
The fix is included in 9.0.18
