### ISSUE TITLE
Expose templates for all ESF UI parts

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#7221]
## Is your feature request related to a problem? Please describe.
Currently, the pinning, sorting, hiding parts of the Excel-style Filter UI can be manipulated and replaced by the developer, but the text-filter, search and unique value list cannot. Expose templates for all parts of the ESF UI.

## Describe the solution you'd like
A solution similar to the pinning, sorting and hiding in the ESF.

## Describe alternatives you've considered
Selecting elements and hiding/removing them from the DOM.

## Additional context
Most applications require different custom UIs and we should allow developers to customize as much as possible.

**Comment by williamverdolini** [comment]
A question: with this feature, will it be possible to customize ESF adding specific filter template per column? A typical scenario is the "tag column" where a possible filter dialog should be something like that

![image](https://user-images.githubusercontent.com/6443266/89176001-181cd500-d589-11ea-9956-16ae9f7bf9c8.png)

with a custom dialog to filter values. It should support remote filtering as the standard filter dialog already supports.

Is there any way to get this result?

**Comment by DiyanDimitrov** [comment]
@williamverdolini, by using the new directives you will be able to fully customize the whole Excel style filter menu. The following sample code demonstrates how to modify the filter operations area for a specific column:

```html
<igx-grid-excel-style-filtering #esf>
    <igx-excel-style-filter-operations>
        <ng-container *ngIf="esf.column?.field === 'ID'">
            <div>My Custom Filtering UI</div>
        </ng-container>
        <ng-container *ngIf="esf.column?.field !== 'ID'">
            <igx-excel-style-clear-filters></igx-excel-style-clear-filters>
            <igx-excel-style-conditional-filter></igx-excel-style-conditional-filter>
            <igx-excel-style-search></igx-excel-style-search>
        </ng-container>
    </igx-excel-style-filter-operations>
</igx-grid-excel-style-filtering>
```
