### ISSUE TITLE
[GroupBy] Grid expanded rows are not visible when expand the last grouped row

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7223]
## Description  
[GroupBy] Grid expanded rows are not visible when expanding the last grouped row

 * igniteui-angular version: 9.1.x
 * browser: all

## Steps to reproduce  

1. Open the corresponding [sample](https://stackblitz.com/edit/angular-gdsryp?file=src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html) 
2. Group 2 to 3 columns
3. Collapse all main grouped rows
4. Navigate to the bottom of the grid
5. Expand the last or the one before the last row

## Result  
The rows below are not visible and the grid is not scrollable.

## Expected result  
The rows should be visible and the grid should be able to scroll to the last visible row.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
@Aleksandyr As the grid has paging enabled and paging takes into account the group rows (they participate in the paging process and are part of the total page size for each page) when you expand the last one it's children will actually go on the next page as the current page is full - already has 15 rows that are the collapsed group rows. So to see it's child you need to go to the next page.
Let me know if you have any questions.

**Comment by Aleksandyr** [comment]
@MayaKirova I understand. I'm closing the issue.
