### ISSUE TITLE
Keyboard shortcuts window

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#7228]
## Is your feature request related to a problem? Please describe.
I want to quickly be able to see all available grid shortcuts without going to the official documentation.

## Describe the solution you'd like
Microsoft Teams uses <kbd>Ctrl + .</kbd> combination to show a window with all available Keyboard shortcuts. My suggestions would be either to provide similar build-in functionality to the igxGrid OR create an `Extras Directive` (like the Data Analysis directives) that will be applicable on an application level.

## Additional context
![image](https://user-images.githubusercontent.com/11193764/80564043-6c963e80-89f5-11ea-812e-f5c6d56b9a7a.png)

**Comment by zdrawku** [comment]
@damyanpetev I would love hearing your two cents on that matter :)

**Comment by kdinev** [comment]
On one hand keyboard shortcuts should be intuitive, on the other the grid is a component and not an application. The component should be as small as possible, in terms of code, and any additional fluff, which doesn't provide any extra functionality should be removed. I consider this request to be documentation related and it should not be part of the product.
