### ISSUE TITLE
KB navigation: Key combination for Close/Submit/Clear Advanced Filtering

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#7243]
## Description  
<kbd>Alt</kbd> + <kbd>L</kbd> is used to open the Advanced filtering Dialog, and in order to close it, you should navigate to one of the action buttons and Cancel/Submit the form. What about a key combination for:
- Cancel
- Submit
- Clear filter

@StefanIvanov we can consider the following, <kbd>Esc</kbd> to close the dialog, <kbd>Alt</kbd>+<kbd>Enter</kbd> to submit it and <kbd>Alt</kbd>+<kbd>C</kbd> to clear the filtering of that particular column (despite your location - weather from the Dialog window or the actual Column header).

**Comment by StefanIvanov** [comment]
I think our safest bet would be to just provide the close on Esc key. Even though I like the idea of a submit and clear filter shortcuts I feel that we should stick to web standards where Enter submits a form, which in our case is not possible with the complex layout and use of the key to toggle states of chips, inputs, etc. Not being able to use that I am reluctant to use the Enter in any key combination. For clear filter have you considered using the backspace/delete key? Of course, if the user would be typing a value in the input, it would erase characters but in all other cases, it could potentially clear a condition or all conditions based on where the focus is.

**Comment by zdrawku** [comment]
@StefanIvanov I didn't check that both `filtering row` and `excel-style filtering` are currently canceling/escaping the dialog with `Esc key` so I agree with you that we should use `Esc key` for the Advanced dialog as well. As for clearing the filter, we provide navigation to the `Clear filter` button, so no further questions here.

@radomirchev, everything is cleared then, @ddincheva you can proceed with the implementation
