### ISSUE TITLE
Igx-Paginator with Igx-remote data operations

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#7247]
## Description  
I detected a problem on the igx-paginator that the current page indicator on the pagination buttons is incorrect and makes the table behave in a incorrect way, so I went to your site over the remote data operations paging demo, to see compare my implementation with the example, but the behave is the same.
So you just need to go here and test just like I will indicate in the steps.

Are we able to set the page that is currently beeing displayed manually?

[remote paging demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html#remote-paging-demo)

 * igniteui-angular: "9.0.1",
 * @angular/compiler: "9.0.7",
 * browser: Chrome

## Steps to reproduce  

change the records per page to 25, then navigate to the 3rd page, you will get indicator “3 of 4” on the page navigation.
Then change the records per page to 5 and you will get the indicator “3 of 16” and the table shows the 1st page.
The table does not recover until you go again to the first page and start paginating again after.

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
paginator indicates “3 of 16” and shows the 1st page

## Attachments  
 should present “1 of 16” and the first page

**Comment by zdrawku** [comment]
Thank you, @MiguelPetrotec. I am submitting another issue to our samples repository as well, because partially the problem is related to the custom paging implementation.

This line specifically:
```ts
public set perPage(val: number) {
        this._perPage = val;
        this.paginate(0); <------
    }
```

I've created a Pull request that will address this problem along with some further enhancements.

**Comment by zdrawku** [comment]
hey @MiguelPetrotec, the fix is part of the latest [alpha version](https://github.com/IgniteUI/igniteui-angular/releases/tag/9.1.0-alpha.12)
