### ISSUE TITLE
Enable Tree shaking. 

### ISSUE THREAD

**Issue by mshehadeh** [IgniteUI/igniteui-angular#7251]
## Is your feature request related to a problem? Please describe.
Currently, if i only use IgxGridModule, i end up with the entire ignite UI in my final bundle. 

## Describe the solution you'd like
I want to be able to import only what i use so i can reduce my bundle size and make my application faster to load. This can be done by adding secondary entry points like angular material, and other components libraries do.

## Describe alternatives you've considered
In the docs. i have seen the usage of 

`import { IgxGridModule } from 'igniteui-angular/grid';
`
but that does not work anymore. 

## Additional context

<img width="487" alt="Screen Shot 2020-05-03 at 11 38 18 AM" src="https://user-images.githubusercontent.com/4926006/80894813-cc148700-8d32-11ea-87cc-c16daf045c26.png">
This comes from a starter app where there is nothing except for IgxGridModule imported in app module like below.

``import { IgxGridModule } from 'igniteui-angular';
` 
Once we start adding modules from the components that you provide, this size does not increase or decrease, point towards the entire library being packaged no matter what.

[demo-app.zip](https://github.com/IgniteUI/igniteui-angular/files/4569341/demo-app.zip)

I have attached a my-dream-app with where those stats came from.

**Comment by kdinev** [comment]
Tree Shaking is fully supported on the production build. In order to deliver the build quicker in the dev environment, the dev build does not go through the tree shaking, or other optimization procedures. Here's the result of the production build with your sample:

![image](https://user-images.githubusercontent.com/1472513/80965507-4fa9a300-8e1b-11ea-9e43-092fcb7c97ab.png)

**Comment by jorgellose** [comment]
I have the same issue with the same example
![image](https://user-images.githubusercontent.com/21179119/83323335-61d20200-a25e-11ea-8ef1-e7c2f3ebf1ec.png)

+921KB in HomeModule, +35 s build time, from 6s to 41s

![image](https://user-images.githubusercontent.com/21179119/83323356-829a5780-a25e-11ea-99c1-7d483ff58513.png)

**Comment by mshehadeh** [comment]
I don't think this relates to the original issue i raised. The grid is quite heavy, but i think third party grids are generally that size. 

This issue relates to the fact that i was reading the data incorrectly + just doing things wrong in general. IGX is tree shaking and tree shaking quite well. 

If you think igx is too heavy, maybe raise a new issue.

**Comment by jorgellose** [comment]
Okay, i thought it was not correct when i saw 250 mentions to Excel in the code, i am not importing than functionality

**Comment by kdinev** [comment]
@jorgellose I tried a build with and without the grid, and the side of the main module goes up by about ~500kb and styles go up by about ~50kb. The grid itself, however simple it may seem, has dependencies on some of its features, so they can be turned on using a simple input. The grid is the largest component in the library and I would suggest separating components that use it in a separate module, so it can be lazy-loaded. 

The 'excel' mentions you're observing are a mix of the excel-style filtering, which is turned on through the filtering configuration, and the excel exporter, which I don't see turned on. We will take a look at whether the exporter service is not being tree-shaken and we can improve that.

**Comment by domJalb** [comment]
I did some testing with the app provided in the original post and compared bundle sizes on the production build when importing just the grid module vs importing just the button module. The end bundle size is 3.5 Mb (Stat size) regardless of what module you import. It doesn't appear there is any tree shaking going on here, or I'm misunderstanding how to optimize the production bundle.

With GridModule only:
<img width="1309" alt="Screen Shot 2021-01-26 at 1 36 28 PM" src="https://user-images.githubusercontent.com/11845822/105908856-93f95680-5fdb-11eb-911e-5544c3cd1936.png">

With ButtonModule only:
<img width="1301" alt="Screen Shot 2021-01-26 at 1 35 08 PM" src="https://user-images.githubusercontent.com/11845822/105908875-9c519180-5fdb-11eb-838b-a0de1274e93a.png">

**Comment by mshehadeh** [comment]
Hey Dom, you should use source map explorer rather than bundle analyzer as this is the exact same thing that thread me off. Source map explorer considers tree shaking but bundle analyser does not.

**Comment by domJalb** [comment]
@mshehadeh thank you for that, very helpful.
