### ISSUE TITLE
IgxGrid behaves differently in Google Chrome vs Edge. Summaries not behaving as expected.

### ISSUE THREAD

**Issue by NickCook-StruMIS** [IgniteUI/igniteui-angular#7259]
## Description  
I have a scenario where I want to use the igxGrid to be able to (filter / group / sort / move & summarize) all columns. I started with the Infragistics igniteui-angular grid summaries overview stackblitz example should here:

https://stackblitz.com/angular/oogeaodleyp?file=src%2Fapp%2Fgrid%2Fgrid-sample-3%2Fgrid-sample-3.component.html

This example works perfect for my requirements. I also made the columns (filterable / groupable / sortable / movable).

Once you make a column groupable or moveable you can no longer turn the column summary on / off by clicking the summary icon in the header (the toggleSummary event does not fire). At first i thought this was a limitataion to the igxGrid but soon realised that the stackblitz example does allow the above feature in Microsoft Edge but not in Google Chrome. 

I have pulled the stackblitz example locally and get the same results.

 * igniteui-angular version: 9.0.1
 * browser: Google Chrome: 81.0.4044.122 / Microsoft Edge: 44.18362.449.0

## Steps to reproduce  

1. Run the above stackblitz example on both Chrome & Edge
2. Modify the grid-sample-3.component.html line 5 and add groupable="true" or movable="true" to the igx-column 'ProductName' column.
3. Click the summary icon in the header to turn on / off the summary footer for ProductName column.

## Result  
The ProductName column no longer hides / shows the summary footer. The other columns behave correctly as before.

## Expected result  
I would expect the grid to behave the same in both Chrome & Edge (not tried other browsers) and be able to group and summarize a column at the same time.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by nrobakova** [comment]
Hi @NickCook-StruMIS ,
Thank you for pointing this.
When the column is movable or groupable  the drag directive is applied for it. To can click action on the icon  be preformed you have to add [attr.draggable]="false"  for it. It the sample you have to update the header template with:
```
  <igx-column #col field="ProductName" header="Product Name" width="17%" [headerClasses]="'prodId'"  groupable="true"  movable="true" [hasSummary]="true">
            <ng-template igxCell let-cell="cell" let-val>
                {{val}}
            </ng-template>
            <ng-template igxHeader let-col>
                <div class="text">{{col.field}}</div>
                <igx-icon class="header-icon" color="{{ col.hasSummary ? '#e41c77' : '' }}" (click)="toggleSummary(col)" [attr.draggable]="false">functions</igx-icon>
            </ng-template>
        </igx-column>
```

**Comment by zdrawku** [comment]
@NickCook-StruMIS, in addition to what Nadia said we are going to update our documentation ([related item](https://github.com/IgniteUI/igniteui-docfx/issues/1941)) in order to address this behavior - whenever a header template is used along grouping/moving functionality, each column header area becomes draggable and you cannot access the custom elements part of the header template `until you mark them as not draggable`, as Nadia pointed out in her reply for the icon.

FYI, the new Edge (based on Chromium browser, called Edgium ) and Chrome are behaving the same way, the click action is not working in both, which is expected.

**Comment by NickCook-StruMIS** [comment]
Excellent, thanks for this. I have just come across this again today implementing the same functionality with the IgxHierarchicalGridComponent and each child IgxRowIsland. And I can confirm the above solution works perfectly.

Thanks
