### ISSUE TITLE
IgxGrid State Restore Is Ignoring HTML

### ISSUE THREAD

**Issue by feargusmac** [IgniteUI/igniteui-angular#7267]
## Description  
I am using an IgxGrid with igx-columns. I want the header text to wrap lines so inside the column I have an ng-template with a div with a class to properly format the header, like this:
(I have created a stackblitz of a simplified version of my grid attached below)

```html
<igx-column [field]="'testHeader'" header="TestHeader" [resizable]=true dataType="string" [sortable]="true" [movable]="true" [width]="'125'" [minWidth]="'100'">
    <ng-template  igxHeader let-column>
        <div class="headerDetails">Header Text</div>
    </ng-template>
</igx-column>
```

This works when the page first loads but when my state restore function is triggered, once the page is refreshed the header wrap is gone, the header becomes whats inside header="TestHeader", and widths are ignored. It seems to be ignoring most of the HTML code after that. Then to get back to the state that looks good I have to clear my cache. I know it has to do with restoring the grid state because if I comment that step out then there's no bug but I can't restore my state.

 * igniteui-angular version: 9.0.12
 * browser: Chrome, Edge

## Steps to reproduce  

1. Open up the stackblitz example: https://stackblitz.com/edit/angular-kekrtr-mtjf2d
2. Notice the header texts are wrapped and are as defined in `<div class="headerDetails"></div>`
3. Hide one of the columns (to trigger the saveGridState() method).
4. Refresh the page (to trigger the restoreGridState() method).
5. Note that the header formatting is gone.

## Result  
Header formatting is gone, the text is no longer what it is defined as in `<div class="headerDetails"></div>` but rather the `header` property of the column, the `width` and `minWidth` properties are being ignored. There's possibly more errors that I haven't caught yet. 

## Expected result  
I expected the state to be restored and the grid to be constructed as it is defined in the HTML. That is, no changes to the headers just restoring the columns selected, their order, which ones are sorted, etc.

## Attachments  
https://stackblitz.com/edit/angular-kekrtr-mtjf2d

**Comment by function-de** [comment]
Interesting. Just got trapped int this one, too. 
Found out that restoring grid state with the HTML template works until you turn on the columns option.

**Comment by hanastasov** [comment]
The igxGridState directive does not take care of temlates. If a developer needs to restore templates (or formatter functions let's say), those templates can be set in the onColumnInit event. The dev needs to query those templates using ViewChild or ViewChildren:
```
<igx-column #testHeaderTemplae [field]="'testHeader'" header="TestHeader" [resizable]=true dataType="string" [sortable]="true" [movable]="true" [width]="'125'" [minWidth]="'100'">
    <ng-template  igxHeader let-column>
        <div class="headerDetails">Header Text</div>
    </ng-template>
</igx-column>
```

```
// component.ts
@ViewChild('testHeader', { read: TemplateRef, static: true }) public testHeaderTemplate: TemplateRef<any>;

public onColumnInit(column: IgxColumnComponent) {
   if (column.field === 'testHeader') {
        column.headerTemplate = this.testHeaderTemplate
   }
}
```

**Comment by feargusmac** [comment]
Thanks for the response. I have implemented your suggestion and it doesn't fully work. It does now recreate the column with the width given in the <igx-column> element but it still doesn't capture the template from the <ng-template> or <div> elements within the column element.

**Comment by hanastasov** [comment]
@feargusmac  Will you be able to provide a sample where the issue happens ?
