### ISSUE TITLE
[hGrid] arrow up/down does not work when you reach any inner grid via kb nav

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7290]
## Description  
Once you reach with kb nav any inner grid while navigating up/down, the navigation goes to the document body and the grid becomes uncontrollable.

 * igniteui-angular version: 9.1.x
 * browser: all

## Steps to reproduce  

1. Open any hGrid dev demos
2. navigate to a row island which is closer to the end of the display view of the grid so that when you open it with alt + arrow right it is expanding out of it.
3. Try to continue navigating up/down

## Result  
The focus goes to the document of the body and the grid stops reacting.

## Expected result  
The focus should remain on the grid you are in and continually responding to the kb interactions.

**Comment by MayaKirova** [comment]
This used to work around version 9.1.0-alpha.8 but was regressed in 9.1.0-alpha.9

**Comment by MayaKirova** [comment]
Regressed after this commit: https://github.com/IgniteUI/igniteui-angular/commit/c29dc15fd8080de62042e00e5d4dc8126bd1263f

**Comment by MayaKirova** [comment]
Revert of change should solve this: https://github.com/IgniteUI/igniteui-angular/pull/7269
