### ISSUE TITLE
Issue when expanding level above 10 in igxTreeGrid

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#7299]
## Description  
If we have more than 10 levels in the IgxTreeGrid and try to expand the children of the 10th child, their position would be the starting position. 

 * igniteui-angular version: 9.0.1

## Steps to reproduce  

1. Run the attached sample
2. Expand all children of the first record

## Result  
When you expand the 10th node its child is not correctly aligned. Its position is the starting position. Not align according to its parent position.

![Capture](https://user-images.githubusercontent.com/52423497/81544111-b715a480-937f-11ea-91f5-b957188e091a.PNG)

## Expected result  
All nodes to be aligned correctly.

## Attachments  
[https://stackblitz.com/edit/igx-tree-grid-levels-issue-fsizmc](https://stackblitz.com/edit/igx-tree-grid-levels-issue-fsizmc)

_Note:_  If we add igx-grid__tree-cell--padding-level-11 to 25 (for example) classes and there set the padding-left property all nodes above level 26 would be aligned as expected.
A sample using this workaround could be found here:
[https://stackblitz.com/edit/igx-tree-grid-levels-issue](https://stackblitz.com/edit/igx-tree-grid-levels-issue)

**Comment by kdinev** [comment]
@teodosiah Currently, we have this by design, as hierarchies above 10 levels would not be visualized properly, even if we define paddings for those. The starting cell would just become enormous and would, by itself, force a horizontal scrollbar on the view.

**Comment by DiyanDimitrov** [comment]
We have decided to implement support for up to 25 levels of hierarchy and add this as limitation of the component in the documentation. For hierarchy with more than 25 levels, the workaround with adding more classes on application level is still valid.
