### ISSUE TITLE
Memory leak issues in hGrid

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#7301]
## Description  
Memory leak issues in hGrid

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGrid
2. In the first grid change page size to 100
3. Click on + icon to expand all rows
4. Open Performance monitor and start scroll down

note: the issue is reproducible in both 9.0.x and 9.1.x versions

## Result  
JS heap size, DOM nodes and JS event liseners are increased

## Expected result  
there should be no memory leaks 

## Attachments  
![hgridMemLeak](https://user-images.githubusercontent.com/11463104/81555784-d74e5f00-9391-11ea-9fb7-0e60acb42dcf.gif)

**Comment by ChronosSF** [comment]
As described this is not a leak. When you scroll down new grids come into the virtualization frame and their state, including handlers and whatnot increase the page memory footprint. If the user wants to select a row in grid 56, he wants that row to be selected when he scrolls back to grid 56.

There would be a leak if scrolling back to top continues to increase the memory footprint of the page as scrolling through already created grids should _reuse_ them and not create new ones increasing the memory usage indefinately. A memory leak is a memory allocation increase on a repeating action.

**Comment by ChronosSF** [comment]
If the memory footprint increases on a repeating action, please update the steps and return the bug back to me.
