### ISSUE TITLE
IGX Grid column width in %

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#7303]
### Description
I need igx columns to be rendered for the given percentage. In columns I have specified width like below but columns are not getting sized according to the given percentage.
`<igx-column [width]="'30%'"></igx-column>`

I have tried by setting width to `<igx-grid>` and to its parent element in all possible ways but none of them making the column to take given percentage instead I believe it is taking default column width.

It would be really helpful if you provide suggestion or sample demo/code.

 * igniteui-angular version: 8.2.9
 * browser: Chrome

**Comment by kdinev** [comment]
@Raju-N What exactly are you observing as a result? Setting 30% width on a column makes it be 30% of the total width of the grid container, given that the grid container width can be calculated.

In this example, I've set the width of the second column to be 30%, and the column is rendered correctly at 30% of the grid width: https://stackblitz.com/edit/angular-gzt3ge?file=src/app/grid/grid-paging-sample/grid-paging-sample.component.html

Keep in mind that columns have a minimum size that they cannot fall under. In the case where the grid container width drops below a value, which will cause 30% of it's total width to be less than the columns minimum width, then the column would just stay at its minimum width.

Here's the full topic on grid sizing: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/sizing.html#column-sizing
