### ISSUE TITLE
Calendar year names are not fully displayed

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#731]
### Description  
The years in the year selector of the calendar are displayed with at most two digits under Edge/IE11.

### Steps to reproduce  

1. Open any calendar or datepicker sample under Edge/IE11
2. Go to the year selector

### Result  
The years are not fully displayed.

### Expected result  
The years should be fully displayed.

### Attachments    
![image](https://user-images.githubusercontent.com/1472513/37144423-ac86775a-22c6-11e8-8e98-3f5262e815f1.png)

![image](https://user-images.githubusercontent.com/1472513/37144531-ff02a2c4-22c6-11e8-922a-080b10f0d86b.png)

**Comment by rkaraivanov** [comment]
Almost 3 years on the backlog...[vote to make the pain go away](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263702-css-intrinsic-sizing)

**Comment by kdinev** [comment]
I did just vote. Meanwhile, we have to work around their lack of implementation.
