### ISSUE TITLE
When clicking on elements in the grid that are not cells the first cell becomes active.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#7312]
## Description  
When the grid takes focus as a result of click on element different than a cell in header/body/footer the first cell in the container is marked as active.

For example when clicking on a row selector:
![row_selection_activate](https://user-images.githubusercontent.com/10397980/81566782-0b328000-93a4-11ea-833c-8b57fdb51d95.gif)

First header cell is activated when clicking on header selector as well.

 * igniteui-angular version: 9.1.x
 * browser: N/A

## Steps to reproduce  

1. Open a grid that has some additional interactive elements outside the cells in the header/footer/body like:
- row selectors in header/body
- grouping expander in header
- summary patch before the fist summary cell.
2.  Click on the element
## Result  
The first cell in the related area (header, body, footer) becomes active.

## Expected result  
The cell does not become active as it was no clicked.

**Comment by ddincheva** [comment]
Described in the issue:  #7311
