### ISSUE TITLE
Access to Parent row data inside a row Island

### ISSUE THREAD

**Issue by Poseclop** [IgniteUI/igniteui-angular#7317]
## Question  
I'm using a HierarchicalGrid and trying to access the parent row data from a row island in order to provide it as a parameter to on click Event (see below: _ObjectX_). How can I do that ? I tried to embed the row island in ng-template but no success.
```html
<igx-hierarchical-grid data="[object1, object2,...]>
    <igx-row-island key="listProp" >
        <igx-column field="islandProp1">  
            <ng-template igxCell let-cell="cell" (click)="onClick(cell.rowData, objectX)>
              ...
            </ng-template>
        </igx-column> 
    </igx-row-island>
</igx-hierarchical-grid>
```
Couldn't find a directive in the docs that would do the trick. Thanks in advance. 

 * igniteui-angular version: 9.0.12
 * browser: Chrome

**Comment by ChronosSF** [comment]
Assuming you only need this to work in a two level hierarchy, it should be possible with something like:

```html
<igx-hierarchical-grid #hgrid data="[object1, object2,...]>
    <igx-row-island key="listProp" >
        <igx-column field="islandProp1">  
            <ng-template igxCell let-cell="cell" (click)="onClick(cell.rowData, hgrid.getRowByKey(cell.grid.foreignKey).rowData">
              ...
            </ng-template>
        </igx-column> 
    </igx-row-island>
</igx-hierarchical-grid>
```
