### ISSUE TITLE
We would like to see a feature where Average and Sum are shown on the Ship country level as shown in the screenshot attached.

### ISSUE THREAD

**Issue by Raqtan** [IgniteUI/igniteui-angular#7334]
![igniteui-angular](https://user-images.githubusercontent.com/3083952/81844273-af7f0880-9503-11ea-9190-8b57db9a6404.png)
# Is your feature request related to a problem? Please describe.

**Comment by radomirchev** [comment]
@Raqtan , the feature request is in the list for the current milestone. You could follow the milestone progress on the [Roadmap board](https://github.com/orgs/IgniteUI/projects/122) or in the [Roadmap file](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md). Please follow the issue for specification verification.

**Comment by zdrawku** [comment]
This is the design and solution that we came up with - it's clean and I hope you will find it elegant. We expose `showSummaryOnCollapse` input that manages the summaries visibility on GroupBy row *collapse action*. When the feature is available with our next 10.1.0 alpha version, I will update the issue.

![GroupBy with summaries](https://user-images.githubusercontent.com/11193764/86912699-214f8900-c126-11ea-8bc7-121e9ffeddea.gif)
