### ISSUE TITLE
Should we persist two active nodes at the same time

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7337]
## Description  
Should we persist two active cells at the same time?

 * igniteui-angular version: all
 * browser: all

## Steps to reproduce  

1. Open any dev demo samples
2. Select/click a cell in both parent and child grid

## Result  
Two cells remain active

## Expected result  
IMO it is confusing to hold two active nodes at the same time

## Attachments  
![image](https://user-images.githubusercontent.com/7037740/81923457-5f2ca700-95e6-11ea-85f2-cc8f01b2a795.png)

![image](https://user-images.githubusercontent.com/7037740/81923520-7bc8df00-95e6-11ea-860d-f1a35b937ea1.png)

**Comment by MayaKirova** [comment]
@ddincheva @rkaraivanov @zdrawku  I believe at some point we discussed whether the active style should remain on a grid that no longer has focus as it looks like the grid is still interactable while in fact the focus is no longer on it and you cannot interact with it.

Refer to: https://github.com/IgniteUI/igniteui-angular/pull/6935#issuecomment-608436856

Currently the grid does not clear the active style when blurred hence clicking on elements outside it or tabbing away from it will still leave the active styles.

IMO it would be better if active styles are cleared and are applied only if the grid has focus. Let me know what you think as it is something that should be applied to the base grid and would affect all grids.

**Comment by zdrawku** [comment]
@MayaKirova, thank you for sharing your thoughts on that. We are going to change that behavior in order to maintain only one active state. This will happen after we expose the [active node changing event](https://github.com/IgniteUI/igniteui-angular/pull/7794).

Marking this item as `enhancement` and removing the `question` label
