### ISSUE TITLE
Can select previous default filter template even after defining custom filter template

### ISSUE THREAD

**Issue by Nick-Angel** [IgniteUI/igniteui-angular#7350]
## Description  
If there exists a grid with both custom and default filter templates, once the user clicks on a default filter template badge and then clicks on the column header of a column with a custom filter template, instead of showing the custom filter template a default filter template is shown instead. 
This can be misleading and problematic for users as developers may not have implemented functionality for that column's default filter template if they're already using the custom filter template (say, if they have specific requirements and run filter queries through a backend)

 * igniteui-angular version: 9.0.13
 * browser: all browsers

## Steps to reproduce  

1. Open stackblitz link: https://stackblitz.com/angular/odpnvkldmnr
2. Click on Discontinued badge
3. Click on any other column header

## Result  
The user sees the default filter template (where they can chain filter queries with AND/OR) instead of the custom filter template.

## Expected result  
Upon clicking a column header with a custom filter template defined, the grid should reset to the default view (where it initially shows the filter badges and custom filter templates)

I would assume a variable just needs to be created/checked to see what type of template is defined for the header, and should be checked here in **grid-header.component.ts's public onClick(event):** https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts

(But that's just my guess)

## Attachments  
Below shows the different filter templates (default and custom) being accessible 
<img width="1390" alt="Screen Shot 2020-05-17 at 3 56 56 PM" src="https://user-images.githubusercontent.com/17068639/82158716-88a03980-9857-11ea-8a8f-0f44c4eaf9e1.png">
<img width="1392" alt="Screen Shot 2020-05-17 at 3 57 12 PM" src="https://user-images.githubusercontent.com/17068639/82158717-88a03980-9857-11ea-95f5-10acdd1bbe81.png">
<img width="1392" alt="Screen Shot 2020-05-17 at 3 57 47 PM" src="https://user-images.githubusercontent.com/17068639/82158718-8938d000-9857-11ea-993c-c967fa8eed15.png">
<img width="1391" alt="Screen Shot 2020-05-17 at 3 58 04 PM" src="https://user-images.githubusercontent.com/17068639/82158719-8938d000-9857-11ea-9c40-f31dcabd1776.png">

**Comment by Nick-Angel** [comment]
Hi @simeonoff , is someone available to check out this bug?

**Comment by simeonoff** [comment]
@Nick-Angel I have assigned our Product Owner @radomirchev to this issue. He will be able to give you a better estimate of when we can resolve this issue.

**Comment by radomirchev** [comment]
@Nick-Angel I am going to schedule the issue for the next sprint. The current one is focused on Ignite UI 9.1 release.

**Comment by Nick-Angel** [comment]
Thanks @simeonoff and @radomirchev !
