### ISSUE TITLE
When child grid is scrolled and press arrow down form its last cell the navigation stops

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#7376]
## Description  
When child grid is scrolled and press arrow down form its last cell the navigation stops

 * igniteui-angular version: 9.1
 * browser: n/a

## Steps to reproduce  

1.Open  [sample ](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/multi_column_headers.html)
2. Expand a row
3. In the child grid scroll horizontal to the last cell
4. Click on cell in column ShipCountry
5. Press arrow down

## Result  
The  navigation stops and there are no active cell

## Expected result  
Cell in the next row should be activated

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
@nrobakova I'm not sure which sample you have used to test as it was not specified. I've tried to reproduce it in the hierarchicalGridRemote sample as it has a ShipCountry column in the child, however I was no able to reproduce the issue with the steps provided:

![child_nav](https://user-images.githubusercontent.com/10397980/82910725-a5cdba00-9f73-11ea-9144-a02960a9467b.gif)

Let me know if I'm missing something or if this reproduces in a different sample.

**Comment by nrobakova** [comment]
Hi @MayaKirova , 
Sorry I just forgot to add a link. The bug is reproducible in the samples, in sample for hGrid Multi Column Headers. I updated the bug description 
![hgridNavigation](https://user-images.githubusercontent.com/11463104/82919096-4032fb00-9f7e-11ea-852b-7b9c54086285.gif)
