### ISSUE TITLE
Update igxGrid Column Header Templates Styles

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-angular#738]
### Description  

Header icons and corresponding columns are hard to visually define. Especially having icons in a numeric and string header template next to each other. 

![screen shot 2018-03-08 at 16 03 41](https://user-images.githubusercontent.com/23053821/37155009-6c01b1d0-22ea-11e8-9a09-7b0daf04e15a.png)

### Expected result  
Header Icons will be clearly defined to the corresponding columns.

![screen shot 2018-03-08 at 16 47 20](https://user-images.githubusercontent.com/23053821/37157072-755e4c06-22f0-11e8-8eb9-e00ee7a3e6a8.png)

![screenshot-2018-3-7 the best fastest angular data grid in the world](https://user-images.githubusercontent.com/23053821/37155073-9a8281a6-22ea-11e8-8783-9da2f5f6722a.png)

**Comment by SlavUI** [comment]
This is completed
