### ISSUE TITLE
IgniteUI Grid Header show full text

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#7387]
### DESCRIPTION

The text in the headers isn't showing and the ellipsis appears as you can see:

![image](https://user-images.githubusercontent.com/36885861/82573510-295b6580-9b86-11ea-80e9-a839e1a4b0c4.png)

If I adopt this proposed solution:

https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/120438/igniteui-grid-header-column-text-is-bigger-and-need-to-wrap-it

When I hide columns there is a strange space to the right, the columns do not expand.
I've tried to manually modify everything related to the columns width, but the resize stops working.
The minWidth only applies for the resize, how can I set a minimum column width and columns autosie work at same time??

![image](https://user-images.githubusercontent.com/36885861/82573594-409a5300-9b86-11ea-9c48-5a857ab24598.png)

This error occurs in your sample of column hidding:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column_hiding.html

### STEPS TO REPRODUCE

In this example, if you hide columns and only there are four columns, there is blanc space at right.

https://stackblitz.com/angular/qdbxynxrxod

### SOLUTION

I think that or Grid should show by default all header text or user could set a default min width and grid expand to fill all space when there is blanc space.

**Comment by kdinev** [comment]
@ssg127 I would suggest using the resizing feature, so you allow the application users to adjust column sizes according to the view that they want to get: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column_resizing.html

**Comment by ssg127** [comment]
@kdinev I know the resize, but I want to see the header text al start, not that the user has to be resizing.

This is basic web functionality.

**Comment by kdinev** [comment]
@ssg127 If you just want the text to wrap, then you can always use the `igxHeader`. The other option would be to override the default header css to not apply the '...'.

```css
.igx-grid__th-title {
    white-space: wrap;
    text-overflow: none;
    word-break: break-word;
}
```

**Comment by ssg127** [comment]
@kdinev Could you provide me an example? I've tried the css option but it doesn't work and using igxHeader I could have filtering and ordering anyway? I've read all documentation but I doesn't know how to solve this problem.

**Comment by kdinev** [comment]
@ssg127 If you use the `igxHeader` template, you will still have filtering and sorting. The header template is for the inner portion of the header element - where the header text is located. All the elements rendered by features would still appear.

As for the CSS override, it should work. Do you apply it in the components css/scss file? @simeonoff

**Comment by simeonoff** [comment]
@kdinev @ssg127 I would not modify the styles of the header using this approach. We can't guarantee the header class won't change in future releases. This is a conscious decision we've made, the text doesn't wrap by default. You can provide your own header template, which can be styled the way you want, just like @kdinev suggested.

If you still want to overwrite the default styles at your own risk, you can do the following in your global css/scss file:

```css
.igx-grid__th {
   align-items: center;
}

.igx-grid__th-title {
   white-space: initial;
   text-overflow: unset;
   word-break: break-word;
   line-height: normal;
}
```

**Comment by ssg127** [comment]
Thank you @kdinev and @simeonoff , I've tried your solutions but it doesn't do exactly what I need. 
If I use the CSS solution, I can see all text but in vertical position and I want to see all the text in horizontal.

![image](https://user-images.githubusercontent.com/36885861/83005040-a36d6d80-a010-11ea-8434-91f5399ad460.png)

In the other hand, if I use `igxHeader`, I have the header text in a `div` and I set min-width and width to fit-content but It doesn't works, because the `<span class="igx-grid__th-title">` and the `<igx-grid-header>` don´t grow, so the header text isn't seen.

![image](https://user-images.githubusercontent.com/36885861/83006353-64401c00-a012-11ea-8468-ec59e0f0b0b6.png)

![image](https://user-images.githubusercontent.com/36885861/83006408-7621bf00-a012-11ea-8976-fd9fe3bc2281.png)

I think that is easy for you set a new property defaultMinValue, and then, this problem will be resolved. If it is not possible, could you give me another solution to see all text in horizontal?

**Comment by simeonoff** [comment]
So you want your column to automatically resize to fit the header text, regardless of how long it is?

**Comment by ssg127** [comment]
Yes, exactly @simeonoff . But If I set a width, when I hide columns there is a strange space to the right, the columns do not expand as you can see at first post.

**Comment by simeonoff** [comment]
I don't think this is currently possible out of the box. 

There's a method in the `IgxColumnResizingService` service called `autosizeColumnOnDblClick`, which will size the column to fit the size of the largest cell/header when the end-user double-clicks on the header border, however, this is not publicly exposed or documented.

Probably the team and @kdinev may decide to expose it under some flag, but I believe this will be a fairly expensive operation just because you have to iterate over every visible cell in every visible column to determine the size to use for each column. This doesn't sound terrible if your content never scrolled, but once you start scrolling horizontally/vertically, this whole thing will need to be re-calculated.

@kdinev any thoughts?

**Comment by ssg127** [comment]
Yes, I know about this method, but I have more than 100 rows so I have scroll and I only want to adjust to header text.

**Comment by kdinev** [comment]
@ssg127 What we can do is add a flag parameter to the `autosize(header?: boolean)` method, which will denote whether the autosize should be performed according to the cell sizes, or to the header size. Do you think this solution would be sufficient for your application?

**Comment by ssg127** [comment]
@kdinev In that case at what point should I call autosize, onColumnInit and onColumnVisibilityChanged? Autosize should be called only once, at init of grid.
If it's possible to call that method and it fits the header it would be enough.
