### ISSUE TITLE
Allow setting of the name of the worksheet in exported workbook in IgxExcelExporter

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#7396]
## Question  
Is there anyway to set or change the worksheet name when we export grid to excel. I am able to set only the filename and not able to configure worksheet name.

Kindly help me with demo or any document to solve the above issue.

 * igniteui-angular version: 8.2.9
 * browser: Chrome

**Comment by wnvko** [comment]
The name of the worksheet is the default `Worksheet1`. Right now there is no way to change the name of the generated worksheet. I've marked this as feature request. The name of the worksheet could be added to [`IgxExcelExporterOptions`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxexcelexporteroptions.html).

**Comment by Raju-N** [comment]
Thanks @wnvko. Will inform the customer on the same.
