### ISSUE TITLE
Multi row layout is not previewed correct in IE11

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#7397]
## Description  
Multi row layout is not previewed correct in IE11

 * igniteui-angular version: 9.0, 9.1
 * browser: IE11

## Steps to reproduce  

1. Open [sample](https://www.infragistics.com//angularsite/components/grid/multi_row_layout.html#feature-integration) in IE 11

## Result  
The cells are not positioned correct

## Expected result  
As in other browsers the cells should be correct or we should document that they do not work in IE11

## Attachments  
![image](https://user-images.githubusercontent.com/11463104/82890629-2af5a680-9f55-11ea-9cdb-a45002f8f5f5.png)

**Comment by ChronosSF** [comment]
AFAIR, IE11 supports the grid layout but handles it a little bit differently. We'll take a look
