### ISSUE TITLE
Set style to igxVirtualHelper

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#7415]
How could I set style to scrollbars from `igxGrid` because the scrollbar is `igx-virtual-helper` and I can't set format to this as another scrollbar. I need to change the width of the scrollbar thumb and scrollbar track but I'm not able to do this correctly.

How could I do this?

**Comment by simeonoff** [comment]
Our upcoming release will contain a new [scrollbar theme](https://www.infragistics.com/products/ignite-ui-angular/docs/9.1.0/sass/#function-igx-scrollbar-theme) that will allow you to customize the colors and size.
