### ISSUE TITLE
When cell selection is "none" clicking a grid cell scrolls the grid to the top and activates the first cell.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#7418]
## Description  
After scrolling down and activating a cell for the first time when selection is disabled, the grid scrolls and activates the first cell instead.

 * igniteui-angular version: 9.1.x
 * browser: 

## Steps to reproduce  

1. Run the following sample: https://stackblitz.com/angular/ygpqnvbpngm
2. Select cell selection to be 'none'
3. Scroll down to the middle and select a cell.

## Result  
The grid scrolls and activates the first cell.

## Expected result  
The clicked cell should be activated. The grid should not scroll.

**Comment by nrobakova** [comment]
This issue is not reproducible with rc1. Can you check it here:
https://stackblitz.com/edit/angular-4rhncq-q6zqq7?file=src/app/app.component.ts

**Comment by MayaKirova** [comment]
@nrobakova I can still reproduce it, here are the exact steps used on the stackblitz you have linked:

![wrong-active-cell](https://user-images.githubusercontent.com/10397980/83260588-ba53c180-a1c2-11ea-9541-6990761d31fc.gif)

Please note that the first click in the grid needs to be a cell from the middle of the grid and cell selection must be none.
