### ISSUE TITLE
Clicking on movable column with ctrl + click emits onColumnMovingStart event

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular#7439]
## Description  
If we have a scenario, where we want to clear all column selection on column moving start event **ONLY**, this will not be possible, because of the current behavior of the grid on this event.
The column moving start event always fires when multiple columns are selected with  **ctrl** + **click** .

## How to reproduce
Having this sample on [Stackblitz](https://stackblitz.com/edit/angular-eneu5t-dwxcxw), try to select multiple with **ctrl** + **click**.

## Result
Only one column gets selected.

## Expected Result
Multiple columns should be selected

**Comment by 3phase** [comment]
I'd close the issue, because the given behavior is reproducible by design. The `onColumnMovingStart` event emits on `pointerdown`, while `onColumnSelectionChange` emits on `click`. When clicking, a `pointerdown` is fired and right after a `click` gets emitted. 
You may use `onColumnMoving` instead.
