### ISSUE TITLE
IgxGridComponent watermark showing in Version 9.1.0

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#7468]
## Description  
Not sure why a Watermark is displayed in the most recent version of igniteui-angular 9.1.0? 
 Watermark "Trial version of IgniteUI for Angular" displays inside bottom right corner of IgxGridComponent.  The word "trial" displays inside background of IgxGridComponent

 * igniteui-angular version: 9.1.0
 * browser: Version 83.0.4103.61 (Official Build) (64-bit)

## Steps to reproduce  

1. Open View that contains IgxGridComponent
2. Watermark displays inside bottom right corner of IgxGridComponent
3. The word "trial" displays inside background image of IgxGridComponent

## Result  
What is the actual result after following the steps to reproduce?
Watermark **"Trial version of IgniteUI for Angular"** displays inside bottom right corner of IgxGridComponent.  The word "trial" displays inside background of IgxGridComponent

## Expected result  
What is the expected result after following the steps to reproduce?
Watermark should not display inside IgxGridComponent. The word "trial" should not display inside background of IgxGridComponent.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by zdrawku** [comment]
Hello @brookhutchinson, In addition to the 9.1.0 release we've also changed our licensing of Ignite UI for Angular product. We've added a "Trial" watermark to the packages that we post on NPM (which are free to use). This [topic ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing.html)outlines all the details necessary to remove the watermark and acquire your licensed version.

Keep in mind that If you are building a commercial product or your license [has expired](http://www.infragistics.com/renewal?_ga=2.107759744.342757142.1590995627-287085328.1590995627), you will need to [acquire a commercial license](https://www.infragistics.com/how-to-buy/product-pricing?_ga=2.107759744.342757142.1590995627-287085328.1590995627). This will enable you to use our private npm feed hosted on https://packages.infragistics.com/npm/js-licensed/ for development (without a trial watermark). There you will find the latest versions of the Ignite UI for Angular packages. If you have a valid commercial license, you can use this private feed and you will have access to the full version of Ignite UI for Angular.

If you are building a non-commercial product [contact us](https://www.infragistics.com/about-us/contact-us?_ga=2.11226294.342757142.1590995627-287085328.1590995627) and we will provide you with the appropriate license.
