### ISSUE TITLE
Scrollbars Now Invisible in igniteui-angular@9.1.0's Data Grid

### ISSUE THREAD

**Issue by Nick-Angel** [IgniteUI/igniteui-angular#7469]
## Description  
After upgrading from igniteui-angular 9.0.15 to 9.1.0, the scrollbars in our data grid were previously made permanently visible by `::webkit-scrollbar` and other selectors, but now the vertical scrollbar is now permanently invisible and shows no scrollbar on scroll. Whether the data grid is in "trial mode" with the watermarks or "licensed mode," the scrollbar is still invisible. Data grids in Firefox in particular scroll at unbelievably fast speeds and when that's coupled with a lack of both vertical and horizontal scrollbars, it makes for a difficult user experience. This may be specifically an issue for MacOS users (I haven't confirmed these same issues on Windows)

Question:
Is there a version of the commercial package for igniteui-angular that we can roll back to while this is being looked at? There don't seem to be any 9.0.x versions.

## Steps to Reproduce
1. Visit https://stackblitz.com/angular/bbmxnnrnkjr?file=package.json preferably on Firefox
2. Notice the lack of visible scroll bars and high scroll speeds
3. Compare with igniteui-angular@9.0.15 in package.json

## Result
Invisible scroll bars

## Expected result  
Both the vertical and horizontal scrollbars are visible and ideally scroll speeds for Firefox are adjusted (if possible).

**Comment by zdrawku** [comment]
Similar to https://github.com/IgniteUI/igniteui-angular/issues/7351

**Comment by ChronosSF** [comment]
Hey @Nick-Angel ,

On MacOS scrollbar visibility is controlled by the end-user through OS settings:
    
System Preferences > General > Show Scroll Bar > Choose "Always"

The sample you linked doesn't seem to contain any CSS that would modify this OS behavior. If you could provide one we will check if we changed anything that would affect your workaround.

We'll try to resolve the Firefox issue with the scrolling speed but I'll keep you updated on that in #7351 .

**Comment by Nick-Angel** [comment]
Hi @ChronosSF, 

I understand that the end-user can set scroll bars to always show, but I don't believe that this is a complete solution. With users who prefer to keep scrollbars visible only on the event of a scroll, these scrollbars are not visible whatsoever. There is also the issue that Firefox scrollbars (under the MacOS default Show Scroll Bar setting) in Ignite UI 9.0.15 show on scroll events but in Ignite UI 9.1.0 they are invisible. In regards to the sample I linked not modifying this OS behavior, do you mean that there is no CSS that modifies the OS behavior when Show Scroll Bar is set to "Always?" In that case, I agree but the issue still stands when Show Scroll Bar is set to default. If you need any points of clarification just let me know.

Thank you for looking into this!

**Comment by Nick-Angel** [comment]
I have attached a video illustrating the behavior and the difference between 9.0.15 and 9.1.0 in Firefox!

**Comment by Nick-Angel** [comment]
Here is a video of the 9.1.0 data grid in firefox with the bug:
[IgniteUI_9.1.0_Bug.mov.zip](https://github.com/IgniteUI/igniteui-angular/files/4725079/IgniteUI_9.1.0_Bug.mov.zip)

**Comment by Nick-Angel** [comment]
And here is a video of the expected behavior in firefox Ignite UI v9.0.15 
[IgniteUI_9.0.15_Expected.mov.zip](https://github.com/IgniteUI/igniteui-angular/files/4725085/IgniteUI_9.0.15_Expected.mov.zip)

**Comment by skrustev** [comment]
Hi @Nick-Angel, 

I was able to reproduce for the scenario with scrollbar visible when scrolling and wanted to let you know that we are looking into providing a fix for it.

**Comment by skrustev** [comment]
Hi @Nick-Angel,

I was able to reproduce the scenario with scrollbar visible when scrolling and wanted to let you know that we are looking into providing a fix for it.

**Comment by Nick-Angel** [comment]
Thanks @skrustev! So we can expect with a coming update Firefox scrollbars to be visible on scroll? This would be great news.
