### ISSUE TITLE
Igx-autocomplete issue when programatically opened 

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#7486]
## Question  
I have an issue with displaying the autocomplete items when the input-element is focused, and I'm not sure if I'm doing it right.

@ViewChild('revItemsPanel') revItemsPanel: IgxAutocompleteDirective;
        this.revItemsPanel.open(); 

expected view:
![image](https://user-images.githubusercontent.com/43247999/83767130-87577500-a67d-11ea-9f26-6c4b2539295f.png)

actual view:
![image](https://user-images.githubusercontent.com/43247999/83767147-8de5ec80-a67d-11ea-887d-271bd3aa37ce.png)

**Comment by wnvko** [comment]
@VirtualisProject I was trying to reproduce your issue in this [Stackblitz](https://stackblitz.com/edit/angular-exkl1j?file=src%2Fapp%2Fautocomplete%2Fautocomplete.component.ts) with no success.
By default `IgxAutoComplete` is shown attached to the input. It is using [`AutoPositionStrategy`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/autopositionstrategy.html). In this strategy `overlayService` is trying to show the drop down containing auto complete items bellow the input. If there is no space it will try to show it above the input. If again there is no space it will push up the drop down until it is completely visible.
However, looking at your pictures you have enough space for items to be shown. One thing cumming to my mind - are you set your custom `overlaySettings` for the `autoComplete`? Also can you reproduce this in a sample and give it to us for further investigation?

**Comment by VirtualisProject** [comment]
Hello @wnvko and thank you for the thourall response. I will double check that this behavior is not caused by some of our css overrides etc and get back to you or close the ticket if i can't reproduce in the provided stackblitz
