### ISSUE TITLE
Private Infragistics NPM repository gives HTTP 500

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#7488]
## Description
Cannot access the private `npm` repo @ `https://packages.infragistics.com/npm/js-licensed/`

 * igniteui-angular version: 9.1
 * browser: build issue, so "all"

## Steps to reproduce
1. Run `npm install` or `yarn` on a project

## Result  

```log
04-Jun-2020 16:48:47 | npm ERR! code E500
04-Jun-2020 16:48:47 | npm ERR! 500 Internal Server Error - GET https://packages.infragistics.com/npm/js-licensed/@infragistics%2figniteui-angular
```

I have tried with several combinations of Auth token, username / password.

This is the masked content of `~/.npmrc`

```npmrc
@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/
//packages.infragistics.com/npm/js-licensed/:_password="OUR_PASSWORD="
//packages.infragistics.com/npm/js-licensed/:username=USERNAME!!COMPANY.com
//packages.infragistics.com/npm/js-licensed/:email=USERNAME@COMPANY.com
//packages.infragistics.com/npm/js-licensed/:always-auth=true
//packages.infragistics.com/npm/js-licensed/:_auth="OUR_AUTH_TOKEN"'
```
Tried commenting the `:_auth`, only the `:_password`, then also the `:username`.

Makes no difference.
It worked before.

## Expected result  
It has worked today until about 14:00 GMT, June 4th 2020

## Attachments
None

**Comment by catull** [comment]
Nope.

With `~/.npmrc` containing this:

```npmrc
@ourcompany:registry=https://artifactory.ourcompany.com:443/artifactory/api/npm/npm-virtual/ 

@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/
//packages.infragistics.com/npm/js-licensed/:always-auth=true
//packages.infragistics.com/npm/js-licensed/:_auth=MY_AUTH_TOKEN

@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=OUR_FONTAWESOME_AUTH_TOKEN
```

The `npm` build breaks with:

```log
04-Jun-2020 18:44:55 | npm ERR! code E500
04-Jun-2020 18:44:55 | npm ERR! 500 Internal Server Error - GET https://packages.infragistics.com/npm/js-licensed/@infragistics%2figniteui-dockmanager
```

Please fix this.

**Comment by zdrawku** [comment]
Hey @catull, we've managed to reproduce the problem with the following configuration:
![image](https://user-images.githubusercontent.com/11193764/83890627-af65d780-a754-11ea-80a6-
8a9f68fd4347.png)

It's possible for the problem to be caused by your token.

I wanted to update you that we are working on it.

**Comment by damyanpetev** [comment]
Just FYI, I tried messing with the token in case a misformatted token can cause the error - removed large chunks from the end and I'm still getting `401 Unauthorized` which is expected. Only when I put something completely off (like `MY_AUTH_TOKEN`) did we manage to repro to 500 error. Might be worth checking with a fresh token, though I doubt the one you had was that far off somehow.

But you said your error had a time component to it - i.e. same `npmrc` config without modifications just suddenly stopped working? Is that happening still or is the error intermittent?

**Comment by kdinev** [comment]
@catull Are you still experiencing this issue?

**Comment by catull** [comment]
Nope, works now.
