### ISSUE TITLE
Add Toolbar to the igxGrid

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-angular#749]
- [ ] Column Pinning UI - #714

**Comment by sbozalieva** [comment]
![base copy 7](https://user-images.githubusercontent.com/23053821/39819142-5c518b06-53ab-11e8-8326-bea5d88131db.png)
![base copy 8](https://user-images.githubusercontent.com/23053821/39819143-5c760a12-53ab-11e8-9a0d-6b1465ffaad9.png)
![base copy 9](https://user-images.githubusercontent.com/23053821/39819144-5c9750dc-53ab-11e8-8ce9-d8ed88a17760.png)
![base copy 10](https://user-images.githubusercontent.com/23053821/39819145-5cb5a6ae-53ab-11e8-8a7f-b87238287efe.png)

**Comment by kdinev** [comment]
We should be very careful with the excel export dependency, and should make sure it and all of its dependencies are not loaded when the export button is not enabled in the toolbar.
