### ISSUE TITLE
Sorting Indicator on all Grid components 

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#7493]
## Is your feature request related to a problem? Please describe.
When user apply sorting on multiple columns on grid components, it is difficult to know which is first, second column. User has to remember the order of sorting on columns. 

## Describe the solution you'd like
There should sorting indicator on grid column. When user perform first sorting column should show 1. it is rounded and highlighted. then if user do second sorting it should show 2 along with Arrow. This way it will be easy to understand how sorting is applied on multiple columns. 
i am looking for Index indicator on column header itself along with Arrow.

**Comment by radomirchev** [comment]
@deepakvia, the feature request is in the list for the current milestone. You could follow the milestone progress on the [Roadmap board](https://github.com/orgs/IgniteUI/projects/122) or in the [Roadmap file](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md).
