### ISSUE TITLE
Links on "explore code" are wrong

### ISSUE THREAD

**Issue by shig2k1** [IgniteUI/igniteui-angular#75]
The blue Explore code button </> on samples links to:
https://github.com/IgniteUI/**igniteui-angular**/blob/master/samples/igTreeGrid/igTreeGrid.html

should be igniteui-angular2

**Comment by kdinev** [comment]
@shig2k1 Is this issue intended for the igniteui-angular2 repo? Because the link here is correct, but I see that it's not working in the angular2 repo.

**Comment by kdinev** [comment]
I created an issue in the igniteui-angular2 repo and I'm closing this one.
