### ISSUE TITLE
igx-grid excelStyleFilter list of entities disappear

### ISSUE THREAD

**Issue by EvgeniyZhukovets** [IgniteUI/igniteui-angular#7504]
## Description  
Disappearing list of entities after scrolling to the bottom in excelStyle filter.

 * igniteui-angular version: 9.0.1
 * browser: Google Chrome

## Steps to reproduce  

1. Create igx-grid with excelStyleFilter
```
<igx-grid #grid1 [data]="states" [autoGenerate]="false" displayDensity="cosy" width="600px"
              height="600px" [paging]="true" [perPage]="10" [allowFiltering]="true" [filterMode]="'excelStyleFilter'">
      <igx-column-group>
        <ng-template igxHeader let-column>
          <h6 translate>...</h6>
        </ng-template>
        <igx-column field="id" header="State" [dataType]="'string'" [sortable]="true" [editable]="false"
                    [resizable]="true" width="85px">
          <ng-template igxHeader let-column>
            <igx-icon [isActive]="false">flag</igx-icon>
          </ng-template>
        </igx-column>
      </igx-column-group>
      ...
</igx-grid>
```
2. Click on filter icon
3. Scroll down
4. Click outside filter window
5. Repeat Step 2

## Result  
Disappeared list of entities

## Expected result  
Able to filter this column

## Attachments  
1) Open filter:
![image](https://user-images.githubusercontent.com/22504733/83972933-c4c13a00-a8eb-11ea-92ec-71f728a7882f.png)
2) Scroll to the bottom:
![image](https://user-images.githubusercontent.com/22504733/83972971-ede1ca80-a8eb-11ea-9507-10903c942cf5.png)
3) Opened filter after clicking outside filter window:
![image](https://user-images.githubusercontent.com/22504733/83972996-15389780-a8ec-11ea-8f17-6168ed91b220.png)

**Comment by DiyanDimitrov** [comment]
This issue #6893 is already fixed in the latest version.
