### ISSUE TITLE
Autocomplete.close reopenes the drop down

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#7508]
## Description  
It seems like the close method for the auto completes opens the drop down before closing it again. 

 * igniteui-angular version: 9.0
 * browser: Chrome

## Steps to reproduce  

1. Call the close method on an already closed autocomplete

## Result  
When calling close on a closed autocomplete, the dropdown flashes for a show moment.

## Expected result  
Calling close on a closed autocomplete should ignore the command.

**Comment by wnvko** [comment]
I am not able to reproduce this [here](https://stackblitz.com/edit/angular-fsw94n?file=src%2Fapp%2Fautocomplete%2Fautocomplete.component.html)
I've tested this in Google Chrome, MS Edge, Mozilla Firefox and Opera browsers.
@Eralmidia can you share a sample showing this issue?

**Comment by Eralmidia** [comment]
Hi Milko

The issue can be illustrated when I do something like this: https://stackblitz.com/edit/angular-3vm5bm?file=src%2Fapp%2Fautocomplete%2Fautocomplete.component.ts

This is a modified version of the sample on the docs page. The only diffence is that I automtically close the dropdown on any key event. As you can see, the box shadow of the drop down will flash for each character, even if there are no matches.

What I'm trying to achieve, is that the autocompete should not be active before a certain number of characters. So if the user has only inputed 1 or 2 characters, the auto complete should remain closed.

**Comment by wnvko** [comment]
Hi @Eralmidia ,
To prevent opening of the autocomplete drop down you may handle `onOpening` event of the drop down itself. Please check this [Stack Blitz](https://stackblitz.com/edit/angular-3vm5bm-9xyhkq?file=src%2Fapp%2Fautocomplete%2Fautocomplete.component.ts). Here the drop down does not show until three characters are entered in the input.

**Comment by Eralmidia** [comment]
Neat, I'll give that a go then. Thanks for the assistance 👍
