### ISSUE TITLE
igx-checkbox can't be checked when a parent element has "igx-form-group" class.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#754]
### Description  
igx-checkbox can't be checked a when parent element has "igx-form-group" class.

### Result  
When I markup as follows, igx-checkbox can't be checked.
```
<div class="igx-form-group">
  <igx-checkbox>label</igx-checkbox>
</div>
```

### Expected result  
igx-checkbox should be checked whatever class parent element has.

### Attachments  
[igx-checkbox.zip](https://github.com/IgniteUI/igniteui-angular/files/1801650/igx-checkbox.zip)
- angular: 5.2.8
- igniteui-angular: 5.2.1

**Comment by simeonoff** [comment]
The igx-form-group class will be depricated with the next release. The intent of this class was to be used **ONLY** with inputs of type text, email, tel, etc, as shown in the examples. I don't remember us ever showing using this class with igx-checkbox.

**Comment by tkiryu** [comment]
@simeonoff , you mean, [igxFormContainer](https://github.com/IgniteUI/igniteui-angular/issues/764) will replace `igx-form-group` in the next release, am I correct?

**Comment by simeonoff** [comment]
@tkiryu yes, the new component will bring some breaking changes related to the input and its styling. So yes, you are correct, although the exact name is igxInputGroup.

**Comment by tkiryu** [comment]
@simeonoff , thank you for the information!
