### ISSUE TITLE
Input type date is not visualized correctly when used inside input group

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#7548]
## Description  
Display value is cut when setting the html input type attribute to date and this input is used with the input group/igxInput directive.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Add html input tag with igxInput directive inside input group
2. Set input type to date.

## Result  
Display value is cut.

## Expected result  
Display value is shown correctly.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![eeee](https://user-images.githubusercontent.com/7972965/84266646-8024e100-ab2d-11ea-8fc2-17152f50867a.png)

**Comment by Lipata** [comment]
@SAndreeva I will suggest using igxDateTimeEditor directive, if possible https://www.infragistics.com/products/ignite-ui-angular/angular/components/date_time_editor.html

**Comment by simeonoff** [comment]
> @SAndreeva I will suggest using `igxDateTimeEditor` directive, if possible https://www.infragistics.com/products/ignite-ui-angular/angular/components/date_time_editor.html

We will still implement a fix for the visual bug.

**Comment by kdinev** [comment]
Related #6544
