### ISSUE TITLE
disabled igx-datePicker control functionality not working for 'dropdown' mode

### ISSUE THREAD

**Issue by SC003** [IgniteUI/igniteui-angular#7577]
# Description  
On setting [disabled] = "true" only input part gets disable. User is able to click calender icon for selecting date and also cancel button will clear the selected date

 * igniteui-angular version: 9.1.0
 * browser: chrome

## Steps to reproduce  

Check below url with setting property [disabled]="true" for editable dropdown
https://stackblitz.com/angular/yryklkvbxgv?file=src%2Fapp%2Fdatepicker-sample-3%2Fdatepicker-sample-3.component.html

## Result  
only input part gets disabled. user is able to click on date/cancel  icon and change/clear the date.

## Expected result  
date and cancel button icon should be disabled.

## Attachments  
[datepicker-disabled property not working.zip](https://github.com/IgniteUI/igniteui-angular/files/4769264/datepicker-disabled.property.not.working.zip)

**Comment by SC003** [comment]
This is the high priority production level issue, please provide solution asap.

**Comment by SC003** [comment]
Is this released or not?
what changes should I need to do to get these updated feature.

**Comment by Lipata** [comment]
@SC003 We are testing it and when it is merged, it will be released next week.
