### ISSUE TITLE
Clicking on row selector check box, scrolls the grid to the first cell

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#7583]
## Description  
Clicking on row selector check box, scrolls the grid to the first cell

 * igniteui-angular version: 9.1
 * browser: n/a

## Steps to reproduce  

1. open dev sample gridColumnMoving
2. Scroll grid down
3. Click on the last row row selector checkbox

## Result  
The grid is scrolled to the first row cell and the selected row is not visible

## Expected result  
The selected row should be vissible

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ddincheva** [comment]
This problem is already addressed in issue #7311
