### ISSUE TITLE
Export to excel using IgxExcelExporterService performance issue

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#7597]
## Description  
I am exporting the grid data using IgxExcelExporterService. It is working fine with less data however if there is huge data the browser becomes unresponsive for few seconds.

 * igniteui-angular version: 8.2.9
 * browser: Chrome

## Steps to reproduce  

1. Load grid with more data. 35k and above rows, 40 columns
2. Export the grid data using IgxExcelExporterService.

## Result  
Browser becomes unresponsive.
For 35k rows and 40 columns - approx 6 seconds unresponsive

**Comment by kdinev** [comment]
Related to #6673

**Comment by DiyanDimitrov** [comment]
This issue was resolved by the fix of #6673.
