### ISSUE TITLE
Grid full screen feature

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#7599]
## Is your feature request related to a problem? Please describe.
We want to show the grid in full screen mode. Currently this feature is not available in ignite ui. So we have implemented work around. Till now it is working fine but from Angular 9 it is not working. it will be great if you can provide this feature in built on ignite ui component.  See attached sample.

## Describe the solution you'd like
provide some button on grid or other component so we can display all type of grid component in full screen. And all grid functionality should work in full screen. See attached sample. 

## Describe alternatives you've considered
We found alternative but it is not working on Angular 9. See attached sample.
[GridDemoApp.zip](https://github.com/IgniteUI/igniteui-angular/files/4780216/GridDemoApp.zip)

**Comment by skrustev** [comment]
Hello @deepakvia,
Have you tried using the native browser full screen and sizing the grid to fit 100% when entering it and sizing it down back when exiting the browser full screen?

**Comment by skrustev** [comment]
Hello @deepakvia,
Have you tried using the native browser full screen and sizing the grid to fit 100% when entering it and sizing it down back when exiting the browser full screen to achieve this effect as well?

**Comment by deepakvia** [comment]
there are issues in doing that. it will be great if you can provide this functionality. then it will be well integrated with ignite components.

**Comment by ChronosSF** [comment]
Hi @deepakvia ,


There is best implemented on an application level. For example you could create a dialog with height 100vh and width 100wh, that contains your grid and show it on demand. 

We can't find good scenarios that would make this functionality beneficial to the product.
