### ISSUE TITLE
If use igx-grid-footer, the bottom row of igxGrid is not visible.

### ISSUE THREAD

**Issue by furugen** [IgniteUI/igniteui-angular#7602]
## Description  
If use igx-grid-footer, the bottom row of igxGrid is not visible.

 * igniteui-angular version: 9.x
 * browser: Google Chorome

## Steps to reproduce  
1. Please visit the following demo page.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection_based_aggregates.html

2. Scroll down to the bottom of the IgxGrid.
![image](https://user-images.githubusercontent.com/8131662/84755068-2ecc9400-affc-11ea-90dc-e50f293facc7.png)

## Result  
I can't see the bottom row.

## Expected result  
I can see the bottom row.

## Attachments  
![image](https://user-images.githubusercontent.com/8131662/84755068-2ecc9400-affc-11ea-90dc-e50f293facc7.png)

**Comment by zdrawku** [comment]
@furugen I believe this problem is fixed in versions [9.0.18](https://github.com/IgniteUI/igniteui-angular/releases/tag/9.0.18) and 9.1.2

**Comment by MayaKirova** [comment]
Duplicate of https://github.com/IgniteUI/igniteui-angular/issues/6065, which is already fixed.
