### ISSUE TITLE
Cannot close IgxSelect from it's icon

### ISSUE THREAD

**Issue by onlyexeption** [IgniteUI/igniteui-angular#7607]
## Description  
Clicking on the IgxSelect icon when the drop down is already opened, doesn't close it but instead reopens it. 

 * igniteui-angular version: 9.0.x
 * browser: all

## Steps to reproduce  

1. Open [Advanced Filtering Sample](https://stackblitz.com/edit/angular-mefb7f)
2. Click on "AND" Group.
3. Open select.
4. Click on select's arrow icon.

## Result  
IgxSelect remains open.

## Expected result  
IgxSelect should close.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
Closing that issue, because 9.0.x is not supported. From 9.1.x above the problem should not be presented.
