### ISSUE TITLE
How to make smooth scrolling in an IgxForOf component

### ISSUE THREAD

**Issue by vazikh-yunusov** [IgniteUI/igniteui-angular#7635]
## Question  

How to make smooth scrolling in an IgxForOf component? I used igxFor bound to remote service according to your instructions, but scrolling is not smooth. I have full chunk scrolling, instead of smooth scrolling

 * igniteui-angular version: 9.1
 * browser: Google Chrome

**Comment by ChronosSF** [comment]
Hey,

I assume you are used one of the samples in https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html as base? Which one?

Generally speaking, if you have remote virtualization there is always going to be a cutoff point where new data has to be fetched and the scrolling hiccups. If remote virtualization is not a must-have for your application it's always better to just feed the grid all its data and then scrolling will be smooth across the whole data.
