### ISSUE TITLE
Create igxInputGroup component 

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#764]
### Description  
New component should be created along with directives that will help to configure all form functionalities provided by the new style capabilities, that the Design team created.

Please follow the [specification](https://github.com/IgniteUI/igniteui-angular/wiki/Input-Group-Specification).

**Comment by simeonoff** [comment]
Is this name decided upon?

**Comment by rkaraivanov** [comment]
@simeonoff No.
