### ISSUE TITLE
IgxCalendar locale defaults to different values between Chrome/Firefox and IE/Edge

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#765]
### Description  
Run an Angular application with IgxCalendar, do not touch the locale property and run the sample.

### Steps to reproduce  

Chrome and Firefox will display the calendar in "en" culture, which is the default and expected, while Ie/Edge will display the calendar in the OS region/language.

**Comment by zdrawku** [comment]
Fixed with PR https://github.com/IgniteUI/igniteui-angular/pull/709
