### ISSUE TITLE
Igx-Grid to show/have summary in the collapsed view after grouping it by columns.

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#7675]
## Is your feature request related to a problem? Please describe.

IGX-GRID Feature Request:
Our clients want aggregation values to be visible in the collapsed view when we group by any column.
So just check the image below:
![summary](https://user-images.githubusercontent.com/20819281/85572968-15a69180-b653-11ea-9a6a-eb7ddac7350e.PNG)

Clients want one summary per column in the space just after the grouping column_name and records count, for each column.

## Describe the solution you'd like

So just after the column name and count, we would ideally want the ability to show at-least single summary, if not multiple for each column,  as multiple summaries might cause the grouping row to expand, which i understand.

But to get faster insight after grouping it is necessary to provide summary of each column after grouping in the collapsed view.

####
Let me know whats your view on it, and if you think this will be considered as a feature request or you want more detail about the feature 
request.

Or if there is an existing solution to do such thing let me know.

**Comment by kdinev** [comment]
@amitmoondra The current grouped row summary is fully templatable and can be populated with any summary data on the grouped rows. Example can be found right before the paging section here:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/groupby.html#group-by-with-paging

**Comment by zdrawku** [comment]
Konstantin's recommendation covers your question, take a look at [the sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/groupby.html#group-by-with-paging) for more information. You can benefit from the GroupBy row templating and easily define your own visual elements, or for example use the grid-summary-row directly:

```html
<ng-template igxGroupByRow let-groupRow>
	<igx-grid-summary-row [style.width.px]='grid1.calcWidth' [gridID]="id"
		[summaries]="printSummaries(groupRow)" [index]="groupRow.index" class="igx-grid__summaries" #summaryRow>
	</igx-grid-summary-row>
</ng-template>
```

```ts
public printSummaries(row){
      const rowSummary = new Map<string, any[]>();
      this.grid1.columnList.filter(col => col.hasSummary).forEach(colm => {
        rowSummary.set(colm.field, colm.summaries.operate(row.records.map(c => c[row.expression.fieldName])));
      });

      return rowSummary;
}
```

@amitmoondra I am marking this **feature-request** as duplicate, [this ](https://github.com/IgniteUI/igniteui-angular/issues/7334)is the item that you can use for tracking and status updates.
