### ISSUE TITLE
Datetime or Time in avaliable type of column

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#7678]
## DESCRIPTION
It is necessary to be able to have time columns, either an independent column or integrating it with the date column.

With the current functionality, the column can be formatted, but when using excelStyleFilter in the select the time always goes to 0 and cannot be filtered taking into account the hours. A timePicker should be used.

## EXAMPLE
![image](https://user-images.githubusercontent.com/36885861/85676168-a5395800-b6c6-11ea-834b-a811c2c57532.png)

## SOLUTION
The solution is to create a new datatype, either DateTime or Time and then use date-time-picker or time-picker.

**Comment by ssg127** [comment]
Nothing? This is a very useful thing and easy to develop I think.

**Comment by kdinev** [comment]
@ssg127 This actually looks like a bug to me. I changed the labels to reflect that. Can you tell us which version you're using?

**Comment by ssg127** [comment]
@kdinev I've seen this error with all versions I've tried, but now, I have two projects, one with 8.2.29 and another with 9.0.20. I used to try new versions but the error is always present. 

Anyway, I think a datetime or time column-type is more useful so that it can also be filtered by time, that's why I added the feature-request label. Correcting the format might be a partial solution, but a new column is better.

**Comment by ssg127** [comment]
Any news about this change?

**Comment by kdinev** [comment]
@ssg127 We haven't gotten to implementing a `time` type of column. 

@zdrawku @radomirchev When do you think this can be prioritized?

**Comment by zdrawku** [comment]
We are adding this feature in the current Milestone 15 planning - it will be considered along with Percent and Currency type columns.

**Comment by ssg127** [comment]
@zdrawku I have seen that you have closed the related [issue](https://github.com/IgniteUI/igniteui-angular/issues/8331). Will this be included in the next version?

**Comment by kdinev** [comment]
@ssg127 The related issue was about Percent and Currency type columns. The time column goes in development now, since the percent and currency are already done. @zdrawku

**Comment by ssg127** [comment]
I have another question, the excelStyleFilter will allow to filter by time or only by date as before? I speak about datetime columns or time columns.
