### ISSUE TITLE
When use grid.columns getter the error is thrown in the console

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#7681]
## Description  

 * browser: all

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-pskbsu)
2. Open the browser console

## Result  

![image](https://user-images.githubusercontent.com/34240583/85696990-163a3900-b6e2-11ea-9b75-26ebcffaae32.png)

## Expected result  

No errors should be thrown in the console

**Comment by hanastasov** [comment]
Let's try to fix it in following way:
- keep `columns` prop, drop new `columnsCollection`, drop migrations
- use `columnList` internally

**Comment by hanastasov** [comment]
Resolved in version 13. Will not fix for 12.3.x as it turns out to be requiring a lot of changes in code and tests.
