### ISSUE TITLE
Slider throws `expressionChangeAfterChecked` error when bound w/ `ngModel`

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#7683]
## Description  
Slider throws when it has bound min/max value and `[ngModel]`.
Same behavior as https://github.com/IgniteUI/igniteui-angular/issues/7336

 * igniteui-angular version: 10.0.x, 9.1.x
 * browser: N/A

## Steps to reproduce  

1. Download this [StackBlitz sample](https://stackblitz.com/angular/gjvgajladxaj?file=src%2Fapp%2Fgrid-finjs%2Fgrid-finjs-demo.component.html)
2. `npm i igniteui-angular@[latest-rc]`
3. Run the sample and observe the console

## Result  
An error is thrown

## Expected result  
No error is thrown

## Additional Info
This appears to have been regressed with https://github.com/IgniteUI/igniteui-angular/issues/7523

**Comment by Aleksandyr** [comment]
@ViktorSlavov It seems that the issue appears without the slider in it, so I can't say that the problem is in the slider.
Here is the modified [sample](https://stackblitz.com/edit/angular-jbuzis-hxu3ng?file=src%2Fapp%2Fgrid-finjs%2Fgrid-finjs-demo.component.html).

**Comment by ViktorSlavov** [comment]
@Aleksandyr Thanks for checking! That seems like a separate issue though.
In a sample with an isolated slider, an error is still thrown when the component is mounting - [StackBlitz](https://stackblitz.com/edit/slider-error-model?file=src/app/slider-sample-3/slider-sample-3.component.html).
Apologies for including the bulkier sample in the issue, I should've gone with a more bare-bones one.
Thanks again!
