### ISSUE TITLE
how can i perform a centered zoom to coordinate by igx-geographic-map

### ISSUE THREAD

**Issue by simonluebker** [IgniteUI/igniteui-angular#7686]
## Question  
How can i achieve, that i can zoom into the map to a given coordinate (longitude, latitude), so that the coordinate will always be centered in the given geo rectangle?

 * igniteui-angular version: 9.0.10
 * browser: chrome version 83.0.4103.106

**Comment by wnvko** [comment]
@simonluebker 
To zoom to a given region in `IgxGeographicMap` you should use `zoomToGeographic` method of the component. Note, this method accepts a region which consists of:
- left - the left side of the region, the longitude of its western border.
- top - the top side of the region, the latitude of its northern border.
- width and height - the width and the height of the region.

So if you need to zoom to a given coordinate and have it in the center of the zoomed region you should calculate the region. For example if you need to zoon at point with coordinates `20LONG`, `10LAT` and the size of the viewing region you need is `8/6` degrees you should provide this region to `zoomToGeographic`:
```
this.map.zoomToGeographic({
        left: 20 - 8 / 2,
        top: 10 - 6 / 2,
        width: 8,
        height: 6
});
```
[Here](https://stackblitz.com/edit/angular-dyyei3?file=src%2Fapp%2Fmaps%2Fgeo-map-overview%2Fmap-overview.component.ts) is a sample showing how you can London centered on the map. Additional information about map navigation you may find in the [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/geo-map-navigation.html).

**Comment by simonluebker** [comment]
Thanks!
