### ISSUE TITLE
IgxGrid ExcelStyleFilter dialog does not show items correctly

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#7698]
## Description  
IgxGrid ExcelStyleFilter dialog does not show items correctly when vertical scroll is performed on a filter dialog, and directly opens another filter dialog.

 * igniteui-angular version: 9.1.4
 * browser: n/a

## Steps to reproduce  

1. Run the sample [igx-filtering.zip](https://github.com/IgniteUI/igniteui-angular/files/4844401/igx-filtering.zip)
2. Open filter dialog on 'Name' column, and scroll down the list (and keep the dialog open)
3. Open filter dialog on 'Id' column

## Result  
There is a white blank space on the filter dialog.

## Expected result  
No white blakc space appears on the filter dialog.

## Attachments
![igx-grid-filter-dialog](https://user-images.githubusercontent.com/14340675/85985430-b0bdb380-ba25-11ea-9511-61bd30a4c23f.gif)

**Comment by DiyanDimitrov** [comment]
@ChronosSF @MayaKirova, this looks similar to #6893, the only difference is that the second ESF is directly opened. Could you please take a look at it?

**Comment by ZCeli** [comment]
I'm wondering if there is a regression on this issue or if there is a particular implementation attached to the solution. 
I have Infragistics 17 installed and the same thing is happening.
