### ISSUE TITLE
igx-grid - Header Misaligned When Horizontally Scrolled

### ISSUE THREAD

**Issue by CarlosBressan** [IgniteUI/igniteui-angular#7713]
## Description  
Header misaligned when horizontally scrolled in any grid that haves horizontal scroll

 * igniteui-angular version: 9.0.3
 * browser: Chrome 83.0.4103.116

## Steps to reproduce  
chage the horizontal scroll

## Result  
Header misaligned of the data

## Expected result  
header should be aligned with the data

## Attachments  
![image](https://user-images.githubusercontent.com/50844862/86054802-2da25a80-ba31-11ea-839b-630a44395f36.png)

**Comment by ChronosSF** [comment]
Hello @CarlosBressan ,


Could you please share a sample that reproduces this behavior? I tried with a simple one but couldn't - you can find it here: https://stackblitz.com/edit/angular-pmpvsc


Thanks!

**Comment by CarlosBressan** [comment]
We discovered the problem and it was caused by our CSS:

igx-tree-grid, igx-grid{

    .igx-grid__thead {

        .igx-grid__tr{
            .igx-display-container{
				left: 0px !important;
			}
        }
    }
}
