### ISSUE TITLE
Automate resource strings generation

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#7747]
## Description  
When resource strings are added for a given component one should:
- first add them to [CurrentResourceStrings](https://github.com/IgniteUI/igniteui-angular/blob/0f46840cecccde9e240fcdf2bd3932ca5e447c6f/projects/igniteui-angular/src/lib/core/i18n/resources.ts#L14).
- on second place include them in [getCurrentResourceStrings](https://github.com/IgniteUI/igniteui-angular/blob/0f46840cecccde9e240fcdf2bd3932ca5e447c6f/projects/igniteui-angular/src/lib/core/i18n/resources.ts#L45) function.
- and finally should extend [IResourceStrings](https://github.com/IgniteUI/igniteui-angular/blob/0f46840cecccde9e240fcdf2bd3932ca5e447c6f/projects/igniteui-angular/src/lib/core/i18n/resources.ts#L9) interface with the newly created resource string interface.

This entire process is not error-proof. Even now we have six components with resource strings generated, from which only three are included in the `IResourceStrings` interface and just two are exposed in `getCurrentResourceStrings` function.

We should automate these three steps.

**Comment by Lipata** [comment]
Will be considered with #6602
