### ISSUE TITLE
igx-input-group is not working with textarea

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#7752]
## Description  
igx-input-group is not working with textarea

 * igniteui-angular version: 10.0.0
 * browser: Google Chrome  83.0.4103.116

## Steps to reproduce  

1. Run sample [angular-vrczrm.zip](https://github.com/IgniteUI/igniteui-angular/files/4885235/angular-vrczrm.zip)
2. Click on Full name field
3. Try to enter the text "Sample".

## Result  
The textarea can not be used to capture text.

## Expected result  
The textarea can be used to capture text.

## Attachments  
[Sample](https://stackblitz.com/edit/angular-vrczrm
)

**Comment by wnvko** [comment]
Possibly related to #7737
