### ISSUE TITLE
Show tooltip on focus

### ISSUE THREAD

**Issue by DerekJDev** [IgniteUI/igniteui-angular#7774]
## Is your feature request related to a problem? Please describe.

Not related to problem, but would be nice to have functionality to support this.

## Describe the solution you'd like

Have function to display a tooltip when an element is focused on. If there was a function to programically open a tooltip positioned on the focused element that would work too.

## Describe alternatives you've considered

I've tried using the existing functionality to programically show the tooltip, which is easy, but positioning it is hard to find out how to do.

**Comment by astaev** [comment]
@DerekJDev 

Please find the sample - https://codesandbox.io/s/delicate-smoke-rxviu?file=/src/app/tooltip-simple/tooltip-simple.component.html
There is a target.showTooltip method which can be used to show a tooltip programmatically. If that's not what you are exactly looking for, please feel free to modify the project and send back us.
