### ISSUE TITLE
Autocomplete drop down is shown when value is cleared

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#7779]
## Description  
When autocomplete gets a value that is not in the list, when the input is blurred then the drop down flickers.

 * igniteui-angular version: 10.0.3

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/angular-eppddh) autocomplete demo
2. Type 'ss' in the `Cinema` input
3. Press Tab

## Result  
Autocomplete value is cleared but drop down flickers.

## Expected result  
Autocomplete value is cleared but drop down is not shown.

**Comment by mddragnev** [comment]
This is not a product issue but a sample one. Here is a sample which fixes it. https://stackblitz.com/edit/angular-eppddh-f1auxx?file=src%2Fapp%2Fdata-entries%2Fautocomplete%2Fmovie%2Fmovie.component.ts
