### ISSUE TITLE
Demo Code Demonstrating Full Capabilities of the Grid Component

### ISSUE THREAD

**Issue by QuinntyneBrown** [IgniteUI/igniteui-angular#778]
Is there an angular-cli project demonstrating the full capabilities of grid component?

I'm mainly interesting in inline CRUD functionality.

Thanks!

**Comment by zdrawku** [comment]
This is the sample that I mentioned couple days ago. As you can see, I am using Firebase for data storage and Grid demonstrates CRUD operations along with remote binding.

https://stackblitz.com/edit/igx-grid-crud-with-firebase?embed=1&file=app/app.component.ts&view=preview


If you have any questions, let me know.

FYI, we are considering to add a detailed step by step guide on how to configure CRUD operations with our igxGrid.
