### ISSUE TITLE
There is no padding inside input group of type fluent when prefix is being hidden dynamically

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#7780]
## Description  
 
 * igniteui-angular version: 10.1.x
 * browser: 

## Steps to reproduce  

1. Open the sample: https://stackblitz.com/edit/github-yhhxcs-v3i1p4
2. Use the button to change the type to fluent.

## Result  
The margin on the left is missing.

## Expected result  
Margin is not missing.

**Comment by simeonoff** [comment]
@SAndreeva igniteui-angular version?

**Comment by simeonoff** [comment]
In order for the design to look right you have to use input-groups of type `fluent` in combination with a `fluent` theme.

Here's a breakdown of what input-group type goes with what theme:

1. Type `line`, `box`, `border`, and `search` - Designed to work with material-based themes.
2. Type `bootstrap` - Designed to work with bootstrap-based themes.
3. Type `fluent` and `fluent_search` - Designed to work with fluent-based themes.

Any future input types we add will follow the same pattern.*

\* We are thinking of refactoring this to limit the types to only 4 - `line`, `border`, `box`, and `search`. The first 3 types will affect the design of the input group only when used with material-based themes. Using those 3 types with other themes will render the theme-specific design, regardless of the selected type, with the exception of `search`. We are still thinking of ways we can implement this change, but it's an effort planned for the next milestone.`
