### ISSUE TITLE
Overlay isn't closed while another overlay's closing animation is in progress

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular#7803]
## Description  
Nothing happens when trying to close an overlay with the Escape key while another overlay's closing animation is in progress.

## Steps to reproduce  

1. Create a couple of overlays with the closeOnEscape property set to true.
2. Have them show up on screen.
3. Try to close one with the Escape key and while its closing animation is in progress try to close the next overlay by pressing the Escape key.

## Result  
The next overlay is not being closed.

## Expected result  
The next overlay should close even with the previous' one closing animation in progress.
Not sure that it should be like that so @StefanIvanov and @wnvko, please look into this and discuss the desired behaviour.

**Comment by StefanIvanov** [comment]
I think your request is valid and if you need any guidance on our end I am available for a discussion.
