### ISSUE TITLE
Dropdown: box-shadow is missing in some cases

### ISSUE THREAD

**Issue by didimmova** [IgniteUI/igniteui-angular#7821]
## Description  
The shadow of the dropdown is missing unless there's an `igx-drop-down-item` in it.

 * igniteui-angular version: 9.1.x
 * browser: all

## Steps to reproduce  

1. Open DevDemos
2. See the Grid Toolbar Sample
3. Click any of the buttons in the toolbar.

## Result  
There's no shadow of the dropdown because the content isn't placed in an `igx-drop-down-item` and there's an `igx-drop-down__list--empty` class added, which removes the box-shadow of the dropdown.

## Expected result  
There should be a shadow unless there's no content in the dropdown at all.

## Attachments  
<img width="710" alt="Screen Shot 2020-07-20 at 4 55 42 PM" src="https://user-images.githubusercontent.com/45598235/87945749-daf51500-caa9-11ea-97de-6e59c919434a.png">

**Comment by Lipata** [comment]
Regressed after #3977 was fixed
