### ISSUE TITLE
When navigate up/down from parent to child and vice versa an error appears

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#7822]
## Description  
When navigate up/down from parent to child and vice versa an error appears

## Steps to reproduce  

1. Open hierarchicalGrid dev demo
2. Start navigating with the kb nav through the child grids
3. Try to navigate from child to parent grid

## Result  
An error appears: Cannot read property 'childGridsData' of undefined

## Expected result  
The navigation should happen without any errors.

## Attachments  
![image](https://user-images.githubusercontent.com/7037740/87946210-64a4e280-caaa-11ea-8527-40c88bb6c4ea.png)

**Comment by MayaKirova** [comment]
@Aleksandyr Could you share some addition information such as the exact steps to reproduce or a gif of the exact actions as I'm not able to reproduce this on my side:

![navigation-hgrid](https://user-images.githubusercontent.com/10397980/87950834-7d17fb80-cab0-11ea-85a6-72edfd3eef41.gif)

**Comment by MayaKirova** [comment]
Issue does not seem to reproduce in master.
