### ISSUE TITLE
rowData property is missing in IGridEditEventArgs

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#7833]
## Description  
[rowData property](https://jp.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/igridediteventargs.html#rowdata) is missing in IGridEditEventArgs.

 * igniteui-angular version: 9.1.8
 * browser: any

## Steps to reproduce  

1. Run the sample [igx-grid-cell-editing.zip](https://github.com/IgniteUI/igniteui-angular/files/4952267/igx-grid-cell-editing.zip)

2. Edit a cell and leave editing cell to raise onCellEdit event

## Result  
On step 1, build fails with the message "Property 'rowData' does not exist on type 'IGridEditEventArgs'."
On step 2, rowData property is undefined.
![igx-grid-cell-editing](https://user-images.githubusercontent.com/14340675/88032557-16aae000-cb79-11ea-9b0c-7ce10a0ae5ad.gif)

## Expected result  
rowData property contains data of the row where the cell is edited.

**Comment by kdinev** [comment]
@ymita `rowData` was added in the event arguments with version 10.

**Comment by ymita** [comment]
@kdinev  Oh okay. Thank you!
