### ISSUE TITLE
Fixed position of the bottom navigation component not working correctly

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#7861]
## Description  
All browsers except Safari did not respect the fixed position of the bottom navigation component.

 * igniteui-angular version: 9.1.x, 10.0.x ,10.1.x
 * browser:  Chrom, Edge, Firefox, IE

## Steps to reproduce  

1. Open **Bottom navigation Routing** component in dev demos
2. Open for example Chrome and Safari and compare

## Result  
In all browsers except Safari, the component takes its parent width, not the width of the viewport.

## Expected result  
The component should take the viewport width as it does in the Safari browser.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[Chrome Screenshot](https://imgur.com/vSsOPAG)
[Safari Screenshot](https://imgur.com/JsXtVXN)

**Comment by simeonoff** [comment]
This is an application specific issue. Not related to the component.
