### ISSUE TITLE
selection highlight dissappears when scrollbar is clicked

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular#791]
### Description  
When the user attempts to scroll the grid horizontally or vertically by clicking either scrollbar, any selection highlighting is wiped out

### Steps to reproduce  

1. select a grid cell
2. click either horizontal or vertical scrollbar

### Result  
selection style is removed from selected row

### Expected result  
Selection style stays. This allows user to highlight a cell/row and scroll horizontally to keep that row in his/her focus while reviewing the data.

**Comment by kdinev** [comment]
@jVanZwieten The style applied is actually the focus style. I'm marking this as a request for enhancement - to add a separate selected style.

**Comment by Lipata** [comment]
Fixed with #879
