### ISSUE TITLE
scroll bar disappears when setting width of igx-columns

### ISSUE THREAD

**Issue by debugmodedotnet** [IgniteUI/igniteui-angular#792]
### Description  
I am working with igx-grid. I have set height of the grid  as below 

`<igx-grid #grid1 [autoGenerate]="false" [height]="'600px'">`

So it enables virtualization and I am able to bind more than 50K rows. However if I set width of columns like below, 

` <igx-column [width]="'100px'" field="Id" header="Id" dataType="number"></igx-column> `

scroll bar of the grid disappears .  I tested it on chrome and Firefox 

any help ?

Thanks 
DJ

**Comment by kdinev** [comment]
Do you also reproduce the same when trying to set column width inside the `onColumnInit` event with `autoGenerate`?

**Comment by ChronosSF** [comment]
Hello @debugmodedotnet ,

If you don't have width set on the grid it will assume that it should render all columns and take their total width. You will not get a horizontal scrollbar in this case.

I am attaching a small sample to demonstrate the difference.

[sample.zip](https://github.com/IgniteUI/igniteui-angular/files/1828470/sample.zip)

**Comment by debugmodedotnet** [comment]
Hi, 

I added event to grid like below 

`<igx-grid #grid1 [autoGenerate]="false" [height]="'600px'" (onColumnInit)='initcolumn($event)'>`

then in component class handling it as follows

` initcolumn(col) {
    // disappear scroll bar
    col.width = '100px';
  }
`

By doing this also scroll bar is disappearing and I am able to reproduce the bug !

**Comment by debugmodedotnet** [comment]
we are talking about vertical scroll bar here , not horizontal !

**Comment by ChronosSF** [comment]
In both grids in the sample I attached the vertical scrollbar is visible and can be operated with. Could you please modify them so that the issue reproduces or share a sample yourself?

**Comment by ChronosSF** [comment]
@debugmodedotnet `columnWidth` is a new property in igxGrid that will allow for a much simpler setup that allows for horizontal virtualization. It will be available with the official 5.3.0 release.
