### ISSUE TITLE
IgxGridState directive not able to reset columnList for igxHierarchicalGrid.

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#7925]
## Description  
Open dev samples

 * igniteui-angular version: 10.1.0

## Steps to reproduce  

1. Open dev samples, go to State directive samples
2. Open hier grid
3. Move columns in the child grid
4. Save state
4. Restore state

Note: It seems that resetting the column list through `grid.columnList.reset(newColumns)`, leads to trigerring`onColumnsChanged`, which triggers the event for the root grid:

https://github.com/IgniteUI/igniteui-angular/blob/d7ab1c144cfd3a45c13653d03741b5eb999f93d4/projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts#L420

, which eventually restores the columnList back to the autogenerated columns:
https://github.com/IgniteUI/igniteui-angular/blob/d7ab1c144cfd3a45c13653d03741b5eb999f93d4/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L4963
 

## Result  
The column list is resetted as initially, instead of restoring to the saved state.

## Expected result  
The column list to be restoring of the saved state.

**Comment by zdrawku** [comment]
Removing this item from the Milestone planning as it is a question with low priority
