### ISSUE TITLE
Refactor all Grid events that are related to cell/row editing

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#7931]
- [x] Replace **onCellEditCancel** with **cellEditExit** and **onRowEditCancel** with **rowEditExit** (including the change in the execution process)
- [x] Remove all **on** prefixes
- [x] Change the execition sequence of **onRowEditEnter** and **onCellEditEnter** (Emit first **onRowEditEnter** so it can cancel the execution and prevent emitting **onCellEditEnter** if needed)
- [x] Update Spec

**Comment by kdinev** [comment]
@IvayloG I actually disagree with this FR, since if I want to handle cases for editDone, regardless of whether the edit is committed or not, then I would have to always handle two events. Currently, there's a way for me to distinguish whether an edit is performed, by comparing the old and new values, so what raises the need for such event?

**Comment by IvayloG** [comment]
In general, the idea was to both emit cellEditDone only when there is an actual value update made and provide a new cell editing event when editing is finished so both are more specific and kind of complement each other.  As there were several more pros as well as concerns behind this FR, I believe @rkaraivanov and @damyanpetev may provide more details, as this idea came from upon a discussion, during the exposing of cellEditDone&rowEditDone events.

**Comment by kdinev** [comment]
But this would then be a breaking change, because it would require a change in the condition under the `Done` events are called, and would introduce a new event, which essentially does the same thing as the original `Done` event. Why is this needed?

**Comment by IvayloG** [comment]
@kdinev Yes it will a breaking change, thus it may be appropriate to combine/pack this with several more (like not emitting these events when there is a pure API update at all) and refactor/update the events concept as well as document it well for the clients (samples and so on). This whole refactoring idea is better suited for an open discussion with @rkaraivanov & @damyanpetev, as there were several specific user cases discussed as well, and this FR is more of a side note of the previously mentioned task.
