### ISSUE TITLE
Igx-grid cannot work in IE11

### ISSUE THREAD

**Issue by lzl82891314** [IgniteUI/igniteui-angular#7946]
## Description  
Data grid cannot work in IE11.

 * igniteui-angular version: 6.0.0
 * angular version: 10.0.6
 * browser: Internet Explorer 11

## Steps to reproduce  

1. Create a new angular sample by `Angular CLI` base on [Getting started
](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/getting_started.html) (good)
2. Run `ig add` and choose `Add component` - `Grids & Lists` - `Grid` (good)
3. In order to work in IE11, set tsconfig.base.json node `target` to `es5` and run `ng serve` (good)
4. The page occur errors  `Syntax error` in IE11 (NG)

## Attachments  
![image](https://user-images.githubusercontent.com/9321017/89755544-634b6080-db12-11ea-95a3-d1ef72fc4a54.png)

![image](https://user-images.githubusercontent.com/9321017/89755485-372fdf80-db12-11ea-91c5-d0e563e38a03.png)

**Comment by kdinev** [comment]
Do you have all the IE11 required polyfills included in your `polyfills.ts`?

**Comment by lzl82891314** [comment]
Yes, I included `import 'core-js/stable'` and `import 'regenerator-runtime/runtime'` based on [@babel/polyfill](https://babeljs.io/docs/en/babel-polyfill) in my `polyfills.ts`, but it's still not work

**Comment by lzl82891314** [comment]
Sorry, it looks like my fault, I just create a pure angular project, and it's not working too

**Comment by lzl82891314** [comment]
Sorry, it looks like my fault, I just create a pure angular project, and it's not working either. I am very sorry about it.

**Comment by lzl82891314** [comment]
When I removed `not IE11` config in `.browserslistrc`, the page worked but have no styles, did I forget any configuration of ig-grid?
![image](https://user-images.githubusercontent.com/9321017/89771664-45422800-db33-11ea-9f9c-b82902629ac6.png)

**Comment by kdinev** [comment]
Yes, by default the produced css from the themes is with `$legacy: false` support, in order to produce smaller css bundle. Just include `$legacy: true` in your theme mixin and the IE11 styles would be included.

**Comment by lzl82891314** [comment]
I have fixed this problem, very thank you for your reply.
