### ISSUE TITLE
igxGrid Summaries Scroll positioning enhancement 

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#795]
### Description  
The igxGrid summaries scrolling need to have the option to be positioned either above or under the Summaries Container in the Grid. In this regard it needs to have similar behavior as the attached Gifs. Visually the scrolling should look thin and despairing when it is not selected.

### Attachments  

![8yiz7-3swov](https://user-images.githubusercontent.com/33216749/37657127-caa067ec-2c52-11e8-95a4-b8fbfa3a68b9.gif)
![v09s0-h680n](https://user-images.githubusercontent.com/33216749/37657160-e187d634-2c52-11e8-9416-a76961403a63.gif)

This will be assigned in Future Sprints for enchantment of the current options.

**Comment by zdrawku** [comment]
@SlavUI we should discuss this enchancement on Monday

**Comment by kdinev** [comment]
This is achievable with non-native scrollbar, which we rejected as an approach some time ago. Closing this for now. If we ever move to a non-native scrollbar like in the `igGrid` with the `igScroll` we would reopen this.
