### ISSUE TITLE
When grid has no height, custom footer with text and font-size in em and page is zoomed the grid shrinks

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#7954]
## Description  
When grid has no height, custom footer with font-size in em and page is zoomed the grid shrinks

 * igniteui-angular version: 10.0.x
 * browser: Chrome

## Steps to reproduce  

1. Open the attached sample.
2. Zoom to 125%

Can also be reproduced at: https://staging.infragistics.com/angular-demos/grid/grid-nested-data-binding-2

## Result  
The grid starts shrinking.

## Expected result  
The grid should stay the same size.

## Attachments  
[grid-zoom.zip](https://github.com/IgniteUI/igniteui-angular/files/5052251/grid-zoom.zip)

**Comment by rkaraivanov** [comment]
Closed via #7976
