### ISSUE TITLE
igx-grid occurs an `NullInjectorError` in angular v8.2.3

### ISSUE THREAD

**Issue by lzl82891314** [IgniteUI/igniteui-angular#7955]
## Question  
I created a simple igx-grid sample with the following configuration in angular v8.2.3 
![image](https://user-images.githubusercontent.com/9321017/89853636-7585d700-dbc4-11ea-8f77-15f6f5fb41ad.png)
![image](https://user-images.githubusercontent.com/9321017/89853667-85052000-dbc4-11ea-94c0-c24c29e35ccc.png)

And when I run `ng build` with `aot: true`, the command line throws the following errors:
![image](https://user-images.githubusercontent.com/9321017/89853227-736f4880-dbc3-11ea-8a44-a2d73a44a249.png)

When I set `aot` to `false`, the build will succeed. But when I run `ng serve`, the browser occurs the following errors:
![image](https://user-images.githubusercontent.com/9321017/89853375-d4971c00-dbc3-11ea-9ed6-9ee6c110c8f6.png)

What should I do to resolve this issue?

 * igniteui-angular version: 10.0.6
 * browser: chrome v84.0.4147.105

**Comment by kdinev** [comment]
You should import the `IgxIconModule` as well.

**Comment by lzl82891314** [comment]
When I import `IgxIconModule` this error occurs either. But this error does not occur in angular v10.0.6, `IgxGridModule` is the only one module I imported in angular v10.0.6 and that sample works well. What's the difference between v8.2.3 and the latest version? Does the latest version of `ignite-ui` not support angular v8.2.3?

**Comment by kdinev** [comment]
The `igniteui-angular` major versions are tied to the `@angular/core` major versions. You can read more about our versioning [here](https://github.com/IgniteUI/igniteui-angular/wiki/Ignite-UI-for-Angular-versioning).
