### ISSUE TITLE
selectedRows getter does not work when binded to a child grid

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#7971]
## Description  
 When trying to get selected rows of a child grid with selectedRows getter it returns empty array 

 * igniteui-angular version: 10.1.x , 10.0.x
 * browser: n/a

## Steps to reproduce  

1. Open this sample [link](https://codesandbox.io/s/funny-dawn-v6xog?file=/src/app/hierarchical-grid/hierarchical-grid-selection/hierarchical-grid-selection.component.html)

2. Expand the first row and select a record from the first child grid

3. Hit the button "Selected Rows"

4. Observe the console
## Result  
The result is empty array

## Expected result  
The result should be a set of selected elements

**Comment by MayaKirova** [comment]
By design, the row island does not aggregate values between different child grid instances when a property getter is invoked on it.
You can loop through the child grids for that particular row island, get their individual values and aggregate them if you wish.
