### ISSUE TITLE
Upgraded to version 9.1.1, but on running test get follwing error, followed all steps that is provided in website

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#7973]
ERROR in ./src/styles/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/sass
-loader/dist/cjs.js??ref--13-3!./src/styles/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: igniteui-angular/lib/core/styles/themes/index.
        on line 15 of C:\development\dev\eds-angular\eds-frontend\src\styles\styles.scss
>> @import "igniteui-angular/lib/core/styles/themes/index";
   ^

SassError: SassError: File to import not found or unreadable: igniteui-angular/lib/core/styles/themes/index.
        on line 15 of C:\development\dev\eds-angular\eds-frontend\src\styles\styles.scss
>> @import "igniteui-angular/lib/core/styles/themes/index";
   ^

    at Object.render [as callback] (C:\development\dev\eds-angular\eds-frontend\node_modules\sass-loader\dist\index.js:73:16)
    at Object.done [as callback] (C:\development\dev\eds-angular\eds-frontend\node_modules\neo-async\async.js:8067:18)
    at options.error (C:\development\dev\eds-angular\eds-frontend\node_modules\node-sass\lib\index.js:294:32)
 @ ./src/styles/styles.scss 2:26-216

Please let me know if there is anything i am doing wrong or that i need to add to make this upgrade work

**Comment by kdinev** [comment]
This import path should be prefixed with `~`:

```scss
@import '~igniteui-angular/lib/core/styles/themes/index';
```

**Comment by amitmoondra** [comment]
No i am fetching the licensed version and according to the licensing documentation, fetching from private npm feed, the way import of theme is done is changed as its scoped.

Check below
https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing.html

So this is throw error while running test.

**Comment by kdinev** [comment]
Did you go through the `ig upgrade` procedure using the CLI, or no?

The correct import path with the licensed package would be:

```scss
@import "~@infragistics/igniteui-angular/lib/core/styles/themes/index";
```

**Comment by amitmoondra** [comment]
yeah this worked, i missed the upgrade command
as i am using yarn, my bad.
But also 
@import "~@infragistics/igniteui-angular/lib/core/styles/themes/index";

this line is not present in documentation, but yeah its understandable now.

Thanks for your help.
