### ISSUE TITLE
onEditDone event returns only `new` and `old value` of the edited cell

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#798]
### Description  
We should consider updating of the "Returns" params or to add a param for the whole row instance.

Currently I need to update the rowData object with the new (updated) cell value in order to pass the whole rowObject to the remove data service that is used:

```
 updateItem(obj){
    this.grid1.cellInEditMode.row.rowData[this.grid1.cellInEditMode.column.field] = obj.newValue;
    
    this.itemService.updateItem(this.grid1.cellInEditMode.row.rowData);
    this.clearState();
  }
```

update method from the source:

```
public update(val: any) {
        this.grid.onEditDone.emit({ currentValue: this.value, newValue: val });
        this.value = val;
        this.gridAPI.update(this.gridID, this);
        this.cdr.markForCheck();
    }
```

**Comment by kdinev** [comment]
@zdrawku This event doesn't have any tests for it. Whom should I assign to write a test?

**Comment by kdinev** [comment]
Related #740
