### ISSUE TITLE
Editing cell does not move when Paragraph tag is contained in the cell data

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#7980]
## Question  
I want to render Paragraph tag in the cell, and edit such cells. Rendering Paragraph tag works fine. But I have an issue with editing cells that contain Paragraph tag. Is this because of a wrong configuration of IgxGrid? I tested Paragraph and Line Break tag, and there is no problem with Line Break tag.

 * igniteui-angular version: 9.1.11
 * browser: any

Steps:
1. Run the sample [igx-grid-html.zip](https://github.com/IgniteUI/igniteui-angular/files/5061780/igx-grid-html.zip)
2. Start editing a cell on Name column
3. Enter any new text
4. Click other cell on Name column to change editing cell

--> Editing cell does not move to the one clicked on step 4
![IgxGrid_Editing](https://user-images.githubusercontent.com/14340675/89998907-165dba80-dcc9-11ea-8e00-ebdf3253fc5a.gif)

Code:
```
<igx-grid
  [data]="data"
  [width]="'100%'"
  [height]="'500px'"
  [displayDensity]="'compact'"
  >
  <igx-column field="id" header="ID" dataType="number" [editable]="true" [movable]="true" [width]="'30%'">
  </igx-column>
  <igx-column field="name" header="Name" dataType="string" [editable]="true" [movable]="true" [width]="'70%'">
    <ng-template igxCell let-cell="cell">
      <div [innerHTML]="cell.value">
      </div>
    </ng-template>
  </igx-column>
</igx-grid>
```

**Comment by ymita** [comment]
@kdinev , @ChronosSF , @zdrawku 
Can you comment on my question?

**Comment by kdinev** [comment]
@ymita Unlike the jQuery product, with Angular you can't input html directly into component and expect that it would be rendered. The HTML will be rejected. Angular exposes custom mechanisms like:

https://angular.io/api/platform-browser/DomSanitizer#bypasssecuritytrusthtml

As the warning says, this exposes a security risk in your application, and we won't bypass security on a library level. If the custom wants, they can handle the input before it's being handed off to the grid and bypass the security manually. I still don't think that this would be rendered as HTML, it would instead be escaped and rendered as a string.

**Comment by ymita** [comment]
@kdinev 
Thank you for your comment. The customer is aware that this involves security risk. But they are still looking for a way to achieve this scenario.

The issue occurs because the height of igxCell and igxCellEditor differ. On step 4, when I mousedown on a cell, IgxGrid generates the corresponding editor. But the generated editor is not right under the mouse cursor so that grid places the editor where the mouse cursor stays on mouseup timing. I get the issue around by setting the row height before editing starts so that editor won't be misplaced.

```
<igx-grid
  #grid1
  primaryKey="id"
  ...
  (onCellEditEnter)="onCellEditStart($event)"
  (onCellEdit)="onCellEdit($event)"
  >
  <igx-column field="id" header="ID" dataType="number" [editable]="true" [movable]="true" [width]="'30%'">
  </igx-column>
  <igx-column field="name" header="Name" dataType="string" [editable]="true" [movable]="true" [width]="'70%'">
    <ng-template igxCell let-cell="cell">
      <div [innerHTML]="cell.value">
      </div>
    </ng-template>
  </igx-column>
</igx-grid>

  onCellEditStart(args: IGridEditEventArgs) {
    const row = this.grid1.getRowByKey(args.rowID);
    row.nativeElement.style.height = row.nativeElement.clientHeight + 'px';
  }

  onCellEdit(args: IGridEditEventArgs) {
    const row = this.grid1.getRowByKey(args.rowID);
    row.nativeElement.style.height = '';
  }
```
