### ISSUE TITLE
Grid summary custom templating

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#7981]
Hello there,
I am having two problems that could potentially be fixed with the same solution. I am using Grid summaries with the igx-grid and would like to add custom styles to **some** grid summary columns. 

1. In the picture below you can see the summary for PFY (77.8%). I would like to give this value a specific color based on the value, like shown in the PFY column in each row. 
![image](https://user-images.githubusercontent.com/43247999/90003947-1f349900-dc95-11ea-87d5-695a36216756.png)

2. I would like to format the summary value. i.e a thousand separator. I've acheived this by creating a local pipe object already in our project in the Summary classref, however feels like a work-around.

## Describe the solution you'd like
It would be great to be able to extend grid-summaries to include custom templating of the summary column.

**Comment by Eralmidia** [comment]
+1 for this feature request, creating these summaries through an object seems awkward, it should be a template, much like the cell and header.
