### ISSUE TITLE
igxGrid can't enter edit mode on mobile

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#7984]
### The issue does not appear on every browser/device! 
I have hosted a simple demo sample and I have tested it on multiple devices with multiple browsers. 
1. On PC the issue can be reproduced using Google Chrome in mobile mode. On Firefox it will work correctly. 
2. On iPhone 8 and iPhone 8+ the issue appears. (I have tested in Safari and Chrome)
3. On iPhone 7 and iPhone 11 I wasn't able to reproduce the issue as well.
4. On multiple android phones using different browsers I wasn't able to reproduce the issue.
5. I have not tested it on any tablets.
 * igniteui-angular version: 9.1.x, 10.0.x

## Steps to reproduce  

1. Run the attached sample
2. Open the sample in Chrome (in mobile mode) and try to edit a cell via double clicking on it

## Result  
The cell won't enter in edit mode.

## Expected result  
The cell should enter in edit mode.

## Attachments  
[gridMobile.zip](https://github.com/IgniteUI/igniteui-angular/files/5064002/gridMobile.zip)

**Comment by Aleksandyr** [comment]
@mmart1n It seems that it is a third party issue.
You can try reproduce the some problem [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event#result) with the sample when you are in mobile mode.

**Comment by Aleksandyr** [comment]
@mmart1n It seems that it is a browser-related third party issue. You can just simply grab that sample from that [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1045882&q=dblclick&can=2) and test it.
