### ISSUE TITLE
igx-tabs - Use full height available

### ISSUE THREAD

**Issue by Swiftpaws** [IgniteUI/igniteui-angular#8001]
## Question  
How to make the igx-tabs component use the full available height ?

 * igniteui-angular version: 10.0.x

Is there a way to make use of the full available height (height: 100%) of the tab content?
I would need to have comp2 occupy the full available height and width of the tabview. -> https://stackblitz.com/edit/angular-okg5s9-98lte1

Or is using tab-items with a routing implementation the "easiest" way to achieve this behavior?

**Comment by rkaraivanov** [comment]
Usually `height: 100%` implies the full height of the parent container. Either you force the parent container to span the whole screen height, or go with `height: 100vh` on the child.

**Comment by Swiftpaws** [comment]
Unfortunately this does not work in my stackblitz. I actually make use of my css class class="useFullSpace" - which sets height:100%; and the same for width. 
All available elements have this class but apparently it is not enough.
![image](https://user-images.githubusercontent.com/18440081/90245621-504ad000-de33-11ea-938c-f3f6a543f895.png)


So I tried some things and came up with a "fix":
`::ng-deep {
  igx-tabs > div, .igx-tabs__content-fixed, .igx-tabs__content-fluid {
    height: 100%;
  }
}`

Result: https://stackblitz.com/edit/angular-okg5s9-g88jof
With this modification the tab-view now occupies the full height! - Although the solution is not very "pretty"

**Comment by rkaraivanov** [comment]
You can apply it in you style class:
```css
.useFullSpace {
  width: 100%;
  height: 100vh;
}
```
[Sample](https://stackblitz.com/edit/angular-okg5s9-7ua6j1?file=src/app/tabs-sample-1/tabs-sample-1.component.scss)

**Comment by Swiftpaws** [comment]
@rkaraivanov thanks, that works for our solution
