### ISSUE TITLE
HammerJS build warning after ng-add schematic

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#8007]
## Description  
Related to issue described in https://github.com/IgniteUI/igniteui-angular/issues/7808#issuecomment-660115910:

We moved Hammer to import for https://github.com/IgniteUI/igniteui-angular/issues/3256, though that might be a bit less relevant right now. Our options are to move it back to `angular.json` scripts entries or per https://github.com/hammerjs/hammer.js/issues/1255 add it to `allowedCommonJsDependencies` since the impact on tree shaking seems minimal (if any - can be tested).

 * igniteui-angular version: 10.0.x / 10.1.x
 * browser: N/A

## Steps to reproduce  

1. Install Ignite UI for Angular in an Angular 10 project using `ng add igniteui-angular`
2. Run `ng build --prod` 
3. Observe the build warnings

## Result  
There's a warning about `main.ts` depending on `hammerjs` which is CommonJS and may cause optimization bailouts.

## Expected result  
Ideally, after running the ng add schematic in Angular 10 project there should be no warnings.

**Comment by grosch** [comment]
What's the status of getting hammerjs out of this package?

**Comment by Lipata** [comment]
@grosch, one of our next sprints will be for bug fixing and we will consider that bug.
