### ISSUE TITLE
Excel style filter improvements

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#8008]
## Is your feature request related to a problem? Please describe.
We are considering moving the filtering in our igx-grids over to the excel style filter. While this filter works quite similar to the filter in Excel (which is a good thing), there seems to be one key feature missing:

In Excel, I have the following column:
![image](https://user-images.githubusercontent.com/12936286/90505241-931de800-e152-11ea-82f5-4b759b71d4a0.png)

Then, in the filter, I do a search for 2. This will correctly give me the rows for 21 and 22.
![image](https://user-images.githubusercontent.com/12936286/90505318-b2b51080-e152-11ea-8af4-559ebf46b009.png)

If I now press enter or click apply, this will actually apply this filter to the grid:
![image](https://user-images.githubusercontent.com/12936286/90505379-ceb8b200-e152-11ea-99e6-6f9a0857c887.png)

This last part does not happen in the igx version of the filter. First of all, enter doesn't seem to confirm at all, but more importantly, if you click apply, nothing actually happens (I'm guessing this is because it still includes the "Select all" option).

So, in order to do the same thing I do with the enter key in Excel, I will now have to first click "Select all" (which will deselect everything), then re-select my search result, and then finally click Apply.

## Describe the solution you'd like
- Enter key should work as apply.
- Enter / apply should apply the results from the search.

**Comment by Eralmidia** [comment]
I just noticed these features are already requested in #5812 and #5813

**Comment by radomirchev** [comment]
@Eralmidia , #5812 is already scheduled for the current milestone and is to be available in 10.2.0 release. #5813 is coming next.

**Comment by Eralmidia** [comment]
@radomirchev Good to hear, closing this then, since it's a duplicate 👍
