### ISSUE TITLE
IgxGrid - verticalScrollContainer scroll arguments

### ISSUE THREAD

**Issue by Swiftpaws** [IgniteUI/igniteui-angular#8017]
## Question  
How do you obtain the scroll arguments for the verticalScrollContainer.onDataChanged? The event tells me that there has been a change but not what has been changed.

I would like to know when the scrollbar reached the end of the list (scrolled down to the last element). Event origin (mousewheel, scrollbar drag) + direction would be a plus

**Comment by ChronosSF** [comment]
As of v.10.1 the grid exposes an [onScroll](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#onscroll) event that has scroll arguments but for your case it could be easier to use onDataChanged and get the state of the verticalScrollContainer, then see if its start index + the chunk size equals the unpinned data view length.

```typescript
const state = verticalScrollContainer.state;
if (state.startIndex + state.chunkSize >= grid.unpinnedDataView.length) {
    // the last virtualization chunk is loaded
}
```

Have in mind though that the virtualization chunk is one record bigger than what fits in the body to allow for smooth scrolling. So the last onDataChanged you will get doesn't necessarily mean that the scroll will be dead bottom. If you need this you can use the aforementioned onScroll event and compare the scrollTop with the scrollHeight.
