### ISSUE TITLE
igxHierarchicalGrid: Error on opening a Row Island with Summaries

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#8021]
## Description  
After modifying the demo code in the IgniteUI for Angular [Hierarchical Grid Summaries Overview](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/summaries.html), by adding the "number" dataType to the BillboardReview column and setting the summaries attribute to use "numberSummary", an error : ERRORError: classRef is not a constructor has been raised.

 * igniteui-angular version: 10.1.0

## Steps to reproduce  

1. Open the attached sample.
2. Expand the first row

## Result  
The row island is not displayed and an error is thrown.

## Expected result  
No errors and the row island to display the expected summaries.

## Attachments  
Sample application could be found [here](https://stackblitz.com/edit/igx-hierarchical-grid-number-summary-issue?file=package.json)

**Comment by MayaKirova** [comment]
@teodosiah After looking into this it seems that the custom summary class from the sample does not extend one of our IgxSummaryOperand classes, hence the existing checks fails to recognize it as a summary and do not pass it correctly to the child grids. If the class is properly extended it works as expected: https://stackblitz.com/edit/igx-hierarchical-grid-number-summary-issue-aktvux

As per the docs it seems that extending one of our existing classes is a requirement for the custom summaries:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries.html#custom-grid-summaries
Unless we decide to change this requirement in the future the custom summary should always extend one of our base classes. Hence I'm marking this as not-a-bug.
