### ISSUE TITLE
igxHierarchicalGrid: After upgrade the row-islands are not displayed

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#8022]
## Description  
After upgrade to version 10, row-islands are not displayed on expanding in igxHierarchicalGid with visualization. The reason for the issue seems to be the setting of the grid's verticalScrollContainer.totalItemCount to some value.
In version 9.1.x or earlier everything seems to work as expected.

 * igniteui-angular version: 10.1.0

## Steps to reproduce  

1. Open the attached sample
2. Expand the first row

## Result  
The row-island is not visible.

## Expected result  
The row to be expanded and the row-island to be visible.
Sample application using version 9.1 could be found [here](https://stackblitz.com/edit/igx-hgrid-verticalscrollcontainer-version-9-1?file=src/app/hierarchical-grid/hierarchical-grid-lod/hierarchical-grid-lod.component.ts).

## Attachments  
Sample application that demonstrates the issue could be found [here](https://stackblitz.com/edit/igx-hgrid-verticalscrollcontainer-version-10?file=src/app/hierarchical-grid/hierarchical-grid-lod/hierarchical-grid-lod.component.ts)

**Comment by SaranyDwarampudi** [comment]
in my example the virtualization is given to parent grid i.e only  when vertical scroll bar is scrolled the new data comes into the parent grid. NOTE: Child grid do not refresh, child grid data comes along with the parent grid data. Please find the data in the image
![image](https://user-images.githubusercontent.com/61456539/90784315-c44b1380-e31e-11ea-9996-1090b4e2090d.png)

**Comment by SaranyDwarampudi** [comment]
@3phase  we are using hierarchized data. And the example createdby Teodosia Hristodorova does not match our example.My example is row-island do not have virtualization (it do not fetch data from database when we click arrow button) only the parent grid fetchs data from database when we scroll the vertical scroll bar
