### ISSUE TITLE
IgxGrid Pinning keyboard navigation is not working when there are pinned columns

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#803]
### Description  
Keyboard navigation is not working when there are pinned columns

### Steps to reproduce  

1. Scroll to the end unpinned area
2. Select a cell from last pinned column
3. Press right arrow key

### Result  
The selected cell is the last one from the unpinned area

**Note:** There are similar scenarios causing issues with the pinning and keyboard navigation

### Expected result  
The selected cell should be the first one from the unpinned area

### Attachments  
![image](https://user-images.githubusercontent.com/1182001/37709589-5a5afae4-2d13-11e8-9aad-ebc111ec4a75.png)

**Comment by ChronosSF** [comment]
Another scenario that may be caused by the same issue:

1. Unpin all columns in that sample
2. Scroll all the way to the right
3. Select a cell and use keyboard navigation to get back to the start

- you can't - the grid stops scrolling at the start of the current chunk.

**Comment by MayaKirova** [comment]
Both scenarios are due to #769. scrollPrev() fails when scrolled to the right edge, the grid doesn't scroll to the correct chunk so the wrong cell is focused.
