### ISSUE TITLE
IgxGrid Pinning Scrollbar thumb changes its position when pinning columns

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#804]
### Description  
Pinning a column is changing the position of the scrollbar thumb

### Steps to reproduce  

1. Scroll till the end of the unpinned area
2. Pin a column

### Result  
Scroll thumb has changed its position

### Expected result  
Scrollbar thumb should behave consistently. Either always resetting its position at the beginning or retaining its current position

### Attachments  
![image](https://user-images.githubusercontent.com/1182001/37709965-b7679df4-2d14-11e8-8fc6-fb652988ae1b.png)

**Comment by ChronosSF** [comment]
This can be deferred for next sprint.

**Comment by MayaKirova** [comment]
@ChronosSF IMO this is the default browser behavior. If the scroll container size changes, the scroll left will also change.
