### ISSUE TITLE
Auto select children in tree grid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#8040]
## Is your feature request related to a problem? Please describe.
It would be useful to have a mode for the grid, where selecting a parent would also select all children (recursively).

## Describe the solution you'd like
Essentially the same request as #7344, but for tree grid instead of grouping.

**Comment by Eralmidia** [comment]
@kdinev Just a quick question about this feature request. Will this be considered as a feature, and if so, is there any chance for it this year? Just wondering, since I need this for a feature in our software being released towards the end of this year. So if it won't be included, I will have to look into implementing this manually.

**Comment by kdinev** [comment]
@Eralmidia Honestly, I thought we had cascading selection already implemented. I believe it's an important feature, so we will try to prioritize it high!

Including @DiyanDimitrov and @radomirchev.

**Comment by Eralmidia** [comment]
@kdinev Brilliant, thanks a lot. I'll await further updates on this 😃

**Comment by DiyanDimitrov** [comment]
I have updated the [Tree Grid spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxTreeGrid-Specification) with the option for cascade selection.

**Comment by godly-devotion** [comment]
If anybody wants to have this behavior now, please take a look at this example:
https://stackblitz.com/edit/igxtreegrid-select-nested-children-rows-fkpouh?file=src/app/tree-grid-selection-template-numbers/tree-grid-selection-template-numbers.component.ts

**Comment by kdinev** [comment]
@godly-devotion The only difference with the implementation we will push is that this doesn't have partial checkbox states on parent nodes when only part of the children are selected. Other than that it looks good!
