### ISSUE TITLE
Entering edit mode on igx-tree-cell does not focus the input

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#8041]
## Description  
When having a tree grid cell and trying to enter cell edit mode, there is no focus on the input within.

 * igniteui-angular version: 10.2.x
 * browser: 

## Steps to reproduce  

1. Open Tree grid flat data dev sample
2. Pin any editable column (for example Salary)
3. Enter edit mode on any cell of the above column (with double click)

## Result  
Observe that the input is not focused.

## Expected result  
The input should be focused and you should be able to write/edit without clicking one more time.

## Notes
This is something related to the difference between the template of cell component and tree cell component. The issue is only reproducible on tree cell.

![editmode](https://user-images.githubusercontent.com/37667452/91044139-7a637580-e61d-11ea-9e73-f0dc44928f9b.gif)

**Comment by Aleksandyr** [comment]
@mddragnev Cannot reproduce the issue.
![tree-grid-edit](https://user-images.githubusercontent.com/7037740/95751853-d8204f80-0ca7-11eb-8479-728982f80972.gif)

**Comment by mddragnev** [comment]
@Aleksandyr Might have been fixed meanwhile. You should close the issue now.
