### ISSUE TITLE
Grid Toolbar refactoring

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#8055]
## Is your feature request related to a problem? Please describe.
Right now if you need to show `IgxToolbar` you should set `showToolbar` to `true`. However if you enable `columnHiding`, `columnPinnig`, `exportExcel` or `exportCsv` inputs in the grid nothing will change if `shorToolbar` is set to `false`.

Additionally you can template the toolbar by adding `ng-template` with `igxToolbarCustomContent` directive.

What is better is to have `igxToolbar` component and to be able to put this component in the grid. It could has its own inputs like `exportExcel`, `exportCsv` and so on. The new component should be easily templateable too. Right now there is no easy way to show column hiding in the toolbar and to the right of it some other content. There is also no way to change the order and location of column hiding, column pinning and export are shown.

## Describe the solution you'd like
Add `igxToolbar` component and allow to add it as a child to the `IgxGrid`, the same way pager is working. Allow customizing of the toolbar, e.g. show column hiding, column pinning and export buttons with child components as this is done in the `IgxCard`.

**Comment by kdinev** [comment]
As part of this work item, please also implement #6858

**Comment by StefanIvanov** [comment]
[spec](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Toolbar-Specification#end-user-experience) has been updated to account for the responsive design behavior of the toolbar content
