### ISSUE TITLE
Certain total row heights cause the first row to appear half-visible

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#806]
### Description  
You can have a grid that is scrolled to the bottom, the vertical scrollbar does nothing and the first row is only half visible without any chance for the end-user to see it fully.

### Steps to reproduce  

1. Open the Column Pinning Sample (igxgrid-pinning-dev branch unless it's already in master)
2. Filter the Phone column by "Contains" 0
3. Observe the grid, try to scroll up or down

### Result  
The first row is half-visible and this cannot be changed

### Expected result  
The margin-top applied to be reversible through the scroll action or some other fix

**Notes**
- This is related and caused by #757 
- This may not be applicable to the code after the virtualization improvements by @skrustev - it should first be tested there before a fix is applied to the current code.

**Comment by MayaKirova** [comment]
@ChronosSF Cannot reproduce on Svetoslav's branch - https://github.com/IgniteUI/igniteui-angular/tree/SKrastev/virt-fixed-offsets . The virtualization improvements there already fix this issue.

**Comment by ChronosSF** [comment]
Related to #768
