### ISSUE TITLE
Ensure editor works as expected when using a custom template and input field is editable

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#8065]
## Description  
- Currently, when there is a user **template** specified, the editor does not go through the **calculateDate()** method and if the input is not read only, it will cause incorrect component behavior during input.
- Should make sure the input value format is recognized/parsed as a valid one.

Sample - [link](https://stackblitz.com/edit/github-7xy3tu-gc2tkt?file=src%2Fapp%2Fdatepicker-sample-1%2Fdatepicker-sample-1.component.html)

**Comment by jackofdiamond5** [comment]
The issue will be resolved in https://github.com/IgniteUI/igniteui-angular/issues/6483
