### ISSUE TITLE
Grid row selection box on hover

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#8066]
## Question  
While the row selection checkbox is a nice feature, it does add quite a bit of noice to UI. 
![image](https://user-images.githubusercontent.com/12936286/91703907-391e1900-eb7b-11ea-9a73-1500db2d734f.png)

Is it currently possible to get a behaviour similar to windows explorer, where the checkbox only is visible on hover?

![image](https://user-images.githubusercontent.com/12936286/91703850-1ee43b00-eb7b-11ea-8a0c-70cf97ca9e02.png)

**Comment by ddincheva** [comment]
Hello @Eralmidia, 
The requested behavior is not supported by default but can be easily achieved with some additional code on the application level.
I managed to build 2 sample applications that show how this behavior can be delivered either using the [row selection template](https://stackblitz.com/edit/github-sroddx-fk3d6i?file=src/app/grid/grid-sample-selection-template-numbers/grid-sample-selection-template-numbers.component.ts) or using the provided new[ action strip component](https://stackblitz.com/edit/github-sroddx?file=src/app/grid/grid-sample-selection-template-numbers/grid-sample-selection-template-numbers.component.html).
Please check out the samples and let me know if you have any further questions or comments and recommendations.

**Comment by Eralmidia** [comment]
Hi @ddincheva 

Thanks a lot, I'll check the samples 😃

**Comment by Eralmidia** [comment]
Seems like it's working fine, I'll close down this issue 🙂

**Comment by Eralmidia** [comment]
@ddincheva I tried implementing the sample in our code (using the row selection template method), and it seems to work for a igx-grid, but not for a igx-tree-grid. Are there some considerations to be made when using this component?

**Comment by Eralmidia** [comment]
Never mind, solved it by changing the igx-grid-cell to igx-tree-grid-cell 👍
