### ISSUE TITLE
Cannot read property 'length' of undefined at IgxForOfDirective._calculateChunkSize

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#807]
### Description  
The grid should work with async pipes, and when the observable result is present, I should be able to pass it with async only.

In our demos.dev/grid sample, "BehaviorSubject" is used to overcome the issue when undefined data is returned, not to throw exception. Also as you can see default data of empty array is passed, which is not correct.

```
@Injectable()
export class RemoteService {
    public remoteData: Observable<any[]>;
    private url: string = "http://services.odata.org/V4/Northwind/Northwind.svc/Products";
    private _remoteData: BehaviorSubject<any[]>;

    constructor(private http: Http) {
        this._remoteData = new BehaviorSubject([]);
        this.remoteData = this._remoteData.asObservable();
    }

    public getData(data?: Array<any>, cb?: () => void): any {
.....
```

Sample with the issue:
https://stackblitz.com/edit/igx-grid-crud-with-firebase?embed=1&file=app/app.component.html&view=preview

### Causes of the issue
When we do not have paging enabled this issue is present.
### Image with the exception

![image](https://user-images.githubusercontent.com/11193764/37721369-f354dd96-2d31-11e8-9f90-759cbb5c522b.png)

**Comment by zdrawku** [comment]
Additional note:

When we have paging set to true, the transform paging pipe method is using the cloneArray method, which is creating the empty array [].

Code:

```
export function cloneArray(array) {
    const arr = [];
    if (!array) {
        return arr;
    }
    let i = array.length;
    while (i--) {
        arr[i] = array[i];
    }
    return arr;
}
```


Possible approach that we could follow in order to fix the issue would be to create get and set properties for 'data' option, and when data is not passed we will set empty array []

**Comment by MayaKirova** [comment]
Actually, this would also reporduce with just an igxFor directive when there's initially no data set (null/undefined) for the igxForOf prop. So this should be handled in the igxFor directive.

**Comment by zdrawku** [comment]
I totally agree with you, @MayaKirova
