### ISSUE TITLE
Igx-tree-grid drop row "between" rows

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#8075]
## Question  
Is there any way to mimic the behaviour of a ig-tree when using row drag in the igx-tree-grid? 

If we look at the old ig-tree component, you could do a drag operation like this:
![image](https://user-images.githubusercontent.com/12936286/91935272-a5b92500-eced-11ea-982b-9f10baad160f.png)

This would move the dragged item in the tree inside the test-1-1-1 item. But then, if you move the cursor slightly higher, you get this behavior:

![image](https://user-images.githubusercontent.com/12936286/91935349-cf724c00-eced-11ea-97fc-5cde50a1a9c4.png)

Now you are instead moving it before the test-1-1-1 item, not inside it. We are modernizing a module which used the jquery based components, but now shall use the igx components instead. However there is (yet?) no igx-tree component available, so we need to replicate the same functionality with a tree-grid.

**Comment by ViktorSlavov** [comment]
@Eralmidia 
You could create a similar behavior in the `IgxTreeGrid` using the [row drag](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row_drag.html) functionality along w/ some custom handling of the [dragMove](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdragdirective.html#dragmove) event and a [custom drag ghost](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row_drag.html#templating-the-drag-ghost):
When [`onRowDragStart`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtreegridcomponent.html#onrowdragstart) is fired, you attach a custom handler to the underlying [`igxDragDirective`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdragdirective.html)'s `dragMove` event. In that handler, you check the current cursor position relative to the displayed rows (so you can get the name of the item under or next to which your row will be "dropped").
To edit the displayed overlay (e.g. "Move to XYZ"), you can pass a custom drag ghost.
For more information about the setup for the row re-ordering, you can check [this section](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row_drag.html#application-demo) in our documentation.

I've put together a small [Code Sandbox sample](https://codesandbox.io/s/heuristic-nightingale-kghks?file=/src/app/tree-grid-row-reorder/tree-grid-row-reorder.component.scss) - please take a look and let us know if this somewhat covers your usecase.

**Comment by Eralmidia** [comment]
@ViktorSlavov  Thanks a lot for the sample. I will use this as a starting point for what I need. I'll close down the issue and reopen if I run into issues.
