### ISSUE TITLE
Feature request: Add submenus for NavigationDrawer

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#8094]
## Is your feature request related to a problem? Please describe.
Currently submenus aren't part of the NavigationDrawer implementation, they have to be hand-builded by the developer. Material already establishes a set of rules for NavigationDrawer menus and submenus and I think it would be great that you provide us with some pre-build ones.

## Describe the solution you'd like
I would expect an specific Array of objects to be passed to the igxDrawerItem (childs?). Also similar to your current "strategy" configuration (positionStrategy, scrollStrategys, etc) I would expect to configure each object with a "SubMenuStrategy". So I can choose if the child's will be displayed as direct childrens (that's the default behaviour for most navigation drawers, **but according to material, only allows 2 levels**), floating sub-menus (**sidenavs spec** [here](https://material.angular.io/components/sidenav/examples), **someones implementation:** [desktop here](https://jsfiddle.net/alvaromenendez/9m60mx6r/7/), [mobile here](https://tympanus.net/Development/ResponsiveMultiLevelMenu/index2.html)).

Currently developers can achieve the desired result by using flags to show/hide the "child" options, however... Some extra features are expected (For example: animations, dividers, breadcrumbs).

For **DESKTOP** usage, I think  FluentUI guidelines are the best:
https://developer.microsoft.com/en-us/fluentui#/controls/web/nav

## Describe alternatives you've considered
Currently I'm using my own styles and flags to fulfill the desired behaviour, however is way to much work to maintain... 

## Additional context
https://material.io/components/navigation-drawer

**Comment by luiscla27** [comment]
I've just added sample 3 implementations, currently this is more or less what doing:

- [Desktop 1](https://www.jqueryscript.net/demo/Multilevel-Sliding-Menu-jQuery-Mobile-Menu/)
- [Desktop 2](https://jsfiddle.net/alvaromenendez/9m60mx6r/7/)
- [Mobile](https://tympanus.net/Development/ResponsiveMultiLevelMenu/index2.html)

**Comment by mmart1n** [comment]
Hi, thanks for bringing this to our attention and helping us improve our product! This is added to the backlog and you can use this issue to track any progress updates on the feature. Meanwhile I believe you will find the following [demo project](https://stackblitz.com/edit/github-igxnavdrawer-submenus-animations) I have prepared for you very helpful. As you can observe it is demonstrating a possible way of creating an igxNavigationDrawer with animated submenus which is looking very similar to the mobile implementation you have provided.
