### ISSUE TITLE
Igx-Grid Remote Filtering and UniqueColumnValuesStrategy

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#8132]
## Description  

After performing a filter request I receive the following error:

![image](https://user-images.githubusercontent.com/60701497/92925783-e8d47000-f432-11ea-833b-b2ad393df2df.png)
`zone-evergreen.js:171 Uncaught TypeError: Cannot read property 'dataType' of null
    at igniteui-angular.js:34562
    at custom-grid.component.ts:552
    at remoteValues.service.ts:87
    at u.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27428)
    at u.invokeTask (zone-evergreen.js:398)
    at s.runTask (zone-evergreen.js:167)
    at invokeTask (zone-evergreen.js:480)
    at o.useG.invoke (zone-evergreen.js:469)
    at r (zone-evergreen.js:2552)`

code of the error:
![image](https://user-images.githubusercontent.com/60701497/92926298-b37c5200-f433-11ea-83f5-8c325e192e7d.png)

`        renderColumnValuesRemotely() {
            this.loadingStart.emit();
            const expressionsTree = this.getColumnFilterExpressionsTree();
            this.grid.uniqueColumnValuesStrategy(this.column, expressionsTree, (colVals) => {
                const columnValues = (this.column.dataType === DataType.Date) ?
                    colVals.map(val => val ? val.toDateString() : val) : colVals;
                this.renderValues(columnValues);
                this.loadingEnd.emit();
            });
        }`

 * igniteui-angular version: 10.1.3
 * browser: Chrome
 * angular: 10.1.0

## Steps to reproduce  

1. Apply a filter to a column

## Result  
Filters correctly and shows error on the console

## Expected result  
Filtering without the error on the console

**Comment by kdinev** [comment]
@MiguelPetrotec I see that you're trying to force the call of the `uniqueColumnValues` strategy. Instead you should provide a function, which the grid will call on it's own in its filtering lifecycle. The strategy method to provide to the grid will receive as arguments the column it's called for, the current expression tree and a callback method to invoke once loading of the unique values has concluded.

e.g.
```ts
public columnValuesStrategy(column: IgxColumnComponent, columnExprTree: IFilteringExpressionsTree,
                                               done: (uniqueValues: any[]) => void) => {
    // Get specific column data.
    const columnValues = //get column values with custom method
    done(columnValues);
}
```

and grid template:
```
<igx-grid #grid1 [data]="data" [filterMode]="'excelStyleFilter'" [uniqueColumnValuesStrategy]="columnValuesStrategy">
    ...
</igx-grid>
```

**Comment by MiguelPetrotec** [comment]
The error disappeared after some changes on other component.

Thank you for your help.

Best regards,

Miguel Domingues
