### ISSUE TITLE
Header and footer fixed sections

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#8133]
Nav-drawer can contain sections that don't look and behave like a traditional nav-item. As in, these sections will not have hover and active styles, and users can add any kind of content inside these sections. This could be supported with an official header and footer section that have a fixed position in the nav-drawer. Header sections should be aligned to top, while footer section should be aligned to the bottom. 
![image](https://user-images.githubusercontent.com/41998471/92926973-8d5fad80-f445-11ea-85a5-bccc8f124fcd.png)

**Comment by DaniMarinov** [comment]
@radomirchev is this planned as an extension of the nav drawer component?

**Comment by DaniMarinov** [comment]
Guys, is this already planned?

**Comment by radomirchev** [comment]
@DaniMarinov already discussed in a meeting for the next Milestone.

**Comment by DaniMarinov** [comment]
Thanks

**Comment by kdinev** [comment]
@DaniMarinov @damyanpetev Correct me if I'm wrong, but this FR doesn't actually have any added value to the component. If there's no such sections, as the component currently is, then the definition of such sections would look like this:

```html
<igx-nav-drawer [pinThreshold]="1600" id="navigation" #drawer>
    <ng-template igxDrawer>
      <!-- HEADER -->
      <div style="height: 300px; display: flex; flex: 0 0 100%; flex-flow: column; align-items: center; justify-content: center;">
        <igx-avatar initials="PR"></igx-avatar>
        <span>PROFILE</span>
      </div>
      <nav>
        <span igxDrawerItem [isHeader]="true">&nbsp;</span>
        <span igxDrawerItem igxRipple routerLink="tournament">
          <igx-icon>emoji_events</igx-icon>
          <span i18n>Tournaments</span>
        </span>
        ...
        
        <!-- FOOTER -->
        <div style="position: fixed; bottom: 0%; height: 120px">
          <span igxDrawerItem igxRipple routerLink="/" fragment="aboutus">
            <igx-icon>chat</igx-icon>
            <span i18n>Contact us</span>
          </span>
          <span igxDrawerItem igxRipple routerLink="/" fragment="aboutus">
            <igx-icon>chat</igx-icon>
            <span i18n>Contact us</span>
          </span>
        </div>
      </nav>
    </ng-template>
``` 

With the feature request, the sections would look like this:

```html
<igx-nav-drawer [pinThreshold]="1600" id="navigation" #drawer>
    <ng-template igxDrawer>
      <div igxDrawerHeader style="height: 300px; display: flex; flex: 0 0 100%; flex-flow: column; align-items: center; justify-content: center;">
        <igx-avatar initials="PR"></igx-avatar>
        <span>PROFILE</span>
      </div>
      <nav>
        <span igxDrawerItem [isHeader]="true">&nbsp;</span>
        <span igxDrawerItem igxRipple routerLink="tournament">
          <igx-icon>emoji_events</igx-icon>
          <span i18n>Tournaments</span>
        </span>
        ...
        
        <div igxDrawerFooter style="position: fixed; bottom: 0%; height: 120px">
          <span igxDrawerItem igxRipple routerLink="/" fragment="aboutus">
            <igx-icon>chat</igx-icon>
            <span i18n>Contact us</span>
          </span>
          <span igxDrawerItem igxRipple routerLink="/" fragment="aboutus">
            <igx-icon>chat</igx-icon>
            <span i18n>Contact us</span>
          </span>
        </div>
      </nav>
    </ng-template>
``` 

The CSS positioning would still be up to the developer. If you need this for the App Builder, then define such templates in the App Builder itself as markup that is produced from the toolbox, but the component itself doesn't need to have such areas defined.

**Comment by DaniMarinov** [comment]
@pmoleri @ig-georgeA after brief discussion with @rkaraivanov and @kdinev, we decided that this change can be handled by the AB team or Ignite UI team, but this change will not be introduced to the Ignite UI product. Since its priority is not high, it is postponed for now.

**Comment by ig-georgeA** [comment]
Ok. So app builder can define:

Header  ON/OFF
Footer ON/OFF

and then users can drop whatever they like into these sections. 

@pmoleri @VladB93 
- I suppose this can either follow the same pattern we have for expansion panel, and if users want component layout in there, they will add a col/row layout. 
- Or handle it like tab-layout and we allow users to select "Header-content" but prevent deleting it. This way users can choose layout properties. Since it's not part of the component anyway, we can do the tab-layout route. And have a min-height set on it.

Any concerns?

**Comment by VladB93** [comment]
@ig-georgeA  The only concern is that usually the app builder doesn't try to do any "magic" in the means of creating custom parts to the component. We try to showcase the component as is in the IgniteUI toolbox. Adding a custom footer and header would lead the user to believe they can code a navdrawer by putting everything in some directive and it would work - while in reality they would need to create their own styles and containers for header and footer. I think this was the original concern - other than that we're fine with doing it in the appbuilder.
