### ISSUE TITLE
Can't entry a time from the keyboard after resetting the time with the reset button.

### ISSUE THREAD

**Issue by furugen** [IgniteUI/igniteui-angular#8146]
## Description  
Can't entry a time from the keyboard after resetting the time with the reset button.

 * igniteui-angular version: 10.1.2
 * browser: Chrome

## Steps to reproduce  

Sample
https://bnmiogaba.github.stackblitz.io
(Source : https://stackblitz.com/github/bnmiogaba)

1. Click time icon.
1. Set hour and minutes.
2. Click reset button.
3. Entry hour and minutes from the keyboard.

![sample](https://user-images.githubusercontent.com/8131662/93165720-d1112a80-f757-11ea-9cfe-8ea61927d60a.gif)

## Result  
Can't entry hour and minutes after click reset button.

## Expected result  
Allow enter hour and minutes after click reset button.

## Attachments  
Sample
https://bnmiogaba.github.stackblitz.io
(Source : https://stackblitz.com/github/bnmiogaba)
![sample](https://user-images.githubusercontent.com/8131662/93165720-d1112a80-f757-11ea-9cfe-8ea61927d60a.gif)

**Comment by Lipata** [comment]
Due to the [following](https://github.com/IgniteUI/igniteui-angular/pull/8235#discussion_r497433755) comment in the PR, related to that issue, first, we need to work on [igxTimePicker refactoring](https://github.com/IgniteUI/igniteui-angular/issues/6482)
