### ISSUE TITLE
IGX-Grid Excel Exporting file problem and allowed formats

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#8168]
[ExportedExample.zip](https://github.com/IgniteUI/igniteui-angular/files/5237637/ExportedExample.zip)

## Description  
Passing the array directly to the “ExportService” and asked for a xlsx format the “ExportService” didn’t return any file or feedback of what is happening, then I passed an other array with simple data and it worked fine exporting the xlsx file.

Then I manipulated the response to exclude from the array the object types entries and dates, because it doesn’t like these two formats for the dates “2020-02-12T17:25:27” and “2020-02-12 17:25:27”, after that the file exported ok.

After I tried to export to CSV and detected that all the values go inside like the exemple file attached.

If not implemented I think that the “ExportService” should have any kind of notification when it has a problem processing the data passed, because it is not giving any kind of feedback and also doesn’t accept any other call after breaking, to work again a refresh is needed.

About the formats is there a place to check or can you tell me what formats are valid?
I know that the object types inside the file must be flattened.

Best regards,

Miguel Domingues 

 * igniteui-angular version: 10.1.3
 * browser: Chrome

**Comment by onlyexeption** [comment]
Hello Miguel, the issue that you had with exporting objects is already resolved in issue #8466 
We also have an opened issue (#8481), regarding the export of dates which will fix the problem for you when resolved!
