### ISSUE TITLE
Remote Filtering combining values with "AND" and "OR" in a column

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#8170]
## Description  

The object passed by the Grid when doing an OR operation in a column and an AND operation is different, it's supposed to be this way?

the following imagens show the respective object for each filter operation performed.

I need to parse this values to make the requests to the server.

 * igniteui-angular version: 10.1.3
 * browser: Chrome

Operator OR:
![image](https://user-images.githubusercontent.com/60701497/93449951-45b9a580-f8cd-11ea-9f64-116bfe342718.png)

![image](https://user-images.githubusercontent.com/60701497/93449418-a1cffa00-f8cc-11ea-91c4-2323207dab03.png)

Operator AND:
![image](https://user-images.githubusercontent.com/60701497/93450044-6255dd80-f8cd-11ea-8a00-e63de7c4a674.png)

![image](https://user-images.githubusercontent.com/60701497/93450122-7d285200-f8cd-11ea-9a7e-f05f0890baaa.png)

**Comment by kdinev** [comment]
@MiguelPetrotec Yes, the filtering login is different, hence the expression tree that is created differs. In the first case both filters are applied separately on the complete set and a join of the two filters is returned, while in the second case both filters are applied first on the complete data set and the second on the result of the first filter and then an intersection of the two filters is returned.
