### ISSUE TITLE
Calendar shows wrong month

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#8173]
## Description  
When `value` is set in `IgxCalendar` template, calendar does not show the correct month and year.

 * igniteui-angular version: 10.1
 * browser: all

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/github-6wddr6?file=src%2Fapp%2Fcalendar-sample-5%2Fcalendar-sample-5.component.ts) sample.
2. Observe shown month and year.

## Result  
Calendar shows current day month and year.

## Expected result  
Calendar should scroll to the date representing the value, e.g. in the attached sample it should show January 1958.

**Comment by hanastasov** [comment]
The calendar has bith the `value` and the `viewDate` properties. By definiton, `viewDate` defaults to current day if not explicitly set, and determines what month will be displayed in the calendar.

At the same time, `value` holds the selected date, if any, and I do not see anywhere in our docs that the selected date should determine the displayed month.

By making this change we are making the `viewDate` dependent on `value`, which controverses what our API docs say.

IMO this change should be reverted.

**Comment by ddincheva** [comment]
> The calendar has bith the `value` and the `viewDate` properties. By definiton, `viewDate` defaults to current day if not explicitly set, and determines what month will be displayed in the calendar.
> 
> At the same time, `value` holds the selected date, if any, and I do not see anywhere in our docs that the selected date should determine the displayed month.
> 
> By making this change we are making the `viewDate` dependent on `value`, which controverses what our API docs say.
> 
> IMO this change should be reverted.

In the sample linked in this issue there is no viewDate set only a value. If the viewDate is set its value is taken. This bug fix is related to the scenarion when there is no viewDate set, only a value.

**Comment by hanastasov** [comment]
>
> In the sample linked in this issue there is no viewDate set only a value. If the viewDate is set its value is taken. This bug fix is related to the scenarion when there is no viewDate set, only a value.

The API docs say that `viewDate` defaults to current day if not set, but actually it is made to default on the `value`, if present. This seems incorrect to me.

**Comment by wnvko** [comment]
I do not know what is correct. IMO if:
- you have no `value` nor `viewDate` it should open calendar in today.
- you have `value` but have no `viewDate` it should open calendar as set in `value`.
- you have `viewDate` it should open calendar where as set in `viewDate`.
Again this is how I think is correct. To solve this we should ping UI/UX guys.

**Comment by hanastasov** [comment]
@StefanIvanov could you please share the UX view point? Basically we have a dedicated `viewDate` property that determines what month is displayed in the calendar. Before this change, and according to API docs, `viewDate` will fallback to the current day, if not set explicitly.

Current behavior, after this change, makes `viewDate` dependent on `value`, if `value` is set. This makes our API docs wrong on the behavior. Also, it makes it hard to apply same logic if we have range, especially multi selection (which value among the N number selected dates would serve as the `viewDate`>).

**Comment by StefanIvanov** [comment]
From a pure UX/UI point of view, the bug fix makes sense because it enables a scenario where the calendar header is used to show the current selection. Talking about the calendar we may have it embedded in a page or show from any element e.g. a button and that would not mean that the end-user will have a clear indication elsewhere about the selected values. For the case where we have a range selection, I think the header should display a value e.g. Mon, Jan 1 - Mon, Jan 5 which is of course as long as a viewDate is not set. So in short, I am against reverting the change and what we have to do instead is update our API docs accordingly.

**Comment by hanastasov** [comment]
> Talking about the calendar we may have it embedded in a page or show from any element e.g. a button and that would not mean that the end-user will have a clear indication elsewhere about the selected values. 

I understand that, but for me it seems like we are presuming like selection is the main purpose of the calendar, which dictates the behavior. If this is true, then fine. But then maybe `special` dates should also dictate the behavior.

Let's extend on this example: a button brings up the calendar, and the user would like to see if there are any selected dates **in the current month.**.

Result:
Calendar brings up a different month.

**Comment by StefanIvanov** [comment]
@hanastasov in your example I think with the introduced behavior the user can see both by checking the header for the selection and by navigating to the current month via the calendar UI and seeing what is marked on the days view.

**Comment by hanastasov** [comment]
> @hanastasov in your example I think with the introduced behavior the user can see both by checking the header for the selection and by navigating to the current month via the calendar UI and seeing what is marked on the days view.

And with the previous behavior user was able to see both in one screen (header indicates the selected value), without additional interaction with the UI. Sounds better to me.

**Comment by hanastasov** [comment]
https://github.com/IgniteUI/igniteui-angular/issues/8173 the issue for correcting the API docs.

**Comment by StefanIvanov** [comment]
@hanastasov thanks for taking care of this!
