### ISSUE TITLE
Manipulating Data for List in Excel-style Filtering

### ISSUE THREAD

**Issue by carmo-evan** [IgniteUI/igniteui-angular#8175]
## Question  
Our team has been looking into different ways we can customize filters for the data grid. Specifically, we would like to be able to manipulate and control the data that builds out the list below the search in excel-style filtering. Is there a way to do that currently or plans to add that ability in the future?

 * igniteui-angular version: 10.1

**Comment by zdrawku** [comment]
Hey @carmo-evan, currently we do provide templates for both ColumnOperations and FilterOperations which you can use to re-template the area with column operands like sorting, moving etc. and the area with filter specific operations - check out [this topic section ](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel_style_filtering.html#templates)for more information .
There you can see a list of all filtering components that you could use/change.
