### ISSUE TITLE
Copy to clipboard of selected text causes error in IE11

### ISSUE THREAD

**Issue by michalsgit** [IgniteUI/igniteui-angular#8176]
## Description  
 * igniteui-angular version: 9.0 and newer
 * browser: IE11(error) all browsers(behavior)

## Steps to reproduce  

1. Open page https://www.infragistics.com/products/ignite-ui-angular in IE11
2. Open Developer Tools
3. Select any text in a cell in the grid
4. Press Ctrl+C

## Result  
It generates error: ERROR TypeError: Unable to get property 'setData' of undefined or null reference
In the clipboard is the whole content of the cell and header.

## Expected result  
No error should occure and only the selected text should be in the clipboard.

## Attachments  
![IgxGridIE11CopyClipboardError](https://user-images.githubusercontent.com/6318187/93484709-88e23b80-f902-11ea-871c-7baa4933044a.png)

**Comment by Aleksandyr** [comment]
@ddincheva Another error is coming when you just click over a cell and start spamming with ctrl+C
![image](https://user-images.githubusercontent.com/7037740/97449068-f5a51880-1939-11eb-8d89-b48b4cfc64e3.png)

**Comment by Aleksandyr** [comment]
@ddincheva It seems that [this ](https://github.com/microsoft/ChakraCore/issues/1071 )suggestion fixes the issue.
Does it count as a third party issue then?

**Comment by ddincheva** [comment]
@Aleksandyr, 
I think that since the problem is related to the browser-specific settings that we have no control over we can consider the described problem as a third-party issue.
