### ISSUE TITLE
Grid default edit templates styles are broken with all themes

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular#8181]
The default editing templates in the grid seem broken in master with all themes.

 * igniteui-angular version: master branch
 * browser: all

## Steps to reproduce  

1. Open the dev demos grid editing sample
2. Enter in edit mode in a cell
3. Observe

## Result  
![image](https://user-images.githubusercontent.com/20106115/93593773-5b0dfd00-f9bd-11ea-87f1-7d03045c395b.png)

![image](https://user-images.githubusercontent.com/20106115/93593809-68c38280-f9bd-11ea-8174-aba444791d9c.png)

## Expected result  
![image](https://user-images.githubusercontent.com/20106115/93594038-cbb51980-f9bd-11ea-8799-13fea3bf5f46.png)

![image](https://user-images.githubusercontent.com/20106115/93594068-db346280-f9bd-11ea-80d5-0d413566b162.png)

**Comment by valadzhov** [comment]
PR [#8198](https://github.com/IgniteUI/igniteui-angular/pull/8198) was created and it fixes the issue visible in the second screenshot - the "Date" label in the date picker. The other issue (the shrinked) grid doesn't seem to be related to the date picker changes and is not fixed with this PR.
