### ISSUE TITLE
i18n not being applied on buttons for hide/pin dropdowns.

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular#8185]
## Description  
The buttons on hide/pin dropdowns are not being translated according to their respective resources.

By the way, I read #2517 but it's not working for me as seen on the screenshots. Only the search input is being updated.

 * igniteui-angular version: 10.1.4
 * browser: Firefox

## Steps to reproduce  

1. Add a translation for the following resources:
```ts
igx_grid_hiding_check_all_label: 'Hide All PPP',
igx_grid_hiding_uncheck_all_label: 'Show AllAAA',
igx_grid_pinning_check_all_label: 'Pin All AAAA',
igx_grid_pinning_uncheck_all_label: 'Unpin All QQQQ',
igx_grid_toolbar_actions_filter_prompt: 'Filter columns list QQQ'
```
2. Change to that resource
3. See that only `igx_grid_toolbar_actions_filter_prompt` was translated.

## Result  
Buttons did not translate.

## Expected result  
Buttons to translate.

## Attachments  
![Screen Shot 2020-09-21 at 09 47 22](https://user-images.githubusercontent.com/2049255/93769196-dacfdd80-fbf0-11ea-96ca-5b0caf225563.jpg)
![Screen Shot 2020-09-21 at 09 43 28](https://user-images.githubusercontent.com/2049255/93769200-dc010a80-fbf0-11ea-9a2a-e9f25d28dc5e.jpg)

**Comment by eestein** [comment]
Hi, any news on this one?

**Comment by eestein** [comment]
@zdrawku @Lipata @DiyanDimitrov @ChronosSF 
Seriously? Not even a feedback? It's been over 23 days now!

**Comment by dkamburov** [comment]
@eestein Apologize for the delayed response, sounds like there is an issue with the localization resources for the hiding UI of the toolbar. Until we provide a fix for it you can use [columnHidingUI ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridtoolbarcomponent.html#columnhidingui) property of the toolbar to set the labels of the buttons
```
ngAfterViewInit() {
    this.grid1.toolbar.columnHidingUI.checkAllText = '[Localized]Show All';
    this.grid1.toolbar.columnHidingUI.uncheckAllText = '[Localized]Hide All';
}
```
