### ISSUE TITLE
 igxRowEditText and igxRowEditActions directives are missing in API documentation

### ISSUE THREAD

**Issue by jacevedo529** [IgniteUI/igniteui-angular#8186]
## Description  
The igxRowEditText and igxRowEditActions directives for the igx-grid Row Editing feature are missing in API documentation:
[https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/index.html](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/index.html)

**Comment by ViktorSlavov** [comment]
@jacevedo529 These shouldn't really be visible in the public API, as they don't have any methods/properties, they just expose the directive selectors. Thanks for catching that!
