### ISSUE TITLE
A small badge option

### ISSUE THREAD

**Issue by YoannaIvanova** [IgniteUI/igniteui-angular#8188]
## Is your feature request related to a problem? Please describe.
I found it difficult to use the current badge size in combination with an avatar on mobile because it looks unnecessarily large for this case.

## Describe the solution you'd like
In addition to the current badge, there should be a smaller badge size, which will be useful for better coverage of other scenarios.

## Additional context
![image](https://user-images.githubusercontent.com/61508933/93996089-7c466300-fd9a-11ea-8ba9-00435cf45b8e.png)
![image](https://user-images.githubusercontent.com/61508933/93996312-c3ccef00-fd9a-11ea-8929-9d7e3c90e0b6.png)
![image](https://user-images.githubusercontent.com/61508933/93996670-33db7500-fd9b-11ea-8f12-396dfec1f2c4.png)

**Comment by simeonoff** [comment]
@YoannaIvanova The attached PR allows you to define custom sizes via additional style rules applied to the badge. We decided to simplify the internal implementation of the badge to allow for robust badge styling, rather than just limit you to size options.
