### ISSUE TITLE
onInteraction event of the igxExpansionPanelHeaderComponent is not cancelable

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#8190]
## Description  
In regards to a customer requirement of being able to toggle the panel by clicking on the expand/collapse indicator exclusively determined that this event can not be cancelled, which is the best approach for achieving such behavior.

 * igniteui-angular version: 9.1.x, 10.1.x
 * browser: any

## Steps to reproduce  

1. Run this sample: https://stackblitz.com/edit/expansion-panel-cancelable-on-interaction-event
2. Click on the expand indicator
3. Click on the panel`s header

## Result  
Expansion panel is toggled via both expand indicator and panel`s header.

## Expected result  
To have a mechanism for triggering toggling only from the expansion indicator.

**Comment by ViktorSlavov** [comment]
@mmart1n , since this is a new feature (along w/ a deprecation), I'll create a PR for only the latest version for **10.2.x**.
If the customer is not willing to upgrade to the latest version, we can discuss later including the feature a patch for **9.1.x**.
