### ISSUE TITLE
Expose readOnly OverlayId in toggle

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#8225]
## Is your feature request related to a problem? Please describe.
Having `OverlayId` will allow more easy filtering and finding of an overlay created via `IgxToggleDirective`. This will also allow fixing of #8023.

## Describe the solution you'd like
Expose `OverlayId` as read-only property in `IgxToggleDirective`.

Additionally `OverlayId` together with `IgxToggle` instance should be emitted in all events of `IgxToggleDirective`  - `onOpened`, `onOpening`, `onClosed`, `onClosing` and `onAppended`.

## Describe alternatives you've considered
There is no alternative now, but trying to work around this by using private properties, e.g. `_overlayId`.

## Note
This is a feature request, but it will add a single read-only property, therefor this could be added in the old supported versions too. This will allow more easy fixing of above mentioned issue.

**Comment by Lipata** [comment]
This was partially implemented with https://github.com/IgniteUI/igniteui-angular/pull/8213
