### ISSUE TITLE
Add @igniteui/material-icons-extended as a dependency or peer dependency of igniteui-angular 

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular#8227]
## Description  
The **@igniteui/material-icons-extended** package is used in the [source code](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.ts#L3) without being listed as a dependency or peer dependency of igniteui-angular, which respectively breaks the compilation of the applications using our package.

 * igniteui-angular version: 10.2.x

## Steps to reproduce  
Create angular application.
Add igniteui-angular with `ng-add`
Add (e.g.) IgxAvatarModule to the app.module.ts of the application.

## Result  
A compile error is thrown:
![image](https://user-images.githubusercontent.com/25771040/94538252-7219de00-024c-11eb-8b58-bf6ef8a8f940.png)

## Expected result  
The application to run

## Attachments  
[Stackblitz](https://stackblitz.com/edit/icons-error?file=src/app/app.module.ts)

**Comment by ChronosSF** [comment]
Related to #8131
