### ISSUE TITLE
 IconComponent with font awesome support?

### ISSUE THREAD

**Issue by RueDeRennes** [IgniteUI/igniteui-angular#824]
how to configure the iconComponent with font awesome?

**Comment by simeonoff** [comment]
This feature will be in the next version release. It is, however in the master, but it is not documented.

**Comment by SlavUI** [comment]
Closing the issue :) @RueDeRennes if needed please reopen the issue

**Comment by lalo-mx** [comment]
With 6.2.0 Beta 3 the example does not longer works. Maybe it should be included in breaking changes 
 in [6.2.0 Beta 3](https://github.com/IgniteUI/igniteui-angular/releases/tag/6.2.0-beta.3)

**Comment by bkulov** [comment]
@lalo-mx The description of the breaking change was not very clear so I changed it. You should use `name` property for `Font Awesome` icon's name. Sorry for the inconvenience.
