### ISSUE TITLE
Can't edit a date cell if grid's data is of ISO String or Numeric types

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#8256]
* igniteui-angular version: 10.0.x
## Steps to reproduce  

1. Go to gridCellEditing dev sample
2. Edit first date value in the data source:
    OrderDate: new Date('2012-02-12').toISOString()
3. Double click the first cell in the OrderDate column to enter edit mode

## Result  
An error is thrown in the console

## Expected result  
Be able to succesfully edit the cell.

**Comment by zdrawku** [comment]
This also applies to the `ExcelStyleFiltering` feature and it is not only when **ISO String type data** is being used. The same error is thrown when **number type data** is used as Date ([a numerical representation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) of the milliseconds as a unit of measurement could be used)

**Steps to reproduce:**
1. Open [the sample](https://stackblitz.com/edit/github-74rjan?file=src/app/grid/grid-excel-style-filtering-sample-3/grid-excel-style-filtering-sample-3.component.html)
2. Open the excel style filter dialog for `Order date` column
3. Error is thrown - `toDateString()` is not a function

![image](https://user-images.githubusercontent.com/11193764/95205054-88481100-07ed-11eb-8c7e-5103197505cf.png)

**Comment by zdrawku** [comment]
@ddincheva @hanastasov add your comments as well

**Comment by hanastasov** [comment]
Also, when date values come in as string/numbers, sorting and filtering are not correct. Sorting/filtering algortihms need to know if the value is date in number/string format in order to parse it to true Date object.

**Comment by ddincheva** [comment]
This problem has been addressed with PR #9160 and is no longer reproducible on the master branch.
