### ISSUE TITLE
auto complete feature on Igx-select with 'Includes' pipe

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#8273]
## Question  
We need to implement auto complete feature on Igx-select component with 'includes' pipe. Could you please provide any link with documentation if available.

 * igniteui-angular version: 8.2
 * browser: google

**Comment by kdinev** [comment]
There's a separate component, which is an `autocomplete` and is applicable to input and drop-down. The `igx-select` mimics a native html select and doesn't support auto complete, as there's no input to type into.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/autocomplete.html

**Comment by Lipata** [comment]
Hi, @Raju-N.

We have already discussed that and @kdinev gave a detailed answer [here](https://github.com/IgniteUI/igniteui-angular/issues/4338#issuecomment-473819553). One of the points in his answer is that even you don't have input, if you type in the select, while it is on focus, will scroll the list to the first match.
