### ISSUE TITLE
Is there a way i can reset grid scroll and align columns back correctly with rows?

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#8285]
## Question  
The issue I am facing is when I reduce data source to 1 row and scroll the grid to the right.
Then move away from the page and then come back with datasource still having one row and then add more data in datasource the columns gets miss aligned and still are in position of the single row

Check the screenshot below.
![image](https://user-images.githubusercontent.com/20819281/95119570-c7cd1980-0769-11eb-9074-eb39a5e7fa63.png)

 * igniteui-angular version: 
 * browser:

**Comment by ChronosSF** [comment]
Hey @amitmoondra ,

Which version of igniteui-angular are you using?

**Comment by amitmoondra** [comment]
igniteui-angular version 10.1.3

**Comment by ChronosSF** [comment]
Okay. What do you mean "move out of the page"? Do you go to another route of your angular app and come back? Do you use something like "RouteReuseStrategy" for your routes within the app? Does the issue occur if you don't navigate out and in the page with the grid?

**Comment by amitmoondra** [comment]
Move out as in I have different tabs, so I hide the grid tab content but RouteReuseStragtegy is not used as its not needed, route is not changed, but only the tab is switched.
But when I go to other tab I hide the grid so that grid state is not lost.

And issue doesnot occur if i am on same page and change datasource from having one row to another.

Also it only happens when I have more columns and their is a horizontal scroll and when i scroll to the right and then reduce the datasource to just have 1 data row, the grid is fine everything is aligned correctly.
But now when I switch tabs to go to other tab and come back with just one row in datasource the scrollbar comes to the far very left, but the columns are still of the right => So here is the issue, now when i add all other rows to data source, they get aligned correctly, but the columns are still incorrect and as per the first records that was there since beginning and leads to miss alignment.

This will only happen if i scroll to the right of the table and then reduce datasource to one row and then move away the scrollbar moves to the left and screws up the columns arrangement.

But weirdly once the move the scrollbar when i see the issue all columns are arranged correctly, seems like a problem with virtualization of columns, but i am not sure.

I hope this gave you a good understanding of the problem, if not i can show you over a call, as making a working example to replicate would be difficult and time consuming.

**Comment by ChronosSF** [comment]
Thanks, this gives me a better idea as to what the I should put into a test scenario when trying to reproduce it.

**Comment by amitmoondra** [comment]
Great thank you very much, I hope you can give a solutions soon, affects our production environment and need to correct it.

**Comment by ChronosSF** [comment]
Without having a sample yet, I can't be sure if it will help but it won't hurt trying the [reflow](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#reflow) method on tab change.

**Comment by amitmoondra** [comment]
Nope this doesnot fix it, also this happens when there is a group by  column. Let me know when you find a solution.

**Comment by ChronosSF** [comment]
You are likely hitting the first entry of the following limitations list - https://www.infragistics.com/products/ignite-ui-angular/angular/components/for_of.html#known-limitations

Please, try adding ngIf in the content of the tab containing the grid that only renders if when the tab is active. In this way the grid set will properly reset between tab navigation.

**Comment by amitmoondra** [comment]
Sure i will check it and update here. Thanks for letting me know the limitation?
Question:
Are you guys thinking of working on fixing these limitation in the future?

**Comment by ChronosSF** [comment]
In some instances Angular may provide a hook that the dev could use to call a method designed to fix the state that we expect would break during detach/attach (such as with RouteReuseStrategy routing)

In the case of a tab, it comes down to again, a hook that ensures the attached state of the control so that, such a method could be called.

So while we can't really ensure every control using projected contains would provide such a hook, we could expose such a method.

@rkaraivanov , @MayaKirova , @radomirchev , what do you think?

**Comment by amitmoondra** [comment]
@ChronosSF i saw a weird behavior today in grid, when there is horizontal scroll in the grid and i move a column in group by section to do a group by operation
then horizontal scroll to the very last column => change browser tab to a different tab then the grid one , come back to grid tab and then you will see horizontal scroll is back at the beginning, which definitely looks like an issue, where the grid remains in focus or something

Please look at this, this doesnot happen when no goruping is done , but only when grouping is done.

Hope you will update me on this ASAP.

**Comment by amitmoondra** [comment]
Also is vertical scroll in grid also resets back to top when you select any cell after scrolling, till the time selection of cell is not done the scroll remains at the same position where ever it was scrolled, but as soon as i select a cell after vertically scrolling and then change to another browser tab and then come back to this tab, the scroll is back to top.
This is incorrect behavior for me and seems buggy.

This is happening in infragistics examples as well on your website.

**Comment by ChronosSF** [comment]
We decided to implement a mutation observer which will solve the issue with projected containers (your original question) - You can find and track the issue progress here: https://github.com/IgniteUI/igniteui-angular/issues/8485

The last two comments are bugs I logged as https://github.com/IgniteUI/igniteui-angular/issues/8487 and https://github.com/IgniteUI/igniteui-angular/issues/8488

**Comment by ChronosSF** [comment]
@amitmoondra , the fix for the scroll issue is now available in the latest releases for 10.1, 10.2 and 11.0 .

**Comment by amitmoondra** [comment]
That is great, i will update to the latest 10.1.X version and update here.

**Comment by amitmoondra** [comment]
this is still an issue, I will provide an image soon and a scenario to recreate it as well.
