### ISSUE TITLE
The 'Done' button for row editing in a grid is skipped when navigating with 'Tab' key in Safari

### ISSUE THREAD

**Issue by SisIvanova** [IgniteUI/igniteui-angular#8306]
## Description  
When editing an existing row in a grid and navigating through the grid using the 'Tab' key, the 'Done' button is being skipped. The same happens when adding a new row.

 * igniteui-angular version: 10.2.x
 * browser: safari

## Steps to reproduce  
1. Open http://localhost:4200/gridRowEdit or http://localhost:4200/gridAddRow in Safari.
2. Start editing a row.
3. When you're done with the changes, press the 'Tab' key to go to the 'Cancel' button and once again to navigate to the 'Done' button.

## Result  
The 'Done' button is being skipped. 

## Expected result  
There should be an option to focus the 'Done' button using the keyboard navigation.

## Attachments  
![Screen Recording](https://user-images.githubusercontent.com/59446295/95327032-24385200-08ac-11eb-8a9c-d3f5a37471e4.gif)

**Comment by Aleksandyr** [comment]
@SisIvanova It seems that this is browser-specific and it depends on your local system settings.
Here is an [article](https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html) describing how you can enable tabulation for all focusable items.
It seems that on macOS by default tabulation is only enabled for text fields and lists.
