### ISSUE TITLE
Action strip displaying for an add row or row in edit mode.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#8307]
## Description  
The action strip is displaying for an add row or row while being edited, which covers the last cell and prevents from viewing its content while editing.

 * igniteui-angular version: 10.2.x
 * browser: any

## Steps to reproduce  

1. Open the "/treeGridAddRow" 
2. Enter edit mode for a row or click on the "Add Row" button
3. Click on the last visible cell

## Result  
The add row is still visible and visibility in that cell is compromised by the action strip still being visible.

## Expected result  
The action strip should now show for row in edit mode/add row.

## Attachments  
![ActionStrip](https://user-images.githubusercontent.com/3768136/95332842-a298f200-08b4-11eb-9e5c-46a4f828c788.jpg)

**Comment by 3phase** [comment]
Currently, the issue results in an error when trying to add a new row on a newly added row prior data fill. The issue happens with paging enabled. Refer to the applied gif for further details.

![bug-action-strip-2](https://user-images.githubusercontent.com/8365193/95469896-cfb6d480-0988-11eb-949d-a9df653c6fe7.gif)
