### ISSUE TITLE
igx-dialog - isOpen is not bindable

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#8320]
## Description  

The property `isOpen` in `IgxDialog` is not bindable. It's declared as an `@Input()` but it only has a getter, which leads to errors.

```ts
export class IgxDialogComponent implements IToggleView, OnInit, OnDestroy, AfterContentInit {
    ...
    @Input()
    get isOpen() {
        return !this.toggleRef.collapsed;
    }
    ....
```

 * igniteui-angular version: "10.1.0"
 * browser: any

## Steps to reproduce

```html
<igx-dialog title="My Dialog"
    [isOpen]="this.myDialogShouldBeOpen"
>
    Content
</igx-dialog>
```

## Result  

In runtime the console prints this error:
> TypeError: Cannot set property isOpen of [object Object] which has only a getter

## Expected result  
The binding works and the dialog is open if and only if the binding is `true`.

## Why?

Right now Dialog can only be opened using imperative API, if this property is bindable I could use it in a fully declarative way. Furthermore, I could remove the dialog entirely when it's not needed (ngIf):

```html
<igx-dialog
    *ngIf="this.myDialogShouldBeOpen"
    title="My Dialog"
    [isOpen]="true"
>
    Content
</igx-dialog>
```

**Comment by dobromirts** [comment]
@pmoleri Do you want to use isOpen as bindable property for any specific case , or you can use the open method instead?

**Comment by pmoleri** [comment]
@dobromirts the use case is to make my code declarative, I find it better that way, and I don't have dialog elements around for dialogs that don't need to be present.

```
<button (click)="this.myDialogShouldBeOpen = true">Open dialog</button>
<igx-dialog
    title="My Dialog"
    [isOpen]="this.myDialogShouldBeOpen"
    (close)="this.myDialogShouldBeOpen = false"
>
    Content
</igx-dialog>
```
or with ngIf
```
<button (click)="this.myDialogShouldBeOpen = true">Open dialog</button>
<igx-dialog
    *ngIf="this.myDialogShouldBeOpen"
    title="My Dialog"
    [isOpen]="true"
    (close)="this.myDialogShouldBeOpen = false"
>
    Content
</igx-dialog>
```

here I'm just using local state, but state could be global stored in a root service.

If declarative state is not something you want to support, then I suppose you can just remove the `@Input` decorator.
