### ISSUE TITLE
How to generate color palettes at runtime using CSS variables

### ISSUE THREAD

**Issue by obedurena** [IgniteUI/igniteui-angular#8342]
## How to use CSS Variables only when applying a component theme?  

We need to be able to switch the colors of our app at runtime. To achieve this with Angular Material we are generating color palettes in our app.component.ts and storing them as CSS variables. We then store them in SASS variables and pass that to Angular's palettes/themes functions. This works just fine because we are able to pass fully generated color palettes to Angular.

The problem is: when we try to generate palettes for Infragistic's components, it tries to generate colors based on those CSS Variables, what obviously fails. To mitigate that we then, instead of calling igx-palette() are creating an object which has the same properties as the one returned by igx-palette.

igx-palette only seems to generate palettes for primary, secondary and grays. When the theme for a component is generated then text-contrast() is called to generate a contrast color which then fails, because the palettes do not contain actual color values, but CSS Variables. We get many warnings similar to: 

`WARNING: Expected color for $background/$foreground but got var(--theme-secondary-50)/white. The contrast color can't be calculated automatically.
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 189:9     text-contrast()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 207:17    igx-contrast-color()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 459:26    resolve-value()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 515:48    apply-palette()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\components\grid\_grid-theme.scss 231:13  igx-grid-theme()
    src\assets\styles\theme\my-grid-theme.scss 36:22                                                @import
    src\assets\styles\theme\my-grid-theme-class.scss 1:9                                            @import
    src\app\components\paged-grid\paged-grid.component.scss 2:9                                          root stylesheet`

How can we generate color palettes at runtime for the Infragistics components?

 * igniteui-angular version: 10.1.4

**Comment by simeonoff** [comment]
@obedurena Since our library supports individual component themes where each component can use a different palette, it's not gonna be as straight-forward as it is in Angular Material. **It will also require a slight modification to our theming engine to allow for such functionality.**

The main obstacle to having this functionality by default is that some of the colors generated for some of the components are not pure palette colors, instead, they are calculated at build time based on the component schema. They may start from a palette color, but then the color is scaled in one way or another using Sass color functions, which obviously won't work with CSS variable references.

That being said, here's the solution I can propose, which will require modified schema/theme files on your end.

Let's take the avatar for example.

First, make sure we include a palette to some scope, in this case the root scope is used:

```scss
@include igx-palette-vars($light-material-palette, $contrast: true);
```

### Approach 1 w/ custom theme schema.

We need to create a custom schema that uses CSS variables, instead of the igx-color function (default) for retrieving colors:

```scss
@include igx-core();
@include igx-theme($palette: $light-material-palette);

$custom-avatar-schema: extend($_light-avatar, (
   icon-background: var(--igx-grays-400),
   icon-color: var(--igx-grays-800),
   initials-background: var(--igx-grays-400),
   initials-color: var(--igx-grays-800)
));

@include igx-avatar(
    igx-avatar-theme(
        $schema: $custom-avatar-schema,
    )
);
```
Now every avatar will use the global CSS palette vars, which allows you to modify them at runtime using JavaScript. You will not see any warnings in your console if you omit a color, like `icon-color` for instance, as it will fallback to a value declared in the `$_light-avatar` schema, which resolves to `var(--igx-avatar-icon-color)`;

### Approach 2, declaring global component themes.

Similar to the previous approach, you can pass the values to the theme function, for instance:

```scss
@include igx-avatar(
    igx-avatar-theme(
        $icon-background: var(--igx-primary-500),
        ...
    )
);
```

This will throw warnings if you do not pass the `$icon-color` property as it can't use the CSS variable reference at build time.

Regardless of the approach you choose, you will be able to use any custom CSS property as the value, but it will require work on your end to create the custom themes/schemas and that can be a lot of work if you want to be able to style all components at runtime.

Let me know if this approach will work for you so that we can implement the required change to support passing CSS variables as values for schemas/themes.

**Comment by obedurena** [comment]
Hello @simeonoff 

Many thanks for your reply and guidance. The Approach 2 which you described is what we are using like:

Palettes for angular material: 
```SCSS
$my-primary-palette: (
  50 : var(--theme-primary-50),
  100 : var(--theme-primary-100),
  200 : var(--theme-primary-200),
  300 : var(--theme-primary-300),
  400 : var(--theme-primary-400),
  500 : var(--theme-primary-500),
  600 : var(--theme-primary-600),
  700 : var(--theme-primary-700),
  800 : var(--theme-primary-800),
  900 : var(--theme-primary-900),
  A100 : var(--theme-primary-A100),
  A200 : var(--theme-primary-A200),
  A400 : var(--theme-primary-A400),
  A700 : var(--theme-primary-A700),
  contrast: (
    50: var(--theme-primary-contrast-50),
    100: var(--theme-primary-contrast-100),
    200: var(--theme-primary-contrast-200),
    300: var(--theme-primary-contrast-300),
    400: var(--theme-primary-contrast-400),
    500: var(--theme-primary-contrast-500),
    600: var(--theme-primary-contrast-600),
    700: var(--theme-primary-contrast-700),
    800: var(--theme-primary-contrast-800),
    900: var(--theme-primary-contrast-900),
    A100: var(--theme-primary-contrast-A100),
    A200: var(--theme-primary-contrast-A200),
    A400: var(--theme-primary-contrast-A400),
    A700: var(--theme-primary-contrast-A700),
  )
);

$my-secondary-palette: (
  50 : var(--theme-secondary-50),
  100 : var(--theme-secondary-100),
  200 : var(--theme-secondary-200),
  300 : var(--theme-secondary-300),
  400 : var(--theme-secondary-400),
  500 : var(--theme-secondary-500),
  600 : var(--theme-secondary-600),
  700 : var(--theme-secondary-700),
  800 : var(--theme-secondary-800),
  900 : var(--theme-secondary-900),
  A100 : var(--theme-secondary-A100),
  A200 : var(--theme-secondary-A200),
  A400 : var(--theme-secondary-A400),
  A700 : var(--theme-secondary-A700),
  contrast: (
    50: var(--theme-secondary-contrast-50),
    100: var(--theme-secondary-contrast-100),
    200: var(--theme-secondary-contrast-200),
    300: var(--theme-secondary-contrast-300),
    400: var(--theme-secondary-contrast-400),
    500: var(--theme-secondary-contrast-500),
    600: var(--theme-secondary-contrast-600),
    700: var(--theme-secondary-contrast-700),
    800: var(--theme-secondary-contrast-800),
    900: var(--theme-secondary-contrast-900),
    A100: var(--theme-secondary-contrast-A100),
    A200: var(--theme-secondary-contrast-A200),
    A400: var(--theme-secondary-contrast-A400),
    A700: var(--theme-secondary-contrast-A700),
  )
);

$my-gray-palette:(
    50 : var(--theme-gray-50),
    100 : var(--theme-gray-100),
    200 : var(--theme-gray-200),
    300 : var(--theme-gray-300),
    400 : var(--theme-gray-400),
    500 : var(--theme-gray-500),
    600 : var(--theme-gray-600),
    700 : var(--theme-gray-700),
    800 : var(--theme-gray-800),
    900 : var(--theme-gray-900)
);

$my-warning-palette: (
  50 : var(--theme-warning-50),
  100 : var(--theme-warning-100),
  200 : var(--theme-warning-200),
  300 : var(--theme-warning-300),
  400 : var(--theme-warning-400),
  500 : var(--theme-warning-500),
  600 : var(--theme-warning-600),
  700 : var(--theme-warning-700),
  800 : var(--theme-warning-800),
  900 : var(--theme-warning-900),
  A100 : var(--theme-warning-A100),
  A200 : var(--theme-warning-A200),
  A400 : var(--theme-warning-A400),
  A700 : var(--theme-warning-A700),
  contrast: (
    50: var(--theme-warning-contrast-50),
    100: var(--theme-warning-contrast-100),
    200: var(--theme-warning-contrast-200),
    300: var(--theme-warning-contrast-300),
    400: var(--theme-warning-contrast-400),
    500: var(--theme-warning-contrast-500),
    600: var(--theme-warning-contrast-600),
    700: var(--theme-warning-contrast-700),
    800: var(--theme-warning-contrast-800),
    900: var(--theme-warning-contrast-900),
    A100: var(--theme-warning-contrast-A100),
    A200: var(--theme-warning-contrast-A200),
    A400: var(--theme-warning-contrast-A400),
    A700: var(--theme-warning-contrast-A700),
  )
);

$brand-primary: var(--theme-primary-500);
$black:                     #000000;

$gray-darker: map-get($my-gray-palette, 900);
$gray-dark: map-get($my-gray-palette, 700);
$gray: map-get($my-gray-palette, 500);
$gray-light: map-get($my-gray-palette, 200);
$gray-lighter: map-get($my-gray-palette, 100);
$brand-info: map-get($my-gray-palette, 500);
$brand-success: #0FDBA6;
$brand-warning: #CC6C4B;
$brand-danger: map-get($my-warning-palette, 500);
$brand-inverse: map-get(map-get($my-primary-palette, contrast), 500);
```

Here we create an object similar to what igx-palette() would return:
```SCSS
$my-palette: (
        primary: $my-primary-palette,
        secondary: $my-secondary-palette,
        grays: $my-gray,
        surface: $gray-lighter,
        info: (500: $brand-info),
        success: (500: $brand-success),
        warn: (500: $brand-warning),
        error: (500: $brand-danger));
```

And here create the theme, in our case for the grid.

```SCSS
$my-grid-theme: igx-grid-theme(
    $palette: $my-palette,

    $header-text-color: $gray-darker,
    $content-text-color: $gray-darker,

    $row-odd-text-color: $gray-darker,
    $row-even-text-color: $gray-darker,
    $row-selected-background: $gray-lighter,
    $row-selected-hover-background: $gray-lighter,
    $row-selected-text-color: $gray-darker,
    $row-hover-background: $gray-lighter,
    $row-hover-text-color: $gray-darker,


    $header-border-color: $gray-light,
    $row-border-color: $gray-light,
    $cell-active-border-color: $gray-light,

    $cell-selected-background: $gray-lighter,
    $cell-selected-text-color: $gray-darker,

    $group-label-text: $gray-darker,
    $group-count-text-color: $gray-darker,
    $filtering-header-text-color: $gray-darker,

    $body-summaries-text-color: $gray-darker,
    $root-summaries-text-color: $gray-darker
);
```

It works, but we get a lot of warnings when the contrast colors are being calculated. 

If going with Approach 1, to style the grid we just would have to pass a variable for every one of the parameters which igx-grid-theme() accepts and then could get rid of the warnings?

**Comment by sddania** [comment]
hello, could you please give me an example how can I use CSS custom properties in igx-palette function?
if I use
```
:root {
    --primary: #2F80ED;
}

@import "igniteui-angular/lib/core/styles/themes/index";
$app-palette: igx-palette(
    $primary:   var(--primary),
    $secondary: $j-selection,
    $info:      $j-accessory,
    $success:   $j-success,
    $warn:      $j-warning,
    $error:     $j-danger,
    $grays:     $j-black,
    $surface:   $j-white
);
```
i get this error
```
SassError: SassError: $color: var(--primary) is not a color.
   ╷
81 │         @return lighten(saturate($color, 10.4), 37.7);
   │                         ^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 81:25   gen-color()
  node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 307:17  generate-palette()
  node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 366:23  igx-palette()

```

**Comment by simeonoff** [comment]
> 
> 
> hello, could you please give me an example how can I use CSS custom properties in igx-palette function?
> if I use
> 
> ```
> :root {
>     --primary: #2F80ED;
> }
> 
> @import "igniteui-angular/lib/core/styles/themes/index";
> $app-palette: igx-palette(
>     $primary:   var(--primary),
>     $secondary: $j-selection,
>     $info:      $j-accessory,
>     $success:   $j-success,
>     $warn:      $j-warning,
>     $error:     $j-danger,
>     $grays:     $j-black,
>     $surface:   $j-white
> );
> ```
> 
> i get this error
> 
> ```
> SassError: SassError: $color: var(--primary) is not a color.
>    ╷
> 81 │         @return lighten(saturate($color, 10.4), 37.7);
>    │                         ^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>   node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 81:25   gen-color()
>   node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 307:17  generate-palette()
>   node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 366:23  igx-palette()
> ```

That's not possible. You can't pass custom CSS props to Sass functions as the value is not known at build time.
