### ISSUE TITLE
Grid emits wrong values in cell with IgxCombo template

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#8343]
## Description  
`cellEdit`, `cellEditDone` and `cellEditExit` emits same value for `newValue` and `oldValue` when cell editor is templated with `igxCombo`.

 * igniteui-angular version: 10.2
 * browser: all

## Steps to reproduce  

1. Set `igxCellEditor` template with `igxCombo` and bind the cell edit value to the combo like this `[(ngModel)]="cell.editValue"`
2. Run the application and update the value of a cell with combo.
3. Update again the value of the cell.

## Result  
On first update `cellEdit`, `cellEditDone` and `cellEditExit` emits correctly `newValue` and `oldValue`. On each next updata `newValue` and `oldValue` are emitted with same value.

## Expected result  
On each cell update `cellEdit`, `cellEditDone` and `cellEditExit` should emit correct `newValue` and `oldValue`.

**Comment by wnvko** [comment]
Similar issue [here](https://github.com/IgniteUI/igniteui-angular-samples/issues/2264)

**Comment by mmart1n** [comment]
> Similar issue [here](https://github.com/IgniteUI/igniteui-angular-samples/issues/2264)
I’m aware of this issue and I'm currently working on it as well.
