### ISSUE TITLE
Row editing overlay disappears version 8

### ISSUE THREAD

**Issue by 14520582** [IgniteUI/igniteui-angular#8344]
I get the same issue https://github.com/IgniteUI/igniteui-angular/issues/8023
Any solutions for version 8?
 * igniteui-angular version: 8.2.31
 * browser: Chrome

**Comment by Lipata** [comment]
Hello.

We are currently supporting 9.1.x and 10.1.x - you can read more about maintenance and support in [this](https://github.com/IgniteUI/igniteui-angular/wiki/Ignite-UI-for-Angular-versioning#maintenance-and-support) document.

You can update to one of those versions, using our [Update Guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update_guide.html#from-8xx-to-90x).
