### ISSUE TITLE
Grid - selectRows does not emit RowSelectionChanged

### ISSUE THREAD

**Issue by Swiftpaws** [IgniteUI/igniteui-angular#8352]
## Description  
The method selectRows does  not seem to emit RowSelectionChanged when executed

 * igniteui-angular version: 10.1.0
 * browser: Chrome dev 

## Steps to reproduce  

Grid - code behind call grid.selectRows 
https://stackblitz.com/edit/github-ub6tvd?file=src/app/grid/grid-sample-selection/grid-selection.component.ts

(Set a timer to select the first row every second - row selection changed should be sent at least once - click to actually emit the event)

## Result  
No row selection changed event is emitted, even though the selection changed on the grid

## Expected result  
Row selection changed event should be emitted regardless of the origin (code behind or user interaction)

**Comment by ddincheva** [comment]
Hello @Swiftpaws,
The behavior that you describe above is by design. When you as a developer perform an action through the public grid API, you know that the action is performed and you have all the necessary information to apply any additional custom logic based on that.

**Comment by ddincheva** [comment]
@Swiftpaws , thank you so much for the feedback. We will update our documentation ASAP.
