### ISSUE TITLE
[IgxCombo, IgxDropDown] - OnOpening and OnClosing events propagate TogglableViewEvents 

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#8353]
## Description  
`IgxComboComponent` and `IgxDropDownComponent` `onOpening` and `onClosing` propagate the events from the underlying `IgxToggleDirective`. The directive's `ToggleViewEventCancelableArgs` have an `id` property that might be confusing for users.

All components that make use of the `IgxToggleDirective` should be looked at, to make sure that their events are emitting the correct value.

`onOpened` and `onClosed` events should also be checked - sometimes, they are emitting `void` (`IgxCombo`, `IgxDropDown`), sometimes they are emitting the component instance (`IgxTimePicker`, `IgxDatePicker`, `IgxBanner`).

**Note:** While changing the `onOpened/Closed` events from `void` to `[componentInstance]` might be easier, we also have a `IBaseEventArgs` interface defined which exposes an `owner` property - it can be explored to convert all events to emit that type, but that would introduce a breaking change.

 * igniteui-angular version: 10.2.x
 * browser: N/A

## Expected result  
Emitters of all toggle-able components are consistent

**Comment by damyanpetev** [comment]
While at it, the `id` on the toggle itself is confusing (read the doc comment :)) and can probably be renamed to `overlayId` as well
