### ISSUE TITLE
Cell becomes empty when row editing is started if a property with get/set accessors is bound.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#8367]
## Description  
Cell becomes empty when row editing is started if a property with get/set accessors is bound.

 * igniteui-angular version: 10.1.9
 * browser: Google Chrome

## Steps to reproduce  

1.Run the sample.
2.Double-click col1 cell.

## Result  
col2, col3, and col4 cells get empty.

## Expected result  
Cell editors hold current cell values.

## Attachments  
[igxGrid.zip](https://github.com/IgniteUI/igniteui-angular/files/5375151/igxGrid.zip)

**Comment by rkaraivanov** [comment]
@mkamiishi 

The grid assumes its data is in the form of [POJO](https://masteringjs.io/tutorials/fundamentals/pojo) entries. If that is not mentioned in our documentation then it should be logged as a documentation bug.
