### ISSUE TITLE
How to use more than one toggles in a single page

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#8387]
## Question  
I have a requirement to use 2 toggles in a single page one with modal and one without modal , so i need to use 2 different overlay settings and i need to close or open the toggles using igxToggle.close() or open() method through the code. I did not find any examples in documentation for more than 1 toggle. Kindly share an example how to get that components.
Thanks in advance

 * igniteui-angular version: 8.2
 * browser: chrome

**Comment by wnvko** [comment]
@Raju-N you can add as much toggles in your page as you need. You can also close or open them, via `open` and `close` methods whenever you want. [Here](https://stackblitz.com/edit/github-q3pyxx?file=src%2Fapp%2Ftoggle-sample-1%2Ftoggle-sample-1.component.html) is a Stackblitz demo showing one page with two toggles - one modal and other one non-modal.

**Comment by Raju-N** [comment]
@wnvko Thanks for the sample demo.
