### ISSUE TITLE
"Row added" snackbar is not visible if the grid has small height.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#8398]
## Description  
When grid has no height and no data and a single row is added the "Row added" snackbar hide behind the grid header.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the gridAddRow dev sample.
2. Remove the grid height.
3. Add row via the button.

![image](https://user-images.githubusercontent.com/10397980/96279270-1d61bb80-0fdf-11eb-8e72-20195b155625.png)

## Result  
Snackbar hides behind header and is only partially visible.

## Expected result  
Snackbar should be visible.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ChronosSF** [comment]
@radomirchev , this is actually fixed already.
