### ISSUE TITLE
Statically Sized Pinned Columns cause remaining columns to size erroneously

### ISSUE THREAD

**Issue by rdherric** [IgniteUI/igniteui-angular#8401]
## Description  
In using the IgxGridComponent, we have discovered an issue with pinned columns that are statically sized as opposed to being managed by the Grid.  When a pinned column is statically sized, the unpinned columns still size to 100% width of the Header, not to the space remaining in the Header after pinning columns.  I have enclosed a ZIP file with sample code as well two images that explain the issue.  I have also opened a support case (CAS-209676-H5M2K4) if that is a better method to communicate.

In the image named `PinnedColumns.png,` you can see Chrome showing the pinned column that has been set to a maximum width of `2rem` in an IGridState.  The configuration may be found in the `PinnedColumnsComponent.`  In the image named `UnpinnedColumns.png,` Chrome is showing that the remainder of the Header is still sized to 100%, which makes the sort icon of the last column get hidden, as well as cause several other issues in our application.

The support representative mentioned that the issue was reproducible and not limited to pinned columns.  I have since discovered a related issue with a statically sized column in a multirow layout Grid.

 * igniteui-angular version: 10.2.0-alpha.4
 * browser: Chrome

## Steps to reproduce  

1. Create an IgxGridComponent
2. Statically size one column - say the first one

## Result  
The remaining columns are sized to 100% of the container, which is the complete row across the top, not the row minus the size of the statically sized columns.

## Expected result  
Automatically-sized columns only take up the space available after statically-sized columns.

## Attachments  
<img width="1920" alt="PinnedColumn" src="https://user-images.githubusercontent.com/8574403/96307189-6b19fc00-0fbe-11eb-9002-ba70c35a78f0.png">
<img width="1920" alt="UnpinnedColumns" src="https://user-images.githubusercontent.com/8574403/96307192-6d7c5600-0fbe-11eb-9dfc-c3364adc71e2.png">
[pinned-columns.zip](https://github.com/IgniteUI/igniteui-angular/files/5394235/pinned-columns.zip)

**Comment by ChronosSF** [comment]
@rdherric , igxGrid only supports sizing of columns in pixels and percentages. If you set the statically sized column width in pixels it works correctly. You may learn more about how sizing works under the hood in this topic - https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/sizing.html#column-sizing

**Comment by rdherric** [comment]
@ChronosSF - I was able to get back to this yesterday.  Using a `px` width does appear to have addressed the issue.  Thank you for that recommendation.  I had not seen the link you sent, but the information is very useful.  

@radomirchev - why was this added to a Sprint if it is not a defect?

**Comment by zdrawku** [comment]
@rdherric adding it to sprint boards is helping us to better plan/distribute the pending work items. For example, if you weren't satisfied with the suggestion and still thought we should do something in addition, like updating the documentation or adding a richer sample, or if you actually found a bug while applying the sizes with pixels, we would have to distribute the work item to a team member to handle your inquiry when possible.

**Comment by radomirchev** [comment]
@rdherric , it was added to a Sprint as a "bug" and its now considered "done" as it is not a defect of the product. There is no way to know it is not a bug without someone to spend time investigating it :)

**Comment by rdherric** [comment]
Oh...silly me.  That should have been obvious.  Thank you both, @radomirchev and @zdrawku.  I will close the defect.
