### ISSUE TITLE
Action strip does not show in IE.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular#8406]
## Description  
Action strip thrown error on initialization since .includes function is not available in IE.
Other components that use .includes in the context of an Array also throw errors in IE.

## Steps to reproduce  

1. Open a sample with action strip in IE, for example: https://www.infragistics.com/angular-demos/data-display/chip-area-sample

## Result  
Error is thrown and action strip is broken:
ERROR TypeError: Object doesn't support property or method 'includes'

![image](https://user-images.githubusercontent.com/10397980/96445082-fcd07600-1217-11eb-968c-b69265f577e5.png)

## Expected result  
No error is thrown and chip shows.

**Comment by dkamburov** [comment]
related to #8409
