### ISSUE TITLE
[IE11] Should we remove the usage of Array.includes or should we depend on 'core-js/es7/array' polyfill?

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#8409]
## Question  
In order to support IE 11 we need either to remove all usages of Array.includes() in the library or depend on 'core-js/es7/array'.
At this point it is used in:

- action-strip.component.ts
- chip-area.component.ts
- grid-header-group.component.ts
- selection.service.ts

![image](https://user-images.githubusercontent.com/1182001/96456838-baaf3080-1227-11eb-95d5-29000256018b.png)

 * igniteui-angular version: 
 * browser: IE 11

At this point I added [fix for samples](https://github.com/IgniteUI/igniteui-angular-samples/pull/2309), but in future we may need to decide to remove `.includes()`

**Comment by dkamburov** [comment]
In my opinion we should remove the Array.includes(). It's a small change and it won't require including a polyfill.
Here's the [change](https://github.com/IgniteUI/igniteui-angular/pull/8428) for the action-strip.

**Comment by ChronosSF** [comment]
@rkaraivanov , @damyanpetev , do you think we should remove all the include code or depend on the polyfill for IE11 ?

**Comment by ChronosSF** [comment]
Discussed with @rkaraivanov and @damyanpetev today. Decided we'll be using array includes and add some documentation about the additional polyfils the product needs for IE11
