### ISSUE TITLE
Virtualizing a lot of items in Edge/IE causes navigation issues

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#841]
### Description  
When the scroll container exceeds a certain threshold IE and Edge produce navigation/scrolling errors with igxFor.

### Steps to reproduce  

1. Open the Grid Performance sample
2. Scroll down a bit then select a cell
3. Try to navigate up with the keyboard

### Result  
The grid navigates *down*

### Expected result  
The grid should navigate *up*

(there are other effects of the issue that can be observed easily)

**Comment by MayaKirova** [comment]
Additionally in some cases when the calculated height is too big (around 17,895,697 for FireFox, 10,737,418 for IE etc.) the scrollbar is not displayed in IE, Firefox and Edge. You can check the igFor sample in demos, where the item height is 300px and the item count is 100 000, where this limitation is also hit.

**Comment by mpavlinov** [comment]
@skrustev Please log this as a known issue for version 5.3.x. We will fix it in 5.4.x. I moved the PR #864 for version 5.4.x.
