### ISSUE TITLE
Add row keyboard navigation is not responding on MacOS.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#8414]
## Description  
Keyboard combinations <kbd>ALT</kbd> + <kbd>+</kbd> and <kbd>ALT</kbd> + <kbd>SHIFT</kbd> + <kbd>+</kbd> are not working on MacOS.

 * igniteui-angular version: 10.2.x
 * browser: Safari, Chrome

## Steps to reproduce  

1. Open any row adding sample on Safari
2. Press any of the keyboard combinations listed.

## Result  
The Row Adding UI does not start and nothing happens.

## Expected result  
The Row Adding UI should be displayed.

**Comment by mddragnev** [comment]
@skrustev Could you please try it with this fix https://github.com/IgniteUI/igniteui-angular/pull/8434 . Might be the same issue.
