### ISSUE TITLE
igx-badge displays blank circle after ng build deploying to DEV server

### ISSUE THREAD

**Issue by bwong9999** [IgniteUI/igniteui-angular#8419]
## Description  
Describe the issue.

 * igniteui-angular version: 10.1.9
 * browser: Chrome

## Steps to reproduce  

1. ng build with option "optimization": true
2. Deploy dist to the server.

## Result  
The igx-badge is showing a blank.  It appears that the background color is not showing for warning, success, etc.

## Expected result  
The igx-badge should not be a blank circle.  I should be able to see green form success and yellow for warning, etc.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
<img width="282" alt="Screen Shot 2020-10-19 at 1 18 44 PM" src="https://user-images.githubusercontent.com/72875816/96507193-b37b2900-120d-11eb-883a-5c2291fdde8c.png">

**Comment by bwong9999** [comment]
Here's a picture of when optimization is set to false.  This is the way it is suppose to work.
<img width="249" alt="Screen Shot 2020-10-19 at 1 38 44 PM" src="https://user-images.githubusercontent.com/72875816/96509395-ccd1a480-1210-11eb-9fd9-88bc1d7ba3dc.png">

**Comment by SisIvanova** [comment]
@bwong9999  We have tried reproducing this issue, however, nothing is breaking on our end. Could you please provide a sample so we can investigate the problem further?

**Comment by bwong9999** [comment]
This a test that I did.  I build it with 

ng build --configuration=dev
[test2.zip](https://github.com/IgniteUI/igniteui-angular/files/5461533/test2.zip)
