### ISSUE TITLE
igxFor not correctly working with formcontrols

### ISSUE THREAD

**Issue by Failender** [IgniteUI/igniteui-angular#8427]
## Description  
When using igxFor inside a reactive form when scrolling the wrong values will be displayed inside the inputs

 * igniteui-angular version: 10.2.0-alpha.1
 * browser: Chrome  86.0.4240.75

## Steps to reproduce  
https://stackblitz.com/edit/github-kqkekn?file=src%2Fapp%2FigxFor%2FigxFor.component.ts
1. Open the stackblitz
2. Fill the first field with an input (0 for example)
3. Scroll down, every entry 5 entries after that (5,10 in this case) will have the just filled value

## Result  
the wrong input fields have the wrong value

## Expected result  
The fields 5 & 10 should have no value

## Attachments  
![gif](https://user-images.githubusercontent.com/8982659/96577258-a294eb00-12d3-11eb-89d6-7fe4e7767ad1.gif)

**Comment by MayaKirova** [comment]
@Failender Virtualization re-uses view instances and only changes their data context when you scroll. The context is the data item for which the specified view is rendered.

This means that things that are bound in the data context will change, while things that are not bound and are instead stored in the component/view instance only would not change.

So if you want the input value to change accordingly to the context it should be bound to a value from that context and should be changed accordingly when you input a new value. For example:
https://stackblitz.com/edit/github-kqkekn-tsl6qv

**Comment by Failender** [comment]
Hey @MayaKirova I cant see your example, since you just send me my stackblitz link. Could you try to edit it again and send me the updated link?

Thank you very much!

**Comment by MayaKirova** [comment]
@Failender The link seems correct to me. It is a fork of your own sample with the following changes:
1.	In the view definition:
<input [formControlName]="field.identifier" **[value]='field.value' (input)="field.value = $event.target.value"**  />
2.	In the component definition:
this.fields.push({
      identifier: this.fields.length,
      **value: null**
    });
With this the input is bound to the data item’s value and also sets the new value when you input something else in it.

**Comment by Failender** [comment]
Hey thanks for your solution 👍 

I also find out the following working solution:

Instead of using [formControlName] we can use [formControl], which will be correctly updated
I updated the stackblitz to contain that solution
