### ISSUE TITLE
ESF does not respect custom column filters

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#8462]
ESF does not respect custom column filters

 * igniteui-angular version: 9.1.x

## Steps to reproduce  

1. Set an `IgxStringFilteringOperand` custom filter to a column of `number` data type.
```typescript
public unitFilters = IgxStringFilteringOperand.instance();,
```
```html
<igx-column field="UnitsInStock" [dataType]="'number'" [filters]="unitFilters">
</igx-column>
```
2. Open ESF dialog

Note that if quick filtering is used, instead of ESF, custom column filters are respected.

## Result  
Default numeric filters are rendered in the UI, instead of the custom ones

## Expected result  
Custom filters to be rendered in the UI

Note:
Only the list item that expands the filters is not changed:
![Untitled](https://user-images.githubusercontent.com/14248932/97999097-950f5300-1df3-11eb-91c6-c20a08c1ce28.png)

**Comment by StefanIvanov** [comment]
@hanastasov if I understand you correctly the ESF dialog correctly shows Number filter because it takes in account the column data context, which in this case is numeric data and therefore Number filter irrelevant whether in the list that is expanded from there we have default or custom operands

**Comment by hanastasov** [comment]
> @hanastasov if I understand you correctly the ESF dialog correctly shows Number filter because it takes in account the column data context, which in this case is numeric data and therefore Number filter irrelevant whether in the list that is expanded from there we have default or custom operands

Correct, there are cases where the list item text does not correspond to the filters in the dropdown, as the screenshot shws:
![Untitled](https://user-images.githubusercontent.com/14248932/97999097-950f5300-1df3-11eb-91c6-c20a08c1ce28.png)

**Comment by StefanIvanov** [comment]
I still think that for a Numeric column we should show Number filters and for a string one, Text filter

**Comment by hanastasov** [comment]
> I still think that for a Numeric column we should show Number filters and for a string one, Text filter

This is the default behavior. But since we allow the developer to assign custom filters, leaving the above mentioned situation as is seems to me like a bug. Imagine a situation where the values in the ESF list are strings, custom filters are string filters, and the user sees the `Number filter` prompting text/

**Comment by StefanIvanov** [comment]
So on a numeric column you want to define string filter operands, is that what you are saying because I don't see how that will create any meaningful outcome. If we are changing anything I say we let people input the value themselves just like they are able to input the operand values for the custom filters they have, but I am still reluctant to do so.

**Comment by hanastasov** [comment]
Imagine a numeric column, where the developer formats the cell display value to represent the meaning of a numeric value. For example cell value of 20 will display `Low` text, value of 110 will display `Critical` text.

The business case says let's filter by 'Low', and 'Critical', so the developer is assigning a custom string filters to that column. 

This seems a valid case to me.

**Comment by DiyanDimitrov** [comment]
@hanastasov, this is a valid case, but changing the label to '**Custom filters**' whenever the column's `filters` are modified does not give the end-user any meaningful information. I agree with @StefanIvanov, that it would be probably better to expose an input for the label.

**Comment by hanastasov** [comment]
I expected that a name of the custom filter would appear in the list item, not just "Custom Filter". Buf it this item of the ESF dialog is templatable, maybe it is just enough.

**Comment by hanastasov** [comment]
Still, let's ignore the filter label for now. Even when the "Contains" filtering condition is chosen in the dropdown, the corresponding input allows entering numbers only, as if this is a numeric filter.

**Comment by DiyanDimitrov** [comment]
We had a discussion about this issue and we have agreed that this is a feature request.

In order to provide custom label for the conditional filters we can make the `igx-excel-style-conditional-filter` content settable like this:
```html
<igx-excel-style-conditional-filter>My custom filters</igx-excel-style-conditional-filter>
```
Also we can provide a template for the filter value input per column like this:
```html
<igx-column>
    <ng-template igxFilterValueInput></ng-template>
</igx-column>
```
