### ISSUE TITLE
Angular Demos Grid Infinite Scroll

### ISSUE THREAD

**Issue by mattbodman** [IgniteUI/igniteui-angular#8478]
## Description  
When trying to load the Grid Infinite Scroll page, `ERROR TypeError: Cannot read property '0' of undefined` is thrown.  There are no other errors and the remote data source loads correctly.

 * igniteui-angular version: 10.2.1. (also happened with previous version as downloaded from IgniteUI website so I updated everything in attempt to fix, but no)
 * browser: Chrome 86.0.4240.111

## Steps to reproduce  

1. Download the demo
2. NPM install
3. NPM start
4. in browser, navigate to the page http://localhost:4200/samples/grid/grid-sample-5

## Result  
broken demo

## Expected result  
working demo

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

<img width="2274" alt="Screen Shot 2020-10-29 at 1 01 46 pm" src="https://user-images.githubusercontent.com/1994501/97520425-f1830480-19e6-11eb-8265-1ee22910b9a9.png">

**Comment by skrustev** [comment]
Hey @mattbodman I tried running our samples and the one specific you mentioned and I couldn't reproduce the issue you are having. Even with going back to an earlier state.

Are you still having the issue with the latest branch and if so could you specify also what node and npm versions are you running as well?

**Comment by mattbodman** [comment]
Hi, thanks for looking into this. However, since you've released a new version of the demo, and the page in question doesn't appear to exist anymore, this issue is probably irrelevant.  Kind regards
