### ISSUE TITLE
Grid with selected cell resets scroll position when the user leaves the browser tab and comes back to it

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#8487]
## Description  
If you scroll the grid down, select a cell, go to another tab and come back 

1. the grid auto-scrolls to top
2. upon hovering it the first cell gets selected

 * igniteui-angular version: 10.2.x (probably 9.1.x too)
 * browser: n/a

## Steps to reproduce  

1. Open https://www.infragistics.com/angular-demos/grid/grid-cell-selection
2. Scroll down
3. Select a cell
4. Go to another browser tab and then return 

## Result  
Scroll resets, weird selection behavior

## Expected result  
The grid scroll state should remain as the user left it

## Attachments  
n/a

**Comment by ChronosSF** [comment]
This is probably related to the added focus behavior with the grid trying to select the first cell when focused. Chrome would focus the grid when the user returns to the tab... Possibly start from there.

**Comment by ChronosSF** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/8285

**Comment by Aleksandyr** [comment]
After a short discussion, It has been determined that this is the default behaviour of the browser and it is not our job to handle it. It's gonna be hacky and painful.

P.S.
The active element always tries to find the first element of the focused area. Once the tab is changed the active node gets blurred and the time we come back the focused area finds it's first focusable child which triggers the scroll.

**Comment by ChronosSF** [comment]
Then we should change the behavior of the auto-focus cell. This is disruptive from UX standpoint. Users wouldn't expect to lose their scroll context when going between tabs.

@kdinev , @radomirchev , @StefanIvanov

**Comment by Aleksandyr** [comment]
That's another state we have to keep I suppose?

**Comment by ChronosSF** [comment]
Not sure what's best tbh. In igGrid the grid would focus the first cell only if its scroll top is 0. There could be other ways to handle this. I'll let @StefanIvanov , @kdinev , @damyanpetev , to chime in as well.

**Comment by StefanIvanov** [comment]
> Not sure what's best tbh. In igGrid the grid would focus the first cell only if its scroll top is 0. There could be other ways to handle this. I'll let @StefanIvanov , @kdinev , @damyanpetev , to chime in as well.

I agree with you, we should precise the focus strategy to avoid this from happening.

**Comment by Aleksandyr** [comment]
Shall we make a call and discuss this matter?
Including @rkaraivanov as well.

**Comment by rkaraivanov** [comment]
@ChronosSF 
The behavior with scrollTop 0 sounds like a reasonable scenario.

**Comment by ChronosSF** [comment]
The only question would probably be - do we have a state storing an "active cell" as #8504 suggests or as it is focused it is just lost when the cell is blurred for whatever reason. My suggestion doesn't solve the former.

**Comment by Aleksandyr** [comment]
@ChronosSF The state that stores the active cell resets when the grid or any focusable container gets blurred.

**Comment by ChronosSF** [comment]
Sorry I checked the samples again . From what I see the cell gets selected as well so that's the state that should be preserved. I think #8504 is basically the same issue I reported here. You should just not refocus the first cell for every focus on the grid.

So expanding on the previous suggestion you could try to not focus the first cell when you receive focus on the grid when there is a cell already selected. You could try to focus it instead, or just let the user interact with the grid to focus a different element.

**Comment by ddincheva** [comment]
Since there are several issues regarding the described problem they are addressed in issue #8677 for easier tracking.
