### ISSUE TITLE
Label is placed on top of the placeholder inside Input Group, Type Date

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#8495]
## Description  
When adding an input group and then changing its type to Date, the label is placed on top of the placeholder text.

 * igniteui-angular version: 10.2
 * browser: Chrome

## Steps to reproduce  

1. Add input group
2. Change type to Date
3. The label is placed on top of the placeholder text

## Result  
The label is placed on top of the placeholder text

## Expected result  
The label should be placed above the placeholder

## Attachments  
<img width="407" alt="Screen Shot 2020-11-03 at 10 06 48 AM" src="https://user-images.githubusercontent.com/41998471/98003445-6e531b80-1df7-11eb-8bb6-bb67e2d3f843.png">

**Comment by wnvko** [comment]
@DaniMarinov you should try to add `igxDateTimeEditor` directive to the input like this:
```
<input type="date" igxDateTimeEditor igxInput />
```

**Comment by damyanpetev** [comment]
The native HTML date editor doesn't actually have a placeholder set, it's implicit, so not detected by the label and the position is wrong and isn't currently supported in the input group. As mentioned we have specialized date editors and pickers.
Examples w/ Date Time Editor: https://www.infragistics.com/products/ignite-ui-angular/angular/components/date-time-editor work just fine with placeholder and label.
