### ISSUE TITLE
Active cell lost when focus out and in again

### ISSUE THREAD

**Issue by RolandTa** [IgniteUI/igniteui-angular#8504]
## Description  
When a cell is activated (ie click on it) and the user is performing a focus out (ie by minimizing the browser window or by focusing a different program) the active cell will be reset when reentering into the grid again.

 * igniteui-angular version: 10.1.11 or 10.2.1
 * browser: Google Chrome 86.0.4240.111

## Steps to reproduce  

1. Open a Grid https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-row-editing
2. Select a cell -> ProductName Konbu for example
3. Minimize the current browser window, or focus a different program on your OS
4. Return to the browser again

## Result  
The Grid is focusing the cell at rowIndex 0/0 instead of maintaining the currrent active cell selection ProductName Konbu

## Expected result  
The grid should maintain the last active selection even on a focus lost and reenter again roundtrip. In our case the user is pulling information out of a third party program (excel) an tries to enter it into the grid - every time he leaves the grid an comes back he is loosing the current active cell state.

**Comment by ChronosSF** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/8487

**Comment by ddincheva** [comment]
Since there are several issues regarding the described problem they are addressed in issue #8677 for easier tracking.
