### ISSUE TITLE
Property to enable/disable virtualization in grids

### ISSUE THREAD

**Issue by Poseclop** [IgniteUI/igniteui-angular#8521]
## Is your feature request related to a problem? Please describe.
Currently, data virtualization is enabled in all grids by setting their height / width. As far as I can tell, there is no way to have a grid with set dimensions without data virtualization enabled.

## Describe the solution you'd like
A property for the different grids that would allow to enable/disable grid virtualization, thus allowing to have a grid with a set height, but no data virtualization.

## Describe alternatives you've considered
I'm trying to ignore grid virtualization as I'm experiencing performance issues (lag when scrolling) with a hierarchical grid that potentially holds a lot of data. I tried to find if something in my template was causing the lag but everything seems ok (see attached template, maybe you can find something I didn't see). 
[grid-template.txt](https://github.com/IgniteUI/igniteui-angular/files/5487869/grid-template.txt)

**Comment by ChronosSF** [comment]
We don't really plan to provide any non-virtualized grids. The rich object model the grid provides with every cell, row, header, column, etc being addressable components makes rendering big grids without virtualization impossible. They would just crash above say 100 rows/10 columns. 

If you have a big hierarchical grid (i see width/height 100%) with compact display density you will still render a lot of elements that have to be updated during scrolls which may slow the scroll down somewhat. Limiting the templates used inside cells as well as just making the grid smaller will help.

What browser are you testing this on? Version of the product? Also make sure to test performance in production mode.

**Comment by Poseclop** [comment]
Thanks for the quick reply.
We're currently using **igniteui-angular v10.1.0** and tests were made in production using both **Chrome 86.0.4240.111 and Edge  86.0.622.61**.
Our grids' height oscillate between 650 and 800px and usually display about a dozen items simultaneously + headers (for a hierarchical grid), see attached picture).
![image](https://user-images.githubusercontent.com/37383113/98214816-42df4680-1f47-11eb-9d86-2a4b99a4a200.png)

**Comment by rkaraivanov** [comment]
@Poseclop 
Can you share a [performance profile](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference) of scrolling in this grid view?

**Comment by Poseclop** [comment]
Again thanks a lot for the support. Here is the profile.
[Profile-20201105T134212.zip](https://github.com/IgniteUI/igniteui-angular/files/5494396/Profile-20201105T134212.zip)

**Comment by ChronosSF** [comment]
Sorry for the delayed response!

I created a sample with mockup data using your template. It had okey-ish performance even out of the box. Certainly a lot better than your perf profile would suggest (yours had scroll event handlers reaching 1 second which is just abysmal). However, I had to get rid of the dynamic assignments of widths and labels, as well as created very basic pipes for `translate` and `opaleDate`. 

Then I tried to get it even faster. As you are using dynamically sized grids for this app, this causes a lot of hits of our resize observer when views are getting swapped around during the virtualized scroll. My best result was when I set defined height in pixels for the child row-island and that makes a lot of sense performance-wise. You could also set the `rowHeight` input to a value that you know would make sense (a few pixels bigger than what you expect your largest row would be for example). 

I am attaching my sample for your reference. It implements the second suggestion, although the first one produced better results and you should try that if it matches your app requirements.

[test-perf.zip](https://github.com/IgniteUI/igniteui-angular/files/5525498/test-perf.zip)

Now, why I can't reproduce the really slow scrolls you are experience is difficult to tell. It could be the things I omitted. Check my sample and if you can add the stuff that I didn't know how to implement, maybe that will get it closer to what you are experiencing and we can work on it from there.

Not having all children expanded will help performance as well. The hierarchical grid is the worst case scenario for virtualization anyway, as it has to constantly swap templates from "grids" to "rows" and all children expanded is the worst case for that. There is little we can do about it.

Additionally, you could sort of disable virtualization by setting the height of the grid to null. I didn't suggest it initially as that's not exactly disabling virtualization but making the grid render all rows. You will then need to wrap it in a scrollable container that would make its header disappear when you scroll it down.
