### ISSUE TITLE
Igx-Grid with default filter sort and filter treechange trigger

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#8523]
I'm trying to use the Igx-grid with the default filter to only perform the request when I submit the selected complete filter and not to use a debounce time to obtain automatically the values.

How can I do this to only use the treeChange when I finish inserting it instead of using the debounce ?

 * igniteui-angular version:  10.1.9
 * browser: Chrome

**Comment by DiyanDimitrov** [comment]
@MiguelPetrotec, The default filter row UI triggers filtering on each keystroke. In order to achieve the functionality you are aiming for, you should either implement your own filtering UI or submit a feature request for a deferred mode of the default filter row UI.
