### ISSUE TITLE
igxInput not working in select header

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#8527]
## Description  
I would like to use an input element in the select header, but this does not seem to work. The input is not getting focus when clicked. Repro: https://stackblitz.com/edit/github-9arclw?file=src/app/select-header-footer/select-header-footer.component.html

 * igniteui-angular version: 10.0.8
 * browser: Chrome

**Comment by IvayloG** [comment]
@Eralmidia The reason the input in the header template not being focused is because the select component ensures its own input does not lose focus. This ensures it's correct behavior. For example, when it does lose focus the component is validated and I expect it will be of no use to validate each time another input is focused anyways.

**Comment by Eralmidia** [comment]
@IvayloG  So then there is no way to create a filter input for an igx-select?

**Comment by Eralmidia** [comment]
Btw a side note: the autocomplete docs page gives 404: https://www.infragistics.com/products/ignite-ui-angular/angular/components/autocomplete

**Comment by IvayloG** [comment]
@Eralmidia Thanks for the notice, it will be soon be fixed! For the time being, please use https://www.infragistics.com/products/ignite-ui-angular/angular/components/autocomplete.html

**Comment by IvayloG** [comment]
@Eralmidia
In short 
- it is possible to implement this in igx-drop-down. Here is a [sample ](https://stackblitz.com/edit/igx-dropdown-search?file=src%2Fapp%2Fdropdown-sample-2%2Fdropdown-sample-2.component.html) illustrating something similar to your requirements.

- Select component is intended for scenarios with a small number of items to pick from + has inbuild items filtering based on keyboard input. For example, you can type "Banana" in [this sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/select#custom-overlay-settings) and the corresponding item will be set as active. Note: The input is readonly at all times.

In general, it is best to be aware of the general purpose of the available components (Drop Down, Select, Autocomplete and Combo). You will find a nice explanation by kdinev describing the purpose of each of these components and intended use [here](https://github.com/IgniteUI/igniteui-angular/issues/4338). 

Last but not least, if you need filtering input (presuming have more then several items in the list to filter), you may consider using the Combo, as it has inbuild search field and is optimized for a large number of items.

**Comment by Eralmidia** [comment]
@IvayloG Thanks. I'll probably go for something like the sample you provided, except with an input field instead of a button. 

You are correct that what I essentially want is the combo. But I really dislike that for single selection, the combo i still showing the checkboxes. Having checkboxes indicated multiselection.
