### ISSUE TITLE
When the viewport is small and column widths are set in percentages, a misalignment between header and field appears

### ISSUE THREAD

**Issue by martinesoff** [IgniteUI/igniteui-angular#8541]
## Description  
When the columns' widths are in percentages and the viewport is small, a misalignment with their headers and fields is observed.

## Steps to reproduce  

1. Open the [StackBlitz sample](https://stackblitz.com/edit/igxtreegrid-collapseall-styling?file=src%2Fapp%2Ftree-grid-editing-sample%2Ftree-grid-editing-sample.component.html).
2. Resize the viewport in order its width is under 900px.

## Result  
There is some misalignment between the headers and fields of the columns.

## Expected result  
There is no misalignment.

## Attachments  
![column alignment after adding right border](https://user-images.githubusercontent.com/5458174/98535667-29176980-228f-11eb-88b9-2b9c0f16b8fb.jpg)

**Comment by desig9stein** [comment]
I don't think that this is a styling issue.
For some reason, the igx-grid-header-group, which has dynamically calculated min-width becomes smaller than its child igx-grid-header. There is a 1px difference, the parent is 48px and the child is 49.
@dkamburov, @ChronosSF, can you guys take a look?

**Comment by radomirchev** [comment]
@ChronosSF , @desig9stein - could you update the status of the issue?

**Comment by dkamburov** [comment]
@martinesoff The reason for this is the usage of border-right:
```
  .igx-grid__td {
    border-right: 1px solid rgba(0, 0, 0, 0.08);
  }
```
This is breaking the grid calculations for the width of the cells. Here's the [sample](https://stackblitz.com/edit/igxtreegrid-collapseall-styling-wbjsbm?file=src%2Fapp%2Ftree-grid-editing-sample%2Ftree-grid-editing-sample.component.scss) without the border and the cells are adjusted properly.
