### ISSUE TITLE
Hierarchical Grid layout is broken when you have a pinned column

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#8569]
## Description  
 * igniteui-angular version: 11.0.x
 * browser: all

## Steps to reproduce  

1. Open dev demos hierarchicalGrid sample
2. Observe the grid layout

Also, the bug is reproducible in the staging environment, you can observe the samples in Hierarchical Grid/Column Pinning topic

## Result  
What is the actual result after following the steps to reproduce?
![image](https://user-images.githubusercontent.com/34240583/98796813-7bce5e00-2414-11eb-8894-60daacd60a46.png)

If the column pinning position is set to end: The pinned column is not in the view at all.
![image](https://user-images.githubusercontent.com/34240583/98798143-314de100-2416-11eb-85d6-d22183f97693.png)

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![Screenshot_5](https://user-images.githubusercontent.com/34240583/98796832-825cd580-2414-11eb-81b2-6d0ee05b0be1.png)

**Comment by StefanIvanov** [comment]
@desig9stein the order of functionality-related columns is such that drag indicator is always left most and expand indicators are always right most
