### ISSUE TITLE
Overlay doesn't calculate its position fit based on the outlet but based on the document

### ISSUE THREAD

**Issue by VladB93** [IgniteUI/igniteui-angular#8595]
### Description  
Describe the issue.

 * igniteui-angular version: 10.2.x
 * browser:  any

### Steps to reproduce  

1. The viewport fit calculation is based on the document instead of the provided outlet thus resulting in strange behavior sometimes:

![image](https://user-images.githubusercontent.com/47364572/99269747-196bc800-282f-11eb-87d2-b076a72f7181.png)

can be useful in cases like this one:

![image](https://user-images.githubusercontent.com/47364572/99270255-3b654a80-282f-11eb-92db-085423a4da4e.png)

Provide a way to choose whether to make the calculations based on the outlet or the document.

**Comment by wnvko** [comment]
This is a feature request. We should add option to overlay determining whether or not overlay content should be shown always in the outlet, e.g. `showInOutlet`.
Note this strongly contradicts with all connected position strategies. This is why we should very carefully decide what should happen in any `target` - `outlet` configuration. The most easy one is `outlet` with `target` inside it. The most strange one coming to my mind will be `target` next to the `outlet`.
