### ISSUE TITLE
ng-disabled directive does not affect datepicker-dropdown

### ISSUE THREAD

**Issue by frankdenouter** [IgniteUI/igniteui-angular#86]
it affects only the input-box

refer to this example:
http://codepen.io/uc/pen/QKEyBR?editors=1010

seems the same for ig-combo.

**Comment by dkamburov** [comment]
You have to use the disabled API for igDatePicker to disable the editor
<ig-date-picker class="form-control" id="datePicker1" ng-model="editors.date" ng-disabled="true" **disabled="true"**></ig-date-picker>

**Comment by frankdenouter** [comment]
Using 'disabled = "true"' indeed disabled the entire datetimepicker, but then it is not bound to the angular-scope. 
In this example, the disabled property is bound to a variable on the scope:
http://codepen.io/uc/pen/kkvqPw?editors=1010

therefore the ng-disabled attribute is needed

**Comment by dkamburov** [comment]
Ok, to make it bound to scope, you need to watch the variable and set the new values. I modified your sample - [http://codepen.io/anon/pen/GjybdJ?editors=1010](http://codepen.io/anon/pen/GjybdJ?editors=1010)

**Comment by frankdenouter** [comment]
Ok, but it would be nice if the ig-date-picker directive had this 'ng-disabled' logic itself. In your example you have to write a watch for each datepicker, giving the controller 'knowledge' of the datepicker-id used on the view. This 'knowledge' does not fit the separation of concerns pattern which can be achieved with angular. I can continue with the solution above. Thanks for the advice.
