### ISSUE TITLE
Grid: null Date type rendering as 12/31/1969 

### ISSUE THREAD

**Issue by ZCeli** [IgniteUI/igniteui-angular#8603]
## Description  
A Date type field with null value renders as 12/31/1969.

 * igniteui-angular version: 10.1.7
 * browser: chrome

## Steps to reproduce  

1. Open any of your sample with a date field
2. Change the sample data date field to new Date(null)

## Result  
What is the actual result after following the steps to reproduce?
You get 12/31/1969

## Expected result  
What is the expected result after following the steps to reproduce?
It should be empty.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

Note: no one would normally use new Date(null). I'm doing so here to mimic a Date type coming from server. I was able to fix it by parsing the date field coming from server in the service file. But I'm wondering if the grid is the one that should handle that kind of scenario.

**Comment by hanastasov** [comment]
Hi @ZCeli, thank you for reaching out to us.

The grid columns has the [`dataType`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcolumncomponent.html#datatype) property, which allows you to mark the column as a date column:

`
<igx-column [dataType] = "'date'"></igx-column>
`
This way the grid knows it should handle date values (let it be a date object, an ISO 8601 date string, or a number that represents a date). If  null value comes from the server, cell display will be empty.

So you do not need to parse the date by yourself using `new Date(null)`. 
`new Date(null)`. represents 1 January 1970 UTC, so it is expected to see this display in the grid or wherever you are passing such value.
