### ISSUE TITLE
How to refresh the igx-carousel - if carousel array changes, carousel should start from first slide instead of current slide

### ISSUE THREAD

**Issue by maheshkns** [IgniteUI/igniteui-angular#8605]
## Description  
Describe the issue.
If we are in second/third slide, if change the slider array, carousel should start first slide.
 * igniteui-angular version:  "6.2.9",
 * browser:  Chrome

## Steps to reproduce  

1. Step 1 add 1 button, on clicking, the carousel should change
2. Step 2 Move to second slide
3. Step 3 click on the button, the carousel should start from first slider

## Result  
What is the actual result after following the steps to reproduce?
On changing the carousel array, the carousel index is not changing 
## Expected result  
What is the expected result after following the steps to reproduce?
On changing the carousel array, the carousel should start from left to right means the carousel should refresh

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment]
@maheshkns There was a major refactoring of the Carousel component in version 9.0.0. You can try upgrading your project to the latest version as we no longer support version 6.2.x.
