### ISSUE TITLE
IgxDatePicker throws script error when alphabets are kept pressing in its input text box in IE11

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#8613]
## Description  
IgxDatePicker throws script error when alphabets are kept pressing in its input text box in IE11

 * igniteui-angular version: 10.2.4, 11.0.2
 * browser: IE11

## Steps to reproduce  

1. Start the attached reproducible sample.
2. Click twice the date picker's input box.
3. Keep pressing "a".

## Result  
After starting to keep pressing "a" for a while, "a" is displayed in the text box.
And a script error 'Unable to convert "Invalid Date" into a date' occurs.

## Expected result  
Alphabets are not be accepted.
No script error occurs. 

## Attachments  
[cas33664-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/5564014/cas33664-app1.zip)
![cas33664-app1-animation](https://user-images.githubusercontent.com/33947244/99614526-05a5a900-2a5d-11eb-8fa1-2a2f36180c1b.gif)

**Comment by jackofdiamond5** [comment]
The issue will be resolved in https://github.com/IgniteUI/igniteui-angular/issues/6483

**Comment by norikois** [comment]
@jackofdiamond5 , @Lipata ,
 Is there a workaround that we can apply to the latest version of the product?
