### ISSUE TITLE
Support changing theme dynamically on Input Group

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#8619]
## Problem
I need to change the theme in runtime using TaaS, but Inputs groups fail to update.

After changing my theme from Fluent to Material the labels still look as in fluent:
![image](https://user-images.githubusercontent.com/12942794/99685310-37207380-2a61-11eb-8047-d1e91a355390.png)

Related to this there's a problem. Even if I'm not switching themes, if the stylesheet hasn't loaded by the time the Input Group was rendered then it will default to material even after it finishes loading.
![image](https://user-images.githubusercontent.com/12942794/99686965-df830780-2a62-11eb-8c96-d9ec1d659317.png)

## Solution
I don't have a clear solution to this. Input Groups could observe some global theme property that I can update using a service.
I think this was @damyanpetev suggestion.

## Alternatives
I could destroy the view and force it to render from scratch so it infers the new theme.
This could be easily achieved with a fake *ngFor on an array with a single theme property.

**Comment by simeonoff** [comment]
We could have a mutation observer that forces re-render of the input group instance whenever the theme changes. I even discussed this limitation with the team before merging the changes done to the input group and how the theming works there. We, however decided that this is an edge case, and we shouldn't pay too much attention to it.
