### ISSUE TITLE
OverlaySettings' closeOnOutsideClick doesn't detect correctly when the outlet is in shadow dom

### ISSUE THREAD

**Issue by VladB93** [IgniteUI/igniteui-angular#8626]
## Description  
Describe the issue.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Create a dropdown with a toggle and outlet.
2. Set the component with shadowdom encapsulation
3. Cancel the onSelection of the dropdown.
4. Try to select an item from the dropdown -> it gets closed.

## Result  
Ev.target is equal to the wrapper of the shadow dom instead of the real target because of ev redirection. As according to this
https://javascript.info/shadow-dom-events#:~:text=Events%20that%20happen%20in%20shadow,caught%20outside%20of%20the%20component.&text=If%20you%20click%20on%20the,the%20element%20inside%20shadow%20DOM

## Expected result  
The target should be real ev.target - get the inner path if the outlet is in shadow dom.

## Attachments  
Sample:
https://stackblitz.com/edit/github-5x938c?file=src/app/dropdown-sample-1/dropdown-sample-1.component.html

**Comment by wnvko** [comment]
We may try to get the target from `event.composedPath()`. [Here](https://github.com/IgniteUI/igniteui-angular/blob/66770b07383f4e7e22dcaee305fe7a9627dc6017/projects/igniteui-angular/src/lib/services/overlay/overlay.ts#L813) we may get the target like this:
```
    const target = ev.composedPath()[0];
```
