### ISSUE TITLE
Can't update to v11. Did something change regarding auth?

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular#8637]
## Description  
I'm trying to update to version 11, but I keep getting 401 (Unauthorized) while trying to do so.

 * igniteui-angular version: 10.1.4
 * browser: Firefox

On my package.json I have `"@infragistics/igniteui-angular": "^10.1.4"` and I also have a .npmrc file with the token in the format:

```
@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/
//packages.infragistics.com/npm/js-licensed/:_auth=my_token
//packages.infragistics.com/npm/js-licensed/:username=my_username
//packages.infragistics.com/npm/js-licensed/:always-auth=true
```

If I remove the node_modules folder and run `npm i` it works and the package is installed. If I try to run `ng update @infragistics/igniteui-angular` I get the 401.

> Error fetching metadata for '@infragistics/igniteui-angular': 401 Unauthorized - GET https://packages.infragistics.com/npm/js-licensed/@infragistics%2figniteui-angular - Unauthorized

Did something change regarding updating to v11? I didn't find anything specific on https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide#from-102x-to-110x

**Comment by zdrawku** [comment]
Hey @eestein, apologies for the delay. If the problem still persists, my suggestion would be to follow the [official angular guide for v10 to v11 upgrade](https://update.angular.io/?v=10.0-11.0) with one addition, upgrade our igniteui-cli package as well (exact command below).

I've [created a repository that mimics](https://github.com/zdrawku/licensed-feed-problem) the whole process of upgrading from **@infragistics/igniteui-angular@10.1.4** to **@infragistics/igniteui-angular@11.0.9** (latest)

As you can see from the [commit history](https://github.com/zdrawku/licensed-feed-problem/commits/master), the only thing that I did was executing:
```cmd
ng update @angular/core @angular/cli igniteui-cli
```

This is my .npmrc:
```
@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/
//packages.infragistics.com/npm/js-licensed/:_auth=my_token
//packages.infragistics.com/npm/js-licensed/:_password=pass
//packages.infragistics.com/npm/js-licensed/:username=zkolev!!infragistics.com
//packages.infragistics.com/npm/js-licensed/:email=zkolev@infragistics.com
//packages.infragistics.com/npm/js-licensed/:always-auth=true

```

If you are still having this problem, try deleting the content from your .npmrc file and setup again the user setting [by following our guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing#how-to-setup-your-environment-to-use-the-private-npm-feed).
