### ISSUE TITLE
Issue with IgxGrid in IgxTab

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#8638]
## Description  
When an IgxGrid with date column (or with Excel Style Filtering) is edited via date picker (or we open the excel style filter) the overlay is not displayed correctly if the grid is positioned within IgxTab.

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/igx-grid-with-datepicker-in-tab-issue?file=src/app/tabs-sample-3/tabs-sample-3.component.html) sample.
2. Select the second tab.
3. Start editing the "Birth Date" column and open the date picker.

## Result  
The grid and the date picker are not displayed correctly.

## Expected result  
The grid and the date picker to be rendered correctly.
Note: If I change the overflow of the  .igx-tabs__content-fixed to visible everything seems to work as expected, however, it is possible in some scenarios to have side effects.

**Comment by simeonoff** [comment]
Hm, I think this can be fixed with CSS alone. @DiyanDimitrov we can take a look, if you want?

**Comment by DiyanDimitrov** [comment]
@simeonoff, thank you for your help. Let us know if something on our side should be fixed.
