### ISSUE TITLE
IgxGrid scrolls back to the top after clicking outside of the browser and then clicking inside the grid.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#8648]
## Description  
IgxGrid scrolls back to the top after clicking outside of the browser and then clicking inside the grid.

 * igniteui-angular version: 11.0.3
 * browser: Chrome, IE11

## Steps to reproduce  

1. Open the attached reproducible sample in a browser.
2. Scroll the grid down to the bottom.
3. Click one of the cells in the grid.
4. Click somewhere outside of the browser.
5. Click somewhere inside of the grid.

## Result  
The grid scrolls back to the top.

## Expected result  
The grid does not scroll. The scroll position should stay at the bottom.

## Attachments  
Reproducible sample:
[cas33740-app2.zip](https://github.com/IgniteUI/igniteui-angular/files/5600080/cas33740-app2.zip)

Gif animation demonstrating the steps to reproduce:
![cas33740-app2-animation](https://user-images.githubusercontent.com/33947244/100300407-52e3c680-2fd9-11eb-94cb-8e49d208fe83.gif)

**Comment by ddincheva** [comment]
Most probably the same as #8504

**Comment by ddincheva** [comment]
Since there are several issues regarding the described problem they are addressed in issue #8677 for easier tracking.
