### ISSUE TITLE
In Igx-grid version 11.0.3 i see an issue check the image attached, the last column is not shown compleltely and there is white space at the end

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#8654]
## Question  
![image](https://user-images.githubusercontent.com/20819281/100398356-321c7f00-3074-11eb-9c5e-5a289747888c.png)

 * igniteui-angular version: 
 * browser:

**Comment by dkamburov** [comment]
Hello @amitmoondra, apologies for the slow reply, but I can't seem to reproduce the issue in our [samples page](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries#summaries-with-group-by). Can you send a reproducible demo so we can investigate the issue?
