### ISSUE TITLE
New cellClasses and formatter implementation may have performance issues for old working code

### ISSUE THREAD

**Issue by ammritt** [IgniteUI/igniteui-angular#8666]
## Question  
Currently, for our Angular app, we have our own grid which wraps around the Infragistics grid. To instantiate our grid, we define our columns (ICustomColumn[]) which will then programmatically instantiate the Infragistics grid.

I have a piece of code that was working fine a few versions ago, but suddenly the performance of this code has drastically gone down eventually crashing the page.  I have picked out the piece of code that has the problem. Please see my codesandbox example below.

https://codesandbox.io/s/igx-cellclasses-issue-g1zg8

In this code, I have a `[cellClasses]="getCellClasses('number')"` which is defining the class of this column based on some internal logic we have. Currently, I cannot use Infragistics way of using  `(onColumnInit)` because this function cannot provide our custom passed information with` ICustomColumn` and that information is required to decide the cellClass.
Performance is actually far worse if such code is used inside an igx-row-island. See my commented out code for **USBillboard200**  field.

Also, this issue is happening for `[formatter]="getFormatter(ICustomColumn)" ` alike code, it was just easy for me to reproduce it for `cellClasses`

I think a possible resolution would be to either: 

1.  Improve performance of this scenario where a developer may need to use alike code to define cellClasses or formatter properties
2. Allow the ability to set custom data for igx-column which can be then caught inside `(onColumnInit)` and further logic can be implemented by dev based on this data to define a formatter/cellClasses and such.

 * igniteui-angular version: Current
 * browser: any

**Comment by rkaraivanov** [comment]
@ammritt 

I've taken a look at your sample and while I do agree there seems to be something strange with the row-island performance
I have to point out a few things.

The way styling and formatting is applied to a cell is through a couple of pipes. The pipes are pure, meaning they trigger only if their input arguments are changed (either **by value _or_ by reference**). Basically the pipes care mainly for two things: the current value for the cell and the current object that should be applied over it (be it a CSS class/style or a formatter function).

In the sample you provided, the way CSS classes are bound degrades the performance in two main ways.
First, the bounding is done through a function call in the template, meaning this will always trigger the said function on a detection cycle.
What's worst is the the said function always returns a new object reference for the CSS classes, thus triggering each cell style pipe at each detection cycle bringing down the overall performance.

I suggest either to 'cache' the CSS style object or transform your function call which does the binding to a pure pipe on its own.
Here is the updated sample with the first approach 
[![Edit Igx-CellClasses-issue (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/igx-cellclasses-issue-forked-69cms?fontsize=14&hidenavigation=1&theme=dark)

We will still take a look at why exactly the hierarchical grid halts to a grind when a row-island has such a binding.

As for your last point, about passing custom data to the igx-column, can you please elaborate more on that?

**Comment by zdrawku** [comment]
Adding @ChronosSF for the row-island performance comments.

**Comment by MayaKirova** [comment]
@ammritt 
When testing this in the improved version with the cached objects as suggested by @rkaraivanov I was not able to see any performance issues with the row islands.
Could you elaborate on what the exact issue seems to be and whether or not it was resolves as part of the object caching as previously suggested?
I’ve attached a small video of what I observed on my side. I didn’t notice any significant delays when expanding a row or when scrolling through expanded rows.

![Hgrid](https://user-images.githubusercontent.com/10397980/105046166-6bb8a780-5a71-11eb-87f0-935a8a2c7419.gif)

My test was performed on Chrome  Version 87.0.4280.141.

Let me know if you are getting a different result , or if you are perhaps testing on a different environment or if perhaps the performance issue is of a different nature and needs specific steps to reproduce.
