### ISSUE TITLE
How can we make Igxinput type="number" to accept only upto 14 decimal precisions on the cell editor of the grid

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#8669]
## Question  
I have a requirement to accept only upto 14 decimal precisions when user edit the number field on Igx-grid , the field is now accepting more than 14 decimals default , how can we restrict this ?

 * igniteui-angular version: 8.2
 * browser: Chrome

**Comment by valadzhov** [comment]
Hi @Raju-N,

The input value can be limited to a desired length by using the [IgxMask](https://www.infragistics.com/products/ignite-ui-angular/angular/components/mask) directive. You can see it implemented in [this sample](https://stackblitz.com/edit/input-wth-mask). Please note that in order for the IgxMask to be used the `type` of the input has to be set to `text`.
