### ISSUE TITLE
Explore and implement a minimum number of elements under which virtualization just renders everything

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#867]
The task includes the following:

- Test the max number of elements that can be rendered on Chrome and IE (best / worst case scenario) before getting noticeable  performance degradation.
- Implement the suggested and approved threshold under which no virtualization is executed by rendering everything and causing the scrollbars to only offset the content.
- Document the threshold appropriately.

**Comment by ChronosSF** [comment]
@kdinev - just checking to see if we still need it in the context of all latest igxGrid changes (default sizing)

**Comment by kdinev** [comment]
I think we still need it, but it's not as necessary as before.

**Comment by SlavUI** [comment]
@ChronosSF  should we close this one ?
