### ISSUE TITLE
Grid active node resets horizontal/vertical scroll positions when page lost focus and regain again

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#8677]
## Description  
If the grid has an active cell and the focus is in the grid when you left the page by changing the active browser tab or click outside your browser and then return back to the grid the active node and the scroll positions are reset.

## Steps to reproduce  

1. Open a Grid https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-row-editing
2. Select a cell -> ProductName Konbu for example
3. Minimize the current browser window, or focus a different program on your OS
4. Return to the browser again

## Result  
What is the actual result after following the steps to reproduce?

 The active node is the first cell in the body and the scroll bars are reset.
## Expected result  
What is the expected result after following the steps to reproduce?

The active node should not be changed and the scroll position should not be reset.

Issues that  state the same problem are:
#8648
#8504
#8488 
#8487

**Comment by amitmoondra** [comment]
can you please update me when will this be fixed?

**Comment by amitmoondra** [comment]
is there any work around till the fix is not released?

**Comment by ddincheva** [comment]
Hello @amitmoondra ,
This fix is currently in development. Unfortunately, we can not provide you a good workaround but in a few days, this fix will be on pull request so I will notify you and you can provide feedback for the fix.

**Comment by amitmoondra** [comment]
that is great, thanks for the update

**Comment by ddincheva** [comment]
Hello @amitmoondra ,
The bug fix related to this issue is already on PR #8726, so you can check it and provide if you have any comments there.
