### ISSUE TITLE
When change the disabled property to true, the label's color will be red like an invalid state.

### ISSUE THREAD

**Issue by cleverdog** [IgniteUI/igniteui-angular#8680]
## Description  
In this sample, I did control the disabled property for igxInput by button.
https://stackblitz.com/edit/input-disabled-yvg7dx?file=src%2Fapp%2Finput-group-sample-1%2Finput-group-sample-1.component.html
When input some value then click the button, the label's color will be red like an invalid state.
If changing the disabled property by Typescript, the issue won't appear.
`this.igxInput.disabled = true`

 * igniteui-angular version: 11.0

## Steps to reproduce  

1. Open the stackblitz.
2. Type some text.
3. Click the button.

## Result  
The label's color will be red like an invalid state.

## Expected result  
Just change the disabled property, don't change the style.

**Comment by kdinev** [comment]
@SisIvanova I will take over this item.
