### ISSUE TITLE
IGX-Grid crash when refreshing

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#8709]
## Description  

When performing a refresh on the Igx-Grid when there is at least one row present, the layout crashes and goes to the top of the screen, I checked and it seems that the grid gets inside a overlay and changes the position to absolute, so I forced the grid to be always relative and got the job done.
But the filters stop working as the video in the link shows.

https://www.loom.com/share/1bbab6f5eb184a62ba0ee10134bc5655

 * igniteui-angular version: "@infragistics/igniteui-angular": "^10.2.5",
 * browser: Chrome

## Steps to reproduce  
Refresh button call process Data that is the function used by the filters to update the grid

**Comment by luiscla27** [comment]
Hello @radomirchev, this issue still occurs, can you please reopen it?
