### ISSUE TITLE
How to restrict Unselect event on ButtonGroup

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#8731]
## Description  
Describe the issue. : We are using Infragistics angular component in our project. In that we have an Igx-grid where we have used 'Button group' component to select a value, we can set the new value on select but if we click again on the selected value it is getting unselected, i dont want to unselect the option. Kindly provide any option if available

 * igniteui-angular version: 8.2
 * browser: chrome

## Steps to reproduce  

1. Step 1 : Create Igx grid with a column for 'Yes/No' using button group component
2. Step 2: On unselect event make the button.selected = true
3. ...

## Result  
What is the actual result after following the steps to reproduce?
It is not making the option selected

## Expected result  
What is the expected result after following the steps to reproduce?
The option need not want to unselect

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by astaev** [comment]
@Raju-N,
[Here ](https://stackblitz.com/edit/github-aqhq5j-lu97xe?file=src/app/grid/grid-sample-3/grid-sample-3.component.html)is a small application modified to meet your requirements. Please take a look at it and feel free to use and modify it.
Basically, it uses the select and unselect event of the buttonGroup, as well as the IgxButtonGroupComponent [selectButton ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxbuttongroupcomponent.html#selectbutton)method.
