### ISSUE TITLE
Tabs, bottom navigation - styling points for headers

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#8757]
## Is your feature request related to a problem? Please describe.
We need styling points for setting the foreground and background of the tab items on both: Tabs component and BottomNavigation.

**Comment by DiyanDimitrov** [comment]
@simeonoff, we will need help from Design Team in order to figure out the best way to provide such styling customizations.

**Comment by simeonoff** [comment]
@DiyanDimitrov sure thing.

**Comment by simeonoff** [comment]
> ## Is your feature request related to a problem? Please describe.
> We need styling points for setting the foreground and background of the tab items on both: Tabs component and BottomNavigation.

In 12.0 you will have direct access to both the label and icon elements. You can apply styles directly to those elements. The alternative will be to use the CSS variables or the Sass theming library to style the background and icon colors.
