### ISSUE TITLE
igxDrop - error TS2341: Property '_data' is private and only accessible within class 'IgxDropDirective'.

### ISSUE THREAD

**Issue by loclv** [IgniteUI/igniteui-angular#8761]
## Description  

`error TS2341: Property '_data' is private and only accessible within class 'IgxDropDirective'`.

 * igniteui-angular version: `11.0.9`
 * igniteui-angular version: `~11.0.6`
 * browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit)

## Steps to reproduce  

1. Create new project with Angular Cli 11 (`npm install -g @angular/cli`)
2. `ng new my-app`
3. Flow [Row Reordering Demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag#row-reordering-demo) to setup droppable Grid. I also created [this repository](https://github.com/loclv/angular-igniteui-row-reordering-demo-11) from this steps.

## Result

Err: `src/app/grid/grid-row-reorder/grid-row-reorder.component.html`

`error TS2341: Property '_data' is private and only accessible within class 'IgxDropDirective'`.

## Expected result  

Drag and drop a column to another order.

![Screenshot from 2021-01-08 16-01-09](https://user-images.githubusercontent.com/6302717/103995353-f4f6f100-51ca-11eb-9b15-a851b1d7ffff.png)

**Comment by loclv** [comment]
thank you for your support! 🚀

**Comment by loclv** [comment]
@ChronosSF @dafo 

I realised that i created new project with strict-mode (a option when create with Angular 11 or using [this](https://angular.io/guide/strict-mode)).

In `./tsconfig.json` i changed `"strictTemplates": true,` to `"strictTemplates": false,` and problem was gone.

```json
{
  ...,
  "angularCompilerOptions": {
    ...,
    "strictTemplates": false
  }
}
```

**Comment by ChronosSF** [comment]
Thanks for the report @loclv !

The issue was an oversight from a separate development. We'll have a fix ready for next week patches.
