### ISSUE TITLE
Icon inputs should have same names in code and view files

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#8769]
## Is your feature request related to a problem? Please describe.
The following `igxIcon` inputs have different names in code and in view files:
- `font` vs `fontSet`
- `active` vs `isActive`
- `innerColor` vs `color`
- `iconName` vs `name`

## Describe the solution you'd like
All inputs should have same name in code and in view files. Otherwise using of the component is very confusing.

**Comment by simeonoff** [comment]
I would argue that neither `font` nor `fontSet` are correct. Color should not be set via javascript either imo. The rest I agree with.

**Comment by wnvko** [comment]
For code I mean `ts` file and for view the `html` file.
