### ISSUE TITLE
Intruduce missing "ing" or "ed" events for grid features.

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#8773]
Currently some features introduce only "ing" events, like `onColumnPinning`, others introduce only "ed" events, like `onColumnResized`. Also, different naming convetion is used in event names and in interfaces.

First table below shows current situation, next table shows implementation plan.

⚠ Behavioral changes
🆕 New stuff
❌ Missing

  | Ing event | Ed event
-- | -- | --
Sorting | ❌ | onSortingDone
Filtering | ❌ | onFilteringDone
Paging | onPagingDone | ❌
Pinning | onColumnPinning | ❌
Hiding | ❌ | onColumnVisibilityChanged
Resizing | ❌ | onColumnResized
Moving | onColumnMovingStart, onColumnMoving | onColumnMovingEnd

Missing events need to be introduced. Also, try to unify naming convention and interfaces (in terms of structure and naming) as much as possible, with as less as possible breaking or behavioral changes. See table below for what will be implemented.

Еvent | Interface
-- | --
sorting   🆕 | ISortingEventArgs   🆕
filtering 🆕 | IFilteringEventArgs   🆕
onPaging 🆕 | IPagingEventArgs🆕
onColumnPinning ⚠ | IPinColumnCancellableEventArgs   🆕
columnVisibilityChanging   🆕 | IColumnVisibilityChangingEventArgs 🆕
columnResizing   🆕 | IColumnResizingEventArgs 🆕
onColumnMovingStart | IColumnMovingStartEventArgs
onColumnMoving | IColumnMovingEventArgs
 |  
onSortingDone | ISortingExpression   \| Array<ISortingExpression>
onFilteringDone | IFilteringExpressionsTree
onPagingDone ⚠ | IPageEventArgs
columnPinned 🆕 | IPinColumnEventArgs
onColumnVisibilityChanged | IColumnVisibilityChangedEventArgs
onColumnResized | IColumnResizeEventArgs
onColumnMovingEnd | IColumnMovingEndEventArgs

📝 Notes:
- All '-ing' events interfaces will extend `IBaseEventArgs` and `CancelableEventArgs`

⚠ Behavioral changes:
- `pageChange` is now hidden, and exposes a message to use `onPagingDone` instead.
- `onPagingDone` will be emitted AFTER the operation has completed
- `onColumnPinning` to emit `IPinColumnCancellableEventArgs`, instead of `IPinColumnEventArgs`. `isPinned` in both "ing" and "ed" events will contain the current pin state of the column.

NOTE: Paging related stuff will be implemented with #8923

**Comment by Aleksandyr** [comment]
@hanastasov @rkaraivanov Can we consider removing all 'on' prefixes of the newly exposed and currently existing events as it was discussed some time ago?

**Comment by hanastasov** [comment]
> @hanastasov @rkaraivanov Can we consider removing all 'on' prefixes of the newly exposed and currently existing events as it was discussed some time ago?

I thought about it, but didn't find it stated official somewhere. It will be a lot of changes, but we need to do it eventually.

**Comment by Aleksandyr** [comment]
At least we can try not exposing the proposed events with that prefix though?

**Comment by hanastasov** [comment]
> At least we can try not exposing the proposed events with that prefix though?

@rkaraivanov suggested the same - new events will skip "on" prefixing. Old events will be renamed later with a mass migration that will happen. I updated the tables accordingly.
