### ISSUE TITLE
igxColumnHiding Feature in the igxGrid

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#878]
### Description  
The users should have an option to hide and unhide columns in the igxGrid using a Column chooser.

- [x] Specification
- [x] Design
- [x] Development
- [x] Tests
- [ ] Documentation
- [ ] Samples

**Comment by tachojelev** [comment]
**NOTE**
The branch from igniteui-angular-samples that contains the new columnHiding sample was updated according to the new structure of the igniteui-angular repo. (This specific commit was not referenced in this issue.)
