### ISSUE TITLE
Summaries does not respect column formatter

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular#8786]
## Description  
Summaries does not respect column formatter. The values in the summary results respect the column pipeArgs, but not the column formatter.

 * igniteui-angular version: 10.2
 * browser: NA

## Steps to reproduce  

1. Open Grid Formatting dev demo
2. Set IgxDateSummaryOperand to the OrderDate column:
```ts
public dateSummary = IgxDateSummaryOperand;
```
```html
<igx-column field="OrderDate" width="200px" [dataType]="'date'" filterable="true" [hasSummary]="true" [summaries]="dateSummary"
```

3. Change the return value in the formatter function if you would like
4. Click the Use formatter function for OrderDate column.

## Result  
The summary results does not respect the formatter function.

## Expected result  
The summary results should respect the formatter function.

## Attachments  
![image](https://user-images.githubusercontent.com/43128948/104445053-52ab8480-55a1-11eb-9996-2698e1b59fa9.png)

**Comment by DiyanDimitrov** [comment]
Related to #8697

**Comment by hanastasov** [comment]
Following a discussion, we agreed to:

1. Intoduce a new input for the column, which is a formatter to format the summary result. Possible name is `summaryFormatter`. The `summaryFormatter` function should take as input the value and the summary operand that will calculate the summary result.
2. Keep operands to return a "clear", non-formatted value (this means to not take pipeArgs argument). summary-cell.component.html template will format the `summaryResult` through the `summaryFormatter` by default, or by the column `pipeArgs` when `summaryFormatter` is not available
3. Let's see how 2) would work for summaries of different types. For example: If the "ReleaseDate" column has `pipeArgs`, it does not make sense to format the `Count` summary using those `pipeArgs`.
