### ISSUE TITLE
IgxTreeGrid reset the expasion state when using "expandAll()"

### ISSUE THREAD

**Issue by sddania** [IgniteUI/igniteui-angular#8797]
## Description  
IgxTreeGrid reset the expasion state when using "expandAll()" function

## Steps to reproduce  
![image](https://user-images.githubusercontent.com/7241893/104621428-6386f380-5690-11eb-862b-8413d9cde362.png)
https://stackblitz.com/edit/github-ymnt8j?file=src%2Fapp%2Ftree-grid-save-state%2FtGrid-state.component.scss

## Result  
on expand all event the expansion grid state on console is empty

## Expected result  
on expand all event the expansion grid state on console is filled with all the expanded rows.

**Comment by DiyanDimitrov** [comment]
@sddania This behavior is by design. The `expandAll` method sets the `expansionDepth` to `Infinity` and clears the `expansionStates`. This approach is simpler and has a better performance than populating all records in the `expansionStates` map.
