### ISSUE TITLE
Emit onColumnVisibilityChanged and onColumnPinning on toolbar actions

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#8844]
## Is your feature request related to a problem? Please describe.
When a column is hidden/pinned through the Excel Style Filtering layout both events onColumnVisibilityChanged and onColumnPinning are emitted. 
If a column is hidden/pinned through the toolbar or the API functions the events are not emitted.

## Describe the solution you'd like
Emit both grid's events onColumnVisibilityChanged and onColumnPinning always when a column gets hidden/pinned.

**Comment by dkamburov** [comment]
@mmart1n These events are now renamed to `columnVisibilityChanged` and `columnPin`. But they seem to be emitted as expected in toolbar. Please use this [sample](https://stackblitz.com/edit/github-4frrjg-ansjdd?file=src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.ts) as a reference.

There is a good chance that this issue has been resolved with the following [commit](https://github.com/IgniteUI/igniteui-angular/commit/be99dcf84a6ca3919606a4683d0654aaf3f61edf).

Please reopen if there are questions or issues regarding this matter.

**Comment by mmart1n** [comment]
> @mmart1n These events are now renamed to `columnVisibilityChanged` and `columnPin`. But they seem to be emitted as expected in toolbar. Please use this [sample](https://stackblitz.com/edit/github-4frrjg-ansjdd?file=src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.ts) as a reference.
> 
> There is a good chance that this issue has been resolved with the following [commit](https://github.com/IgniteUI/igniteui-angular/commit/be99dcf84a6ca3919606a4683d0654aaf3f61edf).
> 
> Please reopen if there are questions or issues regarding this matter.

I have tested the provided sample and it seems that the events are emitted as expected now. Thank you! :)
