### ISSUE TITLE
Incorrect toggling of _shouldBeOpen property of the igxAutocomplete 

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#8899]
## Description  
Our customer is trying to create an igxDropDown component which should get opened via an input with igxAutocomplete directive. The igxDropDown should initially have 0 items and when the user starts typing within the input field a request (the value of the input field is attached as a body) would be sent to the Back-End. It's response should bring filtered items which has to be populated within the igxDropDown component. I have prepared the following [sample ](https://stackblitz.com/edit/github-igx-grid-dropdown-autocomplete-server-side-filtering)for him which simulates a back-end request (worker.service.ts) and where I'm explicitly setting the value of the _shouldBeOpen property of the igxAutocomplete directive in order to work as expected.

 * igniteui-angular version: 11.0.x, 10.2.x
 * browser: any

## Steps to reproduce  

1.  Open the attached sample.
2. Comment line 77 (containing my workaround) within the grid-sorting-sample.component.ts file.
3. Enter edit mode of a cell within the Name column and wait 1 second.
4. Clear the input and wait 1 second.
5. Type "i" and wait 1 second.
6. Clear again the input and wait 1 second.
7. Type "n" and wait 1 second.
8. Clear the input again and wait 1 second.

## Result  
1. On step 3 the dropdown does not contain any items.
2. On step 4 the dropdown does not contain any items.
3. On step 5 the dropdown does not contain any items.
4. On step 6 the dropdown does not contain any items.
5. On step 7 the dropdown should contain 0 items.
6. On step 8 the dropdown contain all 8 items from the data of the WorkerService.

## Expected result  
1. On step 3 the dropdown should be toggled and contain only 1 element (the cell value).
2. On step 4 the dropdown should contain all 8 items from the data of the WorkerService.
3. On step 5 the dropdown should contain 2 items -> Infragistics and Infragistics1.
4. On step 6 the dropdown should contain all 8 items from the data of the WorkerService.
5. On step 7 the dropdown should contain 0 items.
6. On step 8 the dropdown should contain again all 8 items from the data of the WorkerService.

## Attachments  
1. How it should behave after the bug is fixed (currently achieved via commenting line 77  within the grid-sorting-sample.component.ts).
![autoCompleteWorking](https://user-images.githubusercontent.com/44684385/106762914-ffc46a80-663e-11eb-8e72-fbb4699f9687.gif)

2. How it currently behaves if line 77 is commented out.
![autoCompleteNotWorking](https://user-images.githubusercontent.com/44684385/106762930-04891e80-663f-11eb-8b67-655946066b85.gif)

**Comment by valadzhov** [comment]
@mmart1n, do you know if it's necessary for the customer to use a pipe? There's a high possibility that the issue stems from there (and not from the autocomplete). If possible can you suggest to the customer to use the method implemented in [this sample](https://stackblitz.com/edit/autocomplete-server-side-filter). Also, expected result #1 is not correct since the drop down is opened only on input, not on focus event which is performed in step #3.

**Comment by valadzhov** [comment]
@mmart1n, I was wrong. This behaviour is indeed caused by the _shouldBeOpen property, so I made the necessary changes.
But expected result #1 is still incorrect.
