### ISSUE TITLE
a11y: Improve time-picker accessibility

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#8932]
## Description  
Provide an accessible experience for igx-time-picker.

Consider adding some of those roles:
-spinbutton
-presentation
-region

We also need aria-label on the groups HH.MM.AM.

NOTE: We need to trap the focus inside the time picker dialog.

 * igniteui-angular version: 11.1.x
 * browser: all

**Comment by Lipata** [comment]
We've updated ARIA sections of both [igxDatePicker](https://github.com/IgniteUI/igniteui-angular/wiki/Time-Picker-Specification) and [igxTimePicker](https://github.com/IgniteUI/igniteui-angular/wiki/Date-Picker-Specification) components, using the suggestions above and ARIA will be done as part of their refactoring.
