### ISSUE TITLE
Add support for templating igxRowAddText, like igxRowEditText.

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#8964]
Hello guys,

I'm implementing a feature that requires me to validate a value in an already existing row, or a new row before it can be submitted or changed.

I've used the igxRowEditText template to display a validation error, which works like a charm. However, the same approach is not viable when adding a new row. See the images below:

Edit:
![image](https://user-images.githubusercontent.com/43247999/107646530-5bfc3f80-6c7a-11eb-891e-a3273a266e95.png)

Adding:
![image](https://user-images.githubusercontent.com/43247999/107646669-81894900-6c7a-11eb-9992-df8152cb85f8.png)

So my feature request is the following. Implement support for templating igxRowAddText or document that this can be in the existing version if possible. I would rather not add a row, then enter it in edit mode, although this can be a work-around. 

Thanks

**Comment by VirtualisProject** [comment]
Any status on this?

**Comment by radomirchev** [comment]
Hi @VirtualisProject, we are going to include it in the planning for the next sprint. I will update you once we have ETA.
