### ISSUE TITLE
Translate label in Boolean column filter

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#8971]
I need to translate the text that appears in the filter for the Boolean data type. By default it appears true and false but I don't know how to translate it. With the resources I can modify the options but not that. By default is:

![image](https://user-images.githubusercontent.com/36885861/107670951-8f979380-6c93-11eb-8517-139d89ace8cc.png)

And I have:
![image](https://user-images.githubusercontent.com/36885861/107670853-75f64c00-6c93-11eb-8b89-c91a121e750c.png)

I need to show "Sí" or "No" instead of true or false.

**Comment by igdmdimitrov** [comment]
Hi @ssg127, 

Currently this is not supported by the localization resources. There is another way to achieve this but it will not work for columns with Boolean data type. If the column has String data type, then you can use the [Formatted Values Filtering Strategy](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#formatted-values-filtering-strategy). Here is a [Stackblitz sample](https://stackblitz.com/edit/github-bhodty?file=src/app/grid/grid-excel-style-filtering-sample-1/grid-excel-style-filtering-sample-1.component.html) I prepared to illustrate this approach.

**Comment by ssg127** [comment]
@igdmdimitrov Thank you. I've tried and If I do this:
`<igx-column
      field="Discontinued"
      header="Discontinued"
      [sortable]="true"
      [movable]="true"
      [dataType]="'boolean'"
      [formatter]="formatBoolean"
    >`
Filter shows the text Ok but filter doesn't works. I want to use boolean filter instead of string filter.
This cuold be in a future releases?

**Comment by DiyanDimitrov** [comment]
@ssg127 yes, since we already have the True/False strings localized, we can just use them in the Excel style filter menu.

**Comment by ssg127** [comment]
@DiyanDimitrov this could be solved in future? I think it is something necessary.

**Comment by DiyanDimitrov** [comment]
@ssg127, yes, we are going to resolve it.

**Comment by ssg127** [comment]
In which version will this be available in?

**Comment by gedinakova** [comment]
Hello, this fix is already available in 10.2, 11.0 and 11.1. Please, let us know if you still have any issues!

**Comment by ssg127** [comment]
@gedinakova Thank you so much!
