### ISSUE TITLE
Cells in a Boolean column ignore the column formatter

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular#8978]
## Description  
Cells in a Boolean column ignore the column formatter

 * igniteui-angular version: 11.0.x
 * browser: all

## Steps to reproduce  

1. Pass a formatter function to a Boolean column
2. Observe the cells in the column.

## Result  
The default Boolean cell template is shown

## Expected result  
The values in the cells should be passed through the provided formatter function.

**Comment by k8edev** [comment]
We're experiencing this issue as well.
