### ISSUE TITLE
Regression - moving column jump to original position

### ISSUE THREAD

**Issue by ZCeli** [IgniteUI/igniteui-angular#8994]
## Description  
When moving any column in a grid that has nested object the column jumps back to its original position.
This was not happening with version 10.2.6, it started to happen after I updated to version 10.2.12. Reverting the version to 10.2.6 fixes the problem.

 * igniteui-angular version: 10.2.12
 * browser: chrome

## Steps to reproduce  

1. Open a grid that has a column with nested obejct
2. Move any column

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
The column should stay where moved to.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by mddragnev** [comment]
Hello @ZCeli,
I am trying to reproduce the issue [here](https://stackblitz.com/edit/github-54otxh?file=src/app/grid/services/financialData.ts) but without any success. You can see in the dependency tab that the version of igniteui-angular I am using is 10.2.12. Could you please change this sample or attach any sample that reproduces your issue. Also, by nested object do you mean that the data for specific column is an object?
