### ISSUE TITLE
InputGroupType's "Search" naming is unclear

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-angular#8998]
By it's name, it is not clear what the input group type "Search" is supposed to look like. While "Line", "Box" and "Border" are self-explanatory, "Search" sounds more like a functionality.
We should think of a name that describes better the look of that type.

"Line", "Box" and "Border" (and eventually "Search") should be only in the scope of the Material theme.

**Comment by Lipata** [comment]
Search type is presented in the native input and after a discussion with the design team we decided we will not change the name.
