### ISSUE TITLE
Is it a way to create <igx-row-island> conditionally inside IgxHierarchicalGridComponent??

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular#9064]
## Question  
Is there a way to create `<igx-row-island>` conditionally inside `IgxHierarchicalGridComponent`??

I want to add recursive island levels, something like the following example, the issue here is that this would create infinite levels (my guess is that it doesn't work due to infinite recursiveness):

```
<ng-template #treeTemplate>
  <igx-column field="treeCode" [resizable]="true" [filterable]='true'></igx-column>
  <igx-column field="treeDescription" [resizable]="true" [filterable]='true'></igx-column>
  <igx-column field="childCount" [resizable]="true"></igx-column>
  <igx-row-island key="childs" primaryKey="levelId" [autoGenerate]="false">
    <ng-template *ngTemplateOutlet="treeTemplate"></ng-template>
  </igx-row-island>
</ng-template>
<div class="grid__wrapper">
  <igx-hierarchical-grid igxPreventDocumentScroll class="hierarchicalGrid" primaryKey="levelId" [data]="localdata">
    <ng-template *ngTemplateOutlet="treeTemplate"></ng-template>
  </igx-hierarchical-grid>
</div>
```

So I'm trying to solve it with something like this` *ngIf="parentHasChildAvailable(parent)"` or even a fake lazy-load using `(onGridCreated)`.

```
  <igx-row-island key="childs" primaryKey="levelId" [autoGenerate]="false" *ngIf="parentHasChildAvailable(parent)">
    <ng-template *ngTemplateOutlet="treeTemplate"></ng-template>
  </igx-row-island>
```
I'm wondering if there's a natural way to cover my use-case.

 * igniteui-angular version: ^11.1.0
 * browser: Chrome 88.0.4324.182

**Comment by ChronosSF** [comment]
Hi @luiscla27 , 

Have you considered using igxTreeGrid instead? If the records on each level have the same type, it looks a lot more like a tree grid scenario. With it you just specify the foreign key/pk relation or children key and you'll get the whole hierarchy with a simple template.

Check this topic and samples for more information: https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree-grid

**Comment by luiscla27** [comment]
I'll take a look at it :)

**Comment by luiscla27** [comment]
igxTreeGrid fulfills my use case :)
