### ISSUE TITLE
Deselect when clicking selection

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#9086]
## Is your feature request related to a problem? Please describe.
When selecting a cell or row, it doesn't seem to be a way deselect the cell or row again with the mouse. 

## Describe the solution you'd like
It would be nice to have a mode for the grid, where clicking the selection removed the selection again.

**Comment by Eralmidia** [comment]
Additionally, the option to deselect when the grid looses focus would also be nice. We have pages with multiple grids on them, and it looks kinda noisy when multiple grids has selections

**Comment by Szanik** [comment]
+1

**Comment by MonikaKirkova** [comment]
Clearing the selection could be achieved on application level when the grid loses focus. I have [prepared a sample](https://stackblitz.com/edit/angular-dlxodq?file=src%2Fapp%2Fgrid%2Fgrid-cellSelection-sample%2Fgrid-cellSelection.component.ts,src%2Fapp%2Fgrid%2Fgrid-cellSelection-sample%2Fgrid-cellSelection.component.html) demonstrating this behavior.
