### ISSUE TITLE
Igx-grid beginAddRow with virtualized grid

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#9111]
## Question  
I have an issue with using beginAddRow in the Igx-grid. 

I am attempting to add a row at the end of the grid, but in my case the last row in the grid is not rendered yet due to the grid being virtualized. Fetching the row using getRowByIndex will therefore return undefined, even though the data set contains a row with that index.

code:

```
const row = this.grid.getRowByIndex(this.gridData.length - 1);
        if (row) {
            row.beginAddRow();
         }
```
So, my question is quite simple. How can I add a row using beginAddRow on the last row in the data set.

**Comment by MayaKirova** [comment]
@VirtualisProject 
You can first navigate to the row so that it exists in the view before calling the API, for example:
`
    this.grid.navigateTo(lastIndex, -1, () => {
          const row = this.grid.getRowByIndex(lastIndex);
          row.beginAddRow();
    });
`

Here's a sample for your reference as well: https://stackblitz.com/edit/github-mqvynf

**Comment by VirtualisProject** [comment]
Thanks, this resolved my issue.
