### ISSUE TITLE
igx-radio emits multiple change event with ngModel

### ISSUE THREAD

**Issue by StefanoNotaro** [IgniteUI/igniteui-angular#9136]
## Description  
Using igx-radio and ngModel does not work as expected. Inside the method triggered by event "change" we set up the value and trigger again the event. In version 10.1.4 wasn't doing that.

 * igniteui-angular version: 10.2.15
 * browser: Microsoft Edge Version 89.0.774.50

## Steps to reproduce  

1. Navigate to stackblitz example: https://stackblitz.com/edit/angular-igniteui-radio?file=src%2Fapp%2Fapp.module.ts
2. Select Option 1
3. check logs, select again option 2

## Result  
Changing the ngModel does not trigger the change event

## Expected result  
Changing the ngModel does not trigger the change event

## Attachments  
1. Navigate to stackblitz example:
https://stackblitz.com/edit/angular-igniteui-radio?file=src%2Fapp%2Fapp.module.ts

**Comment by wnvko** [comment]
@StefanoNotaro
Your sample uses Angular 11 with IgniteUI 10. Upgrading your IgniteUI version to 11 solves the issue.

**Comment by wnvko** [comment]
Looking further at this there is another issue. Clicking on the label selects the radio, while clicking on radio does not select it.

**Comment by simeonoff** [comment]
> Looking further at this there is another issue. Clicking on the label selects the radio, while clicking on radio does not select it.

This is the **only** issue I could see and I believe it's a regression as this used to work before.
