### ISSUE TITLE
Migrations are failing migrating specific references 

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular#9137]
## Description  
Migrations are failing migrating specific references 

 * igniteui-angular version: 12.0.x
 * browser: all

## Steps to reproduce  

1. Get those tow PR's [9045](https://github.com/IgniteUI/igniteui-angular/pull/9045) | [9058](https://github.com/IgniteUI/igniteui-angular/pull/9058)
2. Build the migrations
3. Link the library and try to change [onValueChanged](https://github.com/IgniteUI/igniteui-angular/pull/9045/files#diff-cdc7ae5fc30bdcf9ea68d4751d517f3594dbf083bf00673ca97a66d34ce3d14a) from [9045](https://github.com/IgniteUI/igniteui-angular/pull/9045) and [onColumnChange](https://github.com/IgniteUI/igniteui-angular/pull/9058/files#diff-737bed701afbcfc6b4ff1e0512bfb1dfbf45d9655edc138f2ff5921c41cdf635) from [9058](https://github.com/IgniteUI/igniteui-angular/pull/9058)

## Result  
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7037740/110944906-c077f080-8345-11eb-97d0-acfa9683d6c1.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7037740/110944909-c1a91d80-8345-11eb-98d6-80318f44655b.png)

**onValueChanged** marges with the declarations afterward.
**onColumnChange** is not recognizing that **getColumnByName** returns **IgxColumnComponent** reference

## Expected result  
The migrations should be applied without any issues

**Comment by damyanpetev** [comment]
Those are two separate issues, but still here's what I see:
- The matching for members is a bit too basic and the overlap between `onValueChange` and `onValueChanged` causes the replace to happen twice on the second one.
- The current migrations can't evaluate return type of methods (like `getColumnByName`) and thus fail to replace the member after.

While the last one is indeed a limitation with the current implementation and should be resolved, the specific PR that hit this is odd - fairly certain `onColumnChange` is internal and thus shouldn't need to be migrated at all.
