### ISSUE TITLE
Setting grid state does not clear previously selected rows

### ISSUE THREAD

**Issue by tishko0** [IgniteUI/igniteui-angular#9139]
## Description  
Restoring previously saved gridstate does not clear newly selected lines

 * igniteui-angular version:  11.2
 * browser: Chrome

## Steps to reproduce  

1. Run sample

## Result  
Row 1 of the grid should deselect as the newly set state does not include it in its selection

## Expected result  
The new grid state should correctly display the state input

## Attachments  
https://stackblitz.com/edit/igxgrid-stale-selection-ajsjdv?file=src%2Fapp%2Fgrid%2Fgrid-sample-selection%2Fgrid-selection.component.ts

**Comment by DaleMatthews** [comment]
Perhaps [this line](https://github.com/IgniteUI/igniteui-angular/blob/9d6312d6e00253faddb3da85e7feeae73486325d/projects/igniteui-angular/src/lib/grids/state.directive.ts#L240) should pass in true
```
context.currGrid.selectRows(state, true);
```

**Comment by hanastasov** [comment]
The fix is available in version [10.2.18](https://github.com/IgniteUI/igniteui-angular/releases/tag/10.2.18)
NPM: https://www.npmjs.com/package/igniteui-angular/v/10.2.18
