### ISSUE TITLE
Question - How to use igx-label with igx-datePicker.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#915]
### Description  
I tried using igx-label with igx-datePicker. But it didn't work well. igx-label doesn't float to the top of the igx-datePicker field.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-label-issue.
2. Click input to show datepicker.
3. Pick out a date from the calendar.

### Result  
Label doesn't float to the top of the igx-datePicker field after editing.

### Expected result  
Label should float to the top of the igx-datePicker field.

### Question
How can igx-label and igx-datePicker work together?

**Comment by simeonoff** [comment]
We've completely rewritten the inputs so this feature will come out of the box with the next release, which will happen on the 16th. It will be in the next beta, too :) Cheers!

**Comment by tkiryu** [comment]
Thanks! I'm looking forward to it!
