### ISSUE TITLE
incorrect style of checkbox text when unchecked in Safari

### ISSUE THREAD

**Issue by loclv** [IgniteUI/igniteui-angular#9168]
## Description

Incorrect style of checkbox text when unchecked in Safari.

 * igniteui-angular version: 11.1.3 (latest version in 2021/03/17)
 * browser: Safari - Version 14.1 (16611.1.18.1.2) - macOS Big Sur 11.3

## Steps to reproduce

https://stackblitz.com/edit/igx-checkbox-disable-safari?file=src/app/checkbox-sample-1/checkbox-sample-1.component.html

1. Click `check/un-check` button.
2. You can see incorrect style of checkbox text (`Simple checkbox` text).

![Screen Shot 2021-03-17 at 7 36 31 PM](https://user-images.githubusercontent.com/6302717/111469844-c14fbe80-8759-11eb-8f43-03308f4f4389.png)

## Expected result

Checkbox text color is not `disabled` color.

**Comment by desig9stein** [comment]
Hi @loclv, I noticed that you are using safari technology preview 14.1 which is not officially released. Since the problem does not appear in the latest official release of safari 14.0.3 (16610.4.3.1.7), I think it's better to wait for an official release and investigate further if the problem persisted. I will leave the issue open for now.

**Comment by loclv** [comment]
@desig9stein Thanks for answering!

**Comment by loclv** [comment]
Sometime, i have same bugs on Safari. My solution is simple:

When change style back to `color: black;`:

```scss
color: black;
-webkit-text-fill-color: black;
```
:smile:

**Comment by loclv** [comment]
My solution detail:

<img width="748" alt="Screen Shot 2021-05-29 at 12 47 41" src="https://user-images.githubusercontent.com/6302717/120059588-b7610a80-c07c-11eb-9430-3b683d7ecb11.png">

**Comment by simeonoff** [comment]
Looks like this is a bug in Safari. We've tested with the latest Safari Technology Preview and the issue is resolved there.

**Comment by loclv** [comment]
@simeonoff Thank for your information!
You can close this issue if you want.

**Comment by simeonoff** [comment]
I will leave it open for now for better discoverability.
