### ISSUE TITLE
Tooltip for long Expansion panel titles 

### ISSUE THREAD

**Issue by DaniMarinov** [IgniteUI/igniteui-angular#9176]
Check [this sample ](https://codesandbox.io/s/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/layouts/expansion-sample-1?fontsize=14&hidenavigation=1&theme=dark&view=preview&file=/src/app/expansion-sample-1/expansion-sample-1.component.html)

As you can see when the title exceeds the component's width, users cannot see the full title. A possible solution is exposing a tooltip on hover revealing the full title.

**Comment by StefanIvanov** [comment]
The expansion panel header is fully templatable, thus one may configure it differently than the ellipsis that is added for the default template. You may add a tooltip, wrap the text to a second line, or choose whatever approach works best for your content.
