### ISSUE TITLE
ignite ui-angular: igx-dropdown-scroll-issue

### ISSUE THREAD

**Issue by manjubhashini-19** [IgniteUI/igniteui-angular#9180]
## Description  
We used class="drop-down__scroll-container" and .drop-down_scroll-container {max-height: 240px} for a scrollabe dropdown taken reference from the link below:

https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/data-entries/dropdown-sample-3

But this is not working in ipad 7th, the container is not scrollable despite giving max height and we tried adding overflow-y: auto/scroll as well.

Please try opening below given link in **ipad 7th gen** scroll bar does not work. I did'nt have a chance to test in iphone(s) however i tested on iPad air software version: 12.5.1 it works fine.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/drop-down

Need your support on this issue.

Please find screenshot and model detail for reference
Model: iPad 7th
iPadOS version : iPadOS 13.7

 * igniteui-angular version: 
 * browser: ipa7th gen

## Steps to reproduce  

1. Open the below link in ipad 7th gen and try to scroll the countries .
2. https://www.infragistics.com/products/ignite-ui-angular/angular/components/drop-down

## Result  
What is the actual result after following the steps to reproduce?
**scroll wont work**

## Expected result  
What is the expected result after following the steps to reproduce?
**scroll should work**

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![scroll screenshot ipad 7th gen](https://user-images.githubusercontent.com/81167028/111993700-ef0f7b80-8b3c-11eb-9b47-8d4004fd9b30.png)

**Comment by Lipata** [comment]
@manjubhashini-19 can you specify the Safari version?

**Comment by manjubhashini-19** [comment]
ipad 7th gen safari version that we used was 13.7.

**Comment by manjubhashini-19** [comment]
Can you please take this on priority as we have a go live in few days and we are utilizing igx dropdown in our application

**Comment by radomirchev** [comment]
@manjubhashini-19, the issue is already prioritized and scheduled for the current Sprint, ending on 2nd of Apr.

**Comment by manjubhashini-19** [comment]
@simeonoff  Will it reflect in our application now? Any changes that we have to add from our end to the application?

**Comment by simeonoff** [comment]
> @simeonoff  Will it reflect in our application now? Any changes that we have to add from our end to the application?

I don't think so, it should just work.

**Comment by manjubhashini-19** [comment]
We are using licensed version and packages are already installed

**Comment by Lipata** [comment]
@manjubhashini-19 you can find the fix in both [10.2.18](https://github.com/IgniteUI/igniteui-angular/releases/tag/10.2.18) and [11.1.5](https://github.com/IgniteUI/igniteui-angular/releases/tag/11.1.5).
