### ISSUE TITLE
Theme generates unnecessary image class

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#9185]
## Description  
I have an image with class `image`. When including `igx-theme` with `$default-palette` it sets the max height of the image to 120px.

 * igniteui-angular version: 11.1.4
 * browser: all

## Steps to reproduce  
Open this [Stackblitz ](https://stackblitz.com/edit/image-theme-issue?file=src%2Fstyles.scss) sample. Observe the image

## Result  
Image height is limited to 120px because of the added trough theme `image` class.

## Expected result  
Image height should not affected.

## Notes
In root `style.scss` if you comment out this line
```
@include igx-theme($default-palette);
```
the issue is gone.

**Comment by simeonoff** [comment]
Closing as it's resolved in both master and 11.1.x branches now.
