### ISSUE TITLE
A weird scrollbar is visible when we decrease the zoom level of browser in infinite scroll

### ISSUE THREAD

**Issue by vijrohit158** [IgniteUI/igniteui-angular#9191]
To make responsive, I have added height of grid in Calc like height: calc(100% - 200px);

<img width="789" alt="Untitled" src="https://user-images.githubusercontent.com/81306261/112310045-1f385500-8cca-11eb-8619-ad1dfdaf36f0.png">

**Comment by MayaKirova** [comment]
@vijrohit158 Currently the igx-grid does not support calc sizes. It can only have pixel or percentage size. You can put it in a container div that has height: calc(100% - 200px) and set the height of the grid to 100% so that it fills that size. 
Let me know if this resolves your issue.
