### ISSUE TITLE
Infragistics getCellByKey(cell.row.rowID, col.field) 

### ISSUE THREAD

**Issue by PreetikaGupta2021** [IgniteUI/igniteui-angular#9201]
## Description  
getCellByKey(cell.row.rowID, col.field) returns undefined for cells not displayed on screen

 * igniteui-angular version: igniteui-angular-9.0.8
 * browser: IE, Chrome

## Steps to reproduce  

1. on igx grid, select a row
2. getCellByKey(cell.row.rowID, col.field) returns only the displayed cells, cells not displayed can't be updated hence

## Result  
getCellByKey(cell.row.rowID, col.field) only returns displayed cells for the selected row

## Expected result  
getCellByKey(cell.row.rowID, col.field) should return all the cells for the selected row and not only the displayed ones

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by ChronosSF** [comment]
igxGrid utilizes virtualization both horizontally and vertically to limit the number of DOM elements on the screen and improve performance. There is literally no IgxGridCellComponent to return for cells that are not in view, so the methods cannot return them.

What do you need an arbitrary cell in the selected row for? Can't you get what you need from the data source or column properties? I can help you workaround this if you let me know what information you need to extract.
