### ISSUE TITLE
IgxCalendarComponent throws errors if its value is InvalidDate

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#9208]
## Description  
The `IgxCalendarComponent` fails to handle a value that is an `InvalidDate`.

 * igniteui-angular version: 10.2.x, 11.1.x, 12.0.x
 * browser: n/a

## Steps to reproduce  

1. Open the following sample [stackblitz](https://stackblitz.com/edit/github-cdwnth?file=src%2Fapp%2Fcalendar-sample-5%2Fcalendar-sample-5.component.ts)
2. Observe.

## Result  
The calendar does not render properly and there are errors in the console.

## Expected result  
The calendar renders normally and there are no errors in the console.

**Comment by zdrawku** [comment]
As we spoke with Bobi, the default behavior of the TimePicker and IgxDateTimeDirective is to handle InvalidDate, null, undefined and NaN.
