### ISSUE TITLE
Is it possible to use both autosize() and have ellipsis for resizable column header text?

### ISSUE THREAD

**Issue by serverinv** [IgniteUI/igniteui-angular#9229]
## Question  
I'd like to use autosize() to set initial columns width and display the whole column header text. At the same time my columns are resizable and I'd like to show ellipsis in the header when user makes the column smaller and overflow happens. Is it possible to have autosizing and resizable columns and show ellipsis in the header when user compresses the columns?

 * igniteui-angular version: 10.2.3
 * browser: Google Chrome 89.0.4389.90

**Comment by serverinv** [comment]
Hello @ChronosSF,
I can have a lot of columns, so horizontal scrollbar is important. 

> use some map to store if you autosized them already or not (so you don't autosize a column that had its size changed by the end-user)

Could you please specify which property can be used to understand if the column was already autosized or not?

**Comment by ChronosSF** [comment]
I'd do something like this:

1. Subscribe to `onScroll`
```html
<igx-grid ... (onScroll)="scrolled($event)">
</igx-grid>
```

2. Create a set with the columns that have been autosized already. Autosize all columns after view init and on horizontal scroll
```typescript
private resizedSet = new Set<string>();

public ngAfterViewInit() {
    this.resizeColumns();
}

public scrolled(args: IGridScrollEventArgs) {
    if (args.direction === 'horizontal') {
        this.resizeColumns();
    }
}

private resizeColumns() {
    this.grid1.columnList.forEach(c => {
        if (!this.resizedSet.has(c.field)) {
            c.autosize();
            this.resizedSet.add(c.field);
        }
    });
}
```

I hope this helps.

**Comment by serverinv** [comment]
Hello @ChronosSF ,
I also use column pinning feature and want to show pin icons in the header.
Here is an example where autosizing doesn't work as expected and ellipsis are added manually (they are not added by default if igxHeader template is used)): https://stackblitz.com/edit/github-ia3jmb-ceyqyb

**Comment by ChronosSF** [comment]
This likely falls under the same improvement I am trying to make for #9261  . I'll update you again in a couple of days when I'll have more time to work on it and test your case under the new code.

Thanks for reporting it!
