### ISSUE TITLE
Need filters for time in igx-grid

### ISSUE THREAD

**Issue by priyankachoudhari** [IgniteUI/igniteui-angular#9247]
In igx-grid - dataType date, when we can display only time and not date (format : HH:mm:ss), the filter is still for date only.
we need filters for time as well.
Eg: Before 12:00
Between 1:00 and 2:00
Please support the same

**Comment by radomirchev** [comment]
@priyankachoudhari after introducing #7678 in Ignite UI 12.0.0, the feature request is resolved. Check this [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-types).
