### ISSUE TITLE
GroupBy sorting does not work as expected after loading igxGrid state

### ISSUE THREAD

**Issue by martinesoff** [IgniteUI/igniteui-angular#9257]
## Description  
When loading the state of the groupBy and sorting, the indicator for the sorting of the grouped columns does not change when clicked and the state of sorting cannot be saved anymore.

 * igniteui-angular version: 11.1.x, 10.2.x
 * browser: any

## Steps to reproduce  
1. Open the following [sample](https://stackblitz.com/edit/igx-grid-state-persistence-issue?file=src%2Fapp%2Fgrid%2Fgrid-save-state%2Fgrid-state.component.ts)
2. Drag any column to apply grouping
3. Click on the Leave button
4. Click on the Go Back button
5. Click on the chip of the grouped column

## Result  
The icon for the direction of the sorting of the grouped column does not change.
Additionally, when reloading the page, the sorting is not saved anymore.

## Expected result  
The icon for the direction of the sorting of the grouped column works as expected and the sorting state is always saved.

## Attachments  
https://user-images.githubusercontent.com/5458174/113420698-6c0ae280-93d2-11eb-9b4f-21ab420e2023.mp4

**Comment by martinesoff** [comment]
I am reopening this since the issue is still reproducible.

**Comment by zdrawku** [comment]
@martinesoff, could you please share a detailed explanation how to reproduce the issue again as @Aleksandyr will be working on it

**Comment by hanastasov** [comment]
The issue is reproducible is vice versa:

1. Open the following sample
2. Drag any column to apply grouping
3. Click on the Leave button
4. Click on the Go Back button
5. Click the sorting header on the sorted column

Observe that the group chip sortind indicator does no change.
