### ISSUE TITLE
Add support for dynamic loading of i18n resources in igx-grid

### ISSUE THREAD

**Issue by kcostenbader** [IgniteUI/igniteui-angular#9286]
Our application services users in many different countries. As such, we have a need to provide internationalization support for these users in these countries.

We would like to use the native i18n functionality provided by the grid, but doing so would require bundling every available language resource with our component. Our users are very, very sensitive to page load time so we are concerned about the impact this would have on the application's performance.

Ideally it would be best if we could dynamically load the appropriate resource when the component is initialized, based on the end-user's selected language. This is actually how we are initializing the angular i18n resources.

**Comment by IvayloG** [comment]
Hello @kcostenbader, did you had the chance to check the relatively newly updated topic regarding i18n [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/localization)? You can refer to the topmost sample, where the localization is based on a language selection. The sample illustrates registering the required resources on ngOnInit. 
Is it an option for you to create/store the required resources similar to the "partialCustomBG" resource from the sample?
Or do you expect to have a service fetching only the required language resources?

**Comment by kcostenbader** [comment]
Yes, we have looked at that, but it illustrates exactly the problem we are trying to avoid, which is defining and loading every possible/available internationalization script in the component. 

We can only ever use one at a time and this use is based on the current user's settings. All of this work will increase the size of the component and require ongoing maintenance to add support for new languages as they are introduced.

When using the jquery igniteui grid, we could easily dynamically load just the resources for the current user's locale with a fallback options to check for the region only followed by a backstop of loading the default en-US settings if neither of the above worked.

We are using SystemJS rather than webpack or other bundling, so we might have to resort to something like that, but it would be much better if there were a native solution to this issue.
