### ISSUE TITLE
igxCarousel: Setting navigation to false has no effect

### ISSUE THREAD

**Issue by SSoelvsten** [IgniteUI/igniteui-angular#929]
### Description  
Changing the navigation property of the Carousel has no effect

### Steps to reproduce  
1. Copy/Paste the minimal example attached below into a new Angular project
2. In _app.component.html_ set `[navigation]="true"` and `"false"`

### Result  
When _navigation_ is set to **false** the webpage looks exactly as if it was set to **true**.

### Expected result  
Based on the API, the left/right-buttons should not be shown, when `[navigation]="false"` 

### Attachments  
The following is a minimal example

**app.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { NgModule } from '@angular/core';

import { IgxCarouselModule, IgxSliderModule } from "igniteui-angular/main";

import { AppComponent } from './app.component';

@NgModule({
    declarations: [
	AppComponent
    ],
    imports: [
	BrowserModule,
	BrowserAnimationsModule
	IgxCarouselModule,
	IgxSliderModule
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }
```
**app.component.html**
```
<igx-carousel [navigation]="false">
  <igx-slide>
    <h3 style="text-align: center; padding-bottom: 50px">1</h3>
  </igx-slide>
  <igx-slide>
    <h3 style="text-align: center; padding-bottom: 50px">2</h3>
  </igx-slide>
  <igx-slide>
    <h3 style="text-align: center; padding-bottom: 50px">3</h3>
  </igx-slide>
</igx-carousel>
```

### Solution: 
Change line 15 in carousel.component.html into
```
<div *ngIf="navigation"> 
```

**Comment by kdinev** [comment]
Closing this issue. It's resolved in `version: 5.3.x`+
