### ISSUE TITLE
Datagrid custom summary template

### ISSUE THREAD

**Issue by TheDiehard22** [IgniteUI/igniteui-angular#9290]
## Is your feature request related to a problem? Please describe.
We have a design for a datagrid where the summary row has extra functionality. It can compare summary data with external data and it can add extra rows from the first cell of the summary row.
Right now we can't add custom templates to a summary cell which you can do with every other cell.

## Describe the solution you'd like
I would like the ability to provide a custom template just like igxHeader, igxCellEditor etc. 

## Describe alternatives you've considered
I've tried adding a footer row which didn't work. Right now I have an extra datagrid right where the summary grid should be and gave it the summarized data as 1 row. This allows me to use custom igxCell templates and the cells still align with eachother when provided with the same config.

![image](https://user-images.githubusercontent.com/16148391/113995743-cf739500-9856-11eb-8eb3-69d776435b32.png)

**Comment by zdrawku** [comment]
Available with version 13.0.1 

https://github.com/IgniteUI/igniteui-angular/pull/10508/files
