### ISSUE TITLE
Dock Manager

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular#9293]
## Additional context
![image](https://user-images.githubusercontent.com/79090369/114007788-41f86b00-987f-11eb-9031-edb47c432a64.png)

**Comment by DiyanDimitrov** [comment]
@KaushikEDS I am closing this since it doesn't have enough information. If you still want to submit a Dock Manager feature request  please use the [dock manager repo](https://github.com/IgniteUI/igniteui-dockmanager).
