### ISSUE TITLE
Automatically focus the newly added row in the igx tree grid.

### ISSUE THREAD

**Issue by Ashokkumar1995** [IgniteUI/igniteui-angular#9300]
## Is your feature request related to a problem? Please describe.
When a new row is added to the large tree grid(scrollable), we are not able to focus the new row.
the new row is added at the end as of now.

## Describe the solution you'd like
i dont know !!
## Describe alternatives you've considered
tried to get the newly added row, but i cant get the newly added row.

---

**Comment by mddragnev** [comment]
Hello @Ashokkumar1995,
When adding, the new row is supposed to be rendered as last record by specification. You can scroll to the newly added row using the SHOW button in the banner which opens when you complete your adding. If you need to get the row object, you can use  [`getRowByIndex`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxtreegridcomponent.html#getrowbyindex) grid API.
Here is a [sample](https://stackblitz.com/edit/github-vfyxrf?file=src/app/tree-grid-add-row-sample/tree-grid-add-row-sample.component.ts) where `TEST` button is logging the last record(if clicked after adding will return the added row object) to the console. If this does not resolve your issue, please, modify the attached sample and give more information of the behavior you are trying to achieve.
