### ISSUE TITLE
Is the IgxGridState directive supposed to honor the disableHiding column attribute?

### ISSUE THREAD

**Issue by ericmahlberg** [IgniteUI/igniteui-angular#9304]
## Question  
Looking at the documentation [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/state-persistence), I don't see anything that would dispute it.  I also tried to stackBlitz and Codesandbox links there but they seem to have an issue and are non-operable.

In my application, I have several columns set to disableHiding and that is honored when the state is not restored from the IgxGridState.  However, as soon as I setState, the columns are now hidable.

I notice that the JSON state payload does not contain 'disableHiding'

Is this by design or a bug?

 * igniteui-angular version: 11.x
 * browser: Chrome

**Comment by rkaraivanov** [comment]
@ericmahlberg 

Thank you for bringing up the broken sample!
As for the `disableHiding` property, it is by design, although I see no issue to actually save the state
of that property as well.

I will mark this as a feature request and push it into the codebase for the next release.

**Comment by ericmahlberg** [comment]
Can this be re-opened?
