### ISSUE TITLE
Column values in Excel Style Filtering dialog are sorted in case-sensitive order

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#9307]
## Description  
Column values in Excel Style Filtering dialog are sorted in case-sensitive order.

 * igniteui-angular version: 11.1.x
 * browser: any

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/grid-excel-style-filtering-columns-sort-order-1?file=src/app/grid/grid-excel-style-filtering-sample-1/grid-excel-style-filtering-sample-1.component.html)
2. Open the Excel style filtering dialog for any column.

## Result  
The column values in the list are sorted in a case-sensitive order - all uppercase letters before any lowercase letters. Example: "B", "a", "c".

## Expected result  
The column values in the list to be sorted in an ascending order, regardless of letter case. Example: "a", "B", "c".

## Attachments  
![image](https://user-images.githubusercontent.com/35433937/114181804-a16f7d00-994a-11eb-8565-eb526db832db.png)

**Comment by DiyanDimitrov** [comment]
We should sort the values in the Excel Style Filtering dialog using the same sort strategy of the grid/column.
