### ISSUE TITLE
Selection form controls missing required property

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#932]
### Description
The radio, checkbox, and switch form controls are missing the required property on them.

### Steps to reproduce

1. Include any of the aforementioned components in your app.
2. Add a required property on them.

### Result  
None of the underlying input elements reflect the required property.

### Expected result  
The underlying input fields should reflect the required property on the element.

**Comment by wnvko** [comment]
Required field is now working. However unchecking the checkbox does not change ng-invalid of the checkbox to ng-valid.

**Comment by simeonoff** [comment]
Closing this as it has been resolved with #949
