### ISSUE TITLE
Grid throws errors when filtering by a date if there's a custom formatter function applied

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#9338]
## Description 
If you have defined a custom formatter function, for a column of type `date` and you attempt to filter by that column, errors are thrown, however, the filter is still applied.

 * igniteui-angular version: 11.1.x, 12.0.x
 * browser: n/a

![advanced-filtering-err](https://user-images.githubusercontent.com/16020256/114884279-5358ee80-9e0e-11eb-9526-7679146112f4.gif)

## Steps to reproduce  

1. Open the following sample - [link](https://stackblitz.com/edit/github-dtbphh?file=src%2Fapp%2Fgrid%2Fgrid-advanced-filtering-sample%2Fgrid-advanced-filtering-sample.component.html)
2. Open the advanced filtering
3. Add a new group
4. Choose `Order Date` as a column.
5. Observe

## Result  
Errors are thrown.

## Expected result  
There are no errors.

**Comment by gedinakova** [comment]
@jackofdiamond5 This is actually an issue with the sample itself - the custom formatter doesn't check the input value validity. On selecting "Order Date" in the AF dialog, the date value given to the custom formatter is null and the `date.getDate()` portion is failing. Changing the formatter as follows resolves the issue:
```
public dateFormatter(date: Date): string {
    return date ? date.getDate() + " my date" : "";
  }
```
