### ISSUE TITLE
Migrations are failing for certain scenarios

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#9347]
## Description  
Member migration fails for the following scenario:

`event.grid.onSomeEvent.subscribe`

![image](https://user-images.githubusercontent.com/1182001/115053753-2416b000-9ee8-11eb-8df8-9138042bb3c6.png)

 * igniteui-angular version: 12.0.0
 * browser: 

## Steps to reproduce  

1. Build migrations for the following [PR](https://github.com/IgniteUI/igniteui-angular/pull/9326)
2. Apply those migrations in [samples ](https://github.com/IgniteUI/igniteui-angular-samples)repo
3. Open hierarchical-grid-custom-kb-navigation-sample.component.ts file

## Result  
`onGridKeydown` failed to migrate to `gridKeydown`

## Expected result  
`onGridKeydown` should migrate to `gridKeydown`
Scenarios like `event.grid.onSomeEvent.subscribe` should be migrated

**Comment by zdrawku** [comment]
While upgrading the angular-samples project to 12.1.0-alpha.1 version I've noticed that the migrations were applied only to the templates and not the .ts files as well.

Steps to reproduce:
- open igniteui-angular-samples project
- checkout to branch [test-migrations-before-12-1-0-alpha-1](https://github.com/IgniteUI/igniteui-angular-samples/tree/test-migrations-before-12-1-0-alpha-1)
- run `npm i igniteui-angular@12.1.0-alpha.1`
- run `ng g igniteui-angular/migrations/migration-collection.json:migration-21`

Observe the changes:
- template:
![image](https://user-images.githubusercontent.com/11193764/124876931-3712bb00-dfd3-11eb-8eb5-7961f31ed344.png)

- component:
![image](https://user-images.githubusercontent.com/11193764/124876903-2eba8000-dfd3-11eb-8261-0d311ae02c46.png)
