### ISSUE TITLE
Issue with IgxInputGroup type 'border'/'box' in IgxDialog

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#9367]
## Description  
When IgxInput with a type property set to 'border'/'box' is inside of IgxDialog component, the border is not displayed.

 * igniteui-angular version: 11.1.4
 * browser: Chrome

## Steps to reproduce  

1. open [this](https://stackblitz.com/edit/dialog-with-input-group-type-border?file=package.json) sample
2. open the dialog

## Result  
The border is not visible

## Expected result  
The border should be displayed like in the input group outside of the dialog

**Comment by phdufeil** [comment]
I also noticed the same behaviour problem in IgxExpansionPanel. More precisely in <igx-expansion-panel-body>.
