### ISSUE TITLE
Excel-style filtering and scrolling - igxOverlay.detach was called with wrong id:16

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#9426]
## Description  
Excel-style filtering dialog is closed on scrolling with the following error - igxOverlay.detach was called with wrong id:16

 * igniteui-angular version: should be reproducible with the alpha version before the fix that we did: 11.2.0-alpha.5
 * The fix that we implemented for the time being - https://github.com/IgniteUI/igniteui-angular/pull/9334/commits/59ec60b5bbc77190350a30c51497bca1a6cec086

## Steps to reproduce  

1. Open excel-style filtering and scroll down - warning is thrown and the dialog is closed
2. I am unable to open it afterwards

## Result  
igxOverlay.detach was called with wrong id:16

**Comment by DiyanDimitrov** [comment]
The fix is working fine, however I have made small adjustments like checking if closing animation has started and removing the focus call in the destroy.
