### ISSUE TITLE
Grid's pinRow method throws an error

### ISSUE THREAD

**Issue by astaev** [IgniteUI/igniteui-angular#9436]
## Description  
Grid's pinRow method throws an error

 * igniteui-angular version: 11.2.x
 * browser: any

## Steps to reproduce  

1. Open this [topic ](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-pinning)
2. Wait first sample to load

## Result  
An error is thrown in the console
ERROR TypeError: this.filteredSortedData is null

## Expected result  
No error

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by gedinakova** [comment]
@dkamburov This issue is still repoduced in IgxTreeGrid. getRowByKey is overridden there.
