### ISSUE TITLE
igx -grid - headers and cells are not properly aligned

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#947]
### Description  
Headers and cells are not properly aligned if width is not set on columns.

### Steps to reproduce  

1. Run the attached sample.
2. Observe igxGrid headers and cells.

### Result  
Headers and cells are not properly aligned - see the screenshot below.

### Expected result  
Headers and cells are aligned.

### StackBlitz sample
https://stackblitz.com/edit/grid-header-cell-misalignment

![igxgrid](https://user-images.githubusercontent.com/7972965/38564570-1129438c-3ce8-11e8-896f-7a402d500068.png)

**Comment by tiliev** [comment]
The issue is removed with removed width and height.

**Comment by SAndreeva** [comment]
@zdrawku , you can close the issue.
