### ISSUE TITLE
Multi-view calendar unnecessarily scrolls months

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#9473]
## Description  
Multi-view calendar scrolls to next month even if that month is already in the view

 * igniteui-angular version: all
 * browser: all

## Steps to reproduce  

1. Run dev demos
2. Open this [sample](http://localhost:4200/calendar) and scroll to the multi-view calendar
3. Inside for example **April** pick **first** of **May**

## Result  
The multi-view moves **April** outside of the view and sets **May** as a first calendar in the view.

## Expected result  
The multi-view should not move **April**  outside of the view and set **May** as the first calendar since **May** is already in the view.

**Comment by hanastasov** [comment]
What happens is the expected behavior by current design. Selecting the date marks the date as the `activeDate`, which determines which is the first month in the view.

Marking it with a feature-request.

**Comment by desig9stein** [comment]
@hanastasov Yes, that's what I meant.
