### ISSUE TITLE
[Firefox] - Click and Dragging to scroll also selects cells and and other unwanted behavior

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#9479]
## Description  
Scrollbar causes cell activation etc. 

 * igniteui-angular version: "11.1.4"
 * browser: FireFox

## Steps to reproduce  

1. Navigate to any grid sample in Firefox
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/virtualization

2. Vertical scroll but while doing so also hover over the grid cells

## Result  
Cells become active and horizontal scrolling occurs while vertical scrolling

## Expected result  
No grid interaction when scrolling

## Attachments  
![Demo](https://user-images.githubusercontent.com/17785923/117066906-56514b80-acf7-11eb-9e89-466055014845.gif)

**Comment by zdrawku** [comment]
Related to https://github.com/IgniteUI/igniteui-angular/issues/9259

**Comment by mddifilippo89** [comment]
What build should this be expected in for the customer to try out?
