### ISSUE TITLE
Ability to subscribe to igx-dialog close or afterClose event like MatDialog in Material Library

### ISSUE THREAD

**Issue by amrit-moomie** [IgniteUI/igniteui-angular#9480]
## Question  
I am trying to use igx-dialog component and see it quite different from what the **[MatDialog](https://material.angular.io/components/dialog/overview)** service does in Angular/Material. A Simple example [here](https://stackblitz.com/edit/angular-lcqyaj)

I am trying to dynamically load a FormComponent from a MainComponent and want to be able to subscribe to event like [afterClosed](https://material.angular.io/components/dialog/api) in MatDialog, that can give me the result from the FormComponent. Is there a way I can do this igx-dialog or igx-overlay ?

I could create my own service and inject it inside the FormComponent and subscribe to its event but I wasn't sure if there is anything inbuilt in the Infragistics component as this is a very common use case in Material design.

 * igniteui-angular version: any
 * browser: any

**Comment by wnvko** [comment]
@amrit-moomie 
`IgxDialog` is a component and not a service as `MatDialog` is. There is no way to pass a component to `IgxDialog`.
However, you may show a component in [`igxOverlay`](https://www.infragistics.com/products/ignite-ui-angular/angular/components/overlay) service. [`onClosed`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxoverlayservice.html#onclosed) event of the service provides access to the component shown in the service. This is where you can get the values of the form.
