### ISSUE TITLE
IgxGridState: Column width and hidden/visible state are not save and restored properly.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#9511]
## Description  
Column width and hidden/visible state are not save and restored properly.

 * igniteui-angular version: 11.1.10
 * browser: Chrome

## Steps to reproduce  

1. Click SAVE button.
2. Resize any column.
3. Hide any column.
4. Click RESTORE button.

## Result  
Column width and visibility are not restored

## Expected result  
Column width and visibility are restored.

## Attachments  
[igTest_mod.zip](https://github.com/IgniteUI/igniteui-angular/files/6464035/igTest_mod.zip)

**Comment by mkamiishi** [comment]
Columns order is not restored either.

Steps to reproduce
1.Run the attached sample igTest_mod_movable.zip.
[igTest_mod_movable.zip](https://github.com/IgniteUI/igniteui-angular/files/6499565/igTest_mod_movable.zip)
2.Move 'column4' between 'column2' and 'column3'.
2.Click SAVE button.
3.Move 'column4' back to the original position.
4.Click RESTORE button.

**Comment by hanastasov** [comment]
Thanks for the info Mihoko! This will be addressed too.

**Comment by hanastasov** [comment]
The grid `columnList`, which is manipulated when moving a column, when resetting grid columns collection from grid state, etc,. is resolved by a @ContentChildren collection, which is a dynamic query by Angular definiton. This means that this query is resolved after a change detection. Angular lists some of the most common issues with dynamic queries here, where we read:

> Code depending on a query result can suddenly stop working as soon as an *ngIf or an *ngFor is added to a template.

Angular claims to have made changes that resolved the issue in version 9, but everything explained in this article seems exactly what happens. Unfortunately I have been not able to reproduce this in a new isolated sample yet. There is also a difference in computations between Ivy and ViewEngine, this is why issue is only reproduced when Ivy is used. Stackblitz do not use Ivy by default, and the same samples work ok in Stackblitz.

Thus, I am suggesting to use the workaround that was recommended in #8129: use the columns template setter to assign templates:
```html
<igx-grid #grid1 [data]="data" height="400px" width="100%" [autoGenerate]="false">
  <ng-container *ngFor="let column of columns">
      <igx-column [field]="column.fieldKey" [header]="column.headerText" [dataType]="column.dataType"
           [headerTemplate]="headerTemplate"
          [cellTemplate]="cellTemplate" >
      </igx-column>
  </ng-container>
</igx-grid>

<ng-template let-value #cellTemplate>
  <div>{{ value }}</div>
</ng-template>
```
@mkamiishi , Please let us know if this is a feasible solution to the customer.

**Comment by mkamiishi** [comment]
The provided workaround looks good so far.
Thank you.
