### ISSUE TITLE
Multiple date and time pickers don't handle updates using reactive forms

### ISSUE THREAD

**Issue by DanielRose** [IgniteUI/igniteui-angular#9515]
## Description  

When multiple date pickers and/or time pickers are bound to the same model using ngModel, they all update when one of the pickers is used to change the value.

However, when using reactive forms, the updates are not handled by the other pickers: When one of the picker is used to change the value, the other pickers don't update. When a different picker is then used, it overwrites the value, but again the other pickers don't update. So when the date picker is used, it will use the original time, and when the time picker is used, it will use the original date.

 * igniteui-angular version: 11.1.10
 * browser: Chrome

## Steps to reproduce  

See the sameple at https://stackblitz.com/edit/github-s5szc1?file=src/app/datepicker-sample-2/datepicker-sample-2.component.html

1. Change the date & time using the "Direct binding" pickers => all pickers update
2. Change the date using one of the "Reactive forms" pickers => other pickers don't update; selected date/time is chosen date & original time
3. Change the time using one of the "Reactive forms" pickers => other pickers don't update; selected date/time is **original** date & chosen time

## Result  

When using reactive forms, the other pickers don't update. When using a date picker, it will always set the original time. When using a time picker, it will always set the original date.

## Expected result  

When using reactive forms, the other pickers should update. When using a date picker, it should use the time set by the time picker. When using a time picker, it should use the time set by the date picker.

**Comment by PlamenaMiteva** [comment]
Hi Daniel,
this is not a bug in the igxDatePicker or igxTimePicker components. Here is a sample (shttps://stackblitz.com/edit/angular-ivy-29oddp?file=src/app/app.component.ts) with two inputs bound to one and the same FormControl and as you can see changing the text in one of the inputs does not affect the text in the other. So, currently shared form controls are not supported by Angular (for reference see [bug](https://github.com/angular/angular/issues/10036)) and ngModel is the only option for them to be synced.

**Comment by DanielRose** [comment]
@PlamenaMiteva If you won't fix this bug, then please reopen and implement #9359. That issue was closed, saying that we are supposed to bind two controls to the same value (which doesn't work in reactive forms).
