### ISSUE TITLE
Product coverage is reduced with 10% after using karma parallel

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#9535]
Result:
https://coveralls.io/builds/39658339

Results on 12.0.x branch, without the karma parallel usage:
https://coveralls.io/github/IgniteUI/igniteui-angular?branch=12.0.x

**Comment by kdinev** [comment]
This is no longer reproducible and we didn't change anything for the issue to go away, so I consider it a coveralls issue.
