### ISSUE TITLE
igxGrid: Show-all and hide-all labels on the Column Hiding UI are not correct.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#9546]
## Description  
Label texts for show-all and hide-all buttons on the Column Hiding UI are not correct if JP resource is used.

 * igniteui-angular version: 11.1.10
 * browser: Chrome

## Steps to reproduce  

Run the attached sample.

## Result  
Hide-all button is labeled "すべて表示" and show-all button is labeled "すべて非表示".

## Expected result  
Hide-all button should be "すべて非表示", and show-all button should be "すべて表示".

## Attachments  
[igxGridG.zip](https://github.com/IgniteUI/igniteui-angular/files/6477930/igxGridG.zip)

**Comment by randriova** [comment]
This issue has been addressed in the following PRs: [67](https://github.com/IgniteUI/igniteui-angular-i18n/pull/67), [69](https://github.com/IgniteUI/igniteui-angular-i18n/pull/69), [70](https://github.com/IgniteUI/igniteui-angular-i18n/pull/70)

**Comment by Lipata** [comment]
@mkamiishi you can find the correct labels in the latest patches for each of the 10.2.x, 11.1.x, and 12.0.x versions: https://github.com/IgniteUI/igniteui-angular-i18n/releases.
