### ISSUE TITLE
Igx-grid row dragging animation

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-angular#9577]
## Is your feature request related to a problem? Please describe.
When re-ordering the grid rows using drag and drop, it's not clear where the dragged row will be moved to.

## Describe the solution you'd like
Could be perfect to add an animation that will make more understandable where the dragged row will be dropped, creating an empty space (removing graphically the the dragged row) and moving the others rows at drag over.
Check this image for reference:
![dd_animation](https://user-images.githubusercontent.com/70320904/118827696-e75e2000-b8bc-11eb-8d8e-e66c67308108.gif)

## Describe alternatives you've considered
An alternative way to accomplish this could be to draw a line in the middle of the rows, where the dragged row will be dropped.
For example:
![image](https://user-images.githubusercontent.com/70320904/118828030-32783300-b8bd-11eb-945b-44319f3eee09.png)

**Comment by loclv** [comment]
In my case, i'm using `igx-tree-grid`, so It will be so nice if other grid types have this feature too.

**Comment by Lipata** [comment]
There is an application scenario that is doing that. You can check it [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag#improving-ux-in-row-drag-scenarios). However this is still a valid feature request.
