### ISSUE TITLE
rowDragStart and rowDragEnd events are not fired in version 11.1.10

### ISSUE THREAD

**Issue by omanzelli** [IgniteUI/igniteui-angular#9580]
## Description  
The `rowDragStart` and `rowDragEnd` events are not fired in version 11.1.10

 * igniteui-angular version: 11.1.10
 * browser: Chrome

## Steps to reproduce  
Here a testing project
[https://stackblitz.com/edit/infragistics-rowdrag-not-fired](https://stackblitz.com/edit/infragistics-rowdrag-not-fired)
Check the logs in the console.

## Result  
The `rowDragStart` and `rowDragEnd` events are not fired.

## Expected result  
Start dragging a row, the `rowDragStart` event is fired. Dropping the row, the `rowDragEnd` is fired.
Installing the version 12, these events are fired properly.
This means that I need to migrate the project to Angular 12 to solve this issue.

## Attachments  
[https://stackblitz.com/edit/infragistics-rowdrag-not-fired](https://stackblitz.com/edit/infragistics-rowdrag-not-fired)
Check the logs in the console.

**Comment by hanastasov** [comment]
The events in 11.1.0 had the on prefix:
```html
    <igx-grid igxPreventDocumentScroll [data]="moonData" [primaryKey]="'name'" [rowDraggable]="true"
      (onRowDragStart)="onRowDragStart($event)" (rowDragEnd)="onRowDragEnd($event)">
```
