### ISSUE TITLE
Update V12 issues

### ISSUE THREAD

**Issue by DeniseCP** [IgniteUI/igniteui-angular#9582]
## Question  
I have a list of issues as a matter of fact.
we have several people that worked on the project and they used some functions and components that are no longer available on the library:

- IgxTabsGroupComponent: I cannot find it on the project anymore? Did you delete or just replace it?
- Tabs.transformContentAnimation: what is the new equivalent in version 12?
- Tabs.performSelectionChange: what is the new equivalent in version 12?
- For Date pickers, what should I use for version 12?
  - Date._updateValidityOnBlur();
  - Date.invalidDate = '';
  - .isEmpty = true;

 * igniteui-angular version: 12.0.0
 * browser: Chrome latest and Brave

**Comment by hanastasov** [comment]
`IgxTabs` and `IgxBottomNav` components were completely refactored in order to provide betters ways to define tab headers and contents. Please run `ng update` in order to migrate the existing `igx-tabs` and `igx-bottom-nav`definitions to the new ones.

**Comment by DeniseCP** [comment]
> `IgxTabs` and `IgxBottomNav` components were completely refactored in order to provide betters ways to define tab headers and contents. Please run `ng update` in order to migrate the existing `igx-tabs` and `igx-bottom-nav`definitions to the new ones.

I did. The project is using IgxTabsGroupComponent and that wasn't changed in the ng update command. And I cannot use the TabsGroupComponent here. Also I cannot find an equivalent for `tabItemSelected`

```  
@ViewChild('sidebarTabs', { read: IgxTabsComponent })
  public sidebarTabs: IgxTabsComponent;

...


  public ngAfterViewInit() {
     this.sidebarTabs.tabItemSelected
      .pipe(takeUntil(this.unsubscribe$))
      .subscribe((e: { tab: IgxTabItemComponent; group: IgxTabsGroupComponent }) => {
        this.isHistoryTabMode = e.group.index === this.HISTORY_TAB_INDEX;
      });
  }```

**Comment by hanastasov** [comment]
> Another issue I run into is regarding adding rows.
> `this.grid.getRowByIndex(index).beginAddRow();`
> I used this to add a new row to the bottom of my grid programmatically, and when adding open so the user could edit right away, but now is no longer available and
> `this.grid.addRow({});` doesn't open the row to edit

See this https://github.com/IgniteUI/igniteui-angular/issues/9429#issuecomment-826932832

**Comment by Lipata** [comment]
@DeniseCP, excluding #9429, do you still have some issues when migrating to v12.0.0?
