### ISSUE TITLE
Column moving does not work if a template contains NgSwitch.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#9583]
## Description  
Column moving does not work if a template contains NgSwitch.

 * igniteui-angular version: 11.1.10
 * browser: Chrome

## Steps to reproduce  
1.Run the attached sample.
2.Try moving a column.

## Result  
Column cannot be moved.

## Expected result  
Column should be movable.

## Attachments  
[igxGrid.zip](https://github.com/IgniteUI/igniteui-angular/files/6513063/igxGrid.zip)

**Comment by mkamiishi** [comment]
*ngIf has the same problem.
Please test with the attached sample as well.
[igxGrid2.zip](https://github.com/IgniteUI/igniteui-angular/files/6519385/igxGrid2.zip)

**Comment by hanastasov** [comment]
@mkamiishi, could you please confirm, if column moving works inside the pinned columns table and does Not work inside the unpinned columns? At least this is the behavior on my side.

**Comment by mkamiishi** [comment]
@hanastasov 
Yes, I see column moving does work within the pinned columns area.
It does not work inside the unpinned columns area.

**Comment by hanastasov** [comment]
Thanks @mkamiishi! I am currently investigating it. The issue boils down to a way the columnList is manipulated when column moving and when resetting grid state.

Same as #9511, #8896 
Quite Similar to #8129

#8129 is will probably work for #9511 and #8896 too, will confirm later. Will also investigate why those issues do not reproduce in pinned columns table and in StackBlitz example too.

**Comment by gedinakova** [comment]
@hanastasov Hristo, I believe #9410 can be linked here, too. The only difference we found to stackblitz (where the issue is not reproducible) was ivy. Hope this helps.

**Comment by hanastasov** [comment]
> @hanastasov Hristo, I believe #9410 can be linked here, too. The only difference we found to stackblitz (where the issue is not reproducible) was ivy. Hope this helps.

Thanks!

**Comment by hanastasov** [comment]
The grid `columnList`, which is manipulated when moving a column, when resetting grid columns collection from grid state, etc,. is resolved by a @ContentChildren collection, which is a dynamic query by Angular definiton. This means that this query is resolved after a change detection. Angular lists some of the most common issues with dynamic queries here, where we read:

> Code depending on a query result can suddenly stop working as soon as an *ngIf or an *ngFor is added to a template.

Angular claims to have made changes that resolved the issue in version 9, but everything explained in this article seems exactly what happens. Unfortunately I have been not able to reproduce this in a new isolated sample yet. There is also a difference in computations between Ivy and ViewEngine, this is why issue is only reproduced when Ivy is used. Stackblitz do not use Ivy by default, and the same samples work ok in Stackblitz.

Thus, I am suggesting to use the workaround that was recommended in #8129: use the columns template setter to assign templates:
```html
<igx-grid #grid1 [data]="data" height="400px" width="100%" [autoGenerate]="false">
  <ng-container *ngFor="let column of columns">
      <igx-column [field]="column.fieldKey" [header]="column.headerText" [dataType]="column.dataType"
           [headerTemplate]="headerTemplate"
          [cellTemplate]="cellTemplate" >
      </igx-column>
  </ng-container>
</igx-grid>

<ng-template let-value #cellTemplate>
  <div>{{ value }}</div>
</ng-template>
```
@mkamiishi , Please let us know if this is a feasible solution to the customer.

**Comment by mkamiishi** [comment]
The provided workaround looks good so far.
Thank you.
