### ISSUE TITLE
Tree: broken Stackblitz examples

### ISSUE THREAD

**Issue by danielsogl** [IgniteUI/igniteui-angular#9592]
## Description  

All examples for the new introduced tree component are broken.

For example: https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/lists/tree-basic-sample

 * igniteui-angular version: 12

## Expected result  

Stackblitz examples should work for the tree component

**Comment by kdinev** [comment]
I tried changing the igniteui-angular version to 12.0.1 and the sample loaded. Could you verify that it loads on your end as well?

https://stackblitz.com/edit/github-uwpcfg-jbf5hj?file=package.json

**Comment by danielsogl** [comment]
Now it's working 👍
