### ISSUE TITLE
Tree: nested objects

### ISSUE THREAD

**Issue by danielsogl** [IgniteUI/igniteui-angular#9593]
## Is your feature request related to a problem? Please describe.

The tree component should handle nested objects with more then one level of children.

## Describe the solution you'd like

```ts
export interface DummyData {
  name: string;
  children?: DummyData[];
}
```

## Additional context

Currently the user have to write duplicated code to handle nested objects.

**Comment by kdinev** [comment]
@danielsogl This is a side effect of an issue in the Angular framework. We have reflected this through the [known issues and limitations](https://www.infragistics.com/products/ignite-ui-angular/angular/components/tree#known-issues-and-limitations) and more details can be found here:

https://github.com/IgniteUI/igniteui-angular/wiki/Tree-Specification#recursive-template-nodes
