### ISSUE TITLE
Need to have soft delete feature in igx-tree-grid. It should change a row flag status instead of deleting row permanently.

### ISSUE THREAD

**Issue by anmolpadit30** [IgniteUI/igniteui-angular#9623]
## Is your feature request related to a problem? Please describe.
In our use case, we need to have the deleted items as well in the same data structure which can have flag status as deleted, because we have ML algorithms that need to learn the unnecessary items for future reference.

currently, the delete icon available on the action strip editing action deletes the whole row permanently from the data structure. and it is very costly to fetch the whole data again from DB just to check the deleted items as the dataset is very large.

## Describe the solution you'd like
the expected solution can be providing an option to the tree-grid as softDelete = true/false. so when it is true it will change a flag status to deleted and auto filter out the table with the deleted row status. and the row should still be present in the data structure.
another solution can be given an option to remove the existing delete icon from the action strip editing action. and enabling users to write custom delete logic.

## Describe alternatives you've considered
The alternative workaround we have considered is hiding the editing action delete icon and adding another custom delete button that enables the writing custom delete function.

**Comment by kdinev** [comment]
@anmolpadit30 Which transaction service are you currently providing to the tree grid? If it's the base one, then there will be no transactions and editing actions will be auto-commit.

For reference of the different out-of-the-box transaction services provided by the package: https://www.infragistics.com/products/ignite-ui-angular/angular/components/transaction

Reference for deferred editing transactions (batch updates): https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/batch-editing
