### ISSUE TITLE
Editable cell styling support

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#9630]
## Is your feature request related to a problem? Please describe.
When having a grid with a lot of columns, it can be tricky for the user to easily determine which columns are editable (when in row edit mode). 

## Describe the solution you'd like
The ability to style the background color of editable cells to a different color than non-editable (read-only) cells.

**Comment by StefanIvanov** [comment]
@Eralmidia thanks for logging this request. Would you say that a style for the text of editable/non-editable cells for the row under edit mode at the moment would work for you as well. Imagine the most simple scenario where cells belonging to non-editable columns have a disabled-style text, while editable ones have a more active look i.e. the current style used for all cells on the edited row?

**Comment by Eralmidia** [comment]
@StefanIvanov Yes, absolutely, that would work fine as well 👍

**Comment by StefanIvanov** [comment]
We have updated the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Editing#row-editing) and will be able to start implementing the design

**Comment by Eralmidia** [comment]
Looks good 👍 One related question about editing: In the spec, the edited field has an underline, like the input fields does. 
![image](https://user-images.githubusercontent.com/12936286/121178942-5f39bd80-c85f-11eb-9888-f38674753880.png)

This doesn't seem to be the default. Is there a setting for this, or are you using custom templates with igx-inputs?

**Comment by StefanIvanov** [comment]
I noticed this too, the spec needs updating that removes that underline since it is outdated now :)

**Comment by Eralmidia** [comment]
@StefanIvanov Just a thought on this one. While the solution of disabled looking text works for row editing, it wouldn't help much in a "Add row scenario", where no fields are already filled out. In that case, something like editable background colors might have been better. Don't know if this is a scenario you have considered?

**Comment by StefanIvanov** [comment]
@Eralmidia we will discuss this scenario internally, the reason we wanted to avoid using the background was because of a number of other features that do so such as selection, active cell, and conditional cell styling, where people often define background styles based on the value in a cell.

**Comment by StefanIvanov** [comment]
Reopening this issue in order to propagate the changes to the row adding scenario 
@desig9stein
