### ISSUE TITLE
Issue with double click on a cell in a new row 

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#9637]
## Description  
Double click on a cell in a new row when it is already in edit mode is adding the row to the grid and put it in edit mode again.

 * igniteui-angular version: 11.1.4

## Steps to reproduce  

1. open [this](https://stackblitz.com/github/zzmiovyaa?file=src/app/app.component.ts) demo
2. add a new row via action strip
3. double click on the new row's cell that is in edit mode

## Result  
The row is added to the grid and again put in edit mode

## Expected result  
Nothing should happen on double click like the behaviour when double-clicking on any cell in a row from the data.

**Comment by radomirchev** [comment]
@teodosiah the issue is included in the next sprint planning. You could expect the fixe to be included in the patch scheduled for 06 Jul.
