### ISSUE TITLE
IgxDialogComponent API - Inputs and labels in a sample code need to be wrapped in <igx-input-group> 

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#9639]
## Description  
IgxDialogComponent API - Inputs and labels in a sample code need to be wrapped in <igx-input-group> 

 * igniteui-angular version: 12.0.0
 * browser: NA

## Steps to reproduce  

Observe the sample code on the top of the following pages:
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdialogcomponent.html
https://jp.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdialogcomponent.html

## Result  
Inputs and labels are not wrapped in `<igx-input-group>`.

```html
<button (click)="form.open()">Show Dialog</button>
<igx-dialog #form title="Sign In" rightButtonLabel="OK">
  <div>
    <input type="text" igxInput/>
    <label igxLabel>Username</label>
  </div>
  <div>
    <input type="password" igxInput/>
    <label igxLabel>Password</label>
  </div>
</igx-dialog>
```

## Expected result  
Inputs and labels are wrapped in `<igx-input-group>`.

**Comment by kdinev** [comment]
@mkamiishi It's not a must to use an `igx-input-group` as content. The `igx-input-group` will just provide homogeneous theming for the inputs, but purely from an API perspective, the example seems perfectly valid.

**Comment by mkamiishi** [comment]
@kdinev
I receive NullInjectorError without `<igx-input-group>`.
https://stackblitz.com/edit/github-ejqwwk-6doagc?file=src/app/input-group-sample-1/input-group-sample-1.component.html
Is this possibly a product bug?

**Comment by wnvko** [comment]
Adding `igxInput` to the `input` requires `igx-input-group`. There is no reason to add `igxInput` without `igx-input-group`, and if you do so you get NullIngectorError. We should fix the documentation with either adding `igx-input-group` or removing `igxInput` directive.

**Comment by kdinev** [comment]
@mkamiishi I totally didn't notice the applied `igxInput` on the input. This is wrong and @wnvko has already PRed fixes :)

**Comment by mkamiishi** [comment]
@kdinev @wnvko 
Thank you for dealing with this promptly.

**Comment by kdinev** [comment]
@wnvko This should have been PRed to `11.1.x` and not `11.2.x`. Please make a new PR to `11.1.x`, as `11.2.x` is not an official branch we support.
