### ISSUE TITLE
Gridscroll on row drag

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#9660]
## Is your feature request related to a problem? Please describe.
Seems like when you drag a row to the bottom of the grid, it doesn't scroll down. This severly limits the usability of row drag for instance when using drag & drop in a tree grid too move a row from one parent to another.
![image](https://user-images.githubusercontent.com/12936286/120788973-46fd3200-c531-11eb-8334-883afbae728b.png)

## Describe the solution you'd like
If a row is dragged to bottom or top of the scroll area of the grid, it should scroll up or down.

**Comment by dafo** [comment]
@Eralmidia can you please take a look at [this example](https://stackblitz.com/edit/all-your-memory-belongs-to-chrome), demonstrating how this functionality may be achieved.

**Comment by Eralmidia** [comment]
Got it to work, thanks!

Still, I feel that the feature request should stand, as this is something which would be very nice to have built into the grid.

**Comment by loclv** [comment]
I had the same issue.

feature request + 1 :smile:

**Comment by dafo** [comment]
FYI - The Grid Row Drag documentation is now updated to cover this scenario - https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag#improving-ux-in-row-drag-scenarios
