### ISSUE TITLE
Reactive Forms make input invalid when form Control is invalid

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-angular#9667]
## Is your feature request related to a problem? Please describe.

Reactive Forms IgxDatePickerComponent and others:

When the form control is required and dirty&touched the validation should highlight the element in Red

## Describe alternatives you've considered

   this works         [class.igx-input-group--invalid]="filterFormGroup.touched && filterFormGroup.get('endDate').errors"

**Comment by jackofdiamond5** [comment]
Hi @ricardosaracino, can you specify the version of `igniteui-angular` that you're currently using? After `11.2` there shouldn't be any issues with updating the validity of the input. You can look at the [Reactive Forms Demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/input-group-reactive-forms) just to verify.

Additionally, if you're trying to manually update the `touched` or `dirty` properties through API methods, this will currently not reflect on the styling of the input. The workaround for this is to call `updateValueAndValidity` after you've updated the properties. More on this can be found here - https://github.com/IgniteUI/igniteui-angular/issues/6434.
