### ISSUE TITLE
Transaction service should have knowledge about component it works with

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#9671]
## Is your feature request related to a problem? Please describe.
Right now transaction service could be provided as DI to a component, module or application. However when transactions are logged they are not logged per component. If you log transaction for several components in one instance of transaction service transaction could interfere and break the state of the components, and if such state is committed it could break the data.  

## Describe the solution you'd like
Transaction service should handle transactions per component.

**Comment by Lipata** [comment]
The implementation in #9672 makes this feature unnecessary.
