### ISSUE TITLE
Page scroll to the top on changing the page

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#9704]
## Description  
When changing the page of IgxGrid, which height is not set, the browser's scrollbar is scrolled to the top.

 * igniteui-angular version: 12.1
 * browser: Chrome, Mozilla

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/srollable-igx-grids-one-page-rdavab?file=src/app/app.component.ts) sample in new window
2. Scroll the browser scrollbar to the bottom
3. Go to the second page of the second grid

## Result  
The page is scrolled back to the top

## Expected result  
The scrollbar position should not be changed

**Comment by cis-ns** [comment]
This seems to be a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/9705

You should also remove `[height]="'600px'"` in order to reproduce properly

**Comment by radomirchev** [comment]
@teodosiah , please check if the issue is duplicated and if so, please close it.

**Comment by teodosiah** [comment]
Closing cause it is duplicate of #9705
