### ISSUE TITLE
Tree Gird Batch Editing sample doesn't work properly with multiple row changes.

### ISSUE THREAD

**Issue by onlyexeption** [IgniteUI/igniteui-angular#9755]
### Description  
Tree Gird Batch Editing sample doesn't work properly when there are multiple row changes.

### Steps to reproduce  

1. Open Tree Gird Batch Editing sample - https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/vNext/angular-demos/tree-grid/treegrid-batchediting
2. On the first entry, edit a cell and click done
3. Edit another cell for the same entry and click done

### Result  
The second change is not applied, however it shows that there are 2 changes made. After commit, only the first change is applied.

### Expected result  
All changes should be applied

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by kdinev** [comment]
Is this fix only applicable to `12.0.x`?

**Comment by zhosti** [comment]
No, it is applicable also for the other versions. We will make PRs for the other versions as well.
