### ISSUE TITLE
While adding row cannot switch to another cell unless there is a change in the current cell

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular#9762]
## Description  
When adding new row, it is not possible to switch between cells unless there is a change in the current cell.
 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Go to add row dev sample
2. Add a new row
3. Without making any change, try to switch between cells

## Result  
It is now possible

## Expected result  
To be possible

## Attachments  
![addrow](https://user-images.githubusercontent.com/37667452/122730049-7aa2c080-d282-11eb-83b7-c9b19efc82b5.gif)

**Comment by ChronosSF** [comment]
@Aleksandyr , this seems to be a critical regression from https://github.com/IgniteUI/igniteui-angular/pull/9476
