### ISSUE TITLE
IgxTabs not rendering with dynamic/asynchronous router-outlet

### ISSUE THREAD

**Issue by remshams** [IgniteUI/igniteui-angular#9765]
## Description  
This bug seems to be related to the one already fixed in the [DataGrid](https://github.com/IgniteUI/igniteui-angular/issues/8071).

Quick summary: The `IgxTabs` do not render when integrated into a page that gets asynchronously/dynamically rendered in a `router-outlet`.

This [respository](https://github.com/remshams/igx-tabs-issue) showcases the issue. After clicking on the login button the error added to the Attachments section occurs.

 * igniteui-angular version: 12.0.4
 * browser: Chrome (91.0.4472.106), Firefox (89.0.1)

I have opened a [PR](https://github.com/IgniteUI/igniteui-angular/pull/9766) which should fix the issue. Please let me know if I should change something or if you prefer to do the changes yourself

## Steps to reproduce  

1. Start the example application from the master branch
2. Open the DevConsole in Chrome/Firefox
3. Click on "Login"

## Result  
The page does not render and instead an error is shown in the console.

The reasons seems that `ngOnDestroy` is called but `ngAfterViewInit` is not. For that reason `_resizeObserver` not being assigned/setup properly leading to the error shown below.

## Expected result  
Page/Tabs should render.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![igx-tabs-disconnect](https://user-images.githubusercontent.com/10899354/122749917-30bfd780-d28e-11eb-8fd7-9ff8d36be652.png)

**Comment by kdinev** [comment]
@remshams Thanks for submitting and fixing this!

**Comment by kdinev** [comment]
@remshams Just FYI, your fix will be available in `12.0.6` next Monday.

**Comment by remshams** [comment]
> @remshams Just FYI, your fix will be available in `12.0.6` next Monday.

@kdinev Thanks for the info and speedy release.

**Comment by remshams** [comment]
@kdinev Do you happen to you know in which version the fix will be released. If we are not mistaken it has not been included in version `12.0.6` and `12.0.7`.

**Comment by zdrawku** [comment]
hi @remshams, as I see the fix is included in version 12.0.6 - https://github.com/IgniteUI/igniteui-angular/releases/tag/12.0.6

**Comment by remshams** [comment]
My bad, completely missed it in the release notes.
Thanks for the speedy response and sorry for the hassle, I should have looked at the notes more carefully.

**Comment by zdrawku** [comment]
all good, I just double checked and your changes are definetely part of 12.0.6 so just go ahead and update to it. Thank you again for your contribution 🚀
