### ISSUE TITLE
IgxHierarchicalGrid - Checkbox ‘checked’ state is rest when a row is expanded.

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-angular#9781]
## Description  
Checkbox ‘checked’ state is rest when a row is expanded.
This happens after reloading the data source.

 * igniteui-angular version: 12.0.5
 * browser: Chrome
 
## Steps to reproduce  

1.	Run the attached sample igxHGrid.zip.
2.	Click ‘LOAD’ button.
3.	Expand the second row.
4.	Click ‘RELOAD’ button.
5.	Expand the second row.
6.	Check any checkbox on the child grid.
7.	Expand the parent grid’s first row .

## Result  
Checkbox is unchecked.

## Expected result  
Checkbox is unchanged.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

[igxHGrid.zip](https://github.com/IgniteUI/igniteui-angular/files/6698366/igxHGrid.zip)

**Comment by mddragnev** [comment]
Hello @mkamiishi,
A workaround for your specific scenario is to set a primary key to the root grid, please make sure that it has a unique value.
I will continue to investigate the issue.

**Comment by mkamiishi** [comment]
Hi @mddragnev ,
I have verified that setting a primary key to the root grid resolves the issue.
Thank you.
