### ISSUE TITLE
Some of the unpinned columns are not visible, when the grid doesn't have any "width" set

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#979]
### Description  
In the Grid Column Pinning Demo when the "width" of the grid has not been set, not all of the unpinned columns are visible.

### Steps to reproduce  

1. Open branch 5.3.x
2. Remove the "width" input of the grid
3. Open the Grid Column Pinning demo

### Result  
Not all of the unpinned columns are visible

### Expected result  
The grid should be fully visible.

### Attachments  
![sketch2](https://user-images.githubusercontent.com/18643062/38689886-63038354-3e85-11e8-9f47-567926fd4c43.png)

**Comment by simeonoff** [comment]
@skrustev @ChronosSF Is this issue not related to the virtualization behavior? Is the problem not that the horizontal scroll is not being shown rather that there's something off with the CSS?

**Comment by ChronosSF** [comment]
@PavlovVasil , try to remove the nav-drawer from the demos and see if this reproduces.
