### ISSUE TITLE
Dart-Sass deprecation warnings

### ISSUE THREAD

**Issue by danielsogl** [IgniteUI/igniteui-angular#9793]
## Description  

After the latest Angular-CLI update (12.1.0) some sass compilation depreaction warnings are shown in the build log.

```sh
WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($pixels, $context)

More info and automated migrator: https://sass-lang.com/d/slash-div

@return ($pixels / $context) * 1rem;
```

 * igniteui-angular version: latest

## Steps to reproduce  

1. Create a new Angular project with core and cli version 12.1
2. install infragistics for angular
3. run build

## Result  

The described error message will be displayed in the build log

## Expected result  

Change the deprecated way to divide values in sass

## Attachments  

 https://sass-lang.com/d/slash-div

**Comment by simeonoff** [comment]
@danielsogl We are currently switching to dart-sass in [this PR]( #9579). This issue will be fixed once we merge this PR and move our build scripts to a newer version of dart-sass.

**Comment by simeonoff** [comment]
Closing as of version 12.1 those deprecation warnings will not be present. This also means that starting with version 12.1 of igniteui-angular `dart-sass` is required and `node-sass(libsass)` will no longer work for compiling our Sass themes.
