### ISSUE TITLE
Get edit value on cell edit

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#9794]
## Question  
I have a scenario with a grid with row selection where the validation of two columns are dependent on each other. Basically, if you enter data into column A, column B should be cleared and vice versa. I'm using the cellEditExit to trigger the validation. When doing a row edit this is not an issue, because the event includes the current rowData. However, when using the add row (using row.beginAddRow()) the rowData is undefined (which of course is correct, since the row isn't added yet). However, the cellEditExit event doesn't include the current edit value of the row, so I can no longer compare the data of the cells in column A and B. How can I acquire the current edit value?

 * igniteui-angular version: 10.2
 * browser:

**Comment by kdinev** [comment]
I believe this is related to #9792

**Comment by Eralmidia** [comment]
@kdinev Thanks, looks like you are on top of this then. We have been a bit confused as to how to use the data in the events, and getting the expected data from oldValue, newValue og rowData regardless of whether it is adding or editing would be very nice.
