### ISSUE TITLE
igx-grid - summary row can't be horizontally scrolled with igniteui-angular@5.3.0-beta.1

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#980]
### Description  
With igniteui-angular@5.3.0-beta.1, summary row can't be horizontally scrolled.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-summary-issue
2. Grab horizontal scrollbar and move it to the right and left.

### Result  
Header and data rows can be scrolled. summary row can't be scrolled.

### Expected result  
Summary row should be able to be scrolled as well.

By the way, with igniteui-angular@5.3.0-beta.0, there was no problem. It seems a regression bug.

**Comment by kdinev** [comment]
@tkiryu This has been fixed in beta 3.
