### ISSUE TITLE
ESF for TreeGrid Groups column

### ISSUE THREAD

**Issue by astaev** [IgniteUI/igniteui-angular#9809]
Related to #9184

## Description  
ESF for treeGrid Groups column

 * igniteui-angular version: 12.1.x
 * browser: any

## Steps to reproduce  

1. Open treeGrid groupBy dev demo
2. Open ESF for Groups column
3. Deselect all, select any item from the list

## Result  
Only the group records is displayed
![image](https://user-images.githubusercontent.com/44602698/123931498-3c4f8480-d999-11eb-90b2-213df1f311f2.png)

## Expected result  
Show the group record and its tree grid rows

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by StefanIvanov** [comment]
@YoannaIvanova and I will look into this issue next sprint and do a bit of research because I understand it but the whole ESF on a tree grid that has group by throws me off a bit :)
