### ISSUE TITLE
igx-grid - summary cells of "number" or "date" are cut off when they come up after being horizontally scrolled.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#981]
### Description  
Summary cells of "number" or "date" are cut off when they come up after being horizontally scrolled.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-summary-issue2
  Due to #980, this issue can't be demostrated with @5.3.0-beta.1., so this sample uses @5.3.0-beta.0.
2. Grab horizontal scrollbar and move it to the right.

### Result  
Summary cells of "number" or "date" are cut off.

### Expected result  
Summary cells of "number" or "date" should not be cut off. In other words, igx-grid should have enough height of summary row at initial rendering.

**Comment by zdrawku** [comment]
I am currently testing this behavior with the latest version.

**Comment by zdrawku** [comment]
Fixed in 5.3.x-beta.3 - [example](https://stackblitz.com/edit/igx-grid-summary-example?embed=1&file=app/app.component.ts&view=preview)

**Comment by tkiryu** [comment]
@zdrawku , It works as I expect! Thank you!
