### ISSUE TITLE
Calcmanager/formulaeditor controls

### ISSUE THREAD

**Issue by jaencalo** [IgniteUI/igniteui-angular#9817]
## Is your feature request related to a problem? Please describe.
Hi, I am Javier Carreño, from Bogota, Colombia. I have been using the infragistics suite since 2010 and have been a registered customer since 2013. I have developed 28+ business applications in the last 11 years, all using Infragistics controls, in Silverlight, Winforms and wpf. In them, I used extensively the calcmanager control to provide user-friendly formulations, including custom functions, statistical functions, big formulas with many "If" sentences, screens with thousands (not hundred, thousands) controls with calcmanager/calcsettings for complex calibration/laboratory calculations, etc. I decided migrate the silverlight applications to Asp.NetCore (+Angular) and I assumed that the calcmanager would be available in Infragistics suite... and, after checking, I found that these controls are available, but in aspnet web forms, not in AspNetCore or Angular...

## Describe the solution you'd like
Please, Include calcmanager engine and formula editor controls for AspNetCore or angular control sets.

## Describe alternatives you've considered
I asked to forums looking for alternatives, without sucess... I asked if I could use somehow the infragistics calculation manager of asp.net web forms on AspNetCore or If is available the source code to migrate to JavaScript/Typescript, or any other alternative, but they only referred me to feature request (here)

## Additional context
After reviewing your competitors, I found that none of them provide these types of controls. No Telerik, No ComponentOne, No devexpress, No syncfusion offers something similar, focusing on UI and forgetting things necessary for the construction of scientific applications

So, thanks for reading this and I appreciate you could consider including these controls in future versions of aspnetcore from Infragistics

Best regards, Javier Carreño, From Bogota, Colombia

**Comment by radomirchev** [comment]
Hi @jaencalo ,

 Thank you for the request. I am Product Owner of Ignite UI for Angular and Design-to-Code in Infragistics. I would review the priority of your request and could give update when we could start on the feature request, next week.

 P.S> Are you familiar with the new product of Infragistics - App Builder : (Indigo.Design App Builder)[https://www.infragistics.com/products/indigo-design/app-builder]? Please, contact me at Rmirchev@infragistics.com if you would like to receive exclusive opportunities for the new product.
