### ISSUE TITLE
Unable to see data in the grid for columns which contains "." in the column name

### ISSUE THREAD

**Issue by nnalmas** [IgniteUI/igniteui-angular#9822]
## Is your feature request related to a problem? Please describe.
I am unable to see data in the igx-grid even if there is data for that column. I am having "." in the column name. The reason for such behavior is expected since a field name with a dot in it is considered as a path and after it cannot be resolved the data is not populated correctly.

## Describe the solution you'd like
I should be able to see the data in the igx-grid even if there is "." in the column name.

## Describe alternatives you've considered
As an alternative we have removed "." in our column name. But it is difficult for us we are fetching the columns dynamically.

## Additional context

![Capture1](https://user-images.githubusercontent.com/86729950/124545775-3fd68600-de47-11eb-8745-50e33884bff9.PNG)
![Capture2](https://user-images.githubusercontent.com/86729950/124545777-3fd68600-de47-11eb-8188-e2fc027d0d8b.PNG)

**Comment by zdrawku** [comment]
hey @nnalmas, a dot in between field names indicates a _property hierarchy_ when it comes to the **igxGrid**. We consider this as [complex data binding](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid#complex-data-binding) - binding to a complex objects through a _path_ of properties in the _data record_. My suggestion is to preprocess your JSON file to remove/replace the dot or consider using custom template for the column, and configure it to render the data - check out the [complex data binding](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid#complex-data-binding) section for more information about that.

**Comment by nnalmas** [comment]
Hello zdrawku,

We are doing it in the same way. Below is the similar data we are using to bind data for columns. But we are unable to see the data.

0: Details
CName: "Condition1"
PunderC: Array(28)
0: {name: "abc16/1.2xyz"}
1: {name: "abc24/2.2 pqr"}
2: {name: "abc12/0.32 pqr~st"}

Thanks,
Nithya.

**Comment by zdrawku** [comment]
If the "." is part of the value and not the field name then everything should be alright. Could you please share with me a sample that is showing the problem that you experience?

**Comment by zdrawku** [comment]
What about the Grid template definition and actual binding, could you please share that as well?
