### ISSUE TITLE
Freezing Columns/Rows on Export to Excel (Angular)

### ISSUE THREAD

**Issue by chris-work** [IgniteUI/igniteui-angular#9863]
## Is your feature request related to a problem? Please describe.
When exporting a report generated in igx-grid, users would like to have the same features/styling/frozen panes when it is exported to Excel.

## Describe the solution you'd like
My preference is for something static/automatic (reads current styling/frozen panes within the existing grid), but something that is dynamic (options to be set in IgxExcelExporterOptions) would also work.

## Describe alternatives you've considered
As far as I know, there is no alternative, other than users manually persisting styling/frozen panes into the downloaded template.

## Additional context
For my case, it applies to large data sets, so it's important to have "pinned" columns and column headers visible at all times.

**Comment by MonikaKirkova** [comment]
We are going to expose header freezing option, which would be included in the IgxExcelExporterOptions.
Additionally, exporting igx-grid with pinned columns is currently supported. The following sample demonstrates this functionality.
https://stackblitz.com/edit/igx-grid-pinned-columns-export?file=src/app/app.component.ts
