### ISSUE TITLE
Additional white space appears under the vertical scrollbar in Grid Performance sample

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular#988]
### Description  
There is an additional white space (looks like an additional part of row) at the end of the table content in Grid Performance sample
**Note: It seems that this behavior is observed only on mixed environment**

### Steps to reproduce  

1. Open Grid Performance sample
2. Look at the end of the vertical scrollbar (under the table content)

### Result  
Additional white space

### Expected result  
No additional white space and I assume that the vertical and horizontal scrollbars should look like the attached screenshot
![screenshot-2018-4-13 screenshot](https://user-images.githubusercontent.com/12935806/38733521-cc8118f0-3f2a-11e8-8e28-762feee3d104.png)

**Comment by SlavUI** [comment]
This seems to be resolved in the new sample visible on the site
