### ISSUE TITLE
Overlay wrapper animation should start together with overlay element animation

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#9882]
## Is your feature request related to a problem? Please describe.

Overlay wrapper animation should start together with overlay element animation. In cases where animation duration is bigger, it is obvious that the wrapper animation is starting after the animation of the element is finished (see igx-dialog's closing animation):

![overlay_anim_demo](https://user-images.githubusercontent.com/2621802/126171271-2ac85db0-8213-4218-aadc-1ea791f05a01.gif)

The closing animation in Material:

![117975646-8e7c0e00-b337-11eb-805c-8965ce95ecd0](https://user-images.githubusercontent.com/2621802/126171541-7bfbf23f-2dd2-44ea-95d5-6642d04472f0.gif)

**Comment by wnvko** [comment]
this was working in old version and regressed with addition of `attach` and `detach` methods
