### ISSUE TITLE
IgxGrid: Visibility issue with Column Pinning/Hiding overlay

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#9883]
## Description  
I have an issue with the Column Pinning/Hiding overlay.

 * igniteui-angular version: 12.0.9
 * browser: Chrome

## Steps to reproduce  

see https://stackblitz.com/edit/github-7hixdh

Open the Column Pinning Menu.

## Result  
The overlay is hidden under the second grid.

## Expected result  
The overlay should be above the second grid.

## Attachments  
![image](https://user-images.githubusercontent.com/46870283/126182926-9b5fc324-3c26-4a91-b79e-572b82ee659a.png)

**Comment by zdrawku** [comment]
For the time being my suggestions would be to override grid's `z-index`. I saw that you set ViewEncapsulaiton to None which means that updating the .scss file with the code below, would be enough, [updated sample](https://stackblitz.com/edit/github-7hixdh-jijtuf?file=src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.scss):

```scss
.igx-grid {
    z-index: unset;
}
``` 

As for the z-index part of the grid, @simeonoff or @wnvko could you please ellaborate why we need to use it? As I checked, there are no other grid elements that could go on top of the grid if we simply remove it:

![image](https://user-images.githubusercontent.com/11193764/126298016-19fd0cb3-00ab-4b97-a265-f425cecfe0e1.png)

**Comment by wnvko** [comment]
Looking at the [issue](https://github.com/IgniteUI/igniteui-angular/issues/5674#issuecomment-525621994) we resolved with setting the grid's z-index to 1 I think we should retain this value.
@Timmeeeey
To solve your issue you can set `z-index` of the first `app-grid-sample` component to at least 2. Note, to create stacking context you should also set `position` to anything different than `static` - I would go with `relative`. Also set the `display` to `block`.
[Here](https://stackblitz.com/edit/github-7hixdh-babkwj?file=src%2Fapp%2Fapp.component.html) is updated sample showing how to solve this.

**Comment by simeonoff** [comment]
To add to what @wnvko posted, I will reference [this issue](https://github.com/IgniteUI/igniteui-angular/issues/7379) regarding the same question. There's a post in there by me explaining why we need the z-index.

**Comment by Timmeeeey** [comment]
I simplified the example. In my project the two grids are in different panes of a Dock Manager so it could happen that the 2nd grid is above the 1st grid.
Could you give me an example how to solve this using the grid's outlet property?

**Comment by zdrawku** [comment]
Hey @Timmeeeey, yes there is a [very good example part of our official documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#external-outlet), that will walk you through the steps of adding a different grid outlet. This will help you to manage the stacking context for each grid in the DOM.

[Full screen Demo](https://www.infragistics.com/angular-demos/grid/grid-external-outlet)
[Live-editing StackBlitz Demo](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-external-outlet)
