### ISSUE TITLE
IgxCombo: configure width of overlay

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#9885]
## Question  
I have a small IgxCombo and not all content is visible in the dropdown overlay.
Is it possible to configure that the overlay width fits the content instead the width of the IgxCombo?

https://stackblitz.com/edit/github-a9cb2t

Current:
![image](https://user-images.githubusercontent.com/46870283/126284966-e45d0a52-cdd3-460d-9328-e493707bedd0.png)

Better:
![image](https://user-images.githubusercontent.com/46870283/126285758-b53c54f9-8dab-4cac-a9a6-76836aff8981.png)

 * igniteui-angular version: 12.0.9
 * browser: Chrome

**Comment by zdrawku** [comment]
You can use [itemsWidth ](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcombocomponent.html#itemswidth)input to manually set the dropDown width.

Updated example:
https://stackblitz.com/edit/github-a9cb2t-zetm6z?file=src/app/combo-template/combo-template.component.html

**Comment by Timmeeeey** [comment]
Ok, but you can only set it to a fixed width (like 300px) and not that it fits the widest item?

**Comment by kdinev** [comment]
@Timmeeeey We don't allow for `auto` or `100%` to be set as `itemsWidth` because of the virtualized items container. The result of `auto` and `100%` would look like this:

![Animation](https://user-images.githubusercontent.com/1472513/126317552-9cc4c3cf-b9a2-4747-ba92-a5003e8a4025.gif)

**Comment by Timmeeeey** [comment]
OK I see. That answered my question.

**Comment by Timmeeeey** [comment]
I'm sorry to reopen this but I have another question related to the width.
Would it be possible to at least set a min-width for the overlay?
I think that would be very convenient because I want the overlay to be wide enough to display the items but not smaller than the Combo component.

**Comment by zdrawku** [comment]
@Timmeeeey, we do not expose a way to set min-with of the overlay, using of `itemsWidth` is the preferable way to manage the dropdown width without affecting the scrolling user experience and the items selection flow of the combo.

**Comment by Timmeeeey** [comment]
ok.
