### ISSUE TITLE
IgxDateRangePickerComponent API change not reflected on the documentation.

### ISSUE THREAD

**Issue by yuhongcheng2003** [IgniteUI/igniteui-angular#9904]
## Description  
There is an API change in 12.x in IgxDateRangePickerComponent not reflected on the documentation. Method selectRange no lnoger exist and is renamed to select.

 * igniteui-angular version: 11.x => 12.x
 * browser: all

## Steps to reproduce  

Compare version 11.x to 12.x 

## Result  
Documentation discrepancy on 
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdaterangepickercomponent.html 

## Expected result  
Documentation should always reflect the actual API,
Integrate this change to NG UPDATE for auto migration.

## Attachments  
Doc:
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxdaterangepickercomponent.html
Repo
https://github.com/IgniteUI/igniteui-angular/blob/12.0.x/projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts

**Comment by zdrawku** [comment]
Hey @yuhongcheng2003, thank you for the notice! There is actualy a problem with the content generation that is more relevant to the deploying of the content rather to the library configuration itself.

For the time being my suggestion is to _specify_ the _exact_ latest version through the API version dropdown, for example:
https://www.infragistics.com/products/ignite-ui-angular/docs/12.0.9/typescript/

When the docs are not refering to the latest site content everything should be fine.

**Comment by yuhongcheng2003** [comment]
Thanks @zdrawku. The specific version seems fixed this issue. May I suggest to add an auto redirect on the latest to a specific version if this is not going to be fixed in a short term. The reason being that, all of the links from your demos/tutorial is pointing the latest and it could be confusing for anyone that is not aware of this issue. 

Also, it would be nice to automatically migrate this change for me when I'm doing ng update to avoid the manual work.

**Comment by Lipata** [comment]
Hi, @yuhongcheng2003. Thank you for catching that igxDateRangePicker migrations are having a problem. [Here](https://github.com/IgniteUI/igniteui-angular/pull/9910) is the fix and it will be available on Monday with [12.0.10](https://github.com/IgniteUI/igniteui-angular/releases) patch.

**Comment by zdrawku** [comment]
Both ng update migration and API docs should be available now on the [API docs site](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/) and with [12.0.10](https://github.com/IgniteUI/igniteui-angular/releases/tag/12.0.10) version of the product.
