### ISSUE TITLE
IgxGrid: row selection behaviour via shift + click

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#9926]
## Question  
If you use `rowSelection="multiple"` and you select rows via `shift + click` then the browser selects everything between these rows (see screenshot). For me this happens most of the time but sometimes this doesn't happen.

This doesn't happen with `cellSelection="multiple"` at all. So is there a way to prevent this behaviour for `rowSelection="multiple"`?

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-selection#angular-row-selection-example

![image](https://user-images.githubusercontent.com/46870283/127175558-f3ed09a7-bb5f-48fc-801f-6d5d7de42695.png)

 * igniteui-angular version: 12.0.9
 * browser: Chrome

**Comment by ddincheva** [comment]
Hello @Timmeeeey,
This is default browser behavior and we try to prevent at least as possible this type of events, but if this causes any issues in your app you can use  from the grid's  selectionService clearTextSelection() method. See the [updated sample](https://stackblitz.com/edit/github-uubzus?file=src/app/grid/grid-sample-selection/grid-selection.component.ts).
If you have additional questions or need any further assistance regarding this topic just let us know.

**Comment by Timmeeeey** [comment]
Hi @ddincheva,
thank you for the updated sample. This is definitively better.
