### ISSUE TITLE
Migrations won't run in projects where tsconfig is not located in the root folder

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#9927]
## Description  
Migrations won't run in projects where tsconfig is not located in the root folder, see https://github.com/IgniteUI/igniteui-angular/issues/9922#issuecomment-887346409

If the tsconfig 

 * igniteui-angular version: 12.0.x
 * browser: N/A

## Steps to reproduce  

1. TBD

## Result  
ng update doesn't work going from v11 to 12 when tsconfig is not located in the root of the project

## Expected result  
Migrations should properly find the tsconfig (through angular.json) or fail gracefully just the parts concerned with the config

## Attachments  
TBD

**Comment by damyanpetev** [comment]
@Eralmidia Since this originated from a conversation in a previous issue, I'll tag you here.
Tried to reproduce the migrations failing behavior and made a repo to test this out with moved tsconfigs under the `src` folder as an example here: https://github.com/damyanpetev/update11Test

I thought the moved tsconfigs would totally confuse the TypeScript and Angular Language services, but they seems to handle things just fine and migrations managed to run alright:
![image](https://user-images.githubusercontent.com/3198469/128503824-236f5bee-2ab3-47f0-90e4-e153248ff34a.png)

Then only thing that was missed was one grid property in markup used through a template variable reference, which relies on the ng language service functionality. That's likely because we didn't manage to find the tsconfig and force `strictTemplates` which is needed for the ng LS to resolve definitions correctly and that's something that we can fix. 

Other than that, the migrations seemed to do their job (as you can see from the test repo history) so there must be something else causing them to fail in your project. This is where we'll need your help - are they still failing to run in your project? If so, maybe there's something else causing it besides the tsconfig location and if you can provide any more detail it'll be greatly appreciated. We put some effort into those migrations you wouldn't have to apply everything manually and would really like to make sure they run in project setups like yours :)

**Comment by Eralmidia** [comment]
@damyanpetev You were indeed right that there was a typeRoot present. (ref the other thread). Removing this, and trying to run update, I now get the following error instead (updating from 10.2 to latests:

[error] TypeError: Cannot read property 'fileName' of undefined
    at UpdateChanges.getDefaultProjectForFile (C:\Users\andreas.kristensen\source\repos\WATS Portal\Portal\node_modules\@infragistics\igniteui-angular\migrations\common\UpdateChanges.js:558:55)
    at UpdateChanges.getDefaultLanguageService (C:\Users\andreas.kristensen\source\repos\WATS Portal\Portal\node_modules\@infragistics\igniteui-angular\migrations\common\UpdateChanges.js:154:30)
    at C:\Users\andreas.kristensen\source\repos\WATS Portal\Portal\node_modules\@infragistics\igniteui-angular\migrations\update-11_1_0\index.js:18:27
    at MergeMapSubscriber.project (C:\Users\ANDREA~1.KRI\AppData\Local\Temp\angular-cli-packages-3IVmq9\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (C:\Users\ANDREA~1.KRI\AppData\Local\Temp\angular-cli-packages-3IVmq9\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (C:\Users\ANDREA~1.KRI\AppData\Local\Temp\angular-cli-packages-3IVmq9\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\ANDREA~1.KRI\AppData\Local\Temp\angular-cli-packages-3IVmq9\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (C:\Users\ANDREA~1.KRI\AppData\Local\Temp\angular-cli-packages-3IVmq9\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (C:\Users\ANDREA~1.KRI\AppData\Local\Temp\angular-cli-packages-3IVmq9\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\ANDREA~1.KRI\AppData\Local\Temp\angular-cli-packages-3IVmq9\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:30:22)

**Comment by damyanpetev** [comment]
@Eralmidia Thanks for the additional info, we'll look into it and get back to you. It seems it might be something to do with a custom migration code for 11.1 and if so we can probably remedy that.

**Comment by Eralmidia** [comment]
@damyanpetev Excellent, hope you have time to look at this soon as we are keen to transition to the latest igx to get the new shiny features 😄 

Also, regarding the original errors in the first post in #9922, will the migrations handle any of these, or should I just go ahead and manually handle these?

**Comment by damyanpetev** [comment]
@Eralmidia PR for the problematic 11.1 migration is up and it should be available soon, likely with the Monday patches.

As for the previous post and what the migrations will handle - there were quire a few discussed, but for the ones I can see for sure:
- as discussed new `RowType` now has the `cells` collection in 12.1 (using the new `CellType`) so that shouldn't error out anymore
- There are migrations that will update the cell class references and handle the grid paginator as much as possible (can be seen in the [my test project commit](https://github.com/damyanpetev/update11Test/commit/368d8a1a068d63f8bd617bd83ba4d4c38d9648e6#diff-3b38a2ad661e1a5631d917c960f50f029409aaf47a388f3766d22d7d665124e7))
- for the others like crud service changes, as not considered public API those usually don't end up in migrations

We keep an [Update Guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide) which lists explains additional manual changes that may be needed between versions. That's still after running the migrations though, usually for things we can't feasibly or reliably automate. So if you can, I'd still wait for the migrations fix so you can run them to hopefully take the bulk of renames and such and after that look at remaining things for manual changes :)

**Comment by Eralmidia** [comment]
@damyanpetev Thanks, I'll hold of until Monday then 🙂

**Comment by Lipata** [comment]
@Eralmidia you can use [12.1.2](https://github.com/IgniteUI/igniteui-angular/releases/tag/12.1.2)

**Comment by Eralmidia** [comment]
@Lipata @damyanpetev 

So, I ran the migrations again, and going from 11.1.0 to 12.1.2 I now get this error:
![image](https://user-images.githubusercontent.com/12936286/130010948-169c11a9-2332-4e5b-9e2e-50468473d427.png)

![image](https://user-images.githubusercontent.com/12936286/130011150-9866a4f7-a12a-4fb5-bc3a-68887da4ae30.png)


Is it a viable option to do the migrations manually? At this point the igx package is the only thing holding us back from upgrading, and I need a solution to this sooner rather than later.

**Comment by damyanpetev** [comment]
Well that's not good😞
I can tell where this is going wrong, though not exactly why - there's a class/interface member marked for migration that's accessed from the return of a method (think `this.getGrid(args).changedProp`). So we look at the method signature of `getGrid()` and use the TypeScript API TypeChecker to inquire about its return type so we can figure out if we should change the prop. The signature was obviously resolved, since the error is after that. The return type of that produces a symbol for the return (for example `IgxGridComponent`) and we have to check its name. That's the part that fails, but it's supper odd - the returned type doesn't specify the symbol as being optional and it never was when we tested, yet it's clearly `undefined` in your case...

Maybe an older version of typescript, though not likely if you're running updates for angular which bump it. I'd really love to get to version of your project so we can get to the bottom of this. Do let me know if that's a possibility.

As for running the migrations manually, unfortunately there's not way to run only parts of the migration without tinkering inside the package source. You could run specific versions though, IIRC there's are from/to and migrate-only flags for `ng update` that could do the versions in steps. Also since migrations are still schematics you can call them explicitly with `ng g`, though they are in a separate collection so something like:
```
ng g @infragistics/igniteui-angular/migrations/migration-collection.json:migration-XX
```
In your case the 12.0 and 12.1 migrations are numbers 20 and 21. My only gripe is there are a lot of renames in those versions and the ideal case would be to try and isolate the thing that blocks the migration (somewhere in ts code) and update that manually and still call the migration to try and update the rest.

**Comment by damyanpetev** [comment]
@Lipata Actually this is likely unrelated to the original title, so might warrant a separate issue.

**Comment by Eralmidia** [comment]
@damyanpetev Unfortunately I'm not able to send the project, as its a large enterprise application.

No, the typescript version is 4.3.5, so that should be fairly recent.

By manually, I actually meant skipping the migration altogether, and just update everything manually in our code. Doesn't sound like a very pleasant task, but I kinda have to get this running soon.

**Comment by radomirchev** [comment]
@Eralmidia did you receive the mail by NAlipiev@infragistics.com?

**Comment by Eralmidia** [comment]
@radomirchev 

Seems like I manged to solve this after all. By using @damyanpetev's tip of running migrations step by step with 

`ng g @infragistics/igniteui-angular/migrations/migration-collection.json:migration-XX`

the migrations did run, and things seems to be more or less working now. I'll run through the manual checklist for the upgrade as well. but most things seems to be OK so far.
