### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError is thrown in Search example

### ISSUE THREAD

**Issue by zhosti** [IgniteUI/igniteui-angular#9934]
## Description  
When enter text in the search bar and then open a filter the error is thrown in the console.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Navigate to [Search Example](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/search#angular-search-example)
2. Open the StackBlitz
3. Enter text in the search bar
4. Click on the first column filter

## Result  
An ExpressionChangedAfterItHasBeenCheckedError  error is thrown in the browser console.

## Expected result  
Should not throw an error.

## Attachments  
![Screenshot 2021-07-28 190058](https://user-images.githubusercontent.com/7760119/127356520-88c7c491-f49b-4e84-9f07-c548446079b9.png)

**Comment by zhosti** [comment]
In `grid-filtering-row.component.ts`, in the `ngAfterViewInit` there is call of  `focusEditElement` method which cause the error message.

**Comment by mtsvyatkova** [comment]
It seems this is no longer reproducible on staging or on production.
