### ISSUE TITLE
Will Group By feature work on Export to Excel service on version 9

### ISSUE THREAD

**Issue by Raju-N** [IgniteUI/igniteui-angular#9962]
## Question  
I am trying to have 'Group By' feature on my Data Grid, and trying to use 'excelExportService'  to export the grid.
But the data is not coming with grouping and collapse feature on the excel. Can you please help on this?  

 * igniteui-angular version: 9.1
 * browser: Chrome

**Comment by onlyexeption** [comment]
Hello, we've implemented this feature and it's available from version 11 оnwards. You'd need to update your igniteui version in order to use it.

**Comment by Raju-N** [comment]
Thanks for your response !
