### ISSUE TITLE
Grid "active" state, separate from "selected"

### ISSUE THREAD

**Issue by baleeds** [IgniteUI/igniteui-angular#9969]
## Is your feature request related to a problem? Please describe.
Our UX requires checkbox multi-select for performing bulk actions but also has the ability to click a single row and open a details panel.  The row that is being viewed in the details panel is then "active" and should have a blue background.  The selection state is decoupled from the active state.

## Describe the solution you'd like
I would like the ability to specify whether a row is "active" or the ability to specify custom classes based on the data in a row.  Another option would be to have the row ID as a data attribute on the row DOM element.

I'm sure your team has seen ag-grid.  Not saying you should be more like ag-grid, but they do have a feature where the grid options can specify a "getRowClass" callback which provides the row data and returns class names for a row.  This feature would work to solve our problem, since we track the "active" state independently from the grid.  One common way to track the active state would be the ID of an item in the current route.
https://www.ag-grid.com/javascript-grid/grid-callbacks/#reference-callbacks

## Describe alternatives you've considered
The only way I can think to do this with my current understanding is to keep track of the active row primary key, and use the template context on each column template to determine if this column's row's data is active.

**Comment by ddincheva** [comment]
Hello @baleeds, 
We take a look at your request and currently we have two grid input properties evenRowCSS and oddRowCSS, which allow you to set custom classes on rows but we can see why this is not enough to address your request. 
So about your suggestion, we have already implemented such behavior but it is only on cell level: we have introduced cellClasses and cellStyles input properties which can be set on column level. Here you can see more detailed [description](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/conditional-cell-styling#overview).
So currently we are planning to introduce similar properties on grid level - probably rowClasses and rowStyles which will accept an object containing key-value pairs. /key is the name of the CSS class/property, the value is either a callback function that returns a boolean or boolean value/. The callback signature for both rowClasses and rowStyles will be:
(row: [RowType](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/RowType.html)) => boolean
Please let us if this going to fulfill your us case.

**Comment by baleeds** [comment]
@ddincheva Yes, the rowClasses and rowStyles callbacks would be immensely helpful!  Is there a timeline on when we might see that feature?

**Comment by radomirchev** [comment]
Hi @baleeds , I am the Product Owner of Ignite UI for Angular. I would like to inform you that the feature has been included in milestone 18 in our [roadmap](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md). When we have draft specification for the feature, you would be updated and you can provide feedback on it. The feature would be released with our next major release. P.S> The [ROADMAP](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md) is to be updated till end of the week

**Comment by baleeds** [comment]
Thanks @radomirchev! I greatly appreciate the details 👏 

Is there a projected timeframe for when the major release might occur?  We are deciding how to proceed in the meantime.

**Comment by radomirchev** [comment]
@baleeds we are targeting end of Sept for the feature release. Which version of Ignite UI you're using?

**Comment by baleeds** [comment]
We are currently on 11.1.2, but we will do major updates for this feature.

**Comment by hanastasov** [comment]
@baleeds, we exposed this feature in an alpha version if you want to test it in advance. The version is `12.2.0-alpha.2` available on and is available on npm already.

**Comment by baleeds** [comment]
Just wanted to thank you all for your attention to this.  The row classes (and styles) feature is working great for our use cases.  🎉

**Comment by zdrawku** [comment]
Thank you, @baleeds! We strive to listen whenever our customers have anything to share. Any type of feedback is highly appreciated as it validates our product direction, with that said, please feel free to share your [feedback/review here](https://www.trustradius.com/products/infragistics-ignite-ui/reviews).

Thank you 🙏
