### ISSUE TITLE
Add `rowAdding` event to match editing event sequence for adding

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#9993]

**Comment by mddragnev** [comment]
@ChronosSF Do we want to match the exact sequence of the editing events? If so, we should also add addRowEnter, addRow, addRowDone and addRowExit

**Comment by ChronosSF** [comment]
I don't think so tbh, because we already fire editing events for it, as adding is actually *editing* an added dummy row. Their arguments indicate that they are fired for such a row as well.

But this was brought up by @hanastasov so maybe he has arguments for adding the other events as well.

**Comment by hanastasov** [comment]
My use case was standard and a pair of "-ing" and "-ed" event is just enough.
